#!/usr/bin/env python3
"""Grade 11 — days 1-15. Subjects: English, Functions, Biology, Chemistry."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,write_new

U='https://tvolearn.com/pages/grade-11'
R='TVO Learn: Grade 11'

def E(t,s,q): return sub('English',t,s,R,U,q)
def F(t,s,q): return sub('Functions',t,s,R,U,q)
def B(t,s,q): return sub('Biology',t,s,R,U,q)
def C(t,s,q): return sub('Chemistry',t,s,R,U,q)

g11=[
day(1,[
E('Literary Analysis: Developing Advanced Thesis Statements','Students develop arguable, specific, sophisticated thesis statements that go beyond observation to make an interpretive claim about a text.',[
  ('An advanced thesis statement in Grade 11 must be ___.',['a fact about the text','a summary of the plot','a question you will answer in the essay','an arguable interpretive claim — a position that a reasonable person could disagree with, which you will support with evidence and analysis'],3),
  ('The difference between a Grade 9 thesis ("The theme of friendship is shown in the novel") and a Grade 11 thesis is ___.',['only length','Grade 11 avoids thesis statements','they are equivalent','a Grade 11 thesis must specify HOW and WHY: "By portraying friendship as simultaneously sustaining and suffocating, the novel critiques the social pressure to prioritise relationships over individual identity"'],3),
  ('A "so what" moment in a thesis ___.',['adds a disclaimer','restates the obvious','lists more evidence','signals the larger significance of the claim — why it matters beyond the text, what it reveals about human experience or the world'],3),
  ('Complex sentence structures in thesis statements help by ___.',['making the statement harder to understand','adding unnecessary length','impressing the teacher with vocabulary','allowing you to embed complexity — acknowledging nuance, qualifications, or competing interpretations within a single, controlled claim'],3),
  ('When a peer reviewer says "I don\'t see what you\'re arguing," the thesis likely ___.',['needs more quotations','is too specific','is too long','is still too vague or descriptive — it states a topic rather than making a specific, contestable claim about it'],3)]),
F('Introduction to Functions: Review and Deepening','Students consolidate Grade 10 function concepts and deepen their understanding of function notation, compositions, inverses, and transformations.',[
  ('The composition f(g(x)) means ___.',['f(x) × g(x)','f(x) + g(x)','(f + g)(x)','apply g first, then apply f to the result — the output of g becomes the input of f'],3),
  ('If f(x) = 2x + 1, find f(g(x)) where g(x) = x².',['2x² + 1','2x + x²','4x + 1','(2x+1)²'],0),
  ('The inverse of a function f(x) is ___.',['1/f(x)','−f(x)','f(−x)','the function that reverses the operation of f — if f maps x to y, f⁻¹ maps y back to x'],3),
  ('To find the inverse of f(x) = 3x − 2, you ___.',['negate f(x)','divide f(x) by 3','reflect across the x-axis','swap x and y (write x = 3y − 2), then solve for y: y = (x+2)/3, so f⁻¹(x) = (x+2)/3'],3),
  ('The graph of f⁻¹(x) is ___.',['f(x) flipped vertically','f(x) shifted right','f(x) compressed horizontally','the reflection of f(x) across the line y = x'],3)]),
B('Cell Biology: Cell Structure and Organelle Functions','Students review and deepen their understanding of cell organelles, distinguishing eukaryotic from prokaryotic cells and plant from animal cells.',[
  ('The key distinction between prokaryotic and eukaryotic cells is ___.',['size only','presence of a cell wall','absence vs. presence of a nucleus: prokaryotes (bacteria) have no membrane-bound nucleus; eukaryotes (animals, plants, fungi) have a defined nucleus enclosed by a membrane','number of chromosomes'],2),
  ('The mitochondrion\'s primary function is ___.',['protein synthesis','lipid storage','DNA replication','ATP (energy) production through cellular respiration — converting glucose and oxygen to ATP, CO₂, and water'],3),
  ('Ribosomes are found ___.',['only in the nucleus','only in plant cells','only in mitochondria','in all living cells — both prokaryotic and eukaryotic — as they are the sites of protein synthesis (translation)'],3),
  ('A plant cell has these structures absent from animal cells: ___.',['mitochondria and ribosomes','a nucleus and cell membrane','cell wall, large central vacuole, and chloroplasts','lysosomes and centrioles'],2),
  ('The endoplasmic reticulum (ER) has two forms: rough ER ___.',['contains ribosomes and is involved in protein synthesis and transport; smooth ER is involved in lipid synthesis and detoxification','is smooth and makes lipids; smooth ER makes proteins','both are identical','produces energy; smooth ER stores calcium only'],0)]),
C('Matter and Chemical Bonding: Review and Extension','Students review atomic theory, the periodic table, and chemical bonding, and extend to molecular geometry and polarity.',[
  ('Electronegativity is ___.',['the charge of an ion','the number of electrons in an atom','an atom\'s ability to attract electrons toward itself in a chemical bond — increases across a period (left to right) and decreases down a group','the energy released in bonding'],2),
  ('A polar covalent bond forms when ___.',['electrons are transferred between atoms','electrons are shared equally','atoms share electrons unequally (due to electronegativity differences), creating partial positive and negative charges (δ+ and δ−) on the bonded atoms','atoms have identical electronegativities'],2),
  ('Water (H₂O) is a polar molecule because ___.',['hydrogen is very electronegative','oxygen has 8 electrons','both O-H bonds are polar AND the bent geometry means the dipoles don\'t cancel — producing a net molecular dipole','it has two hydrogen atoms'],2),
  ('Carbon dioxide (CO₂) is non-polar despite having polar C=O bonds because ___.',['carbon has no electronegativity','the bonds are ionic','it has only two bonds','the linear geometry means the two bond dipoles point in opposite directions and exactly cancel, giving CO₂ a net dipole of zero'],3),
  ('VSEPR theory predicts ___.',['the colour of a compound','the reactivity of a molecule','the mass of a molecule','the three-dimensional shape of a molecule based on electron pair repulsion — lone pairs and bonding pairs arrange themselves to minimise repulsion'],3)]),
]),
day(2,[
E('Independent Reading: Canadian Literature','Students read and analyse a Canadian novel or short story collection, examining Canadian identity, landscape, and social themes.',[
  ('What makes a work "distinctly Canadian" in literature?',['Only being set in Canada','Only being written by a Canadian-born author','It cannot be defined','Often a combination of landscape and environment as significant forces, themes of identity in a vast, cold, multicultural nation, irony and understatement, and engagement with the colonial legacy'],3),
  ('Alice Munro\'s short stories are often described as having ___.',['simple linear plots','no female characters','happy endings always','extraordinary compression and depth — exploring entire lives and deep psychological truths within a few pages through non-linear structure and precise observation'],3),
  ('Reconciliation as a theme in contemporary Indigenous Canadian literature ___.',['is entirely separate from aesthetic literary concerns','is always the same story','is a new development with no prior literary history','intersects with questions of land, language, spiritual connection, family trauma from residential schools, and the recovery of Indigenous identity — often in formally innovative ways'],3),
  ('Canadian literature\'s sense of "garrison mentality" (Northrop Frye\'s concept) refers to ___.',['an obsession with military history','only Quebec literature','only Indigenous literature','a recurring theme of small communities — physical and psychological — fighting to maintain identity and safety against a threatening, overwhelming landscape or outside force'],3),
  ('A close reading of setting in a Canadian novel should examine ___.',['only weather descriptions','only urban or rural designation','landscape as only backdrop','how the Canadian environment — the Shield, the prairies, the North, the multicultural city — functions symbolically and psychologically, not just as background'],3)]),
F('Polynomial Functions: Characteristics and Graphs','Students investigate polynomial functions of degree 3 and higher — end behaviour, zeros (with multiplicity), local extrema, and connecting equations to graphs.',[
  ('A polynomial of odd degree with a positive leading coefficient has end behaviour: ___.',['rises right, rises left','falls right, falls left','rises left, falls right','falls left, rises right — as x → −∞, y → −∞; as x → +∞, y → +∞'],3),
  ('A zero with multiplicity 2 means ___.',['the zero appears twice in different equations','there are two separate zeros','the function has two y-intercepts','the factor (x − r)² appears — the graph touches but does not cross the x-axis at that zero'],3),
  ('A zero with multiplicity 3 means ___.',['the graph doesn\'t cross the x-axis','the function has 3 zeros total','there are three separate zeros','the factor (x − r)³ appears — the graph crosses the x-axis but flattens ("inflects") as it does so'],3),
  ('A cubic function y = −2(x − 1)(x + 3)² has ___.',['three crossing zeros','only one zero','two zeros, x = 1 (crosses, odd multiplicity) and x = −3 (touches, even multiplicity), with negative leading coefficient','three touching zeros'],2),
  ('Finding local maxima and minima of a polynomial (without calculus) requires ___.',['only looking at the leading coefficient','only the x-intercepts','the y-intercept only','technology (graphing calculator) or calculus — beyond Grade 11, but you can identify their approximate location from a careful graph'],3)]),
B('Cell Division: Mitosis and Meiosis Compared','Students compare mitosis (somatic cell division) and meiosis (gamete formation), explaining their roles in growth, repair, and sexual reproduction.',[
  ('Mitosis produces ___.',['4 haploid daughter cells','2 haploid daughter cells','2 diploid daughter cells genetically identical to the parent — used for growth, repair, and asexual reproduction','2 cells with half the chromosomes'],2),
  ('Meiosis produces ___.',['4 genetically identical diploid cells','2 diploid cells','2 cells with double chromosomes','4 haploid daughter cells that are genetically diverse — used in sexual reproduction to produce eggs and sperm'],3),
  ('Crossing over (recombination) occurs during ___.',['anaphase I of meiosis','mitosis only','meiosis II','prophase I of meiosis, when homologous chromosomes pair up and exchange segments — generating new combinations of alleles that increase genetic diversity'],3),
  ('The significance of independent assortment (Mendel\'s second law) at the cellular level is ___.',['chromosomes are always identical','all gametes are genetically identical','genes on the same chromosome always stay together','during meiosis I, homologous pairs align independently, so the maternal or paternal chromosome of each pair ends up in a gamete independently — generating enormous variation'],3),
  ('Cancer is related to cell division because ___.',['cancer only affects the nucleus','cancer is caused by mitosis itself','only meiosis causes cancer','uncontrolled cell division (caused by mutations in proto-oncogenes or tumour suppressor genes that normally regulate the cell cycle) is the defining feature of cancer'],3)]),
C('Chemical Reactions: Types and Balancing','Students classify chemical reactions (synthesis, decomposition, single/double displacement, combustion) and practise balancing equations with increasing complexity.',[
  ('A synthesis reaction has the general form ___.',['AB → A + B','AB + CD → AD + CB','A + B → AB — two or more reactants combine to form a single product','AB → A + B + C'],2),
  ('A double displacement (metathesis) reaction involves ___.',['one element replacing another in a compound','one reactant forming two products','combining two elements','two compounds exchanging their ionic partners: AB + CD → AD + CB'],3),
  ('To balance H₂ + O₂ → H₂O, the balanced equation is ___.',['H₂ + O₂ → H₂O (unbalanced)','2H + O₂ → H₂O','H₂ + O → H₂O','2H₂ + O₂ → 2H₂O — four hydrogen atoms and two oxygen atoms on each side'],3),
  ('Combustion reactions always involve ___.',['only carbon and hydrogen','releasing nitrogen gas','absorbing energy','reacting with oxygen (O₂), producing carbon dioxide and water (for complete combustion of hydrocarbons) and releasing energy'],3),
  ('The law of conservation of mass states ___.',['mass is destroyed in exothermic reactions','mass increases in chemical reactions','products always have less mass than reactants','the total mass of reactants equals the total mass of products in a chemical reaction — no atoms are created or destroyed'],3)]),
]),
day(3,[
E('Media and Communication: Persuasive Speaking and Debate','Students develop formal oral skills through structured debate, applying logical reasoning, evidence use, and rebuttal techniques.',[
  ('The three classical appeals in persuasion are ___.',['fact, opinion, evidence','introduction, body, conclusion','topic, argument, conclusion','ethos (credibility/character), logos (logic/evidence), and pathos (emotion) — effective persuasion typically uses all three'],3),
  ('In formal debate, a rebuttal is ___.',['introducing your main argument','a type of opening statement','summarising your position','directly responding to and countering your opponent\'s specific arguments — not just repeating your own points'],3),
  ('Using logical fallacies (e.g., ad hominem, straw man) in debate ___.',['strengthens your argument','is acceptable in informal debate','is required by debate rules','weakens your credibility — opponents can call them out, and trained audiences recognise them as substitutes for genuine argument'],3),
  ('The difference between persuasion and manipulation is ___.',['there is no difference','manipulation is always acceptable','persuasion is always wrong','persuasion relies on accurate evidence, valid logic, and genuine appeals to shared values; manipulation distorts facts, exploits emotional vulnerabilities, or deceives'],3),
  ('Effective rebuttal requires ___.',['only repeating your original points','ignoring the opponent\'s arguments','changing the subject','listening carefully to identify the weakest or most contestable point in the opponent\'s argument and targeting it specifically'],3)]),
F('Polynomial Functions: Factoring and Solving','Students factor higher-degree polynomials using the factor theorem, synthetic division, and sum/difference of cubes, and solve polynomial equations.',[
  ('The factor theorem states ___.',['x − r is never a factor of a polynomial','a polynomial has at most 3 factors','a polynomial is always divisible by x','if P(r) = 0, then (x − r) is a factor of P(x) — substituting a root into the polynomial gives zero'],3),
  ('To find a factor of P(x) = x³ − 6x² + 11x − 6, you test integer factors of −6.',['P(2) = 8 − 24 + 22 − 6 = 0, so (x − 2) is a factor','P(1) = −2, so (x − 1) is not a factor','P(3) = 27 − 54 + 33 − 6 = 0, so (x − 3) is a factor','Only P(0) = 0 works'],2),
  ('After finding one factor using the factor theorem, you find remaining factors by ___.',['guessing the other factors','using only the quadratic formula','trial and error only','polynomial long division or synthetic division to reduce the degree, then factoring or using the quadratic formula on the quotient'],3),
  ('The sum of cubes factors as ___.',['a³ + b³ = (a + b)(a² − ab + b²)','a³ + b³ = (a + b)³','a³ + b³ = (a + b)(a + b)²','a³ + b³ = (a − b)(a² + ab + b²)'],0),
  ('The roots of P(x) = x³ − 6x² + 11x − 6 = (x−1)(x−2)(x−3) are ___.',['x = −1, −2, −3','x = 1, 2, 3','x = 6, 11, −6','x = 0, 1, 2'],1)]),
B('Genetics: Mendelian Genetics and Extensions','Students apply Mendelian genetics to monohybrid and dihybrid crosses and extensions: codominance, incomplete dominance, sex-linked traits.',[
  ('In codominance, two alleles ___.',['blend to produce an intermediate phenotype','only one is expressed','are both recessive','are both expressed simultaneously in the heterozygote — e.g., AB blood type shows both A and B antigens'],3),
  ('Incomplete dominance produces ___.',['only homozygous phenotypes','a phenotype matching one parent completely','an intermediate phenotype in the heterozygote — e.g., red × white → pink flowers in snapdragons','a new, third phenotype unrelated to either parent'],2),
  ('A sex-linked trait is carried on ___.',['only the Y chromosome','an autosome','the mitochondria','the X chromosome — males (XY) are hemizygous and express X-linked traits with only one allele, while females (XX) need two copies for expression of recessives'],3),
  ('A dihybrid cross between two AaBb parents produces offspring in a ___ ratio.',['3:1','9:3:3:1 (using a 4×4 Punnett square) — for phenotype ratios when two genes assort independently','1:1:1:1','1:2:1'],1),
  ('The Hardy-Weinberg principle states ___.',['evolution always occurs','small populations always evolve','allele frequencies always change each generation','allele and genotype frequencies in a large, randomly mating population remain constant from generation to generation in the absence of evolutionary forces'],3)]),
C('Stoichiometry: Mole Concept and Calculations','Students learn the mole concept, molar mass, Avogadro\'s number, and perform stoichiometric calculations (mass-to-mole, mole-to-mole, mass-to-mass).',[
  ('One mole of any substance contains ___.',['10²³ particles','exactly 1000 g','6.02 × 10²³ particles (Avogadro\'s number) — whether atoms, molecules, or ions'],2),
  ('The molar mass of water (H₂O) is ___.',['18 g/mol (H: 1×2=2, O: 16, total = 18)','16 g/mol','2 g/mol','20 g/mol'],0),
  ('In the equation 2H₂ + O₂ → 2H₂O, the mole ratio of H₂ to H₂O is ___.',['1:2','2:1','1:1 (2 mol H₂ produces 2 mol H₂O)','2:3'],2),
  ('A mass-to-mass stoichiometry calculation requires ___.',['only the molar mass of reactants','only knowing the balanced equation','only the volume of gases','converting grams to moles (using molar mass), applying the mole ratio from the balanced equation, then converting moles back to grams'],3),
  ('If 4 g of H₂ reacts completely with excess O₂ (molar mass H₂ = 2), how many moles of H₂O form?',['1 mol','2 mol (4g ÷ 2 g/mol = 2 mol H₂; mole ratio H₂:H₂O = 1:1, so 2 mol H₂O)','4 mol','0.5 mol'],1)]),
]),
day(4,[
E('Writing: The Analytical Essay (Extended Form)','Students write a multi-paragraph analytical essay demonstrating thesis-driven argument, sophisticated evidence integration, and logical cohesion across 5-7 paragraphs.',[
  ('Coherence in a multi-paragraph essay is created by ___.',['having equal-length paragraphs','using the same quotations in each paragraph','starting each paragraph with "Firstly, Secondly, Thirdly"','logical sequencing of ideas, effective topic sentences that connect back to the thesis, and transitions that show the relationship between ideas'],3),
  ('A topic sentence functions as ___.',['a quotation from the text','a fact that needs no argument','a transition only','a mini-thesis for its paragraph — stating the paragraph\'s specific claim and connecting it to the essay\'s overall argument'],3),
  ('Embedding quotations effectively means ___.',['always introducing them with "Quote:"','dropping quotations without context','using only very long quotations','integrating them grammatically into your sentence, introducing them with context, and following them with analysis — never letting a quotation speak for itself'],3),
  ('Evaluating the strength of your own argument in revision means ___.',['only counting the number of paragraphs','checking word count','only proofreading for spelling','reading your essay as a skeptic: where are the claims unsupported? Where does the logic leap? Where does an opposing reader have an easy counterpoint?'],3),
  ('Using academic vocabulary does NOT mean ___.',['precision in word choice','clarity in argumentation','using subject-specific terminology accurately','inflating your language with longer words to sound sophisticated — clarity and precision are more valuable than complexity for its own sake'],3)]),
F('Rational Functions: Characteristics and Graphing','Students analyse rational functions — identifying vertical and horizontal asymptotes, holes, domain restrictions, and graphing behaviour.',[
  ('A rational function has the form ___.',['f(x) = ax + b','f(x) = axⁿ','f(x) = aˣ','f(x) = p(x)/q(x) where p and q are polynomials and q(x) ≠ 0'],3),
  ('Vertical asymptotes occur where ___.',['the numerator equals zero','the function reaches its maximum','the function crosses the x-axis','the denominator equals zero (and the numerator does not also equal zero there) — the function approaches ±∞'],3),
  ('A "hole" in a rational function occurs where ___.',['the denominator is very large','both numerator and denominator equal zero at the same x-value — a common factor cancels, leaving a hole (removable discontinuity) rather than a vertical asymptote','the numerator is larger than the denominator','the function is undefined at all points'],1),
  ('For f(x) = (x² − 4)/(x − 2), the simplified form is ___.',['x + 2 with a hole at x = 2 (since (x²−4) = (x−2)(x+2) and (x−2) cancels)','x − 2 with no hole','x² − 4 unchanged','x + 2 with no restrictions'],0),
  ('The horizontal asymptote of f(x) = (3x² + 1)/(x² − 2) as x → ±∞ is ___.',['y = 0','y = 3 (ratio of leading coefficients when degrees are equal)','y = 1','y = −2'],1)]),
B('Evolution: Natural Selection and Speciation','Students examine evidence for evolution, mechanisms of natural selection, and how new species arise through reproductive isolation.',[
  ('Darwin\'s natural selection requires four conditions: ___.',['random mutation, genetic drift, gene flow, and bottleneck','overproduction of offspring, heritable variation, differential survival and reproduction, and accumulation of favourable traits over many generations','only mutation and time','identical offspring, resource competition, environmental change, and migration'],1),
  ('A bottleneck effect occurs when ___.',['a large population grows rapidly','populations merge','gene flow increases significantly','a population is drastically reduced by a chance event, leaving a small surviving group that may not represent the original genetic diversity — reducing variation and potentially fixing harmful alleles'],3),
  ('Allopatric speciation occurs when ___.',['two populations mate more frequently','two populations develop new traits simultaneously','a species reproduces asexually','a geographic barrier separates a population into two groups that evolve independently until they become reproductively incompatible — unable to interbreed even if the barrier is removed'],3),
  ('Evidence for evolution includes ___.',['only the fossil record','only molecular biology','only comparative anatomy','convergent lines of evidence: fossil record, comparative anatomy (homologous structures), biogeography, molecular biology (DNA similarities), and direct observation of evolution in fast-reproducing organisms'],3),
  ('Antibiotic resistance in bacteria is ___.',['disproved by Darwinian theory','only caused by intentional mutation','created by the antibiotic itself','a direct, observed example of natural selection: bacteria with resistance alleles survive and reproduce when antibiotics are present, rapidly increasing resistance allele frequency'],3)]),
C('Stoichiometry: Limiting Reagents and Percent Yield','Students apply stoichiometry to limiting reagent problems and calculate theoretical, actual, and percent yield.',[
  ('The limiting reagent in a reaction is ___.',['the cheapest reactant','the reactant present in largest mass','the reactant in smallest mass','the reactant that is completely consumed first, determining the maximum amount of product that can form'],3),
  ('In 2H₂ + O₂ → 2H₂O, if you have 3 mol H₂ and 2 mol O₂, the limiting reagent is ___.',['H₂ (need 4 mol O₂ to use all H₂, but only 2 mol O₂ available... actually: 3 mol H₂ needs 1.5 mol O₂; 2 mol O₂ could use 4 mol H₂; so H₂ is limiting)','O₂','both are limiting','neither is limiting'],0),
  ('Theoretical yield is ___.',['the yield actually obtained in lab','always less than actual yield','the maximum amount of product that could form if the limiting reagent were completely converted to product, with no losses','the yield at 50% efficiency'],2),
  ('Percent yield = ___.',['(theoretical yield / actual yield) × 100','(actual yield / theoretical yield) × 100 — measures how efficiently a reaction was performed in practice','(molar mass / actual yield) × 100','(actual yield + theoretical yield) × 100'],1),
  ('A percent yield greater than 100% is ___.',['common in industrial chemistry','achievable with good technique','theoretically possible','impossible — it would mean producing more product than stoichiometry allows; usually indicates impurities in the collected product or a measurement error'],3)]),
]),
day(5,[
E('Close Reading: Poetry Analysis','Students apply close reading skills to analyse poetic form, imagery, diction, tone, and theme in Grade 11 poetry (Romantic, modern, and contemporary).',[
  ('The Romantic period in poetry (late 18th-early 19th century) is characterised by ___.',['industrial themes','cynicism and irony','classical structure only','celebration of nature, individual emotion and imagination, the sublime, and a reaction against rationalism and industrialisation'],3),
  ('Modernist poetry (early 20th century) broke from tradition through ___.',['strict adherence to rhyme and metre','complete avoidance of imagery','use of only classical allusions','fragmentation, free verse, stream of consciousness, irony, and the influence of psychoanalysis and the disillusionment of WWI'],3),
  ('Analyzing enjambment in a poem means examining ___.',['the poem\'s rhyme scheme','only the first and last lines','the poem\'s stanza breaks','how lines run on without pause — how the continuation of meaning across line breaks creates tension, speed, or ambiguity'],3),
  ('Diction analysis in poetry means ___.',['only counting syllables','only identifying adjectives','identifying rhymes','examining the poet\'s specific word choices — their connotations, register (formal/informal), sonic qualities, and the emotional/intellectual effects they create'],3),
  ('A poem\'s "speaker" is ___.',['always the poet','only fictional','never described by readers','the voice or persona narrating or addressing the poem — distinct from the poet, with its own perspective, tone, and relationship to the audience'],3)]),
F('Exponential Functions: Growth, Decay, and Graphing','Students investigate exponential functions, identifying key features of graphs, and modelling real-world growth and decay situations.',[
  ('An exponential function has the form ___.',['f(x) = x^n','f(x) = ax + b','f(x) = mx + b','f(x) = aˣ (or f(x) = abˣ) where the variable is in the exponent — growth if b > 1, decay if 0 < b < 1'],3),
  ('The graph of f(x) = 2ˣ has ___.',['a vertical asymptote at x = 0','a horizontal asymptote at x = 0','passes through (0, 0)','a horizontal asymptote at y = 0 (the x-axis), passes through (0, 1), and increases without bound as x increases'],3),
  ('Compound interest is modelled by ___.',['A = P + rt (linear)','A = P(1 + r/n)^(nt) — exponential growth where P is principal, r is annual rate, n is compounding frequency, and t is time in years','A = Prt only','A = P × r × t'],1),
  ('Half-life in exponential decay means ___.',['the time for a substance to reach zero','the time for an element to decay completely','the minimum amount remaining after any period','the time for a radioactive substance (or any exponentially decaying quantity) to reduce to exactly half its initial amount'],3),
  ('Doubling time and half-life are ___.',['the same concept','unrelated','only for population biology','analogous: doubling time applies to exponential growth, half-life to exponential decay — both describe the characteristic time scale of the process'],3)]),
B('Photosynthesis: Light-Dependent and Light-Independent Reactions','Students examine the two stages of photosynthesis — the light reactions in the thylakoid and the Calvin cycle in the stroma — in biochemical detail.',[
  ('The light-dependent reactions of photosynthesis occur in ___.',['the stroma of the chloroplast','the cytoplasm','the mitochondrial matrix','the thylakoid membranes of the chloroplast — chlorophyll absorbs light energy and uses it to produce ATP and NADPH, releasing oxygen from water splitting'],3),
  ('The products of the light-dependent reactions that feed into the Calvin cycle are ___.',['glucose and oxygen','CO₂ and water','only oxygen','ATP and NADPH — the energy currency used to drive the carbon fixation reactions of the Calvin cycle (light-independent reactions)'],3),
  ('The Calvin cycle (light-independent reactions) ___.',['produces ATP from light','splits water molecules','occurs in the thylakoid','uses ATP and NADPH from the light reactions to fix CO₂ into organic molecules (ultimately producing G3P, from which glucose is made) in the stroma of the chloroplast'],3),
  ('The overall equation for photosynthesis is ___.',['6O₂ + C₆H₁₂O₆ → 6CO₂ + 6H₂O + energy','CO₂ + H₂O → glucose (simplified)','6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂','C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP'],2),
  ('Photorespiration reduces photosynthetic efficiency because ___.',['plants absorb too much light','chlorophyll is unstable','CO₂ is toxic to plants','when CO₂ levels are low and O₂ levels are high, RuBisCO (the enzyme fixing CO₂) binds O₂ instead, causing carbon loss rather than carbon fixation'],3)]),
C('Solutions Chemistry: Concentration and Solubility','Students explore solution chemistry — concentration units (mol/L), solubility rules, and factors affecting solubility and rate of dissolving.',[
  ('Concentration in mol/L (molarity, M) is calculated as ___.',['mass ÷ volume (in L)','moles × volume','moles ÷ mass','moles of solute ÷ volume of solution in litres — c = n/V'],3),
  ('To prepare 250 mL of 2.0 M NaCl (molar mass 58.5 g/mol), you need ___.',['250 g of NaCl','117 g of NaCl','58.5 g of NaCl','29.25 g (n = c×V = 2.0 × 0.25 = 0.5 mol; mass = 0.5 × 58.5 = 29.25 g)'],3),
  ('A saturated solution is ___.',['a solution with no solute dissolved','one that dissolves solute very quickly','a solution with no solvent remaining','a solution at equilibrium — containing the maximum amount of dissolved solute at a given temperature; additional solute will not dissolve'],3),
  ('Solubility typically increases with temperature for ___.',['all solids','only ionic compounds','gases in water','most solid solutes (ionic and molecular) — higher temperature increases molecular kinetic energy and breaks solute-solute interactions more effectively'],3),
  ('The solubility of gases in water ___.',['increases with temperature','is unaffected by temperature','is unaffected by pressure','decreases with temperature and increases with pressure (Henry\'s Law) — carbonated drinks go flat when warm because CO₂ solubility decreases'],3)]),
]),
day(6,[
E('Literature: The Short Story — Advanced Analysis','Students perform close analysis of short stories, examining narrative technique, point of view, structural choices, and the function of ambiguity.',[
  ('Unreliable narration in a short story means ___.',['the narrator lies deliberately','the author is dishonest','the story has factual errors','the narrator\'s account is incomplete, self-deluded, or distorted — the gap between what the narrator presents and what the reader infers creates dramatic irony and interpretive richness'],3),
  ('In medias res opening in a short story ___.',['begins with a long backstory','uses flashback throughout','always confuses readers','begins in the middle of the action, dropping the reader into an ongoing situation — creating immediate tension and immersion'],3),
  ('The "iceberg theory" (Hemingway) in short fiction means ___.',['stories must be about the ocean','the story is always cold in tone','plot is the only important element','the story\'s real meaning lies beneath the surface — what is omitted and implied is more powerful than what is explicitly stated'],3),
  ('Ambiguous endings in short stories ___.',['indicate poor writing','are only used by inexperienced writers','always resolve if read carefully','are deliberately crafted to produce interpretive openness — multiple valid readings that reflect the complexity of life rather than the neatness of formula'],3),
  ('The most sophisticated analysis of a short story examines ___.',['only plot events','only character description','only rhyme and rhythm','the relationship between form and meaning: how structure, narrative technique, language, and imagery work together to create the story\'s effects and meanings'],3)]),
F('Logarithmic Functions: Definition, Properties, and Graphs','Students are introduced to logarithms as the inverse of exponential functions and explore their properties and applications.',[
  ('log_b(x) = y means ___.',['b times y equals x','b + y = x','b ÷ y = x','b^y = x — the logarithm answers "to what power must we raise b to get x?"'],3),
  ('log₁₀(1000) = ___.',['100','10³ (but we want the log)','3 (since 10³ = 1000)','30'],2),
  ('The product rule of logarithms states ___.',['log(a × b) = log(a) × log(b)','log(a + b) = log(a) + log(b)','log(a + b) = log(a) + log(b) — this is FALSE','log(ab) = log(a) + log(b) — a true rule: multiplying arguments corresponds to adding logarithms'],3),
  ('The graph of y = log₂(x) has ___.',['a vertical asymptote at y = 0','a horizontal asymptote at x = 0','passes through (1, 0) and (2, 1), is increasing, has a vertical asymptote at x = 0 (the y-axis), and is the reflection of y = 2ˣ across y = x','passes through (0, 0)'],2),
  ('Logarithms are useful in science because ___.',['they only apply to earthquakes','they simplify multiplication to addition','they eliminate the need for exponents','they compress very large (or very small) ranges — the Richter scale, pH, decibels all use logarithmic scales to make very wide ranges of values manageable'],1)]),
B('Cellular Respiration: Glycolysis, Krebs Cycle, ETC','Students examine the three stages of aerobic cellular respiration — glycolysis, the Krebs (citric acid) cycle, and the electron transport chain — and fermentation.',[
  ('Glycolysis occurs in ___.',['the mitochondrial matrix','the thylakoid','the nucleus','the cytoplasm — glucose is split into two pyruvate molecules, producing a net 2 ATP and 2 NADH, in a process requiring no oxygen'],3),
  ('The Krebs (citric acid) cycle occurs in ___.',['the cytoplasm','the thylakoid membrane','the chloroplast stroma','the mitochondrial matrix — pyruvate is oxidised, releasing CO₂, and producing NADH, FADH₂, and 2 ATP per glucose molecule'],3),
  ('The electron transport chain (ETC) occurs in ___.',['the cytoplasm','the mitochondrial matrix','the nucleus','the inner mitochondrial membrane — electrons from NADH and FADH₂ flow through protein complexes, driving ATP synthesis; oxygen is the final electron acceptor, combining with H⁺ to form water'],3),
  ('Aerobic respiration of one glucose molecule yields approximately ___.',['2 ATP','4 ATP','10 ATP','36-38 ATP total — 2 from glycolysis, 2 from the Krebs cycle, and ~32-34 from the ETC via oxidative phosphorylation'],3),
  ('Fermentation (anaerobic pathway) ___.',['produces more ATP than aerobic respiration','requires oxygen','only occurs in bacteria','regenerates NAD⁺ from NADH so glycolysis can continue — producing only 2 ATP per glucose but allowing continued energy production when oxygen is absent'],3)]),
C('Acids and Bases: Brønsted-Lowry Theory and pH Calculations','Students extend acid-base understanding to Brønsted-Lowry theory, conjugate pairs, and calculating pH and pOH from concentrations.',[
  ('Brønsted-Lowry theory defines an acid as ___.',['a substance producing OH⁻ in water (Arrhenius definition)','a substance with pH < 7 always','only a strong acid','a proton (H⁺) donor — and a base as a proton acceptor, broadening the definition beyond water solutions'],3),
  ('In the reaction HCl + H₂O → H₃O⁺ + Cl⁻, the conjugate base of HCl is ___.',['H₃O⁺','H₂O','HCl itself','Cl⁻ — the species remaining after HCl donates its proton'],3),
  ('pH = −log[H⁺]. If [H⁺] = 1 × 10⁻⁴ M, then pH = ___.',['−4','0.0001','8','4 (since −log(10⁻⁴) = 4)'],3),
  ('pOH = 14 − pH for aqueous solutions at 25°C. If pH = 3, then pOH = ___.',['3','17','11 (pOH = 14 − 3 = 11)','−3'],2),
  ('A strong acid like HCl ___.',['partially dissociates in water','does not dissociate in water','reacts with strong bases only','fully dissociates in water — [HCl] = [H⁺], so you can directly calculate pH from concentration'],3)]),
]),
day(7,[
E('Non-Fiction: The Essay Tradition','Students examine the essay as a literary form — from Montaigne and Francis Bacon to contemporary essayists — and write their own personal/reflective essay.',[
  ('The essay as a literary form originated with ___.',['newspaper opinion columns','academic journals','Greek philosophy','Michel de Montaigne in 16th-century France — "essais" meaning "attempts," personal explorations of ideas through a combination of anecdote, reflection, and argument'],3),
  ('The personal essay is literary in that ___.',['it must be fictional','it avoids argumentation','it only describes personal events','it uses literary techniques — metaphor, voice, narrative, image — to transform personal experience into a vehicle for exploring larger ideas'],3),
  ('A contemporary essayist like James Baldwin or Ta-Nehisi Coates uses personal experience to ___.',['avoid political topics','only entertain readers','provide autobiographical facts only','illuminate systemic social and political realities — the personal becomes a lens for examining race, power, and injustice in ways academic argument cannot'],3),
  ('The difference between a personal essay and a diary entry is ___.',['only length','personal essays use no personal experience','a diary entry is literary; personal essays are not','a personal essay is crafted for an audience, shaped with intention, and uses experience as material for intellectual and aesthetic exploration — a diary is private and unmediated'],3),
  ('When writing your own personal essay, the key challenge is ___.',['including enough facts','matching the teacher\'s personal style','writing about the most dramatic event possible','moving between the specific (concrete personal detail) and the general (idea, insight, significance) — the essay earns its ideas through particularity'],3)]),
F('Trigonometric Functions: Graphs of sin, cos, tan','Students graph y = sin x, y = cos x, and y = tan x, identifying key features (period, amplitude, asymptotes) and applying transformations.',[
  ('The key features of y = sin x include ___.',['amplitude 2, period 180°','no amplitude','amplitude 1, period 360°, range [−1, 1], x-intercepts at 0°, 180°, 360°...','amplitude 1, period 180°'],2),
  ('y = cos x differs from y = sin x in that ___.',['they are completely different functions','cos x has a larger amplitude','cos x has a shorter period','y = cos x starts at (0°, 1) while y = sin x starts at (0°, 0) — cos x is the sin x shifted left by 90°'],3),
  ('The graph of y = tan x has ___.',['amplitude 1','horizontal asymptotes','a period of 360°','vertical asymptotes at 90°, 270°, ... (where cos x = 0), a period of 180°, and an undefined amplitude since it goes to ±∞'],3),
  ('In y = 3sin(2x − 60°) + 1, the amplitude is ___.',['2','1','60°','3 (|a| = 3 determines amplitude)'],3),
  ('In y = 3sin(2x − 60°) + 1, the period is ___.',['360°','720°','30°','180° (period = 360°/|k| = 360°/2 = 180°)'],3)]),
B('Plant Biology: Anatomy, Photosynthesis, and Transpiration','Students examine plant structure (roots, stems, leaves), vascular tissue (xylem and phloem), and water transport (transpiration and the cohesion-tension theory).',[
  ('Xylem tissue in plants ___.',['carries sugars downward','only stores water','carries water in both directions','carries water and dissolved minerals upward from roots to leaves — the cells are dead at maturity, forming hollow tubes'],3),
  ('Phloem tissue in plants ___.',['carries only water','is dead at maturity','only exists in leaves','carries photosynthates (mainly sucrose) from source (leaves) to sink (roots, growing shoots, fruits) in a process called translocation — cells are living'],3),
  ('Transpiration is ___.',['the absorption of water by roots','the transport of sugars in the phloem','only water evaporation from the soil','the evaporation of water from leaf surfaces (mostly through stomata) — drives water movement through the xylem via the cohesion-tension mechanism'],3),
  ('Stomata open and close in response to ___.',['only temperature','only wind','only darkness','guard cell turgor: in light, guard cells absorb water and swell (opening stomata for gas exchange); in darkness or water stress, they lose turgor and close (reducing transpiration)'],3),
  ('The cohesion-tension theory explains ___.',['how phloem transports sugars','how root pressure alone moves water','how water enters roots','how the cohesion of water molecules (hydrogen bonding) and tension from transpiration pull water as a continuous column through the xylem from roots to leaves'],3)]),
C('Organic Chemistry: Naming and Reactions','Students learn IUPAC nomenclature for simple organic compounds (alkanes, alkenes, alcohols, carboxylic acids) and examine substitution, addition, and esterification reactions.',[
  ('The IUPAC name for CH₃CH₂CH₃ is ___.',['methane','butane','ethane','propane — three carbon chain, all single bonds, no functional group'],3),
  ('An addition reaction with alkenes involves ___.',['breaking a C-C single bond','removing atoms from a molecule','replacing one atom with another','adding atoms across a C=C double bond — e.g., H₂ + CH₂=CH₂ → CH₃CH₃ (hydrogenation)'],3),
  ('An esterification reaction combines ___.',['two alcohols','an alcohol and a base','an acid and a base','a carboxylic acid and an alcohol to produce an ester and water (e.g., acetic acid + ethanol → ethyl acetate + water)'],3),
  ('The functional group −OH is found in ___.',['carboxylic acids','aldehydes','esters','alcohols — it defines the alcohol family and gives them their characteristic properties (higher boiling points, water miscibility for small alcohols)'],3),
  ('The functional group −COOH is found in ___.',['alcohols','esters','alkenes','carboxylic acids — the combination of a carbonyl (C=O) and hydroxyl (−OH) makes carboxylic acids acidic; they donate the −OH proton in water'],3)]),
]),
day(8,[
E('Shakespeare: Othello or Hamlet','Students study one of Shakespeare\'s major tragedies in depth, examining tragic structure, the tragic hero, language, and key thematic concerns.',[
  ('The Aristotelian tragic hero has ___.',['no personal agency','perfect virtue','a hamartia (tragic flaw) or error of judgement that leads to their downfall — even the greatest tragic heroes bring about their own ruin through a quality that is also their defining characteristic','no relation to their downfall'],2),
  ('Othello\'s hamartia is often identified as ___.',['excessive intelligence','political ambition','cowardice','jealousy combined with credulity — his tendency to trust Iago over Desdemona, and to let jealousy overwhelm his reason and love'],3),
  ('Dramatic irony in tragedy is ___.',['statements that turn out to be true','dialogue between two characters','when actors improvise on stage','when the audience knows more than one or more characters — in Othello, we know Iago\'s malevolence while Othello does not, creating intense tragic tension'],3),
  ('The soliloquy in Shakespearean tragedy ___.',['is a conversation between two characters','always provides false information','allows a character to speak their inner thoughts directly to the audience, revealing psychological depth not visible through dialogue and action alone','is only used in comedy'],3),
  ('Shakespeare\'s tragedies explore ___.',['only romantic love','only political power','only revenge narratives','fundamental aspects of human experience: ambition, jealousy, loyalty, love, power, moral corruption — through characters of complexity in whom audiences recognise themselves'],3)]),
F('Trigonometric Identities','Students prove and apply basic trigonometric identities (Pythagorean, quotient, reciprocal) and use them to simplify expressions.',[
  ('The Pythagorean identity is ___.',['sin x + cos x = 1','tan²x + 1 = sec²x — this is one form; the fundamental form is sin²x + cos²x = 1','sin x = cos(90° − x)','tan x = sin x + cos x'],1),
  ('The quotient identity states ___.',['sin x / cos x = 1','sin x + cos x = tan x','cos x / sin x = tan x','sin x / cos x = tan x — this follows directly from the definitions of sin, cos, and tan'],3),
  ('The reciprocal identity for cosecant is ___.',['csc x = cos x','csc x = sin x','csc x = 1/tan x','csc x = 1/sin x'],3),
  ('To prove a trigonometric identity, you ___.',['substitute specific values to "prove" it','move terms from right to left only','start from both sides simultaneously','start from one side (usually the more complex) and transform it algebraically using known identities until it equals the other side — you may only work on one side at a time'],3),
  ('Simplify: (1 − sin²x)/cos x',['cos x (using sin²x + cos²x = 1, so 1 − sin²x = cos²x; then cos²x/cos x = cos x)','1/cos x','sin x','1 − sin x/cos x'],0)]),
B('Animal Physiology: Digestion and Circulation','Students examine the human digestive system and cardiovascular system, connecting structural features to functions.',[
  ('Mechanical digestion (physical breakdown) begins in ___.',['the stomach','the small intestine','the oesophagus','the mouth — teeth physically break food into smaller pieces, increasing surface area for enzymatic digestion; the tongue shapes the bolus for swallowing'],3),
  ('Enzymes in the small intestine (from the pancreas and intestinal wall) ___.',['only digest fats','only digest proteins','digest nothing (only absorption occurs)','complete the chemical digestion of carbohydrates, proteins, and fats into absorbable monomers (glucose, amino acids, fatty acids)'],3),
  ('The heart\'s right side ___.',['pumps oxygenated blood to the body','only receives blood from the body','pumps oxygenated blood to the lungs','receives deoxygenated blood from the body (via right atrium) and pumps it to the lungs (via right ventricle) — pulmonary circulation'],3),
  ('Capillaries are the site of ___.',['all blood storage','fast, high-pressure blood flow','heart pumping','gas exchange, nutrient delivery, and waste collection between blood and tissues — their walls are only one cell thick to facilitate diffusion'],3),
  ('A normal resting heart rate of 60-100 BPM is controlled by ___.',['conscious thought','the cerebral cortex','respiratory muscles','the sinoatrial (SA) node — the heart\'s natural pacemaker in the right atrium that generates electrical impulses initiating each heartbeat'],3)]),
C('Electrochemistry: Oxidation-Reduction Reactions','Students examine redox reactions, oxidation states, the activity series, galvanic cells, and electrolysis.',[
  ('In a redox reaction, oxidation means ___.',['gaining electrons','forming a neutral atom','gaining protons','losing electrons — "OIL RIG": Oxidation Is Loss, Reduction Is Gain'],3),
  ('In Zn + Cu²⁺ → Zn²⁺ + Cu, ___.',['Zn is reduced; Cu²⁺ is oxidised','both are oxidised','both are reduced','Zn is oxidised (loses 2 electrons); Cu²⁺ is reduced (gains 2 electrons)'],3),
  ('The activity series (reactivity series) predicts ___.',['which elements are most common','which metals are magnetic','which metals are heaviest','which metals can displace other metals from their salts — a more active metal (higher on the series) replaces a less active metal ion in solution'],3),
  ('A galvanic (voltaic) cell ___.',['uses electrical energy to drive a non-spontaneous redox reaction','requires no chemical reaction','only works with acids','converts chemical energy from a spontaneous redox reaction into electrical energy — like a battery'],3),
  ('Electrolysis ___.',['is always spontaneous','produces no useful products','only works with metals','uses electrical energy to drive a non-spontaneous chemical reaction — for example, decomposing water into H₂ and O₂, or electroplating metals'],3)]),
]),
day(9,[
E('Writing: The Literary Research Essay','Students write a research essay that situates a literary text within its historical, cultural, or biographical context, integrating secondary sources responsibly.',[
  ('Secondary sources in a literary research essay ___.',['replace close reading of the primary text','should be copied to show research','only include internet sources','provide scholarly perspectives, historical context, and critical arguments that enrich your analysis of the primary text — they supplement, not replace, your own reading'],3),
  ('In-text citation (MLA or APA) is required ___.',['only for direct quotations','when using information, ideas, or arguments from a source, whether quoted, paraphrased, or summarised — failure to cite is plagiarism','only in formal academic papers','only for statistics'],1),
  ('The difference between quoting and paraphrasing is ___.',['there is no difference','quotation is always better','paraphrasing avoids citation','quoting reproduces the exact words of a source; paraphrasing restates the ideas in your own words — both require citation'],3),
  ('Evaluating the credibility of a secondary source requires examining ___.',['only how recently it was written','only whether it is published in a book','how long it is','author credentials, publication venue (peer-reviewed journal vs. blog), methodology, evidence quality, and whether other scholars in the field engage with it'],3),
  ('A common error in literary research essays is ___.',['using too much evidence','making your argument too clear','over-quoting secondary sources and under-arguing — filling pages with what critics say without making your own analytical contribution'],3)]),
F('Applications of Exponential and Logarithmic Functions','Students solve exponential equations using logarithms and apply these functions to compound interest, population growth, and half-life problems.',[
  ('To solve 3ˣ = 50, you ___.',['use x = 50/3','cannot solve without a calculator being present','use the change of base formula: x = log(50)/log(3) ≈ 3.56','try x = 3 and x = 4 only'],2),
  ('A population of 1000 grows at 5% per year. After t years, population P = ___.',['P = 1000 + 50t','P = 1000 × 0.05t','P = 1000(0.05)^t','P = 1000(1.05)^t — exponential growth model'],3),
  ('The half-life formula is A(t) = A₀(1/2)^(t/h), where h is the half-life. If h = 3 years, how much of 80 g remains after 9 years?',['20 g','40 g','10 g (80 × (1/2)^(9/3) = 80 × (1/2)³ = 80/8 = 10)','5 g'],2),
  ('Using logarithms to solve population doubling time: if P = P₀(2)^(t/T), how long to double at a 7% annual growth rate? (Using rule of 70: T ≈ 70/r)',['100 years','7 years','14 years (T ≈ 70/7 = 10 years exactly by rule; exact log gives ~10.2 years)','70 years'],2),
  ('Compound interest A = P(1 + r/n)^(nt). $2000 invested at 6% compounded monthly for 5 years gives ___.',['A = 2000(1.06)^5','A = 2000 + 2000×0.06×5','A = 2000(1 + 0.06/12)^(12×5) ≈ $2693.71','A = 2000 × 0.06 × 60'],2)]),
B('Ecology: Population Dynamics and Community Ecology','Students examine population growth models (exponential and logistic), interspecific interactions, and energy flow in ecosystems.',[
  ('Logistic growth differs from exponential growth in that ___.',['logistic growth is always slower','logistic growth cannot model population change','logistic growth has no carrying capacity','logistic growth incorporates a carrying capacity (K) — the maximum population the environment can sustain — so growth slows as the population approaches K'],3),
  ('The logistic growth equation dN/dt = rN(K−N)/K shows that ___.',['population always grows to infinity','K represents initial population','growth rate is always constant','when N is small, growth is approximately exponential; when N approaches K, (K−N)/K approaches 0 and growth slows to zero'],3),
  ('Interspecific competition between two species may result in ___.',['always one species going extinct','always coexistence','evolution with no change','competitive exclusion (one species eliminates the other from the habitat) OR resource partitioning (species evolve to use different resources, allowing coexistence)'],3),
  ('A mutualistic relationship (e.g., bees and flowers) benefits ___.',['only the bee','only the flower','only one species at the expense of the other','both species — bees get nectar, flowers get pollination'],3),
  ('Energy flow through a food chain is ___.',['100% efficient at each level','50% efficient','infinite in a healthy ecosystem','approximately 10% efficient (the 10% rule) — 90% of energy is lost as heat at each trophic level, so food chains are limited to 4-5 levels'],3)]),
C('Chemical Equilibrium: Le Chatelier\'s Principle','Students examine reversible reactions, dynamic equilibrium, equilibrium constant expressions (Keq), and Le Chatelier\'s principle for predicting shifts.',[
  ('Dynamic equilibrium means ___.',['the reaction has stopped completely','only the forward reaction is occurring','there is no reaction','the forward and reverse reactions occur at equal rates — concentrations of reactants and products remain constant, but molecular exchange continues'],3),
  ('The equilibrium constant expression Keq for aA + bB ⇌ cC + dD is ___.',['Keq = [A][B]/[C][D]','Keq = (a+b)/(c+d)','Keq = [C]^c[D]^d / [A]^a[B]^b — products over reactants, with each concentration raised to the power of its stoichiometric coefficient','Keq = [C][D]/[A][B] regardless of coefficients'],2),
  ('A large Keq (>> 1) means ___.',['products are strongly favoured at equilibrium — the reaction goes essentially to completion','reactants are strongly favoured','the reaction is at equilibrium with equal concentrations','the reaction is very slow'],0),
  ('Le Chatelier\'s principle states ___.',['equilibrium always favours the exothermic direction','equilibrium never shifts','increasing temperature always increases product yield','when a system at equilibrium is disturbed, it will shift to counteract the disturbance — e.g., increasing product concentration shifts equilibrium to the left'],3),
  ('Adding an inert gas to a gas-phase equilibrium system at constant volume ___.',['shifts equilibrium to the right','shifts equilibrium to the left','doubles the pressure','does not affect the equilibrium position because it does not change the partial pressures or concentrations of the reacting species'],3)]),
]),
day(10,[
E('Drama: Studying a Contemporary Play','Students read and analyse a 20th or 21st century Canadian or international play, examining dramatic technique, theatrical conventions, and thematic concerns.',[
  ('Dramatic irony in theatre differs from dramatic irony in prose in that ___.',['they are identical','dramatic irony only exists in comedy','irony doesn\'t exist in drama','in performance, actors\' physical choices — expressions, blocking, tone — can layer additional levels of meaning onto the scripted irony, creating a visual/gestural dimension absent from prose'],3),
  ('Stage directions in a script ___.',['are not part of the literary text','only specify where actors stand','must always be followed by directors','reveal the playwright\'s intentions about staging, character, and atmosphere — and in published editions, are part of the literary text available for analysis'],3),
  ('Political theatre (Brecht, Canadian political plays) aims to ___.',['only entertain','avoid all political content','always use realistic staging','provoke critical thinking about social and political structures — using theatrical techniques to prevent passive identification and encourage active, analytical engagement with ideas'],3),
  ('Reading a play vs. watching it performed involves ___.',['completely different works','no meaningful differences','identical interpretive experiences','complementary but distinct experiences — reading gives you the text; performance adds interpretation through actors\' choices, design, music, and directorial vision'],3),
  ('The unities (time, place, action) in classical drama ___.',['are required in all modern drama','have never been questioned','are irrelevant to study','were formal constraints in classical drama (one location, one day, one main action) that modern theatre largely abandoned — though many plays still explore their possibilities'],3)]),
F('Discrete Functions: Sequences and Series','Students investigate arithmetic and geometric sequences and series, using formulas for nth term and sum, with applications to finance and patterns.',[
  ('In an arithmetic sequence, each term is ___.',['multiplied by a common ratio','squared each time','the same as the previous','obtained by adding a common difference d to the previous term — e.g., 5, 8, 11, 14... (d = 3)'],3),
  ('The nth term of an arithmetic sequence is ___.',['tₙ = t₁ × rⁿ⁻¹','tₙ = t₁ + n','tₙ = t₁ + (n−1)d — where t₁ is the first term and d is the common difference','tₙ = t₁ × n'],2),
  ('In a geometric sequence, each term is ___.',['the square of the previous','the sum of the previous two','the same as the previous','multiplied by a common ratio r — e.g., 2, 6, 18, 54... (r = 3)'],3),
  ('The sum of the first n terms of a geometric series is ___.',['Sₙ = n(t₁ + tₙ)/2','Sₙ = t₁rⁿ','Sₙ = t₁(rⁿ − 1)/(r − 1) — for r ≠ 1','Sₙ = t₁ + (n−1)r'],2),
  ('Compound interest is a geometric sequence because ___.',['interest is added as a fixed amount each period','it has a common difference','it does not relate to sequences','each year\'s value is the previous year\'s value multiplied by (1 + r) — a constant ratio'],3)]),
B('Animal Physiology: Nervous System and Endocrine System','Students examine the structure and function of neurons, the central and peripheral nervous system, and the hormonal regulation of body functions.',[
  ('A nerve impulse (action potential) is transmitted by ___.',['chemical diffusion only','physical contraction of the nerve','muscle contractions','a rapid change in membrane potential caused by the movement of Na⁺ and K⁺ ions across the neuron membrane — the "all-or-nothing" electrical signal'],3),
  ('The synapse between two neurons involves ___.',['direct electrical connection only','DNA transfer between neurons','physical contact between neurons','neurotransmitters: the presynaptic neuron releases chemicals into the synaptic cleft, which bind to receptors on the postsynaptic neuron, either exciting or inhibiting it'],3),
  ('The somatic (voluntary) nervous system controls ___.',['involuntary internal organs','digestion','cardiac muscle','skeletal (voluntary) muscles — consciously directed movement'],3),
  ('The autonomic nervous system\'s sympathetic division ___.',['slows the heart and increases digestion','only controls pain','prepares the body for "fight or flight": increases heart rate, blood pressure, and blood glucose; dilates airways; reduces digestion','controls only smooth muscle'],2),
  ('Hormones differ from nerve signals in that ___.',['hormones are faster','hormones only work in the brain','there is no difference','hormones are chemical messengers released into the bloodstream and travel to distant target organs — slower than nerve impulses but longer-lasting and body-wide in their effects'],3)]),
C('Nuclear Chemistry: Radioactive Decay and Nuclear Reactions','Students examine types of radioactive decay (alpha, beta, gamma), nuclear equations, half-life calculations, and applications of nuclear chemistry.',[
  ('Alpha (α) decay produces ___.',['only energy','a beta particle and energy','an electron and a neutrino','a helium nucleus (⁴₂He) — the parent nucleus loses 2 protons and 2 neutrons, becoming a different element with Z decreased by 2 and A decreased by 4'],3),
  ('Beta (β) decay produces ___.',['a helium nucleus','only gamma radiation','no change in the nucleus','an electron (β particle) emitted from the nucleus when a neutron converts to a proton and electron — the element changes (Z increases by 1, A stays the same)'],3),
  ('Gamma (γ) radiation is ___.',['a stream of electrons','a stream of helium nuclei','a type of sound wave','high-energy electromagnetic radiation emitted when an excited nucleus releases energy — it accompanies alpha or beta decay and has no charge or mass'],3),
  ('Half-life of a radioactive isotope means ___.',['the time for the nucleus to split in half','the time for 25% to decay','the minimum decay time','the time required for exactly half of the radioactive nuclei in a sample to decay — after n half-lives, (1/2)ⁿ of the original sample remains'],3),
  ('Carbon-14 dating works because ___.',['all carbon-14 remains constant over time','carbon-14 has a very long half-life of millions of years','carbon-14 is non-radioactive in living organisms','living organisms maintain a constant C-14/C-12 ratio; when an organism dies, C-14 decays at a known rate (half-life ~5730 years) allowing age to be calculated from remaining C-14'],3)]),
]),
day(11,[
E('Writing: The Personal Statement and Formal Writing for Future Purposes','Students write a university or college personal statement, understanding audience, voice, and purpose in high-stakes formal writing.',[
  ('A university personal statement differs from a school essay in that ___.',['it is shorter and less important','it has no thesis','it never discusses achievements','its primary purpose is to present a specific, authentic version of who you are to an admissions committee — your voice, experiences, and thinking matter as much as credentials'],3),
  ('The biggest mistake in a personal statement is ___.',['being too specific about experiences','sounding too genuine','connecting experience to thinking','telling a story without reflection — describing events without revealing what you learned, how you think, and what these experiences show about who you are'],3),
  ('Specific, concrete details in a personal statement are important because ___.',['they make it longer','they replace the need for argument','they impress with facts only','specific details are memorable and credible — admissions officers read thousands of vague statements about "leadership" and "passion"; concrete detail makes you real and distinct'],3),
  ('The personal statement is an opportunity to address ___.',['only academic achievements','anything not shown in transcripts: your thinking, growth, distinctive experiences, intellectual passions, and the qualities that make you a contributing member of a learning community','only extracurricular activities','only weaknesses in your transcript'],1),
  ('Editing a personal statement requires ___.',['only checking grammar','removing all personal details','asking everyone to edit it until it sounds generic','reading it aloud for naturalness of voice, cutting any sentence that doesn\'t serve the essay\'s argument, and asking someone who doesn\'t know you to read it for clarity and authenticity'],3)]),
F('Combinations and Permutations: Counting Principles','Students apply the fundamental counting principle, factorial notation, permutations (ₙPᵣ), and combinations (ₙCᵣ) to counting and probability problems.',[
  ('The Fundamental Counting Principle states ___.',['total = a + b + c for all events','all events must be independent always','only applies to 2 events','if one event can occur in m ways and another in n ways, they can occur together in m × n ways'],3),
  ('n! (n factorial) means ___.',['n divided by itself','only defined for n < 10','n + (n−1) + ... + 1','n × (n−1) × (n−2) × ... × 2 × 1 — the number of ways to arrange n distinct objects'],3),
  ('ₙPᵣ = n!/(n−r)! counts ___.',['combinations of r items from n','unordered subsets','only circular arrangements','the number of ordered arrangements (permutations) of r items chosen from n distinct items — order matters'],3),
  ('ₙCᵣ = n!/[r!(n−r)!] counts ___.',['ordered arrangements','only pairs of items','circular permutations','the number of unordered selections (combinations) of r items from n — order does not matter'],3),
  ('How many ways can 3 students be chosen from a class of 25 for a committee (order doesn\'t matter)?',['25P3 = 13800','25 × 3 = 75','25!/3!','₂₅C₃ = 25!/(3! × 22!) = 2300'],3)]),
B('Genetics: Chromosomal Abnormalities and Genetic Disorders','Students examine chromosomal abnormalities (trisomy, monosomy), genetic disorders (single-gene, multifactorial), and genetic counselling.',[
  ('Trisomy 21 (Down syndrome) results from ___.',['a point mutation in chromosome 21','a deletion of chromosome 21','only paternal chromosomes being duplicated','non-disjunction during meiosis — chromosome 21 fails to separate, producing a gamete with 2 copies of chromosome 21; the resulting zygote has 3 copies (47 total chromosomes)'],3),
  ('A recessive autosomal disorder (e.g., cystic fibrosis) is expressed when ___.',['only one copy of the allele is inherited','the individual is male','the mother is a carrier','an individual has two copies of the recessive allele (homozygous recessive) — carriers (heterozygotes) are unaffected'],3),
  ('An autosomal dominant disorder (e.g., Huntington\'s disease) ___.',['requires two copies of the allele for expression','only affects males','skips generations','requires only one copy of the dominant allele to be expressed — affected individuals usually have at least one affected parent, and it doesn\'t skip generations'],3),
  ('BRCA1/2 gene mutations are associated with ___.',['a guaranteed diagnosis of cancer','no increased cancer risk','immunity to all cancer','significantly increased risk of breast and ovarian cancer — but are inherited predispositions, not certainties; lifestyle and other genetic factors also play a role'],3),
  ('Genetic counselling helps individuals and families ___.',['make all genetic decisions for clients','guarantee they will have healthy children','require genetic testing by law','understand the implications of genetic information, assess risk, and make informed decisions about family planning and medical management — empowering autonomous choice'],3)]),
C('Thermochemistry: Energy Changes in Chemical Reactions','Students examine exothermic and endothermic reactions, Hess\'s Law, enthalpy of formation, and calorimetry.',[
  ('An exothermic reaction ___.',['absorbs heat from the surroundings','has ΔH > 0','has no energy change','releases heat to the surroundings — ΔH < 0 (negative enthalpy change), products have lower energy than reactants'],3),
  ('An endothermic reaction ___.',['releases heat','has ΔH < 0','has no temperature change','absorbs heat from the surroundings — ΔH > 0 (positive enthalpy change), products have higher energy than reactants'],3),
  ('Hess\'s Law states ___.',['only direct measurements of ΔH are valid','ΔH depends on the direction but not on the path','all reactions have equal ΔH values','the enthalpy change for a reaction is the same regardless of the pathway taken — allowing ΔH values to be added and subtracted algebraically for multi-step reactions'],3),
  ('In a calorimetry experiment, q = mcΔT, where ___.',['m = moles, c = concentration','m is mass, c is specific heat capacity, ΔT is temperature change — this calculates the heat absorbed or released by the water in the calorimeter','m is molecular mass, c is colour','q is pressure and T is volume'],1),
  ('The standard enthalpy of formation (ΔH°f) of an element in its standard state is ___.',['measured by calorimetry for each element','equal to its molar mass','always positive','defined as zero by convention — this provides the baseline for calculating enthalpy changes of reactions'],3)]),
]),
day(12,[
E('Media Analysis: Advertising and Consumer Culture','Students critically analyse advertising techniques, examining how ads construct desire, identity, and social norms, and practise writing critical media analysis.',[
  ('Advertising creates desire by ___.',['only providing product information','only using celebrity endorsements','always telling the truth about products','linking products to values, emotions, and identities people aspire to — buying the product is presented as a way to become the person in the ad, not just to acquire an object'],3),
  ('The male gaze in advertising (Laura Mulvey\'s concept) refers to ___.',['only how men look at ads','only female consumers seeing ads','all advertising using the same angle','the visual convention of presenting the world from a heterosexual male viewpoint — objectifying women as passive objects to be looked at rather than active subjects'],3),
  ('Greenwashing in advertising means ___.',['genuinely sustainable product marketing','using green colour schemes','companies making misleading claims about the environmental benefits of their products to attract eco-conscious consumers without substantive environmental changes','only in food advertising'],2),
  ('Analysing an ad\'s rhetorical strategy means ___.',['only describing what you see','ignoring the target audience','only examining the visual layout','examining how the ad uses ethos (brand credibility), logos (product claims), and pathos (emotional appeal) to persuade its specific target audience'],3),
  ('The CRTC (Canadian Radio-television and Telecommunications Commission) ___.',['has no authority over advertising','regulates all Canadian media content','promotes all advertising','regulates broadcasting and telecommunications in Canada, including rules about advertising to children, truth in advertising, and Canadian content requirements'],1)]),
F('Probability: Conditional Probability and Independent Events','Students examine classical and experimental probability, conditional probability, independent and dependent events, and Bayes\' theorem (introductory).',[
  ('Two events A and B are independent if ___.',['P(A) = P(B)','P(A ∩ B) = 0','P(A) + P(B) = 1','P(A|B) = P(A) — knowing B occurred gives no information about A; equivalently, P(A ∩ B) = P(A) × P(B)'],3),
  ('Conditional probability P(A|B) means ___.',['P(A) × P(B)','P(A) − P(B)','P(A) + P(B)','the probability of A occurring given that B has already occurred = P(A ∩ B)/P(B)'],3),
  ('Drawing two cards from a deck without replacement: P(both hearts) = ___.',['(13/52)²','13/52 × 12/52 = 156/2704 (dependent events)','13/52 × 13/51','13/52 × 12/51 = 156/2652 ≈ 0.0588 (dependent: second draw changes after first)'],3),
  ('A false positive in medical testing occurs when ___.',['a test correctly identifies disease','a test correctly identifies no disease','the disease goes undetected','the test indicates disease when none is present — understanding this requires conditional probability (Bayes\' theorem) to interpret test results correctly'],3),
  ('In a bag with 3 red and 5 blue marbles, P(red then blue without replacement) = ___.',['3/8 × 5/8','3/8 × 5/7 = 15/56 (dependent)','3/8 + 5/7','8/8 × 5/7'],1)]),
B('Human Health: Immune System and Disease','Students examine innate and adaptive immunity, vaccination, autoimmune disorders, and the biological basis of disease response.',[
  ('Innate immunity is ___.',['only effective against specific pathogens','slower to activate than adaptive immunity','identical in all individuals','the non-specific first line of defence — including skin, mucus membranes, fever, inflammation, and phagocytic cells — present from birth and responding rapidly but non-specifically to any pathogen'],3),
  ('Adaptive (acquired) immunity is ___.',['non-specific','only present in adults','identical to innate immunity','specific — triggered by exposure to particular antigens, producing lymphocytes (B and T cells) that target those antigens specifically and create immunological memory'],3),
  ('Vaccination works by ___.',['injecting active disease-causing microbes','providing temporary passive immunity only','eliminating all future immune responses','exposing the immune system to antigens (in a safe form) to trigger an adaptive immune response and build immunological memory, so future exposure to the real pathogen triggers rapid response'],3),
  ('An autoimmune disease occurs when ___.',['the immune system fails to respond at all','only external pathogens cause disease','immunity is too weak','the adaptive immune system mistakenly attacks the body\'s own tissues — examples include Type 1 diabetes (attacks pancreatic beta cells), rheumatoid arthritis, and multiple sclerosis'],3),
  ('Anaphylaxis is ___.',['a mild immune response','only caused by food','only a response to exercise','a severe, life-threatening allergic reaction — an exaggerated immune response to an antigen causing widespread vasodilation, airway constriction, and circulatory collapse'],3)]),
C('Electrochemistry: Batteries and Industrial Applications','Students examine common battery types, fuel cells, the Downs cell, the chlor-alkali process, and environmental considerations of electrochemical technologies.',[
  ('A fuel cell differs from a battery in that ___.',['fuel cells have no reaction','fuel cells produce no electricity','batteries are always rechargeable','a fuel cell continuously converts fuel (e.g., hydrogen) and an oxidant (oxygen) to electricity as long as fuel is supplied — it doesn\'t "run out" like a battery but is replenished'],3),
  ('The hydrogen fuel cell produces ___.',['CO₂ and water','only water vapour','only hydrogen gas','electricity, with water as the only byproduct — making it a very clean energy source if the hydrogen is produced from renewable energy'],1),
  ('Lithium-ion batteries are preferred for EVs because ___.',['they use no lithium','they are non-rechargeable','they are the cheapest batteries available','they have high energy density, low weight, and can be recharged many times — though mining lithium raises environmental and ethical concerns'],3),
  ('The Downs cell uses electrolysis to produce ___.',['aluminium from bauxite','hydrogen from water','table salt from sodium and chlorine','sodium metal and chlorine gas from molten NaCl — allowing the production of pure sodium used in various industrial processes'],3),
  ('Electroplating uses electrolysis to ___.',['dissolve metals','extract metals from ore','measure metal purity','coat an object with a thin layer of metal by making it the cathode in an electroplating solution containing the metal ions'],3)]),
]),
day(13,[
E('Independent Reading: Global Literature','Students read a novel from outside Canada and the Anglo-American tradition, examining universal themes and culturally specific contexts.',[
  ('Reading world literature in translation exposes students to ___.',['simpler stories than English literature','only historical texts','fiction unworthy of serious study','narrative traditions, world views, and ways of structuring story that may differ fundamentally from the Western tradition — enriching and challenging assumptions about what literature "is"'],3),
  ('Magical realism (e.g., Gabriel García Márquez, Salman Rushdie) is characterised by ___.',['purely realistic narrative','fantasy with no real-world connection','supernatural events treated as mundane within an otherwise realistic narrative — challenging the boundary between reality and myth in ways that often carry political meaning','only South American fiction'],2),
  ('Post-colonial literature often engages with ___.',['colonial nostalgia','only native traditions','no English literary tradition','the legacy of colonialism: identity in the aftermath of occupation, language and cultural displacement, the writing back against or within the coloniser\'s language, and the complexity of "home"'],3),
  ('Examining the cultural context of world literature means ___.',['reducing all meaning to culture','ignoring the text itself','assuming all meaning is culturally specific','researching the historical, political, and social circumstances of the author and their country to understand references, values, and narrative choices that might otherwise be opaque'],3),
  ('Universal themes in world literature suggest ___.',['all cultures are identical','cultural context is irrelevant','stories that work everywhere are identical','despite enormous cultural difference, certain human concerns — love, justice, identity, survival, power, family — appear across all literary traditions, suggesting deep commonalities'],3)]),
F('Discrete Structures: Financial Mathematics','Students apply sequences, series, and exponential functions to advanced financial calculations: mortgages, annuities, and investment planning.',[
  ('An annuity is ___.',['a one-time investment','a type of insurance','a government pension only','a series of equal regular payments over time — e.g., monthly mortgage payments or pension payments'],3),
  ('The present value of an annuity is ___.',['the final payment amount','only relevant for pensions','always greater than its future value','the current lump-sum equivalent of a series of future payments — discounted to account for the time value of money'],3),
  ('A mortgage amortises over time because ___.',['you pay only interest forever','the principal never decreases','banks keep all extra payments','early payments are mostly interest; as the principal decreases, the interest portion of each payment falls and the principal repayment portion rises — gradually paying down the loan'],3),
  ('The Rule of 72 approximates ___.',['the time for a loan to be paid off','the number of years to double a debt','the interest rate needed to triple an investment','the time for an investment to double in value: divide 72 by the annual interest rate percentage'],3),
  ('Starting to save at age 18 vs. age 28 for retirement ___.',['makes no difference due to compound interest','is less important than the amount saved','only matters if interest rates are high','makes a very dramatic difference due to compound interest — an extra decade of compounding can double or triple the final value of the investment'],3)]),
B('Biodiversity: Species Classification and Conservation','Students examine the classification of life (taxonomic hierarchy, domains), threats to biodiversity, and strategies for conservation.',[
  ('The taxonomic hierarchy from broadest to most specific is ___.',['Kingdom, Phylum, Class, Order, Family, Genus, Species — a mnemonic: King Philip Came Over For Good Soup','Domain, Species, Genus, Family, Order...','Species, Genus, Family, Class, Phylum...','Kingdom, Species, Class, Order, Family, Phylum, Genus'],0),
  ('The three domains of life are ___.',['Animals, Plants, Fungi','Prokaryotes, Eukaryotes, Viruses','Bacteria, Archaea, Eukarya — a more fundamental classification than kingdom, based on molecular (rRNA) evidence','Plants, Animals, Protists'],2),
  ('Habitat loss is the primary driver of biodiversity loss because ___.',['only introduced species matter','climate change is the only factor','species can always move to new habitats','most species are highly adapted to specific habitats — when those habitats are destroyed, species cannot survive elsewhere, and many populations crash to extinction'],3),
  ('Keystone species are ___.',['the most common species in an ecosystem','the largest species present','always predators','species that have a disproportionately large effect on their ecosystem relative to their abundance — their removal causes cascading changes that fundamentally alter the community'],3),
  ('In-situ conservation means ___.',['conservation only in zoos','transplanting species to new habitats','keeping species in seed banks only','protecting species within their natural habitat — through national parks, protected areas, wildlife corridors, and restoration projects, as opposed to ex-situ conservation in captivity'],3)]),
C('Chemistry Review: Major Concepts and Connections','Students connect and review the major themes of Grade 11 Chemistry — bonding, stoichiometry, solutions, equilibrium, organic chemistry, and electrochemistry.',[
  ('The unifying concept connecting bonding, stoichiometry, and equilibrium is ___.',['the periodic table','electronegativity only','conservation of mass','energy — chemical reactions involve energy changes arising from bond breaking and forming; stoichiometry tracks atom amounts conserved in reactions; equilibrium describes energy-determined stable states'],0),
  ('Le Chatelier\'s principle and biological enzyme regulation are connected because ___.',['they are completely different','enzymes do not reach equilibrium','enzyme systems are exothermic always','cells regulate biochemical pathways by feedback inhibition — a form of Le Chatelier\'s principle where excess product inhibits the enzyme producing it, restoring balance'],3),
  ('Electrochemical principles (redox, activity series) explain ___.',['only industrial processes','only battery technology','only lab demonstrations','why iron rusts, why some metals are more reactive, how batteries work, why electrolysis works, and how cells transfer energy through electron carriers like NAD⁺/NADH'],3),
  ('The organic chemistry of fuels, plastics, and pharmaceuticals all involve ___.',['only ionic compounds','only metals','inorganic chemistry primarily','carbon-based molecules with functional groups that determine chemical properties — connecting organic chemistry to energy, materials, and medicine'],3),
  ('A student who truly understands Grade 11 Chemistry can ___.',['only solve numerical problems','only name compounds','only memorise the periodic table','see the chemical world: understand why medications work, why climate change involves chemical reactions, why metals corrode, and why food spoils — chemistry is everywhere'],3)]),
]),
day(14,[
E('Oral Communication: Seminar Leadership and Discussion Facilitation','Students lead a Socratic seminar on a literary or social topic, developing advanced oral communication, questioning, and facilitation skills.',[
  ('A Socratic seminar differs from a debate in that ___.',['only one person speaks in a Socratic seminar','winning is the goal','formal preparation is not required','the goal is collaborative inquiry — deepening understanding together through questioning and discussion, not winning an argument by defeating opponents'],3),
  ('An effective discussion facilitator ___.',['only asks questions to people who want to talk','always shares their own opinion first','avoids asking challenging questions','asks open, generative questions; listens actively to build on responses; redirects when needed; draws out quiet participants; and keeps the discussion focused while remaining flexible'],3),
  ('Active listening in an academic discussion means ___.',['waiting for your turn to speak','only nodding','only tracking what the teacher says','genuinely attending to what others say, tracking the development of ideas, building on and challenging specific points others have made, and changing your mind when given good reason'],3),
  ('Challenging someone\'s idea in a seminar respectfully means ___.',['never challenging anyone','only challenging in writing','attacking the person making the argument','engaging with the specific claim: "I see what you\'re saying, but I think the text suggests something different — in line X, ___"'],3),
  ('The learning value of a Socratic seminar comes from ___.',['only the teacher\'s contributions','the peer who talks the most','only having the right answers','the process of formulating your thinking in real time, responding to unexpected challenges, and developing ideas through genuine intellectual exchange with peers'],3)]),
F('Grade 11 Functions: Review and Synthesis','Students consolidate the major concepts of the Functions (MCR3U) course, connecting different function families and preparing for Grade 12 Advanced Functions.',[
  ('The key distinction between polynomial and rational functions is ___.',['rational functions always have asymptotes','polynomial functions have more zeros','polynomial functions have no restrictions on domain','rational functions involve division by a polynomial containing a variable, which creates domain restrictions (vertical asymptotes or holes) absent in polynomials'],3),
  ('Exponential and logarithmic functions are inverses: this means ___.',['they have the same graph','they can replace each other','y = bˣ and y = logb(x) are reflections of each other across y = x, and operations on one "undo" operations on the other','they are equally useful for all applications'],2),
  ('The most important connecting idea across all Grade 11 function families is ___.',['that they all look similar on a graph','that they all have asymptotes','that all functions can be graphed the same way','that every function family has characteristic behaviour (growth/decay, periodicity, asymptotes) determined by its algebraic form — understanding the form predicts the behaviour'],3),
  ('Trigonometric functions are distinct from polynomial and exponential functions in that ___.',['they have no practical applications','they are harder to graph','they have no domain restrictions','they are periodic — they repeat their values at regular intervals — modelling oscillating and cyclical phenomena like sound waves and tides'],3),
  ('A student prepared for Grade 12 Advanced Functions should be able to ___.',['only solve equations','only graph functions','only evaluate f(x) for specific values','determine domain and range, identify transformations, connect algebraic form to graphical behaviour, and choose the right function family to model a given situation'],3)]),
B('Biology Synthesis: Connections Across Strands','Students connect the major themes of Grade 11 Biology — cell biology, genetics, evolution, ecology, and physiology — into a unified understanding of life.',[
  ('The connection between cell biology and genetics is ___.',['they are unrelated at the cellular level','DNA is only relevant to genetics, not cells','cell structure determines gene expression','DNA in every cell\'s nucleus contains the genetic information that determines the cell\'s proteins and therefore its structure and function — all of biology ultimately connects at the molecular level'],3),
  ('Evolution connects to ecology because ___.',['evolution occurs independently of environment','ecology studies only short-term changes','ecology has no evolutionary implications','ecological interactions (predation, competition, mutualism) are the agents of natural selection — evolution shapes the adaptations that allow species to fill ecological niches'],3),
  ('Photosynthesis and cellular respiration are ___.',['identical processes','both performed by all cells','opposite processes: photosynthesis converts light energy to chemical energy in glucose; cellular respiration releases that chemical energy as ATP — together they cycle energy and carbon through the biosphere','unrelated to each other'],2),
  ('Genetics and evolution are connected because ___.',['evolution can occur without genetic change','genetics is not relevant to populations','mutations only matter for individual organisms','evolution is, at the molecular level, change in allele frequencies over time — genetics provides the mechanism (heritable variation) on which natural selection acts'],3),
  ('The most important insight from Grade 11 Biology is ___.',['that biology is a collection of facts to memorise','that evolution is only relevant to historical species','that cells are the only relevant level of organisation','that life is a deeply interconnected set of processes operating simultaneously at molecular, cellular, organismal, population, and ecosystem levels — change at any level affects all others'],3)]),
C('Chemistry in Society: Green Chemistry and Sustainability','Students examine the principles of green chemistry, Life Cycle Assessment, the circular economy, and the role of chemists in addressing sustainability challenges.',[
  ('Green chemistry aims to ___.',['only reduce industrial costs','oppose all chemical manufacturing','only use natural ingredients','design chemical products and processes that reduce or eliminate the generation of hazardous substances — preventing pollution at its source rather than managing it afterward'],3),
  ('The 12 principles of green chemistry include ___.',['using more energy in reactions','maximising waste production for safety','all chemicals are equally safe','atom economy (maximising incorporation of reactant atoms into product), using renewable feedstocks, designing for degradability, and minimising energy consumption'],3),
  ('Life Cycle Assessment (LCA) in chemistry evaluates ___.',['only the production stage','only cost','only final product safety','the environmental impact of a chemical product across its entire life: raw material extraction, manufacturing, transportation, use, and end-of-life disposal or recycling'],3),
  ('The circular economy applies to chemistry by ___.',['requiring all chemicals to be recycled infinitely','eliminating all synthetic chemistry','ensuring all products are biodegradable','designing chemical products and manufacturing processes to keep materials in use as long as possible, minimising waste and the need for virgin raw materials'],3),
  ('A sustainable future for chemistry requires ___.',['eliminating all chemistry','only natural products','only government regulation','chemists who can design products that are effective, affordable, and safe for human health and the environment — chemistry is essential to solving sustainability challenges, not just a source of them'],3)]),
]),
day(15,[
E('English: Year in Review and Looking Ahead to Grade 12','Students reflect on their growth as readers, writers, and thinkers in Grade 11 and set meaningful goals for Grade 12 and beyond.',[
  ('The most significant shift in Grade 11 English from Grade 10 is ___.',['only longer essays required','less reading overall','simpler vocabulary required','greater intellectual independence — you are expected to formulate your own arguments, choose your own interpretive focus, and engage with more complex texts with less scaffolding'],3),
  ('Sophisticated literary analysis at the Grade 11 level involves ___.',['memorising established interpretations','avoiding controversial interpretations','paraphrasing the text in detail','forming original, arguable interpretations; supporting them with precise textual evidence; analysing how formal choices create meaning; and engaging with the complexity and ambiguity of literary texts'],3),
  ('The most important writing skill developed in Grade 11 is ___.',['longer paragraphs','more quotations per paragraph','more varied vocabulary','thesis construction: the ability to frame a specific, arguable, intellectually interesting claim that organises and drives a coherent analytical essay'],3),
  ('Students who engage deeply with literature develop ___.',['only language skills for English class','an immunity to other arguments','no skills transferable to STEM subjects','analytical thinking, empathy, ability to engage with complexity and ambiguity, and skill at constructing and evaluating arguments — skills fundamental to all intellectual and professional fields'],3),
  ('Grade 12 English will build on Grade 11 by ___.',['requiring only grammar work','needing less analysis','being simpler and shorter','expecting even more sophisticated and independent engagement with texts, more extended and complex essays, and greater ability to situate literature within broader intellectual, historical, and cultural contexts'],3)]),
F('Functions: Final Exam Preparation','Students practise comprehensive problem-solving across all Grade 11 Functions topics.',[
  ('Solve: 2ˣ = 128',['x = 7 (since 2⁷ = 128)','x = 64','x = 14','x = 256'],0),
  ('A polynomial P(x) has zeros at x = −2 (multiplicity 2), x = 1, x = 4, with positive leading coefficient. As x → +∞, y → ___.',['y → −∞','y → 0','y → −∞ (negative leading coefficient)','y → +∞ (positive leading coefficient of even-degree polynomial... wait: degree 4 with positive leading coefficient: both ends go to +∞)'],3),
  ('Simplify: (sin²x + cos²x)/sinx',['sinx','cosx','1/sinx (since sin²x + cos²x = 1)','tanx'],2),
  ('₁₀C₄ = ___.',['210','5040','40','10'],0),
  ('For geometric series with t₁ = 3, r = 2, find S₆.',['189','96','63','3(2⁶ − 1)/(2 − 1) = 3 × 63 = 189'],3)]),
B('Biology: Final Exam Preparation','Students review key concepts across all Grade 11 Biology strands.',[
  ('The central dogma of molecular biology is ___.',['DNA → RNA → Protein (transcription then translation)','Protein → RNA → DNA','RNA → DNA → Protein','DNA → Protein directly'],0),
  ('Natural selection favours ___.',['the strongest individual','the fastest individual','the most intelligent individual','individuals with heritable traits that increase reproductive success in the current environment'],3),
  ('In aerobic cellular respiration, where is the most ATP produced?',['Glycolysis (2 ATP)','Krebs cycle (2 ATP)','Fermentation (2 ATP)','Electron transport chain (~32-34 ATP) — through oxidative phosphorylation driven by the proton gradient'],3),
  ('The biodiversity of a community is measured by ___.',['only the number of species (richness)','both species richness (number of different species) and species evenness (relative abundance of each species)','only the number of individuals','only the biomass of all species combined'],1),
  ('An ecosystem with high biodiversity is generally ___.',['less stable than one with low diversity','more likely to collapse','identical to one with low diversity in terms of function','more resilient — multiple species can perform similar functions, so the loss of one species is less catastrophic'],3)]),
C('Chemistry: Final Exam Preparation','Students review key concepts across all Grade 11 Chemistry strands.',[
  ('A reaction with ΔH = −200 kJ is ___.',['endothermic','thermoneutral','unpredictable','exothermic — the negative sign indicates heat is released to the surroundings'],3),
  ('Percent yield of 85% means ___.',['85% of the theoretical product was not formed','there was an 85% error in measurement','only 15% of reactants were used','you obtained 85% of the maximum possible product — 15% was lost to incomplete reaction, side reactions, or handling losses'],3),
  ('In the equilibrium A + B ⇌ C + D, increasing the concentration of A will ___.',['shift equilibrium to the left','have no effect','decrease the Keq','shift equilibrium to the right, producing more C and D until a new equilibrium is established'],3),
  ('The IUPAC name for CH₃CH₂OH is ___.',['methanol','propenol','ethanal','ethanol — two-carbon chain (eth-), single bond only (-an-), alcohol functional group (-ol)'],3),
  ('Zn²⁺ + 2e⁻ → Zn is an example of ___.',['oxidation (loss of electrons)','a combustion reaction','acid-base neutralisation','reduction (gain of electrons) — the zinc ion gains 2 electrons to become neutral zinc metal'],3)]),
]),
]

write_new(11, g11)
print('grade11.ts written (15 days)')
