#!/usr/bin/env python3
"""Generate missing GradesBooster curriculum TypeScript files."""
import os, re

DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data')
WK = ['Mon','Tue','Wed','Thu','Fri']

def lbl(n): return f"Day {n} — {WK[(n-1)%5]}"

def build(days):
    out = ["import type { DayContent } from '@/types';","","const curriculum: DayContent[] = ["]
    for d in days:
        out.append(f'{{day:{d[0]}, label:"{lbl(d[0])}", subjects:[')
        for sub in d[1]:
            sk,ti,su,rl,ru,quiz = sub
            out.append(f'  {{subject:"{sk}", title:"{ti}", summary:"{su}",')
            out.append(f'   resourceLabel:"{rl}", resourceUrl:"{ru}",')
            out.append('   quiz:[')
            for i,(q,opts,a) in enumerate(quiz):
                sep = ',' if i<len(quiz)-1 else ''
                os2 = ','.join(f'"{o}"' for o in opts)
                out.append(f'     {{q:"{q}", options:[{os2}], answer:{a}}}{sep}')
            out.append('   ]},')
        out.append(']},')
    out += ['];','','export default curriculum;']
    return '\n'.join(out)

def write_new(grade, days):
    p = f'{DIR}/grade{grade}.ts'
    open(p,'w').write(build(days))
    print(f'grade{grade}.ts written ({len(days)} days)')

def append_to(grade, days):
    p = f'{DIR}/grade{grade}.ts'
    content = open(p).read().rstrip()
    if content.endswith('export default curriculum;'):
        content = content[:-len('export default curriculum;')].rstrip()
    # The trailing "];" closes the `const curriculum: DayContent[] = [...]`
    # array itself -- it has to come off too, or new day blocks land after
    # the array closes instead of inside it (silently produces a file with
    # two top-level array-literal statements back to back, which looks
    # plausible on a skim but is invalid TS/JS: everything from the second
    # "];" onward is unreachable, so previously-appended days would go
    # missing from the actual exported array).
    if content.endswith('];'):
        content = content[:-len('];')].rstrip()
    extra = []
    for d in days:
        extra.append(f'{{day:{d[0]}, label:"{lbl(d[0])}", subjects:[')
        for sub in d[1]:
            sk,ti,su,rl,ru,quiz = sub
            extra.append(f'  {{subject:"{sk}", title:"{ti}", summary:"{su}",')
            extra.append(f'   resourceLabel:"{rl}", resourceUrl:"{ru}",')
            extra.append('   quiz:[')
            for i,(q,opts,a) in enumerate(quiz):
                sep = ',' if i<len(quiz)-1 else ''
                os2 = ','.join(f'"{o}"' for o in opts)
                extra.append(f'     {{q:"{q}", options:[{os2}], answer:{a}}}{sep}')
            extra.append('   ]},')
        extra.append(']},')
    extra += ['];','','export default curriculum;']
    open(p,'w').write(content+'\n'+'\n'.join(extra))
    print(f'grade{grade}.ts appended {len(days)} days')

def sub(sk,ti,su,rl,ru,quiz): return [sk,ti,su,rl,ru,quiz]
def day(n,subs): return [n,subs]

# ─── GRADE 1 ────────────────────────────────────────────────────────────────
L1='https://tvolearn.com/pages/grade-1-language'
M1='https://tvolearn.com/pages/grade-1-mathematics'
S1='https://tvolearn.com/pages/grade-1-science-and-technology'
SS1='https://tvolearn.com/pages/grade-1-social-studies'

g1=[
day(1,[sub('Language','Short Vowel Sounds','Ontario Grade 1 Reading strand: students blend short vowel sounds in CVC words such as cat, bed, pig, hop, sun.','TVO Learn: Grade 1 Language',L1,[('Which word has the short A sound?',['Cake','Cat','Cape','Cane'],1),('Which word has the short E sound?',['Bead','Beat','Bed','Bean'],2),('Which word has the short I sound?',['Kite','Bike','Fine','Pig'],3),('Which word has the short O sound?',['Coat','Note','Hop','Hope'],2),('Which word has the short U sound?',['Cube','Mule','Fun','Tune'],2)]),
sub('Math','Counting to 20','Ontario Grade 1 Number strand: students count forward and backward by 1s within 20 and represent quantities using objects and numerals.','TVO Learn: Grade 1 Mathematics',M1,[('What number comes after 15?',['14','16','17','13'],1),('What number is one less than 10?',['9','11','8','12'],0),('Count: 17, 18, 19, ___',['20','21','22','18'],0),('Which number is between 12 and 14?',['11','15','13','10'],2),('How many fingers on two hands?',['8','9','10','11'],2)]),
sub('Science','Living and Non-living Things','Ontario Grade 1 Life Systems strand: living things grow, reproduce, and respond to their environment; non-living things do not.','TVO Learn: Grade 1 Science & Technology',S1,[('Which of these is a living thing?',['Rock','Chair','Tree','Table'],2),('Which is NOT a living thing?',['Bird','Flower','Dog','Brick'],3),('Living things need food and ___.',['Electricity','Television','Water','Money'],2),('Which is a sign that something is alive?',['It is heavy','It grows and changes','It is hard','It is coloured'],1),('A plant is a living thing because it ___.',['Is made of wood','Grows and makes seeds','Is green','Cannot move'],1)]),
sub('SocialStudies','My Family','Ontario Grade 1 Social Studies Heritage and Identity strand: students describe their family and recognize that families differ in structure and traditions.','TVO Learn: Grade 1 Social Studies',SS1,[('A family is a group of people who ___.',['Work at the same job','Live on the same street','Care for each other','All look the same'],2),('Which of these is a family member?',['Teacher','Parent','Neighbour','Friend'],1),('Families can be ___.',['Only large','Only small','Many different sizes','Always the same'],2),('What do most families do together?',['Ignore each other','Share meals and celebrate','Work the same job','Go to the same school'],1),('Every family is ___.',['Exactly the same','Unique and special','Always big','Always small'],1)])]),
day(2,[sub('Language','Long Vowel Sounds','Ontario Grade 1 Reading strand: long vowels say their name, as in cake, bee, kite, boat, cube. The silent E rule often signals a long vowel.','TVO Learn: Grade 1 Language',L1,[('Which word has a long A sound?',['Cat','Cab','Cake','Cap'],2),('Which word has a long E sound?',['Bed','Bed','Bee','Bet'],2),('Which word has a long O sound?',['Hop','Hot','Hog','Hope'],3),('What makes the vowel long in the word KITE?',['Two vowels together','Silent E at the end','Consonant blend','Capital letter'],1),('Which word has a long U sound?',['Cup','Cut','Cub','Cube'],3)]),
sub('Math','Numbers to 50','Ontario Grade 1 Number strand: students count, read, write, and represent whole numbers to 50, and describe their positions on a number line.','TVO Learn: Grade 1 Mathematics',M1,[('What number comes after 39?',['38','40','41','37'],1),('Which is greater: 27 or 32?',['27','32','Equal','Cannot tell'],1),('What is 10 more than 24?',['14','25','34','44'],2),('Which number is between 15 and 20?',['14','21','17','25'],2),('Count by 1s: 45, 46, 47, ___',['48','49','44','50'],0)]),
sub('Science','Seasonal Changes: Fall','Ontario Grade 1 Earth and Space Systems strand: in fall, days shorten, leaves change colour and drop, and animals prepare for winter.','TVO Learn: Grade 1 Science & Technology',S1,[('In fall, leaves on deciduous trees ___.',['Stay green','Turn colour and fall off','Grow bigger','Turn white'],1),('Fall days are ___ than summer days.',['Longer','The same length','Shorter','Hotter'],2),('Which month is typically fall in Ontario?',['July','October','March','May'],1),('What do many animals do to prepare for winter?',['Grow wings','Go swimming','Gather food or migrate','Turn red'],2),('Fall comes after which season?',['Spring','Winter','Summer','Rainy season'],2)]),
sub('SocialStudies','My School Community','Ontario Grade 1 Social Studies strand: students identify school community members and their roles, and describe how everyone contributes.','TVO Learn: Grade 1 Social Studies',SS1,[('Who is usually the leader of a whole school?',['A student','The principal','A teacher','A librarian'],1),('What is a teacher\'s main job?',['Cook lunch','Help students learn','Fix the building','Drive the bus'],1),('How can students help their school community?',['Being noisy','Picking up litter and helping others','Staying home','Ignoring rules'],1),('What does a librarian do?',['Fix computers','Cook lunch','Help students find books','Drive buses'],2),('Why do schools have rules?',['To be unfair','To keep everyone safe and learning','To punish students','Just because adults say so'],1)])]),
day(3,[sub('Language','Consonant Blends: bl, cl, fl, pl','Ontario Grade 1 Reading strand: consonant blends are two or more consonants together where each sound is heard, such as bl in black and cl in clap.','TVO Learn: Grade 1 Language',L1,[('Which word starts with the BL blend?',['Clock','Floor','Black','Play'],2),('Which word starts with the CL blend?',['Blue','Clap','Floor','Plane'],1),('Which word starts with the FL blend?',['Play','Clock','Blue','Flag'],3),('Which word starts with the PL blend?',['Black','Floor','Plant','Clock'],2),('A consonant blend means ___.',['A single letter','Two consonants you hear separately','Only vowels','Silent letters'],1)]),
sub('Math','Addition to 10','Ontario Grade 1 Number strand: students add two one-digit numbers with sums to 10 using objects, drawings, and number lines.','TVO Learn: Grade 1 Mathematics',M1,[('3 + 4 = ?',['6','7','8','5'],1),('5 + 5 = ?',['9','10','11','8'],1),('2 + 6 = ?',['7','8','9','6'],1),('1 + 9 = ?',['9','10','11','8'],1),('4 + 3 = ?',['6','7','8','5'],1)]),
sub('Science','Materials: Solid, Liquid, Gas','Ontario Grade 1 Matter and Materials strand: students identify the three states of matter by exploring everyday examples of solids, liquids, and gases.','TVO Learn: Grade 1 Science & Technology',S1,[('Which state of matter has a definite shape?',['Liquid','Gas','Solid','Steam'],2),('Water is an example of a ___.',['Solid','Liquid','Gas','Rock'],1),('Which state of matter fills its entire container?',['Solid','Liquid','Gas','Ice'],2),('Ice is water in a ___ state.',['Liquid','Gas','Solid','Hot'],2),('Steam is water in a ___ state.',['Solid','Liquid','Gas','Cold'],2)]),
sub('SocialStudies','Maps and Directions','Ontario Grade 1 Social Studies strand B: students use directional language and simple maps to describe locations in familiar places.','TVO Learn: Grade 1 Social Studies',SS1,[('A map is a ___.',['Photo from space','Drawing of a real place from above','Painting of nature','Written story'],1),('If you face north, south is ___.',['Behind you','To your left','To your right','Above you'],0),('Which direction does the sun rise?',['West','North','East','South'],2),('On most maps, north is at the ___.',['Bottom','Left','Top','Right'],2),('What do we call a map of the whole world?',['A globe or world map','A street map','A treasure map','A floor plan'],0)])]),
day(4,[sub('Language','Sight Words','Ontario Grade 1 Reading strand: students recognize high-frequency Dolch sight words automatically, supporting reading fluency. Examples: the, and, a, to, said, is, you, in, was.','TVO Learn: Grade 1 Language',L1,[('Which of these is a common sight word?',['Elephant','the','xylophone','umbrella'],1),('Why do we practise sight words?',['They are long words','We see them very often in reading','They are nouns only','They are hard to spell'],1),('Which is spelled correctly?',['Teh','Thuh','The','Tha'],2),('Sight words help us ___.',['Spell big words','Read more quickly and fluently','Learn maths','Do science'],1),('Which is NOT a typical sight word?',['and','the','is','rhinoceros'],3)]),
sub('Math','Subtraction from 10','Ontario Grade 1 Number strand: students subtract one-digit numbers from numbers up to 10 using objects, drawings, and number lines.','TVO Learn: Grade 1 Mathematics',M1,[('10 - 3 = ?',['6','7','8','5'],1),('8 - 4 = ?',['3','4','5','6'],1),('7 - 2 = ?',['4','5','6','3'],1),('9 - 5 = ?',['3','4','5','6'],1),('6 - 6 = ?',['0','1','2','3'],0)]),
sub('Science','Needs of Living Things','Ontario Grade 1 Life Systems strand: all living things need air, water, food, and shelter. Plants also need sunlight to make food through photosynthesis.','TVO Learn: Grade 1 Science & Technology',S1,[('Which is NOT a basic need of living things?',['Water','Food','Television','Air'],2),('Plants use sunlight to make their own ___.',['Soil','Food','Water','Shelter'],1),('Animals need shelter to ___.',['Go to school','Be protected from weather and predators','Play sports','Find water'],1),('What do living things need to breathe?',['Water','Air','Food','Sunlight'],1),('Which is a basic need ALL living things share?',['Transportation','Water','Money','Television'],1)]),
sub('SocialStudies','Community Workers','Ontario Grade 1 Social Studies strand B: students identify community workers and explain how their work benefits everyone in the community.','TVO Learn: Grade 1 Social Studies',SS1,[('Who builds houses and buildings?',['A teacher','A construction worker','A doctor','A chef'],1),('What does a bus driver do?',['Teach students','Carry passengers from place to place','Fix roads','Cook food'],1),('Where does a chef work?',['A school','A hospital','A kitchen or restaurant','A store'],2),('Why do communities need workers with many different jobs?',['They do not','Different jobs meet different community needs','Only doctors are needed','Only teachers are needed'],1),('Who repairs broken water pipes?',['A teacher','A pilot','A plumber','A baker'],2)])]),
day(5,[sub('Language','Word Families: -at and -an','Ontario Grade 1 Reading strand: word families share the same rime (ending pattern). The -at family includes cat, bat, hat, sat; the -an family includes can, man, ran, tan.','TVO Learn: Grade 1 Language',L1,[('Which word belongs to the -AT family?',['Can','Run','Hat','Men'],2),('Which word belongs to the -AN family?',['Cat','Bat','Hat','Can'],3),('How many words are in the -AT family: cat, bat, hat, sat?',['2','3','4','5'],2),('Which word rhymes with CAN?',['Cat','Hat','Ran','Bit'],2),('Word families help us ___.',['Count numbers','Recognize spelling patterns and read new words','Draw pictures','Do experiments'],1)]),
sub('Math','Place Value: Tens and Ones','Ontario Grade 1 Number strand: students decompose two-digit numbers into tens and ones using base-ten blocks, understanding that the position of a digit determines its value.','TVO Learn: Grade 1 Mathematics',M1,[('In the number 23, the digit 2 means ___.',['2 ones','20 tens','2 tens','20 ones'],2),('How many tens are in 35?',['3','5','35','2'],0),('How many ones are in 47?',['4','7','47','11'],1),('What is 3 tens and 4 ones?',['43','34','30','4'],1),('In the number 16, the 6 means ___.',['6 tens','6 ones','16 ones','1 ten'],1)]),
sub('Science','Seasonal Changes: Winter','Ontario Grade 1 Earth and Space Systems strand: in winter, temperatures drop, many trees are bare, some animals hibernate, and people wear warm clothing.','TVO Learn: Grade 1 Science & Technology',S1,[('What season comes after fall?',['Spring','Summer','Winter','Rainy season'],2),('In winter, many deciduous trees ___.',['Grow new leaves','Have bare branches','Grow taller','Turn green'],1),('What do bears do in winter?',['Fly south','Swim in rivers','Hibernate','Grow bigger'],2),('In Ontario, winter weather is usually ___.',['Hot and dry','Warm and rainy','Cold with snow and ice','Always sunny'],2),('Days in winter are ___ than in summer.',['Longer','The same','Shorter','Always sunny'],2)]),
sub('SocialStudies','Rules and Responsibilities','Ontario Grade 1 Social Studies strand A: students describe their rights and responsibilities at home, at school, and in the community.','TVO Learn: Grade 1 Social Studies',SS1,[('Why do schools have rules?',['To be unfair','To keep everyone safe and learning','To punish students','Rules are not needed'],1),('A responsibility is something you ___.',['Are allowed to ignore','Must do for yourself or others','Can always skip','Only adults do'],1),('Which is a student responsibility at school?',['Talking over the teacher','Completing work and respecting others','Playing all day','Ignoring homework'],1),('Rights and responsibilities work together because ___.',['They are the same thing','Rights give us freedom; responsibilities ensure we respect others','Only rights matter','Only responsibilities matter'],1),('Which is an example of a right?',['Working all day','Being treated fairly and kept safe','Having no rules','Ignoring others'],1)])]),
day(6,[sub('Language','Writing Complete Sentences','Ontario Grade 1 Writing strand: a complete sentence has a subject and a verb, begins with a capital letter, and ends with a punctuation mark.','TVO Learn: Grade 1 Language',L1,[('Every sentence must start with a ___.',['lowercase letter','Period','Capital letter','Number'],2),('Which is a complete sentence?',['the dog','Runs fast.','The dog runs fast.','Fast dog.'],2),('A sentence that asks a question ends with a ___.',['Period','Exclamation mark','Question mark','Comma'],2),('Which sentence has correct punctuation?',['the cat is big','The cat is big.','the cat is big.','The cat is big'],1),('A sentence needs a subject (who) and a ___ (action).','',0)]),
sub('Math','Skip Counting by 2s','Ontario Grade 1 Number strand: students skip count by 2s from 0, landing on even numbers: 0, 2, 4, 6, 8, 10...','TVO Learn: Grade 1 Mathematics',M1,[('Skip count by 2s: 2, 4, 6, ___',['5','7','8','9'],2),('Skip count by 2s: 10, 12, 14, ___',['15','16','17','13'],1),('Which numbers do you land on when skip counting by 2s?',['Odd numbers','Even numbers','All numbers','Random numbers'],1),('Skip count by 2s from 0: 0, 2, 4, 6, 8, ___',['9','10','11','12'],1),('Skip counting by 2s helps us count ___ faster.',['Odd numbers','By tens','Pairs or groups of 2','By fives'],2)]),
sub('Science','Animals and Their Young','Ontario Grade 1 Life Systems strand: animals reproduce and care for their young; baby animals resemble their parents and grow to look like them.','TVO Learn: Grade 1 Science & Technology',S1,[('A baby dog is called a ___.',['Kitten','Calf','Puppy','Foal'],2),('A baby cat is called a ___.',['Puppy','Kitten','Cub','Lamb'],1),('Baby animals grow up to look like their ___.',['Owners','Parents','Teachers','Friends'],1),('Why do parent animals care for their young?',['For fun','To keep them safe until they can survive','They do not care','Because they are paid'],1),('Which baby animal hatches from an egg?',['Puppy','Kitten','Duckling','Lamb'],2)]),
sub('SocialStudies','Our Province: Ontario','Ontario Grade 1 Social Studies strand B: students identify Ontario on a map of Canada, name its capital city, and describe some key features.','TVO Learn: Grade 1 Social Studies',SS1,[('What is the capital city of Ontario?',['Ottawa','Toronto','Vancouver','Montreal'],1),('Ontario is located in ___.',['Far west Canada','Far north','East-central Canada','The far east'],2),('What large bodies of water border southern Ontario?',['The Atlantic Ocean','The Pacific Ocean','The Great Lakes','The Arctic Ocean'],2),('Ontario\'s provincial flower is the ___.',['Rose','Trillium','Tulip','Sunflower'],1),('Which city is the largest in Ontario?',['Ottawa','Hamilton','Toronto','London'],2)])]),
day(7,[sub('Language','Question Words: Who, What, Where, When, Why','Ontario Grade 1 Reading and Writing strands: students identify and use the five W question words to gather information from texts and to formulate questions.','TVO Learn: Grade 1 Language',L1,[('Which question word asks about a person?',['What','Where','Who','When'],2),('Which question word asks about a place?',['Who','What','When','Where'],3),('Which question word asks about a time?',['Who','Where','When','Why'],2),('Which question word asks for a reason?',['What','Where','Who','Why'],3),('What question word asks about an object or event?',['Who','What','Where','When'],1)]),
sub('Math','Skip Counting by 5s','Ontario Grade 1 Number strand: students skip count by 5s from 0, recognising the pattern: 0, 5, 10, 15, 20...','TVO Learn: Grade 1 Mathematics',M1,[('Skip count by 5s: 5, 10, 15, ___',['18','20','19','17'],1),('Skip count by 5s: 20, 25, 30, ___',['32','35','33','38'],1),('How many 5s make 25?',['3','4','5','6'],2),('Skip counting by 5s is like counting ___.',['By ones','By twos','By fives','By tens'],2),('5, 10, 15, 20 — what comes next?',['21','22','25','30'],2)]),
sub('Science','Parts of a Plant','Ontario Grade 1 Life Systems strand: students identify and describe the functions of the main parts of a plant: roots, stem, leaves, and flower.','TVO Learn: Grade 1 Science & Technology',S1,[('Which part of a plant is usually underground?',['Leaves','Flower','Stem','Roots'],3),('What do roots do?',['Make food from sunlight','Attract bees','Anchor the plant and absorb water','Make flowers'],2),('Which part carries water from the roots upward?',['Leaf','Flower','Stem','Seed'],2),('Leaves make food for the plant using ___.',['Rain and soil only','Sunlight, water, and air','Roots and flowers','Heat and wind'],1),('What does the flower help the plant make?',['More leaves','Seeds','Bigger roots','Stems'],1)]),
sub('SocialStudies','Canadian Symbols','Ontario Grade 1 Social Studies strand B: students identify major Canadian symbols including the maple leaf, beaver, flag, and national anthem.','TVO Learn: Grade 1 Social Studies',SS1,[('What animal is a symbol of Canada?',['Eagle','Beaver','Bear','Moose'],1),('What is the main symbol on the Canadian flag?',['A star','A bear','A maple leaf','A sun'],2),('What are the two official colours of the Canadian flag?',['Blue and white','Red and white','Green and gold','Red and blue'],1),('What is Canada\'s national anthem?',['God Save the King','O Canada','The Maple Leaf Forever','True North'],1),('The maple leaf represents ___.',['The United States','The beaver','Canada','The queen'],2)])]),
day(8,[sub('Language','Punctuation: Period, Question Mark, Exclamation Mark','Ontario Grade 1 Writing strand: students use end punctuation correctly — period for statements, question mark for questions, and exclamation mark for strong emotion.','TVO Learn: Grade 1 Language',L1,[('Which punctuation ends a statement?',['?','!','.','...'],2),('Which punctuation ends a question?',['.',',','?','!'],2),('Which punctuation shows excitement or strong feeling?',['.',',','?','!'],3),('The cat is big ___.',['?','!','.','...'],2),('Is the cat big ___?',['.',',','?','!'],2)]),
sub('Math','Skip Counting by 10s','Ontario Grade 1 Number strand: students skip count by 10s from 0, recognising the pattern: 0, 10, 20, 30, 40, 50.','TVO Learn: Grade 1 Mathematics',M1,[('Skip count by 10s: 10, 20, 30, ___',['35','40','45','50'],1),('Skip count by 10s: 50, 60, 70, ___',['75','80','85','90'],1),('How many 10s make 40?',['2','3','4','5'],2),('10, 20, 30, 40 — what comes next?',['41','42','50','60'],2),('Skip counting by 10s is the same as counting ___.',['by ones','by fives','groups of 10','groups of 2'],2)]),
sub('Science','Seeds and How Plants Grow','Ontario Grade 1 Life Systems strand: students investigate how seeds germinate and grow into plants when given water, warmth, air, and light.','TVO Learn: Grade 1 Science & Technology',S1,[('What do seeds need to germinate (sprout)?',['Ice and darkness','Water, warmth, and air','Only sunlight','Only soil'],1),('What is germination?',['When a plant dies','When a seed starts to grow into a plant','When leaves fall off','When flowers bloom'],1),('Where do seeds come from?',['Rocks','Flowers and fruit of plants','The sky','Water'],1),('As a seed grows it first produces a ___.',['Flower','Fruit','Tiny shoot and root','Large tree'],2),('Which is the correct order: seed, ___, plant?',['Leaf','Root only','Seedling','Flower'],2)]),
sub('SocialStudies','Indigenous Peoples of Canada','Ontario Grade 1 Social Studies strand A: students learn that Indigenous peoples were the first peoples of Canada and have rich cultures, languages, and traditions.','TVO Learn: Grade 1 Social Studies',SS1,[('Who were the first peoples of Canada?',['European settlers','Indigenous peoples','American visitors','Recent immigrants'],1),('Indigenous peoples have lived in Canada for ___.',['A few years','About 200 years','Thousands of years','50 years'],2),('Indigenous peoples have their own ___.',['Nothing special','Languages and traditions','European customs only','Modern technology only'],1),('We should respect Indigenous cultures because ___.',['They are far away','They are part of Canada\'s history and identity','It does not matter','They are strangers'],1),('What do we call the different groups of First Nations peoples?',['All the same group','Nations, each with their own culture','European groups','American groups'],1)])]),
day(9,[sub('Language','Retelling a Story','Ontario Grade 1 Reading strand: students retell stories in sequence using the language of beginning, middle, and end, and story elements: characters, setting, problem, solution.','TVO Learn: Grade 1 Language',L1,[('The beginning of a story tells us ___.',['How it ends','Who the characters are and the setting','The solution','A lesson only'],1),('The middle of a story contains the ___.',['Happy ending','Problem or challenge','Introduction of characters only','Title'],1),('The end of a story shows the ___.',['New characters','Beginning again','Solution to the problem','First event'],2),('Characters are ___.',['The place where the story happens','The people or animals in the story','The problem only','The ending'],1),('Setting means ___.',['The character\'s name','Where and when the story takes place','The problem','The solution'],1)]),
sub('Math','2D Shapes','Ontario Grade 1 Geometry strand: students identify and describe properties of 2D shapes: circle, square, rectangle, and triangle.','TVO Learn: Grade 1 Mathematics',M1,[('How many sides does a triangle have?',['2','3','4','5'],1),('How many corners does a square have?',['3','4','5','6'],1),('Which 2D shape has no corners?',['Triangle','Square','Circle','Rectangle'],2),('How many sides does a rectangle have?',['3','4','5','6'],1),('Which shape has four equal sides?',['Rectangle','Triangle','Circle','Square'],3)]),
sub('Science','Pushes and Pulls','Ontario Grade 1 Science Physical Education strand: a force is a push or pull that can move, stop, or change the direction of an object.','TVO Learn: Grade 1 Science & Technology',S1,[('A push moves an object ___.',['Toward you','Away from you','Up only','Down only'],1),('A pull moves an object ___.',['Away from you','Toward you','To the side only','Upward'],1),('Which is an example of a push?',['Opening a drawer','Reeling in a fish','Kicking a ball','Pulling a cart'],2),('Forces can change the ___ of a moving object.',['Colour','Speed or direction','Smell','Temperature'],1),('Which is an example of a pull?',['Kicking a ball','Pushing a door open','Opening a drawer','Throwing a ball'],2)]),
sub('SocialStudies','Families Around the World','Ontario Grade 1 Social Studies strand A: students learn that families around the world share common needs but meet them in different ways through their cultures.','TVO Learn: Grade 1 Social Studies',SS1,[('Families around the world all need ___.',['The same food','The same clothing','Food, shelter, and love','Electricity'],2),('Different families may speak ___.',['Only English','Only French','Many different languages','The same language always'],2),('Learning about other cultures helps us ___.',['Ignore differences','Understand and respect each other','Copy everyone','Stay separate'],1),('All families celebrate ___.',['The same holidays','Nothing','Important events in their own way','Only Christmas'],2),('What do all families around the world have in common?',['They look the same','Members care for each other','They live the same way','They all have the same rules'],1)])]),
day(10,[sub('Language','Main Idea','Ontario Grade 1 Reading strand: the main idea is what a text is mostly about. Supporting details give more information about the main idea.','TVO Learn: Grade 1 Language',L1,[('The main idea of a text is ___.',['A small detail','What the text is mostly about','The last sentence','A character\'s name'],1),('Supporting details ___.',['Are the most important idea','Explain the main idea with examples','Are not connected to the main idea','Are always at the beginning'],1),('A good title for a text about dogs would be ___.',['Cats are Great','All About Dogs','My Birthday','The Red Ball'],1),('How do you find the main idea?',['Read only the last sentence','Ask yourself what the text is mostly about','Count the words','Look at the pictures only'],1),('Which sentence is a main idea?',['The dog has brown spots.','Dogs make wonderful pets for many reasons.','The dog ran fast.','My dog is named Rex.'],1)]),
sub('Math','3D Shapes','Ontario Grade 1 Geometry strand: students identify and describe 3D figures: sphere, cube, cylinder, and cone, relating them to everyday objects.','TVO Learn: Grade 1 Mathematics',M1,[('Which 3D shape looks like a ball?',['Cube','Cylinder','Sphere','Cone'],2),('Which 3D shape looks like a box?',['Sphere','Cylinder','Cone','Cube'],3),('Which 3D shape looks like a soup can?',['Sphere','Cylinder','Cube','Cone'],1),('A cone has ___ flat face(s).',['0','1','2','3'],1),('A cube has how many faces?',['4','5','6','8'],2)]),
sub('Science','Sound and Hearing','Ontario Grade 1 Science strand: sounds are made by vibrations. The ear detects sound waves, and sounds can be loud or soft, high-pitched or low-pitched.','TVO Learn: Grade 1 Science & Technology',S1,[('Sounds are made by ___.',['Light','Vibrations','Heat','Gravity'],1),('Which body part do we use to hear?',['Eyes','Nose','Ears','Hands'],2),('A loud sound has ___ vibrations than a soft sound.',['Fewer','Smaller','Larger or stronger','Slower'],2),('Which makes a high-pitched sound?',['A bass drum','A tuba','A whistle','A cow'],2),('Covering your ears reduces sound because ___.',['Sound stops completely','Less sound reaches your eardrums','Your hearing improves','Vibrations increase'],1)]),
sub('SocialStudies','Being a Good Citizen','Ontario Grade 1 Social Studies strand A: students describe what it means to be a responsible and caring member of their school and community.','TVO Learn: Grade 1 Social Studies',SS1,[('A good citizen ___.',['Takes others\' things','Helps others and follows rules','Is always noisy','Litters'],1),('What does it mean to be responsible?',['Doing whatever you want','Taking care of your duties','Being unkind','Ignoring others'],1),('Why is it important to be kind to others?',['It is not important','It makes the community happy and safe','It is only for adults','Only teachers need to be kind'],1),('Being a good citizen at school means ___.',['Talking during lessons','Sharing, listening, and helping others','Pushing in line','Breaking rules'],1),('Good citizens follow rules because ___.',['Rules are boring','Rules keep everyone safe and happy','Only some people follow rules','Teachers created them'],1)])]),
day(11,[sub('Language','Characters and Setting','Ontario Grade 1 Reading strand: characters are the people or animals in a story; setting is where and when the story takes place.','TVO Learn: Grade 1 Language',L1,[('Characters are ___.',['The place of the story','The people or animals in the story','The ending','The problem'],1),('Setting means ___.',['What happens in the story','Who is in the story','Where and when the story takes place','The solution'],2),('Which question helps identify the setting?',['Who is in the story?','What is the problem?','Where and when does the story happen?','How does it end?'],2),('A character\'s traits describe ___.',['Where the story happens','What the character is like (brave, funny, etc.)','The problem','The solution'],1),('Can a story have more than one character?',['No, only one character','Yes, stories can have many characters','Only in long stories','Only in fairy tales'],1)]),
sub('Math','Measuring Length','Ontario Grade 1 Measurement strand: students measure length using non-standard units (paperclips, cubes) and compare objects using longer, shorter, taller.','TVO Learn: Grade 1 Mathematics',M1,[('Which unit is NOT a standard unit of measurement?',['Centimetre','Metre','Paperclip','Kilometre'],2),('If a pencil is 8 cubes long and a crayon is 5 cubes long, which is longer?',['Crayon','Pencil','Equal','Cannot tell'],1),('Taller means ___.',['Shorter in height','Greater in height','The same height','Heavier'],1),('We measure length to find out ___.',['How heavy something is','How long or tall something is','What colour it is','How many there are'],1),('Which tool measures length in centimetres?',['Scale','Ruler','Thermometer','Clock'],1)]),
sub('Science','Light','Ontario Grade 1 Science strand: light travels in a straight line, can reflect off surfaces, and allows us to see. The sun is the main natural source of light on Earth.','TVO Learn: Grade 1 Science & Technology',S1,[('What is the main natural source of light on Earth?',['The moon','A lamp','The sun','Stars'],2),('Light travels in a ___.',['Curve','Circle','Straight line','Zigzag'],2),('Which of these is a source of light?',['A rock','A book','A light bulb','A chair'],2),('When light hits a mirror it ___.',['Disappears','Is absorbed','Bounces back (reflects)','Turns to heat'],2),('We need light to ___.',['Hear sounds','See objects','Smell things','Taste food'],1)]),
sub('SocialStudies','Rights of Children','Ontario Grade 1 Social Studies strand A: students identify children\'s rights as outlined by the United Nations Convention on the Rights of the Child (UNCRC).','TVO Learn: Grade 1 Social Studies',SS1,[('Children have the right to ___.',['Do whatever they want','Be safe, cared for, and educated','Ignore school rules','Have no responsibilities'],1),('What is the UNCRC?',['A type of book','A United Nations document protecting children\'s rights worldwide','A school subject','A type of toy'],1),('Which of these is a child\'s right?',['Working full-time jobs','Education and protection from harm','Having no rules','Ignoring adults'],1),('Rights and responsibilities go together because ___.',['They are opposite','Our rights give us freedom; responsibilities ensure we respect others\' rights','Only rights matter','Only adults have rights'],1),('Who is responsible for protecting children\'s rights?',['No one','Children themselves','Governments, communities, and families','Only schools'],2)])]),
day(12,[sub('Language','Making Predictions','Ontario Grade 1 Reading strand: students use text clues, pictures, and prior knowledge to predict what will happen next in a story or text.','TVO Learn: Grade 1 Language',L1,[('Making a prediction means ___.',['Guessing what might happen next using clues','Reading the end first','Looking at pictures only','Counting words'],0),('What clues help you make a prediction?',['Random guessing','Title, pictures, and what you have read so far','Only the last page','The font size'],1),('If dark clouds appear in a story, you might predict ___.',['It will get hotter','It will rain or storm','The story is ending','A character will laugh'],1),('After making a prediction, a good reader ___.',['Ignores whether it was right','Reads on to check the prediction','Stops reading','Changes the story'],1),('Predictions can be ___.',['Always correct','Always wrong','Sometimes right and sometimes wrong, and that is okay','Only for science'],2)]),
sub('Math','Measuring Mass','Ontario Grade 1 Measurement strand: students compare the mass of objects using non-standard units and a balance scale, using language like heavier and lighter.','TVO Learn: Grade 1 Mathematics',M1,[('Which object is likely heavier: a book or a feather?',['Feather','Book','They are equal','Cannot tell'],1),('A balance scale tips toward ___.',['The lighter object','The heavier object','Neither side','The centre'],1),('Mass measures ___.',['How long something is','How heavy something is','How tall something is','How hot something is'],1),('Which unit is used to measure mass in science?',['Centimetres','Litres','Kilograms or grams','Degrees'],2),('If one side of a balance is heavier, the other side ___.',['Goes down','Goes up','Stays level','Disappears'],1)]),
sub('Science','Magnetism','Ontario Grade 1 Science strand: magnets attract certain metals (iron, steel, nickel). They have north and south poles; like poles repel, opposite poles attract.','TVO Learn: Grade 1 Science & Technology',S1,[('What does a magnet attract?',['All metals','Certain metals like iron and steel','Plastic','Wood'],1),('A magnet has two ___.',['Colours','Sizes','Poles (north and south)','Faces'],2),('When two north poles of magnets face each other they ___.',['Attract','Repel (push apart)','Stick together','Do nothing'],1),('Which of these would a magnet pick up?',['A wooden block','A plastic cup','A paper clip','An eraser'],2),('Opposite poles of a magnet ___.',['Repel each other','Do nothing','Attract each other','Break apart'],2)]),
sub('SocialStudies','Community Helpers','Ontario Grade 1 Social Studies strand B: students describe the roles of community helpers including firefighters, police, medical workers, and educators.','TVO Learn: Grade 1 Social Studies',SS1,[('Who helps put out fires?',['A teacher','A firefighter','A doctor','A librarian'],1),('Who keeps the neighbourhood safe?',['A baker','A police officer','A dentist','A librarian'],1),('Who helps us when we are sick?',['A firefighter','A police officer','A teacher','A doctor or nurse'],3),('What do all community helpers have in common?',['They all wear red','They all drive trucks','They help people in the community','They all work at schools'],2),('How can you show respect to community helpers?',['Ignore them','Thank them and follow their instructions','Argue with them','Avoid them'],1)])]),
day(13,[sub('Language','Cause and Effect','Ontario Grade 1 Reading strand: cause is why something happens; effect is what happens as a result. Signal words include because, so, and as a result.','TVO Learn: Grade 1 Language',L1,[('The cause is ___.',['What happens','Why something happens','When it happens','Who does it'],1),('The effect is ___.',['Why something happens','What happens as a result','Where it happens','Who does it'],1),('Which signal word often introduces a cause?',['Then','Finally','Because','Next'],2),('It rained, so the grass got wet. What is the effect?',['It rained','The rain fell hard','The grass got wet','The sun came out'],2),('She studied hard, so she did well on the test. What is the cause?',['She did well on the test','She studied hard','The test was easy','The teacher helped'],1)]),
sub('Math','Fractions: Halves','Ontario Grade 1 Number strand: students divide shapes and sets into two equal parts, using the language of halves and one-half.','TVO Learn: Grade 1 Mathematics',M1,[('A half means dividing something into ___ equal parts.',['1','2','3','4'],1),('Which shows a half of a circle?',['3/4 of a circle','A whole circle','2 equal semicircles','1 quarter'],2),('If you cut a sandwich into halves, how many pieces do you have?',['1','2','3','4'],1),('One-half is written as ___.',['1/3','1/4','1/2','2/1'],2),('If you eat one half of a pizza, what fraction is left?',['1/3','1/4','1/2','2/3'],2)]),
sub('Science','Weather Patterns','Ontario Grade 1 Earth and Space Systems strand: students observe and record daily weather conditions including temperature, precipitation, and cloud cover, identifying patterns over time.','TVO Learn: Grade 1 Science & Technology',S1,[('Which tool measures air temperature?',['Ruler','Thermometer','Scale','Clock'],1),('What type of precipitation falls as solid flakes?',['Rain','Hail','Sleet','Snow'],3),('Cloudy weather means ___.',['No clouds in the sky','The sky is covered with clouds','It is raining heavily','The sun is very bright'],1),('Weather patterns help us ___.',['Pick favourite colours','Plan clothing and activities','Choose what to eat','Watch television'],1),('What instrument measures rainfall?',['Thermometer','Rain gauge','Barometer','Wind vane'],1)]),
sub('SocialStudies','Land and Water in Canada','Ontario Grade 1 Social Studies strand B: students identify landforms and bodies of water in Canada including lakes, rivers, mountains, and plains.','TVO Learn: Grade 1 Social Studies',SS1,[('Which of these is a body of water?',['Mountain','Prairie','Lake Superior','Forest'],2),('Which is a landform?',['Lake Ontario','Atlantic Ocean','Rocky Mountain','St. Lawrence River'],2),('What are the Great Lakes?',['Five large lakes in central Canada and the US','Mountains in western Canada','Prairies in central Canada','Glaciers in the north'],0),('Canada has ___ coastlines.',['One — the east','Three — east, west, and north','Only in the south','No coastline'],1),('The Canadian Shield is ___.',['A large ocean','A great river','A vast region of ancient rock in central Canada','A mountain range'],2)])]),
day(14,[sub('Language','Describing Words: Adjectives','Ontario Grade 1 Writing strand: adjectives are describing words that tell us more about a noun — they describe colour, size, shape, number, and feeling.','TVO Learn: Grade 1 Language',L1,[('An adjective is a ___.',['Naming word','Action word','Describing word','Connecting word'],2),('Which word is an adjective in: The big dog ran?',['The','Big','Dog','Ran'],1),('Which word is an adjective?',['Jump','Happy','Dog','Run'],1),('Which sentence has an adjective?',['The dog ran.','She ran fast.','The tiny cat sat.','He jumped.'],2),('Adjectives help us ___.',['Name things','Show actions','Describe things more clearly','Connect sentences'],2)]),
sub('Math','Data: Tally Charts','Ontario Grade 1 Data strand: students collect and organise data using tally marks, where each mark represents one item and a bundle of five is shown with a diagonal line.','TVO Learn: Grade 1 Mathematics',M1,[('One tally mark represents ___.',['5 items','2 items','1 item','10 items'],2),('A group of 5 tally marks looks like ___.',['IIII','Four vertical lines','Four lines crossed by one diagonal line','IIIII'],2),('If you have 7 tally marks, you have ___ items.',['5','6','7','8'],2),('Why do we use tally marks?',['For decoration','To count and record data quickly','To spell words','To draw pictures'],1),('IIII I (5 marks) represents how many?',['4','5','6','7'],1)]),
sub('Science','The Sun','Ontario Grade 1 Earth and Space Systems strand: the Sun is a star, the centre of our solar system, and Earth\'s main source of heat and light. It causes day and night through Earth\'s rotation.','TVO Learn: Grade 1 Science & Technology',S1,[('The Sun is a ___.',['Planet','Moon','Star','Comet'],2),('The Sun gives Earth heat and ___.',['Rain','Light','Wind','Snow'],1),('Day and night are caused by Earth ___.',['Moving around the Sun','Rotating (spinning) on its axis','Moving away from the Sun','The Moon blocking the Sun'],1),('The Sun rises in the ___ and sets in the ___.',['West, east','North, south','East, west','South, north'],2),('Why is the Sun important for life on Earth?',['It is not important','It provides heat and light needed by plants and animals','Only humans need it','Only plants need it'],1)]),
sub('SocialStudies','Canada\'s Natural Resources','Ontario Grade 1 Social Studies strand B: students identify natural resources in Canada such as trees, water, minerals, and farmland and explain why they are important.','TVO Learn: Grade 1 Social Studies',SS1,[('A natural resource is ___.',['Something people make in a factory','Something found in nature that people use','A type of money','A building'],1),('Which of these is a natural resource?',['A plastic bottle','A car','Fresh water','A computer'],2),('Why are Canada\'s forests a natural resource?',['They look nice','They provide wood, paper, and habitat for animals','They are cold','They are very tall'],1),('Which natural resource do farmers use to grow food?',['Rocks','Plastic','Farmland and soil','Metal'],2),('Why is it important to protect natural resources?',['It is not important','So future generations can also use them','Only adults care about this','Resources never run out'],1)])]),
day(15,[sub('Language','Action Words: Verbs','Ontario Grade 1 Writing strand: verbs are action words that tell what a subject does. Every complete sentence needs a verb.','TVO Learn: Grade 1 Language',L1,[('A verb is a ___.',['Naming word','Describing word','Action word','Connecting word'],2),('Which word is a verb: The cat runs fast?',['The','Cat','Runs','Fast'],2),('Which word is a verb?',['Dog','Happy','Jump','Big'],2),('Every complete sentence needs a ___.',['Noun only','Adjective','Verb','Question mark'],2),('Which sentence uses a verb correctly?',['The dog happy.','The big dog.','The dog runs.','Dog the runs.'],2)]),
sub('Math','Data: Pictographs','Ontario Grade 1 Data strand: a pictograph uses pictures or symbols to represent data. A key shows what each symbol means.','TVO Learn: Grade 1 Mathematics',M1,[('In a pictograph, each picture represents ___.',['A word','A number or amount shown in the key','A colour','A shape'],1),('What is the purpose of a key in a pictograph?',['To make it pretty','To explain what each symbol means','To list all students','To show the title'],1),('If each star = 2 votes and there are 3 stars, how many votes are there?',['3','5','6','2'],2),('A pictograph makes data easier to ___.',['Hide','Understand and compare','Ignore','Collect'],1),('Which type of data is best shown in a pictograph?',['Favourite colours of students in a class','The alphabet','How to add numbers','A story'],0)]),
sub('Science','Soil and Earth Materials','Ontario Grade 1 Earth and Space Systems strand: soil is made of rock particles, organic matter, air, and water. Different soils have different properties.','TVO Learn: Grade 1 Science & Technology',S1,[('Soil is made of small pieces of ___ and organic matter.',['Plastic','Metal','Rock','Wood'],2),('Why is soil important for plants?',['It is not','Soil holds the roots and provides nutrients','Soil provides sunlight','Soil provides rain'],1),('Which type of soil holds the most water?',['Sandy soil','Rocky soil','Clay soil','Gravelly soil'],2),('Earthworms help soil by ___.',['Destroying roots','Mixing and aerating the soil','Removing water','Making soil harder'],1),('What is humus?',['A food dip','Decayed organic matter that enriches soil','A type of rock','A type of sand'],1)]),
sub('SocialStudies','Multiculturalism in Canada','Ontario Grade 1 Social Studies strand A: Canada is a multicultural country where people from many backgrounds live and contribute, enriching Canadian society.','TVO Learn: Grade 1 Social Studies',SS1,[('Canada is described as multicultural because ___.',['Everyone speaks the same language','People from many different cultures live here','Only Canadian-born people live here','Everyone follows the same traditions'],1),('How does multiculturalism make Canada stronger?',['It causes problems','It brings different ideas, foods, arts, and perspectives','It does not affect Canada','Only big cities benefit'],1),('Which of Canada\'s two official languages reflects its multicultural roots?',['Spanish and English','French and English','French and Italian','English and Chinese'],1),('How can we celebrate multiculturalism at school?',['Ignore other cultures','Learn about and share different cultural traditions','Speak only one language','Avoid different foods'],1),('What does it mean to respect another culture?',['Copying everything they do','Ignoring their customs','Valuing their traditions and treating them fairly','Avoiding them'],2)])]),
day(16,[sub('Language','Nouns: People, Places, Things','Ontario Grade 1 Writing strand: a noun names a person, place, or thing. Proper nouns name specific people, places, or things and begin with a capital letter.','TVO Learn: Grade 1 Language',L1,[('A noun is a ___.',['Describing word','Action word','Naming word','Connecting word'],2),('Which word is a noun: The dog runs fast?',['The','Dog','Runs','Fast'],1),('Which is a proper noun?',['dog','city','Canada','house'],2),('Proper nouns always start with a ___.',['lowercase letter','Period','Capital letter','Number'],2),('Which of these is a common noun?',['Toronto','Canada','Maria','school'],3)]),
sub('Math','Addition to 20','Ontario Grade 1 Number strand: students add two numbers with sums up to 20 using strategies such as counting on, making tens, and using doubles.','TVO Learn: Grade 1 Mathematics',M1,[('7 + 6 = ?',['12','13','14','11'],1),('9 + 9 = ?',['16','17','18','19'],2),('5 + 8 = ?',['13','12','14','15'],0),('11 + 4 = ?',['14','15','16','13'],1),('6 + 7 = ?',['12','13','14','11'],1)]),
sub('Science','Food Chains','Ontario Grade 1 Life Systems strand: a food chain shows how energy passes from one living thing to another. It starts with a plant (producer), then a herbivore (consumer), then a carnivore.','TVO Learn: Grade 1 Science & Technology',S1,[('In a food chain, plants are called ___.',['Consumers','Herbivores','Producers','Carnivores'],2),('An animal that eats only plants is called a ___.',['Carnivore','Omnivore','Herbivore','Producer'],2),('In a food chain, arrows show ___.',['Friendship','The direction energy flows','Where animals live','The seasons'],1),('Which is a correct simple food chain?',['Fox eats grass eats rabbit','Grass is eaten by rabbit, rabbit is eaten by fox','Sun eats grass eats fox','Fox eats sun eats rabbit'],1),('A carnivore is an animal that eats ___.',['Only plants','Only animals','Both plants and animals','Only grass'],1)]),
sub('SocialStudies','Global Communities','Ontario Grade 1 Social Studies strand B: students compare communities around the world, identifying similarities and differences in how people meet their basic needs.','TVO Learn: Grade 1 Social Studies',SS1,[('Communities around the world are ___.',['Exactly the same','All different with nothing in common','Different in some ways and similar in others','Only similar'],2),('What basic need do all communities around the world share?',['The same language','The same food','Food, shelter, and water','Electricity'],2),('How do people in different communities get food?',['Everyone grows rice','In many different ways — farming, fishing, buying at stores','Everyone hunts','Everyone buys at supermarkets'],1),('What is one way communities around the world are similar?',['Same language','Same food','Same sports','People care for each other'],3),('Learning about global communities helps us ___.',['Ignore other cultures','Understand that we are all connected','Think only our way is right','Avoid other countries'],1)])]),
day(17,[sub('Language','Pronouns','Ontario Grade 1 Writing strand: pronouns take the place of nouns. Examples: I, you, he, she, it, we, they.','TVO Learn: Grade 1 Language',L1,[('A pronoun takes the place of a ___.',['Verb','Adjective','Noun','Adverb'],2),('What pronoun replaces "Maria"?',['He','It','She','They'],2),('What pronoun replaces "the boys"?',['He','She','It','They'],3),('What pronoun replaces "the dog"?',['He','She','It','They'],2),('Which sentence uses a pronoun correctly?',['Dog runs fast.','Maria she runs fast.','She runs fast.','Running fast.'],2)]),
sub('Math','Subtraction from 20','Ontario Grade 1 Number strand: students subtract single-digit numbers from teens numbers and find differences within 20 using various strategies.','TVO Learn: Grade 1 Mathematics',M1,[('15 - 7 = ?',['7','8','9','6'],1),('20 - 9 = ?',['10','11','12','9'],1),('18 - 6 = ?',['11','12','13','10'],1),('14 - 8 = ?',['5','6','7','4'],1),('17 - 9 = ?',['7','8','9','6'],1)]),
sub('Science','Animal Habitats','Ontario Grade 1 Life Systems strand: a habitat is the natural environment where an animal lives, providing food, water, shelter, and space.','TVO Learn: Grade 1 Science & Technology',S1,[('A habitat provides animals with food, water, shelter, and ___.',['Toys','Space','Television','Money'],1),('Which habitat does a polar bear live in?',['Jungle','Desert','Arctic tundra','Rainforest'],2),('Which animal lives in a pond habitat?',['Camel','Frog','Polar bear','Penguin'],1),('A desert habitat is ___.',['Cold and wet','Hot and dry with little rainfall','Always covered in snow','Always rainy'],1),('What happens to an animal if its habitat is destroyed?',['Nothing changes','It may struggle to survive or must find a new habitat','It gets bigger','It becomes stronger'],1)]),
sub('SocialStudies','Helping Others in the Community','Ontario Grade 1 Social Studies strand A: students explore ways they can contribute to their community through volunteering, kindness, and helping neighbours.','TVO Learn: Grade 1 Social Studies',SS1,[('How can you help your community?',['Taking things','Littering','Volunteering and being kind to others','Ignoring others'],2),('Why is volunteering important?',['It is not','It benefits others and makes the community stronger','Only adults volunteer','It earns money'],1),('What is a way kids can help the environment?',['Buying more toys','Picking up litter and recycling','Using more electricity','Wasting food'],1),('Being kind to a new student at school helps them ___.',['Feel uncomfortable','Feel welcome and included','Stay silent','Ignore others'],1),('Why do communities need volunteers?',['They do not','Volunteers do important work that helps everyone','Volunteering is boring','Only hospitals need volunteers'],1)])]),
day(18,[sub('Language','Compound Words','Ontario Grade 1 Reading strand: a compound word is made of two smaller words joined together to make a new word, such as sunshine, raincoat, and backpack.','TVO Learn: Grade 1 Language',L1,[('A compound word is ___.',['A very long word','Two small words joined to make a new word','A word with a silent letter','A nonsense word'],1),('Which is a compound word?',['Apple','Beautiful','Sunshine','Elephant'],2),('What two words make "raincoat"?',['Rain + coat','Rai + ncoat','R + aincoat','Rainc + oat'],0),('What compound word means a bag worn on your back?',['Schoolbag','Backpack','Handbag','Purse'],1),('Which of these is a compound word?',['Running','Quickly','Strangely','Starfish'],3)]),
sub('Math','Ordinal Numbers','Ontario Grade 1 Number strand: ordinal numbers describe position in a sequence: first (1st), second (2nd), third (3rd), and so on.','TVO Learn: Grade 1 Mathematics',M1,[('What is the ordinal form of 1?',['Onest','First','Oneish','1nd'],1),('What is the ordinal form of 3?',['Threeth','Thirdly','Third','Threest'],2),('If you are 4th in line, how many people are ahead of you?',['3','4','5','2'],0),('What comes after fifth?',['Sixth','Seveth','Fourthly','Fiftth'],0),('The ordinal number "2nd" means ___.',['Second','Twoth','Twoeth','Secondly'],0)]),
sub('Science','Plants and the Environment','Ontario Grade 1 Life Systems strand: plants are producers that provide food and oxygen for other living things; they also prevent soil erosion and provide habitats.','TVO Learn: Grade 1 Science & Technology',S1,[('Plants produce oxygen through a process called ___.',['Digestion','Hibernation','Photosynthesis','Respiration'],2),('Why are plants important for animals?',['They are not','They provide food and oxygen for animals','They provide electricity','They provide money'],1),('What holds soil in place and prevents erosion?',['Rocks alone','Plant roots','Rain','Wind'],1),('Which of these would NOT survive without plants?',['Rocks','Rivers','Most animals','Clouds'],2),('How do plants help improve air quality?',['They do not','They absorb carbon dioxide and release oxygen','They create pollution','They absorb oxygen'],1)]),
sub('SocialStudies','Celebrations and Traditions','Ontario Grade 1 Social Studies strand A: students explore different cultural celebrations and traditions, recognising the diversity of practices and their importance to families.','TVO Learn: Grade 1 Social Studies',SS1,[('A tradition is ___.',['Something done only once','A special activity a family or culture repeats over time','Always about food','Only for children'],1),('Why do families celebrate traditions?',['They have to','To mark important events and strengthen bonds','It is boring','To spend money'],1),('Which is an example of a tradition?',['Brushing your teeth','An annual family holiday gathering','Going to sleep','Watching TV'],1),('How are celebrations different around the world?',['They are all the same','They vary in customs, foods, and meanings','Only the date changes','Only adults celebrate'],1),('Learning about others\' celebrations helps us ___.',['Ignore differences','Understand and appreciate cultural diversity','Copy everything','Stay separate'],1)])]),
day(19,[sub('Language','Synonyms','Ontario Grade 1 Writing strand: synonyms are words that have the same or similar meanings. Using synonyms makes writing more interesting.','TVO Learn: Grade 1 Language',L1,[('A synonym is a word that means the ___.',['Opposite','Same or similar thing','Nothing at all','Bigger thing'],1),('Which is a synonym for big?',['Small','Large','Tiny','Little'],1),('Which is a synonym for happy?',['Sad','Angry','Joyful','Tired'],2),('Which is a synonym for fast?',['Slow','Quick','Quiet','Soft'],1),('Using synonyms in writing makes it ___.',['More confusing','More boring','More interesting and varied','Shorter'],2)]),
sub('Math','Money: Coins','Ontario Grade 1 Number strand: students identify Canadian coins (penny, nickel, dime, quarter) and their values, and count small collections of coins.','TVO Learn: Grade 1 Mathematics',M1,[('How much is a nickel worth?',['1 cent','5 cents','10 cents','25 cents'],1),('How much is a dime worth?',['1 cent','5 cents','10 cents','25 cents'],2),('How much is a quarter worth?',['1 cent','5 cents','10 cents','25 cents'],3),('Which coin is worth the most?',['Penny','Nickel','Dime','Quarter'],3),('How many nickels make a dime?',['1','2','3','4'],1)]),
sub('Science','Energy and Movement','Ontario Grade 1 Science Physical Education strand: energy can cause objects to move. Stored energy (potential) and moving energy (kinetic) are two basic forms.','TVO Learn: Grade 1 Science & Technology',S1,[('What is energy?',['The ability to do work or cause change','A type of rock','A kind of animal','A colour'],0),('A ball sitting on a hill has ___ energy.',['No','Kinetic (moving)','Potential (stored)','Electrical'],2),('A ball rolling down a hill has ___ energy.',['No','Kinetic (moving)','Potential (stored)','Chemical'],1),('Which of these uses electrical energy?',['A rock','A wooden block','A light bulb','A leaf'],2),('What energy does the Sun give to Earth?',['Mechanical','Heat and light (solar energy)','Chemical','Nuclear'],1)]),
sub('SocialStudies','Traditions from Around the World','Ontario Grade 1 Social Studies strand A: students explore cultural traditions from different countries, building respect and appreciation for diversity.','TVO Learn: Grade 1 Social Studies',SS1,[('Why do countries have their own traditions?',['They have to','Traditions reflect the culture, history, and values of a people','Everyone chose the same ones','Rules forced them to'],1),('Which festival involves lanterns and is celebrated in China?',['Diwali','Hanukkah','Chinese Lantern Festival','Carnival'],2),('Diwali is celebrated by people of which background?',['Chinese','Hindu (and others in South Asia)','Japanese','European'],1),('Why is it important to learn about traditions from around the world?',['It is not important','It promotes respect and understanding','It is confusing','Only tourists need to know'],1),('Which of these is a Canadian tradition?',['Cinco de Mayo','Diwali as celebrated in Canada','Canada Day fireworks','Chinese New Year only'],1)])]),
day(20,[sub('Language','Antonyms','Ontario Grade 1 Writing strand: antonyms are words that have opposite meanings, such as hot/cold, happy/sad, and big/small.','TVO Learn: Grade 1 Language',L1,[('An antonym is a word that means the ___ of another word.',['Same','Opposite','Similar','Bigger'],1),('What is the antonym of BIG?',['Large','Huge','Small','Giant'],2),('What is the antonym of HOT?',['Warm','Cold','Cool','Frozen'],1),('What is the antonym of DAY?',['Morning','Afternoon','Evening','Night'],3),('Using antonyms helps us ___.',['Make writing longer','Compare and contrast ideas','Confuse readers','Remove nouns'],1)]),
sub('Math','Time: Reading Clocks','Ontario Grade 1 Measurement strand: students tell time to the hour and half hour on both analogue and digital clocks.','TVO Learn: Grade 1 Mathematics',M1,[('On a clock, the short hand points to the ___.',['Minutes','Seconds','Hour','Day'],2),('What time is shown when both hands point to 12?',['6:00','12:00','3:00','9:00'],1),('If the hour hand points to 3 and the minute hand to 12, the time is ___.',['12:03','12:30','3:00','3:30'],2),('Half past 4 means ___.',['4:00','4:05','4:30','4:15'],2),('How many hours are in one day?',['12','24','48','60'],1)]),
sub('Science','Simple Machines','Ontario Grade 1 Science strand: simple machines make work easier. Examples include lever, wheel and axle, pulley, inclined plane, wedge, and screw.','TVO Learn: Grade 1 Science & Technology',S1,[('A simple machine makes work ___.',['Harder','Slower','Easier','More confusing'],1),('A ramp is an example of an ___.',['Lever','Pulley','Inclined plane','Wheel and axle'],2),('A wheel and axle reduces ___.',['Speed','The force needed to move things','Height','Distance'],1),('Which simple machine is a seesaw an example of?',['Pulley','Inclined plane','Wedge','Lever'],3),('How many types of simple machines are there?',['3','4','5','6'],3)]),
sub('SocialStudies','Canada Day and National Holidays','Ontario Grade 1 Social Studies strand B: students learn about Canada Day and other national holidays, understanding what they celebrate and why they are important.','TVO Learn: Grade 1 Social Studies',SS1,[('Canada Day is celebrated on ___.',['July 4','July 1','October 1','November 11'],1),('What does Canada Day celebrate?',['Christmas','Canada\'s birthday as a nation','Thanksgiving','Halloween'],1),('Remembrance Day honours ___.',['The founding of Canada','Veterans who served in wars','Canadian athletes','Canadian scientists'],1),('What is the date of Remembrance Day?',['October 31','December 25','November 11','July 1'],2),('Victoria Day in Canada honours ___.',['Canada Day celebrations','The Queen\'s birthday and the monarchy','Halloween','Summer solstice'],1)])]),
day(21,[sub('Language','Prefixes: un- and re-','Ontario Grade 1 Reading strand: a prefix is added to the beginning of a word to change its meaning. Un- means not; re- means again.','TVO Learn: Grade 1 Language',L1,[('What does the prefix UN- mean?',['Again','Before','Not','After'],2),('What does UNKIND mean?',['Very kind','Not kind','Kind again','Extremely kind'],1),('What does the prefix RE- mean?',['Not','Before','After','Again'],3),('What does REREAD mean?',['Not read','Read before','Read again','Read after'],2),('Which word has a prefix?',['Running','Jumped','Unhappy','Cats'],2)]),
sub('Math','Number Patterns','Ontario Grade 1 Algebra and Patterning strand: students identify, describe, and extend number patterns involving addition or subtraction.','TVO Learn: Grade 1 Mathematics',M1,[('What comes next? 2, 4, 6, 8, ___',['9','10','12','11'],1),('What is the rule? 10, 20, 30, 40...',['Add 5','Add 10','Add 2','Add 15'],1),('What comes next? 1, 3, 5, 7, ___',['8','9','10','6'],1),('What is the rule? 20, 18, 16, 14...',['Add 2','Subtract 3','Subtract 2','Add 1'],2),('What comes next? 5, 10, 15, 20, ___',['21','22','25','30'],2)]),
sub('Science','Rocks and Their Properties','Ontario Grade 1 Earth and Space Systems strand: rocks can be described by colour, texture, hardness, and size. Different rocks have different properties and uses.','TVO Learn: Grade 1 Science & Technology',S1,[('Rocks can be described by ___.',['Their feelings','Their colour, texture, and hardness','Their names only','Their families'],1),('Which rock is used to make jewellery?',['Limestone','Granite','Diamond (a mineral)','Sandstone'],2),('What does the hardness of a rock tell us?',['Its colour','How easily it can be scratched','Its weight','Its age'],1),('Where can you find rocks?',['Only underground','Only in rivers','Everywhere — on land, in water, underground','Only in mountains'],2),('Which of these is made from a natural rock or mineral?',['Plastic cup','Salt (a mineral)','Glass window (made from sand, a mineral)','Both b and c'],3)]),
sub('SocialStudies','Maps of Canada','Ontario Grade 1 Social Studies strand B: students read simple maps of Canada, identifying provinces, territories, capital cities, and geographic regions.','TVO Learn: Grade 1 Social Studies',SS1,[('How many provinces does Canada have?',['8','9','10','12'],2),('How many territories does Canada have?',['1','2','3','4'],2),('What is the capital city of Canada?',['Toronto','Montreal','Ottawa','Vancouver'],2),('Which province is on the far east coast of Canada?',['British Columbia','Ontario','Alberta','Newfoundland and Labrador'],3),('Which territory is in the far north of Canada?',['Ontario','Nunavut','Quebec','Alberta'],1)])]),
day(22,[sub('Language','Suffixes: -er and -ing','Ontario Grade 1 Reading strand: a suffix is added to the end of a word to change its meaning. -Er means one who does; -ing indicates an ongoing action.','TVO Learn: Grade 1 Language',L1,[('What does the suffix -ER mean when added to a verb?',['The action itself','One who does the action','Doing the action now','Having done the action'],1),('What does TEACHER mean?',['To teach','One who teaches','Is teaching','Taught'],1),('What does RUNNING mean?',['Ran once','About to run','Currently doing the action of running','One who runs'],2),('Which word has a suffix?',['Running','Of','The','And'],0),('Adding -ING to a verb creates a ___.',['Noun','Adjective','Present participle (ongoing action)','Prefix'],2)]),
sub('Math','Addition Strategies','Ontario Grade 1 Number strand: students use mental math strategies such as doubles, near doubles, make ten, and counting on to add efficiently.','TVO Learn: Grade 1 Mathematics',M1,[('Counting on means starting at the bigger number and ___.',['Subtracting','Adding backwards','Counting forward the smaller number','Counting from 1'],2),('6 + 6 = 12 is an example of a ___.',['Near double','Double','Make ten','Counting on'],1),('7 + 6: think 7 + 7 = 14, then subtract 1 = 13. This is a ___.',['Double','Near double strategy','Make ten','Counting on'],1),('Make 10: 8 + 5 = 8 + 2 + 3 = 10 + 3 = ___',['12','13','14','11'],1),('Which strategy works best for 9 + 4?',['Count from 1','Doubles','Make ten: 9+1+3=13','Subtraction'],2)]),
sub('Science','Water on Earth','Ontario Grade 1 Earth and Space Systems strand: water covers most of Earth\'s surface. It exists in three states and cycles through the environment.','TVO Learn: Grade 1 Science & Technology',S1,[('What percentage of Earth\'s surface is covered by water?',['About 30 percent','About 50 percent','About 70 percent','About 90 percent'],2),('Water in three states: ___.',['Solid, liquid, gas','Hot, warm, cold','Fast, slow, still','Deep, shallow, wide'],0),('What is the water cycle?',['How water is made in factories','The continuous movement of water through evaporation, condensation, and precipitation','How we filter drinking water','How rain is collected in rivers'],1),('Which state is water in when it forms clouds?',['Solid','Liquid','Gas (water vapour)','Plasma'],2),('Why is clean water important?',['It is not','All living things need clean water to survive','Only fish need clean water','Only humans need water'],1)]),
sub('SocialStudies','Provinces of Canada','Ontario Grade 1 Social Studies strand B: students identify the ten provinces of Canada and some facts about each, locating them on a map.','TVO Learn: Grade 1 Social Studies',SS1,[('Which province is on the west coast of Canada?',['Ontario','Quebec','British Columbia','Manitoba'],2),('Which province is Canada\'s largest by area?',['Ontario','Quebec','Alberta','British Columbia'],1),('The Maritime provinces include New Brunswick, Nova Scotia, and ___.',['Ontario','Prince Edward Island','Quebec','Newfoundland'],1),('Which province is known for the Prairies (flat grasslands)?',['British Columbia','Ontario','Saskatchewan','Quebec'],2),('What is the capital city of Quebec?',['Montreal','Quebec City','Ottawa','Toronto'],1)])]),
day(23,[sub('Language','Poetry','Ontario Grade 1 Reading and Writing strands: students read and write simple poems, identifying rhyme, rhythm, and descriptive language, and appreciating how poets choose words carefully.','TVO Learn: Grade 1 Language',L1,[('Poetry often uses ___.',['Only long sentences','Rhyme, rhythm, and descriptive language','Only facts','Lots of numbers'],1),('Which lines rhyme?',['The cat sat on the mat / The dog ran to school','Roses are red / Violets are blue','Today is Monday / I ate my lunch','She ran fast / He jumped high'],1),('Rhythm in a poem means ___.',['The poem is long','A regular beat or pattern in the words','The poem rhymes','The poem is happy'],1),('A poem is different from a story because ___.',['It has no words','It often uses line breaks and focuses on feelings and images','It is always longer','It has no characters'],1),('Which is an example of descriptive language in a poem?',['She went to the store','The shimmering silver moon glowed softly','It was night','He walked home'],1)]),
sub('Math','Subtraction Strategies','Ontario Grade 1 Number strand: students use strategies such as counting back, fact families, and think-addition to subtract efficiently.','TVO Learn: Grade 1 Mathematics',M1,[('Counting back: 12 - 3 means start at 12 and count back ___.',['12 steps','1 step','3 steps','2 steps'],2),('Think-addition: 13 - 5 = ? Think 5 + ___ = 13',['7','8','9','6'],1),('A fact family uses the same three numbers. 7+5=12, 5+7=12, 12-5=___, 12-7=5.',['5','7','4','6'],1),('Which is a subtraction strategy?',['Counting on from 1','Making a ten','Counting back from the bigger number','Skip counting by 5'],2),('14 - 6 = ?',['7','8','9','6'],1)]),
sub('Science','Stars and Space','Ontario Grade 1 Earth and Space Systems strand: the Sun is the closest star to Earth. Stars are large balls of hot gas. The Moon orbits Earth.','TVO Learn: Grade 1 Science & Technology',S1,[('The Sun is a ___.',['Planet','Moon','Large ball of hot gas called a star','Comet'],2),('Which planet do we live on?',['Mars','Venus','Earth','Jupiter'],2),('The Moon ___.',['Makes its own light','Orbits (circles) the Earth','Is a star','Is bigger than Earth'],1),('Stars are visible mainly at ___.',['Noon','Dawn','Night','Dusk only'],2),('How does the Moon appear to change shape?',['It actually changes shape','We see different amounts of its lit side as it orbits Earth','Clouds cover it','It grows and shrinks'],1)]),
sub('SocialStudies','Caring for the Environment','Ontario Grade 1 Social Studies strand B: students identify ways to protect the environment including reducing waste, recycling, and conserving water and energy.','TVO Learn: Grade 1 Social Studies',SS1,[('What does REDUCE mean in reduce, reuse, recycle?',['Throw away more','Use less of something','Make something bigger','Buy more'],1),('Which is an example of recycling?',['Throwing a bottle in the garbage','Turning a used newspaper into new paper','Buying new items','Wasting water'],1),('Why should we turn off lights when leaving a room?',['Lights do not matter','To save electrical energy','Lights are too bright','To make the room dark'],1),('What is one way to conserve water?',['Leave the tap running','Take very long showers','Turn off the tap while brushing teeth','Water your lawn every hour'],2),('Caring for the environment benefits ___.',['Only humans','Only animals','Both humans and all living things now and in the future','Nobody'],2)])]),
day(24,[sub('Language','Non-Fiction Text Features','Ontario Grade 1 Reading strand: non-fiction texts contain features like headings, photographs, captions, table of contents, and indexes that help readers find and understand information.','TVO Learn: Grade 1 Language',L1,[('What is a heading in a non-fiction text?',['A type of hat','A bold title that tells what a section is about','A picture at the top','The author\'s name'],1),('What is a caption?',['A title','Words that explain a photograph or illustration','A type of heading','The conclusion'],1),('What does a table of contents show?',['The author\'s biography','Chapter/section titles and page numbers','Definitions of words','Only pictures'],1),('How is a non-fiction text different from fiction?',['It has pictures','Non-fiction contains facts about real topics; fiction is made up','It is shorter','It has more chapters'],1),('Which of these is a non-fiction book?',['The Three Little Pigs','Charlotte\'s Web','Encyclopaedia of Animals','Harry Potter'],2)]),
sub('Math','Review: Number Sense to 50','Ontario Grade 1 Number strand review: students count, compare, order, and represent numbers to 50, and demonstrate understanding of place value and operations.','TVO Learn: Grade 1 Mathematics',M1,[('What is 3 tens and 7 ones?',['30','37','73','13'],1),('Which is greatest: 24, 42, or 34?',['24','34','42','44'],2),('15 + 7 = ?',['20','22','21','23'],1),('20 - 8 = ?',['11','12','13','14'],1),('Skip count by 5s: 25, 30, ___',['33','35','40','32'],1)]),
sub('Science','Seasons Review','Ontario Grade 1 Earth and Space Systems strand review: students review the four seasons, their characteristics, and how plants, animals, and people respond to seasonal changes.','TVO Learn: Grade 1 Science & Technology',S1,[('What are the four seasons in order starting with spring?',['Spring, Summer, Fall, Winter','Summer, Fall, Winter, Spring','Winter, Spring, Summer, Fall','Fall, Winter, Spring, Summer'],0),('In which season do most plants grow flowers?',['Winter','Fall','Spring and Summer','No season'],2),('Which season has the longest days in Ontario?',['Winter','Fall','Summer','Spring'],2),('What do deciduous trees do in fall?',['Grow new leaves','Lose their leaves','Stay the same','Grow taller only'],1),('In Ontario, which season has the coldest temperatures?',['Fall','Spring','Summer','Winter'],3)]),
sub('SocialStudies','Rights Review','Ontario Grade 1 Social Studies strand A review: students review children\'s rights, responsibilities, and what it means to be a responsible citizen in the school and community.','TVO Learn: Grade 1 Social Studies',SS1,[('What are the three main rights of all children?',['Work, play, travel','Education, safety, and being cared for','Money, toys, vacations','Adults choose their rights'],1),('What is a responsibility?',['Something we are paid for','Something we are expected to do for ourselves and others','Something only adults have','Something we can always skip'],1),('Name one way to be a responsible student.',['Talking in class','Helping others and doing your work','Ignoring instructions','Being noisy'],1),('Responsible citizens ___.',['Only follow rules they like','Follow rules, help others, and care for their community','Do whatever they want','Never follow rules'],1),('Why do rights and responsibilities go together?',['They do not','Having rights means taking responsibility to respect others\' rights too','Only adults need to think about this','Rights are more important'],1)])]),
day(25,[sub('Language','Creative Writing','Ontario Grade 1 Writing strand: students write short creative stories with a beginning, middle, and end, using descriptive language, interesting characters, and a simple plot.','TVO Learn: Grade 1 Language',L1,[('Creative writing lets you ___.',['Write only facts','Create imaginary stories and characters','Write only your name','Copy other stories'],1),('A good creative story has a ___.',['Beginning only','Beginning, middle, and end','Middle only','Only a problem'],1),('What makes a story more interesting?',['Very short sentences only','Descriptive language and interesting characters','Just names and places','Numbers and lists'],1),('The problem in a story is ___.',['The beginning','The ending','The challenge the character must solve','The setting'],2),('A story\'s solution is ___.',['The problem','How the character solves the problem','The setting','The beginning'],1)]),
sub('Math','Review: Patterns and Shapes','Ontario Grade 1 Geometry and Patterning review: students identify and extend patterns, and describe properties of 2D and 3D shapes.','TVO Learn: Grade 1 Mathematics',M1,[('Which 2D shape has three sides?',['Square','Rectangle','Circle','Triangle'],3),('What comes next? Triangle, Square, Triangle, Square, ___',['Circle','Triangle','Rectangle','Square'],1),('A cube has how many faces?',['4','5','6','8'],2),('Which is a 3D shape?',['Circle','Square','Sphere','Triangle'],2),('What is the pattern rule? 5, 10, 15, 20...',['Add 2','Add 5','Add 10','Add 3'],1)]),
sub('Science','Life Cycles Review','Ontario Grade 1 Life Systems strand review: students review life cycles of different animals including butterfly, frog, and chicken, identifying the stages.','TVO Learn: Grade 1 Science & Technology',S1,[('What are the four stages of a butterfly\'s life cycle?',['Egg, larva, pupa, adult','Baby, child, teen, adult','Seed, sprout, plant, flower','Egg, chick, chicken, adult'],0),('What is a tadpole?',['A baby butterfly','A baby frog','A type of fish','A baby bird'],1),('In the life cycle of a chicken: egg, chick, ___.',['Larva','Pupa','Adult chicken','Caterpillar'],2),('All life cycles ___.',['Begin with an adult','End with a seed','Are continuous processes','Are the same for all animals'],2),('What is metamorphosis?',['A type of habitat','A kind of rock','A process of dramatic change in form during a life cycle','A season change'],2)]),
sub('SocialStudies','Community Review','Ontario Grade 1 Social Studies review: students review the concept of community, types of communities, community workers, and the importance of caring for the environment.','TVO Learn: Grade 1 Social Studies',SS1,[('What is a community?',['A building','A group of people living and working together in a place','A type of map','A natural resource'],1),('Name two types of communities.',['Urban and rural','Big and small','Old and new','Rich and poor'],0),('Which community worker helps people get from place to place?',['A teacher','A bus driver or train conductor','A doctor','A librarian'],1),('Why should communities care for the environment?',['Only some communities do','To keep the natural world healthy for everyone now and in the future','It is not necessary','Only scientists care about this'],1),('What makes a community strong?',['Only money','Cooperation, diversity, and people helping each other','Lots of buildings','Only having the same culture'],1)])]),
day(26,[sub('Language','Story Structure Review','Ontario Grade 1 Reading and Writing strands review: students apply understanding of story structure (characters, setting, problem, solution) to read and write stories.','TVO Learn: Grade 1 Language',L1,[('What are the five main story elements?',['Title, pages, words, pictures, cover','Characters, setting, problem, events, solution','Beginning, ending, middle, pictures, words','Nouns, verbs, adjectives, adverbs, pronouns'],1),('The setting tells us ___.',['The characters\' feelings','Where and when the story takes place','The main problem','The lesson'],1),('The problem in a story creates ___.',['The happy ending','The setting','Conflict and suspense','The characters'],1),('Identifying story elements helps readers ___.',['Read faster','Understand and remember stories better','Skip pages','Count words'],1),('Which element is most important in a story?',['Setting','Characters','All elements work together','Pictures'],2)]),
sub('Math','Review: Addition and Subtraction','Ontario Grade 1 Number strand review: students apply addition and subtraction strategies to solve problems within 20.','TVO Learn: Grade 1 Mathematics',M1,[('14 + 5 = ?',['18','19','20','21'],1),('17 - 8 = ?',['8','9','10','7'],1),('A farmer has 12 chickens. 4 run away. How many are left?',['7','8','9','10'],1),('Sam has 6 apples and gets 7 more. How many total?',['12','13','14','15'],1),('20 - 11 = ?',['8','9','10','11'],1)]),
sub('Science','Animal Review','Ontario Grade 1 Life Systems strand review: students review key concepts about animals including needs, habitats, young, and adaptations.','TVO Learn: Grade 1 Science & Technology',S1,[('What do all animals need to survive?',['Television','Food, water, air, and shelter','Only food','Money'],1),('An adaptation is ___.',['A type of habitat','A special feature that helps an animal survive','A kind of food','A life cycle stage'],1),('Which animal is adapted to cold Arctic environments?',['Camel','Polar bear','Frog','Butterfly'],1),('What is a food chain?',['A chain you can eat','A sequence showing who eats whom in an ecosystem','A type of animal','A habitat'],1),('Baby animals grow to look like their ___.',['Owners','Teachers','Parents','Friends'],2)]),
sub('SocialStudies','Heritage Review','Ontario Grade 1 Social Studies strand A review: students review concepts of heritage, identity, family, traditions, and cultural celebrations.','TVO Learn: Grade 1 Social Studies',SS1,[('Heritage includes ___.',['Only buildings','The traditions, stories, values, and culture passed through generations','Only money','Only food'],1),('How does learning about our heritage help us?',['It does not','It helps us understand who we are and where we come from','It is boring','Only adults need to learn heritage'],1),('Which of these is part of a family\'s heritage?',['A new toy','A traditional recipe passed down through generations','A new house','A recent movie'],1),('How do families pass on their heritage?',['By forgetting old traditions','Through stories, traditions, celebrations, and language','By never celebrating','By moving away'],1),('Why is Canada\'s multicultural heritage an asset?',['It causes confusion','It brings diverse perspectives and richness to Canadian society','It creates problems','Only in big cities'],1)])]),
day(27,[sub('Language','Reading Fluency','Ontario Grade 1 Reading strand: reading fluency means reading smoothly, at an appropriate pace, with expression. Practice with familiar texts builds fluency.','TVO Learn: Grade 1 Language',L1,[('Reading fluency means ___.',['Reading as fast as possible','Reading smoothly, accurately, and with expression','Reading silently only','Reading only short books'],1),('Which practice builds reading fluency?',['Reading a new book every day only','Re-reading familiar texts and reading aloud','Only reading in your head','Only reading alone'],1),('Expression in reading means ___.',['Reading in a monotone voice','Changing your voice to match the mood and punctuation','Only whispering','Only shouting'],1),('A fluent reader ___.',['Reads every word slowly','Pauses at commas and periods','Sounds out every letter individually','Never re-reads'],1),('Why is reading fluency important?',['It is not','Fluent reading allows you to focus on understanding the meaning','Only speed matters','Only accuracy matters'],1)]),
sub('Math','Review: Measurement','Ontario Grade 1 Measurement strand review: students apply understanding of length, mass, capacity, and time to solve problems.','TVO Learn: Grade 1 Mathematics',M1,[('Which tool measures length?',['Scale','Ruler','Thermometer','Clock'],1),('Which measures how heavy something is?',['Ruler','Thermometer','Scale','Clock'],2),('Half past 7 means ___.',['7:05','7:15','7:30','7:50'],2),('If a pencil is 10 cubes long and a pen is 14 cubes long, which is shorter?',['Pen','Pencil','Equal','Cannot tell'],1),('What unit do we use to measure length in metric system?',['Pounds','Kilograms','Centimetres','Degrees'],2)]),
sub('Science','Plant Review','Ontario Grade 1 Life Systems and Earth strand review: students review plant parts, plant needs, life cycles, and the importance of plants to the environment.','TVO Learn: Grade 1 Science & Technology',S1,[('Which part of a plant makes food?',['Root','Stem','Leaf (through photosynthesis)','Seed'],2),('What are the four things plants need to grow?',['Books, pencils, chairs, desks','Sunlight, water, air, and nutrients from soil','Money, toys, television, games','Electricity, heat, noise, colour'],1),('What does a plant seed need to germinate?',['Darkness only','Water, warmth, and air','Only sunlight','Only soil'],1),('A fruit contains ___.',['Only juice','Seeds that can grow into new plants','Roots','Stems'],1),('Why are plants important to the environment?',['They are not','They produce oxygen, provide food, and support habitats','Only for decoration','Only for food'],1)]),
sub('SocialStudies','Culture Review','Ontario Grade 1 Social Studies strand A review: students review key vocabulary and concepts related to culture, including traditions, celebrations, language, and respect for diversity.','TVO Learn: Grade 1 Social Studies',SS1,[('Culture includes ___.',['Only clothing','Language, traditions, art, food, and values of a group of people','Only food','Only music'],1),('How do we show respect for different cultures?',['Ignoring them','Making fun of them','Learning about them and treating everyone fairly','Copying everything'],2),('Why is cultural diversity an asset in Canada?',['It causes problems','It enriches society with different perspectives and ideas','Only if everyone speaks the same language','Only in big cities'],1),('Which is the best way to learn about another culture?',['Assume you know everything','Ask respectful questions and listen to learn','Read one book and decide','Watch one movie'],1),('Multiculturalism in Canada means ___.',['Only one culture is valued','All cultures are respected and valued','French and English only','Immigrants must forget their culture'],1)])]),
day(28,[sub('Language','Spelling Patterns: -ight, -ake, -ine','Ontario Grade 1 Reading strand: spelling patterns help students decode and spell new words. Word families like night, sight, light; cake, lake, make; mine, fine, pine share patterns.','TVO Learn: Grade 1 Language',L1,[('Which word belongs to the -IGHT family?',['Lake','Mine','Night','Cake'],2),('Which word belongs to the -AKE family?',['Night','Light','Right','Cake'],3),('Which word belongs to the -INE family?',['Sight','Fine','Night','Lake'],1),('Which spelling pattern do BRIGHT and TIGHT share?',['ake','ine','ight','ake'],2),('Learning spelling patterns helps us ___.',['Only spell one word','Read and spell many words in the same family','Draw letters only','Sound out every letter always'],1)]),
sub('Math','Review: Data and Probability','Ontario Grade 1 Data strand review: students collect, organise, and interpret data using tally charts and pictographs, and explore basic probability.','TVO Learn: Grade 1 Mathematics',M1,[('A tally chart uses ___ to count data.',['Pictures','Numbers only','Tally marks','Coins'],2),('A pictograph uses ___ to show data.',['Only numbers','Pictures or symbols','Only tally marks','Letters'],1),('If 5 students chose apples and 3 chose oranges, which is more popular?',['Oranges','Apples','Equal','Cannot tell'],1),('Probability means ___.',['Collecting data','The chance of an event happening','Drawing graphs','Counting by 5s'],1),('If a bag has 3 red and 1 blue marble, reaching in without looking gives you a better chance of pulling out a ___.',['Blue','Red','Green','Cannot tell'],1)]),
sub('Science','Earth and Weather Review','Ontario Grade 1 Earth and Space Systems review: students review weather patterns, the water cycle, rocks, soil, and the Sun\'s role in Earth\'s systems.','TVO Learn: Grade 1 Science & Technology',S1,[('What causes day and night?',['Earth moving around the Sun','Earth rotating on its axis','The Moon blocking the Sun','Clouds covering the sky'],1),('The water cycle involves ___.',['Evaporation, condensation, and precipitation','Only rain falling','Only rivers flowing','Only clouds forming'],0),('What is a thermometer used for?',['Measuring length','Measuring mass','Measuring temperature','Measuring time'],2),('Soil is made of ___.',['Only sand','Rock particles, organic matter, air, and water','Only clay','Only rocks'],1),('The Sun provides Earth with ___.',['Only light','Only heat','Heat and light energy essential for life','Water'],2)]),
sub('SocialStudies','Citizenship and Community','Ontario Grade 1 Social Studies review: students review civic concepts including rights, responsibilities, community participation, and environmental stewardship.','TVO Learn: Grade 1 Social Studies',SS1,[('What does it mean to be a good citizen?',['Following only favourite rules','Ignoring community issues','Being responsible, respectful, and contributing to your community','Doing whatever you want'],2),('Why is voting important in a democracy?',['It is not','Citizens choose their leaders and have a voice in decisions','Only important people vote','Votes do not count'],1),('How can children participate in their community?',['Only adults participate','Through volunteering, recycling, and helping neighbours','By staying home','By watching others'],1),('What is one way to care for the community environment?',['Littering','Wasting water','Reducing, reusing, and recycling','Using more electricity'],2),('A democratic community values ___.',['Silence','Only one person\'s opinion','Fairness, equality, and participation of all members','Money above all'],2)])]),
day(29,[sub('Language','Reading Skills Review','Ontario Grade 1 Reading strand review: students review key reading strategies including predicting, retelling, identifying main idea, making connections, and using text features.','TVO Learn: Grade 1 Language',L1,[('Which reading strategy helps you guess what happens next?',['Retelling','Connecting','Predicting','Summarising'],2),('Retelling a story means ___.',['Reading it again','Telling the main events in your own words in order','Drawing pictures','Changing the ending'],1),('The main idea is ___.',['A small detail','What the text is mostly about','The first sentence always','The title'],1),('A text-to-self connection means ___.',['The text connects to another book','Comparing two texts','Relating the text to your own personal experience','Connecting to world events'],2),('Non-fiction text features include ___.',['Plot and characters','Headings, captions, and index','Only pictures','Stories and poems'],1)]),
sub('Math','Review: Number Sense','Ontario Grade 1 Number strand review: students review counting, place value, addition, subtraction, fractions, and money.','TVO Learn: Grade 1 Mathematics',M1,[('4 tens + 7 ones = ?',['40','47','74','17'],1),('18 + 5 = ?',['22','23','24','21'],1),('20 - 13 = ?',['6','7','8','9'],1),('One-half is written as ___.',['1/3','1/4','1/2','2/3'],2),('A dime is worth ___ cents.',['5','10','25','50'],1)]),
sub('Science','Life Science Review','Ontario Grade 1 Life Systems strand review: students review living vs non-living, needs of living things, plants, animals, food chains, and habitats.','TVO Learn: Grade 1 Science & Technology',S1,[('What are the four needs of all living things?',['Sun, moon, stars, planets','Air, water, food, and shelter','Books, toys, music, games','Electricity, light, heat, money'],1),('Name two parts of a plant.',['Wheel and pedal','Root and leaf','Lens and frame','Door and window'],1),('A food chain starts with a ___.',['Carnivore','Herbivore','Producer (plant)','Decomposer'],2),('A habitat provides an animal with ___.',['Toys and entertainment','Food, water, shelter, and space','Electricity and heat','School and education'],1),('Which best describes metamorphosis?',['A type of habitat','A food chain','A dramatic change in form during a life cycle','A kind of rock'],2)]),
sub('SocialStudies','Review: Communities and Canada','Ontario Grade 1 Social Studies review: students demonstrate understanding of communities, Canadian geography, symbols, and civic values.','TVO Learn: Grade 1 Social Studies',SS1,[('Which Canadian symbol has a maple leaf?',['The flag','The coat of arms','The dollar bill','All three'],3),('What is the capital city of Canada?',['Toronto','Ottawa','Montreal','Vancouver'],1),('How many provinces does Canada have?',['8','9','10','12'],2),('Which of the following is an example of multiculturalism?',['Everyone speaks the same language','Many different cultures contributing to society','One culture being better','Avoiding other cultures'],1),('What should every citizen do to keep their community clean?',['Litter occasionally','Leave lights on always','Reduce waste and recycle','Waste water'],2)])]),
day(30,[sub('Language','Year Review: Language Arts','Ontario Grade 1 Language strand comprehensive review: students demonstrate reading, writing, and oral communication skills developed throughout the year.','TVO Learn: Grade 1 Language',L1,[('A noun names a ___.',['Action','Person, place, or thing','Describing word','Connecting word'],1),('A verb shows ___.',['A name','An action or state of being','A description','A connection'],1),('An adjective describes a ___.',['Verb','Noun','Adverb','Pronoun'],1),('Which is a complete sentence?',['The dog.','Runs fast.','The dog runs.','Big dog fast.'],2),('Why is reading every day important?',['It is not','It builds vocabulary, comprehension, and imagination','Only for school','Only for homework'],1)]),
sub('Math','Year Review: Mathematics','Ontario Grade 1 Mathematics comprehensive review covering number sense, geometry, measurement, patterning, and data.','TVO Learn: Grade 1 Mathematics',M1,[('3 tens + 5 ones = ?',['53','30','35','45'],2),('9 + 8 = ?',['16','17','18','15'],1),('20 - 7 = ?',['12','13','14','11'],1),('A square has ___ equal sides.',['2','3','4','5'],2),('Skip count by 2s: 16, 18, 20, ___',['21','22','24','23'],1)]),
sub('Science','Year Review: Science','Ontario Grade 1 Science comprehensive review covering life systems, earth and space, matter, and physical science.','TVO Learn: Grade 1 Science & Technology',S1,[('Living things need ___.',['Electricity and television','Air, water, food, and shelter','Money and toys','Books and pencils'],1),('Earth has ___ seasons.',['2','3','4','5'],2),('A push and pull are examples of ___.',['Weather','Forces','Patterns','States of matter'],1),('The Sun is a ___.',['Planet','Moon','Star','Comet'],2),('Plants make their food using sunlight through ___.',['Digestion','Hibernation','Photosynthesis','Respiration'],2)]),
sub('SocialStudies','Year Review: Social Studies','Ontario Grade 1 Social Studies comprehensive review covering family, community, Canada, and civic values.','TVO Learn: Grade 1 Social Studies',SS1,[('What is the capital of Canada?',['Toronto','Montreal','Ottawa','Vancouver'],2),('Community workers ___.',['Create problems','Provide services that help people','Only work for money','Are not important'],1),('What does it mean to be a good citizen?',['Following only favourite rules','Being responsible and contributing positively to the community','Ignoring rules','Doing whatever you want'],1),('Canada\'s two official languages are ___.',['Spanish and English','French and English','Italian and French','English and Chinese'],1),('Why is respecting all cultures important in Canada?',['It is not','Canada is built on diversity and everyone deserves respect','Only some cultures matter','Only in big cities'],1)])]),
]

if __name__ == "__main__":
    write_new(1, g1)
    print("Grade 1 done")
