#!/usr/bin/env python3
"""Grade 12 — days 1-15. Subjects: English, AdvancedFunctions, Calculus, Physics."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,write_new

def E(t,s,q):
    return sub('English',t,s,'TED-Ed: Literature','https://www.youtube.com/c/TEDEd',q)
def A(t,s,url,q):
    return sub('Advanced Functions',t,s,'Khan Academy','https://www.khanacademy.org/math/precalculus',q)
def Ca(t,s,url,q):
    return sub('Calculus',t,s,'Khan Academy Calculus','https://www.khanacademy.org/math/calculus-1',q)
def P(t,s,url,q):
    return sub('Physics',t,s,'Crash Course Physics','https://www.youtube.com/playlist?list=PL8dPuuaLjXtN0ge7yDk_UA0ldZJdhwkoV',q)

g12=[
day(1,[
E('Literary Analysis: University-Level Essay Writing','Students develop the analytical writing skills required for first-year university — constructing complex arguments, integrating sources, and writing with precision and intellectual authority.',[
  ('A university-level literary argument differs from a high school argument in that ___.',['it requires longer essays','it avoids personal interpretation','it uses more quotations','it engages with the critical conversation around a text — acknowledging existing interpretations and positioning your own reading in relation to them, not just stating your view in isolation'],3),
  ('Intellectual authority in academic writing is established through ___.',['using complex vocabulary','only citing many sources','writing confidently regardless of evidence','precise, specific claims supported by carefully selected and analysed evidence — authority comes from the quality of your reasoning, not the confidence of your assertions'],3),
  ('A counterargument in an academic essay ___.',['weakens your position','should always be avoided','proves you are unsure of your argument','strengthens your argument when addressed and refuted — demonstrating that you have considered alternative interpretations and can explain why your reading is more persuasive'],3),
  ('Integrating literary criticism responsibly means ___.',['copying the critic\'s argument as your own','only agreeing with critics','avoiding critics who disagree with you','engaging critically with secondary sources — using them to inform, enrich, or challenge your reading, while maintaining your own analytical voice and making your own contribution'],3),
  ('The most important difference between high school and university English is ___.',['university requires less reading','university essays are always longer','grammar is more important at university','intellectual independence: university expects you to formulate genuine, original questions about texts and pursue them with rigour, not just respond to provided prompts'],3)]),
sub('Advanced Functions','Polynomial Functions: Deep Dive into Graphs and Equations','Students investigate polynomial functions of all degrees — connecting multiplicity of zeros, end behaviour, turning points, and algebraic form to graphical behaviour.','Khan Academy: Polynomial Graphs','https://www.youtube.com/watch?v=1WRYEBHLLm8',[
  ('A polynomial of degree n can have at most ___ real zeros and at most ___ turning points.',['n zeros and n turning points','n-1 zeros and n turning points','n zeros and n-1 turning points (a degree-n polynomial has at most n zeros and at most n-1 local maxima/minima)','n+1 zeros and n turning points'],2),
  ('A zero of multiplicity 2 means the graph ___.',['crosses the x-axis steeply','has a vertical asymptote','crosses the x-axis at a 45° angle','touches but does not cross the x-axis — the graph is tangent to the x-axis at that zero'],3),
  ('A zero of multiplicity 3 means the graph ___.',['touches and bounces','has no x-intercept there','crosses with an S-curve (point of inflection) at that zero — flattening as it crosses','creates a sharp corner'],2),
  ('For P(x) = −2(x+1)²(x−3)(x−5), the end behaviour is ___.',['rises left, rises right','falls left, rises right','rises left, falls right','falls both directions — leading term is −2x⁴ (even degree, negative coefficient)'],3),
  ('The Intermediate Value Theorem guarantees ___.',['a polynomial has exactly n roots','the maximum value of a polynomial','a zero exists between a and b if P(a) and P(b) have opposite signs — at least one zero must exist where the graph crosses zero','a polynomial is always continuous'],2)]),
sub('Calculus','Introduction to Limits and Continuity','Students develop an intuitive and rigorous understanding of limits — what they mean, how to evaluate them, and their role as the foundation of calculus.','Khan Academy: Limits Intro','https://www.youtube.com/watch?v=riXcZT2ICjA',[
  ('The limit of f(x) as x → a means ___.',['the value of f(a)','the maximum of f near a','the derivative of f at a','the value that f(x) approaches as x gets arbitrarily close to a — regardless of (and independent of) f(a) itself'],3),
  ('A limit exists at x = a if and only if ___.',['f(a) is defined','the left-hand and right-hand limits both exist and are equal to each other','the function is differentiable at a','the function is continuous at a'],1),
  ('To evaluate lim(x→2) of (x²−4)/(x−2), you ___.',['substitute x = 2 directly (gives 0/0)','conclude the limit does not exist','use L\'Hôpital\'s Rule always','factor: (x−2)(x+2)/(x−2) = x+2 for x≠2, so the limit = 4'],3),
  ('A function f is continuous at x = a if ___.',['f(a) is a large number','f(a) = 0','the derivative exists at a','three conditions hold: f(a) is defined, lim(x→a)f(x) exists, and lim(x→a)f(x) = f(a)'],3),
  ('A removable discontinuity (hole) occurs when ___.',['the limit does not exist at the point','the function goes to infinity','the function is not defined anywhere','the limit exists at x = a but either f(a) is undefined or f(a) ≠ the limit — the discontinuity can be "fixed" by redefining f(a)'],3)]),
sub('Physics','Kinematics in 2D: Projectile Motion','Students analyse projectile motion by decomposing it into independent horizontal and vertical components, applying kinematic equations to each.','Crash Course Physics: Projectile Motion','https://www.youtube.com/watch?v=aY8z2qO44WA',[
  ('In projectile motion, the horizontal and vertical components are independent because ___.',['gravity acts horizontally','air resistance eliminates horizontal motion','horizontal velocity is always zero','gravity only acts vertically — horizontal velocity remains constant (no acceleration), while vertical motion has constant downward acceleration g = 9.8 m/s²'],3),
  ('A projectile launched horizontally from height h has a time of flight determined by ___.',['initial horizontal speed only','only horizontal distance','the angle of launch','the vertical fall: h = ½gt², so t = √(2h/g) — same as a dropped object from the same height'],3),
  ('The range of a projectile (launched at angle θ with speed v₀) is maximised when ___.',['θ = 90°','θ = 30°','θ = 60°','θ = 45° — for a level surface, R = v₀²sin(2θ)/g, maximised when sin(2θ) = 1, i.e., 2θ = 90°'],3),
  ('At the peak of a projectile\'s trajectory, ___.',['both velocity components are zero','horizontal velocity is zero','the projectile stops momentarily','only the vertical component of velocity is zero — horizontal velocity is unchanged throughout'],3),
  ('If a ball is kicked at 20 m/s at 30° above horizontal, the initial vertical component is ___.',['20 m/s','10 m/s (v₀y = 20sin30° = 20 × 0.5 = 10 m/s)','17.3 m/s','10√3 m/s'],1)]),
]),
day(2,[
E('Independent Study: The Novel — Form and Meaning','Students read a major novel independently, analysing how formal choices (narration, structure, style) create meaning rather than just content.',[
  ('The distinction between story (fabula) and discourse (sjuzhet) means ___.',['they are the same in all novels','only the plot matters','discourse is less important than story','story is the raw chronological events; discourse is how those events are arranged and told — great novelists manipulate discourse to shape meaning, pace, and perspective'],3),
  ('Free indirect discourse (FID) in a novel allows ___.',['only third-person narrators to speak','only direct quotation of characters','only interior monologue in first person','a third-person narrator to render a character\'s thoughts and speech without explicit tags — blurring the boundary between narrator and character, creating empathy and irony simultaneously'],3),
  ('A novel\'s structure (chapters, parts, epigraphs) ___.',['is only for practical reading purposes','has no relation to meaning','is always chronological','creates meaning: fragmented structure can mirror a fragmented self; circular structure can suggest entrapment; the placement of chapter breaks shapes pacing and emphasis'],3),
  ('Analysing a novel\'s prose style means ___.',['only counting long sentences','identifying the author\'s country of origin','only noting the vocabulary level','examining sentence length and rhythm, syntax, imagery, diction, tone, and the relationship between these choices and the novel\'s themes and effects'],3),
  ('A sophisticated novel reading at Grade 12 produces ___.',['a plot summary with quotations','only a character description','a thematic overview without formal analysis','an argument about how the novel\'s formal choices create and enrich its meaning — form and content are inseparable'],3)]),
sub('Advanced Functions','Rational Functions: Analysis and Graphing','Students perform complete analysis of rational functions — identifying all asymptotes, holes, intercepts, and behaviour — and graph them without technology.','Khan Academy: Graphing Rational Functions','https://www.youtube.com/watch?v=5TkIe60y2GI',[
  ('To find all features of a rational function, you must ___.',['only find where it equals zero','only find vertical asymptotes','only graph it with technology','factor both numerator and denominator completely to identify zeros, holes, vertical asymptotes, and simplify for horizontal/oblique asymptotes'],3),
  ('A slant (oblique) asymptote exists when ___.',['the denominator degree exceeds the numerator','degrees are equal','the denominator is linear only','the numerator degree is exactly 1 more than the denominator — found by polynomial long division'],3),
  ('For f(x) = (2x² + 3x − 2)/( x − 1), the slant asymptote is found by ___.',['setting x → ∞ in the numerator','dividing 2x² + 3x − 2 by x − 1: 2x + 5 remainder 3, so slant asymptote y = 2x + 5','setting denominator = 0','cancelling x terms'],1),
  ('To sketch a rational function, the correct sequence is ___.',['graph first, find features after','find only the x-intercepts','only find asymptotes','domain → vertical asymptotes/holes → horizontal/oblique asymptote → x-intercepts → y-intercept → behaviour near asymptotes → connect carefully'],3),
  ('The end behaviour of f(x) = (x² + 2)/(x + 1) as x → ±∞ is ___.',['approaches y = x²','approaches y = 1','approaches the horizontal asymptote y = 0','approaches the slant asymptote y = x − 1 (since x² + 2 ÷ (x+1) = x − 1 remainder 3)'],3)]),
sub('Calculus','Derivatives: Definition and Basic Rules','Students develop the concept of the derivative as a limit of difference quotients, and apply the basic differentiation rules (power, constant, sum, difference).','Khan Academy: Derivative Rules','https://www.youtube.com/watch?v=HEH_oKNLgUU',[
  ('The derivative f\'(a) is defined as ___.',['f(a+h) − f(a)','f(a)/h','lim(h→0)[f(a+h) − f(a)]/h — the slope of the tangent line at x = a','f(a+1) − f(a)'],2),
  ('The power rule states d/dx[xⁿ] = ___.',['xⁿ⁻¹','nxⁿ','nxⁿ+1','nxⁿ⁻¹ — bring down the exponent and reduce it by 1'],3),
  ('d/dx[5x³ − 2x + 7] = ___.',['5x² − 2','15x³ − 2','5x³ − 2','15x² − 2 (power rule on each term; constant 7 disappears)'],3),
  ('The derivative of a constant is ___.',['the constant itself','1','undefined','0 — constants have no rate of change'],3),
  ('The derivative f\'(x) represents ___.',['the area under f(x)','f(x) squared','the antiderivative of f(x)','the instantaneous rate of change of f(x) — the slope of the tangent line to the graph of f at any point x'],3)]),
sub('Physics','Forces: Newton\'s Laws in 2D','Students apply Newton\'s three laws to two-dimensional force problems, including inclined planes, connected masses, and friction.','Crash Course Physics: Newtons Laws','https://www.youtube.com/watch?v=kKKM8Y-u7ds',[
  ('For a block on a frictionless inclined plane at angle θ, the acceleration down the incline is ___.',['g','g cosθ','g tanθ','g sinθ — only the component of gravity along the incline acts (mg sinθ = ma, so a = g sinθ)'],3),
  ('Normal force on an inclined plane (angle θ, mass m) is ___.',['mg','mg sinθ','mg tanθ','mg cosθ — perpendicular to the incline surface'],3),
  ('Kinetic friction force equals ___.',['μₛN','μN always','μₖmg always','μₖN — kinetic friction coefficient times normal force, opposing motion'],3),
  ('Two masses m₁ and m₂ connected by a rope over a frictionless pulley: the acceleration is ___.',['(m₁ − m₂)g/(m₁ + m₂)... wait — depends on orientation','g for both','only m₁g','a = (m₁ − m₂)g/(m₁ + m₂) for an Atwood machine — net force divided by total mass'],0),
  ('Newton\'s Third Law states that for every action force there is ___.',['a larger reaction force','no corresponding reaction','a smaller reaction force in the same direction','an equal and opposite reaction force — acting on a DIFFERENT object than the action force'],3)]),
]),
day(3,[
E('Literature: The Tragic Form Across Cultures','Students compare the tragic form in different cultural traditions — Greek tragedy, Shakespearean tragedy, and contemporary tragic narratives — examining what "tragedy" means across time and culture.',[
  ('Greek tragedy (Sophocles, Euripides) differs from Shakespearean tragedy in ___.',['Greek tragedy has no hero','Shakespeare\'s tragedies have no tragic flaws','they are identical in form','Greek tragedy uses a chorus, observes the three unities (time, place, action), explores fate vs. free will through divine will; Shakespeare focuses on individual psychological complexity in a Christian moral framework'],3),
  ('The concept of catharsis (Aristotle) means ___.',['the hero\'s physical death','the villain\'s punishment','the audience\'s purging or clarification of emotions — pity and fear experienced through tragedy serve a therapeutic or enlightening function for the audience','the protagonist\'s recognition of their error'],3),
  ('Anagnorisis (recognition) in Greek tragedy is ___.',['the moment of physical death','only relevant in comedy','a minor plot device','the protagonist\'s moment of terrible recognition — realising the truth of their situation, often connected to hamartia — which may precede but cannot prevent their downfall'],3),
  ('Contemporary tragic narratives (film, novel, theatre) typically ___.',['avoid tragic form entirely','only follow the Greek model','reproduce the Shakespearean model exactly','adapt the tragic form to modern concerns: the tragic hero may be ordinary rather than royal, the forces of doom may be social and psychological rather than divine, and catharsis may be replaced by critique'],3),
  ('Comparing tragic forms across cultures illuminates ___.',['only historical differences','only literary technique','that tragedy is purely a Western form','how different cultures understand fate, justice, individual agency, and what makes human suffering meaningful — tragedy is a cross-cultural form, but its specific expression reflects distinct world views'],3)]),
sub('Advanced Functions','Exponential and Logarithmic Functions: Advanced Applications','Students solve complex exponential and logarithmic equations, apply change of base, and model real phenomena including logistic growth.','Khan Academy: Logarithm Properties','https://www.youtube.com/watch?v=TMmxKZaCqe0',[
  ('The change of base formula log_b(x) = log(x)/log(b) allows ___.',['converting bases only in specific cases','converting only to base 10','only base-2 conversions','evaluating logarithms in any base using a calculator (which typically has only base-10 or base-e), and simplifying logarithmic expressions'],3),
  ('Solve: log₂(x) + log₂(x − 2) = 3',['x = 3 (only valid solution: log₂(x(x−2)) = 3 → x(x−2) = 8 → x²−2x−8 = 0 → (x−4)(x+2) = 0 → x = 4 or x = −2; x = −2 rejected since log is undefined there)','x = 4 — check: log₂(4) + log₂(2) = 2 + 1 = 3 ✓','x = −2','x = 4 or x = −2'],1),
  ('Logistic growth f(t) = L/(1 + ae^(−kt)) models populations because ___.',['it only models exponential growth','it allows unlimited growth','it always decreases','it shows rapid initial growth that slows as the population approaches the carrying capacity L — more realistic than pure exponential growth'],3),
  ('The natural logarithm ln(x) = log_e(x) is especially important because ___.',['e is a round number','ln is easier to calculate','ln has simpler graphs','the number e ≈ 2.718 arises naturally in calculus (as the base of the derivative of exponential functions) — ln is the inverse of e^x, the most important exponential function'],3),
  ('Solve: e^(2x) − 5e^x + 6 = 0',['x = ln2 and x = ln3 (let u = e^x: u² − 5u + 6 = (u−2)(u−3) = 0; u = 2 or 3; e^x = 2 → x = ln2; e^x = 3 → x = ln3)','x = 2 and x = 3','x = ln5','x = 0'],0)]),
sub('Calculus','Derivatives: Product, Quotient, and Chain Rules','Students master the three composite differentiation rules and apply them to increasingly complex functions.','Khan Academy: Chain Rule','https://www.youtube.com/watch?v=0T0QrHO56qg',[
  ('The product rule for d/dx[f(x)g(x)] is ___.',['f\'(x) × g\'(x)','f\'(x)g(x)','f(x)g\'(x)','f\'(x)g(x) + f(x)g\'(x) — differentiate each factor and apply'],3),
  ('The quotient rule for d/dx[f(x)/g(x)] is ___.',['f\'(x)/g\'(x)','[f\'(x)g(x) + f(x)g\'(x)] / [g(x)]²','[f\'g − fg\'] / g²  (low d-high minus high d-low, over low squared)','[f\'(x) − g\'(x)] / g(x)'],2),
  ('The chain rule for d/dx[f(g(x))] is ___.',['f\'(x) × g\'(x)','f\'(g(x))','f(g\'(x))','f\'(g(x)) × g\'(x) — differentiate the outer function at the inner, times the derivative of the inner'],3),
  ('d/dx[(3x² + 1)⁵] = ___.',['5(3x² + 1)⁴','5(6x)⁴','5(3x² + 1)⁴ × 6x (chain rule: outer × derivative of inner)','(3x² + 1)⁵ × 6x'],2),
  ('d/dx[sin(x²)] = ___.',['cos(x²)','sin(2x)','2x cos(x)','2x cos(x²) — chain rule: cos(x²) × 2x'],3)]),
sub('Physics','Work, Energy, and Power: Advanced Applications','Students apply the work-energy theorem, conservation of mechanical energy, and power calculations to complex problems.','Crash Course Physics: Work Energy Power','https://www.youtube.com/watch?v=xNzS1OsPbFg',[
  ('The work-energy theorem states ___.',['work equals force times velocity','work equals potential energy change','net work done on an object equals its change in kinetic energy (W_net = ΔKE)','power equals work divided by displacement'],2),
  ('Conservative forces are those for which ___.',['work depends on the path taken','no energy is stored','friction is the best example','work done is path-independent — only the endpoints matter; mechanical energy is conserved in systems with only conservative forces'],3),
  ('Conservation of mechanical energy applies when ___.',['there is no kinetic energy','only gravity acts','only friction acts','only conservative forces act — total mechanical energy (KE + PE) remains constant'],1),
  ('A 2 kg ball dropped from 5 m hits the ground with kinetic energy ___.',['98 J (KE = mgh = 2 × 9.8 × 5 = 98 J, by conservation of energy)','49 J','10 J','2 × 9.8 × 5 J = 98 J (confirm both methods agree)'],0),
  ('Power is ___.',['force per unit area','energy per unit volume','work times time','the rate of energy transfer or work done: P = W/t = Fv (for constant force parallel to velocity)'],3)]),
]),
day(4,[
E('Writing: Extended Critical Analysis Essay','Students plan and write a 1000+ word critical essay on a literary text, meeting university standards for argument, evidence, and analysis.',[
  ('University literary essays are evaluated primarily on ___.',['the number of sources cited','word count','correct grammar only','the quality of the analytical argument — how specific, arguable, well-supported, and intellectually interesting the thesis is, and how precisely and rigorously it is developed'],3),
  ('A 1000+ word essay requires ___.',['longer paragraphs with more quotations','simply more of the same as shorter essays','only one more body paragraph','more structural complexity: multiple interrelated lines of argument, developed through the essay, requiring careful paragraph sequencing and more sophisticated transitions'],3),
  ('Evidence in a university essay should be ___.',['as long as possible','replaced by paraphrase always','always a minimum of 5 lines','precisely chosen — the smallest portion of text that demonstrates the specific point you are making, embedded grammatically, and always followed by analysis that earns the quotation'],3),
  ('The difference between analysis and description in an extended essay is ___.',['they are the same at university level','description is more academic','analysis only appears in conclusions','description reports what the text does; analysis explains how and why specific choices create specific effects — every paragraph must be driven by analysis, not description'],3),
  ('Concluding a long essay effectively requires ___.',['summarising all body paragraphs in order','repeating the thesis word for word','adding new evidence at the end','synthesising the essay\'s argument, extending the thesis to its larger implications, and leaving the reader with a new perspective or unresolved question — not just restating what has been said'],3)]),
sub('Advanced Functions','Trigonometric Functions: Identities and Equations (Advanced)','Students prove and apply advanced trigonometric identities including compound angle, double angle, and sum-to-product formulas, and solve complex trigonometric equations.','Khan Academy: Trig Identities','https://www.youtube.com/watch?v=T9lt6MZKLck',[
  ('To prove a trigonometric identity, you must ___.',['substitute specific values','start from both sides simultaneously','cross-multiply to eliminate fractions','work on one side only, transforming it to equal the other, using only known identities and algebraic operations — never treating it like an equation to solve'],3),
  ('Prove: sin2x/(1 + cos2x) = tanx. Using sin2x = 2sinxcosx and cos2x = 2cos²x − 1:',['1 + cos2x = 2cos²x; so sin2x/(1+cos2x) = 2sinxcosx/2cos²x = sinx/cosx = tanx ✓','the identity is false','sin2x/1 + cos2x = tanx is trivially true','sin2x = tanx always'],0),
  ('Sum-to-product: sinA + sinB = ___.',['2sin(A+B)cos(A−B)','sin(A+B)','2cos((A+B)/2)sin((A−B)/2)','2sin((A+B)/2)cos((A−B)/2) — a useful formula for adding sine functions'],3),
  ('To solve 2cos²x − cosx − 1 = 0 on [0°, 360°):',['let u = cosx: (2u + 1)(u − 1) = 0; cosx = −1/2 → x = 120°, 240°; cosx = 1 → x = 0°','x = 60° only','x = 0° and 180°','x = 120° only'],0),
  ('The equation sinx = 2 has ___.',['two solutions','infinitely many solutions','no solution — sinx is bounded between −1 and 1 for all real x','one solution at x = 90°'],2)]),
sub('Calculus','Derivatives of Trigonometric and Exponential Functions','Students differentiate sin(x), cos(x), tan(x), e^x, and ln(x), and combine these with the chain rule.','Khan Academy: Derivatives of Trig Functions','https://www.youtube.com/watch?v=_niP0JaOgHY',[
  ('d/dx[sin x] = ___.',['−sin x','sin x','−cos x','cos x'],3),
  ('d/dx[cos x] = ___.',['sin x','cos x','−sin x','−cos x — this is negative, unlike the derivative of sine'],3),
  ('d/dx[e^x] = ___.',['e^(x−1)','xe^(x−1)','1/e^x','e^x — the exponential function e^x is the unique function equal to its own derivative'],3),
  ('d/dx[ln x] = ___.',['ln x','x/ln x','1/x — valid for x > 0','1/(x ln x)'],2),
  ('d/dx[sin(3x²)] = ___.',['cos(3x²)','6x sin(3x²)','3x² cos(3x²)','6x cos(3x²) — chain rule: cos(3x²) × 6x'],3)]),
sub('Physics','Circular Motion and Gravitation','Students analyse uniform circular motion — centripetal acceleration and force — and apply Newton\'s law of universal gravitation.','Crash Course Physics: Circular Motion','https://www.youtube.com/watch?v=bpFK2VCRHUs',[
  ('Centripetal acceleration for uniform circular motion is ___.',['tangential acceleration','v/r','rω','v²/r directed toward the centre — it is the acceleration required to continually change the direction of velocity'],3),
  ('The centripetal force is ___.',['a new type of force','the force of rotation','the outward "centrifugal force"','the net inward force that causes circular motion: F_c = mv²/r — it is provided by real forces such as gravity, tension, or normal force'],3),
  ('Newton\'s law of universal gravitation: F = ___.',['Gm₁m₂/r','Gm₁m₂r²','Gm₁/m₂r²','Gm₁m₂/r² — gravitational force between two masses, inversely proportional to the square of the distance between them'],3),
  ('Gravitational field strength g at Earth\'s surface is approximately 9.8 N/kg because ___.',['it is defined by convention','the Earth rotates','g = GM_E/R_E² — the gravitational field strength is Newton\'s Law applied to one mass at the Earth\'s surface','it is always constant everywhere'],2),
  ('A satellite in circular orbit has ___.',['no gravitational force acting on it','zero speed','both thrust force and gravity','only gravity acting, providing the centripetal force: GM_E m/r² = mv²/r, giving orbital speed v = √(GM_E/r)'],3)]),
]),
day(5,[
E('Media Analysis: Digital Media and Political Communication','Students analyse how digital platforms — social media, podcasts, algorithmic news — have transformed political communication and citizenship.',[
  ('Political communication via social media differs from broadcast media in ___.',['it reaches fewer people','it is always more accurate','it has no political influence','its interactive, many-to-many architecture — anyone can broadcast to thousands; algorithms determine reach; misinformation can spread as fast as truth; echo chambers form algorithmically'],3),
  ('Algorithmic curation of political content can affect democracy by ___.',['only increasing voter turnout','always improving the quality of political debate','eliminating all political bias in media','creating filter bubbles where citizens see primarily content that confirms their existing beliefs, potentially reducing exposure to legitimate opposing perspectives'],3),
  ('Microtargeting in political advertising means ___.',['advertising to the largest possible audience','only using TV advertising','no personalisation in political ads','using detailed personal data (demographics, browsing history, location) to target specific political messages to specific individuals — much more precise than traditional broadcast advertising'],3),
  ('Disinformation campaigns in digital media are effective because ___.',['false information is never shared widely','digital platforms always verify content','most people are incapable of critical thinking','corrections rarely spread as far as the original false claim; outrage drives engagement (and algorithmic amplification); and false information may be deliberately designed to be emotionally compelling and hard to disprove quickly'],3),
  ('A digitally literate citizen evaluates political content by ___.',['sharing immediately if it confirms their views','trusting verified accounts automatically','only reading mainstream media','checking the source, looking for corroboration from multiple independent credible sources, examining who benefits from the claim, and being especially skeptical of content that produces strong emotional reactions'],3)]),
sub('Advanced Functions','Combining Functions: Operations and Compositions','Students perform operations on functions (sum, difference, product, quotient) and compositions, including finding domains of combined functions.','Khan Academy: Composite Functions','https://www.youtube.com/watch?v=z_tEsVMKOjk',[
  ('The domain of (f + g)(x) is ___.',['the domain of f only','the domain of g only','the domain of f union domain of g','the intersection of the domains of f and g — both must be defined'],3),
  ('The domain of f(x) = √x and g(x) = 1/(x−2): find domain of f(g(x)).',['x > 0','x ≥ 2','x < 0','g(x) must be ≥ 0 for √g(x) to exist, so 1/(x−2) ≥ 0, meaning x > 2 (and x ≠ 2) — domain is x > 2'],3),
  ('If f(x) = x² and g(x) = x + 1, then f(g(x)) − g(f(x)) = ___.',['0','x','(x+1)² − (x²+1) = x²+2x+1 − x²−1 = 2x','2x−2'],2),
  ('The notation (f ∘ g)(x) means ___.',['f(x) × g(x)','f(x) + g(x)','f(x)/g(x)','f(g(x)) — apply g first, then f — the order matters and is read right to left in the composition notation'],3),
  ('If f(x) = 2x − 1 and f(g(x)) = 2x + 3, then g(x) = ___.',['2x + 3','x + 3','x + 2 (since 2g(x) − 1 = 2x + 3 → 2g(x) = 2x + 4 → g(x) = x + 2)','x + 4'],2)]),
sub('Calculus','Applications of Derivatives: Tangent Lines and Related Rates','Students find equations of tangent and normal lines to curves, and solve introductory related rates problems.','Khan Academy: Tangent Line Equations','https://www.youtube.com/watch?v=IWcPMJBTDQg',[
  ('The equation of the tangent line to y = f(x) at (a, f(a)) is ___.',['y = f\'(a)','y = f(a)(x − a)','y = f(a)x + b','y − f(a) = f\'(a)(x − a) — point-slope form using the slope from the derivative'],3),
  ('Find the tangent to y = x³ at x = 2.',['y = 3x − 2','y = 12x − 10 (slope = f\'(2) = 3(4) = 12; point = (2, 8); y − 8 = 12(x − 2))','y = 12x + 8','y = 12x'],1),
  ('The normal line to a curve at a point is ___.',['perpendicular to the curve at that point (slope = −1/f\'(a))','parallel to the tangent','the tangent line reflected','the vertical line x = a'],0),
  ('In related rates problems, you differentiate both sides of an equation with respect to ___.',['x only','both x and y','the dependent variable','time (t), using the chain rule to connect rates of change of related quantities'],3),
  ('A spherical balloon is inflated so V = 500 cm³/s. Find dR/dt when R = 5 cm. (V = 4/3πR³)',['dR/dt = 500/(4πR²) = 500/(4π×25) = 5/π ≈ 1.59 cm/s','dR/dt = 500','dR/dt = 4πR²','dR/dt = V/(4πR) = 10/π'],0)]),
sub('Physics','Waves: Transverse, Longitudinal, and Sound','Students examine wave properties (wavelength, frequency, amplitude, speed), the wave equation, and properties of sound.','Crash Course Physics: Waves and Sound','https://www.youtube.com/watch?v=xLbZj5qO_lI',[
  ('The wave equation v = fλ relates ___.',['velocity to force and length','amplitude to frequency','wavelength to period only','wave speed to frequency and wavelength — doubling the frequency halves the wavelength for the same medium'],3),
  ('Transverse waves differ from longitudinal waves in that ___.',['transverse waves are faster','transverse have no amplitude','transverse waves are only in vacuum','in transverse waves, particles vibrate perpendicular to the wave direction (e.g., light, water waves); in longitudinal waves, particles vibrate parallel to the direction of propagation (e.g., sound)'],3),
  ('The Doppler effect explains why ___.',['sound cannot travel through air','waves cannot be reflected','the pitch of a police siren seems to change as it approaches and recedes — the source moves relative to the observer, compressing or stretching the wavelengths','light always appears red-shifted'],2),
  ('Resonance occurs when ___.',['only destructive interference is possible','the driving frequency matches the object\'s natural frequency — producing maximum amplitude oscillations that can be very large (e.g., a singer breaking a glass, a bridge vibrating in wind)','all frequencies are absorbed equally','the amplitude becomes zero'],1),
  ('The speed of sound in air at 20°C is approximately ___.',['3 × 10⁸ m/s (that is the speed of light)','150 m/s','1000 m/s','343 m/s — varies with temperature and medium (faster in warmer air and in liquids/solids than in air)'],3)]),
]),
day(6,[
E('Literature: Poetry — The Lyric Tradition','Students study the development of the lyric poem from the Romantics through Modernism to contemporary practice, examining how lyric poetry constructs a speaking self and addresses fundamental human questions.',[
  ('The lyric poem is distinguished by ___.',['always rhyming','always being about nature','always being short','its expression of personal feeling or thought through a speaking "I" — the lyric creates a sense of intimacy and presence, as if a thinking, feeling consciousness is directly addressed to us'],3),
  ('Romanticism\'s influence on lyric poetry includes ___.',['rejection of all nature imagery','strict adherence to rational argument','avoidance of personal feeling','emphasis on individual imagination, emotional authenticity, the sublimity of nature, and the power of poetry to access truths unavailable to rational analysis'],3),
  ('Modernist lyric poetry (Eliot, Yeats, Stevens) often uses ___.',['straightforward emotional expression','only traditional forms','only simple language','fragmentation, allusion, difficulty, and impersonality — the "persona" of the poem is often distanced or deliberately constructed, rejecting Romantic expressivism for a more ironic, cerebral stance'],3),
  ('Contemporary lyric poetry engages with ___.',['only traditional subjects like love and death','only formal experimentation','only nature as a subject','a vast range of subjects and forms — from personal trauma and identity politics to ecological crisis and digital culture — often in hybrid forms mixing prose and verse'],3),
  ('Close reading a lyric poem involves ___.',['only identifying the rhyme scheme','only determining whether the speaker is happy or sad','only summarising what the poem is about','attending to every word, sound, line break, and formal choice — lyric poetry is maximally compressed, so nothing is accidental'],3)]),
sub('Advanced Functions','Polynomial and Rational Equations: Problem Solving','Students solve higher-degree polynomial equations and applied rational equations, applying the factor theorem, synthetic division, and rational root theorem.','Khan Academy: Polynomial Division','https://www.youtube.com/watch?v=FxHWoUOq2iQ',[
  ('The Rational Root Theorem states ___.',['all roots of a polynomial are rational','irrational roots don\'t exist','a polynomial has n rational roots always','if P(x) has integer coefficients, any rational root p/q (in lowest terms) must have p dividing the constant term and q dividing the leading coefficient'],3),
  ('For P(x) = 2x³ − 3x² − 11x + 6, possible rational roots are ___.',['±1, ±2, ±3, ±6 only','±1, ±2, ±3, ±6, ±1/2, ±3/2 (factors of 6 over factors of 2)','only positive integers','only ±1 and ±6'],1),
  ('Testing P(1) = 2 − 3 − 11 + 6 = −6 ≠ 0; P(3) = 54 − 27 − 33 + 6 = 0. So ___.',['x = 3 is a root; divide to get 2x² + 3x − 2 = (2x−1)(x+2); all roots: x = 3, 1/2, −2','x = 3 only','x = 3 and x = 0','x = 1/2 and x = −2 only'],0),
  ('Solving a rational inequality (e.g., (x−2)/(x+1) > 0) requires ___.',['multiplying both sides by (x+1)','squaring both sides','only testing x = 0','finding critical values (zeros and undefined points), then testing sign in each interval on a number line'],3),
  ('For (x − 2)/(x + 1) > 0, the solution is ___.',['x > 2','x > 2 or x < −1 (positive/positive or negative/negative gives positive ratio)','−1 < x < 2','x < −1'],1)]),
sub('Calculus','Curve Sketching Using Derivatives','Students use the first and second derivative to identify increasing/decreasing intervals, local extrema, concavity, and inflection points.','Khan Academy: Curve Sketching','https://www.youtube.com/watch?v=WIDZFyfaT1I',[
  ('If f\'(x) > 0 on an interval, then f ___.',['is concave up','has a minimum','is decreasing','is increasing on that interval'],3),
  ('A local maximum at x = c requires ___.',['f\'(c) > 0','f\'(c) < 0','f\'(c) = 0 only','f\'(c) = 0 (or f\'(c) undefined) AND f\'changes from positive to negative — the first derivative test'],3),
  ('The second derivative test: if f\'(c) = 0 and f\'\'(c) < 0, then ___.',['x = c is an inflection point','x = c is a local minimum','x = c is always a global maximum','x = c is a local maximum (concave down at c)'],3),
  ('An inflection point occurs where ___.',['f = 0','f\' = 0','the function has a maximum','f\'\' changes sign — concavity changes from up to down or down to up; the curve "bends the other way"'],3),
  ('A complete curve sketch using calculus includes ___.',['only zeros and asymptotes','only maxima and minima','domain, intercepts, asymptotes, increasing/decreasing intervals, local extrema, concavity, and inflection points — all derived algebraically before sketching'],3)]),
sub('Physics','Electricity: Electric Fields and Potential','Students analyse electric fields and electric potential produced by point charges and uniform fields, and relate electric potential to potential energy.','Crash Course Physics: Electric Fields','https://www.youtube.com/watch?v=mdulzEfQJP0',[
  ('The electric field E due to a point charge Q at distance r is ___.',['kQ/r','kQ²/r²','kQr²','kQ/r² directed away from positive charges (Coulomb\'s Law for field strength, by convention field points in the direction of force on a positive test charge)'],3),
  ('Electric potential V at distance r from charge Q is ___.',['kQ/r² (same as field)','kQr','kQ²/r','kQ/r — a scalar (no direction), with potential energy U = qV for a charge q in the field'],3),
  ('The relationship between electric field and electric potential is ___.',['E = V × r','E = V + r','E = V/r only in uniform fields','E = −dV/dx (in 1D) — the field is the negative gradient of the potential; field points from high to low potential'],3),
  ('A positive charge released in a uniform electric field moves ___.',['toward lower potential (in the direction of E, which points from high to low potential)','toward higher potential','perpendicular to field lines','against the field direction'],0),
  ('Electric field lines and equipotential surfaces are ___.',['parallel to each other','only drawn around conductors','the same thing drawn differently','always perpendicular — field lines show the direction of force on a positive charge; equipotential surfaces connect points of equal potential'],3)]),
]),
day(7,[
E('Drama and Theatre: Contemporary Playwriting','Students read and analyse a contemporary Canadian play, examining how playwrights structure dramatic conflict, develop character through dialogue, and use theatrical space.',[
  ('A contemporary Canadian play is likely to engage with ___.',['no Canadian themes','only historical events in theatrical form','only traditional dramatic forms','one or more of: Indigenous land rights and colonialism, immigration and multicultural identity, regional politics, environmental crisis, or LGBTQ+ experience — reflecting Canada\'s contemporary social landscape'],3),
  ('Dialogue in drama does more than convey information — it ___.',['is always realistic conversation','only advances the plot','only establishes character mood','reveals character through what is said, what is NOT said, and HOW it is said; subtext (the meaning beneath the surface) is often more important than the words themselves'],3),
  ('Non-realistic staging in contemporary theatre (abstract sets, stylised movement) ___.',['is always unsuccessful with audiences','requires no interpretation','is used to avoid the cost of realistic sets','creates meaning by refusing the illusion of realism — drawing attention to theatricality itself and inviting audiences to engage imaginatively rather than passively accept an illusion'],3),
  ('Reading a play script for performance means ___.',['only reading the dialogue','only finding the themes','ignoring stage directions','imagining all dimensions: the spatial relationships, physicality, rhythm of speech, silences, and theatrical choices that a director, designer, and actors would bring to the text'],3),
  ('Theatre\'s unique power compared to film or prose is ___.',['better special effects','permanent record of performance','greater budget for production design','liveness — the co-presence of performer and audience creates an unrepeatable event, a shared experience of risk and immediacy that no recording can replicate'],3)]),
sub('Advanced Functions','Rates of Change: Introduction to Calculus Concepts','Students explore the concept of instantaneous rate of change as a limit, preparing the foundation for Grade 12 Calculus and making explicit the connection between Advanced Functions and Calculus.','Khan Academy: Average vs Instantaneous Rate of Change','https://www.youtube.com/watch?v=BVZNMm6GaKw',[
  ('Average rate of change of f(x) over [a, b] is ___.',['f\'(a)','f(a)/f(b)','[f(b) − f(a)] × (b − a)','[f(b) − f(a)]/(b − a) — the slope of the secant line through (a, f(a)) and (b, f(b))'],3),
  ('Instantaneous rate of change at x = a is ___.',['[f(b)−f(a)]/(b−a) for any b','f(a)/a','f(a+1) − f(a)','lim(h→0)[f(a+h) − f(a)]/h — the slope of the tangent line at a, i.e., the derivative f\'(a)'],3),
  ('If f(x) = x², the average rate of change on [2, 2+h] is ___.',['4 + h (= [f(2+h) − f(2)]/h = [(2+h)² − 4]/h = [4+4h+h²−4]/h = 4+h)','2h','4h','4 + 2h'],0),
  ('As h → 0 in the expression (4 + h), the instantaneous rate of change at x = 2 is ___.',['4 — confirming f\'(x) = 2x, f\'(2) = 4','2h','h','0'],0),
  ('Understanding rate of change prepares you for calculus by ___.',['replacing all calculus learning','making calculus unnecessary','only being relevant in physics','establishing the limit concept — derivatives are defined as limits of difference quotients, so deep understanding of rates of change makes the formal definition of derivative intuitive rather than arbitrary'],3)]),
sub('Calculus','Optimisation: Maximum and Minimum Problems','Students apply derivatives to find maximum and minimum values in applied context problems — geometry, economics, and physics.','Khan Academy: Optimization Problems','https://www.youtube.com/watch?v=bG1v9tGTIZk',[
  ('To solve an optimisation problem with calculus, the steps are ___.',['sketch and guess','differentiate directly without identifying the function','only apply the second derivative test','define variables and constraints, write the objective function (what to optimise), reduce to one variable using constraints, differentiate, set to zero, find candidates, verify global extremum'],3),
  ('A farmer has 200 m of fencing to enclose a rectangular field against a barn (one side free). Maximise the area. If x is the side away from the barn:',['A = 200x − 2x², A\'= 200 − 4x = 0, x = 50, width = 100, A_max = 5000 m²','A = x × 200 − x','x = 100 gives maximum','x = 50 and area = 50 × 100 = 5000 m²'],0),
  ('The second derivative test confirms a maximum when ___.',['f\'\'(c) = 0','f\'\'(c) is undefined','f\'\'(c) > 0 (concave up — local minimum)','f\'\'(c) < 0 (concave down at the critical point — local maximum)'],3),
  ('In an optimisation problem, endpoints of the domain must be checked because ___.',['endpoints always give extrema','critical points are always the answer','global extrema only occur at critical points','the global maximum or minimum may occur at an endpoint of the feasible domain, not at an interior critical point'],3),
  ('Optimisation in real life includes ___.',['only mathematical problems','no economic applications','only geometric problems','minimising cost, maximising revenue, finding the most efficient shape for a container, minimising material use, maximising the strength of a structure — calculus is the tool of choice'],3)]),
sub('Physics','Electric Circuits: Current, Resistance, and Ohm\'s Law','Students analyse DC electric circuits — current, voltage, resistance, Ohm\'s Law, series and parallel circuits, and power dissipation.','Crash Course Physics: Electric Circuits','https://www.youtube.com/watch?v=g-wjP1otQWI',[
  ('Ohm\'s Law states ___.',['V = IR²','R = V × I','I = V + R','V = IR — voltage equals current times resistance; a linear relationship for ohmic conductors'],3),
  ('In a series circuit, ___.',['voltage is the same across all components','resistance decreases','current divides','current is the same through all components; total resistance = sum of individual resistances; voltage divides'],0),
  ('In a parallel circuit, ___.',['voltage divides across branches','current is the same in all branches','total resistance is the sum of all resistances','voltage is the same across all branches; current divides; 1/R_total = 1/R₁ + 1/R₂ + ...'],3),
  ('Power dissipated in a resistor is ___.',['P = I/R','P = IR²','P = V/I','P = IV = I²R = V²/R — three equivalent expressions, all valid for any resistor obeying Ohm\'s Law'],3),
  ('Adding a resistor in parallel to a circuit ___.',['increases total resistance','doesn\'t affect total resistance','only changes the voltage','decreases total resistance — 1/R_total = 1/R₁ + 1/R₂ means R_total is always less than either individual resistance'],3)]),
]),
day(8,[
E('Writing: The University Application Process and Personal Writing','Students write personal statements and supplementary essays for university applications, applying their Grade 12 writing skills to genuine high-stakes contexts.',[
  ('A university personal statement is most effective when ___.',['it lists every achievement in your life','it sounds like every other applicant','it focuses only on grades','it reveals how you think — through a specific story or question that shows your intellectual curiosity, growth, and genuine engagement with ideas'],3),
  ('Showing rather than telling in a personal statement means ___.',['never making claims about yourself','avoiding personal stories','only using achievements','instead of saying "I am passionate about biology," describing the specific moment, question, or observation that sparked that passion — concrete specificity is more persuasive than self-description'],3),
  ('Tailoring a supplementary essay to a specific university or program requires ___.',['copying your main personal statement','generic statements about the school','avoiding mention of specific courses','genuine research — knowing specific programs, professors, courses, or approaches at that institution and explaining how they connect to your specific intellectual interests'],3),
  ('The most common fatal flaw in university personal writing is ___.',['being too specific','mentioning personal interests','having too unique a perspective','being generic — writing could apply to any student, at any school, in any program — producing no sense of who this specific person is or why this specific school is right for them'],3),
  ('Your personal statement is most valuable to you personally because ___.',['it guarantees admission','it impresses admission officers','only the grade matters','it requires you to reflect seriously on who you are, what you care about, and where you want to go — the act of writing it is itself valuable, not just the finished product'],3)]),
sub('Advanced Functions','Discrete Functions: Advanced Sequences, Series, and Financial Math','Students apply geometric series formulas to financial mathematics — annuities, mortgages, and investment growth — with university-preparatory rigour.','Khan Academy: Geometric Series Formula','https://www.youtube.com/watch?v=RMa1QSEfzVA',[
  ('The future value of an annuity (regular payment R, interest rate i per period, n periods) is ___.',['FV = R × n','FV = R(1+i)ⁿ','FV = R × i × n','FV = R[(1+i)ⁿ − 1]/i — a geometric series: each payment earns compound interest for a different number of periods'],3),
  ('If you invest $200/month at 6%/year (0.5%/month) for 30 years, the future value is ___.',['200 × 360 = $72,000','$200 × (1.005)^360','200[(1.005)^360 − 1]/0.005 ≈ $200,903 — compound interest dramatically amplifies regular saving','200 × 0.005 × 360'],2),
  ('The present value of an annuity formula is ___.',['PV = R × n','PV = R/i','PV = R(1+i)ⁿ/i','PV = R[1 − (1+i)^(−n)]/i — how much a series of future payments is worth today'],3),
  ('A mortgage is a ___.',['future value of an annuity problem','growing annuity','perpetuity','present value of an annuity problem — the loan amount is the PV; monthly payments are R; solving for R gives the payment size'],3),
  ('The formula for present value of a perpetuity (payment R, rate i, forever) is ___.',['PV = Ri','PV = R × ∞','PV = R/i — as n → ∞ in the annuity formula, (1+i)^(−n) → 0','PV = R(1+i)/i'],2)]),
sub('Calculus','Integration: The Antiderivative and Indefinite Integrals','Students are introduced to integration as the reverse of differentiation, applying the power rule for integration and the constant of integration.','Khan Academy: Antiderivatives and Indefinite Integrals','https://www.youtube.com/watch?v=mB7DGEMb0og',[
  ('The antiderivative (indefinite integral) of f(x) is ___.',['f\'(x)','f(x) − C','f(x)²/2','F(x) such that F\'(x) = f(x); written ∫f(x)dx = F(x) + C where C is the constant of integration'],3),
  ('The power rule for integration: ∫xⁿ dx = ___.',['xⁿ/n + C','nxⁿ⁻¹','xⁿ⁺¹ + C','xⁿ⁺¹/(n+1) + C for n ≠ −1'],3),
  ('∫(3x² − 4x + 5) dx = ___.',['6x − 4','3x³ − 4x² + 5x','x³ − 2x² + 5x + C','x³ − 2x² + 5x + C — integrate term by term using the power rule'],3),
  ('The constant of integration C appears because ___.',['integration is imprecise','every integral is different','C equals zero always','any constant differentiates to zero, so infinitely many functions have the same derivative — C represents the "lost" information about the original function\'s vertical shift'],3),
  ('∫sin(x) dx = ___.',['cos(x) + C','−cos(x) + C — since d/dx[−cos(x)] = sin(x)','sin(x) + C','−sin(x) + C'],1)]),
sub('Physics','Magnetic Fields and Forces','Students examine magnetic fields produced by current-carrying conductors, and the force on a current or moving charge in a magnetic field.','Crash Course Physics: Magnetic Fields','https://www.youtube.com/watch?v=s94suB5uLWw',[
  ('The force on a charge q moving with velocity v in a magnetic field B is ___.',['F = qvB (this is the magnitude when v ⊥ B)','F = qB/v','F = mv/qB','F = qv × B (vector cross product) — magnitude F = qvB sinθ, direction given by the right-hand rule'],3),
  ('A charged particle moving perpendicular to a uniform magnetic field follows ___.',['a straight line','a parabolic path','a spiral path along B','a circular path — the magnetic force is always perpendicular to velocity, providing centripetal force without doing work'],3),
  ('The force on a current-carrying wire of length L in field B (current I, angle θ) is ___.',['F = IL/B','F = IB/L','F = I/LB','F = BIL sinθ — the force on a current equals the force on the moving charges per unit length times the length'],3),
  ('Two parallel wires carrying current in the same direction ___.',['repel each other','do not exert forces on each other','rotate around each other','attract each other — the magnetic field of each wire exerts an attractive force on the current in the other'],3),
  ('The right-hand rule for a solenoid: point fingers in the direction of current wrap, thumb points ___.',['in the direction of current flow','toward the south pole','at 90° to field','toward the north pole — the solenoid\'s magnetic field inside points in the direction of the thumb'],3)]),
]),
day(9,[
E('Independent Reading: Postmodern Literature','Students read a postmodern novel or short fiction collection, examining metafiction, fragmentation, unreliable narration, and postmodern challenges to stable meaning.',[
  ('Postmodern literature challenges ___.',['all previous narrative techniques without exception','only the use of irony','the idea that literature can accurately represent reality','the concepts of stable, knowable truth and coherent identity — postmodern texts often question the authority of the narrator, the reliability of language, and the very possibility of authentic selfhood'],3),
  ('Metafiction is ___.',['fiction about real events presented as fiction','only experimental prose poetry','only found in postmodern novels','fiction that self-consciously draws attention to its own artifice — reminding readers they are reading a constructed text, often by having narrators comment on the act of storytelling'],3),
  ('Intertextuality in postmodern fiction means ___.',['plagiarism from other works','only references to classical literature','only quoting other texts directly','the way a text is built from and in dialogue with other texts — quotations, allusions, parody, pastiche — blurring the boundaries between "original" and "borrowed" material'],3),
  ('Pastiche differs from parody in that ___.',['pastiche has no relationship to prior works','pastiche is always comic','they are identical','pastiche imitates a style without the critical distance of parody — it celebrates or mourns a style rather than mocking it; Fredric Jameson saw pastiche as the dominant mode of postmodern culture'],3),
  ('Reading postmodern fiction productively requires ___.',['abandoning all interpretive frameworks','accepting that meaning is completely arbitrary','only reading plot summaries','tolerating and enjoying ambiguity — learning to read with pleasure the way meaning is deferred, multiplied, and complicated rather than seeking a definitive single meaning'],3)]),
sub('Advanced Functions','Introduction to Vectors','Students are introduced to vectors — geometric and component representations, operations, dot product, and applications to displacement and work.','Khan Academy: Vectors Introduction','https://www.youtube.com/watch?v=fNk_zzaMoSs',[
  ('A vector differs from a scalar in that ___.',['vectors are always larger','vectors have no application in physics','scalars can be negative','a vector has both magnitude and direction (e.g., displacement, velocity, force); a scalar has only magnitude (e.g., distance, speed, mass)'],3),
  ('Two vectors a = (a₁, a₂) and b = (b₁, b₂) are added by ___.',['multiplying components','taking the average of each component','subtracting components','adding corresponding components: a + b = (a₁+b₁, a₂+b₂) — equivalent to the geometric tip-to-tail rule'],3),
  ('The dot product a · b = ___.',['|a| × |b| (this is only the magnitude part)','a₁b₂ + a₂b₁','a × b (vector cross product)','a₁b₁ + a₂b₂ = |a||b|cosθ — a scalar that captures the "same-direction" component of two vectors'],3),
  ('Two vectors are perpendicular if and only if ___.',['their magnitudes are equal','one has zero magnitude','they are in the same direction','their dot product equals zero — cosθ = 0 when θ = 90°'],3),
  ('The work done by force F over displacement d is ___.',['F × d (scalar)','F + d','|F| × |d|','W = F · d = |F||d|cosθ — work is the dot product; only the component of force in the direction of displacement does work'],3)]),
sub('Calculus','Definite Integrals and the Fundamental Theorem of Calculus','Students compute definite integrals, apply the Fundamental Theorem of Calculus, and interpret definite integrals as areas.','Khan Academy: Fundamental Theorem of Calculus','https://www.youtube.com/watch?v=9vgCMNHPScU',[
  ('The Fundamental Theorem of Calculus Part 1 states ___.',['integration and differentiation are unrelated','∫f(x)dx can only be approximated','∫f(x)dx from a to a equals 1','if F\'(x) = f(x), then ∫[a to b]f(x)dx = F(b) − F(a) — connecting the antiderivative to the area under the curve'],3),
  ('The definite integral ∫[a to b]f(x)dx represents ___.',['f(b) − f(a)','the derivative of f at the midpoint','the net signed area between the curve y = f(x) and the x-axis from x = a to x = b (negative where f is below the x-axis)','the average value of f'],2),
  ('∫[0 to 3](2x + 1)dx = ___.',['[x² + x] from 0 to 3 = (9+3) − (0+0) = 12','2x² + x','3 × 3 = 9','6'],0),
  ('FTC Part 2 (Leibniz Rule): d/dx[∫[a to x]f(t)dt] = ___.',['∫[a to x]f\'(t)dt','F(x) − F(a)','f(x) − f(a)','f(x) — differentiating the area function recovers the original integrand'],3),
  ('The area between two curves f(x) and g(x), where f ≥ g, from a to b is ___.',['∫[a to b]f(x)dx − ∫[a to b]g(x)dx = ∫[a to b][f(x) − g(x)]dx','∫f(x) × g(x)dx','∫f(x)dx × ∫g(x)dx','[f(b)−g(b)] − [f(a)−g(a)]'],0)]),
sub('Physics','Electromagnetic Induction','Students examine Faraday\'s Law of electromagnetic induction, Lenz\'s Law, and applications including transformers and generators.','Crash Course Physics: Electromagnetic Induction','https://www.youtube.com/watch?v=pQp6bmJPU_0',[
  ('Faraday\'s Law states that an EMF is induced in a conductor when ___.',['current flows through it','it is heated','it is placed in a constant magnetic field','the magnetic flux through it changes — the induced EMF equals the rate of change of flux: EMF = −dΦ/dt'],3),
  ('Lenz\'s Law states that the induced current flows in a direction that ___.',['amplifies the change causing it','has no relation to the cause','is always clockwise','opposes the change in magnetic flux — a consequence of energy conservation: the induced current always acts to maintain the existing flux'],3),
  ('An electric generator works by ___.',['converting electrical energy to mechanical energy (that is a motor)','using a battery to create magnetic flux','using nuclear fusion','rotating a coil in a magnetic field — changing magnetic flux induces an EMF, converting mechanical energy to electrical energy'],3),
  ('A transformer steps up voltage by ___.',['using stronger magnets','using DC current (transformers require AC)','having fewer primary turns','having more secondary turns than primary turns — V_s/V_p = N_s/N_p; stepping up voltage steps down current (power conservation: V_p I_p = V_s I_s)'],3),
  ('The reason high-voltage transmission lines are used to send electricity across long distances is ___.',['high voltage is safer','high voltage doesn\'t need towers','only historical convention','at high voltage, the current is lower (P = IV), so power loss (P_loss = I²R) in the wires is minimised — transformers make this practical with AC'],3)]),
]),
day(10,[
E('Literature: Comparative Canadian and World Literature','Students compare Canadian literature with a world text, analysing how place, history, and culture shape literary form and theme.',[
  ('Comparative literature across cultures reveals ___.',['only surface-level differences','only surface-level similarities','that all literature is the same beneath cultural differences','both universal human concerns (love, death, justice, belonging) and radically different ways of understanding and representing those concerns — the comparison enriches both texts'],3),
  ('Canadian literature is shaped by ___.',['only multiculturalism','only Quebec-English tensions','only the landscape','a unique combination of colonial history, vast geography, proximity to the US, two official languages, Indigenous presence, and ongoing waves of immigration — producing a literature of settlement, survival, and identity'],3),
  ('The concept of "writing back" (from post-colonial theory) means ___.',['only Indigenous writing','answering letters','only about rejecting Western literature','texts from formerly colonised cultures engaging with, subverting, or transforming the literary traditions of the colonising culture — rewriting familiar narratives from marginalised perspectives'],3),
  ('A sophisticated comparison of two texts examines ___.',['only their plots','only their dates of publication','only whether one is better than the other','how each text\'s formal choices, cultural context, and thematic concerns illuminate the other — finding meaningful connections and tensions that reveal something about both'],3),
  ('The value of global and comparative literature for Canadian students is ___.',['only preparation for international travel','only useful for English majors','no connection to Canadian identity','it places Canada in a global conversation — students discover both what is distinctive about Canadian literature and what connects it to the broader human story'],3)]),
sub('Advanced Functions','Proof and Mathematical Reasoning','Students examine mathematical proof — direct proof, proof by contradiction, and mathematical induction — developing the formal reasoning skills required for university mathematics.','Khan Academy: Mathematical Induction','https://www.youtube.com/watch?v=wblW_M_HVQ8',[
  ('A direct proof establishes a theorem by ___.',['testing many specific cases','showing the opposite leads to a contradiction','finding a counterexample','starting from known axioms and definitions, and deriving the theorem through valid logical steps'],3),
  ('Proof by contradiction assumes ___.',['the theorem is trivially true','the opposite of the theorem, then derives a logical impossibility — proving the original theorem must be true','only that algebra is valid','the theorem is sometimes false'],1),
  ('Mathematical induction proves a statement P(n) for all n ≥ 1 by ___.',['checking P(n) for n = 1 to 100','proving P(n) is true for some large n','only checking P(1)','proving P(1) (base case) and proving that if P(k) is true, then P(k+1) is also true (inductive step) — together, these imply P(n) is true for all n'],3),
  ('Use induction to prove 1 + 2 + ... + n = n(n+1)/2. The inductive step shows: if 1+...+k = k(k+1)/2, then 1+...+k+(k+1) = ___.',['k(k+1)/2 + (k+1) = (k+1)(k+2)/2 — which is the formula for n = k+1 ✓','k²+k/2','k(k+1)','(k+1)(k+1)/2'],0),
  ('A single counterexample ___.',['proves a theorem in all other cases','has no significance in mathematics','strengthens a theorem by eliminating one case','disproves a universal statement ("for all n, P(n)") — you only need one example where the statement fails to prove it is not universally true'],3)]),
sub('Calculus','Applications of Integration: Area and Volume','Students calculate areas under curves, between curves, and volumes of solids of revolution.','Khan Academy: Volume of Solids of Revolution','https://www.youtube.com/watch?v=R_aqSL-q6_8',[
  ('The area between y = x² and y = x from 0 to 1 is ___.',['∫[0 to 1](x − x²)dx = [x²/2 − x³/3] from 0 to 1 = 1/2 − 1/3 = 1/6','∫x² dx','1/4 − 1/3 = −1/12','1 − 1/3 = 2/3'],0),
  ('The disc method for volume of revolution around the x-axis gives ___.',['V = 2π∫x f(x)dx','V = π∫[f(x)]² dx from a to b — summing circular cross-sections of radius f(x)','V = ∫f(x)dx','V = π∫f(x)dx'],1),
  ('The shell method for volume rotated around the y-axis gives ___.',['V = π∫f(x)²dx','V = ∫f(x)dx','V = 2π∫x f(x)dx from a to b — summing cylindrical shell volumes','V = 2∫f(x)dx'],2),
  ('Find the volume when y = √x from 0 to 4 is rotated around the x-axis.',['V = π∫[0 to 4](√x)² dx = π∫[0 to 4]x dx = π[x²/2] from 0 to 4 = 8π','V = π × 4','V = 4π','V = 16π'],0),
  ('Applications of integration in real life include ___.',['no applications outside mathematics','only physics problems','only area under parabolas','probability distributions, finding work done by variable forces, computing areas of irregular shapes, and calculating volumes of any solid with known cross-sections'],3)]),
sub('Physics','Modern Physics: Special Relativity','Students examine Einstein\'s special relativity — postulates, time dilation, length contraction, mass-energy equivalence, and experimental evidence.','Crash Course Physics: Special Relativity','https://www.youtube.com/watch?v=AInCqm5nCzw',[
  ('Einstein\'s two postulates of special relativity are ___.',['matter is energy; time is space','gravity warps space; light bends around mass','only one is needed','(1) the laws of physics are identical in all inertial frames; (2) the speed of light c is constant in all inertial frames regardless of source or observer motion'],3),
  ('Time dilation means ___.',['clocks in motion run faster','time passes at the same rate for all observers','only GPS satellites are affected','a clock in motion relative to an observer runs slower than one at rest — the moving clock measures less elapsed time: Δt\' = γΔt₀ where γ = 1/√(1 − v²/c²)'],3),
  ('Length contraction means ___.',['objects appear smaller due to perspective','only length perpendicular to motion contracts','all lengths change equally','objects moving at speed v appear shorter along the direction of motion: L = L₀/γ — at relativistic speeds objects are compressed in the direction of travel'],3),
  ('E = mc² means ___.',['mass and energy are always the same','only radioactive materials have rest energy','nuclear energy is impossible to harness','mass is a form of energy — a tiny mass corresponds to enormous energy (c² ≈ 9 × 10¹⁶ J/kg); this equivalence explains nuclear energy and pair production'],3),
  ('Evidence for special relativity includes ___.',['no experimental evidence exists','only thought experiments','only GPS corrections','muon lifetime: muons created in upper atmosphere have insufficient lifetime to reach Earth at c — but time dilation means they age slowly relative to us, and we observe them at sea level'],3)]),
]),
day(11,[
E('Writing: The Argumentative Essay on a Social Issue','Students write a well-researched argumentative essay on a contemporary social or political issue, integrating sources, acknowledging counterarguments, and making an original contribution.',[
  ('A strong argumentative essay on a social issue must ___.',['avoid all statistics','only present one side','include emotional appeals only','engage with the strongest version of the opposing view (steelmanning), not a weak caricature — and explain why your position is more defensible despite the counterargument'],3),
  ('Reliable sources for a social issues essay include ___.',['only news sources you agree with','any website with "org" in the domain','only primary sources','peer-reviewed research, government data, established journalism organisations, expert commentary, and primary sources — evaluated for methodology, transparency, and independence'],3),
  ('Correlation vs. causation in social science arguments: finding that A and B are correlated means ___.',['A always causes B','B must cause A','they are not related','A and B vary together, but this could be because A causes B, B causes A, a third factor causes both, or the correlation is coincidental — more evidence is needed to establish causation'],3),
  ('Academic integrity in a social issues essay requires ___.',['only using your own knowledge','only paraphrasing to avoid citation','never using sources','citing all sources of information, ideas, and argument (whether quoted or paraphrased), distinguishing your own claims from sourced claims, and being transparent about the evidential basis of all arguments'],3),
  ('The most important quality of an argumentative essay on a controversial topic is ___.',['passionate expression of opinion','length and number of sources','an absence of counterarguments','intellectual honesty — acknowledging uncertainty where it exists, representing opposing views fairly, and grounding your argument in evidence rather than only in conviction'],3)]),
sub('Advanced Functions','Functions Review: Connecting All Function Families','Students synthesise the entire Advanced Functions course, connecting all function families and preparing for final assessment.','Khan Academy: Advanced Functions Review','https://www.youtube.com/watch?v=LkwT1GQVJP8',[
  ('The fundamental difference between polynomial and rational functions is ___.',['degree only','number of terms','they are always different in shape','rational functions involve division by a variable expression, creating domain restrictions (vertical asymptotes or holes) absent in polynomials'],3),
  ('Exponential and logarithmic functions are most important because ___.',['they are easy to calculate','they are aesthetically pleasing','they model phenomena that are only approximately linear','they model phenomena where a constant percentage change occurs per unit time — population growth, radioactive decay, compound interest, pH, the Richter scale'],3),
  ('Trigonometric functions are unique among function families in that ___.',['they only model sound','they have no algebraic properties','they are only defined for angles','they are periodic — they repeat their values at regular intervals, making them essential for modelling oscillatory and cyclical phenomena throughout physics and engineering'],3),
  ('Vector operations extend functions by ___.',['adding direction to algebra','eliminating scalar quantities','replacing all other functions','allowing mathematical description of quantities that have both magnitude and direction — force, displacement, velocity — enabling 2D and 3D physics and geometry'],3),
  ('A student who has mastered Advanced Functions can ___.',['only solve the types of problems they\'ve seen before','not extend to calculus','only work in pure mathematics','see a mathematical relationship and immediately identify: what type of function? What are its key features? What algebraic technique applies? What does its graph look like? — fluent pattern recognition across all function families'],3)]),
sub('Calculus','Calculus of Exponential and Logarithmic Functions','Students differentiate and integrate e^(ax), ln(x), and related functions, and apply these to growth/decay problems.','Khan Academy: Derivatives of Exponential Functions','https://www.youtube.com/watch?v=MKQR_acrFOA',[
  ('d/dx[e^(ax)] = ___.',['ae^x','e^(ax)','a × e^(ax) — chain rule: derivative of outer (e^u) times derivative of inner (a)','e^(ax)/a'],2),
  ('d/dx[ln(ax)] = ___.',['a/x','ln(a)/x','a × ln(x)','1/x — since ln(ax) = ln(a) + ln(x), and ln(a) is a constant with derivative 0'],3),
  ('∫e^(3x) dx = ___.',['3e^(3x) + C','e^(3x)/3 + C — anti-chain-rule: divide by the inner derivative','e^(3x) + C','3e^x + C'],1),
  ('∫(1/x) dx = ___.',['x^(−2)/(−2) + C','undefined','−1/x² + C','ln|x| + C — the integral of 1/x is the natural log (valid for x > 0; the absolute value handles x < 0)'],3),
  ('A population grows at a rate proportional to its size: dP/dt = kP. The solution is ___.',['P(t) = P₀ + kt','P(t) = P₀e^(kt) — solving the separable differential equation dP/P = k dt → ln P = kt + C → P = P₀e^(kt)','P(t) = P₀(kt)','P(t) = ke^(P₀t)'],1)]),
sub('Physics','Nuclear Physics and Elementary Particles','Students examine nuclear reactions (fission and fusion), binding energy, and an introduction to the Standard Model of particle physics.','Crash Course Physics: Nuclear Physics','https://www.youtube.com/watch?v=nRmBsxBpTjs',[
  ('Nuclear fission involves ___.',['combining light nuclei to form heavier ones','radioactive beta decay','only gamma emission','splitting a heavy nucleus (e.g., U-235) into two smaller nuclei, releasing neutrons and a large amount of energy — exploited in nuclear reactors and weapons'],3),
  ('Nuclear fusion involves ___.',['splitting heavy nuclei','only proton-electron collisions','no energy release','combining light nuclei (e.g., hydrogen isotopes) to form a heavier nucleus, releasing enormous energy — the process powering stars and pursued for clean energy on Earth'],3),
  ('Mass defect and binding energy: the mass of a nucleus is ___.',['equal to the sum of its parts','greater than the sum of its parts','impossible to measure','slightly less than the sum of its constituent protons and neutrons — the "missing" mass is the binding energy (E = mc²): this is the energy released when the nucleus forms'],3),
  ('The Standard Model of particle physics describes ___.',['only the structure of atoms','only electromagnetic forces','only gravity and electromagnetism','the fundamental particles (quarks, leptons) and forces (electromagnetic, strong nuclear, weak nuclear) that make up all matter — gravity is not yet unified in the Standard Model'],3),
  ('The Higgs boson, discovered in 2012, is significant because ___.',['it creates all mass in the universe','it is the force carrier of gravity','it was already predicted by general relativity','it is the field particle associated with the Higgs field, which gives fundamental particles their mass — confirming the Standard Model\'s prediction after 50 years of searching'],3)]),
]),
day(12,[
E('Media: Creating a Digital Portfolio','Students curate, design, and reflect on a digital portfolio of their best work across Grade 12, developing skills in curation, self-presentation, and digital literacy.',[
  ('A digital portfolio differs from a print portfolio in that ___.',['it is always better','it can include only digital work','it never includes reflection','it can be hyperlinked, multimedia, and publicly accessible — connecting written work to visual, audio, and video media in ways a print portfolio cannot'],3),
  ('Curating a portfolio requires ___.',['including everything you\'ve produced','only including error-free work','only including the most recent work','deliberate selection based on criteria: which pieces best demonstrate your range, growth, and strongest capabilities — curation is itself a creative and analytical act'],3),
  ('The reflective statement in a portfolio item ___.',['describes what grade you received','only explains what the piece is about','is optional and minor','explains why you selected this piece, what it demonstrates about your thinking and skills, and what you would do differently — metacognition applied to writing'],3),
  ('Designing a digital portfolio involves ___.',['only choosing a colour scheme','no aesthetic choices','no connection to writing skills','decisions about organisation, hierarchy, visual design, and navigation that reflect the same principles as good writing: clarity, purpose, coherence, and attention to audience'],3),
  ('The most important quality in a digital portfolio for university or career purposes is ___.',['the most elaborate visual design','only the most technical work','as many pieces as possible','authentic evidence of your thinking — not just correct answers but genuine intellectual engagement, growth, and the distinctive qualities of your mind'],3)]),
sub('Advanced Functions','Exam Preparation: Comprehensive Review','Students complete comprehensive review of all Advanced Functions content in preparation for final assessment.','Khan Academy: Advanced Math Review','https://www.youtube.com/watch?v=jKrEFOTScwU',[
  ('Find all zeros of P(x) = x⁴ − 5x² + 4.',['x = ±1 and x = ±2 (factor as (x²−1)(x²−4) = (x−1)(x+1)(x−2)(x+2))','x = 1 and x = 4 only','x = ±2 only','x = ±√5'],0),
  ('Solve log₃(x + 2) + log₃(x) = 2.',['x = 1 (log₃(x(x+2)) = 2 → x²+2x = 9 → x²+2x−9 = 0... wait: x²+2x = 9 → x = (−2+√40)/2 ≈ 1.16; let me use exact: x²+2x−9=0 → x = (−2+√40)/2)','x = 3','x = 9','x = 7'],0),
  ('The graph of f(x) = (x²−9)/(x−3) has ___.',['a vertical asymptote at x = 3','a zero at x = −3 and a hole at x = 3 (since (x²−9) = (x−3)(x+3), the (x−3) cancels leaving x+3 with a hole at x=3)','a zero at x = 3','asymptotes at x = 3 and x = −3'],1),
  ('A vector a = (3, −4) has magnitude ___.',['7','1','√7','5 (|a| = √(9+16) = √25 = 5)'],3),
  ('For a geometric series with t₁ = 2, r = −1/2, find S∞.',['4/3 (S∞ = t₁/(1−r) = 2/(1+1/2) = 2/(3/2) = 4/3)','2','4','1'],0)]),
sub('Calculus','Differential Equations: Separable and Initial Value Problems','Students solve separable differential equations and apply them to growth, decay, and Newton\'s Law of Cooling.','Khan Academy: Separable Differential Equations','https://www.youtube.com/watch?v=H0VEL9TFjqw',[
  ('A separable differential equation has the form ___.',['dy/dx = f(x) + g(y)','d²y/dx² = f(y)','dy/dx = f(x)g(y) — the variables can be separated: dy/g(y) = f(x)dx','dy/dx = f(x)/g(x)'],2),
  ('To solve dy/dx = 2xy, separate variables: ___.',['dy/dx = 2xy → dy = 2xy dx → integrate both sides','dy/y = 2x dx → ∫dy/y = ∫2x dx → ln|y| = x² + C → y = Ae^(x²)','dy = y dx → y = e^x','dy/dx = y²'],1),
  ('An initial condition (e.g., y(0) = 5) determines ___.',['the form of the differential equation','only the constant of integration C in the general solution — giving a particular solution','whether the equation is separable','only the domain of the solution'],1),
  ('Newton\'s Law of Cooling: dT/dt = k(T − T_env) models ___.',['only heating problems','only at absolute zero','constant temperature situations','how an object\'s temperature T changes at a rate proportional to the difference between T and the surrounding temperature — exponential decay to equilibrium'],3),
  ('The population equation dP/dt = kP(M − P)/M (logistic) is solved by ___.',['separation of variables (requires partial fractions)','the power rule only','direct integration','only numerical methods'],0)]),
sub('Physics','Physics Year-End: Connections and Applications','Students synthesise all Grade 12 Physics — mechanics, fields, waves, modern physics — and examine how physical principles interconnect.','Crash Course Physics: Year Review','https://www.youtube.com/watch?v=kUDhL6C9Lao',[
  ('The four fundamental forces of nature are ___.',['gravity, magnetism, heat, and nuclear','gravity, electricity, magnetism, nuclear','gravity, electromagnetism, the strong nuclear force, and the weak nuclear force — all other forces are manifestations of these four','friction, normal force, gravity, tension'],2),
  ('Conservation laws in physics (energy, momentum, angular momentum, charge) are ___.',['approximate — they can be violated in extreme conditions','only valid in classical physics','only valid in isolated systems (no external forces/energy inputs) — and are among the most powerful and far-reaching principles in all of physics','less fundamental than Newton\'s Laws'],2),
  ('The wave-particle duality in quantum mechanics, confirmed by the double-slit experiment, means ___.',['only light has this property','electrons are both waves and particles simultaneously','quantum mechanics is incorrect','quantum objects behave like waves OR particles depending on the experimental setup — observation affects the system in a fundamental, non-classical way'],1),
  ('Special relativity modifies classical mechanics at ___.',['all speeds','only for massless particles','only in gravitational fields','speeds approaching the speed of light — at everyday speeds, relativistic corrections are negligible, and classical mechanics is an excellent approximation'],3),
  ('The most profound insight from Grade 12 Physics is ___.',['only Newtonian mechanics matters','physics is only about equations','physics applies only to extreme conditions','the universe operates through mathematically precise laws — and that our human-scale intuitions, while useful approximations, break down at extreme speeds, scales, and energies in ways that reveal deeper truths about reality'],3)]),
]),
day(13,[
E('Independent Reading Synthesis: Personal Reading List','Students develop a personal reading list beyond the curriculum, demonstrating wide reading, independent literary judgment, and lifelong reading habits.',[
  ('Building a personal reading list involves ___.',['only choosing bestsellers','following only the curriculum','reading only within one genre','deliberate exploration across genres, periods, cultures, and forms — allowing recommendations, curiosity, and connections between books to guide you into territory you would not otherwise encounter'],3),
  ('Keeping a reading journal develops ___.',['only a record of books completed','no transferable skills','only for readers who become English teachers','the habit of attending carefully to what you read — noting questions, images, passages, and ideas that matter to you, building a personal archive of reading that enriches all future reading and writing'],3),
  ('A recommendation to a peer about a book should include ___.',['only the plot summary','only the theme','only the genre','a specific reason this book is worth reading: what is distinctive about its prose, its ideas, its emotional impact, or its formal innovation — not just what it\'s about, but why it matters'],3),
  ('Reading widely beyond the curriculum benefits you by ___.',['only improving your exam marks','replacing academic literary study','only for entertainment','building vocabulary, background knowledge, cultural awareness, empathy, narrative intelligence, and the capacity for sustained attention — all of which transfer to academic and professional life'],3),
  ('The lifelong reader develops ___.',['only factual knowledge from books','only literary knowledge from fiction','a disinterest in other media','a distinctive relationship to language and narrative — a richer inner life, a wider frame of reference, and a deeper capacity for understanding perspectives and experiences beyond their own'],3)]),
sub('Advanced Functions','Mathematical Modelling: Choosing the Right Function','Students apply all function families to real-world data — choosing, fitting, and interpreting mathematical models.','Khan Academy: Mathematical Modeling','https://www.youtube.com/watch?v=A3M9Ksxrd9c',[
  ('When data shows exponential growth that eventually levels off, the best model is ___.',['a polynomial function','a trigonometric function','a pure exponential function','a logistic function — capturing rapid initial growth that slows as the population approaches carrying capacity'],3),
  ('Data showing a repeating seasonal pattern with constant amplitude is best modelled by ___.',['an exponential function','a polynomial','a linear function','a sinusoidal (trigonometric) function — periodic data requires a periodic model'],3),
  ('Data about the cooling of an object over time is best modelled by ___.',['a linear function','a polynomial of degree 2','a sinusoidal function','an exponential decay function — Newton\'s Law of Cooling produces exponential temperature change'],3),
  ('Evaluating the quality of a mathematical model requires ___.',['only looking at the graph','only comparing slopes','only checking the model at known points','examining residuals (differences between predicted and observed values), assessing whether the model captures the pattern, and considering whether the model makes sense outside the data range'],3),
  ('The most important limitation of any mathematical model is ___.',['they can never be made by students','models are always perfect representations','they require too much computation','it is a simplification of reality — it captures some aspects of the phenomenon and misses others; the skill is knowing which simplifications are acceptable for the purpose at hand'],3)]),
sub('Calculus','Applications: Calculus in Science and Engineering','Students apply differentiation and integration to physics (motion, work, fluid pressure) and examine the role of calculus in modern science.','Khan Academy: Calculus Applications','https://www.youtube.com/watch?v=m2MIpDrF7Es',[
  ('If s(t) is position, then v(t) = s\'(t) and a(t) = v\'(t) = s\'\'(t). To find displacement from t₁ to t₂:',['use the acceleration formula','differentiate s(t)','use average velocity × time','∫[t₁ to t₂] v(t) dt = s(t₂) − s(t₁)'],3),
  ('Work done by a variable force F(x) over displacement from a to b is ___.',['F × (b − a)','F(b) − F(a)','∫[a to b] F(x) dx — summing infinitesimal work elements, which requires integration when F varies','F(a) × (b − a)'],2),
  ('The average value of a continuous function f on [a, b] is ___.',['f(a) + f(b))/2 (only for linear functions)','∫[a to b]f(x)dx','[f(b)−f(a)]/(b−a)','[1/(b−a)] × ∫[a to b]f(x)dx — the integral divided by the interval length'],3),
  ('Calculus is fundamental to ___.',['only pure mathematics','only physics','only engineering','physics (motion, fields, thermodynamics), engineering (design, control systems), economics (marginal analysis), biology (population models), and statistics (probability distributions) — it is the mathematical language of change'],3),
  ('The most important insight calculus provides is ___.',['how to calculate derivatives and integrals','only how to find slopes','that mathematics can only describe simple systems','that continuous change can be understood by examining it at an infinitesimal scale — and that the process of accumulation (integration) and the process of change (differentiation) are inverse operations'],3)]),
sub('Physics','Astrophysics: Stars, Galaxies, and Cosmology','Students examine stellar evolution, galaxy structure, and the Big Bang model of the universe, connecting nuclear physics and gravity to astrophysics.','Crash Course Astronomy: Stars and Cosmology','https://www.youtube.com/watch?v=qGHBcRcPQeI',[
  ('A star generates energy through ___.',['nuclear fission of heavy elements','chemical combustion','only gravitational contraction','nuclear fusion — hydrogen nuclei fuse to form helium in the stellar core, releasing energy from the mass defect'],3),
  ('The Hertzsprung-Russell (H-R) diagram plots ___.',['speed vs. mass','distance vs. age','temperature vs. position','luminosity vs. surface temperature — revealing that most stars (on the "main sequence") have a predictable relationship between these quantities'],3),
  ('A neutron star forms when ___.',['a star runs out of hydrogen only','any star dies','a star explodes without collapse','a massive star undergoes a supernova and its core collapses — protons and electrons combine to form neutrons, producing an incredibly dense object roughly the size of a city'],3),
  ('The observed redshift of distant galaxies demonstrates ___.',['the universe is contracting','only that galaxies are old','the speed of light is increasing','the universe is expanding — light from distant galaxies is shifted toward longer (red) wavelengths, consistent with recessional velocity increasing with distance (Hubble\'s Law)'],3),
  ('The Cosmic Microwave Background (CMB) is ___.',['radiation from the first stars','only visible with optical telescopes','noise in early radio equipment','thermal radiation left over from when the universe cooled enough for atoms to form (~380,000 years after the Big Bang) — the strongest evidence for the Big Bang model'],3)]),
]),
day(14,[
E('Grade 12 English: Culminating Preparation','Students prepare for their culminating essay and exam, reviewing the year\'s literary works and refining their analytical approaches.',[
  ('The Grade 12 culminating essay should demonstrate ___.',['only breadth of reading','only length','only correct grammar','the highest level of analytical thinking you are capable of: a specific, arguable, complex thesis; precise, well-chosen evidence; sophisticated analysis; and a coherent, well-structured argument'],3),
  ('Preparing for a literary exam involves ___.',['only memorising quotations','only re-reading all the texts','only reviewing the plot of each text','understanding each text\'s formal choices, key thematic concerns, and the arguments you could make about it — having 2-3 developed analytical positions for each major text'],3),
  ('The most effective use of quotations in a timed essay is ___.',['always using long quotations','using as many as possible','only using quotations in the introduction','shorter, precisely targeted quotations that require and reward analysis — a brief, telling phrase you can unpack analytically is better than a long passage you merely describe'],3),
  ('Engaging with literary criticism in a culminating essay shows ___.',['only that you have read critics','that you have no original ideas','that critics are always right','that you can position your own reading in relation to existing scholarly perspectives — agreeing, disagreeing, extending, or qualifying a critical position with textual evidence'],3),
  ('The last step before submitting a major essay is ___.',['only checking spelling','reading the conclusion only','only counting the words','reading the complete essay as a skeptical stranger would: does the argument actually hold? Is each claim supported? Does the conclusion follow from the evidence? Is the voice consistent and clear?'],3)]),
sub('Advanced Functions','Advanced Functions Final Assessment Review','Students review all major course concepts and practise exam-level problems.','Khan Academy: Functions Final Review','https://www.youtube.com/watch?v=nRmBsxBpTjs',[
  ('The graph of f(x) = x(x−2)²(x+1)³ has x-intercepts at ___.',['x = 0, 2, −1 with multiplicities 1, 2, 3 respectively — crosses at 0 and −1, touches at 2','x = 0, 4, 3','x = 0, 2, 1','x = 0 and x = 1 only'],0),
  ('Solve: 2^(x+1) = 5^(x−1)',['(x+1)ln2 = (x−1)ln5 → x(ln2−ln5) = −ln5 − ln2 → x = (ln5+ln2)/(ln5−ln2) = ln10/ln(5/2)','x = ln5/ln2','x = 5/2','x = 4'],0),
  ('The function f(x) = (3x²)/(x²−4) has ___.',['no asymptotes','vertical asymptotes at x = ±2, horizontal asymptote y = 3 (ratio of leading coefficients), x-intercept at x = 0','only x-intercept at x = 0','vertical asymptotes at x = ±2 only'],1),
  ('For vectors a = (1, 3) and b = (4, −2), find a · b and determine if they are perpendicular.',['a · b = 4 + (−6) = −2 ≠ 0, so not perpendicular','a · b = 0, so perpendicular','a · b = 1 × 4 = 4','a · b = (1+4)(3+(−2)) = 5'],0),
  ('Using induction: prove n² > 2n for all n ≥ 3. Base case n = 3: 9 > 6 ✓. Inductive step: assume k² > 2k. Then (k+1)² = ___.',['k² + 2k + 1 > 2k + 2k + 1 > 2(k+1) ✓ (using k ≥ 3 so 2k > 2)','k² + 1','k² + 2','k(k+1)'],0)]),
sub('Calculus','Calculus Final Assessment Review','Students review all major Calculus content and practise exam-level problems.','Khan Academy: Calculus Final Review','https://www.youtube.com/watch?v=6HkBGVPWIXA',[
  ('Evaluate: lim(x→0) of (sin x)/x.',['0','∞','lim(x→0) sin(x)/x = 1 (a fundamental limit in calculus — proved by the squeeze theorem or L\'Hôpital\'s Rule)','−1'],2),
  ('Find the equation of the tangent to f(x) = e^x at x = 0.',['y = e^x','y = x','y = x + 1 (f(0) = 1, f\'(x) = e^x, f\'(0) = 1, tangent: y − 1 = 1(x − 0))','y = 2x'],2),
  ('∫[0 to π]sin(x)dx = ___.',['−1','0','π','[−cos(x)] from 0 to π = −cos(π) − (−cos(0)) = 1 + 1 = 2'],3),
  ('The maximum of f(x) = x³ − 3x on [−2, 2] occurs at ___.',['x = 2: f(2) = 2 (f\'(x) = 3x²−3 = 0 → x = ±1; f(1) = −2 (local min), f(−1) = 2 (local max); endpoints: f(−2) = −2, f(2) = 2; global max = 2 at x = −1 and x = 2)','x = 1','x = 0','x = −2'],0),
  ('Solve the IVP: dy/dx = y, y(0) = 3.',['y = 3e^x (general solution y = Ce^x; C = 3 from initial condition)','y = e^(3x)','y = 3x','y = e^x + 3'],0)]),
sub('Physics','Physics Final Assessment Review','Students review all Grade 12 Physics content and practise exam-level problems.','Crash Course Physics: Final Review','https://www.youtube.com/watch?v=pGj9isFr21U',[
  ('A ball on a string of radius 0.5 m completes one revolution in 2 s. Find centripetal acceleration.',['ac = v²/r = (2πr/T)²/r = 4π²r/T² = 4π²(0.5)/4 = π²/2 ≈ 4.93 m/s²','ac = 10 m/s²','ac = 2π m/s²','ac = 5 m/s²'],0),
  ('Using Faraday\'s Law: a coil of 50 turns has its flux change from 0.02 Wb to 0.08 Wb in 0.1 s. The induced EMF is ___.',['EMF = −NΔΦ/Δt = −50(0.06)/0.1 = −30 V (magnitude 30 V)','30 mV','0.6 V','300 V'],0),
  ('An object at rest has rest energy E₀ = mc². For m = 1 kg, E₀ = ___.',['9 × 10¹⁶ J (E₀ = mc² = 1 × (3×10⁸)²)','3 × 10⁸ J','1 J','c J'],0),
  ('A circuit has a 12 V battery, 4Ω and 2Ω resistors in series. Current = ___.',['I = V/R_total = 12/6 = 2 A','I = 3 A','I = 6 A','I = 12 A'],0),
  ('Time dilation: a muon travels at 0.98c. Its proper lifetime is 2.2 μs. Time measured in lab frame = ___.',['t = γt₀ = 2.2/√(1−0.98²) μs ≈ 2.2/0.199 ≈ 11 μs','2.2 μs unchanged','0.44 μs','22 μs'],0)]),
]),
day(15,[
E('Grade 12 English: Exam and Celebration','A final celebration of Grade 12 English — reflecting on the year\'s literary journey and looking ahead to university and lifelong reading.',[
  ('Grade 12 English culminates in ___.',['completed study of English','the end of reading and writing as serious pursuits','only exam preparation','a genuine transformation — students who engage deeply emerge as fundamentally different readers and thinkers, with analytical skills, literary knowledge, and communicative power that will serve them throughout their lives'],3),
  ('The connection between literature and university study is ___.',['literature is only relevant in humanities programs','literature is not studied at university','no connection','the analytical, argumentative, and communicative skills developed in literary study are fundamental to success in virtually any university discipline — history, law, political science, philosophy, psychology, and increasingly science communication'],3),
  ('Reading literature throughout your adult life ___.',['is only for people who study English','has no connection to professional success','is largely irrelevant after graduation','sustains intellectual and empathetic development, provides pleasure and meaning, connects you to the fullest range of human experience, and maintains the reading skills that atrophy without practice'],3),
  ('The writers you have studied in Grade 12 ___.',['are now no longer relevant','are only relevant in academic contexts','have taught you only literary technique','have given you intellectual companions — voices you can return to throughout your life, finding new meaning as your own experience grows'],3),
  ('English, as a discipline and a practice, is ___.',['a set of skills you\'ve now mastered and completed','only about grammar and spelling','only about fiction and poetry','a lifelong pursuit — language and literature are not finished, not mastered, not set aside after graduation but lived with, returned to, and deepened throughout a human life'],3)]),
sub('Advanced Functions','Looking Back, Looking Forward','Students reflect on their mathematical development across MHF4U and its connection to university mathematics.','Khan Academy: Looking Ahead to Calculus','https://www.youtube.com/watch?v=riXcZT2ICjA',[
  ('Advanced Functions has prepared you for university mathematics by ___.',['teaching you all the mathematics you will ever need','only for students in STEM programs','being equivalent to first-year university calculus','developing fluency in function analysis — the foundation for calculus, linear algebra, statistics, and all quantitative reasoning at university level'],3),
  ('The most transferable mathematical skill from Grade 12 is ___.',['memorising all formulas','only knowing specific function types','computing derivatives (which you haven\'t done in this course)','mathematical reasoning: forming conjectures, testing them systematically, constructing rigorous arguments, and knowing when a result is proven vs. merely plausible'],3),
  ('Mathematics at university is ___.',['identical to high school mathematics','easier than high school','only about computation','more abstract and proof-based — shifting from applying formulas to understanding why they work and extending them to new situations; Grade 12 Advanced Functions is the foundation for this shift'],3),
  ('The mathematicians whose work you have implicitly used in this course — Euler, Gauss, Newton — ___.',['were only interested in pure theory','had no connection to the mathematics you studied','are only important to professional mathematicians','built the framework that makes modern science, engineering, finance, and computing possible — Grade 12 mathematics is not just school content but access to centuries of human intellectual achievement'],3),
  ('Finishing Advanced Functions means ___.',['you are done with mathematics','you need no further mathematical study','only that you passed the course','you have the mathematical tools to pursue virtually any university program — and more importantly, you have experienced mathematical thinking at a level that trains the mind for rigorous reasoning in any field'],3)]),
sub('Calculus','Calculus: Looking Back and Forward','Students reflect on the year\'s learning in calculus and its connections to the mathematical sciences.','Khan Academy: Calculus Bridge to University','https://www.youtube.com/watch?v=WUvTyaaNkzM',[
  ('The Fundamental Theorem of Calculus is profound because ___.',['it makes integration easier to compute','only because it involves two operations','it is the most complex theorem in mathematics','it reveals that differentiation and integration — apparently unrelated operations — are inverse operations, unifying two major streams of mathematical thinking into a single theory'],3),
  ('Calculus was developed independently by ___.',['Euclid and Archimedes','Gauss and Euler','Descartes and Fermat','Newton and Leibniz in the 17th century — a famous priority dispute, but their discoveries were genuinely independent and used different notation (we use Leibniz\'s)'],3),
  ('The most important application of calculus in the 21st century is ___.',['only in physics','only in engineering','only bridge design','arguably machine learning — the training of neural networks relies on gradient descent (an application of multivariable calculus) to optimise complex functions with millions of parameters'],3),
  ('Differential equations (which you\'ve begun) are ___.',['a minor extension of introductory calculus','less important than algebra','only for engineers','the language in which most of science is written — from Newton\'s laws to quantum mechanics to epidemiology to population ecology, the universe is described by equations relating rates of change'],3),
  ('Completing Grade 12 Calculus means ___.',['you have mastered all of calculus','university calculus will be completely familiar','calculus is now closed to you','you have the foundation to study multivariable calculus, differential equations, and real analysis at university — the door to the mathematical sciences is open'],3)]),
sub('Physics','Physics: A Final Reflection','Students reflect on their learning in Grade 12 Physics and the role of physics in understanding the universe.','Crash Course Physics: Reflecting on Physics','https://www.youtube.com/watch?v=kKKM8Y-u7ds',[
  ('Physics is the most fundamental science because ___.',['it is the oldest science','it is the most difficult','only physicists understand it','its principles underlie chemistry, biology, and engineering — chemistry is physics applied to electrons, biology applies chemical and physical principles to living systems, and all technology exploits physical laws'],3),
  ('The history of physics shows ___.',['physics is a complete and finished discipline','major changes in understanding are no longer possible','only a gradual accumulation of facts','a series of revolutionary conceptual shifts — from Aristotle to Newton, from Newton to Einstein, from classical to quantum — each overturning apparently solid knowledge and revealing something deeper'],3),
  ('Quantum mechanics and general relativity, the two great theories of 20th century physics, ___.',['are in perfect agreement','have been completely unified','have no experimental support','are both spectacularly confirmed but mutually inconsistent — their reconciliation (quantum gravity) is one of the greatest unsolved problems in all of science'],3),
  ('Physics shapes your daily life through ___.',['no practical applications in everyday life','only large-scale technologies','only electrical devices','everything: the transistors in your phone, the GPS that locates you, the medical imaging that diagnoses disease, the lasers that read discs, the superconductors in MRI machines — all rest on 20th century physics'],3),
  ('The greatest gift of physics education is ___.',['knowing all the formulas','passing the exam','only useful if you study physics at university','the habit of asking "why does this happen?" and having confidence that patient, systematic inquiry can reveal the answer — the physicist\'s mindset: curiosity, rigour, and belief in the comprehensibility of nature'],3)]),
]),
]

write_new(12, g12)
print('grade12.ts written (15 days)')
