#!/usr/bin/env python3
"""Phase 3 extension: Grade 11, Days 61-70 (fourth Grade 11 batch, taking
the grade from 60 to 70 days). Topics chosen to avoid any overlap with the
existing Day 1-60 set (see data/grade11.json / data/grade11.ts): the
epistolary novel, the persuasive manifesto, news bias and fact-checking,
debate rebuttal and cross-examination, the character study essay, cohesion
and coherence, the confessional poem, the elegy, postmodern fiction and
fragmented narrative; set theory and Venn diagrams, graph theory, the
ambiguous case of the sine law, measures of central tendency and spread,
optimization with quadratic models, solving equations graphically versus
algebraically, systems of three linear equations, the real number system,
conic sections (circles); sex-linked inheritance and pedigree analysis,
the Hardy-Weinberg principle, comparative anatomy and homologous
structures, extremophiles, pollination strategies and coevolution,
bioinformatics and DNA sequencing, animal adaptations to extreme
environments, the brain and higher function, freshwater ecosystems and
watershed health; periodic trends in atomic properties, empirical and
molecular formula determination, colorimetry and Beer's law, acid rain
and atmospheric chemistry, photochemistry, flame tests and atomic
emission, soaps/detergents and surfactant chemistry, food chemistry and
the Maillard reaction, and phase diagrams/sublimation.

Topics were checked closely against near-neighbours already on the books
to avoid overlap: "Genetics: Sex-Linked Inheritance and Pedigree
Analysis" is distinct from Day 3's Mendelian extensions and Day 30's
chromosomal abnormalities; "Comparative Anatomy and Homologous
Structures" is a distinct evidentiary category from Day 38's fossil-record
evidence; "The Brain -- Structure and Higher Function" narrows in on a
single organ the way Day 54's "Vision and the Eye" narrowed in from the
general nervous-system survey on Day 10; "Freshwater Ecosystems and
Watershed Health" is distinct from Day 32's biomes/global-ecosystems
survey and Day 41's nutrient-cycles/biogeochemistry lesson; "Acid Rain
and Atmospheric Chemistry" is distinct from Day 20's general
pollution/remediation lesson and Day 39's ozone/greenhouse-gas lesson the
same way those two are distinct from each other; "Colorimetry and Beer's
Law" and "Flame Tests and Atomic Emission" are specific analytical
techniques distinct from Day 19's general qualitative/quantitative survey
and Day 45's spectroscopy lesson, the same way Day 58's mass spectrometry
lesson was; "Empirical and Molecular Formula Determination" is distinct
from Day 3's mole concept and Day 4's limiting reagents/percent yield.
"Buffer Solutions", "Catalysts and Reaction Mechanisms", and
"Symbiotic Relationships" were all considered and rejected as too close
to existing Days 26, 16/33/48, and 9 respectively (per the note already
in gen_grade11_days51_60.py).

Subject keys for Grade 11 are "English", "Functions", "Biology",
"Chemistry" (same as prior Grade 11 batches).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote or apostrophe characters are used
anywhere in question/summary/option text; quotation marks and
apostrophes use the curly Unicode form (' " ").
"""
import sys
sys.path.insert(0, '/sessions/happy-laughing-ritchie/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E11 = 'https://tvolearn.com/pages/grade-11-english'
F11 = 'https://tvolearn.com/pages/grade-11-functions'
B11 = 'https://tvolearn.com/pages/grade-11-biology'
C11 = 'https://tvolearn.com/pages/grade-11-chemistry'
RE, RF, RB, RC = (
    'TVO Learn: Grade 11 English',
    'TVO Learn: Grade 11 Functions',
    'TVO Learn: Grade 11 Biology',
    'TVO Learn: Grade 11 Chemistry',
)


def E(t, s, q):
    return sub('English', t, s, RE, E11, q)


def F(t, s, q):
    return sub('Functions', t, s, RF, F11, q)


def B(t, s, q):
    return sub('Biology', t, s, RB, B11, q)


def C(t, s, q):
    return sub('Chemistry', t, s, RC, C11, q)


g11_61_70 = [
day(61, [
E('Literature: The Epistolary Novel',
  'Grade 11 English strand: an epistolary novel tells its story through documents such as letters, diary entries, or emails, letting readers piece together plot and character directly from a narrator’s own words without an external narrating voice.',
  [('An epistolary novel tells its story primarily through ___.', ['Documents such as letters, diary entries, or emails', 'A single omniscient narrator describing events from outside the story', 'A concept unrelated to novel structure', 'A series of stage directions with no narration at all'], 0),
   ('Which is an example of a document that might appear in an epistolary novel?', ['A diary entry written by one of the story’s characters', 'A table of contents listing chapter titles', 'An example entirely unrelated to epistolary fiction', 'A publisher’s note printed on the copyright page'], 0),
   ('Why might an epistolary novel feel especially intimate or immediate to a reader?', ['Readers encounter events directly through a character’s own private words, without an external narrator’s filter', 'This format always distances the reader from the story’s characters', 'Epistolary novels never let a reader access a character’s private thoughts', 'A reason unrelated to how a novel is structured'], 0),
   ('Why might an author use multiple correspondents exchanging letters rather than a single diary?', ['Multiple perspectives can reveal gaps or contradictions in how different characters understand the same events', 'Using multiple correspondents always reduces a story to a single point of view', 'This choice has no effect on how a reader interprets events', 'A reason unrelated to narrative perspective'], 0),
   ('Why might the epistolary form create dramatic irony, where the reader knows more than any single character does?', ['Piecing together separate documents can let a reader see connections that no individual letter-writer is aware of', 'Dramatic irony can never occur in an epistolary novel', 'This format guarantees every character knows exactly as much as the reader', 'A reason unrelated to the epistolary form'], 0)]),
F('Discrete Math: Set Theory and Venn Diagrams',
  'Grade 11 Functions strand (Discrete Mathematics): a set is a well-defined collection of distinct objects, and Venn diagrams visually represent relationships between sets, including union, intersection, and complement.',
  [('A set is best described as ___.', ['A well-defined collection of distinct objects', 'A collection that may repeat the same object many times', 'A concept unrelated to discrete mathematics', 'A single object with no connection to a collection'], 0),
   ('In a Venn diagram, the overlapping region between two circles represents the ___ of the two sets.', ['Intersection', 'Union, with no connection to overlap', 'A region unrelated to set theory', 'Complement, with no connection to overlap'], 0),
   ('The union of two sets, A and B, contains ___.', ['Every element that belongs to A, to B, or to both', 'Only elements that belong to both A and B at once', 'A concept unrelated to combining sets', 'No elements at all, regardless of A and B'], 0),
   ('Why might a Venn diagram be a useful tool for solving a problem involving overlapping survey categories, such as students who play two different sports?', ['It visually separates students in only one category from students counted in both, avoiding double-counting', 'Venn diagrams always cause every element to be counted twice', 'This tool has no connection to solving problems about overlapping groups', 'A reason unrelated to representing set relationships'], 0),
   ('Why is set theory considered a foundational tool for the rest of discrete mathematics, including probability?', ['Many probability and counting problems can be modelled precisely using the language of sets and their relationships', 'Set theory has no connection to probability or counting problems', 'This concept only applies to purely abstract mathematics with no further use', 'Probability problems can never be represented using sets'], 0)]),
B('Genetics: Sex-Linked Inheritance and Pedigree Analysis',
  'Grade 11 Biology strand: sex-linked traits are carried on the X or Y chromosome, producing inheritance patterns that differ between males and females, and a pedigree chart traces how such a trait passes through a family across generations.',
  [('A sex-linked trait is carried on ___.', ['The X or Y chromosome', 'An autosome that is unrelated to sex chromosomes', 'A concept unrelated to inheritance', 'A structure found only in plant cells'], 0),
   ('A pedigree chart is best described as a diagram that traces ___.', ['How a trait passes through a family across generations', 'The geographic migration of a species over time', 'A concept unrelated to genetics', 'The exact age of every family member shown'], 0),
   ('Why do X-linked recessive traits, such as red-green colour blindness, appear more often in males than in females?', ['Males have only one X chromosome, so a single recessive allele on it is always expressed', 'Males always carry two X chromosomes, identical to females', 'X-linked traits have no connection to biological sex', 'Females can never carry or express an X-linked recessive trait'], 0),
   ('On a pedigree chart, a filled-in shape typically represents an individual who ___.', ['Expresses the trait being studied', 'Is entirely unrelated to the family being studied', 'Was never tested for the trait in question', 'Cannot pass the trait to any offspring under any circumstances'], 0),
   ('Why is pedigree analysis a valuable tool for genetic counselling?', ['It can help estimate the probability that future offspring will inherit a particular trait or condition', 'Pedigree charts provide no useful information about inheritance patterns', 'This tool has no application outside of a biology classroom', 'Genetic counselling never makes use of a family’s inheritance history'], 0)]),
C('Chemistry: The Periodic Table — Trends in Atomic Properties',
  'Grade 11 Chemistry strand: atomic radius, ionization energy, and electronegativity all change in predictable patterns across a period and down a group of the periodic table, reflecting how nuclear charge and electron shielding shift with atomic structure.',
  [('Atomic radius generally ___ across a period from left to right.', ['Decreases', 'Increases, with no connection to nuclear charge', 'A pattern unrelated to atomic structure', 'Stays exactly the same in every case'], 0),
   ('Ionization energy is best described as the energy required to ___.', ['Remove an electron from a gaseous atom', 'Add an electron to a gaseous atom', 'A concept unrelated to atomic properties', 'Split an atom’s nucleus into smaller fragments'], 0),
   ('Why does atomic radius generally increase down a group of the periodic table?', ['Each successive period adds a new electron shell, placing outer electrons farther from the nucleus', 'Electron shells are removed with each new period, moving down a group', 'Atomic radius has no connection to the number of electron shells', 'Atoms in the same group always have an identical atomic radius'], 0),
   ('Why does ionization energy generally increase across a period from left to right?', ['Increasing nuclear charge pulls the outer electrons in more tightly, making them harder to remove', 'Nuclear charge decreases steadily across a period', 'Ionization energy has no connection to nuclear charge', 'Outer electrons become easier to remove as nuclear charge increases'], 0),
   ('Why are periodic trends in atomic properties useful for predicting how an element will react chemically?', ['Properties like electronegativity and ionization energy strongly influence how readily an atom gains, loses, or shares electrons', 'Periodic trends have no connection to how an element behaves in a reaction', 'Every element reacts in an identical way regardless of its position on the periodic table', 'This concept only applies to purely theoretical chemistry with no practical use'], 0)])]),

day(62, [
E('Writing: The Persuasive Manifesto',
  'Grade 11 English strand: a manifesto is a public declaration of beliefs and intentions, using bold, direct language and a clear call to action to rally an audience around a cause or vision for change.',
  [('A manifesto is best described as a public declaration of ___.', ['Beliefs and intentions', 'A private, confidential opinion never meant to be shared', 'A concept unrelated to persuasive writing', 'Purely factual, statistical data with no viewpoint expressed'], 0),
   ('Which is a stylistic feature commonly associated with a manifesto?', ['Bold, direct language and a clear call to action', 'A cautious, hedging tone that avoids taking any position', 'A feature entirely unrelated to persuasive writing', 'Long, purely descriptive passages with no argument at all'], 0),
   ('Why might a manifesto use short, declarative sentences rather than lengthy, qualified ones?', ['Short, direct statements can convey conviction and urgency to an audience', 'Short sentences always weaken a piece of persuasive writing', 'Sentence length has no connection to how persuasive a text feels', 'A manifesto should never attempt to convey urgency of any kind'], 0),
   ('Why is a clear call to action considered an essential element of a manifesto?', ['It directs the audience toward a specific response or change, rather than leaving the message abstract', 'A call to action always weakens a manifesto’s persuasive power', 'Manifestos are never intended to prompt any response from an audience', 'This element has no connection to the purpose of a manifesto'], 0),
   ('Why might students study historical and contemporary manifestos as models for persuasive writing?', ['They demonstrate how bold, structured language can rally an audience around a shared cause', 'Manifestos have no useful lessons for other forms of persuasive writing', 'This form of writing has no historical or contemporary relevance', 'A reason unrelated to studying persuasive techniques'], 0)]),
F('Discrete Math: Introduction to Graph Theory',
  'Grade 11 Functions strand (Discrete Mathematics): a graph is a mathematical structure made of vertices (points) connected by edges (lines), used to model relationships and networks such as road systems or social connections.',
  [('In graph theory, a vertex is best described as a ___.', ['Point in the graph, often representing an object or location', 'Line connecting two points in the graph', 'A concept unrelated to graph theory', 'Numerical value assigned to an entire graph'], 0),
   ('An edge in a graph represents ___.', ['A connection or relationship between two vertices', 'A single isolated point with no connections', 'A concept unrelated to graphs', 'The total number of vertices in the graph'], 0),
   ('Which is an example of a real-world situation that could be modelled using a graph?', ['A network of roads connecting different cities', 'A situation entirely unrelated to connections or relationships', 'A single number with no connection to other values', 'A list of items with no relationships between them'], 0),
   ('In graph theory, the degree of a vertex refers to ___.', ['The number of edges connected to that vertex', 'The exact physical distance between two vertices', 'A concept unrelated to graph theory', 'The total number of vertices in the entire graph'], 0),
   ('Why is graph theory a useful tool for solving real-world optimization problems, such as finding the shortest delivery route?', ['It provides a structured way to represent and analyze connections, distances, or costs between locations', 'Graph theory has no real-world application outside of pure mathematics', 'Optimization problems can never be represented using vertices and edges', 'This concept only applies to purely abstract mathematics with no practical use'], 0)]),
B('Genetics: Population Genetics and the Hardy-Weinberg Principle',
  'Grade 11 Biology strand: population genetics studies how allele frequencies change within a population over time, and the Hardy-Weinberg principle describes the theoretical conditions under which those frequencies remain stable across generations.',
  [('Population genetics primarily studies how ___ change within a population over time.', ['Allele frequencies', 'The physical location of a population exclusively', 'A concept unrelated to genetics', 'The exact number of species present, with no connection to alleles'], 0),
   ('The Hardy-Weinberg principle describes the conditions under which allele frequencies in a population ___.', ['Remain stable across generations', 'Always change dramatically every generation', 'A concept unrelated to population genetics', 'Become identical to those of an entirely different species'], 0),
   ('Which of these is a condition required for a population to remain in Hardy-Weinberg equilibrium?', ['No mutation is occurring within the population', 'Constant migration into and out of the population', 'A condition unrelated to genetic equilibrium', 'Non-random mating based on specific traits'], 0),
   ('Why is the Hardy-Weinberg principle useful even though real populations rarely meet all of its conditions perfectly?', ['It provides a baseline for detecting when evolutionary forces, like natural selection, are actually acting on a population', 'The Hardy-Weinberg principle has no practical use in studying real populations', 'Real populations always meet every condition of Hardy-Weinberg equilibrium perfectly', 'This principle has no connection to detecting evolutionary change'], 0),
   ('Why might a sudden environmental change, such as a new predator, cause a population to shift away from Hardy-Weinberg equilibrium?', ['The change can favour certain alleles over others, altering allele frequencies through natural selection', 'Environmental change never has any effect on allele frequencies', 'A population’s allele frequencies are always completely unaffected by its environment', 'This concept has no relevance to population genetics'], 0)]),
C('Chemistry: Empirical and Molecular Formula Determination',
  'Grade 11 Chemistry strand: an empirical formula shows the simplest whole-number ratio of atoms in a compound, while a molecular formula shows the actual number of each atom present, and the molecular formula can be found from the empirical formula using the compound’s molar mass.',
  [('An empirical formula shows ___.', ['The simplest whole-number ratio of atoms in a compound', 'The exact, actual number of every atom in a compound', 'A concept unrelated to chemical formulas', 'Only the mass of a compound, with no connection to atoms'], 0),
   ('A molecular formula shows ___.', ['The actual number of each atom present in a compound', 'Only the simplest possible ratio of atoms, never the actual number', 'A concept unrelated to chemical formulas', 'The exact colour of a compound in its solid state'], 0),
   ('To determine an empirical formula from experimental data, a chemist typically first converts the mass of each element to ___.', ['Moles', 'Litres, with no connection to mass', 'A unit unrelated to determining a formula', 'Degrees Celsius, with no connection to mass'], 0),
   ('Why might a molecular formula be a whole-number multiple of its corresponding empirical formula?', ['The empirical formula only shows the simplest ratio, so the actual compound may contain that ratio repeated several times', 'A molecular formula can never relate mathematically to an empirical formula', 'Molecular and empirical formulas are always numerically identical for every compound', 'This relationship has no basis in a compound’s actual structure'], 0),
   ('Why is knowing a compound’s molar mass necessary to determine its molecular formula from its empirical formula?', ['The molar mass reveals how many times the empirical formula’s mass fits into the actual compound’s total mass', 'Molar mass has no connection to determining a molecular formula', 'A molecular formula can always be determined with no reference to mass at all', 'This concept only applies to compounds with no measurable mass'], 0)])]),

day(63, [
E('Media Literacy: Analyzing News Bias and Fact-Checking',
  'Grade 11 English strand: news bias occurs when a report favours a particular perspective through word choice, source selection, or omission, and fact-checking practices help readers verify claims and identify that bias before accepting a report as accurate.',
  [('News bias occurs when a report favours a particular perspective through ___.', ['Word choice, source selection, or omission', 'The exact font used to print the article', 'A concept unrelated to news reporting', 'The specific day of the week the article is published'], 0),
   ('Which is an example of a fact-checking practice a reader might use to verify a claim?', ['Comparing the claim against multiple independent, credible sources', 'Accepting a claim immediately without any further investigation', 'A practice entirely unrelated to verifying information', 'Trusting a claim because it appeared in a single social media post'], 0),
   ('Why might the specific sources a journalist chooses to quote reveal a form of bias in a news report?', ['Selectively quoting sources who share one perspective can present an incomplete picture of an issue', 'The sources chosen for a report never have any influence on its perspective', 'This factor has no connection to how a news report is constructed', 'Every journalist is required to quote an identical number of sources'], 0),
   ('Why is omission — leaving out certain facts or context — considered a subtle but powerful form of bias?', ['Leaving out relevant information can shape a reader’s understanding without any single statement being false', 'Omitting information can never influence how a reader interprets a report', 'A reason unrelated to how bias appears in news reporting', 'Every fact relevant to a story must always be included in a report'], 0),
   ('Why is developing strong fact-checking habits especially important for navigating news encountered on social media?', ['Information can spread quickly on social media before its accuracy has been verified by anyone', 'Fact-checking is never necessary for information found on social media', 'All information shared on social media is automatically verified before posting', 'This skill has no relevance to how people consume news today'], 0)]),
F('Trigonometry: The Ambiguous Case of the Sine Law',
  'Grade 11 Functions strand: when solving a triangle using the sine law with two sides and a non-included angle (SSA), the given information can sometimes produce two possible triangles, one possible triangle, or no triangle at all — a situation called the ambiguous case.',
  [('The ambiguous case of the sine law arises when a triangle is defined by ___.', ['Two sides and a non-included angle', 'Three sides and no angles at all', 'A concept unrelated to solving triangles', 'Two angles and no sides at all'], 0),
   ('In the ambiguous case, the given information can result in ___.', ['Two possible triangles, one possible triangle, or no triangle at all', 'Exactly one possible triangle in every single case', 'A number of triangles unrelated to the given information', 'Always three distinct possible triangles'], 0),
   ('Why might two different triangles both satisfy the same SSA information in the ambiguous case?', ['The unknown angle could be either acute or obtuse and still be consistent with the given side lengths', 'SSA information always determines a single unique triangle with no other possibility', 'This situation has no connection to how the sine law is applied', 'Two triangles can never share the same combination of two sides and a non-included angle'], 0),
   ('Why might no triangle exist at all for a particular set of SSA measurements in the ambiguous case?', ['The given side opposite the known angle may be too short to reach and close the triangle', 'Every possible combination of SSA measurements always produces at least one valid triangle', 'This outcome has no connection to solving triangles with the sine law', 'A missing triangle can only occur when three sides are given instead of SSA'], 0),
   ('Why is it important to check for the ambiguous case whenever a triangle is defined using two sides and a non-included angle?', ['Failing to check can lead to reporting only one solution when a second valid triangle also exists', 'Checking for the ambiguous case is never necessary when solving a triangle', 'The ambiguous case only applies to right triangles, never to any other triangle', 'This concept has no relevance to correctly solving a triangle'], 0)]),
B('Biology: Comparative Anatomy and Homologous Structures',
  'Grade 11 Biology strand: comparative anatomy examines the physical structures of different species, and homologous structures — features with a shared underlying form despite different functions, such as a bat’s wing and a human arm — provide strong evidence for common ancestry.',
  [('A homologous structure is best described as a feature that shares a ___ despite serving a different function across species.', ['Similar underlying form', 'Identical function, with no connection to structure', 'A concept unrelated to comparative anatomy', 'Completely unrelated form across every species'], 0),
   ('Which is a commonly cited example of homologous structures?', ['A bat’s wing and a human arm', 'Two entirely unrelated structures found in different species', 'A bird’s wing and an insect’s wing', 'A shark’s fin and a bird’s wing'], 0),
   ('Why do homologous structures provide strong evidence for common ancestry between species?', ['A shared underlying structure suggests both species inherited that basic form from a common ancestor', 'Homologous structures always indicate that two species are completely unrelated', 'This evidence has no connection to evolutionary relationships between species', 'Common ancestry can never be supported using evidence from anatomy'], 0),
   ('An analogous structure differs from a homologous structure because it involves ___.', ['A similar function evolving independently, without a shared underlying structure', 'An identical underlying structure shared by two closely related species', 'A concept unrelated to comparative anatomy', 'A feature that always indicates the two species share a recent common ancestor'], 0),
   ('Why is comparative anatomy considered a valuable source of evidence alongside the fossil record when studying evolutionary relationships?', ['Structural similarities in living species can reveal shared ancestry even when a complete fossil record is unavailable', 'Comparative anatomy has no connection to studying evolutionary relationships', 'Anatomical evidence is always less reliable than every other type of evidence', 'This field has no relevance to the study of evolutionary biology'], 0)]),
C('Chemistry: Colorimetry and Beer’s Law',
  'Grade 11 Chemistry strand: colorimetry measures how much light of a specific wavelength a coloured solution absorbs, and Beer’s law describes the direct relationship between that absorbance and the solution’s concentration, allowing an unknown concentration to be determined.',
  [('Colorimetry measures how much light of a specific wavelength a solution ___.', ['Absorbs', 'Produces on its own, with no light source involved', 'A concept unrelated to colorimetry', 'Reflects exclusively, with no connection to absorption'], 0),
   ('Beer’s law describes a direct relationship between a solution’s absorbance and its ___.', ['Concentration', 'Exact temperature, with no connection to absorbance', 'A property unrelated to colorimetry', 'Physical volume, with no connection to concentration'], 0),
   ('Why is a calibration curve, built from solutions of known concentration, useful when using Beer’s law to find an unknown concentration?', ['It lets an unknown sample’s absorbance be compared against a reliable, established relationship between absorbance and concentration', 'A calibration curve has no connection to determining an unknown concentration', 'Beer’s law can only be applied without ever using a calibration curve', 'This tool is only useful for solutions with no colour at all'], 0),
   ('Why might a more concentrated coloured solution generally absorb more light than a diluted one?', ['A greater concentration means more light-absorbing particles are present for light to pass through', 'A more concentrated solution always absorbs less light than a diluted one', 'Concentration has no connection to how much light a solution absorbs', 'This relationship has no basis in the properties of the solution'], 0),
   ('Why is colorimetry a valuable technique in fields such as water-quality testing and medical laboratories?', ['It allows the concentration of a specific substance in a solution to be determined quickly and precisely', 'Colorimetry has no practical application outside of a chemistry classroom', 'Concentration can never be determined using a solution’s absorbance', 'This technique only applies to purely theoretical chemistry problems'], 0)])]),

day(64, [
E('Oral Communication: Debate Rebuttal and Cross-Examination',
  'Grade 11 English strand: an effective rebuttal directly addresses an opponent’s argument with evidence and logical reasoning, while cross-examination uses targeted questions to expose weaknesses in an opponent’s position during a structured debate.',
  [('An effective rebuttal directly addresses an opponent’s argument using ___.', ['Evidence and logical reasoning', 'A completely unrelated topic chosen at random', 'A concept unrelated to debate', 'Personal insults directed at the opponent'], 0),
   ('Cross-examination in a debate primarily involves ___.', ['Asking targeted questions to expose weaknesses in an opponent’s position', 'Reading a prepared speech with no questions asked at all', 'A concept unrelated to debate', 'Agreeing with every point an opponent has made'], 0),
   ('Why is it important for a rebuttal to engage directly with an opponent’s specific claim, rather than simply restating one’s own original argument?', ['Directly addressing the claim shows the audience that the opposing argument has been carefully considered and refuted', 'Restating one’s own argument is always a more effective strategy than engaging with an opponent’s claim', 'A rebuttal never needs to reference what an opponent has actually argued', 'This distinction has no connection to effective debating'], 0),
   ('Why might a well-crafted cross-examination question be phrased to require a brief, specific answer rather than an open-ended one?', ['A brief, specific answer makes it harder for an opponent to avoid addressing a weakness directly', 'Open-ended questions are always the most effective type of question in cross-examination', 'The phrasing of a question has no effect on how easily it can be answered', 'This strategy has no connection to exposing weaknesses in an argument'], 0),
   ('Why do debate skills like rebuttal and cross-examination remain valuable beyond a formal debate setting?', ['They build the ability to evaluate arguments critically and respond to opposing viewpoints in many real-world contexts', 'These skills have no application outside of a formal debate', 'Rebuttal and cross-examination are only useful in a courtroom setting', 'A reason unrelated to communication skills'], 0)]),
F('Statistics: Measures of Central Tendency and Spread',
  'Grade 11 Functions strand (Data Management): measures of central tendency, such as the mean, median, and mode, describe a typical value in a data set, while measures of spread, such as range and interquartile range, describe how varied the data actually is.',
  [('The mean of a data set is calculated by ___.', ['Adding all the values and dividing by the number of values', 'Selecting the single largest value in the data set', 'A calculation unrelated to central tendency', 'Selecting the value that appears most frequently'], 0),
   ('The median of a data set is best described as ___.', ['The middle value when the data is arranged in order', 'The value that appears most often in the data set', 'A concept unrelated to central tendency', 'The difference between the largest and smallest values'], 0),
   ('The range of a data set is calculated by ___.', ['Subtracting the smallest value from the largest value', 'Adding every value in the data set together', 'A calculation unrelated to measures of spread', 'Dividing the largest value by the smallest value'], 0),
   ('Why might the median be a more appropriate measure of central tendency than the mean for a data set with an extreme outlier?', ['The median is not pulled toward an extreme value the way the mean can be', 'The median is always affected more strongly by an outlier than the mean is', 'Outliers have no effect on either the mean or the median', 'The mean is always the more appropriate measure regardless of outliers'], 0),
   ('Why is a measure of spread, such as the interquartile range, useful alongside a measure of central tendency?', ['It reveals how consistent or varied the data actually is, which a single central value cannot show on its own', 'Measures of spread provide no additional information beyond central tendency alone', 'A reason unrelated to interpreting a data set', 'Central tendency always provides a complete picture of a data set with no further information needed'], 0)]),
B('Biology: Extremophiles and the Limits of Life',
  'Grade 11 Biology strand: extremophiles are organisms, primarily microorganisms, that thrive in conditions once thought too harsh for life, such as extreme heat, cold, pressure, or acidity, expanding scientific understanding of where and how life can exist.',
  [('An extremophile is best described as an organism that ___.', ['Thrives in conditions once thought too harsh for life', 'Can only survive in mild, temperate environments', 'A concept unrelated to biology', 'Requires an environment identical to that of most other organisms'], 0),
   ('Which of these is an example of an extreme condition in which an extremophile might live?', ['The near-boiling water of a deep-sea hydrothermal vent', 'A comfortable room-temperature environment with average humidity', 'A condition entirely unrelated to extremophiles', 'A typical backyard garden with no unusual conditions'], 0),
   ('Why has the discovery of extremophiles changed scientific understanding of where life might exist elsewhere in the universe?', ['It shows that life can adapt to conditions once assumed to make survival impossible, broadening the search for life on other worlds', 'Extremophiles have no connection to the scientific search for life beyond Earth', 'The discovery of extremophiles proved that life can only exist under mild, Earth-like conditions', 'This discovery has no relevance to astrobiology or the study of extreme environments'], 0),
   ('Why might enzymes from extremophiles, such as heat-tolerant bacteria, be valuable in industrial or laboratory applications?', ['These enzymes can remain functional under extreme conditions, such as high heat, where typical enzymes would stop working', 'Enzymes from extremophiles always stop functioning under any unusual condition', 'This concept has no practical application outside of basic biology', 'Industrial applications never make use of enzymes derived from any organism'], 0),
   ('Why do scientists classify many extremophiles within the domain Archaea rather than Bacteria or Eukarya?', ['Archaea often possess distinct cellular and genetic features suited to surviving extreme environments', 'All extremophiles are classified identically within a single domain with no distinctions made', 'Domain classification has no connection to an organism’s ability to survive extreme conditions', 'This concept has no relevance to the classification of living things'], 0)]),
C('Chemistry: Acid Rain and Atmospheric Chemistry',
  'Grade 11 Chemistry strand: acid rain forms when sulphur dioxide and nitrogen oxides released by burning fossil fuels react with water vapour in the atmosphere to produce sulphuric and nitric acid, lowering the pH of precipitation and damaging ecosystems.',
  [('Acid rain primarily forms when sulphur dioxide and nitrogen oxides react with ___ in the atmosphere.', ['Water vapour', 'Solid particles exclusively, with no connection to water vapour', 'A substance unrelated to atmospheric chemistry', 'Oxygen gas alone, with no other reactant involved'], 0),
   ('Sulphur dioxide and nitrogen oxides that contribute to acid rain are primarily released by ___.', ['Burning fossil fuels', 'Ordinary evaporation of lake water, with no connection to combustion', 'A process unrelated to acid rain formation', 'The natural respiration of forest ecosystems alone'], 0),
   ('Why does acid rain typically have a lower pH than unpolluted rainwater?', ['The sulphuric and nitric acid formed in the atmosphere increase the concentration of hydrogen ions in the precipitation', 'Acid rain always has a pH identical to that of unpolluted rainwater', 'This difference has no connection to the chemical reactions occurring in the atmosphere', 'Acid rain forms with no acids present at all'], 0),
   ('Why might acid rain be especially damaging to lakes and forests with limited natural buffering capacity?', ['Without enough naturally occurring bases to neutralize the added acidity, the pH of soil and water can drop sharply', 'Every ecosystem has an identical, unlimited capacity to neutralize acid rain', 'Buffering capacity has no connection to how an ecosystem responds to acid rain', 'Acid rain never has any measurable effect on soil or water pH'], 0),
   ('Why have regulations limiting sulphur dioxide and nitrogen oxide emissions from industrial sources helped reduce acid rain in many regions?', ['Reducing the emission of these gases directly reduces the raw materials available to form sulphuric and nitric acid in the atmosphere', 'These regulations have no connection to the chemical formation of acid rain', 'Acid rain formation is entirely unrelated to industrial emissions', 'Emission regulations always increase the rate of acid rain formation instead'], 0)])]),

day(65, [
E('Writing: The Character Study Essay',
  'Grade 11 English strand: a character study essay closely analyzes a single character’s motivations, relationships, and development, using specific textual evidence to build an interpretation of that character’s role within the larger work.',
  [('A character study essay primarily focuses on analyzing ___.', ['A single character’s motivations, relationships, and development', 'The publication history of the entire text', 'A concept unrelated to literary analysis', 'The biography of the author, with no connection to the character'], 0),
   ('Why is specific textual evidence, such as a direct quotation, important when writing a character study essay?', ['It grounds the writer’s interpretation of the character in details actually present in the text', 'Textual evidence is never necessary when analyzing a character', 'A reason unrelated to supporting a literary interpretation', 'An interpretation of a character should rely only on a reader’s personal opinion, with no evidence needed'], 0),
   ('Which is an example of a character’s development that a character study essay might trace?', ['A shift in the character’s values after a significant event in the plot', 'A detail entirely unrelated to a character’s growth', 'The exact number of pages the character appears on', 'The font used to print the character’s dialogue'], 0),
   ('Why might a character study essay examine a character’s relationships with other characters, rather than looking at that character in isolation?', ['Relationships can reveal aspects of a character’s values and motivations that might not be visible otherwise', 'A character’s relationships with others are never relevant to understanding that character', 'This approach has no connection to analyzing a character’s development', 'Characters in a text never influence or reveal anything about one another'], 0),
   ('Why might tracing a character’s internal contradictions strengthen a character study essay?', ['Contradictions can reveal a more complex, realistic portrait of a character than a purely consistent description would', 'A strong character study essay should ignore any contradictions found in a character', 'Internal contradictions have no connection to literary analysis', 'Every well-written character is entirely consistent, with no contradictions present'], 0)]),
F('Functions: Optimization Problems Using Quadratic Models',
  'Grade 11 Functions strand: many real-world quantities, such as area or revenue, can be modelled with a quadratic function, and the vertex of that function’s parabola represents the maximum or minimum value the quantity can reach.',
  [('In a quadratic model, the vertex of the parabola represents the ___ value the modelled quantity can reach.', ['Maximum or minimum', 'Only the minimum value, with no connection to a maximum', 'A value unrelated to optimization problems', 'The value exactly halfway between the two x-intercepts, unrelated to the quantity itself'], 0),
   ('If a quadratic function opens downward, its vertex represents a ___ value.', ['Maximum', 'Minimum, with no connection to a downward-opening parabola', 'A value unrelated to the shape of the parabola', 'Value that can never actually be reached by the function'], 0),
   ('Which is an example of a real-world quantity that might be modelled and optimized using a quadratic function?', ['The maximum area that can be enclosed by a fixed length of fencing', 'A quantity that changes at a constant rate with no connection to a parabola', 'A quantity entirely unrelated to optimization problems', 'The exact colour of an object with no connection to area or revenue'], 0),
   ('Why is completing the square, or finding the vertex form of a quadratic function, a useful strategy for solving an optimization problem?', ['It directly reveals the coordinates of the vertex, which represent the optimal value being sought', 'Completing the square has no connection to identifying a maximum or minimum value', 'This strategy only applies to functions that have no vertex at all', 'Vertex form always hides the optimal value rather than revealing it'], 0),
   ('Why might a business use a quadratic model to determine the price that maximizes revenue?', ['Revenue often rises and then falls as price increases, a pattern that a parabola can accurately represent', 'Revenue always increases indefinitely as price increases, with no maximum value', 'Quadratic models have no practical application in business or economics', 'This concept only applies to purely abstract mathematics with no real-world use'], 0)]),
B('Plant Biology: Pollination Strategies and Coevolution with Pollinators',
  'Grade 11 Biology strand: flowering plants have evolved diverse pollination strategies, including traits like colour, scent, and nectar that attract specific pollinators, and this relationship has driven coevolution between plants and the animals that pollinate them.',
  [('Flowering plants attract pollinators using traits such as ___.', ['Colour, scent, and nectar', 'A trait entirely unrelated to pollination', 'The thickness of the plant’s bark alone', 'The depth of the plant’s root system exclusively'], 0),
   ('Coevolution between a plant and its pollinator describes a process in which ___.', ['Each species evolves in response to selective pressures exerted by the other', 'Only the plant evolves, while the pollinator remains completely unchanged', 'A concept unrelated to plant-pollinator relationships', 'The two species evolve in complete isolation from one another'], 0),
   ('Why might a flower’s shape closely match the body shape of a specific pollinator species, such as a particular species of moth?', ['A close structural match can make pollen transfer more efficient for that specific pollinator', 'A flower’s shape has no connection to which pollinators visit it', 'This kind of specialized matching never occurs between plants and pollinators', 'Every flower is pollinated equally well by every possible pollinator species'], 0),
   ('Why might a plant that relies on wind pollination typically produce flowers with less colourful petals and little scent compared to insect-pollinated flowers?', ['Attracting a specific animal pollinator is unnecessary when pollen is instead carried by the wind', 'Wind-pollinated plants always produce the most brightly coloured, strongly scented flowers', 'Pollination strategy has no connection to a flower’s colour or scent', 'This concept has no relevance to understanding plant reproduction'], 0),
   ('Why is the coevolutionary relationship between plants and pollinators considered ecologically significant?', ['A decline in pollinator populations can directly threaten the reproduction of the plant species that depend on them', 'Plants and their pollinators have no meaningful ecological connection to one another', 'Pollinator populations have no effect on plant reproduction rates', 'This relationship has no broader significance for ecosystems'], 0)]),
C('Chemistry: Photochemistry and Light-Induced Reactions',
  'Grade 11 Chemistry strand: photochemistry studies chemical reactions triggered when a molecule absorbs light energy, exciting an electron to a higher energy level and enabling reactions, such as photosynthesis or the breakdown of ozone, that would not otherwise occur.',
  [('Photochemistry studies chemical reactions that are triggered when a molecule ___.', ['Absorbs light energy', 'Is cooled to an extremely low temperature, with no connection to light', 'A process unrelated to photochemistry', 'Is placed under extremely high pressure, with no connection to light'], 0),
   ('When a molecule absorbs light energy in a photochemical reaction, an electron is typically ___.', ['Excited to a higher energy level', 'Removed from the molecule permanently, with no return possible', 'A change unrelated to photochemistry', 'Converted directly into a different element'], 0),
   ('Which of these is an example of a naturally occurring photochemical reaction?', ['Photosynthesis in a green plant', 'A reaction that occurs identically with or without the presence of light', 'A reaction entirely unrelated to the absorption of light', 'The freezing of water into ice'], 0),
   ('Why does the breakdown of ozone in the atmosphere depend on a photochemical reaction?', ['Ultraviolet light provides the energy needed to break the bonds within an ozone molecule', 'Ozone breaks down at an identical rate whether or not light is present', 'This process has no connection to the absorption of light energy', 'Photochemical reactions never occur within the atmosphere'], 0),
   ('Why is photochemistry considered relevant to technologies such as solar panels and photographic film?', ['These technologies rely on a chemical or electrical response triggered specifically by the absorption of light', 'Photochemistry has no connection to any modern technology', 'Solar panels and photographic film function with no dependence on light at all', 'This concept only applies to purely theoretical chemistry with no practical use'], 0)])]),

day(66, [
E('Grammar: Cohesion and Coherence in Extended Writing',
  'Grade 11 English strand: cohesion refers to how sentences and paragraphs are grammatically and lexically linked using devices like transitions and pronouns, while coherence refers to how logically and clearly the overall ideas in a piece of writing connect and flow.',
  [('Cohesion in writing refers to how sentences and paragraphs are ___.', ['Grammatically and lexically linked, using devices like transitions and pronouns', 'Printed on the page, with no connection to meaning', 'A concept unrelated to writing structure', 'Numbered in sequential order, with no connection to language'], 0),
   ('Coherence in writing refers to how ___.', ['Logically and clearly the overall ideas in a piece connect and flow', 'Long each individual sentence in a piece of writing is', 'A concept unrelated to writing structure', 'Many total paragraphs a piece of writing contains'], 0),
   ('Which is an example of a cohesive device a writer might use to link two sentences?', ['A transition word, such as “however” or “therefore”', 'A device entirely unrelated to linking sentences', 'Repeating the exact same sentence twice in a row', 'Leaving a blank line between every sentence'], 0),
   ('Why might a piece of writing be grammatically cohesive, with clear transitions, but still lack coherence overall?', ['The individual ideas may not logically build toward a clear, unified point, even if the sentences connect smoothly', 'Cohesion and coherence always mean exactly the same thing, with no possible difference between them', 'This situation can never occur in a piece of writing', 'A lack of coherence always results from missing transition words alone'], 0),
   ('Why is revising for both cohesion and coherence important in an extended piece of academic writing?', ['Together, they ensure a reader can follow both the sentence-to-sentence connections and the overall logical argument', 'Revising for cohesion and coherence has no effect on how clearly a piece of writing communicates its ideas', 'Extended academic writing never requires revision for either cohesion or coherence', 'A reason unrelated to producing clear, effective writing'], 0)]),
F('Functions: Solving Equations Graphically versus Algebraically',
  'Grade 11 Functions strand: an equation can be solved algebraically by manipulating symbols to isolate a variable, or graphically by finding where a function’s graph crosses the x-axis or where two graphs intersect, with each approach offering different advantages.',
  [('Solving an equation graphically typically involves finding where a graph ___.', ['Crosses the x-axis or intersects another graph', 'Reaches its exact maximum height, with no connection to solving equations', 'A concept unrelated to solving equations', 'Changes colour, with no connection to its shape'], 0),
   ('Solving an equation algebraically typically involves ___.', ['Manipulating symbols to isolate the variable', 'Sketching an accurate graph with no symbolic manipulation involved', 'A concept unrelated to solving equations', 'Guessing a solution with no further verification'], 0),
   ('Why might a graphical approach be especially useful for solving an equation that is difficult or impossible to solve algebraically?', ['A graph can reveal an approximate solution even when an exact algebraic method is not readily available', 'Graphical approaches can never provide any useful information about a solution', 'Every equation can always be solved exactly using algebra alone, with no exceptions', 'This advantage has no connection to solving equations'], 0),
   ('Why might an algebraic approach be preferred over a graphical approach when an exact solution is required?', ['Algebraic methods can produce a precise value, while reading a graph often only gives an approximate one', 'Algebraic methods always produce a less precise answer than a graph', 'Graphical methods always provide a more exact solution than algebraic methods', 'This distinction has no connection to how equations are solved'], 0),
   ('Why is it valuable for a student to be able to solve the same equation using both graphical and algebraic methods?', ['Comparing both methods can help confirm a solution is correct and build a deeper understanding of the relationship between an equation and its graph', 'Using both methods together provides no additional confidence in a solution', 'A reason unrelated to understanding how equations and graphs are connected', 'Graphical and algebraic methods can never be used to verify one another'], 0)]),
B('Biotechnology: Bioinformatics and DNA Sequencing',
  'Grade 11 Biology strand: bioinformatics combines biology with computer science to analyze large sets of biological data, particularly DNA sequences, allowing researchers to compare genomes, identify genes, and study evolutionary relationships at a molecular level.',
  [('Bioinformatics combines biology with ___.', ['Computer science', 'A field entirely unrelated to analyzing biological data', 'Architecture, with no connection to biological data', 'Physical education, with no connection to biological data'], 0),
   ('DNA sequencing is best described as a process that determines ___.', ['The exact order of nucleotides in a DNA molecule', 'The physical mass of a DNA molecule', 'A concept unrelated to DNA sequencing', 'The colour of a cell’s nucleus'], 0),
   ('Why is bioinformatics necessary for analyzing the enormous amount of data produced by modern DNA sequencing technology?', ['Computational tools can process and compare far more genetic data than would be possible using manual analysis alone', 'Bioinformatics has no connection to analyzing DNA sequencing data', 'DNA sequencing produces so little data that computational analysis is never needed', 'This field has no practical application in modern biology'], 0),
   ('Why might comparing DNA sequences across different species be useful for studying evolutionary relationships?', ['Greater similarity between DNA sequences can indicate a more recent shared common ancestor', 'DNA sequence comparisons provide no information about evolutionary relationships', 'Every species shares an identical DNA sequence, regardless of ancestry', 'This concept has no connection to the study of evolution'], 0),
   ('Why is bioinformatics considered valuable in fields such as medicine, including the development of personalized treatments?', ['Analyzing an individual’s genetic data can help identify specific genetic factors relevant to their health', 'Bioinformatics has no application in modern medicine', 'Genetic data provides no useful information for developing medical treatments', 'This concept only applies to purely theoretical research with no practical use'], 0)]),
C('Chemistry: Flame Tests and Atomic Emission',
  'Grade 11 Chemistry strand: a flame test identifies certain metal ions by the characteristic colour they produce when heated, a result of electrons absorbing energy, jumping to a higher energy level, and then releasing that energy as light of a specific wavelength when they fall back down.',
  [('A flame test identifies certain metal ions based on the ___ they produce when heated.', ['Characteristic colour', 'Exact mass, with no connection to colour', 'A property unrelated to flame tests', 'Boiling point, with no connection to colour'], 0),
   ('The characteristic colour seen in a flame test results from an electron ___.', ['Falling back to a lower energy level and releasing energy as light', 'Being permanently removed from the atom, with no return possible', 'A process unrelated to atomic emission', 'Splitting the nucleus of the atom into smaller fragments'], 0),
   ('Why does heating a metal ion in a flame first cause an electron to jump to a higher energy level?', ['The electron absorbs energy from the flame, allowing it to move to a less stable, higher-energy position', 'Electrons are removed from the atom entirely when the flame is applied', 'Heating a metal ion has no effect on the position of its electrons', 'This process has no connection to atomic emission'], 0),
   ('Why does each metal ion tend to produce a distinct, characteristic flame colour rather than an identical colour for every metal?', ['Each element has its own unique set of energy levels, so the light released has a specific wavelength', 'Every metal ion always produces an identical colour when heated in a flame', 'Flame colour has no connection to the internal energy levels of an atom', 'This concept has no scientific basis'], 0),
   ('Why are flame tests considered a useful, quick qualitative technique in a chemistry laboratory?', ['They allow certain metal ions to be identified rapidly using a simple, low-cost procedure', 'Flame tests provide no useful information for identifying an unknown substance', 'This technique requires expensive, highly specialized equipment unavailable in most laboratories', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(67, [
E('Literature: The Confessional Poem',
  'Grade 11 English strand: a confessional poem draws directly on the poet’s own personal, often intimate or painful experiences, using a candid first-person voice to explore emotions that earlier poetic traditions frequently kept private.',
  [('A confessional poem draws directly on the poet’s own ___.', ['Personal, often intimate or painful experiences', 'Entirely invented experiences with no connection to the poet’s own life', 'A concept unrelated to poetry', 'Purely factual, historical events with no personal connection'], 0),
   ('Confessional poetry is typically written using a ___ voice.', ['Candid first-person', 'Distant, impersonal third-person', 'A voice unrelated to confessional poetry', 'Voice that avoids any expression of emotion'], 0),
   ('Why might a confessional poem address a topic that earlier poetic traditions often avoided discussing openly?', ['Confessional poetry values direct honesty about personal experience over maintaining a more formal, reserved distance', 'Confessional poetry always avoids any topic connected to personal experience', 'Earlier poetic traditions never avoided any particular subject matter', 'This choice has no connection to the goals of confessional poetry'], 0),
   ('Why might a reader find a confessional poem especially emotionally resonant compared to a more impersonal poem?', ['The poem’s candid, personal voice can create a strong sense of intimacy and honesty with the reader', 'Confessional poems are always less emotionally engaging than impersonal poems', 'A poem’s use of a personal voice has no effect on how a reader experiences it', 'This concept has no connection to how poetry communicates emotion'], 0),
   ('Why might critics debate whether a confessional poem should be read as strictly autobiographical?', ['A poet may shape or heighten real experiences for artistic effect, blurring the line between fact and craft', 'Every confessional poem is always an exact, unaltered record of true events', 'This question has no relevance to interpreting confessional poetry', 'Confessional poems never contain any element of artistic shaping or invention'], 0)]),
F('Functions: Systems of Three Linear Equations',
  'Grade 11 Functions strand: a system of three linear equations in three variables can be solved using elimination or substitution to systematically reduce the system, and its solution represents the single point where all three planes intersect, if one exists.',
  [('A system of three linear equations in three variables has a solution that represents ___.', ['The single point where all three planes intersect, if one exists', 'The area enclosed by all three equations combined', 'A concept unrelated to systems of equations', 'The exact midpoint between any two of the three equations'], 0),
   ('A common strategy for solving a system of three linear equations is to first ___.', ['Eliminate one variable to reduce the system to two equations with two variables', 'Ignore two of the three equations entirely', 'A strategy unrelated to solving systems of equations', 'Add all three equations together with no further steps taken'], 0),
   ('Why might a system of three linear equations have no solution at all?', ['The three planes represented by the equations may never intersect at a single common point', 'Every system of three linear equations always has exactly one solution', 'A system with no solution can never occur when working with linear equations', 'This outcome has no connection to how the equations relate to one another'], 0),
   ('Why might a system of three linear equations have infinitely many solutions?', ['The three equations may represent planes that intersect along a shared line or are otherwise dependent on one another', 'Infinitely many solutions can never occur in a system of linear equations', 'This outcome has no connection to how the three planes are positioned relative to one another', 'A system always has either exactly one solution or no solution at all, with no other possibility'], 0),
   ('Why might a system of three linear equations be useful for modelling a real-world situation involving three related unknown quantities, such as the cost of three different products?', ['It allows all three unknown quantities to be determined simultaneously using the relationships described by the equations', 'Systems of three linear equations have no real-world modelling applications', 'This type of situation can never be represented using a system of equations', 'This concept only applies to purely abstract mathematics with no practical use'], 0)]),
B('Biology: Animal Adaptations to Extreme Environments',
  'Grade 11 Biology strand: animals living in extreme environments, such as deserts, polar regions, or high altitudes, have evolved specialized structural, physiological, and behavioural adaptations that allow them to survive conditions that would be lethal to most other species.',
  [('An adaptation is best described as a trait that ___.', ['Improves an organism’s ability to survive and reproduce in its environment', 'Always harms an organism’s chances of survival', 'A concept unrelated to evolutionary biology', 'Has no effect at all on an organism’s survival or reproduction'], 0),
   ('Which is an example of a structural adaptation that helps an animal survive in a cold, polar environment?', ['A thick layer of insulating blubber', 'A structural feature entirely unrelated to surviving cold temperatures', 'Large ears that maximize heat loss', 'Thin fur with no insulating properties at all'], 0),
   ('Which is an example of a physiological adaptation that helps an animal survive in a hot desert environment?', ['The ability to produce highly concentrated urine that conserves water', 'A physiological process entirely unrelated to conserving water', 'A process that always increases water loss regardless of the environment', 'The complete inability to regulate internal body temperature'], 0),
   ('Why might a behavioural adaptation, such as being active only at night, help an animal survive in a hot desert environment?', ['Avoiding activity during the hottest part of the day can reduce water loss and the risk of overheating', 'Behavioural adaptations have no connection to helping an animal survive extreme temperatures', 'Being active only at night always increases an animal’s risk of overheating', 'This concept has no relevance to understanding animal adaptations'], 0),
   ('Why do animals living at high altitudes often have physiological adaptations related to oxygen use, such as an increased concentration of red blood cells?', ['Air at high altitudes contains less available oxygen, so the body must adapt to transport it more efficiently', 'Oxygen availability is identical at every altitude, with no variation at all', 'High-altitude environments have no connection to an animal’s oxygen-related adaptations', 'This concept has no relevance to understanding animal physiology'], 0)]),
C('Chemistry: Soaps, Detergents, and Surfactant Chemistry',
  'Grade 11 Chemistry strand: soaps and detergents are surfactants, molecules with a water-attracting head and a water-repelling, fat-attracting tail, allowing them to surround grease and oil particles so they can be lifted away and rinsed off with water.',
  [('A surfactant molecule, such as one found in soap, has a structure with ___.', ['A water-attracting head and a water-repelling, fat-attracting tail', 'Two identical water-attracting ends, with no water-repelling portion', 'A concept unrelated to surfactant chemistry', 'Two identical water-repelling ends, with no water-attracting portion'], 0),
   ('The water-attracting portion of a surfactant molecule is described as ___.', ['Hydrophilic', 'Hydrophobic, with no connection to attracting water', 'A term unrelated to surfactant chemistry', 'Insoluble, with no connection to water at all'], 0),
   ('Why can a surfactant molecule surround a grease or oil particle in water?', ['Its water-repelling tail attaches to the grease while its water-attracting head faces outward into the surrounding water', 'Surfactant molecules have no interaction at all with grease or oil particles', 'Grease and oil dissolve directly in water without any need for a surfactant', 'This process has no connection to the structure of a surfactant molecule'], 0),
   ('Why is soap generally less effective than synthetic detergents in hard water, which contains dissolved calcium and magnesium ions?', ['Soap can react with these ions to form an insoluble precipitate, often seen as soap scum, reducing its cleaning ability', 'Soap always cleans more effectively in hard water than any synthetic detergent', 'Hard water has no effect on the cleaning ability of soap', 'This concept has no connection to surfactant chemistry'], 0),
   ('Why are surfactants considered essential to the function of everyday cleaning products?', ['They allow water, which does not dissolve grease and oil on its own, to lift and rinse away those substances', 'Surfactants have no practical role in cleaning products', 'Water alone is always equally effective at removing grease and oil without any surfactant', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(68, [
E('Writing: The Elegy and Commemorative Writing',
  'Grade 11 English strand: an elegy is a reflective piece of writing, often a poem, composed to mourn or commemorate someone or something that has been lost, typically moving from an expression of grief toward some form of consolation or acceptance.',
  [('An elegy is best described as a reflective piece of writing composed to ___.', ['Mourn or commemorate someone or something that has been lost', 'Celebrate an achievement with no connection to loss or grief', 'A concept unrelated to commemorative writing', 'Provide a purely factual, unemotional record of an event'], 0),
   ('An elegy often moves from an initial expression of grief toward ___.', ['Some form of consolation or acceptance', 'An abrupt ending with no further development', 'A concept unrelated to the structure of an elegy', 'A tone of anger that never resolves in any way'], 0),
   ('Which is an example of a subject an elegy might commemorate?', ['The death of a loved one', 'A subject entirely unrelated to loss or commemoration', 'A purely hypothetical event that never actually occurred', 'An upcoming celebration with no connection to loss'], 0),
   ('Why might a writer use vivid, sensory imagery when composing an elegy?', ['Sensory detail can help preserve and honour a specific memory of what has been lost', 'Imagery has no connection to how an elegy conveys meaning', 'Elegies are always written using flat, unemotional language with no imagery', 'This technique has no relevance to commemorative writing'], 0),
   ('Why might writing an elegy be considered a meaningful way for a writer to process grief?', ['Putting loss into words can help a writer reflect on and find some sense of meaning in a difficult experience', 'Writing about a difficult experience never has any emotional value for the writer', 'An elegy is only ever written for a stranger, with no personal connection to the writer', 'This concept has no connection to the purpose of commemorative writing'], 0)]),
F('Number Theory: The Real Number System',
  'Grade 11 Functions strand: the real number system organizes numbers into nested categories — natural numbers, whole numbers, integers, rational numbers, and irrational numbers — each broader category containing the ones before it.',
  [('A rational number is best described as a number that can be expressed as ___.', ['A ratio of two integers, with a non-zero denominator', 'A decimal that never ends and never repeats', 'A concept unrelated to the real number system', 'A number that cannot be written as a fraction under any circumstances'], 0),
   ('An irrational number is best described as a number whose decimal representation ___.', ['Never ends and never repeats in a pattern', 'Always terminates after a small number of digits', 'A concept unrelated to the real number system', 'Always repeats in an identical, predictable pattern'], 0),
   ('Which of these is an example of an irrational number?', ['Pi (the ratio of a circle’s circumference to its diameter)', 'A number entirely unrelated to the real number system', 'One-half, expressed as the fraction 1/2', 'The whole number 4'], 0),
   ('Why are all integers also considered rational numbers?', ['Every integer can be expressed as a ratio of itself to 1, satisfying the definition of a rational number', 'Integers can never be expressed as a ratio of two whole numbers', 'This relationship has no connection to how numbers are classified', 'Integers and rational numbers describe two entirely separate, non-overlapping categories'], 0),
   ('Why is understanding the nested structure of the real number system useful when solving equations, such as recognizing when a solution is irrational?', ['It helps identify what kind of number a solution actually is, which can affect how that solution is interpreted or approximated', 'This structure has no connection to solving or interpreting equations', 'Every solution to every equation is always a rational number', 'This concept only applies to purely abstract mathematics with no practical use'], 0)]),
B('Human Biology: The Brain — Structure and Higher Function',
  'Grade 11 Biology strand: the human brain is organized into regions, including the cerebrum, cerebellum, and brainstem, each responsible for different functions ranging from voluntary movement and higher-order thinking to basic life-sustaining processes.',
  [('The cerebrum is primarily responsible for ___.', ['Higher-order thinking, sensory processing, and voluntary movement', 'Only regulating heart rate, with no connection to thought', 'A concept unrelated to the brain’s structure', 'Producing red blood cells exclusively'], 0),
   ('The cerebellum primarily coordinates ___.', ['Balance and fine motor coordination', 'Long-term memory storage exclusively', 'A function unrelated to the brain’s structure', 'Digestion of food within the stomach'], 0),
   ('The brainstem is primarily responsible for regulating ___.', ['Basic life-sustaining processes, such as breathing and heart rate', 'Complex, abstract problem-solving exclusively', 'A concept unrelated to the brain’s structure', 'The five senses exclusively, with no connection to basic life functions'], 0),
   ('Why might damage to the cerebellum specifically affect a person’s balance and coordination, rather than their ability to think abstractly?', ['Different brain regions are specialized for different functions, so damage to one region primarily affects the processes it controls', 'Every region of the brain performs an identical function, so damage anywhere produces identical effects', 'The cerebellum has no connection to controlling balance or coordination', 'This concept has no relevance to understanding brain structure'], 0),
   ('Why is understanding the specialized regions of the brain useful in fields such as neurology and psychology?', ['It helps explain how specific injuries or conditions might affect particular abilities, such as movement, memory, or language', 'Brain structure has no connection to understanding injury or illness', 'Every function of the brain is controlled equally by every brain region', 'This concept has no practical application outside of basic biology'], 0)]),
C('Chemistry: Food Chemistry and the Maillard Reaction',
  'Grade 11 Chemistry strand: the Maillard reaction is a chemical reaction between amino acids and reducing sugars that occurs when food is heated, producing the browning, flavour, and aroma characteristic of foods such as toasted bread and seared meat.',
  [('The Maillard reaction occurs between amino acids and ___.', ['Reducing sugars', 'Water molecules exclusively, with no connection to sugars', 'A substance unrelated to food chemistry', 'Salt crystals, with no connection to amino acids'], 0),
   ('The Maillard reaction is primarily responsible for producing a food’s ___.', ['Browning, flavour, and aroma when heated', 'Exact nutritional content, with no connection to browning', 'A property unrelated to food chemistry', 'Colour before it has been heated at all'], 0),
   ('Why does the Maillard reaction typically require heat in order to occur?', ['Heat provides the energy needed for the amino acids and sugars to react and form new flavour and colour compounds', 'The Maillard reaction occurs at an identical rate regardless of temperature', 'Heat has no connection to the chemical reaction responsible for browning food', 'This reaction only occurs at temperatures below freezing'], 0),
   ('Which of these is an example of a food where the Maillard reaction produces a noticeable effect?', ['Seared meat developing a browned, flavourful crust', 'A food that shows no change at all when heated', 'An example entirely unrelated to food chemistry', 'A glass of cold water left at room temperature'], 0),
   ('Why is understanding the Maillard reaction useful for both home cooks and the food industry?', ['It helps explain how cooking temperature and time can be controlled to achieve a desired flavour, aroma, and appearance', 'The Maillard reaction has no practical application in cooking or food preparation', 'Cooking temperature has no effect on a food’s flavour or appearance', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(69, [
E('Independent Reading: Postmodern Fiction and Fragmented Narrative',
  'Grade 11 English strand: postmodern fiction often rejects a single, linear plot in favour of a fragmented narrative structure, non-traditional chronology, and self-aware storytelling that challenges a reader’s expectations of how a story should be told.',
  [('Postmodern fiction often rejects a ___ in favour of a fragmented narrative structure.', ['Single, linear plot', 'Story with any characters at all', 'A concept unrelated to narrative structure', 'Story that contains any dialogue whatsoever'], 0),
   ('A fragmented narrative structure is best described as one that ___.', ['Presents a story in disconnected or non-chronological pieces', 'Always presents events in strict chronological order with no exceptions', 'A concept unrelated to postmodern fiction', 'Contains only a single scene with no other narrative content'], 0),
   ('Why might a postmodern novel present events out of chronological order?', ['This structure can mirror the fragmented, non-linear way memory or perception can actually work', 'A fragmented structure always makes a story easier to follow than a linear one', 'Chronological order has no connection to how a story is structured', 'Postmodern fiction always presents events in strict chronological order'], 0),
   ('Why might postmodern fiction draw attention to its own artificiality as a constructed story, similar to metafiction?', ['It can challenge a reader’s assumption that a story presents a single, objective version of reality', 'Drawing attention to a story’s construction has no effect on how a reader interprets it', 'Postmodern fiction always presents itself as a completely objective, factual account', 'This technique has no connection to postmodern literary traditions'], 0),
   ('Why might reading fragmented, postmodern narratives build valuable interpretive skills for a student?', ['Piecing together a non-linear structure requires active inference and a tolerance for ambiguity', 'Fragmented narratives require no interpretive effort from a reader at all', 'This type of reading has no connection to building literary analysis skills', 'A reason unrelated to independent reading'], 0)]),
F('Quadratic Relations: Introduction to Conic Sections (Circles)',
  'Grade 11 Functions strand: a circle is a conic section defined as the set of all points equidistant from a fixed centre point, and its equation can be written in standard form using the coordinates of the centre and the length of the radius.',
  [('A circle is defined as the set of all points that are ___ from a fixed centre point.', ['Equidistant', 'At a constantly changing distance, with no fixed relationship', 'A concept unrelated to conic sections', 'Located directly on the centre point itself'], 0),
   ('In the standard form equation of a circle, the value r represents the circle’s ___.', ['Radius', 'Diameter, with no connection to the radius', 'A value unrelated to a circle’s equation', 'Circumference, with no connection to the radius'], 0),
   ('For a circle with the equation x squared plus y squared equals 25, what is the radius of the circle?', ['5', '25', 'A value unrelated to this equation', '10'], 0),
   ('Why is a circle considered a type of conic section?', ['It can be formed by slicing a cone with a plane perpendicular to the cone’s axis', 'Circles have no mathematical relationship to a cone of any kind', 'A concept unrelated to how conic sections are defined', 'A circle can only ever be created by slicing a cube, not a cone'], 0),
   ('Why is being able to identify a circle’s centre and radius directly from its standard form equation useful for graphing it quickly?', ['It allows the circle to be plotted immediately, without needing to generate and plot a long table of individual points', 'The standard form equation provides no useful information for graphing a circle', 'A circle can never be graphed using information from its equation alone', 'This concept only applies to purely abstract mathematics with no practical use'], 0)]),
B('Ecology: Freshwater Ecosystems and Watershed Health',
  'Grade 11 Biology strand: freshwater ecosystems, including lakes, rivers, and wetlands, form part of larger watersheds, and the health of these systems depends on factors such as water quality, nutrient levels, and the surrounding land use within that watershed.',
  [('A watershed is best described as an area of land that ___.', ['Drains into a common body of water, such as a river or lake', 'Never has any connection to a body of water', 'A concept unrelated to freshwater ecosystems', 'Contains only a single isolated pond with no surrounding drainage'], 0),
   ('Which of these is an example of a freshwater ecosystem?', ['A wetland', 'An ecosystem entirely unrelated to freshwater', 'A coral reef found in the open ocean', 'A desert with no permanent water source'], 0),
   ('Why might excess nutrient runoff from surrounding farmland negatively affect the health of a freshwater lake within its watershed?', ['Excess nutrients can trigger algal blooms that deplete oxygen levels in the water as they decompose', 'Nutrient runoff always improves the overall health of a freshwater ecosystem', 'Land use within a watershed has no effect on the water quality of a connected lake', 'This concept has no relevance to understanding freshwater ecosystems'], 0),
   ('Why are wetlands often described as valuable for filtering pollutants before they reach a larger body of water?', ['Wetland vegetation and soil can trap and break down certain pollutants as water slowly moves through them', 'Wetlands have no effect on the water quality of a connected watershed', 'Pollutants are never filtered or reduced by any natural process within a wetland', 'This concept has no relevance to understanding watershed health'], 0),
   ('Why is understanding the connection between land use and water quality important for protecting freshwater ecosystems within a watershed?', ['Human activity anywhere within a watershed can ultimately affect the water quality of the freshwater systems it drains into', 'Land use has no meaningful connection to the health of a freshwater ecosystem', 'Freshwater ecosystems are always completely unaffected by human activity', 'This concept has no relevance to ecological conservation efforts'], 0)]),
C('Chemistry: Phase Diagrams and Sublimation',
  'Grade 11 Chemistry strand: a phase diagram shows the conditions of temperature and pressure under which a substance exists as a solid, liquid, or gas, and sublimation is the direct transition from a solid to a gas without passing through a liquid state.',
  [('A phase diagram shows the conditions of ___ under which a substance exists as a solid, liquid, or gas.', ['Temperature and pressure', 'Colour and density exclusively, with no connection to phase', 'A concept unrelated to a substance’s physical state', 'Mass and volume exclusively, with no connection to phase'], 0),
   ('Sublimation is best described as a direct transition from a ___ to a gas.', ['Solid, without passing through a liquid state', 'Liquid, without passing through a solid state', 'A concept unrelated to phase changes', 'Gas, with no connection to a change of state at all'], 0),
   ('Which of these is a commonly cited example of a substance that readily sublimates at everyday pressures?', ['Dry ice (solid carbon dioxide)', 'A substance entirely unrelated to sublimation', 'Liquid water at room temperature', 'Table salt dissolved in water'], 0),
   ('On a phase diagram, the triple point represents the unique condition at which a substance can exist ___.', ['As a solid, liquid, and gas simultaneously, in equilibrium', 'Only as a solid, with no other phase possible', 'A concept unrelated to phase diagrams', 'Only as a gas, with no other phase possible'], 0),
   ('Why is a phase diagram a useful tool for predicting how a substance will behave under a specific set of conditions, such as at a very high altitude?', ['It shows exactly which phase a substance will be in at a given combination of temperature and pressure', 'A phase diagram provides no useful information about how a substance behaves under different conditions', 'Temperature and pressure have no connection to the phase a substance takes', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(70, [
E('Review: Epistolary Novels, Manifestos, and Fragmented Narrative',
  'Grade 11 English strand review: this lesson revisits the epistolary novel, the persuasive manifesto, news bias and fact-checking, debate rebuttal and cross-examination, the character study essay, cohesion and coherence, the confessional poem, the elegy, and postmodern fragmented narrative.',
  [('An epistolary novel tells its story primarily through ___.', ['Documents such as letters, diary entries, or emails', 'A single omniscient narrator describing events from outside the story', 'A concept unrelated to novel structure', 'A series of stage directions with no narration at all'], 0),
   ('A manifesto is best described as a public declaration of ___.', ['Beliefs and intentions', 'A private, confidential opinion never meant to be shared', 'A concept unrelated to persuasive writing', 'Purely factual, statistical data with no viewpoint expressed'], 0),
   ('An elegy is best described as a reflective piece of writing composed to ___.', ['Mourn or commemorate someone or something that has been lost', 'Celebrate an achievement with no connection to loss or grief', 'A concept unrelated to commemorative writing', 'Provide a purely factual, unemotional record of an event'], 0),
   ('A fragmented narrative structure is best described as one that ___.', ['Presents a story in disconnected or non-chronological pieces', 'Always presents events in strict chronological order with no exceptions', 'A concept unrelated to postmodern fiction', 'Contains only a single scene with no other narrative content'], 0),
   ('Why is it useful to review these varied reading, writing, and communication skills together?', ['They reinforce complementary approaches to interpreting and producing texts effectively', 'These skills have no connection to each other', 'Review is never useful for English language skills', 'Each skill must be studied with no connection to the others'], 0)]),
F('Review: Discrete Math, Trigonometry, and Number Systems',
  'Grade 11 Functions strand review: this lesson revisits set theory and Venn diagrams, graph theory, the ambiguous case of the sine law, measures of central tendency and spread, optimization with quadratic models, solving equations graphically versus algebraically, systems of three linear equations, the real number system, and conic sections.',
  [('A set is best described as ___.', ['A well-defined collection of distinct objects', 'A collection that may repeat the same object many times', 'A concept unrelated to discrete mathematics', 'A single object with no connection to a collection'], 0),
   ('The ambiguous case of the sine law arises when a triangle is defined by ___.', ['Two sides and a non-included angle', 'Three sides and no angles at all', 'A concept unrelated to solving triangles', 'Two angles and no sides at all'], 0),
   ('The median of a data set is best described as ___.', ['The middle value when the data is arranged in order', 'The value that appears most often in the data set', 'A concept unrelated to central tendency', 'The difference between the largest and smallest values'], 0),
   ('An irrational number is best described as a number whose decimal representation ___.', ['Never ends and never repeats in a pattern', 'Always terminates after a small number of digits', 'A concept unrelated to the real number system', 'Always repeats in an identical, predictable pattern'], 0),
   ('Why is it useful to review discrete mathematics, trigonometry, and number systems together?', ['It reinforces how these mathematical tools and reasoning skills connect and build on one another', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
B('Review: Genetics, Anatomy, and Ecosystems',
  'Grade 11 Biology strand review: this lesson revisits sex-linked inheritance and pedigree analysis, the Hardy-Weinberg principle, comparative anatomy, extremophiles, pollination strategies, bioinformatics, animal adaptations to extreme environments, the brain, and freshwater ecosystems.',
  [('A sex-linked trait is carried on ___.', ['The X or Y chromosome', 'An autosome that is unrelated to sex chromosomes', 'A concept unrelated to inheritance', 'A structure found only in plant cells'], 0),
   ('A homologous structure is best described as a feature that shares a ___ despite serving a different function across species.', ['Similar underlying form', 'Identical function, with no connection to structure', 'A concept unrelated to comparative anatomy', 'Completely unrelated form across every species'], 0),
   ('An extremophile is best described as an organism that ___.', ['Thrives in conditions once thought too harsh for life', 'Can only survive in mild, temperate environments', 'A concept unrelated to biology', 'Requires an environment identical to that of most other organisms'], 0),
   ('A watershed is best described as an area of land that ___.', ['Drains into a common body of water, such as a river or lake', 'Never has any connection to a body of water', 'A concept unrelated to freshwater ecosystems', 'Contains only a single isolated pond with no surrounding drainage'], 0),
   ('Why is it useful to review genetics, anatomy, and ecosystem concepts together?', ['It reinforces how these interconnected biological concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in biology', 'Each topic must be studied with no connection to the others'], 0)]),
C('Review: Atomic Trends, Analytical Techniques, and Applied Chemistry',
  'Grade 11 Chemistry strand review: this lesson revisits periodic trends in atomic properties, empirical and molecular formula determination, colorimetry, acid rain, photochemistry, flame tests, surfactant chemistry, food chemistry, and phase diagrams.',
  [('Atomic radius generally ___ across a period from left to right.', ['Decreases', 'Increases, with no connection to nuclear charge', 'A pattern unrelated to atomic structure', 'Stays exactly the same in every case'], 0),
   ('Beer’s law describes a direct relationship between a solution’s absorbance and its ___.', ['Concentration', 'Exact temperature, with no connection to absorbance', 'A property unrelated to colorimetry', 'Physical volume, with no connection to concentration'], 0),
   ('The characteristic colour seen in a flame test results from an electron ___.', ['Falling back to a lower energy level and releasing energy as light', 'Being permanently removed from the atom, with no return possible', 'A process unrelated to atomic emission', 'Splitting the nucleus of the atom into smaller fragments'], 0),
   ('Sublimation is best described as a direct transition from a ___ to a gas.', ['Solid, without passing through a liquid state', 'Liquid, without passing through a solid state', 'A concept unrelated to phase changes', 'Gas, with no connection to a change of state at all'], 0),
   ('Why is it useful to review atomic trends, analytical techniques, and applied chemistry together?', ['It reinforces how these interconnected chemistry concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in chemistry', 'Each topic must be studied with no connection to the others'], 0)])]),
]

def _rebalance_answer_positions(days, seed=20260818):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g11_61_70)
    append_to(11, g11_61_70)
