#!/usr/bin/env python3
"""Phase 3: Grade 11, Days 41-50 (second Grade 11 batch). Topics chosen
to avoid any overlap with the existing Day 1-40 set (see
data/grade11.json): existentialism in drama, unreliable narrators,
radical functions, Pascal's triangle, expected value, nutrient cycles,
polygenic inheritance, stem cell research, intermolecular forces, and
spectroscopy.

Subject keys for Grade 11 are "English", "Functions", "Biology",
"Chemistry" (same as gen_grade11_days31_40.py).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys
sys.path.insert(0, '/sessions/modest-compassionate-lamport/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E11 = 'https://tvolearn.com/pages/grade-11-english'
F11 = 'https://tvolearn.com/pages/grade-11-functions'
B11 = 'https://tvolearn.com/pages/grade-11-biology'
C11 = 'https://tvolearn.com/pages/grade-11-chemistry'
RE, RF, RB, RC = (
    'TVO Learn: Grade 11 English',
    'TVO Learn: Grade 11 Functions',
    'TVO Learn: Grade 11 Biology',
    'TVO Learn: Grade 11 Chemistry',
)


def E(t, s, q):
    return sub('English', t, s, RE, E11, q)


def F(t, s, q):
    return sub('Functions', t, s, RF, F11, q)


def B(t, s, q):
    return sub('Biology', t, s, RB, B11, q)


def C(t, s, q):
    return sub('Chemistry', t, s, RC, C11, q)


g11_41_50 = [
day(41, [
E('Literature: Existentialism in Modern Drama',
  'Grade 11 English strand: existentialist drama explores themes of individual freedom, meaninglessness, and the search for purpose in an indifferent or absurd universe.',
  [('Existentialist drama often explores themes of ___.', ['Individual freedom, meaninglessness, and the search for purpose', 'Only lighthearted, comedic subject matter', 'A topic entirely unrelated to human experience', 'Historical events with no connection to personal meaning'], 0),
   ('Why might a playwright present a universe as “indifferent” or “absurd” in an existentialist work?', ['To highlight a character’s struggle to create meaning despite a lack of inherent purpose', 'This portrayal always removes any depth from a play', 'An indifferent universe has no connection to existentialist themes', 'Absurdity has no role in this genre of drama'], 0),
   ('Which is an example of a choice a character in existentialist drama might face?', ['Deciding how to act with no clear guidance from society or fate', 'A choice with no connection to personal freedom', 'A decision that is always made for the character with no agency', 'A choice unrelated to the play’s central themes'], 0),
   ('Why might individual freedom be considered both empowering and burdensome in existentialist thought?', ['Freedom to choose also means taking full responsibility for the consequences of those choices', 'Freedom has no connection to responsibility in existentialist thought', 'This concept is never explored in existentialist drama', 'Individual freedom is always portrayed as entirely effortless'], 0),
   ('Why do audiences continue to find existentialist drama relevant today?', ['Questions about purpose and meaning remain universally significant to human experience', 'Existentialist themes have no relevance to modern audiences', 'This genre of drama has no lasting significance', 'These questions were only relevant during a specific historical period'], 0)]),
F('Radical Functions and Their Graphs',
  'Grade 11 Functions strand: a radical function contains a variable inside a root, such as a square root, and its graph and domain are affected by the restriction that the expression under the root cannot be negative.',
  [('A radical function contains a variable inside a ___.', ['Root, such as a square root', 'A denominator only, with no connection to roots', 'An exponent only, with no root involved', 'A function unrelated to roots'], 0),
   ('For a square root function to be defined using real numbers, the expression under the root must be ___.', ['Greater than or equal to zero', 'Always negative', 'Equal to exactly one', 'A value unrelated to the function’s domain'], 0),
   ('Why does the domain of a square root function often have a restriction?', ['The square root of a negative number is not a real number', 'Square root functions never have any domain restrictions', 'This restriction has no connection to how square roots behave', 'All real numbers can always be used under a square root'], 0),
   ('What is a defining feature of the graph of a basic square root function, y equals the square root of x?', ['It starts at the origin and only extends to the right', 'It extends infinitely in all four directions with no starting point', 'It has no defined starting point at all', 'It is a straight line passing through the origin'], 0),
   ('Why might radical functions be useful for modelling real-world situations, such as the relationship between an object’s speed and stopping distance?', ['They can represent relationships where one quantity depends on the root of another', 'Radical functions have no real-world modelling applications', 'This type of situation can never be represented mathematically', 'This concept only applies to purely abstract mathematics'], 0)]),
B('Ecology: Nutrient Cycles and Biogeochemistry',
  'Grade 11 Biology strand: nutrient cycles, such as the carbon and nitrogen cycles, describe how essential elements move through living organisms and the physical environment.',
  [('Nutrient cycles describe how essential elements move through ___.', ['Living organisms and the physical environment', 'Only living organisms, with no connection to the environment', 'A concept unrelated to ecosystems', 'Only the physical environment, with no connection to organisms'], 0),
   ('Which is an example of a nutrient cycle studied in ecology?', ['The carbon cycle', 'A cycle entirely unrelated to essential elements', 'A concept unrelated to biogeochemistry', 'A process with no connection to living organisms'], 0),
   ('Why are nutrient cycles important for sustaining life on Earth?', ['They ensure essential elements remain available for use by living organisms over time', 'Nutrient cycles have no connection to sustaining life', 'These cycles serve no biological purpose', 'This concept has no relevance to ecosystem health'], 0),
   ('Which process might contribute to moving carbon from the atmosphere into living organisms?', ['Photosynthesis', 'A process entirely unrelated to carbon', 'An action with no connection to plants', 'A process that removes carbon from all ecosystems permanently'], 0),
   ('Why might human activities, such as burning fossil fuels, disrupt natural nutrient cycles?', ['They can release stored carbon at a rate faster than natural processes can absorb it', 'Human activities have no effect on natural nutrient cycles', 'Nutrient cycles are entirely unaffected by any external factors', 'This concept has no connection to environmental science'], 0)]),
C('Chemistry: Intermolecular Forces and Physical Properties',
  'Grade 11 Chemistry strand: intermolecular forces are attractions between molecules that influence physical properties like boiling point, melting point, and solubility.',
  [('Intermolecular forces are attractions that occur ___.', ['Between molecules', 'Only within a single atom, with no connection to other molecules', 'A concept unrelated to molecular interactions', 'Exclusively within a single molecule’s own bonds'], 0),
   ('Which physical property can be influenced by the strength of intermolecular forces?', ['Boiling point', 'The exact atomic number of an element', 'A property entirely unrelated to molecular interactions', 'The number of protons in an atom’s nucleus'], 0),
   ('Why might a substance with stronger intermolecular forces generally have a higher boiling point?', ['More energy is required to overcome the stronger attractions between molecules', 'Intermolecular forces have no effect on a substance’s boiling point', 'Boiling point is determined entirely by atomic mass, with no other factors', 'This relationship has no connection to molecular behaviour'], 0),
   ('Which is an example of a type of intermolecular force?', ['Hydrogen bonding', 'A force found only within a single atom’s nucleus', 'A concept unrelated to molecular attraction', 'A type of force that only occurs in solid metals'], 0),
   ('Why is understanding intermolecular forces useful for predicting whether two substances will mix, or be soluble in one another?', ['Similar types and strengths of intermolecular forces often allow substances to dissolve into one another effectively', 'Intermolecular forces have no connection to solubility', 'Solubility is determined entirely at random, with no predictable pattern', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(42, [
E('Writing: The Op-Ed and Public Argument',
  'Grade 11 English strand: an op-ed presents a clear, well-supported argument on a public issue, aiming to persuade readers through evidence, logical reasoning, and a compelling authorial voice.',
  [('An op-ed presents a clear, well-supported argument on ___.', ['A public issue', 'A topic entirely unrelated to public discussion', 'Only a private matter with no public relevance', 'A subject that requires no supporting evidence'], 0),
   ('Why should an op-ed rely on logical reasoning to support its argument?', ['Sound reasoning strengthens the credibility and persuasiveness of the piece', 'Logical reasoning has no role in persuasive writing', 'An op-ed should avoid using any reasoning or evidence', 'Logic always weakens the emotional impact of an argument'], 0),
   ('Why might a compelling authorial voice help make an op-ed more effective?', ['A strong, distinct voice can better engage and persuade readers', 'Voice has no connection to how persuasive a piece of writing is', 'An op-ed should always sound completely neutral and impersonal', 'This element is only relevant in purely creative writing'], 0),
   ('Which is an example of an appropriate topic for a public argument in an op-ed?', ['A current policy debate affecting the community', 'A topic with no connection to any public issue', 'A purely factual, non-debatable topic', 'A subject with no relevance to readers at all'], 0),
   ('Why is it valuable for a writer to anticipate counterarguments when crafting a public argument?', ['Addressing counterarguments can strengthen the overall persuasiveness of the piece', 'Counterarguments should never be considered in this type of writing', 'Anticipating opposing views always weakens an argument', 'This step has no connection to effective persuasive writing'], 0)]),
F('Discrete Math: Pascal’s Triangle and the Binomial Theorem',
  'Grade 11 Functions strand: Pascal’s Triangle is a triangular array of numbers where each number is the sum of the two directly above it, and it provides the coefficients used in the Binomial Theorem.',
  [('In Pascal’s Triangle, each number is found by ___.', ['Adding the two numbers directly above it', 'Multiplying the row number by itself', 'A method unrelated to the numbers above it', 'Subtracting the two numbers above it'], 0),
   ('Pascal’s Triangle provides the coefficients used in ___.', ['The Binomial Theorem', 'A concept entirely unrelated to algebra', 'Only geometry problems, with no algebraic connection', 'A theorem unrelated to expanding expressions'], 0),
   ('The Binomial Theorem provides a method for ___.', ['Expanding expressions of the form (a + b) raised to a power', 'Solving quadratic equations exclusively', 'A process unrelated to algebraic expansion', 'Finding the roots of a polynomial only'], 0),
   ('Why might Pascal’s Triangle be useful for quickly finding binomial coefficients instead of manually expanding an expression?', ['It provides a direct, structured pattern for the coefficients without needing full expansion', 'Pascal’s Triangle provides no useful shortcut for this type of problem', 'Binomial coefficients can never be found using Pascal’s Triangle', 'This tool has no connection to expanding binomial expressions'], 0),
   ('Why are the concepts behind Pascal’s Triangle and the Binomial Theorem relevant to probability and counting problems?', ['The same combinatorial patterns used here also describe the number of ways to choose items from a set', 'These concepts have no connection to probability or counting', 'Pascal’s Triangle only applies to algebra, with no other mathematical use', 'This topic is entirely unrelated to combinatorics'], 0)]),
B('Genetics: Polygenic Inheritance and Continuous Traits',
  'Grade 11 Biology strand: polygenic inheritance occurs when multiple genes influence a single trait, often resulting in a continuous range of phenotypes, such as height, rather than distinct categories.',
  [('Polygenic inheritance occurs when ___.', ['Multiple genes influence a single trait', 'Only a single gene influences a trait, with no other genes involved', 'No genes are involved in determining a trait', 'A concept unrelated to inheritance patterns'], 0),
   ('Traits controlled by polygenic inheritance often result in ___.', ['A continuous range of phenotypes', 'Only two distinct, separate categories', 'No variation at all among individuals', 'A pattern unrelated to genetic influence'], 0),
   ('Which is an example of a trait commonly associated with polygenic inheritance?', ['Height', 'A trait determined by a single gene with only two possible outcomes', 'A characteristic entirely unrelated to genetics', 'A trait with no connection to inherited genes'], 0),
   ('Why might environmental factors also influence traits controlled by polygenic inheritance?', ['Environmental conditions, alongside genetics, can affect how a continuous trait is ultimately expressed', 'Environmental factors have no effect on polygenic traits', 'Polygenic traits are influenced only by genetics, with no other factors involved', 'This concept has no connection to how traits develop'], 0),
   ('Why is polygenic inheritance more complex to study than traits controlled by a single gene?', ['Multiple genes interacting make it harder to predict exact outcomes for offspring', 'Polygenic inheritance is always simpler to study than single-gene traits', 'Multiple genes have no effect on the complexity of inheritance patterns', 'This concept has no connection to genetic complexity'], 0)]),
C('Nuclear Chemistry: Half-Life Calculations and Applications',
  'Grade 11 Chemistry strand: half-life is the time required for half of a radioactive sample to decay, and half-life calculations are used in applications ranging from medicine to archaeological dating.',
  [('Half-life refers to the time required for ___.', ['Half of a radioactive sample to decay', 'An entire radioactive sample to decay completely', 'No decay to occur within a sample', 'A concept unrelated to radioactive decay'], 0),
   ('Which is an example of a practical application of half-life calculations?', ['Determining the age of ancient artifacts through radiocarbon dating', 'A use entirely unrelated to radioactive decay', 'A process with no connection to scientific measurement', 'An application unrelated to chemistry or physics'], 0),
   ('If a radioactive sample has a half-life of 10 years, how much of the original sample remains after 20 years?', ['One quarter', 'One half', 'The entire original sample', 'None of the original sample'], 0),
   ('Why is half-life considered a constant, predictable property of a specific radioactive isotope?', ['Each isotope decays at a consistent, characteristic rate regardless of external conditions', 'Half-life values constantly change based on the surrounding temperature', 'Half-life has no connection to how a specific isotope behaves', 'This property is always identical across every radioactive isotope'], 0),
   ('Why is understanding half-life important in medical treatments involving radioactive isotopes?', ['It helps determine safe and effective dosages and timing for treatment', 'Half-life has no relevance to medical treatments', 'Medical treatments never involve any use of radioactive isotopes', 'This concept only applies to purely theoretical chemistry'], 0)])]),

day(43, [
E('Media Literacy: Podcasts and Long-Form Audio Storytelling',
  'Grade 11 English strand: podcasts use audio-only storytelling techniques, such as pacing, sound design, and narrative voice, to engage listeners over an extended format without visual elements.',
  [('Podcasts rely on ___ to engage listeners, without the use of visual elements.', ['Audio-only storytelling techniques', 'Only visual imagery, with no audio component', 'A format identical to television broadcasting', 'A medium unrelated to storytelling'], 0),
   ('Which is an example of a technique used in audio storytelling?', ['Sound design to create atmosphere', 'Only spoken dialogue, with no other audio elements', 'A technique unrelated to sound or audio', 'Visual editing effects'], 0),
   ('Why might pacing be especially important in a long-form audio format like a podcast?', ['Without visual cues, careful pacing helps maintain listener engagement and clarity', 'Pacing has no effect on how a podcast is experienced', 'Audio storytelling never requires attention to pacing', 'This element only matters in visual media'], 0),
   ('Why might a podcast host’s narrative voice significantly shape a listener’s experience?', ['Voice can convey tone, emotion, and personality that shapes how content is received', 'Narrative voice has no effect on how a podcast is perceived', 'All podcast hosts sound identical, with no distinct voice', 'This element is irrelevant to audio storytelling'], 0),
   ('Why has long-form audio storytelling, like podcasting, grown as a popular media format?', ['It allows for in-depth exploration of topics in a flexible, accessible format', 'Podcasts have no unique advantages compared to other media formats', 'Long-form audio storytelling has no connection to audience engagement', 'This format has declined significantly in popularity in recent years'], 0)]),
F('Statistics: Normal Distribution and Z-Scores',
  'Grade 11 Functions strand (Data Management): a z-score indicates how many standard deviations a data value is from the mean, providing a standardized way to compare values within a normal distribution.',
  [('A z-score indicates how many ___ a data value is from the mean.', ['Standard deviations', 'Simple units, with no connection to standard deviation', 'Percentiles, with no connection to standard deviation', 'A measurement unrelated to the mean'], 0),
   ('A z-score of zero means a data value is ___.', ['Exactly equal to the mean', 'Far above the mean', 'Far below the mean', 'Impossible to determine from a normal distribution'], 0),
   ('Why is a z-score useful for comparing values from two different normal distributions?', ['It standardizes the values, allowing for a meaningful comparison despite different means and standard deviations', 'Z-scores have no use for comparing different data sets', 'Values from different distributions can never be meaningfully compared', 'This concept only applies to purely abstract mathematics'], 0),
   ('A positive z-score indicates that a data value is ___ the mean.', ['Above', 'Below', 'Exactly equal to', 'Completely unrelated to'], 0),
   ('Why might z-scores be useful in standardized testing, such as comparing a student’s performance to a larger population?', ['They provide a way to understand how a specific score compares to the overall distribution of scores', 'Z-scores have no application in standardized testing', 'Standardized testing never involves any statistical comparison', 'This concept has no connection to interpreting test results'], 0)]),
B('Human Health: Cardiovascular System and Disease Prevention',
  'Grade 11 Biology strand: the cardiovascular system circulates blood throughout the body, and understanding its function helps explain how lifestyle factors can influence the risk of cardiovascular disease.',
  [('The cardiovascular system’s primary role is to ___.', ['Circulate blood throughout the body', 'A role entirely unrelated to blood or circulation', 'Only produce new blood cells, with no circulatory function', 'Have no connection to bodily functions at all'], 0),
   ('Which is an example of a lifestyle factor that might influence cardiovascular disease risk?', ['Diet and physical activity level', 'A factor entirely unrelated to health or lifestyle', 'Only genetics, with no connection to lifestyle choices', 'A factor with no relevance to cardiovascular health'], 0),
   ('Why might regular physical activity help reduce the risk of cardiovascular disease?', ['It can strengthen the heart and improve overall circulatory efficiency', 'Physical activity has no connection to cardiovascular health', 'Exercise always increases the risk of cardiovascular disease', 'This factor has no relevance to disease prevention'], 0),
   ('The heart is best described as a key organ within the ___.', ['Cardiovascular system', 'Digestive system', 'A system entirely unrelated to circulation', 'Skeletal system'], 0),
   ('Why is understanding the cardiovascular system valuable for making informed health decisions?', ['It can help individuals recognize how their choices affect their long-term heart health', 'This understanding has no connection to personal health decisions', 'The cardiovascular system has no relevance to overall health', 'This knowledge provides no useful, practical benefit'], 0)]),
C('Chemical Equilibrium: Calculating Equilibrium Constants',
  'Grade 11 Chemistry strand: the equilibrium constant expresses the ratio of product to reactant concentrations at equilibrium, providing insight into how far a reaction proceeds toward products.',
  [('The equilibrium constant expresses the ratio of ___.', ['Product to reactant concentrations at equilibrium', 'Only reactant mass, with no connection to products', 'The colour of products compared to reactants', 'A value unrelated to concentration'], 0),
   ('A large equilibrium constant value generally suggests that a reaction ___.', ['Favours the formation of products', 'Favours the reactants remaining unchanged', 'Has no products formed at all', 'Cannot be analyzed using this method'], 0),
   ('Why does the equilibrium constant remain the same for a given reaction at a constant temperature, regardless of the starting concentrations?', ['It reflects an inherent property of the reaction’s balance between products and reactants at that temperature', 'The equilibrium constant always changes depending on the starting concentrations used', 'This value has no connection to temperature or reaction conditions', 'Equilibrium constants are entirely random values with no scientific basis'], 0),
   ('Why is understanding equilibrium constants useful in industrial chemical processes?', ['It helps predict and optimize the yield of a desired product', 'Equilibrium constants have no practical application in industry', 'Industrial processes never require an understanding of chemical equilibrium', 'This concept only applies to purely theoretical chemistry problems'], 0),
   ('If the equilibrium constant for a reaction is very small, this suggests the reaction ___.', ['Favours the reactants, with relatively little product formed', 'Favours the products completely, with no reactants remaining', 'Cannot reach equilibrium under any conditions', 'Has no relationship to the concentration of products or reactants'], 0)])]),

day(44, [
E('Reading: Magical Realism and Cultural Identity',
  'Grade 11 English strand: magical realism blends realistic settings with fantastical elements, often used by authors to explore questions of cultural identity, history, and belonging.',
  [('Magical realism blends realistic settings with ___.', ['Fantastical elements', 'Only purely factual, non-fictional content', 'Two completely unrelated fictional genres with no connection', 'Only historical events with no fictional elements'], 0),
   ('Authors often use magical realism to explore questions of ___.', ['Cultural identity, history, and belonging', 'A topic entirely unrelated to identity or culture', 'Only lighthearted, comedic subject matter', 'Themes with no connection to any real experience'], 0),
   ('Which is a characteristic feature of magical realism?', ['Magical events treated as a normal part of an otherwise realistic world', 'A story set entirely in a fantasy world with no realistic elements', 'A completely factual account with no fictional elements', 'The total absence of any magical or fantastical elements'], 0),
   ('Why might magical realism be an effective genre for exploring the complexities of cultural identity?', ['It can capture layered, sometimes contradictory experiences that realism alone might not fully express', 'This genre has no connection to exploring identity or culture', 'Magical realism removes all meaningful connection to real experiences', 'Cultural identity can never be meaningfully explored through fiction'], 0),
   ('Why do readers often find magical realism a distinctive and memorable literary experience?', ['It challenges typical boundaries between the real and the fantastical', 'This genre is identical to standard realistic fiction', 'Magical realism never differs from other literary genres', 'Readers experience no unique response to this genre'], 0)]),
F('Functions: Rate of Change -- Average vs Instantaneous',
  'Grade 11 Functions strand: average rate of change describes how a function changes over an interval, while instantaneous rate of change describes how a function is changing at a single specific point.',
  [('Average rate of change describes how a function changes ___.', ['Over an interval', 'At a single specific point only', 'With no connection to any interval', 'In a way unrelated to the function’s values'], 0),
   ('Instantaneous rate of change describes how a function is changing ___.', ['At a single specific point', 'Over an interval with no connection to a specific point', 'A concept unrelated to a function’s behaviour', 'Only across the function’s entire domain at once'], 0),
   ('Average rate of change over an interval can be calculated using a method similar to finding ___.', ['The slope between two points', 'The y-intercept of the function only', 'A method unrelated to the function’s graph', 'The domain of the function exclusively'], 0),
   ('Why might instantaneous rate of change be more difficult to calculate directly than average rate of change?', ['It requires examining the function’s behaviour at a single point rather than across a measurable interval', 'Instantaneous rate of change is always simpler to calculate than average rate of change', 'These two concepts require an identical method of calculation', 'This concept has no connection to how functions behave'], 0),
   ('Why is understanding rate of change useful for interpreting real-world data, such as speed over time?', ['It helps quantify how one variable is changing in relation to another', 'Rate of change has no real-world application', 'Speed and rate of change have no mathematical connection', 'This concept only applies to purely abstract mathematics'], 0)]),
B('Microbiology: Fungi and Decomposition',
  'Grade 11 Biology strand: fungi play a critical ecological role as decomposers, breaking down dead organic matter and recycling nutrients back into the ecosystem.',
  [('Fungi play a critical ecological role as ___.', ['Decomposers', 'Producers exclusively, with no connection to decomposition', 'Organisms unrelated to nutrient recycling', 'A category with no ecological function'], 0),
   ('Decomposers like fungi help break down ___.', ['Dead organic matter', 'Only living organisms, with no connection to decomposition', 'A material entirely unrelated to biological matter', 'Rocks and other inorganic minerals only'], 0),
   ('Why is the decomposition process carried out by fungi important for an ecosystem?', ['It recycles nutrients back into the ecosystem, making them available for other organisms', 'Decomposition has no connection to nutrient availability', 'Fungi provide no meaningful ecological benefit', 'This process has no relevance to ecosystem health'], 0),
   ('Which is an example of an organism classified as a fungus?', ['A mushroom', 'A type of bacteria with no connection to fungi', 'A plant with no connection to decomposition', 'An animal unrelated to this classification'], 0),
   ('Why might an ecosystem struggle to function properly without decomposers like fungi?', ['Nutrients would remain locked in dead organic matter rather than being recycled for use by other organisms', 'Decomposers have no meaningful role in any ecosystem', 'Ecosystems function identically with or without decomposers', 'This concept has no connection to nutrient cycling'], 0)]),
C('Organic Chemistry: Esters, Amides, and Biological Relevance',
  'Grade 11 Chemistry strand: esters and amides are organic functional groups found in many natural and biological molecules, including fats, fragrances, and proteins.',
  [('Esters and amides are examples of organic ___.', ['Functional groups', 'Elements found only on the periodic table', 'A concept unrelated to organic chemistry', 'Purely inorganic compounds'], 0),
   ('Which biological molecules commonly contain ester or amide functional groups?', ['Fats and proteins', 'Only pure metals, with no connection to biology', 'A category entirely unrelated to biological molecules', 'Only minerals, with no organic connection'], 0),
   ('Esters are often associated with which characteristic in nature?', ['Distinctive fragrances and flavours', 'A complete absence of any noticeable scent', 'A property entirely unrelated to smell or taste', 'Only colour, with no connection to scent'], 0),
   ('Why might understanding functional groups like esters and amides be useful for studying biological molecules?', ['These functional groups help determine the structure and function of important biological compounds', 'Functional groups have no connection to how biological molecules behave', 'This concept has no relevance to studying biology or biochemistry', 'Esters and amides are never found in naturally occurring molecules'], 0),
   ('Why are amide bonds particularly significant in biology?', ['They form the basis of the peptide bonds that link amino acids together to form proteins', 'Amide bonds have no connection to protein structure', 'Proteins are never formed using any type of chemical bond', 'This concept has no relevance to biological chemistry'], 0)])]),

day(45, [
E('Grammar: The Rhetorical Triangle -- Ethos, Pathos, Logos',
  'Grade 11 English strand: the rhetorical triangle describes three key persuasive appeals — ethos (credibility), pathos (emotion), and logos (logic) — that writers and speakers use to build a convincing argument.',
  [('The rhetorical triangle describes three key persuasive appeals: ethos, pathos, and ___.', ['Logos', 'Only a single additional appeal, with no third element', 'A concept unrelated to persuasion', 'An appeal with no connection to rhetoric'], 0),
   ('Ethos, as a persuasive appeal, is based on ___.', ['Credibility', 'Only emotional appeal, with no connection to credibility', 'Pure logic, with no connection to trust', 'A concept unrelated to rhetoric'], 0),
   ('Pathos, as a persuasive appeal, is based on ___.', ['Emotion', 'Only logical reasoning, with no emotional component', 'Credibility exclusively, with no emotional appeal', 'A concept unrelated to persuasion'], 0),
   ('Logos, as a persuasive appeal, is based on ___.', ['Logic and reasoning', 'Only emotional appeal, with no logical component', 'Credibility exclusively, with no logical reasoning', 'A concept unrelated to argumentation'], 0),
   ('Why might an effective persuasive argument use a combination of ethos, pathos, and logos?', ['Combining these appeals can address different aspects of how an audience is convinced', 'Using more than one appeal always weakens a persuasive argument', 'Only one of these appeals should ever be used in an argument', 'These three appeals have no connection to persuasive effectiveness'], 0)]),
F('Number Theory: Complex Numbers -- Further Operations',
  'Grade 11 Functions strand (extension): building on earlier operations, complex numbers can also be divided using the conjugate of the denominator, and can be represented graphically on the complex plane.',
  [('Dividing complex numbers typically involves multiplying by the ___ of the denominator.', ['Conjugate', 'Reciprocal, with no connection to the conjugate', 'Square root, with no connection to division', 'A concept unrelated to complex numbers'], 0),
   ('The complex plane is used to graphically represent complex numbers using ___.', ['A real axis and an imaginary axis', 'Only a single axis, with no distinction between real and imaginary parts', 'A method unrelated to graphing', 'Two identical axes representing the exact same value'], 0),
   ('The conjugate of a complex number changes the sign of its ___.', ['Imaginary part', 'Real part only, with no change to the imaginary part', 'Both the real and imaginary parts equally', 'A part unrelated to the complex number’s structure'], 0),
   ('Why is multiplying by the conjugate a useful strategy when dividing complex numbers?', ['It eliminates the imaginary part from the denominator, simplifying the expression', 'This strategy has no effect on simplifying a complex number expression', 'Complex numbers can never be divided using any method', 'Multiplying by the conjugate always makes an expression more complicated'], 0),
   ('Why might representing complex numbers on the complex plane be useful for visualizing operations like addition?', ['It allows complex number operations to be interpreted geometrically, similar to vectors', 'The complex plane has no useful application for visualizing complex numbers', 'Complex numbers can never be represented graphically', 'This concept only applies to purely abstract mathematics with no visual representation'], 0)]),
B('Evolution: Genetic Drift and the Founder Effect',
  'Grade 11 Biology strand: genetic drift describes random changes in allele frequencies within a population, and the founder effect occurs when a new population is established by a small number of individuals with limited genetic variation.',
  [('Genetic drift describes ___.', ['Random changes in allele frequencies within a population', 'A predictable, non-random pattern of genetic change', 'A concept unrelated to genetics or populations', 'The complete absence of any genetic variation'], 0),
   ('The founder effect occurs when a new population is established by ___.', ['A small number of individuals with limited genetic variation', 'A very large, genetically diverse group of individuals', 'A process entirely unrelated to population genetics', 'Individuals with absolutely no genetic differences from the original population'], 0),
   ('Why might genetic drift have a more significant impact on small populations than on large ones?', ['Random changes in allele frequency tend to have a proportionally greater effect in smaller populations', 'Genetic drift affects large and small populations in an identical way', 'Population size has no connection to the impact of genetic drift', 'This concept has no relevance to understanding population genetics'], 0),
   ('Why might a population resulting from the founder effect have reduced genetic diversity compared to the original population?', ['Only a limited sample of the original population’s genetic variation is carried forward', 'The founder effect always increases genetic diversity in a new population', 'Genetic diversity has no connection to how a new population is established', 'This concept has no relevance to evolutionary biology'], 0),
   ('Why are genetic drift and the founder effect important concepts for understanding evolutionary change?', ['They illustrate how chance events, not just natural selection, can shape a population’s genetic makeup over time', 'These concepts have no connection to evolutionary change', 'Evolution occurs exclusively through natural selection, with no other contributing factors', 'This topic has no relevance to studying biology'], 0)]),
C('Analytical Chemistry: Spectroscopy and Identification',
  'Grade 11 Chemistry strand: spectroscopy studies how matter interacts with light or other electromagnetic radiation, providing a valuable tool for identifying unknown substances based on their unique absorption patterns.',
  [('Spectroscopy studies how matter interacts with ___.', ['Light or other electromagnetic radiation', 'Only sound waves, with no connection to light', 'A factor entirely unrelated to matter', 'Only gravity, with no connection to radiation'], 0),
   ('Spectroscopy is a valuable tool for identifying unknown substances based on their ___.', ['Unique absorption patterns', 'Colour alone, with no connection to absorption patterns', 'Physical mass only, with no other characteristics considered', 'A property entirely unrelated to light interaction'], 0),
   ('Why might each substance have a unique spectroscopic pattern?', ['Different molecular and atomic structures interact with light in distinct, characteristic ways', 'All substances produce an identical spectroscopic pattern regardless of structure', 'Spectroscopic patterns have no connection to molecular structure', 'This concept has no scientific basis'], 0),
   ('Why is spectroscopy useful in fields like forensic science?', ['It can help identify unknown substances found at a scene based on their light-interaction properties', 'Spectroscopy has no practical application in forensic science', 'Identifying unknown substances never requires this type of analysis', 'This technique only applies to purely theoretical chemistry'], 0),
   ('Why might astronomers use spectroscopy to study distant stars?', ['Light from stars can reveal information about their chemical composition based on their spectral patterns', 'Spectroscopy has no application in astronomy', 'Distant stars cannot be studied using techniques involving light analysis', 'This concept has no connection to identifying chemical composition'], 0)])]),

day(46, [
E('Independent Reading: War Literature and Testimony',
  'Grade 11 English strand: war literature and personal testimony offer firsthand or fictionalized accounts of conflict, often used to preserve historical memory and explore the human impact of war.',
  [('War literature and personal testimony often offer accounts of ___.', ['Conflict', 'A topic entirely unrelated to historical events', 'Only fictional, invented scenarios with no historical basis', 'Events with no connection to human experience'], 0),
   ('Why might this type of literature be used to preserve historical memory?', ['Firsthand or fictionalized accounts can document experiences that might otherwise be forgotten', 'This literature has no connection to preserving history', 'War literature never engages with historical events', 'Preserving historical memory has no relevance to this genre'], 0),
   ('Why might reading war literature help readers understand the human impact of conflict?', ['Personal narratives can convey emotional and lived experiences that statistics alone cannot capture', 'War literature provides no insight into the human impact of conflict', 'This genre has no connection to understanding historical events', 'Readers gain no meaningful understanding from this type of literature'], 0),
   ('Which is an example of a form that war literature or testimony might take?', ['A memoir written by someone who experienced a conflict firsthand', 'A form entirely unrelated to personal experience', 'A genre that never includes any firsthand accounts', 'A type of writing unrelated to historical events'], 0),
   ('Why might studying war literature alongside historical accounts provide a fuller understanding of a conflict?', ['Literature can offer emotional and personal perspectives that complement factual historical records', 'Literature and historical accounts have no meaningful connection to each other', 'Studying literature alongside history provides no additional insight', 'This combination of sources has no educational value'], 0)]),
F('Geometry: Vectors -- Introduction to Magnitude and Direction',
  'Grade 11 Functions and Geometry strand: a vector is a quantity that has both magnitude (size) and direction, distinguishing it from a scalar, which has only magnitude.',
  [('A vector is a quantity that has both magnitude and ___.', ['Direction', 'Colour', 'A property unrelated to measurement', 'Temperature'], 0),
   ('A scalar, unlike a vector, has only ___.', ['Magnitude', 'Direction, with no connection to magnitude', 'Neither magnitude nor direction', 'A property unrelated to measurement'], 0),
   ('Which is an example of a quantity that would typically be represented as a vector rather than a scalar?', ['Force', 'Temperature', 'Mass', 'A quantity unrelated to direction'], 0),
   ('Why is direction an essential component when describing a vector quantity, unlike a scalar quantity?', ['It provides crucial information about which way a quantity is acting, not just how much', 'Direction has no relevance to how a vector is used or interpreted', 'Vectors never involve any directional component', 'A scalar and a vector are always identical to one another'], 0),
   ('Why might vectors be useful for representing the motion of an object, such as an airplane accounting for wind?', ['Multiple vector quantities, like speed and wind direction, can be combined to determine overall motion', 'Vectors have no practical use for representing motion', 'Motion can never involve more than one directional influence', 'This concept only applies to purely abstract mathematics with no real-world use'], 0)]),
B('Animal Behaviour: Communication and Social Structures',
  'Grade 11 Biology strand: many animal species use various forms of communication, such as vocalizations, visual displays, and chemical signals, to coordinate behaviour within complex social structures.',
  [('Animals may use various forms of communication, including ___.', ['Vocalizations, visual displays, and chemical signals', 'Only written language, with no other form of communication', 'A method entirely unrelated to communication', 'No forms of communication whatsoever'], 0),
   ('Animal communication can help coordinate behaviour within ___.', ['Complex social structures', 'A concept entirely unrelated to animal behaviour', 'Structures with no connection to social organization', 'A framework unrelated to animal interactions'], 0),
   ('Which is an example of a chemical signal used in animal communication?', ['A pheromone', 'A form of communication entirely unrelated to chemistry', 'A signal with no biological function', 'A visual display with no chemical component'], 0),
   ('Why might complex social structures benefit a species, such as through cooperative behaviours?', ['Coordinated group behaviour can improve outcomes like finding food or avoiding predators', 'Social structures provide no benefit to a species’ survival', 'Communication has no connection to social organization in animals', 'This concept has no relevance to understanding animal behaviour'], 0),
   ('Why is studying animal communication valuable for understanding broader evolutionary and ecological patterns?', ['It can reveal how species adapt and interact within their environments and social groups', 'Animal communication has no connection to evolutionary or ecological study', 'This topic has no relevance to biology as a field of study', 'Communication patterns in animals provide no useful scientific insight'], 0)]),
C('Solutions: Solubility Rules and Precipitation Reactions',
  'Grade 11 Chemistry strand: solubility rules help predict whether a compound will dissolve in water, and a precipitation reaction occurs when two soluble solutions combine to form an insoluble solid product.',
  [('Solubility rules help predict whether a compound will ___.', ['Dissolve in water', 'Always remain a solid regardless of conditions', 'A concept unrelated to dissolving', 'Change colour when combined with another substance'], 0),
   ('A precipitation reaction occurs when two soluble solutions combine to form ___.', ['An insoluble solid product', 'Only a gas, with no solid product formed', 'No reaction of any kind', 'A liquid product that remains fully dissolved'], 0),
   ('Why are solubility rules useful for predicting the outcome of mixing two solutions?', ['They help determine whether a solid precipitate will form based on the ions present', 'Solubility rules provide no useful information about chemical reactions', 'The outcome of mixing solutions can never be predicted', 'This concept has no connection to chemical reactions'], 0),
   ('Which is an example of a visible sign that a precipitation reaction has occurred?', ['The formation of a cloudy or solid substance in the solution', 'No visible change of any kind', 'A change in temperature only, with no other visible effect', 'A change unrelated to the appearance of the solution'], 0),
   ('Why might precipitation reactions be useful in a laboratory setting, such as for identifying unknown ions in a solution?', ['Specific precipitates can indicate the presence of particular ions based on known solubility patterns', 'Precipitation reactions provide no useful information for identifying substances', 'This type of reaction has no practical laboratory application', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(47, [
E('Writing: The Literary Analysis of Setting',
  'Grade 11 English strand: analyzing setting involves examining how the time and place of a story influence its mood, characters, and themes, rather than treating setting as simply a backdrop.',
  [('Analyzing setting involves examining how the time and place of a story influence its ___.', ['Mood, characters, and themes', 'Only its exact page length', 'A factor entirely unrelated to a story’s meaning', 'The font used in the printed text'], 0),
   ('Why might treating setting as more than just a backdrop deepen a reader’s analysis of a text?', ['Setting can actively shape a story’s meaning rather than simply existing in the background', 'Setting always has no connection to a story’s deeper meaning', 'A story’s setting never influences how it is interpreted', 'This type of analysis provides no additional insight into a text'], 0),
   ('Which is an example of how setting might influence a story’s mood?', ['A dark, isolated location contributing to a sense of tension or unease', 'A setting description with no connection to a story’s tone', 'A location entirely unrelated to how a story feels', 'Setting choices that never affect a reader’s emotional response'], 0),
   ('Why might a character’s actions or values be shaped by the specific setting of a story?', ['A time and place can present specific social norms, pressures, or opportunities that influence a character', 'Setting never has any influence on a character’s choices', 'Characters are always completely unaffected by their surroundings', 'This concept has no connection to literary analysis'], 0),
   ('Why is analyzing setting a valuable skill in literary analysis?', ['It reveals another layer of meaning that contributes to a story’s overall themes and impact', 'Setting has no connection to a story’s themes', 'This type of analysis is never a meaningful part of studying literature', 'Setting should always be considered irrelevant to a text’s significance'], 0)]),
F('Functions: Transformations Across Function Families',
  'Grade 11 Functions strand: transformations, such as shifts, stretches, and reflections, apply consistently across different types of functions, including polynomial, exponential, and trigonometric functions.',
  [('Transformations such as shifts, stretches, and reflections apply ___.', ['Consistently across different types of functions', 'Only to a single, specific type of function', 'A concept unrelated to how functions behave', 'In a way that is completely unpredictable and inconsistent'], 0),
   ('A vertical shift moves a function’s graph ___.', ['Up or down', 'Only left or right', 'In no particular direction', 'Only diagonally, with no vertical movement'], 0),
   ('A horizontal reflection of a function’s graph would ___.', ['Flip the graph across the y-axis', 'Have no effect on the graph at all', 'Only move the graph vertically', 'Change the type of function entirely'], 0),
   ('Why is it useful to recognize that transformation rules apply similarly across different function families?', ['It allows previously learned transformation skills to be applied to new, more complex types of functions', 'Transformation rules are always completely different for each individual type of function', 'This concept has no connection to understanding function behaviour', 'Transformations can never be meaningfully compared across different functions'], 0),
   ('Why might understanding transformations be useful for quickly sketching the graph of a new function based on a known one?', ['It allows you to predict how the graph will change without recalculating every point', 'Transformations provide no useful shortcut for graphing functions', 'Every new function must always be graphed completely from scratch', 'This concept has no practical application for graphing'], 0)]),
B('Biotechnology: Cloning and Stem Cell Research',
  'Grade 11 Biology strand: cloning creates a genetically identical copy of an organism or cell, and stem cell research explores the potential of unspecialized cells to develop into various specialized cell types.',
  [('Cloning creates a genetically identical copy of ___.', ['An organism or cell', 'A concept entirely unrelated to genetics', 'Only non-living materials, with no biological connection', 'A random, unrelated biological structure'], 0),
   ('Stem cells are considered unspecialized cells with the potential to ___.', ['Develop into various specialized cell types', 'Remain permanently unable to change into any other cell type', 'A potential entirely unrelated to cell development', 'Only replicate identical stem cells with no further specialization'], 0),
   ('Why does stem cell research hold significant potential for medical treatments?', ['Stem cells could potentially be used to repair or replace damaged tissues and organs', 'Stem cell research has no potential medical applications', 'This field of research has no connection to treating disease or injury', 'Stem cells have no ability to develop into other cell types'], 0),
   ('Why might cloning research raise ethical questions, particularly regarding more complex organisms?', ['It raises significant questions about identity, consent, and the appropriate use of the technology', 'Cloning research raises no ethical questions of any kind', 'This technology has no connection to complex ethical considerations', 'Ethical considerations are irrelevant to biotechnology research'], 0),
   ('Why is stem cell research considered a rapidly evolving area of biology?', ['New discoveries continue to expand understanding of stem cells’ potential applications', 'This field of research has remained completely unchanged over time', 'Stem cell research has no connection to ongoing scientific discovery', 'This topic has no relevance to modern biological research'], 0)]),
C('Electrochemistry: Galvanic vs Electrolytic Cells',
  'Grade 11 Chemistry strand: a galvanic cell generates electrical energy from a spontaneous chemical reaction, while an electrolytic cell uses electrical energy to drive a non-spontaneous chemical reaction.',
  [('A galvanic cell generates electrical energy from ___.', ['A spontaneous chemical reaction', 'A non-spontaneous chemical reaction requiring external energy', 'A process entirely unrelated to chemical reactions', 'No chemical reaction at all'], 0),
   ('An electrolytic cell uses electrical energy to drive ___.', ['A non-spontaneous chemical reaction', 'A spontaneous chemical reaction with no external energy required', 'A process entirely unrelated to electricity', 'No chemical reaction of any kind'], 0),
   ('Which is an example of a device that functions as a galvanic cell?', ['A battery', 'A device that requires an external power source to function at all', 'A tool entirely unrelated to chemical reactions', 'An object that generates no electrical energy'], 0),
   ('Why is electroplating considered an example of an electrolytic process?', ['It uses an external electrical current to drive a chemical reaction that would not occur on its own', 'Electroplating occurs spontaneously with no external energy required', 'This process has no connection to electrochemistry', 'Electrolytic cells have no practical, real-world applications'], 0),
   ('Why is understanding the difference between galvanic and electrolytic cells useful in fields like battery technology?', ['It helps engineers design systems that either generate or consume electrical energy as needed', 'This distinction has no practical relevance to battery technology', 'Galvanic and electrolytic cells function in an identical way', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(48, [
E('Oral Communication: The Elevator Pitch and Concise Persuasion',
  'Grade 11 English strand: an elevator pitch is a brief, focused presentation designed to quickly and persuasively communicate an idea, typically within the span of a short conversation.',
  [('An elevator pitch is designed to ___.', ['Quickly and persuasively communicate an idea', 'Provide an extremely detailed, lengthy explanation of a topic', 'Avoid making any clear or persuasive point', 'A concept unrelated to communication'], 0),
   ('Why is brevity an important characteristic of an effective elevator pitch?', ['It respects the limited time available and keeps the audience’s attention focused', 'Brevity has no connection to how effective a pitch is', 'An elevator pitch should always be as long and detailed as possible', 'This characteristic is irrelevant to persuasive communication'], 0),
   ('Which is an example of an effective strategy for opening an elevator pitch?', ['A concise, attention-grabbing statement about the core idea', 'A lengthy, unrelated introduction with no clear focus', 'An opening with no connection to the main idea being pitched', 'A pitch that begins with no clear point at all'], 0),
   ('Why might practising concise persuasion, like an elevator pitch, be a valuable communication skill?', ['It builds the ability to clearly communicate key ideas efficiently in a variety of real-world situations', 'This skill has no application outside of a specific business context', 'Concise persuasion is never a valuable or practical communication skill', 'This type of communication has no real-world relevance'], 0),
   ('Why should an elevator pitch clearly convey why an idea matters to the specific listener?', ['Relevance to the listener increases the likelihood that the pitch will be persuasive and memorable', 'Relevance to the listener has no effect on how persuasive a pitch is', 'An elevator pitch should never consider the specific listener’s interests', 'This factor has no connection to effective communication'], 0)]),
F('Probability: Expected Value and Decision Making',
  'Grade 11 Functions strand (Data Management): expected value is a calculation that combines the probability and outcome of each possible result in a situation, helping guide decisions involving uncertainty.',
  [('Expected value combines the probability and outcome of ___.', ['Each possible result in a situation', 'Only the single most likely outcome, with no other results considered', 'A concept unrelated to probability', 'A random, unrelated calculation with no connection to outcomes'], 0),
   ('Expected value can help guide decisions that involve ___.', ['Uncertainty', 'Situations with absolutely no risk or uncertainty involved', 'A concept entirely unrelated to probability or outcomes', 'Decisions where every outcome is already known with complete certainty'], 0),
   ('If a game has a 50 percent chance of winning $10 and a 50 percent chance of winning nothing, what is the expected value?', ['$5', '$10', '$0', '$20'], 0),
   ('Why might a business use expected value calculations when deciding whether to invest in a new project?', ['It provides a way to weigh potential outcomes and their likelihoods to inform a more rational decision', 'Expected value calculations provide no useful information for business decisions', 'Businesses never consider probability when making investment decisions', 'This concept only applies to purely theoretical, abstract mathematics'], 0),
   ('Why is expected value considered a useful tool despite not guaranteeing any single specific outcome?', ['It provides a mathematically informed estimate of the average result over many repeated trials', 'Expected value always guarantees the exact outcome of any single event', 'This concept has no practical use if a single outcome cannot be guaranteed', 'Expected value calculations have no connection to probability'], 0)]),
B('Physiology: The Respiratory System and Gas Exchange',
  'Grade 11 Biology strand: the respiratory system enables gas exchange, bringing oxygen into the body and removing carbon dioxide, a process essential for cellular respiration.',
  [('The respiratory system enables gas exchange by bringing in ___ and removing carbon dioxide.', ['Oxygen', 'Only nitrogen, with no connection to oxygen', 'A gas entirely unrelated to respiration', 'Water vapour exclusively, with no other gases involved'], 0),
   ('Gas exchange in the respiratory system is essential for supporting ___.', ['Cellular respiration', 'A process entirely unrelated to cellular function', 'Only digestion, with no connection to respiration', 'A function unrelated to obtaining energy'], 0),
   ('Which structure in the lungs is primarily responsible for gas exchange?', ['Alveoli', 'The trachea exclusively, with no other structures involved', 'A structure entirely unrelated to the respiratory system', 'The oesophagus'], 0),
   ('Why is a large surface area within the lungs important for efficient gas exchange?', ['It allows for a greater area over which oxygen and carbon dioxide can be exchanged', 'Surface area has no connection to the efficiency of gas exchange', 'Gas exchange never depends on the surface area of the lungs', 'This concept has no relevance to respiratory function'], 0),
   ('Why might understanding the respiratory system be relevant to studying diseases like asthma?', ['It helps explain how conditions affecting the airways or lungs can impair effective gas exchange', 'The respiratory system has no connection to respiratory diseases', 'Diseases like asthma have no relevance to studying human physiology', 'This knowledge provides no useful understanding of respiratory conditions'], 0)]),
C('Chemistry: Reaction Mechanisms and Rate-Determining Steps',
  'Grade 11 Chemistry strand: many chemical reactions occur through a series of smaller steps called a reaction mechanism, with the slowest step, known as the rate-determining step, controlling the overall reaction rate.',
  [('A reaction mechanism describes a chemical reaction as occurring through ___.', ['A series of smaller steps', 'A single, instantaneous step with no intermediate stages', 'A process entirely unrelated to chemical reactions', 'No defined steps of any kind'], 0),
   ('The rate-determining step of a reaction is best described as ___.', ['The slowest step in the reaction mechanism', 'The fastest step in the reaction mechanism', 'A step unrelated to the overall reaction rate', 'The very first step, regardless of its speed'], 0),
   ('Why does the rate-determining step control the overall speed of a multi-step reaction?', ['The overall reaction cannot proceed faster than its slowest individual step allows', 'The rate-determining step has no effect on the overall reaction speed', 'The fastest step always determines the overall reaction rate instead', 'This concept has no connection to how reaction rates are determined'], 0),
   ('Why might understanding a reaction’s mechanism be useful for chemists trying to increase a reaction’s speed?', ['Identifying the rate-determining step helps target where a catalyst or condition change would be most effective', 'Reaction mechanisms provide no useful information for increasing reaction speed', 'A reaction’s mechanism has no connection to its overall rate', 'This concept only applies to purely theoretical chemistry with no practical use'], 0),
   ('Why are reaction mechanisms considered more detailed than a simple balanced chemical equation?', ['They reveal the actual step-by-step process by which reactants are converted into products', 'A balanced equation always provides more detail than a reaction mechanism', 'Reaction mechanisms and balanced equations always contain identical information', 'This concept has no connection to understanding how a reaction proceeds'], 0)])]),

day(49, [
E('Literature: Unreliable Narrators',
  'Grade 11 English strand: an unreliable narrator is a storyteller whose credibility is compromised, requiring readers to critically evaluate the accuracy of the account being presented.',
  [('An unreliable narrator is a storyteller whose ___ is compromised.', ['Credibility', 'Physical appearance', 'Age, with no connection to the accuracy of their account', 'Name, with no connection to trustworthiness'], 0),
   ('Why might readers need to critically evaluate the account presented by an unreliable narrator?', ['The narrator’s version of events may be biased, incomplete, or intentionally misleading', 'Unreliable narrators always present a completely accurate account of events', 'Readers never need to question a narrator’s reliability', 'This type of narration has no effect on how a story should be read'], 0),
   ('Which is an example of a reason a narrator might be considered unreliable?', ['The narrator has a personal bias that distorts their perspective', 'The narrator always presents events with complete objectivity and no bias', 'A reason entirely unrelated to how a story is told', 'The narrator has no connection to the events of the story at all'], 0),
   ('Why might an author choose to use an unreliable narrator instead of a more straightforward narrative voice?', ['It can create suspense, complexity, or deeper thematic exploration by challenging readers’ assumptions', 'This technique always makes a story less engaging or effective', 'Unreliable narrators have no impact on a reader’s experience of a story', 'This narrative choice serves no meaningful literary purpose'], 0),
   ('Why is recognizing an unreliable narrator an important literary analysis skill?', ['It helps readers form a more accurate and critical understanding of the story’s true events and meaning', 'Recognizing this technique has no effect on how a story is interpreted', 'Unreliable narration never influences how a story should be understood', 'This skill has no connection to literary analysis'], 0)]),
F('Review: Radicals, Statistics, and Vectors',
  'Grade 11 Functions strand review: this lesson revisits radical functions, Pascal’s Triangle and the Binomial Theorem, normal distribution and z-scores, average versus instantaneous rate of change, and vectors.',
  [('A radical function contains a variable inside a ___.', ['Root, such as a square root', 'A denominator only, with no connection to roots', 'An exponent only, with no root involved', 'A function unrelated to roots'], 0),
   ('A z-score indicates how many ___ a data value is from the mean.', ['Standard deviations', 'Simple units, with no connection to standard deviation', 'Percentiles, with no connection to standard deviation', 'A measurement unrelated to the mean'], 0),
   ('A vector is a quantity that has both magnitude and ___.', ['Direction', 'Colour', 'A property unrelated to measurement', 'Temperature'], 0),
   ('Average rate of change describes how a function changes ___.', ['Over an interval', 'At a single specific point only', 'With no connection to any interval', 'In a way unrelated to the function’s values'], 0),
   ('Why is it useful to review radicals, statistics, and vectors together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
B('Conservation: Invasive Species and Ecosystem Disruption',
  'Grade 11 Biology strand: an invasive species is a non-native organism that spreads rapidly in a new environment, often disrupting local ecosystems by outcompeting native species for resources.',
  [('An invasive species is best described as ___.', ['A non-native organism that spreads rapidly in a new environment', 'A native organism that has always existed in a particular ecosystem', 'A concept entirely unrelated to ecology', 'A species with no ability to affect its environment'], 0),
   ('Invasive species often disrupt local ecosystems by ___.', ['Outcompeting native species for resources', 'Having no effect on the native species in an ecosystem', 'Only benefiting native species with no negative impact', 'A process entirely unrelated to ecological competition'], 0),
   ('Why might an invasive species spread rapidly in a new environment?', ['It may lack natural predators or competitors that would otherwise limit its population', 'Invasive species always spread more slowly than native species', 'This concept has no connection to how species interact with their environment', 'Invasive species never have any competitive advantage in a new habitat'], 0),
   ('Why is the introduction of invasive species considered a significant conservation concern?', ['It can lead to declines in native species populations and disrupt ecosystem balance', 'Invasive species have no impact on conservation efforts', 'This concept has no relevance to studying ecosystems', 'The introduction of new species always benefits an ecosystem with no drawbacks'], 0),
   ('Which is an example of a way invasive species might be introduced to a new environment?', ['Accidental transport through global trade and travel', 'A method entirely unrelated to human activity', 'A process that never involves any human influence', 'A cause with no connection to species movement'], 0)]),
C('Industrial Chemistry: Minimizing Waste and Environmental Impact',
  'Grade 11 Chemistry strand: industrial chemistry involves designing processes that minimize waste, energy use, and environmental impact while still efficiently producing needed chemical products.',
  [('Industrial chemistry involves designing processes that minimize ___.', ['Waste, energy use, and environmental impact', 'The efficiency of a chemical process', 'A factor entirely unrelated to chemical production', 'The overall usefulness of the final chemical product'], 0),
   ('Why might a company choose to redesign a chemical process to reduce waste?', ['It can lower costs and reduce negative effects on the environment', 'Reducing waste always increases both costs and environmental harm', 'Waste reduction has no benefit for a company or the environment', 'This concept has no connection to industrial chemistry'], 0),
   ('Which is an example of a strategy used to reduce environmental impact in industrial chemical processes?', ['Recycling byproducts back into the production process', 'A strategy entirely unrelated to reducing waste', 'Increasing the amount of waste produced with no consideration for the environment', 'A method that has no connection to industrial chemistry'], 0),
   ('Why is balancing efficiency and environmental impact an important consideration in industrial chemistry?', ['Processes need to remain practical and cost-effective while also minimizing harm to the environment', 'Efficiency and environmental impact have no connection to each other', 'Industrial processes never need to consider environmental impact', 'This balance has no relevance to real-world chemical production'], 0),
   ('Why might industries increasingly prioritize minimizing environmental impact in their chemical processes today?', ['Growing awareness of environmental and regulatory concerns is influencing how industries operate', 'Industries have no incentive to consider environmental impact in their processes', 'This concept has no connection to modern industrial practices', 'Environmental impact has always been ignored in industrial chemistry'], 0)])]),

day(50, [
E('Writing: Crafting a Personal Philosophy Statement',
  'Grade 11 English strand: a personal philosophy statement articulates a writer’s core beliefs and guiding principles, often reflecting on experiences that have shaped their outlook on life.',
  [('A personal philosophy statement articulates a writer’s ___.', ['Core beliefs and guiding principles', 'A completely unrelated topic', 'Someone else’s beliefs and values', 'A summary of unrelated facts'], 0),
   ('Why might a writer reflect on past experiences when crafting a personal philosophy statement?', ['Experiences often shape and reveal the beliefs and principles a person holds', 'Past experiences have no connection to a person’s beliefs', 'A personal philosophy statement should never include any reflection', 'This type of writing has no connection to a writer’s own life'], 0),
   ('Which is an example of a statement that might appear in a personal philosophy statement?', ['I believe that resilience is built through facing and overcoming challenges.', 'The weather today is mild.', 'This is a random, unrelated fact.', 'A philosophy statement contains no personal beliefs.'], 0),
   ('Why might writing a personal philosophy statement be a valuable exercise for a student preparing for future goals?', ['It encourages clarity about one’s values, which can guide future decisions', 'This type of writing has no connection to future planning or goals', 'A personal philosophy statement serves no meaningful purpose', 'Reflecting on personal values has no practical benefit'], 0),
   ('Why is authenticity important when writing a personal philosophy statement?', ['A genuine reflection of one’s actual beliefs makes the statement more meaningful and credible', 'Authenticity has no value in this type of writing', 'A personal philosophy statement should always reflect beliefs that are not genuinely held', 'This quality has no connection to how the statement is received'], 0)]),
F('Review: Complex Numbers, Probability, and Reaction Mechanisms',
  'Grade 11 Functions strand review: this lesson revisits further complex number operations, Pascal’s Triangle, expected value, and connects mathematical reasoning to scientific applications like reaction mechanisms.',
  [('Dividing complex numbers typically involves multiplying by the ___ of the denominator.', ['Conjugate', 'Reciprocal, with no connection to the conjugate', 'Square root, with no connection to division', 'A concept unrelated to complex numbers'], 0),
   ('Pascal’s Triangle provides the coefficients used in ___.', ['The Binomial Theorem', 'A concept entirely unrelated to algebra', 'Only geometry problems, with no algebraic connection', 'A theorem unrelated to expanding expressions'], 0),
   ('Expected value combines the probability and outcome of ___.', ['Each possible result in a situation', 'Only the single most likely outcome, with no other results considered', 'A concept unrelated to probability', 'A random, unrelated calculation with no connection to outcomes'], 0),
   ('Why is it useful to review complex numbers, probability, and their connections to other subjects together?', ['It reinforces how these mathematical concepts connect to broader problem-solving and scientific applications', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0),
   ('Why might mathematical reasoning skills, like those used with probability, be useful outside of a mathematics classroom?', ['These skills can support informed decision-making in real-world situations involving uncertainty', 'Mathematical reasoning has no application outside of a classroom setting', 'Probability and reasoning skills are only ever useful in purely theoretical contexts', 'This concept has no connection to real-world problem-solving'], 0)]),
B('Review: Genetics, Behaviour, and Human Physiology',
  'Grade 11 Biology strand review: this lesson revisits polygenic inheritance, genetic drift and the founder effect, animal communication, cloning and stem cell research, the respiratory system, and invasive species.',
  [('Polygenic inheritance occurs when ___.', ['Multiple genes influence a single trait', 'Only a single gene influences a trait, with no other genes involved', 'No genes are involved in determining a trait', 'A concept unrelated to inheritance patterns'], 0),
   ('The founder effect occurs when a new population is established by ___.', ['A small number of individuals with limited genetic variation', 'A very large, genetically diverse group of individuals', 'A process entirely unrelated to population genetics', 'Individuals with absolutely no genetic differences from the original population'], 0),
   ('Stem cells are considered unspecialized cells with the potential to ___.', ['Develop into various specialized cell types', 'Remain permanently unable to change into any other cell type', 'A potential entirely unrelated to cell development', 'Only replicate identical stem cells with no further specialization'], 0),
   ('An invasive species is best described as ___.', ['A non-native organism that spreads rapidly in a new environment', 'A native organism that has always existed in a particular ecosystem', 'A concept entirely unrelated to ecology', 'A species with no ability to affect its environment'], 0),
   ('Why is it useful to review genetics, behaviour, and human physiology topics together?', ['It reinforces how these interconnected biological concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in biology', 'Each topic must be studied with no connection to the others'], 0)]),
C('Review: Intermolecular Forces, Equilibrium, and Organic Chemistry',
  'Grade 11 Chemistry strand review: this lesson revisits intermolecular forces, half-life calculations, equilibrium constants, esters and amides, spectroscopy, solubility rules, and reaction mechanisms.',
  [('Intermolecular forces are attractions that occur ___.', ['Between molecules', 'Only within a single atom, with no connection to other molecules', 'A concept unrelated to molecular interactions', 'Exclusively within a single molecule’s own bonds'], 0),
   ('A large equilibrium constant value generally suggests that a reaction ___.', ['Favours the formation of products', 'Favours the reactants remaining unchanged', 'Has no products formed at all', 'Cannot be analyzed using this method'], 0),
   ('Esters and amides are examples of organic ___.', ['Functional groups', 'Elements found only on the periodic table', 'A concept unrelated to organic chemistry', 'Purely inorganic compounds'], 0),
   ('The rate-determining step of a reaction is best described as ___.', ['The slowest step in the reaction mechanism', 'The fastest step in the reaction mechanism', 'A step unrelated to the overall reaction rate', 'The very first step, regardless of its speed'], 0),
   ('Why is it useful to review intermolecular forces, equilibrium, and organic chemistry together?', ['It reinforces how these interconnected chemistry concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in chemistry', 'Each topic must be studied with no connection to the others'], 0)])]),
]

def _rebalance_answer_positions(days, seed=20260726):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g11_41_50)
    append_to(11, g11_41_50)
