#!/usr/bin/env python3
"""Phase 3 extension: Grade 11, Days 51-60 (third Grade 11 batch, first
past the Day 50 milestone). Topics chosen to avoid any overlap with the
existing Day 1-50 set (see data/grade11.json): the anti-hero, the braided
essay, nominalization, frame narratives/metafiction, algorithmic bias,
the graphic novel, rhetorical analysis of a historical speech, active
listening, tone shifts; exponential/logarithmic equations, rational
inequalities, the sine and cosine laws, composite/inverse trig,
mathematical induction, radical equations, sampling methods, linear-
quadratic systems, function symmetry; the lymphatic system, osmosis and
cell transport, circadian rhythms, vision and the eye, the integumentary
system, antibiotic resistance, animal reproduction strategies, animal
migration, the history of evolutionary theory; inorganic nomenclature,
metallic bonding and alloys, chromatography, crystal lattice types,
amines, colloids, electroplating and corrosion prevention, mass
spectrometry, and water hardness.

A few topics originally considered were swapped out after checking
data/grade11.json directly: "Buffer Solutions" (too close to Day 26
"Chemistry: Solutions and Buffers"), "Catalysts and Reaction Mechanisms
in Industry" (too close to Days 16/33/48 on kinetics and mechanisms),
"Alcohols and Ethers" (Day 7 already names alcohols under organic
nomenclature), "Mortgages and Effective Interest Rate" (Day 13 already
names mortgages explicitly), "Modelling with Combined Function Families"
(too close to Day 47's cross-family transformations), "Postcolonial
Literature and Identity" (Day 26's summary already covers colonialism),
"The Socratic Seminar" (too close to Day 14's seminar leadership),
"Photoperiodism" (Day 17's summary already names photoperiodism),
"Symbiotic Relationships" and "Biomagnification and Trophic Levels"
(too close to Day 9's interspecific interactions/energy flow and Day
26's bioaccumulation), "Skeletal System" (Day 35 already covers the
muscular and skeletal systems together), and "Epigenetics" (too close
to Day 36's gene expression and regulation).

Subject keys for Grade 11 are "English", "Functions", "Biology",
"Chemistry" (same as gen_grade11_days41_50.py).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote or apostrophe characters are used
anywhere in question/summary/option text; quotation marks and
apostrophes use the curly Unicode form (' " ").
"""
import sys
sys.path.insert(0, '/sessions/happy-laughing-ritchie/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E11 = 'https://tvolearn.com/pages/grade-11-english'
F11 = 'https://tvolearn.com/pages/grade-11-functions'
B11 = 'https://tvolearn.com/pages/grade-11-biology'
C11 = 'https://tvolearn.com/pages/grade-11-chemistry'
RE, RF, RB, RC = (
    'TVO Learn: Grade 11 English',
    'TVO Learn: Grade 11 Functions',
    'TVO Learn: Grade 11 Biology',
    'TVO Learn: Grade 11 Chemistry',
)


def E(t, s, q):
    return sub('English', t, s, RE, E11, q)


def F(t, s, q):
    return sub('Functions', t, s, RF, F11, q)


def B(t, s, q):
    return sub('Biology', t, s, RB, B11, q)


def C(t, s, q):
    return sub('Chemistry', t, s, RC, C11, q)


g11_51_60 = [
day(51, [
E('Literature: The Anti-Hero in Contemporary Fiction',
  'Grade 11 English strand: an anti-hero is a central character who lacks traditional heroic qualities such as courage or moral clarity, yet still commands a reader’s attention and sympathy through complexity and flawed humanity.',
  [('An anti-hero is best described as a central character who ___.', ['Lacks traditional heroic qualities but still commands the reader’s attention', 'Always displays flawless moral courage', 'A concept unrelated to characterization', 'Never appears as the protagonist of a story'], 0),
   ('Why might readers still sympathize with an anti-hero despite their flaws?', ['Their complexity and flawed humanity can feel more relatable than an idealized hero', 'Anti-heroes never earn any sympathy from readers', 'A reason unrelated to characterization', 'Readers only sympathize with characters who are entirely virtuous'], 0),
   ('Which is an example of a trait commonly associated with an anti-hero?', ['A morally ambiguous choice made for a selfish reason', 'A trait entirely unrelated to characterization', 'Consistently choosing the most selfless option available', 'Complete indifference to every character in the story'], 0),
   ('Why might an author use an anti-hero instead of a conventional hero to explore a story’s themes?', ['An anti-hero’s contradictions can reveal more nuanced or realistic themes about human nature', 'This choice always simplifies a story’s themes', 'Anti-heroes have no connection to a story’s deeper meaning', 'Conventional heroes are always a more effective choice for exploring theme'], 0),
   ('Why has the anti-hero become an especially prominent figure in contemporary fiction and television?', ['Audiences increasingly value morally complex characters over idealized ones', 'Contemporary audiences have no interest in complex characters', 'A reason unrelated to fiction or storytelling', 'Anti-heroes were more common in fiction written centuries ago'], 0)]),
F('Functions: Solving Exponential and Logarithmic Equations Together',
  'Grade 11 Functions strand: exponential and logarithmic equations can be solved together by using the fact that logarithms and exponents are inverse operations, allowing one form to be rewritten as the other to isolate the variable.',
  [('Logarithms and exponents are considered ___ operations of one another.', ['Inverse', 'Identical', 'A relationship unrelated to logarithms', 'Unrelated'], 0),
   ('To solve an equation like 2 to the power of x equals 8 using logarithms, a useful first step is to ___.', ['Take the logarithm of both sides of the equation', 'Add 8 to both sides of the equation', 'A step unrelated to solving exponential equations', 'Divide both sides by the base immediately with no other steps'], 0),
   ('Solve for x: log base 2 of x equals 3.', ['x = 8', 'x = 6', 'A value unrelated to the equation', 'x = 3'], 0),
   ('Why is rewriting an exponential equation in logarithmic form useful when the variable is in the exponent?', ['It isolates the exponent as a standalone variable that can be solved for directly', 'This rewriting never helps isolate a variable', 'Exponential equations can never be solved using logarithms', 'This concept has no connection to solving equations'], 0),
   ('Why might solving exponential and logarithmic equations together be useful for modelling real-world situations, such as radioactive decay reaching a certain level?', ['It allows the exact time or amount to be calculated when a quantity grows or decays exponentially', 'These equations have no real-world modelling application', 'Radioactive decay can never be modelled using exponential functions', 'This concept only applies to purely abstract mathematics'], 0)]),
B('Biology: The Lymphatic System — Fluid Balance and Circulation',
  'Grade 11 Biology strand: the lymphatic system returns excess interstitial fluid to the bloodstream through a network of vessels and lymph nodes, helping maintain fluid balance throughout the body.',
  [('The lymphatic system’s primary role in fluid balance is to ___.', ['Return excess interstitial fluid to the bloodstream', 'Pump blood directly through the heart', 'A role entirely unrelated to fluid balance', 'Remove all fluid from the body permanently'], 0),
   ('Lymph nodes are best described as structures that ___.', ['Filter lymph fluid as it passes through the lymphatic vessels', 'Pump lymph fluid throughout the body', 'A structure entirely unrelated to the lymphatic system', 'Produce red blood cells exclusively'], 0),
   ('Why might swelling, or edema, occur if the lymphatic system is not functioning properly?', ['Excess fluid can build up in tissues instead of being returned to the bloodstream', 'Edema has no connection to the lymphatic system', 'The lymphatic system never affects fluid levels in tissues', 'Swelling always indicates a problem with the digestive system instead'], 0),
   ('Unlike the cardiovascular system, the lymphatic system relies primarily on ___ to move fluid through its vessels.', ['Surrounding muscle contractions, since it lacks a central pump', 'A single, powerful central pump identical to the heart', 'A mechanism entirely unrelated to fluid movement', 'Gravity alone, with no other contributing factor'], 0),
   ('Why is understanding the lymphatic system’s role in fluid balance useful alongside studying the cardiovascular system?', ['The two systems work closely together to circulate fluid and maintain the body’s internal balance', 'The lymphatic system has no connection to circulation', 'These two systems function in complete isolation from one another', 'This knowledge has no relevance to human physiology'], 0)]),
C('Chemistry: Nomenclature of Inorganic Compounds',
  'Grade 11 Chemistry strand: naming inorganic compounds follows systematic IUPAC rules that differ for ionic compounds, compounds with polyatomic ions, and molecular (covalent) compounds using prefixes.',
  [('The systematic naming of inorganic compounds follows rules established by ___.', ['IUPAC', 'A system with no formal naming rules', 'A naming convention unrelated to chemistry', 'Random, informal common names only'], 0),
   ('In naming a binary molecular (covalent) compound, prefixes such as “di-” and “tri-” indicate ___.', ['The number of atoms of each element present', 'The charge of the compound', 'A concept unrelated to naming compounds', 'The state of matter of the compound'], 0),
   ('What is the correct name for the ionic compound with the formula NaCl?', ['Sodium chloride', 'Sodium dichloride', 'A name unrelated to this formula', 'Disodium chloride'], 0),
   ('Why do ionic compounds containing a transition metal, such as iron, often require a Roman numeral in their name?', ['Many transition metals can form more than one possible ionic charge', 'Roman numerals are never used when naming ionic compounds', 'This naming convention has no connection to a metal’s charge', 'Transition metals always form exactly one possible ionic charge'], 0),
   ('Why is a systematic naming system important for inorganic compounds?', ['It allows chemists to communicate a compound’s exact composition clearly and consistently', 'A systematic naming system provides no useful information about a compound', 'Inorganic compounds have no need for a standardized naming system', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(52, [
E('Writing: The Braided Essay — Weaving Multiple Narrative Threads',
  'Grade 11 English strand: a braided essay interweaves two or more distinct narrative threads or topics, alternating between them so that their juxtaposition creates new meaning without a single linear structure.',
  [('A braided essay interweaves ___.', ['Two or more distinct narrative threads or topics', 'Only a single, uninterrupted narrative thread', 'A concept unrelated to essay structure', 'A strictly chronological retelling of one event only'], 0),
   ('Why might a braided essay alternate between its separate threads rather than presenting them one after another?', ['The juxtaposition between threads can create new meaning through their connections', 'Alternating between threads always confuses the reader with no benefit', 'A reason unrelated to essay structure', 'This structure removes any possible connection between ideas'], 0),
   ('Which is an example of how a braided essay might be structured?', ['Alternating sections about a personal memory and a related historical event', 'A single paragraph with no separate sections', 'A structure unrelated to braided essays', 'A strictly linear structure with only one topic discussed'], 0),
   ('Why might a writer choose a braided structure instead of a traditional, single-thread essay?', ['It can reveal connections between seemingly unrelated ideas that a linear structure might not capture', 'A braided structure never reveals any new connections', 'This structure has no connection to how an essay is organized', 'A traditional, single-thread essay is always the more effective choice'], 0),
   ('Why is transition especially important when moving between threads in a braided essay?', ['Clear transitions help the reader follow the connections between each separate thread', 'Transitions are never necessary in this type of essay', 'A reason unrelated to essay writing', 'A braided essay should have no transitions between its threads at all'], 0)]),
F('Functions: Rational Inequalities',
  'Grade 11 Functions strand: solving a rational inequality involves finding the values of a variable that make an expression greater than or less than another, while carefully accounting for values that make the denominator zero.',
  [('A rational inequality involves an expression with a variable in the ___.', ['Denominator', 'Exponent only, with no connection to a denominator', 'A concept unrelated to rational inequalities', 'Numerator only, with no connection to fractions'], 0),
   ('When solving a rational inequality, why must values that make the denominator zero be excluded from the solution?', ['Division by zero is undefined, so those values cannot be part of the solution', 'These values are always automatically included in the solution', 'This restriction has no connection to solving rational inequalities', 'Denominators never affect the solution to an inequality'], 0),
   ('A sign analysis (or test point) approach is often used to solve rational inequalities because ___.', ['It helps determine where the expression is positive or negative across different intervals', 'It has no connection to solving inequalities', 'Sign analysis only applies to solving equations, not inequalities', 'This approach guarantees an identical answer regardless of the inequality being solved'], 0),
   ('For the inequality one divided by the quantity x minus 2, greater than zero, which value of x must be excluded from the solution?', ['x = 2', 'x = 0', 'A value unrelated to this inequality', 'x = -2'], 0),
   ('Why might the solution to a rational inequality be expressed using interval notation rather than a single value?', ['A rational inequality is often satisfied by a range of values rather than one specific value', 'Interval notation is never appropriate for expressing this type of solution', 'A reason unrelated to rational inequalities', 'Rational inequalities always have exactly one possible solution value'], 0)]),
B('Biology: Osmosis and Cell Transport Mechanisms',
  'Grade 11 Biology strand: cells regulate the movement of water and solutes across their membranes through mechanisms including osmosis, diffusion, and active transport, each responding differently to concentration gradients.',
  [('Osmosis specifically describes the movement of ___ across a selectively permeable membrane.', ['Water', 'Only large proteins, with no connection to water', 'A concept unrelated to cell transport', 'Solid particles exclusively, with no connection to fluid movement'], 0),
   ('Diffusion describes the movement of particles from an area of ___ concentration to an area of ___ concentration.', ['Higher; lower', 'Lower; higher', 'A pattern unrelated to concentration gradients', 'Equal; equal, with no net movement ever occurring'], 0),
   ('Unlike diffusion, active transport requires ___.', ['Energy, typically in the form of ATP', 'No energy of any kind', 'A concept unrelated to active transport', 'A concentration gradient moving from low to high with no energy involved'], 0),
   ('Why might a cell placed in a hypertonic solution lose water through osmosis?', ['Water moves toward the higher solute concentration outside the cell', 'Water always moves toward the lower solute concentration in this situation', 'Hypertonic solutions have no effect on water movement', 'Cells never lose water regardless of the surrounding solution'], 0),
   ('Why is active transport essential for cells that need to move substances against their concentration gradient?', ['It allows a cell to accumulate substances even when they are already more concentrated inside the cell', 'Active transport has no connection to moving substances against a gradient', 'Substances can never move against a concentration gradient under any circumstances', 'This process has no relevance to cell function'], 0)]),
C('Chemistry: Alloys and Metallic Bonding',
  'Grade 11 Chemistry strand: metallic bonding involves a lattice of positive metal ions surrounded by a “sea” of delocalized electrons, and alloys are mixtures of metals (or a metal with another element) engineered to enhance properties like strength or resistance to corrosion.',
  [('Metallic bonding is best described as a lattice of positive metal ions surrounded by ___.', ['A “sea” of delocalized electrons', 'A rigid, fixed set of shared electron pairs only', 'A concept unrelated to metallic bonding', 'No electrons of any kind'], 0),
   ('An alloy is best described as ___.', ['A mixture of metals, or a metal combined with another element', 'A single pure metal with no other elements present', 'A concept unrelated to metallic materials', 'A compound formed exclusively through ionic bonding'], 0),
   ('Why are metals generally good conductors of electricity?', ['Delocalized electrons in the metallic lattice can move freely to carry a current', 'Metals never allow electrons to move freely', 'This property has no connection to metallic bonding', 'Electrical conductivity is unrelated to a material’s bonding structure'], 0),
   ('Why might steel, an alloy of iron and carbon, be stronger than pure iron alone?', ['The added carbon atoms disrupt the regular metal lattice, making it harder for layers to slide past one another', 'Adding carbon always weakens the structure of a pure metal', 'Alloys have no connection to the strength of a material', 'Pure iron is always stronger than any alloy made from it'], 0),
   ('Why might engineers choose an alloy over a pure metal for a specific application, such as building an aircraft?', ['Alloys can be engineered to have enhanced properties, like greater strength or corrosion resistance', 'Alloys always perform worse than pure metals in every application', 'This concept has no connection to material selection in engineering', 'Pure metals are always the only option considered for such applications'], 0)])]),

day(53, [
E('Grammar: Nominalization and Academic Register',
  'Grade 11 English strand: nominalization turns a verb or adjective into a noun (such as turning “decide” into “decision”), a technique that can create a more formal academic register but may also make writing feel dense or impersonal if overused.',
  [('Nominalization is the process of turning a verb or adjective into a ___.', ['Noun', 'Adverb, with no connection to nouns', 'A concept unrelated to grammar', 'Conjunction'], 0),
   ('Which of these is an example of nominalization?', ['Turning “decide” into “decision”', 'Turning “decision” into “decide”', 'An example unrelated to nominalization', 'Turning “quickly” into “quick”'], 0),
   ('Why might a writer use nominalization to create a more formal academic register?', ['It can make writing sound more abstract, objective, and suited to academic contexts', 'Nominalization always makes writing sound more casual and conversational', 'This technique has no effect on a piece of writing’s tone', 'Academic writing never uses nominalization of any kind'], 0),
   ('Why might overusing nominalization make a piece of writing feel dense or difficult to read?', ['Turning too many actions into nouns can make sentences feel static and abstract', 'Nominalization always makes writing easier and clearer to read', 'This technique has no connection to how readable a text feels', 'Dense writing is never linked to a writer’s specific word choices'], 0),
   ('Why is it useful for a writer to recognize nominalization when revising a piece of academic writing?', ['It allows a writer to balance formality with clarity by adjusting how many nominalizations are used', 'Recognizing nominalization has no practical use during revision', 'A reason unrelated to academic writing', 'Nominalizations should always be removed entirely from every piece of writing'], 0)]),
F('Trigonometry: Applications of the Sine and Cosine Laws in 3D',
  'Grade 11 Functions strand: the sine law and cosine law allow the sides and angles of non-right triangles to be calculated, and these tools can be extended to solve three-dimensional problems by breaking a scenario into multiple connected triangles.',
  [('The sine law and cosine law are used to solve triangles that ___.', ['Do not necessarily contain a right angle', 'Must always contain a right angle', 'A concept unrelated to solving triangles', 'Have no defined angles or sides at all'], 0),
   ('The cosine law is especially useful for solving a triangle when ___ are known.', ['Two sides and the angle between them', 'Only a single side, with no other information', 'A combination of information unrelated to solving triangles', 'No sides or angles at all'], 0),
   ('In a three-dimensional problem, such as finding the height of a structure viewed from two different points, why might a problem need to be broken into multiple connected triangles?', ['Each triangle can represent a different set of known angles or distances that together solve the full scenario', 'Three-dimensional problems can never be solved using triangles', 'This approach has no connection to solving real-world problems', 'A single triangle always provides enough information for any 3D scenario'], 0),
   ('The sine law states that the ratio of a side’s length to the sine of its opposite angle is ___ for all three sides of a triangle.', ['Constant', 'Always different', 'A relationship unrelated to the sine law', 'Equal to zero'], 0),
   ('Why are the sine and cosine laws valuable tools in fields like surveying and navigation?', ['They allow unknown distances and angles to be calculated without needing a right angle', 'These laws have no practical application outside of a mathematics classroom', 'Surveying and navigation never require the calculation of unknown distances', 'This concept only applies to purely theoretical geometry'], 0)]),
B('Biology: Circadian Rhythms and Biological Clocks',
  'Grade 11 Biology strand: a circadian rhythm is an internal, roughly 24-hour biological cycle that regulates processes such as sleep, hormone release, and body temperature, and is influenced by an internal “biological clock” as well as external cues like light.',
  [('A circadian rhythm is best described as an internal biological cycle that repeats roughly every ___.', ['24 hours', '24 minutes', 'A time period unrelated to circadian rhythms', '24 days'], 0),
   ('Which of these is an example of a process regulated by circadian rhythms?', ['The sleep-wake cycle', 'A process entirely unrelated to biological cycles', 'The immediate reflex of pulling a hand away from a hot surface', 'The one-time process of puberty'], 0),
   ('Which external cue is particularly influential in keeping the body’s internal biological clock synchronized?', ['Light exposure', 'A cue entirely unrelated to biological rhythms', 'The sound of an alarm clock exclusively, with no other influence', 'Air pressure alone, with no connection to light'], 0),
   ('Why might travelling across several time zones disrupt a person’s circadian rhythm, resulting in jet lag?', ['The body’s internal clock remains set to the original time zone while external light cues suddenly shift', 'Circadian rhythms are never affected by travel or time zone changes', 'Jet lag has no connection to the body’s internal biological clock', 'The body’s internal clock adjusts to a new time zone instantly with no disruption'], 0),
   ('Why is understanding circadian rhythms useful for fields like medicine and shift-work scheduling?', ['Disruptions to these natural cycles can affect health, alertness, and overall well-being', 'Circadian rhythms have no connection to health or scheduling', 'This concept has no practical application outside of basic biology', 'Shift work never has any effect on a person’s internal biological clock'], 0)]),
C('Chemistry: Chromatography — Principles and Applications',
  'Grade 11 Chemistry strand: chromatography separates the components of a mixture based on how differently each component travels through a stationary phase when carried by a moving mobile phase, a technique widely used to identify and purify substances.',
  [('Chromatography separates the components of a mixture based on ___.', ['How differently each component travels through a stationary phase', 'The colour of the mixture alone, with no other factor considered', 'A concept unrelated to separating mixtures', 'The temperature of the mixture exclusively'], 0),
   ('In paper chromatography, the stationary phase is best described as ___.', ['The paper itself, through which the mobile phase travels', 'A liquid that moves freely with no fixed surface at all', 'A concept unrelated to chromatography', 'A gas with no connection to the paper or the mixture'], 0),
   ('Why do different components of a mixture typically separate as they travel through the stationary phase?', ['Each component interacts differently with the stationary and mobile phases, causing it to travel at a different rate', 'All components of a mixture always travel at an identical rate', 'This separation has no connection to a component’s chemical properties', 'Separation in chromatography occurs entirely at random'], 0),
   ('Which is an example of a practical application of chromatography?', ['Identifying the individual dyes present in a sample of ink', 'A use entirely unrelated to separating or identifying substances', 'Measuring the exact temperature of a chemical reaction', 'Determining the mass of a single atom'], 0),
   ('Why is chromatography considered a valuable technique in fields like forensic science and pharmaceutical testing?', ['It allows complex mixtures to be separated and their individual components identified or verified', 'Chromatography has no practical application in these fields', 'Mixtures can never be separated using a technique like chromatography', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(54, [
E('Reading: Analyzing Frame Narratives and Metafiction',
  'Grade 11 English strand: a frame narrative encloses one story within another, while metafiction draws attention to its own status as a constructed work of fiction, and both techniques invite readers to think critically about how stories are told.',
  [('A frame narrative encloses ___.', ['One story within another', 'A single story with no additional layers', 'A concept unrelated to narrative structure', 'Only factual, non-fictional accounts'], 0),
   ('Metafiction is best described as fiction that ___.', ['Draws attention to its own status as a constructed work of fiction', 'Never acknowledges that it is a work of fiction', 'A concept unrelated to metafiction', 'Always presents itself as a completely factual account'], 0),
   ('Which is an example of a technique used in metafiction?', ['A narrator directly addressing the reader about the act of writing the story', 'A technique entirely unrelated to metafiction', 'A story that never acknowledges its own construction in any way', 'A narrative with no narrator present at all'], 0),
   ('Why might an author use a frame narrative to structure a story?', ['It can provide context or a specific perspective through which the inner story is understood', 'A frame narrative always removes any context from the inner story', 'This structure has no connection to how a story is understood', 'Frame narratives are never used to provide additional context'], 0),
   ('Why might metafiction challenge a reader’s usual expectations of a story?', ['It disrupts the illusion that a story is a straightforward, self-contained reality', 'Metafiction always reinforces a reader’s usual expectations with no disruption', 'This technique has no effect on how a reader experiences a story', 'Readers never notice when a story draws attention to its own fictional nature'], 0)]),
F('Functions: Composite and Inverse Trigonometric Relationships',
  'Grade 11 Functions strand: a composite function combines two functions so the output of one becomes the input of the other, and this idea extends to trigonometric functions and their inverses, such as evaluating sine of inverse cosine of x.',
  [('A composite function combines two functions so that ___.', ['The output of one function becomes the input of the other', 'Both functions are added together with no other connection', 'A concept unrelated to composite functions', 'Neither function has any effect on the other'], 0),
   ('The inverse trigonometric function, inverse cosine of x, returns ___.', ['The angle whose cosine is x', 'The cosine of the angle x', 'A value unrelated to inverse trigonometric functions', 'The reciprocal of x with no connection to angles'], 0),
   ('When evaluating a composite expression like sine of inverse cosine of x, the inner function is evaluated ___.', ['First, before the outer function is applied to that result', 'After the outer function, with no particular order required', 'A step unrelated to evaluating composite functions', 'At the same time as the outer function, with no defined order'], 0),
   ('Why must the domain of an inverse trigonometric function, such as inverse cosine of x, be restricted to specific values of x?', ['The original trigonometric function is not one-to-one over its full domain, so its inverse must be limited to remain a function', 'Inverse trigonometric functions never require any domain restriction', 'This restriction has no connection to how inverse functions are defined', 'The original trigonometric function is always one-to-one over its entire domain'], 0),
   ('Why might understanding composite and inverse trigonometric relationships be useful for simplifying complex trigonometric expressions?', ['These relationships can allow an expression to be rewritten in a simpler, more manageable form', 'Composite and inverse relationships never simplify a trigonometric expression', 'This concept only applies to purely abstract mathematics with no practical use', 'Trigonometric expressions can never be simplified using these relationships'], 0)]),
B('Biology: Sensory Systems — Vision and the Eye',
  'Grade 11 Biology strand: the eye converts light into neural signals through a series of structures, including the cornea, lens, and retina, which then travel along the optic nerve to be interpreted by the brain.',
  [('The primary function of the eye is to convert ___ into neural signals.', ['Light', 'Sound waves, with no connection to vision', 'A concept unrelated to the eye’s function', 'Chemical signals exclusively, with no connection to light'], 0),
   ('Which structure of the eye is primarily responsible for detecting light and converting it into neural signals?', ['The retina', 'A structure entirely unrelated to vision', 'The eyebrow', 'The eyelid'], 0),
   ('The lens of the eye primarily functions to ___.', ['Focus light onto the retina', 'Produce neural signals directly, with no connection to light', 'A function unrelated to vision', 'Filter sound before it reaches the retina'], 0),
   ('Why is the optic nerve essential for vision, even though structures like the retina detect light?', ['It carries the neural signals generated by the retina to the brain, where they are interpreted', 'The optic nerve has no connection to how visual information reaches the brain', 'Neural signals from the retina are never transmitted to the brain', 'This structure only plays a role in hearing, not vision'], 0),
   ('Why might understanding the structures involved in vision be useful for diagnosing conditions like nearsightedness?', ['It helps explain how a misshapen eye or lens can prevent light from focusing properly on the retina', 'This understanding has no connection to diagnosing vision problems', 'Nearsightedness has no relationship to the structures of the eye', 'Vision problems can never be explained using knowledge of eye structures'], 0)]),
C('Chemistry: Crystal Structures and Lattice Types',
  'Grade 11 Chemistry strand: solids can be classified by their crystal lattice type — ionic, molecular, covalent network, or metallic — and each type’s characteristic bonding gives rise to distinct physical properties like melting point and hardness.',
  [('A crystal lattice is best described as ___.', ['An orderly, repeating arrangement of particles in a solid', 'A completely random, disordered arrangement of particles', 'A concept unrelated to solids', 'A structure found only in liquids'], 0),
   ('Which of these is an example of a covalent network lattice?', ['Diamond', 'A structure entirely unrelated to crystal lattices', 'Table salt', 'A pure metal such as copper'], 0),
   ('Why do ionic crystal lattices, such as table salt, typically have high melting points?', ['The strong electrostatic attraction between oppositely charged ions requires significant energy to overcome', 'Ionic lattices always have very low melting points', 'This property has no connection to the type of bonding present', 'Melting point is determined entirely by colour, with no connection to bonding'], 0),
   ('Why is diamond, a covalent network lattice, known for being an extremely hard material?', ['Each carbon atom is strongly bonded to four others in a continuous three-dimensional network', 'Diamond has no connection to covalent network bonding', 'Covalent network lattices are always among the softest materials', 'Hardness has no relationship to a crystal’s lattice structure'], 0),
   ('Why is classifying a solid by its crystal lattice type useful for predicting its physical properties?', ['The type of particles and bonding within the lattice strongly influence properties like melting point and hardness', 'Crystal lattice type has no connection to a solid’s physical properties', 'All crystal lattice types produce identical physical properties', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(55, [
E('Media Literacy: Analyzing Algorithmic Bias in Media Platforms',
  'Grade 11 English strand: algorithmic bias occurs when the automated systems that curate content on media platforms systematically favour certain viewpoints or information over others, often shaping what audiences see without their awareness.',
  [('Algorithmic bias occurs when automated systems that curate content ___.', ['Systematically favour certain viewpoints or information over others', 'Present every viewpoint with exactly equal, unbiased frequency', 'A concept unrelated to media platforms', 'Have no influence at all on what content audiences see'], 0),
   ('Why might users be largely unaware that an algorithm is shaping the content they see?', ['Curation often happens automatically in the background, without an obvious explanation to the user', 'Every media platform clearly explains its curation process to every user', 'Algorithms have no actual influence on the content displayed to users', 'A reason unrelated to how media platforms function'], 0),
   ('Which is an example of a potential consequence of algorithmic bias on a media platform?', ['A user being repeatedly shown content that reinforces their existing beliefs', 'A consequence entirely unrelated to algorithmic curation', 'Every user seeing an identical, unbiased selection of content', 'Algorithms having no effect on which content becomes popular'], 0),
   ('Why is critically evaluating the source of recommended content an important media literacy skill today?', ['It helps individuals recognize when their information may be shaped by an algorithm rather than by balanced coverage', 'This skill has no connection to understanding modern media platforms', 'Recommended content is always presented with no underlying algorithmic influence', 'Media literacy has no relevance to how algorithms curate content'], 0),
   ('Why might researchers and regulators express concern about algorithmic bias on major media platforms?', ['It can influence public opinion and limit exposure to diverse perspectives at a large scale', 'Algorithmic bias has no meaningful impact on public opinion', 'A reason unrelated to media literacy or society', 'Media platforms have no influence on public discourse'], 0)]),
F('Discrete Math: Mathematical Induction (Introduction)',
  'Grade 11 Functions strand (Discrete Mathematics): mathematical induction is a method of proof that establishes a statement is true for all natural numbers by proving it holds for a base case and then showing that if it holds for one case, it must hold for the next.',
  [('Mathematical induction is a method used to prove a statement is true for ___.', ['All natural numbers', 'Only a single specific number', 'A concept unrelated to proof techniques', 'No numbers at all'], 0),
   ('The first step of a proof by mathematical induction is called the ___.', ['Base case', 'Final case, with no earlier steps required', 'A step unrelated to mathematical induction', 'Conclusion'], 0),
   ('The second step of a proof by mathematical induction, which shows that if a statement holds for one case it must hold for the next, is called the ___.', ['Inductive step', 'Base case, repeated a second time', 'A step unrelated to mathematical induction', 'Final answer'], 0),
   ('Why is mathematical induction often compared to a row of falling dominoes?', ['Proving the first domino falls and that each domino knocks over the next shows the entire row will fall', 'This comparison has no connection to how mathematical induction works', 'Dominoes and mathematical induction share no meaningful similarity', 'Mathematical induction only ever proves a single case, similar to one domino falling alone'], 0),
   ('Why is mathematical induction a useful proof technique in mathematics?', ['It provides a rigorous way to prove that a pattern or formula holds true for an infinite set of cases', 'Mathematical induction can only ever prove a statement for a single case', 'This technique has no practical use in proving mathematical statements', 'Mathematical induction has no connection to patterns or formulas'], 0)]),
B('Biology: The Integumentary System — Skin as an Organ',
  'Grade 11 Biology strand: the integumentary system, primarily the skin, functions as the body’s largest organ, providing protection, regulating temperature, and enabling sensation through specialized layers and structures.',
  [('The integumentary system is primarily made up of the ___.', ['Skin', 'A structure entirely unrelated to the integumentary system', 'Heart and blood vessels', 'Lungs and airways'], 0),
   ('The skin is often described as the body’s largest ___.', ['Organ', 'Muscle, with no connection to organs', 'A structure unrelated to this classification', 'Bone'], 0),
   ('Which of these is a function of the skin as part of the integumentary system?', ['Regulating body temperature', 'Pumping blood throughout the body', 'A function entirely unrelated to the skin', 'Producing digestive enzymes'], 0),
   ('Why is the skin’s role in protection considered essential to overall health?', ['It acts as a barrier against pathogens, injury, and harmful UV radiation', 'The skin provides no protective function to the body', 'This function has no connection to overall health', 'Protection from the environment is handled entirely by the skeletal system instead'], 0),
   ('Why might sweating be considered an example of the skin’s role in temperature regulation?', ['The evaporation of sweat from the skin’s surface helps cool the body down', 'Sweating has no connection to regulating body temperature', 'The skin plays no role in maintaining a stable internal temperature', 'Sweating always raises the body’s internal temperature instead of lowering it'], 0)]),
C('Chemistry: Organic Chemistry — Amines and Nitrogen-Containing Compounds',
  'Grade 11 Chemistry strand: amines are organic compounds containing a nitrogen atom bonded to carbon, and their properties, including basicity and distinctive odour, make them important in biological molecules and industrial applications.',
  [('An amine is an organic compound containing a nitrogen atom bonded to ___.', ['Carbon', 'Only oxygen, with no connection to carbon', 'A concept unrelated to organic chemistry', 'Only hydrogen, with no connection to carbon'], 0),
   ('Amines are generally classified based on ___.', ['How many carbon groups are bonded to the nitrogen atom', 'Their exact colour, with no connection to structure', 'A concept unrelated to classifying amines', 'The total number of oxygen atoms present'], 0),
   ('Which property is commonly associated with amines?', ['A distinctive, often fish-like odour', 'A complete absence of any noticeable scent', 'A property entirely unrelated to smell', 'An odour identical to all other organic compounds'], 0),
   ('Why do amines generally behave as weak bases?', ['The nitrogen atom’s lone pair of electrons can accept a proton', 'Amines have no connection to acid-base behaviour', 'Amines always behave as strong acids instead of bases', 'This property has no connection to their nitrogen atom'], 0),
   ('Why are amines considered important in biological molecules, such as amino acids and neurotransmitters?', ['The nitrogen-containing amine group contributes to the structure and function of these essential molecules', 'Amines have no connection to biological molecules', 'Amino acids and neurotransmitters never contain nitrogen', 'This concept has no relevance to biochemistry'], 0)])]),

day(56, [
E('Literature: The Graphic Novel as Literary Form',
  'Grade 11 English strand: a graphic novel conveys narrative through the interaction of images and text, using visual techniques like panel layout and framing to shape pacing and meaning in ways unique to the medium.',
  [('A graphic novel conveys its narrative through the interaction of ___.', ['Images and text', 'Only text, with no visual component', 'A concept unrelated to graphic novels', 'Only images, with no written text at all'], 0),
   ('In a graphic novel, a “panel” refers to ___.', ['A single framed image that represents one moment in the narrative', 'The entire book from beginning to end', 'A concept unrelated to graphic novels', 'Only the written dialogue, with no connection to images'], 0),
   ('Why might the size or shape of a panel affect the pacing of a graphic novel?', ['Panel size can control how quickly or slowly a reader’s eye moves through a sequence of events', 'Panel size has no connection to how a reader experiences pacing', 'All panels in a graphic novel are always identical in size and shape', 'Pacing in a graphic novel is determined only by the written dialogue'], 0),
   ('Why might a graphic novel be considered a distinct literary form rather than simply an illustrated version of a prose novel?', ['It relies on the specific interplay between images and text to construct meaning, not just illustration', 'A graphic novel is always identical in form and function to a prose novel', 'This medium has no unique qualities that distinguish it from other literary forms', 'Images in a graphic novel serve no purpose beyond decoration'], 0),
   ('Why might analyzing a graphic novel require different critical skills than analyzing a purely prose-based text?', ['Readers must interpret visual elements, like framing and layout, alongside written language', 'Graphic novels require no unique analytical skills compared to prose texts', 'This type of analysis has no connection to literary study', 'Visual elements in a graphic novel carry no meaning of their own'], 0)]),
F('Functions: Solving Radical Equations and Extraneous Roots',
  'Grade 11 Functions strand: solving a radical equation typically involves isolating the radical and squaring both sides, a process that can introduce an extraneous root — a solution that satisfies the resulting equation but not the original one.',
  [('Solving a radical equation typically involves isolating the radical and then ___.', ['Squaring both sides of the equation', 'Adding the same value to both sides with no other steps', 'A step unrelated to solving radical equations', 'Dividing both sides by the radical term itself'], 0),
   ('An extraneous root is a solution that ___.', ['Satisfies the squared equation but not the original radical equation', 'Always satisfies both the original equation and the squared equation', 'A concept unrelated to solving radical equations', 'Can never occur when solving a radical equation'], 0),
   ('Why is it necessary to check each potential solution to a radical equation in the original equation?', ['Squaring both sides can introduce a solution that does not actually satisfy the original equation', 'Checking solutions is never a necessary step when solving radical equations', 'This step has no connection to solving radical equations correctly', 'Every solution found is always guaranteed to be valid with no further checking needed'], 0),
   ('Solve for x: the square root of the quantity x plus 3, equals 4. What is x?', ['x = 13', 'x = 7', 'A value unrelated to the equation', 'x = 1'], 0),
   ('Why might radical equations be useful for modelling real-world situations, such as calculating a pendulum’s period based on its length?', ['They can represent relationships where one quantity depends on the square root of another', 'Radical equations have no real-world modelling applications', 'This type of situation can never be represented using a radical equation', 'This concept only applies to purely abstract mathematics'], 0)]),
B('Biology: Antibiotic Resistance and Microbial Evolution',
  'Grade 11 Biology strand: antibiotic resistance develops when bacteria undergo mutations or exchange genetic material that allow them to survive exposure to antibiotics, a clear example of natural selection acting on a microbial population.',
  [('Antibiotic resistance develops when bacteria ___.', ['Undergo mutations or exchange genetic material that allow them to survive antibiotic exposure', 'Are completely destroyed by every antibiotic with no exceptions', 'A concept unrelated to bacterial survival', 'Lose all ability to reproduce after antibiotic exposure'], 0),
   ('Antibiotic resistance is often described as a clear real-world example of ___.', ['Natural selection acting on a microbial population', 'A process entirely unrelated to evolutionary biology', 'A random event with no connection to survival or reproduction', 'A phenomenon that never occurs in bacterial populations'], 0),
   ('Why might overusing antibiotics contribute to the spread of antibiotic-resistant bacteria?', ['Surviving resistant bacteria are more likely to reproduce and pass on their resistance', 'Overusing antibiotics always eliminates every bacterium, including resistant ones', 'Antibiotic use has no connection to bacterial resistance', 'Bacteria never develop resistance regardless of antibiotic exposure'], 0),
   ('Which of these is a mechanism by which bacteria can exchange genetic material, contributing to the spread of resistance?', ['Horizontal gene transfer between bacterial cells', 'A mechanism entirely unrelated to bacterial genetics', 'A process that only occurs in complex multicellular organisms', 'A method with no connection to spreading resistance genes'], 0),
   ('Why is antibiotic resistance considered a significant concern for public health?', ['It can make common bacterial infections increasingly difficult to treat effectively', 'Antibiotic resistance has no impact on how infections are treated', 'This concept has no relevance to public health', 'Resistant bacteria are always easier to treat than non-resistant bacteria'], 0)]),
C('Chemistry: Colloids, Emulsions, and Suspensions',
  'Grade 11 Chemistry strand: mixtures can be classified as colloids, emulsions, or suspensions based on particle size and stability, distinguishing them from true solutions in which particles are fully dissolved and do not settle out.',
  [('Unlike a true solution, a suspension contains particles that ___.', ['Are large enough to eventually settle out of the mixture', 'Are fully dissolved and never settle out', 'A concept unrelated to suspensions', 'Cannot be seen or detected under any circumstances'], 0),
   ('A colloid is best described as a mixture in which ___.', ['Small particles are dispersed throughout another substance without settling out or fully dissolving', 'All particles are fully dissolved, identical to a true solution', 'A concept unrelated to colloids', 'No particles of any kind are present'], 0),
   ('An emulsion is specifically a colloid formed by combining ___.', ['Two liquids that would not normally mix, such as oil and water', 'Only solids, with no connection to liquids', 'A concept unrelated to emulsions', 'Only gases, with no liquid component'], 0),
   ('Why might an emulsion, such as mayonnaise, require an emulsifying agent to remain stable?', ['An emulsifier helps keep the two normally immiscible liquids evenly dispersed rather than separating', 'Emulsifying agents have no effect on the stability of a mixture', 'Emulsions never require any additional ingredient to remain stable', 'This concept has no connection to how emulsions are formed'], 0),
   ('Why is the Tyndall effect, the scattering of light, useful for distinguishing a colloid from a true solution?', ['Colloid particles are large enough to scatter light, while a true solution’s particles are not', 'The Tyndall effect occurs identically in both colloids and true solutions', 'This effect has no connection to distinguishing types of mixtures', 'True solutions always scatter light more strongly than colloids'], 0)])]),

day(57, [
E('Writing: The Rhetorical Analysis of a Historical Speech',
  'Grade 11 English strand: a rhetorical analysis of a historical speech examines how a speaker used specific persuasive techniques and appeals, within the context of their historical moment, to influence an audience.',
  [('A rhetorical analysis of a historical speech examines how a speaker used ___.', ['Specific persuasive techniques and appeals to influence an audience', 'Only the exact date the speech was delivered', 'A concept unrelated to rhetorical analysis', 'A completely random selection of unrelated words'], 0),
   ('Why is understanding a speech’s historical context important when conducting a rhetorical analysis?', ['The context can reveal why certain appeals or arguments would have been especially persuasive to that audience', 'Historical context has no connection to how a speech was received', 'A rhetorical analysis should never consider a speech’s historical context', 'Every audience throughout history responds to speeches in an identical way'], 0),
   ('Which is an example of a rhetorical technique a speaker might use in a historical speech?', ['Repetition of a key phrase to reinforce a central idea', 'A technique entirely unrelated to rhetorical analysis', 'Avoiding any structure or organization within the speech', 'A method with no connection to persuading an audience'], 0),
   ('Why might analyzing the intended audience of a historical speech deepen a reader’s understanding of its rhetorical choices?', ['A speaker’s appeals are often shaped specifically to resonate with that audience’s values and concerns', 'The intended audience has no influence on a speaker’s rhetorical choices', 'This factor has no connection to conducting a rhetorical analysis', 'Every historical speech is written with no audience in mind at all'], 0),
   ('Why do rhetorical analyses of historical speeches remain a valuable exercise for students today?', ['They build skills in recognizing persuasive techniques used in both historical and contemporary communication', 'This skill has no relevance to understanding modern communication', 'Rhetorical analysis is only useful for studying speeches, with no broader application', 'Historical speeches have no lasting relevance to contemporary rhetorical study'], 0)]),
F('Statistics: Sampling Methods and Bias',
  'Grade 11 Functions strand (Data Management): the way a sample is selected from a population — through methods like simple random, stratified, or convenience sampling — can introduce bias that affects how accurately the sample represents the larger population.',
  [('A sample is best described as ___.', ['A subset of a population selected for study', 'The entire population being studied, with no subset involved', 'A concept unrelated to statistics', 'A value calculated only after all data has been collected'], 0),
   ('In a simple random sample, every member of the population ___.', ['Has an equal chance of being selected', 'Is guaranteed to be selected', 'A concept unrelated to random sampling', 'Has no chance of ever being selected'], 0),
   ('Why might convenience sampling, such as surveying only people who happen to be nearby, introduce bias into a study?', ['The sample may not accurately represent the diversity of the larger population', 'Convenience sampling always produces a perfectly representative sample', 'This method has no connection to introducing bias into a study', 'Bias can never occur regardless of how a sample is selected'], 0),
   ('A stratified sample divides a population into subgroups and then ___.', ['Randomly samples from within each subgroup', 'Selects the entire population with no subgroups involved', 'A method unrelated to stratified sampling', 'Excludes all subgroups except one from the sample entirely'], 0),
   ('Why is understanding sampling methods and potential bias important when interpreting the results of a survey or study?', ['The way a sample was selected can significantly affect how reliably its results reflect the larger population', 'Sampling methods have no connection to how reliable a study’s results are', 'A reason unrelated to interpreting statistical results', 'Every sampling method produces results that are equally accurate'], 0)]),
B('Biology: Animal Reproduction — Strategies and Adaptations',
  'Grade 11 Biology strand: animal species have evolved diverse reproductive strategies, from producing many offspring with little parental care to producing few offspring with extensive care, each adapted to different environmental pressures.',
  [('A reproductive strategy involving many offspring with relatively little parental care is often associated with species that ___.', ['Face high offspring mortality in their environment', 'Always provide extensive parental care to every offspring', 'A concept unrelated to reproductive strategies', 'Produce exactly one offspring at a time with no exceptions'], 0),
   ('A reproductive strategy involving few offspring with extensive parental care is often associated with species that ___.', ['Invest heavily in ensuring each offspring survives', 'Provide no parental care of any kind', 'A concept unrelated to reproductive strategies', 'Always produce the maximum number of offspring possible'], 0),
   ('Which is an example of an adaptation related to reproductive strategy in animals?', ['A sea turtle laying a large number of eggs, most of which will not survive', 'An adaptation entirely unrelated to reproduction', 'A behaviour with no connection to offspring survival', 'A strategy that never varies between different animal species'], 0),
   ('Why might environmental pressures, such as predation risk or resource availability, influence which reproductive strategy a species evolves?', ['These pressures shape which strategy is most likely to result in successful offspring survival over time', 'Environmental pressures have no influence on reproductive strategies', 'All species evolve the exact same reproductive strategy regardless of their environment', 'This concept has no connection to evolutionary biology'], 0),
   ('Why is studying diverse animal reproductive strategies valuable for understanding evolutionary biology?', ['It reveals how natural selection can favour very different solutions to the same challenge of successful reproduction', 'Reproductive strategies have no connection to evolutionary biology', 'All animal species share an identical reproductive strategy', 'This topic has no relevance to studying biology'], 0)]),
C('Chemistry: Electroplating and Corrosion Prevention',
  'Grade 11 Chemistry strand: electroplating uses an electrolytic cell to coat an object with a thin layer of metal, a process closely related to methods like cathodic protection that are used to prevent corrosion in structures such as pipelines and ships.',
  [('Electroplating uses an electrolytic cell to ___.', ['Coat an object with a thin layer of metal', 'Remove all metal coatings from an object', 'A concept unrelated to electroplating', 'Melt an object completely with no coating applied'], 0),
   ('Corrosion, such as the rusting of iron, is best described as a ___.', ['Chemical reaction that gradually deteriorates a metal, often through oxidation', 'Process that has no connection to chemical reactions', 'A concept unrelated to metal degradation', 'Reaction that only occurs in the complete absence of oxygen'], 0),
   ('Cathodic protection helps prevent corrosion by ___.', ['Using a more easily oxidized “sacrificial” metal to protect the structure being safeguarded', 'Removing all metal from a structure entirely', 'A method unrelated to preventing corrosion', 'Increasing the exposure of a structure to oxygen and moisture'], 0),
   ('Why might a sacrificial anode, such as zinc attached to a ship’s hull, help protect the ship’s steel from corroding?', ['The zinc corrodes preferentially, protecting the more valuable steel structure from oxidation', 'Sacrificial anodes have no effect on preventing corrosion', 'The steel always corrodes at a faster rate than the sacrificial metal', 'This method has no connection to electrochemistry'], 0),
   ('Why are electroplating and corrosion prevention considered important applications of electrochemistry in industry?', ['They allow materials to be protected or enhanced, extending the lifespan and improving the properties of structures and products', 'These processes have no practical industrial applications', 'Electrochemistry has no connection to protecting materials from damage', 'This concept only applies to purely theoretical chemistry problems'], 0)])]),

day(58, [
E('Oral Communication: Active Listening and Constructive Feedback',
  'Grade 11 English strand: active listening involves fully concentrating on and engaging with a speaker’s message, and it forms the foundation for giving constructive feedback that is specific, respectful, and genuinely useful to the listener.',
  [('Active listening involves ___.', ['Fully concentrating on and engaging with a speaker’s message', 'Waiting silently only until it is one’s turn to speak', 'A concept unrelated to communication', 'Ignoring a speaker’s message entirely while planning a response'], 0),
   ('Which is an example of a technique used in active listening?', ['Paraphrasing what a speaker said to confirm understanding', 'A technique entirely unrelated to active listening', 'Interrupting a speaker frequently with unrelated comments', 'Avoiding any eye contact or visible engagement with the speaker'], 0),
   ('Why is specificity considered an important quality of constructive feedback?', ['Specific feedback gives the listener clear, actionable information they can use to improve', 'Specific feedback always confuses the listener with no benefit', 'A reason unrelated to giving feedback', 'Vague feedback is always more useful than specific feedback'], 0),
   ('Why might active listening be considered a necessary foundation for giving effective feedback?', ['Fully understanding a speaker’s message allows feedback to directly address what was actually communicated', 'Active listening has no connection to the quality of feedback given afterward', 'Effective feedback can be given with no attention paid to the original message', 'This skill has no relevance to oral communication'], 0),
   ('Why is active listening considered a valuable skill beyond the classroom, such as in future workplace settings?', ['It supports clear communication, collaboration, and stronger relationships in many contexts', 'Active listening has no application outside of a classroom setting', 'This skill is never useful in professional or workplace communication', 'A reason unrelated to real-world communication skills'], 0)]),
F('Functions: Solving Systems of Linear-Quadratic Equations',
  'Grade 11 Functions strand: a linear-quadratic system consists of one linear and one quadratic equation, and its solution — the points where a line and a parabola intersect — can be found algebraically through substitution or graphically.',
  [('A linear-quadratic system consists of ___.', ['One linear equation and one quadratic equation', 'Two linear equations, with no quadratic equation involved', 'A concept unrelated to systems of equations', 'Two quadratic equations, with no linear equation involved'], 0),
   ('The solution to a linear-quadratic system represents ___.', ['The point or points where a line and a parabola intersect', 'A single point unrelated to either equation in the system', 'A concept unrelated to solving systems of equations', 'The vertex of the parabola exclusively, with no connection to the line'], 0),
   ('A common algebraic method for solving a linear-quadratic system involves ___.', ['Substituting the linear equation into the quadratic equation', 'Ignoring the linear equation entirely', 'A method unrelated to solving this type of system', 'Adding both equations together with no other steps'], 0),
   ('How many possible solutions can a linear-quadratic system have?', ['Zero, one, or two solutions, depending on how the line and parabola intersect', 'Always exactly one solution, with no other possibility', 'A number of solutions unrelated to how the graphs intersect', 'Always exactly three solutions in every case'], 0),
   ('Why might a linear-quadratic system be useful for modelling a real-world situation, such as finding when a thrown object’s height matches a constant reference height?', ['It can represent the relationship between a changing quantity, like height, and a fixed or steadily changing comparison value', 'Linear-quadratic systems have no real-world modelling applications', 'This type of situation can never be represented using a system of equations', 'This concept only applies to purely abstract mathematics'], 0)]),
B('Biology: Animal Migration — Patterns and Physiological Triggers',
  'Grade 11 Biology strand: animal migration is the seasonal movement of a species between different geographic regions, often triggered by physiological cues such as changing day length or hormone levels, and is critical for accessing food, breeding grounds, or favourable climates.',
  [('Animal migration is best described as ___.', ['The seasonal movement of a species between different geographic regions', 'A permanent, one-time relocation with no seasonal pattern', 'A concept unrelated to animal behaviour', 'Movement that occurs entirely at random with no discernible pattern'], 0),
   ('Which of these is a common reason animal species migrate?', ['To access food, breeding grounds, or a more favourable climate', 'A reason entirely unrelated to survival or reproduction', 'To permanently abandon their original habitat with no intention of returning', 'Migration serves no biological purpose for any species'], 0),
   ('Which physiological cue might help trigger migratory behaviour in a species?', ['Changing day length', 'A cue entirely unrelated to physiology', 'A random signal with no biological basis', 'The colour of nearby vegetation exclusively'], 0),
   ('Why might hormone levels play a role in triggering an animal’s migratory behaviour?', ['Hormonal changes can prepare an animal’s body for the physical demands of a long journey', 'Hormones have no connection to triggering migratory behaviour', 'Migratory behaviour is never influenced by any internal physiological signal', 'This concept has no relevance to understanding animal migration'], 0),
   ('Why is studying animal migration valuable for conservation efforts?', ['Understanding migratory patterns helps identify and protect the habitats and routes species depend on', 'Animal migration has no connection to conservation efforts', 'Migratory species require no special conservation considerations', 'This topic has no relevance to studying biology'], 0)]),
C('Chemistry: Mass Spectrometry and Molecular Identification',
  'Grade 11 Chemistry strand: mass spectrometry identifies a molecule by ionizing a sample and measuring the mass-to-charge ratio of the resulting fragments, producing a distinctive pattern that can reveal a compound’s structure and molecular mass.',
  [('Mass spectrometry identifies a molecule by ionizing a sample and measuring its ___.', ['Mass-to-charge ratio', 'Colour when exposed to light', 'A concept unrelated to mass spectrometry', 'Boiling point exclusively, with no connection to ionization'], 0),
   ('The pattern of fragments produced during mass spectrometry can help reveal a compound’s ___.', ['Structure and molecular mass', 'Exact temperature at the time of testing', 'A concept unrelated to molecular identification', 'Colour, with no connection to its structure'], 0),
   ('Why is a sample first ionized during mass spectrometry?', ['Charged particles can be manipulated and measured using electric and magnetic fields', 'Ionization has no connection to how mass spectrometry works', 'A sample must remain completely neutral for this technique to function', 'This step is only relevant for very large, complex molecules'], 0),
   ('Why might each compound produce a unique fragmentation pattern in mass spectrometry?', ['A molecule’s specific structure determines how it breaks apart during ionization', 'All compounds produce an identical fragmentation pattern regardless of structure', 'Fragmentation patterns have no connection to a molecule’s structure', 'This concept has no scientific basis'], 0),
   ('Why is mass spectrometry a valuable tool in fields such as forensic science and pharmaceutical research?', ['It allows unknown or trace substances to be identified with a high degree of precision', 'Mass spectrometry has no practical application in these fields', 'Identifying unknown substances never requires this type of technique', 'This technique only applies to purely theoretical chemistry problems'], 0)])]),

day(59, [
E('Reading: Analyzing Tone Shifts Across a Text',
  'Grade 11 English strand: a tone shift occurs when a writer’s attitude toward a subject changes over the course of a text, often signalled by changes in word choice, sentence structure, or imagery, and recognizing these shifts deepens a reader’s interpretation.',
  [('A tone shift occurs when a writer’s attitude toward a subject ___.', ['Changes over the course of a text', 'Remains exactly the same throughout an entire text with no variation', 'A concept unrelated to tone', 'Is never expressed anywhere within a text'], 0),
   ('Which of these might signal a tone shift within a text?', ['A noticeable change in word choice or imagery', 'A signal entirely unrelated to a writer’s tone', 'An identical sentence repeated without any change', 'The page number changing within a printed book'], 0),
   ('Why might an author use a tone shift to move from a light, humorous tone to a more serious one?', ['The shift can emphasize a significant change in the story’s events or the character’s circumstances', 'Tone shifts never carry any meaningful significance within a text', 'This technique has no connection to how a story is structured', 'An author’s tone must always remain identical throughout a text'], 0),
   ('Why is recognizing a tone shift an important skill in literary analysis?', ['It reveals a deeper layer of meaning connected to how the writer’s perspective evolves', 'Recognizing tone shifts has no effect on how a text is interpreted', 'A tone shift never provides any additional insight into a text', 'This skill has no connection to literary analysis'], 0),
   ('Why might a reader need to consider both word choice and structure together to fully identify a tone shift?', ['A shift in tone is often reinforced by multiple techniques working together, not just a single word', 'Word choice and structure never work together to create a tone shift', 'A reason unrelated to identifying tone shifts', 'Tone shifts can only ever be identified through a text’s structure, with no connection to word choice'], 0)]),
F('Functions: Symmetry — Even, Odd, and Neither',
  'Grade 11 Functions strand: a function’s symmetry can be classified as even (symmetric about the y-axis), odd (symmetric about the origin), or neither, based on how the function behaves when its input is replaced with its negative.',
  [('A function is classified as even if its graph is symmetric about the ___.', ['Y-axis', 'X-axis, with no connection to the y-axis', 'A concept unrelated to symmetry', 'Origin exclusively, with no connection to the y-axis'], 0),
   ('A function is classified as odd if its graph is symmetric about the ___.', ['Origin', 'Y-axis, with no connection to the origin', 'A concept unrelated to symmetry', 'X-axis exclusively, with no connection to the origin'], 0),
   ('To test whether a function is even, a mathematician checks whether f of negative x is equal to ___.', ['f(x)', 'The negative of f(x), with no connection to f(x)', 'A value unrelated to testing for symmetry', 'Zero, in every case with no exceptions'], 0),
   ('To test whether a function is odd, a mathematician checks whether f of negative x is equal to ___.', ['The negative of f(x)', 'f(x), with no connection to the negative of f(x)', 'A value unrelated to testing for symmetry', 'One, in every case with no exceptions'], 0),
   ('Why is identifying a function’s symmetry useful when sketching its graph?', ['It allows part of the graph to be reflected to quickly determine the rest of the graph’s shape', 'Symmetry provides no useful shortcut when graphing a function', 'A function’s symmetry has no connection to its overall graph', 'Every function must be graphed with no consideration of its symmetry'], 0)]),
B('Biology: The History of Evolutionary Theory (Darwin and Wallace)',
  'Grade 11 Biology strand: Charles Darwin and Alfred Russel Wallace independently developed the theory of evolution by natural selection, drawing on observations from their travels, and their combined work fundamentally reshaped the scientific understanding of how species change over time.',
  [('Charles Darwin and Alfred Russel Wallace independently developed the theory of ___.', ['Evolution by natural selection', 'A theory entirely unrelated to evolution', 'The immediate creation of every species with no change over time', 'A concept unrelated to the history of biology'], 0),
   ('Darwin’s observations during his voyage on the ___ contributed significantly to his theory of evolution.', ['HMS Beagle', 'A ship entirely unrelated to his scientific work', 'A vessel with no connection to his voyage of observation', 'A location unrelated to gathering scientific evidence'], 0),
   ('Why is it notable that Darwin and Wallace developed strikingly similar theories of evolution independently?', ['It suggests their shared theory was strongly supported by consistent patterns observed in nature', 'This similarity has no significance in the history of science', 'Independent discovery in science never carries any scientific weight', 'Darwin and Wallace worked together directly for their entire careers, with no independent research involved'], 0),
   ('Why did Darwin and Wallace’s theory of evolution by natural selection represent such a significant shift in scientific understanding?', ['It offered a mechanism explaining how species could change and adapt over time, without requiring separate creation', 'This theory had no significant impact on the scientific understanding of species', 'Evolutionary theory was already universally accepted before their work', 'Their theory has no connection to how species are understood to change over time'], 0),
   ('Why do biologists still study the history of Darwin and Wallace’s work today?', ['It provides important context for understanding how a foundational scientific theory developed and gained acceptance', 'Their historical work has no relevance to modern biology', 'A reason unrelated to studying the history of science', 'Darwin and Wallace’s theory has since been proven to have no scientific basis'], 0)]),
C('Chemistry: Water Chemistry and Hardness',
  'Grade 11 Chemistry strand: water hardness is caused by dissolved calcium and magnesium ions, and understanding water chemistry, including methods like ion exchange softening, is important for both household and industrial applications.',
  [('Water hardness is primarily caused by dissolved ___ ions.', ['Calcium and magnesium', 'Sodium and potassium exclusively, with no connection to hardness', 'A type of ion unrelated to water hardness', 'Chloride ions exclusively, with no connection to hardness'], 0),
   ('Which of these is a common effect of hard water in household settings?', ['Reduced soap lathering and mineral buildup in pipes', 'An effect entirely unrelated to water chemistry', 'Water that is always unsafe to drink', 'No noticeable effect on household appliances or plumbing'], 0),
   ('Ion exchange softening works by replacing calcium and magnesium ions in water with ___.', ['Sodium ions', 'A gas, with no connection to ion exchange', 'A method unrelated to water softening', 'Additional calcium ions, increasing the water’s hardness further'], 0),
   ('Why might dissolved calcium and magnesium ions cause mineral buildup, or scale, inside pipes and appliances over time?', ['These ions can form solid deposits as water evaporates or reacts with other substances', 'Calcium and magnesium ions never form any solid deposits', 'This process has no connection to water hardness', 'Mineral buildup only occurs in water with no dissolved ions at all'], 0),
   ('Why is understanding water hardness and softening methods important in industrial applications, such as in boilers?', ['Mineral buildup from hard water can reduce efficiency and damage industrial equipment over time', 'Water hardness has no effect on industrial equipment', 'This concept only applies to purely theoretical chemistry problems', 'Industrial equipment is never affected by the chemical composition of water'], 0)])]),

day(60, [
E('Review: Anti-Heroes, Braided Essays, and Rhetorical Analysis',
  'Grade 11 English strand review: this lesson revisits the anti-hero, the braided essay, nominalization, frame narratives and metafiction, algorithmic bias, the graphic novel, rhetorical analysis, active listening, and tone shifts.',
  [('An anti-hero is best described as a central character who ___.', ['Lacks traditional heroic qualities but still commands the reader’s attention', 'Always displays flawless moral courage', 'A concept unrelated to characterization', 'Never appears as the protagonist of a story'], 0),
   ('A braided essay interweaves ___.', ['Two or more distinct narrative threads or topics', 'Only a single, uninterrupted narrative thread', 'A concept unrelated to essay structure', 'A strictly chronological retelling of one event only'], 0),
   ('A frame narrative encloses ___.', ['One story within another', 'A single story with no additional layers', 'A concept unrelated to narrative structure', 'Only factual, non-fictional accounts'], 0),
   ('Active listening involves ___.', ['Fully concentrating on and engaging with a speaker’s message', 'Waiting silently only until it is one’s turn to speak', 'A concept unrelated to communication', 'Ignoring a speaker’s message entirely while planning a response'], 0),
   ('Why is it useful to review these varied reading, writing, and communication skills together?', ['They reinforce complementary approaches to interpreting and producing texts effectively', 'These skills have no connection to each other', 'Review is never useful for English language skills', 'Each skill must be studied with no connection to the others'], 0)]),
F('Review: Equations, Trigonometry, and Discrete Mathematics',
  'Grade 11 Functions strand review: this lesson revisits exponential and logarithmic equations, rational inequalities, the sine and cosine laws, mathematical induction, radical equations, sampling methods, linear-quadratic systems, and function symmetry.',
  [('To solve an equation like 2 to the power of x equals 8 using logarithms, a useful first step is to ___.', ['Take the logarithm of both sides of the equation', 'Add 8 to both sides of the equation', 'A step unrelated to solving exponential equations', 'Divide both sides by the base immediately with no other steps'], 0),
   ('A rational inequality involves an expression with a variable in the ___.', ['Denominator', 'Exponent only, with no connection to a denominator', 'A concept unrelated to rational inequalities', 'Numerator only, with no connection to fractions'], 0),
   ('Mathematical induction is a method used to prove a statement is true for ___.', ['All natural numbers', 'Only a single specific number', 'A concept unrelated to proof techniques', 'No numbers at all'], 0),
   ('A function is classified as even if its graph is symmetric about the ___.', ['Y-axis', 'X-axis, with no connection to the y-axis', 'A concept unrelated to symmetry', 'Origin exclusively, with no connection to the y-axis'], 0),
   ('Why is it useful to review equations, trigonometry, and discrete mathematics together?', ['It reinforces how these mathematical tools and reasoning skills connect and build on one another', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
B('Review: Systems, Senses, and Evolutionary History',
  'Grade 11 Biology strand review: this lesson revisits the lymphatic system, osmosis and cell transport, circadian rhythms, vision and the eye, the integumentary system, antibiotic resistance, animal reproduction, animal migration, and the history of evolutionary theory.',
  [('The lymphatic system’s primary role in fluid balance is to ___.', ['Return excess interstitial fluid to the bloodstream', 'Pump blood directly through the heart', 'A role entirely unrelated to fluid balance', 'Remove all fluid from the body permanently'], 0),
   ('A circadian rhythm is best described as an internal biological cycle that repeats roughly every ___.', ['24 hours', '24 minutes', 'A time period unrelated to circadian rhythms', '24 days'], 0),
   ('Antibiotic resistance is often described as a clear real-world example of ___.', ['Natural selection acting on a microbial population', 'A process entirely unrelated to evolutionary biology', 'A random event with no connection to survival or reproduction', 'A phenomenon that never occurs in bacterial populations'], 0),
   ('Charles Darwin and Alfred Russel Wallace independently developed the theory of ___.', ['Evolution by natural selection', 'A theory entirely unrelated to evolution', 'The immediate creation of every species with no change over time', 'A concept unrelated to the history of biology'], 0),
   ('Why is it useful to review body systems, sensory biology, and evolutionary history together?', ['It reinforces how these interconnected biological concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in biology', 'Each topic must be studied with no connection to the others'], 0)]),
C('Review: Bonding, Separation, and Applied Chemistry',
  'Grade 11 Chemistry strand review: this lesson revisits inorganic nomenclature, metallic bonding and alloys, chromatography, crystal lattice types, amines, colloids, electroplating and corrosion, mass spectrometry, and water hardness.',
  [('The systematic naming of inorganic compounds follows rules established by ___.', ['IUPAC', 'A system with no formal naming rules', 'A naming convention unrelated to chemistry', 'Random, informal common names only'], 0),
   ('Metallic bonding is best described as a lattice of positive metal ions surrounded by ___.', ['A “sea” of delocalized electrons', 'A rigid, fixed set of shared electron pairs only', 'A concept unrelated to metallic bonding', 'No electrons of any kind'], 0),
   ('Chromatography separates the components of a mixture based on ___.', ['How differently each component travels through a stationary phase', 'The colour of the mixture alone, with no other factor considered', 'A concept unrelated to separating mixtures', 'The temperature of the mixture exclusively'], 0),
   ('Water hardness is primarily caused by dissolved ___ ions.', ['Calcium and magnesium', 'Sodium and potassium exclusively, with no connection to hardness', 'A type of ion unrelated to water hardness', 'Chloride ions exclusively, with no connection to hardness'], 0),
   ('Why is it useful to review bonding, separation techniques, and applied chemistry together?', ['It reinforces how these interconnected chemistry concepts relate to one another', 'These topics have no connection to each other', 'Review is never useful in chemistry', 'Each topic must be studied with no connection to the others'], 0)])]),
]

def _rebalance_answer_positions(days, seed=20260806):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g11_51_60)
    append_to(11, g11_51_60)
