#!/usr/bin/env python3
"""Grade 2 standalone optional-worksheet content -- Project Plan item 8.

This is a NEW, separate content pipeline from data/grade2.ts (the 187-day
lesson sequence). It generates data/grade2_worksheets.ts: 10 worksheets per
subject x 4 subjects (Language, Math, Science, SocialStudies) = 40
worksheets, exactly 15 multiple-choice questions each (Grade 2 uses mc()
only, per gen_worksheets.py -- grades 2-12 are multiple choice, only K/1
are free-response).

Structural note: modeled loosely on gen_grade2_days181_187.py for coding
style (helpers, a rebalance pass for answer-position bias, if __main__
entry point), but the schema here is worksheet(subject, number, title,
questions) from gen_worksheets.py, not the day-based sub()/day() schema.

Each subject's 10 worksheets are organized around 10 distinct practice
themes/strands spanning the Grade 2 curriculum, roughly foundational to
more advanced. These are supplementary practice worksheets -- overlap with
topics already covered across the 187 days is expected and fine, per the
Project Plan item 8 scope.

Content is authored with the correct answer always written first in each
option list; _rebalance() below reshuffles each worksheet's 15 answers
across index positions 0-3 (roughly 4/4/4/3) using a seeded RNG, so no
worksheet or subject is biased toward one answer letter.

No embedded straight double-quotes or apostrophes anywhere -- contractions
and possessives are avoided/rewritten throughout (e.g. "does not" not
"doesnt", "of Canada" not "Canadas"), matching the hard rule enforced by
mc()/worksheet() in gen_worksheets.py.
"""
import random
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_worksheets import mc, worksheet, write_worksheets

RNG_SEED = 20260820


def _rebalance_worksheet(title, raw_questions, rng):
    """raw_questions: list of (qtext, [correct, wrong1, wrong2, wrong3]).
    Shuffles each question options so the correct answer lands in a
    varied index (0-3), distributed evenly across the worksheet 15
    questions, and returns a list of mc(...) question tuples."""
    assert len(raw_questions) == 15, f'{title!r}: expected 15 raw questions, got {len(raw_questions)}'
    n = len(raw_questions)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    out = []
    for (qtext, opts), target in zip(raw_questions, targets):
        assert len(opts) == 4, f'{title!r}: {qtext!r} needs exactly 4 options'
        correct = opts[0]
        wrong = opts[1:]
        rng.shuffle(wrong)
        new_opts = [None, None, None, None]
        new_opts[target] = correct
        wi = 0
        for slot in range(4):
            if new_opts[slot] is None:
                new_opts[slot] = wrong[wi]
                wi += 1
        out.append(mc(qtext, new_opts, target))
    return out


def build_subject(subject_key, themed_worksheets, rng):
    out = []
    for i, (title, raw_questions) in enumerate(themed_worksheets, 1):
        questions = _rebalance_worksheet(title, raw_questions, rng)
        out.append(worksheet(subject_key, i, title, questions))
    return out


MATH = [
('Counting and Number Sense to 100', [
    ('What number comes right after 47?', ['48', '46', '49', '57']),
    ('What number comes right before 90?', ['89', '91', '88', '80']),
    ('Which of these numbers is greater, 62 or 26?', ['62', '26', 'They are equal', 'Cannot be compared']),
    ('What is the missing number in the pattern 30, 40, __, 60?', ['50', '45', '55', '35']),
    ('Which of these numbers is an even number?', ['24', '25', '27', '29']),
    ('Which of these numbers is an odd number?', ['33', '32', '30', '38']),
    ('What number is 10 more than 45?', ['55', '35', '46', '44']),
    ('What number is 10 less than 72?', ['62', '82', '71', '73']),
    ('Which number has a 5 in the tens place?', ['58', '85', '15', '5']),
    ('How many tens are in the number 90?', ['9', '0', '90', '19']),
    ('Which of these numbers is the smallest: 19, 91, 45, 54?', ['19', '91', '45', '54']),
    ('Which of these numbers is the largest: 38, 83, 58, 35?', ['83', '38', '58', '35']),
    ('Counting by ones, what number comes right after 99?', ['100', '101', '98', '90']),
    ('Which number comes between 55 and 57?', ['56', '58', '54', '50']),
    ('What number is shown by 6 tens and 3 ones?', ['63', '36', '69', '93']),
]),
('Addition Facts to 20', [
    ('What is 7 + 6?', ['13', '12', '14', '11']),
    ('What is 9 + 8?', ['17', '16', '18', '15']),
    ('What is 5 + 5?', ['10', '9', '11', '15']),
    ('What is 8 + 7?', ['15', '14', '16', '13']),
    ('What is 6 + 9?', ['15', '14', '16', '13']),
    ('What is 10 + 4?', ['14', '13', '15', '40']),
    ('What is 3 + 8?', ['11', '10', '12', '9']),
    ('What is 12 + 5?', ['17', '16', '18', '15']),
    ('What is 9 + 9?', ['18', '17', '19', '16']),
    ('What is 4 + 13?', ['17', '16', '18', '15']),
    ('What number added to 6 makes 14?', ['8', '7', '9', '6']),
    ('What is 11 + 6?', ['17', '16', '18', '15']),
    ('What is 15 + 3?', ['18', '17', '19', '16']),
    ('What is 2 + 17?', ['19', '18', '20', '17']),
    ('What is 7 + 7?', ['14', '13', '15', '12']),
]),
('Subtraction Facts to 20', [
    ('What is 15 - 7?', ['8', '7', '9', '6']),
    ('What is 18 - 9?', ['9', '8', '10', '7']),
    ('What is 12 - 5?', ['7', '6', '8', '5']),
    ('What is 20 - 8?', ['12', '11', '13', '10']),
    ('What is 14 - 6?', ['8', '7', '9', '6']),
    ('What is 16 - 9?', ['7', '6', '8', '5']),
    ('What is 11 - 4?', ['7', '6', '8', '5']),
    ('What is 19 - 10?', ['9', '8', '10', '7']),
    ('What is 13 - 5?', ['8', '7', '9', '6']),
    ('What is 17 - 8?', ['9', '8', '10', '7']),
    ('What number subtracted from 14 leaves 6?', ['8', '7', '9', '6']),
    ('What is 10 - 3?', ['7', '6', '8', '5']),
    ('What is 20 - 12?', ['8', '7', '9', '6']),
    ('What is 9 - 4?', ['5', '4', '6', '3']),
    ('What is 18 - 11?', ['7', '6', '8', '5']),
]),
('Place Value: Tens and Ones', [
    ('In the number 47, what digit is in the tens place?', ['4', '7', '40', '47']),
    ('In the number 47, what digit is in the ones place?', ['7', '4', '70', '47']),
    ('What number has 5 tens and 2 ones?', ['52', '25', '502', '50']),
    ('What number has 3 tens and 9 ones?', ['39', '93', '30', '9']),
    ('How many ones are in 8 tens?', ['0', '8', '80', '18']),
    ('What is 30 + 4 written as one number?', ['34', '43', '304', '340']),
    ('What is 60 + 7 written as one number?', ['67', '76', '607', '670']),
    ('In the number 82, what does the 8 represent?', ['8 tens', '8 ones', '8 hundreds', '8 units only']),
    ('Which number has the same number of tens and ones?', ['55', '45', '54', '65']),
    ('What number is formed by 9 tens and 0 ones?', ['90', '9', '900', '19']),
    ('Which is greater, a number with 6 tens or a number with 4 tens, if the ones digits match?', ['The one with 6 tens', 'The one with 4 tens', 'They are always equal', 'Cannot be determined']),
    ('What is the value of the 3 in the number 73?', ['3 tens, or 30', '3 ones, or 3', '3 hundreds', '30 tens']),
    ('What is the value of the 7 in the number 73?', ['7 tens, or 70', '7 ones, or 7', '7 hundreds', '700']),
    ('How many tens are in the number 100?', ['10', '1', '100', '0']),
    ('Which number below has a 0 in the ones place?', ['40', '44', '4', '14']),
]),
('Skip Counting by 2s, 5s, and 10s', [
    ('Skip counting by 2s, what comes after 8?', ['10', '9', '12', '11']),
    ('Skip counting by 5s, what comes after 15?', ['20', '25', '18', '16']),
    ('Skip counting by 10s, what comes after 40?', ['50', '45', '60', '41']),
    ('Which set of numbers shows counting by 2s?', ['2, 4, 6, 8', '2, 4, 8, 10', '1, 2, 3, 4', '2, 5, 8, 11']),
    ('Which set of numbers shows counting by 5s?', ['5, 10, 15, 20', '5, 6, 7, 8', '5, 15, 20, 30', '2, 5, 10, 15']),
    ('Which set of numbers shows counting by 10s?', ['10, 20, 30, 40', '10, 15, 20, 25', '1, 10, 100, 1000', '10, 12, 14, 16']),
    ('If you skip count by 2s starting at 1, which numbers do you say?', ['1, 3, 5, 7', '2, 4, 6, 8', '1, 2, 3, 4', '1, 4, 7, 10']),
    ('Skip counting by 5s from 0, what is the fifth number said?', ['25', '20', '30', '15']),
    ('Skip counting by 10s from 0, what is the sixth number said?', ['60', '50', '70', '100']),
    ('Which is faster for reaching 100, counting by 1s or by 10s?', ['Counting by 10s', 'Counting by 1s', 'They take the same time', 'Neither can reach 100']),
    ('What number comes two steps after 6 when counting by 2s?', ['10', '8', '12', '9']),
    ('What number comes two steps after 20 when counting by 5s?', ['30', '25', '35', '22']),
    ('What number comes two steps after 50 when counting by 10s?', ['70', '60', '80', '52']),
    ('Skip counting by 2s starting at 2, would you ever say 17?', ['No, 17 is odd', 'Yes, always', 'Only on the third try', 'Cannot tell']),
    ('Skip counting by 10s starting at 5, which of these would you say?', ['25', '20', '22', '30']),
]),
('Telling Time to the Hour and Half Hour', [
    ('When the minute hand points to 12 and the hour hand points to 3, what time is shown?', ['3:00', '12:00', '3:30', '12:03']),
    ('When the minute hand points to the 6, how many minutes past the hour is it?', ['30 minutes', '15 minutes', '45 minutes', '6 minutes']),
    ('What is another way to say 4:30?', ['Half past four', 'Quarter past four', 'Fifteen minutes past four', 'Four in the evening only']),
    ('How many minutes are in one full hour?', ['60', '30', '12', '100']),
    ('How many minutes are in half an hour?', ['30', '60', '15', '45']),
    ('On a clock, which hand is shorter, the hour hand or the minute hand?', ['The hour hand', 'The minute hand', 'They are the same length', 'Neither hand is shorter']),
    ('If it is 2:00 now, what time will it be in one hour?', ['3:00', '1:00', '2:30', '4:00']),
    ('If it is 5:30 now, what time will it be in half an hour?', ['6:00', '5:00', '6:30', '5:45']),
    ('How many hours are shown on the face of a standard clock?', ['12', '24', '60', '10']),
    ('At what time does the hour hand point exactly at the 8 and the minute hand point exactly at the 12?', ['8:00', '12:00', '8:30', '12:08']),
    ('If the hour hand is halfway between 6 and 7, and the minute hand points to 6, what time is it?', ['6:30', '6:00', '7:00', '7:30']),
    ('Which time comes first in the same morning, 7:00 or 9:00?', ['7:00', '9:00', 'They happen at the same time', 'Cannot be determined']),
    ('How many minutes past the hour is quarter past?', ['15 minutes', '30 minutes', '45 minutes', '5 minutes']),
    ('What time is quarter past 2?', ['2:15', '2:30', '2:45', '2:05']),
    ('What time is quarter to 3, meaning 15 minutes before 3?', ['2:45', '3:15', '2:15', '3:45']),
]),
('Money: Coins and Bills', [
    ('How many cents is a nickel worth?', ['5 cents', '1 cent', '10 cents', '25 cents']),
    ('How many cents is a dime worth?', ['10 cents', '5 cents', '25 cents', '1 cent']),
    ('How many cents is a quarter worth?', ['25 cents', '10 cents', '5 cents', '50 cents']),
    ('How many cents is a penny worth?', ['1 cent', '5 cents', '10 cents', '25 cents']),
    ('How many pennies equal one nickel?', ['5', '10', '1', '25']),
    ('How many nickels equal one quarter?', ['5', '4', '10', '2']),
    ('How many dimes equal one dollar?', ['10', '5', '100', '4']),
    ('What is the total value of 2 dimes and 1 nickel?', ['25 cents', '20 cents', '15 cents', '30 cents']),
    ('What is the total value of 3 quarters?', ['75 cents', '50 cents', '100 cents', '60 cents']),
    ('How many cents make one dollar?', ['100 cents', '10 cents', '50 cents', '1000 cents']),
    ('Which coin is worth more, a dime or a nickel?', ['A dime', 'A nickel', 'They are equal', 'Neither has value']),
    ('If you have 1 quarter and 2 dimes, how much money do you have?', ['45 cents', '35 cents', '50 cents', '40 cents']),
    ('What is the value of 4 nickels and 1 dime?', ['30 cents', '25 cents', '35 cents', '20 cents']),
    ('Which Canadian bill shows a value of five dollars?', ['The five dollar bill', 'The ten dollar bill', 'The one dollar coin', 'The twenty dollar bill']),
    ('If an item costs 40 cents and you pay with 2 quarters, how much change should you get back?', ['10 cents', '15 cents', '5 cents', '20 cents']),
]),
('Measurement: Length and Mass', [
    ('Which unit would you use to measure the length of a pencil?', ['Centimetres', 'Kilograms', 'Litres', 'Hours']),
    ('Which unit would you use to measure how heavy a bag of apples is?', ['Kilograms', 'Centimetres', 'Metres', 'Minutes']),
    ('Which tool is used to measure length?', ['A ruler', 'A clock', 'A scale for weight only', 'A thermometer']),
    ('Which tool is used to measure mass, or how heavy something is?', ['A balance scale', 'A ruler', 'A clock', 'A measuring cup']),
    ('Which of these is longer, 1 metre or 1 centimetre?', ['1 metre', '1 centimetre', 'They are the same', 'Cannot be compared']),
    ('About how many centimetres long is a small paperclip?', ['About 3 centimetres', 'About 30 centimetres', 'About 3 metres', 'About 300 centimetres']),
    ('Which object is likely heavier, a feather or a brick?', ['A brick', 'A feather', 'They weigh the same', 'Neither has mass']),
    ('If a pencil is 15 centimetres long, what unit are we using?', ['Centimetres', 'Kilograms', 'Litres', 'Degrees']),
    ('Which of these would best be measured in metres rather than centimetres?', ['The length of a hallway', 'The length of an eraser', 'The width of a coin', 'The length of an ant']),
    ('What does it mean to estimate a measurement?', ['To make a careful guess before measuring exactly', 'To measure with no tools at all', 'To always be exactly correct', 'To ignore the object completely']),
    ('Which unit measures how heavy an object is?', ['Mass', 'Length', 'Time', 'Colour']),
    ('If Object A is heavier than Object B on a balance scale, which side of the scale goes down?', ['The side with Object A', 'The side with Object B', 'Neither side moves', 'Both sides go down equally']),
    ('About how long is a standard classroom ruler?', ['About 30 centimetres', 'About 3 centimetres', 'About 300 centimetres', 'About 3 metres']),
    ('Which is a better estimate for the length of a school bus, 12 metres or 12 centimetres?', ['12 metres', '12 centimetres', '12 kilograms', '12 litres']),
    ('When comparing the mass of two objects, what does a balance scale help you determine?', ['Which object is heavier or lighter', 'Which object is longer', 'Which object is a brighter colour', 'Which object is older']),
]),
('2D and 3D Shapes', [
    ('How many sides does a triangle have?', ['3', '4', '5', '6']),
    ('How many sides does a rectangle have?', ['4', '3', '5', '6']),
    ('How many corners, or vertices, does a square have?', ['4', '3', '5', '0']),
    ('Which shape has no straight sides at all?', ['A circle', 'A triangle', 'A square', 'A rectangle']),
    ('How many faces does a cube have?', ['6', '4', '8', '12']),
    ('How many flat faces does a sphere have?', ['0', '6', '4', '1']),
    ('What shape are all the faces of a cube?', ['Squares', 'Circles', 'Triangles', 'Rectangles that are not square']),
    ('How many edges does a cube have?', ['12', '6', '8', '4']),
    ('Which of these is a 3D shape?', ['A cone', 'A circle', 'A square', 'A triangle']),
    ('Which of these is a 2D shape?', ['A rectangle', 'A cube', 'A sphere', 'A cylinder']),
    ('How many vertices, or corners, does a cube have?', ['8', '6', '12', '4']),
    ('Which shape looks like a can of soup?', ['A cylinder', 'A cube', 'A cone', 'A sphere']),
    ('Which shape has exactly one flat circular face and comes to a point?', ['A cone', 'A cylinder', 'A cube', 'A sphere']),
    ('How many sides does a pentagon have?', ['5', '4', '6', '3']),
    ('What is the difference between a 2D shape and a 3D shape?', ['A 3D shape has depth or thickness, a 2D shape is flat', 'A 2D shape is always bigger', 'A 3D shape has no corners', 'There is no difference between them']),
]),
('Fractions: Halves, Thirds, and Quarters', [
    ('If a pizza is cut into 2 equal pieces, what is each piece called?', ['One half', 'One third', 'One quarter', 'One whole']),
    ('If a pizza is cut into 4 equal pieces, what is each piece called?', ['One quarter', 'One half', 'One third', 'Two halves']),
    ('If a pizza is cut into 3 equal pieces, what is each piece called?', ['One third', 'One quarter', 'One half', 'One fifth']),
    ('How many halves make one whole?', ['2', '3', '4', '1']),
    ('How many quarters make one whole?', ['4', '2', '3', '8']),
    ('How many thirds make one whole?', ['3', '2', '4', '6']),
    ('Which fraction shows one half?', ['1 out of 2 equal parts', '1 out of 4 equal parts', '1 out of 3 equal parts', '2 out of 2 equal parts']),
    ('If you eat one quarter of a sandwich, how much is left?', ['Three quarters', 'One half', 'One third', 'The whole sandwich']),
    ('Which is larger, one half or one quarter of the same whole?', ['One half', 'One quarter', 'They are equal', 'Cannot be compared']),
    ('Which is larger, one third or one half of the same whole?', ['One half', 'One third', 'They are equal', 'Cannot be compared']),
    ('If a chocolate bar is split into 2 equal parts and you take 1 part, what fraction did you take?', ['One half', 'One third', 'One quarter', 'Two halves']),
    ('For a fraction to be fair, what must the parts be?', ['Equal in size', 'Different colours', 'Different sizes', 'Cut by an adult only']),
    ('If you have 4 equal parts of a shape and colour 2 of them, what fraction is coloured?', ['One half', 'One quarter', 'One third', 'Two thirds']),
    ('Which shows three out of four equal parts?', ['Three quarters', 'One quarter', 'One half', 'Two thirds']),
    ('If a group of 3 friends shares one sandwich equally, what fraction does each friend get?', ['One third', 'One half', 'One quarter', 'One whole']),
]),
]

LANGUAGE = [
('Letter Sounds and the Alphabet', [
    ('How many letters are in the English alphabet?', ['26', '24', '20', '30']),
    ('Which letter comes right after G in the alphabet?', ['H', 'F', 'I', 'J']),
    ('Which letter comes right before M in the alphabet?', ['L', 'N', 'K', 'O']),
    ('Which of these letters is a vowel?', ['E', 'B', 'C', 'D']),
    ('Which of these letters is a consonant?', ['T', 'A', 'E', 'O']),
    ('How many vowels are in the English alphabet?', ['5', '3', '7', '10']),
    ('Which letter makes the first sound in the word sun?', ['S', 'T', 'U', 'N']),
    ('Which letter makes the last sound in the word cat?', ['T', 'C', 'A', 'K']),
    ('Which word begins with the same sound as ball?', ['Bike', 'Cake', 'Fish', 'Dog']),
    ('Which letter is missing in c_t if the word means a small animal that says meow?', ['A', 'E', 'I', 'O']),
    ('Put these letters in alphabetical order: D, A, C, B.', ['A, B, C, D', 'D, C, B, A', 'B, A, D, C', 'C, B, A, D']),
    ('Which letter usually makes a buzzing sound, like in the word zebra?', ['Z', 'S', 'X', 'J']),
    ('Which of these words starts with a vowel sound?', ['Apple', 'Table', 'Mouse', 'Zebra']),
    ('How many letters are in the word dog?', ['3', '2', '4', '5']),
    ('Which letter comes at the very end of the alphabet?', ['Z', 'Y', 'A', 'X']),
]),
('Sight Words and Simple Sentences', [
    ('Which word correctly completes: I ___ to the park.', ['went', 'goed', 'going', 'gone']),
    ('Which word means the opposite of down in: I climbed ___ the ladder.', ['up', 'down', 'left', 'slow']),
    ('Which of these is a complete sentence?', ['The dog runs fast.', 'Running fast dog.', 'Fast the dog.', 'Dog fast running.']),
    ('Which word fits best: She ___ a red hat.', ['has', 'is', 'am', 'be']),
    ('Which sight word means the same as a female person who is your parent?', ['mother', 'father', 'brother', 'sister']),
    ('Which word completes the sentence: They ___ playing outside.', ['are', 'am', 'is', 'be']),
    ('Which of these words is a common sight word taught in early grades?', ['said', 'elephant', 'dinosaur', 'umbrella']),
    ('Which word correctly completes: We saw ___ birds in the tree.', ['three', 'tree', 'free', 'there']),
    ('Choose the sentence that is written correctly.', ['The sun is bright today.', 'sun the bright is today', 'Bright today the sun is', 'Today bright the is sun']),
    ('Which word means the same as big?', ['large', 'tiny', 'small', 'short']),
    ('Which word best completes: This is ___ favourite book.', ['my', 'I', 'me', 'we']),
    ('Which of these words is spelled correctly?', ['because', 'becaus', 'becuase', 'becase']),
    ('Which word completes: Can you ___ me with this?', ['help', 'helps', 'helping', 'helped']),
    ('Which sentence asks a question?', ['Where is my book?', 'My book is here.', 'I found my book.', 'Put the book down.']),
    ('Which word means more than one dog?', ['dogs', 'dog', 'doged', 'dogss']),
]),
('Nouns and Verbs', [
    ('What is a noun?', ['A word that names a person, place, or thing', 'A word that shows action', 'A word that describes a noun', 'A word that joins sentences']),
    ('What is a verb?', ['A word that shows action', 'A word that names a thing', 'A word that describes a colour', 'A word that names a place only']),
    ('Which word in this list is a noun?', ['table', 'run', 'jump', 'quickly']),
    ('Which word in this list is a verb?', ['swim', 'dog', 'school', 'pencil']),
    ('In the sentence The boy kicks the ball, which word is the verb?', ['kicks', 'boy', 'the', 'ball']),
    ('In the sentence The cat sleeps on the mat, which word is a noun?', ['cat', 'sleeps', 'on', 'the']),
    ('Which of these words names a place?', ['school', 'jump', 'happy', 'fast']),
    ('Which of these words names a person?', ['teacher', 'swim', 'blue', 'slowly']),
    ('Which sentence has a verb showing action?', ['The bird flies high.', 'The bird is blue.', 'The bird sat still.', 'The bird has feathers.']),
    ('Which word below can be used as a noun for a container?', ['box', 'run', 'happy', 'quick']),
    ('In the sentence Sara reads a book, what is the noun that receives the action?', ['book', 'Sara', 'reads', 'a']),
    ('Which word below is a verb that means to move quickly on foot?', ['run', 'chair', 'window', 'soft']),
    ('Which sentence is missing a verb?', ['The dog the yard.', 'The dog runs in the yard.', 'The dog barks loudly.', 'The dog sleeps quietly.']),
    ('Which of these is a noun that names a thing, not a person or place?', ['pencil', 'teacher', 'park', 'doctor']),
    ('In the sentence Birds fly south in winter, which word is the verb?', ['fly', 'Birds', 'south', 'winter']),
]),
('Adjectives and Describing Words', [
    ('What is an adjective?', ['A word that describes a noun', 'A word that shows action', 'A word that names a place', 'A word that joins two sentences']),
    ('Which word describes the size of an object?', ['huge', 'run', 'quickly', 'jump']),
    ('In the sentence The tall tree swayed, which word is the adjective?', ['tall', 'tree', 'swayed', 'the']),
    ('Which word describes how something tastes?', ['sweet', 'run', 'jump', 'fast']),
    ('Which of these words describes a colour?', ['green', 'run', 'talk', 'sit']),
    ('Which sentence uses an adjective to describe the dog?', ['The fluffy dog barked.', 'The dog barked loudly.', 'The dog is a dog.', 'Dog the barked fluffy.']),
    ('Which word could describe how a person feels?', ['happy', 'table', 'jump', 'chair']),
    ('Which word describes the shape of an object?', ['round', 'quickly', 'softly', 'happily']),
    ('In the sentence She wore a bright yellow dress, which words are adjectives?', ['bright and yellow', 'wore and dress', 'she and a', 'dress and she']),
    ('Which word means the opposite of small?', ['large', 'tiny', 'short', 'little']),
    ('Which word best describes how loud a sound is?', ['loud', 'square', 'cold', 'fast']),
    ('Which word describes the texture of a rock?', ['rough', 'quickly', 'happily', 'loudly']),
    ('In the sentence The tiny kitten slept, which word describes the kitten?', ['tiny', 'kitten', 'slept', 'the']),
    ('Which word would best describe a very cold day?', ['freezing', 'warm', 'hot', 'mild']),
    ('Which sentence uses two adjectives to describe the same noun?', ['The big red balloon floated away.', 'The balloon floated away.', 'It floated away quickly.', 'Away floated the balloon.']),
]),
('Sentence Types and End Punctuation', [
    ('What punctuation mark ends a statement sentence?', ['A period', 'A question mark', 'An exclamation mark', 'A comma']),
    ('What punctuation mark ends a question?', ['A question mark', 'A period', 'An exclamation mark', 'A comma']),
    ('What punctuation mark shows strong feeling or excitement?', ['An exclamation mark', 'A period', 'A question mark', 'A comma']),
    ('Which of these sentences is a question?', ['Where did you put my shoes?', 'I put my shoes here.', 'My shoes are here.', 'Put your shoes here.']),
    ('Which of these sentences is a statement?', ['The sky is blue.', 'Is the sky blue?', 'Look at the sky!', 'Blue sky look.']),
    ('Which of these sentences shows excitement?', ['Watch out for that ball!', 'The ball is round.', 'Where is the ball?', 'The ball rolled away.']),
    ('Every sentence should begin with what kind of letter?', ['A capital letter', 'A lowercase letter', 'A number', 'A symbol']),
    ('Which sentence is punctuated correctly?', ['I like apples.', 'i like apples.', 'I like apples', 'i like Apples']),
    ('Which sentence correctly asks a question?', ['Do you like pizza?', 'Do you like pizza.', 'do you like pizza', 'Do You like pizza!']),
    ('A sentence that gives a command, like Close the door, usually ends with what?', ['A period', 'A question mark', 'An exclamation mark only', 'No punctuation at all']),
    ('Which of these is written as a complete sentence with correct end punctuation?', ['The rain fell all day.', 'the rain fell all day', 'The rain fell all day', 'Rain the fell all day.']),
    ('Which punctuation mark would best end the sentence: What is your name', ['A question mark', 'A period', 'An exclamation mark', 'A comma']),
    ('Which sentence uses an exclamation mark correctly?', ['That was amazing!', 'That was amazing.', 'That was amazing?', 'That, was amazing']),
    ('What is the purpose of end punctuation in a sentence?', ['To show how the sentence should be read or understood', 'To make the sentence longer', 'To replace all the nouns', 'To remove capital letters']),
    ('Which sentence type tells the reader something is happening, without asking or showing excitement?', ['A statement', 'A question', 'An exclamation', 'A command only']),
]),
('Rhyming Words and Word Families', [
    ('Which word rhymes with cat?', ['hat', 'dog', 'run', 'sit']),
    ('Which word rhymes with light?', ['night', 'lamp', 'dark', 'sun']),
    ('Which word rhymes with train?', ['rain', 'truck', 'boat', 'car']),
    ('Which word belongs to the same word family as hop, top, and mop?', ['pop', 'run', 'sit', 'jump']),
    ('Which word belongs to the same word family as cake, lake, and make?', ['bake', 'dog', 'tree', 'book']),
    ('Which word does not rhyme with the others: bee, tree, see, dog?', ['dog', 'bee', 'tree', 'see']),
    ('Which word rhymes with star?', ['car', 'sun', 'moon', 'sky']),
    ('Which word rhymes with blue?', ['shoe', 'red', 'green', 'sky']),
    ('Which pair of words rhymes?', ['frog and log', 'frog and cat', 'frog and dog', 'frog and pig']),
    ('Which word rhymes with day?', ['play', 'night', 'dark', 'sun']),
    ('In the -at word family, which word fits?', ['bat', 'bet', 'bit', 'but']),
    ('In the -og word family, which word fits?', ['dog', 'dig', 'dug', 'dag']),
    ('Which word rhymes with snow?', ['grow', 'sun', 'rain', 'tree']),
    ('Which two of these three words rhyme: bug, jug, cat?', ['bug and jug', 'bug and cat', 'jug and cat', 'none of them rhyme']),
    ('Which word rhymes with tree?', ['bee', 'sun', 'moon', 'star']),
]),
('Story Elements: Character, Setting, Plot', [
    ('Who is a character in a story?', ['A person or animal that the story is about', 'The place where the story happens', 'The lesson the story teaches', 'The title of the story']),
    ('What is the setting of a story?', ['The time and place where the story happens', 'The main character', 'The problem in the story', 'The final sentence']),
    ('What is the plot of a story?', ['The sequence of events that happen', 'The cover of the book', 'The name of the author', 'The setting only']),
    ('What is usually the main problem in a story called?', ['The conflict', 'The setting', 'The title', 'The author']),
    ('What happens at the end of most stories, when the problem is solved?', ['The resolution', 'The setting', 'The introduction', 'The title']),
    ('Which of these best describes a setting?', ['A forest at nighttime', 'A brave girl', 'A talking fox', 'A hidden treasure']),
    ('Which of these best describes a character?', ['A curious boy', 'A snowy mountain', 'A locked door', 'A rainy morning']),
    ('Why is the setting important to a story?', ['It tells readers when and where events happen', 'It has no effect on the story', 'It replaces all characters', 'It is always left out of stories']),
    ('What do we call the main character who the story mostly follows?', ['The main character, or protagonist', 'The setting', 'The plot', 'The moral']),
    ('Which part of a story usually comes first?', ['The beginning, introducing characters and setting', 'The resolution', 'The climax', 'The very last sentence']),
    ('What is a moral in a story?', ['A lesson the story teaches', 'The name of the main character', 'The setting of the story', 'The title of the book']),
    ('In a story about a lost puppy finding its way home, what is the main problem?', ['The puppy is lost', 'The puppy has fur', 'The puppy likes to play', 'The puppy has a name']),
    ('Which of these is an example of a plot event?', ['A dragon chases the knight through the forest', 'A tall green mountain', 'A cheerful young girl', 'A cold winter morning']),
    ('Why do authors create characters with different personalities?', ['To make the story more interesting and realistic', 'To make every character exactly the same', 'To confuse the reader on purpose', 'Characters do not need personalities']),
    ('What is the climax of a story?', ['The most exciting or important turning point', 'The very first sentence', 'The name of the book', 'The setting description']),
]),
('Compound Words', [
    ('What is a compound word?', ['A word made by joining two smaller words together', 'A word with only one letter', 'A word that has no meaning', 'A word that is always very short']),
    ('Which of these is a compound word?', ['sunflower', 'happy', 'quickly', 'jump']),
    ('Which two words combine to make the compound word snowman?', ['snow and man', 'sun and man', 'snow and van', 'snow and moon']),
    ('Which compound word is made from the words butter and fly?', ['butterfly', 'flybutter', 'butterflies', 'flying butter']),
    ('Which two smaller words make up the word baseball?', ['base and ball', 'bass and ball', 'base and bell', 'bat and ball']),
    ('Which of these is NOT a compound word?', ['happy', 'sunlight', 'toothbrush', 'notebook']),
    ('Which two words combine to make raincoat?', ['rain and coat', 'rain and boot', 'ran and coat', 'rain and hat']),
    ('Which compound word is made from the words class and room?', ['classroom', 'classhouse', 'roomclass', 'classdoor']),
    ('Which compound word describes a sea animal shaped like a horse?', ['seahorse', 'starfish', 'catfish', 'jellyfish']),
    ('Which two words make up the compound word football?', ['foot and ball', 'fast and ball', 'foot and bell', 'for and tall']),
    ('Which two words combine to make the compound word sunlight?', ['sun and light', 'sun and shine', 'moon and light', 'day and light']),
    ('Which two words make up the compound word bedroom?', ['bed and room', 'bed and roam', 'bad and room', 'bed and broom']),
    ('Which compound word is made from the words back and pack?', ['backpack', 'packback', 'backpacks', 'packing']),
    ('Which compound word names a house built in or near a tree?', ['treehouse', 'housetree', 'treeroom', 'roomtree']),
    ('Which two words combine to make the word rainbow?', ['rain and bow', 'rain and blow', 'ran and bow', 'rain and bowl']),
]),
('Synonyms and Antonyms', [
    ('What is a synonym?', ['A word that means almost the same as another word', 'A word that means the opposite of another word', 'A word that rhymes with another word', 'A word with no meaning']),
    ('What is an antonym?', ['A word that means the opposite of another word', 'A word that means the same as another word', 'A word that rhymes with another word', 'A punctuation mark']),
    ('Which word is a synonym for happy?', ['glad', 'sad', 'angry', 'tired']),
    ('Which word is an antonym for hot?', ['cold', 'warm', 'boiling', 'sunny']),
    ('Which word is a synonym for big?', ['large', 'small', 'tiny', 'short']),
    ('Which word is an antonym for fast?', ['slow', 'quick', 'speedy', 'rapid']),
    ('Which word is a synonym for small?', ['tiny', 'huge', 'giant', 'large']),
    ('Which word is an antonym for up?', ['down', 'high', 'above', 'tall']),
    ('Which word is a synonym for smart?', ['clever', 'silly', 'slow', 'confused']),
    ('Which word is an antonym for happy?', ['sad', 'glad', 'cheerful', 'pleased']),
    ('Which word means almost the same as the word begin?', ['start', 'end', 'stop', 'finish']),
    ('Which word is an antonym for begin?', ['end', 'start', 'commence', 'launch']),
    ('Which word is a synonym for loud?', ['noisy', 'quiet', 'silent', 'soft']),
    ('Which word is an antonym for loud?', ['quiet', 'noisy', 'booming', 'roaring']),
    ('Which word is a synonym for tired?', ['sleepy', 'energetic', 'awake', 'active']),
]),
('Plural Nouns', [
    ('What does a plural noun show?', ['More than one person, place, or thing', 'Only one person, place, or thing', 'An action word', 'A describing word']),
    ('What is the plural of cat?', ['cats', 'cat', 'cates', 'catss']),
    ('What is the plural of box?', ['boxes', 'boxs', 'box', 'boxies']),
    ('What is the plural of dog?', ['dogs', 'doges', 'dog', 'dogies']),
    ('What is the plural of bus?', ['buses', 'bus', 'busses only', 'buss']),
    ('What is the plural of baby, changing y to i and adding es?', ['babies', 'babys', 'baby', 'babyes']),
    ('What is the plural of child?', ['children', 'childs', 'childrens', 'childes']),
    ('What is the plural of mouse, the small animal?', ['mice', 'mouses', 'mices', 'mouse']),
    ('What is the plural of foot?', ['feet', 'foots', 'feets', 'footes']),
    ('What is the plural of leaf?', ['leaves', 'leafs', 'leves', 'leafes']),
    ('Which word below is already plural?', ['children', 'child', 'mouse', 'foot']),
    ('What is the plural of glass?', ['glasses', 'glass', 'glasss', 'glasies']),
    ('Which ending is often added to make a regular noun plural?', ['s or es', 'ing', 'ed', 'ly']),
    ('What is the plural of tooth?', ['teeth', 'tooths', 'toothes', 'teeths']),
    ('What is the plural of wish?', ['wishes', 'wishs', 'wish', 'wishies']),
]),
]

SCIENCE = [
('Living and Non-Living Things', [
    ('Which of these is a living thing?', ['A tree', 'A rock', 'A chair', 'A cloud']),
    ('Which of these is a non-living thing?', ['A rock', 'A dog', 'A flower', 'A bird']),
    ('What do living things need to survive?', ['Food, water, and air', 'Only sunlight', 'Only water', 'Nothing at all']),
    ('Which of these can grow and change over time?', ['A living thing', 'A rock', 'A toy car', 'A pencil']),
    ('Do plants count as living things?', ['Yes, plants are living things', 'No, plants are not alive', 'Only animals are living things', 'Only people are living things']),
    ('Which of these is true about non-living things?', ['They do not grow or need food', 'They breathe air', 'They need water to survive', 'They can move on their own']),
    ('Which group includes only living things?', ['Dog, cat, and tree', 'Dog, rock, and cloud', 'Chair, table, and rock', 'Cloud, rain, and rock']),
    ('What is one way to tell if something is alive?', ['It can grow and reproduce', 'It is heavy', 'It is a certain colour', 'It sits still']),
    ('Which of these things can reproduce, or make more of its own kind?', ['A rabbit', 'A rock', 'A bicycle', 'A book']),
    ('Is water alive?', ['No, water is non-living', 'Yes, water grows', 'Yes, water breathes', 'Yes, water needs food']),
    ('Which of these needs sunlight to make its own food?', ['A green plant', 'A rock', 'A car', 'A shoe']),
    ('Which of these is an example of a living thing changing over its life?', ['A puppy growing into a dog', 'A rock staying the same shape', 'A toy staying on a shelf', 'A book staying closed']),
    ('Which of these is NOT something all living things need?', ['Money', 'Water', 'Air', 'Food']),
    ('Which of these best describes a non-living thing like a rock?', ['It does not grow, move, or need food', 'It grows taller each year', 'It needs food to survive', 'It can have babies']),
    ('Which sentence is true?', ['All animals and plants are living things', 'Only animals are living things', 'Only plants are living things', 'Nothing outside is living']),
]),
('Animal Life Cycles and Growth', [
    ('What is a life cycle?', ['The stages an animal goes through as it grows and changes', 'A type of food animals eat', 'A place where animals live', 'A tool used to study animals']),
    ('What comes first in the life cycle of a frog?', ['Egg', 'Tadpole', 'Frog', 'Froglet']),
    ('What is a baby frog called before it grows legs?', ['Tadpole', 'Caterpillar', 'Cub', 'Chick']),
    ('What does a caterpillar turn into after it forms a chrysalis?', ['A butterfly', 'A frog', 'A bird', 'A fish']),
    ('What is the correct order of a butterfly life cycle?', ['Egg, caterpillar, chrysalis, butterfly', 'Butterfly, egg, caterpillar, chrysalis', 'Chrysalis, egg, butterfly, caterpillar', 'Caterpillar, butterfly, egg, chrysalis']),
    ('What is a baby dog called?', ['A puppy', 'A kitten', 'A cub', 'A calf']),
    ('What is a baby cat called?', ['A kitten', 'A puppy', 'A cub', 'A chick']),
    ('What is a baby cow called?', ['A calf', 'A kitten', 'A puppy', 'A cub']),
    ('What is a baby chicken called?', ['A chick', 'A duckling', 'A kitten', 'A cub']),
    ('How do most mammals grow when they are born?', ['They drink milk from their mother', 'They start eating solid food right away', 'They hatch from an egg outside a nest', 'They can fly immediately']),
    ('Which animal hatches from an egg?', ['A chicken', 'A dog', 'A cat', 'A cow']),
    ('What happens to a tadpole as it grows into a frog?', ['It grows legs and loses its tail', 'It grows a shell', 'It grows wings', 'It grows fur']),
    ('Why do animals go through a life cycle?', ['To grow, change, and eventually have their own young', 'To stay exactly the same forever', 'To turn into a different kind of animal', 'To avoid growing at all']),
    ('Which of these shows a life cycle stage of a plant?', ['Seed, then sprout, then adult plant', 'Egg, then tadpole, then frog', 'Caterpillar, then chrysalis, then butterfly', 'Puppy, then dog']),
    ('What is the young stage of a butterfly called, right after it hatches from an egg?', ['Caterpillar', 'Chrysalis', 'Cocoon only', 'Adult']),
]),
('Habitats and Animal Needs', [
    ('What is a habitat?', ['The natural place where an animal lives', 'A type of food', 'A tool for building', 'A season of the year']),
    ('Which habitat would a polar bear most likely live in?', ['A cold arctic habitat', 'A hot desert', 'A rainforest', 'A city park']),
    ('Which habitat would a camel most likely live in?', ['A hot desert', 'A cold arctic', 'A deep ocean', 'A rainy forest']),
    ('What do animals need from their habitat to survive?', ['Food, water, shelter, and space', 'Only shelter', 'Only food', 'Nothing at all']),
    ('Which of these is an example of a water habitat?', ['A pond', 'A desert', 'A mountain top', 'A city street']),
    ('Why might an animal struggle to survive if its habitat is destroyed?', ['It may lose its food, water, and shelter', 'It will grow bigger and stronger', 'It will not be affected at all', 'It will find money to buy food']),
    ('Which animal is well suited to living in a forest habitat?', ['A deer', 'A shark', 'A camel', 'A polar bear']),
    ('What do we call an animal that eats only plants?', ['A herbivore', 'A carnivore', 'An omnivore', 'A predator']),
    ('What do we call an animal that eats only meat?', ['A carnivore', 'A herbivore', 'An omnivore', 'A scavenger only']),
    ('What do we call an animal that eats both plants and meat?', ['An omnivore', 'A herbivore', 'A carnivore', 'A producer']),
    ('Which of these is a shelter that an animal might use in the wild?', ['A den or burrow', 'A shopping mall', 'A car', 'A classroom']),
    ('Why do some animals migrate, or travel long distances?', ['To find better food, water, or weather', 'To stay in one place forever', 'To avoid all other animals', 'To grow a new habitat']),
    ('Which of these habitats would have the least amount of water?', ['A desert', 'A pond', 'An ocean', 'A rainforest']),
    ('What might happen if an animal habitat has too little food for all the animals living there?', ['Some animals may need to move or struggle to survive', 'All animals will immediately be fine', 'The habitat will grow more animals automatically', 'Nothing will change']),
    ('Which of these best describes why habitats are important to protect?', ['They provide the things animals need to live and grow', 'They are only important to people', 'They have no effect on animals', 'They are the same everywhere on Earth']),
]),
('Plants: Parts and Growth', [
    ('What part of the plant absorbs water from the soil?', ['The roots', 'The leaves', 'The petals', 'The stem only']),
    ('What part of the plant makes food using sunlight?', ['The leaves', 'The roots', 'The petals', 'The seeds']),
    ('What part of the plant supports it and carries water upward?', ['The stem', 'The roots', 'The petals', 'The seeds']),
    ('What part of the plant often attracts insects for pollination?', ['The flower', 'The roots', 'The stem', 'The soil']),
    ('What grows into a new plant when it is placed in soil with water and sunlight?', ['A seed', 'A leaf', 'A petal', 'A stem only']),
    ('What do plants need to grow well?', ['Sunlight, water, air, and soil', 'Only sunlight', 'Only water', 'Nothing at all']),
    ('What is the process called when plants make their own food using sunlight?', ['Photosynthesis', 'Pollination', 'Germination', 'Migration']),
    ('What is it called when a seed begins to grow into a plant?', ['Germination', 'Photosynthesis', 'Pollination', 'Hibernation']),
    ('Which part of the plant usually grows underground?', ['The roots', 'The leaves', 'The flower', 'The stem']),
    ('Why do plants need sunlight?', ['To make their own food', 'To stay cool', 'To attract animals', 'To grow roots only']),
    ('Which of these is the correct order for how a plant grows from a seed?', ['Seed, sprout, seedling, adult plant', 'Adult plant, seed, sprout, seedling', 'Seedling, seed, sprout, adult plant', 'Sprout, adult plant, seed, seedling']),
    ('What do bees help plants do when they visit flowers?', ['Pollinate them so they can make seeds', 'Water them', 'Remove their leaves', 'Change their colour']),
    ('Which of these is NOT a part of most plants?', ['Fur', 'Roots', 'Stem', 'Leaves']),
    ('What happens to a plant if it does not get enough water?', ['It may wilt or die', 'It grows faster', 'It changes colour to blue', 'It grows extra roots instantly']),
    ('Why are leaves usually green?', ['They contain a substance called chlorophyll', 'They are painted by farmers', 'They absorb only red light', 'They reflect all sunlight']),
]),
('Properties of Liquids and Solids', [
    ('Which of these is a solid?', ['A rock', 'Water', 'Juice', 'Milk']),
    ('Which of these is a liquid?', ['Water', 'A rock', 'A book', 'A chair']),
    ('What shape does a liquid take?', ['The shape of its container', 'Always a circle', 'Always a square', 'No shape at all']),
    ('Does a solid change shape when you move it to a new container?', ['No, a solid keeps its own shape', 'Yes, it always changes shape', 'Yes, it disappears', 'Yes, it turns into gas']),
    ('Which of these properties describes a solid?', ['It holds its own shape', 'It always flows', 'It has no shape', 'It always spreads out flat']),
    ('Which of these properties describes a liquid?', ['It flows and takes the shape of its container', 'It always keeps one fixed shape', 'It cannot be poured', 'It is always frozen']),
    ('Which of these items would be classified as a solid?', ['A wooden block', 'Milk', 'Juice', 'Water']),
    ('Which of these items would be classified as a liquid?', ['Orange juice', 'A rock', 'A pencil', 'A book']),
    ('What happens when you pour a liquid from a tall cup into a short wide bowl?', ['It takes the new shape of the bowl', 'It stays shaped like the cup', 'It disappears completely', 'It turns into a solid']),
    ('Can you stack solids on top of each other?', ['Yes, solids can usually be stacked', 'No, solids cannot be touched', 'No, solids always spread out flat', 'Yes, but only if they are liquids']),
    ('Which best describes what happens when a solid ice cube melts?', ['It turns into a liquid', 'It turns into a gas immediately', 'It becomes heavier as a solid', 'It stays exactly the same']),
    ('Why can liquids be poured but solids usually cannot?', ['Liquids flow freely while solids hold their shape', 'Solids are always wet', 'Liquids are always heavier', 'Solids always float']),
    ('Which of these would keep the same shape whether it is in a box or on a table?', ['A wooden block', 'Water', 'Milk', 'Juice']),
    ('Which of these best explains why water is called a liquid?', ['It flows and takes the shape of its container', 'It always stays in a cube shape', 'It cannot be poured', 'It never moves']),
    ('Which group below contains only solids?', ['Rock, wood, and metal', 'Water, juice, and milk', 'Rock and juice', 'Wood and milk']),
]),
('States of Matter and Changes', [
    ('What are the three common states of matter?', ['Solid, liquid, and gas', 'Hot, cold, and warm', 'Big, medium, and small', 'Fast, slow, and still']),
    ('What happens to ice when it is heated?', ['It melts into a liquid', 'It turns into a gas immediately', 'It becomes harder', 'It disappears with no change']),
    ('What happens to water when it is frozen?', ['It becomes a solid', 'It becomes a gas', 'It disappears', 'It becomes hotter']),
    ('What happens to water when it is boiled?', ['It turns into a gas called water vapour', 'It turns into a solid', 'It disappears forever', 'It becomes colder']),
    ('Which state of matter has no fixed shape and can fill any container completely, like air?', ['Gas', 'Solid', 'Liquid', 'None of these']),
    ('What is it called when a liquid changes into a gas?', ['Evaporation', 'Condensation', 'Freezing', 'Melting']),
    ('What is it called when a gas changes back into a liquid?', ['Condensation', 'Evaporation', 'Freezing', 'Melting']),
    ('What is it called when a liquid changes into a solid?', ['Freezing', 'Melting', 'Evaporation', 'Condensation']),
    ('What is it called when a solid changes into a liquid?', ['Melting', 'Freezing', 'Evaporation', 'Condensation']),
    ('Which of these is an example of a gas?', ['The air we breathe', 'A rock', 'Ice', 'Juice']),
    ('Why does water vapour in the air sometimes turn into tiny water droplets on a cold glass?', ['The gas cools down and condenses into a liquid', 'The glass creates new water', 'The water vapour disappears completely', 'The glass turns into water']),
    ('Which change happens when you leave an ice cube out on a warm table?', ['It melts into a liquid', 'It stays frozen forever', 'It turns into a gas right away', 'It becomes a different solid']),
    ('What state of matter is steam?', ['A gas', 'A solid', 'A liquid', 'None of these']),
    ('Which of these correctly matches a state change with its name?', ['Water freezing into ice is called freezing', 'Water freezing into ice is called melting', 'Water freezing into ice is called evaporation', 'Water freezing into ice is called condensation']),
    ('Why is it useful to know that matter can change state?', ['It helps us understand everyday changes like ice melting or water boiling', 'It has no use in daily life', 'It only matters to scientists in labs', 'It never actually happens']),
]),
('Simple Machines and Movement', [
    ('What is a simple machine?', ['A basic tool that makes work easier', 'A machine with an engine', 'A computer', 'A type of vehicle only']),
    ('Which of these is an example of a simple machine?', ['A lever', 'A television', 'A computer', 'A telephone']),
    ('What does a lever help you do?', ['Lift or move a heavy object with less effort', 'Cook food', 'Store water', 'Send messages']),
    ('What is a wheel and axle used for?', ['Helping objects move or turn more easily', 'Cooking food', 'Cleaning clothes', 'Sending messages']),
    ('What is a pulley used for?', ['Lifting objects using a rope and wheel', 'Cooking food', 'Measuring temperature', 'Cleaning windows']),
    ('What is an inclined plane, or ramp, used for?', ['Moving objects up or down more easily', 'Cooking food', 'Sending signals', 'Measuring time']),
    ('Which simple machine would help you get a heavy box up into a truck?', ['A ramp', 'A pencil', 'A cup', 'A book']),
    ('What is a screw used for?', ['Holding objects together or lifting materials', 'Cooking food', 'Measuring length', 'Sending messages']),
    ('What is a wedge used for?', ['Splitting or cutting through objects', 'Cooking food', 'Storing water', 'Sending signals']),
    ('Why do people use simple machines?', ['To make work easier and require less effort', 'To make work harder', 'To use more energy than necessary', 'To slow down every task']),
    ('Which simple machine is a playground seesaw an example of?', ['A lever', 'A wheel and axle', 'A pulley', 'A screw']),
    ('Which simple machine would you use to raise a flag up a flagpole?', ['A pulley', 'A wedge', 'A screw', 'An inclined plane']),
    ('Which of these best describes how a wheelbarrow uses a simple machine?', ['It uses a wheel and axle plus a lever to move loads easily', 'It uses only a pulley', 'It uses only a screw', 'It does not use any simple machine']),
    ('Which simple machine has a sharp edge used for cutting, like an axe?', ['A wedge', 'A lever', 'A pulley', 'A wheel and axle']),
    ('Why might a door hinge be considered similar to a lever?', ['It helps the door swing open with less effort', 'It has no effect on the door', 'It makes the door heavier', 'It only decorates the door']),
]),
('Forces: Push and Pull', [
    ('What is a force?', ['A push or a pull on an object', 'A type of animal', 'A colour', 'A shape']),
    ('Which of these is an example of a push?', ['Pushing a swing forward', 'Pulling a wagon', 'Pulling a rope', 'Pulling a drawer open']),
    ('Which of these is an example of a pull?', ['Pulling open a door', 'Kicking a ball', 'Pushing a shopping cart', 'Pushing a swing']),
    ('What force pulls objects down toward the Earth?', ['Gravity', 'Friction', 'Magnetism', 'Wind']),
    ('What is friction?', ['A force that slows down moving objects when surfaces rub together', 'A force that pulls objects toward the Earth', 'A force that only pushes objects', 'A type of energy from the sun']),
    ('Why is it harder to slide a box across a carpet than across a smooth floor?', ['Carpet creates more friction than a smooth floor', 'Carpet has no friction at all', 'Smooth floors are always heavier', 'Carpet pulls objects upward']),
    ('What might happen if you push a ball harder?', ['It will move faster or farther', 'It will stop moving completely', 'It will not move at all', 'It will disappear']),
    ('Which of these forces can pull certain metal objects toward it without touching them?', ['Magnetism', 'Friction', 'Gravity', 'Sound']),
    ('What happens to a ball if you drop it and nothing stops it?', ['Gravity pulls it toward the ground', 'It floats in the air forever', 'It moves sideways on its own', 'Nothing happens to it']),
    ('Which of these actions uses a pulling force?', ['Pulling a wagon along the ground', 'Kicking a soccer ball', 'Pushing a door open', 'Throwing a ball forward']),
    ('Which surface would likely create the most friction for a sliding box?', ['Rough sandpaper', 'Smooth ice', 'Polished tile', 'Wet glass']),
    ('Why do objects eventually stop rolling on the ground?', ['Friction slows them down over time', 'Gravity pushes them faster', 'Magnetism pulls them backward', 'Wind always stops them instantly']),
    ('Which of these best shows two forces acting in opposite directions in a tug of war?', ['Two teams pulling a rope in opposite directions', 'One team pushing a ball', 'One person lifting a box', 'One person standing still']),
    ('What force helps keep your feet on the ground when you jump?', ['Gravity', 'Friction', 'Magnetism', 'Sound']),
    ('Which of these would reduce friction the most between two surfaces?', ['Adding oil or grease', 'Adding sand', 'Adding sandpaper', 'Pressing harder together']),
]),
('Air and Water in the Environment', [
    ('What is the water cycle?', ['The continuous movement of water between the sky and the Earth', 'A tool for measuring rain', 'A type of ocean current', 'A method of cleaning water']),
    ('What is it called when water vapour rises into the sky and forms clouds?', ['Evaporation and condensation', 'Freezing', 'Pollution', 'Erosion']),
    ('What falls from clouds as part of the water cycle?', ['Precipitation such as rain or snow', 'Only sunshine', 'Only wind', 'Only clouds']),
    ('Why is air important to living things?', ['Living things need air to breathe', 'Air has no use for living things', 'Only plants need air', 'Only fish need air']),
    ('What can happen to air quality when there is too much smoke or pollution?', ['The air becomes unhealthy to breathe', 'The air always becomes cleaner', 'The air disappears completely', 'Nothing changes at all']),
    ('Which of these is a source of clean air for our planet?', ['Trees and plants', 'Factories with heavy smoke', 'Cars stuck in traffic', 'Burning garbage']),
    ('Why do we need to protect fresh water sources like rivers and lakes?', ['Living things depend on clean water to survive', 'Water has no importance to living things', 'Only fish need clean water', 'Rivers never get polluted']),
    ('What is one way that water becomes polluted?', ['Garbage or chemicals are dumped into it', 'Rain falls into it', 'Fish swim in it', 'The sun shines on it']),
    ('What can people do to help keep the air clean?', ['Reduce pollution such as smoke and exhaust', 'Burn more garbage', 'Drive more cars unnecessarily', 'Cut down more trees']),
    ('Which of these is a sign of good air quality?', ['Clear skies with little smog', 'Thick smoky skies', 'Grey polluted air', 'Air that smells like smoke']),
    ('Why is the water cycle important for living things on Earth?', ['It moves fresh water around so living things can use it', 'It has no effect on living things', 'It only affects the ocean', 'It stops all rain from falling']),
    ('What happens to water in a puddle on a sunny day?', ['It evaporates into the air', 'It freezes instantly', 'It turns into a solid', 'It disappears with no explanation']),
    ('Which of these actions could help reduce water pollution?', ['Not dumping chemicals or garbage into rivers', 'Pouring oil into a lake', 'Throwing trash into a stream', 'Washing chemicals into a river']),
    ('What do clouds mainly consist of?', ['Tiny water droplets or ice crystals', 'Solid rock particles', 'Sand', 'Metal particles']),
    ('Why should people care about protecting air and water in the environment?', ['Living things depend on clean air and water to survive and stay healthy', 'Air and water have no connection to living things', 'Pollution never affects health', 'Only certain animals need clean air and water']),
]),
('Caring for the Environment', [
    ('What does it mean to recycle?', ['To turn used materials into new products instead of throwing them away', 'To throw all garbage into a landfill', 'To burn all waste materials', 'To bury all waste underground']),
    ('Which of these materials can usually be recycled?', ['Paper, glass, and some plastics', 'Food scraps only', 'Broken glass only', 'Nothing can be recycled']),
    ('What is composting?', ['Turning food scraps and plant waste into rich soil', 'Burning garbage for energy', 'Throwing garbage into rivers', 'Storing garbage in a landfill forever']),
    ('Why is it important to reduce the amount of waste we create?', ['It helps protect the environment and save resources', 'It has no effect on the environment', 'It makes garbage disappear instantly', 'It is not important at all']),
    ('What are the three Rs often taught for helping the environment?', ['Reduce, reuse, and recycle', 'Read, write, and relax', 'Run, reach, and rest', 'Rain, rocks, and roots']),
    ('Which of these is an example of reusing an item?', ['Using an old jar to store pencils', 'Throwing away a jar after one use', 'Burning an old jar', 'Burying a jar in the yard']),
    ('Why might turning off lights when you leave a room help the environment?', ['It saves energy and reduces waste', 'It has no effect on energy use', 'It uses more electricity', 'It makes the room darker forever']),
    ('What can happen to animals and habitats when litter is left in nature?', ['Animals can be harmed or their habitat can be damaged', 'Animals are never affected by litter', 'Litter always helps habitats grow', 'Habitats improve when litter is present']),
    ('Which of these is a way to conserve, or save, water at home?', ['Turning off the tap while brushing your teeth', 'Leaving the tap running all day', 'Using more water than needed', 'Washing the car every single day']),
    ('Why do communities set up recycling bins?', ['To help collect materials that can be reused instead of thrown away', 'To collect only food waste', 'To make more garbage', 'To replace all garbage cans']),
    ('Which of these actions helps protect trees and forests?', ['Recycling paper products', 'Wasting paper unnecessarily', 'Cutting down trees for no reason', 'Burning wood without need']),
    ('What happens to most garbage that is not recycled or composted?', ['It usually ends up in a landfill', 'It disappears on its own', 'It turns into clean water', 'It becomes new soil instantly']),
    ('Why is it helpful to walk, bike, or carpool instead of always driving alone?', ['It can reduce pollution from vehicle exhaust', 'It always increases pollution', 'It has no effect on the environment', 'It uses more fuel than driving alone']),
    ('Which of these is an example of reducing waste?', ['Bringing a reusable bag instead of using a new plastic bag each time', 'Using a new plastic bag every time you shop', 'Throwing away items you could reuse', 'Buying more than you need every time']),
    ('Why should people care for the environment around them?', ['Healthy environments support all living things, including people', 'The environment has no effect on living things', 'Only plants are affected by the environment', 'Caring for the environment is not necessary']),
]),
]

SOCIAL_STUDIES = [
('Families Then and Now', [
    ('What is one way families communicated with each other long ago, before phones existed?', ['Writing letters', 'Sending text messages', 'Making video calls', 'Using the internet']),
    ('Which of these was a common way to travel long ago, before cars were invented?', ['By horse and carriage', 'By airplane', 'By car', 'By subway train']),
    ('How has technology changed family life over time?', ['Families now have phones, computers, and other modern tools', 'Families have not changed at all', 'Families no longer use any tools', 'Technology has made no difference']),
    ('Which of these is an example of a family tradition?', ['A special meal shared every year on a holiday', 'A brand new toy', 'A school assignment', 'A weather report']),
    ('Why do families pass down traditions from one generation to the next?', ['To keep their history and culture alive', 'To make school easier', 'To avoid learning anything new', 'Because it is required by law']),
    ('How did people usually preserve food long ago, before refrigerators were common?', ['By salting, drying, or storing food in cool cellars', 'By freezing food in modern freezers', 'By using microwaves', 'By ordering food online']),
    ('Which of these is an example of a family heirloom?', ['An old photograph passed down through generations', 'A brand new video game', 'A fast food meal', 'A weather forecast']),
    ('How might chores for children have been different for families long ago?', ['Children often helped more with farm work or household tasks', 'Children never had any chores', 'Children only used computers for chores', 'Children did not live with families']),
    ('What is one way you can learn about your family history?', ['Asking older relatives about the past', 'Watching cartoons', 'Playing video games', 'Ignoring old photographs']),
    ('Which of these shows a change in family life from long ago to today?', ['Many families now use washing machines instead of washing by hand', 'Families never washed clothes long ago', 'Washing machines have always existed', 'Nothing about washing clothes has changed']),
    ('Why is it useful to compare families today with families long ago?', ['It helps us understand how life has changed over time', 'It has no value for understanding history', 'It only matters for very old people', 'Families have always been exactly the same']),
    ('Which of these is a type of family structure?', ['A family with two parents and children', 'Only families with grandparents', 'Only families with one child', 'There is only one type of family']),
    ('What role did storytelling often play in families long ago?', ['Passing down history, culture, and lessons orally', 'Sending emails', 'Watching television', 'Making video calls']),
    ('Which of these best shows how communication with faraway relatives has changed?', ['Video calls now let families see and talk to each other instantly', 'Letters are now the only way to communicate', 'People never contact faraway relatives', 'Communication has not changed at all']),
    ('Why might a family celebrate a tradition from their culture?', ['To honour their heritage and bring the family together', 'To follow a rule with no meaning', 'Because it is required by the government', 'To avoid spending time together']),
]),
('Community Traditions and Celebrations', [
    ('What is a community celebration?', ['A special event that brings people in a community together', 'A type of building', 'A kind of food', 'A weather event']),
    ('Why do communities hold festivals and celebrations?', ['To share culture and bring people together', 'To close down local businesses', 'To avoid meeting neighbours', 'To create traffic problems']),
    ('Which of these is an example of a community celebration in Canada?', ['Canada Day', 'A regular school day', 'A grocery store visit', 'A weekday commute']),
    ('What might a community parade include?', ['Music, decorated floats, and performers', 'Only silence', 'Only empty streets', 'Only paperwork']),
    ('Why is it valuable to learn about celebrations from different cultures?', ['It helps us understand and respect different traditions', 'It has no value at all', 'It is only useful for one culture', 'Cultures never have different celebrations']),
    ('Which of these is often part of a harvest festival tradition?', ['Celebrating and sharing food from the fall harvest', 'Ignoring the change of seasons', 'Avoiding all food traditions', 'Closing all farms permanently']),
    ('What is one way communities might celebrate a special holiday together?', ['Gathering for a shared meal or event', 'Staying completely separate from neighbours', 'Avoiding all traditions', 'Closing the community centre forever']),
    ('Why might different communities in Canada celebrate different traditions?', ['Canada has many cultures, each with their own customs', 'All communities in Canada are identical', 'Traditions are not allowed in Canada', 'Only one tradition exists in Canada']),
    ('What is one purpose of a community festival?', ['To celebrate shared culture, history, or achievements', 'To keep people from gathering', 'To close down public spaces', 'To create confusion']),
    ('Which of these might be part of a lunar new year celebration?', ['A dragon dance and family gatherings', 'A quiet day with no activities', 'Closing all businesses with no events', 'Avoiding family members']),
    ('Why do many communities decorate public spaces during celebrations?', ['To create a festive atmosphere for everyone to enjoy', 'To make the community look empty', 'To block streets permanently', 'To avoid the holiday completely']),
    ('What can students learn by participating in community celebrations?', ['About traditions, history, and different cultures', 'Nothing useful at all', 'Only about sports', 'Only about weather']),
    ('Which of these best describes a community tradition passed down over many years?', ['A yearly event that connects people to their history', 'A brand new event with no history', 'An event that never repeats', 'An event with no connection to culture']),
    ('Why might people wear special clothing during a cultural celebration?', ['To honour and represent their heritage', 'To hide from other people', 'Because it is required by weather', 'Because there is no other choice of clothing']),
    ('How can attending a celebration from a different culture help you?', ['It can teach you to appreciate and respect other traditions', 'It has no benefit at all', 'It only teaches you about weather', 'It teaches you to ignore other cultures']),
]),
('Maps and Directions', [
    ('What is a map?', ['A drawing that shows what a place looks like from above', 'A photograph of a person', 'A written story', 'A type of food']),
    ('What is a map key, or legend, used for?', ['Explaining what the symbols on a map mean', 'Showing the weather', 'Showing the time of day', 'Showing a list of foods']),
    ('What are the four main compass directions?', ['North, south, east, and west', 'Up, down, left, and right', 'Hot, cold, wet, and dry', 'Big, small, tall, and short']),
    ('On most maps, which direction is usually at the top?', ['North', 'South', 'East', 'West']),
    ('What does a compass rose show on a map?', ['The directions, such as north, south, east, and west', 'The temperature of a place', 'The population of a city', 'The price of items']),
    ('Which of these is a symbol you might find on a map key?', ['A small tree icon for a park', 'A picture of a clock', 'A picture of a phone', 'A picture of a shoe']),
    ('What is the purpose of a scale on a map?', ['To show how map distances relate to real distances', 'To show the weather forecast', 'To show how heavy an object is', 'To show the time zones']),
    ('If you are facing north and turn to face the opposite direction, which way are you now facing?', ['South', 'East', 'West', 'North']),
    ('Which of these would most likely be shown on a community map?', ['Streets, parks, and buildings', 'Ocean currents only', 'Planets and stars', 'Weather patterns only']),
    ('Why are maps useful for finding your way around a community?', ['They show the layout of streets and important places', 'They show what people are wearing', 'They show the price of houses', 'They show only weather information']),
    ('What might a globe show that a flat map cannot show as accurately?', ['The round shape of the Earth', 'The temperature of a city', 'The population of a town', 'The name of a street']),
    ('If a map shows a school directly east of your house, which direction would you travel from your house to reach the school?', ['East', 'West', 'North', 'South']),
    ('What is the purpose of grid lines sometimes found on maps?', ['To help locate specific places using rows and columns', 'To show the weather', 'To show how much something costs', 'To decorate the map']),
    ('Which of these tools might you use alongside a map to figure out direction outdoors?', ['A compass', 'A calculator', 'A paintbrush', 'A thermometer']),
    ('Why might someone use an aerial, or bird view, map of their neighbourhood?', ['To see the layout of streets and buildings from above', 'To see the weather forecast', 'To see a list of prices', 'To see a story about the town']),
]),
('Communities Around the World', [
    ('What is a community?', ['A group of people living and interacting in the same area', 'A single person living alone', 'A type of animal', 'A kind of weather']),
    ('Which of these is an example of a rural community?', ['A small farming town', 'A large downtown city', 'An underwater city', 'A city in outer space']),
    ('Which of these is an example of an urban community?', ['A large city with many tall buildings', 'A small farm with few neighbours', 'An empty desert with no people', 'An island with no buildings']),
    ('Why might people in a mountain community build homes differently than people near the ocean?', ['They adapt their homes to their local land and climate', 'All homes everywhere are exactly the same', 'Location has no effect on how homes are built', 'Mountains and oceans have identical climates']),
    ('Which of these is a way that communities around the world might differ?', ['Language, customs, and food', 'All communities eat the exact same food', 'All communities speak the exact same language', 'Communities have no differences']),
    ('Why do some communities near rivers or oceans often use boats for transportation?', ['Water travel is often easier where there is a lot of water nearby', 'Boats are required everywhere in the world', 'Land travel is impossible near water', 'Rivers and oceans do not allow any travel']),
    ('What might people in a community that gets a lot of snow need to prepare for?', ['Cold weather clothing and snow removal tools', 'Only very hot weather clothing', 'No preparation at all', 'Boats for travel only']),
    ('Which of these best describes how communities depend on their environment?', ['They often use local resources like land, water, or forests', 'Communities never use their environment', 'All communities ignore their surroundings', 'Environment has no effect on community life']),
    ('Why might studying communities around the world help students understand diversity?', ['It shows how different people live and adapt to their surroundings', 'It has no educational value', 'It shows that all communities are the same', 'It only teaches about one country']),
    ('Which of these is a way that communities can be connected to each other, even from far away?', ['Trade and communication technology', 'Complete isolation with no contact', 'Ignoring all other communities', 'Refusing to share any resources']),
    ('What is one reason people might choose to live in a city rather than in the countryside?', ['Access to more jobs, schools, and services', 'Cities never have any jobs', 'Countryside always has more people', 'Cities have no buildings']),
    ('Which of these is a natural resource that a coastal community might rely on?', ['Fish from the ocean', 'Desert sand only', 'Mountain snow only', 'Underground caves only']),
    ('Why might different communities have different types of homes around the world?', ['Climate, materials, and culture can all affect home design', 'All homes must look exactly the same everywhere', 'Homes have no connection to climate', 'Culture never affects how homes look']),
    ('Which of these best shows an example of community cooperation?', ['Neighbours working together to clean a local park', 'Neighbours ignoring each other completely', 'Refusing to help anyone nearby', 'Avoiding all community events']),
    ('Why is it helpful to learn about communities different from your own?', ['It builds understanding and respect for different ways of life', 'It has no benefit at all', 'It teaches that other communities are wrong', 'It is only useful for adults']),
]),
('Rules and Responsibilities in a Community', [
    ('Why do communities have rules?', ['To keep people safe and help things run smoothly', 'To make life more difficult', 'To confuse residents', 'Rules serve no purpose']),
    ('Who is responsible for creating laws in a community, like a city or town?', ['Local government leaders', 'Only children', 'Only visitors', 'No one is responsible']),
    ('Which of these is an example of a classroom rule?', ['Raise your hand before speaking', 'Run in the hallways', 'Ignore the teacher completely', 'Leave the classroom without permission']),
    ('Why is it important to follow traffic rules in a community?', ['To keep drivers and pedestrians safe', 'Traffic rules have no purpose', 'Traffic rules only apply to adults', 'Following rules makes travel more dangerous']),
    ('What is a responsibility?', ['A duty or job that a person is expected to do', 'A type of building', 'A kind of food', 'A season of the year']),
    ('Which of these is a responsibility a student might have at school?', ['Completing homework on time', 'Ignoring all assignments', 'Refusing to attend class', 'Avoiding all responsibilities']),
    ('Why might a community have a rule against littering?', ['To keep the environment clean and safe for everyone', 'Littering rules have no purpose', 'Littering helps the environment', 'Rules against littering are unnecessary']),
    ('Who helps enforce community rules and laws, such as keeping people safe?', ['Police officers', 'Only teachers', 'Only parents', 'No one enforces rules']),
    ('Which of these is an example of a community responsibility for all residents?', ['Recycling and keeping shared spaces clean', 'Ignoring all shared spaces', 'Damaging public property', 'Avoiding all community involvement']),
    ('Why do libraries have rules about being quiet?', ['To help everyone read and study without distraction', 'Quiet rules have no purpose', 'Libraries prefer loud noise', 'Rules make libraries worse']),
    ('What might happen if a community had no rules at all?', ['It could become unsafe or disorganized', 'Everything would run perfectly', 'Rules have no effect on communities', 'Nothing would change at all']),
    ('Which of these is an example of being a responsible citizen?', ['Voting when you are old enough and following laws', 'Ignoring all laws', 'Refusing to participate in the community', 'Avoiding all civic duties']),
    ('Why is it important for community members to respect each other rules and property?', ['It helps everyone live together peacefully', 'Respect has no importance in a community', 'Rules are meant to be broken', 'Property does not need to be respected']),
    ('Which of these is a rule that helps keep a playground safe?', ['Taking turns on the equipment', 'Pushing other children', 'Ignoring the other children', 'Running onto the road']),
    ('Why might a community ask residents to follow noise rules at night?', ['To help everyone get proper rest', 'Noise rules have no benefit', 'Rest is not important to a community', 'Noise never affects other people']),
]),
('Goods and Services in a Community', [
    ('What are goods?', ['Physical items that people make or grow to sell or use', 'Actions that help other people', 'A type of weather', 'A kind of rule']),
    ('What are services?', ['Actions or work that people do to help others', 'Physical items like food or toys', 'A type of building', 'A kind of weather']),
    ('Which of these is an example of a good?', ['A loaf of bread', 'A haircut', 'A doctor visit', 'A bus ride']),
    ('Which of these is an example of a service?', ['A haircut from a hairdresser', 'A loaf of bread', 'A toy car', 'A book']),
    ('Which worker mainly provides a service rather than a good?', ['A firefighter', 'A farmer growing vegetables', 'A baker making bread', 'A factory making shoes']),
    ('Which worker mainly produces a good?', ['A farmer growing crops', 'A dentist', 'A teacher', 'A mail carrier']),
    ('Why do communities need both goods and services?', ['People rely on both products and helpful work to meet their needs', 'Communities only need goods', 'Communities only need services', 'Goods and services are not needed']),
    ('What is a consumer?', ['A person who buys or uses goods and services', 'A person who only makes goods', 'A type of building', 'A kind of weather']),
    ('What is a producer?', ['A person or business that makes goods or provides services', 'A person who only buys things', 'A type of weather', 'A kind of rule']),
    ('Which of these community workers provides an important service to keep people healthy?', ['A doctor', 'A shoemaker', 'A toy maker', 'A baker']),
    ('Why might a community need a grocery store?', ['To provide food and other goods to residents', 'Grocery stores serve no purpose', 'Communities never need food', 'Food is not considered a good']),
    ('Which of these is an example of trading goods for money?', ['Buying a toy at a store', 'Volunteering at a shelter', 'Reading a book', 'Watching a movie at home']),
    ('Why do people pay for services like haircuts or car repairs?', ['The service provider uses time, skill, and effort to help them', 'Services are always free', 'Services require no skill at all', 'Payment is never expected for services']),
    ('Which of these best shows the difference between a good and a service?', ['A good is an item you can hold, a service is help someone provides', 'A good and a service are exactly the same', 'Goods are always free and services always cost money', 'Services are physical items you can hold']),
    ('Why is it helpful for communities to have workers who provide different goods and services?', ['It allows people to get many different needs met close to home', 'It has no benefit to the community', 'Communities function better with only one type of worker', 'Goods and services are unnecessary in a community']),
]),
('Landmarks and Local Community Features', [
    ('What is a landmark?', ['A notable place or feature that helps identify a location', 'A type of weather', 'A kind of food', 'A rule in a community']),
    ('Which of these is an example of a well known Canadian landmark?', ['The CN Tower', 'A regular house', 'An empty field', 'A grocery cart']),
    ('Why are landmarks useful for people finding their way around?', ['They serve as recognizable points for giving directions', 'Landmarks have no use for navigation', 'Landmarks are always invisible', 'Landmarks only exist in stories']),
    ('Which of these might be considered a natural landmark?', ['A large waterfall', 'A shopping mall', 'A parking lot', 'A traffic light']),
    ('Which of these might be considered a human-made landmark?', ['A famous bridge', 'A mountain', 'A river', 'A forest']),
    ('Why might a community build a monument or statue?', ['To honour an important person or event', 'Monuments have no purpose', 'To block traffic', 'To confuse visitors']),
    ('Which of these is an example of a community building that serves the public?', ['A public library', 'A private garage', 'A single family bedroom', 'A locked closet']),
    ('Why might tourists visit famous landmarks?', ['To see interesting and historically important places', 'Landmarks have no appeal to visitors', 'Tourists avoid all landmarks', 'Landmarks are not open to the public']),
    ('What might a town hall building be used for?', ['Local government meetings and community business', 'Only for sports games', 'Only for movies', 'Only for weather forecasting']),
    ('Which of these is a landmark you might find near water in many communities?', ['A harbour or dock', 'A desert dune', 'A mountain peak', 'A snow cave']),
    ('Why is it helpful to know the landmarks in your own community?', ['It can help you navigate and feel connected to your area', 'Landmarks provide no benefit to residents', 'Communities never have landmarks', 'Knowing landmarks is not useful at all']),
    ('Which of these best describes a historic landmark?', ['A place with importance from the past that is preserved', 'A brand new building with no history', 'A place with no significance', 'A type of weather event']),
    ('Which of these might be a landmark specific to a coastal community?', ['A lighthouse', 'A desert cactus', 'A snowy mountain peak', 'A wheat field']),
    ('Why might a community protect and preserve its landmarks?', ['To keep history and culture alive for future generations', 'Landmarks have no value to preserve', 'Preserving landmarks wastes resources', 'Landmarks are not connected to history']),
    ('Which of these is an example of a landmark found in many Canadian communities?', ['A war memorial', 'A private backyard', 'A single house', 'A grocery list']),
]),
('Cultural Diversity and Traditions', [
    ('What does cultural diversity mean?', ['A variety of different cultures existing within a community', 'Everyone in a community being exactly the same', 'A single culture with no variety', 'A rule against different cultures']),
    ('Why is Canada often described as a culturally diverse country?', ['It is home to people from many different backgrounds and cultures', 'Everyone in Canada shares the exact same culture', 'Canada has only one type of tradition', 'Cultural diversity does not exist in Canada']),
    ('Which of these is an example of cultural diversity in a community?', ['People celebrating different holidays and traditions', 'Everyone eating the exact same food', 'Everyone speaking only one language', 'A community with no traditions at all']),
    ('Why might learning about different cultures help build a stronger community?', ['It encourages understanding, respect, and cooperation', 'It has no effect on a community', 'It creates more conflict', 'Cultures should never be discussed']),
    ('Which of these is an example of a cultural tradition passed down through generations?', ['A traditional dance performed at celebrations', 'A brand new invention', 'A weather pattern', 'A type of rock']),
    ('Why might people from different cultures share their food traditions with a community?', ['To celebrate and introduce others to their heritage', 'Sharing food traditions has no purpose', 'Food traditions should be kept completely secret', 'Communities never share food']),
    ('Which of these best shows respect for cultural diversity?', ['Learning about and appreciating different traditions', 'Making fun of traditions different from your own', 'Ignoring all cultures other than your own', 'Refusing to learn about other cultures']),
    ('Why might a school celebrate multicultural events?', ['To help students learn about and appreciate different cultures', 'Multicultural events have no educational value', 'Schools should avoid discussing culture', 'Only one culture should be taught in schools']),
    ('Which of these is an example of a cultural custom?', ['A special greeting used by a certain culture', 'A weather forecast', 'A math equation', 'A type of rock']),
    ('Why do many communities in Canada celebrate multiple different holidays throughout the year?', ['Because the population includes people from many cultural backgrounds', 'Only one holiday is allowed in Canada', 'Communities are not permitted to celebrate holidays', 'Holidays have no cultural connection']),
    ('Which of these is an example of cultural clothing worn during special occasions?', ['Traditional clothing worn during a cultural festival', 'Everyday clothing bought at any store', 'Clothing with no cultural meaning', 'A school uniform only']),
    ('Why is respecting cultural differences important in a diverse community?', ['It helps people live together peacefully and understand one another', 'Respect for differences causes more conflict', 'Communities function better with no diversity', 'Diversity should be ignored completely']),
    ('Which of these is an example of a cultural celebration involving music and dance?', ['A traditional festival with performances', 'A quiet library visit', 'A grocery store trip', 'A math test']),
    ('Why might newcomers to a community want to share their traditions with others?', ['To help others understand their culture and feel connected', 'Sharing traditions serves no purpose', 'Newcomers should hide all traditions', 'Traditions are not important to share']),
    ('Which of these best describes the benefit of a culturally diverse community?', ['It brings a variety of ideas, traditions, and perspectives together', 'Diversity weakens a community', 'All communities should avoid diversity', 'Diverse communities cannot function well']),
]),
('Transportation Then and Now', [
    ('How did most people travel long distances before cars were invented?', ['By horse and carriage or on foot', 'By airplane', 'By subway train', 'By car']),
    ('Which of these is a modern form of transportation?', ['An airplane', 'A horse and buggy', 'A canoe made of bark', 'A covered wagon']),
    ('How has transportation changed travel times over the years?', ['Modern transportation is often much faster than travel long ago', 'Travel times have stayed exactly the same', 'Transportation has made travel slower', 'Transportation has no effect on travel time']),
    ('Which of these was an early form of water transportation?', ['A canoe', 'An airplane', 'A subway train', 'A car']),
    ('Why might people have used trains as a major form of transportation in the past?', ['Trains could carry many people and goods over long distances', 'Trains have never existed', 'Trains could only carry one person', 'Trains were slower than walking']),
    ('Which of these is an example of public transportation?', ['A city bus', 'A private car owned by one family', 'A single bicycle', 'A private airplane']),
    ('Why might communities build bike lanes today?', ['To provide a safe space for cyclists and reduce car traffic', 'Bike lanes have no purpose', 'Bike lanes are only for cars', 'Communities never consider transportation options']),
    ('How did the invention of the automobile change communities?', ['It allowed people to travel farther and faster than before', 'It made travel completely impossible', 'It had no effect on communities', 'It only worked for very short distances']),
    ('Which of these is a benefit of public transportation like buses and trains?', ['It can reduce traffic and pollution from many individual cars', 'Public transportation increases pollution', 'Public transportation has no benefits', 'It only helps one person at a time']),
    ('Which of these transportation methods produces no pollution at all?', ['Walking or riding a bicycle', 'Driving a car', 'Flying an airplane', 'Riding in a large truck']),
    ('Why might people in northern communities have used snowmobiles or dog sleds for transportation?', ['To travel over snow and ice where cars may not work well', 'Snow has no effect on transportation', 'Cars always work best in deep snow', 'Northern communities never needed transportation']),
    ('How did early explorers in Canada often travel along rivers and lakes?', ['By canoe', 'By airplane', 'By car', 'By subway']),
    ('Which of these best shows a change in transportation technology over time?', ['Horses were replaced by cars for most long distance travel', 'Cars have always existed', 'Horses are still the most common transportation today', 'Transportation has never changed']),
    ('Why is it useful to compare transportation methods from the past and today?', ['It helps us understand how technology has improved travel', 'Comparing transportation has no value', 'Transportation has never changed at all', 'Only cars have ever existed']),
    ('Which of these is an example of transportation used mainly for short trips within a neighbourhood?', ['A bicycle', 'An airplane', 'A cargo ship', 'A freight train']),
]),
('Jobs and Community Helpers', [
    ('What is a community helper?', ['A person whose job helps keep the community safe and running well', 'A person who never helps anyone', 'A type of building', 'A kind of weather']),
    ('Which of these is a job that helps keep people safe?', ['A police officer', 'A toy maker', 'A candy seller', 'A movie actor']),
    ('What is the main job of a firefighter?', ['Putting out fires and helping in emergencies', 'Teaching students', 'Delivering mail', 'Selling groceries']),
    ('What is the main job of a doctor?', ['Helping people stay healthy and treating illness', 'Delivering mail', 'Building houses', 'Selling food']),
    ('What is the main job of a teacher?', ['Helping students learn new things', 'Fixing cars', 'Delivering packages', 'Growing crops']),
    ('What is the main job of a mail carrier?', ['Delivering letters and packages to homes', 'Teaching students', 'Treating patients', 'Building roads']),
    ('What is the main job of a farmer?', ['Growing crops or raising animals for food', 'Delivering mail', 'Teaching students', 'Directing traffic']),
    ('Which community helper directs traffic and enforces laws to keep people safe?', ['A police officer', 'A farmer', 'A librarian', 'A baker']),
    ('What is the main job of a librarian?', ['Helping people find and borrow books', 'Fixing cars', 'Growing crops', 'Building houses']),
    ('Why are community helpers important?', ['They provide important services that keep the community safe and running smoothly', 'They provide no useful services', 'Communities do not need any helpers', 'Their jobs have no value']),
    ('Which community helper would you call in a medical emergency?', ['A paramedic', 'A baker', 'A librarian', 'A mail carrier']),
    ('What is the main job of a construction worker?', ['Building or repairing structures like houses and roads', 'Teaching students', 'Treating illness', 'Delivering mail']),
    ('Which of these community helpers works to put out fires and rescue people?', ['A firefighter', 'A teacher', 'A farmer', 'A librarian']),
    ('Why might a community need many different kinds of workers?', ['Different jobs meet different important needs in the community', 'A community only needs one type of worker', 'Different jobs have no value', 'Communities function best with no workers at all']),
    ('Which of these is an example of a job that helps provide food for a community?', ['A farmer growing crops', 'A firefighter', 'A police officer', 'A mail carrier']),
]),
]


if __name__ == '__main__':
    rng = random.Random(RNG_SEED)
    all_worksheets = []
    all_worksheets += build_subject('Language', LANGUAGE, rng)
    all_worksheets += build_subject('Math', MATH, rng)
    all_worksheets += build_subject('Science', SCIENCE, rng)
    all_worksheets += build_subject('SocialStudies', SOCIAL_STUDIES, rng)
    write_worksheets(2, all_worksheets)
