#!/usr/bin/env python3
"""Grade 9, Days 181-187 -- extends Grade 9 from 180 to 187 days, completing
the full 187-day Ontario Grade 9 curriculum target. This is the FINAL batch
for this grade. Topics chosen after dumping and reading the full Day 1-180
title list (data/grade9.json) to avoid any overlap, which by this point is
exhaustive across all four subjects.

New topics introduced in this batch (Days 181-186, one per subject per day),
confirmed absent from every prior Day 1-180 (subject, title) pair:

Language: Conditional Sentences and If-Clauses; Collocations and Natural Word
Pairings; Analyzing Bathos and Anticlimax in Narrative; Writing a Toast or
Celebratory Speech; Analyzing Bias in Photojournalism and Image Selection;
Varying Sentence Openers for Style and Flow.

Math: Twin Primes and the Twin Prime Conjecture; Retirement Savings, RRSPs,
and TFSAs; An Introduction to Hypothesis Testing; Determinants and Inverses
of 2x2 Matrices; The Equation of a Sphere in Three Dimensions; An
Introduction to Implicit Differentiation.

Science: Blood Types and the ABO/Rh Blood Group System; Catalysis and the
Haber Process for Ammonia Production; Kirchhoffs Current and Voltage Laws;
Wave Action and the Formation of Coastal Landforms; Space Telescopes and
Observational Astronomy; Introduction to Semiconductors and Diodes.

SocialStudies (Geography-focused, matching the existing Grade 9 convention):
Urban Cemeteries and Changing Land Use; Lighthouse Networks and Maritime
Navigation History; River Basin Management and Watershed Planning; Amusement
Parks and the Leisure Industry; Postal Codes and Spatial Data Systems; Urban
Skyscrapers and Vertical City Growth.

Day 187 is the final cross-subject review day of the entire 187-day Grade 9
build, drawing quiz content from 5 of the 6 new topics per subject introduced
in Days 181-186 of this same batch (mirroring the established review-day
convention of prior batches, which likewise reviewed a representative subset
rather than every single day). Its four review titles ("Language Review:
Conditionals, Collocations, Bathos, and Sentence Openers", "Math Review: Twin
Primes, Retirement Savings, Hypothesis Testing, and Implicit Differentiation",
"Science Review: Blood Types, the Haber Process, Kirchhoffs Laws, and
Semiconductors", "Social Studies Review: Cemeteries, Lighthouses, Watersheds,
and Skyscrapers") are textually distinct from every earlier review day's
title in Days 1-180. Since this is the very last day of the entire K-12
Grade 9 curriculum build, its review summaries briefly acknowledge that this
concludes the full 187-day course, while still following the exact
mechanical review-day format used in every prior batch.

Subject keys for Grade 9 are "Language", "Math", "Science",
"SocialStudies" (same as all earlier Grade 9 batches); SocialStudies
content is Geography-focused, matching the existing convention.

videoUrl is intentionally left unset for every subject -- fetch_video_ids.py
fills these in automatically on its next daily run. No embedded ASCII double-
quote characters are used anywhere in question/summary/option text;
apostrophes are avoided entirely (e.g. "Kirchhoffs Laws" not "Kirchhoff's
Laws", "Earths" not "Earth's", "citys" not "city's", "readers" not
"reader's").
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

L9 = 'https://tvolearn.com/pages/grade-9-english'
M9 = 'https://tvolearn.com/pages/grade-9-mathematics'
S9 = 'https://tvolearn.com/pages/grade-9-science'
SS9 = 'https://tvolearn.com/pages/grade-9-geography'
RL, RM, RS, RSS = (
    'TVO Learn: Grade 9 English',
    'TVO Learn: Grade 9 Mathematics',
    'TVO Learn: Grade 9 Science',
    'TVO Learn: Grade 9 Geography',
)


def L(t, s, q):
    return sub('Language', t, s, RL, L9, q)


def M(t, s, q):
    return sub('Math', t, s, RM, M9, q)


def Sc(t, s, q):
    return sub('Science', t, s, RS, S9, q)


def SS(t, s, q):
    return sub('SocialStudies', t, s, RSS, SS9, q)


def _rebalance_answer_positions(days, seed=20260818):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g9_181_187 = [
day(181, [
L('Grammar: Conditional Sentences and If-Clauses',
  'Grade 9 Language strand: a conditional sentence expresses a condition and its result using an if-clause paired with a main clause, and different conditional types (zero, first, second, and third) signal different degrees of likelihood, from general truths to hypothetical or impossible situations.',
  [('What does a conditional sentence express?', ['A condition and its result, using an if-clause paired with a main clause', 'A statement with no connection to cause and result', 'A command given without any explanation', 'A question that can never be answered with certainty'], 0),
   ('What does a zero conditional typically describe?', ['A general truth or fact that is always the case when the condition is met', 'A hypothetical situation that could never actually happen', 'An event that occurred only once in the distant past', 'A condition that has no result of any kind'], 0),
   ('Which sentence is an example of a first conditional, describing a realistic future possibility?', ['If it rains tomorrow, the game will be cancelled.', 'If it rained tomorrow, the game would be cancelled.', 'If it had rained yesterday, the game would have been cancelled.', 'It rains and the game cancels every time without exception.'], 0),
   ('What does a second conditional typically describe?', ['A hypothetical or unlikely situation in the present or future', 'An event that is guaranteed to happen exactly as described', 'A situation set entirely in the distant past with no connection to the present', 'A conditional sentence that has no if-clause'], 0),
   ('What does a third conditional describe, and how does it differ from a second conditional?', ['A third conditional describes a hypothetical situation in the past that did not happen, while a second conditional describes a hypothetical situation in the present or future', 'A third conditional and a second conditional are always identical in meaning', 'A third conditional only describes events that are certain to occur in the future', 'A second conditional always describes an impossible past event'], 0)]),
M('Number Theory: Twin Primes and the Twin Prime Conjecture',
  'Grade 9 Math strand: twin primes are pairs of prime numbers that differ by exactly two, such as 11 and 13, and the twin prime conjecture proposes that infinitely many such pairs exist, a statement that remains unproven despite extensive study in number theory.',
  [('What defines a pair of twin primes?', ['Two prime numbers that differ by exactly two', 'Two prime numbers that differ by exactly one', 'Two prime numbers that are always identical to each other', 'Any two numbers that happen to be even'], 0),
   ('Which of the following is an example of a twin prime pair?', ['11 and 13', '8 and 10', '15 and 17', '9 and 11'], 0),
   ('What does the twin prime conjecture propose?', ['That infinitely many pairs of twin primes exist', 'That only a finite number of twin prime pairs exist', 'That no twin prime pairs exist beyond the number 100', 'That every prime number has exactly one twin'], 0),
   ('What is notable about the current mathematical status of the twin prime conjecture?', ['It remains unproven, despite extensive study and progress toward understanding prime number patterns', 'It has been definitively proven true using a complete mathematical proof', 'It has been definitively proven false through a counterexample', 'Mathematicians have never attempted to study this conjecture'], 0),
   ('How does the study of twin primes connect to the broader study of prime numbers and their distribution, examined earlier in this course?', ['It builds on the same foundation of prime factorization and number properties while focusing specifically on the spacing between consecutive primes', 'Twin primes have no connection to the broader study of prime numbers', 'The study of twin primes replaces the need to understand prime factorization entirely', 'Twin primes can only be studied without any reference to prime numbers generally'], 0)]),
Sc('Biology: Blood Types and the ABO/Rh Blood Group System',
   'Grade 9 Science strand: human blood is classified into types based on the presence or absence of specific antigens on red blood cells, with the ABO system defining types A, B, AB, and O, and the Rh factor further classifying blood as positive or negative, a distinction critical for safe blood transfusions.',
   [('What determines a persons blood type in the ABO system?', ['The presence or absence of specific antigens on red blood cells', 'The persons age at the time blood is tested', 'The colour of the persons blood, which varies between types', 'Blood type is determined entirely by random chance with no biological basis'], 0),
    ('What are the four possible blood types in the ABO system?', ['A, B, AB, and O', 'Only A and B, with no other possible types', 'Positive and negative, with no further classification', 'X, Y, Z, and W'], 0),
    ('What does the Rh factor indicate about a persons blood?', ['Whether a specific additional antigen is present, classifying blood as positive or negative', 'The Rh factor indicates a persons age rather than any blood property', 'The Rh factor has no connection to blood classification of any kind', 'The Rh factor always determines a persons blood type in the ABO system directly'], 0),
    ('Why is knowing a patients blood type critical before a blood transfusion?', ['Transfusing incompatible blood types can trigger a dangerous immune response against the donated red blood cells', 'Blood type has no effect on the safety of a transfusion', 'Every blood type is universally compatible with every other blood type', 'Transfusions are never affected by antigens present on red blood cells'], 0),
    ('Why is a person with type O negative blood sometimes referred to as a universal donor?', ['Their red blood cells lack the A, B, and Rh antigens that could trigger an immune reaction in recipients of most other blood types', 'Type O negative blood is never compatible with any other blood type', 'Universal donor status has no connection to the antigens present on red blood cells', 'Every blood type is equally suitable as a universal donor'], 0)]),
SS('Social Studies: The Geography of Urban Cemeteries and Changing Land Use',
   'Grade 9 Social Studies (Geography) strand: urban cemeteries occupy significant land within growing cities, and as urban areas expand, planners must balance preserving these historically and culturally significant sites with pressures to use limited urban land for housing, infrastructure, or other development.',
   [('Why can urban cemeteries present a land use challenge in growing cities?', ['They occupy significant land that could otherwise be used for housing, infrastructure, or other development, creating pressure between preservation and growth', 'Cemeteries never occupy any meaningful amount of land within a city', 'Growing cities never experience any pressure related to limited land availability', 'Urban cemeteries have no connection to the study of land use planning'], 0),
    ('What is one reason city planners often choose to preserve historic cemeteries rather than redevelop them?', ['Historic cemeteries often hold significant historical and cultural value for a community', 'Historic cemeteries are always considered worthless and are never preserved', 'Preservation of cemeteries has no connection to a communitys cultural history', 'City planners are legally forbidden from ever considering preservation of any site'], 0),
    ('How might a rapidly growing citys population increase pressure on land occupied by cemeteries?', ['Rising demand for housing and infrastructure can make previously undeveloped or lightly used land, including cemetery land, more attractive for development', 'Population growth never creates any additional demand for urban land', 'Cemetery land is always completely unaffected by a citys population growth', 'A growing population always reduces the demand for housing and infrastructure'], 0),
    ('What alternative approach might a city take instead of removing an historic cemetery to free up land?', ['Incorporating the cemetery into surrounding green space or public areas while limiting new development nearby', 'Cities are always required to remove every cemetery once land becomes valuable', 'There is never any alternative to removing a cemetery once land pressure increases', 'Cemeteries can never be incorporated into any other type of public space'], 0),
    ('Why do geographers study the land use patterns associated with cemeteries as part of urban geography?', ['They reveal how cities balance historical preservation, cultural values, and the practical demand for limited urban land', 'Cemeteries have no connection to the study of urban geography', 'Every city in the world manages cemetery land in an identical way', 'This topic is considered purely a matter of religious practice, not geography'], 0)]),
]),
day(182, [
L('Vocabulary: Collocations and Natural Word Pairings',
  'Grade 9 Language strand: a collocation is a combination of words that speakers of a language habitually use together, such as make a decision rather than do a decision, and learning common collocations helps writers sound more natural and precise.',
  [('What is a collocation?', ['A combination of words that speakers of a language habitually use together', 'A word that has no relationship to any other word in a sentence', 'A punctuation mark used to join two related clauses', 'A term used only to describe words borrowed from another language'], 0),
   ('Which phrase is the natural, commonly used collocation in English?', ['make a decision', 'do a decision', 'have a decision', 'give a decision'], 0),
   ('Why can incorrect collocations make writing sound unnatural, even if the grammar is technically correct?', ['Native speakers expect certain words to be paired together by convention, and unexpected pairings can sound awkward despite being grammatically valid', 'Incorrect collocations always create a grammar error that must be corrected', 'Collocations have no effect on how natural a sentence sounds', 'Every possible word pairing in English is equally natural and common'], 0),
   ('Which of the following is an example of a strong verb-noun collocation?', ['pay attention', 'put attention', 'make attention', 'do attention'], 0),
   ('How can reading widely help a writer learn natural collocations?', ['Repeated exposure to how words are commonly paired together in authentic text builds an intuitive sense of natural word combinations', 'Reading has no effect on a writers understanding of natural word pairings', 'Collocations can only be learned by memorizing a single fixed list with no exposure to real text', 'Every collocation is used so rarely that reading provides no useful exposure'], 0)]),
M('Financial Literacy: Retirement Savings, RRSPs, and TFSAs',
  'Grade 9 Math strand: an RRSP (Registered Retirement Savings Plan) and a TFSA (Tax-Free Savings Account) are two common Canadian savings accounts that offer different tax advantages for long-term saving, and understanding how contributions, withdrawals, and taxation differ between them supports informed financial planning for retirement.',
  [('What is the main purpose of a Registered Retirement Savings Plan (RRSP)?', ['To help individuals save for retirement while receiving certain tax advantages', 'To provide a short-term loan with no connection to retirement savings', 'An RRSP has no defined financial purpose of any kind', 'To guarantee an individual will never pay any tax for the rest of their life'], 0),
   ('What is a key tax advantage commonly associated with a Tax-Free Savings Account (TFSA)?', ['Investment growth and withdrawals from a TFSA are generally not subject to additional tax', 'Every dollar deposited into a TFSA is taxed at the highest possible rate', 'A TFSA offers no tax advantage of any kind compared to a regular savings account', 'Withdrawals from a TFSA are always taxed twice'], 0),
   ('How does an RRSP contribution typically affect taxable income in the year it is made?', ['It can reduce taxable income for that year, since RRSP contributions are generally tax-deductible', 'RRSP contributions always increase taxable income for that year', 'RRSP contributions have no effect on taxable income in any year', 'An RRSP contribution guarantees a full tax refund with no other conditions'], 0),
   ('Why might understanding the difference between an RRSP and a TFSA be useful when planning long-term savings?', ['Each account offers different tax treatment and rules, so choosing between them can affect how much of a persons savings growth is available in the future', 'An RRSP and a TFSA are always identical in every respect, so the choice never matters', 'Long-term savings decisions have no connection to the type of account used', 'Only one of these two account types has ever existed in Canada'], 0),
   ('How do RRSPs and TFSAs both support the broader financial literacy goal of planning for the future, studied throughout this course?', ['Both accounts are tools that can help individuals grow savings over time using different tax rules, supporting informed long-term financial decision-making', 'These accounts have no connection to broader financial planning skills', 'Financial literacy has no relevance to choosing a savings account', 'RRSPs and TFSAs are used exclusively for short-term daily spending'], 0)]),
Sc('Chemistry: Catalysis and the Haber Process for Ammonia Production',
   'Grade 9 Science strand: a catalyst is a substance that speeds up a chemical reaction without being consumed in the process, and the Haber process uses an iron catalyst along with controlled temperature and pressure to combine nitrogen and hydrogen gas into ammonia, a reaction essential to producing synthetic fertilizer.',
   [('What is a catalyst?', ['A substance that speeds up a chemical reaction without being consumed in the process', 'A substance that always slows down a chemical reaction significantly', 'A substance that is permanently used up during every chemical reaction', 'A catalyst has no effect on the rate of any chemical reaction'], 0),
    ('What two gases are combined during the Haber process?', ['Nitrogen and hydrogen', 'Oxygen and carbon dioxide', 'Helium and neon', 'Chlorine and fluorine'], 0),
    ('What catalyst is commonly used in the Haber process?', ['Iron', 'Gold', 'Silver', 'No catalyst is used at any point in the Haber process'], 0),
    ('What important product results from the Haber process, and why is it significant?', ['Ammonia, which is essential for producing synthetic fertilizer used in large-scale agriculture', 'Table salt, which has no connection to agricultural fertilizer', 'The Haber process produces no useful product of any kind', 'Pure oxygen, used only in industrial welding'], 0),
    ('Why are controlled temperature and pressure important in the Haber process, in addition to the iron catalyst?', ['Specific conditions of temperature and pressure help maximize the yield of ammonia while keeping the reaction rate practical for industrial production', 'Temperature and pressure have no effect on the outcome of the Haber process', 'The reaction proceeds identically regardless of temperature or pressure conditions', 'Controlling temperature and pressure always prevents any ammonia from forming'], 0)]),
SS('Social Studies: The Geography of Lighthouse Networks and Maritime Navigation History',
   'Grade 9 Social Studies (Geography) strand: lighthouses were historically built at strategically hazardous coastal locations, such as headlands, reefs, and harbour entrances, to guide ships safely and prevent shipwrecks, and their placement reflects a careful geographic understanding of dangerous coastal features and shipping routes.',
   [('Why were lighthouses historically built at specific coastal locations?', ['To guide ships safely and prevent shipwrecks at strategically hazardous locations', 'Lighthouses were built at completely random locations with no connection to coastal hazards', 'Lighthouses have never been connected to maritime safety in any way', 'They were built only as decorative structures with no navigational purpose'], 0),
    ('What types of coastal features were lighthouses commonly built near?', ['Headlands, reefs, and harbour entrances', 'Only the exact centre of a countrys largest city', 'Locations completely inland, far from any coastline', 'Lighthouses were built only in the middle of open ocean with no nearby coastal feature'], 0),
    ('How does lighthouse placement reflect an understanding of geography and shipping routes?', ['Lighthouses were positioned based on knowledge of dangerous coastal features and the routes ships commonly travelled', 'Lighthouse placement has no connection to geography or shipping routes', 'Lighthouses were placed without any consideration of where ships actually travelled', 'Every lighthouse in history was built in an identical location with no variation'], 0),
    ('How did the development of modern satellite navigation technology affect the role of traditional lighthouses?', ['It reduced reliance on lighthouses for primary navigation, though many remain in use as a backup or for historical and safety reasons', 'Modern navigation technology had no effect on the role of lighthouses', 'Lighthouses became more essential to primary navigation after satellite technology was developed', 'All lighthouses were immediately destroyed once satellite navigation became available'], 0),
    ('Why might historians and geographers study the network of historic lighthouses along a coastline together, rather than as isolated structures?', ['Examining the network reveals broader patterns in historic shipping routes, trade, and the geographic hazards that shaped maritime activity in a region', 'Lighthouses have no connection to broader patterns of trade or shipping routes', 'Every lighthouse network functions in complete isolation with no relationship to nearby structures', 'Studying lighthouse networks provides no insight into historical geography'], 0)]),
]),
day(183, [
L('Reading: Analyzing Bathos and Anticlimax in Narrative',
  'Grade 9 Language strand: bathos is an abrupt and unintentional (or comically intentional) shift from a serious, elevated tone to something trivial or absurd, while anticlimax occurs when a build-up of tension resolves in a disappointing or deflating way, a technique authors sometimes use deliberately for comic or ironic effect.',
  [('What is bathos?', ['An abrupt shift from a serious, elevated tone to something trivial or absurd', 'A gradual build toward an emotionally satisfying and dramatic conclusion', 'A literary device that always increases tension without any resolution', 'A term used only to describe changes in a characters physical appearance'], 0),
   ('What is anticlimax?', ['A resolution to a build-up of tension that feels disappointing or deflating rather than dramatic', 'A resolution that always exceeds the tension built up beforehand', 'A term with no connection to how a narrative resolves tension', 'An event that always occurs at the very beginning of a story'], 0),
   ('Why might an author use bathos deliberately in a narrative?', ['To create a comic or ironic effect by undercutting a serious moment with something trivial', 'Bathos is always an accident and is never used deliberately by an author', 'Bathos always makes a serious scene feel more dramatic and intense', 'Authors are forbidden from using bathos in any published work'], 0),
   ('How does anticlimax typically affect a readers expectations built up during rising action?', ['It deliberately fails to deliver the dramatic payoff the rising action seemed to promise', 'It always delivers exactly the dramatic payoff a reader expects', 'Anticlimax has no relationship to a readers expectations', 'Anticlimax only occurs before any rising action has taken place'], 0),
   ('How can recognizing bathos or anticlimax deepen a readers understanding of an authors purpose?', ['It can reveal that the author is using tone or structure deliberately to create humour, irony, or social commentary rather than a conventional dramatic payoff', 'Recognizing these techniques never reveals anything about an authors purpose', 'Bathos and anticlimax are always signs of a poorly written narrative with no deliberate purpose', 'These techniques only appear in narratives with no serious moments at all'], 0)]),
M('Statistics: An Introduction to Hypothesis Testing',
  'Grade 9 Math strand: hypothesis testing is a statistical method used to evaluate whether observed data provides enough evidence to reject a null hypothesis, a default assumption of no effect or no difference, in favour of an alternative hypothesis.',
  [('What is the purpose of hypothesis testing in statistics?', ['To evaluate whether observed data provides enough evidence to reject a null hypothesis in favour of an alternative hypothesis', 'To guarantee that a researchers initial assumption is always correct', 'Hypothesis testing has no defined purpose in statistical analysis', 'To calculate the exact mean of an entire population with complete certainty'], 0),
   ('What does the null hypothesis typically represent?', ['A default assumption of no effect or no difference', 'A hypothesis that is always proven true before any data is collected', 'A hypothesis that assumes a large and significant effect exists', 'The null hypothesis has no defined meaning in statistics'], 0),
   ('What is the alternative hypothesis in a hypothesis test?', ['A statement proposing that a real effect or difference exists, contrary to the null hypothesis', 'A statement that is always identical to the null hypothesis', 'A hypothesis that is never tested against any data', 'A hypothesis that assumes no data was ever collected'], 0),
   ('Why might a researcher fail to reject the null hypothesis after analyzing their data?', ['The observed data may not provide strong enough evidence to conclude that a real effect or difference exists', 'Failing to reject the null hypothesis always proves it is definitely true', 'Researchers are required to reject the null hypothesis regardless of the data collected', 'This outcome has no meaning in the context of hypothesis testing'], 0),
   ('How does hypothesis testing build on the study of the central limit theorem examined earlier in this course?', ['Understanding how sample means behave and approximate a normal distribution helps determine how likely an observed result would be if the null hypothesis were true', 'Hypothesis testing has no connection whatsoever to the central limit theorem', 'The central limit theorem eliminates the need for any hypothesis testing', 'Hypothesis testing can only be performed without any reference to sample distributions'], 0)]),
Sc('Physics: Kirchhoffs Current and Voltage Laws',
   'Grade 9 Science strand: Kirchhoffs current law states that the total current flowing into a junction in a circuit equals the total current flowing out, while Kirchhoffs voltage law states that the sum of voltage changes around any closed loop in a circuit equals zero, both essential tools for analyzing complex circuits.',
   [('What does Kirchhoffs current law state about a junction in a circuit?', ['The total current flowing into the junction equals the total current flowing out', 'Current flowing into a junction is always greater than current flowing out', 'No current can ever flow through a junction in a circuit', 'Kirchhoffs current law applies only to circuits with a single component'], 0),
    ('What does Kirchhoffs voltage law state about a closed loop in a circuit?', ['The sum of voltage changes around the loop equals zero', 'The sum of voltage changes around a closed loop always equals the total current in the circuit', 'Voltage never changes at any point within a closed loop', 'Kirchhoffs voltage law applies only to circuits with no closed loops'], 0),
    ('Why are Kirchhoffs laws especially useful when analyzing a complex circuit with multiple branches?', ['They provide systematic rules for relating current and voltage at junctions and around loops, even when a circuit cannot be simplified into a single loop', 'Kirchhoffs laws can only be applied to circuits with a single component and no branches', 'Complex circuits with multiple branches cannot be analyzed using any consistent rule', 'Kirchhoffs laws have no practical application in circuit analysis'], 0),
    ('How does Kirchhoffs current law relate to the conservation of electric charge?', ['It reflects the principle that electric charge is conserved, so charge entering a junction cannot simply disappear', 'Kirchhoffs current law has no connection to the conservation of electric charge', 'Electric charge is regularly created or destroyed at a circuit junction', 'Conservation of charge only applies to circuits with no junctions'], 0),
    ('How do Kirchhoffs laws build on the earlier study of series and parallel circuits in this course?', ['They provide more general rules that can be applied to analyze circuits combining series and parallel elements in more complex configurations', 'Kirchhoffs laws have no connection to series and parallel circuits studied earlier', 'These laws can only be applied to circuits with no series or parallel elements', 'Kirchhoffs laws replace the need to understand series and parallel circuits entirely'], 0)]),
SS('Social Studies: The Geography of River Basin Management and Watershed Planning',
   'Grade 9 Social Studies (Geography) strand: a watershed is the area of land that drains into a particular river, lake, or other body of water, and river basin management coordinates land use, water quality protection, and resource allocation across an entire watershed, often requiring cooperation among multiple communities or jurisdictions.',
   [('What is a watershed?', ['The area of land that drains into a particular river, lake, or other body of water', 'A structure built specifically to store drinking water underground', 'A term used only to describe land that never drains into any body of water', 'A watershed refers only to the exact centre point of a river'], 0),
    ('What is the general goal of river basin management?', ['To coordinate land use, water quality protection, and resource allocation across an entire watershed', 'To ensure that no communities ever cooperate on managing a shared watershed', 'River basin management has no connection to water quality or land use', 'To eliminate all human use of water within a watershed permanently'], 0),
    ('Why might river basin management require cooperation among multiple communities or jurisdictions?', ['A single watershed often spans multiple political boundaries, so decisions made upstream can affect water quality and supply downstream', 'A watershed always remains entirely within a single, isolated jurisdiction', 'Upstream activities never have any effect on downstream communities', 'Cooperation between jurisdictions is never necessary for managing a watershed'], 0),
    ('How can land use decisions, such as farming or construction, within a watershed affect water quality in a connected river or lake?', ['Runoff from these activities can carry pollutants, sediment, or excess nutrients into nearby waterways, affecting the entire watershed', 'Land use decisions within a watershed have no effect on nearby water quality', 'Runoff from farming or construction never reaches any connected river or lake', 'Water quality is entirely unrelated to how land within a watershed is used'], 0),
    ('Why do geographers consider watershed boundaries, rather than only political boundaries, when planning resource management?', ['Watershed boundaries reflect the natural flow of water across land, which often does not align with political borders but strongly influences how resources and pollution move through a region', 'Watershed boundaries and political boundaries always align perfectly with no exceptions', 'Natural water flow has no relevance to planning resource management', 'Political boundaries are always more important than natural geography in every planning decision'], 0)]),
]),
day(184, [
L('Writing: Writing a Toast or Celebratory Speech',
  'Grade 9 Language strand: a toast or celebratory speech is a brief, occasion-specific piece of spoken writing that honours a person or event, typically combining a warm or humorous personal anecdote with a sincere closing message, and is crafted to be heard aloud rather than read silently.',
  [('What is the main purpose of a toast or celebratory speech?', ['To honour a person or event through a brief, occasion-specific piece of spoken writing', 'To provide a lengthy, detailed technical report on an unrelated subject', 'To criticize the person or event being celebrated', 'A toast has no defined purpose in spoken communication'], 0),
   ('What combination of content does an effective toast typically include?', ['A warm or humorous personal anecdote paired with a sincere closing message', 'Only a list of statistics with no personal anecdote included', 'A lengthy academic argument with no connection to the person being honoured', 'An anecdote about a completely unrelated person or event'], 0),
   ('Why is it important for a toast to be crafted for the ear rather than the eye?', ['A toast is meant to be heard aloud, so its rhythm, pacing, and clarity when spoken matter more than how it appears in written form', 'A toast is always read silently by the audience rather than spoken aloud', 'The way a toast sounds when spoken has no importance at all', 'A toast should always be written using only complex academic vocabulary'], 0),
   ('Why might a speaker keep a toast relatively brief?', ['A brief toast helps maintain audience attention and fits the celebratory pace of the occasion', 'A toast is always required to last for a very long, detailed period of time', 'Brevity has no effect on how an audience receives a spoken toast', 'A toast should always include as much unrelated information as possible'], 0),
   ('How does a toast differ from a eulogy, studied earlier in this course?', ['A toast typically celebrates a joyful occasion with a warm or humorous tone, while a eulogy honours someone who has died with a more reflective and solemn tone', 'A toast and a eulogy are always identical in tone and purpose', 'A eulogy is always shorter than a typical toast', 'There is no meaningful difference between these two forms of spoken writing'], 0)]),
M('Algebra: Determinants and Inverses of 2x2 Matrices',
  'Grade 9 Math strand: the determinant of a 2x2 matrix is a single scalar value calculated from its entries that indicates whether the matrix has an inverse, and a matrix with a nonzero determinant can be inverted using a formula that divides its adjugate by the determinant.',
  [('What does the determinant of a 2x2 matrix indicate?', ['Whether the matrix has an inverse', 'The exact number of rows contained in the matrix only', 'The colour associated with a matrixs entries', 'A determinant has no mathematical meaning for any matrix'], 0),
   ('Under what condition does a 2x2 matrix fail to have an inverse?', ['When its determinant equals zero', 'When its determinant is a large positive number', 'Every 2x2 matrix always has an inverse regardless of its determinant', 'When the matrix contains only positive entries'], 0),
   ('For a 2x2 matrix with entries a, b, c, and d arranged in the standard form, how is the determinant calculated?', ['By subtracting the product of b and c from the product of a and d', 'By adding all four entries of the matrix together', 'By multiplying all four entries of the matrix together', 'The determinant cannot be calculated using the entries of the matrix'], 0),
   ('What is required to calculate the inverse of a 2x2 matrix using the standard formula?', ['The matrixs determinant must be nonzero, since the formula involves dividing by the determinant', 'The matrixs determinant must always equal exactly zero', 'No calculation involving the determinant is required to find a matrix inverse', 'Only matrices with negative entries can ever be inverted'], 0),
   ('How does finding the determinant and inverse of a 2x2 matrix build on the earlier introduction to matrices in this course?', ['It extends the basic understanding of matrix rows, columns, and operations to a specific calculation used to determine invertibility and solve matrix equations', 'Determinants and inverses have no connection to the earlier introduction to matrices', 'This topic replaces the need to understand matrix rows and columns entirely', 'A matrix inverse can only be found without any reference to its determinant'], 0)]),
Sc('Earth Science: Wave Action and the Formation of Coastal Landforms',
   'Grade 9 Science strand: wave action is the continuous physical process by which ocean waves erode, transport, and deposit sediment along a coastline, gradually shaping landforms such as sea cliffs, sea caves, arches, and sandy beaches over time.',
   [('What is wave action?', ['The continuous physical process by which ocean waves erode, transport, and deposit sediment along a coastline', 'A process that occurs only far offshore, never affecting a coastline directly', 'Wave action has no connection to the shaping of coastal landforms', 'A term used only to describe waves in a swimming pool'], 0),
    ('Which coastal landform can form when wave action erodes a section of a headland into a hollow opening?', ['A sea cave', 'A river delta', 'A sand dune formed entirely by wind, with no wave action involved', 'A glacier'], 0),
    ('How can a sea arch eventually form through continued wave action?', ['Erosion can enlarge a sea cave until it eventually cuts all the way through a headland, leaving an arch-shaped opening', 'A sea arch forms instantly with no gradual erosion process involved', 'Sea arches are formed entirely by volcanic activity, with no connection to wave action', 'Wave action always fills in existing openings rather than enlarging them'], 0),
    ('What role does sediment deposition play in the formation of a sandy beach?', ['Waves transport and deposit sand and other sediment along the shoreline, gradually building up a beach over time', 'Sediment deposition has no role in the formation of any coastal landform', 'Beaches form only through erosion, with no sediment ever deposited', 'Sand is always removed from a coastline with none ever deposited by waves'], 0),
    ('Why can coastal landforms shaped by wave action change noticeably over long periods of time?', ['Continuous erosion, transport, and deposition of sediment gradually reshape a coastline, so landforms are not permanently fixed', 'Coastal landforms shaped by wave action never change once they are formed', 'Wave action stops permanently after a landform is first created', 'Coastlines are entirely unaffected by any ongoing physical process'], 0)]),
SS('Social Studies: The Geography of Amusement Parks and the Leisure Industry',
   'Grade 9 Social Studies (Geography) strand: amusement parks are often located near major population centres or transportation corridors to maximize visitor access, and the leisure industry surrounding them can significantly shape local economies through tourism spending, seasonal employment, and supporting infrastructure such as hotels and roads.',
   [('Why are amusement parks often located near major population centres or transportation corridors?', ['To maximize visitor access and attract as many potential guests as possible', 'Amusement parks are always deliberately built as far as possible from any population centre', 'Location has no effect on how many visitors an amusement park attracts', 'Transportation access is never considered when siting an amusement park'], 0),
    ('How can an amusement park influence the local economy of a surrounding region?', ['Through tourism spending, seasonal employment, and demand for supporting infrastructure such as hotels and roads', 'Amusement parks have no measurable effect on any local economy', 'Local economies are always harmed by the presence of an amusement park', 'Amusement parks eliminate the need for any supporting infrastructure nearby'], 0),
    ('What is a common characteristic of employment associated with the amusement park and leisure industry?', ['It is often seasonal, with staffing levels rising and falling based on visitor demand throughout the year', 'Employment in this industry is always identical every single day of the year', 'Amusement parks never hire any seasonal or temporary staff', 'Leisure industry jobs have no connection to visitor demand'], 0),
    ('Why might a region with a major amusement park also see growth in hotels, restaurants, and other tourism-related businesses?', ['Visitors travelling to the park often need nearby accommodations and services, encouraging additional businesses to develop in the area', 'Amusement park visitors never require any nearby accommodations or services', 'Tourism-related businesses always decline in regions near a major amusement park', 'There is no connection between an amusement park and nearby business growth'], 0),
    ('Why do geographers study the location and economic impact of amusement parks as part of the leisure industry?', ['They illustrate how site selection and visitor patterns can shape regional economic development and land use around a major attraction', 'Amusement parks have no connection to the geographic study of the leisure industry', 'Every amusement park in the world has an identical economic impact on its region', 'This topic is considered purely a matter of engineering, not geography'], 0)]),
]),
day(185, [
L('Media Literacy: Analyzing Bias in Photojournalism and Image Selection',
  'Grade 9 Language strand: photojournalism uses images to document and communicate real events, but the specific moment, angle, framing, and caption chosen by an editor can shape how an audience interprets a story, making critical evaluation of image selection an important media literacy skill.',
  [('What is photojournalism?', ['The use of images to document and communicate real events', 'A form of writing that never includes any visual images', 'A genre of fiction focused entirely on invented events', 'A technique used only to edit video, never still photographs'], 0),
   ('How can the specific moment captured in a news photograph shape audience interpretation?', ['A single frozen moment can emphasize one emotion or impression while leaving out the broader context surrounding it', 'A single photograph always shows the complete, unbiased context of an entire event', 'The moment captured in a photograph has no effect on how an audience interprets a story', 'Every news photograph is required to include the full timeline of an event'], 0),
   ('Why is the caption accompanying a news photograph important to consider critically?', ['A caption frames how a viewer should interpret the image, and different wording can shift the impression a viewer forms', 'A caption never influences how a viewer interprets an accompanying photograph', 'Captions are always identical regardless of which publication uses the image', 'Photographs are never published together with a caption of any kind'], 0),
   ('How might the camera angle chosen for a photograph influence audience perception of a subject?', ['An angle can make a subject appear more powerful, vulnerable, sympathetic, or threatening depending on how it is framed', 'Camera angle has no effect whatsoever on how a subject is perceived', 'Every camera angle produces exactly the same impression of a subject', 'Camera angle only matters in video, never in still photography'], 0),
   ('Why is critically evaluating image selection considered an important media literacy skill?', ['Recognizing how editorial choices about images can shape a narrative helps a reader interpret news coverage more critically rather than accepting it at face value', 'Image selection has no connection to how a news story is understood', 'A media-literate reader has no responsibility for how they interpret a photograph', 'Every photograph used in journalism is chosen with no editorial judgment involved'], 0)]),
M('Geometry: The Equation of a Sphere in Three Dimensions',
  'Grade 9 Math strand: the equation of a sphere in three-dimensional space describes every point equidistant from a fixed centre point, following a form similar to the equation of a circle but extended with an additional coordinate to account for the third dimension.',
  [('What does the equation of a sphere describe in three-dimensional space?', ['Every point equidistant from a fixed centre point', 'A single fixed point with no defined radius', 'A flat two-dimensional shape with no depth', 'The equation of a sphere describes no consistent geometric relationship'], 0),
   ('How does the equation of a sphere relate to the equation of a circle studied earlier in this course?', ['It follows a similar form, extended with an additional coordinate to account for the third dimension', 'The equation of a sphere has no relationship to the equation of a circle', 'A sphere and a circle are always described using exactly the same two-dimensional equation', 'The equation of a circle already fully describes a sphere with no changes needed'], 0),
   ('What does the radius in the equation of a sphere represent?', ['The constant distance from every point on the sphere to its centre', 'The total volume enclosed by the sphere', 'The distance between two unrelated spheres', 'The radius has no defined meaning in the equation of a sphere'], 0),
   ('How many coordinates are needed to describe the centre of a sphere in three-dimensional space?', ['Three coordinates', 'One coordinate', 'Two coordinates', 'No coordinates are needed to describe the centre of a sphere'], 0),
   ('Why might understanding the equation of a sphere be useful when extending two-dimensional geometry concepts into three dimensions?', ['It shows how a familiar two-dimensional relationship can be generalized to describe three-dimensional space using an additional coordinate', 'Three-dimensional geometry has no connection to concepts studied in two-dimensional geometry', 'The equation of a sphere cannot be used to represent any real three-dimensional object', 'Extending equations into three dimensions removes the need for a defined centre point'], 0)]),
Sc('Astronomy: Space Telescopes and Observational Astronomy',
   'Grade 9 Science strand: space telescopes orbit above Earths atmosphere, allowing astronomers to observe wavelengths of light that are absorbed or distorted by the atmosphere and to capture images with greater clarity than most ground-based telescopes, expanding our understanding of distant objects in the universe.',
   [('Where are space telescopes positioned relative to Earths atmosphere?', ['Above Earths atmosphere, in orbit around the planet', 'Deep underground, shielded from all forms of light', 'On the surface of the Moon exclusively, with no orbiting telescopes', 'Space telescopes are always located at the bottom of the ocean'], 0),
    ('Why can space telescopes observe wavelengths of light that are difficult to detect from the ground?', ['Earths atmosphere absorbs or distorts certain wavelengths before they reach ground-based telescopes', 'Earths atmosphere has no effect on any wavelength of light reaching a telescope', 'Ground-based telescopes can already detect every wavelength with no atmospheric interference', 'Space telescopes are incapable of detecting any wavelength of light'], 0),
    ('What is one advantage space telescopes generally have over most ground-based telescopes?', ['They can capture images with greater clarity, since they avoid atmospheric distortion', 'Space telescopes always produce blurrier images than ground-based telescopes', 'Space telescopes have no advantage of any kind over ground-based telescopes', 'Ground-based telescopes always produce clearer images than any space telescope'], 0),
    ('How have space telescopes contributed to our understanding of distant objects in the universe?', ['They have provided detailed images and data on galaxies, stars, and other distant objects that would be difficult to observe as clearly from Earths surface', 'Space telescopes have contributed no useful information about distant objects', 'Distant galaxies and stars cannot be observed using any type of telescope', 'Space telescopes are used exclusively to observe objects within Earths own atmosphere'], 0),
    ('Why might astronomers use both space telescopes and ground-based telescopes together in their research?', ['Combining data from both types of telescopes can provide a more complete picture, since each has different strengths depending on the wavelengths and conditions being studied', 'Space telescopes and ground-based telescopes can never be used together in the same research', 'Ground-based telescopes are always made completely obsolete by space telescopes', 'Combining data from different telescopes provides no additional scientific benefit'], 0)]),
SS('Social Studies: The Geography of Postal Codes and Spatial Data Systems',
   'Grade 9 Social Studies (Geography) strand: a postal code is a geographic identifier assigned to a specific area to organize mail delivery, and beyond their original purpose, postal code systems are widely used in spatial data analysis to map demographic trends, plan services, and study patterns across a region.',
   [('What was the original purpose of a postal code system?', ['To organize and streamline mail delivery to a specific geographic area', 'Postal codes were originally created to track international trade agreements', 'Postal codes have no connection to organizing mail delivery of any kind', 'They were created only to identify the population of an entire country'], 0),
    ('Beyond mail delivery, how are postal code systems commonly used today?', ['As a geographic identifier in spatial data analysis to map demographic trends and plan services', 'Postal codes are used only for mail delivery, with no other application', 'Postal code systems have no connection to spatial data analysis of any kind', 'They are used exclusively to determine a countrys national borders'], 0),
    ('How can businesses or governments use postal code data to plan services?', ['By analyzing patterns in postal code data, they can identify areas with particular needs, such as demand for certain services or infrastructure', 'Postal code data provides no useful information for planning any service', 'Businesses and governments are forbidden from using postal code data for planning', 'Every postal code area has identical needs, so no analysis is required'], 0),
    ('Why might postal code boundaries not perfectly align with natural or cultural geographic boundaries?', ['Postal codes are primarily designed around efficient mail delivery routes, which may not match the boundaries of natural features or cultural communities', 'Postal code boundaries always align perfectly with every natural and cultural boundary', 'Postal codes are designed with no consideration of mail delivery efficiency', 'There is no possible mismatch between postal codes and other types of boundaries'], 0),
    ('Why do geographers consider postal code systems a useful tool for spatial data analysis?', ['They provide a consistent, widely available geographic unit that can be used to map and compare data across a region', 'Postal code systems provide no consistent geographic unit useful for analysis', 'Spatial data analysis never makes use of any postal code information', 'Every geographic analysis method is equally effective regardless of the data unit used'], 0)]),
]),
day(186, [
L('Grammar: Varying Sentence Openers for Style and Flow',
  'Grade 9 Language strand: varying sentence openers, such as beginning with a prepositional phrase, an -ing phrase, an adverb, or a subordinate clause instead of always starting with the subject, helps a writer create rhythm, avoid monotony, and emphasize different elements of a sentence.',
  [('Why might a writer vary the way sentences begin throughout a paragraph?', ['To create rhythm, avoid monotony, and emphasize different elements of a sentence', 'Varying sentence openers always makes a paragraph more difficult to understand', 'Every sentence in a paragraph is required to begin with its subject', 'Sentence openers have no effect on the rhythm or flow of a paragraph'], 0),
   ('Which sentence begins with a prepositional phrase rather than its subject?', ['After the storm passed, the streets were quiet.', 'The streets were quiet after the storm passed.', 'The storm passed, and the streets were quiet.', 'Quiet streets remained after the storm passed.'], 0),
   ('What is an example of a sentence that opens with an -ing phrase?', ['Running toward the finish line, she felt a surge of energy.', 'She felt a surge of energy running toward the finish line.', 'She ran toward the finish line and felt a surge of energy.', 'The finish line brought her a surge of energy as she ran.'], 0),
   ('How can beginning a sentence with a subordinate clause affect its emphasis?', ['It can place emphasis on the condition or circumstance described in the subordinate clause before introducing the main idea', 'A subordinate clause can never be placed at the beginning of a sentence', 'Beginning with a subordinate clause always removes all emphasis from a sentence', 'Subordinate clauses have no connection to how a sentence is structured'], 0),
   ('Why might a paragraph that begins every sentence with its subject start to feel monotonous to a reader?', ['Repeating the same sentence structure can create a flat, repetitive rhythm that fails to hold a readers interest', 'Starting every sentence with its subject always creates the most engaging rhythm possible', 'Sentence structure has no connection to how engaging a paragraph feels', 'A paragraph can never feel monotonous regardless of its sentence structure'], 0)]),
M('Calculus Preview: An Introduction to Implicit Differentiation',
  'Grade 9 Math strand: implicit differentiation is a technique used to find the derivative of a relation that is not explicitly solved for one variable in terms of another, applying the chain rule to differentiate both sides of an equation with respect to a single variable.',
  [('What is implicit differentiation used to find?', ['The derivative of a relation that is not explicitly solved for one variable in terms of another', 'The exact numerical value of a variable with no reference to a derivative', 'A method used only to graph a function, never to differentiate it', 'Implicit differentiation has no defined mathematical purpose'], 0),
   ('What rule is applied when using implicit differentiation?', ['The chain rule', 'A rule that ignores every term involving the dependent variable', 'No mathematical rule is applied during implicit differentiation', 'A rule that only applies to functions with a single term'], 0),
   ('Why is implicit differentiation useful for a relation like a circle equation that is not solved for y?', ['It allows the derivative to be found directly without first needing to rewrite the relation explicitly in terms of one variable', 'Implicit differentiation can never be applied to a circle equation', 'A circle equation must always be rewritten explicitly before any derivative can be found', 'Implicit differentiation removes the need for any equation at all'], 0),
   ('When differentiating a term containing y implicitly with respect to x, what additional factor must be included?', ['The derivative of y with respect to x, often written as dy/dx', 'No additional factor is ever needed when differentiating a term containing y', 'The derivative of x with respect to y must always be included instead', 'A constant term must always be added regardless of the original equation'], 0),
   ('How does implicit differentiation build on the earlier introduction to the derivative as a rate of change in this course?', ['It applies the same core concept of a derivative while extending the technique to relations that are not written explicitly as a function of one variable', 'Implicit differentiation has no connection to the earlier introduction to derivatives', 'This technique replaces the need to understand a derivative as a rate of change', 'Implicit differentiation can only be applied to relations with no variables at all'], 0)]),
Sc('Physics: Introduction to Semiconductors and Diodes',
   'Grade 9 Science strand: a semiconductor is a material with electrical conductivity between that of a conductor and an insulator, and a diode is a simple electronic component made from semiconductor material that allows current to flow easily in one direction while strongly resisting flow in the opposite direction.',
   [('How does the electrical conductivity of a semiconductor compare to that of a conductor and an insulator?', ['It falls between the conductivity of a conductor and an insulator', 'A semiconductor always conducts electricity better than any conductor', 'A semiconductor never conducts any electricity under any circumstances', 'Semiconductors and insulators always have exactly identical conductivity'], 0),
    ('What is a diode?', ['A simple electronic component made from semiconductor material that allows current to flow easily in one direction', 'A component that allows current to flow equally well in both directions at all times', 'A diode is a component made only from pure metal, with no semiconductor material involved', 'A component that blocks all electric current in every direction'], 0),
    ('What happens when current attempts to flow through a diode in its resisted direction?', ['The diode strongly resists the flow of current in that direction', 'The diode allows the current to flow through with no resistance at all', 'The diode converts the current entirely into light with no resistance', 'A diode has no effect on current flowing in any direction'], 0),
    ('Why are semiconductor materials, such as silicon, especially useful in modern electronics?', ['Their conductivity can be precisely controlled and modified, making them essential for building components like diodes and transistors', 'Semiconductor materials have no practical application in modern electronics', 'Silicon is used in electronics only because it cannot conduct any electricity', 'Semiconductor conductivity can never be controlled or modified in any way'], 0),
    ('How does the one-directional behaviour of a diode make it useful in a circuit, building on the earlier study of circuits in this course?', ['It can control the direction of current flow, which is useful for tasks such as converting alternating current to direct current', 'A diodes behaviour has no useful application within an electrical circuit', 'A diode always allows current to flow in every direction, providing no directional control', 'Diodes are used exclusively to store electrical energy, with no effect on current direction'], 0)]),
SS('Social Studies: The Geography of Urban Skyscrapers and Vertical City Growth',
   'Grade 9 Social Studies (Geography) strand: as available land in dense urban centres becomes scarce and expensive, cities often grow vertically through the construction of skyscrapers, allowing more residential, office, or commercial space to be created within a limited geographic footprint.',
   [('Why do cities often grow vertically by constructing skyscrapers?', ['Because available land in dense urban centres becomes scarce and expensive, so building upward allows more space within a limited footprint', 'Skyscrapers are built only in cities with abundant, inexpensive available land', 'Vertical growth has no connection to the scarcity or cost of urban land', 'Cities always prefer horizontal expansion over vertical growth regardless of land availability'], 0),
    ('What types of space can skyscrapers provide within a limited urban footprint?', ['Residential, office, or commercial space', 'Skyscrapers can only ever be used for a single, single-purpose function', 'Skyscrapers provide no usable space of any kind', 'They are built exclusively for agricultural use within a city'], 0),
    ('How can vertical city growth affect the density of a citys population within a given area?', ['It can significantly increase population density by allowing more people to live or work within the same amount of land', 'Vertical growth always decreases the number of people who can live within a given area', 'Skyscraper construction has no effect on a citys population density', 'Population density is entirely unrelated to how a citys buildings are structured'], 0),
    ('What is one infrastructure challenge that can accompany rapid vertical growth in a city?', ['Existing transportation, water, and utility systems may need significant upgrades to support the increased density', 'Vertical growth never requires any change to existing infrastructure', 'Infrastructure systems automatically expand with no need for planning or investment', 'Skyscrapers eliminate the need for any transportation or utility systems'], 0),
    ('Why do geographers study vertical city growth alongside horizontal urban sprawl as part of urban geography?', ['Comparing the two patterns helps explain different strategies cities use to accommodate growth within their available land and resources', 'Vertical growth and horizontal sprawl have no connection to each other in urban geography', 'Every city grows using exactly the same strategy regardless of land availability', 'This topic is considered purely a matter of architecture, not geography'], 0)]),
]),
day(187, [
L('Language Review: Conditionals, Collocations, Bathos, and Sentence Openers',
  'Grade 9 Language strand review: students revisit conditional sentences and if-clauses, collocations and natural word pairings, analyzing bathos and anticlimax, analyzing bias in photojournalism, and varying sentence openers from Days 181-186. This review closes out the full 187-day Grade 9 Language curriculum.',
  [('What does a conditional sentence express?', ['A condition and its result, using an if-clause paired with a main clause', 'A statement with no connection to cause and result', 'A command given without any explanation', 'A question that can never be answered with certainty'], 0),
   ('What is a collocation?', ['A combination of words that speakers of a language habitually use together', 'A word that has no relationship to any other word in a sentence', 'A punctuation mark used to join two related clauses', 'A term used only to describe words borrowed from another language'], 0),
   ('What is bathos?', ['An abrupt shift from a serious, elevated tone to something trivial or absurd', 'A gradual build toward an emotionally satisfying and dramatic conclusion', 'A literary device that always increases tension without any resolution', 'A term used only to describe changes in a characters physical appearance'], 0),
   ('What is photojournalism?', ['The use of images to document and communicate real events', 'A form of writing that never includes any visual images', 'A genre of fiction focused entirely on invented events', 'A technique used only to edit video, never still photographs'], 0),
   ('Why might a writer vary the way sentences begin throughout a paragraph?', ['To create rhythm, avoid monotony, and emphasize different elements of a sentence', 'Varying sentence openers always makes a paragraph more difficult to understand', 'Every sentence in a paragraph is required to begin with its subject', 'Sentence openers have no effect on the rhythm or flow of a paragraph'], 0)]),
M('Math Review: Twin Primes, Retirement Savings, Hypothesis Testing, and Implicit Differentiation',
  'Grade 9 Math strand review: students revisit twin primes and the twin prime conjecture, RRSPs and TFSAs, an introduction to hypothesis testing, the equation of a sphere, and implicit differentiation from Days 181-186. This review closes out the full 187-day Grade 9 Math curriculum.',
  [('What defines a pair of twin primes?', ['Two prime numbers that differ by exactly two', 'Two prime numbers that differ by exactly one', 'Two prime numbers that are always identical to each other', 'Any two numbers that happen to be even'], 0),
   ('What is the main purpose of a Registered Retirement Savings Plan (RRSP)?', ['To help individuals save for retirement while receiving certain tax advantages', 'To provide a short-term loan with no connection to retirement savings', 'An RRSP has no defined financial purpose of any kind', 'To guarantee an individual will never pay any tax for the rest of their life'], 0),
   ('What is the purpose of hypothesis testing in statistics?', ['To evaluate whether observed data provides enough evidence to reject a null hypothesis in favour of an alternative hypothesis', 'To guarantee that a researchers initial assumption is always correct', 'Hypothesis testing has no defined purpose in statistical analysis', 'To calculate the exact mean of an entire population with complete certainty'], 0),
   ('What does the equation of a sphere describe in three-dimensional space?', ['Every point equidistant from a fixed centre point', 'A single fixed point with no defined radius', 'A flat two-dimensional shape with no depth', 'The equation of a sphere describes no consistent geometric relationship'], 0),
   ('What is implicit differentiation used to find?', ['The derivative of a relation that is not explicitly solved for one variable in terms of another', 'The exact numerical value of a variable with no reference to a derivative', 'A method used only to graph a function, never to differentiate it', 'Implicit differentiation has no defined mathematical purpose'], 0)]),
Sc('Science Review: Blood Types, the Haber Process, Kirchhoffs Laws, and Semiconductors',
   'Grade 9 Science strand review: students revisit blood types and the ABO/Rh system, catalysis and the Haber process, Kirchhoffs current and voltage laws, space telescopes, and semiconductors and diodes from Days 181-186. This review closes out the full 187-day Grade 9 Science curriculum.',
   [('What determines a persons blood type in the ABO system?', ['The presence or absence of specific antigens on red blood cells', 'The persons age at the time blood is tested', 'The colour of the persons blood, which varies between types', 'Blood type is determined entirely by random chance with no biological basis'], 0),
    ('What is a catalyst?', ['A substance that speeds up a chemical reaction without being consumed in the process', 'A substance that always slows down a chemical reaction significantly', 'A substance that is permanently used up during every chemical reaction', 'A catalyst has no effect on the rate of any chemical reaction'], 0),
    ('What does Kirchhoffs current law state about a junction in a circuit?', ['The total current flowing into the junction equals the total current flowing out', 'Current flowing into a junction is always greater than current flowing out', 'No current can ever flow through a junction in a circuit', 'Kirchhoffs current law applies only to circuits with a single component'], 0),
    ('Where are space telescopes positioned relative to Earths atmosphere?', ['Above Earths atmosphere, in orbit around the planet', 'Deep underground, shielded from all forms of light', 'On the surface of the Moon exclusively, with no orbiting telescopes', 'Space telescopes are always located at the bottom of the ocean'], 0),
    ('How does the electrical conductivity of a semiconductor compare to that of a conductor and an insulator?', ['It falls between the conductivity of a conductor and an insulator', 'A semiconductor always conducts electricity better than any conductor', 'A semiconductor never conducts any electricity under any circumstances', 'Semiconductors and insulators always have exactly identical conductivity'], 0)]),
SS('Social Studies Review: Cemeteries, Lighthouses, Watersheds, and Skyscrapers',
   'Grade 9 Social Studies (Geography) strand review: students revisit urban cemeteries and land use, lighthouse networks and maritime navigation, river basin management and watersheds, postal codes and spatial data, and vertical city growth from Days 181-186. This final review closes out the full 187-day Grade 9 Social Studies curriculum, completing the entire K-12 Grade 9 course build.',
   [('Why can urban cemeteries present a land use challenge in growing cities?', ['They occupy significant land that could otherwise be used for housing, infrastructure, or other development, creating pressure between preservation and growth', 'Cemeteries never occupy any meaningful amount of land within a city', 'Growing cities never experience any pressure related to limited land availability', 'Urban cemeteries have no connection to the study of land use planning'], 0),
    ('Why were lighthouses historically built at specific coastal locations?', ['To guide ships safely and prevent shipwrecks at strategically hazardous locations', 'Lighthouses were built at completely random locations with no connection to coastal hazards', 'Lighthouses have never been connected to maritime safety in any way', 'They were built only as decorative structures with no navigational purpose'], 0),
    ('What is a watershed?', ['The area of land that drains into a particular river, lake, or other body of water', 'A structure built specifically to store drinking water underground', 'A term used only to describe land that never drains into any body of water', 'A watershed refers only to the exact centre point of a river'], 0),
    ('What was the original purpose of a postal code system?', ['To organize and streamline mail delivery to a specific geographic area', 'Postal codes were originally created to track international trade agreements', 'Postal codes have no connection to organizing mail delivery of any kind', 'They were created only to identify the population of an entire country'], 0),
    ('Why do cities often grow vertically by constructing skyscrapers?', ['Because available land in dense urban centres becomes scarce and expensive, so building upward allows more space within a limited footprint', 'Skyscrapers are built only in cities with abundant, inexpensive available land', 'Vertical growth has no connection to the scarcity or cost of urban land', 'Cities always prefer horizontal expansion over vertical growth regardless of land availability'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g9_181_187)
    append_to(9, g9_181_187)
