#!/usr/bin/env python3
"""Grade 12, Days 91-100 -- extends Grade 12 from 90 to 100 days. Topics
chosen to avoid any overlap with the existing Day 1-90 set (see
data/grade12.json): deconstruction and the instability of meaning, the
Künstlerroman, flash fiction, the found poem, the Verfremdungseffekt in
Brechtian theatre, New Journalism, the palimpsest narrative, the elegy,
and second-person narration; Vieta’s formulas, Cardano’s formula for
cubic equations, the pigeonhole principle, RSA encryption, Catalan
numbers, the AM-GM inequality, Bézout’s identity, Descartes’ rule of
signs, and Stirling’s approximation; double integrals, the ratio test,
line integrals of vector fields, the alternating series test, the
Wronskian, second-order linear differential equations, surface
integrals, the root test, and Taylor’s remainder theorem; the
Michelson-Morley experiment, the Stern-Gerlach experiment, the
Franck-Hertz experiment, the Zeeman effect, cyclotron motion, the
Josephson effect, pulsars, the cosmic microwave background, and quantum
computing.

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as all earlier Grade 12 batches).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
CA12 = 'https://tvolearn.com/pages/grade-12-calculus-and-vectors'
PH12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RCA, RPH = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus and Vectors',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def CA(t, s, q):
    return sub('Calculus', t, s, RCA, CA12, q)


def PH(t, s, q):
    return sub('Physics', t, s, RPH, PH12, q)


def _rebalance_answer_positions(days, seed=20261001):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g12_91_100 = [
day(91, [
E('Literary Theory: Deconstruction and the Instability of Meaning',
  'Grade 12 English strand: deconstruction is a critical approach, associated with Jacques Derrida, that examines the binary oppositions and internal contradictions within a text to show that meaning is unstable and continually deferred rather than fixed.',
  [('What does a deconstructive reading of a text focus on examining?', ['The binary oppositions and internal contradictions within the text', 'Only the exact publication date of the text', 'A concept unrelated to literary theory', 'The font and page layout of the printed edition'], 0),
   ('According to deconstruction, is the meaning of a text considered fixed and singular?', ['No, meaning is considered unstable and continually deferred', 'Yes, deconstruction insists every text has exactly one fixed meaning', 'A concept unrelated to deconstruction', 'Meaning has no connection to how deconstruction reads a text'], 0),
   ('Which of the following best describes an aim of a deconstructive literary analysis?', ['Revealing how a text undermines or contradicts its own apparent claims', 'Summarizing the plot of a text in strict chronological order', 'Counting the total number of words used in a text', 'Identifying only the historical setting in which a text was published'], 0),
   ('Why might a deconstructive critic examine a hierarchical opposition within a text, such as speech versus writing, or reason versus emotion?', ['To show how the privileged term in the pair actually depends on, and is destabilized by, the term it is opposed to', 'Hierarchical oppositions are never examined by any form of literary theory', 'This concept has no connection to literary theory', 'Deconstruction always confirms that the privileged term is entirely independent of its opposite'], 0),
   ('Why has deconstruction been influential, yet also controversial, as a mode of literary criticism?', ['It challenges the idea that texts have a single, stable, author-intended meaning, unsettling more traditional approaches to interpretation', 'Deconstruction has never had any influence on how literary texts are interpreted', 'This concept has no relevance to literary theory', 'Traditional approaches to interpretation are never challenged by any critical theory'], 0)]),
AF('Functions: Vieta’s Formulas — Relating Roots and Coefficients',
   'Grade 12 Advanced Functions strand: Vieta’s formulas relate the coefficients of a polynomial equation to sums and products of its roots, such as the sum of roots equaling negative b over a for a quadratic ax squared plus bx plus c.',
   [('What do Vieta’s formulas relate for a polynomial equation?', ['The polynomial’s coefficients to sums and products of its roots', 'Only the polynomial’s degree to its number of terms', 'A concept unrelated to functions', 'The polynomial’s graph to its colour when plotted'], 0),
    ('For the quadratic x² − 7x + 12 = 0, what is the sum of the roots according to Vieta’s formulas?', ['7', '12', '−7', '5'], 0),
    ('For the quadratic x² − 7x + 12 = 0, what is the product of the roots according to Vieta’s formulas?', ['12', '7', '−12', '5'], 0),
    ('For the cubic x³ − 6x² + 11x − 6 = 0 (whose roots are 1, 2, and 3), what is the sum of the roots according to Vieta’s formulas?', ['6', '11', '−6', '3'], 0),
    ('Why is verifying Vieta’s formulas useful as a check after solving a polynomial equation for its roots?', ['It provides an independent numerical check that the found roots are consistent with the original coefficients', 'Vieta’s formulas can never be used to check any solved polynomial equation', 'This concept has no connection to functions', 'Checking roots against coefficients is never a useful step after solving an equation'], 0)]),
CA('Calculus: Double Integrals — Volume Under a Surface',
   'Grade 12 Calculus strand: a double integral of a positive function f(x,y) over a region R computes the volume of the solid lying under the surface z = f(x,y) and above that region, typically evaluated as an iterated integral.',
   [('What does a double integral of a positive function f(x,y) over a region R compute?', ['The volume of the solid under the surface z = f(x,y) and above the region R', 'The slope of the surface at a single point only', 'A concept unrelated to calculus', 'The perimeter of the region R with no reference to the surface'], 0),
    ('How is a double integral typically evaluated over a rectangular region?', ['As an iterated integral, integrating with respect to one variable at a time', 'By measuring the region’s area with a ruler and estimating visually', 'A concept unrelated to double integrals', 'By evaluating the function at a single corner point of the region'], 0),
    ('What is the value of ∫₀¹ ∫₀² (x + y) dy dx?', ['3', '4', '2', '5'], 0),
    ('Why does the order of integration (dx dy versus dy dx) generally not affect the value of a double integral over a rectangular region with a continuous integrand?', ['Fubini’s theorem guarantees the two iterated integrals are equal in this case', 'The order of integration always changes the final numerical value of a double integral', 'This concept has no connection to calculus', 'Continuous integrands can never be integrated in more than one order'], 0),
    ('Why are double integrals useful for computing quantities like the total mass of a flat plate with variable density?', ['Integrating the density function over the plate’s region yields the total mass directly', 'Double integrals have no application to computing the mass of a physical object', 'This concept has no relevance to calculus', 'Variable density can never be incorporated into any integral calculation'], 0)]),
PH('Physics: The Michelson-Morley Experiment and the Search for the Ether',
   'Grade 12 Physics strand: the Michelson-Morley experiment used an interferometer to search for Earth’s motion through a hypothetical luminiferous ether, and its null result provided key evidence for the constancy of the speed of light.',
   [('What was the Michelson-Morley experiment designed to detect?', ['Earth’s motion through a hypothetical medium called the luminiferous ether', 'The exact mass of a single electron', 'A concept unrelated to physics', 'The temperature of the surface of the sun'], 0),
    ('What was the surprising result of the Michelson-Morley experiment?', ['No significant difference in the speed of light was detected in any direction (a null result)', 'A very large difference in the speed of light was detected in every direction tested', 'A concept unrelated to the Michelson-Morley experiment', 'The experiment detected sound waves rather than light waves'], 0),
    ('What device did Michelson and Morley use to precisely compare the speed of light along two perpendicular paths?', ['An interferometer', 'A telescope', 'A concept unrelated to this experiment', 'A voltmeter'], 0),
    ('Why was the null result of the Michelson-Morley experiment significant for the development of special relativity?', ['It provided strong experimental support for the idea that the speed of light is constant for all observers, regardless of relative motion', 'The null result had no connection to any later development in physics', 'This concept has no connection to physics', 'Special relativity was developed with no reference to any experimental result'], 0),
    ('If Earth were moving through a stationary ether, why would scientists have expected light travelling parallel to Earth’s motion to take a measurably different time than light travelling perpendicular to it?', ['An ether wind would be expected to add to or subtract from light’s speed depending on its direction of travel relative to the ether', 'The direction of travel was never expected to have any effect on the measured speed of light', 'This concept has no relevance to physics', 'Light was assumed to travel at a different constant speed in every possible direction with no underlying reason'], 0)]),
]),

day(92, [
E('Literature: The Künstlerroman — The Artist’s Coming-of-Age Novel',
  'Grade 12 English strand: a Künstlerroman is a subtype of the bildungsroman that traces an artist’s growth toward creative and artistic maturity, often dramatizing tension between the artist’s ambitions and conventional social expectations.',
  [('What is a Künstlerroman a specific subtype of?', ['The bildungsroman, or novel of formation', 'The prose poem', 'A concept unrelated to literature', 'The annotated bibliography'], 0),
   ('What does a Künstlerroman specifically trace the development of?', ['An artist’s growth toward creative and artistic maturity', 'A detective’s investigation of a single crime', 'A concept unrelated to the Künstlerroman', 'A nation’s complete political history'], 0),
   ('Which of these would most likely be the central focus of a Künstlerroman?', ['A young painter’s gradual development of an artistic vision and identity', 'A recipe for a traditional regional dish', 'A user manual explaining how to operate new software', 'A weather almanac predicting seasonal rainfall'], 0),
   ('Why might a Künstlerroman be distinguished from a more general bildungsroman even though both track a protagonist’s development?', ['A Künstlerroman specifically centers on the tensions and choices involved in becoming an artist, such as balancing art with social expectation', 'A Künstlerroman never focuses on any protagonist’s development in any way', 'This concept has no connection to literature', 'The bildungsroman and Künstlerroman are always completely identical with no meaningful distinction'], 0),
   ('Why might tension between an artist-protagonist and their surrounding society be a recurring theme within the Künstlerroman genre?', ['The artist’s unconventional perspective or ambitions often puts them at odds with more conventional social expectations', 'Artist-protagonists in this genre are never in any tension with their surrounding society', 'This concept has no relevance to literature', 'Social expectations have no connection to how an artist’s development is portrayed'], 0)]),
AF('Functions: Cardano’s Formula for Solving Cubic Equations',
   'Grade 12 Advanced Functions strand: Cardano’s formula solves a depressed cubic equation of the form t³ + pt + q = 0, and its use of square roots of negative numbers even for equations with three real roots played a key historical role in the acceptance of complex numbers.',
   [('What type of cubic equation does Cardano’s formula directly solve?', ['A depressed cubic of the form t³ + pt + q = 0 (with no squared term)', 'Any equation of exactly degree one', 'A concept unrelated to functions', 'An equation containing no variable terms at all'], 0),
    ('To convert a general cubic x³ + bx² + cx + d = 0 into depressed form, what substitution is used?', ['x = t − b/3', 'x = t + b', 'A concept unrelated to Cardano’s formula', 'x = t², squaring the original variable'], 0),
    ('The depressed cubic t³ − 3t + 2 = 0 factors as (t − 1)²(t + 2). What does this tell us about its roots?', ['It has a repeated root at t = 1, along with a root at t = −2, not three distinct real roots', 'It has three entirely distinct real roots with no repetition', 'A concept unrelated to Cardano’s formula', 'It has no real roots of any kind'], 0),
    ('In Cardano’s formula, what does encountering a negative value under a square root (requiring complex intermediate steps) typically signal, even when the cubic has three real roots?', ['The formula passes through complex numbers (the casus irreducibilis) even though the final roots are real', 'A negative value under the square root always means the cubic has no real roots at all', 'This concept has no connection to functions', 'Complex numbers are never involved in any step of solving a cubic equation'], 0),
    ('Why is Cardano’s formula historically significant in the development of complex numbers?', ['It forced mathematicians to work with square roots of negative numbers to obtain real solutions, motivating acceptance of complex numbers', 'Cardano’s formula never required any use of square roots of negative numbers', 'This concept has no relevance to functions', 'Complex numbers were fully accepted by mathematicians long before Cardano’s formula was developed'], 0)]),
CA('Calculus: The Ratio Test for Series Convergence',
   'Grade 12 Calculus strand: the ratio test examines the limit L of the absolute value of the ratio of consecutive terms of a series, concluding absolute convergence when L is less than 1, divergence when L is greater than 1, and remaining inconclusive when L equals 1.',
   [('What does the ratio test use to determine whether a series converges?', ['The limit of the ratio of consecutive terms’ absolute values', 'The total number of terms in the series', 'A concept unrelated to calculus', 'The colour of the graph representing the series'], 0),
    ('According to the ratio test, if the limit L of |a_(n+1)/a_n| is less than 1, what can be concluded about the series?', ['The series converges absolutely', 'The series always diverges', 'A concept unrelated to the ratio test', 'No conclusion can ever be reached using this test'], 0),
    ('Applying the ratio test to the series Σ n/2ⁿ, what is the limit L of |a_(n+1)/a_n| as n approaches infinity?', ['1/2', '2', '1', '0'], 0),
    ('Based on that limit of 1/2, what does the ratio test conclude about the series Σ n/2ⁿ?', ['The series converges', 'The series diverges', 'A concept unrelated to this series', 'The test provides no conclusion whatsoever in this case'], 0),
    ('Why is the ratio test inconclusive when the limit L equals exactly 1?', ['Both convergent series, like Σ1/n², and divergent series, like Σ1/n, can produce a limit of exactly 1, so another test is needed', 'A limit of exactly 1 always guarantees that a series converges', 'This concept has no connection to calculus', 'A limit of exactly 1 always guarantees that a series diverges'], 0)]),
PH('Physics: The Stern-Gerlach Experiment and Electron Spin',
   'Grade 12 Physics strand: the Stern-Gerlach experiment passed silver atoms through a non-uniform magnetic field and observed the beam split into exactly two discrete spots, providing direct evidence for the quantization of electron spin.',
   [('What did the Stern-Gerlach experiment pass a beam of silver atoms through?', ['An inhomogeneous (non-uniform) magnetic field', 'A perfectly uniform electric field only', 'A concept unrelated to physics', 'A vacuum containing no fields of any kind'], 0),
    ('What was the key surprising observation in the Stern-Gerlach experiment?', ['The beam split into exactly two discrete spots rather than a continuous smear', 'The beam passed through completely undeflected in every trial', 'A concept unrelated to the Stern-Gerlach experiment', 'The beam formed a perfectly continuous, unbroken band with no separation'], 0),
    ('What quantized property of the electron does the Stern-Gerlach experiment provide evidence for?', ['Electron spin (intrinsic angular momentum)', 'The electron’s exact rest mass', 'A concept unrelated to this experiment', 'The electron’s electric charge sign only'], 0),
    ('Why did the classical expectation for the Stern-Gerlach experiment predict a continuous spread of deflection rather than two discrete spots?', ['Classically, the atoms’ magnetic moments could point in any continuous range of directions, producing a continuous range of deflections', 'Classical physics predicted the atoms would experience no deflection whatsoever', 'This concept has no connection to physics', 'Classical physics already predicted exactly two discrete spots before the experiment was performed'], 0),
    ('Why is the Stern-Gerlach experiment considered a foundational demonstration of quantization in quantum mechanics?', ['It showed directly, at a macroscopic detection level, that an atomic property could take only discrete values rather than a continuous range', 'The experiment showed that atomic properties are never quantized in any way', 'This concept has no relevance to physics', 'Quantization had already been fully confirmed through entirely different, unrelated experiments before this one'], 0)]),
]),

day(93, [
E('Writing: Flash Fiction and Radical Compression',
  'Grade 12 English strand: flash fiction is an extremely short narrative form, often under 1000 words, that demands radical compression and careful implication rather than full explanation in order to convey a complete story arc.',
  [('What does flash fiction require in order to convey a complete story in a very limited number of words?', ['Radical compression and careful implication rather than full explanation', 'An extremely detailed, chapter-by-chapter plot outline', 'A concept unrelated to writing', 'A completely unrelated series of disconnected facts'], 0),
   ('Roughly how many words might a piece of flash fiction typically contain?', ['Often under 1000 words, sometimes far fewer', 'Always over 100,000 words', 'A concept unrelated to flash fiction', 'Exactly 50,000 words with no variation'], 0),
   ('Why might a flash fiction writer rely heavily on implication rather than direct explanation of events?', ['Limited space means many details must be suggested rather than fully stated, trusting the reader to infer meaning', 'Implication is never used in any short narrative form', 'This concept has no connection to writing', 'Flash fiction always explains every detail of the story explicitly and at length'], 0),
   ('Which of these best illustrates the demands of flash fiction?', ['A complete story about a couple’s failing marriage told in exactly one hundred words.', 'A five-hundred-page historical epic spanning three generations.', 'A weather report broadcast on the evening news.', 'A textbook chapter summarizing an entire century of history.'], 0),
   ('Why is flash fiction often considered a particularly useful exercise for developing precision in a writer’s prose more broadly?', ['It forces a writer to eliminate anything unnecessary, sharpening word choice and structural economy', 'Flash fiction never requires any particular precision in a writer’s word choice', 'This concept has no relevance to writing', 'Precision in prose is never developed through practising a short narrative form'], 0)]),
AF('Discrete Math: The Pigeonhole Principle',
   'Grade 12 Advanced Functions strand: the pigeonhole principle states that if more items are placed into containers than there are containers, at least one container must hold more than one item, a simple idea with powerful applications in proving existence.',
   [('What does the pigeonhole principle guarantee when more items are placed into containers than there are containers?', ['At least one container must hold more than one item', 'Every container will always hold exactly one item', 'A concept unrelated to discrete math', 'No container will ever hold any item at all'], 0),
    ('If 13 people are in a room, how many of them must share the same birth month, according to the pigeonhole principle (there are 12 months)?', ['At least 2', 'At least 13', 'A concept unrelated to the pigeonhole principle', 'Exactly 12, no more and no fewer'], 0),
    ('A drawer contains socks of 4 different colours. What is the minimum number of socks you must pull out to guarantee a matching pair?', ['5', '4', '2', '8'], 0),
    ('In a group of 367 people, why must at least two people share the same birthday, according to the pigeonhole principle?', ['There are only 366 possible birthdays (including February 29), so with 367 people at least one date must repeat', '367 people can never share any birthday under any circumstances', 'This concept has no connection to functions', 'The pigeonhole principle only ever applies to groups smaller than 100 people'], 0),
    ('Why is the pigeonhole principle useful for proving that something must exist, without needing to explicitly construct an example of it?', ['It shows that a certain outcome is unavoidable purely from counting, even without identifying the specific case that satisfies it', 'The pigeonhole principle can never be used to prove that anything exists', 'This concept has no relevance to functions', 'Proving existence always requires explicitly constructing every possible example first'], 0)]),
CA('Calculus: Line Integrals of Vector Fields and Work',
   'Grade 12 Calculus strand: the line integral of a vector field F along a curve C, written as the integral of F dot dr, computes the work done by a force field as an object moves along that path.',
   [('What physical quantity does the line integral of a force field F along a path C typically represent?', ['The work done by the force as an object moves along the path', 'The exact mass of the object being moved', 'A concept unrelated to calculus', 'The colour of the path being traced'], 0),
    ('How is the line integral of F along a parametrized curve r(t) generally evaluated?', ['By substituting the parametrization and integrating F(r(t)) dot r′(t) over the parameter interval', 'By measuring the curve’s length with a ruler and stopping there', 'A concept unrelated to line integrals', 'By evaluating the field F at a single random point along the curve'], 0),
    ('For a constant force field F = (3, 4) acting on an object moving in a straight line from (0,0) to (2,0), what is the work done, given by the line integral of F dot dr?', ['6', '8', '10', '14'], 0),
    ('Why does a line integral of a vector field depend on the direction in which the curve is traversed?', ['Reversing the direction of travel negates the dot product contribution at each point, flipping the integral’s sign', 'The direction of travel never has any effect on the value of a line integral', 'This concept has no connection to calculus', 'Line integrals always produce the exact same positive value regardless of direction'], 0),
    ('Why is a vector field being described as conservative important for evaluating line integrals of work efficiently?', ['In a conservative field, the line integral depends only on the endpoints, not the specific path taken', 'Conservative fields make line integrals impossible to evaluate by any method', 'This concept has no relevance to calculus', 'The path taken always affects the result even in a conservative field'], 0)]),
PH('Physics: The Franck-Hertz Experiment and Quantized Energy Levels',
   'Grade 12 Physics strand: the Franck-Hertz experiment accelerated electrons through mercury vapour and observed regularly spaced dips in current, confirming that atoms absorb energy only in the discrete amounts predicted by the Bohr model.',
   [('What gas did the original Franck-Hertz experiment use to demonstrate quantized atomic energy levels?', ['Mercury vapour', 'Hydrogen gas', 'A concept unrelated to physics', 'Pure oxygen gas'], 0),
    ('What pattern did Franck and Hertz observe in the current as the accelerating voltage was increased?', ['Regularly spaced dips in current at specific voltage intervals', 'A perfectly smooth, continuously increasing current with no dips', 'A concept unrelated to the Franck-Hertz experiment', 'A current that instantly dropped to zero and never recovered'], 0),
    ('The Franck-Hertz experiment showed regular current dips spaced at approximately 4.9 volts. What does this spacing correspond to physically?', ['The specific energy needed to excite a mercury atom to its first excited state', 'The exact mass of a single mercury atom', 'A concept unrelated to this experiment', 'The total voltage of the entire electrical circuit used'], 0),
    ('Why do electrons lose a very specific amount of kinetic energy when they collide with a mercury atom in this experiment, rather than losing a continuously varying amount?', ['Mercury atoms can only absorb energy in the discrete amount that matches the gap between their allowed energy levels', 'Electrons never lose any kinetic energy when colliding with a mercury atom', 'This concept has no connection to physics', 'Mercury atoms can absorb any arbitrary, continuously varying amount of energy'], 0),
    ('Why is the Franck-Hertz experiment considered strong experimental confirmation of the Bohr model’s prediction of quantized atomic energy levels?', ['It directly demonstrated, through measurable electrical current, that atoms absorb energy only in fixed, discrete amounts rather than continuously', 'The experiment showed that atomic energy levels are entirely continuous with no discrete structure', 'This concept has no relevance to physics', 'The Bohr model had already been fully confirmed by entirely unrelated evidence before this experiment'], 0)]),
]),

day(94, [
E('Literature: The Found Poem — Repurposing Existing Text',
  'Grade 12 English strand: a found poem is created by taking existing non-poetic text, such as a legal notice or advertisement, and reshaping it through selective omission and line breaks into a poem, recontextualizing its meaning.',
  [('What is a found poem created from?', ['Existing non-poetic text that is rearranged into a poem', 'A completely original composition with no source material', 'A concept unrelated to literature', 'A musical score with no accompanying words'], 0),
   ('What techniques might a poet use to transform found text into a found poem?', ['Selective omission and the addition of line breaks to reshape rhythm and emphasis', 'Rewriting every single word of the source text from scratch', 'A concept unrelated to the found poem', 'Translating the source text into an entirely different, unrelated language'], 0),
   ('Which of the following could serve as raw material for a found poem?', ['A set of instructions from a product’s user manual', 'A blank, unused sheet of paper', 'An abstract mathematical proof with no descriptive text', 'A silent musical rest with no accompanying lyrics'], 0),
   ('Why might rearranging an ordinary text, like a legal notice, into a found poem change how a reader experiences its meaning?', ['The new line breaks and structure can draw attention to particular words or phrases and highlight unintended ironies or rhythms', 'Rearranging a text into a found poem never changes how a reader experiences it', 'This concept has no connection to literature', 'Line breaks and structure have no effect on how any text is experienced by a reader'], 0),
   ('Why does the found poem tradition raise interesting questions about authorship and originality?', ['The poet does not invent the words but transforms an existing text’s presentation and context, raising the question of how much of this counts as original creation', 'Found poems are always considered entirely unoriginal with no creative contribution whatsoever', 'This concept has no relevance to literature', 'Questions of authorship and originality never arise in relation to any literary form'], 0)]),
AF('Number Theory: RSA Encryption and Public-Key Cryptography',
   'Grade 12 Advanced Functions strand: RSA encryption relies on the difficulty of factoring the product of two large prime numbers, using Euler’s totient function to generate a public and private key pair for secure communication.',
   [('What mathematical difficulty does the security of RSA encryption rely on?', ['Factoring the product of two large prime numbers', 'Adding two small even numbers together', 'A concept unrelated to number theory', 'Rounding a decimal number to the nearest whole number'], 0),
    ('In RSA, if p = 3 and q = 11, what is n = p × q?', ['33', '14', '3', '11'], 0),
    ('Using p = 3 and q = 11, what is Euler’s totient φ(n) = (p − 1)(q − 1)?', ['20', '33', '14', '30'], 0),
    ('Why must the public exponent e in RSA be chosen so that gcd(e, φ(n)) = 1?', ['So that e has a multiplicative inverse modulo φ(n), which is required to compute the private key d', 'This condition on e is never actually required by the RSA algorithm', 'This concept has no connection to functions', 'The value of φ(n) has no relevance to choosing the public exponent e'], 0),
    ('Why does RSA encryption become vulnerable if quantum computers can efficiently factor large numbers using Shor’s algorithm?', ['RSA’s security depends on factoring being computationally difficult, so an efficient factoring method would undermine that protection', 'RSA’s security has no connection whatsoever to the difficulty of factoring large numbers', 'This concept has no relevance to functions', 'Quantum computers have no potential effect on any existing cryptographic method'], 0)]),
CA('Calculus: The Alternating Series Test and Conditional Convergence',
   'Grade 12 Calculus strand: the alternating series test states that a series of the form the sum of (−1)ⁿ bₙ converges if the terms bₙ eventually decrease and approach zero, and a series that converges this way but not absolutely is called conditionally convergent.',
   [('What two conditions does the alternating series test require the terms bₙ to satisfy for the series to converge?', ['The terms must eventually decrease in magnitude and approach zero', 'The terms must all be exactly equal to one another', 'A concept unrelated to calculus', 'The terms must grow without bound as n increases'], 0),
    ('Does the alternating harmonic series, the sum of (−1)ⁿ⁺¹/n, converge according to the alternating series test?', ['Yes', 'No, it diverges according to the alternating series test', 'A concept unrelated to the alternating series test', 'The alternating series test cannot be applied to this series at all'], 0),
    ('Is the alternating harmonic series absolutely convergent?', ['No, it is only conditionally convergent', 'Yes, it is fully absolutely convergent', 'A concept unrelated to this series', 'Absolute convergence has no connection to this series'], 0),
    ('Why is a series like the alternating harmonic series called conditionally convergent rather than absolutely convergent?', ['It converges only because of the alternating signs cancelling out; the series of absolute values diverges', 'It is called conditionally convergent because every term in the series is identical', 'This concept has no connection to calculus', 'Conditional convergence has no relationship to the behaviour of a series’ absolute values'], 0),
    ('Why can rearranging the terms of a conditionally convergent series change the value the series converges to, or even make it diverge?', ['Because the series does not converge absolutely, its sum is not guaranteed to be independent of the order of its terms', 'Rearranging the terms of any series never has any effect on its sum', 'This concept has no relevance to calculus', 'Conditionally convergent series always sum to the exact same value regardless of term order'], 0)]),
PH('Physics: The Zeeman Effect — Magnetic Splitting of Spectral Lines',
   'Grade 12 Physics strand: the Zeeman effect describes how a single atomic spectral line splits into multiple closely spaced lines when the emitting atoms are placed in an external magnetic field, revealing the quantization of angular momentum.',
   [('What happens to a spectral line when the emitting atoms are placed in an external magnetic field, according to the Zeeman effect?', ['The single spectral line splits into multiple closely spaced lines', 'The spectral line disappears completely with no trace', 'A concept unrelated to physics', 'The spectral line merges together with every other line in the spectrum'], 0),
    ('What atomic property interacting with the external magnetic field causes the Zeeman splitting of spectral lines?', ['The magnetic moment associated with the atom’s orbital and spin angular momentum', 'The atom’s total mass alone, with no reference to any magnetic property', 'A concept unrelated to the Zeeman effect', 'The colour of the light emitted before any field is applied'], 0),
    ('Does the amount of splitting observed in the Zeeman effect generally increase as the strength of the applied magnetic field increases?', ['Yes', 'No, the amount of splitting is always exactly the same regardless of field strength', 'A concept unrelated to the Zeeman effect', 'Magnetic field strength has no connection to the amount of splitting observed'], 0),
    ('Why does the Zeeman effect provide evidence for the quantization of angular momentum within an atom?', ['The magnetic field splits an energy level into a discrete, finite set of separated sublevels rather than a continuous band', 'The Zeeman effect shows that angular momentum in an atom is always perfectly continuous', 'This concept has no connection to physics', 'Angular momentum has no relationship to how spectral lines are split by a magnetic field'], 0),
    ('Why is the Zeeman effect a valuable tool for astronomers studying magnetic fields on the surface of the sun or other stars?', ['The amount of splitting observed in a star’s spectral lines can be used to estimate the strength of its magnetic field', 'The Zeeman effect provides no useful information about magnetic fields on distant stars', 'This concept has no relevance to physics', 'Astronomers have no way of measuring magnetic fields on objects they cannot physically visit'], 0)]),
]),

day(95, [
E('Drama: The Verfremdungseffekt — Brechtian Alienation in Theatre',
  'Grade 12 English strand: the Verfremdungseffekt, associated with Bertolt Brecht, is a theatrical technique designed to prevent audience emotional immersion so that viewers remain critically and intellectually engaged with a play’s social content.',
  [('What is the primary purpose of the Verfremdungseffekt in Brechtian theatre?', ['To prevent the audience from becoming emotionally absorbed, encouraging critical reflection instead', 'To make the audience forget entirely that they are watching a performance', 'A concept unrelated to drama', 'To ensure the audience never thinks critically about the events on stage'], 0),
   ('Which theatrical technique might a director use to create a Verfremdungseffekt?', ['Having actors directly address the audience, breaking the illusion of the fourth wall', 'Hiding the entire stage crew and every technical element from view at all times', 'A concept unrelated to the Verfremdungseffekt', 'Ensuring the lighting never changes throughout the entire performance'], 0),
   ('Does Brechtian theatre generally aim for the audience to lose themselves emotionally in the story, forgetting they are watching a performance?', ['No, it deliberately works against this kind of complete emotional immersion', 'Yes, complete emotional immersion is the primary goal of Brechtian theatre', 'A concept unrelated to Brechtian theatre', 'Emotional immersion has no connection to how Brechtian theatre is staged'], 0),
   ('Why might Brecht have wanted audiences to remain consciously aware that they were watching a constructed performance rather than a seamless illusion of reality?', ['Maintaining critical distance was intended to keep audiences thinking analytically about the social and political issues being staged, rather than being swept up in emotion alone', 'Brecht wanted audiences to be completely unaware that they were watching a performance', 'This concept has no connection to drama', 'Critical distance was never a goal of any theatrical technique Brecht developed'], 0),
   ('Why is the Verfremdungseffekt considered a significant departure from more traditional, immersive theatrical approaches?', ['It intentionally works against theatrical conventions designed to create a convincing illusion, prioritizing intellectual engagement instead', 'The Verfremdungseffekt is identical in every way to traditional, immersive theatrical staging', 'This concept has no relevance to drama', 'Traditional theatrical approaches never attempt to create any kind of illusion for the audience'], 0)]),
AF('Discrete Math: Catalan Numbers and Counting Problems',
   'Grade 12 Advanced Functions strand: the nth Catalan number, given by one over (n plus 1) times the binomial coefficient (2n choose n), counts a wide variety of combinatorial structures, including balanced arrangements of parentheses and binary tree shapes.',
   [('What kind of counting problems do Catalan numbers frequently solve?', ['Problems counting valid arrangements like balanced parentheses or binary tree shapes', 'Problems involving only simple, one-step addition', 'A concept unrelated to discrete math', 'Problems that have no possible numerical solution'], 0),
    ('What is the formula for the nth Catalan number?', ['1/(n+1) multiplied by the binomial coefficient (2n choose n)', 'n multiplied by (n − 1) with no further terms', 'A concept unrelated to Catalan numbers', 'The square root of n, rounded to the nearest whole number'], 0),
    ('What is C₃, the third Catalan number (using n = 3)?', ['5', '10', '20', '4'], 0),
    ('How many distinct ways can 3 pairs of parentheses be validly balanced, given that this count equals the 3rd Catalan number?', ['5', '3', '6', '9'], 0),
    ('Why do Catalan numbers appear in such a wide variety of seemingly unrelated combinatorial problems?', ['Many different structures, such as tree shapes, lattice paths, and bracket sequences, share the same underlying recursive counting pattern', 'Catalan numbers never actually appear in more than a single specific type of counting problem', 'This concept has no relevance to functions', 'Combinatorial problems never share any underlying mathematical pattern with one another'], 0)]),
CA('Calculus: The Wronskian and Linear Independence of Solutions',
   'Grade 12 Calculus strand: the Wronskian of two functions y₁ and y₂, defined as y₁y₂′ minus y₂y₁′, helps determine whether two solutions to a linear differential equation are linearly independent, which is required to form the general solution.',
   [('What does the Wronskian of two functions help determine?', ['Whether the two functions are linearly independent', 'The exact maximum value either function ever reaches', 'A concept unrelated to calculus', 'The colour of each function’s graph'], 0),
    ('What is the formula for the Wronskian of two functions y₁ and y₂?', ['y₁y₂′ − y₂y₁′', 'y₁ + y₂ with no derivatives involved', 'A concept unrelated to the Wronskian', 'y₁ divided by y₂, with no derivatives involved'], 0),
    ('What is the Wronskian of y₁ = eˣ and y₂ = e⁻ˣ, evaluated at a general value of x?', ['−2 (a nonzero constant)', '0 for every value of x', 'e^(2x), a function that grows without bound', '1 for every value of x'], 0),
    ('Since the Wronskian of eˣ and e⁻ˣ is a nonzero constant, what does this indicate about these two solutions to a differential equation?', ['They are linearly independent', 'They are linearly dependent on one another', 'A concept unrelated to this result', 'Linear independence cannot be determined from this result'], 0),
    ('Why is establishing linear independence of solutions important when writing the general solution to a second-order linear differential equation?', ['Two linearly independent solutions are needed so that their combination can represent every possible solution to the equation', 'Linear independence has no relevance to constructing a general solution', 'This concept has no relevance to calculus', 'A single solution is always sufficient to represent every possible solution to any differential equation'], 0)]),
PH('Physics: Cyclotron Motion and Mass Spectrometry',
   'Grade 12 Physics strand: a charged particle moving perpendicular to a uniform magnetic field follows a circular path of radius r = mv/(qB), a relationship used in mass spectrometry to determine a particle’s mass-to-charge ratio.',
   [('What path does a charged particle follow when moving perpendicular to a uniform magnetic field?', ['A circular path', 'A perfectly straight, undeflected line', 'A concept unrelated to physics', 'A path that instantly stops the particle in place'], 0),
    ('What is the formula for the radius of a charged particle’s circular path in a magnetic field, in terms of its mass m, charge q, speed v, and field strength B?', ['r = mv/(qB)', 'r = qB/(mv)', 'A concept unrelated to cyclotron motion', 'r = m + v + q + B, added together with no other operation'], 0),
    ('A proton (mass 1.67×10⁻²⁷ kg, charge 1.6×10⁻¹⁹ C) moves at 2×10⁶ m/s perpendicular to a magnetic field of 0.5 T. What is the approximate radius of its circular path?', ['Approximately 0.042 m (about 4.2 cm)', 'Approximately 4.2 m', 'Approximately 0.42 mm', 'Approximately 420 m'], 0),
    ('Why does the cyclotron frequency of a charged particle in a magnetic field remain independent of the particle’s speed (for non-relativistic speeds)?', ['As speed increases, the radius increases proportionally, so the time to complete one revolution stays the same', 'A faster particle always takes proportionally longer to complete a single revolution', 'This concept has no connection to physics', 'Cyclotron frequency has no mathematical relationship to a particle’s speed or radius'], 0),
    ('Why is measuring the radius of a charged particle’s circular path in a known magnetic field useful in a mass spectrometer?', ['The measured radius allows the particle’s mass-to-charge ratio to be calculated, helping identify the isotope or ion', 'The radius of a particle’s path provides no useful information about its mass or charge', 'This concept has no relevance to physics', 'Mass spectrometers never make use of any magnetic field in their operation'], 0)]),
]),

day(96, [
E('Media Analysis: New Journalism and the Literary Nonfiction Movement',
  'Grade 12 English strand: New Journalism, associated with writers like Tom Wolfe and Truman Capote in the 1960s and 1970s, applies literary techniques such as scene construction and extended dialogue to factual reporting and nonfiction.',
  [('What does New Journalism apply to factual reporting?', ['Literary techniques typically associated with fiction, such as scene construction and extended dialogue', 'Only strict statistical tables with no accompanying narrative text', 'A concept unrelated to media analysis', 'A completely invented, fictional storyline with no factual basis'], 0),
   ('Which literary technique might a New Journalism writer use that a traditional, objective news report would typically avoid?', ['Rendering a subject’s inner thoughts or extended dialogue in a novelistic style', 'Listing only the date and location of an event with no further detail', 'A concept unrelated to New Journalism', 'Citing exclusively official government statistics with no narrative elements'], 0),
   ('With which decade is the rise of New Journalism most closely associated?', ['The 1960s and 1970s', 'The 1920s and 1930s', 'A concept unrelated to New Journalism', 'The 2010s and 2020s'], 0),
   ('Why might a New Journalism piece be considered more subjective than a traditional news report, even though it is still grounded in factual reporting?', ['Its novelistic techniques, like a chosen narrative perspective and selective scene-building, shape the reader’s experience in ways closer to fiction', 'New Journalism pieces are always considered exactly as objective as a traditional wire report', 'This concept has no connection to media analysis', 'Narrative perspective and scene-building have no effect on how a reader experiences a nonfiction text'], 0),
   ('Why did New Journalism spark debate about the boundary between fiction and nonfiction reporting?', ['Its heavy use of scene, dialogue, and narrative shaping raised questions about how much creative license a factual account should allow', 'New Journalism never used any technique that could be associated with fiction writing', 'This concept has no relevance to media analysis', 'The boundary between fiction and nonfiction has never been a subject of any debate in journalism'], 0)]),
AF('Functions: The Arithmetic Mean-Geometric Mean Inequality',
   'Grade 12 Advanced Functions strand: the AM-GM inequality states that for non-negative real numbers, the arithmetic mean is always greater than or equal to the geometric mean, with equality only when all the numbers are equal, making it a useful tool for optimization.',
   [('What does the AM-GM inequality state about non-negative real numbers?', ['Their arithmetic mean is always greater than or equal to their geometric mean', 'Their arithmetic mean is always less than their geometric mean', 'A concept unrelated to functions', 'Their arithmetic mean and geometric mean are never mathematically related in any way'], 0),
    ('For the two numbers 4 and 9, what is their arithmetic mean?', ['6.5', '6', '36', '13'], 0),
    ('For the two numbers 4 and 9, what is their geometric mean?', ['6', '6.5', '36', '13'], 0),
    ('According to AM-GM, when does equality between the arithmetic mean and the geometric mean occur?', ['Only when all the numbers being averaged are equal', 'Only when all the numbers being averaged are negative', 'A concept unrelated to the AM-GM inequality', 'Equality never occurs under any circumstances between these two means'], 0),
    ('Why is the AM-GM inequality a useful tool for solving optimization problems, such as minimizing x + 1/x for x greater than 0?', ['It provides a lower bound for a sum whose product is fixed, achieved when the terms are equal', 'The AM-GM inequality has no application to any optimization problem', 'This concept has no relevance to functions', 'Optimization problems can never make use of any inequality between two averages'], 0)]),
CA('Calculus: Second-Order Linear Differential Equations with Constant Coefficients',
   'Grade 12 Calculus strand: solving ay″ + by′ + cy = 0 involves forming the characteristic equation ar² + br + c = 0, whose roots determine whether the general solution involves distinct exponentials, a repeated exponential, or oscillating sine and cosine terms.',
   [('What equation is formed to solve a second-order linear differential equation with constant coefficients, ay″ + by′ + cy = 0?', ['The characteristic equation ar² + br + c = 0', 'A single linear equation with no squared term of any kind', 'A concept unrelated to calculus', 'An equation involving only the original variable y with no derivatives'], 0),
    ('For the differential equation y″ − 5y′ + 6y = 0, what is its characteristic equation?', ['r² − 5r + 6 = 0', 'r² + 5r − 6 = 0', 'A concept unrelated to this differential equation', '5r − 6 = 0, with no squared term'], 0),
    ('What are the roots of r² − 5r + 6 = 0?', ['r = 2 and r = 3', 'r = −2 and r = −3', 'r = 1 and r = 6', 'r = 5 and r = 6'], 0),
    ('Given the two distinct real roots r = 2 and r = 3, what is the general solution to y″ − 5y′ + 6y = 0?', ['y = C₁e^(2x) + C₂e^(3x)', 'y = C₁e^(5x) + C₂e^(6x)', 'A concept unrelated to this differential equation', 'y = C₁sin(2x) + C₂cos(3x)'], 0),
    ('Why does a characteristic equation with complex conjugate roots produce oscillatory (sine and cosine) terms in the general solution?', ['Euler’s formula converts the complex exponential solutions into equivalent real sinusoidal solutions', 'Complex conjugate roots always produce only exponentially decaying terms with no oscillation', 'This concept has no connection to calculus', 'Oscillatory solutions never arise from any type of characteristic equation'], 0)]),
PH('Physics: The Josephson Effect and Superconducting Quantum Interference',
   'Grade 12 Physics strand: the Josephson effect describes how a supercurrent can tunnel between two superconductors separated by a thin insulating barrier, a quantum tunneling effect involving Cooper pairs that underlies extremely sensitive magnetic field detectors.',
   [('What does the Josephson effect describe occurring between two superconductors separated by a thin insulating barrier?', ['A supercurrent can tunnel across the barrier even with no applied voltage', 'All electrical current is permanently blocked from crossing the barrier', 'A concept unrelated to physics', 'The barrier instantly becomes a perfect electrical insulator with zero current ever flowing'], 0),
    ('What quantum mechanical phenomenon allows current to cross the thin insulating barrier in a Josephson junction?', ['Quantum tunneling of Cooper pairs', 'Ordinary electrical conduction through an open circuit', 'A concept unrelated to the Josephson effect', 'Simple mechanical vibration of the barrier material'], 0),
    ('What are the paired charge carriers responsible for superconductivity, which tunnel across a Josephson junction, called?', ['Cooper pairs', 'Individual free protons', 'A concept unrelated to superconductivity', 'Photon pairs'], 0),
    ('Why is the Josephson effect useful for building extremely sensitive magnetic field detectors known as SQUIDs?', ['The current through a Josephson junction is exquisitely sensitive to small changes in magnetic flux, allowing tiny fields to be measured', 'The Josephson effect has no practical application to detecting magnetic fields', 'This concept has no relevance to physics', 'SQUIDs measure magnetic fields using an entirely unrelated mechanical process'], 0),
    ('Why is the Josephson effect considered a striking demonstration of macroscopic quantum phenomena?', ['A quantum tunneling effect that would normally be confined to microscopic scales produces a measurable current at a macroscopic, laboratory scale', 'The Josephson effect only ever occurs at scales too small to be measured by any instrument', 'This concept has no relevance to physics', 'Quantum tunneling has no connection to any measurable macroscopic phenomenon'], 0)]),
]),

day(97, [
E('Literature: The Palimpsest Narrative — Layered Stories',
  'Grade 12 English strand: borrowing its name from a manuscript reused after its original writing was scraped away, a palimpsest narrative structures a story so that an earlier text or history remains faintly present beneath a newer, overlaid narrative.',
  [('What does the term palimpsest originally refer to?', ['A manuscript whose original writing was scraped away and reused, though faint traces remain', 'A brand-new, never-before-used sheet of paper', 'A concept unrelated to literature', 'A digital file that has never been edited'], 0),
   ('What structural quality defines a palimpsest narrative in literature?', ['An earlier story or history remains faintly present beneath a newer, overlaid narrative', 'The story is told using only a single, isolated timeline with no layering', 'A concept unrelated to the palimpsest narrative', 'Every trace of an earlier story is always completely and permanently erased'], 0),
   ('Which of these best illustrates a palimpsest narrative?', ['A contemporary novel where a character keeps uncovering fragments of a much older, half-erased family history embedded within the present-day story.', 'A user manual explaining how to assemble furniture.', 'A weather report describing tomorrow’s forecast.', 'A grocery list organized by food category.'], 0),
   ('Why might an author use a palimpsest structure to explore themes of memory or colonial history?', ['It can visually and structurally represent how earlier histories continue to shape and show through a present-day narrative, even when suppressed', 'A palimpsest structure never has any connection to themes of memory or history', 'This concept has no connection to literature', 'Earlier histories are always completely irrelevant to any present-day narrative'], 0),
   ('Why does the palimpsest metaphor resonate with postcolonial literature that grapples with layered or erased histories?', ['It captures how a dominant later narrative can partially overwrite an earlier one without ever fully erasing its traces', 'The palimpsest metaphor has no relevance to postcolonial literature of any kind', 'This concept has no relevance to literature', 'Postcolonial literature never engages with the idea of layered or overwritten histories'], 0)]),
AF('Number Theory: Bézout’s Identity and the Extended Euclidean Algorithm',
   'Grade 12 Advanced Functions strand: Bézout’s identity guarantees that the greatest common divisor of two integers a and b can be written as an integer linear combination ax + by, and the extended Euclidean algorithm computes those coefficients x and y.',
   [('What does Bézout’s identity guarantee about the gcd of two integers a and b?', ['It can be written as an integer linear combination ax + by of a and b', 'It is always exactly equal to zero', 'A concept unrelated to number theory', 'It can never be expressed using either a or b'], 0),
    ('What does the extended Euclidean algorithm compute, in addition to the gcd of two numbers?', ['The integer coefficients x and y satisfying Bézout’s identity', 'The exact prime factorization of both numbers', 'A concept unrelated to Bézout’s identity', 'The average of the two numbers being compared'], 0),
    ('Using the extended Euclidean algorithm on a = 99 and b = 78, what is gcd(99, 78)?', ['3', '9', '6', '21'], 0),
    ('Continuing that example, which of the following is a valid Bézout combination expressing gcd(99, 78) = 3?', ['−11(99) + 14(78) = 3', '3(99) − 2(78) = 3', 'A concept unrelated to Bézout’s identity', '1(99) + 1(78) = 3'], 0),
    ('Why is Bézout’s identity foundational to computing modular inverses used in cryptographic algorithms like RSA?', ['When gcd(a,b) = 1, the coefficient x in ax + by = 1 gives the modular inverse of a modulo b', 'Bézout’s identity has no application to computing any kind of modular inverse', 'This concept has no relevance to functions', 'Modular inverses are never required by any cryptographic algorithm'], 0)]),
CA('Calculus: Surface Integrals — Measuring Flux Across a Surface',
   'Grade 12 Calculus strand: a surface integral of a vector field F over a surface S measures the flux of the field passing through that surface, using a vector element of surface area dS that points along the surface’s normal direction.',
   [('What does a surface integral of a vector field F over a surface S typically measure?', ['The flux of the field passing through the surface', 'The exact perimeter of the surface’s boundary', 'A concept unrelated to calculus', 'The colour of the surface being measured'], 0),
    ('What does the quantity dS represent in a surface integral?', ['A vector element of surface area, pointing in the direction normal to the surface', 'A single fixed point located anywhere on the surface', 'A concept unrelated to surface integrals', 'The total volume enclosed underneath the surface'], 0),
    ('For a uniform field F = (0, 0, 5) passing through a flat horizontal surface of area 4 square units lying in the xy-plane, what is the flux ∫∫ₛ F · dS?', ['20', '5', '4', '9'], 0),
    ('Why does the flux of a vector field through a surface depend on the angle between the field and the surface’s normal vector?', ['Only the component of the field aligned with the normal direction contributes to the flux, decreasing as the angle from the normal increases', 'The angle between a field and a surface’s normal vector never affects the calculated flux', 'This concept has no connection to calculus', 'Flux is always determined entirely by the surface’s area alone, regardless of the field’s direction'], 0),
    ('Why are surface integrals important for stating physical laws like Gauss’s law for electric fields?', ['Gauss’s law relates the total electric flux through a closed surface to the enclosed charge, so surface integrals underlie its formal definition', 'Gauss’s law has no mathematical connection to any surface integral', 'This concept has no relevance to calculus', 'Electric flux through a surface can never be expressed using any type of integral'], 0)]),
PH('Physics: Pulsars — Rotating Neutron Stars as Cosmic Lighthouses',
   'Grade 12 Physics strand: a pulsar is a rapidly rotating, highly magnetized neutron star whose misaligned magnetic and rotation axes cause a beam of radiation to sweep past Earth like a lighthouse, producing extremely regular pulses.',
   [('What type of stellar remnant is a pulsar?', ['A rapidly rotating, highly magnetized neutron star', 'A slowly cooling, non-rotating white dwarf', 'A concept unrelated to physics', 'An ordinary main-sequence star like the sun'], 0),
    ('Why do pulsars appear to emit regular pulses of radiation, as observed from Earth?', ['Their beam of radiation sweeps past Earth once per rotation, similar to a lighthouse beam', 'They emit radiation continuously in every direction with no variation at all', 'A concept unrelated to pulsars', 'They emit a single, permanent burst of radiation that never repeats'], 0),
    ('What is required about the alignment of a pulsar’s magnetic axis and rotation axis for the lighthouse-like pulsing effect to be observed?', ['The magnetic axis must be misaligned (not identical) with the rotation axis', 'The magnetic axis and rotation axis must always be perfectly identical', 'A concept unrelated to pulsars', 'The pulsar must have no rotation axis of any kind'], 0),
    ('Why can the extremely regular timing of many pulsars be used as remarkably precise cosmic clocks?', ['Their rotation rates are extremely stable over short timescales, so the pulse intervals remain very consistent', 'Pulsar rotation rates change randomly and unpredictably from moment to moment', 'This concept has no connection to physics', 'Pulsars emit pulses at completely random, unmeasurable intervals'], 0),
    ('Why do pulsars gradually slow down (increase their pulse period) over very long timescales?', ['They lose rotational energy by radiating electromagnetic energy and particles into space', 'Pulsars gain rotational energy over time, causing them to spin increasingly faster', 'This concept has no relevance to physics', 'A pulsar’s rotation rate never changes at all over any timescale'], 0)]),
]),

day(98, [
E('Writing: The Elegy — Poetic Form and the Language of Mourning',
  'Grade 12 English strand: an elegy is a poem of mourning and reflection on death or loss that traditionally moves through stages of grief, praise for the deceased, and eventual consolation.',
  [('What is the traditional subject of an elegy as a poetic form?', ['Mourning and reflection on death or loss', 'A humorous account of an everyday inconvenience', 'A concept unrelated to writing', 'A set of technical instructions for a household task'], 0),
   ('Which of the following elements is traditionally associated with the structure of an elegy?', ['A movement from grief toward eventual consolation or acceptance', 'A structure that begins and ends with identical, unchanging language', 'A concept unrelated to the elegy', 'A strict requirement that no emotion of any kind ever be expressed'], 0),
   ('Which of these would most likely be the subject of an elegy?', ['A poem written in memory of a close friend who has died.', 'A poem celebrating a sports team’s championship victory.', 'A set of assembly instructions for a bookshelf.', 'A weather forecast for the coming week.'], 0),
   ('Why might a poet writing an elegy include praise for the qualities of the person being mourned?', ['Celebrating the deceased’s virtues can honour their memory and help articulate the significance of the loss', 'Praise for the deceased is never included in any traditional elegy', 'This concept has no connection to writing', 'An elegy is required to avoid any positive description of the person being mourned'], 0),
   ('Why might the elegy be considered a form that balances deeply personal emotion with a more universal meditation on mortality?', ['While rooted in a specific loss, elegies often extend into broader reflections on death and the human condition that resonate with any reader', 'Elegies are always confined strictly to personal detail with no broader reflection whatsoever', 'This concept has no relevance to writing', 'Mortality is never a subject that an elegy engages with in any way'], 0)]),
AF('Functions: Descartes’ Rule of Signs',
   'Grade 12 Advanced Functions strand: Descartes’ rule of signs uses the number of sign changes in a polynomial’s coefficients to place an upper bound on its number of positive (or, after substituting −x, negative) real roots.',
   [('What does Descartes’ rule of signs help determine about a polynomial equation?', ['An upper bound on the number of positive real roots, based on sign changes in the coefficients', 'The exact value of every root of the polynomial', 'A concept unrelated to functions', 'The polynomial’s degree, based on its leading coefficient alone'], 0),
    ('For p(x) = x³ − 4x² + x − 6, how many sign changes occur in the sequence of coefficients (1, −4, 1, −6)?', ['3', '1', '2', '0'], 0),
    ('Based on that sign-change count of 3, what are the possible numbers of positive real roots for p(x), according to Descartes’ rule?', ['3 or 1', '3 only, with no other possibility', '0 or 2', '4 or 2'], 0),
    ('To find the possible number of negative real roots of p(x), which substitution does Descartes’ rule require?', ['Replace x with −x and count the sign changes in the resulting polynomial', 'Replace every coefficient with its absolute value before counting sign changes', 'A concept unrelated to Descartes’ rule', 'Set the entire polynomial equal to zero with no further substitution'], 0),
    ('Why is Descartes’ rule of signs useful before attempting to fully solve a higher-degree polynomial equation?', ['It quickly narrows down how many real roots of each sign to expect, guiding the search for actual solutions', 'It has no practical use before attempting to solve a polynomial equation', 'This concept has no relevance to functions', 'It always determines the exact roots of the polynomial without any further work'], 0)]),
CA('Calculus: The Root Test for Series Convergence',
   'Grade 12 Calculus strand: the root test computes the limit L of the nth root of the absolute value of a series’ terms, concluding convergence when L is less than 1 and divergence when L is greater than 1, and is especially useful for terms raised to the nth power.',
   [('What does the root test compute to determine whether a series converges?', ['The limit of the nth root of the absolute value of the terms', 'The sum of the first n terms of the series', 'A concept unrelated to calculus', 'The average value of every term in the series'], 0),
    ('According to the root test, if L, the limit of the nth root of |aₙ|, is greater than 1, what can be concluded?', ['The series diverges', 'The series always converges absolutely', 'A concept unrelated to the root test', 'No conclusion can ever be reached in this case'], 0),
    ('Applying the root test to the series Σ (n/(2n+1))ⁿ, what is the limit of the nth root of |aₙ| as n approaches infinity?', ['1/2', '1', '2', '0'], 0),
    ('Based on that limit of 1/2, what does the root test conclude about the series Σ (n/(2n+1))ⁿ?', ['The series converges', 'The series diverges', 'A concept unrelated to this series', 'The root test provides no conclusion in this case'], 0),
    ('Why is the root test often preferred over the ratio test for series whose terms involve an nth power, like (f(n))ⁿ?', ['Taking the nth root directly cancels the outer exponent, simplifying the limit calculation', 'The root test can never be applied to any series involving an nth power', 'This concept has no relevance to calculus', 'The ratio test always produces a simpler calculation than the root test in every case'], 0)]),
PH('Physics: The Cosmic Microwave Background and the Big Bang',
   'Grade 12 Physics strand: the cosmic microwave background is faint, nearly uniform radiation left over from about 380,000 years after the Big Bang, when the universe cooled enough for neutral atoms to form and photons to travel freely, providing strong evidence for the Big Bang theory.',
   [('What is the cosmic microwave background radiation considered strong evidence for?', ['The Big Bang theory of the universe’s origin', 'The existence of a permanently static, unchanging universe', 'A concept unrelated to physics', 'The idea that the universe has no measurable age at all'], 0),
    ('Approximately how long after the Big Bang did the light we now observe as the cosmic microwave background begin travelling freely through space?', ['About 380,000 years', 'About 13.8 seconds', 'A concept unrelated to the cosmic microwave background', 'About 4.6 billion years'], 0),
    ('What event, known as recombination, allowed photons to begin travelling freely through the universe, eventually forming the cosmic microwave background?', ['Electrons combined with nuclei to form neutral atoms, making the universe transparent to light', 'All matter in the universe instantly disappeared, leaving only empty space', 'A concept unrelated to the cosmic microwave background', 'Stars formed for the very first time, emitting the first ever light'], 0),
    ('Why does the cosmic microwave background appear today as microwave radiation rather than the much higher-energy radiation it was originally emitted as?', ['The expansion of the universe has stretched (redshifted) the wavelength of this radiation over billions of years', 'The radiation has remained at exactly the same wavelength since it was first emitted', 'This concept has no connection to physics', 'Microwave radiation was the original form in which this light was first emitted'], 0),
    ('Why is the near-uniformity of the cosmic microwave background across the entire sky significant for cosmological models of the early universe?', ['It indicates the early universe was extremely close to the same temperature and density everywhere, supporting models of a hot, uniform early state', 'Near-uniformity across the sky provides no useful information about the early universe', 'This concept has no relevance to physics', 'Cosmological models predict the early universe should have been wildly different in temperature from place to place, with no supporting evidence either way'], 0)]),
]),

day(99, [
E('Literature: Second-Person Narration and Reader Address',
  'Grade 12 English strand: second-person narration uses you as the pronoun for its protagonist, directly addressing the reader and creating an unusual sense of intimacy or implication within the events of the story.',
  [('What pronoun does second-person narration primarily use to refer to its protagonist?', ['You', 'He or she', 'A concept unrelated to literature', 'They, used exclusively in the plural'], 0),
   ('What effect can second-person narration create by directly addressing you as the protagonist?', ['A sense of intimacy or implication, positioning the reader as a participant in the events', 'A sense of complete emotional distance with no connection to the reader at all', 'A concept unrelated to second-person narration', 'An effect identical in every way to a purely factual, impersonal report'], 0),
   ('Which of these sentences is an example of second-person narration?', ['You walk into the room, unsure of what you will find.', 'She walked into the room, unsure of what she would find.', 'They walked into the room, unsure of what they would find.', 'The room was entered by an unknown figure.'], 0),
   ('Why might second-person narration feel unusually immersive or even uncomfortable to some readers compared to first- or third-person narration?', ['Being directly addressed as the story’s subject can blur the line between the reader’s own identity and that of the narrated character', 'Second-person narration never creates any sense of immersion for a reader', 'This concept has no connection to literature', 'First-, second-, and third-person narration always produce exactly the same effect on a reader'], 0),
   ('Why is second-person narration considered a relatively uncommon but distinctive stylistic choice in literary fiction?', ['Sustaining direct address to you across an entire narrative is technically challenging and can feel unconventional, making it a notable stylistic departure', 'Second-person narration is the single most common narrative point of view used in fiction', 'This concept has no relevance to literature', 'There is no meaningful stylistic difference between second-person and third-person narration'], 0)]),
AF('Functions: Stirling’s Approximation for Factorials',
   'Grade 12 Advanced Functions strand: Stirling’s approximation estimates n! using the square root of 2πn multiplied by (n/e)ⁿ, becoming proportionally more accurate as n grows large, and is widely used in combinatorics and statistical mechanics.',
   [('What does Stirling’s approximation estimate?', ['The value of a large factorial, n!', 'The exact value of a single prime number', 'A concept unrelated to functions', 'The slope of a randomly chosen straight line'], 0),
    ('What is the general form of Stirling’s approximation for n!?', ['The square root of 2πn, multiplied by (n/e)ⁿ', 'n multiplied by (n − 1), with no exponential term', 'A concept unrelated to Stirling’s approximation', 'The square root of n, with no other factors involved'], 0),
    ('As n becomes very large, what happens to the relative error of Stirling’s approximation compared to the exact value of n!?', ['It shrinks toward zero, meaning the approximation becomes proportionally more accurate', 'It grows without bound, making the approximation increasingly inaccurate', 'A concept unrelated to Stirling’s approximation', 'It remains exactly the same regardless of how large n becomes'], 0),
    ('Why is Stirling’s approximation particularly useful when working with combinatorial expressions like C(2n, n) for large n?', ['Computing exact factorials for huge values of n is impractical, and the approximation simplifies asymptotic analysis of such expressions', 'Stirling’s approximation has no application to any combinatorial expression involving factorials', 'This concept has no relevance to functions', 'Exact factorial values are always trivial to compute for extremely large values of n'], 0),
    ('Why might Stirling’s approximation be considered essential in fields like statistical mechanics, where quantities involving huge factorials frequently appear?', ['It allows practical, workable estimates to be made for quantities that would otherwise require computing enormous, unwieldy exact factorials', 'Statistical mechanics never involves any calculation requiring a factorial of any size', 'This concept has no relevance to functions', 'Huge factorials never appear in any calculation related to physical systems'], 0)]),
CA('Calculus: Taylor’s Remainder Theorem — Bounding the Error of an Approximation',
   'Grade 12 Calculus strand: Taylor’s remainder theorem, in its Lagrange form, bounds the error between a function and its Taylor polynomial approximation using a derivative evaluated at some unknown point c between the centre and the point of approximation.',
   [('What does Taylor’s remainder theorem provide a bound for?', ['The error between a function and its Taylor polynomial approximation', 'The exact value of a function at every possible point', 'A concept unrelated to calculus', 'The total number of terms a Taylor series must contain'], 0),
    ('In the Lagrange form of the remainder, R_n(x) = f^(n+1)(c)/(n+1)! times (x−a)^(n+1), what must be true about c?', ['c lies somewhere between a and x', 'c must always be equal to zero', 'A concept unrelated to Taylor’s remainder theorem', 'c must always be equal to x itself'], 0),
    ('For f(x) = eˣ approximated by its 2nd-degree Taylor polynomial centred at a = 0, evaluated at x = 1, the remainder formula involves (n+1)! in the denominator with n = 2. What is 3!?', ['6', '9', '3', '2'], 0),
    ('Since eˣ’s third derivative is eˣ itself, and e^c is less than e for any c between 0 and 1, why is the remainder R₂(1) for approximating e using a 2nd-degree Taylor polynomial guaranteed to be less than e/6?', ['Because f‴(c) = e^c is bounded above by e on the interval [0,1], giving R₂(1) < e times 1³/3! = e/6', 'The remainder can never be bounded using any property of the function’s derivatives', 'This concept has no connection to calculus', 'e^c grows without any upper bound on the interval between 0 and 1'], 0),
    ('Why is Taylor’s remainder theorem valuable when using a truncated Taylor series to approximate a function for practical computation?', ['It quantifies how many terms are needed to achieve a desired accuracy in the approximation', 'It provides no useful information about the accuracy of a truncated Taylor series', 'This concept has no relevance to calculus', 'Truncated Taylor series are always exactly as accurate as the full, infinite series'], 0)]),
PH('Physics: Quantum Computing and the Qubit',
   'Grade 12 Physics strand: a qubit, the basic unit of quantum information, can exist in a superposition of the states 0 and 1, and entanglement between multiple qubits allows a quantum computer’s state space to grow exponentially with the number of qubits.',
   [('What is the basic unit of information in a quantum computer called?', ['A qubit', 'A classical bit', 'A concept unrelated to physics', 'A photon, with no further defining property'], 0),
    ('What key property allows a qubit to exist in a combination of the states 0 and 1 simultaneously, unlike a classical bit?', ['Superposition', 'Ordinary electrical resistance', 'A concept unrelated to quantum computing', 'Simple mechanical vibration'], 0),
    ('What quantum phenomenon allows the states of two or more qubits to become correlated in ways that have no classical analogue?', ['Entanglement', 'Ordinary magnetic attraction', 'A concept unrelated to quantum computing', 'Simple electrical conduction'], 0),
    ('Why does measuring a qubit that is in a superposition of states cause it to collapse to a single definite value?', ['The act of measurement forces the quantum system into one of its possible definite outcomes, ending the superposition', 'Measurement has no effect whatsoever on a qubit’s quantum state', 'This concept has no connection to physics', 'A qubit always remains in superposition permanently, even after being measured'], 0),
    ('Why can a quantum computer with n entangled qubits, in principle, represent and process information in ways that scale much more powerfully than n classical bits?', ['The system’s state space grows exponentially with the number of qubits due to superposition and entanglement, enabling certain calculations to be parallelized', 'A system of n entangled qubits behaves in exactly the same way as n independent classical bits', 'This concept has no relevance to physics', 'Superposition and entanglement have no effect on how much information a quantum system can represent'], 0)]),
]),

day(100, [
E('Review: Literary Theory, Form, and Voice (Days 91-99)',
  'Grade 12 English strand review: students revisit deconstruction, the Künstlerroman, flash fiction, the found poem, the Verfremdungseffekt, New Journalism, the palimpsest narrative, the elegy, and second-person narration.',
  [('What does a deconstructive reading of a text focus on examining?', ['The binary oppositions and internal contradictions within the text', 'Only the exact publication date of the text', 'A concept unrelated to literary theory', 'The font and page layout of the printed edition'], 0),
   ('What does flash fiction require in order to convey a complete story in a very limited number of words?', ['Radical compression and careful implication rather than full explanation', 'An extremely detailed, chapter-by-chapter plot outline', 'A concept unrelated to writing', 'A completely unrelated series of disconnected facts'], 0),
   ('What is the primary purpose of the Verfremdungseffekt in Brechtian theatre?', ['To prevent the audience from becoming emotionally absorbed, encouraging critical reflection instead', 'To make the audience forget entirely that they are watching a performance', 'A concept unrelated to drama', 'To ensure the audience never thinks critically about the events on stage'], 0),
   ('What does the term palimpsest originally refer to?', ['A manuscript whose original writing was scraped away and reused, though faint traces remain', 'A brand-new, never-before-used sheet of paper', 'A concept unrelated to literature', 'A digital file that has never been edited'], 0),
   ('What pronoun does second-person narration primarily use to refer to its protagonist?', ['You', 'He or she', 'A concept unrelated to literature', 'They, used exclusively in the plural'], 0)]),
AF('Review: Roots, Combinatorics, and Number Theory (Days 91-99)',
   'Grade 12 Advanced Functions strand review: students revisit Vieta’s formulas, Cardano’s formula, the pigeonhole principle, RSA encryption, Catalan numbers, the AM-GM inequality, Bézout’s identity, Descartes’ rule of signs, and Stirling’s approximation.',
   [('What do Vieta’s formulas relate for a polynomial equation?', ['The polynomial’s coefficients to sums and products of its roots', 'Only the polynomial’s degree to its number of terms', 'A concept unrelated to functions', 'The polynomial’s graph to its colour when plotted'], 0),
    ('What does the pigeonhole principle guarantee when more items are placed into containers than there are containers?', ['At least one container must hold more than one item', 'Every container will always hold exactly one item', 'A concept unrelated to discrete math', 'No container will ever hold any item at all'], 0),
    ('What kind of counting problems do Catalan numbers frequently solve?', ['Problems counting valid arrangements like balanced parentheses or binary tree shapes', 'Problems involving only simple, one-step addition', 'A concept unrelated to discrete math', 'Problems that have no possible numerical solution'], 0),
    ('What does Bézout’s identity guarantee about the gcd of two integers a and b?', ['It can be written as an integer linear combination ax + by of a and b', 'It is always exactly equal to zero', 'A concept unrelated to number theory', 'It can never be expressed using either a or b'], 0),
    ('What does Stirling’s approximation estimate?', ['The value of a large factorial, n!', 'The exact value of a single prime number', 'A concept unrelated to functions', 'The slope of a randomly chosen straight line'], 0)]),
CA('Review: Multivariable Calculus and Series Tests (Days 91-99)',
   'Grade 12 Calculus strand review: students revisit double integrals, the ratio test, line integrals of vector fields, the alternating series test, the Wronskian, second-order linear differential equations, surface integrals, the root test, and Taylor’s remainder theorem.',
   [('What does a double integral of a positive function f(x,y) over a region R compute?', ['The volume of the solid under the surface z = f(x,y) and above the region R', 'The slope of the surface at a single point only', 'A concept unrelated to calculus', 'The perimeter of the region R with no reference to the surface'], 0),
    ('What physical quantity does the line integral of a force field F along a path C typically represent?', ['The work done by the force as an object moves along the path', 'The exact mass of the object being moved', 'A concept unrelated to calculus', 'The colour of the path being traced'], 0),
    ('What does the Wronskian of two functions help determine?', ['Whether the two functions are linearly independent', 'The exact maximum value either function ever reaches', 'A concept unrelated to calculus', 'The colour of each function’s graph'], 0),
    ('What does a surface integral of a vector field F over a surface S typically measure?', ['The flux of the field passing through the surface', 'The exact perimeter of the surface’s boundary', 'A concept unrelated to calculus', 'The colour of the surface being measured'], 0),
    ('What does Taylor’s remainder theorem provide a bound for?', ['The error between a function and its Taylor polynomial approximation', 'The exact value of a function at every possible point', 'A concept unrelated to calculus', 'The total number of terms a Taylor series must contain'], 0)]),
PH('Review: Historic Experiments and Cosmic Phenomena (Days 91-99)',
   'Grade 12 Physics strand review: students revisit the Michelson-Morley experiment, the Stern-Gerlach experiment, the Franck-Hertz experiment, the Zeeman effect, cyclotron motion, the Josephson effect, pulsars, the cosmic microwave background, and quantum computing.',
   [('What was the Michelson-Morley experiment designed to detect?', ['Earth’s motion through a hypothetical medium called the luminiferous ether', 'The exact mass of a single electron', 'A concept unrelated to physics', 'The temperature of the surface of the sun'], 0),
    ('What gas did the original Franck-Hertz experiment use to demonstrate quantized atomic energy levels?', ['Mercury vapour', 'Hydrogen gas', 'A concept unrelated to physics', 'Pure oxygen gas'], 0),
    ('What path does a charged particle follow when moving perpendicular to a uniform magnetic field?', ['A circular path', 'A perfectly straight, undeflected line', 'A concept unrelated to physics', 'A path that instantly stops the particle in place'], 0),
    ('What type of stellar remnant is a pulsar?', ['A rapidly rotating, highly magnetized neutron star', 'A slowly cooling, non-rotating white dwarf', 'A concept unrelated to physics', 'An ordinary main-sequence star like the sun'], 0),
    ('What is the basic unit of information in a quantum computer called?', ['A qubit', 'A classical bit', 'A concept unrelated to physics', 'A photon, with no further defining property'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g12_91_100)
    append_to(12, g12_91_100)
