#!/usr/bin/env python3
"""Phase 3: Grade 12, Days 31-40 (first Grade 12 batch, continuing the
10-day pattern used for Grades 3-11). Topics chosen to avoid any overlap
with the existing Day 1-30 set (see data/grade12.json): algorithmic
bias, feminist criticism, matrices, parametric/polar equations,
mathematical induction, rotational motion, fluid mechanics, continuity/
IVT, Taylor series, and Euler's method.

IMPORTANT: Grade 12's subject keys are "English", "AdvancedFunctions",
"Calculus", "Physics" -- confirmed via
grep -o 'subject:"[^"]*"' data/grade12.ts | sort -u -- Ontario Grade 12
splits math/science into individual university-prep courses, same
pattern as Grade 11 but with different course names.

Note: existing data/grade12.json has a pre-existing quirk where Day 30
is missing its Calculus entry (only 3 subjects instead of 4) -- this
predates this batch and is not something this script touches or fixes.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys
sys.path.insert(0, '/sessions/modest-compassionate-lamport/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
C12 = 'https://tvolearn.com/pages/grade-12-calculus'
P12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RC, RP = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def C(t, s, q):
    return sub('Calculus', t, s, RC, C12, q)


def P(t, s, q):
    return sub('Physics', t, s, RP, P12, q)


g12_31_40 = [
day(31, [
E('Media Literacy: Analyzing Algorithmic Bias in News Feeds',
  'Grade 12 English strand: algorithmic bias occurs when the systems that curate content for social media and news feeds systematically favour certain perspectives, shaping what audiences see without their explicit awareness.',
  [('Algorithmic bias occurs when content-curating systems ___.', ['Systematically favour certain perspectives', 'Present every perspective with perfectly equal weight', 'Have no influence on what audiences see', 'Are entirely random with no underlying pattern'], 0),
   ('Why might users be unaware that an algorithm is shaping the content they see?', ['These systems often operate in the background without an obvious explanation of their choices', 'Algorithms always clearly explain every content decision to users', 'Users are always fully aware of every algorithmic choice made', 'This concept has no connection to how content feeds function'], 0),
   ('Why might algorithmic bias contribute to the formation of an “echo chamber”?', ['Repeatedly showing similar content can reinforce a narrower range of existing views', 'Algorithms always show a perfectly balanced range of opposing views', 'Echo chambers have no connection to how content is curated', 'This concept never affects the diversity of content a person sees'], 0),
   ('Why is media literacy around algorithmic bias considered increasingly important?', ['So much of the information people encounter today is shaped by automated curation systems', 'Algorithmic curation has no real impact on the information landscape', 'This topic has no relevance to modern media consumption', 'People today receive information through no automated systems at all'], 0),
   ('Which is a strategy for reducing the effects of algorithmic bias on one’s own understanding of an issue?', ['Deliberately seeking out sources with differing perspectives', 'Relying exclusively on a single automatically curated feed', 'Avoiding any conscious evaluation of where information comes from', 'Assuming every recommended article is fully representative of all views'], 0)]),
AF('Introduction to Matrices',
   'Grade 12 Advanced Functions strand: a matrix is a rectangular array of numbers organized in rows and columns, commonly used to represent and solve systems of equations efficiently.',
   [('A matrix is best described as ___.', ['A rectangular array of numbers organized in rows and columns', 'A single number with no organized structure', 'A concept unrelated to organizing numerical data', 'Only a graph with no numerical values'], 0),
    ('Matrices are commonly used to represent and solve ___.', ['Systems of equations', 'Only single, isolated equations with no system involved', 'A concept unrelated to equations', 'Data with no mathematical structure at all'], 0),
    ('In a matrix, the dimensions are typically described as ___.', ['The number of rows by the number of columns', 'Only the total number of entries, with no other structure', 'A measurement unrelated to rows or columns', 'The number of columns by the number of rows exclusively, with no alternative convention'], 0),
    ('Why might matrices be more efficient than traditional algebraic methods for solving large systems of equations?', ['They organize the coefficients in a structured way, allowing systematic methods to solve many equations at once', 'Matrices are always less efficient than traditional algebraic methods', 'This structure has no advantage for solving systems of equations', 'Large systems of equations can never be solved using matrices'], 0),
    ('Why are matrices useful in fields like computer graphics?', ['They can efficiently represent transformations like scaling, rotation, and translation of objects', 'Matrices have no practical application in computer graphics', 'This mathematical tool has no connection to representing transformations', 'Computer graphics never involve any mathematical representation of transformations'], 0)]),
C('Continuity and the Intermediate Value Theorem',
  'Grade 12 Calculus strand: the Intermediate Value Theorem states that if a function is continuous on a closed interval, it must take on every value between its endpoint values at least once within that interval.',
  [('The Intermediate Value Theorem applies to a function that is ___.', ['Continuous on a closed interval', 'Discontinuous at every point within the interval', 'A concept unrelated to continuity', 'Undefined across its entire domain'], 0),
   ('According to the Intermediate Value Theorem, a continuous function on a closed interval must take on ___.', ['Every value between its endpoint values at least once', 'Only the exact values at its two endpoints, and no values between them', 'No values at all within that interval', 'A value entirely unrelated to its endpoints'], 0),
   ('Why is continuity a required condition for the Intermediate Value Theorem to apply?', ['A discontinuous function could skip over a value between its endpoints', 'Continuity has no connection to whether a function takes on all values between two points', 'The Intermediate Value Theorem applies equally well to any type of function', 'Discontinuous functions always take on every value in an interval regardless'], 0),
   ('Why might the Intermediate Value Theorem be useful for confirming that a function has a root (a zero) within a given interval?', ['If the function changes sign between two endpoints, it must cross zero somewhere in between', 'This theorem has no connection to identifying where a function equals zero', 'A function’s sign changes never provide any useful mathematical information', 'The Intermediate Value Theorem only applies to functions with no roots at all'], 0),
   ('Why is the Intermediate Value Theorem considered a foundational result in calculus?', ['It establishes an important guaranteed property of continuous functions used throughout calculus', 'This theorem has no broader significance in the study of calculus', 'Continuous functions have no special guaranteed properties', 'This result is never applied to any other calculus concepts'], 0)]),
P('Physics: Rotational Motion and Torque',
  'Grade 12 Physics strand: rotational motion describes objects spinning around an axis, and torque is the rotational equivalent of force, describing how effectively a force causes an object to rotate.',
  [('Rotational motion describes objects that are ___.', ['Spinning around an axis', 'Moving only in a perfectly straight line', 'A concept unrelated to motion', 'Completely stationary with no movement at all'], 0),
   ('Torque is best described as the rotational equivalent of ___.', ['Force', 'Mass', 'Only colour, with no connection to motion', 'A concept unrelated to rotational motion'], 0),
   ('Torque depends on both the applied force and ___.', ['The distance from the axis of rotation where the force is applied', 'Only the colour of the object being rotated', 'A factor entirely unrelated to force or distance', 'The temperature of the object exclusively'], 0),
   ('Why does applying a force farther from the axis of rotation generally produce more torque?', ['A greater distance from the axis increases the rotational effect of the same applied force', 'Distance from the axis has no effect on the amount of torque produced', 'Torque is always identical regardless of where a force is applied', 'This relationship has no connection to how rotational motion works'], 0),
   ('Why is understanding torque important in engineering applications like designing a wrench or a door handle?', ['It helps determine how effectively a force will produce rotational motion in a practical design', 'Torque has no relevance to designing tools or mechanical devices', 'Engineering applications never require any understanding of rotational motion', 'This concept has no practical, real-world use'], 0)])]),

day(32, [
E('Literature: Feminist Literary Criticism',
  'Grade 12 English strand: feminist literary criticism examines how gender shapes the representation of characters, themes, and power dynamics within a text, often questioning traditional or patriarchal narrative structures.',
  [('Feminist literary criticism examines how ___ shapes a text.', ['Gender', 'Only the physical setting, with no connection to gender', 'A factor entirely unrelated to representation or power', 'The publication date exclusively'], 0),
   ('This critical approach often questions ___.', ['Traditional or patriarchal narrative structures', 'Only grammar and punctuation choices', 'A concept unrelated to gender or power dynamics', 'The physical formatting of a printed text'], 0),
   ('Which is an example of a question a feminist literary critic might ask about a text?', ['How are female characters represented in relation to power and agency?', 'What font was used in the original printing?', 'A question entirely unrelated to gender or representation', 'How many total pages does the book contain?'], 0),
   ('Why might feminist literary criticism examine whose perspective is centred in a narrative?', ['Whose story is told, and how, can reveal underlying assumptions about gender and power', 'Perspective has no connection to how gender is represented in a text', 'This critical approach never considers whose viewpoint a story reflects', 'Narrative perspective is entirely unrelated to literary analysis'], 0),
   ('Why is feminist literary criticism considered a valuable lens for analyzing texts, even those written long before the approach existed?', ['It can reveal assumptions about gender embedded in a text, regardless of when it was written', 'This critical lens can only be applied to very recently written texts', 'Historical texts have no meaningful gender dynamics to examine', 'This approach has no value for texts from earlier time periods'], 0)]),
AF('Systems of Equations: Solving with Matrices',
   'Grade 12 Advanced Functions strand: matrices provide a systematic method for solving systems of linear equations, often using techniques like row reduction to find the values that satisfy all equations simultaneously.',
   [('Matrices provide a systematic method for solving ___.', ['Systems of linear equations', 'Only a single equation, with no system involved', 'A concept unrelated to solving equations', 'Data with no connection to linear relationships'], 0),
    ('Row reduction is a technique used to ___.', ['Simplify a matrix to help solve a system of equations', 'Add unnecessary complexity to a matrix with no benefit', 'A process unrelated to solving systems of equations', 'Only change the colour of a matrix’s display'], 0),
    ('A solution to a system of equations must satisfy ___.', ['All equations in the system simultaneously', 'Only one single equation, with no connection to the others', 'None of the equations in the system', 'A condition entirely unrelated to the given equations'], 0),
    ('Why might using matrices be more efficient than substitution when solving a system with many variables?', ['Matrix methods provide an organized, systematic process that scales well as the number of equations increases', 'Matrices are always less efficient than substitution for any number of variables', 'Systems with many variables can never be solved using matrices', 'This method has no advantage for larger systems of equations'], 0),
    ('Why are systems of equations solved with matrices relevant to real-world applications, like resource allocation problems?', ['Many real-world problems involve multiple constraints and variables that can be represented as a system of equations', 'Systems of equations have no real-world applications', 'Resource allocation problems never involve multiple variables or constraints', 'This mathematical method only applies to purely abstract, theoretical problems'], 0)]),
C('Derivatives of Inverse Trigonometric Functions',
  'Grade 12 Calculus strand: each inverse trigonometric function, such as arcsine or arctangent, has a specific derivative formula that can be applied when differentiating expressions involving these functions.',
  [('Inverse trigonometric functions include functions such as ___.', ['Arcsine and arctangent', 'Only sine and cosine, with no inverse functions involved', 'A concept unrelated to trigonometry', 'Functions with no connection to angles'], 0),
   ('Each inverse trigonometric function has ___.', ['A specific derivative formula', 'No defined derivative under any circumstances', 'A derivative identical to every other function', 'A formula entirely unrelated to differentiation'], 0),
   ('Why might a problem require using the chain rule alongside an inverse trigonometric derivative formula?', ['If the inverse trigonometric function contains another function as its input, the chain rule accounts for that inner function', 'The chain rule is never required when differentiating inverse trigonometric functions', 'Inverse trigonometric functions can never contain another function as an input', 'This combination of rules has no connection to differentiation'], 0),
   ('Why are the derivatives of inverse trigonometric functions useful in physics problems involving angles, like analyzing motion?', ['These derivatives can help relate rates of change involving angles to other changing quantities', 'Inverse trigonometric derivatives have no application in physics', 'Angles and rates of change have no mathematical relationship', 'This concept only applies to purely abstract mathematics with no physical application'], 0),
   ('Why is memorizing the derivative formulas for inverse trigonometric functions useful for solving calculus problems efficiently?', ['It allows these derivatives to be applied directly without re-deriving them from first principles each time', 'Memorizing these formulas provides no benefit for solving calculus problems', 'These formulas must always be re-derived from scratch for every single problem', 'This concept has no connection to solving calculus problems efficiently'], 0)]),
P('Physics: Angular Momentum and Conservation',
  'Grade 12 Physics strand: angular momentum describes the rotational analog of linear momentum, and the law of conservation of angular momentum states that it remains constant in a system with no external torque acting on it.',
  [('Angular momentum is best described as the rotational analog of ___.', ['Linear momentum', 'Electric charge', 'A concept unrelated to momentum', 'Only mass, with no connection to motion'], 0),
   ('The law of conservation of angular momentum states that it remains constant when ___.', ['No external torque acts on a system', 'An external torque is constantly applied to a system', 'A system has no mass at all', 'A concept unrelated to torque or motion'], 0),
   ('Which is a classic example of angular momentum conservation?', ['A figure skater spinning faster when pulling their arms inward', 'An object that experiences no rotational motion whatsoever', 'A situation entirely unrelated to rotational motion', 'A skater who slows down for no identifiable reason'], 0),
   ('Why does a figure skater spin faster when pulling their arms in close to their body?', ['Reducing the distance of mass from the axis of rotation increases rotational speed to conserve angular momentum', 'Pulling the arms in has no effect on rotational speed', 'Angular momentum conservation has no connection to a skater’s spin', 'This effect occurs completely randomly, with no underlying physical principle'], 0),
   ('Why is the conservation of angular momentum an important principle in astrophysics, such as explaining the rotation of collapsing stars?', ['As a star’s mass collapses inward, conservation of angular momentum can cause it to spin dramatically faster', 'This principle has no application in astrophysics', 'Stars never experience any changes in their rotational speed', 'Angular momentum conservation only applies to objects on Earth'], 0)])]),

day(33, [
E('Independent Reading: Literature in Translation',
  'Grade 12 English strand: literature in translation allows readers to access stories originally written in another language, raising important questions about how meaning, tone, and cultural nuance can shift through the translation process.',
  [('Literature in translation allows readers to access stories ___.', ['Originally written in another language', 'Written exclusively in the reader’s native language', 'With no connection to any other language or culture', 'That have never been read in their original form'], 0),
   ('Reading literature in translation raises questions about how ___ can shift through the translation process.', ['Meaning, tone, and cultural nuance', 'Only the total page count', 'A factor entirely unrelated to language or meaning', 'The physical binding of the book'], 0),
   ('Why might a translator face difficult choices when translating a text with culturally specific idioms?', ['A direct, literal translation might not capture the intended meaning or feeling for a new audience', 'Idioms always translate directly and perfectly into any other language', 'Cultural nuance has no connection to how idioms are understood', 'Translators never encounter any difficult choices when working with idioms'], 0),
   ('Why is reading literature in translation valuable for building a broader understanding of world cultures?', ['It provides access to perspectives and stories that might otherwise be inaccessible to a reader', 'Literature in translation provides no meaningful access to other cultures', 'This type of reading has no connection to understanding global perspectives', 'Only literature originally written in a reader’s own language has any cultural value'], 0),
   ('Why might comparing a translated text to its original language version (even without full fluency) offer interesting insight for a student?', ['It can highlight specific choices a translator made and how those choices shape interpretation', 'Comparing versions never reveals anything meaningful about translation choices', 'A translated text is always completely identical in every way to its original', 'This type of comparison has no value for literary study'], 0)]),
AF('Piecewise and Absolute Value Functions: Advanced Analysis',
   'Grade 12 Advanced Functions strand: advanced analysis of piecewise and absolute value functions involves examining their behaviour at boundary points, including continuity and differentiability considerations.',
   [('Advanced analysis of piecewise functions often examines their behaviour at ___.', ['Boundary points', 'Only points far from any boundary', 'A concept unrelated to the function’s domain', 'The function’s y-intercept exclusively'], 0),
    ('An absolute value function can often be rewritten as a ___ function.', ['Piecewise', 'Purely exponential, with no other classification possible', 'A function unrelated to piecewise definitions', 'Purely logarithmic, with no other classification possible'], 0),
    ('Why might a piecewise function be continuous at a boundary point but not differentiable there?', ['The function’s pieces can connect smoothly in value but still have a sharp corner or change in slope', 'Continuity and differentiability are always identical properties with no distinction', 'A piecewise function can never be continuous at any of its boundary points', 'This situation has no connection to how piecewise functions behave'], 0),
    ('Why is examining a function’s behaviour at boundary points important for advanced analysis?', ['It reveals whether the function behaves smoothly and predictably, or has abrupt changes, at those specific locations', 'Boundary points have no significance in analyzing a piecewise function', 'A function always behaves identically at every point in its domain', 'This concept has no connection to understanding a function’s properties'], 0),
    ('Why might absolute value functions be useful for modelling real-world situations involving distance or deviation from a target value?', ['Absolute value naturally represents a non-negative measure of how far a value is from a reference point', 'Absolute value functions have no real-world modelling applications', 'Distance and deviation can never be represented using this type of function', 'This concept only applies to purely abstract, theoretical mathematics'], 0)]),
C('Concavity and the Second Derivative Test',
  'Grade 12 Calculus strand: concavity describes whether a function curves upward or downward, and the second derivative test uses the sign of a function’s second derivative to classify critical points as local maxima or minima.',
  [('Concavity describes whether a function ___.', ['Curves upward or downward', 'Increases at a constant, unchanging rate', 'A concept unrelated to how a function’s graph curves', 'Remains perfectly flat across its entire domain'], 0),
   ('The second derivative test uses the sign of a function’s second derivative to classify ___.', ['Critical points as local maxima or minima', 'Only the function’s domain restrictions', 'A concept entirely unrelated to critical points', 'The function’s y-intercept exclusively'], 0),
   ('If the second derivative at a critical point is positive, this generally indicates ___.', ['A local minimum', 'A local maximum', 'A point with no special significance', 'A value unrelated to concavity'], 0),
   ('Why might the second derivative test fail to classify a critical point in some cases?', ['If the second derivative equals zero at that point, the test provides no conclusive information', 'The second derivative test always provides a definitive answer with no exceptions', 'This test never encounters any situations where it fails to classify a point', 'This concept has no connection to how critical points are evaluated'], 0),
   ('Why is understanding concavity useful when sketching an accurate graph of a function?', ['It helps identify where a curve bends upward or downward, adding important detail beyond just increasing or decreasing behaviour', 'Concavity has no relevance to accurately sketching a function’s graph', 'A graph can be fully and accurately sketched with no consideration of concavity', 'This concept only applies to purely theoretical mathematics with no graphing application'], 0)]),
P('Physics: Fluid Mechanics -- Pressure and Buoyancy',
  'Grade 12 Physics strand: fluid mechanics studies the behaviour of liquids and gases, including how pressure varies with depth and how buoyant force allows objects to float or sink based on displaced fluid.',
  [('Fluid mechanics studies the behaviour of ___.', ['Liquids and gases', 'Only solid objects, with no connection to fluids', 'A field unrelated to physics', 'Only electricity, with no connection to fluids'], 0),
   ('Buoyant force is related to the amount of fluid ___.', ['Displaced by an object', 'That remains completely undisturbed by an object', 'A factor entirely unrelated to an object’s presence in a fluid', 'That evaporates from a container'], 0),
   ('Why does pressure generally increase with depth in a fluid?', ['The weight of the fluid above a given point increases as depth increases', 'Pressure always remains exactly the same regardless of depth', 'Depth has no relationship to the pressure within a fluid', 'This concept has no connection to how fluids behave'], 0),
   ('Why does an object float if the buoyant force acting on it is greater than or equal to its weight?', ['The upward buoyant force is sufcient to counteract the downward pull of gravity on the object', 'Buoyant force has no effect on whether an object floats or sinks', 'An object always sinks regardless of the buoyant force acting on it', 'This relationship has no connection to Archimedes’ principle'], 0),
   ('Why is understanding fluid mechanics important for engineering applications like ship design?', ['It helps engineers predict how a vessel will interact with water, including whether it will float as intended', 'Fluid mechanics has no practical application in engineering design', 'Ship design never requires any understanding of buoyancy or pressure', 'This field of physics has no connection to real-world engineering'], 0)])]),

day(34, [
E('Writing: Adaptation Analysis -- From Page to Screen',
  'Grade 12 English strand: analyzing a film adaptation of a literary work involves examining the creative choices made in translating a story from prose to a visual medium, including changes to plot, character, and tone.',
  [('Analyzing a film adaptation involves examining creative choices made in translating a story from prose to ___.', ['A visual medium', 'A purely audio format with no visual elements', 'A format entirely unrelated to storytelling', 'An identical, unchanged text with no adaptation involved'], 0),
   ('Which is an example of an element that might change during a book-to-film adaptation?', ['The pacing or structure of the plot', 'The complete absence of any creative interpretation', 'A factor entirely unrelated to storytelling choices', 'An element that always remains perfectly identical between mediums'], 0),
   ('Why might a filmmaker choose to alter certain details from the original source material?', ['Visual storytelling has different constraints and strengths than written prose', 'Filmmakers are always required to keep every detail of a text completely unchanged', 'Film adaptations never involve any creative interpretation or changes', 'This concept has no connection to how different mediums function'], 0),
   ('Why might comparing a novel to its film adaptation deepen understanding of both works?', ['It highlights how different mediums can shape the same underlying story in distinct ways', 'Comparing these two versions never reveals anything meaningful', 'A novel and its film adaptation are always completely identical in every way', 'This type of analysis has no value for studying literature or film'], 0),
   ('Why is evaluating an adaptation’s creative choices different from simply judging whether it is “faithful” to the original text?', ['It considers whether the adaptation achieves its own artistic goals within its medium, not just literal accuracy', 'A film adaptation should always be judged solely on how literally it matches the original text', 'Creative choices in an adaptation are never worth evaluating on their own terms', 'This distinction has no relevance to analyzing an adaptation'], 0)]),
AF('Rational Inequalities: Solving and Graphing',
   'Grade 12 Advanced Functions strand: solving a rational inequality involves finding the values of x where a rational expression is positive or negative, often using critical values and a sign analysis across intervals.',
   [('Solving a rational inequality involves finding the values of x where the expression is ___.', ['Positive or negative, as specified by the inequality', 'Always equal to exactly zero', 'A concept unrelated to the expression’s sign', 'Undefined across its entire domain'], 0),
    ('Critical values for a rational inequality typically come from ___.', ['Where the numerator or denominator equals zero', 'Only where the numerator equals a specific positive number', 'A concept unrelated to the rational expression', 'The y-intercept of the expression exclusively'], 0),
    ('Why must values that make the denominator of a rational inequality equal to zero always be excluded from the solution?', ['The expression is undefined at those values, so they cannot satisfy the inequality', 'These values should always be included as valid solutions', 'The denominator has no effect on which values are valid solutions', 'This concept has no connection to solving rational inequalities'], 0),
    ('Why is a sign analysis across intervals a useful method for solving a rational inequality?', ['It allows you to systematically determine whether the expression is positive or negative within each interval created by the critical values', 'A sign analysis provides no useful information for solving inequalities', 'Rational inequalities can never be solved using an interval-based approach', 'This method has no connection to determining an expression’s sign'], 0),
    ('Why might the solution to a rational inequality be represented using interval notation?', ['It concisely and clearly represents a range or set of ranges of values that satisfy the inequality', 'Interval notation provides no useful way to represent a solution set', 'Rational inequalities never have a solution that can be expressed as a range of values', 'This notation has no connection to representing mathematical solutions'], 0)]),
C('Improper Integrals',
  'Grade 12 Calculus strand: an improper integral involves either an infinite interval of integration or an integrand that becomes unbounded within the interval, evaluated using limits.',
  [('An improper integral may involve ___.', ['An infinite interval of integration', 'Only a finite, clearly bounded interval with no special considerations', 'A concept unrelated to intervals of integration', 'An integrand that is always perfectly well-behaved with no exceptions'], 0),
   ('Improper integrals are evaluated using ___.', ['Limits', 'Only basic arithmetic, with no other mathematical tools involved', 'A method entirely unrelated to calculus', 'Simple substitution with no further steps required'], 0),
   ('If the limit used to evaluate an improper integral exists and is finite, the integral is said to ___.', ['Converge', 'Diverge', 'Have no defined mathematical behaviour', 'Equal exactly zero in every single case'], 0),
   ('Why might an integral be considered improper if its integrand becomes unbounded (approaches infinity) within the interval?', ['The function’s value grows without limit at some point, requiring special evaluation using a limit', 'An unbounded integrand has no effect on how an integral should be evaluated', 'Improper integrals never involve any unbounded behaviour within the interval', 'This concept has no connection to how integrals are classified'], 0),
   ('Why are improper integrals useful for modelling real-world situations, such as calculating total probability over an infinite range of outcomes?', ['They provide a mathematical framework for handling quantities that extend over an infinite interval', 'Improper integrals have no real-world modelling applications', 'Infinite intervals can never be meaningfully evaluated using integration', 'This concept only applies to purely abstract, theoretical mathematics'], 0)]),
P('Physics: Thermodynamics -- Laws and Applications',
  'Grade 12 Physics strand: the laws of thermodynamics describe how energy is transferred and transformed, including the principle that energy cannot be created or destroyed and that natural processes tend to increase overall entropy.',
  [('The first law of thermodynamics states that energy ___.', ['Cannot be created or destroyed, only transformed', 'Is constantly created from nothing', 'Can be permanently destroyed with no trace remaining', 'Has no connection to how physical systems behave'], 0),
   ('The second law of thermodynamics relates to the tendency of natural processes to increase overall ___.', ['Entropy', 'Mass', 'Colour', 'A factor entirely unrelated to energy or disorder'], 0),
   ('Why is a perpetual motion machine (one that runs forever with no energy input) considered impossible according to the laws of thermodynamics?', ['It would violate the principle that energy cannot be created and that some energy is always lost as heat in real processes', 'Perpetual motion machines are fully consistent with all known laws of thermodynamics', 'The laws of thermodynamics have no connection to energy conservation', 'This concept has no relevance to how physical systems actually operate'], 0),
   ('Which is an example of a real-world application of thermodynamic principles?', ['The design of an engine that converts fuel into usable mechanical energy', 'A process entirely unrelated to energy transformation', 'An application with no connection to thermodynamics', 'A situation where no energy transfer occurs whatsoever'], 0),
   ('Why is understanding thermodynamics important for engineers designing energy-efficient systems?', ['It helps them understand the fundamental limits and losses involved in converting and transferring energy', 'Thermodynamics has no relevance to designing energy-efficient systems', 'Energy efficiency has no connection to the laws of thermodynamics', 'Engineers never need to consider energy transformation when designing systems'], 0)])]),

day(35, [
E('Oral Communication: Formal Debate at the University Level',
  'Grade 12 English strand: formal university-level debate requires rigorous research, structured argumentation, and the ability to respond persuasively and respectfully to complex counterarguments under time constraints.',
  [('University-level formal debate requires rigorous ___.', ['Research', 'Avoidance of any factual support', 'A concept unrelated to argumentation', 'Improvisation with no preparation whatsoever'], 0),
   ('Why is structured argumentation important in a formal debate setting?', ['It helps ensure the argument is clear, logical, and easy for the audience and judges to follow', 'Structure has no effect on how an argument is received in a debate', 'Formal debates should always avoid any clear organization', 'This concept has no connection to effective persuasive communication'], 0),
   ('Why must debaters be able to respond persuasively to complex counterarguments?', ['A strong debate requires directly and effectively addressing points raised by the opposing side', 'Debaters should always ignore any counterarguments presented by the opposing side', 'Counterarguments have no role in a formal debate format', 'This skill has no connection to effective debating'], 0),
   ('Why is responding respectfully to an opponent considered important in formal debate, even when strongly disagreeing?', ['It maintains the integrity and credibility of the debate as a serious, respectful exchange of ideas', 'Respectful communication has no value in a competitive debate setting', 'Debaters should always respond to opponents in a hostile or dismissive manner', 'This concept has no connection to effective or credible argumentation'], 0),
   ('Why are formal debate skills considered valuable preparation for university-level academic work?', ['They build the ability to research thoroughly, think critically, and communicate persuasively under pressure', 'Debate skills have no connection to success in university-level academic work', 'These skills are only useful within a formal debate competition setting', 'University-level work never requires any of these particular skills'], 0)]),
AF('Parametric Equations: Introduction and Applications',
   'Grade 12 Advanced Functions strand: parametric equations define x and y coordinates separately in terms of a third variable, often called a parameter, allowing more complex curves and motion paths to be represented.',
   [('Parametric equations define x and y coordinates separately in terms of a ___.', ['Third variable, called a parameter', 'Single, fixed constant with no variation', 'Concept entirely unrelated to coordinates', 'Colour, with no connection to numerical values'], 0),
    ('Parametric equations allow more complex ___ to be represented compared to a single function equation.', ['Curves and motion paths', 'Only straight lines, with no other shapes possible', 'A concept unrelated to graphing', 'Numbers with no connection to geometry'], 0),
    ('Why might parametric equations be useful for representing the motion of a projectile over time?', ['They can separately track horizontal and vertical position as functions of a shared time parameter', 'Parametric equations have no useful application for modelling motion', 'Projectile motion can never be represented using parametric equations', 'This concept only applies to purely abstract, theoretical mathematics'], 0),
    ('Why can a parametric representation describe curves, like a circle, that are not functions in the traditional x-y form?', ['The parameter allows multiple y-values to correspond to the same x-value, which a standard function cannot represent', 'Parametric equations can never represent shapes like circles', 'A circle can always be represented using a standard, traditional function', 'This concept has no connection to representing non-function curves'], 0),
    ('Why are parametric equations useful in computer animation for defining the path an object follows?', ['They allow precise control over both the position and timing of an object’s movement along a path', 'Parametric equations have no application in computer animation', 'Animation paths can never be defined using mathematical equations', 'This concept has no practical use outside of pure mathematics'], 0)]),
C('Partial Fractions in Integration',
  'Grade 12 Calculus strand: partial fraction decomposition breaks a complex rational expression into a sum of simpler fractions, making certain integrals significantly easier to evaluate.',
  [('Partial fraction decomposition breaks a complex rational expression into ___.', ['A sum of simpler fractions', 'A single, more complicated fraction', 'A concept unrelated to rational expressions', 'An expression with no fractions involved at all'], 0),
   ('Partial fractions are primarily used to make certain ___ significantly easier to evaluate.', ['Integrals', 'Only basic arithmetic calculations, with no connection to calculus', 'A concept entirely unrelated to integration', 'Simple addition problems'], 0),
   ('Why might a rational expression need to be decomposed into partial fractions before it can be integrated?', ['The original complex form may not have a straightforward antiderivative, while the simpler decomposed terms often do', 'Partial fraction decomposition never simplifies the process of integration', 'Every rational expression can always be integrated directly with no decomposition needed', 'This technique has no connection to evaluating integrals'], 0),
   ('Why is factoring the denominator an important first step in partial fraction decomposition?', ['The factors of the denominator determine the specific form of the simpler fractions used in the decomposition', 'Factoring the denominator provides no useful information for this process', 'Partial fraction decomposition never requires factoring the denominator', 'This concept has no connection to breaking down a rational expression'], 0),
   ('Why is partial fraction decomposition considered a valuable technique in a calculus toolkit?', ['It expands the range of integrals that can be solved using standard integration techniques', 'This technique provides no additional benefit for solving integration problems', 'Partial fractions have no practical application in evaluating integrals', 'This concept is never useful for expanding integration capabilities'], 0)]),
P('Physics: Capacitors and Electric Potential Energy',
  'Grade 12 Physics strand: a capacitor stores electric charge and energy in an electric field between two conductive plates, with the amount of stored energy related to its capacitance and the voltage applied.',
  [('A capacitor stores electric charge and energy in an electric field between ___.', ['Two conductive plates', 'A single, isolated point with no surrounding structure', 'A concept unrelated to electric charge', 'Only non-conductive, insulating materials with no charge storage'], 0),
   ('The amount of energy stored in a capacitor is related to its capacitance and ___.', ['The voltage applied', 'Only its physical colour, with no connection to voltage', 'A factor entirely unrelated to electric charge', 'The temperature of the surrounding room exclusively'], 0),
   ('Which is an example of a device that commonly uses capacitors?', ['A camera flash', 'A device with no connection to electrical energy storage', 'An object that stores no charge or energy whatsoever', 'A tool entirely unrelated to electric circuits'], 0),
   ('Why might a capacitor be useful in a circuit that requires a quick burst of energy, like a camera flash?', ['Capacitors can release their stored energy very rapidly compared to some other energy storage methods', 'Capacitors are never able to release energy quickly', 'This application has no connection to how capacitors store and release energy', 'A camera flash never involves any electrical energy storage'], 0),
   ('Why is understanding capacitors important for designing modern electronic devices?', ['Capacitors play a key role in managing and storing electrical energy within many circuits', 'Capacitors have no role in modern electronic device design', 'Electronic devices never require any form of energy storage components', 'This concept has no relevance to practical circuit design'], 0)])]),

day(36, [
E('Literature: Trauma and Memory in Contemporary Fiction',
  'Grade 12 English strand: contemporary fiction often explores how trauma shapes memory and identity, using techniques like fragmented narrative structure or nonlinear timelines to reflect a character’s psychological experience.',
  [('Contemporary fiction dealing with trauma often explores how it shapes ___.', ['Memory and identity', 'Only a character’s physical appearance', 'A topic entirely unrelated to personal experience', 'Grammar and sentence structure exclusively'], 0),
   ('Which is a narrative technique authors might use to reflect the psychological experience of trauma?', ['A fragmented or nonlinear narrative structure', 'A strictly chronological structure with absolutely no variation', 'A technique entirely unrelated to storytelling structure', 'The complete avoidance of any narrative structure at all'], 0),
   ('Why might a nonlinear timeline effectively represent how memory functions after a traumatic event?', ['Memory related to trauma often does not follow a clear, linear order, and this structure can mirror that experience', 'A nonlinear timeline has no connection to representing memory or trauma', 'Trauma always results in a perfectly clear and linear memory of events', 'This narrative technique is never used to explore psychological themes'], 0),
   ('Why is exploring trauma in fiction considered valuable, even though the subject matter can be difficult?', ['It can offer readers insight into difficult human experiences and foster empathy and understanding', 'Exploring difficult subject matter in fiction has no value for readers', 'Trauma has no connection to meaningful literary exploration', 'This topic should always be avoided entirely in contemporary fiction'], 0),
   ('Why might critics analyze the specific literary techniques an author uses to represent trauma, rather than just the subject matter itself?', ['The techniques themselves shape how a reader experiences and understands the depicted trauma', 'Literary technique has no connection to how a reader experiences a text’s themes', 'Only the subject matter of a text is ever worth analyzing', 'This type of analysis provides no additional insight into a text'], 0)]),
AF('Introduction to Polar Coordinates',
   'Grade 12 Advanced Functions strand: polar coordinates locate a point using a distance from the origin and an angle from a reference direction, offering an alternative to the standard x-y coordinate system.',
   [('Polar coordinates locate a point using ___.', ['A distance from the origin and an angle from a reference direction', 'Only two perpendicular distances, with no angle involved', 'A concept entirely unrelated to location or position', 'A single number with no other defining information'], 0),
    ('Polar coordinates offer an alternative to the standard ___ coordinate system.', ['x-y', 'Purely numerical, with no coordinate system involved at all', 'A system entirely unrelated to graphing points', 'Binary'], 0),
    ('Why might polar coordinates be more convenient than x-y coordinates for describing certain circular or spiral shapes?', ['These shapes can often be expressed more simply using distance and angle rather than separate horizontal and vertical values', 'Polar coordinates are always less convenient for any type of curved shape', 'Circular and spiral shapes can never be represented using polar coordinates', 'This coordinate system has no advantage for describing any type of shape'], 0),
    ('In polar coordinates, the angle is typically measured from ___.', ['A fixed reference direction, often the positive x-axis', 'A completely random, undefined direction each time', 'A concept unrelated to angles or direction', 'Only the vertical axis, with no other reference points used'], 0),
    ('Why might polar coordinates be useful in fields like navigation or radar systems?', ['These systems often naturally involve measuring direction and distance from a central reference point', 'Polar coordinates have no practical application in navigation or radar', 'Navigation systems never involve any measurement of angle or distance', 'This coordinate system only applies to purely theoretical mathematics'], 0)]),
C('Volumes of Solids of Revolution: The Shell Method',
  'Grade 12 Calculus strand: the shell method calculates the volume of a solid of revolution by integrating the surface areas of thin cylindrical shells, offering an alternative approach to the disk or washer method.',
  [('The shell method calculates volume by integrating the surface areas of thin ___.', ['Cylindrical shells', 'Flat, two-dimensional squares with no depth', 'A concept unrelated to volume calculation', 'Solid spheres with no hollow structure'], 0),
   ('The shell method offers an alternative approach to the ___ method.', ['Disk or washer', 'Only basic addition, with no other calculus method involved', 'A method entirely unrelated to calculating volume', 'Simple multiplication with no further steps required'], 0),
   ('Why might the shell method be preferred over the disk or washer method for certain solids of revolution?', ['Depending on the axis of rotation and shape, one method can involve significantly simpler integration than the other', 'The shell method is always the only valid way to calculate any solid of revolution’s volume', 'These two methods always produce identical levels of calculation difficulty', 'This choice of method has no effect on how easily a volume can be calculated'], 0),
   ('When using the shell method, the height and radius of each cylindrical shell typically depend on ___.', ['The function defining the boundary of the region being rotated', 'A completely fixed, unchanging value with no connection to the given function', 'A factor entirely unrelated to the original region', 'Only the colour of the region, with no other mathematical relationship'], 0),
   ('Why is having multiple methods, like the shell and disk/washer methods, valuable when solving volume problems?', ['Different problems are often more easily solved using one method over the other, depending on the shape and axis of rotation', 'Having multiple methods provides no additional benefit for solving these problems', 'Only a single method should ever be used regardless of the specific problem', 'This concept has no connection to effectively solving calculus problems'], 0)]),
P('Physics: RC Circuits and Time Constants',
  'Grade 12 Physics strand: an RC circuit contains a resistor and a capacitor, and its time constant describes how quickly the capacitor charges or discharges through the resistor.',
  [('An RC circuit contains a resistor and a ___.', ['Capacitor', 'Magnet, with no connection to resistors', 'Component entirely unrelated to electric circuits', 'Light bulb exclusively, with no other components'], 0),
   ('The time constant of an RC circuit describes how quickly the capacitor ___.', ['Charges or discharges through the resistor', 'Permanently loses all electrical properties', 'A process entirely unrelated to charge or discharge', 'Changes colour during circuit operation'], 0),
   ('Why does the resistor in an RC circuit affect how quickly the capacitor charges?', ['The resistor limits the current flow, which directly affects the rate of charge accumulation on the capacitor', 'The resistor has no effect on how quickly a capacitor charges', 'Resistors and capacitors have no functional relationship within a circuit', 'This concept has no connection to how RC circuits behave'], 0),
   ('Why might RC circuits be used in timing applications, such as a simple flashing light circuit?', ['The predictable charging and discharging behaviour can be used to control precise time delays', 'RC circuits have no practical application in timing-related devices', 'Timing applications never rely on any predictable circuit behaviour', 'This concept has no connection to real-world circuit design'], 0),
   ('Why is understanding the time constant important when designing an RC circuit for a specific application?', ['It allows engineers to predict and control how quickly the circuit responds to changes in voltage', 'The time constant provides no useful information for circuit design', 'RC circuits never behave in any predictable or calculable way', 'This concept has no relevance to practical engineering applications'], 0)])]),

day(37, [
E('Literary Analysis: Narrative Perspective and Unreliable Narration',
  'Grade 12 English strand: narrative perspective shapes how a story is told and understood, and an unreliable narrator’s compromised credibility requires readers to critically evaluate the accuracy of the account presented.',
  [('Narrative perspective shapes how a story is ___.', ['Told and understood', 'Physically printed and bound', 'A concept unrelated to storytelling', 'Marketed to potential readers only'], 0),
   ('An unreliable narrator is one whose ___ is compromised.', ['Credibility', 'Physical description', 'Age, with no connection to trustworthiness', 'Name, with no connection to the accuracy of their account'], 0),
   ('Why might readers need to critically evaluate the account presented by an unreliable narrator?', ['The narrator’s version of events may be biased, incomplete, or intentionally misleading', 'Unreliable narrators always present a completely accurate account of events', 'Readers never need to question a narrator’s reliability', 'This type of narration has no effect on how a story should be read'], 0),
   ('Why might an author choose a first-person perspective specifically to create narrative unreliability?', ['A first-person narrator’s limited, subjective viewpoint can naturally create doubt about the full accuracy of events', 'First-person narration always guarantees complete objectivity and reliability', 'Perspective has no connection to whether a narrator can be considered reliable', 'This narrative choice has no effect on how a reader interprets a story'], 0),
   ('Why is analyzing narrative perspective considered an advanced literary analysis skill?', ['It requires recognizing how the chosen point of view shapes, limits, or biases the information a reader receives', 'Narrative perspective has no connection to how a text’s meaning is constructed', 'This type of analysis provides no additional insight into a text', 'Perspective is never worth considering when analyzing a work of literature'], 0)]),
AF('Mathematical Induction: A Formal Proof Technique',
   'Grade 12 Advanced Functions strand: mathematical induction is a formal proof technique used to establish that a statement holds true for all natural numbers, by proving a base case and an inductive step.',
   [('Mathematical induction is a formal technique used to prove a statement holds true for all ___.', ['Natural numbers', 'Only a single, specific number', 'A concept unrelated to numbers', 'Irrational numbers exclusively, with no connection to natural numbers'], 0),
    ('A proof by mathematical induction requires proving a base case and ___.', ['An inductive step', 'A completely unrelated final conclusion with no connection to the base case', 'No further steps beyond the base case', 'A random, unrelated mathematical statement'], 0),
    ('The base case in a proof by induction typically establishes that the statement is true for ___.', ['The first (or smallest) relevant value', 'Every single possible value all at once', 'A value entirely unrelated to the statement being proven', 'No specific value at all'], 0),
    ('Why is the inductive step considered the core logical mechanism of a proof by mathematical induction?', ['It shows that if the statement holds for one value, it must also hold for the next value, creating a chain of truth', 'The inductive step provides no meaningful logical connection between values', 'This step has no connection to proving a statement for all natural numbers', 'A proof by induction never requires demonstrating any logical connection between values'], 0),
    ('Why is mathematical induction a particularly useful proof technique for statements involving patterns across an infinite set of numbers?', ['It provides a rigorous way to confirm a pattern holds for every case without needing to check each one individually', 'Mathematical induction can never be used for statements involving an infinite set of numbers', 'This technique provides no advantage over checking every single case individually', 'This concept has no connection to proving patterns in mathematics'], 0)]),
C('Taylor and Maclaurin Series: An Introduction',
  'Grade 12 Calculus strand: a Taylor series approximates a function as an infinite sum of terms based on its derivatives at a single point, with a Maclaurin series being the special case centred at zero.',
  [('A Taylor series approximates a function using an infinite sum of terms based on its ___.', ['Derivatives at a single point', 'Only its value at two distinct endpoints', 'A concept unrelated to derivatives', 'Physical graph colour with no mathematical basis'], 0),
   ('A Maclaurin series is a special case of a Taylor series centred at ___.', ['Zero', 'One', 'Infinity', 'A value that changes randomly with each calculation'], 0),
   ('Why might a Taylor series be useful for approximating the value of a complicated function at a specific point?', ['It can express the function as a sum of simpler polynomial terms that are easier to evaluate', 'Taylor series provide no useful method for approximating a function’s value', 'Complicated functions can never be approximated using any mathematical technique', 'This concept has no connection to evaluating functions'], 0),
   ('Why does including more terms in a Taylor series generally improve the accuracy of the approximation?', ['Additional terms capture more detail about how the function behaves near the chosen point', 'Adding more terms always makes a Taylor series approximation less accurate', 'The number of terms included has no effect on the accuracy of the approximation', 'This concept has no connection to how Taylor series function'], 0),
   ('Why are Taylor series useful in fields like physics and engineering for simplifying complex functions?', ['They allow difficult functions to be approximated with simpler polynomial expressions for practical calculations', 'Taylor series have no practical application in physics or engineering', 'Complex functions never need to be simplified for real-world calculations', 'This concept only applies to purely theoretical mathematics with no real-world use'], 0)]),
P('Physics: Diffraction and Polarization of Light',
  'Grade 12 Physics strand: diffraction describes the bending of light waves around obstacles or through openings, while polarization describes the restriction of light’s oscillation to a specific direction.',
  [('Diffraction describes the bending of light waves around ___.', ['Obstacles or through openings', 'Only a perfectly straight, unobstructed path', 'A concept unrelated to the behaviour of light', 'A completely opaque, solid surface with no gaps'], 0),
   ('Polarization describes the restriction of light’s oscillation to ___.', ['A specific direction', 'Every possible direction simultaneously, with no restriction', 'A concept unrelated to how light waves oscillate', 'No oscillation whatsoever'], 0),
   ('Which is an example of a practical application of polarization?', ['Polarized sunglasses reducing glare', 'An application entirely unrelated to light behaviour', 'A technology that has no connection to how light oscillates', 'A device that has no effect on visible light'], 0),
   ('Why does diffraction become more noticeable when light passes through a narrower opening?', ['A narrower opening causes a greater relative bending of the light wave around its edges', 'The width of an opening has no effect on the amount of diffraction that occurs', 'Diffraction never becomes more or less noticeable regardless of opening size', 'This concept has no connection to how light waves interact with obstacles'], 0),
   ('Why is understanding diffraction and polarization important in fields like optics and photography?', ['These wave properties of light directly affect how lenses and optical instruments perform', 'Diffraction and polarization have no relevance to optics or photography', 'Optical instruments never need to account for the wave properties of light', 'This concept has no practical, real-world application'], 0)])]),

day(38, [
E('Writing: The Op-Ed for a National Publication',
  'Grade 12 English strand: writing an op-ed intended for a national publication requires a clear, timely argument on an issue of broad public interest, supported by credible evidence and a distinctive, authoritative voice.',
  [('An op-ed for a national publication requires a clear argument on an issue of ___.', ['Broad public interest', 'No relevance to the general public', 'A concept unrelated to current events', 'Interest to only a single individual reader'], 0),
   ('Why is timeliness often an important quality for an op-ed intended for a national publication?', ['Op-eds often respond to current events, so relevance to the present moment increases their impact', 'Timeliness has no connection to how an op-ed is received', 'Op-eds should always avoid any connection to current events', 'This quality has no relevance to persuasive writing intended for publication'], 0),
   ('Why should an op-ed rely on credible evidence to support its argument?', ['Credible evidence strengthens the argument’s persuasiveness and the writer’s authority on the topic', 'Evidence is unnecessary for an op-ed intended for a national publication', 'An op-ed should never include any supporting evidence', 'Evidence always weakens a persuasive argument in this context'], 0),
   ('Why might a distinctive, authoritative voice be especially important in an op-ed aimed at a broad national audience?', ['It helps the piece stand out and establishes the writer’s credibility on a widely relevant issue', 'A distinctive voice has no effect on how an op-ed is received by a large audience', 'An op-ed for a national audience should always sound completely generic and impersonal', 'Voice has no connection to how persuasive a piece of writing is'], 0),
   ('Why is understanding a national publication’s specific audience important when writing an op-ed for it?', ['Tailoring the argument and tone to the audience increases the likelihood the piece will resonate and be published', 'The audience of a publication has no effect on how an op-ed should be written', 'Op-eds should always be written identically regardless of the specific publication', 'This factor has no connection to effective persuasive writing'], 0)]),
AF('Transformations of Functions: A Unified Approach',
   'Grade 12 Advanced Functions strand: this lesson synthesizes transformation rules -- shifts, stretches, reflections -- across all major function families studied this year, reinforcing a single, unified framework for predicting graph changes.',
   [('A unified approach to transformations applies the same general rules across ___.', ['All major function families', 'Only a single, specific type of function', 'A concept unrelated to function behaviour', 'Numbers with no connection to graphing'], 0),
    ('A vertical stretch of a function’s graph affects its ___.', ['Steepness or rate of change', 'Colour', 'Only its horizontal position', 'A property unrelated to the graph’s shape'], 0),
    ('Why is it valuable to recognize that shift, stretch, and reflection rules apply consistently across polynomial, exponential, and trigonometric functions?', ['It allows previously learned transformation skills to be applied efficiently to any new function encountered', 'Transformation rules are always completely different and unrelated for each individual type of function', 'This concept has no connection to understanding function behaviour more broadly', 'Transformations can never be meaningfully generalized across different function types'], 0),
    ('Why might combining multiple transformations, such as a shift and a stretch, require careful attention to the order of operations?', ['Applying transformations in a different order can sometimes produce a different final graph', 'The order of transformations never has any effect on the final resulting graph', 'Multiple transformations can never be combined and applied to the same function', 'This concept has no connection to accurately predicting a transformed graph'], 0),
    ('Why is a unified understanding of transformations useful when preparing for university-level mathematics courses?', ['It builds a flexible, generalizable skill that applies to the wide variety of functions encountered in more advanced study', 'This understanding has no connection to success in future mathematics courses', 'University-level mathematics never involves any further study of function transformations', 'This concept has no practical value beyond a single specific course'], 0)]),
C('Euler’s Method for Differential Equations',
  'Grade 12 Calculus strand: Euler’s Method provides a numerical approximation to the solution of a differential equation by using small, successive linear steps based on the equation’s slope at each point.',
  [('Euler’s Method provides a numerical approximation to the solution of a ___.', ['Differential equation', 'Basic linear equation with no derivatives involved', 'A concept unrelated to calculus', 'Simple arithmetic expression with no variables'], 0),
   ('Euler’s Method uses small, successive ___ based on the equation’s slope at each point.', ['Linear steps', 'Random, unrelated jumps with no mathematical basis', 'A concept unrelated to slope or rate of change', 'Steps determined entirely by guesswork with no calculation involved'], 0),
   ('Why might Euler’s Method be useful for differential equations that cannot be solved using standard analytical techniques?', ['It provides a practical way to approximate a solution numerically, even when an exact algebraic solution is difficult to find', 'Euler’s Method is never useful for solving any type of differential equation', 'All differential equations can always be solved exactly using simple algebraic methods', 'This concept has no connection to approximating solutions numerically'], 0),
   ('Why does using smaller step sizes generally improve the accuracy of Euler’s Method?', ['Smaller steps more closely follow the true curve of the solution, reducing the accumulated approximation error', 'Smaller step sizes always make the approximation significantly less accurate', 'Step size has no effect on the accuracy of Euler’s Method', 'This concept has no connection to how numerical approximation methods work'], 0),
   ('Why are numerical methods like Euler’s Method important in fields like engineering and physics, where exact solutions are often unavailable?', ['They provide a practical, computable way to model and predict system behaviour despite the complexity of the underlying equations', 'Numerical methods have no real-world application in engineering or physics', 'Engineers and physicists never need to work with equations that lack exact solutions', 'This concept only applies to purely theoretical mathematics with no practical use'], 0)]),
P('Physics: Particle Accelerators and Detection Methods',
  'Grade 12 Physics strand: particle accelerators use electric and magnetic fields to propel charged particles to very high speeds, allowing scientists to study fundamental particles through the resulting high-energy collisions.',
  [('Particle accelerators use electric and magnetic fields to propel charged particles to ___.', ['Very high speeds', 'A state of complete rest, with no motion involved', 'A concept unrelated to particle physics', 'Speeds that always remain constant and unchanging'], 0),
   ('Scientists study fundamental particles through the results of ___.', ['High-energy collisions', 'A process entirely unrelated to particle interactions', 'Only visual observation, with no experimental interaction involved', 'Collisions that produce no measurable, detectable data'], 0),
   ('Why are strong magnetic fields necessary in a particle accelerator?', ['Magnetic fields can steer and control the path of fast-moving charged particles', 'Magnetic fields have no role in the operation of a particle accelerator', 'Charged particles are never affected by magnetic fields in any way', 'This concept has no connection to how accelerators function'], 0),
   ('Why do scientists analyze the debris produced by high-energy particle collisions?', ['The resulting particles and their behaviour can reveal information about fundamental physical processes', 'The debris from these collisions provides no useful scientific information', 'Particle collisions never produce any detectable byproducts', 'This concept has no connection to studying fundamental particles'], 0),
   ('Why are particle accelerators considered valuable tools for testing theoretical models in physics?', ['They allow scientists to create experimental conditions that can confirm or challenge predictions made by theoretical physics', 'Particle accelerators have no connection to testing theoretical physics models', 'Theoretical physics predictions can never be tested through experimentation', 'This concept has no relevance to advancing scientific understanding'], 0)])]),

day(39, [
E('Literature: Absurdism and the Theatre of the Absurd',
  'Grade 12 English strand: the Theatre of the Absurd presents illogical situations and meaningless dialogue to reflect a perceived lack of inherent purpose in human existence, challenging traditional dramatic conventions.',
  [('The Theatre of the Absurd presents ___ to reflect a perceived lack of inherent purpose.', ['Illogical situations and meaningless dialogue', 'Only perfectly logical, straightforward events', 'A concept unrelated to human existence or meaning', 'Dialogue that always follows conventional, expected patterns'], 0),
   ('The Theatre of the Absurd challenges ___.', ['Traditional dramatic conventions', 'No established artistic conventions whatsoever', 'A concept entirely unrelated to theatre or drama', 'Only the physical staging of a play, with no thematic challenge'], 0),
   ('Why might a playwright use illogical or nonsensical dialogue to convey a philosophical idea about existence?', ['The absence of clear logic can mirror a broader sense of meaninglessness or confusion in the human condition', 'Illogical dialogue always removes any philosophical meaning from a play', 'This technique has no connection to exploring ideas about human existence', 'Nonsensical dialogue is never used intentionally for thematic purposes'], 0),
   ('Why might audiences initially find works from the Theatre of the Absurd disorienting or confusing?', ['These works intentionally depart from familiar logical structure and conventional storytelling expectations', 'These works are always presented in a perfectly clear, conventional format', 'Audiences never experience any disorientation when engaging with this type of theatre', 'This genre has no connection to challenging typical audience expectations'], 0),
   ('Why is the Theatre of the Absurd considered a significant movement in the broader history of drama?', ['It fundamentally challenged traditional ideas about narrative structure, meaning, and purpose in theatre', 'This movement had no lasting influence on the history or development of drama', 'The Theatre of the Absurd never actually challenged any existing theatrical conventions', 'This genre has no connection to broader developments in dramatic art'], 0)]),
AF('Review: Matrices, Parametric, and Polar Concepts',
   'Grade 12 Advanced Functions strand review: this lesson revisits matrices, solving systems with matrices, rational inequalities, parametric equations, polar coordinates, and mathematical induction.',
   [('A matrix is best described as ___.', ['A rectangular array of numbers organized in rows and columns', 'A single number with no organized structure', 'A concept unrelated to organizing numerical data', 'Only a graph with no numerical values'], 0),
    ('Parametric equations define x and y coordinates separately in terms of a ___.', ['Third variable, called a parameter', 'Single, fixed constant with no variation', 'Concept entirely unrelated to coordinates', 'Colour, with no connection to numerical values'], 0),
    ('Polar coordinates locate a point using ___.', ['A distance from the origin and an angle from a reference direction', 'Only two perpendicular distances, with no angle involved', 'A concept entirely unrelated to location or position', 'A single number with no other defining information'], 0),
    ('A proof by mathematical induction requires proving a base case and ___.', ['An inductive step', 'A completely unrelated final conclusion with no connection to the base case', 'No further steps beyond the base case', 'A random, unrelated mathematical statement'], 0),
    ('Why is it useful to review matrices, parametric, and polar concepts together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
C('Applications in Economics: Marginal Cost and Revenue',
  'Grade 12 Calculus strand: derivatives can model marginal cost and marginal revenue in economics, representing the rate of change in total cost or revenue with respect to producing one additional unit.',
  [('In economics, marginal cost represents the rate of change in total cost with respect to ___.', ['Producing one additional unit', 'The total number of years a business has operated', 'A concept unrelated to production or cost', 'The colour of the product being manufactured'], 0),
   ('Marginal revenue can be found by taking the ___ of the total revenue function.', ['Derivative', 'Sum', 'Product', 'A calculation entirely unrelated to derivatives'], 0),
   ('Why might a business use marginal cost and marginal revenue to help determine an optimal level of production?', ['Comparing these rates of change can help identify the production level where profit is maximized', 'Marginal cost and marginal revenue provide no useful information for business decisions', 'Businesses never use any mathematical analysis when determining production levels', 'This concept has no connection to real-world economic decision-making'], 0),
   ('Why is calculus a useful mathematical tool for analyzing economic concepts like marginal cost and revenue?', ['Calculus provides tools for precisely analyzing rates of change, which are central to how these economic concepts are defined', 'Calculus has no meaningful application to the field of economics', 'Marginal cost and marginal revenue can never be analyzed using calculus', 'This concept only applies to purely theoretical mathematics with no economic application'], 0),
   ('Why might a company aim to produce at the point where marginal cost equals marginal revenue?', ['This is often the production level associated with maximizing overall profit', 'This condition has no connection to a company’s profit', 'Companies should always aim to produce as much as physically possible with no other consideration', 'This concept has no relevance to economic decision-making'], 0)]),
P('Physics: Dark Matter and Dark Energy',
  'Grade 12 Physics strand: dark matter and dark energy are largely unobserved components of the universe inferred from their gravitational effects and their role in the universe’s accelerating expansion.',
  [('Dark matter and dark energy are largely inferred from their ___.', ['Gravitational effects', 'Direct visual observation through a standard telescope', 'A concept unrelated to the study of the universe', 'Complete absence of any detectable influence'], 0),
   ('Dark energy is associated with the universe’s ___.', ['Accelerating expansion', 'Complete lack of any expansion whatsoever', 'Steady, unchanging size with no expansion or contraction', 'A concept entirely unrelated to cosmology'], 0),
   ('Why do scientists believe dark matter exists, even though it cannot be directly observed with light-based telescopes?', ['Its gravitational influence on visible matter, such as galaxy rotation, suggests the presence of additional unseen mass', 'Dark matter has no measurable or inferred effect on the observable universe', 'Scientists have never found any evidence suggesting the existence of dark matter', 'This concept has no connection to observations made in astrophysics'], 0),
   ('Why is dark energy considered significant for understanding the ultimate fate of the universe?', ['It appears to be driving the accelerating expansion, which has major implications for how the universe will evolve over time', 'Dark energy has no connection to the universe’s long-term expansion or evolution', 'The fate of the universe has no relationship to any form of energy', 'This concept has no relevance to modern cosmological studies'], 0),
   ('Why do dark matter and dark energy remain some of the most significant open questions in modern physics?', ['Despite strong indirect evidence for their existence, their fundamental nature is not yet well understood', 'These topics have already been completely explained with no remaining scientific questions', 'Dark matter and dark energy have no real significance to the field of physics', 'This concept has no connection to ongoing scientific research'], 0)])]),

day(40, [
E('Writing: Revising the Personal Essay for Depth and Precision',
  'Grade 12 English strand: revising a personal essay for depth and precision involves moving beyond surface-level description to sharpen reflection, cut unnecessary language, and ensure every detail serves the essay’s central meaning.',
  [('Revising a personal essay for depth involves moving beyond ___.', ['Surface-level description', 'Only correcting spelling and punctuation errors', 'A concept unrelated to a writer’s reflection', 'Adding random, unrelated details with no clear purpose'], 0),
   ('Why might a writer cut certain sentences or details during revision, even if they are well-written?', ['Removing content that does not serve the essay’s central meaning can sharpen its overall focus and impact', 'Well-written sentences should always be kept regardless of their relevance to the essay’s focus', 'Cutting content during revision never improves a piece of writing', 'This concept has no connection to effective revision practices'], 0),
   ('Why is precision in word choice particularly important during the revision of a personal essay?', ['Precise language can more accurately and powerfully convey the specific nuance of a writer’s reflection', 'Word choice has no effect on how clearly or powerfully an essay communicates its meaning', 'Vague, imprecise language is always just as effective as precise language', 'This concept has no connection to strengthening a piece of personal writing'], 0),
   ('Why might a writer benefit from stepping away from a draft before revising it for depth and precision?', ['Returning with fresh perspective can make it easier to notice what is unclear, unnecessary, or underdeveloped', 'Stepping away from a draft has no effect on the quality of the eventual revision', 'A writer should always revise immediately with no time between drafting and revising', 'This concept has no connection to effective revision strategies'], 0),
   ('Why is revising for depth and precision considered an essential final stage of the personal essay writing process?', ['It transforms an initial draft into a more polished, meaningful piece that fully communicates the writer’s intended reflection', 'This stage of the writing process provides no meaningful improvement to a personal essay', 'A first draft is always already as strong as a fully revised piece of writing', 'This concept has no relevance to producing a strong final personal essay'], 0)]),
AF('Review: Rational Inequalities, Piecewise, and Transformations',
   'Grade 12 Advanced Functions strand review: this lesson revisits rational inequalities, advanced piecewise and absolute value function analysis, and the unified framework for function transformations.',
   [('Solving a rational inequality involves finding the values of x where the expression is ___.', ['Positive or negative, as specified by the inequality', 'Always equal to exactly zero', 'A concept unrelated to the expression’s sign', 'Undefined across its entire domain'], 0),
    ('An absolute value function can often be rewritten as a ___ function.', ['Piecewise', 'Purely exponential, with no other classification possible', 'A function unrelated to piecewise definitions', 'Purely logarithmic, with no other classification possible'], 0),
    ('A vertical stretch of a function’s graph affects its ___.', ['Steepness or rate of change', 'Colour', 'Only its horizontal position', 'A property unrelated to the graph’s shape'], 0),
    ('Why must values that make the denominator of a rational inequality equal to zero always be excluded from the solution?', ['The expression is undefined at those values, so they cannot satisfy the inequality', 'These values should always be included as valid solutions', 'The denominator has no effect on which values are valid solutions', 'This concept has no connection to solving rational inequalities'], 0),
    ('Why is it valuable to review rational inequalities, piecewise functions, and transformations together?', ['It reinforces how these related function concepts connect to and build upon one another', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be studied with no connection to the others'], 0)]),
C('Review: Integration Techniques and Numerical Methods',
  'Grade 12 Calculus strand review: this lesson revisits improper integrals, partial fractions, Taylor series, Euler’s Method, and applications of derivatives in economics.',
  [('An improper integral may involve ___.', ['An infinite interval of integration', 'Only a finite, clearly bounded interval with no special considerations', 'A concept unrelated to intervals of integration', 'An integrand that is always perfectly well-behaved with no exceptions'], 0),
   ('Partial fraction decomposition breaks a complex rational expression into ___.', ['A sum of simpler fractions', 'A single, more complicated fraction', 'A concept unrelated to rational expressions', 'An expression with no fractions involved at all'], 0),
   ('A Taylor series approximates a function using an infinite sum of terms based on its ___.', ['Derivatives at a single point', 'Only its value at two distinct endpoints', 'A concept unrelated to derivatives', 'Physical graph colour with no mathematical basis'], 0),
   ('Euler’s Method uses small, successive ___ based on the equation’s slope at each point.', ['Linear steps', 'Random, unrelated jumps with no mathematical basis', 'A concept unrelated to slope or rate of change', 'Steps determined entirely by guesswork with no calculation involved'], 0),
   ('Why is it valuable to review integration techniques and numerical methods together?', ['It reinforces how these advanced calculus tools connect and expand what problems can be solved', 'These topics have no connection to each other', 'Review is never useful in calculus', 'Each topic must be studied with no connection to the others'], 0)]),
P('Review: Thermodynamics, Circuits, and Modern Physics',
  'Grade 12 Physics strand review: this lesson revisits rotational motion, fluid mechanics, thermodynamics, capacitors and RC circuits, diffraction and polarization, particle accelerators, and dark matter and dark energy.',
  [('Torque is best described as the rotational equivalent of ___.', ['Force', 'Mass', 'Only colour, with no connection to motion', 'A concept unrelated to rotational motion'], 0),
   ('The second law of thermodynamics relates to the tendency of natural processes to increase overall ___.', ['Entropy', 'Mass', 'Colour', 'A factor entirely unrelated to energy or disorder'], 0),
   ('The time constant of an RC circuit describes how quickly the capacitor ___.', ['Charges or discharges through the resistor', 'Permanently loses all electrical properties', 'A process entirely unrelated to charge or discharge', 'Changes colour during circuit operation'], 0),
   ('Dark energy is associated with the universe’s ___.', ['Accelerating expansion', 'Complete lack of any expansion whatsoever', 'Steady, unchanging size with no expansion or contraction', 'A concept entirely unrelated to cosmology'], 0),
   ('Why is it valuable to review these physics topics together at the end of the unit?', ['It reinforces how these physical principles connect across mechanics, thermodynamics, and modern physics', 'These topics have no connection to each other', 'Review is never useful in physics', 'Each topic must be studied with no connection to the others'], 0)])]),
]

def _rebalance_answer_positions(days, seed=20260727):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g12_31_40)
    append_to(12, g12_31_40)
