#!/usr/bin/env python3
"""Grade 12, Days 161-170 -- extends Grade 12 from 160 to 170 days. Topics
chosen after dumping the full existing Day 1-160 title list (data/grade12.json,
640 subject entries) to avoid any overlap -- Grade 12 has been extremely
heavily mined across sixteen prior batches, so this batch hunts for angles
not yet touched: the morality play, the revenge tragedy, Menippean satire,
the closet drama, ergodic literature and hypertext fiction, erasure poetry,
the jeremiad, the verse essay, and the roman-fleuve for English; the
Student t-distribution, analysis of variance (ANOVA), Hamiltonian paths and
cycles, Dijkstras algorithm, the stable marriage problem, Fermat primes and
constructible polygons, Bertrands postulate, Liouville numbers, and the
Runge phenomenon for Advanced Functions; systems of linear differential
equations, Sturm-Liouville theory, the Adams-Bashforth multistep method,
Monte Carlo integration, the Gibbs phenomenon, Cesaro summation, the
Riemann rearrangement theorem, asymptotic expansions, and the total
derivative for Calculus; gyroscopic precession, rolling without slipping,
the Poynting vector, LC circuits, polarization and Malus law, the quantum
harmonic oscillator, exoplanet detection, Olbers paradox, and band theory
of solids for Physics. Every one of these 36 titles/key terms was checked
against the full Day 1-160 dump and confirmed absent. Day 170 is a review
day, following the exact per-subject review pattern used on Day 150/160:
one review lesson per subject, each quizzing the first five of that
subject's nine new topics.

Subject keys for Grade 12 are "English", "AdvancedFunctions", "Calculus",
"Physics" (same as all earlier Grade 12 batches).

videoUrl is intentionally left unset for every subject -- fetch_video_ids.py
fills these in automatically on its next daily run. No embedded ASCII
double-quote or straight-apostrophe characters are used anywhere in
title/question/summary/option text; apostrophes and accented characters
are avoided entirely, matching the convention used since the Days 131-140
batch and followed exactly by the Days 151-160 batch immediately before
this one.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
CA12 = 'https://tvolearn.com/pages/grade-12-calculus-and-vectors'
PH12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RCA, RPH = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus and Vectors',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def CA(t, s, q):
    return sub('Calculus', t, s, RCA, CA12, q)


def PH(t, s, q):
    return sub('Physics', t, s, RPH, PH12, q)


def _rebalance_answer_positions(days, seed=20260816):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g12_161_170 = [
day(161, [
E('The Morality Play: Medieval Allegory on the Stage',
  'Grade 12 English strand: a morality play is a form of medieval drama in which characters personify abstract qualities, such as Virtue or Vice, guiding a representative human protagonist through temptation and moral choice toward an explicitly didactic lesson about salvation and conduct.',
  [('What kind of characters typically populate a morality play?', ['Personifications of abstract qualities, such as Virtue or Vice', 'Historical figures with no symbolic meaning at all', 'Animals with no connection to human conduct', 'Characters drawn entirely from ancient myth with no allegory involved'], 0),
   ('What is the central dramatic journey of a typical morality play protagonist?', ['A representative human figure moves through temptation and moral choice toward a lesson about conduct and salvation', 'A protagonist who faces no temptation or choice of any kind', 'A protagonist whose journey has no moral or religious dimension', 'A protagonist who exists only to entertain, with no didactic purpose'], 0),
   ('What is the primary purpose of a morality play, distinct from purely entertaining drama?', ['To teach an explicitly didactic moral or religious lesson', 'To avoid any instructive or moral content whatsoever', 'To document real historical events with no symbolic characters', 'To remove any protagonist or central character from the plot'], 0),
   ('How does the morality play compare to commedia dellArte, studied in an earlier batch?', ['Commedia dellArte relies on improvised stock comic roles, while the morality play uses fixed allegorical figures to deliver an explicit moral lesson', 'The two traditions are identical in purpose and character type', 'The morality play is always improvised, exactly like commedia dellArte', 'Commedia dellArte is always didactic and religious, unlike the morality play'], 0),
   ('Why might allegorical characters like Virtue and Vice be an effective device for a medieval audience?', ['Personifying abstract ideas makes moral concepts concrete and easy to follow on stage', 'Abstract personification makes moral lessons impossible to understand', 'Medieval audiences rejected any use of symbolic or allegorical characters', 'Allegory removes any possibility of teaching a moral lesson'], 0)]),
AF('Statistics: The Student t-Distribution and Small-Sample Inference',
   'Grade 12 Advanced Functions strand: the Student t-distribution is a probability distribution used instead of the normal distribution when estimating a population mean from a small sample with an unknown population standard deviation, having heavier tails that account for the extra uncertainty of a small sample.',
   [('When is the Student t-distribution typically used instead of the normal distribution?', ['When estimating a population mean from a small sample with an unknown population standard deviation', 'Only when the entire population has already been measured directly', 'When the population standard deviation is known exactly in advance', 'Only for samples larger than several thousand observations'], 0),
    ('How do the tails of the t-distribution compare to those of the normal distribution?', ['The t-distribution has heavier tails, reflecting greater uncertainty', 'The t-distribution has no tails at all', 'The t-distribution always has thinner tails than the normal distribution', 'The two distributions have identical tails in every case'], 0),
    ('What happens to the t-distribution as the sample size grows very large?', ['It approaches the shape of the normal distribution', 'It becomes flatter and wider without bound', 'It collapses to a single fixed point regardless of sample size', 'It becomes completely unrelated to the normal distribution'], 0),
    ('Which earlier-studied concept does the t-distribution extend to account for small-sample uncertainty?', ['The normal distribution and z-scores', 'The binomial distribution alone, with no connection to the normal distribution', 'The travelling salesman problem', 'The pigeonhole principle'], 0),
    ('Why is a parameter called degrees of freedom important when using the t-distribution?', ['It reflects the sample size and determines the exact shape of the t-distribution being used', 'Degrees of freedom have no effect on the shape of the distribution', 'The t-distribution ignores sample size entirely', 'Degrees of freedom only matter for the normal distribution, not the t-distribution'], 0)]),
CA('Systems of Linear Differential Equations and the Matrix Exponential Approach',
   'Grade 12 Calculus strand: a system of linear differential equations describes several interrelated quantities changing over time at once, and writing the system in matrix form lets its solution be expressed using the matrix exponential, built from the eigenvalues and eigenvectors of the coefficient matrix.',
   [('What does a system of linear differential equations describe?', ['Several interrelated quantities changing over time at once', 'A single isolated quantity with no relationship to any other variable', 'A purely algebraic system with no rates of change involved', 'A system with no matrix representation possible'], 0),
    ('What mathematical object is used to express the solution of a linear system written in matrix form?', ['The matrix exponential', 'A single scalar constant with no matrix involved', 'The determinant of the coefficient matrix alone', 'A system with no defined solution of any kind'], 0),
    ('Which earlier-studied concepts are used to construct the matrix exponential for a given system?', ['The eigenvalues and eigenvectors of the coefficient matrix', 'The mean and standard deviation of a data set', 'The binomial theorem', 'The trapezoid rule for numerical integration'], 0),
    ('How does this matrix approach relate to solving a single second-order linear differential equation with constant coefficients, studied earlier?', ['A single higher-order equation can be rewritten as a system of first-order equations and solved the same way', 'The two techniques share no mathematical connection whatsoever', 'Systems of differential equations can never be reduced to a single equation', 'The matrix exponential approach only applies to algebraic equations, not differential ones'], 0),
    ('Why is expressing a coupled system in matrix form useful for analysis and computation?', ['It organizes multiple interacting equations into a single structured object whose behaviour can be studied using linear algebra tools', 'Matrix notation removes all information about how the equations are coupled', 'Matrix form can only be used when the equations are completely unrelated to one another', 'Matrix notation eliminates the need to ever compute eigenvalues'], 0)]),
PH('Gyroscopic Precession and the Physics of a Spinning Top',
   'Grade 12 Physics strand: gyroscopic precession occurs when an external torque, such as gravity acting on a tilted spinning top, causes its spin axis to sweep out a cone rather than simply falling over, because the torque changes the direction of angular momentum rather than its magnitude.',
   [('What is gyroscopic precession?', ['The slow sweeping of a spinning objects axis in a cone shape under an external torque', 'The instant collapse of a spinning object the moment any torque is applied', 'A spinning objects tendency to speed up indefinitely with no external influence', 'The complete absence of any motion in a spinning object'], 0),
    ('Why does a tilted spinning top precess rather than simply fall over under gravity?', ['The torque from gravity changes the direction of its angular momentum rather than its magnitude', 'Gravity has no effect whatsoever on a spinning object', 'The tops angular momentum is destroyed instantly by any applied torque', 'Precession only occurs in objects that are not actually spinning'], 0),
    ('Which earlier-studied conserved quantity is central to explaining gyroscopic precession?', ['Angular momentum', 'Electric charge', 'Linear momentum in a straight line only', 'Volume of the spinning object'], 0),
    ('What shape does the axis of a precessing gyroscope typically trace out over time?', ['A cone', 'A perfectly straight line with no curvature', 'A single fixed point with no motion at all', 'A random, unpredictable path with no defined shape'], 0),
    ('Why is gyroscopic precession useful in devices such as gyrocompasses and stabilizers?', ['A spinning gyroscopes resistance to having its angular momentum direction changed lets it maintain a stable reference orientation', 'Gyroscopes provide no stability of any kind once set in motion', 'Precession makes a gyroscopes orientation completely unpredictable and useless', 'Gyroscopic devices rely entirely on electric charge rather than rotational motion'], 0)]),
]),
day(162, [
E('The Revenge Tragedy: Blood and Retribution on the Elizabethan Stage',
  'Grade 12 English strand: the revenge tragedy is a dramatic genre, prominent on the Elizabethan and Jacobean stage, centred on a protagonist who pursues vengeance for a grievous wrong, typically a murder, and moves through intrigue, madness, and violence toward a climactic and often devastating bloodbath.',
  [('What central action drives the plot of a revenge tragedy?', ['A protagonist pursuing vengeance for a grievous wrong, typically a murder', 'A protagonist entirely uninterested in justice or retribution', 'A protagonist who forgives every wrong immediately with no conflict', 'A plot with no central grievance or wrong of any kind'], 0),
   ('On which historical stage tradition did the revenge tragedy become especially prominent?', ['The Elizabethan and Jacobean stage', 'Ancient Greek comic theatre exclusively', 'Modern absurdist theatre only', 'A tradition with no connection to English drama'], 0),
   ('What dramatic elements commonly appear as a revenge tragedy builds toward its climax?', ['Intrigue, madness, and escalating violence', 'A complete absence of conflict or tension', 'Only comic misunderstandings with no serious consequences', 'A plot that resolves entirely offstage with no dramatic action'], 0),
   ('How does the revenge tragedy differ from the broader category of tragic form studied in an earlier batch?', ['It is a specific historical subgenre organized around the pursuit of vengeance, rather than tragedy in its most general cross-cultural sense', 'The two concepts describe entirely unrelated dramatic forms', 'Revenge tragedy contains no tragic elements whatsoever', 'The general tragic form always requires a revenge plot specifically'], 0),
   ('Why might a revenge tragedys protagonist often become a morally compromised figure by the plays end?', ['Pursuing vengeance can draw the protagonist into the same violence and corruption that caused the original wrong', 'Pursuing revenge always leaves a protagonist morally untouched', 'Revenge tragedies never depict any change in their protagonists', 'Moral compromise is impossible within a strictly tragic dramatic structure'], 0)]),
AF('Statistics: Analysis of Variance (ANOVA) and Comparing Multiple Means',
   'Grade 12 Advanced Functions strand: analysis of variance, or ANOVA, tests whether the means of three or more groups differ significantly by comparing the variance between group means to the variance within each group, extending simpler two-sample comparison methods to studies with multiple groups at once.',
   [('What question does an ANOVA test primarily answer?', ['Whether the means of three or more groups differ significantly from one another', 'Whether a single data point is an outlier', 'Whether exactly two population parameters are identical', 'Whether a sample was collected using a random method'], 0),
    ('What two sources of variance does ANOVA compare to draw its conclusion?', ['The variance between group means and the variance within each group', 'The mean and the mode of a single group only', 'The sample size and the number of variables measured', 'The correlation coefficient and the regression slope'], 0),
    ('Why is ANOVA useful when a study involves more than two groups?', ['It allows comparing all groups at once, rather than requiring many separate two-group comparisons', 'ANOVA can only ever compare exactly two groups at a time', 'It removes the need to ever compare group means', 'ANOVA is limited to studies with a single group only'], 0),
    ('How does ANOVA relate to hypothesis testing and the p-value, studied in an earlier batch?', ['ANOVA produces a test statistic and an associated p-value used to decide whether observed group differences are statistically significant', 'ANOVA has no connection whatsoever to hypothesis testing', 'ANOVA always produces a p-value of exactly zero', 'Hypothesis testing cannot be applied to comparisons involving more than one group'], 0),
    ('Why might a researcher choose ANOVA over running several separate two-sample tests on the same data?', ['Running many separate tests increases the chance of a false positive, which ANOVA is designed to control for when comparing multiple groups at once', 'Running separate tests always gives more reliable results than ANOVA', 'ANOVA and separate two-sample tests always produce identical, interchangeable results', 'ANOVA requires more groups than could ever be tested individually'], 0)]),
CA('Sturm-Liouville Theory and Eigenfunction Problems',
   'Grade 12 Calculus strand: Sturm-Liouville theory studies a class of second-order differential equations whose solutions, under suitable boundary conditions, form an orthogonal family of eigenfunctions with associated eigenvalues, generalizing the framework behind Legendre polynomials and other special functions studied earlier.',
   [('What kind of equation does Sturm-Liouville theory study?', ['A class of second-order differential equations with associated boundary conditions', 'A purely algebraic equation with no derivatives involved', 'A first-order equation with no boundary conditions of any kind', 'An equation with no possible eigenfunction solutions'], 0),
    ('What structure do the solutions of a Sturm-Liouville problem form, under suitable boundary conditions?', ['An orthogonal family of eigenfunctions with associated eigenvalues', 'A single, unique solution with no other related solutions', 'A family of solutions with no orthogonality property at all', 'A set of solutions unrelated to any eigenvalue'], 0),
    ('Which earlier-studied special functions fit within the general Sturm-Liouville framework?', ['Legendre polynomials', 'The binomial coefficients', 'The Fibonacci sequence', 'The determinant of a matrix'], 0),
    ('What can the orthogonal eigenfunctions from a Sturm-Liouville problem be used for, similar to a Fourier series?', ['Expanding other functions as a weighted sum of the eigenfunctions', 'Eliminating the need for any function expansion', 'Making it impossible to represent any other function', 'Converting every function into a single constant'], 0),
    ('Why is Sturm-Liouville theory considered a unifying framework for several special functions studied across this course?', ['It shows that many previously separate special functions arise as eigenfunctions of the same general type of boundary value problem', 'It proves that special functions such as Legendre polynomials have no relationship to one another', 'It only applies to a single special function with no broader generalization', 'It removes the need to ever consider boundary conditions'], 0)]),
PH('Rolling Without Slipping: Combining Translation and Rotation',
   'Grade 12 Physics strand: rolling without slipping describes motion in which an objects point of contact with the surface has zero relative velocity, linking its rotational and translational motion through a fixed relationship between angular velocity and linear speed, essential to analyzing wheels and rolling spheres.',
   [('What condition defines rolling without slipping?', ['The point of contact between the object and the surface has zero relative velocity', 'The object slides freely with no rotation at all', 'The object spins in place with no translational motion whatsoever', 'The surface and the object never make contact'], 0),
    ('What relationship links angular velocity and linear speed for an object rolling without slipping?', ['A fixed relationship in which linear speed equals angular velocity multiplied by the objects radius', 'The two quantities are completely unrelated to one another', 'Angular velocity is always exactly zero during rolling motion', 'Linear speed is always zero whenever angular velocity is nonzero'], 0),
    ('Which earlier-studied concepts does analyzing rolling without slipping combine?', ['Translational motion and rotational motion together', 'Only electric circuits, with no mechanics involved', 'Only wave phenomena, with no rotation involved', 'Only thermodynamic quantities, with no motion involved'], 0),
    ('Why is friction generally necessary at the contact point for rolling without slipping to occur?', ['Friction provides the torque needed to keep the surface velocity at the contact point equal to zero', 'Friction always causes an object to slip rather than roll smoothly', 'Rolling without slipping requires a completely frictionless surface', 'Friction has no role in rotational motion of any kind'], 0),
    ('How does the total kinetic energy of a rolling object, such as a ball, differ from that of an object simply sliding at the same speed?', ['A rolling object has additional rotational kinetic energy on top of its translational kinetic energy', 'A rolling object always has less total kinetic energy than a sliding object at the same speed', 'Rolling motion contains no kinetic energy of any kind', 'Sliding and rolling objects always have identical total kinetic energy at the same speed'], 0)]),
]),
day(163, [
E('Menippean Satire: Mocking Attitudes Rather Than Persons',
  'Grade 12 English strand: Menippean satire is a loose, prose-based satirical form that mocks mental attitudes, such as pedantry or dogmatism, rather than targeting specific individuals, often mixing genres and digressive structure to parody the very form of intellectual seriousness it examines.',
  [('What does Menippean satire primarily target?', ['Mental attitudes, such as pedantry or dogmatism, rather than specific individuals', 'Only named, real individuals with no attention to ideas', 'A single historical event with no interest in ideas or attitudes', 'Only physical appearance, with no interest in intellectual attitudes'], 0),
   ('What structural quality often characterizes Menippean satire?', ['A loose, digressive structure that often mixes genres', 'A perfectly rigid, single-genre structure with no digression', 'A structure identical to a strict formal sonnet', 'A structure that forbids any prose content whatsoever'], 0),
   ('What might Menippean satire parody through its own form?', ['The very form of intellectual seriousness or pedantry it examines', 'Only visual art, with no connection to written form', 'A structure with no relationship to its satirical target', 'Menippean satire never engages with its own form in any way'], 0),
   ('How does Menippean satire differ from the general satire studied earlier in this course, which often targets specific social behaviour through comedy?', ['Menippean satire specifically emphasizes mocking abstract attitudes and intellectual postures through a loose, mixed-genre structure, rather than social behaviour alone', 'The two forms are entirely identical with no meaningful distinction', 'Menippean satire never engages with comedy of any kind', 'General satire always uses a loose, digressive, mixed-genre structure'], 0),
   ('Why might a writer choose Menippean satires digressive, mixed-genre approach to critique a rigid ideology?', ['A chaotic, genre-blending structure can itself mimic and undercut the rigid seriousness being mocked', 'A digressive structure makes any critique of ideology completely impossible', 'Mixed-genre writing has no capacity to satirize an idea or attitude', 'Rigid, single-genre structure is required for any form of satire'], 0)]),
AF('Discrete Math: Hamiltonian Paths and Cycles in Graphs',
   'Grade 12 Advanced Functions strand: a Hamiltonian path visits every vertex of a graph exactly once, and a Hamiltonian cycle does so while also returning to its starting vertex, a concept closely related to the travelling salesman problem but focused on the existence of such a route rather than its optimal cost.',
   [('What must a Hamiltonian path do, with respect to the vertices of a graph?', ['Visit every vertex exactly once', 'Visit only a single vertex, ignoring all others', 'Visit every edge exactly once, ignoring the vertices', 'Avoid visiting any vertex at all'], 0),
    ('What additional requirement distinguishes a Hamiltonian cycle from a Hamiltonian path?', ['A Hamiltonian cycle must also return to its starting vertex', 'A Hamiltonian cycle may skip some vertices entirely', 'A Hamiltonian cycle must visit each vertex more than once', 'A Hamiltonian cycle has no relationship to the starting vertex'], 0),
   ('How does the Hamiltonian path problem relate to the travelling salesman problem, studied in an earlier batch?', ['Both concern visiting every vertex once, but the travelling salesman problem also seeks the lowest-cost such route among weighted edges', 'The two problems are entirely unrelated to one another', 'The travelling salesman problem ignores whether every vertex is visited', 'Hamiltonian paths always ignore the structure of the underlying graph'], 0),
    ('Is determining whether a general graph contains a Hamiltonian cycle considered an easy problem to solve exactly for large graphs?', ['No, it is computationally difficult in general, similar in spirit to other hard combinatorial problems', 'Yes, it can always be solved instantly regardless of graph size', 'The question has no defined answer for any graph', 'It is only meaningful for graphs with a single vertex'], 0),
    ('Why are Hamiltonian cycles relevant to practical routing and network design problems?', ['Finding a route that visits every required location exactly once and returns to the start models many real scheduling and logistics tasks', 'Hamiltonian cycles have no application outside of pure graph theory', 'Practical routing problems never require visiting every location', 'Hamiltonian cycles are only relevant to graphs with no edges'], 0)]),
CA('Multistep Methods: The Adams-Bashforth Technique for Differential Equations',
   'Grade 12 Calculus strand: the Adams-Bashforth method is a multistep numerical technique for solving differential equations that estimates each new value using several previously computed points rather than only the most recent one, often achieving greater accuracy than single-step methods like Eulers method for a comparable step size.',
   [('What distinguishes a multistep method like Adams-Bashforth from a single-step method such as Eulers method?', ['It estimates each new value using several previously computed points rather than only the most recent one', 'It uses no previous data of any kind at every step', 'It requires recomputing the entire solution from scratch at every step', 'It can only ever be applied to algebraic equations, not differential ones'], 0),
    ('What kind of problem is the Adams-Bashforth method designed to solve numerically?', ['Differential equations', 'Purely algebraic equations with no derivatives', 'Static geometry problems with no rates of change', 'Problems with no numerical component whatsoever'], 0),
    ('What advantage can a multistep method like Adams-Bashforth offer compared to Eulers method for a similar step size?', ['Often greater accuracy, by making use of more information from earlier points', 'It always produces exactly the same accuracy as Eulers method in every case', 'It guarantees an error of exactly zero regardless of step size', 'It eliminates the need for any step size at all'], 0),
    ('How does the Adams-Bashforth method relate to the Runge-Kutta methods studied in an earlier batch?', ['Both are numerical techniques for approximating solutions to differential equations, though Runge-Kutta uses intermediate evaluations within a single step rather than several previous steps', 'The two methods have no relationship to one another whatsoever', 'Runge-Kutta methods are a type of multistep method identical to Adams-Bashforth', 'Adams-Bashforth requires no numerical approximation of any kind'], 0),
    ('Why might a multistep method require special starting values before it can begin its normal iteration?', ['It needs several previous points to work from, which are not yet available at the very start of the computation', 'Multistep methods never require any starting information at all', 'Starting values are irrelevant to any numerical differential equation method', 'A multistep method can begin using only a single arbitrary future point'], 0)]),
PH('The Poynting Vector and the Flow of Electromagnetic Energy',
   'Grade 12 Physics strand: the Poynting vector describes the direction and rate of energy flow carried by an electromagnetic wave, calculated from the cross product of the electric and magnetic field vectors, and is used to quantify the intensity of radiation such as sunlight or a radio signal.',
   [('What does the Poynting vector describe about an electromagnetic wave?', ['The direction and rate of energy flow it carries', 'The exact colour of the light involved', 'The mass of the particles composing the wave', 'The temperature of the medium the wave travels through'], 0),
    ('From which two field vectors is the Poynting vector calculated?', ['The electric field vector and the magnetic field vector', 'The gravitational field vector and the electric field vector', 'Two separate magnetic field vectors with no electric component', 'A single scalar temperature value with no field vectors involved'], 0),
    ('What mathematical operation combines the electric and magnetic fields to produce the Poynting vector?', ['The cross product', 'Simple scalar addition of their magnitudes only', 'Division of one field by the other', 'The dot product, producing a single scalar value'], 0),
    ('What practical quantity can the Poynting vector be used to calculate for a beam of light or a radio signal?', ['The intensity, or rate of energy flow per unit area, of the radiation', 'The exact wavelength of the radiation with no reference to energy', 'The electric charge carried by the radiation', 'The rest mass of the electromagnetic wave'], 0),
    ('Why is the Poynting vector a useful tool for connecting electromagnetic theory to energy transport?', ['It translates the abstract electric and magnetic field description of a wave into a concrete measure of energy flow through space', 'It has no connection to energy transport of any kind', 'It only applies to static electric fields with no wave motion involved', 'It measures mass transport rather than energy transport'], 0)]),
]),
day(164, [
E('The Closet Drama: Plays Written to Be Read, Not Performed',
  'Grade 12 English strand: a closet drama is a play written in dramatic form, complete with dialogue and stage directions, that is intended primarily to be read on the page rather than staged in performance, allowing a writer to use theatrical structure for effects that would be difficult or impossible to realize in a live production.',
  [('What distinguishes a closet drama from a conventional stage play?', ['It is intended primarily to be read rather than performed on stage', 'It contains no dialogue or stage directions of any kind', 'It is legally forbidden from ever being performed under any circumstances', 'It cannot be written in dramatic form at all'], 0),
   ('What formal features does a closet drama typically retain, despite not being intended for performance?', ['Dialogue and stage directions', 'A complete absence of any character or scene structure', 'Only prose narration, with no dramatic form at all', 'Only poetic metre, with no dialogue whatsoever'], 0),
   ('What might a writer gain by using the closet drama form instead of a conventional stageable play?', ['The ability to explore theatrical effects, scale, or content that would be difficult or impossible to stage live', 'Closet drama removes any creative freedom compared to a stageable play', 'Closet drama can only depict extremely simple, small-scale settings', 'A closet drama is identical in every effect to a normal stage play'], 0),
   ('How does the closet drama compare to the verse drama studied in an earlier batch?', ['Verse drama emphasizes poetic form for the stage, while closet drama specifically emphasizes dramatic form intended for reading rather than performance', 'The two forms are entirely identical in intended audience and purpose', 'Closet drama can never contain any poetic language', 'Verse drama is always intended to be read rather than performed'], 0),
   ('Why might a closet drama be considered a genuinely distinct literary form, rather than simply an unperformed stage play?', ['Its intended mode of reception as a text shapes choices a writer makes about scale, imagery, and structure from the outset', 'A closet drama is identical in every respect to a play that simply has not yet been staged', 'The intended audience has no influence on how a dramatic work is written', 'Closet dramas are always converted into conventional novels before publication'], 0)]),
AF('Discrete Math: Dijkstras Algorithm and Shortest Paths in Weighted Graphs',
   'Grade 12 Advanced Functions strand: Dijkstras algorithm finds the shortest path from a starting vertex to every other vertex in a graph with non-negative edge weights, repeatedly selecting the closest unvisited vertex and updating the shortest known distances to its neighbours until every vertex has been finalized.',
   [('What problem does Dijkstras algorithm solve?', ['Finding the shortest path from a starting vertex to every other vertex in a weighted graph', 'Finding the longest possible path between exactly two vertices', 'Counting the total number of vertices in a graph', 'Determining whether a graph contains any cycles at all'], 0),
    ('What requirement must the edge weights of a graph satisfy for Dijkstras algorithm to work correctly?', ['They must be non-negative', 'They must all be exactly equal to one another', 'They must all be negative numbers', 'Edge weights are not permitted at all in this algorithm'], 0),
    ('What does Dijkstras algorithm repeatedly do at each step?', ['Selects the closest unvisited vertex and updates the shortest known distances to its neighbours', 'Selects a completely random vertex with no regard for distance', 'Removes all edges from the graph one at a time', 'Ignores every vertexs neighbours entirely'], 0),
    ('How does Dijkstras algorithm relate to the network flow and max-flow min-cut ideas studied in an earlier batch?', ['Both operate on weighted or capacitated graphs, though Dijkstras algorithm optimizes shortest distance rather than maximum flow', 'The two concepts are entirely unrelated to graph theory', 'Dijkstras algorithm and max-flow min-cut solve exactly the same problem', 'Network flow ignores edge weights entirely, unlike Dijkstras algorithm'], 0),
    ('Why is Dijkstras algorithm widely used in applications such as GPS navigation and network routing?', ['It efficiently finds the shortest or lowest-cost route through a large network of connected points', 'It has no practical application outside of pure theoretical graph theory', 'It only works for graphs containing exactly two vertices', 'It always produces the longest possible route between two points'], 0)]),
CA('Monte Carlo Integration: Numerical Integration by Random Sampling',
   'Grade 12 Calculus strand: Monte Carlo integration estimates the value of a definite integral by randomly sampling points within a region and using the proportion or average of sampled function values to approximate the integral, a technique especially useful for high-dimensional integrals where methods like Simpsons rule become impractical.',
   [('What does Monte Carlo integration use to estimate the value of a definite integral?', ['Randomly sampled points within a region', 'A single, exactly computed function value at one fixed point', 'An entirely deterministic grid with no randomness involved', 'The exact algebraic antiderivative of the function'], 0),
    ('How is the integral estimate typically formed from the randomly sampled points?', ['By using the proportion or average of sampled function values to approximate the integral', 'By discarding all sampled points and returning zero automatically', 'By selecting only the single largest sampled value', 'By ignoring the function values entirely and counting only the number of points'], 0),
    ('In which situation does Monte Carlo integration become especially useful compared to methods like Simpsons rule, studied earlier?', ['For high-dimensional integrals, where grid-based methods become impractical', 'Only for integrals of a single constant function', 'Only for one-dimensional integrals with a known closed-form antiderivative', 'Monte Carlo integration is never preferred over any other numerical method'], 0),
    ('What generally happens to the accuracy of a Monte Carlo integration estimate as more random samples are used?', ['The estimate typically becomes more accurate, converging toward the true integral value', 'Accuracy always decreases as more samples are added', 'The number of samples used has no effect on accuracy at all', 'A single sample always gives the most accurate possible estimate'], 0),
    ('Why does Monte Carlo integration rely fundamentally on the law of large numbers, studied in an earlier batch?', ['Averaging many random samples converges toward the true expected value being estimated, which is the core idea behind the law of large numbers', 'The law of large numbers has no connection to random sampling of any kind', 'Monte Carlo integration produces the same single sample value no matter how many trials are run', 'The law of large numbers only applies to discrete, non-numerical outcomes'], 0)]),
PH('LC Circuits and Electromagnetic Oscillations',
   'Grade 12 Physics strand: an LC circuit consists of an inductor and a capacitor connected together, exchanging energy back and forth between the capacitors electric field and the inductors magnetic field, producing a natural oscillation whose frequency depends on the values of the inductance and capacitance.',
   [('What two components make up a basic LC circuit?', ['An inductor and a capacitor', 'Only two resistors with no other components', 'A battery and a light bulb only', 'Two capacitors with no inductor at all'], 0),
    ('What kind of energy exchange occurs continuously in an oscillating LC circuit?', ['Energy repeatedly transfers between the capacitors electric field and the inductors magnetic field', 'All electrical energy is instantly converted into heat and lost', 'No energy exchange of any kind occurs in this circuit', 'Energy is transferred only to an external light source'], 0),
    ('What determines the natural oscillation frequency of an LC circuit?', ['The values of the inductance and the capacitance', 'The colour of the wires used in the circuit', 'The physical size of the circuit board alone', 'The ambient room temperature exclusively'], 0),
    ('How does an LC circuit compare to the RC circuits studied in an earlier batch?', ['An RC circuit charges and discharges exponentially toward equilibrium, while an LC circuit continuously oscillates by exchanging energy between its two fields', 'The two circuit types behave in an identical way in every respect', 'An RC circuit oscillates indefinitely, exactly like an LC circuit', 'LC circuits contain no capacitor of any kind, unlike RC circuits'], 0),
    ('Why is the LC circuits natural oscillation considered a foundational concept for understanding radio-frequency electronics?', ['Its ability to oscillate at a specific frequency underlies the tuning and signal-generating behaviour used in many radio and communication circuits', 'LC circuits have no application to radio or communication technology', 'LC circuits can only ever produce a single, unchanging direct current', 'Oscillation in an LC circuit has no connection to frequency of any kind'], 0)]),
]),
day(165, [
E('Ergodic Literature and Hypertext Fiction: Reading as Navigation',
  'Grade 12 English strand: ergodic literature requires a reader to perform non-trivial effort to traverse the text, as in hypertext fiction, where clicking or choosing links creates a non-linear reading path, turning the act of reading itself into an act of navigation and making each readers experience of the same work potentially unique.',
  [('What does ergodic literature require of its reader, beyond ordinary sequential reading?', ['Non-trivial effort to traverse the text', 'No reading effort of any kind beyond turning pages in a fixed order', 'A single, identical reading path for every possible reader', 'The complete removal of any reader choice or interaction'], 0),
   ('What structural feature defines hypertext fiction as a form of ergodic literature?', ['Clicking or choosing links creates a non-linear reading path through the text', 'The text can only ever be read in one single, fixed linear order', 'Hypertext fiction removes all links and choices from the reading experience', 'Hypertext fiction is printed exclusively on paper with no digital component'], 0),
   ('How does hypertext fiction turn reading into an act of navigation?', ['Readers actively choose a path through branching or linked text rather than passively following one fixed sequence', 'Readers have no ability to make choices while engaging with hypertext fiction', 'Navigation in hypertext fiction refers only to a physical, real-world location', 'Hypertext fiction eliminates the reader entirely from the reading process'], 0),
   ('How does ergodic literature compare to the choices explored in video game narrative, studied in an earlier batch?', ['Both can give a reader or player meaningful agency in shaping how a narrative unfolds, though ergodic literature applies this idea broadly across written and digital texts', 'The two concepts describe entirely unrelated forms of storytelling', 'Video game narrative always follows a single, fixed linear sequence', 'Ergodic literature can never involve any digital medium'], 0),
   ('Why might two different readers of the same ergodic, hypertext work have genuinely different reading experiences?', ['Their choices at branching points can lead them through different sequences of the same underlying text', 'All readers of an ergodic text are forced to follow the exact same sequence regardless of choice', 'Ergodic texts contain no branching points or reader choices whatsoever', 'Differences between readers experiences are always due to printing errors alone'], 0)]),
AF('Discrete Math: The Stable Marriage Problem and the Gale-Shapley Algorithm',
   'Grade 12 Advanced Functions strand: the stable marriage problem asks how to pair up two equal-sized groups, each with ranked preferences over the other group, so that no two unmatched members would both prefer each other over their assigned partners, a stable pairing that the Gale-Shapley algorithm is guaranteed to construct.',
   [('What does the stable marriage problem ask for?', ['A pairing of two equal-sized groups, based on preferences, with no unmatched pair that would both prefer each other over their assigned partners', 'The single largest possible group with no pairing involved', 'A pairing chosen entirely at random with no reference to preferences', 'A method for counting the total number of people in two groups'], 0),
    ('What information does each member of the two groups provide in this problem?', ['A ranked list of preferences over members of the other group', 'No preferences of any kind', 'A single random number with no connection to preference', 'The exact age of every other member in both groups'], 0),
    ('What guarantee does the Gale-Shapley algorithm provide about the pairing it produces?', ['It always produces a stable pairing, with no pair that would mutually prefer each other over their assigned partners', 'It always produces a pairing that is guaranteed to be unstable', 'It never terminates and produces no pairing at all', 'It ignores the preferences of one of the two groups entirely'], 0),
    ('How does the stable marriage problem relate to bipartite matching, referenced in earlier discrete math batches?', ['It is a specific type of bipartite matching problem, adding preference rankings and a stability requirement on top of simple matching', 'The two ideas have no mathematical relationship whatsoever', 'Bipartite matching always ignores whether the two groups are equal in size', 'Stable marriage matching requires only one group rather than two'], 0),
    ('Why is the stable marriage problem relevant to real-world applications such as matching students to schools?', ['It models how to pair participants with ranked preferences in a way that avoids pairs who would both prefer to swap partners', 'It has no real-world application beyond a purely abstract mathematical puzzle', 'Real-world matching problems never involve any preferences at all', 'The algorithm can only be applied to problems with a single participant'], 0)]),
CA('The Gibbs Phenomenon and Convergence of Fourier Series',
   'Grade 12 Calculus strand: the Gibbs phenomenon is a persistent overshoot that appears near a jump discontinuity when a Fourier series approximation of a function is truncated to finitely many terms, an overshoot that does not vanish as more terms are added, even though the series still converges to the function elsewhere.',
   [('What is the Gibbs phenomenon?', ['A persistent overshoot near a jump discontinuity in a truncated Fourier series approximation', 'A guarantee that a Fourier series always converges perfectly with no error at any point', 'A phenomenon that only occurs in functions with no discontinuities at all', 'A complete failure of the Fourier series to converge anywhere'], 0),
    ('Where does the Gibbs phenomenon specifically appear in a functions Fourier approximation?', ['Near a jump discontinuity in the function being approximated', 'Only at points where the function is perfectly smooth and continuous', 'Uniformly across the entire domain with no special location', 'Only at the single midpoint of the functions domain'], 0),
    ('What happens to the size of the Gibbs overshoot as more terms are added to the truncated Fourier series?', ['The overshoot persists at roughly the same height, even as more terms are added', 'The overshoot disappears completely once even a few terms are included', 'The overshoot grows without bound as more terms are added', 'The overshoot only appears if exactly one term is used'], 0),
    ('Which earlier-studied representation of a function does the Gibbs phenomenon specifically concern?', ['The Fourier series', 'The Taylor series', 'The continued fraction expansion', 'The partial fraction decomposition'], 0),
    ('Why is the Gibbs phenomenon an important practical consideration when using truncated Fourier series to model signals with sharp discontinuities?', ['It shows that truncated approximations can retain a persistent, non-vanishing error near discontinuities, which matters for applications sensitive to overshoot', 'It proves that Fourier series can never be used to approximate any function with a discontinuity', 'It shows that the Gibbs overshoot always vanishes entirely once the series converges', 'It has no practical relevance to any real signal or application'], 0)]),
PH('Polarization of Light and Malus Law',
   'Grade 12 Physics strand: polarization describes the orientation of the oscillations of a light waves electric field, and Malus law gives the intensity of light transmitted through a polarizing filter as proportional to the square of the cosine of the angle between the lights polarization direction and the filters transmission axis.',
   [('What does the polarization of a light wave describe?', ['The orientation of the oscillations of the waves electric field', 'The exact colour or wavelength of the light', 'The total energy carried by the light wave', 'The speed at which the light wave travels through a vacuum'], 0),
    ('What does Malus law describe?', ['The intensity of light transmitted through a polarizing filter as a function of the angle between polarization and the filters axis', 'The exact frequency of a light wave with no reference to polarization', 'The total distance light travels before being absorbed completely', 'The relationship between light intensity and its source temperature only'], 0),
    ('According to Malus law, what mathematical relationship gives the transmitted intensity through a polarizing filter?', ['Intensity proportional to the square of the cosine of the angle between polarization direction and the filters transmission axis', 'Intensity that is always exactly equal to the original, unfiltered intensity', 'Intensity proportional to the angle itself, with no trigonometric function involved', 'Intensity that is always exactly zero regardless of angle'], 0),
    ('What happens to transmitted light intensity, according to Malus law, when the polarization direction is aligned exactly with the filters transmission axis?', ['The transmitted intensity is at its maximum value', 'The transmitted intensity is always exactly zero', 'The transmitted intensity becomes negative', 'The relationship becomes undefined at this particular angle'], 0),
    ('Why are polarizing filters useful in applications such as sunglasses and camera lenses?', ['They can selectively block light oscillating in certain directions, reducing glare from reflected, partially polarized light', 'Polarizing filters have no effect on the light passing through them', 'Polarizing filters block all light regardless of its polarization direction', 'Polarizing filters only function with light that carries no electric field at all'], 0)]),
]),
day(166, [
E('Erasure Poetry: Making New Meaning by Removing Text',
  'Grade 12 English strand: erasure poetry is created by taking an existing source text and removing, blacking out, or otherwise obscuring most of its words, leaving behind a sparse new poem formed from the remaining fragments, turning the act of subtraction itself into a compositional method.',
  [('How is an erasure poem typically created?', ['By removing, blacking out, or otherwise obscuring most of the words in an existing source text', 'By writing an entirely new poem with no source text involved at all', 'By translating an existing poem word for word into another language', 'By memorizing an existing text and reciting it aloud with no changes'], 0),
   ('What forms the actual content of the finished erasure poem?', ['The sparse fragments of the source text left behind after removal', 'An entirely separate text with no relationship to the original source', 'Only the words that were physically removed from the source', 'A summary written by the poet with no reference to the original wording'], 0),
   ('What is distinctive about erasure poetrys compositional method compared to most other poetic forms?', ['It treats subtraction, or removing existing words, as the primary creative act, rather than adding new words', 'It requires the poet to add significantly more words than the original source contained', 'It forbids any use of an existing text as source material', 'It is identical in method to writing an entirely original poem from a blank page'], 0),
   ('How does erasure poetry differ from the found poem, studied in an earlier batch?', ['A found poem typically rearranges or reframes existing text with minimal removal, while erasure poetry is defined specifically by removing most of the source words', 'The two forms are identical in every respect, including their exact method', 'A found poem always adds many new invented words, unlike erasure poetry', 'Erasure poetry never uses any pre-existing source text'], 0),
   ('Why might a poet choose an existing, well-known text as the basis for an erasure poem?', ['Working against a recognizable original can add an extra layer of meaning through the contrast between what is kept and what is removed', 'Using a well-known text removes any possibility of creating new meaning', 'Erasure poems can only ever be created from entirely obscure, unknown texts', 'The identity of the source text has no bearing on the finished poems meaning'], 0)]),
AF('Number Theory: Fermat Primes and Constructible Regular Polygons',
   'Grade 12 Advanced Functions strand: a Fermat prime is a prime number of the special form two raised to a power of two plus one, and a classical result connects these primes to geometry, showing that a regular polygon can be constructed using only a compass and straightedge exactly when its number of sides meets a condition built from distinct Fermat primes.',
   [('What special algebraic form defines a Fermat prime?', ['A prime number of the form two raised to a power of two, plus one', 'Any prime number that is also an even number', 'A prime number that is exactly one less than a power of two', 'Any number that is the sum of two smaller prime numbers'], 0),
    ('What classical geometric question do Fermat primes connect to?', ['Which regular polygons can be constructed using only a compass and straightedge', 'How to compute the exact area of any triangle', 'How to bisect an arbitrary angle using only a compass', 'How to determine the volume of a general polyhedron'], 0),
    ('How many Fermat primes have been confirmed to exist, based on current mathematical knowledge?', ['Only a small, known finite number, with no further ones confirmed despite extensive searching', 'Infinitely many, with a simple formula generating every one', 'Exactly one, and no others are believed to exist', 'None at all; Fermat primes have been proven never to exist'], 0),
    ('How does the Fermat prime construction result build on ideas from the Euclidean algorithm and modular arithmetic studied earlier?', ['It draws on deep number-theoretic results about primes to answer a question originally posed in classical geometry', 'It has no relationship whatsoever to number theory, relying only on geometry', 'It relies entirely on calculus, with no connection to number theory', 'It shows that geometry and number theory can never be meaningfully connected'], 0),
    ('Why is the link between Fermat primes and constructible polygons considered a striking result in mathematics?', ['It connects a purely number-theoretic property of certain primes to a concrete geometric construction question, bridging two very different areas of mathematics', 'It shows that geometry and number theory are entirely unrelated fields', 'It proves that no regular polygon can ever be constructed with compass and straightedge', 'It applies only to polygons with an even number of sides'], 0)]),
CA('Cesaro Summation and Assigning Values to Divergent Series',
   'Grade 12 Calculus strand: Cesaro summation assigns a value to certain divergent series by taking the limit of the averages of their partial sums rather than the partial sums themselves, allowing a meaningful sum to be defined for series, such as the alternating series of ones and negative ones, that do not converge in the ordinary sense.',
   [('What does Cesaro summation compute, instead of taking the limit of a series partial sums directly?', ['The limit of the averages of the partial sums', 'The limit of the individual terms of the series alone', 'The product, rather than any kind of average or sum, of the partial sums', 'The largest single partial sum in the entire sequence'], 0),
    ('What kind of series can Cesaro summation sometimes assign a meaningful value to?', ['Certain divergent series that do not converge in the ordinary sense', 'Only series that already converge in the ordinary sense', 'Only series with a single term and no further terms', 'A series consisting entirely of zeros'], 0),
    ('What value does Cesaro summation classically assign to a simple alternating series of ones and negative ones?', ['One-half, from averaging its oscillating partial sums', 'Exactly zero, with no averaging involved', 'Positive infinity, since the series never settles down', 'The method assigns no value to this series at all'], 0),
    ('How does Cesaro summation relate to Abel summation, studied in an earlier batch?', ['Both are methods for assigning values to certain divergent series, though Abel summation and Cesaro summation use different underlying limiting procedures', 'The two methods are identical in every technical detail', 'Cesaro summation can only be applied to convergent series, unlike Abel summation', 'Abel summation and Cesaro summation have no shared purpose whatsoever'], 0),
    ('Why must a summation method like Cesaro summation be consistent with ordinary convergence for series that do converge normally?', ['It should reproduce the standard sum whenever a series already converges in the usual sense, so it extends rather than contradicts ordinary summation', 'Consistency with ordinary convergence is not a meaningful requirement for any summation method', 'Cesaro summation always contradicts the ordinary sum of a convergent series', 'A summation method must always disagree with the standard result whenever possible'], 0)]),
PH('The Quantum Harmonic Oscillator and Energy Quantization',
   'Grade 12 Physics strand: the quantum harmonic oscillator models a particle in a parabolic potential well and shows that, unlike a classical oscillator, it can only possess discrete, evenly spaced energy levels, including a nonzero minimum called the zero-point energy, illustrating a general feature of bound quantum systems.',
   [('What kind of potential does the quantum harmonic oscillator model a particle as moving within?', ['A parabolic potential well', 'A completely flat potential with no variation at all', 'A potential that exists only outside of any bound region', 'A potential defined solely by electric charge with no spatial shape'], 0),
    ('How do the allowed energy levels of the quantum harmonic oscillator differ from those of a classical oscillator?', ['They are discrete and evenly spaced, rather than forming a smooth continuous range', 'They are identical in every way to the continuous energies allowed classically', 'The quantum oscillator allows only a single fixed energy level with no others possible', 'Quantum energy levels are always spaced further apart at lower energies than at higher ones'], 0),
    ('What is the zero-point energy of a quantum harmonic oscillator?', ['A nonzero minimum energy the system always retains, even in its lowest possible state', 'An energy level equal to exactly zero in the lowest possible state', 'The maximum possible energy the oscillator can ever reach', 'An energy value that only applies to classical, non-quantum oscillators'], 0),
    ('How does the quantum harmonic oscillator illustrate a general feature shared with other bound quantum systems, such as the atom studied earlier?', ['Confinement leads to quantized, discrete energy levels rather than a continuous range of allowed energies', 'Bound quantum systems never display any quantization of energy', 'The quantum harmonic oscillator behaves identically to a completely free, unbound particle', 'Energy quantization is a feature unique to the harmonic oscillator alone'], 0),
    ('Why is the quantum harmonic oscillator considered an especially important model system in quantum mechanics?', ['Many more complicated physical systems can be approximated, near a stable equilibrium, by a harmonic oscillator potential', 'It has no application to any physical system beyond a single idealized spring', 'It is the only quantum system in which energy levels are ever quantized', 'The model applies exclusively to macroscopic, classical-scale objects'], 0)]),
]),
day(167, [
E('The Jeremiad: The Rhetoric of Lament and Warning',
  'Grade 12 English strand: a jeremiad is a rhetorical mode of impassioned lament and moral warning, named for the biblical prophet Jeremiah, that condemns a communitys present corruption while calling for a return to earlier values, a structure that has recurred throughout political and religious oratory.',
  [('What two rhetorical elements does a jeremiad typically combine?', ['Impassioned lament over present corruption and a call to return to earlier values', 'Pure celebration with no criticism of any kind', 'A neutral, purely factual description with no persuasive intent', 'Silence and the complete avoidance of any moral judgment'], 0),
   ('After which figure is the jeremiad named?', ['The biblical prophet Jeremiah', 'A Roman emperor with no connection to prophecy', 'A modern political theorist with no historical prophetic tradition', 'An ancient Greek dramatist unrelated to biblical tradition'], 0),
   ('In what kind of discourse has the jeremiad structure often recurred throughout history?', ['Political and religious oratory', 'Only in private, unpublished personal letters', 'Only in strictly factual scientific writing', 'Only in purely comic or satirical writing with no serious intent'], 0),
   ('How does the jeremiad compare to the op-ed form studied in an earlier batch?', ['Both can argue publicly for change, but the jeremiad specifically follows a lament-and-warning structure rooted in a longstanding rhetorical and prophetic tradition', 'The two forms are identical in structure, audience, and historical origin', 'An op-ed can never contain any critical or persuasive content', 'The jeremiad has no connection to persuasive or rhetorical purpose at all'], 0),
   ('Why might a speaker invoke a jeremiads structure of lament and warning to motivate an audience toward change?', ['Framing present problems as a decline from once-held values can create urgency and a sense of shared moral stakes', 'A jeremiad structure removes any sense of urgency from an argument', 'This rhetorical structure has never been used to motivate any audience', 'Lament and warning are incompatible with any call for future action'], 0)]),
AF('Number Theory: Bertrands Postulate and Prime Gaps',
   'Grade 12 Advanced Functions strand: Bertrands postulate states that for every integer greater than one, there is always at least one prime number between it and its double, a guarantee about how far apart consecutive primes can be that complements broader results such as the prime number theorem studied earlier.',
   [('What does Bertrands postulate guarantee about primes near a given integer greater than one?', ['At least one prime number exists between the integer and its double', 'No prime number can ever exist between the integer and its double', 'Exactly one hundred primes always exist in that range', 'The integer itself must always be prime'], 0),
    ('What kind of mathematical statement is Bertrands postulate, despite its name?', ['A proven theorem about the distribution of prime numbers', 'An unproven conjecture with no known proof', 'A statement that has been definitively disproven', 'A purely geometric statement with no connection to prime numbers'], 0),
    ('How does Bertrands postulate relate to the concept of prime gaps?', ['It places an upper bound on how large the gap between certain consecutive primes can be', 'It proves that prime gaps must always be exactly one', 'It shows that prime gaps grow without any bound whatsoever, even for small integers', 'Bertrands postulate has no connection to the spacing between primes'], 0),
    ('How does Bertrands postulate complement the prime number theorem, studied in an earlier batch?', ['Both describe how primes are distributed among the integers, though the prime number theorem gives an average density while Bertrands postulate gives a guaranteed local bound', 'The two results contradict each other directly', 'The prime number theorem and Bertrands postulate address entirely unrelated mathematical questions', 'Bertrands postulate replaces the need for the prime number theorem entirely'], 0),
    ('Why is a guaranteed bound like Bertrands postulate useful, even though it is a relatively coarse statement about prime spacing?', ['It provides a simple, reliable guarantee about locating a prime within a specific range, which can be a useful stepping stone in other proofs', 'A coarse guarantee about prime spacing has no mathematical usefulness whatsoever', 'It gives the exact location of every prime number with no uncertainty at all', 'It applies only to a single specific integer and no others'], 0)]),
CA('The Riemann Rearrangement Theorem and Conditionally Convergent Series',
   'Grade 12 Calculus strand: the Riemann rearrangement theorem states that the terms of a conditionally convergent series, one that converges only because of cancellation between positive and negative terms rather than absolute convergence, can be reordered to converge to any chosen real number, or even to diverge entirely.',
   [('What surprising conclusion does the Riemann rearrangement theorem reach about certain series?', ['Reordering the terms of a conditionally convergent series can change its sum to any chosen real number, or make it diverge', 'Reordering the terms of any series always leaves its sum completely unchanged', 'Rearranging terms is never mathematically permitted for any type of series', 'Every series becomes divergent the moment its terms are reordered'], 0),
    ('What defines a conditionally convergent series, as distinct from an absolutely convergent one?', ['It converges only because of cancellation between positive and negative terms, not because the series of absolute values converges', 'It converges regardless of the order in which its terms are summed', 'It contains only positive terms with no cancellation of any kind', 'It never converges under any possible arrangement of its terms'], 0),
    ('Does the Riemann rearrangement theorem apply to absolutely convergent series in the same surprising way?', ['No, absolutely convergent series converge to the same sum regardless of how their terms are rearranged', 'Yes, absolutely convergent series can also be rearranged to sum to any value', 'The theorem applies only to series with a single nonzero term', 'Absolutely convergent series can never be summed under any rearrangement'], 0),
    ('Which earlier-studied convergence tests help distinguish conditional convergence from absolute convergence for an alternating series?', ['The alternating series test, together with a comparison of the series of absolute values', 'The binomial theorem, with no connection to convergence testing', 'The pigeonhole principle, which addresses a different type of problem entirely', 'The quadratic formula, which has no bearing on infinite series'], 0),
    ('Why is the Riemann rearrangement theorem considered a cautionary result about infinite series?', ['It shows that some familiar rules of finite arithmetic, such as the order of addition not mattering, can fail dramatically for infinite series', 'It confirms that infinite sums always behave exactly like finite sums in every respect', 'It shows that no infinite series can ever be rearranged under any circumstances', 'It proves that conditional convergence is mathematically impossible'], 0)]),
PH('Exoplanet Detection: The Transit and Radial Velocity Methods',
   'Grade 12 Physics strand: exoplanets, planets orbiting stars beyond our solar system, are commonly detected using the transit method, which measures the small periodic dip in a stars brightness as a planet passes in front of it, and the radial velocity method, which measures the tiny wobble a planets gravity induces in its stars motion.',
   [('What does the transit method use to detect an exoplanet?', ['A small, periodic dip in a stars brightness as the planet passes in front of it', 'A sudden, permanent increase in the stars total brightness', 'The exact colour of the planet as seen directly through a telescope', 'A measurement of the planets surface temperature from Earth'], 0),
    ('What physical effect does the radial velocity method rely on to detect an exoplanet?', ['A tiny wobble in the stars motion caused by the gravitational pull of the orbiting planet', 'A complete stop in the stars motion caused by the planet', 'A direct, unobstructed photograph of the planet itself', 'A measurable change in the stars chemical composition'], 0),
    ('What periodic pattern in stellar brightness is characteristic of a successful transit detection?', ['A small dip in brightness that repeats regularly as the planet orbits the star', 'A single, permanent, non-repeating loss of all stellar brightness', 'A random, irregular pattern with no periodicity at all', 'A brightness increase rather than any decrease'], 0),
    ('Which earlier-studied wave phenomenon underlies how the radial velocity method detects a stars wobble?', ['The Doppler effect, applied to shifts in the stars observed light spectrum', 'The photoelectric effect, with no connection to Doppler shifts', 'Total internal reflection, unrelated to any motion of the star', 'Structural colour, which has no connection to stellar spectra'], 0),
    ('Why do astronomers often use both the transit and radial velocity methods together when studying the same exoplanet?', ['Combining both methods can reveal additional properties, such as the planets mass and radius, that neither method alone fully provides', 'Using two different methods together always produces contradictory, unusable results', 'The transit method alone provides complete information with no need for any other method', 'The two methods can never be applied to the same exoplanet system'], 0)]),
]),
day(168, [
E('The Verse Essay: Discursive Argument in Poetic Form',
  'Grade 12 English strand: a verse essay presents a sustained, discursive argument or reflection, much like a prose essay, but does so using the compressed, patterned language of poetry, showing that reasoned argument and poetic form are not mutually exclusive modes of writing.',
  [('What does a verse essay attempt to do, similar to a prose essay?', ['Present a sustained, discursive argument or reflection', 'Tell a purely fictional story with no argumentative content', 'Record a private, unstructured diary entry with no wider audience', 'Present a list of facts with absolutely no interpretive argument'], 0),
   ('What formal quality distinguishes a verse essay from a conventional prose essay?', ['It uses the compressed, patterned language of poetry rather than ordinary prose', 'It contains no argument or reasoning of any kind', 'It must always be exactly fourteen lines long, like a sonnet', 'It forbids the use of any structured reasoning whatsoever'], 0),
   ('What does the existence of the verse essay suggest about the relationship between poetry and argument?', ['That reasoned argument and poetic form are not mutually exclusive modes of writing', 'That poetry can never contain any form of reasoned argument', 'That prose is the only form capable of sustained argument', 'That verse essays never engage with ideas or reflection of any kind'], 0),
   ('How might a verse essay differ in effect from the extended metaphor as argument, studied in an earlier batch?', ['A verse essay sustains an entire discursive argument in poetic form, while an extended metaphor is a single figurative device that can appear within many kinds of writing', 'The two concepts describe exactly the same technique with no distinction', 'An extended metaphor always requires an entire poem-length argument', 'A verse essay can never include any figurative language such as metaphor'], 0),
   ('Why might a writer choose the compressed, patterned language of verse to develop an extended argument, rather than plain prose?', ['The rhythm, imagery, and compression of verse can add emotional and aesthetic force to an argument beyond what plain prose alone provides', 'Verse form always weakens the clarity of any argument being made', 'Poetic language is incapable of conveying any reasoned idea', 'A verse essay is defined by the complete absence of any reasoning'], 0)]),
AF('Functions: Liouville Numbers and the Existence of Transcendental Numbers',
   'Grade 12 Advanced Functions strand: a Liouville number is a real number that can be approximated extremely closely by rational numbers, closely enough to prove it cannot be the root of any polynomial with integer coefficients, making Liouville numbers the first numbers ever explicitly proven to be transcendental.',
   [('What special approximation property defines a Liouville number?', ['It can be approximated extremely closely by rational numbers, more closely than typical irrational numbers allow', 'It cannot be approximated by any rational number whatsoever', 'It is always itself a rational number with a simple fraction form', 'It is defined only as the root of a specific integer polynomial'], 0),
    ('What broader category of numbers does every Liouville number belong to?', ['Transcendental numbers, meaning it is not the root of any polynomial with integer coefficients', 'Algebraic numbers that satisfy some polynomial with integer coefficients', 'Rational numbers expressible as a simple fraction', 'Prime numbers with no fractional or decimal component'], 0),
    ('What was historically significant about the discovery of Liouville numbers?', ['They were the first numbers ever explicitly proven to be transcendental', 'They were the first numbers ever proven to be rational', 'They disproved the existence of any transcendental number', 'They were the first numbers shown to be roots of integer polynomials'], 0),
    ('How does the concept of a Liouville number relate to continued fractions, studied in an earlier batch?', ['Extremely good rational approximations, similar to those produced by continued fraction truncations, are central to how Liouville numbers are constructed and identified', 'Continued fractions have no relationship whatsoever to how well a number can be approximated', 'Liouville numbers can only ever be represented as a single simple fraction', 'Continued fractions apply only to rational numbers, never to transcendental ones'], 0),
    ('Why was proving the existence of transcendental numbers considered an important mathematical milestone?', ['It confirmed that not every real number can be described as the root of a polynomial with integer coefficients, revealing a genuinely different class of numbers', 'It proved that every real number must be algebraic, with no exceptions', 'It showed that transcendental numbers and rational numbers are exactly the same set', 'It had no impact on the broader understanding of the real number system'], 0)]),
CA('Asymptotic Expansions and Approximating Functions for Large Arguments',
   'Grade 12 Calculus strand: an asymptotic expansion approximates a function using a series that may not converge in the usual sense, yet whose early terms give an increasingly accurate approximation as the argument grows large, a technique especially valuable for functions with no simple closed form, such as certain special functions studied earlier.',
   [('What is distinctive about an asymptotic expansion compared to a standard convergent series such as a Taylor series?', ['It may not converge in the usual sense, yet its early terms still give an increasingly accurate approximation as the argument grows large', 'It always converges in exactly the same way as a Taylor series', 'It can only ever be used for functions with a simple closed form', 'It requires the argument to remain small rather than large'], 0),
    ('In what regime, small or large arguments, is an asymptotic expansion typically most useful?', ['Large arguments', 'Only arguments extremely close to zero', 'Only arguments that are exactly equal to one', 'Asymptotic expansions are never tied to any particular size of argument'], 0),
    ('For which kind of functions studied earlier in this course might an asymptotic expansion be especially valuable?', ['Special functions with no simple closed form, such as the Gamma function or Bessel functions', 'Only basic polynomial functions with an already simple closed form', 'Only constant functions with a single fixed value', 'Functions that already have an exact and simple algebraic formula'], 0),
    ('How does the usefulness of an asymptotic expansion despite non-convergence compare to the behaviour of a divergent series studied in this batch, such as under Cesaro summation?', ['Both situations show that a series need not converge in the ordinary sense to still carry meaningful, useful mathematical information', 'Asymptotic expansions and divergent series share no conceptual similarity whatsoever', 'An asymptotic expansion must always converge in the ordinary sense to be useful', 'Cesaro summation and asymptotic expansions apply exclusively to polynomial functions'], 0),
    ('Why might a scientist or engineer prefer an asymptotic expansion over an exact but extremely complicated closed-form expression?', ['A truncated asymptotic expansion can give a simple, sufficiently accurate approximation for large arguments without needing to evaluate an unwieldy exact formula', 'Asymptotic expansions are always less accurate than any exact closed-form expression', 'Exact closed-form expressions are never more complicated than an asymptotic approximation', 'Asymptotic expansions can only ever be used for purely theoretical purposes with no practical value'], 0)]),
PH('Olbers Paradox: Why Is the Night Sky Dark',
   'Grade 12 Physics strand: Olbers paradox asks why the night sky is dark rather than uniformly bright, given that in an infinite, static universe filled evenly with stars every line of sight should eventually terminate on a stars surface, a puzzle resolved by the universes finite age and the expansion revealed by cosmological redshift.',
   [('What observational fact does Olbers paradox attempt to explain?', ['Why the night sky appears dark rather than uniformly bright', 'Why the daytime sky appears blue rather than another colour', 'Why stars appear to twinkle rather than shine steadily', 'Why the Moon appears to change shape over the course of a month'], 0),
    ('Under the assumption of an infinite, static, evenly star-filled universe, what would every line of sight from Earth eventually be expected to hit?', ['The surface of some star, making the entire sky appear bright', 'Empty space with absolutely no light reaching Earth at all', 'A single, unique star directly overhead only', 'Nothing at all, since light could never reach Earth in such a universe'], 0),
    ('Which two features of the actual universe help resolve Olbers paradox?', ['The universes finite age and its ongoing cosmic expansion', 'The complete absence of any stars in the universe', 'The fact that all stars are located at exactly the same distance from Earth', 'The claim that light from stars never actually reaches Earth'], 0),
    ('How does cosmological redshift, arising from the universes expansion, contribute to explaining the darkness of the night sky?', ['It shifts light from very distant, receding sources toward longer wavelengths, reducing the visible brightness reaching Earth', 'Redshift makes every distant star appear brighter than it otherwise would', 'Redshift has no connection whatsoever to the observed darkness of the sky', 'Redshift only affects sound waves, not light from distant stars'], 0),
    ('Why is Olbers paradox considered an important historical puzzle in cosmology?', ['Resolving it required insights into the finite age and expansion of the universe, ideas central to modern cosmological models', 'It was resolved without any reference to the age or expansion of the universe', 'It has no connection to how modern cosmological models were developed', 'It was resolved by proving that stars do not actually emit any light'], 0)]),
]),
day(169, [
E('The Roman-Fleuve: The Multi-Volume Novel Sequence',
  'Grade 12 English strand: a roman-fleuve, literally a river novel, is an extended sequence of related novels that follows a set of characters, a family, or a community across multiple volumes and often several decades, allowing a scale and cumulative depth of development no single novel could achieve alone.',
  [('What does the term roman-fleuve literally translate to?', ['River novel', 'Broken novel', 'Silent novel', 'Frame novel'], 0),
   ('What structural feature defines a roman-fleuve as a literary form?', ['An extended sequence of related novels following characters, a family, or a community across multiple volumes', 'A single, self-contained novel with no sequel or related volumes at all', 'A collection of entirely unrelated short stories with no shared characters', 'A single volume that must be read in a completely non-linear order'], 0),
   ('What span of time does a roman-fleuve often cover across its multiple volumes?', ['Often several decades', 'A single afternoon, with no passage of time at all', 'Exactly twenty-four hours, mirroring a single day', 'A period that must always be under one calendar year'], 0),
   ('How does the roman-fleuve differ from the serial novel, studied in an earlier batch, which was published in periodic instalments?', ['The roman-fleuve is defined by its multi-volume novel structure and scale, while the serial novel is defined by its instalment-based method of original publication', 'The two forms are identical in both structure and method of publication', 'A serial novel can never be published as a sequence of separate volumes', 'The roman-fleuve is always published in a single instalment with no volumes'], 0),
   ('Why might an author choose the roman-fleuve form to portray a family or community over time?', ['Multiple volumes allow gradual, cumulative development of character and social change that a single novel could not fully capture', 'A multi-volume structure makes any long-term character development impossible', 'Portraying change over decades is always better achieved within a single short story', 'The roman-fleuve form forbids depicting more than one central character'], 0)]),
AF('Functions: The Runge Phenomenon and the Limits of Polynomial Interpolation',
   'Grade 12 Advanced Functions strand: the Runge phenomenon is the tendency of a high-degree polynomial interpolation through equally spaced points to oscillate wildly near the edges of the interval, showing that simply increasing polynomial degree does not always improve the accuracy of an interpolated approximation.',
   [('What does the Runge phenomenon describe?', ['Wild oscillation near the edges of an interval when interpolating with a high-degree polynomial through equally spaced points', 'A guarantee that higher-degree polynomial interpolation always improves accuracy everywhere', 'A phenomenon that only ever occurs with linear, first-degree interpolation', 'The complete failure of any polynomial to pass through the given data points'], 0),
    ('What spacing of interpolation points is classically associated with triggering the Runge phenomenon?', ['Equally spaced points', 'Points spaced according to a special, unevenly clustered pattern near the edges', 'A single repeated point used many times over', 'Points chosen entirely at random with no fixed spacing rule'], 0),
    ('What does the Runge phenomenon reveal about the relationship between polynomial degree and interpolation accuracy?', ['Simply increasing the polynomial degree does not always improve the accuracy of the interpolated approximation', 'Higher polynomial degree always produces a strictly better approximation with no exceptions', 'Polynomial degree has no effect whatsoever on interpolation accuracy', 'Only degree-one polynomials can ever be used for interpolation'], 0),
    ('How does the Runge phenomenon relate to polynomial interpolation and Lagranges method, studied in an earlier batch?', ['It reveals a practical limitation of naive high-degree polynomial interpolation using equally spaced points, a method built directly on Lagranges approach', 'It has no connection whatsoever to polynomial interpolation of any kind', 'Lagranges method is entirely immune to the Runge phenomenon under all conditions', 'The Runge phenomenon only applies to trigonometric functions, not polynomials'], 0),
    ('Why is the Runge phenomenon an important practical consideration for anyone building a numerical approximation from sampled data?', ['It shows that careful choice of interpolation points and method matters, since a naive high-degree fit at equally spaced points can actually worsen accuracy', 'It shows that interpolation should always use the highest possible polynomial degree with no other consideration', 'It proves that numerical approximation from data is always perfectly accurate regardless of method', 'It only matters for functions with an already simple, low-degree closed form'], 0)]),
CA('The Total Derivative and Differentiability in Several Variables',
   'Grade 12 Calculus strand: the total derivative of a multivariable function captures how the function changes in response to small changes in all of its variables simultaneously, providing the precise formal criterion for differentiability in several variables that goes beyond simply having each individual partial derivative exist.',
   [('What does the total derivative of a multivariable function capture?', ['How the function changes in response to small changes in all of its variables simultaneously', 'How the function changes with respect to only a single variable, ignoring all others', 'The value of the function at a single isolated point, with no reference to change', 'The average value of the function across its entire domain'], 0),
    ('What formal mathematical role does the total derivative play for a multivariable function?', ['It provides the precise criterion for differentiability in several variables', 'It has no connection to the concept of differentiability at all', 'It only applies to functions of a single variable', 'It replaces the need to ever compute a partial derivative'], 0),
    ('Why is having each individual partial derivative exist not automatically sufficient for a multivariable function to be considered differentiable?', ['The existence of individual partial derivatives alone does not guarantee the more demanding condition of a well-behaved linear approximation in every direction at once', 'Existence of partial derivatives is always completely sufficient for differentiability with no exceptions', 'Partial derivatives and differentiability are entirely unrelated concepts', 'A function can never have partial derivatives without also being fully differentiable'], 0),
    ('How does the total derivative relate to the gradient vector and directional derivatives, studied in an earlier batch?', ['The total derivative provides the underlying linear approximation from which directional derivatives, computed using the gradient, can be derived in any direction', 'The gradient vector has no mathematical relationship to the total derivative', 'Directional derivatives can only be computed for functions of a single variable', 'The total derivative and the gradient vector describe completely unrelated mathematical objects'], 0),
    ('Why is a rigorous notion of the total derivative important for extending single-variable calculus concepts, such as the chain rule, to multivariable functions?', ['It gives the proper linear approximation framework needed to correctly generalize rules like the chain rule to functions of several variables', 'Single-variable calculus concepts never need to be extended to multivariable functions', 'The total derivative removes any need for a chain rule in multivariable calculus', 'A rigorous total derivative has no bearing on how other calculus rules generalize'], 0)]),
PH('Band Theory of Solids: Conductors, Insulators, and Semiconductors',
   'Grade 12 Physics strand: band theory explains the electrical behaviour of solids by describing how the allowed energy levels of electrons in a crystal merge into continuous bands, with the size of the gap between a filled valence band and the next available conduction band determining whether a material behaves as a conductor, insulator, or semiconductor.',
   [('What structures does band theory describe forming from the allowed energy levels of electrons in a crystal?', ['Continuous energy bands', 'A single, isolated energy level with no surrounding structure', 'A set of completely random, unrelated energy values', 'A structure identical for every possible material with no variation'], 0),
    ('What determines whether a material behaves as a conductor, insulator, or semiconductor, according to band theory?', ['The size of the energy gap between the filled valence band and the next available conduction band', 'The colour of the material as seen by the human eye', 'The exact physical shape into which the material has been cut', 'The materials temperature at the moment it was first formed'], 0),
    ('How does a conductor typically differ from an insulator in terms of this energy gap?', ['A conductor has little or no gap, allowing electrons to move into the conduction band easily, while an insulator has a large gap that strongly resists this', 'A conductor always has a larger energy gap than an insulator', 'Conductors and insulators always have exactly the same size of energy gap', 'The energy gap has no influence on whether a material conducts electricity'], 0),
    ('How does band theory provide a deeper explanation for the behaviour of semiconductors, studied in an earlier batch as a more applied topic?', ['It explains semiconductor behaviour in terms of a moderate energy gap that can be overcome under the right conditions, unlike the gaps in typical conductors or insulators', 'Band theory has no connection whatsoever to how semiconductors behave', 'Semiconductors are explained by band theory as having no energy gap of any kind', 'Band theory shows that semiconductors and insulators always behave in an identical way'], 0),
    ('Why is band theory considered a fundamental framework in condensed matter physics?', ['It provides a unified quantum-mechanical explanation for the electrical behaviour of a very wide range of solid materials', 'It only applies to a single specific material with no broader application', 'It explains electrical behaviour without any reference to quantum mechanics at all', 'Band theory is limited exclusively to materials that conduct no electricity whatsoever'], 0)]),
]),
day(170, [
E('English Review: Dramatic Forms, Satire, Rhetoric, and the Novel Sequence',
  'Grade 12 English review: revisiting the morality play, the revenge tragedy, Menippean satire, the closet drama, and ergodic literature and hypertext fiction from Days 161-165.',
  [('What kind of characters typically populate a morality play?', ['Personifications of abstract qualities, such as Virtue or Vice', 'Historical figures with no symbolic meaning at all', 'Animals with no connection to human conduct', 'Characters drawn entirely from ancient myth with no allegory involved'], 0),
   ('What central action drives the plot of a revenge tragedy?', ['A protagonist pursuing vengeance for a grievous wrong, typically a murder', 'A protagonist entirely uninterested in justice or retribution', 'A protagonist who forgives every wrong immediately with no conflict', 'A plot with no central grievance or wrong of any kind'], 0),
   ('What does Menippean satire primarily target?', ['Mental attitudes, such as pedantry or dogmatism, rather than specific individuals', 'Only named, real individuals with no attention to ideas', 'A single historical event with no interest in ideas or attitudes', 'Only physical appearance, with no interest in intellectual attitudes'], 0),
   ('What distinguishes a closet drama from a conventional stage play?', ['It is intended primarily to be read rather than performed on stage', 'It contains no dialogue or stage directions of any kind', 'It is legally forbidden from ever being performed under any circumstances', 'It cannot be written in dramatic form at all'], 0),
   ('What does ergodic literature require of its reader, beyond ordinary sequential reading?', ['Non-trivial effort to traverse the text', 'No reading effort of any kind beyond turning pages in a fixed order', 'A single, identical reading path for every possible reader', 'The complete removal of any reader choice or interaction'], 0)]),
AF('AdvancedFunctions Review: Inference, Graph Algorithms, and Prime Structure',
   'Grade 12 Advanced Functions review: revisiting the Student t-distribution, ANOVA, Hamiltonian paths and cycles, Dijkstras algorithm, and the stable marriage problem from Days 161-165.',
   [('When is the Student t-distribution typically used instead of the normal distribution?', ['When estimating a population mean from a small sample with an unknown population standard deviation', 'Only when the entire population has already been measured directly', 'When the population standard deviation is known exactly in advance', 'Only for samples larger than several thousand observations'], 0),
    ('What question does an ANOVA test primarily answer?', ['Whether the means of three or more groups differ significantly from one another', 'Whether a single data point is an outlier', 'Whether exactly two population parameters are identical', 'Whether a sample was collected using a random method'], 0),
    ('What must a Hamiltonian path do, with respect to the vertices of a graph?', ['Visit every vertex exactly once', 'Visit only a single vertex, ignoring all others', 'Visit every edge exactly once, ignoring the vertices', 'Avoid visiting any vertex at all'], 0),
    ('What problem does Dijkstras algorithm solve?', ['Finding the shortest path from a starting vertex to every other vertex in a weighted graph', 'Finding the longest possible path between exactly two vertices', 'Counting the total number of vertices in a graph', 'Determining whether a graph contains any cycles at all'], 0),
    ('What does the stable marriage problem ask for?', ['A pairing of two equal-sized groups, based on preferences, with no unmatched pair that would both prefer each other over their assigned partners', 'The single largest possible group with no pairing involved', 'A pairing chosen entirely at random with no reference to preferences', 'A method for counting the total number of people in two groups'], 0)]),
CA('Calculus Review: Systems, Numerical Methods, and Series Behaviour',
   'Grade 12 Calculus review: revisiting systems of linear differential equations, Sturm-Liouville theory, the Adams-Bashforth method, Monte Carlo integration, and the Gibbs phenomenon from Days 161-165.',
   [('What does a system of linear differential equations describe?', ['Several interrelated quantities changing over time at once', 'A single isolated quantity with no relationship to any other variable', 'A purely algebraic system with no rates of change involved', 'A system with no matrix representation possible'], 0),
    ('What kind of equation does Sturm-Liouville theory study?', ['A class of second-order differential equations with associated boundary conditions', 'A purely algebraic equation with no derivatives involved', 'A first-order equation with no boundary conditions of any kind', 'An equation with no possible eigenfunction solutions'], 0),
    ('What distinguishes a multistep method like Adams-Bashforth from a single-step method such as Eulers method?', ['It estimates each new value using several previously computed points rather than only the most recent one', 'It uses no previous data of any kind at every step', 'It requires recomputing the entire solution from scratch at every step', 'It can only ever be applied to algebraic equations, not differential ones'], 0),
    ('What does Monte Carlo integration use to estimate the value of a definite integral?', ['Randomly sampled points within a region', 'A single, exactly computed function value at one fixed point', 'An entirely deterministic grid with no randomness involved', 'The exact algebraic antiderivative of the function'], 0),
    ('What is the Gibbs phenomenon?', ['A persistent overshoot near a jump discontinuity in a truncated Fourier series approximation', 'A guarantee that a Fourier series always converges perfectly with no error at any point', 'A phenomenon that only occurs in functions with no discontinuities at all', 'A complete failure of the Fourier series to converge anywhere'], 0)]),
PH('Physics Review: Rotation, Fields, Optics, and Quantum Confinement',
   'Grade 12 Physics review: revisiting gyroscopic precession, rolling without slipping, the Poynting vector, LC circuits, and polarization and Malus law from Days 161-165.',
   [('What is gyroscopic precession?', ['The slow sweeping of a spinning objects axis in a cone shape under an external torque', 'The instant collapse of a spinning object the moment any torque is applied', 'A spinning objects tendency to speed up indefinitely with no external influence', 'The complete absence of any motion in a spinning object'], 0),
    ('What condition defines rolling without slipping?', ['The point of contact between the object and the surface has zero relative velocity', 'The object slides freely with no rotation at all', 'The object spins in place with no translational motion whatsoever', 'The surface and the object never make contact'], 0),
    ('What does the Poynting vector describe about an electromagnetic wave?', ['The direction and rate of energy flow it carries', 'The exact colour of the light involved', 'The mass of the particles composing the wave', 'The temperature of the medium the wave travels through'], 0),
    ('What two components make up a basic LC circuit?', ['An inductor and a capacitor', 'Only two resistors with no other components', 'A battery and a light bulb only', 'Two capacitors with no inductor at all'], 0),
    ('What does the polarization of a light wave describe?', ['The orientation of the oscillations of the waves electric field', 'The exact colour or wavelength of the light', 'The total energy carried by the light wave', 'The speed at which the light wave travels through a vacuum'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g12_161_170)
    append_to(12, g12_161_170)
