#!/usr/bin/env python3
"""Grade 12 — days 16-30."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,append_to

def E(t,s,u,q):return sub('English',t,s,'TED-Ed: Literature',u,q)
def A(t,s,u,q):return sub('Advanced Functions',t,s,'Khan Academy',u,q)
def Ca(t,s,u,q):return sub('Calculus',t,s,'Khan Academy Calculus',u,q)
def P(t,s,u,q):return sub('Physics',t,s,'Crash Course Physics',u,q)

g12b=[
day(16,[
E('Postcolonial Literature: Writing Back to Empire','Students examine postcolonial theory and its application to literary texts — how writers from formerly colonised nations rewrite colonial narratives.','https://www.youtube.com/watch?v=G15p7uOc-aA',[
  ('The term "writing back" (Ashcroft et al.) refers to ___.',['authors responding to publisher rejections','only African literature','only protest poetry','postcolonial writers engaging with, subverting, and rewriting the canonical texts of the colonising culture — reclaiming language and narrative for suppressed perspectives'],3),
  ('Chinua Achebe\'s critique of Conrad\'s Heart of Darkness argues ___.',['the novel is flawless','Conrad was not a racist','the novel is primarily about navigation','Conrad dehumanises Africans by making Africa merely a backdrop for a European psychological journey — denying African people interiority, agency, and humanity'],3),
  ('The use of the coloniser\'s language by postcolonial writers is ___.',['a sign of cultural defeat','never chosen freely','unproblematic and straightforward','a complex negotiation — some see it as accommodation, others as strategic subversion; many writers (Achebe, Ngugi, Rushdie) have debated this directly in essays and in their fiction'],3),
  ('Hybridity (Homi Bhabha) in postcolonial literature refers to ___.',['mixing languages only','a purely biological concept','cultural purity in new nations','the complex cultural mixing produced by colonialism — neither purely coloniser nor colonised, but a "third space" of negotiated identity'],3),
  ('Applying postcolonial theory to a Canadian text requires ___.',['recognising Canada has no colonial history','only examining French-English relations','treating all colonial experiences as identical','acknowledging Canada\'s specific colonial history — both as a British colony and as a settler-colonial state with ongoing impacts on Indigenous peoples — a complex dual position'],3)]),
A('Vectors in Three Dimensions','Students extend 2D vector concepts to 3D — Cartesian coordinates, vector operations, magnitude, dot product, and angle between vectors.','https://www.youtube.com/watch?v=k7RM-ot2NWY',[
  ('A vector in 3D is written as ___.',['(x, y)','[x:y:z]','x + y + z','a = (a₁, a₂, a₃) or a₁i + a₂j + a₃k — three components corresponding to x, y, z directions'],3),
  ('The magnitude of a = (2, −1, 3) is ___.',['6','2 + 1 + 3 = 6','√(4+1+9) = √14','√(2+1+3) = √6'],2),
  ('The dot product a · b for a=(1,2,3) and b=(4,−1,2) is ___.',['(4,−2,6)','4−1+6 = 9... wait: 1×4 + 2×(−1) + 3×2 = 4 − 2 + 6 = 8','4 + 2 + 6 = 12','1×4 − 2×1 + 3×2 = 8'],3),
  ('The angle θ between vectors a and b satisfies ___.',['sinθ = a·b/(|a||b|)','cosθ = |a|/|b|','tanθ = a·b','cosθ = a·b/(|a||b|) — rearranging the dot product formula: a·b = |a||b|cosθ'],3),
  ('Two vectors in 3D are perpendicular when ___.',['they have equal magnitudes','their components are proportional','|a| = |b| = 1','their dot product equals zero: a·b = a₁b₁ + a₂b₂ + a₃b₃ = 0'],3)]),
Ca('Related Rates: Advanced Applications','Students solve multi-step related rates problems in geometry, physics, and engineering contexts.','https://www.youtube.com/watch?v=I9mVUo-bhM8',[
  ('The key step in any related rates problem is ___.',['to differentiate the known quantity','to find the maximum value','only to identify the unknown','to write an equation relating the quantities that are changing, then differentiate both sides with respect to time using the chain rule'],3),
  ('A ladder 5 m long leans against a wall. The base slides out at 0.5 m/s. When base is 3 m from wall: find how fast the top slides down.',['dy/dt = 0.375 m/s down (x²+y²=25; 2x dx/dt+2y dy/dt=0; y=4; dy/dt = −x/y × dx/dt = −3/4 × 0.5 = −0.375 m/s)','dy/dt = 0.5 m/s','dy/dt = 1 m/s','dy/dt = 0.25 m/s'],0),
  ('Water pours into a conical tank (radius r, height h, r/h = 1/2) at 5 m³/min. Find dh/dt when h = 3 m.',['dh/dt = 5/(9π/4) = 20/(9π) m/min (V=1/3πr²h=πh³/12; dV/dt=πh²/4 × dh/dt; 5=π(9)/4 × dh/dt)','dh/dt = 5 m/min','dh/dt = 5/(3π) m/min','dh/dt = 20/(3π) m/min'],0),
  ('Two cars leave an intersection at right angles: A at 60 km/h north, B at 80 km/h east. Find rate of distance increase after 1 hour.',['100 km/h (z²=x²+y²; 2z dz/dt=2x dx/dt+2y dy/dt; at t=1: x=80, y=60, z=100; dz/dt=(80×80+60×60)/100=100)','140 km/h','50 km/h','72 km/h'],0),
  ('What distinguishes a related rates problem from a standard derivative problem?',['related rates use only one variable','related rates never require the chain rule','related rates only involve geometry','in related rates, multiple quantities change with time, and we use implicit differentiation with respect to time to relate their rates — the chain rule appears on every term'],3)]),
P('Momentum and Impulse','Students analyse linear momentum, impulse, and the impulse-momentum theorem in collision contexts.','https://www.youtube.com/watch?v=nPnPqH-R_Y4',[
  ('Linear momentum is defined as ___.',['p = mv² (kinetic energy, not momentum)','p = ma','p = Ft','p = mv — a vector quantity; its direction is the same as velocity'],3),
  ('The impulse-momentum theorem states ___.',['J = mv only','J = Ft² ','J = ma × t','J = FΔt = Δp — the impulse (force × time) equals the change in momentum; this connects force, time, and motion change'],3),
  ('Conservation of linear momentum applies when ___.',['all forces are equal','friction is absent','the system is in free fall','no net external force acts on the system — the total momentum before equals total momentum after, regardless of what happens internally'],3),
  ('In a perfectly inelastic collision ___.',['both objects pass through each other','kinetic energy is conserved','the objects bounce elastically','the objects stick together — momentum is conserved but kinetic energy is not; some KE converts to heat, sound, or deformation'],3),
  ('A 0.5 kg ball at 10 m/s east collides and sticks to a 1.5 kg ball at rest. Final velocity:',['v = 0.5×10/(0.5+1.5) = 5/2 = 2.5 m/s east','v = 5 m/s','v = 3.3 m/s','v = 10 m/s'],0)]),
]),
day(17,[
E('Comparative Essay: World Literature','Students write a formal comparative essay on two world literature texts, applying university-level analytical standards.','https://www.youtube.com/watch?v=MSYw502dJNY',[
  ('A comparative essay thesis must ___.',['only list the works to be compared','treat works as entirely separate','describe similarities only','make a claim about what the comparison reveals — not just "A and B are similar/different" but "this specific similarity/difference illuminates X about both texts"'],3),
  ('Integrating two texts in a comparative essay is best done by ___.',['discussing one text fully, then the other (block method always)','never mixing the texts','only using plot summaries','using a point-by-point structure for analytical comparison — each paragraph focuses on a specific comparative point, weaving both texts together to support the analytical claim'],3),
  ('When comparing texts from different cultural contexts, a student must ___.',['assume all cultures value the same things','treat one culture as the norm and the other as exotic','only focus on form, not context','acknowledge the cultural and historical specificity of each text — avoid imposing one cultural framework on the other, and use both contexts to enrich the comparison'],3),
  ('The most sophisticated comparative essays ___.',['only describe similarities','only note obvious differences','treat texts independently and in parallel only','find a productive tension — a similarity that conceals difference, or a difference that reveals a shared concern — and use this to generate genuine analytical insight'],3),
  ('Works from different languages in translation present ___.',['no issues since translation is neutral','opportunities to compare style directly','no analytical interest','a specific interpretive challenge — you are reading the translator\'s choices as well as the author\'s, and you should acknowledge this while still engaging meaningfully with the available text'],3)]),
A('Lines and Planes in Three Dimensions','Students write vector and parametric equations of lines in 3D, and scalar and vector equations of planes.','https://www.youtube.com/watch?v=1DfkHs6MFJk',[
  ('The vector equation of a line through point P₀=(x₀,y₀,z₀) with direction d=(a,b,c) is ___.',['r = (x₀+a, y₀+b, z₀+c)','r = d × P₀','r = P₀ + t (the direction is missing)','r = (x₀,y₀,z₀) + t(a,b,c) — a point plus a scalar multiple of the direction vector'],3),
  ('The parametric equations of the same line are ___.',['only x = x₀ + at','x=x₀+at, y=y₀+bt, z=z₀+ct — one equation per dimension, each parameterised by t','x=at, y=bt, z=ct only','x=x₀t, y=y₀t, z=z₀t'],1),
  ('The scalar (Cartesian) equation of a plane with normal n=(A,B,C) through (x₀,y₀,z₀) is ___.',['A+B+C=D','Ax + By + Cz = 0 (only if through origin)','A(x+x₀)+B(y+y₀)+C(z+z₀)=0','A(x−x₀)+B(y−y₀)+C(z−z₀)=0 — or equivalently Ax+By+Cz=D where D=Ax₀+By₀+Cz₀'],3),
  ('Two planes are parallel if and only if ___.',['they have the same x-intercept','their equations differ only by a constant','they are both horizontal','their normal vectors are parallel (one is a scalar multiple of the other)'],3),
  ('A line is perpendicular to a plane when ___.',['the line\'s direction vector is horizontal','the line passes through the origin','the line has slope 1','the line\'s direction vector is parallel to the plane\'s normal vector — the line points in the same direction as the normal'],3)]),
Ca("L'Hôpital's Rule and Indeterminate Forms","Students apply L'Hôpital's Rule to evaluate limits of indeterminate forms (0/0, ∞/∞, ∞−∞, 0·∞).",'https://www.youtube.com/watch?v=_2aCDXyFZC8',[
  ("L'Hôpital's Rule states that if lim f/g = 0/0 or ∞/∞, then ___.",['lim f/g = lim (f+g)','lim f/g = lim (f−g)/(g)','lim f/g = f/g evaluated at the limit point',"lim f(x)/g(x) = lim f'(x)/g'(x) — provided the latter limit exists; differentiate numerator and denominator separately (not the quotient rule)"],3),
  ('Evaluate lim(x→0) sin(x)/x.',["Apply L'Hôpital: lim cos(x)/1 = 1","Apply L'Hôpital: lim −sin(x)/0 = undefined","Apply L'Hôpital: lim cos(x)/cos(x) = 1",'This is not 0/0 form; the limit is 0'],0),
  ('Evaluate lim(x→∞) x/eˣ.',["L'Hôpital (∞/∞): lim 1/eˣ = 0 — exponentials grow faster than polynomials","L'Hôpital: lim 1/xeˣ",'The limit is ∞','The limit is 1'],0),
  ('The form 0·∞ is handled by ___.',['directly multiplying the limits','taking the square root','no special technique needed','rewriting as 0/(1/∞) = 0/0 or ∞/(1/0) = ∞/∞, then applying L\'Hôpital'],3),
  ('Evaluate lim(x→0⁺) x·ln(x).',['0 (rewrite as ln(x)/(1/x) = ∞/∞; L\'Hôpital: (1/x)/(−1/x²) = −x → 0)','∞','1','−1'],0)]),
P('Conservation of Momentum: Collisions in 2D','Students apply conservation of momentum to two-dimensional collisions, resolving vectors into components.','https://www.youtube.com/watch?v=3sGOCBfpmbY',[
  ('For a 2D collision, conservation of momentum applies ___.',['only in the horizontal direction','only for elastic collisions','only if no friction acts','independently to both x and y components simultaneously — momentum is a vector, so each component is separately conserved'],3),
  ('In a 2D elastic collision, both ___ and ___ are conserved.',['mass and velocity','force and time','mass and charge','momentum (vector) and kinetic energy (scalar) — both are conserved simultaneously'],3),
  ('A 2 kg ball moving at 5 m/s east hits a 2 kg ball at rest. After collision ball 1 moves north. By symmetry (equal masses, elastic):',['both balls move east at 2.5 m/s','ball 2 moves east at 5 m/s, ball 1 stops — total KE and momentum conserved (for equal mass elastic head-on collision)... but this is 2D so ball 1 moves north — ball 2 moves east at 5 m/s','both stop','ball 1 bounces back west'],1),
  ('The coefficient of restitution e = ___.',['e = m₁/m₂','e = v₁_initial/v₂_final','e = final momentum/initial momentum','e = relative speed after/relative speed before — 0 for perfectly inelastic, 1 for perfectly elastic'],3),
  ('An explosion (reverse collision) starting from rest: total momentum after = ___.',['equal to the initial kinetic energy','equal to the mass times the speed of the larger piece','equal to the net external force','zero — momentum is conserved; since initial momentum was zero, all fragments\' momenta sum to zero'],3)]),
]),
day(18,[
E('Literary Theory: Reading Through a Lens','Students apply feminist, Marxist, and psychoanalytic critical lenses to literary texts, understanding how theory shapes interpretation.','https://www.youtube.com/watch?v=qGHBcRcPQeI',[
  ('Applying a critical lens to a text means ___.',['finding the one correct interpretation','proving the author had specific intentions','only citing theory in a bibliography','using a theoretical framework to ask specific questions of the text — the lens determines what you notice, what questions you ask, and how you interpret what you find'],3),
  ('Feminist literary criticism examines ___.',['only texts by women','only texts with female protagonists','only gender in isolation from other factors','how texts construct, reinforce, challenge, or subvert gender roles and the social, political, and economic structures that subordinate women — applied to texts by any author'],3),
  ('Marxist literary criticism examines ___.',['only communist literature','only economic statistics in fiction','only class conflict in plot','how texts reflect, reinforce, or critique the economic base and ideological superstructure of society — including class, labour, power, and commodity relations'],3),
  ('Psychoanalytic literary criticism (Freud, Lacan) examines ___.',['only mentally ill characters','only the author\'s biography','only obvious symbolism','the unconscious dimensions of texts — repression, desire, the uncanny, dream logic, the dynamics of id/ego/superego or Lacanian registers (Symbolic, Imaginary, Real)'],3),
  ('The danger of applying theory mechanically is ___.',['the theory becomes irrelevant','theory always improves a reading','no danger exists in using theory','the text is reduced to an illustration of the theory — sophisticated critical work uses theory as a lens to illuminate specific textual details, not as a formula that produces predetermined readings'],3)]),
A('The Cross Product in 3D','Students compute cross products of 3D vectors and apply them to find normals to planes, areas of parallelograms, and equations of planes.','https://www.youtube.com/watch?v=pJzmiywagfY',[
  ('The cross product a × b produces ___.',['a scalar equal to |a||b|cosθ','the component-wise product of two vectors','the dot product of two vectors','a vector perpendicular to both a and b — with magnitude |a||b|sinθ'],3),
  ('For a=(1,0,0) and b=(0,1,0), a × b = ___.',['(0,0,0)','(1,1,0)','(−1,0,0)','(0,0,1) = k — the z-unit vector; confirms right-hand rule'],3),
  ('The area of a parallelogram with sides a and b is ___.',['a · b','|a| × |b|','|a|² + |b|²','|a × b| — the magnitude of the cross product equals the area of the parallelogram spanned by the two vectors'],3),
  ('To find the equation of a plane through three points P₁, P₂, P₃, find ___.',['the midpoint of the three points','only the distance between the points','the sum of all coordinates','vectors P₁P₂ and P₁P₃, then compute their cross product to get the normal n, then write the plane equation using n and any of the three points'],3),
  ('a × b = −(b × a) means ___.',['cross product is commutative','cross product always gives zero','a × b and b × a are equal','cross product is anti-commutative — reversing the order reverses the direction of the resulting vector; the magnitude is the same'],3)]),
Ca('Implicit Differentiation and Inverse Functions','Students apply implicit differentiation to curves defined implicitly, and differentiate inverse trigonometric and general inverse functions.','https://www.youtube.com/watch?v=mSVrqKZDRF4',[
  ('Implicit differentiation is needed when ___.',['the function is a polynomial','the function has no y variable','y is explicitly solved in terms of x','y cannot easily be isolated — you differentiate both sides with respect to x, treating y as a function of x and applying the chain rule whenever y appears'],3),
  ('Differentiate x² + y² = 25 implicitly. dy/dx = ___.',['2x + 2y','−x/y (differentiating: 2x + 2y·dy/dx = 0 → dy/dx = −x/y)','x/y','−y/x'],1),
  ('d/dx[arcsin(x)] = ___.',['cos(arcsin x)','1/cos(x)','−1/√(1−x²)','1/√(1−x²) — derived via implicit differentiation of y = arcsin(x) → sin(y) = x → cos(y)·dy/dx = 1 → dy/dx = 1/cos(y) = 1/√(1−x²)'],3),
  ('d/dx[arctan(x)] = ___.',['sec²(x)','1/(1+x²) — derived: tan(y) = x → sec²(y)·dy/dx = 1 → dy/dx = cos²(y) = 1/(1+x²)','1/cos²(x)','−1/(1+x²)'],1),
  ('The general inverse function derivative rule: if g = f⁻¹, then g\'(x) = ___.',['1/f(x)','f\'(g(x))','g(f\'(x))','1/f\'(g(x)) — the slope of the inverse at x is the reciprocal of the slope of f at the corresponding point'],3)]),
P('Simple Harmonic Motion','Students analyse SHM — period, frequency, amplitude, restoring force — and apply to springs and pendulums.','https://www.youtube.com/watch?v=ZkLXIZoCo-o',[
  ('Simple harmonic motion occurs when ___.',['speed is constant','the restoring force is constant','the amplitude increases over time','the restoring force is proportional to and opposite to the displacement: F = −kx — this produces sinusoidal oscillation'],3),
  ('For a spring-mass system, the period is ___.',['T = 2π√(k/m)','T = 2πm/k','T = 2π√(m/k) — independent of amplitude; depends only on mass and spring constant','T = 2π√k'],2),
  ('For a simple pendulum of length L, T = ___.',['T = 2π√(g/L)','T = 2πL/g','T = 2π√(L/g) — valid for small angles only; independent of mass and (approximately) amplitude','T = 2πg/L'],2),
  ('The total mechanical energy in SHM is ___.',['only kinetic energy','only potential energy','zero at the equilibrium position','constant: E = ½kA² (where A is amplitude) — KE and PE convert to each other, but their sum is always ½kA²'],3),
  ('At maximum displacement (amplitude) in SHM, the velocity is ___ and acceleration is ___.  ',['maximum and maximum','zero and zero','maximum and zero','zero and maximum — at the endpoints, the object momentarily stops (v=0) and the restoring force (and thus acceleration) is greatest'],3)]),
]),
day(19,[
E('Satire: Social Critique Through Comedy','Students analyse satire as a literary mode — examining targets, techniques (irony, parody, exaggeration), and the ethics and limits of satirical writing.','https://www.youtube.com/watch?v=d1bE7LfNqlU',[
  ('Satire differs from simple comedy in that ___.',['satire is never funny','satire is always gentler than direct critique','satire has no political dimension','satire uses humour to expose, criticise, and potentially reform human folly, vice, or social institutions — comedy is an end in itself; satirical comedy is a means to a critical end'],3),
  ('Horatian satire (after Horace) is characterised by ___.',['bitter, savage attack','no use of irony','no political targets','gentle, urbane wit — the satirist laughs with the audience at human folly, gently nudging toward reform rather than condemning'],3),
  ('Juvenalian satire (after Juvenal) is characterised by ___.',['gentle humour','no exaggeration','praise of the satirical target','bitter, contemptuous indignation — the satirist condemns and attacks; the tone is harsh, the critique unsparing'],3),
  ('Jonathan Swift\'s "A Modest Proposal" uses ___.',['straightforward rhetorical argument','direct emotional appeal','pure comedy without bite','sustained irony — the narrator\'s reasonable tone and logical precision make the monstrous proposal (eating Irish babies) more horrifying, not less; the gap between manner and content is the satirical engine'],3),
  ('The ethics of satire involve ___.',['no ethical considerations','only attacking powerful institutions','that any target is fair game','difficult questions about power: satire that "punches down" (mocks the vulnerable) is ethically different from satire that challenges power — and the line is not always clear'],3)]),
A('Equations of Lines and Planes: Intersections and Distances','Students find intersections of lines and planes in 3D and calculate distances from points to lines and planes.','https://www.youtube.com/watch?v=5AWob_z74Ks',[
  ('To find where a line intersects a plane, substitute the ___ into the plane equation.',['normal vector of the plane','coordinates of any point on the plane','parametric equations of the line (in terms of t) and solve for t',  'direction vector of the line'],2),
  ('The distance from point P=(x₁,y₁,z₁) to plane Ax+By+Cz=D is ___.',['|AP₁|','√(A²+B²+C²)','|Ax₁+By₁+Cz₁|','|Ax₁+By₁+Cz₁−D|/√(A²+B²+C²) — a formula analogous to the 2D point-to-line distance'],3),
  ('Two lines in 3D can be ___.',['only parallel or intersecting','always coplanar','always intersecting','parallel, intersecting, or skew (non-parallel, non-intersecting lines that do not lie in the same plane)'],3),
  ('To determine if two lines in 3D intersect, you ___.',['check if their direction vectors are equal','set their position vectors equal and check for consistency','only check if they are parallel','set parametric equations equal in all three coordinates and check if a consistent solution (value of both parameters) exists'],1),
  ('The angle between two planes equals ___.',['the angle between their x-intercepts','90° always','the angle between a line and the plane','the angle between their normal vectors (or its supplement, taking the acute angle)'],3)]),
Ca('Mean Value Theorem and Monotonicity','Students state and apply the Mean Value Theorem, Rolle\'s Theorem, and use them to analyse function behaviour.','https://www.youtube.com/watch?v=mAul5vTAJSA',[
  ('Rolle\'s Theorem states: if f is continuous on [a,b], differentiable on (a,b), and f(a)=f(b), then ___.',['f is constant on [a,b]','f has no local extrema','there exists c in (a,b) such that f\'(c) = 1','there exists c in (a,b) such that f\'(c) = 0 — at least one point where the tangent is horizontal'],3),
  ('The Mean Value Theorem states: if f is continuous on [a,b] and differentiable on (a,b), then ___.',['f achieves its maximum at a or b','f(a) = f(b) always','f\'(x) = 0 for some x','there exists c in (a,b) such that f\'(c) = [f(b)−f(a)]/(b−a) — the instantaneous rate equals the average rate at some interior point'],3),
  ('A geometric interpretation of the MVT: ___.',['the tangent and secant are always perpendicular','the function always has a zero','the function achieves both max and min','the tangent line at some interior point c is parallel to the secant line through (a,f(a)) and (b,f(b))'],3),
  ('If f\'(x) > 0 for all x in (a,b), then the MVT implies ___.',['f is constant','f has no extrema only','f(a) = f(b)','f is strictly increasing on (a,b) — a corollary: a positive derivative implies increasing function'],3),
  ('If f\'(x) = g\'(x) for all x, then ___.',['f(x) = g(x)','f and g are both zero','no relationship can be inferred','f(x) = g(x) + C for some constant C — their derivatives being equal means they can only differ by a constant (a direct corollary of the MVT)'],3)]),
P('Wave Superposition and Interference','Students analyse the superposition of waves — constructive and destructive interference, standing waves, and resonance in strings and air columns.','https://www.youtube.com/watch?v=7cDAYFTXq3E',[
  ('The principle of superposition states ___.',['waves cannot occupy the same space','only two waves can interfere','louder waves always dominate','when two or more waves overlap, the resultant displacement is the algebraic sum of the individual displacements — waves pass through each other unchanged'],3),
  ('Constructive interference occurs when ___.',['waves have different frequencies','waves are perpendicular','the path difference is a half-integer multiple of λ','waves arrive in phase (path difference = nλ for integer n) — crests coincide, producing maximum amplitude'],3),
  ('Destructive interference occurs when ___.',['waves have equal amplitudes only','waves travel in opposite directions','path difference = nλ','waves arrive out of phase (path difference = (n+½)λ) — crest meets trough, producing minimum or zero amplitude'],3),
  ('A standing wave on a string fixed at both ends has nodes at ___.',['antinodes only','only at the centre','random positions along the string','the fixed endpoints — and additional nodes at intervals of λ/2; antinodes are halfway between nodes'],3),
  ('The fundamental frequency of a string of length L, tension T, mass/length μ is ___.',['f₁ = L/(2√(T/μ))','f₁ = 2L√(μ/T)','f₁ = 1/(2L) × √(T/μ) — the lowest resonant frequency; harmonics are multiples of f₁','f₁ = √(TL/μ)'],2)]),
]),
day(20,[
E('The Research Essay: Argument and Evidence at University Level','Students write and revise a fully documented research essay integrating primary texts, secondary criticism, and their own analysis.','https://www.youtube.com/watch?v=vtIzMaLkCaM',[
  ('A literary research essay differs from a personal response in that ___.',['it does not use primary texts','it is longer only','personal response is always better','it situates your argument within the existing critical conversation — using secondary sources to identify what critics have argued and positioning your own reading in relation to that conversation'],3),
  ('Selecting secondary sources for a literary research essay requires ___.',['only using Wikipedia and study guides','any online source about the author','only the most recent criticism','peer-reviewed scholarly articles and books — sources that have been evaluated by experts in the field and make rigorous, evidence-based arguments about the text'],3),
  ('Synthesising sources in a research essay means ___.',['quoting each source in order','only summarising each source separately','never agreeing with any source','weaving together multiple perspectives to illuminate your own argument — sources speak to each other and to your thesis, not just in sequence'],3),
  ('MLA citation requires ___.',['only in-text page numbers for everything','only a bibliography, no in-text citation','only footnotes, no bibliography','in-text citations (author page#) and a corresponding Works Cited page — for online sources, include URL or DOI and access date as applicable'],3),
  ('Academic integrity in a research essay means ___.',['only quoting correctly','only avoiding copy-paste','only citing sources you agree with','citing every source of ideas, information, and argument (whether quoted, paraphrased, or summarised) and presenting your own original synthesis and argument — not reproducing others\' analysis as your own'],3)]),
A('Geometric Vectors: Applications to Physics and Engineering','Students apply 3D vector concepts to displacement, velocity, force equilibrium, and work problems.','https://www.youtube.com/watch?v=ozwodzD5bte',[
  ('Resolving a force into components in 3D uses ___.',['trigonometry only','the dot product alone','only the magnitude of the force','F = Fₓi + F_yj + F_zk — decomposing the force vector into x, y, z components using direction cosines or given angles'],3),
  ('For three forces to be in equilibrium, their vector sum must be ___.',['equal to the largest force','non-zero','pointing downward','zero: F₁ + F₂ + F₃ = 0 — equilibrium means no net force, so all components sum to zero'],3),
  ('The scalar projection of a onto b is ___.',['|a||b|','a·b (the full dot product)','a×b','a·b̂ = a·b/|b| — the signed magnitude of a\'s component in the direction of b'],3),
  ('The vector projection of a onto b is ___.',['a·b/|b|²','(a·b̂)b̂ = (a·b/|b|²)b — the component of a in the direction of b, as a vector','|a|cosθ','a × b'],1),
  ('Work done by a force F over displacement d is ___.',['|F||d|','F × d (cross product — this gives a vector, not work)','F + d','W = F · d = |F||d|cosθ — only the component of force in the direction of displacement does work'],3)]),
Ca('Integration by Substitution','Students apply the substitution rule (u-substitution) to evaluate indefinite and definite integrals of composite functions.','https://www.youtube.com/watch?v=-9M9P7xNDH4',[
  ('The substitution rule reverses ___.',['the product rule','the quotient rule','the power rule','the chain rule — if the integrand is of the form f(g(x))g\'(x), let u = g(x), du = g\'(x)dx, and integrate f(u)du'],3),
  ('∫2x(x²+1)⁵ dx: let u = x²+1, du = 2x dx. The integral becomes ___.',['∫u⁵ du = u⁶/6 + C = (x²+1)⁶/6 + C','∫2xu⁵ du','∫u⁵ 2x dx','∫(x²+1)⁵ du'],0),
  ('∫sin(3x) dx: let u = 3x, du = 3 dx. The integral = ___.',['−cos(3x)/3 + C (= ∫sin(u) du/3 = −cos(u)/3 + C)','−cos(3x) + C','cos(3x)/3 + C','−3cos(3x) + C'],0),
  ('For a definite integral with substitution, you must ___.',['always change back to x before evaluating','never use substitution in definite integrals','keep the same limits of integration','either change the limits of integration to u-values, or substitute back to x before evaluating at original limits'],3),
  ('∫[0 to 1] x·e^(x²) dx: let u = x², du = 2x dx. Limits: u(0)=0, u(1)=1. Result:',['∫[0 to 1] e^u du/2 = [e^u/2]₀¹ = (e−1)/2','e/2','(e−1)','e−1'],0)]),
P('Optics: Reflection and Refraction','Students apply the law of reflection and Snell\'s Law to mirrors, lenses, and fibre optics; analyse total internal reflection.','https://www.youtube.com/watch?v=_dBmNF_XBTU',[
  ('The law of reflection states ___.',['the angle of incidence and refraction are equal','light always reflects at 45°','reflected rays are always horizontal','the angle of incidence equals the angle of reflection, both measured from the normal to the surface'],3),
  ('Snell\'s Law of refraction is ___.',['n₁cosθ₁ = n₂cosθ₂','n₁θ₁ = n₂θ₂','n₁/sinθ₁ = n₂/sinθ₂','n₁sinθ₁ = n₂sinθ₂ — where n is the index of refraction; light bends toward the normal when entering a denser medium'],3),
  ('Total internal reflection occurs when ___.',['any light passes from air to glass','n₁ < n₂','the angle of refraction reaches 90° (critical angle sinθ_c = n₂/n₁) and beyond — light is entirely reflected back into the denser medium','light passes from glass to air at any angle'],2),
  ('A converging (convex) lens ___.',['creates only virtual images','only works for objects at infinity','diverges parallel rays','converges parallel rays to a focal point; the thin lens equation 1/f = 1/dₒ + 1/dᵢ relates focal length, object distance, and image distance'],3),
  ('Optical fibre works by ___.',['total reflection from metal coatings','only working in vacuum','absorption of light','total internal reflection — light is repeatedly totally internally reflected along the fibre, allowing lossless transmission of data over long distances'],3)]),
]),
day(21,[
E('The Novel as Social Document: Realism and Its Discontents','Students examine realist novels and their sociological dimension — how fiction can document social reality while remaining art.','https://www.youtube.com/watch?v=qGHBcRcPQeI',[
  ('Nineteenth-century realism in the novel aimed to ___.',['create pure fantasy worlds','avoid representing working-class life','focus only on aristocratic characters','represent society as it actually is — with documentary precision, attention to social class, economic conditions, and the quotidian lives of ordinary people, not just heroes and aristocrats'],3),
  ('The sociological reading of a novel examines ___.',['only the author\'s biography','only plot and character','only style and form','how the novel reflects and critiques the social structures, ideologies, and class relations of its historical moment — what it can tell us about the world that produced it'],3),
  ('A "condition of England" novel (like those by Dickens or Gaskell) characteristically ___.',['romanticises the past','avoids contemporary social problems','only follows middle-class characters','dramatises a contemporary social problem — poverty, industrialisation, factory conditions, child labour — as a way of drawing public attention to injustice'],3),
  ('The danger of reading a novel only as a social document is ___.',['it always misidentifies the social context','it makes the novel more interesting','it is the correct approach','reducing the novel to a source of sociological information while ignoring its formal complexity, aesthetic achievements, and the ways form and content are inseparable'],3),
  ('Contemporary fiction as social document includes ___.',['no claim to documentary accuracy','only "issues novels" without literary merit','only literary fiction set in the past','novels that address climate change, algorithmic culture, economic precarity, migration, and racial justice — fiction as a mode of social imagination that can reveal what statistics and journalism cannot'],3)]),
A('Vectors: Applications to Navigation and Problem Solving','Students apply 3D vector techniques to navigation, structural problems, and multi-step applied problems.','https://www.youtube.com/watch?v=ml4NSzCQobk',[
  ('A boat travels at 20 km/h in a river with current 5 km/h perpendicular. Its actual speed is ___.',['25 km/h','15 km/h','10 km/h','√(20² + 5²) = √425 ≈ 20.6 km/h — vector addition of boat velocity and current velocity'],3),
  ('A plane heads north at 800 km/h; wind blows east at 100 km/h. The resultant speed is ___.',['900 km/h','√(800² + 100²) = √650000 ≈ 806 km/h','700 km/h','800 + 100 = 900 km/h (this adds speeds, not vectors)'],1),
  ('Forces of 30 N north and 40 N east act on an object. The resultant force is ___.',['70 N','50 N at arctan(40/30) N of E — √(30²+40²) = 50 N; direction = arctan(E/N) from north','10 N','50 N due northeast'],1),
  ('To find the angle between two 3D vectors a = (1,2,2) and b = (2,1,−2):',['cosθ = (2+2−4)/(3×3) = 0/9 = 0, so θ = 90° (perpendicular)','θ = 45°','θ = 60°','θ = 30°'],0),
  ('A force of (3, 4, 0) N acts over displacement (1, 1, 5) m. Work done = ___.',['(3+4+0)(1+1+5) = 49 J','√(3²+4²+0²) J','3·1 + 4·1 + 0·5 = 7 J — dot product gives scalar work','3+4+1+1+5 = 14 J'],2)]),
Ca('Integration by Parts','Students apply the integration by parts formula to products of functions, including repeated application and tabular method.','https://www.youtube.com/watch?v=2I-_SV8cwsw',[
  ('Integration by parts: ∫u dv = ___.',['uv − ∫u dv','u dv − v du','∫u dx + ∫dv','uv − ∫v du — derived from the product rule for differentiation'],3),
  ('To integrate ∫x·eˣ dx, choose u = x, dv = eˣ dx. Then du = dx, v = eˣ. Result:',['x·eˣ − eˣ + C = eˣ(x−1) + C','x·eˣ + eˣ + C','x·eˣ + C','eˣ(x+1) + C'],0),
  ('For ∫ln(x) dx, choose u = ln(x), dv = dx. Then du = 1/x dx, v = x. Result:',['x·ln(x) − x + C (= x ln(x) − ∫x · 1/x dx = x ln(x) − ∫1 dx)','ln(x)/x + C','x/ln(x) + C','ln(x) + C'],0),
  ('∫x²·sin(x) dx requires ___.',['one application of parts','u-substitution only','no special technique','two applications of integration by parts (or the tabular method) — the power of x reduces each time until only sin(x) remains'],3),
  ('The mnemonic LIATE suggests choosing u as ___.',['the function that differentiates to zero','the last function in the product','the exponential always','the function that comes first in: Logarithm, Inverse trig, Algebraic, Trig, Exponential — generally the "earlier" choice makes du simpler'],3)]),
P('The Photoelectric Effect and Wave-Particle Duality','Students examine the photoelectric effect, photon model of light, and the evidence for wave-particle duality.','https://www.youtube.com/watch?v=kcSYV8bZhjc',[
  ('The photoelectric effect is the emission of electrons from a metal surface when ___.',['a current is applied to the metal','the metal is heated sufficiently','the metal is cooled to absolute zero','light of sufficient frequency illuminates the metal — demonstrating that light transfers energy in discrete quanta (photons)'],3),
  ('Classical wave theory failed to explain the photoelectric effect because ___.',['it predicted no electrons would be emitted','it correctly predicted everything','it predicted only red light would work','it predicted that any frequency of light would eject electrons given enough intensity — but experiment showed frequency, not intensity, determines if electrons are ejected'],3),
  ('Einstein\'s explanation of the photoelectric effect (1905) proposed ___.',['light is purely a particle with no wave properties','the metal surface is the key factor','the current from the battery ejects electrons','light energy comes in discrete packets (photons) of energy E = hf — below the threshold frequency, no single photon has enough energy to eject an electron regardless of intensity'],3),
  ('De Broglie\'s hypothesis proposed that matter also has wave properties: λ = ___.',['h/(mv) = h/p — the de Broglie wavelength of a particle with momentum p; confirmed experimentally by electron diffraction','h/f','h × mv','mv/h'],0),
  ('Wave-particle duality means ___.',['only light can be a wave','only electrons can be particles','quantum objects are neither waves nor particles','quantum objects exhibit wave behaviour (interference, diffraction) in some experiments and particle behaviour (discrete energy, localised detection) in others — the nature of the observation determines which aspect is revealed'],3)]),
]),
day(22,[
E('Short Fiction Masterworks: Structure, Voice, and Compression','Students study canonical short stories, examining how compressed form demands particular mastery of voice, structure, epiphany, and economy of language.','https://www.youtube.com/watch?v=dtRCMONW8bQ',[
  ('The short story differs from the novel in that ___.',['it is always easier to write','it has no character development','it can never achieve the depth of a novel','it demands absolute economy — every word must work; there is no space for subplots, extended development, or leisurely description — the form itself creates pressure'],3),
  ('The "epiphany" in Joyce\'s short fiction (from "Dubliners") refers to ___.',['a religious experience only','a surprise plot twist','the story\'s happy ending','a moment of sudden insight or revelation — often quiet and internal — when a character perceives something essential about themselves or their situation'],3),
  ('Point of view in a short story is especially important because ___.',['first person is always best','third person is always better','point of view has no relation to meaning','the limited space means the narrative voice is almost everything — the angle from which the story is told determines what is knowable, what is visible, and what the reader can understand'],3),
  ('Chekhov\'s famous "gun" principle states ___.',['every story needs violence','guns are important in Russian fiction','stories should be realistic only','if a gun is shown in the first act, it must be fired by the third — dramatic economy requires that every element introduced must be relevant; details are significant precisely because they are selected'],3),
  ('Compression in short fiction achieves ___.',['nothing that a longer story could not do better','less than the novel in all respects','only brevity without depth','a different kind of intensity — the reader carries more weight; implication, suggestion, and what is left unsaid become as important as what is stated, creating resonant ambiguity'],3)]),
A('Counting Principles and Permutations','Students apply the fundamental counting principle, permutations (with and without repetition), and circular permutations to combinatorics problems.','https://www.youtube.com/watch?v=XqQTXW7XfYA',[
  ('The fundamental counting principle: if event A can occur in m ways and event B in n ways, then A then B can occur in ___.',['m + n ways (addition applies when events are mutually exclusive alternatives)','m × n ways — the multiplication principle: each choice for A pairs with each choice for B','m! ways','m − n ways'],1),
  ('The number of permutations of n distinct objects taken r at a time is ___.',['n!/(n−r)!... = nPr','n!/r!','nCr = n!/(r!(n−r)!)','n!'],0),
  ('How many 4-digit PINs have no repeated digits?',['10 × 9 × 8 × 7 = 5040 (=10P4)','10⁴ = 10000','10 × 9 × 8 = 720','4! = 24'],0),
  ('In how many ways can 5 people sit at a round table?',['5! = 120','(5−1)! = 4! = 24 — circular permutations fix one position to account for rotational equivalence','5!/5 = 24','5'],1),
  ('If 3 of 8 books must always be together, the number of arrangements on a shelf is ___.',['8! arrangements','3! × 6! (treat the 3 as a block: 6! arrangements of 6 items × 3! internal arrangements of the block)','6! only','3! × 8!'],1)]),
Ca('Volumes of Solids of Revolution: Advanced','Students compute volumes using disc/washer and shell methods, and apply the methods to multi-region problems.','https://www.youtube.com/watch?v=EFkEnCYdVAU',[
  ('The washer method for a solid between y=f(x) and y=g(x) (f≥g) rotated about x-axis gives ___.',['V = π∫[f(x)−g(x)]² dx','V = π∫[f(x)+g(x)] dx','V = 2π∫x[f(x)−g(x)] dx','V = π∫{[f(x)]² − [g(x)]²} dx — subtract the inner circle (g) from the outer circle (f)'],3),
  ('Find the volume when the region between y=x and y=x² (0≤x≤1) is rotated about the x-axis.',['V = π∫₀¹(x² − x⁴)dx = π[x³/3 − x⁵/5]₀¹ = π(1/3−1/5) = 2π/15','V = π/6','V = π/3','V = π/15'],0),
  ('The shell method integrates ___ when rotating about the y-axis.',['horizontal strips of width dy','the radius squared','circular discs perpendicular to y','vertical shells: V = 2π∫x·f(x) dx from a to b — shell radius = x, shell height = f(x)'],3),
  ('Choosing between disc/washer and shell methods: prefer shells when ___.',['always preferring shells','the function has no closed form','only for linear functions','solving for x in terms of y would be difficult — shells allow integration in x even when rotating about y'],3),
  ('The volume of a sphere of radius r by discs: V = π∫[-r to r](r²−x²) dx = ___.',['4πr²/3','πr³','4πr³/3 ✓ — [π(r²x − x³/3)] from −r to r = π(r³−r³/3) − π(−r³+r³/3) = 4πr³/3','2πr³'],2)]),
P('Atomic Structure and Quantum Numbers','Students examine the Bohr model, quantum mechanical model, and electron configurations using quantum numbers.','https://www.youtube.com/watch?v=Ewf6RuLlSvc',[
  ('The Bohr model of the hydrogen atom correctly predicted ___.',['the spectra of all elements','the 3D shape of orbitals','the Zeeman effect','the discrete emission spectrum of hydrogen — electrons occupy fixed energy levels, and photon emission corresponds to electron transitions between levels: ΔE = hf'],3),
  ('The principal quantum number n determines ___.',['the spin of the electron','the magnetic orientation of the orbital','the shape of the orbital','the energy level and size of the orbital — n = 1, 2, 3, ... with higher n meaning higher energy and larger radius'],3),
  ('The four quantum numbers (n, l, mₗ, mₛ) together specify ___.',['only the energy of the electron','only the orbital shape','only the spin orientation','a unique quantum state for each electron in an atom — the Pauli Exclusion Principle states no two electrons can share the same set of four quantum numbers'],3),
  ('The Heisenberg Uncertainty Principle states ___.',['measurement has no effect on quantum systems','electrons move in defined circular orbits','quantum mechanics is only approximate','Δx × Δp ≥ ℏ/2 — the more precisely we know a particle\'s position, the less precisely we can know its momentum, and vice versa; this is a fundamental feature of nature, not a limitation of our instruments'],3),
  ('Electron configuration of carbon (Z=6) following Aufbau principle is ___.',['1s¹2s²2p³','1s²2s²2p² — 2 electrons in 1s, 2 in 2s, 2 in 2p (Hund\'s rule: they enter different 2p orbitals with parallel spins)','1s²2s¹2p³','1s²2p⁴'],1)]),
]),
day(23,[
E('Documentary and Non-Fiction: Truth, Form, and Ethics','Students examine documentary film and literary non-fiction (creative non-fiction, journalism) — exploring how non-fiction makes arguments and ethical obligations to truth.','https://www.youtube.com/watch?v=2HqT7QbVCnc',[
  ('Documentary film differs from fiction film in that ___.',['documentary has no narrative structure','documentary is always objective','documentary uses no cinematic technique','documentary claims a relationship to actual events and people — but this claim does not mean documentary is neutral or unmediated; every documentary makes choices that shape the audience\'s understanding'],3),
  ('Rhetorical strategies in documentary include ___.',['no rhetorical strategies','only factual presentation','only verbal argument','interview selection, ordering of footage, music and sound, narration, juxtaposition — all of which guide the viewer toward a particular interpretation while appearing merely to present facts'],3),
  ('Creative non-fiction (e.g., literary journalism, memoir, personal essay) ___.',['has no responsibility to truth','is always more subjective than journalism','should avoid literary techniques','uses the techniques of fiction (scene, character, voice, imagery, structure) in the service of factual content — but maintains an ethical obligation to truth that fiction does not'],3),
  ('The ethics of documentary representation include ___.',['no ethical obligations since subjects consented','only legal considerations','no issue if filming in public spaces','obligations around consent, fair representation, potential harm to subjects, and the power differential between filmmaker and subject — particularly when filming vulnerable communities'],3),
  ('Analysing a documentary as a text means ___.',['accepting it as a neutral truth document','only checking factual accuracy','only watching without analysis','examining its rhetorical strategies, cinematic choices, ideological assumptions, and the relationship between its claims and the evidence it presents — treating it as an argument, not just a record'],3)]),
A('Combinations and the Binomial Theorem','Students calculate combinations, apply Pascal\'s triangle, and expand binomials using the Binomial Theorem.','https://www.youtube.com/watch?v=Eu2oYKiPxu0',[
  ('The number of combinations of n objects taken r at a time is ___.',['n!/r!','n!/(n−r)!','n!','C(n,r) = n!/(r!(n−r)!) — order does not matter in combinations; fewer than permutations by a factor of r!'],3),
  ('How many ways can a committee of 3 be chosen from 10 people?',['10!/3! = 604800','10P3 = 720','C(10,3) = 10!/(3!7!) = 120','10 × 3 = 30'],2),
  ('The Binomial Theorem states (a+b)ⁿ = ___.',['aⁿ + bⁿ only','n·aⁿ⁻¹b + aⁿ','∑ C(n,k) aᵏbⁿ⁻ᵏ','∑[k=0 to n] C(n,k) aⁿ⁻ᵏ bᵏ — a sum of n+1 terms with binomial coefficients from Pascal\'s triangle'],3),
  ('The term with b³ in (2x + 3)⁵ is ___.',['C(5,3)(2x)²(3)³ = 10 × 4x² × 27 = 1080x²','C(5,2)(2x)³(3)²','C(5,3)(2x)³(3)²','C(5,3)(2x)²(3)³ = 1080x²'],0),
  ('Pascal\'s triangle has the property that ___.',['C(n,r) = C(n,r−1) + C(n,r+1)','C(n,r) = C(n−1,r)','each entry is the sum of all entries above','C(n,r) = C(n−1,r−1) + C(n−1,r) — each entry is the sum of the two entries above it'],3)]),
Ca('Numerical Integration: Riemann Sums and the Trapezoid Rule','Students approximate definite integrals using Riemann sums, the Trapezoid Rule, and Simpson\'s Rule.','https://www.youtube.com/watch?v=YTKQswb60Pw',[
  ('A Riemann sum approximates a definite integral by ___.',['using the antiderivative','differentiating at sample points','only using the left endpoint always','summing the areas of rectangles; left, right, and midpoint Riemann sums use different sample points within each subinterval'],3),
  ('The Trapezoid Rule approximates ∫f dx using ___.',['only left-endpoint rectangles','the average of f(a) and f(b) only','only the area of one trapezoid','trapezoids instead of rectangles: T = (h/2)[f(x₀)+2f(x₁)+...+2f(xₙ₋₁)+f(xₙ)] where h = (b−a)/n'],3),
  ('Simpson\'s Rule (n even) is ___.',['only the midpoint rule','the same as the trapezoid rule','only used for linear functions','(h/3)[f(x₀)+4f(x₁)+2f(x₂)+4f(x₃)+...+4f(xₙ₋₁)+f(xₙ)] — alternating coefficients 4 and 2; generally more accurate than trapezoid'],3),
  ('Numerical integration is necessary when ___.',['the function is always integrable','only for physics problems','you cannot use the FTC','the antiderivative cannot be expressed in closed form — many real-world functions (e.g., e^(−x²), √(1+x³)) have no elementary antiderivative'],3),
  ('As the number of subintervals n → ∞, all Riemann sum approximations ___.',['diverge','approach different limits','remain the same','converge to the exact value of the definite integral — this is precisely the definition of the Riemann integral'],3)]),
P('Nuclear Reactions: Fission, Fusion, and Radioactive Decay','Students analyse nuclear reactions, calculate binding energy per nucleon, and apply decay equations.','https://www.youtube.com/watch?v=nRmBsxBpTjs',[
  ('Radioactive decay follows ___.',['a linear decrease in activity','a quadratic decay law','constant activity indefinitely','an exponential law: N(t) = N₀e^(−λt), where λ is the decay constant; after each half-life, half the remaining nuclei have decayed'],3),
  ('Half-life T½ is related to decay constant λ by ___.',['T½ = λ','T½ = 1/λ','T½ = e^λ','T½ = ln2/λ = 0.693/λ — solving N₀/2 = N₀e^(−λT½)'],3),
  ('Binding energy per nucleon peaks at ___.',['uranium-238 (heaviest stable nucleus)','hydrogen-1 (lightest)','carbon-12 (organic life basis)','iron-56 — nuclei lighter than iron release energy by fusion; nuclei heavier than iron release energy by fission; this is why both processes release energy'],3),
  ('Carbon-14 dating works because ___.',['C-14 is created only in labs','C-14 is stable indefinitely','C-14 is the most common carbon isotope','C-14 is produced at a constant rate in the atmosphere by cosmic rays and incorporated into living organisms; after death, C-14 decays with T½ ≈ 5730 years, allowing age determination'],3),
  ('The Q-value of a nuclear reaction is ___.',['the quantity of material used','the quality of the nuclear fuel','the charge of the nucleus','the energy released: Q = (mass of reactants − mass of products) × c²; positive Q means energy is released (exothermic)'],3)]),
]),
day(24,[
E('Contemporary Drama: Stagecraft and Text','Students examine a contemporary play, analysing the relationship between the written text and its realisation in performance.','https://www.youtube.com/watch?v=W3MJj5AjAMc',[
  ('A play script is ___.',['the complete work of art in itself','less important than the director\'s vision','always the same in any production','a blueprint for performance — the text is indeterminate until realised; staging choices, casting, design, and acting all complete the work the playwright began'],3),
  ('Stage directions in a contemporary play ___.',['are always followed literally','are always ignored by directors','tell audiences what to think','may be poetic, ambiguous, or minimal — some playwrights (Beckett, Pinter) make stage directions part of the artistic text; others leave maximum freedom to the director and designer'],3),
  ('Theatre\'s relationship to contemporary politics includes ___.',['avoidance of political content','only historical political subjects','documentary theatre only','verbatim theatre (using real testimony), protest theatre, community-based theatre, and mainstream drama that addresses current social and political questions'],3),
  ('Analysing a contemporary play without seeing it in production requires ___.',['imagining a specific production as if it were the only one','admitting analysis is impossible without performance','only reading the dialogue as prose','imaginative performance reading — envisioning how the text could be staged, what choices are available, and how different productions might emphasise different aspects of the text'],3),
  ('The most important question when analysing a scene in a contemporary play is ___.',['what happens in the plot','what time period is the play set in','how many characters appear','what does each character want in this scene, and what theatrical means are used to create or frustrate that desire — dramatic action is always about want and obstacle'],3)]),
A('Probability Distributions: Binomial and Geometric','Students work with discrete probability distributions — binomial and geometric — applying formulas and interpreting results.','https://www.youtube.com/watch?v=J8jNoF-K8Z8',[
  ('The binomial distribution applies when ___.',['trials have more than two outcomes','probability changes each trial','only one trial is performed','there are n independent identical trials, each with two outcomes (success/failure), and probability of success p is constant — counting the number of successes X'],3),
  ('P(X=k) for a binomial distribution is ___.',['C(n,k) × pᵏ × (1−p)^n','p^k × (1-p)^(n-k)','C(n,k) × pᵏ × (1−p)^(n−k) — choosing which k trials succeed times the probability of that pattern','n × p × k'],2),
  ('For a binomial random variable X ~ B(n,p), E(X) = ___.',['np(1−p)','n/p','p/n','np — the expected number of successes in n trials; variance is np(1−p)'],3),
  ('The geometric distribution models ___.',['the number of successes in n trials','only continuous random variables','the probability of exactly one success','the number of trials until the first success: P(X=k) = (1−p)^(k−1) × p; E(X) = 1/p'],3),
  ('A quality control check has 5% defective rate. Find P(exactly 2 defective in 20 items).',['C(20,2)(0.05)²(0.95)¹⁸ ≈ 0.189','(0.05)² × 20','C(20,2)(0.05)²','2/20 = 0.10'],0)]),
Ca('Differential Equations: Growth, Decay, and Newton\'s Law','Students solve separable ODEs applied to exponential growth, radioactive decay, and Newton\'s Law of Cooling.','https://www.youtube.com/watch?v=H0VEL9TFjqw',[
  ('The general solution of dP/dt = kP is ___.',['P(t) = P₀ + kt','P(t) = ke^(P₀t)','P(t) = P₀kt','P(t) = P₀e^(kt) — separate, integrate both sides: ∫dP/P = ∫k dt → ln P = kt + C → P = Ae^(kt)'],3),
  ('A culture of 1000 bacteria doubles in 3 hours. After 9 hours:',['8000 (doubles 3 times: ×2×2×2 = 8; 1000 × 8 = 8000)','6000','3000','2000'],0),
  ('Radioactive decay: dN/dt = −λN. Given N₀ = 400 and T½ = 5 years, after 10 years N = ___.',['400 × (1/2)² = 100 (two half-lives)','200','400 − 2λ','400e^(−10)'],0),
  ('Newton\'s Law of Cooling: T(t) = T_env + (T₀ − T_env)e^(−kt). A 90°C coffee in a 20°C room cools to 70°C in 10 min. After 30 more minutes T ≈ ___.',['solve: 70=20+(90−20)e^(−10k) → e^(−10k)=5/7; T(40)=20+70e^(−40k)=20+70(5/7)⁴ ≈ 20+70×0.26=38°C','50°C','60°C','45°C'],0),
  ('A differential equation is separable if ___.',['it involves only one variable','its solution is always exponential','it has constant coefficients','it can be written as dy/g(y) = f(x) dx — the variables can be completely separated to opposite sides before integrating'],3)]),
P('Modern Physics: Quantum Mechanics and the Standard Model','Students examine the probabilistic nature of quantum mechanics, wave functions, and an overview of the Standard Model.','https://www.youtube.com/watch?v=p7bzE1E5PMY',[
  ('The wave function ψ(x,t) in quantum mechanics gives ___.',['the exact position of the particle','the energy of the particle directly','the actual path of the particle','the probability amplitude — |ψ|² gives the probability density of finding the particle at position x at time t'],3),
  ('The Schrödinger equation is ___.',['a statement of conservation of energy','only applicable to classical waves','only for relativistic particles','the fundamental equation of quantum mechanics — describing how the wave function evolves in time; solving it gives the allowed quantum states and their energies'],3),
  ('Quantum tunnelling allows ___.',['particles to exceed the speed of light','energy conservation to be violated','only photons to pass through barriers','particles to pass through potential barriers that classical mechanics would prohibit — explained by the non-zero probability amplitude on the far side of the barrier; crucial in nuclear fusion and semiconductor devices'],3),
  ('The Standard Model classifies matter as composed of ___.',['atoms and molecules only','protons and neutrons only','photons and electrons only','quarks (making up protons, neutrons) and leptons (electrons, neutrinos) — interacting via bosons: photons (EM), W/Z bosons (weak), gluons (strong)'],3),
  ('The unresolved problems in the Standard Model include ___.',['no unresolved problems','only cosmological questions','only mathematical issues','no quantum description of gravity, no explanation of dark matter or dark energy, and no explanation of the matter-antimatter asymmetry in the universe'],3)]),
]),
day(25,[
E('Research Essay Workshop: Drafting and Peer Review','Students workshop research essay drafts in a peer-review setting, applying structured feedback protocols and revising for argument, evidence, and style.','https://www.youtube.com/watch?v=8eB7SSNC5ys',[
  ('Peer review is most valuable when ___.',['reviewers focus only on grammar','reviewers are lenient to encourage the writer','reviewers only praise the essay','reviewers respond as genuine readers — identifying where the argument is unclear, where evidence is unconvincing, where the analysis is superficial — providing the response a real academic reader would give'],3),
  ('The most important question to ask about a research essay draft is ___.',['is the Works Cited formatted correctly?','is the essay long enough?','are there enough quotations?','does each paragraph contribute to a single unified argument, and does the evidence actually support the specific claim made in each paragraph?'],3),
  ('Revising an essay is different from editing in that ___.',['editing is more important','they are the same process','revising is only fixing grammar','revising involves reconsidering the argument, structure, and evidence — making major changes to content and organisation; editing addresses sentence-level clarity and correctness'],3),
  ('When evidence does not support your claim, the correct response is ___.',['delete the evidence','misrepresent the evidence to fit','ignore the problem','revise either the claim to match the evidence, or find better evidence for the existing claim — intellectual honesty requires alignment between claim and evidence'],3),
  ('Academic voice in a research essay is characterised by ___.',['only long, complex sentences','avoiding the first person always','only formal vocabulary','precision, economy, and analytical clarity — making specific, defensible claims; avoiding vague assertions; using evidence not to decorate but to prove; maintaining a consistently critical and engaged voice'],3)]),
A('Probability: Conditional Probability and Independence','Students apply conditional probability, Bayes\' Theorem, and independence to complex probability problems.','https://www.youtube.com/watch?v=H02B3aMNKzE',[
  ('Conditional probability P(A|B) = ___.',['P(A) + P(B)','P(A) × P(B)','P(A)/P(B)','P(A∩B)/P(B) — the probability of A given that B has occurred; restricts the sample space to outcomes in B'],3),
  ('Events A and B are independent if and only if ___.',['P(A) = P(B)','P(A∩B) = 0','P(A) + P(B) = 1','P(A|B) = P(A), equivalently P(A∩B) = P(A)P(B) — knowing B occurred gives no information about A'],3),
  ('Bayes\' Theorem: P(A|B) = ___.',['P(B|A)/P(A)','P(A|B) = P(A)P(B)','P(B|A)×P(A)×P(B)','P(B|A)×P(A) / P(B) — allows updating probability of A given new evidence B'],3),
  ('A medical test has 99% sensitivity (P(+|disease)) and 95% specificity (P(−|no disease)). Prevalence = 1%. P(disease | positive test) ≈ ___.',['≈ 16.7% (Bayes: P(D|+) = 0.99×0.01/(0.99×0.01+0.05×0.99) ≈ 0.0099/0.059 ≈ 0.167)','≈ 99%','≈ 50%','≈ 5%'],0),
  ('The multiplication rule for conditional probability: P(A∩B) = ___.',['P(A) + P(B) − P(A∪B)','P(A)×P(B) always','P(A|B) − P(B)','P(A)×P(B|A) = P(B)×P(A|B) — either form works; the second factor is the conditional probability of the second event given the first'],3)]),
Ca('Arc Length and Surface Area','Students calculate arc lengths of curves and surface areas of solids of revolution using integration.','https://www.youtube.com/watch?v=PwmqebSqc_s',[
  ('The arc length of y = f(x) from a to b is ___.',['∫[a to b]√(1+[f(x)]²) dx','∫[a to b]f(x) dx','∫[a to b](1+f(x)) dx','∫[a to b]√(1+[f\'(x)]²) dx — derived from approximating the curve by infinitesimal line segments ds = √(dx²+dy²)'],3),
  ('Find the arc length of y = x³/² from x=0 to x=4.',['∫[0 to 4]√(1+(3x^(1/2)/2)²) dx = ∫√(1+9x/4) dx — solved by substitution; ≈ 9.07','∫√(1+x³) dx','4³/² = 8','4 × √(1+9) = 4√10'],0),
  ('Surface area of y=f(x) rotated about x-axis from a to b is ___.',['2π∫f(x) dx','π∫[f(x)]² dx (this is volume by discs)','π∫f(x)√(1+[f\'(x)]²) dx','2π∫f(x)√(1+[f\'(x)]²) dx — sum of infinitesimal bands of circumference 2πf(x) and slant height ds'],3),
  ('These formulas require that f(x) is ___.',['only integrable','only continuous','always positive','continuously differentiable (f\' continuous) on [a,b] — so that ds = √(1+[f\'(x)]²)dx is well-defined'],3),
  ('For a circle of radius r (parametrically x=rcosθ, y=rsinθ), the arc length (circumference) formula gives ___.',['2πr² (this is area)','πr²','πr','2πr — ∫[0 to 2π]√((−rsinθ)²+(rcosθ)²) dθ = ∫[0 to 2π]r dθ = 2πr ✓'],3)]),
P('Medical and Applied Physics','Students see how physics principles apply to medicine — X-rays, MRI, PET scans, ultrasound, and radiation therapy.','https://www.youtube.com/watch?v=cMJpFjmJZ9s',[
  ('X-rays penetrate soft tissue but are absorbed by bone because ___.',['X-rays are repelled by calcium','bone is harder than soft tissue','bone is denser and contains calcium which absorbs X-rays more strongly — the differential absorption creates the radiographic image','X-rays cannot travel through any material'],2),
  ('MRI (Magnetic Resonance Imaging) uses ___.',['X-rays with computer processing','radioactive tracers','ultrasound at very high frequencies','the magnetic properties of hydrogen nuclei (protons) — a strong magnetic field aligns them, then radiofrequency pulses disturb the alignment; detecting the return to equilibrium creates images of soft tissue'],3),
  ('PET (Positron Emission Tomography) works by ___.',['using external X-ray sources','using a magnetic field to image organs','measuring sound waves inside the body','detecting gamma rays from positron-electron annihilation — a positron-emitting tracer is injected, and annihilation events (producing paired gamma rays) reveal metabolic activity'],3),
  ('Ultrasound imaging uses ___.',['gamma radiation','visible light','infrared radiation','high-frequency sound waves (1–20 MHz) — reflected differently by tissues of different density; safe for foetal imaging because it uses no ionising radiation'],3),
  ('Radiation therapy targets cancer because ___.',['only cancer cells absorb radiation','radiation has no side effects','normal cells cannot be harmed by radiation','ionising radiation damages DNA, killing rapidly dividing cells (cancer cells divide faster than most normal cells) — but normal tissue damage is a significant side effect requiring careful dosing and targeting'],3)]),
]),
day(26,[
E('Oral Communication: Seminar and Academic Discussion','Students prepare for and participate in a formal Socratic seminar, developing skills in academic discussion, active listening, and building on others\' ideas.','https://www.youtube.com/watch?v=bPkHcTk55Vc',[
  ('A Socratic seminar is characterised by ___.',['the teacher asking all the questions','competitive debate with winners','only one student speaking at a time','open-ended discussion in which students build on each other\'s ideas, ask genuine questions, and arrive at deeper understanding through collaborative inquiry'],3),
  ('Effective academic discussion requires ___.',['talking as much as possible','always agreeing with the previous speaker','never asking questions during someone\'s turn','active listening — being able to summarise what the previous speaker said before responding, engaging with their actual argument rather than changing the subject'],3),
  ('To advance a seminar discussion, a student should ___.',['only repeat what they prepared','introduce a new topic unrelated to the discussion','ask for more clarification','build on a previous contribution, extend an idea, respectfully challenge an assertion with evidence, or introduce a complicating example that tests the group\'s emerging understanding'],3),
  ('The purpose of requiring textual evidence in a seminar is ___.',['to show you did the reading','to fill time in the discussion','to penalise students who didn\'t prepare','to ground claims in specific textual detail — preventing discussion from floating into vague assertion, and ensuring claims about texts are based on what texts actually say and do'],3),
  ('The highest level of seminar participation involves ___.',['speaking longest','making the most points','never asking questions','asking a question that genuinely opens up new thinking for the group — the best seminar contributions change the direction of the discussion productively'],3)]),
A('Advanced Functions: Comprehensive Review','Students review the full MHF4U course with examination-level practice problems spanning all strands.','https://www.youtube.com/watch?v=MKQR_acrFOA',[
  ('A function f has an inverse f⁻¹ if and only if ___.',['f is continuous','f is differentiable','f is defined for all x','f is one-to-one (passes the horizontal line test) — a bijection from its domain to its range, so the inverse is also a function'],3),
  ('Solve: log₂(x+1) − log₂(x−1) = 3.',['x = 9/7: log₂((x+1)/(x−1)) = 3 → (x+1)/(x−1) = 8 → x+1 = 8x−8 → 9 = 7x → x = 9/7... check: x−1 = 2/7 > 0 ✓','x = 3','x = 7','x = 9'],0),
  ('The dot product of a = (1,−2,3) and b = (4,1,−2) is ___.',['4−2+6 = 8... no: 1×4+(−2)×1+3×(−2) = 4−2−6 = −4','4 + 2 − 6 = 0','1×4−2×1+3×2 = 8','−4 (1×4 + (−2)×1 + 3×(−2) = 4−2−6 = −4)'],3),
  ('The general term of the expansion (3x−2)⁶ containing x⁴ is ___.',['C(6,2)(3x)⁴(−2)² = 15 × 81x⁴ × 4 = 4860x⁴','C(6,4)(3x)⁴(−2)² = 15 × 81x⁴ × 4 = 4860x⁴','C(6,2)(3x)⁴(2)² = 4860x⁴','C(6,4)(3x)⁴(−2)² — note: term with x⁴ has k=4 in (3x)^(6−k)(−2)^k: k=2 → C(6,2)(3x)⁴(−2)² = 15×81×4 x⁴ = 4860x⁴'],3),
  ('In how many ways can the letters of MISSISSIPPI be arranged?',['11!/4!4!2! = 34650 (11 letters: 1M, 4I, 4S, 2P)','11!','11!/4!4!','11!/4!'],0)]),
Ca('Calculus: Comprehensive Review','Students review the full calculus course with examination-level problems on limits, derivatives, and integrals.','https://www.youtube.com/watch?v=HEH_oKNLgUU',[
  ('Find the derivative of f(x) = x²·sin(3x).',['f\'(x) = 2x·sin(3x) + x²·3cos(3x) = 2x sin(3x) + 3x²cos(3x) (product rule)','f\'(x) = 2x·cos(3x)','f\'(x) = x²·3cos(3x)','f\'(x) = 2x·sin(3x) + x²·cos(3x)'],0),
  ('A box with square base (side x) and no top has surface area 108 cm². Maximise volume. V = x²h, 4xh+x² = 108 → h = (108−x²)/(4x). V(x) = ___.',['V = x²(108−x²)/(4x) = x(108−x²)/4 = 27x − x³/4; V\'= 27−3x²/4 = 0 → x² = 36 → x = 6; V_max = 6×(108−36)/24 = 6×3 = 108 cm³','V = 108x','V = x³/4','V = 27x²'],0),
  ('∫[1 to e] (ln x)/x dx = ___.',['[let u=ln x, du=1/x dx: ∫₀¹ u du = u²/2|₀¹ = 1/2]','ln(e)/e = 1/e','1','e'],0),
  ('The area enclosed by y = x² and y = 2x is ___.',['∫[0 to 2](2x−x²) dx = [x²−x³/3]₀² = 4−8/3 = 4/3','2/3','8/3','4/3'],3),
  ('Solve: dy/dx = x/y; y(0) = 2.',['y dy = x dx; ∫y dy = ∫x dx; y²/2 = x²/2 + C; at (0,2): C = 2; y² = x² + 4; y = √(x²+4)','y = x²/2 + 2','y = xe^x + 2','y = 2e^(x²/2)'],0)]),
P('Physics: Comprehensive Review','Students review the full SPH4U course with examination-level multi-concept problems.','https://www.youtube.com/watch?v=pGj9isFr21U',[
  ('A 1500 kg car accelerates from 0 to 25 m/s in 10 s up a 10° incline (μₖ = 0.1). Net force required:',['F_net = ma + mg sinθ + μₖmg cosθ = 1500(2.5) + 1500(9.8)(0.174) + 0.1×1500×9.8×0.985 ≈ 3750+2557+1447 ≈ 7754 N','F = 1500 × 2.5 = 3750 N','F = mg sinθ only','F = ma only'],0),
  ('A spring (k=400 N/m) is compressed 0.2 m and launches a 0.1 kg ball. Speed at launch:',['½kx² = ½mv²; v = x√(k/m) = 0.2√4000 ≈ 12.6 m/s','v = kx/m = 0.2×400/0.1 = 800 m/s','v = 0.2 m/s','v = √(kx) = √80 ≈ 8.9 m/s'],0),
  ('A charge q₁ = +2μC is 0.3 m from q₂ = −3μC. The electrostatic force magnitude:',['F = kq₁q₂/r² = 9×10⁹ × 2×10⁻⁶ × 3×10⁻⁶ / 0.09 = 0.6 N (attractive)','F = 0.06 N','F = 6 N','F = 0.006 N'],0),
  ('A proton (m=1.67×10⁻²⁷ kg, q=1.6×10⁻¹⁹ C) enters a 0.5 T field at 10⁶ m/s perpendicular. Radius of circular path:',['r = mv/(qB) = 1.67×10⁻²⁷×10⁶/(1.6×10⁻¹⁹×0.5) ≈ 0.0209 m ≈ 2.1 cm','r = 1 m','r = 0.1 m','r = mv/q = 10.4 m'],0),
  ('Muons created in upper atmosphere have T½ = 2.2 μs. Moving at 0.98c, the lab-frame half-life is ___.',['γ × 2.2 μs where γ = 1/√(1−0.96) ≈ 5; lab T½ ≈ 11 μs','2.2 μs unchanged','4.4 μs','1.1 μs'],0)]),
]),
day(27,[
E('Writing Workshop: Style, Voice, and the Sentence','Students examine prose style at the level of the sentence — rhythm, syntax, diction — and revise their own writing for greater clarity, precision, and voice.','https://www.youtube.com/watch?v=kLJE8IYIQEM',[
  ('Prose style at the sentence level includes ___.',['only grammar and spelling','only vocabulary choice','only sentence length','rhythm (patterns of stress, sentence length variation), syntax (clause structure, subordination), and diction (word choice, register, tone) — all working together to create a distinctive voice'],3),
  ('Varying sentence length in academic prose ___.',['has no effect on the reader','should be avoided in formal writing','shows inconsistent style','creates rhythm and emphasis — a short sentence after several long ones lands with particular force; uniform sentence length produces monotony regardless of the quality of the ideas'],3),
  ('Nominalisations (turning verbs/adjectives into nouns) in academic writing ___.',['always improve clarity','should be avoided always','are mandatory in formal academic style','can obscure agency and make prose unnecessarily dense — "the improvement of student performance" is weaker than "students improved"; nominalisation is sometimes appropriate but often inflates and obscures'],3),
  ('The difference between a precise word and an approximate one is ___.',['only a matter of style','unimportant if the meaning is roughly correct','only important in poetry','enormous in academic writing — "the passage suggests ambivalence" is analytically precise; "the passage shows something complicated" is not; precision in diction is precision in thinking'],3),
  ('Revision at the sentence level should happen ___.',['before revising the argument structure','only for the introduction','never — first drafts are always good enough','after the larger revision (argument, structure, evidence) is complete — it is inefficient to perfect sentences in a paragraph that may be restructured or deleted'],3)]),
A('Advanced Functions: Final Exam Preparation','Rigorous examination-level practice with full worked solutions for all Advanced Functions topics.','https://www.youtube.com/watch?v=LkwT1GQVJP8',[
  ('Determine all values of k for which x³ + 5x² + kx + 2 has (x+2) as a factor.',['P(−2) = 0: −8+20−2k+2=0 → 14−2k=0 → k=7','k = 3','k = −7','k = 5'],0),
  ('Find the scalar equation of the plane through P(1,2,3), Q(2,−1,0), R(4,1,2).',['PQ=(1,−3,−3), PR=(3,−1,−1); n = PQ×PR = (3×(−1)−(−3)×(−1), (−3)×3−1×(−1), 1×(−1)−(−3)×3) = (−3−3, −9+1, −1+9) = (−6,−8,8); simplify: (3,4,−4); eq: 3(x−1)+4(y−2)−4(z−3) = 0 → 3x+4y−4z = −1','x+y+z = 6','3x+4y+4z = 6','3x−4y+4z = 0'],0),
  ('A geometric series has t₃ = 12 and t₆ = 96. Find t₁ and r.',['t₃=t₁r²=12; t₆=t₁r⁵=96; dividing: r³=8 → r=2; t₁=12/4=3','r=2, t₁=3','r=4, t₁=0.75','r=2, t₁=6'],1),
  ('P(at least one 6 in 4 rolls of a fair die) = ___.',['4/6','1 − P(no sixes) = 1 − (5/6)⁴ = 1 − 625/1296 = 671/1296 ≈ 0.518','4 × 1/6 = 2/3','(1/6)⁴'],1),
  ('The maximum value of f(x) = sin(2x) + cos(2x) is ___.',['2','1','√2 (write as R·sin(2x+φ) where R=√(1²+1²)=√2)','√3'],2)]),
Ca('Calculus: Final Exam Preparation','Rigorous examination-level problems for Calculus and Vectors.','https://www.youtube.com/watch?v=6HkBGVPWIXA',[
  ('Find the area between y=e^x, y=x, x=0, x=1.',['∫₀¹(e^x − x)dx = [e^x − x²/2]₀¹ = (e−1/2) − (1−0) = e − 3/2 ≈ 1.218','e − 1','1/2','e'],0),
  ('A particle has velocity v(t) = 3t² − 6t. Find the displacement from t=0 to t=3.',['∫₀³(3t²−6t)dt = [t³−3t²]₀³ = 27−27 = 0 (returns to start)','9','−9','3'],0),
  ('Evaluate ∫ x·ln(x) dx.',['use parts: u=ln(x), dv=x dx → v=x²/2; x²ln(x)/2 − ∫x²/2 × 1/x dx = x²ln(x)/2 − x²/4 + C','x²ln(x)/2 + C','ln(x²)/2 + C','x ln(x) − x + C'],0),
  ('The line tangent to the curve x²y + y³ = 10 at (1,2):',['implicit diff: 2xy + x²y\' + 3y²y\' = 0; y\'(x²+3y²) = −2xy; y\'(1,2) = −4/13; tangent: y−2 = −4/13(x−1)','y = −x + 3','y = −4/13 x + 30/13','y−2 = 4/13(x−1)'],0),
  ('A box is formed by cutting squares of side x from corners of a 30×20 cm sheet. Maximise volume.',['V = x(30−2x)(20−2x); V\'= 0 gives 12x²−200x+600=0 → 3x²−50x+150=0; x=(50±√(2500−1800))/6=(50±√700)/6; x≈(50−26.5)/6≈3.9 cm','x = 5 cm','x = 3 cm','x = 10 cm'],0)]),
P('Physics: Final Exam Preparation','Comprehensive examination-level physics problems spanning all SPH4U topics.','https://www.youtube.com/watch?v=kKKM8Y-u7ds',[
  ('A 0.5 kg ball on a 1 m string moves in a horizontal circle at 3 m/s. Tension in string (ignore gravity):',['T = mv²/r = 0.5×9/1 = 4.5 N','T = 0.5 × 3 = 1.5 N','T = 1.5/1 = 1.5 N','T = 5 N'],0),
  ('Two parallel plates 0.01 m apart with potential difference 100 V. Electric field between plates:',['E = V/d = 100/0.01 = 10,000 V/m','E = 100 V/m','E = 10 V/m','E = 1000 V/m'],0),
  ('An 8 kg mass oscillates on a spring (k = 200 N/m). Period:',['T = 2π√(m/k) = 2π√(8/200) = 2π√(0.04) = 2π × 0.2 ≈ 1.26 s','T = 2π√(200/8) ≈ 15.7 s','T = 0.2 s','T = 2π s'],0),
  ('A generator coil (N=100 turns, area 0.05 m², B=0.8 T) rotates at 60 Hz. Peak EMF:',['EMF_max = NBAω = 100×0.8×0.05×(2π×60) ≈ 1508 V','EMF = NBAB = 4 V','EMF = 100×60 = 6000 V','EMF = 60 V'],0),
  ('An electron (m=9.11×10⁻³¹ kg) is accelerated through 500 V. Final kinetic energy and speed:',['KE = qV = 1.6×10⁻¹⁹×500 = 8×10⁻¹⁷ J; v = √(2KE/m) = √(1.6×10⁻¹⁶/9.11×10⁻³¹) ≈ 1.33×10⁷ m/s','v = 500 m/s','v = c = 3×10⁸ m/s','v = 3×10⁵ m/s'],0)]),
]),
day(28,[
E('Culminating Essay: Writing Under Examination Conditions','Students practise writing a full analytical essay under timed conditions, applying all skills developed throughout the year.','https://www.youtube.com/watch?v=kLJE8IYIQEM',[
  ('The most important 5 minutes of a timed literary essay are ___.',['the last 5 minutes of writing','the middle of the essay','the conclusion','the first 5 minutes of planning — a clear, specific thesis and a logical outline before writing saves time and produces a more coherent essay than beginning immediately'],3),
  ('In a timed essay, the most common weakness is ___.',['writing too slowly','knowing the text too well','writing in too formal a register','insufficient analytical development — students describe textual events or state themes without explaining how specific textual choices create meaning; analysis takes time and cannot be rushed'],3),
  ('Choosing a quotation under time pressure: prefer ___.',['the longest quotation you can recall','any passage you remember','only quotations you\'ve memorised exactly','a short, specific phrase that is analytically productive — better to have two precise words you can analyse fully than two sentences you can only describe'],3),
  ('Ending a timed essay effectively: the conclusion should ___.',['repeat the introduction word for word','only name the texts again','introduce new evidence','synthesise the essay\'s argument in 3-5 sentences — showing how the evidence collectively demonstrates the thesis, and opening one genuinely new perspective or question without introducing new evidence'],3),
  ('A student who has genuinely mastered Grade 12 English will find timed writing ___.',['impossible without notes','irrelevant to real university skill','only useful for English exams','challenging but empowering — demonstrating that analytical thinking and articulate expression under pressure are real intellectual capacities, not just performances'],3)]),
A('Advanced Functions: Culminating Task','Students complete a culminating task integrating multiple strands of the MHF4U course.','https://www.youtube.com/watch?v=jKrEFOTScwU',[
  ('Part 1: Identify all features of f(x) = (x²−4)/(x²−x−2) and sketch.',['Factor: (x−2)(x+2)/((x−2)(x+1)); hole at x=2; VA at x=−1; HA y=1 (equal degrees); x-int at x=−2; y-int at f(0)=4/−2=−2; hole at (2, 4/3)','VA at x=2 and x=1 only','HA at y = 0','x-int at x = ±2 with no hole'],0),
  ('Part 2: Solve 2^(x+1) = 3^(x−1) algebraically.',['(x+1)ln2 = (x−1)ln3; x(ln2−ln3) = −ln3−ln2 = −ln6; x = ln6/(ln3−ln2) ≈ 3.82','x = ln(3/2)','x = 1','x = 2'],0),
  ('Part 3: The position vectors of points A and B are a=(3,1,−2) and b=(1,−1,4). Find the midpoint M and |AB|.',['M = ((3+1)/2, (1−1)/2, (−2+4)/2) = (2,0,1); |AB| = √((−2)²+(−2)²+6²) = √44 = 2√11','M = (4,0,2); |AB| = 8','M = (2,0,1); |AB| = √40','M = (1,1,1); |AB| = √44'],0),
  ('Part 4: A fair coin is tossed 8 times. Find P(at least 6 heads).',['P(X≥6) = P(6)+P(7)+P(8) = [C(8,6)+C(8,7)+C(8,8)]/2⁸ = (28+8+1)/256 = 37/256 ≈ 0.145','37/256','1/4','37/64'],1),
  ('Part 5: Prove by induction that ∑(k=1 to n) k³ = [n(n+1)/2]².',['Base: n=1: 1 = (1×2/2)² = 1 ✓. Inductive step: assume ∑k³ = [k(k+1)/2]²; add (k+1)³: [k(k+1)/2]²+(k+1)³ = (k+1)²[k²/4+(k+1)] = (k+1)²(k²+4k+4)/4 = [(k+1)(k+2)/2]² ✓','Not provable by induction','Formula is incorrect','Requires calculus, not induction'],0)]),
Ca('Calculus: Culminating Task','Students complete a culminating task integrating limits, derivatives, and integrals.','https://www.youtube.com/watch?v=9vgCMNHPScU',[
  ('Part 1: lim(x→0) (e^x − 1 − x)/x².',["L'Hôpital twice: (e^x−1)/(2x) → e^x/2 → 1/2","L'Hôpital once: e^x − 1","the limit is 0","the limit is 1"],0),
  ('Part 2: Differentiate f(x) = arctan(√x) and find f\'(1).',['f\'(x) = 1/(1+x) × 1/(2√x) = 1/(2√x(1+x)); f\'(1) = 1/(2×1×2) = 1/4','f\'(1) = 1/2','f\'(1) = 1/4 using chain rule on arctan(x^(1/2)): 1/(1+x) × 1/(2√x)','f\'(x) = 1/(2√x)'],2),
  ('Part 3: ∫₀^(π/2) sin²(x) dx.',['use identity sin²x = (1−cos2x)/2; ∫₀^(π/2)(1−cos2x)/2 dx = [x/2−sin(2x)/4]₀^(π/2) = π/4','π/2','π/4','1/2'],2),
  ('Part 4: Find the point on y = x² closest to (0, 3).',['Minimise D² = x² + (x²−3)²; d(D²)/dx = 2x+2(x²−3)(2x) = 2x(1+4x²−12) = 2x(4x²−11) = 0; x=0 (local max of distance) or x²=11/4; point: (√(11)/2, 11/4)','(0,0)','(1,1)','(√3, 3)'],0),
  ('Part 5: Solve dy/dx = xy with y(0) = 1.',['separate: dy/y = x dx; ln|y| = x²/2 + C; y(0)=1 → C=0; y = e^(x²/2)','y = e^x','y = x²/2 + 1','y = xe^x + 1'],0)]),
P('Physics: Culminating Task','Students complete a multi-concept physics culminating task.','https://www.youtube.com/watch?v=aY8z2qO44WA',[
  ('A projectile is launched at 50 m/s at 37° above horizontal. Find max height and range.',['v₀y=50sin37°=30 m/s; v₀x=50cos37°=40 m/s; max H=v₀y²/(2g)=900/19.6≈45.9 m; T=2×30/9.8≈6.1 s; R=40×6.1≈245 m','H=50 m; R=200 m','H=30 m; R=300 m','H=40 m; R=250 m'],0),
  ('A 2 kg block slides down a 30° ramp (μₖ=0.2) of length 5 m from rest. Speed at bottom:',['a = g(sin30°−μₖcos30°) = 9.8(0.5−0.2×0.866) = 9.8×0.327 = 3.2 m/s²; v²=2×3.2×5=32; v≈5.66 m/s','v = √(2gh) = √(2×9.8×2.5) ≈ 7 m/s','v = 5 m/s','v = 10 m/s'],0),
  ('A transformer: 120 V primary, 2400 V secondary, 0.5 A secondary current. Primary current:',['V_p I_p = V_s I_s; I_p = 2400×0.5/120 = 10 A','I_p = 0.5 A','I_p = 2.5 A','I_p = 0.025 A'],0),
  ('Radioactive source: activity at t=0 is 8000 Bq; after 12 hours = 1000 Bq. Find T½.',['8000×(1/2)^(12/T½) = 1000; (1/2)^(12/T½)=1/8=(1/2)³; 12/T½=3; T½=4 hours','T½ = 3 hours','T½ = 6 hours','T½ = 2 hours'],0),
  ('Calculate the de Broglie wavelength of an electron (m=9.11×10⁻³¹ kg) moving at 10⁶ m/s.',['λ = h/(mv) = 6.63×10⁻³⁴/(9.11×10⁻³¹×10⁶) ≈ 7.28×10⁻¹⁰ m = 0.728 nm','λ = 10⁻³⁴ m','λ = 10⁻⁶ m','λ = 1 nm'],0)]),
]),
day(29,[
E('Grade 12 English: Oral Culminating and Reflection','Students deliver oral culminating presentations and reflect on their growth as readers, writers, and thinkers across Grade 12.','https://www.youtube.com/watch?v=MSYw502dJNY',[
  ('An oral culminating in Grade 12 English demonstrates ___.',['only public speaking skill','only the ability to memorise','only knowledge of plot','the integration of all your analytical learning: the ability to think aloud, respond to texts in real time, construct an argument under pressure, and communicate sophisticated ideas to an audience'],3),
  ('Reflecting on your development as a reader across Grade 12 means ___.',['only counting books read','only identifying your favourite text','only recognising what you found difficult','articulating what has changed in how you read — what you now notice, ask, and value that you did not before — making your intellectual growth conscious and available for further development'],3),
  ('The skills developed in Grade 12 English that transfer most directly to university are ___.',['only essay formatting','only reading speed','only knowledge of canonical literature','critical reading, analytical argument, evidence-based reasoning, and clear written communication — the core intellectual skills of university education in any discipline'],3),
  ('The most significant intellectual growth in Grade 12 English occurs when ___.',['you finish all the assessments','you get the highest mark','you have memorised the most quotations','you move from seeking the "right answer" to generating your own well-supported, genuinely original interpretive arguments — from passive consumer to active maker of meaning'],3),
  ('Grade 12 English is fundamentally about ___.',['learning to write five-paragraph essays','memorising literary terms','preparing for English at university','developing your capacity to think carefully, feel deeply, and communicate precisely — using literature as the site and language as the tool of that development'],3)]),
A('Advanced Functions: Final Reflection and Looking Forward','Students reflect on the year\'s learning in Advanced Functions and its significance for future study.','https://www.youtube.com/watch?v=nRmBsxBpTjs',[
  ('The central organising concept of Advanced Functions is ___.',['the derivative of a function','only polynomial equations','only trigonometric functions','the function — as a general mathematical object with domain, range, graph, and multiple representations; all topics in the course are about different families of functions and their properties'],3),
  ('A student who has mastered Advanced Functions can ___.',['only solve textbook problems','only work in Ontario high schools','never need mathematics again','see a mathematical relationship and ask: What type of function models this? What are its key features? How does it transform? This is mathematical fluency that transfers to any quantitative field'],3),
  ('The connection between Advanced Functions and Calculus is ___.',['calculus is harder but unrelated','calculus uses completely different functions','Advanced Functions is only for non-calculus students','direct: calculus studies how functions change (differentiation) and accumulate (integration); you need deep knowledge of all function families to do calculus effectively'],3),
  ('The proof and reasoning strand in Advanced Functions ___.',['is only for future mathematics students','is unrelated to the function content','is only about mathematical induction','introduces the formal mathematical reasoning that is the foundation of university mathematics — learning to construct and verify proofs, not just apply algorithms'],3),
  ('Looking back on Grade 12 mathematics, the most valuable habit of mind developed is ___.',['memorisation of formulas','speed at calculation','test-taking strategy','mathematical curiosity — the willingness to ask "why does this work?" and "what would happen if...?" and to pursue those questions rigorously to a satisfying answer'],3)]),
Ca('Calculus: Final Reflection and University Preparation','Students reflect on Calculus learning and prepare for university calculus courses.','https://www.youtube.com/watch?v=riXcZT2ICjA',[
  ('The two most important ideas in Calculus are ___.',['the product rule and chain rule','limits and power rule','derivatives and integrals as separate topics','the derivative (instantaneous rate of change as a limit) and the integral (accumulated change); and that they are inverse operations — the Fundamental Theorem connecting them'],3),
  ('University calculus (Calculus I, II) will build on your Grade 12 learning by ___.',['starting completely from scratch','being much easier','not requiring any Grade 12 preparation','introducing multivariable calculus, series, improper integrals, and applications in physics, engineering, and economics — Grade 12 calculus is the essential foundation'],3),
  ('The most important skill for university calculus is ___.',['algebraic fluency — limits and derivatives require confident algebra; students who struggle with algebra in Grade 12 will find university calculus very difficult','memorising all derivative rules','only understanding limits','only understanding integration'],0),
  ('Calculus is the mathematics of ___.',['only curves and slopes','only physics','only areas and volumes','change — and thus of the continuous aspects of the real world: motion, growth, decay, oscillation, flow, and optimisation; it is the most widely applied branch of mathematics'],3),
  ('The experience of Grade 12 Calculus ___.',['is sufficient for all future mathematics needs','shows mathematics is only about computation','shows that advanced mathematics is inaccessible to most people','demonstrates that with persistence and conceptual understanding, genuinely deep mathematical ideas are accessible — and that the intellectual reward of understanding such ideas is considerable'],3)]),
P('Physics: Final Reflection and Looking to University','Students reflect on their Grade 12 Physics learning and its connections to university physics and modern life.','https://www.youtube.com/watch?v=aY8z2qO44WA',[
  ('The most important conceptual development in Grade 12 Physics is ___.',['learning to use complex formulas','understanding the SI unit system','knowing all fundamental constants','moving from the intuitive Newtonian world to the deeply counter-intuitive worlds of quantum mechanics and relativity — where human intuition, while useful at everyday scales, fundamentally misleads'],3),
  ('University physics (mechanics, E&M, waves/optics, modern physics) builds on Grade 12 by ___.',['being completely different in content','being much easier','repeating the same material','deepening and mathematising every concept — using multivariable calculus, differential equations, and linear algebra as the primary tools; Grade 12 physics is the conceptual foundation'],3),
  ('Physics problem-solving skill transfers to ___.',['only physics problems','only engineering problems','only science','any domain requiring structured analytical reasoning: identifying what is given and unknown, selecting appropriate principles, working systematically, checking answers dimensionally and intuitively'],3),
  ('The most significant open problems in physics today are ___.',['already solved in principle','only mathematical','only relevant to theorists','quantum gravity, dark matter, dark energy, matter-antimatter asymmetry, and a unified theory of all forces — each of which may require conceptual revolutions as profound as Einstein\'s or Planck\'s'],3),
  ('Grade 12 Physics has shown you that ___.',['physics is a closed discipline with all answers known','physics is only for those who plan to study it at university','equations are more important than concepts','the universe operates according to mathematical laws of astonishing elegance and power — and that patient, systematic, mathematically guided inquiry is the most reliable path to understanding it'],3)]),
]),
day(30,[
E('Grade 12 Celebration: A Year of Growth','A final day celebrating the intellectual journey of Grade 12 — reflecting on growth, looking ahead to university and life, and recognising what has been accomplished.','https://www.youtube.com/watch?v=jTDkTt1UTXM',[
  ('The most important thing accomplished in Grade 12 is ___.',['a high grade average','only university preparation','only skill development','genuine intellectual growth — deeper, more independent thinking; the ability to sustain a complex argument; wider reading and a more developed aesthetic and critical sensibility'],3),
  ('University marks a transition from ___.',['one set of rules to another set of rules','high school content to harder content','being assessed to never being assessed again','guided learning to independent intellectual life — you choose your own questions, pursue your own research, and take responsibility for your own intellectual development to a degree impossible in high school'],3),
  ('The reading and writing skills developed in Grade 12 ___.',['are only for English programs','will be forgotten quickly after exams','have no relevance outside school','are fundamental to success in any field requiring communication, analysis, or sustained thinking — virtually every university program and professional career'],3),
  ('Looking back on all of Grade 12, the subject that will most surprise you at university is ___.',['the one that gave you the worst grade','the one that was easiest in high school','the one you studied least','the one that opens up into a vast new world — where high school content was the surface of an ocean; at university you begin to dive'],3),
  ('The best preparation for university and adult life that Grade 12 has provided is ___.',['knowing all the curriculum content','achieving the highest possible marks','only having specific skills','the experience of sustained intellectual effort — wrestling with difficulty, revising your thinking, producing work you genuinely stand behind, and discovering what you are actually capable of'],3)]),
sub('Advanced Functions and Calculus','Grade 12 Mathematics: Final Day Celebration','Students celebrate completing two of Ontario\'s most rigorous mathematics courses and look ahead with confidence.','Khan Academy: Encouragement for Math Students','https://www.youtube.com/watch?v=riXcZT2ICjA',[
  ('Completing both Advanced Functions and Calculus in Grade 12 demonstrates ___.',['only that you like mathematics','only good test-taking strategy','nothing about future capabilities','genuine mathematical maturity — you have engaged with the deepest mathematical ideas taught in Ontario secondary school, and you have the foundation for any quantitatively demanding university program'],3),
  ('The discipline of solving a difficult mathematics problem translates to ___.',['only future mathematics problems','only to science and engineering','nothing outside mathematics','any domain requiring persistence, systematic analysis, and comfort with complexity — the problem-solving mindset is not subject-specific'],3),
  ('The most important mathematical truth you have encountered in Grade 12 is ___.',['the formula for the area of a circle','the quadratic formula','only the power rule','that calculus connects the two most fundamental mathematical operations — differentiation and integration — in a single elegant theorem; and that this connection, discovered 350 years ago, underlies virtually all of modern science and technology'],3),
  ('A student who has done well in Grade 12 mathematics should feel ___.',['that they have exhausted mathematics','that mathematics is now fully mastered','that mathematics is only useful for specialists','that they have developed genuine mathematical power — the ability to reason precisely, handle abstraction, and apply formal thinking to real problems — a portable, durable, and extremely valuable intellectual asset'],3),
  ('Looking ahead, Grade 12 mathematics graduates who pursue further study will discover ___.',['that first-year university mathematics is the same as Grade 12','that mathematics becomes less interesting at university','that all mathematics has now been discovered','that mathematics is a vast, living field of inquiry — Grade 12 covered two centuries of mathematical development; several more centuries (and open research problems) await'],3)]),
sub('Physics','Grade 12 Physics: Final Day','Students celebrate completing Grade 12 Physics and look ahead to university and the world of physics.','Crash Course Physics: Celebration','https://www.youtube.com/watch?v=pGj9isFr21U',[
  ('Grade 12 Physics has given you ___.',['only a set of formulas to memorise','only laboratory skills','only a foundation for university physics','a way of seeing the world — every natural phenomenon from the motion of planets to the behaviour of electrons is in principle understandable through the application of a small number of elegant physical laws'],3),
  ('The greatest physicists (Newton, Faraday, Maxwell, Einstein, Bohr, Feynman) were unified by ___.',['only mathematical genius','only experimental skill','only theoretical creativity','deep curiosity about how the world works — combined with the discipline to pursue that curiosity systematically, the mathematical tools to express what they found, and the imagination to conceive what had never been conceived before'],3),
  ('Climate change, renewable energy, quantum computing, and medical imaging are all ___.',['unrelated to physics','only political issues','only engineering problems','direct applications of physical principles — Grade 12 Physics is not abstract knowledge but the foundation of the most pressing technological challenges facing humanity'],3),
  ('The challenges that await the next generation of physicists and engineers include ___.',['only incremental improvements to existing technology','problems that have already been solved','only problems in pure mathematics','fusion energy, quantum computers, materials science for sustainability, space exploration, and the ultimate questions of quantum gravity and the nature of dark matter — genuinely open, important, and difficult'],3),
  ('The final lesson of Grade 12 Physics is ___.',['physics is too difficult for most people','only specialists need to understand physics','physics content is fully memorised and complete','curiosity is the essential scientific virtue — the questions "why?" and "what if?" and "how do we know?" asked persistently, rigorously, and with mathematical precision, are what the entire edifice of physics is built on'],3)]),
]),
]

append_to(12, g12b)
print('grade12.ts appended 15 days')
