#!/usr/bin/env python3
"""Phase 3: Grade 12, Days 41-50 (second and final Grade 12 batch,
completing the Days 1-50 rollout across Grades 3-12). Topics chosen to
avoid any overlap with the existing Day 1-40 set (see
data/grade12.json): metafiction, ecocriticism, matrix determinants,
complex number polar form, curvature, power series, blackbody
radiation, superconductivity, and orbital mechanics.

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as gen_grade12_days31_40.py).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys
sys.path.insert(0, '/sessions/modest-compassionate-lamport/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
C12 = 'https://tvolearn.com/pages/grade-12-calculus'
P12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RC, RP = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def C(t, s, q):
    return sub('Calculus', t, s, RC, C12, q)


def P(t, s, q):
    return sub('Physics', t, s, RP, P12, q)


g12_41_50 = [
day(41, [
E('Writing: The Extended Metaphor as Argument',
  'Grade 12 English strand: an extended metaphor sustains a single comparison throughout a piece of writing, allowing a writer to build a persuasive or reflective argument through layered, cumulative imagery.',
  [('An extended metaphor sustains ___ throughout a piece of writing.', ['A single comparison', 'A constantly changing, unrelated set of comparisons', 'No figurative language whatsoever', 'Only literal, factual description'], 0),
   ('Why might a writer use an extended metaphor to build an argument, rather than stating a claim directly?', ['A sustained comparison can make an abstract idea feel more vivid and persuasive through cumulative imagery', 'Extended metaphors always make an argument less clear to readers', 'Figurative language has no connection to persuasive writing', 'Direct claims are always more effective than any use of metaphor'], 0),
   ('Which is an example of how an extended metaphor might be used in an essay about resilience?', ['Comparing a person’s growth to a tree bending but not breaking in a storm, returning to this image throughout', 'Using a single, isolated comparison mentioned only once with no further development', 'Avoiding any figurative language throughout the entire essay', 'A comparison that changes completely and randomly in every paragraph'], 0),
   ('Why does maintaining consistency in an extended metaphor’s details strengthen its effectiveness?', ['Consistency allows the comparison to build meaning cumulatively rather than confusing the reader with shifting imagery', 'Consistency has no effect on how an extended metaphor is understood', 'An effective extended metaphor should always change its central comparison partway through', 'This concept has no connection to strong persuasive writing'], 0),
   ('Why is crafting an effective extended metaphor considered an advanced writing skill?', ['It requires sustaining a coherent comparison while still developing a clear, persuasive argument', 'This technique requires no particular skill or planning to execute effectively', 'Extended metaphors are never considered a sophisticated literary or rhetorical technique', 'This concept has no connection to advanced argumentative writing'], 0)]),
AF('Matrices: Determinants and Inverses',
   'Grade 12 Advanced Functions strand: the determinant of a matrix is a single number that reveals key properties, including whether the matrix has an inverse, which can be used to solve systems of equations.',
   [('The determinant of a matrix is ___.', ['A single number that reveals key properties of the matrix', 'A completely separate matrix with no connection to the original', 'A concept unrelated to matrices', 'Always equal to zero for every matrix'], 0),
    ('A matrix has an inverse only if its determinant is ___.', ['Not equal to zero', 'Always equal to exactly zero', 'A negative number in every single case', 'A factor entirely unrelated to whether an inverse exists'], 0),
    ('The inverse of a matrix can be used to help solve ___.', ['Systems of equations', 'Only a single equation, with no system involved', 'A concept unrelated to matrices', 'Problems with no numerical component at all'], 0),
    ('Why is it useful to check a matrix’s determinant before attempting to find its inverse?', ['It immediately tells you whether an inverse actually exists, saving unnecessary calculation', 'The determinant provides no useful information before calculating an inverse', 'Every matrix always has an inverse, regardless of its determinant', 'This concept has no connection to solving matrix problems efficiently'], 0),
    ('Why are matrix inverses useful for solving a system of linear equations written in matrix form?', ['Multiplying by the inverse matrix allows you to isolate and directly solve for the unknown variables', 'Matrix inverses have no application in solving systems of equations', 'Systems of equations written in matrix form can never be solved using an inverse', 'This concept only applies to purely abstract mathematics with no problem-solving use'], 0)]),
C('Related Rates in Three Dimensions',
  'Grade 12 Calculus strand: three-dimensional related rates problems involve finding how one changing quantity, such as volume or surface area, relates to the rate of change of another quantity over time.',
  [('Three-dimensional related rates problems involve finding how one changing quantity relates to ___.', ['The rate of change of another quantity over time', 'A completely fixed, unchanging value with no relationship to time', 'A concept unrelated to rates of change', 'Only the colour of the three-dimensional object involved'], 0),
   ('Which is an example of a three-dimensional related rates problem?', ['Finding how quickly the volume of a balloon changes as its radius increases', 'A problem with no connection to changing quantities', 'A situation involving no three-dimensional shapes whatsoever', 'A calculation entirely unrelated to calculus'], 0),
   ('Why is implicit differentiation typically used when solving a related rates problem?', ['Multiple quantities are changing with respect to time, requiring differentiation of an equation relating them', 'Implicit differentiation is never used in related rates problems', 'These problems can always be solved using only basic algebra with no calculus involved', 'This concept has no connection to solving related rates problems'], 0),
   ('Why is drawing a clear diagram often a helpful first step in solving a three-dimensional related rates problem?', ['It helps visualize the relationships between the changing quantities before setting up the necessary equation', 'Diagrams provide no useful benefit when solving these types of problems', 'Related rates problems never involve any relationships that can be visualized', 'This step has no connection to accurately solving the problem'], 0),
   ('Why are three-dimensional related rates problems relevant to real-world engineering situations, like monitoring a filling water tank?', ['They model how physical quantities change together in real time, which is essential for many practical systems', 'Related rates problems have no real-world engineering applications', 'Engineers never need to understand how changing quantities relate to one another', 'This concept only applies to purely theoretical mathematics with no practical use'], 0)]),
P('Physics: Doppler Effect and Wave Phenomena',
  'Grade 12 Physics strand: the Doppler effect describes the change in observed frequency of a wave when its source and observer are moving relative to each other, such as a siren’s pitch changing as it passes by.',
  [('The Doppler effect describes a change in observed ___ of a wave.', ['Frequency', 'Colour, with no connection to sound or wave frequency', 'Mass', 'A property entirely unrelated to waves'], 0),
   ('The Doppler effect occurs when a wave’s source and observer are ___.', ['Moving relative to each other', 'Both completely stationary with no relative motion', 'A concept unrelated to motion or waves', 'Located an infinite distance apart with no possible interaction'], 0),
   ('Which is a classic everyday example of the Doppler effect?', ['A siren’s pitch appearing to change as an ambulance passes by', 'A sound that always remains at exactly the same pitch regardless of motion', 'A situation entirely unrelated to sound waves', 'An event where no sound is produced or heard at all'], 0),
   ('Why does the frequency of a wave appear higher as its source approaches an observer?', ['The source moving closer causes successive wave crests to reach the observer more frequently', 'The source’s motion has no effect on the frequency perceived by an observer', 'Frequency always remains exactly the same regardless of relative motion', 'This concept has no connection to how sound waves are perceived'], 0),
   ('Why is the Doppler effect useful in fields like astronomy for studying distant galaxies?', ['Shifts in the frequency of light from distant objects can reveal whether they are moving toward or away from Earth', 'The Doppler effect has no application outside of everyday sound phenomena', 'Astronomers never use wave phenomena to study the motion of distant objects', 'This concept has no connection to studying the universe'], 0)])]),

day(42, [
E('Literature: Postmodern Metafiction and Self-Reference',
  'Grade 12 English strand: metafiction is a literary technique in which a work self-consciously draws attention to its own status as fiction, often blurring the line between the story and its own construction.',
  [('Metafiction is a technique in which a work draws attention to its own status as ___.', ['Fiction', 'A completely factual, non-fictional account', 'A concept unrelated to storytelling', 'A physical object with no narrative content'], 0),
   ('Metafiction often blurs the line between a story and ___.', ['Its own construction', 'A completely unrelated external event', 'A concept unrelated to narrative technique', 'The reader’s personal, private life'], 0),
   ('Which is an example of a metafictional technique?', ['A character acknowledging that they are aware they exist within a novel', 'A story told in a completely straightforward, traditional manner with no self-awareness', 'A technique entirely unrelated to narrative self-reference', 'A plot that never draws attention to its own fictional nature'], 0),
   ('Why might an author use metafiction to explore questions about the nature of storytelling itself?', ['Drawing attention to a text’s construction can prompt readers to reflect on how narratives shape meaning and truth', 'Metafiction never engages with any deeper questions about storytelling', 'This technique has no connection to exploring the nature of fiction', 'Readers never reflect on a text’s construction when metafiction is used'], 0),
   ('Why is metafiction considered a significant technique within postmodern literature specifically?', ['It reflects broader postmodern interests in questioning objective truth and traditional narrative authority', 'Metafiction has no particular connection to postmodern literary movements', 'This technique was never associated with any specific literary period or movement', 'Postmodern literature never engages with questions about narrative construction'], 0)]),
AF('Functions: Iteration and Fixed Points',
   'Grade 12 Advanced Functions strand: iterating a function means repeatedly applying it to its own output, and a fixed point is a value that remains unchanged when the function is applied to it.',
   [('Iterating a function means repeatedly applying it to ___.', ['Its own output', 'A completely different, unrelated function', 'A concept unrelated to functions', 'Only its original input value, with no repetition involved'], 0),
    ('A fixed point of a function is a value that ___.', ['Remains unchanged when the function is applied to it', 'Always changes dramatically every time the function is applied', 'A concept unrelated to how a function behaves', 'Can never be found for any type of function'], 0),
    ('If f(x) = x for a specific value of x, that value is considered ___.', ['A fixed point of the function f', 'Always equal to zero, with no other possible value', 'Unrelated to the concept of a fixed point', 'A value that can never satisfy any function'], 0),
    ('Why might repeatedly iterating a function sometimes cause its output to approach a fixed point?', ['For certain functions, each application can move the value closer to a value that satisfies the fixed point condition', 'Iteration never causes a function’s output to approach any particular value', 'Fixed points have no connection to the process of iterating a function', 'This concept only applies to functions with no real-world or mathematical significance'], 0),
    ('Why are iteration and fixed points useful concepts in fields like computer science, such as in certain algorithms?', ['Some algorithms rely on repeated iteration toward a stable, unchanging solution', 'Iteration and fixed points have no application in computer science', 'Computer algorithms never involve repeatedly applying the same process', 'This concept only applies to purely theoretical mathematics with no practical use'], 0)]),
C('Curvature and the Osculating Circle',
  'Grade 12 Calculus strand: curvature measures how sharply a curve bends at a given point, and the osculating circle is the circle that best approximates the curve’s shape at that specific point.',
  [('Curvature measures how sharply a curve ___ at a given point.', ['Bends', 'Remains perfectly straight', 'A concept unrelated to a curve’s shape', 'Changes colour'], 0),
   ('The osculating circle is the circle that best approximates a curve’s shape at ___.', ['A specific point', 'Every point along the entire curve simultaneously', 'A concept unrelated to the curve’s geometry', 'No particular location at all'], 0),
   ('Why might a curve with a very small radius of osculating circle be described as having high curvature?', ['A tighter, smaller circle indicates the curve is bending more sharply at that point', 'A smaller radius always indicates that a curve is barely bending at all', 'The size of the osculating circle has no connection to how sharply a curve bends', 'This relationship has no basis in the mathematical definition of curvature'], 0),
   ('Why is curvature useful for analyzing the safety of a road’s design, such as at a sharp turn?', ['Higher curvature at a turn generally requires lower speeds for a vehicle to safely navigate it', 'Curvature has no practical application in road design', 'Road design never requires any mathematical analysis of curve sharpness', 'This concept only applies to purely abstract mathematics with no engineering application'], 0),
   ('Why does a straight line have zero curvature?', ['A straight line does not bend at all, so there is no rate of change in its direction', 'Straight lines always have the highest possible curvature value', 'Curvature has no defined value for a straight line', 'This concept has no connection to how curvature is mathematically defined'], 0)]),
P('Physics: Blackbody Radiation and Planck’s Law',
  'Grade 12 Physics strand: a blackbody is an idealized object that absorbs all incoming radiation, and Planck’s Law describes how the intensity of radiation it emits depends on wavelength and temperature.',
  [('A blackbody is an idealized object that absorbs ___.', ['All incoming radiation', 'No radiation whatsoever', 'Only visible light, with no other wavelengths absorbed', 'A concept unrelated to the absorption of radiation'], 0),
   ('Planck’s Law describes how the intensity of radiation emitted by a blackbody depends on wavelength and ___.', ['Temperature', 'Colour, with no connection to any physical property', 'Mass', 'A factor entirely unrelated to radiation'], 0),
   ('Why does a hotter blackbody emit radiation with a shorter peak wavelength compared to a cooler one?', ['Higher temperatures shift the distribution of emitted energy toward shorter, higher-energy wavelengths', 'Temperature has no effect on the wavelength of radiation emitted by a blackbody', 'Cooler objects always emit radiation at shorter wavelengths than hotter objects', 'This concept has no connection to how blackbody radiation behaves'], 0),
   ('Why was Planck’s Law historically significant in the development of physics?', ['It helped resolve a major problem in classical physics and laid groundwork for the development of quantum theory', 'Planck’s Law had no significant impact on the development of modern physics', 'This law has no connection to the historical development of quantum theory', 'Blackbody radiation was never a significant area of study in physics'], 0),
   ('Why is blackbody radiation relevant to understanding the light emitted by stars?', ['Stars approximately behave like blackbodies, so their emitted light can reveal information about their temperature', 'Blackbody radiation has no connection to understanding the properties of stars', 'The light emitted by stars provides no useful information about their physical characteristics', 'This concept has no relevance to astrophysics'], 0)])]),

day(43, [
E('Media Analysis: The Rhetoric of Product Advertising',
  'Grade 12 English strand: product advertising uses specific rhetorical strategies, such as emotional appeal, aspirational imagery, and repetition, to persuade consumers and shape brand perception.',
  [('Product advertising uses specific strategies to ___.', ['Persuade consumers and shape brand perception', 'Provide a completely neutral, unbiased description of a product', 'Avoid influencing consumer opinion or behaviour in any way', 'A purpose entirely unrelated to persuasion'], 0),
   ('Which is an example of a rhetorical strategy commonly used in product advertising?', ['Aspirational imagery suggesting a desirable lifestyle', 'Providing only a plain list of technical specifications with no persuasive framing', 'A strategy entirely unrelated to influencing consumer perception', 'Avoiding any emotional appeal whatsoever'], 0),
   ('Why might repetition of a brand’s slogan or image be an effective advertising strategy?', ['Repeated exposure can increase familiarity and recognition, which can influence consumer preference', 'Repetition has no effect on how consumers perceive or remember a brand', 'Advertisers always avoid using repetition in their campaigns', 'This concept has no connection to marketing or persuasion'], 0),
   ('Why is analyzing the rhetorical strategies used in advertising considered an important media literacy skill?', ['It helps consumers recognize how persuasive techniques are shaping their perceptions and purchasing decisions', 'Advertising rhetoric has no real influence on consumer behaviour', 'This type of analysis provides no useful insight into media messages', 'Media literacy has no connection to understanding advertising techniques'], 0),
   ('Why might an advertisement use emotional appeal rather than purely factual information about a product?', ['Emotional connections can be a powerful motivator for purchasing decisions, sometimes more so than facts alone', 'Emotional appeal is never used as a strategy in product advertising', 'Advertisements always rely exclusively on factual, technical information', 'This concept has no connection to how consumers make purchasing decisions'], 0)]),
AF('Complex Numbers: Polar Form and De Moivre’s Theorem',
   'Grade 12 Advanced Functions strand: a complex number can be expressed in polar form using magnitude and angle, and De Moivre’s Theorem provides an efficient method for raising a complex number to a power.',
   [('A complex number in polar form is expressed using magnitude and ___.', ['Angle', 'Colour, with no connection to complex numbers', 'A factor entirely unrelated to magnitude', 'Only its real component, with no angle involved'], 0),
    ('De Moivre’s Theorem provides an efficient method for ___.', ['Raising a complex number to a power', 'Only adding two complex numbers together', 'A concept unrelated to complex number operations', 'Converting a complex number into a purely real number'], 0),
    ('Why might polar form be more convenient than standard form for multiplying complex numbers?', ['In polar form, multiplication involves simply multiplying magnitudes and adding angles, which is often simpler', 'Polar form is always significantly more complicated for performing any operation', 'Standard form is always the only usable form for complex number operations', 'This concept has no connection to simplifying complex number calculations'], 0),
    ('Why is De Moivre’s Theorem particularly useful for finding the roots of a complex number?', ['It provides a systematic way to determine multiple roots using the angle and magnitude in polar form', 'De Moivre’s Theorem has no application in finding roots of complex numbers', 'Complex number roots can never be found using any systematic mathematical method', 'This concept only applies to real numbers, not complex numbers'], 0),
    ('Why are polar form and De Moivre’s Theorem useful in fields like electrical engineering?', ['Complex numbers in polar form can effectively represent quantities like alternating current, where magnitude and phase both matter', 'These mathematical tools have no practical application in engineering', 'Electrical engineering never requires the use of complex numbers', 'This concept only applies to purely theoretical mathematics with no real-world use'], 0)]),
C('Vector-Valued Functions and Motion',
  'Grade 12 Calculus strand: a vector-valued function outputs a vector rather than a single number, often used to describe an object’s position, velocity, and acceleration as it moves through space over time.',
  [('A vector-valued function outputs ___ rather than a single number.', ['A vector', 'Only a single, unrelated integer', 'A concept unrelated to functions', 'A purely qualitative description with no numerical value'], 0),
   ('Vector-valued functions are often used to describe an object’s ___ over time.', ['Position, velocity, and acceleration', 'Colour and physical appearance only', 'A factor entirely unrelated to motion', 'Temperature exclusively, with no connection to movement'], 0),
   ('Why might differentiating a vector-valued function describing position produce a function describing velocity?', ['The derivative of a position vector with respect to time represents the rate of change of position, which is velocity', 'Differentiation has no connection to finding an object’s velocity from its position', 'A vector-valued function can never be differentiated using standard calculus techniques', 'This concept has no relevance to understanding motion'], 0),
   ('Why are vector-valued functions particularly useful for describing motion that is not confined to a single straight line?', ['They can simultaneously represent multiple components of motion, such as horizontal and vertical movement', 'Vector-valued functions can only ever describe motion along a single straight line', 'This mathematical tool has no advantage over standard single-output functions for describing motion', 'This concept only applies to purely theoretical mathematics with no connection to real motion'], 0),
   ('Why are vector-valued functions relevant to fields like robotics and aerospace engineering?', ['They provide a precise mathematical way to model and predict the complex movement of objects through space', 'Vector-valued functions have no practical application in these fields', 'Robotics and aerospace engineering never require modelling motion mathematically', 'This concept only applies to purely abstract mathematics with no engineering relevance'], 0)]),
P('Physics: Semiconductors and Modern Electronics',
  'Grade 12 Physics strand: semiconductors are materials with electrical conductivity between that of a conductor and an insulator, forming the foundation of modern electronic devices like transistors and diodes.',
  [('Semiconductors have electrical conductivity that is ___.', ['Between that of a conductor and an insulator', 'Identical to that of a perfect conductor', 'Identical to that of a perfect insulator', 'A property entirely unrelated to electrical conductivity'], 0),
   ('Semiconductors form the foundation of modern electronic devices like ___.', ['Transistors and diodes', 'Only simple, non-electronic mechanical tools', 'A category entirely unrelated to electronics', 'Devices that involve no electrical components whatsoever'], 0),
   ('Why can the conductivity of a semiconductor be precisely controlled, unlike that of a typical conductor or insulator?', ['Semiconductors can be modified through a process called doping, which adjusts their electrical properties', 'Semiconductor conductivity can never be adjusted or controlled in any way', 'This property has no connection to how semiconductors are used in electronics', 'Doping has no effect on a semiconductor’s electrical behaviour'], 0),
   ('Why are transistors, made from semiconductor materials, considered essential to modern computing?', ['They act as tiny switches that control the flow of electric current, forming the basis of digital logic circuits', 'Transistors have no functional role in modern computing devices', 'Computing devices never rely on any semiconductor-based components', 'This concept has no connection to how electronic devices process information'], 0),
   ('Why is understanding semiconductor physics important for continued advancements in electronic technology?', ['It enables engineers to develop smaller, more efficient, and more powerful electronic components', 'Semiconductor physics has no connection to advancements in electronic technology', 'Electronic devices never benefit from advances in materials science or physics', 'This concept has no relevance to the development of modern technology'], 0)])]),

day(44, [
E('Independent Reading: The Graphic Novel as Literary Form',
  'Grade 12 English strand: the graphic novel combines sophisticated visual and textual storytelling techniques, and analyzing it as a literary form requires examining panel composition, visual symbolism, and narrative pacing together.',
  [('Analyzing a graphic novel as a literary form requires examining panel composition, visual symbolism, and ___ together.', ['Narrative pacing', 'Only the total number of printed pages', 'A factor entirely unrelated to storytelling technique', 'The book’s physical cover design exclusively'], 0),
   ('Why might a graphic novel be considered a sophisticated literary form, rather than a simplified version of prose fiction?', ['It requires interpreting complex interactions between text and image to construct meaning', 'Graphic novels never require any meaningful interpretation from readers', 'This form of storytelling is always considered less complex than traditional prose', 'This concept has no connection to how literary sophistication is evaluated'], 0),
   ('Which is an example of a visual storytelling technique unique to the graphic novel form?', ['Using panel size and layout to control pacing and emphasis', 'A technique identical to those used exclusively in traditional prose novels', 'A method entirely unrelated to visual storytelling', 'Avoiding any use of images throughout the entire work'], 0),
   ('Why might symbolism in a graphic novel be conveyed differently than in a traditional prose novel?', ['Visual elements, like recurring imagery or colour choices, can convey symbolic meaning without relying solely on written description', 'Symbolism can never be conveyed through visual elements in any medium', 'Graphic novels never make use of any symbolic or thematic elements', 'This concept has no connection to how meaning is constructed in different literary forms'], 0),
   ('Why is it valuable at the Grade 12 level to apply the same rigorous literary analysis to graphic novels as to traditional prose texts?', ['It recognizes and develops skills for interpreting a legitimate and increasingly significant contemporary literary form', 'Graphic novels have no legitimate place within serious literary study', 'This type of analysis provides no meaningful academic value', 'Literary analysis skills developed through prose can never apply to any other narrative form'], 0)]),
AF('Sequences: Limits and Convergence',
   'Grade 12 Advanced Functions strand: the limit of a sequence describes the value its terms approach as the sequence continues indefinitely, and a sequence is said to converge if this limit exists.',
   [('The limit of a sequence describes the value its terms approach as the sequence ___.', ['Continues indefinitely', 'Stops after exactly two terms', 'A concept unrelated to how a sequence behaves', 'Remains completely undefined at every term'], 0),
    ('A sequence is said to converge if ___.', ['Its limit exists', 'It has no defined terms whatsoever', 'Its terms become increasingly unpredictable with no discernible pattern', 'A condition entirely unrelated to limits'], 0),
    ('If a sequence does not approach any single finite value as it continues, it is said to ___.', ['Diverge', 'Converge', 'Remain perfectly constant at every term', 'Have no defined mathematical behaviour at all'], 0),
    ('Why might the sequence 1, 1/2, 1/4, 1/8... be considered a convergent sequence?', ['Its terms approach zero as the sequence continues indefinitely', 'This sequence has no defined limit under any circumstances', 'A sequence whose terms decrease can never be considered convergent', 'This concept has no connection to how sequence limits are determined'], 0),
    ('Why is the concept of sequence convergence foundational to understanding infinite series later in calculus?', ['Whether the individual terms of a sequence converge is closely connected to whether a related series will also converge', 'Sequence convergence has no connection to the study of infinite series', 'Infinite series can always be evaluated with no consideration of sequence behaviour', 'This concept has no relevance to more advanced calculus topics'], 0)]),
C('Power Series and Radius of Convergence',
  'Grade 12 Calculus strand: a power series is an infinite sum involving powers of a variable, and its radius of convergence describes the range of values for which the series produces a finite, well-defined sum.',
  [('A power series is an infinite sum involving ___.', ['Powers of a variable', 'Only a single constant term with no variable involved', 'A concept unrelated to infinite sums', 'Colours with no numerical or mathematical basis'], 0),
   ('The radius of convergence describes the range of values for which a power series ___.', ['Produces a finite, well-defined sum', 'Always produces an infinite, undefined result', 'A concept unrelated to convergence', 'Has no mathematical meaning whatsoever'], 0),
   ('Why might a power series converge for some values of x but diverge for others?', ['The behaviour of the series’ terms can change significantly depending on the specific value substituted for the variable', 'A power series always converges identically for every possible value of x', 'The value of x has no effect on whether a power series converges', 'This concept has no connection to how power series function'], 0),
   ('Why is determining the radius of convergence an important step before using a power series to approximate a function?', ['The approximation is only valid and meaningful within that specific range of convergence', 'The radius of convergence provides no useful information for using a power series', 'A power series can always be used to approximate a function for absolutely any input value', 'This concept has no connection to the practical application of power series'], 0),
   ('Why are power series useful for representing functions that are otherwise difficult to work with directly?', ['They can express a complicated function as an infinite sum of simpler polynomial-like terms', 'Power series provide no useful way to represent complicated functions', 'Difficult functions can never be represented using any form of infinite series', 'This concept only applies to purely theoretical mathematics with no practical use'], 0)]),
P('Physics: General Relativity -- Curved Spacetime',
  'Grade 12 Physics strand: general relativity describes gravity not as a force but as the curvature of spacetime caused by the presence of mass, with massive objects warping the space around them.',
  [('General relativity describes gravity as ___.', ['The curvature of spacetime caused by mass', 'A completely separate, unrelated force with no connection to mass', 'A concept entirely unrelated to the structure of the universe', 'A force that behaves identically to electromagnetism in every way'], 0),
   ('According to general relativity, massive objects ___ the space around them.', ['Warp', 'Have no effect whatsoever on', 'Completely erase', 'A relationship entirely unrelated to mass and space'], 0),
   ('Why might light bend as it passes near a very massive object, like a star?', ['The star’s mass curves the surrounding spacetime, altering the path that light follows', 'Light is never affected in any way by the presence of massive objects', 'This phenomenon has no connection to the theory of general relativity', 'Massive objects have no measurable effect on the space around them'], 0),
   ('Why was general relativity a significant departure from earlier, classical understandings of gravity?', ['It reconceived gravity as a geometric property of spacetime rather than a direct force acting between objects', 'General relativity is identical in every way to earlier classical theories of gravity', 'This theory made no meaningful change to how gravity was understood', 'Classical theories of gravity already fully described the curvature of spacetime'], 0),
   ('Why is general relativity important for the accuracy of technologies like GPS satellites?', ['Differences in spacetime curvature at different altitudes affect time measurement, which must be accounted for in GPS calculations', 'General relativity has no practical application in modern technology', 'GPS satellites never require any adjustment based on relativistic effects', 'This concept has no connection to how satellite-based positioning systems function'], 0)])]),

day(45, [
E('Literature: Ecocriticism and Nature Writing',
  'Grade 12 English strand: ecocriticism examines the relationship between literature and the natural environment, analyzing how texts represent nature and what values or assumptions those representations reveal.',
  [('Ecocriticism examines the relationship between literature and ___.', ['The natural environment', 'Only a text’s use of grammar and syntax', 'A concept entirely unrelated to the physical world', 'A story’s publication history exclusively'], 0),
   ('This critical approach analyzes how texts represent nature and what ___ those representations reveal.', ['Values or assumptions', 'Only the exact word count of a given passage', 'A concept unrelated to interpretation or meaning', 'The font used in the original printed edition'], 0),
   ('Which is an example of a question an ecocritic might ask about a text?', ['Does this text portray nature as something to be dominated, or as something to coexist with?', 'What was the exact publication date of the text?', 'A question entirely unrelated to how nature is represented', 'How many chapters does the text contain?'], 0),
   ('Why might ecocriticism be considered an increasingly relevant lens for analyzing literature today?', ['Growing environmental concerns make examining how literature shapes attitudes toward nature especially significant', 'Ecocriticism has no connection to contemporary environmental concerns', 'This critical approach has no relevance to how literature is studied today', 'Literature never engages meaningfully with representations of the natural world'], 0),
   ('Why might an ecocritic examine not just what a text says about nature, but also whose perspective is centred in that portrayal?', ['Whose viewpoint shapes the depiction of nature can reveal underlying cultural or ideological assumptions', 'Perspective has no connection to how nature is represented in a text', 'Ecocriticism never considers whose viewpoint is reflected in a text', 'This concept has no relevance to literary analysis of nature writing'], 0)]),
AF('Optimization: Constrained Problems with Multiple Variables',
   'Grade 12 Advanced Functions strand: constrained optimization involves finding the maximum or minimum value of a quantity while satisfying one or more limiting conditions involving multiple variables.',
   [('Constrained optimization involves finding a maximum or minimum value while satisfying ___.', ['One or more limiting conditions', 'No conditions whatsoever', 'A concept entirely unrelated to limiting factors', 'Only conditions involving a single variable, with no others considered'], 0),
    ('These optimization problems typically involve ___ variables.', ['Multiple', 'Exactly one, with no other variables ever involved', 'No variables whatsoever', 'A concept unrelated to variables'], 0),
    ('Which is an example of a real-world constrained optimization problem?', ['Maximizing the volume of a box given a fixed amount of material', 'A problem with no limiting conditions or constraints involved', 'A situation entirely unrelated to optimizing a specific quantity', 'A scenario where every possible outcome is equally acceptable'], 0),
    ('Why is it important to express the given constraint mathematically before attempting to solve an optimization problem?', ['The constraint defines the relationship between variables, which can then be used to reduce the problem to a single variable', 'The constraint provides no useful mathematical information for solving the problem', 'Optimization problems can always be solved with no consideration of any given constraints', 'This concept has no connection to the process of solving these problems'], 0),
    ('Why are constrained optimization problems relevant to fields like business and economics?', ['Businesses often need to maximize outcomes like profit while working within limited resources like budget or materials', 'Constrained optimization has no real-world application in business or economics', 'Businesses never need to consider limiting factors when making decisions', 'This concept only applies to purely theoretical mathematics with no economic relevance'], 0)]),
C('Slope Fields and Differential Equations',
  'Grade 12 Calculus strand: a slope field visually represents the general behaviour of solutions to a differential equation by drawing short line segments indicating the slope at various points across the plane.',
  [('A slope field visually represents the general behaviour of solutions to a ___.', ['Differential equation', 'Basic linear equation with no derivatives involved', 'A concept unrelated to calculus', 'Simple arithmetic expression with no variables'], 0),
   ('A slope field is constructed using short line segments indicating ___ at various points.', ['The slope', 'Only the colour of each individual point', 'A concept unrelated to rate of change', 'The exact numerical value of the function itself, with no connection to slope'], 0),
   ('Why might a slope field be useful even before an exact solution to a differential equation has been found?', ['It provides a visual sense of how solutions generally behave across different regions of the plane', 'Slope fields provide no useful information about a differential equation’s behaviour', 'A differential equation must always be solved exactly before any visual representation is possible', 'This concept has no connection to understanding differential equations qualitatively'], 0),
   ('Why can sketching a specific solution curve on a slope field be a useful way to approximate that solution?', ['Following the direction indicated by the line segments approximates the path a specific solution would take', 'Slope fields provide no way to approximate an actual solution curve', 'Solution curves have no relationship to the line segments shown in a slope field', 'This concept has no connection to visually approximating a differential equation’s solution'], 0),
   ('Why are slope fields a valuable tool for building qualitative understanding in the study of differential equations?', ['They allow patterns in solution behaviour to be recognized without needing to solve the equation algebraically first', 'Slope fields have no value for building understanding of differential equations', 'Qualitative understanding is never useful when studying differential equations', 'This concept only applies to purely abstract mathematics with no conceptual benefit'], 0)]),
P('Physics: Quark Confinement and the Strong Force',
  'Grade 12 Physics strand: quarks are fundamental particles bound together by the strong force, and quark confinement describes the observation that individual quarks are never found isolated in nature.',
  [('Quarks are fundamental particles bound together by the ___.', ['Strong force', 'Force of gravity exclusively, with no other force involved', 'A concept entirely unrelated to fundamental particles', 'Electromagnetic force exclusively, with no other force involved'], 0),
   ('Quark confinement describes the observation that individual quarks ___.', ['Are never found isolated in nature', 'Are commonly found existing completely independently', 'A concept unrelated to how quarks exist in nature', 'Do not actually exist as fundamental particles'], 0),
   ('Why does the strong force behave differently from gravity as the distance between particles increases?', ['The strong force actually increases in strength as quarks are pulled apart, unlike gravity, which weakens with distance', 'The strong force always weakens in exactly the same way as gravity does', 'Distance has no effect on the behaviour of the strong force', 'This concept has no connection to how fundamental forces operate'], 0),
   ('Which is an example of a composite particle made up of quarks bound together?', ['A proton', 'An electron, which is not made up of quarks', 'A particle entirely unrelated to the strong force', 'A photon, which carries no quark structure'], 0),
   ('Why is understanding quark confinement important for a complete picture of the Standard Model of particle physics?', ['It explains a fundamental and distinctive behaviour of one of the basic forces governing how matter is structured', 'Quark confinement has no relevance to understanding the Standard Model', 'The Standard Model of particle physics has no connection to the behaviour of quarks', 'This concept has no significance in modern particle physics'], 0)])]),

day(46, [
E('Writing: The Eulogy and Occasional Speech',
  'Grade 12 English strand: a eulogy or occasional speech is written for a specific ceremonial purpose, requiring a tone appropriate to the occasion and language that connects personal reflection to broader, shared meaning.',
  [('A eulogy or occasional speech is written for a specific ___ purpose.', ['Ceremonial', 'Entirely unrelated to any occasion or event', 'Purely technical, with no ceremonial element at all', 'A purpose disconnected from any audience or context'], 0),
   ('This type of speech requires a tone that is appropriate to ___.', ['The occasion', 'No specific context or audience whatsoever', 'A factor entirely unrelated to the purpose of the speech', 'Only the speaker’s personal preference, with no consideration of the audience'], 0),
   ('Why might a eulogy connect personal reflection to broader, shared meaning?', ['It helps an audience relate the specific memories being shared to universal themes like loss, love, or legacy', 'Personal reflection and broader meaning are always completely unrelated in this type of speech', 'A eulogy should never attempt to connect with a shared audience experience', 'This concept has no connection to effective occasional speech writing'], 0),
   ('Why is understanding the specific occasion important when writing a speech like a eulogy or a wedding toast?', ['The purpose and tone required can differ significantly depending on the specific ceremonial context', 'The occasion has no effect on how this type of speech should be written', 'All occasional speeches should always be written in an identical way regardless of context', 'This concept has no connection to effective speech writing'], 0),
   ('Why might careful word choice be especially important when writing a eulogy?', ['The language needs to convey genuine emotion and respect appropriate to a sensitive and significant occasion', 'Word choice has no particular significance in this specific type of writing', 'A eulogy should always use the most casual, informal language possible', 'This concept has no connection to writing an effective ceremonial speech'], 0)]),
AF('Functions: Symmetry -- Even, Odd, and Neither',
   'Grade 12 Advanced Functions strand: a function can be classified as even, odd, or neither based on how its graph behaves under reflection, which reveals useful structural properties about the function.',
   [('A function can be classified as even, odd, or ___.', ['Neither', 'Only positive, with no other classification possible', 'Only negative, with no other classification possible', 'A category unrelated to function symmetry'], 0),
    ('An even function’s graph is symmetric with respect to the ___.', ['y-axis', 'x-axis exclusively, with no connection to the y-axis', 'Origin exclusively, with no connection to the y-axis', 'A concept unrelated to any axis of symmetry'], 0),
    ('An odd function’s graph is symmetric with respect to the ___.', ['Origin', 'y-axis exclusively, with no connection to the origin', 'x-axis exclusively, with no connection to the origin', 'A concept unrelated to any point of symmetry'], 0),
    ('Why might identifying a function as even or odd be useful before analyzing or graphing it further?', ['It reveals a structural property that can simplify calculations or predictions about the function’s behaviour', 'This classification provides no useful information about a function’s behaviour', 'Every function must always be treated identically regardless of any symmetry it has', 'This concept has no connection to understanding or graphing a function'], 0),
    ('Why might recognizing a function as odd be particularly useful when evaluating a definite integral over a symmetric interval?', ['An odd function’s symmetry can allow certain integrals over a symmetric interval to be simplified or determined without full calculation', 'Symmetry classification has no connection to evaluating definite integrals', 'Odd functions can never be integrated using any simplified method', 'This concept only applies to purely abstract mathematics with no practical calculation benefit'], 0)]),
C('Logistic Growth Models',
  'Grade 12 Calculus strand: a logistic growth model describes a quantity that initially grows rapidly but slows as it approaches a maximum sustainable value, called the carrying capacity, unlike unlimited exponential growth.',
  [('A logistic growth model describes a quantity that initially grows rapidly but ___ as it approaches a maximum value.', ['Slows', 'Continues increasing at an unlimited, ever-accelerating rate', 'A concept unrelated to how the quantity changes over time', 'Immediately drops to zero with no gradual change'], 0),
   ('The maximum sustainable value in a logistic growth model is called the ___.', ['Carrying capacity', 'Growth rate, with no connection to a maximum value', 'Initial value exclusively, with no connection to a maximum', 'A concept unrelated to sustainable growth'], 0),
   ('Why is a logistic growth model often more realistic than a simple exponential growth model for describing a population over a long period of time?', ['Real populations are usually limited by factors like resources, unlike the unlimited growth assumed by a purely exponential model', 'Logistic models are always identical to purely exponential growth models', 'Exponential growth always provides a perfectly accurate long-term prediction for real populations', 'This concept has no connection to how populations actually behave over time'], 0),
   ('Why does a logistic growth curve have an S-shape (or sigmoid shape) when graphed?', ['Growth starts slowly, accelerates, and then levels off as the quantity approaches its carrying capacity', 'A logistic growth curve is always a perfectly straight line with no curvature', 'The S-shape has no connection to how logistic growth is mathematically defined', 'This concept has no relevance to how the model is graphed or interpreted'], 0),
   ('Why are logistic growth models useful in fields like epidemiology, such as modelling the spread of a disease within a limited population?', ['They can realistically capture how spread initially accelerates but then slows as the population of susceptible individuals decreases', 'Logistic growth models have no application in epidemiology', 'Disease spread within a population can never be modelled mathematically', 'This concept only applies to purely theoretical mathematics with no real-world use'], 0)]),
P('Physics: Superconductivity',
  'Grade 12 Physics strand: superconductivity is a phenomenon in which certain materials, when cooled below a critical temperature, conduct electric current with zero electrical resistance.',
  [('Superconductivity occurs when certain materials conduct electric current with ___.', ['Zero electrical resistance', 'Extremely high electrical resistance', 'A property entirely unrelated to electrical resistance', 'Resistance that increases continuously over time with no limit'], 0),
   ('Superconductivity occurs when a material is cooled below its ___.', ['Critical temperature', 'Boiling point exclusively, with no connection to a critical temperature', 'Melting point exclusively, with no connection to a critical temperature', 'A factor entirely unrelated to temperature'], 0),
   ('Why is zero electrical resistance in a superconductor considered a significant property?', ['It allows electric current to flow without any energy loss due to resistance, unlike ordinary conductors', 'Zero resistance has no meaningful benefit compared to typical conductors', 'Ordinary conductors already have zero electrical resistance under normal conditions', 'This property has no connection to how electric current flows through a material'], 0),
   ('Which is an example of a practical application that relies on superconductivity?', ['Powerful electromagnets used in MRI machines', 'A technology entirely unrelated to electricity or magnetism', 'A device that requires high electrical resistance to function', 'An application that has no connection to cooling materials'], 0),
   ('Why does the need for extremely low temperatures currently limit the widespread practical use of many superconducting materials?', ['Maintaining such low temperatures requires significant energy and specialized equipment, adding cost and complexity', 'Temperature has no effect on whether a material exhibits superconductivity', 'Superconducting materials can maintain their properties at any temperature with no special conditions required', 'This concept has no connection to the practical challenges of using superconductors'], 0)])]),

day(47, [
E('Oral Communication: The TED-Style Talk',
  'Grade 12 English strand: a TED-style talk presents a single compelling idea within a concise time limit, combining a personal narrative hook, clear structure, and a memorable closing to leave a lasting impression on the audience.',
  [('A TED-style talk presents ___ within a concise time limit.', ['A single compelling idea', 'As many unrelated ideas as possible within the given time', 'A concept unrelated to focused, structured communication', 'A purely technical report with no central idea'], 0),
   ('Why might a TED-style talk begin with a personal narrative hook?', ['A relatable, personal opening can quickly capture audience interest and establish an emotional connection', 'A personal narrative hook always weakens the impact of this type of talk', 'This structure never appears in an effective TED-style presentation', 'This concept has no connection to engaging an audience from the outset'], 0),
   ('Why is having a clear structure especially important for a concise talk with a strict time limit?', ['A clear structure helps ensure the core idea is communicated efficiently and memorably within limited time', 'Structure has no effect on how well a concise talk communicates its main idea', 'A time limit has no influence on how a talk should be structured', 'This concept has no connection to effective public speaking within a constrained format'], 0),
   ('Why might a TED-style talk aim to end with a particularly memorable closing statement?', ['A strong closing can reinforce the central idea and leave a lasting impression on the audience', 'The closing statement has no particular importance in this type of talk', 'A memorable ending always distracts from the main message of the talk', 'This concept has no connection to effective persuasive or informative speaking'], 0),
   ('Why is focusing on a single compelling idea, rather than several unrelated ones, considered an effective approach for this speaking format?', ['A single focused idea is easier for an audience to understand, remember, and be moved by within a short time frame', 'Focusing on a single idea always makes a talk less interesting to an audience', 'Multiple unrelated ideas are always more effective than a single focused one', 'This concept has no connection to how audiences process and retain information'], 0)]),
AF('Recursive Sequences: Advanced Applications',
   'Grade 12 Advanced Functions strand: advanced recursive sequences apply a defining rule repeatedly to model complex real-world processes, such as compound growth patterns that depend on more than one previous term.',
   [('Advanced recursive sequences apply a defining rule repeatedly to model ___.', ['Complex real-world processes', 'A concept entirely unrelated to real-world modelling', 'Only purely abstract patterns with no practical application', 'A single, isolated calculation with no repeated process involved'], 0),
    ('Some advanced recursive sequences depend on ___ previous term(s).', ['More than one', 'Exactly zero, with no dependence on any prior term', 'Only a single previous term, in every possible case', 'A concept unrelated to how recursive sequences are defined'], 0),
    ('Which is an example of a sequence where each term depends on the two previous terms?', ['The Fibonacci sequence', 'A sequence with no defined recursive pattern whatsoever', 'A sequence unrelated to recursive definitions', 'Any sequence with a constant, unchanging value throughout'], 0),
    ('Why might a recursive sequence be a natural way to model a population that grows based on both current and previous population data?', ['A recursive definition can directly capture how a term’s value depends on one or more earlier terms in the sequence', 'Recursive sequences have no useful application for modelling population growth', 'Population growth can never depend on more than a single prior data point', 'This concept has no connection to how recursive sequences function'], 0),
    ('Why are advanced recursive sequences relevant to computer science, particularly in the design of certain algorithms?', ['Many algorithms are designed using a recursive structure, where a solution depends on solutions to smaller, related instances of the same problem', 'Recursive sequences have no connection to how algorithms are designed', 'Computer science algorithms never rely on any form of recursive structure', 'This concept only applies to purely theoretical mathematics with no application to computing'], 0)]),
C('Sequences and Series Convergence Tests',
  'Grade 12 Calculus strand: convergence tests, such as the ratio test or comparison test, provide systematic methods for determining whether an infinite series converges to a finite sum or diverges.',
  [('Convergence tests provide systematic methods for determining whether an infinite series ___.', ['Converges to a finite sum or diverges', 'Always produces exactly the same numerical result', 'A concept unrelated to the behaviour of infinite series', 'Contains a finite, specific number of terms'], 0),
   ('Which is an example of a convergence test used to analyze an infinite series?', ['The ratio test', 'A method entirely unrelated to analyzing series behaviour', 'A test that only applies to determining a series’ first term', 'A test unrelated to determining whether a series converges'], 0),
   ('Why might the ratio test be particularly useful for analyzing a series involving factorials or exponential terms?', ['This test often simplifies effectively when applied to series with these specific types of rapidly changing terms', 'The ratio test is never useful for analyzing any type of infinite series', 'Factorial and exponential terms can never be analyzed using any convergence test', 'This concept has no connection to how convergence tests are applied'], 0),
   ('Why is determining whether a series converges or diverges an important step before attempting to find its exact sum?', ['A sum only meaningfully exists if the series actually converges to a finite value', 'Every infinite series always has a well-defined finite sum, regardless of convergence', 'Convergence has no connection to whether a series has a meaningful sum', 'This concept has no relevance to working with infinite series'], 0),
   ('Why are multiple convergence tests useful, rather than relying on just one single test for every series?', ['Different series have different characteristics, and certain tests are more effective or conclusive for specific types of series', 'Having multiple tests provides no additional benefit for analyzing series', 'A single convergence test is always equally effective for every possible type of series', 'This concept has no connection to effectively analyzing infinite series'], 0)]),
P('Physics: Resonance and Acoustics',
  'Grade 12 Physics strand: resonance occurs when a system is driven to oscillate at its natural frequency with increased amplitude, a principle central to acoustics and the design of musical instruments.',
  [('Resonance occurs when a system is driven to oscillate at its ___ with increased amplitude.', ['Natural frequency', 'Slowest possible frequency, regardless of its natural properties', 'A concept unrelated to oscillation', 'Maximum possible temperature'], 0),
   ('Resonance is a principle central to ___ and the design of musical instruments.', ['Acoustics', 'A field entirely unrelated to sound', 'Only visual art, with no connection to sound', 'A concept unrelated to oscillating systems'], 0),
   ('Why might a wine glass shatter when exposed to a sound at exactly its natural frequency?', ['The resonant vibration can build up amplitude until it exceeds the structural limits of the glass', 'Resonance has no effect on the vibration of a physical object like a glass', 'Sound waves never have any physical effect on solid objects', 'This concept has no connection to how resonance and vibration function'], 0),
   ('Why do musical instrument designers carefully consider the shape and material of an instrument’s body?', ['These factors influence the instrument’s resonant properties, shaping the sound quality it produces', 'The shape and material of an instrument have no effect on the sound it produces', 'Resonance has no connection to how musical instruments are designed', 'This concept has no relevance to acoustics or instrument design'], 0),
   ('Why is understanding resonance important for engineers designing structures like bridges?', ['Structures need to be designed to avoid dangerous resonant vibrations caused by factors like wind or foot traffic', 'Resonance has no relevance to the structural design of bridges or buildings', 'Engineers never need to consider natural frequency when designing large structures', 'This concept has no connection to structural safety or engineering design'], 0)])]),

day(48, [
E('Literature: Voice in Contemporary Indigenous Poetry',
  'Grade 12 English strand: contemporary Indigenous poetry often centres voice, land, and community, blending traditional oral storytelling traditions with modern poetic forms to explore identity and resilience.',
  [('Contemporary Indigenous poetry often centres voice, land, and ___.', ['Community', 'A theme entirely unrelated to identity or culture', 'Only fictional, invented settings with no connection to real experience', 'Grammar rules with no thematic significance'], 0),
   ('This poetry often blends traditional oral storytelling traditions with ___.', ['Modern poetic forms', 'A style entirely disconnected from any storytelling tradition', 'Only historical writing with no modern influence', 'Forms that have no connection to poetry as an art form'], 0),
   ('Why might Indigenous poets draw on oral storytelling traditions within a written poetic form?', ['It honours cultural heritage while adapting it to reach and resonate with contemporary readers', 'Oral storytelling traditions have no connection to contemporary written poetry', 'Poets never draw on any cultural or historical tradition when writing', 'This concept has no relevance to understanding contemporary Indigenous literature'], 0),
   ('Why might land be a significant recurring theme in much contemporary Indigenous poetry?', ['Connection to land is often deeply tied to identity, culture, and history for many Indigenous communities', 'Land has no significance as a theme in Indigenous poetry', 'This theme is never explored within Indigenous literary traditions', 'This concept has no relevance to contemporary poetry as a genre'], 0),
   ('Why is engaging with contemporary Indigenous poetry valuable for building a fuller understanding of Canadian literature?', ['It offers vital perspectives and voices that enrich and expand the broader literary landscape', 'This poetry has no connection to Canadian literary history or identity', 'Indigenous voices add no unique perspective to literary study', 'Studying this poetry has no educational or cultural value'], 0)]),
AF('Review: Determinants, Complex Numbers, and Optimization',
   'Grade 12 Advanced Functions strand review: this lesson revisits matrix determinants, function iteration and fixed points, complex numbers in polar form, constrained optimization, and even/odd function symmetry.',
   [('The determinant of a matrix is ___.', ['A single number that reveals key properties of the matrix', 'A completely separate matrix with no connection to the original', 'A concept unrelated to matrices', 'Always equal to zero for every matrix'], 0),
    ('A complex number in polar form is expressed using magnitude and ___.', ['Angle', 'Colour, with no connection to complex numbers', 'A factor entirely unrelated to magnitude', 'Only its real component, with no angle involved'], 0),
    ('Constrained optimization involves finding a maximum or minimum value while satisfying ___.', ['One or more limiting conditions', 'No conditions whatsoever', 'A concept entirely unrelated to limiting factors', 'Only conditions involving a single variable, with no others considered'], 0),
    ('An even function’s graph is symmetric with respect to the ___.', ['y-axis', 'x-axis exclusively, with no connection to the y-axis', 'Origin exclusively, with no connection to the y-axis', 'A concept unrelated to any axis of symmetry'], 0),
    ('Why is it useful to review determinants, complex numbers, and optimization together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
C('Applications: Calculus in Biology -- Population Models',
  'Grade 12 Calculus strand: calculus provides tools for modelling how populations change over time, using derivatives to represent growth rates and differential equations to capture more complex population dynamics.',
  [('Calculus provides tools for modelling how populations change over ___.', ['Time', 'Only a single, fixed instant with no consideration of change', 'A concept unrelated to population dynamics', 'Colour, with no connection to any biological process'], 0),
   ('Derivatives can be used in population modelling to represent ___.', ['Growth rates', 'Only a population’s total, unchanging size', 'A factor entirely unrelated to how a population changes', 'The exact geographic location of a population'], 0),
   ('Why might a differential equation be used to model a population influenced by both births and a limited food supply?', ['A differential equation can capture how the rate of population change depends on multiple interacting factors at once', 'Differential equations have no application in modelling biological populations', 'Population change can never be represented using any calculus-based method', 'This concept has no connection to how real populations actually behave'], 0),
   ('Why is calculus considered a valuable tool for biologists studying population dynamics?', ['It provides precise mathematical methods for analyzing and predicting how population sizes change under various conditions', 'Calculus has no meaningful application within the field of biology', 'Population dynamics can never be meaningfully studied using mathematical tools', 'This concept only applies to purely theoretical mathematics with no biological relevance'], 0),
   ('Why might comparing a simple exponential model to a more complex logistic model be useful when studying a real population?', ['Comparing models can reveal which assumptions more accurately reflect the real-world limiting factors affecting that population', 'Comparing different population models provides no useful scientific insight', 'A single, simple model is always equally accurate for every real-world population', 'This concept has no connection to how biologists evaluate mathematical models'], 0)]),
P('Physics: Satellites and Orbital Mechanics',
  'Grade 12 Physics strand: orbital mechanics describes how satellites remain in orbit through a balance between gravitational pull and their forward velocity, determining factors like orbital period and altitude.',
  [('Satellites remain in orbit through a balance between gravitational pull and their ___.', ['Forward velocity', 'Complete lack of any motion whatsoever', 'Internal temperature, with no connection to motion', 'A factor entirely unrelated to orbital mechanics'], 0),
   ('Orbital mechanics helps determine factors like orbital period and ___.', ['Altitude', 'Colour, with no connection to a satellite’s orbit', 'A factor entirely unrelated to a satellite’s position', 'The material used to construct the satellite exclusively'], 0),
   ('Why does a satellite orbiting at a higher altitude generally have a longer orbital period?', ['A larger orbit requires travelling a greater distance, and gravitational pull is weaker farther from Earth, both factors that affect this relationship', 'Altitude has no effect on how long a satellite takes to complete one orbit', 'All satellites, regardless of altitude, always have exactly the same orbital period', 'This concept has no connection to how orbital mechanics functions'], 0),
   ('Why is precise calculation important when placing a satellite into a stable orbit?', ['Even small errors in velocity or altitude can prevent a satellite from maintaining a stable, sustained orbit', 'Precision has no effect on whether a satellite can maintain a stable orbit', 'Satellites can be placed into orbit with no consideration of gravitational or velocity factors', 'This concept has no relevance to the practical challenges of satellite deployment'], 0),
   ('Why is understanding orbital mechanics essential for planning communication and weather satellite networks?', ['It ensures satellites are placed at altitudes and orbits appropriate for their specific intended function', 'Orbital mechanics has no connection to how satellite networks are planned or designed', 'Communication and weather satellites never require any specific orbital placement', 'This concept has no practical application in modern satellite technology'], 0)])]),

day(49, [
E('Writing: Synthesizing Multiple Sources in Academic Argument',
  'Grade 12 English strand: synthesizing multiple sources involves weaving together evidence and ideas from several texts to construct a cohesive, original argument, rather than simply summarizing each source in isolation.',
  [('Synthesizing multiple sources involves weaving together evidence and ideas from several texts to construct ___.', ['A cohesive, original argument', 'A series of completely separate, disconnected summaries', 'A concept unrelated to using multiple sources', 'An argument based entirely on a single source, with no others considered'], 0),
   ('Why is synthesis different from simply summarizing each source one at a time?', ['Synthesis actively connects and compares ideas across sources to build a new, unified argument', 'Synthesis and summarizing sources one at a time are always identical processes', 'Synthesis never involves comparing or connecting ideas from multiple sources', 'This concept has no connection to constructing an academic argument'], 0),
   ('Why might a writer place two sources in conversation with each other when they offer differing perspectives?', ['Directly comparing differing viewpoints can help develop a more nuanced and well-supported original argument', 'Sources with differing perspectives should always be discussed in complete isolation from one another', 'Comparing differing viewpoints never strengthens an academic argument', 'This concept has no connection to effective source synthesis'], 0),
   ('Why is synthesis considered a more advanced academic skill than simple summary?', ['It requires critical thinking to identify meaningful connections, patterns, or tensions across multiple sources', 'Synthesis requires no more skill or critical thinking than a simple summary', 'Summary is always considered a more advanced skill than synthesis', 'This concept has no connection to the development of academic writing skills'], 0),
   ('Why is the ability to synthesize sources particularly valuable for university-level research writing?', ['University-level research often requires building an original argument informed by a wide range of existing scholarship', 'Synthesis has no particular relevance to university-level academic work', 'University research writing never involves engaging with multiple existing sources', 'This concept has no connection to succeeding in advanced academic writing'], 0)]),
AF('Review: Sequences, Symmetry, and Recursive Applications',
   'Grade 12 Advanced Functions strand review: this lesson revisits sequence limits and convergence, function symmetry, and advanced recursive sequence applications from Days 41-47.',
   [('The limit of a sequence describes the value its terms approach as the sequence ___.', ['Continues indefinitely', 'Stops after exactly two terms', 'A concept unrelated to how a sequence behaves', 'Remains completely undefined at every term'], 0),
    ('A function can be classified as even, odd, or ___.', ['Neither', 'Only positive, with no other classification possible', 'Only negative, with no other classification possible', 'A category unrelated to function symmetry'], 0),
    ('Advanced recursive sequences apply a defining rule repeatedly to model ___.', ['Complex real-world processes', 'A concept entirely unrelated to real-world modelling', 'Only purely abstract patterns with no practical application', 'A single, isolated calculation with no repeated process involved'], 0),
    ('A sequence is said to converge if ___.', ['Its limit exists', 'It has no defined terms whatsoever', 'Its terms become increasingly unpredictable with no discernible pattern', 'A condition entirely unrelated to limits'], 0),
    ('Why is it useful to review sequences, symmetry, and recursive applications together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
C('Review: Curvature, Power Series, and Growth Models',
  'Grade 12 Calculus strand review: this lesson revisits curvature, power series and radius of convergence, slope fields, logistic growth models, and convergence tests from Days 41-47.',
  [('Curvature measures how sharply a curve ___ at a given point.', ['Bends', 'Remains perfectly straight', 'A concept unrelated to a curve’s shape', 'Changes colour'], 0),
   ('The radius of convergence describes the range of values for which a power series ___.', ['Produces a finite, well-defined sum', 'Always produces an infinite, undefined result', 'A concept unrelated to convergence', 'Has no mathematical meaning whatsoever'], 0),
   ('The maximum sustainable value in a logistic growth model is called the ___.', ['Carrying capacity', 'Growth rate, with no connection to a maximum value', 'Initial value exclusively, with no connection to a maximum', 'A concept unrelated to sustainable growth'], 0),
   ('Which is an example of a convergence test used to analyze an infinite series?', ['The ratio test', 'A method entirely unrelated to analyzing series behaviour', 'A test that only applies to determining a series’ first term', 'A test unrelated to determining whether a series converges'], 0),
   ('Why is it useful to review curvature, power series, and growth models together?', ['It reinforces how these advanced calculus tools connect and build upon one another', 'These topics have no connection to each other', 'Review is never useful in calculus', 'Each topic must be studied with no connection to the others'], 0)]),
P('Physics: Renewable Energy Technologies -- Physics Principles',
  'Grade 12 Physics strand: renewable energy technologies, such as solar panels and wind turbines, apply fundamental physics principles to convert natural sources of energy into usable electrical power.',
  [('Renewable energy technologies apply fundamental physics principles to convert natural sources of energy into ___.', ['Usable electrical power', 'A form of energy with no practical application', 'A concept unrelated to energy conversion', 'Heat that is immediately released with no further use'], 0),
   ('Which is an example of a renewable energy technology?', ['A solar panel', 'A technology that relies exclusively on non-renewable fuel sources', 'A device entirely unrelated to energy generation', 'A tool that generates no usable energy whatsoever'], 0),
   ('Why do solar panels rely on the photoelectric effect to generate electricity?', ['Light striking the solar panel’s material can release electrons, creating an electric current', 'Solar panels have no connection to the physics of light and electrons', 'The photoelectric effect has no practical application in renewable energy', 'This concept has no relevance to how solar panels function'], 0),
   ('Why does a wind turbine’s design take into account principles of rotational motion and torque?', ['Efficiently converting wind’s kinetic energy into rotational motion is essential for generating usable electrical power', 'Rotational motion and torque have no connection to how a wind turbine operates', 'Wind turbines generate electricity with no reliance on any physical principles', 'This concept has no relevance to renewable energy technology design'], 0),
   ('Why is understanding the underlying physics of renewable energy technologies important for improving their efficiency?', ['A deeper understanding of these principles can guide innovations that capture and convert energy more effectively', 'Physics has no connection to improving the efficiency of renewable energy systems', 'Renewable energy technologies cannot be improved through any scientific understanding', 'This concept has no relevance to ongoing renewable energy research and development'], 0)])]),

day(50, [
E('Literature: The Anti-Hero in Modern Narrative',
  'Grade 12 English strand: the anti-hero is a protagonist who lacks traditional heroic qualities, such as clear moral virtue, complicating a reader’s sense of who to root for and challenging conventional narrative expectations.',
  [('An anti-hero is a protagonist who lacks ___.', ['Traditional heroic qualities, such as clear moral virtue', 'Any role or presence within the narrative whatsoever', 'A concept unrelated to a story’s central character', 'A name or any other form of identity within the story'], 0),
   ('The anti-hero complicates a reader’s sense of ___.', ['Who to root for', 'The physical setting of the story', 'A concept unrelated to a reader’s engagement with a character', 'The story’s exact publication date'], 0),
   ('Why might an author use an anti-hero to challenge conventional narrative expectations?', ['It disrupts the traditional clear divide between hero and villain, prompting more complex moral reflection from the reader', 'Anti-heroes always make a narrative simpler and less morally complex', 'This character type has no effect on how a reader engages with a story’s themes', 'This concept has no connection to challenging typical storytelling conventions'], 0),
   ('Which is an example of a trait an anti-hero might possess?', ['A protagonist who acts primarily out of self-interest rather than clear moral conviction', 'A character defined entirely by unwavering moral virtue with no flaws', 'A trait entirely unrelated to a character’s moral complexity', 'A character who has no discernible motivations of any kind'], 0),
   ('Why might readers find anti-heroes compelling despite, or because of, their moral ambiguity?', ['Their complexity can feel more psychologically realistic and prompt deeper engagement with questions of morality', 'Readers never find morally ambiguous characters compelling in any way', 'Anti-heroes always make a narrative less engaging or interesting to readers', 'This concept has no connection to how audiences respond to complex characters'], 0)]),
AF('Review: Grade 12 Advanced Functions -- Comprehensive Synthesis',
   'Grade 12 Advanced Functions comprehensive review: this lesson revisits matrices and determinants, complex numbers in polar form, sequence convergence, constrained optimization, and function symmetry across the Days 41-49 batch.',
   [('A matrix has an inverse only if its determinant is ___.', ['Not equal to zero', 'Always equal to exactly zero', 'A negative number in every single case', 'A factor entirely unrelated to whether an inverse exists'], 0),
    ('De Moivre’s Theorem provides an efficient method for ___.', ['Raising a complex number to a power', 'Only adding two complex numbers together', 'A concept unrelated to complex number operations', 'Converting a complex number into a purely real number'], 0),
    ('If a sequence does not approach any single finite value as it continues, it is said to ___.', ['Diverge', 'Converge', 'Remain perfectly constant at every term', 'Have no defined mathematical behaviour at all'], 0),
    ('An odd function’s graph is symmetric with respect to the ___.', ['Origin', 'y-axis exclusively, with no connection to the origin', 'x-axis exclusively, with no connection to the origin', 'A concept unrelated to any point of symmetry'], 0),
    ('Why is a comprehensive review valuable at the end of this unit of Advanced Functions material?', ['It reinforces how matrices, complex numbers, sequences, and function properties connect as tools for advanced problem-solving', 'These topics have no meaningful connections to each other', 'Comprehensive review provides no benefit at the end of a unit', 'Each topic must be understood with absolutely no connection to the others'], 0)]),
C('Review: Grade 12 Calculus -- Comprehensive Synthesis',
  'Grade 12 Calculus comprehensive review: this lesson revisits vector-valued functions, slope fields, power series, logistic growth models, and biological population applications across the Days 41-49 batch.',
  [('Vector-valued functions are often used to describe an object’s ___ over time.', ['Position, velocity, and acceleration', 'Colour and physical appearance only', 'A factor entirely unrelated to motion', 'Temperature exclusively, with no connection to movement'], 0),
   ('A slope field is constructed using short line segments indicating ___ at various points.', ['The slope', 'Only the colour of each individual point', 'A concept unrelated to rate of change', 'The exact numerical value of the function itself, with no connection to slope'], 0),
   ('A power series is an infinite sum involving ___.', ['Powers of a variable', 'Only a single constant term with no variable involved', 'A concept unrelated to infinite sums', 'Colours with no numerical or mathematical basis'], 0),
   ('Derivatives can be used in population modelling to represent ___.', ['Growth rates', 'Only a population’s total, unchanging size', 'A factor entirely unrelated to how a population changes', 'The exact geographic location of a population'], 0),
   ('Why is a comprehensive review valuable at the end of this unit of Calculus material?', ['It reinforces how these advanced techniques connect and expand what real-world and mathematical problems can be solved', 'These topics have no meaningful connections to each other', 'Comprehensive review provides no benefit at the end of a unit', 'Each topic must be understood with absolutely no connection to the others'], 0)]),
P('Review: Grade 12 Physics -- Comprehensive Synthesis',
  'Grade 12 Physics comprehensive review: this lesson revisits the Doppler effect, blackbody radiation, semiconductors, general relativity, quark confinement, superconductivity, resonance, orbital mechanics, and renewable energy.',
  [('The Doppler effect describes a change in observed ___ of a wave.', ['Frequency', 'Colour, with no connection to sound or wave frequency', 'Mass', 'A property entirely unrelated to waves'], 0),
   ('General relativity describes gravity as ___.', ['The curvature of spacetime caused by mass', 'A completely separate, unrelated force with no connection to mass', 'A concept entirely unrelated to the structure of the universe', 'A force that behaves identically to electromagnetism in every way'], 0),
   ('Superconductivity occurs when certain materials conduct electric current with ___.', ['Zero electrical resistance', 'Extremely high electrical resistance', 'A property entirely unrelated to electrical resistance', 'Resistance that increases continuously over time with no limit'], 0),
   ('Satellites remain in orbit through a balance between gravitational pull and their ___.', ['Forward velocity', 'Complete lack of any motion whatsoever', 'Internal temperature, with no connection to motion', 'A factor entirely unrelated to orbital mechanics'], 0),
   ('Why is a comprehensive review valuable at the end of this unit of Physics material?', ['It reinforces how these advanced physics principles connect across waves, modern physics, and applied technology', 'These topics have no meaningful connections to each other', 'Comprehensive review provides no benefit at the end of a unit', 'Each topic must be understood with absolutely no connection to the others'], 0)])]),
]

def _rebalance_answer_positions(days, seed=20260728):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g12_41_50)
    append_to(12, g12_41_50)
