#!/usr/bin/env python3
"""Grade 10 — days 16-30."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,append_to

U='https://tvolearn.com/pages/grade-10'
R='TVO Learn: Grade 10'

def E(t,s,q): return sub('English',t,s,R,U,q)
def M(t,s,q): return sub('Math',t,s,R,U,q)
def Sc(t,s,q): return sub('Science',t,s,R,U,q)
def H(t,s,q): return sub('History',t,s,R,U,q)

g10b=[
day(16,[
E('Reading: Short Fiction and the Short Story Form','Students analyse the distinctive features of the short story — economy of language, compressed plot, a single dominant effect — through close reading of examples.',[
  ('The "single effect" principle (Poe) in short fiction means ___.',['stories must have only one character','stories should produce one dominant emotional or intellectual effect in the reader, to which every element contributes','stories must end happily','only one literary device is used'],1),
  ('Economy in short fiction means ___.',['stories must be under 1000 words','every word must count — short stories cannot afford excess, so each detail, word, and image must do multiple jobs simultaneously','using only simple vocabulary','avoiding all description'],1),
  ('The epiphany in short fiction (James Joyce\'s concept) is ___.',['the climax of the action','a religious vision','a character\'s sudden, profound moment of insight or recognition that changes their understanding','the opening image'],2),
  ('Ambiguity in a short story ___.',['is always a flaw','means the story is poorly written','occurs when the story resists a single definitive interpretation, deliberately leaving room for multiple readings','only confuses readers'],2),
  ('Analysing setting in a short story involves ___.',['only noting the location','ignoring setting for plot','examining how place and time create mood, reflect character psychology, and create symbolic meaning that extends beyond the physical','only noting the weather'],2)]),
M('Quadratics: Completing the Square','Students convert quadratic equations from standard to vertex form by completing the square, then use vertex form for graphing and solving.',[
  ('Completing the square transforms ax² + bx + c into ___.',['factored form','slope-intercept form','vertex form a(x − h)² + k, revealing the vertex directly','scientific notation'],2),
  ('To complete the square for x² + 6x, you add and subtract ___.',['9 (half of 6, squared: (6/2)² = 9)','6','3','36'],0),
  ('x² + 8x + 3 in vertex form is ___.',['(x + 4)² − 13','(x + 4)² + 3','(x + 8)² − 13','(x − 4)² − 13'],0),
  ('Solve x² − 4x − 5 = 0 by completing the square.',['x = 5 or x = −1 (vertex form: (x−2)² = 9, x−2 = ±3)','x = 4 or x = −5','x = 2 or x = −3','x = 5 or x = 1'],0),
  ('Why is vertex form useful?',['It is never useful','Only for graphing horizontal lines','It directly reveals the vertex (h, k) and direction of opening, making graphing and optimisation problems much easier','It eliminates all other methods'],2)]),
Sc('Chemistry: Acids, Bases, and pH','Students examine Arrhenius acid/base definitions, the pH scale, neutralisation reactions, and indicators.',[
  ('An Arrhenius acid ___.',['accepts a proton','produces hydroxide ions in solution','produces hydrogen ions (H⁺) when dissolved in water','is always corrosive'],2),
  ('An Arrhenius base ___.',['donates a proton','produces hydrogen ions','produces hydroxide ions (OH⁻) when dissolved in water','is always a liquid'],2),
  ('A pH of 7 indicates ___.',['a strong acid','a strong base','a neutral solution (equal H⁺ and OH⁻)','a weak base'],2),
  ('A neutralisation reaction between an acid and a base produces ___.',['only water','only a salt','water and a salt','only CO₂'],2),
  ('Universal indicator or pH paper measures ___.',['temperature','concentration of the solution','the approximate pH of a solution by changing colour','only strong acids and bases'],2)]),
H('Post-War Canada: Social Change 1945-1970','Students examine the baby boom, suburbanisation, the welfare state, women\'s liberation, and shifting Canadian values in the post-WWII decades.',[
  ('Canada\'s post-WWII welfare state included ___.',['only pensions','no new social programs','the creation of unemployment insurance (1940), family allowances (1944), hospital insurance (1957), Medicare (1966), and the Canada Pension Plan (1965)','only healthcare'],2),
  ('The women\'s liberation movement in Canada in the 1960s-70s fought for ___.',['only voting rights (already won)','no significant changes','equal pay, reproductive rights, equal access to education and careers, and an end to legal and social discrimination','only workplace safety'],2),
  ('The Royal Commission on the Status of Women (1970) ___.',['found no inequalities','was irrelevant','documented systemic gender inequality in Canada and made 167 recommendations that shaped decades of policy reform','only addressed employment issues'],2),
  ('Post-WWII suburbanisation was driven by ___.',['a preference for dense urban living','a decline in car ownership','government housing policy, veterans\' benefits, affordable mortgages, and the growth of car culture — creating the suburban lifestyle that defines much of Canada today','only immigration'],2),
  ('Pierre Trudeau\'s "Just Society" vision (1968 onward) emphasised ___.',['regional favouritism','collective rights over individual rights','only economic growth','individual rights, bilingualism, multiculturalism, and the Charter — a vision of Canada as a rights-based, diverse nation rather than a British-French bicultural compact'],3)]),
]),
day(17,[
E('Writing: Voice and Style in Creative Non-Fiction','Students examine and practise creative non-fiction (personal essay, literary journalism) — writing that uses narrative and literary techniques to engage with real events and ideas.',[
  ('Creative non-fiction differs from journalism because ___.',['it invents facts','it ignores truth','it is shorter','while factually accurate, it uses literary techniques — scene-setting, character, metaphor, dialogue, and personal voice — to make real events and ideas as compelling as fiction'],3),
  ('The personal essay is ___.',['a formal academic essay in first person','only for personal stories with no ideas','always about childhood memories','a literary form that uses personal experience as a lens to explore larger intellectual, social, or philosophical questions'],3),
  ('Voice in creative non-fiction must be ___.',['formal and distant','identical to academic writing','generic and impersonal','distinctive and authentic — the writer\'s personality, perspective, and sensibility must be audible on every page'],3),
  ('Literary journalism (narrative non-fiction) researches ___.',['only one source','without interviewing people','facts, people, and events thoroughly, then presents them through narrative techniques — creating scenes, developing characters, and building a story arc from real material','only online sources'],3),
  ('The ethical obligation in creative non-fiction is ___.',['to entertain at all costs','to be as emotional as possible','to avoid research','to represent facts, people, and events truthfully — even when using literary techniques, you cannot invent or fabricate'],3)]),
M('Analytic Geometry: Circles and Equations','Students write and analyse equations of circles in the form (x−h)² + (y−k)² = r², identify centre and radius, and find intersections with lines.',[
  ('The equation (x − 3)² + (y + 2)² = 25 represents a circle with centre ___ and radius ___.',['(3, −2) and 5','(−3, 2) and 5','(3, 2) and 25','(−3, −2) and 5'],0),
  ('A circle centred at the origin with radius 7 has equation ___.',['x + y = 7','x² + y² = 49','x² + y² = 7','(x+7)² + (y+7)² = 0'],1),
  ('To find whether a point lies inside, on, or outside a circle, you ___.',['use the slope formula','compare the distance from the point to the centre with the radius','always substitute into the linear equation','use the midpoint formula'],1),
  ('A diameter of a circle has endpoints (2, 1) and (8, 5). The centre is at ___.',['(5, 3) — midpoint of the diameter','(6, 4)','(10, 6)','(3, 2)'],0),
  ('The radius of a circle with centre (1, 2) passing through (4, 6) is ___.',['5 (distance from (1,2) to (4,6) = √9+16 = 5)','7','√7','3'],0)]),
Sc('Biology: Ecosystems and Human Impact','Students examine ecosystem dynamics, human impacts on biodiversity, and conservation approaches including stewardship and sustainable development.',[
  ('A trophic cascade occurs when ___.',['the sun provides less energy','rainfall increases','a change in one trophic level (typically through predator loss or addition) causes large changes in population sizes at other levels','only in marine ecosystems'],2),
  ('Eutrophication of lakes is caused by ___.',['acid rain only','oil spills','excess nutrients (often nitrogen and phosphorus from agricultural runoff) causing algal blooms, oxygen depletion, and ecosystem collapse','only industrial pollution'],2),
  ('The concept of "ecological footprint" measures ___.',['how far you walk each day','only your carbon emissions','the land and water area required to sustain an individual\'s or population\'s consumption and absorb its waste','only food consumption'],2),
  ('Ecological restoration involves ___.',['only building new habitats','leaving ecosystems alone completely','actively rehabilitating degraded, damaged, or destroyed ecosystems by reintroducing species, removing invasives, and improving habitat quality','only replanting trees'],2),
  ('An ecosystem service is ___.',['a government program','only about food production','a service provided only by coral reefs','a benefit that humans receive from functioning ecosystems: clean water, air purification, pollination, climate regulation, flood control'],3)]),
H('Canada and International Relations: 1970-2000','Students examine Canada\'s foreign policy — peacekeeping, the G7, NAFTA, and humanitarian commitments — in the late 20th century.',[
  ('Canada\'s peacekeeping role, established by Lester Pearson\'s Suez Crisis proposal (1956), meant ___.',['Canada sending troops to fight in all wars','Canada staying neutral in all conflicts','Canada contributing military personnel to UN peacekeeping operations to separate warring parties and maintain ceasefires — earning an international reputation for peace','Canada avoiding all international commitments'],2),
  ('NAFTA (North American Free Trade Agreement, 1994) ___.',['only applied to Mexico and the US','was rejected by Canada','eliminated most tariffs on goods traded between Canada, the US, and Mexico, deeply integrating the three economies','had no impact on Canadian employment'],2),
  ('Canada\'s military involvement in Kosovo (1999) and other humanitarian interventions reflected ___.',['isolationism','neutrality in all conflicts','the R2P (Responsibility to Protect) principle — that the international community has a duty to intervene when governments commit atrocities against their own people','only NATO obligations'],2),
  ('The Chrétien government\'s decision NOT to join the US-led invasion of Iraq (2003) reflected ___.',['complete indifference to international affairs','anti-American sentiment','Canada\'s commitment to multilateralism — requiring UN Security Council authorisation before military action, even when this meant disagreeing with its closest ally','a lack of military capacity'],2),
  ('Canada\'s G7 membership reflects ___.',['Canada being the world\'s largest economy','Canada having nuclear weapons','Canada\'s status as one of the world\'s major industrialised democratic nations, with influence in global economic and security discussions','Canada being an American state'],2)]),
]),
day(18,[
E('Media Literacy: News Literacy and Misinformation','Students develop skills for critically evaluating news sources, identifying misinformation, and understanding how false information spreads.',[
  ('Misinformation differs from disinformation in that ___.',['they are identical','misinformation is always worse','misinformation is false information spread without intent to deceive, while disinformation is deliberately false or misleading information spread to deceive','disinformation is accidental'],2),
  ('A "deepfake" is ___.',['a credible news source','a type of documentary','a satire article','AI-generated video or audio that realistically depicts someone saying or doing something they never did — a growing tool for disinformation'],3),
  ('The SIFT method for evaluating sources stands for ___.',['Search, Investigate, Find, Trust','Stop, Investigate the source, Find better coverage, Trace claims — a practical framework for quickly assessing online information credibility','Source, Integrity, Fact, Truth','Standard, Internet, Facts, Testing'],1),
  ('Filter bubbles in social media refer to ___.',['blocking spam','only seeing news','algorithms that show you content matching your existing preferences and beliefs, creating an information environment that reinforces your worldview and filters out contradicting perspectives','parental controls'],2),
  ('Lateral reading for fact-checking means ___.',['reading a page very carefully from top to bottom','relying on the website\'s "about" page','never reading news online','opening multiple new tabs to look for what other credible sources say about this source or claim, rather than judging the source only from the source itself'],3)]),
M('Functions: Introduction to Polynomial Functions','Students are introduced to polynomial functions — degree, end behaviour, zeros, and graphical features — as a bridge from Grade 10 quadratics to Grade 11 functions.',[
  ('A polynomial function of degree n has ___.',['only n terms','exactly n roots always','a graph that crosses the x-axis n times always','at most n real zeros (x-intercepts), and its end behaviour is determined by the leading term'],3),
  ('The end behaviour of a polynomial is determined by ___.',['all terms equally','the constant term','the leading term (the term with the highest degree and its coefficient)','the number of terms'],2),
  ('A cubic function (degree 3) with positive leading coefficient has end behaviour: ___.',['rises left, falls right','falls both directions','rises both directions','falls left, rises right'],3),
  ('The zeros of a polynomial function are ___.',['the y-intercepts','the slope values','the x-values where f(x) = 0 — the x-intercepts of the graph','the coefficient values'],2),
  ('A polynomial function y = (x − 2)(x + 1)(x − 4) has x-intercepts at ___.',['x = 2, 1, 4','x = −2, 1, −4','x = 2, −1, 4','x = 0, 2, −1, 4'],2)]),
Sc('Physics: Nuclear Energy and Radiation Safety','Students examine nuclear fission reactors, CANDU reactor technology, radioactive waste management, and radiation safety.',[
  ('The CANDU (CANada Deuterium Uranium) reactor is notable because ___.',['it uses enriched uranium','it was built in the US','it produces no radiation','it uses natural (unenriched) uranium as fuel and heavy water (D₂O) as a moderator — a uniquely Canadian nuclear technology'],3),
  ('A nuclear reactor moderator ___.',['splits uranium atoms','provides the reaction\'s fuel','transfers heat to a generator','slows neutrons to the speed needed to sustain a fission chain reaction — in CANDU, heavy water is the moderator'],3),
  ('Radioactive waste management is challenging because ___.',['nuclear waste is harmless','it decays in days','only liquid waste is produced','high-level radioactive waste remains dangerous for thousands of years, requiring secure long-term storage in geological repositories'],3),
  ('Radiation protection uses the ALARA principle, which means ___.',['always leave all radiation alone','radioactive materials need no protection','As Low As Reasonably Achievable — minimise exposure through time, distance, and shielding','all radiation is immediately fatal'],0),
  ('A significant advantage of nuclear power over fossil fuels is ___.',['no waste produced','no safety concerns','it produces no air pollution and very low greenhouse gas emissions during operation, providing large amounts of reliable baseload electricity','it uses renewable fuel'],2)]),
H('Social Movements: Civil Rights and Equality in Canada','Students examine the civil rights struggles of Black Canadians, the women\'s movement, LGBTQ+ rights, and disability rights in the 20th-21st century.',[
  ('The Viola Desmond case (1946) is significant because ___.',['it involved a legal dispute about property','it was about voting rights','she successfully argued her case','a Black Nova Scotian woman was arrested for refusing to leave a whites-only section of a movie theatre — her case became a landmark in the civil rights history of Black Canadians'],3),
  ('The Nova Scotia Human Rights Act (1963) and the Canadian Human Rights Act (1977) were ___.',['purely symbolic','unenforceable','legislation that prohibited discrimination in public life on grounds of race, religion, sex, and other grounds, providing legal tools to fight discrimination','only about employment'],2),
  ('LGBTQ+ rights milestones in Canada include ___.',['no significant legal changes','only the decriminalisation of homosexuality','only marriage equality','decriminalisation of homosexuality (1969), addition of sexual orientation to the Charter (1995 SCC ruling), and equal marriage rights nationally (2005)'],3),
  ('The disability rights movement in Canada achieved ___.',['no legal recognition','only charitable support','recognition in the Charter (Section 15), the Accessibility for Ontarians with Disabilities Act (2005), and the Accessible Canada Act (2019)','only building code changes'],2),
  ('A common pattern across all these civil rights movements is ___.',['change was granted voluntarily by governments','each movement operated in isolation','courts did all the work','marginalised groups had to organise, advocate, and sometimes challenge law in courts over decades before rights were recognised and enforced'],2)]),
]),
day(19,[
E('Shakespeare: A Midsummer Night\'s Dream or Julius Caesar','Students study a second Shakespeare play, analysing dramatic structure, language, and themes with greater independence and sophistication than in Grade 9.',[
  ('In Shakespeare\'s comedies, the central disruption is ___.',['a tragic death','a political crisis','a major war','a social or romantic disorder that is resolved by the play\'s end — usually through marriage or reconciliation'],3),
  ('In Julius Caesar, Brutus\'s fatal flaw is arguably ___.',['cowardice','greed','ambition','an idealism that blinds him to political realities and allows him to be manipulated by Cassius'],3),
  ('Antony\'s funeral speech ("Friends, Romans, countrymen") is dramatically effective because ___.',['he directly insults the conspirators','he praises Brutus and the conspirators throughout but subtly turns the crowd against them through irony — a masterclass in rhetoric','he reveals the assassination plot','he appeals only to reason'],1),
  ('The theme of appearance vs. reality in Shakespeare is explored through ___.',['characters who are always honest','only supernatural elements','disguise, self-deception, political manipulation, and the gap between public persona and private reality — characters are often not what they seem','only the comedies'],2),
  ('Studying Shakespeare with greater independence means ___.',['only reading sparknotes','the teacher explains everything','making your own interpretive choices — selecting which scenes to focus on, forming your own thematic arguments, and supporting them with textual evidence','avoiding personal interpretation'],2)]),
M('Review: Functions, Geometry, and Systems','Students consolidate Grade 10 mathematics — quadratics, trigonometry, analytic geometry, linear systems, and an introduction to polynomial functions.',[
  ('The parabola y = −3(x + 2)² + 7 has vertex ___ and opens ___.',['(2, 7) downward','(−2, 7) downward','(−2, 7) upward','(2, −7) upward'],1),
  ('Find the angle in a triangle where cos A = (9 + 25 − 16)/(2 × 3 × 5) = 18/30.',['A ≈ 53°','A = 90°','A ≈ 37°','A = 60°'],0),
  ('The circle (x + 1)² + (y − 3)² = 16 has centre ___ and radius ___.',['(1, −3) and 4','(−1, 3) and 16','(−1, 3) and 4','(1, 3) and 4'],2),
  ('Solve: 3x² − x − 2 = 0',['x = 1 and x = −2/3','x = −1 and x = 2/3','x = 1 and x = 2/3','x = −1 and x = −2/3'],0),
  ('A polynomial y = x(x − 3)(x + 2) has zeros at ___.',['x = 0, 3, −2','x = 0, −3, 2','x = 1, 3, −2','x = 3 and x = −2 only'],0)]),
Sc('Science: Energy Systems and Sustainability','Students examine Ontario\'s energy mix, the transition to renewable energy, and the science behind solar, wind, hydro, and nuclear power.',[
  ('Ontario\'s electricity mix includes ___.',['mostly coal','only nuclear','mostly imported US electricity','a combination of nuclear (~60%), hydro (~24%), wind and solar (~9%), and gas — making it one of the lowest-carbon grids in the world'],3),
  ('Solar photovoltaic (PV) cells convert ___.',['heat directly to electricity','chemical energy to electricity','wind energy to electricity','light (photons) to electricity via the photovoltaic effect in semiconductor materials'],3),
  ('Wind turbines convert ___.',['solar energy to wind','chemical energy to electricity','the kinetic energy of moving air to rotational mechanical energy, which drives a generator to produce electricity','water pressure to electricity'],2),
  ('Hydroelectric power generates electricity by ___.',['burning water','using solar panels on water','harnessing the gravitational potential energy of falling water to spin turbines connected to generators','splitting water molecules'],2),
  ('A major challenge of renewable energy transition is ___.',['renewables produce too much electricity','nuclear is already renewable','fossil fuels will run out soon','intermittency — solar produces no electricity at night, and wind is variable — requiring energy storage solutions like batteries or pumped hydro'],3)]),
H('Canada\'s Constitution and Federalism','Students examine the Canadian Constitution — the division of powers, federalism, constitutional amendments, and ongoing debates about the constitutional order.',[
  ('The division of powers in the Constitution Act (1867) allocates ___.',['all power to provinces','all power to the federal government','certain powers exclusively to the federal government (e.g., defence, criminal law), others to provinces (e.g., education, health care), and some to both (concurrent)','powers only based on tradition'],2),
  ('Section 91 lists federal powers, which include ___.',['education and hospitals','property and civil rights','criminal law, banking, currency, navigation, and trade — matters of national concern','only defence and foreign affairs'],2),
  ('Section 92 lists provincial powers, which include ___.',['criminal law and banking','defence and foreign policy','property and civil rights, hospitals, education, and natural resources within the province','taxation of all kinds'],2),
  ('Intergovernmental transfers (e.g., Equalization) redistribute ___.',['tax dollars from provinces to the federal government','money between private businesses','money from wealthier provinces (through federal taxation) to provinces with lower fiscal capacity, enabling comparable public services across Canada','only to Quebec'],2),
  ('A constitutional amendment in Canada typically requires ___.',['only a federal majority vote','only a referendum','a provincial legislature vote alone','the consent of Parliament and at least 7 of 10 provinces representing 50% of the population — the "7/50 formula"'],3)]),
]),
day(20,[
E('Independent Novel Study: Final Essay','Students write a full independent analytical essay on their novel, demonstrating the full range of Grade 10 literary analysis skills.',[
  ('The most important quality of a Grade 10 analytical essay is ___.',['length','number of quotations','correct spelling','a clear, arguable thesis supported by well-chosen evidence and analytical reasoning that connects evidence to argument'],3),
  ('Literary analysis differs from plot summary in that ___.',['plot summary is more valuable','they are identical','literary analysis requires less detail','literary analysis asks "how" and "why" — examining the author\'s choices and their effects — while plot summary only describes "what happens"'],3),
  ('An effective concluding paragraph ___.',['just repeats the introduction','leaves the reader with nothing new','adds an entirely new argument','synthesises the essay\'s argument, extends the thesis to a larger significance, and leaves the reader with a new insight or question'],3),
  ('Revision of an essay differs from proofreading in that ___.',['they are the same thing','only spelling matters','revision is for surface errors only','revision addresses big-picture issues (argument, structure, evidence, analysis) while proofreading addresses surface errors (grammar, spelling, punctuation)'],3),
  ('Receiving and using feedback means ___.',['accepting all suggestions uncritically','rejecting all external input','writing without revision','reading feedback carefully, asking what specific concerns underlie the comments, and making deliberate choices about what to change and why'],3)]),
M('Introduction to Functions: Domain, Range, Notation','Students are introduced to functions formally — function notation f(x), domain, range, mapping diagrams, and identifying functions vs. relations.',[
  ('A function is a relation in which ___.',['every y-value maps to one x-value','every x-value maps to exactly one y-value','all x and y values are positive','every ordered pair is (x, x)'],1),
  ('The domain of a function is ___.',['the set of all output values','the graph of the function','the set of all possible input values (x-values)','the rule of the function'],2),
  ('The range of a function is ___.',['the set of all input values','the equation of the function','the set of all possible output values (y-values)','the domain reflected'],2),
  ('f(x) = 3x − 2. Find f(4).',['10','14','12','6'],0),
  ('The vertical line test determines ___.',['the domain','the range','the y-intercept','whether a graph represents a function — if any vertical line intersects the graph more than once, it is not a function'],3)]),
Sc('Chemistry: Organic Chemistry Introduction','Students are introduced to organic compounds — hydrocarbons (alkanes, alkenes, alkynes), functional groups, and their importance in medicine, materials, and environment.',[
  ('Organic chemistry is the study of ___.',['all chemical reactions','only natural substances','only laboratory-made substances','compounds containing carbon — the chemistry of life and of most fuels, medicines, plastics, and synthetic materials'],3),
  ('Hydrocarbons are compounds containing only ___.',['carbon and oxygen','carbon and nitrogen','carbon and hydrogen','carbon only'],2),
  ('Alkanes are hydrocarbons with ___.',['at least one double bond','at least one triple bond','only single carbon-carbon bonds — the simplest hydrocarbon family, e.g., methane, ethane, propane','aromatic rings'],2),
  ('Alkenes contain ___.',['only single bonds','at least one triple C-C bond','at least one double carbon-carbon bond (C=C), making them more reactive than alkanes','only aromatic rings'],2),
  ('Functional groups in organic chemistry are ___.',['always carbon only','specific atoms or groups of atoms that determine the characteristic chemical reactions of a molecule (e.g., –OH = alcohol, –COOH = carboxylic acid)','only found in natural compounds','only in plastics'],1)]),
H('The Environment and Politics: Canada\'s Climate Debate','Students examine the political dimensions of climate change in Canada — carbon pricing, oil sands, Indigenous rights, and intergenerational justice.',[
  ('Canada\'s carbon pricing system (federal carbon tax/backstop) ___.',['gives money to oil companies','increases government profit directly','has faced no political opposition','puts a price on carbon emissions to incentivise reduction, with proceeds returned to Canadians as rebates — controversial politically, especially in fossil fuel-dependent provinces'],3),
  ('Alberta\'s oil sands are significant because ___.',['they are small and economically minor','they represent a conflict between environmental and economic interests — a massive economic resource and employer that also produces some of the world\'s most GHG-intensive oil, intersecting with Indigenous rights issues','they are already shut down','they are internationally praised universally'],1),
  ('Intergenerational justice in the climate debate means ___.',['only current generations matter','older generations should pay all costs','current decisions about emissions and fossil fuel development will disproportionately affect future generations who had no vote in those decisions','young people have no role in the debate'],2),
  ('Indigenous peoples are disproportionately affected by climate change because ___.',['they live in cities mostly','they are too small a population to be significantly affected','many Indigenous communities live in northern and coastal regions most vulnerable to climate impacts (permafrost thaw, sea level rise, disruption of traditional hunting/fishing/gathering)','they have caused the most emissions'],2),
  ('Climate litigation — suing governments for inadequate climate action — is ___.',['not happening in Canada','always unsuccessful','only a European tactic','an emerging legal strategy in Canada and globally, with youth-led cases challenging governments\' insufficient climate policies under constitutional rights frameworks'],3)]),
]),
day(21,[
E('Media Creation: Short Film or Podcast Episode','Students plan, script, and produce a short media piece (podcast episode or video essay) on a literary or social topic, applying media literacy and production skills.',[
  ('A video essay differs from a documentary in that ___.',['it uses no research','it is always shorter','it is fictional','it is usually narrated by a single voice presenting a personal analytical argument, often directly to camera — blending documentary and persuasive essay forms'],3),
  ('Pre-production in media making includes ___.',['only editing','only recording','only publishing','all the planning work before recording begins: research, scripting, storyboarding, location scouting, and equipment preparation'],3),
  ('A strong script for a media piece ___.',['is identical to a written essay','is read word for word with no improvisation','is optional','serves as a guide, with natural speech rhythms, clear structure, and room for the speaker\'s personality to come through'],3),
  ('Ethical considerations in creating media about real people or communities include ___.',['no ethics apply in student media','only copyright issues matter','informed consent, accurate representation, avoiding harm, and being especially careful with vulnerable communities whose stories you do not share','only privacy in social media'],2),
  ('Publishing a media piece to a real audience (school website, YouTube) means ___.',['no additional responsibility','only technical quality matters','all facts must be perfect','it is a public act with real consequences — accuracy, fairness, and quality matter far more than when the audience is only your teacher'],3)]),
M('Quadratics and Functions: Consolidation','Students review and consolidate Grade 10 quadratic and function concepts, preparing for Grade 11 Functions.',[
  ('Convert y = x² − 6x + 11 to vertex form.',['y = (x − 3)² + 2','y = (x + 3)² − 11','y = (x − 6)² + 2','y = (x − 3)² − 9 + 11 = (x−3)²+2'],0),
  ('A function has domain {x ∈ ℝ | x ≠ −2}. What type of function likely has this restriction?',['A linear function','A polynomial function','A rational function with denominator (x + 2)','A quadratic function'],2),
  ('f(x) = x² − 4 and g(x) = 2x + 1. Find f(g(2)).',['f(5) = 21','f(2) + g(2) = 5','g(f(2)) = 1','f(5) = 25'],0),
  ('The zeros of f(x) = x² − x − 6 are ___.',['x = 2 and x = −3','x = −2 and x = 3','x = 3 and x = 2','x = 6 and x = −1'],1),
  ('A quadratic with vertex (2, −3) and passing through (0, 1) has a = ___.',['a = 1','a = −1','a = 4','a = 0'],0)]),
Sc('Science: Human Health and Biotechnology','Students examine how scientific knowledge is applied in medicine — vaccines, antibiotics, gene therapy, and CRISPR — and the ethical questions raised.',[
  ('mRNA vaccines (like those developed for COVID-19) work by ___.',['injecting a weakened virus','injecting DNA into the nucleus','using a live pathogen','delivering messenger RNA instructions that cause your cells to produce a viral protein, training your immune system to recognise and fight the real pathogen'],3),
  ('Antibiotic resistance is a growing problem because ___.',['antibiotics are now weaker','bacteria have evolved to survive antibiotic treatment, often due to overuse or misuse of antibiotics — a major public health threat requiring careful prescribing and new antibiotic development','viruses have become resistant','resistance only affects hospitals'],1),
  ('CRISPR-Cas9 genome editing allows ___.',['only reading DNA','only destroying cells','precise cutting and editing of DNA sequences at targeted locations, enabling potential treatments for genetic diseases and raising ethical questions about germline editing and enhancement','only adding genes'],2),
  ('Personalised medicine uses ___.',['the same treatment for all patients','only natural remedies','no data from patients','genetic and other biological data to tailor medical treatments to individual patients, improving effectiveness and reducing side effects'],3),
  ('The ethical principle of informed consent in medicine means ___.',['doctors decide what is best','patients must accept recommended treatment','patients have the right to receive complete, understandable information about a proposed treatment or research study before deciding whether to participate','only applies in research'],2)]),
H('Canada Today: Contemporary Challenges','Students examine contemporary challenges facing Canada: reconciliation, climate, housing, inequality, and democratic participation.',[
  ('Canada\'s housing crisis affects young Canadians because ___.',['housing is affordable everywhere','only major cities have issues','the crisis is limited to coastal cities','rapidly rising home prices and rents in most Canadian cities have made homeownership essentially unattainable for most people your age, raising fundamental questions about intergenerational equity'],3),
  ('Income inequality in Canada has ___.',['decreased dramatically','remained perfectly stable','has no effect on social outcomes','grown significantly since the 1980s, with the top income earners capturing an increasing share of income growth while wages for middle and lower income Canadians have stagnated in real terms'],3),
  ('Truth and Reconciliation in Canada is ___.',['complete','only about acknowledging the past','not relevant to young Canadians','an ongoing process of healing, redress, and structural change — including implementation of the 94 Calls to Action, land rights resolution, and building genuine nation-to-nation relationships'],3),
  ('Declining voter turnout (especially among youth) is concerning because ___.',['democracy works fine without participation','politicians will decide what young people need','youth issues are always addressed regardless','when young people disengage from formal politics, their interests are underrepresented in policy decisions that will affect their lives for decades'],3),
  ('A genuinely engaged Grade 10 citizen can ___.',['only vote in 3-6 years','do nothing meaningful until they\'re older','change nothing at the local level','stay informed, discuss issues critically, join youth advocacy groups, contact elected officials, participate in public consultations, and model the democratic citizenship Canada needs'],3)]),
]),
day(22,[
E('Writing: Final Culminating Task','Students complete a major writing task — analytical essay, creative work, or multimodal project — that demonstrates the full range of Grade 10 English skills.',[
  ('A culminating writing task should demonstrate ___.',['only your vocabulary knowledge','only your grammar skills','a wide range of skills learned over the year: analytical thinking, thesis development, evidence use, stylistic control, and sophisticated engagement with ideas','only your length capabilities'],2),
  ('Self-editing a major piece means ___.',['fixing only spelling errors','asking a friend to rewrite it','reading aloud to catch awkward phrasing','systematically reviewing for argument clarity, evidence quality, analytical depth, cohesion, and then surface errors — in that order'],3),
  ('A strong culminating essay demonstrates intellectual maturity by ___.',['avoiding complex sentences','using only safe, obvious arguments','acknowledging complexity — engaging with nuance, counterarguments, and the limitations of your own interpretation, rather than oversimplifying','only using approved ideas'],2),
  ('Publishing or presenting a culminating piece to a real audience ___.',['only stresses students','is irrelevant to the work\'s quality','makes writing more meaningful and develops genuine communication skills by creating authentic purpose and accountability beyond the classroom','should be avoided'],2),
  ('Reflecting on a year of writing development means ___.',['only comparing grades','ignoring what you\'ve learned','recognising that writing is a thinking skill — as your writing has improved, so has your ability to form, develop, and communicate complex ideas','only noting what still needs work'],2)]),
M('Exam Preparation: Grade 10 Mathematics Review','Students review all major Grade 10 math concepts for assessment readiness.',[
  ('Solve: x² + 2x − 15 = 0',['x = 3 and x = −5','x = −3 and x = 5','x = 5 and x = −5','x = 3 and x = 5'],0),
  ('In triangle ABC, a = 10, b = 7, B = 30°. Use the Sine Law to find sin A.',['sin A = 10 sin30° / 7 = 5/7 ≈ 0.714','sin A = 7/10','sin A = sin30°','sin A = 1'],0),
  ('The midpoint of (−4, 6) and (2, −2) is ___.',['(−1, 2)','(−2, 4)','(−3, 4)','(1, −2)'],0),
  ('A parabola has zeros at x = −1 and x = 5 and passes through (0, −5). Find a.',['a = 1','a = −1','a = 5','a = −5'],0),
  ('If f(x) = 2x² − 3, find f(−2).',['f(−2) = 2(4) − 3 = 5','f(−2) = −11','f(−2) = 4 − 3 = 1','f(−2) = −4 − 3 = −7'],0)]),
Sc('Science: Review and Synthesis','Students synthesise all three Grade 10 science strands — chemistry, biology, and physics — and their interconnections.',[
  ('Chemical bonding concepts explain ___.',['only why acids are sour','physical, biological, and chemical properties of all substances: why water is liquid at room temperature, why DNA has a double helix, why metals conduct electricity','only laboratory reactions','only ionic compounds'],1),
  ('Evolution (biology) connects to chemistry through ___.',['no connection exists','only fossil records','mutation being a chemical process — changes in DNA base sequences caused by chemical damage, replication errors, or mutagens lead to the genetic variation on which natural selection acts','only protein structure'],2),
  ('Newton\'s laws and kinematics explain ___.',['only car crashes','only sports','both mechanical motion at the human scale and, with quantum modifications, the behaviour of electrons in atoms — physics underlies both chemistry and biology','only space travel'],2),
  ('Climate change is a Grade 10 Science topic because ___.',['it only involves biology','it only involves physics','it only involves chemistry','it requires all three strands: the chemistry of greenhouse gases, the biology of ecosystem impacts, and the physics of heat transfer and atmospheric energy balance'],3),
  ('The most important lesson from Grade 10 Science is ___.',['memorising all the formulas','science is a collection of fixed facts','only chemistry is important','science is a way of thinking — a method for using evidence, model-building, and testing to understand the world, which applies across disciplines and to the decisions of everyday life'],3)]),
H('Grade 10 History: Looking Back and Forward','Students synthesise Grade 10 history and connect it to their emerging understanding of citizenship and their role in the future of Canada.',[
  ('The thread connecting Canada\'s WWII experience, the Charter, and reconciliation is ___.',['only conflict','only politics','the ongoing expansion of who is recognised as a full, rights-bearing member of the Canadian community — from enfranchising women and fighting fascism to protecting minority rights and acknowledging Indigenous sovereignty','only economic growth'],2),
  ('Canada\'s relationship with the United States, seen across the 20th century, is best described as ___.',['complete Canadian independence','identical interests always','complete American dominance','deep economic and cultural integration combined with persistent efforts to maintain a distinct Canadian identity — a relationship of both partnership and ongoing negotiation of sovereignty'],3),
  ('The evolution of immigration policy from exclusion to multiculturalism shows ___.',['Canada was always multicultural','policy never matters','change only happens through demographics','policy reflects the values and power dynamics of its time — and can change dramatically when social movements, court decisions, and political will align'],2),
  ('Climate change is a historical issue because ___.',['it only started recently','it has nothing to do with history','it only matters to scientists','its causes are rooted in historical decisions about industrialisation and fossil fuels, and its solutions require understanding the history of international cooperation, Indigenous knowledge, and political economy'],3),
  ('As a Grade 10 student completing this course, your most important takeaway is ___.',['dates and facts about WWII','how to memorise the Constitution','only Quebec history matters','that history is not about the past — it is about understanding how we got here and taking responsibility for where we go next'],3)]),
]),
day(23,[
E('Reading and Writing: Synthesis Task','Students read two or three related texts on a contemporary issue and write a synthesis essay that integrates ideas across sources with an original argument.',[
  ('Synthesising sources means ___.',['summarising each source separately','using only one source at a time','copying from all sources equally','building a unified, original argument that draws on multiple sources — connecting, comparing, and using them to support your own analytical position'],3),
  ('A synthesis essay differs from a research essay in that ___.',['it uses no sources','it is always shorter','it requires original research','it focuses on connecting and integrating a given set of sources rather than independently researching a topic, though both require original analytical argument'],3),
  ('When sources disagree, a synthesis essay should ___.',['only use the sources that agree with your thesis','ignore the disagreement','present only one side','acknowledge and explore the tension between sources, using it to develop a more nuanced argument that accounts for the complexity'],3),
  ('Original voice in synthesis means ___.',['copying the authors\' styles','avoiding analysis','using the authors\' words only','your thesis and argument are your own — sources provide evidence, but you are the author of the argument'],3),
  ('The most common weakness in synthesis writing is ___.',['too much original argument','over-reliance on quotations','too many sources','the "laundry list" structure — listing what each source says without building a coherent, unified analytical argument that advances your own thesis'],3)]),
M('Trigonometry Extension: Sine and Cosine Graphs','Students explore the graphs of y = sinx and y = cosx, identifying amplitude, period, phase shift, and vertical shift for transformations.',[
  ('The period of y = sinx is ___.',['180°','90°','360° (or 2π radians) — the function completes one full cycle every 360°','720°'],2),
  ('The amplitude of y = 3sin(x) is ___.',['3 — the maximum displacement from the midline','9','1/3','1'],0),
  ('In y = sin(2x), the period is ___.',['720°','360°','90°','180° — multiplying x by 2 halves the period'],3),
  ('A phase shift of 30° in y = cos(x − 30°) means ___.',['the graph shifts up 30°','the graph shifts left 30°','the graph compresses horizontally','the graph shifts right 30°'],3),
  ('The vertical shift in y = sinx + 2 is ___.',['the period changes to 2','the amplitude is 2','the graph shifts up 2 units','the frequency doubles'],2)]),
Sc('Physics: Modern Physics Concepts','Students are introduced to key modern physics concepts: quantum theory, the photoelectric effect, the wave-particle duality of light, and relativistic effects.',[
  ('The photoelectric effect showed that ___.',['light is purely a wave','electrons have no mass','light behaves as particles (photons) — each photon carries energy proportional to its frequency, and can eject electrons from metal surfaces if its energy exceeds a threshold','electricity can produce light'],2),
  ('Wave-particle duality means ___.',['waves and particles are unrelated','only light has this duality','quantum objects like electrons and photons exhibit both wave-like and particle-like properties depending on how they are observed or measured','all objects behave this way at human scale'],2),
  ('Einstein\'s E = mc² means ___.',['energy is always conserved','mass and energy are different and unrelated','matter and energy are equivalent — mass can be converted to energy (as in nuclear reactions) and energy to mass','only applies in nuclear physics'],2),
  ('Quantum mechanics is necessary because ___.',['classical physics explains everything','atoms follow the same rules as baseballs','there are no laws at atomic scale','classical physics fails to describe the behaviour of particles at atomic and subatomic scales — quantum mechanics provides the correct framework'],3),
  ('The uncertainty principle (Heisenberg) states ___.',['scientists are not precise enough','measurement is always perfect','position and momentum can always both be determined precisely','you cannot precisely know both the position and momentum of a particle simultaneously — a fundamental limit of nature, not of measurement technology'],3)]),
H('Historical Thinking: Applying Concepts','Students apply the six historical thinking concepts to a contemporary Canadian issue, demonstrating the relevance of historical reasoning to present-day problems.',[
  ('Applying historical significance to a contemporary issue means asking ___.',['is this event recent?','is this in the news?','how many people are affected?','why does this matter? Who is affected, and what long-term consequences might it have — the same criteria we use to assess historical events'],3),
  ('Using cause and consequence thinking about climate policy means ___.',['only looking at economic causes','assuming one cause','only considering future consequences','tracing the multiple causes of current emissions, the complex consequences of different policy choices, and the interconnected systems that make climate change both a cause and consequence of other issues'],3),
  ('Continuity and change thinking reveals that some aspects of inequality in Canada ___.',['have completely disappeared','are entirely new','are unrelated to history','have persisted over generations (systemic racism, Indigenous dispossession) while others have changed significantly — understanding both helps identify what still needs to change'],2),
  ('Historical perspective taking applied to contemporary debates means ___.',['only studying the past','avoiding taking any position','caring only about your own perspective','understanding that different people hold different values and see the same issue through different historical experiences — this builds empathy and better problem-solving'],3),
  ('The ethical dimension of historical thinking applied today means ___.',['judging only historical actors','avoiding all moral judgment','not caring about outcomes','recognising that we have responsibilities arising from historical injustices, and that our own choices about how to respond to these injustices are themselves historical and ethical decisions'],3)]),
]),
day(24,[
E('Literature: A Non-Western Perspective','Students read and analyse a novel or collection of short stories from a non-Western tradition (translated or originally in English), examining cultural context and literary universality.',[
  ('Why study literature from non-Western traditions?',['Only Western literature has universal themes','Non-Western literature is too difficult','World literature uses only different settings','World literature expands our understanding of universal human experiences while also challenging Western assumptions about how stories work, what values matter, and whose experiences are central'],3),
  ('When reading literature in translation, it is important to acknowledge ___.',['translations are always perfect','the original text is irrelevant','no meaning is lost in translation','that translation always involves interpretation — choices made by the translator shape the text, and some nuances of the original language and culture may be altered or lost'],3),
  ('Cultural context helps readers understand ___.',['only surface details','nothing important','only historical facts','references, values, and narrative conventions that may be unfamiliar — without context, important meanings may be missed or misread from a Western perspective'],2),
  ('Universal themes in world literature include ___.',['only themes from each culture','no shared human experiences across cultures','unique themes in each tradition','love, loss, justice, identity, family, power, and what it means to be human — themes that transcend culture even as they are expressed through culturally specific stories'],3),
  ('Avoiding cultural projection means ___.',['learning nothing from other cultures','reading non-Western literature as confirmation of Western views','interpreting cultural differences as deficiencies from a Western norm','reading literature from other traditions on its own terms, with curiosity about difference rather than measuring it against Western literary standards'],3)]),
M('Exam Readiness: Problem Solving and Communication','Students practise explaining their mathematical reasoning clearly in writing — an essential skill for senior math assessments.',[
  ('Mathematical communication means ___.',['only showing numerical steps','avoiding words in solutions','always using symbols only','clearly explaining your reasoning in words alongside mathematical work — describing what you did and why, so a reader can follow your thinking'],3),
  ('When solving a word problem, the first step is ___.',['doing the calculation immediately','drawing a picture','defining variables and restating what is given and what is being asked — this prevents errors and demonstrates clear thinking','checking the answer first'],2),
  ('Checking reasonableness of an answer means ___.',['only checking arithmetic','recalculating the same way','always getting a decimal','asking whether your answer makes sense in the context of the problem — a negative time, a probability above 1, or an impossibly large distance signal an error'],0),
  ('Partial credit on exams usually requires ___.',['a correct final answer only','showing only the setup','all correct or nothing','showing all work, even if the final answer is wrong — examiners award marks for correct method and reasoning'],3),
  ('The most effective exam preparation for math is ___.',['reading the textbook','memorising formulas only','re-reading your notes','practising problems under time pressure, then reviewing errors carefully to understand what went wrong — not just redoing problems you already know'],3)]),
Sc('Science: Career Connections','Students explore STEM careers and how Grade 10 science knowledge connects to post-secondary pathways and the workforce.',[
  ('Environmental science careers connect to ___.',['only biology from Grade 10','only physics','a combination of biology (ecosystems), chemistry (pollution analysis), and physics (atmospheric science) from Grade 10, plus mathematics, geography, and policy','only laboratory work'],2),
  ('Biomedical engineering connects to ___.',['only physics','only chemistry','biology (cell and human biology) and physics (mechanics, fluids, imaging) and chemistry (biomaterials)','only medicine'],2),
  ('Data science, a rapidly growing field, requires ___.',['only computer science','only mathematics','no science background','strong mathematical foundations (statistics, algebra) combined with domain knowledge in whatever field the data is from — including science fields'],3),
  ('Clean energy technology careers require knowledge of ___.',['only electrical engineering','only economics','physics (electricity, thermodynamics), chemistry (batteries, fuel cells), and materials science — all rooted in Grade 10 science concepts','only environmental science'],2),
  ('The most transferable skill from Grade 10 science to any career is ___.',['memorising formulas','lab technique','only knowing specific content','evidence-based reasoning — the ability to define a problem, gather data, analyse it critically, and draw justified conclusions'],3)]),
H('Reflection: My Canada','Students write a personal reflection on what Canada means to them, connecting historical learning to personal identity and future citizenship commitments.',[
  ('A thoughtful reflection on Canadian identity should ___.',['only celebrate Canada','only criticise Canada','remain neutral on all issues','acknowledge both Canada\'s genuine achievements and its significant failures, and consider what kind of Canada you want to help build'],3),
  ('Canada\'s history of Indigenous dispossession, Japanese-Canadian internment, and racial exclusion in immigration policy teaches ___.',['that Canada has always been perfect','that these were unavoidable','that only some Canadians are responsible for the past','that good intentions and democratic structures are not sufficient protection against injustice — active vigilance and institutional accountability are always needed'],3),
  ('The most important thing young Canadians can do for democracy is ___.',['only vote when old enough','leave politics to older generations','remain politically uninformed','stay engaged, informed, and civically active throughout their lives — democracy atrophies without participation'],3),
  ('Canada\'s commitment to diversity and human rights is ___.',['perfectly achieved','irrelevant to daily life','a fixed achievement that needs no further work','an ongoing aspiration that requires constant attention, especially as new communities arrive and old inequalities persist'],3),
  ('My Canada is ___.',['already perfect','not my responsibility to improve','only for people born here','a work in progress — and you are part of its continuing story, with both the right and the responsibility to participate in shaping what it becomes'],3)]),
]),
day(25,[
E('Language Conventions: Grammar for Academic Writing','Students master advanced grammar for academic writing: subordination, parallelism, active vs. passive voice, avoiding wordiness, and punctuation (semicolons, colons, dashes).',[
  ('A semicolon can join ___.',['a dependent and independent clause','any two phrases','two independent clauses that are closely related in meaning — stronger than a comma, weaker than a period','a list of only two items'],2),
  ('A colon is used to ___.',['end a sentence','separate subjects from verbs','introduce a list, explanation, or quotation that follows a complete independent clause','before every quotation'],2),
  ('An em dash (—) is used to ___.',['indicate a range of numbers','replace all commas','only in informal writing','add emphasis or set off supplementary information — it creates a stronger pause than commas and more informality than parentheses'],3),
  ('Eliminating wordiness means ___.',['removing all adjectives','using simpler vocabulary','making essays shorter overall','removing unnecessary words without losing meaning: "due to the fact that" → "because"'],3),
  ('Parallelism errors in lists mean ___.',['the list has too many items','items are alphabetical','mixing grammatical forms: "She likes swimming, to run, and hikes" — all items must be in the same form: "swimming, running, and hiking"','the list is too long'],2)]),
M('Functions and Graphs: Transformations','Students apply transformations (stretch, compress, reflect, shift) to parent functions, building intuition for Grade 11 Functions.',[
  ('The transformation y = f(x) + 3 shifts the graph ___.',['right 3 units','down 3 units','left 3 units','up 3 units'],3),
  ('The transformation y = f(x − 2) shifts the graph ___.',['up 2 units','left 2 units','right 2 units — replacing x with (x − c) shifts the graph RIGHT by c','down 2 units'],2),
  ('The transformation y = −f(x) ___.',['shifts the graph down','shifts the graph right','compresses the graph horizontally','reflects the graph over the x-axis (negates all y-values)'],3),
  ('The transformation y = f(2x) ___.',['stretches horizontally by 2','shifts right by 2','reflects over the y-axis','compresses horizontally by a factor of 2 (each x-value is halved to get the same output)'],3),
  ('The transformation y = 2f(x) ___.',['compresses vertically','stretches the graph horizontally','shifts up 2','stretches vertically by a factor of 2 (all y-values are doubled)'],3)]),
Sc('Biology: Human Reproduction and Development','Students examine human reproduction, the menstrual cycle, fertilisation, prenatal development, and related health topics.',[
  ('Fertilisation occurs when ___.',['the ovum is released from the ovary','implantation occurs in the uterus','the embryo develops all its organs','a sperm cell penetrates the ovum, combining their 23 chromosomes each to form a 46-chromosome zygote'],3),
  ('The placenta\'s function is ___.',['to produce eggs','to contract during birth','to produce testosterone','to exchange nutrients, oxygen, and waste between the mother\'s blood and the developing foetus without allowing blood to mix'],3),
  ('Critical periods in prenatal development are important because ___.',['no time is more sensitive than another','the foetus cannot be harmed before birth','some developmental stages are irreversible','during specific windows, organ systems are developing and are especially vulnerable to damage from teratogens (alcohol, drugs, infections)'],2),
  ('Hormones that regulate the menstrual cycle include ___.',['only oestrogen','only progesterone','adrenaline and cortisol','oestrogen, progesterone, FSH (follicle stimulating hormone), and LH (luteinising hormone) — working in a coordinated monthly feedback cycle'],3),
  ('Reproductive health education is important because ___.',['it encourages sexual activity','it is only for biology class','it is unrelated to well-being','informed young people can make healthier decisions, understand their bodies, and recognise and respond to reproductive health issues effectively'],3)]),
H('Media and History: How History is Represented','Students examine how films, television, novels, and social media represent historical events, and how to critically evaluate historical representation in popular media.',[
  ('Historical films and television often ___.',['perfectly represent historical events','have no influence on public understanding of history','are always based entirely on primary sources','prioritise dramatic narrative over historical accuracy — compressing timelines, inventing dialogue, and simplifying complex events for entertainment purposes'],3),
  ('The danger of Hollywood historical films is ___.',['they are too long','only that they use old footage','they are always good for education','they can shape public understanding of historical events more powerfully than academic history, potentially spreading inaccuracies, anachronisms, or ideological distortions at large scale'],3),
  ('How should a historically literate person watch a historical film?',['Never watch historical films','Believe everything in the film','Only watch documentaries','Engage critically — enjoy the narrative while staying alert to what has been changed, simplified, or omitted, and consulting historical sources for the fuller picture'],3),
  ('Social media\'s effect on historical memory includes ___.',['no significant effect','only preserving accurate history','replacing all other forms of historical knowledge','spreading both valuable grassroots history (family stories, community memory) and serious distortions (memes decontextualising events, conspiracy theories), making media literacy essential'],3),
  ('The inclusion of diverse perspectives in historical representation in film and media ___.',['is always present','is not important','makes historical narratives less accurate','corrects the long dominance of perspectives from powerful groups and brings the experiences of women, Indigenous peoples, and marginalised communities into mainstream historical consciousness'],3)]),
]),
day(26,[
E('Year-End Celebration: Reading and Writing Portfolio','Students curate and present a portfolio of their best reading and writing work from Grade 10, reflecting on their development.',[
  ('A portfolio of best work shows ___.',['only your first piece','only your longest piece','only error-free work','a curated selection demonstrating the range and depth of your skills — showing growth, versatility, and your strongest analytical and creative moments'],3),
  ('Selecting pieces for a portfolio involves ___.',['taking the highest-graded pieces only','random selection','choosing based on teacher preference','deliberate reflection: which pieces best demonstrate your analytical thinking, voice, and growth as a reader and writer'],3),
  ('Writing a portfolio reflection means ___.',['listing your grades','only noting what you liked','summarising each piece','examining how your skills have developed, what you have learned about reading and writing, and what you want to improve in Grade 11'],3),
  ('Sharing portfolio work with a peer or audience ___.',['only reveals weaknesses','is only for teachers to do','is inappropriate at high school level','makes writing purposeful and develops the communication skills of presenting your thinking to others — a skill for life beyond school'],3),
  ('The most valuable thing in a writing portfolio is ___.',['the piece with the best grade','the longest essay','the piece with the most quotations','the piece that shows who you are as a thinker — your voice, your ideas, and your genuine engagement with literature and language'],3)]),
M('Looking Ahead: Grade 11 Mathematics Pathways','Students learn about the three Grade 11 math pathways — Functions (MCR3U), Functions and Applications (MCF3M), and Foundations for College (MBF3C) — and make informed choices.',[
  ('MCR3U (Grade 11 Functions) is the pathway for students planning ___.',['a direct path to the workforce','college-level programs not requiring advanced math','post-secondary programs requiring calculus or advanced math: university STEM, business, economics, or health science programs','all Grade 12 courses equally'],2),
  ('Functions in Grade 11 extend Grade 10 quadratics to ___.',['linear equations only','polynomial, rational, exponential, and trigonometric functions — a significantly more abstract and rigorous treatment','geometry only','financial math only'],1),
  ('Choosing a math pathway wisely requires ___.',['only considering current grade','following friends\' choices','ignoring post-secondary plans','researching the prerequisites for programs you\'re interested in and honestly assessing your mathematical skills — changing pathways later is difficult'],3),
  ('The most important preparation for Grade 11 Functions is ___.',['memorising all quadratic formulas','only practising graphing','avoiding all math over summer','solid understanding of Grade 10 quadratics, functions, and analytic geometry — the Grade 11 course assumes mastery of these topics from the start'],3),
  ('Mathematics beyond high school is used in ___.',['only pure math careers','only engineering','only science','nearly every professional field: architecture, nursing, social science (statistics), finance, data analysis, education, and increasingly in arts and humanities through digital tools'],3)]),
Sc('Science: Looking Forward to Grade 11','Students preview Grade 11 science pathways — Biology, Chemistry, Physics — and understand how Grade 10 learning connects.',[
  ('Grade 11 Biology extends Grade 10 knowledge of ___.',['only evolution','only cells','atomic theory','cellular processes, genetics, evolution, and ecosystems into greater depth — including animal and plant physiology, population ecology, and evolution through natural selection'],3),
  ('Grade 11 Chemistry builds directly on ___.',['only physics concepts','only biology','no Grade 10 content','atomic theory, chemical bonding, and reaction types from Grade 10 — extending to stoichiometry (quantitative reactions), solution chemistry, and gas laws'],2),
  ('Grade 11 Physics extends ___.',['only waves','only nuclear science','only optics from Grade 10','kinematics, forces, work and energy from Grade 10 into more complex motion (projectile, circular) and introduces electricity, waves, and modern physics in greater depth'],3),
  ('All three Grade 11 sciences require ___.',['no mathematics','only memorisation','only writing skills','stronger mathematical skills than Grade 10 — especially algebra, significant figures, and graphing — as quantitative problem-solving becomes more central'],3),
  ('Choosing Grade 11 sciences based on future interests means ___.',['taking all sciences always','taking no sciences','only choosing based on the teacher','considering whether you want to continue toward health sciences (biology + chemistry), engineering (physics + chemistry), environmental science (all three), or other pathways'],3)]),
H('History Final Reflection: What Did We Learn?','Students write a final synthesis on the most significant lessons from Grade 10 History for their identity and future as Canadian citizens.',[
  ('The most significant lesson from WWII for democratic citizens is ___.',['democracies always win wars','only military power matters','history has no lessons','even democratic societies can engage in serious injustices (internment, racism) — democratic structures do not automatically prevent human rights violations; active vigilance and rights protection are essential'],3),
  ('The Charter of Rights and Freedoms matters to Grade 10 students because ___.',['it only applies to adults','only lawyers need to know it','it is already fully implemented','it protects your rights right now, and understanding it empowers you to recognise when your rights or others\' rights are violated and to seek remedy'],3),
  ('Reconciliation is a Grade 10 student\'s concern because ___.',['only the government can act on reconciliation','it was resolved by the TRC report','it is only a political issue','how your generation responds to the legacy of colonialism will determine whether the Calls to Action are implemented, and that response starts with education and empathy'],3),
  ('The most important citizenship skill developed in Grade 10 History is ___.',['memorising dates','knowing all prime ministers','only understanding WWII','critical historical thinking — the ability to analyse competing claims, evaluate evidence, consider multiple perspectives, and form reasoned judgements about complex questions'],3),
  ('Canada\'s history teaches that ___.',['Canada has always been just','change is impossible','history is irrelevant','the Canada we have was made by choices — and the better Canada we want requires your generation to make better choices, informed by honest understanding of both the achievements and the failures of our past'],3)]),
]),
day(27,[
E('Media: Social Media and Identity','Students analyse how social media platforms construct and perform identity, and examine the mental health, social, and political implications.',[
  ('Social media platforms are ___.',['neutral tools that reflect real life','always harmful','only entertainment','designed environments shaped by algorithmic choices, monetisation incentives, and design psychology — they actively shape how users present themselves and what they consume'],3),
  ('The "performance of self" on social media means ___.',['social media shows the real you always','only celebrities perform identity online','everyone acts completely natural online','users actively curate and construct a version of themselves for an audience — social media identity is a performance, not a transparent window into the self'],3),
  ('Algorithmic amplification can harm democratic discourse by ___.',['making politics too boring','spreading only factual content','limiting political discussion','creating filter bubbles, amplifying outrage and extreme content (since it drives engagement), and enabling the rapid spread of misinformation'],3),
  ('Social media\'s mental health impacts on adolescents may include ___.',['no scientific evidence of any impact','only positive effects on wellbeing','stronger social connections for everyone','increased anxiety and depression linked to social comparison, cyberbullying, disrupted sleep, and the pursuit of validation through likes — though research shows complex, varied effects'],3),
  ('Being a responsible social media user means ___.',['avoiding all social media','only using private accounts','sharing everything immediately without thinking','thinking critically about what you consume, being aware of how platforms manipulate you, respecting others\' dignity online, and not sharing unverified information'],3)]),
M('Personal Finance: Practical Mathematics','Students apply math to real personal finance scenarios — tax filing, credit, mortgages, insurance — relevant to their near future.',[
  ('A credit score measures ___.',['your income','how much money you have','your tax bracket','your creditworthiness — based on payment history, amount owed, length of credit history, and types of credit — used by lenders to decide whether to lend and at what rate'],3),
  ('Compound interest on debt (like a credit card at 20% APR) is ___.',['beneficial to the borrower','easy to pay off','irrelevant if you make minimum payments','extremely expensive over time — minimum payments barely cover interest, so debt can grow exponentially if not paid down aggressively'],3),
  ('A mortgage is ___.',['rent you pay to a landlord','a type of savings account','a government housing subsidy','a loan secured against property — usually for 25 years, where missing payments can result in losing your home'],3),
  ('Filing an income tax return in Canada ___.',['is optional','only applies to people with high income','is required annually for all Canadians who earn income — and even those with low income should file to receive benefits and credits they are entitled to','can be done without any documentation'],2),
  ('OSAP (Ontario Student Assistance Program) provides ___.',['employment','guaranteed employment after graduation','unlimited funding for any student','needs-based grants and loans to eligible post-secondary students to help cover tuition and living costs'],3)]),
Sc('Science: Environmental Decision Making','Students apply scientific knowledge to make and justify environmental decisions, practising evidence-based reasoning and ethical analysis.',[
  ('A life cycle assessment (LCA) ___.',['only considers manufacturing cost','only measures CO₂','evaluates only the end-of-life disposal','examines the environmental impact of a product or service across its entire life: raw materials, manufacturing, transportation, use, and disposal — giving a complete picture of its environmental cost'],3),
  ('Greenwashing refers to ___.',['genuine environmental improvement','government environmental regulation','reducing a company\'s carbon footprint','companies making misleading claims about their products\' environmental benefits to attract eco-conscious consumers without making substantive changes'],3),
  ('When evaluating an environmental policy proposal, you should consider ___.',['only economic costs','only environmental benefits','only public opinion','scientific effectiveness, economic costs and benefits, social equity (who bears costs and who benefits), technological feasibility, and political realities'],3),
  ('The precautionary principle in environmental decisions means ___.',['wait for 100% certainty before acting','regulation is always wrong','industry self-regulation is sufficient','when scientific evidence suggests potential serious harm, take protective action even if full certainty has not yet been established'],3),
  ('Effective environmental citizenship includes ___.',['only personal recycling','only political activism','ignoring environmental issues','a combination of personal choices (reducing consumption), political engagement (voting for climate action), and community action (supporting local environmental initiatives)'],3)]),
H('Year-End Exam Preparation: Canadian History and Civics','Students review key concepts and practise historical thinking skills for assessment.',[
  ('The most testable skill in Canadian history is ___.',['memorising dates and names','only knowing WWII','only understanding the Constitution','historical thinking — using concepts of significance, causation, continuity and change, perspective, evidence, and ethical judgement to analyse and interpret historical events and issues'],3),
  ('When answering a source-analysis question in history, you should ___.',['copy the source text','describe what you see only','ignore the source\'s context','identify the source\'s origin (author, audience, purpose, date), analyse its content, evaluate its reliability and limitations, and connect it to your historical knowledge'],3),
  ('A short analytical response in history should ___.',['list all the facts you know','avoid taking a position','be as long as possible','begin with a clear claim, support it with specific evidence, and explain the connection between evidence and claim — even a paragraph must have an argument'],3),
  ('The connection between Canada\'s WWII home front and contemporary Canadian identity is ___.',['no connection','only about economics','only about military history','that the decisions made then — about women\'s roles, immigration, civil liberties, and social programs — directly shaped the Canada we live in today'],3),
  ('In an exam essay on Canadian history, the most important first step is ___.',['writing as fast as possible','copying the question','writing your conclusion first','reading the question carefully and forming a clear, specific argument before writing — a minute of planning saves five minutes of aimless writing'],3)]),
]),
day(28,[
E('Writing: Reflecting on Grade 10 English','Students write a final metacognitive reflection on their development as readers, writers, and thinkers in Grade 10.',[
  ('Metacognitive reflection means ___.',['listing all the books read','summarising essay grades','only writing what you enjoyed','thinking carefully about your own learning process — how you have grown, what strategies work for you, and what skills you still want to develop'],3),
  ('The most important growth in Grade 10 English is ___.',['vocabulary size','writing speed','perfect grammar','the development of analytical thinking — the ability to form, support, and communicate complex interpretive arguments about texts and ideas'],3),
  ('Setting meaningful literacy goals for Grade 11 means ___.',['hoping things will be easier','picking goals your teacher suggested','avoiding challenging texts','identifying specific, realistic improvements in areas where you still struggle, and committing to the strategies that will get you there'],3),
  ('Reading widely outside school hours ___.',['is less important than school reading','is only for pleasure and has no academic value','replaces school reading','builds background knowledge, vocabulary, and the habit of sustained attention that makes all academic reading easier and more rewarding'],3),
  ('The most powerful thing writing can do is ___.',['earn good grades','fill required pages','meet word counts','make meaning — writing develops thought, communicates ideas, and connects human experiences across time and culture'],3)]),
M('Mathematics: Year-End Summary and Growth Reflection','Students reflect on their mathematical growth in Grade 10 and the role of mathematical thinking in their lives.',[
  ('The key mathematical concept connecting all Grade 10 topics is ___.',['only algebra','only geometry','functions — the relationship between two quantities, expressed through equations, graphs, and tables, underlies quadratics, trig, analytic geometry, and data management','only trigonometry'],2),
  ('Mathematical persistence means ___.',['getting every answer right immediately','only doing easy problems','giving up when confused','continuing to work on a challenging problem, trying different approaches, and learning from errors — the most important mathematical disposition'],3),
  ('The connection between mathematics and other subjects in Grade 10 is ___.',['no connection exists','only through physics','only through economics','profound: history uses data analysis, science requires measurement and modelling, English benefits from logical argument, and economics uses functions and statistics'],3),
  ('The biggest misconception about mathematics is ___.',['that it takes practice','that it requires thought','that it involves patterns','that some people are just "not math people" — mathematical skill is developed through practice and persistence, not a fixed innate ability'],3),
  ('Grade 10 mathematics has prepared you for ___.',['nothing useful in life','only Grade 11 exams','only STEM careers','a wide range of future study and careers, but most importantly for logical, quantitative thinking — a fundamental skill for navigating a complex world full of data, models, and numerical claims'],3)]),
Sc('Science: Science and Society — A Final Reflection','Students reflect on the role of science in society and their responsibilities as scientifically literate citizens.',[
  ('Scientific literacy means ___.',['knowing all scientific facts','only being good at labs','being a scientist','being able to read, understand, and critically evaluate scientific claims — distinguishing evidence-based science from pseudoscience, and understanding the nature and limits of scientific knowledge'],3),
  ('The relationship between science and policy is ___.',['science automatically determines policy','scientists should make all decisions','science has no role in policy','complex — science provides evidence and analysis, but policy decisions also involve values, economics, and politics: science informs but does not determine policy'],3),
  ('Anti-science sentiment (vaccine hesitancy, climate denial) is best addressed by ___.',['dismissing people who hold these views','only more data','making science optional','understanding its roots (distrust of institutions, misinformation, community identity) and engaging respectfully with evidence and transparent communication rather than dismissal'],3),
  ('The most important scientific habit for a Grade 10 graduate to carry into adult life is ___.',['remembering the periodic table','knowing all physics formulas','being able to identify DNA bases','asking "what is the evidence?" — evaluating claims critically, distinguishing correlation from causation, and updating beliefs when evidence warrants'],3),
  ('Science\'s greatest achievement is ___.',['only medicine','only technology','only the internet','the method itself — a self-correcting system of knowledge-building based on evidence, peer review, and revision, which has transformed human understanding and wellbeing despite being a very recent human invention'],3)]),
H('Canada\'s Story: A Continuing Narrative','Students write a final historical essay on the most significant development in Canadian history and its relevance to their lives as future citizens.',[
  ('Canada\'s most significant unresolved historical challenge is ___.',['the 1867 Confederation debt','WWI conscription crisis','the implementation of Responsible Government','the relationship between the Canadian state and Indigenous peoples — a relationship marked by colonisation, dispossession, and injustice that requires ongoing reconciliation, not just acknowledgement'],3),
  ('The Charter of Rights and Freedoms (1982) is significant because ___.',['it was Canada\'s first constitution','it only affects criminal law','it was only a ceremonial change','it transformed Canada into a rights-based constitutional democracy where courts can strike down laws that violate fundamental rights — a genuine revolution in the relationship between citizens and the state'],3),
  ('Canada\'s identity as a "middle power" committed to multilateralism is ___.',['outdated in the 21st century','a permanent achievement','only relevant in foreign policy','a strategic choice that reflects both Canada\'s values and its interests — small enough to need international cooperation, influential enough to shape it'],3),
  ('The most important historical lesson for Grade 10 students is ___.',['study hard for tests','grades matter most','history is boring','history is not about the past — it is the ongoing story of how human beings make choices about power, justice, and belonging, and your generation will be the authors of its next chapters'],3),
  ('Completing Grade 10 History means ___.',['you now know everything about Canada','history class is finished','you can stop thinking about current events','you have developed the historical thinking skills to be a more engaged, critical, and responsible citizen — skills that matter every day, not just in exams'],3)]),
]),
day(29,[
E('Exam Skills: The Unseen Poem','Students practise analysing an unseen poem under exam conditions — applying close reading, identifying form and content, and writing a focused analytical response.',[
  ('Approaching an unseen poem for the first time, you should ___.',['write immediately','read only the first stanza','guess the theme from the title','read the entire poem at least twice: once for overall meaning and feeling, then again for specific craft choices to analyse'],3),
  ('In an unseen poem analysis, you should prioritise ___.',['identifying the rhyme scheme before anything else','memorising all literary terms','proving you know many techniques','analysing HOW specific craft choices create meaning and effect — the technique is never the point; its effect is'],3),
  ('If you are unsure of an image\'s meaning in an unseen poem, you should ___.',['skip it','say "I don\'t know"','look it up (in an exam, this isn\'t possible)','make a thoughtful, supported interpretation based on context — there is rarely only one correct reading, and a well-reasoned interpretation earns marks even if it differs from others'],3),
  ('Time management for an unseen poem response (20 minutes) should be ___.',['all time writing','no planning','10 minutes reading/annotating, 2 minutes planning your thesis, 8 minutes writing — having a clear argument before writing saves time','15 minutes reading, 5 minutes writing'],0),
  ('A strong response to an unseen poem ___.',['identifies every literary term','summarises the poem','avoids quoting the poem','makes an argument about how the poem creates meaning, supports it with specific quotation and analysis, and returns to the central argument in a conclusion'],3)]),
M('Exam Skills: Mathematical Problem Solving Strategies','Students practise multi-step problem solving strategies for exam conditions.',[
  ('When a math problem seems impossible, the best strategy is ___.',['leave it blank immediately','only try one approach','panic','write what you know: draw a diagram, define variables, write related formulas — starting the solution often reveals the path forward'],3),
  ('Working backwards in a problem means ___.',['guessing the answer','only for simple problems','never used in real math','starting from what you want to find and determining what you would need to know — useful for complex problems where the path forward is unclear'],3),
  ('Checking your answer in a word problem means ___.',['recalculating the same way','only for calculator problems','only checking arithmetic','substituting your answer back into the original problem context to verify it makes sense — does the answer answer the question asked? Is it a reasonable value?'],3),
  ('Making an estimate before solving is useful because ___.',['it replaces the calculation','it is only for multiple choice','it takes too much time','it gives you a benchmark — if your calculation gives a very different answer from your estimate, that signals an error to find'],3),
  ('The most important strategy for a difficult exam problem is ___.',['copying from a neighbour','skipping and never returning','showing partial work earns no marks','attempting every part and showing all work — partial marks for method are available even when the final answer is wrong'],3)]),
Sc('Science: Exam Preparation and Review','Students review key concepts from all three Grade 10 science strands for assessment readiness.',[
  ('The difference between ionic and covalent bonding is ___.',['no difference','only in crystal structure','only in state at room temperature','ionic bonding involves electron transfer between a metal and non-metal forming ions; covalent bonding involves electron sharing between non-metals'],3),
  ('Natural selection requires ___.',['directed change by an organism','a single generation to produce new species','no genetic variation','heritable variation within a population, differential reproductive success (some variants reproduce more), and inheritance of advantageous traits'],3),
  ('Newton\'s Second Law (F = ma) means ___.',['only mass affects force','only acceleration matters','force and acceleration are unrelated','a net force on an object causes acceleration proportional to the force and inversely proportional to mass — doubling the force doubles the acceleration; doubling the mass halves it'],3),
  ('pH 3 compared to pH 5 is ___.',['twice as acidic','no difference in acidity','ten times less acidic','one hundred times more acidic — because pH is a logarithmic scale, each unit represents a 10-fold change in H⁺ concentration'],3),
  ('The conservation of energy means ___.',['energy is destroyed in friction','energy can be created in nuclear reactions','machines can exceed 100% efficiency','the total energy in a closed system remains constant — energy transforms between forms (kinetic to potential, chemical to thermal) but is neither created nor destroyed'],3)]),
H('History Exam: Practise Essay','Students practise a 45-minute historical essay, applying all historical thinking skills to a significant Canadian history question.',[
  ('A strong history essay begins with ___.',['a question restated verbatim','a general statement about history','a list of facts','a clear, specific thesis that states your argument — not just the topic, but your interpretive claim about it'],3),
  ('Historical evidence in an essay should ___.',['only come from memory','be as general as possible','include only dates','be specific: named people, events, dates, and details that directly support your analytical argument'],3),
  ('Acknowledging historical complexity in an essay means ___.',['avoiding a clear argument','only presenting two sides','making no judgements','recognising that causes are multiple, perspectives differ, and outcomes are contested — and integrating this complexity into your argument rather than oversimplifying'],3),
  ('The conclusion of a history essay should ___.',['introduce new evidence','restate only the facts','only repeat your thesis word for word','synthesise your argument, confirm your thesis has been proven, and extend to a broader significance — why does this matter beyond the specific question?'],3),
  ('After writing a history essay under time pressure, you should ___.',['never reread your work','immediately submit without review','only check spelling','reread quickly for argument clarity, logical flow, and whether you actually answered the question asked — these are the most common exam errors'],3)]),
]),
day(30,[
E('Year-End: English as a Lifelong Practice','A final celebration of reading, writing, and thinking. Students share work, set goals, and understand English as a practice they will carry into all areas of their lives.',[
  ('Reading great literature develops ___.',['only vocabulary','only knowledge of plots','only grammar skills','empathy, critical thinking, historical and cultural awareness, and the capacity for sustained engagement with complex ideas — skills that transfer to every area of life'],3),
  ('Writing is a thinking tool because ___.',['writing is only for communication','you think first, then write','writing and thinking are separate activities','the act of writing forces you to clarify, organise, and develop your thinking — ideas that seem clear in your head often reveal their gaps and complexities when you write them down'],3),
  ('The texts you have studied in Grade 10 English ___.',['are now irrelevant to your life','only matter for literary study','have no connection to the real world','have expanded your understanding of human experience, your awareness of power and language, and your ability to engage critically with the world'],3),
  ('Continuing to read widely beyond school ___.',['is optional and has no value','only applies to people in literature programs','replaces formal education','is one of the most powerful investments you can make in your intellectual and empathetic development — the lifelong reader is better equipped for almost everything'],3),
  ('The most important thing you\'ve learned in Grade 10 English is ___.',['how to avoid comma splices','the plot of every text','only Shakespeare\'s language','that language and story are not decorations on top of human experience — they are the medium through which we understand, make sense of, and share that experience'],3)]),
M('Grade 10 Math: Final Celebration and Reflection','A final review and reflection on mathematical growth, connecting the year\'s learning to lifelong mathematical thinking.',[
  ('The most useful mathematical idea from Grade 10 for daily life is ___.',['the quadratic formula specifically','factoring polynomials','the Cosine Law','the concept of function — understanding relationships between variables — which underlies everything from budgeting to understanding health statistics to evaluating environmental claims'],3),
  ('Mathematical confidence is built by ___.',['only solving easy problems','avoiding all challenging problems','only memorising formulas','working through difficulty, making mistakes, learning from them, and developing the persistence to try new approaches — not by only doing what already feels comfortable'],3),
  ('Grade 10 math connects to citizenship through ___.',['no connection','only through science','only through engineering','the ability to understand and evaluate statistical claims in media, evaluate financial products, understand probability (in health and risk decisions), and interpret graphical data — mathematical literacy is civic literacy'],3),
  ('The mathematical skill most undervalued by students is ___.',['computation speed','formula memorisation','the ability to perform operations','the ability to communicate mathematical reasoning clearly — being able to explain why a solution works is more valuable and harder than just finding the answer'],3),
  ('Finishing Grade 10 Math means ___.',['you\'ve learned all the math you\'ll ever need','math is finished for most of you','only engineers need to remember this','you\'ve built a foundation — functions, geometry, data, and algebraic reasoning — that will serve you in whatever you do next, from everyday decisions to advanced study'],3)]),
Sc('Grade 10 Science: Final Synthesis','A final celebration of scientific learning and a look ahead to senior science and life as a scientifically literate citizen.',[
  ('The three Grade 10 science strands connect through ___.',['having nothing in common','only sharing lab equipment','only being about Canada','the fundamental idea that the world operates through consistent, discoverable principles — whether in the chemical behaviour of atoms, the evolution of life, or the motion of objects'],3),
  ('Science is not a set of facts to memorise but ___.',['a way to pass tests','a collection of correct answers','only relevant for scientists','a method for building knowledge through observation, hypothesis, experimentation, and revision — the facts are important, but the method is more powerful'],3),
  ('Being scientifically literate in the age of misinformation means ___.',['trusting all claims from scientists','trusting no online information','ignoring science in daily decisions','being able to evaluate claims critically: checking sources, looking for evidence, understanding the difference between correlation and causation, and recognising the provisional nature of scientific knowledge'],3),
  ('The environmental challenges facing your generation ___.',['are already solved','only require technology','are someone else\'s problem','will require scientific knowledge to understand, technical innovation to address, political will to implement, and social change to sustain — and science literacy is the foundation of all of it'],3),
  ('The greatest scientific frontier for your generation is ___.',['already fully mapped out','only space exploration','only artificial intelligence','genuinely unknown — questions about consciousness, quantum computing, the origins of life, dark matter, and the full potential of biotechnology remain open, and some of you may contribute to answering them'],3)]),
H('Canada\'s Future: Your Role as a Citizen','A final reflection on Canadian history, citizenship, and the responsibilities of the Grade 10 generation.',[
  ('Canada\'s most important strength as you enter adulthood is ___.',['its military power','only its natural resources','only its geography','its commitment — imperfect but genuine and ongoing — to democratic governance, human rights, diversity, and international cooperation: values worth defending and improving'],3),
  ('The generation entering high school now will determine ___.',['nothing important about Canada\'s future','only their personal futures','only economic outcomes','whether reconciliation moves from aspiration to reality, whether Canada meets its climate commitments, and whether democracy remains a genuine tool for all Canadians or only for the privileged'],3),
  ('Studying Canadian history has prepared you to ___.',['feel proud of everything Canada has done','feel ashamed of everything','ignore current events','engage more thoughtfully with current issues — recognising historical patterns, understanding how we got here, and taking seriously your role in shaping what comes next'],3),
  ('The most important civic skill for your generation is ___.',['only voting','only protesting','only consuming news','critical thinking combined with civic engagement: being able to evaluate claims, understand systems, recognise injustice, and act purposefully — not just react — in the democratic spaces available to you'],3),
  ('Canada\'s story is ___.',['finished','already told in full','only about the past','still being written — and you are not just a reader of this story, but one of its authors'],3)]),
]),
]

append_to(10, g10b)
print('Grade 10 days 16-30 appended.')
