#!/usr/bin/env python3
"""Phase 4 extension: Grade 12, Days 61-70 (extending the completed Days
1-60 curriculum arc -- see gen_grade12_days51_60.py for the immediately
preceding batch). Topics chosen to avoid any overlap with the existing
Day 1-60 set (see data/grade12.json), which already spans extremely
advanced ground -- Taylor/Maclaurin series, De Moivre's theorem, general
relativity, quantum mechanics, matrices, parametric/polar equations,
eigenvalues, the Squeeze Theorem, the Bohr model, diasporic identity,
the normal distribution, hyperbolic functions, neutron stars, modular
arithmetic, volumes by cross-sections, and more.

New topics for this batch: epistolary and archival fiction, magical
realism, the Riemann sum revisited through improper series, spherical
coordinates, the Laplace transform, wave-particle duality of matter
(de Broglie), gauge bosons, and more (see full list in g12_61_70 below).

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as gen_grade12_days51_60.py).

Note: Day 30 in the existing data has only 3 subjects (missing a
Calculus entry) -- a pre-existing data quirk from an earlier session,
unrelated to this batch and not something this script touches.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys
sys.path.insert(0, '/sessions/happy-laughing-ritchie/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
C12 = 'https://tvolearn.com/pages/grade-12-calculus'
P12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RC, RP = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def C(t, s, q):
    return sub('Calculus', t, s, RC, C12, q)


def P(t, s, q):
    return sub('Physics', t, s, RP, P12, q)


g12_61_70 = [
day(61, [
E('Literature: Magical Realism and the Blending of Worlds',
  'Grade 12 English strand: magical realism is a literary mode in which fantastical or supernatural events are presented within an otherwise realistic setting as an unremarkable part of everyday life, often used to explore cultural, political, or historical truths.',
  [('Magical realism presents fantastical or supernatural events within an otherwise ___ setting.', ['Realistic', 'Entirely fictional, with no connection to any recognizable world', 'A concept unrelated to literary mode', 'Purely scientific, with no room for the impossible'], 0),
   ('In magical realism, the supernatural is typically treated as ___ by characters within the story.', ['An unremarkable part of everyday life', 'A shocking impossibility that halts the entire narrative', 'A concept unrelated to how characters respond to events', 'Something that never actually occurs within the story'], 0),
   ('Magical realism is often used by authors to explore cultural, political, or ___ truths.', ['Historical', 'Concepts entirely disconnected from any lived reality', 'Only mathematical truths, with no connection to culture', 'Truths that have no bearing on any real-world context'], 0),
   ('Why might an author choose magical realism, rather than strict realism, to depict a community’s history of trauma or upheaval?', ['The blending of the fantastical and the real can capture emotional and historical truths that literal description alone might not fully convey', 'Magical realism always removes any emotional weight from a story’s historical content', 'This mode has no capacity to reflect real cultural or political experience', 'This concept has no connection to how authors represent difficult histories'], 0),
   ('Why is magical realism considered a distinct literary mode rather than simply a subgenre of fantasy?', ['Its supernatural elements remain fully embedded within a recognizably real world and social context, rather than constructing an entirely separate fantastical universe', 'Magical realism and fantasy are entirely identical, with no meaningful distinction between them', 'This mode never engages with any real-world setting or social context', 'This concept has no relevance to categorizing different literary modes'], 0)]),
AF('Introduction to Complex Analysis: The Complex Plane Revisited',
   'Grade 12 Advanced Functions strand: complex analysis extends algebraic operations on complex numbers into geometric transformations on the complex plane, where multiplication corresponds to a combined rotation and scaling.',
   [('In complex analysis, multiplying two complex numbers corresponds geometrically to a combined rotation and ___ on the complex plane.', ['Scaling', 'Reflection exclusively, with no connection to rotation', 'A concept unrelated to complex number operations', 'Translation exclusively, with no connection to angle or magnitude'], 0),
    ('A complex number can be represented on the complex plane using its ___ and angle from the positive real axis.', ['Magnitude', 'Colour, with no connection to a numerical value', 'A concept unrelated to representing complex numbers', 'Only its real part, ignoring the imaginary part entirely'], 0),
    ('Adding two complex numbers on the complex plane corresponds geometrically to ___ their position vectors.', ['Adding', 'Multiplying, an entirely different operation', 'A concept unrelated to complex number addition', 'Rotating by ninety degrees regardless of the numbers involved'], 0),
    ('Why does multiplying a complex number by i correspond to a ninety-degree rotation on the complex plane?', ['Since i has a magnitude of one and an angle of ninety degrees, multiplying by i adds ninety degrees to the original number’s angle without changing its magnitude', 'Multiplying by i always doubles a complex number’s magnitude with no change in angle', 'The value i has no defined geometric relationship to rotation on the complex plane', 'This concept has no connection to how complex multiplication behaves geometrically'], 0),
    ('Why is viewing complex numbers as points on a plane, rather than purely as algebraic expressions, valuable for understanding their behaviour under repeated operations?', ['The geometric view reveals patterns, such as rotation and scaling, that are difficult to see from algebraic manipulation alone', 'The geometric interpretation of complex numbers provides no additional insight beyond algebraic manipulation', 'Complex numbers have no meaningful geometric representation of any kind', 'This concept has no relevance to understanding complex number operations'], 0)]),
C('Calculus: Improper Integrals and Infinite Series -- A Second Look',
  'Grade 12 Calculus strand: connecting the convergence behaviour of improper integrals to that of infinite series highlights a shared underlying question -- whether an unbounded accumulation process settles toward a finite value.',
  [('Both improper integrals and infinite series raise the shared question of whether an unbounded accumulation process settles toward a ___ value.', ['Finite', 'Negative, in every single case regardless of the terms involved', 'A concept unrelated to convergence', 'Undefined, with no possibility of a numerical result'], 0),
   ('An improper integral with an infinite bound is said to converge if the limit of its accumulated area approaches a ___ number as the bound grows without limit.', ['Finite', 'Only zero, with no other finite value possible', 'A concept unrelated to evaluating improper integrals', 'Negative infinity in every single case'], 0),
   ('Comparing the terms of an infinite series to a related integral is a strategy sometimes used to test the series for ___.', ['Convergence', 'Divisibility, a concept unrelated to series behaviour', 'A concept unrelated to testing infinite series', 'Symmetry, which has no bearing on convergence'], 0),
   ('Why might comparing an infinite series to a related improper integral help determine whether that series converges?', ['If the corresponding integral converges to a finite value, the sum of the related series is often bounded in a comparable way, supporting a convergence conclusion', 'An infinite series and an improper integral can never share any meaningful mathematical relationship', 'This comparison has no connection to determining whether a series converges', 'This concept has no relevance to advanced calculus techniques for testing convergence'], 0),
   ('Why is the concept of convergence, applied consistently across both integrals and series, considered a unifying theme in advanced calculus study?', ['It shows that seemingly different infinite processes can be analyzed using closely related reasoning about limits and boundedness', 'Convergence has no meaningful application to either improper integrals or infinite series', 'Integrals and series are entirely unrelated processes with no shared mathematical structure', 'This concept has no relevance to deepening a student’s understanding of calculus'], 0)]),
P('Physics: Wave-Particle Duality of Matter -- The de Broglie Hypothesis',
  'Grade 12 Physics strand: the de Broglie hypothesis proposes that all matter, not only light, exhibits wave-like properties, with a particle’s wavelength inversely related to its momentum.',
  [('The de Broglie hypothesis proposes that all matter exhibits ___ properties, not only light.', ['Wave-like', 'Purely solid, with no wave-like behaviour whatsoever', 'A concept unrelated to the behaviour of matter', 'Only particle-like properties, with no wave component at all'], 0),
   ('According to the de Broglie hypothesis, a particle’s wavelength is inversely related to its ___.', ['Momentum', 'Electric charge, which has no defined relationship to wavelength', 'A concept unrelated to describing a particle’s wave nature', 'Colour, a property that particles at this scale do not possess'], 0),
   ('The de Broglie hypothesis extends wave-particle duality, previously associated mainly with light, to include ___.', ['All matter', 'Only massless particles, excluding matter with mass', 'A concept unrelated to wave-particle duality', 'Only extremely large, macroscopic objects exclusively'], 0),
   ('Why is the wave nature of everyday macroscopic objects, such as a thrown ball, never noticeably observed?', ['The de Broglie wavelength of an object with significant mass and momentum is extraordinarily small compared to any observable scale', 'Macroscopic objects never possess any momentum, so no wavelength can be calculated', 'The de Broglie hypothesis applies only to light and has no bearing on matter with mass', 'This concept has no relevance to understanding wave-particle duality'], 0),
   ('Why was the de Broglie hypothesis a significant conceptual step in the development of quantum mechanics?', ['It suggested that the wave-particle duality already observed in light might be a universal feature of matter itself, reshaping how physicists understood particles', 'The de Broglie hypothesis had no meaningful influence on the development of quantum theory', 'This hypothesis contradicted no prior assumptions about the nature of particles', 'This concept has no relevance to the historical development of quantum mechanics'], 0)])]),

day(62, [
E('Writing: The Epistolary and Archival Narrative Form',
  'Grade 12 English strand: an epistolary or archival narrative tells a story through documents such as letters, diary entries, or records, requiring readers to piece together plot, character, and reliability from fragmented, first-person sources.',
  [('An epistolary or archival narrative tells a story through documents such as letters, diary entries, or ___.', ['Records', 'A single, continuous third-person account with no documents involved', 'A concept unrelated to this narrative form', 'Illustrations exclusively, with no written text at all'], 0),
   ('This narrative form requires readers to piece together plot, character, and ___ from fragmented, first-person sources.', ['Reliability', 'A concept entirely unrelated to interpreting fragmented documents', 'Only page numbers, with no connection to meaning', 'Font style, with no connection to narrative content'], 0),
   ('Which is an example of a document that might appear in an epistolary narrative?', ['A series of letters exchanged between characters', 'A single, omniscient narrator’s uninterrupted account', 'A document entirely unrelated to this narrative form', 'A form with no written or recorded content whatsoever'], 0),
   ('Why might an author use an epistolary or archival structure to tell a story rather than a conventional single narrator?', ['Presenting multiple documents from different sources can create dramatic irony, gaps in knowledge, and questions about each writer’s reliability', 'An epistolary structure always simplifies a story compared to a conventional single narrator', 'This narrative form has no effect on how a reader experiences gaps in knowledge or perspective', 'This concept has no connection to how narrative structure shapes meaning'], 0),
   ('Why does an epistolary or archival narrative often demand more active interpretive work from its reader than a traditionally narrated story?', ['The reader must infer connections, timelines, and truths that are not explicitly stated by any single authoritative narrator', 'This narrative form requires no interpretation, since every document explains itself completely', 'Fragmented documents always present a single, unambiguous version of events', 'This concept has no relevance to how readers engage with unconventional narrative structures'], 0)]),
AF('Introduction to Spherical Coordinates',
   'Grade 12 Advanced Functions strand: spherical coordinates locate a point in three-dimensional space using a radial distance and two angles, offering an alternative to Cartesian coordinates that is especially useful for problems with a natural centre point.',
   [('Spherical coordinates locate a point in three-dimensional space using a radial distance and ___ angles.', ['Two', 'Zero, since spherical coordinates use no angles at all', 'A concept unrelated to describing a point’s position', 'Four, an inaccurate number of angles for this coordinate system'], 0),
    ('Spherical coordinates are especially useful for problems with a natural ___ point.', ['Centre', 'Edge, which has no special relevance to spherical coordinates', 'A concept unrelated to choosing an appropriate coordinate system', 'Corner, a feature unrelated to spherical symmetry'], 0),
    ('The radial distance in spherical coordinates measures how far a point is from the ___.', ['Origin', 'Nearest coordinate axis exclusively, with no connection to the origin', 'A concept unrelated to spherical coordinates', 'Edge of the coordinate plane, a boundary that does not exist'], 0),
    ('Why might spherical coordinates be more convenient than Cartesian coordinates for describing the position of a satellite orbiting the Earth?', ['A satellite’s position is naturally described relative to Earth’s centre using a distance and two angles, matching the structure of spherical coordinates', 'Cartesian coordinates are always simpler than spherical coordinates for describing any orbiting object', 'Spherical coordinates have no practical advantage over Cartesian coordinates in any real-world application', 'This concept has no connection to describing the position of objects in three-dimensional space'], 0),
    ('Why is choosing an appropriate coordinate system, such as spherical instead of Cartesian, an important problem-solving skill in advanced mathematics?', ['A well-chosen coordinate system can dramatically simplify a problem’s symmetry, making calculations more manageable than a poorly matched system would allow', 'The choice of coordinate system never affects how difficult a given problem is to solve', 'Spherical coordinates can never simplify any three-dimensional mathematical problem', 'This concept has no relevance to solving advanced problems efficiently'], 0)]),
C('Calculus: The Laplace Transform -- A First Look',
  'Grade 12 Calculus strand: the Laplace transform converts a function of time into a function of a complex frequency variable, often turning certain differential equations into more manageable algebraic equations.',
  [('The Laplace transform converts a function of time into a function of a complex ___ variable.', ['Frequency', 'Colour, with no connection to time or frequency', 'A concept unrelated to the Laplace transform', 'Volume, with no connection to this transformation'], 0),
   ('The Laplace transform often turns certain differential equations into more manageable ___ equations.', ['Algebraic', 'Equations that are always impossible to solve by any method', 'A concept unrelated to simplifying differential equations', 'Purely geometric equations, with no connection to algebra'], 0),
   ('The Laplace transform is defined using an ___ that integrates a function multiplied by a decaying exponential.', ['Improper integral', 'A concept unrelated to how the Laplace transform is calculated', 'Only a simple derivative, with no integral involved', 'A finite sum, with no integral involved whatsoever'], 0),
   ('Why might engineers prefer to convert a differential equation into an algebraic equation using the Laplace transform, before eventually transforming back?', ['Algebraic equations are often significantly easier to manipulate and solve than differential equations, simplifying complex system analysis', 'Differential equations are always easier to solve directly than any algebraic equation', 'The Laplace transform never simplifies any calculation involving differential equations', 'This concept has no relevance to practical applications of calculus'], 0),
   ('Why is the Laplace transform considered a valuable bridge between calculus studied in Grade 12 and further study in engineering or applied mathematics?', ['It introduces the powerful idea of transforming a problem into a different, more manageable mathematical domain, a technique used throughout advanced applied fields', 'The Laplace transform has no further relevance beyond a single introductory calculus lesson', 'This transformation technique is never used in any engineering or applied mathematics context', 'This concept has no connection to preparing students for further mathematical study'], 0)]),
P('Physics: Gauge Bosons and the Fundamental Forces',
  'Grade 12 Physics strand: the Standard Model describes each fundamental force as being mediated by an exchange of specific particles called gauge bosons, such as the photon for electromagnetism and gluons for the strong force.',
  [('The Standard Model describes each fundamental force as being mediated by an exchange of specific particles called ___.', ['Gauge bosons', 'Neutrinos, which do not mediate fundamental forces in this way', 'A concept unrelated to the Standard Model', 'Protons, which are not force-carrying particles'], 0),
   ('The photon is the gauge boson associated with the ___ force.', ['Electromagnetic', 'Strong force exclusively, with no connection to electromagnetism', 'A concept unrelated to describing fundamental forces', 'Gravitational force, which has no confirmed gauge boson in the Standard Model'], 0),
   ('Gluons are the gauge bosons associated with the ___ force.', ['Strong', 'Weak force exclusively, with no connection to gluons', 'A concept unrelated to the Standard Model', 'Electromagnetic force, which is mediated by the photon instead'], 0),
   ('Why is the photon considered the “carrier” of the electromagnetic force between two charged particles?', ['In the Standard Model, the exchange of photons between charged particles is understood as the mechanism producing the electromagnetic interaction between them', 'Photons have no established role in mediating any interaction between charged particles', 'The electromagnetic force operates with no need for any exchanged particle at all', 'This concept has no relevance to understanding fundamental forces in modern physics'], 0),
   ('Why is understanding gauge bosons considered essential to the Standard Model’s explanation of how particles interact?', ['They provide the underlying mechanism proposed for how the fundamental forces are transmitted between particles at the subatomic level', 'Gauge bosons have no role in explaining any interaction between fundamental particles', 'The Standard Model’s explanation of particle interactions has no connection to these carrier particles', 'This concept has no relevance to modern particle physics'], 0)])]),

day(63, [
E('Literature: The Bildungsroman -- The Novel of Formation',
  'Grade 12 English strand: a bildungsroman traces a protagonist’s psychological and moral development from youth to maturity, typically structured around a series of formative experiences, setbacks, and realizations that shape adult identity.',
  [('A bildungsroman traces a protagonist’s psychological and moral development from youth to ___.', ['Maturity', 'A state of complete stagnation, with no development at all', 'A concept unrelated to this literary form', 'Infancy, a reversal of typical development'], 0),
   ('A bildungsroman is typically structured around a series of ___ experiences.', ['Formative', 'Entirely inconsequential, with no lasting impact on the protagonist', 'A concept unrelated to how this literary form is structured', 'Repetitive, with no meaningful change or growth involved'], 0),
   ('The formative experiences in a bildungsroman often include setbacks and ___.', ['Realizations', 'A complete absence of self-reflection throughout the entire narrative', 'A concept unrelated to this genre’s typical structure', 'Only external events, with no internal change in the protagonist'], 0),
   ('Why might a bildungsroman include a protagonist’s significant failure or disillusionment as a key turning point?', ['Confronting failure or a loss of illusion often catalyzes the deeper self-understanding central to the genre’s focus on maturation', 'A bildungsroman never includes any failure or disillusionment experienced by its protagonist', 'Setbacks have no meaningful role in a protagonist’s psychological or moral development', 'This concept has no connection to how coming-of-age narratives are typically structured'], 0),
   ('Why does the bildungsroman remain a widely studied and adapted literary form across different cultures and time periods?', ['The universal experience of growing into adult identity resonates across diverse cultural and historical contexts, allowing endless variation on a shared structure', 'This literary form has no lasting relevance to readers from different cultures or eras', 'Coming-of-age narratives are never studied or adapted across different literary traditions', 'This concept has no connection to why certain literary forms endure over time'], 0)]),
AF('Functions: The Behaviour of Rational Functions Near Oblique Asymptotes',
   'Grade 12 Advanced Functions strand: an oblique (slant) asymptote occurs when the degree of a rational function’s numerator exceeds the degree of its denominator by exactly one, and polynomial division reveals the linear function the curve approaches.',
   [('An oblique asymptote occurs when the degree of a rational function’s numerator exceeds the degree of its denominator by exactly ___.', ['One', 'Three, an incorrect difference for an oblique asymptote', 'A concept unrelated to rational function behaviour', 'Zero, meaning the degrees would instead be equal'], 0),
    ('Polynomial division of a rational function reveals the ___ function that the curve approaches as an oblique asymptote.', ['Linear', 'Quadratic, an incorrect degree for an oblique asymptote', 'A concept unrelated to finding an oblique asymptote', 'Constant, which describes a horizontal asymptote instead'], 0),
    ('A rational function can approach an oblique asymptote as x approaches ___.', ['Positive or negative infinity', 'Only a single specific finite value, with no connection to infinity', 'A concept unrelated to asymptotic behaviour', 'Zero exclusively, with no connection to infinite behaviour'], 0),
    ('Why does performing polynomial long division on a rational function help identify its oblique asymptote?', ['The quotient from the division represents the linear function the curve approaches, while the remainder term shrinks toward zero as x grows large', 'Polynomial long division has no connection to finding a rational function’s asymptotic behaviour', 'The remainder from polynomial division always grows larger as x increases, contradicting the asymptote’s definition', 'This concept has no relevance to analyzing a rational function’s graph'], 0),
    ('Why can a rational function never have both an oblique asymptote and a horizontal asymptote at the same time?', ['These two types of asymptotes depend on different, mutually exclusive relationships between the numerator’s and denominator’s degrees', 'A rational function can freely have both an oblique and a horizontal asymptote simultaneously in every case', 'The degrees of the numerator and denominator have no bearing on the type of asymptote a function has', 'This concept has no relevance to understanding the end behaviour of rational functions'], 0)]),
C('Calculus: Related Extrema -- Optimization on Closed Intervals Revisited',
  'Grade 12 Calculus strand: finding the absolute maximum and minimum of a continuous function on a closed interval requires comparing the function’s value at all critical points within the interval to its value at both endpoints.',
  [('Finding the absolute maximum and minimum of a continuous function on a closed interval requires comparing its value at all critical points to its value at both ___.', ['Endpoints', 'Local minima exclusively, with no connection to the interval’s boundaries', 'A concept unrelated to this optimization method', 'Inflection points exclusively, with no connection to the endpoints'], 0),
   ('A critical point of a function occurs where its derivative is zero or ___.', ['Undefined', 'Always positive, with no other possible value', 'A concept unrelated to identifying critical points', 'Equal to the function’s own value at that point'], 0),
   ('This method for finding absolute extrema on a closed interval is sometimes called the ___ theorem approach.', ['Extreme value', 'Mean value, a related but distinct calculus concept', 'A concept unrelated to finding absolute extrema', 'Intermediate value, a related but distinct calculus concept'], 0),
   ('Why is it necessary to check the function’s value at the endpoints of a closed interval, even if a critical point exists within that interval?', ['The absolute maximum or minimum on a closed interval could occur at an endpoint rather than at any interior critical point', 'The endpoints of a closed interval never need to be checked when searching for an absolute extremum', 'A function’s value at its endpoints has no bearing on identifying its absolute maximum or minimum', 'This concept has no relevance to solving optimization problems on a closed interval'], 0),
   ('Why does the Extreme Value Theorem guarantee that a continuous function on a closed interval has both an absolute maximum and an absolute minimum?', ['Continuity on a closed, bounded interval ensures the function’s values do not escape to infinity or leave gaps, guaranteeing these extreme values are attained', 'A continuous function on a closed interval is never guaranteed to reach an absolute maximum or minimum value', 'The Extreme Value Theorem applies only to functions that are not continuous', 'This concept has no relevance to solving closed-interval optimization problems'], 0)]),
P('Physics: Superfluidity and Extreme Low-Temperature Phenomena',
  'Grade 12 Physics strand: superfluidity is a state of matter, observed in liquid helium at extremely low temperatures, in which the fluid flows with effectively zero viscosity, allowing it to exhibit striking behaviours impossible for ordinary liquids.',
  [('Superfluidity is a state of matter observed in liquid helium at extremely low ___.', ['Temperatures', 'Pressures exclusively, with no connection to temperature', 'A concept unrelated to superfluid behaviour', 'Densities exclusively, with no connection to temperature'], 0),
   ('A superfluid flows with effectively zero ___.', ['Viscosity', 'Electrical resistance exclusively, a property associated with superconductivity instead', 'A concept unrelated to fluid behaviour', 'Mass, which a superfluid still clearly possesses'], 0),
   ('Superfluidity allows liquid helium to exhibit striking behaviours, such as flowing up and over the walls of its ___.', ['Container', 'Source of heat exclusively, with no connection to its physical container', 'A concept unrelated to superfluid behaviour', 'Original measuring instrument, with no connection to its container'], 0),
   ('Why does a superfluid’s effectively zero viscosity allow it to flow through extremely narrow channels that would completely block an ordinary liquid?', ['Without internal friction resisting its motion, a superfluid can pass through microscopic gaps that would otherwise dissipate the flow of a normal viscous fluid', 'A superfluid always has significantly higher viscosity than an ordinary liquid, making narrow-channel flow more difficult', 'Viscosity has no connection to how easily a fluid can pass through narrow spaces', 'This concept has no relevance to understanding the unusual behaviour of superfluids'], 0),
   ('Why do physicists study superfluidity as an example of a macroscopic quantum phenomenon?', ['Superfluid behaviour arises from quantum effects that become observable at a large, everyday scale rather than remaining confined to individual particles', 'Superfluidity has no connection to quantum mechanics of any kind', 'Quantum phenomena are never observable at any macroscopic, everyday scale', 'This concept has no relevance to the study of low-temperature physics'], 0)])]),

day(64, [
E('Media Analysis: The Language of Political Speechwriting',
  'Grade 12 English strand: political speechwriting relies on deliberate rhetorical techniques -- including repetition, parallel structure, and carefully chosen imagery -- to build emotional resonance and persuade an audience toward a specific position.',
  [('Political speechwriting relies on deliberate rhetorical techniques, including repetition and parallel ___.', ['Structure', 'A concept entirely unrelated to persuasive rhetorical technique', 'Silence, with no connection to spoken rhetorical devices', 'Punctuation exclusively, with no connection to sentence structure'], 0),
   ('Political speeches often use carefully chosen ___ to build emotional resonance with an audience.', ['Imagery', 'Statistics exclusively, with no connection to emotional appeal', 'A concept unrelated to persuasive speechwriting', 'Only technical jargon, with no emotional resonance intended'], 0),
   ('Which is an example of parallel structure in a political speech?', ['Repeating the same grammatical pattern across a series of related phrases', 'Using a completely different sentence structure in every single sentence', 'A technique entirely unrelated to speechwriting', 'Avoiding any form of repetition throughout the entire speech'], 0),
   ('Why might a speechwriter use the rhetorical device of repetition, such as repeating a key phrase throughout a speech?', ['Repetition reinforces a central idea, making it more memorable and emotionally resonant for the audience', 'Repetition always weakens the persuasive impact of a political speech', 'This rhetorical device has no connection to how an audience experiences a speech', 'This concept has no relevance to analyzing political rhetoric'], 0),
   ('Why is analyzing the rhetorical techniques of political speeches a valuable media literacy skill for Grade 12 students?', ['It builds the critical awareness needed to recognize how persuasive language shapes public opinion, supporting more informed civic engagement', 'Analyzing political rhetoric has no connection to developing informed, critical citizens', 'Political speeches never rely on any deliberate persuasive technique', 'This concept has no relevance to media literacy education'], 0)]),
AF('Functions: The Envelope of a Family of Curves',
   'Grade 12 Advanced Functions strand: a family of curves is generated by varying a parameter in a function’s equation, and the envelope of that family is a curve tangent to every member of the family, tracing the boundary of the region they sweep out.',
   [('A family of curves is generated by varying a ___ in a function’s equation.', ['Parameter', 'Colour, with no connection to a function’s equation', 'A concept unrelated to generating related curves', 'Coordinate axis, which does not vary within a single family of curves'], 0),
    ('The envelope of a family of curves is a curve ___ to every member of the family.', ['Tangent', 'Perpendicular, an inaccurate description of an envelope curve', 'A concept unrelated to describing a family of curves', 'Parallel, an inaccurate description of an envelope curve'], 0),
    ('The envelope of a family of curves traces the ___ of the region they sweep out.', ['Boundary', 'Exact centre point, with no connection to the swept region’s edge', 'A concept unrelated to describing the envelope', 'Area, a numerical value rather than a traced curve'], 0),
    ('Why might the trajectories of projectiles launched at the same speed but different angles form a family of curves with a describable envelope?', ['Varying the launch angle while keeping speed fixed generates a family of parabolic paths, and the outer boundary they collectively sweep out forms the envelope curve', 'Projectile trajectories launched at different angles never share any common mathematical relationship', 'The envelope of a family of curves has no connection to any physical or real-world scenario', 'This concept has no relevance to understanding families of related functions'], 0),
    ('Why is the concept of an envelope curve a useful extension of a Grade 12 student’s understanding of families of functions?', ['It shows how varying a single parameter across many related curves can generate a meaningful new boundary curve, deepening insight into how functions relate to one another', 'Families of curves generated by a varying parameter have no useful mathematical properties worth studying', 'An envelope curve can never be meaningfully defined for any family of functions', 'This concept has no relevance to a broader understanding of functions'], 0)]),
C('Calculus: Jerk -- The Derivative of Acceleration',
  'Grade 12 Calculus strand: jerk is the rate of change of acceleration with respect to time, found by differentiating the acceleration function, and it is used to describe how abruptly acceleration itself is changing.',
  [('Jerk is the rate of change of acceleration with respect to ___.', ['Time', 'Position exclusively, with no connection to how acceleration changes over time', 'A concept unrelated to describing motion', 'Velocity exclusively, rather than acceleration'], 0),
   ('Jerk is found by ___ the acceleration function.', ['Differentiating', 'Integrating, the opposite calculus operation', 'A concept unrelated to relating jerk to acceleration', 'Multiplying by a constant, with no calculus operation involved'], 0),
   ('Jerk describes how abruptly ___ itself is changing.', ['Acceleration', 'Position exclusively, with no connection to acceleration', 'A concept unrelated to describing changes in motion', 'Time itself, which does not change in this context'], 0),
   ('Why might engineers designing an elevator or a roller coaster be concerned with minimizing jerk, not just controlling acceleration?', ['A sudden, large jerk can feel physically uncomfortable or jarring to passengers, even if the acceleration itself stays within a reasonable range', 'Jerk has no connection to how passengers physically experience a ride’s motion', 'Minimizing acceleration alone always guarantees a smooth, comfortable ride with no further consideration needed', 'This concept has no relevance to designing vehicles or mechanical systems'], 0),
   ('Why does jerk represent the third derivative of an object’s position function with respect to time?', ['Velocity is the first derivative of position, acceleration is the second derivative, and jerk, being the derivative of acceleration, is therefore the third', 'Jerk is unrelated to position, velocity, or acceleration in any mathematical sense', 'The relationship between position, velocity, acceleration, and jerk has no connection to derivatives', 'This concept has no relevance to understanding rates of change in the study of motion'], 0)]),
P('Physics: Ferromagnetism and Magnetic Domains',
  'Grade 12 Physics strand: ferromagnetic materials contain regions called magnetic domains, in which atomic magnetic moments align in the same direction, and a material becomes strongly magnetized when an external field aligns these domains together.',
  [('Ferromagnetic materials contain regions called magnetic ___, in which atomic magnetic moments align in the same direction.', ['Domains', 'Voids, regions with no atomic magnetic moments present at all', 'A concept unrelated to ferromagnetism', 'Circuits, a concept unrelated to describing atomic-level magnetic alignment'], 0),
   ('A ferromagnetic material becomes strongly magnetized when an external field aligns its magnetic domains ___.', ['Together', 'Into a completely random, disordered arrangement', 'A concept unrelated to how ferromagnetism works', 'In directions that oppose the external field at every point'], 0),
   ('Which of these is an example of a common ferromagnetic material?', ['Iron', 'Wood, which is not a ferromagnetic material', 'A material entirely unrelated to magnetism', 'Glass, which is not a ferromagnetic material'], 0),
   ('Why does an unmagnetized piece of iron have no overall external magnetic field, even though it is made of a ferromagnetic material?', ['Its magnetic domains typically point in many different, randomly oriented directions, causing their individual magnetic effects to cancel out overall', 'An unmagnetized ferromagnetic material always has all of its domains already perfectly aligned', 'Magnetic domains have no connection to whether a ferromagnetic material exhibits an overall external field', 'This concept has no relevance to understanding why some materials are magnetic and others are not'], 0),
   ('Why can heating a ferromagnetic material above a certain temperature, called the Curie temperature, cause it to lose its magnetism?', ['Sufficient thermal energy disrupts the alignment of magnetic domains, randomizing their orientation and eliminating the material’s net magnetic effect', 'Heating a ferromagnetic material always strengthens the alignment of its magnetic domains', 'Temperature has no established relationship to the magnetic properties of a ferromagnetic material', 'This concept has no relevance to understanding the behaviour of magnetic materials'], 0)])]),

day(65, [
E('Writing: The Personal Essay of Intellectual Formation',
  'Grade 12 English strand: an essay of intellectual formation traces how a specific idea, book, mentor, or experience reshaped the writer’s thinking, using reflective narrative to show the process of a changing mind rather than simply stating a conclusion.',
  [('An essay of intellectual formation traces how a specific idea, book, mentor, or experience reshaped the writer’s ___.', ['Thinking', 'Physical appearance, a concept unrelated to intellectual change', 'A concept unrelated to this type of personal essay', 'Financial circumstances exclusively, with no connection to ideas'], 0),
   ('This type of essay uses reflective narrative to show the process of a ___ mind.', ['Changing', 'Completely fixed, with no capacity for growth or change', 'A concept unrelated to intellectual reflection', 'Empty, with no ideas present before or after the experience'], 0),
   ('An essay of intellectual formation typically avoids simply stating a ___, favouring the process of change instead.', ['Conclusion', 'Question, since raising questions is central to this essay form', 'A concept unrelated to how this essay is typically structured', 'Title, which has no bearing on the essay’s central content'], 0),
   ('Why might this type of essay focus on a specific, concrete moment of realization rather than a vague, general statement of belief?', ['A specific, vivid moment allows the reader to witness the actual process of changing thought, making the reflection feel genuine and earned rather than abstract', 'A vague, general statement is always more effective than a specific moment in this type of essay', 'The specific details of a formative moment have no bearing on how convincing a reflective essay feels', 'This concept has no relevance to writing an effective essay of intellectual formation'], 0),
   ('Why is this type of reflective, process-oriented essay considered valuable preparation for university application writing and beyond?', ['It develops the ability to reflect honestly and specifically on one’s own intellectual growth, a skill valued in both academic admissions writing and ongoing scholarly work', 'This type of essay has no connection to skills needed for university application writing', 'Reflective writing about intellectual growth has no relevance to any future academic context', 'This concept has no relevance to developing mature, reflective writing skills'], 0)]),
AF('Functions: Continued Fractions -- An Alternative Representation',
   'Grade 12 Advanced Functions strand: a continued fraction expresses a number as a whole number plus a fraction whose denominator is itself a sum involving another fraction, offering an alternative way to represent and approximate real numbers.',
   [('A continued fraction expresses a number as a whole number plus a fraction whose denominator is itself a sum involving another ___.', ['Fraction', 'Whole number exclusively, with no further fraction involved', 'A concept unrelated to this method of representing numbers', 'Radical expression exclusively, with no connection to fractions'], 0),
    ('Continued fractions offer an alternative way to represent and ___ real numbers.', ['Approximate', 'Permanently erase, with no way to recover the original value', 'A concept unrelated to continued fractions', 'Ignore, with no meaningful mathematical use'], 0),
    ('A continued fraction that terminates after a finite number of steps represents a ___ number.', ['Rational', 'Irrational, a type of number requiring an infinite continued fraction', 'A concept unrelated to continued fractions', 'Imaginary, a type of number unrelated to continued fraction representation'], 0),
    ('Why might a continued fraction provide a particularly good rational approximation of an irrational number like pi?', ['Truncating a continued fraction at successive stages tends to produce increasingly accurate rational approximations compared to many other approximation methods', 'Continued fractions never provide any useful approximation of an irrational number', 'Rational approximations of irrational numbers have no connection to continued fraction representation', 'This concept has no relevance to approximating real numbers'], 0),
    ('Why is exploring continued fractions a valuable extension of a Grade 12 student’s understanding of how numbers can be represented?', ['It reveals an alternative structure to the familiar decimal system, deepening insight into the properties of rational and irrational numbers', 'Continued fractions have no meaningful connection to understanding the properties of numbers', 'Decimal representation is the only meaningful way any real number can ever be expressed', 'This concept has no relevance to broadening a student’s mathematical understanding'], 0)]),
C('Calculus: The Mean Value Theorem for Integrals',
  'Grade 12 Calculus strand: the Mean Value Theorem for Integrals guarantees that a continuous function on a closed interval attains its average value at least once within that interval, connecting the definite integral to a specific function value.',
  [('The Mean Value Theorem for Integrals guarantees that a continuous function on a closed interval attains its ___ value at least once within that interval.', ['Average', 'Maximum value exclusively, with no connection to the function’s average behaviour', 'A concept unrelated to this theorem', 'Minimum value exclusively, with no connection to the function’s average behaviour'], 0),
   ('The Mean Value Theorem for Integrals connects the definite integral to a specific ___ value.', ['Function', 'Constant term exclusively, with no connection to the function itself', 'A concept unrelated to this theorem', 'Derivative value exclusively, a concept associated with a different mean value theorem'], 0),
   ('For this theorem to apply, the function in question must be ___ on the given closed interval.', ['Continuous', 'Undefined at every point within the interval', 'A concept unrelated to the conditions of this theorem', 'Discontinuous at every single point within the interval'], 0),
   ('Why does the Mean Value Theorem for Integrals guarantee the existence of a point where the function equals its average value, rather than simply approximating it?', ['Because the function is continuous, the Intermediate Value Theorem ensures it must actually attain every value between its minimum and maximum, including its average', 'This theorem only ever provides a rough approximation, never guaranteeing an exact point of equality', 'Continuity has no connection to whether a function attains a specific value within an interval', 'This concept has no relevance to understanding definite integrals'], 0),
   ('Why is the Mean Value Theorem for Integrals a useful conceptual bridge between the definite integral and the idea of an average value?', ['It formally justifies interpreting a definite integral, divided by the interval’s length, as the function’s true average value over that interval', 'A definite integral has no meaningful connection to the concept of an average value', 'This theorem provides no useful interpretation of what a definite integral represents', 'This concept has no relevance to understanding the applications of integration'], 0)]),
P('Physics: Beta Decay and the Weak Nuclear Force',
  'Grade 12 Physics strand: beta decay is a type of radioactive decay in which a neutron transforms into a proton, releasing an electron and an antineutrino, a process mediated by the weak nuclear force.',
  [('In beta decay, a neutron transforms into a proton, releasing an electron and an ___.', ['Antineutrino', 'Alpha particle, a particle released in a different type of radioactive decay', 'A concept unrelated to beta decay', 'Additional proton, an inaccurate description of the particles released'], 0),
   ('Beta decay is a process mediated by the ___ nuclear force.', ['Weak', 'Strong, the force primarily responsible for holding the nucleus together', 'A concept unrelated to beta decay', 'Gravitational, a force with no meaningful role at the nuclear scale'], 0),
   ('After beta decay, the resulting nucleus has ___ proton(s) than before the decay.', ['One more', 'One fewer, an inaccurate description of the change', 'A concept unrelated to the outcome of beta decay', 'The same number of, with no change at all'], 0),
   ('Why was the existence of the antineutrino originally proposed to explain observations in beta decay, even before it was directly detected?', ['Without an additional particle carrying away some energy and momentum, the observed beta decay events appeared to violate the conservation of energy and momentum', 'The antineutrino was proposed with no connection to any experimental observation or conservation principle', 'Beta decay was always fully explained without needing to propose any additional particle', 'This concept has no relevance to the historical development of nuclear and particle physics'], 0),
   ('Why is beta decay classified separately from alpha decay in terms of the fundamental force responsible for the process?', ['Beta decay results from the weak nuclear force transforming a neutron into a proton, while alpha decay results primarily from the strong force and Coulomb repulsion ejecting a nuclear fragment', 'Beta decay and alpha decay are governed by exactly the same fundamental force with no meaningful distinction', 'The classification of decay types has no connection to which fundamental force is responsible', 'This concept has no relevance to understanding different types of radioactive decay'], 0)])]),

day(66, [
E('Literature: The Frame Narrative and Nested Storytelling',
  'Grade 12 English strand: a frame narrative encloses one or more inner stories within an outer, framing story, a structure used to control perspective, create thematic resonance between levels of narrative, and comment on the act of storytelling itself.',
  [('A frame narrative encloses one or more inner stories within an outer, ___ story.', ['Framing', 'Entirely unrelated, with no connection to the inner stories at all', 'A concept unrelated to this narrative structure', 'Deleted, meaning no outer story remains in the final text'], 0),
   ('The frame narrative structure can be used to create thematic resonance between different ___ of narrative.', ['Levels', 'Page numbers exclusively, with no connection to narrative meaning', 'A concept unrelated to how nested stories relate to each other', 'Fonts, a formatting choice unrelated to narrative structure'], 0),
   ('A frame narrative can be used by an author to comment on the act of ___ itself.', ['Storytelling', 'Punctuation exclusively, with no connection to narrative technique', 'A concept unrelated to how a frame narrative functions', 'Printing, a technical process unrelated to storytelling'], 0),
   ('Why might an author use a frame narrative to present a story that might otherwise seem implausible if told directly?', ['Presenting the story as being recounted by a character within a frame can add a layer of narrative distance that makes an extraordinary tale feel more credible', 'A frame narrative always makes an implausible story seem less believable to a reader', 'This narrative structure has no effect on how a reader perceives the credibility of a story', 'This concept has no connection to how narrative framing shapes reader response'], 0),
   ('Why is analyzing the relationship between an outer frame and its inner story considered a sophisticated literary skill at the Grade 12 level?', ['It requires tracking how meaning shifts and echoes between narrative levels, recognizing that the frame itself can be as significant as the story it contains', 'The outer frame of a narrative never has any meaningful relationship to its inner story', 'This type of analysis requires no attention to structure or narrative levels', 'This concept has no relevance to advanced literary analysis'], 0)]),
AF('Functions: The Logistic Function and S-Shaped Growth',
   'Grade 12 Advanced Functions strand: the logistic function models growth that starts nearly exponential but slows and levels off as it approaches a maximum sustainable value, producing a distinctive S-shaped curve.',
   [('The logistic function models growth that starts nearly exponential but slows and levels off as it approaches a maximum sustainable ___.', ['Value', 'Rate of change exclusively, with no connection to an upper limit', 'A concept unrelated to logistic growth', 'Starting point, a value that does not represent the growth ceiling'], 0),
    ('The graph of a logistic function produces a distinctive ___ shaped curve.', ['S', 'U, an inaccurate description of the logistic curve’s shape', 'A concept unrelated to describing the logistic function’s graph', 'V, an inaccurate description of the logistic curve’s shape'], 0),
    ('Unlike a purely exponential function, the logistic function includes a built-in ___ that growth approaches but does not exceed.', ['Upper limit', 'Starting value exclusively, with no connection to an eventual ceiling', 'A concept unrelated to how the logistic function differs from exponential growth', 'Negative boundary exclusively, an inaccurate description of this limit'], 0),
    ('Why might a logistic function be a more realistic model than a purely exponential function for describing the growth of a population in a limited environment?', ['A population’s growth is eventually constrained by limited resources, and the logistic function captures this slowing and levelling off as the population nears the environment’s capacity', 'An exponential function always provides a more realistic long-term model of population growth than a logistic function', 'A population’s growth is never affected or limited by the resources available in its environment', 'This concept has no relevance to modelling real-world growth processes'], 0),
    ('Why is the transition from near-exponential growth to a levelling plateau a defining mathematical feature of the logistic function?', ['This shift reflects the function’s built-in maximum value, which increasingly slows the rate of growth as the function’s value approaches that ceiling', 'The logistic function grows at a constant, unchanging rate throughout its entire domain', 'A levelling plateau has no connection to how the logistic function is mathematically defined', 'This concept has no relevance to distinguishing logistic growth from other growth models'], 0)]),
C('Calculus: Torricelli’s Trumpet -- An Infinite Surface, a Finite Volume',
  'Grade 12 Calculus strand: Torricelli’s Trumpet is a solid of revolution with a finite volume but an infinite surface area, a classic example illustrating that convergence and divergence of related integrals do not always align intuitively.',
  [('Torricelli’s Trumpet is a solid of revolution with a finite volume but an ___ surface area.', ['Infinite', 'Undefined, with no numerical relationship to the shape at all', 'A concept unrelated to this classic calculus example', 'Zero, an inaccurate description of the surface area'], 0),
   ('Torricelli’s Trumpet is a classic example illustrating that convergence and divergence of related integrals do not always align ___.', ['Intuitively', 'Identically, in every single case with no exceptions', 'A concept unrelated to this example’s significance', 'Numerically, in a way that contradicts the actual mathematical result'], 0),
   ('The shape of Torricelli’s Trumpet is generated by revolving a curve that ___ approaches the axis of revolution as it extends toward infinity.', ['Gradually', 'Never, since the curve moves further away from the axis as it extends', 'A concept unrelated to how the shape is generated', 'Immediately, reaching the axis at a single finite point'], 0),
   ('Why does Torricelli’s Trumpet’s volume integral converge to a finite value while its surface area integral diverges to infinity?', ['The functions describing volume and surface area involve the radius differently, causing the volume’s integrand to shrink quickly enough to converge while the surface area’s integrand does not', 'The volume and surface area integrals of this shape always converge or diverge together, with no possible distinction between them', 'Convergence and divergence of these two related integrals have no connection to how the underlying functions are defined', 'This concept has no relevance to understanding improper integrals'], 0),
   ('Why is Torricelli’s Trumpet often used as a thought-provoking example in an introduction to improper integrals and infinite solids?', ['It challenges the intuitive assumption that a shape requiring infinite material to coat could still be filled using only a finite amount of material, illustrating a genuinely surprising mathematical result', 'This example provides no meaningful insight into the behaviour of improper integrals', 'A solid’s volume and surface area are always intuitively predictable from one another', 'This concept has no relevance to deepening understanding of convergence in calculus'], 0)]),
P('Physics: The Casimir Effect and Vacuum Energy',
  'Grade 12 Physics strand: the Casimir effect is a measurable attractive force between two closely spaced, uncharged conductive plates, arising from restrictions on the quantum vacuum fluctuations permitted in the narrow gap between them.',
  [('The Casimir effect is a measurable attractive force between two closely spaced, ___ conductive plates.', ['Uncharged', 'Strongly positively charged, an inaccurate description of this effect', 'A concept unrelated to this quantum phenomenon', 'Strongly negatively charged, an inaccurate description of this effect'], 0),
   ('The Casimir effect arises from restrictions on the quantum vacuum ___ permitted in the narrow gap between two plates.', ['Fluctuations', 'Particles exclusively, a concept distinct from vacuum fluctuations', 'A concept unrelated to explaining the Casimir effect', 'Temperature, a property unrelated to the origin of this effect'], 0),
   ('As the gap between two plates exhibiting the Casimir effect narrows, the attractive force between them generally ___.', ['Increases', 'Disappears entirely, with no force present at a narrower gap', 'A concept unrelated to how this force depends on the gap’s width', 'Reverses direction, becoming a repulsive force at any narrower gap'], 0),
   ('Why does restricting the space between two conductive plates lead to a net attractive force, according to the explanation offered by quantum field theory?', ['Fewer vacuum fluctuation modes are permitted within the narrow gap compared to the unrestricted space outside, creating a pressure imbalance that pushes the plates together', 'Restricting the space between two plates always increases the number of permitted fluctuation modes within the gap', 'The Casimir effect has no connection to quantum field theory or vacuum fluctuations', 'This concept has no relevance to understanding forces that arise at extremely small scales'], 0),
   ('Why is the Casimir effect considered significant experimental evidence relevant to quantum field theory?', ['It demonstrates a measurable, real-world physical consequence of the vacuum fluctuations predicted by quantum field theory, connecting abstract theory to observable force', 'The Casimir effect provides no experimental support for any prediction made by quantum field theory', 'Vacuum fluctuations have never been connected to any measurable physical force', 'This concept has no relevance to modern theoretical physics'], 0)])]),

day(67, [
E('Writing: The Extended Definition Essay -- Defining an Abstract Concept',
  'Grade 12 English strand: an extended definition essay explores the meaning of an abstract concept, such as justice or courage, by examining its various dimensions through examples, comparisons, and consideration of what the concept is not.',
  [('An extended definition essay explores the meaning of an abstract concept, such as justice or ___.', ['Courage', 'A concrete physical object, unlike the abstract concepts typically explored', 'A concept unrelated to this type of essay', 'A specific date, a detail unrelated to defining an abstract concept'], 0),
   ('An extended definition essay examines a concept’s various dimensions through examples and ___.', ['Comparisons', 'A concept entirely unrelated to how this essay develops its definition', 'Only a single, brief dictionary quotation, with no further development', 'Random, disconnected facts with no relevance to the concept'], 0),
   ('One common strategy in an extended definition essay is considering what the concept ___.', ['Is not', 'Looks like physically, a strategy suited to concrete rather than abstract concepts', 'A concept unrelated to this essay’s typical strategies', 'Costs, a detail unrelated to defining most abstract concepts'], 0),
   ('Why might an extended definition essay use a specific narrative example to illustrate an abstract concept like courage?', ['A concrete example grounds an abstract idea in a relatable, vivid situation, helping the reader understand the concept’s nuance beyond a simple dictionary definition', 'A concrete example always makes an abstract concept harder for a reader to understand', 'Narrative examples have no useful role in developing an extended definition', 'This concept has no relevance to how an extended definition essay is typically structured'], 0),
   ('Why is defining an abstract concept through multiple approaches, rather than a single dictionary definition, considered more intellectually rigorous?', ['Abstract concepts often carry nuanced, sometimes contested meanings that a single brief definition cannot fully capture, so multiple approaches reveal a fuller understanding', 'A single dictionary definition always fully and adequately captures the meaning of any abstract concept', 'Abstract concepts never have multiple dimensions or nuanced meanings worth exploring', 'This concept has no relevance to writing a sophisticated definition essay'], 0)]),
AF('Introduction to Fourier Series -- Representing Functions as Sums of Waves',
   'Grade 12 Advanced Functions strand: a Fourier series expresses a periodic function as an infinite sum of sine and cosine functions of different frequencies, allowing complex periodic behaviour to be broken down into simpler wave components.',
   [('A Fourier series expresses a periodic function as an infinite sum of sine and ___ functions of different frequencies.', ['Cosine', 'Logarithmic, a type of function not used in constructing a Fourier series', 'A concept unrelated to representing periodic functions', 'Exponential, a type of function not primarily used in this representation'], 0),
    ('A Fourier series allows complex periodic behaviour to be broken down into simpler ___ components.', ['Wave', 'Polynomial, a type of component not used in a Fourier series', 'A concept unrelated to Fourier series representation', 'Matrix, a concept unrelated to this type of series'], 0),
    ('For a Fourier series to represent a function, that function must be ___.', ['Periodic', 'Entirely random, with no repeating pattern of any kind', 'A concept unrelated to the conditions for a Fourier series', 'Undefined at every single point in its domain'], 0),
    ('Why might a Fourier series be useful for analyzing a complicated periodic sound wave, such as a musical instrument’s tone?', ['Breaking the wave into its individual sine and cosine components reveals the specific frequencies present, corresponding to the fundamental pitch and its overtones', 'A Fourier series has no connection to analyzing sound waves or musical tones', 'A complicated sound wave can never be broken down into simpler wave components', 'This concept has no relevance to understanding periodic phenomena'], 0),
    ('Why is the idea of representing a complicated function as a sum of simpler sine and cosine waves considered a powerful mathematical tool?', ['It transforms a potentially difficult function into a structured combination of well-understood, simple periodic components, making analysis and further calculation more manageable', 'Representing a function as a sum of sine and cosine waves never simplifies any subsequent analysis', 'Sine and cosine functions have no useful role in representing more complicated periodic functions', 'This concept has no relevance to advanced mathematical analysis'], 0)]),
C('Calculus: The Gamma Function -- Extending the Factorial',
  'Grade 12 Calculus strand: the Gamma function extends the factorial operation, normally defined only for non-negative integers, to a broader domain using an improper integral, so that non-integer and even complex inputs produce a meaningful result.',
  [('The Gamma function extends the factorial operation to a broader domain using an ___.', ['Improper integral', 'Only basic multiplication, with no integral involved', 'A concept unrelated to defining the Gamma function', 'A finite sum, with no integral involved whatsoever'], 0),
   ('The factorial operation is normally defined only for non-negative ___.', ['Integers', 'Irrational numbers exclusively, with no connection to the standard factorial', 'A concept unrelated to the standard definition of factorial', 'Negative numbers exclusively, which the standard factorial does not include'], 0),
   ('The Gamma function allows non-integer and even ___ inputs to produce a meaningful result.', ['Complex', 'Undefined, meaning no meaningful result is produced at all', 'A concept unrelated to the extended domain of the Gamma function', 'Only negative even integers, an inaccurate description of this extension'], 0),
   ('Why is an improper integral, rather than a simple repeated multiplication, needed to extend the factorial to non-integer values?', ['Repeated multiplication only makes direct sense for whole-number counts, while an integral-based definition can be evaluated continuously across a much broader range of inputs', 'Repeated multiplication already works perfectly well for extending the factorial to any non-integer input', 'An improper integral has no connection to extending mathematical operations beyond their original domain', 'This concept has no relevance to understanding the Gamma function’s definition'], 0),
   ('Why is the Gamma function considered an important bridge between the introductory calculus studied in Grade 12 and more advanced mathematical topics?', ['It shows how a familiar, elementary operation can be meaningfully generalized using integral calculus, a pattern of extension that recurs throughout more advanced mathematics', 'The Gamma function has no further relevance beyond a single specific calculation involving factorials', 'Generalizing familiar operations using calculus is never a useful or recurring theme in advanced mathematics', 'This concept has no relevance to preparing for further mathematical study'], 0)]),
P('Physics: Bose-Einstein Condensates -- A Fifth State of Matter',
  'Grade 12 Physics strand: a Bose-Einstein condensate forms when a dilute gas of certain particles is cooled to temperatures near absolute zero, causing a large fraction of the particles to occupy the same lowest-energy quantum state simultaneously.',
  [('A Bose-Einstein condensate forms when a dilute gas is cooled to temperatures near ___.', ['Absolute zero', 'Room temperature, a temperature far too high for this phenomenon to occur', 'A concept unrelated to this state of matter', 'The boiling point of water, a temperature far too high for this phenomenon'], 0),
   ('In a Bose-Einstein condensate, a large fraction of particles occupy the same lowest-energy quantum ___ simultaneously.', ['State', 'Location exclusively, a description that does not fully capture this quantum phenomenon', 'A concept unrelated to describing this state of matter', 'Charge, a property unrelated to this collective quantum behaviour'], 0),
   ('A Bose-Einstein condensate is sometimes described as a distinctive additional state of matter beyond solid, liquid, gas, and ___.', ['Plasma', 'Vacuum, which is not typically classified as a state of matter', 'A concept unrelated to classifying states of matter', 'Crystal, a description of solid structure rather than a distinct state of matter'], 0),
   ('Why does achieving a Bose-Einstein condensate require cooling particles to such extraordinarily low temperatures?', ['At higher temperatures, particles have enough thermal energy to occupy many different energy states, so extreme cooling is needed to make the shared lowest-energy state dominate', 'Temperature has no meaningful connection to which quantum energy states particles occupy', 'A Bose-Einstein condensate can form just as easily at room temperature as near absolute zero', 'This concept has no relevance to understanding this exotic state of matter'], 0),
   ('Why do physicists consider Bose-Einstein condensates valuable for studying quantum mechanical behaviour?', ['Because a large number of particles behave coherently as a single quantum entity, effects that are normally confined to individual particles become observable on a larger, more accessible scale', 'Bose-Einstein condensates provide no useful opportunity to observe or study quantum mechanical behaviour', 'Quantum behaviour is always equally observable regardless of temperature or particle number', 'This concept has no relevance to modern experimental physics'], 0)])]),

day(68, [
E('Literature: The Confessional Mode in Poetry and Prose',
  'Grade 12 English strand: confessional literature presents deeply personal, often taboo or painful material -- including mental illness, trauma, or family conflict -- with a directness that challenges earlier conventions of poetic and narrative restraint.',
  [('Confessional literature presents deeply personal, often taboo or painful material with a directness that challenges earlier conventions of poetic and narrative ___.', ['Restraint', 'Punctuation, a technical concern unrelated to this literary mode’s defining feature', 'A concept unrelated to the confessional mode', 'Rhyme scheme exclusively, a formal feature unrelated to confessional content'], 0),
   ('Which is an example of subject matter commonly explored in confessional literature?', ['Mental illness, trauma, or family conflict', 'Only cheerful, uncomplicated everyday events with no emotional weight', 'A subject entirely unrelated to personal experience', 'Purely fictional events with no connection to the author’s own life'], 0),
   ('The confessional mode is notable for its directness in departing from earlier conventions of ___.', ['Restraint', 'Punctuation exclusively, a technical rather than thematic convention', 'A concept unrelated to how this mode differs from earlier writing', 'Grammar exclusively, a technical rather than thematic convention'], 0),
   ('Why might confessional literature have been considered controversial or boundary-pushing when it first gained prominence?', ['It directly addressed personal and often painful subject matter that had previously been considered too private or taboo for public literary expression', 'Confessional literature has never addressed any subject matter previously considered private or taboo', 'This literary mode was always immediately accepted with no controversy of any kind', 'This concept has no relevance to understanding the historical reception of confessional writing'], 0),
   ('Why does confessional writing require a careful balance between raw honesty and deliberate literary craft?', ['Without craft, deeply personal material can feel unshaped or self-indulgent, while skilled shaping transforms raw experience into work with broader resonance and meaning', 'Confessional writing requires no literary craft whatsoever, relying only on raw, unshaped honesty', 'Literary craft and personal honesty are always entirely incompatible with one another', 'This concept has no relevance to understanding how confessional literature achieves its effects'], 0)]),
AF('Functions: Benford’s Law and the Distribution of Leading Digits',
   'Grade 12 Advanced Functions strand: Benford’s Law describes the surprising, non-uniform frequency with which each digit from 1 to 9 appears as the leading digit in many naturally occurring numerical data sets, following a pattern based on logarithms.',
   [('Benford’s Law describes the surprising, non-uniform frequency with which each digit appears as the ___ digit in many naturally occurring data sets.', ['Leading', 'Final, an inaccurate description of the digit position described by Benford’s Law', 'A concept unrelated to this statistical pattern', 'Middle, an inaccurate description of the digit position described by Benford’s Law'], 0),
    ('The pattern described by Benford’s Law is based on a formula involving ___.', ['Logarithms', 'Only simple addition, with no logarithmic relationship involved', 'A concept unrelated to how Benford’s Law is mathematically defined', 'Basic multiplication exclusively, with no logarithmic component'], 0),
    ('According to Benford’s Law, the digit ___ appears as a leading digit more frequently than any other digit in many natural data sets.', ['1', '9, the digit predicted to appear least frequently under Benford’s Law', 'A concept unrelated to the specific predictions of Benford’s Law', '5, a digit with only a moderate predicted frequency under Benford’s Law'], 0),
    ('Why is Benford’s Law sometimes used by forensic accountants and auditors to help detect potentially fabricated financial data?', ['Genuinely occurring data sets tend to follow the predictable, non-uniform pattern of leading digits described by Benford’s Law, so significant deviations can raise suspicion about how numbers were generated', 'Benford’s Law has no practical application in detecting unusual patterns in financial data', 'Fabricated numbers always naturally follow the exact same leading-digit pattern as genuinely occurring data', 'This concept has no relevance to any real-world application of mathematics'], 0),
    ('Why is Benford’s Law considered a surprising result to many people encountering it for the first time?', ['Intuition might suggest each leading digit from 1 to 9 should appear with roughly equal frequency, but the actual observed pattern is strikingly uneven and logarithmic in structure', 'Benford’s Law confirms the intuitive expectation that each leading digit occurs with exactly equal frequency', 'This law has no connection to how digits are distributed in any real numerical data', 'This concept has no relevance to understanding surprising results in mathematics'], 0)]),
C('Calculus: Escape Velocity -- An Application of Integration',
  'Grade 12 Calculus strand: escape velocity, the minimum speed needed for an object to break free of a planet’s gravitational pull without further propulsion, can be derived by integrating the work done against a gravitational force that weakens with distance.',
  [('Escape velocity is the minimum speed needed for an object to break free of a planet’s gravitational pull without further ___.', ['Propulsion', 'Air resistance, a factor not central to this idealized calculation', 'A concept unrelated to escape velocity', 'Rotation, a factor not central to this idealized calculation'], 0),
   ('Escape velocity can be derived by integrating the work done against a gravitational force that weakens with ___.', ['Distance', 'Time exclusively, rather than distance from the planet', 'A concept unrelated to how escape velocity is derived', 'Mass of the escaping object exclusively, rather than distance'], 0),
   ('The gravitational force between two objects, used in the escape velocity derivation, decreases as the distance between them ___.', ['Increases', 'Decreases, an inaccurate description of this relationship', 'A concept unrelated to gravitational force', 'Remains exactly constant, regardless of the distance involved'], 0),
   ('Why is integration necessary to calculate the total work needed to escape a planet’s gravity, rather than treating the gravitational force as constant throughout the calculation?', ['Since gravitational force changes continuously with distance from the planet, the work must be accumulated over infinitesimally small changes in distance to be calculated accurately', 'Gravitational force remains exactly constant at every distance from a planet, making integration unnecessary', 'Integration has no connection to calculating work done against a distance-dependent force', 'This concept has no relevance to deriving escape velocity'], 0),
   ('Why is the concept of escape velocity, derived using integration, significant for understanding space exploration?', ['It defines the minimum energy threshold a spacecraft must overcome to leave a planet’s gravitational influence, directly informing the propulsion required for a mission', 'Escape velocity has no practical relevance to planning or understanding space missions', 'A spacecraft never needs to overcome any gravitational threshold to leave a planet', 'This concept has no connection to applying calculus to real-world physical problems'], 0)]),
P('Physics: Quantum Entanglement and Non-Local Correlations',
  'Grade 12 Physics strand: quantum entanglement is a phenomenon in which two or more particles become correlated such that measuring a property of one instantaneously determines the corresponding property of the other, regardless of the distance separating them.',
  [('Quantum entanglement is a phenomenon in which measuring a property of one particle instantaneously determines the corresponding property of ___.', ['The other particle', 'An entirely unrelated particle with no established connection', 'A concept unrelated to quantum entanglement', 'Only the measuring instrument itself, with no connection to any second particle'], 0),
   ('The correlation between entangled particles holds regardless of the ___ separating them.', ['Distance', 'Colour, a property unrelated to the distance-independence of entanglement', 'A concept unrelated to describing entangled particles', 'Temperature, a property unrelated to the distance-independence of entanglement'], 0),
   ('Quantum entanglement was famously discussed in a thought experiment questioning whether quantum mechanics could be a ___ theory.', ['Complete', 'Purely classical, a description inconsistent with quantum mechanics', 'A concept unrelated to this historical debate', 'Entirely disproven, an inaccurate description of the debate’s outcome'], 0),
   ('Why does quantum entanglement raise questions about locality, the classical assumption that an object is only directly influenced by its immediate surroundings?', ['Measuring one entangled particle appears to instantaneously affect the determined state of its distant partner, challenging the classical expectation that influences require time to travel across space', 'Quantum entanglement fully confirms every assumption of classical locality with no challenge to those assumptions', 'Entangled particles have no correlated properties of any kind', 'This concept has no relevance to understanding the foundational questions raised by quantum mechanics'], 0),
   ('Why is quantum entanglement considered foundational to emerging technologies such as quantum computing and quantum cryptography?', ['The correlated, non-classical relationship between entangled particles can be harnessed to process or transmit information in ways not possible using purely classical systems', 'Quantum entanglement has no practical application to any current or emerging technology', 'Quantum computing and quantum cryptography rely entirely on classical, non-quantum principles', 'This concept has no relevance to modern applied physics research'], 0)])]),

day(69, [
E('Writing: The Public Letter -- Rhetoric for a Named Audience',
  'Grade 12 English strand: a public letter is addressed to a specific named audience, such as a government official or organization, while anticipating a wider readership, requiring a writer to balance direct address with broader persuasive appeal.',
  [('A public letter is addressed to a specific named audience while anticipating a ___ readership.', ['Wider', 'Nonexistent, since a public letter reaches no one beyond its named recipient', 'A concept unrelated to how a public letter functions', 'Identical, single-person readership with no broader audience at all'], 0),
   ('Writing an effective public letter requires balancing direct address with broader ___ appeal.', ['Persuasive', 'A concept entirely unrelated to the purpose of a public letter', 'Purely decorative, with no connection to convincing any reader', 'Financial, a concern unrelated to the letter’s persuasive purpose'], 0),
   ('Which is an example of an appropriate named recipient for a public letter?', ['A government official or organization', 'A close personal friend, in an entirely private context', 'A recipient entirely unrelated to the concept of a public letter', 'No recipient at all, since a public letter requires no named audience'], 0),
   ('Why might a writer use formal, precise language when addressing a specific official in a public letter, even while writing partly for a broader audience?', ['Formal precision signals credibility and seriousness to the named recipient, while remaining accessible and persuasive enough to resonate with a broader public readership', 'Formal language always alienates a public letter’s broader intended readership', 'The tone and precision of language have no bearing on how a public letter is received', 'This concept has no relevance to writing an effective public letter'], 0),
   ('Why is the public letter considered a historically significant form of persuasive civic writing?', ['It has repeatedly allowed writers to hold specific figures or institutions publicly accountable while simultaneously shaping broader public opinion on an issue', 'Public letters have never played any meaningful role in civic or political discourse', 'This form of writing has no persuasive function beyond its single named recipient', 'This concept has no relevance to understanding the history of persuasive writing'], 0)]),
AF('Functions: The Mandelbrot Set and Iterated Complex Functions',
   'Grade 12 Advanced Functions strand: the Mandelbrot set is generated by repeatedly applying a simple complex-number function to itself and testing whether the resulting sequence of values stays bounded, producing a boundary of extraordinary geometric complexity.',
   [('The Mandelbrot set is generated by repeatedly applying a simple complex-number function to itself and testing whether the resulting sequence of values stays ___.', ['Bounded', 'Exactly zero, in every single case regardless of the starting value', 'A concept unrelated to how the Mandelbrot set is generated', 'Undefined, with no meaningful sequence produced at all'], 0),
    ('The boundary of the Mandelbrot set is known for its extraordinary geometric ___.', ['Complexity', 'Simplicity, an inaccurate description of this famous boundary', 'A concept unrelated to describing the Mandelbrot set', 'Uniformity, an inaccurate description of this intricate boundary'], 0),
    ('Generating the Mandelbrot set involves repeatedly applying a function to its own previous ___.', ['Output', 'Colour, a property unrelated to the iterative process involved', 'A concept unrelated to this iterative process', 'Original starting input exclusively, ignoring all intermediate outputs'], 0),
    ('Why does the process of repeatedly feeding a function’s output back in as its next input, as used in generating the Mandelbrot set, sometimes lead to values that grow without bound?', ['Depending on the starting complex number, the repeated squaring and adding involved in the function can cause the sequence of resulting values to grow larger and larger rather than settle down', 'This iterative process always produces a sequence of values that stays exactly the same at every step', 'Feeding a function’s output back into itself has no connection to whether resulting values grow or stay bounded', 'This concept has no relevance to understanding how the Mandelbrot set is generated'], 0),
    ('Why is the Mandelbrot set often cited as an example of complex, intricate structure arising from a remarkably simple underlying rule?', ['A single, simple iterative formula involving complex numbers produces a boundary of endless, self-similar detail, illustrating how simple rules can generate immense complexity', 'The Mandelbrot set requires an extremely complicated underlying formula to produce its distinctive boundary', 'Simple mathematical rules can never produce genuinely intricate or complex results', 'This concept has no relevance to understanding the relationship between simple rules and complex outcomes'], 0)]),
C('Calculus: The Catenary Revisited -- Calculus of Hanging Structures',
  'Grade 12 Calculus strand: analyzing the equilibrium shape of a flexible, uniformly dense cable hanging under its own weight leads to a differential equation whose solution, the catenary curve, has practical applications in the engineering of arches and suspension structures.',
  [('Analyzing the equilibrium shape of a flexible, uniformly dense cable hanging under its own weight leads to a ___ equation.', ['Differential', 'Purely linear equation, a description that understates this problem’s complexity', 'A concept unrelated to modelling a hanging cable', 'Quadratic equation exclusively, a description that does not capture this problem’s calculus-based nature'], 0),
   ('The solution to the hanging cable problem is known as the ___ curve.', ['Catenary', 'Parabolic, a curve visually similar but mathematically distinct from the true solution', 'A concept unrelated to the shape formed by a hanging cable', 'Circular, an inaccurate description of the resulting curve’s shape'], 0),
   ('The catenary curve has practical applications in the engineering of arches and ___ structures.', ['Suspension', 'Structures with no connection to hanging or supported weight of any kind', 'A concept unrelated to real-world applications of the catenary', 'Purely decorative structures, with no engineering or structural relevance'], 0),
   ('Why is the catenary curve, rather than a parabola, the mathematically correct shape for a cable hanging freely under only its own weight?', ['The differential equation modelling the forces acting along a uniformly loaded, freely hanging cable produces a hyperbolic cosine solution, which is distinct from a parabola even though the two curves can look visually similar', 'A parabola and a catenary are mathematically identical curves in every possible case', 'The shape of a hanging cable has no defined mathematical relationship to any differential equation', 'This concept has no relevance to understanding the calculus of hanging structures'], 0),
   ('Why might an architect deliberately design an arch based on an inverted catenary curve?', ['An inverted catenary distributes the structure’s weight as pure compression along the arch, avoiding the bending stress that a different curve’s shape might introduce', 'The specific shape of an arch has no bearing on how weight or structural stress is distributed', 'A catenary-based arch always experiences significantly more structural stress than any other arch shape', 'This concept has no relevance to real-world applications of calculus in architecture and engineering'], 0)]),
P('Physics: Hawking Radiation and Black Hole Thermodynamics',
  'Grade 12 Physics strand: Hawking radiation is theoretical thermal radiation predicted to be emitted by black holes due to quantum effects near the event horizon, suggesting that black holes are not perfectly black but instead slowly lose mass over time.',
  [('Hawking radiation is theoretical thermal radiation predicted to be emitted by black holes due to quantum effects near the ___.', ['Event horizon', 'Exact geometric centre of the black hole, an inaccurate location for this predicted effect', 'A concept unrelated to this theoretical prediction', 'Outer edge of the observable universe, an inaccurate description unrelated to a black hole'], 0),
   ('Hawking radiation suggests that black holes slowly lose ___ over time.', ['Mass', 'Electric charge exclusively, with no connection to mass loss', 'A concept unrelated to this theoretical prediction', 'Angular momentum exclusively, with no connection to mass loss'], 0),
   ('Hawking radiation implies that black holes are not perfectly ___, contrary to their name.', ['Black', 'Massive, a property Hawking radiation does not directly contradict', 'A concept unrelated to this theoretical prediction', 'Round, a property Hawking radiation does not directly contradict'], 0),
   ('Why might a smaller black hole be predicted to emit Hawking radiation more intensely than a much larger black hole?', ['The predicted temperature associated with Hawking radiation increases as a black hole’s mass decreases, so smaller black holes are theorized to radiate more intensely and evaporate faster', 'Hawking radiation intensity has no established theoretical relationship to a black hole’s mass or size', 'Larger black holes are always predicted to emit more intense Hawking radiation than smaller ones', 'This concept has no relevance to theoretical predictions about black hole behaviour'], 0),
   ('Why is Hawking radiation considered a significant theoretical bridge between general relativity and quantum mechanics?', ['It emerges from applying quantum field theory concepts to the curved spacetime near a black hole’s event horizon, connecting two major branches of modern physics that are otherwise difficult to unify', 'Hawking radiation has no connection to either general relativity or quantum mechanics', 'General relativity and quantum mechanics have never been meaningfully connected through any theoretical prediction', 'This concept has no relevance to understanding major unresolved questions in modern physics'], 0)])]),

day(70, [
E('Review: Grade 12 English -- Days 61-69 Synthesis',
  'Grade 12 English strand review: this lesson revisits magical realism, the epistolary and archival narrative form, the bildungsroman, the confessional mode in poetry and prose, and the public letter from Days 61-69.',
  [('Magical realism presents fantastical or supernatural events within an otherwise ___ setting.', ['Realistic', 'Entirely fictional, with no connection to any recognizable world', 'A concept unrelated to literary mode', 'Purely scientific, with no room for the impossible'], 0),
   ('An epistolary or archival narrative tells a story through documents such as letters, diary entries, or ___.', ['Records', 'A single, continuous third-person account with no documents involved', 'A concept unrelated to this narrative form', 'Illustrations exclusively, with no written text at all'], 0),
   ('A bildungsroman traces a protagonist’s psychological and moral development from youth to ___.', ['Maturity', 'A state of complete stagnation, with no development at all', 'A concept unrelated to this literary form', 'Infancy, a reversal of typical development'], 0),
   ('Confessional literature presents deeply personal, often taboo or painful material with a directness that challenges earlier conventions of poetic and narrative ___.', ['Restraint', 'Punctuation, a technical concern unrelated to this literary mode’s defining feature', 'A concept unrelated to the confessional mode', 'Rhyme scheme exclusively, a formal feature unrelated to confessional content'], 0),
   ('Why is it useful to review magical realism, epistolary narrative, the bildungsroman, and confessional writing together?', ['These related English concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in English', 'Each topic must be learned in complete isolation'], 0)]),
AF('Review: Grade 12 Advanced Functions -- Days 61-69 Synthesis',
   'Grade 12 Advanced Functions strand review: this lesson revisits spherical coordinates, oblique asymptotes, the logistic function, Benford’s Law, and the Mandelbrot set from Days 61-69.',
   [('Spherical coordinates locate a point in three-dimensional space using a radial distance and ___ angles.', ['Two', 'Zero, since spherical coordinates use no angles at all', 'A concept unrelated to describing a point’s position', 'Four, an inaccurate number of angles for this coordinate system'], 0),
    ('An oblique asymptote occurs when the degree of a rational function’s numerator exceeds the degree of its denominator by exactly ___.', ['One', 'Three, an incorrect difference for an oblique asymptote', 'A concept unrelated to rational function behaviour', 'Zero, meaning the degrees would instead be equal'], 0),
    ('The logistic function models growth that starts nearly exponential but slows and levels off as it approaches a maximum sustainable ___.', ['Value', 'Rate of change exclusively, with no connection to an upper limit', 'A concept unrelated to logistic growth', 'Starting point, a value that does not represent the growth ceiling'], 0),
    ('According to Benford’s Law, the digit ___ appears as a leading digit more frequently than any other digit in many natural data sets.', ['1', '9, the digit predicted to appear least frequently under Benford’s Law', 'A concept unrelated to the specific predictions of Benford’s Law', '5, a digit with only a moderate predicted frequency under Benford’s Law'], 0),
    ('Why is it useful to review spherical coordinates, oblique asymptotes, the logistic function, and Benford’s Law together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
C('Review: Grade 12 Calculus -- Days 61-69 Synthesis',
  'Grade 12 Calculus strand review: this lesson revisits the Laplace transform, the Mean Value Theorem for Integrals, Torricelli’s Trumpet, the Gamma function, and the catenary from Days 61-69.',
  [('The Laplace transform converts a function of time into a function of a complex ___ variable.', ['Frequency', 'Colour, with no connection to time or frequency', 'A concept unrelated to the Laplace transform', 'Volume, with no connection to this transformation'], 0),
   ('The Mean Value Theorem for Integrals guarantees that a continuous function on a closed interval attains its ___ value at least once within that interval.', ['Average', 'Maximum value exclusively, with no connection to the function’s average behaviour', 'A concept unrelated to this theorem', 'Minimum value exclusively, with no connection to the function’s average behaviour'], 0),
   ('Torricelli’s Trumpet is a solid of revolution with a finite volume but an ___ surface area.', ['Infinite', 'Undefined, with no numerical relationship to the shape at all', 'A concept unrelated to this classic calculus example', 'Zero, an inaccurate description of the surface area'], 0),
   ('The Gamma function extends the factorial operation to a broader domain using an ___.', ['Improper integral', 'Only basic multiplication, with no integral involved', 'A concept unrelated to defining the Gamma function', 'A finite sum, with no integral involved whatsoever'], 0),
   ('Why is it useful to review the Laplace transform, the Mean Value Theorem for Integrals, Torricelli’s Trumpet, and the Gamma function together?', ['These related calculus techniques reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in calculus', 'Each topic must be studied with no connection to the others'], 0)]),
P('Review: Grade 12 Physics -- Days 61-69 Synthesis',
  'Grade 12 Physics strand review: this lesson revisits the de Broglie hypothesis, gauge bosons, superfluidity, Bose-Einstein condensates, and Hawking radiation from Days 61-69.',
  [('The de Broglie hypothesis proposes that all matter exhibits ___ properties, not only light.', ['Wave-like', 'Purely solid, with no wave-like behaviour whatsoever', 'A concept unrelated to the behaviour of matter', 'Only particle-like properties, with no wave component at all'], 0),
   ('The Standard Model describes each fundamental force as being mediated by an exchange of specific particles called ___.', ['Gauge bosons', 'Neutrinos, which do not mediate fundamental forces in this way', 'A concept unrelated to the Standard Model', 'Protons, which are not force-carrying particles'], 0),
   ('A superfluid flows with effectively zero ___.', ['Viscosity', 'Electrical resistance exclusively, a property associated with superconductivity instead', 'A concept unrelated to fluid behaviour', 'Mass, which a superfluid still clearly possesses'], 0),
   ('Hawking radiation suggests that black holes slowly lose ___ over time.', ['Mass', 'Electric charge exclusively, with no connection to mass loss', 'A concept unrelated to this theoretical prediction', 'Angular momentum exclusively, with no connection to mass loss'], 0),
   ('Why is it useful to review the de Broglie hypothesis, gauge bosons, superfluidity, and Hawking radiation together?', ['These related physics concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in physics', 'Each topic must be studied with no connection to the others'], 0)])]),
]


def _rebalance_answer_positions(days, seed=20260819):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g12_61_70)
    append_to(12, g12_61_70)
