#!/usr/bin/env python3
"""Grade 12, Days 81-90 -- extends Grade 12 from 80 to 90 days. Topics
chosen to avoid any overlap with the existing Day 1-80 set (see
data/grade12.json): the roman a clef, the prose poem, data journalism and
infographics, ekphrasis, impromptu academic response, annotated
bibliographies, the unreliable chronicle, periodic and cumulative
sentences, and speculative fiction ethics; the Riemann zeta function,
polynomial interpolation, the Chinese remainder theorem, generating
functions, the fundamental theorem of algebra, Fermat's little theorem,
convex and concave functions, the method of undetermined coefficients,
and Ramsey theory; the epsilon-delta definition of a limit, numerical
differentiation, series solutions to differential equations, the
integral test, the washer method, the divergence theorem, Stokes'
theorem, the Fourier transform, and Green's theorem; neutrino
oscillations, quantum tunneling, the Meissner effect, gravitational
lensing, the Chandrasekhar limit, quark-gluon plasma, the
Aharonov-Bohm effect, sonoluminescence, and the Fermi paradox.

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as all earlier Grade 12 batches).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
CA12 = 'https://tvolearn.com/pages/grade-12-calculus-and-vectors'
PH12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RCA, RPH = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus and Vectors',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def CA(t, s, q):
    return sub('Calculus', t, s, RCA, CA12, q)


def PH(t, s, q):
    return sub('Physics', t, s, RPH, PH12, q)


def _rebalance_answer_positions(days, seed=20261001):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g12_81_90 = [
day(81, [
E('Literature: The Roman a Clef — Fiction Disguising Reality',
  'Grade 12 English strand: a roman a clef is a novel that portrays real people and events under a thin fictional disguise, requiring readers to recognize the reality behind invented names.',
  [('What does a roman a clef portray under a thin fictional disguise?', ['Real people and events', 'Only entirely invented, fantastical worlds', 'A concept unrelated to literature', 'A textbook’s worth of unrelated facts'], 0),
   ('Does reading a roman a clef often require recognizing the reality behind invented names?', ['Yes', 'No, this genre never draws on any real people or events', 'A concept unrelated to the roman a clef', 'Invented names are never used in this literary form'], 0),
   ('Why might an author choose to write a roman a clef instead of a straightforward memoir?', ['Fictional disguise can offer legal protection or creative freedom while still commenting on real events', 'Authors never have any reason to disguise real events as fiction', 'This concept has no connection to literature', 'A roman a clef is always completely unrelated to any real event'], 0),
   ('Which of these best describes a roman a clef?', ['A novel where a thinly veiled character is widely understood to represent a real public figure.', 'A cookbook with detailed recipes and ingredient lists.', 'A weather almanac predicting seasonal patterns.', 'A dictionary defining unfamiliar vocabulary terms.'], 0),
   ('Why might readers familiar with the real events behind a roman a clef experience the novel differently than readers who are not?', ['Recognizing the real-world parallels can add an additional layer of meaning and interpretation to the story', 'Prior knowledge of real events never changes how a reader experiences this type of novel', 'This concept has no relevance to literature', 'A roman a clef reads identically regardless of a reader’s background knowledge'], 0)]),
AF('Functions: The Riemann Zeta Function — An Introductory Glimpse',
   'Grade 12 Advanced Functions strand: the Riemann zeta function is an infinite series that extends far beyond basic algebra, connecting number theory to complex analysis through the distribution of prime numbers.',
   [('What does the Riemann zeta function connect number theory to?', ['Complex analysis', 'Only basic arithmetic with whole numbers', 'A concept unrelated to functions', 'Elementary geometry only'], 0),
    ('Is the Riemann zeta function related to the distribution of prime numbers?', ['Yes', 'No, it has no connection to prime numbers at all', 'A concept unrelated to the Riemann zeta function', 'Prime numbers are never studied using any function'], 0),
    ('Is the Riemann zeta function defined as an infinite series?', ['Yes', 'No, it is defined using only a single finite term', 'A concept unrelated to the Riemann zeta function', 'Infinite series have no connection to this function'], 0),
    ('Why might mathematicians consider the Riemann zeta function to be one of the most important unsolved problems in number theory?', ['Questions about where its values equal zero remain unresolved and have deep implications for understanding primes', 'Every question about the Riemann zeta function has already been completely solved', 'This concept has no connection to functions', 'The Riemann zeta function has no remaining open questions of any mathematical significance'], 0),
    ('Why is introducing the Riemann zeta function useful for students planning further study in advanced mathematics?', ['It offers a glimpse into how seemingly abstract functions connect to major unsolved problems in the field', 'This function has no relevance to any area of further mathematical study', 'This concept has no relevance to functions', 'Advanced mathematics never involves studying any function of this type'], 0)]),
CA('Calculus: The Epsilon-Delta Definition of a Limit',
   'Grade 12 Calculus strand: the epsilon-delta definition provides a rigorous, formal way to define what it means for a function to approach a limit, using precise inequalities involving small quantities epsilon and delta.',
   [('What does the epsilon-delta definition provide for the concept of a limit?', ['A rigorous, formal definition using precise inequalities', 'Only an informal, intuitive description with no precision', 'A concept unrelated to calculus', 'A definition that applies only to whole numbers'], 0),
    ('Does the epsilon-delta definition use the quantities epsilon and delta to express closeness?', ['Yes', 'No, it never uses any small quantities to define closeness', 'A concept unrelated to the epsilon-delta definition', 'Epsilon and delta have no connection to limits'], 0),
    ('Is the epsilon-delta definition considered a more rigorous approach than an informal description of a limit?', ['Yes', 'No, it is considered a less precise approach than an informal description', 'A concept unrelated to limits', 'Rigor has no connection to how a limit is defined'], 0),
    ('Why might mathematicians prefer the epsilon-delta definition over an intuitive description when proving that a limit exists?', ['It provides a precise, unambiguous standard that can be used to construct a rigorous mathematical proof', 'The epsilon-delta definition is never useful for constructing a mathematical proof', 'This concept has no connection to calculus', 'Intuitive descriptions are always more rigorous than any formal definition'], 0),
    ('Why is understanding the epsilon-delta definition valuable for students planning to study calculus at a university level?', ['University-level calculus often relies on this rigorous foundation to prove more advanced results', 'The epsilon-delta definition has no relevance to university-level mathematics', 'This concept has no relevance to calculus', 'Formal limit definitions are never used beyond an introductory high school course'], 0)]),
PH('Physics: Neutrino Oscillations and Flavor Changing',
   'Grade 12 Physics strand: neutrinos can change, or oscillate, between different types called flavors as they travel, a phenomenon that revealed neutrinos have a small but nonzero mass.',
   [('What can neutrinos do as they travel, according to neutrino oscillation?', ['Change between different types called flavors', 'Instantly disappear with no trace', 'A concept unrelated to physics', 'Always remain in exactly the same unchanging state'], 0),
    ('Did the discovery of neutrino oscillations reveal that neutrinos have a nonzero mass?', ['Yes', 'No, neutrino oscillations proved neutrinos have absolutely no mass', 'A concept unrelated to neutrino oscillations', 'Mass has no connection to neutrino oscillation behaviour'], 0),
    ('Are there multiple types, or flavors, of neutrinos?', ['Yes', 'No, only a single type of neutrino has ever been identified', 'A concept unrelated to neutrino physics', 'Flavor has no connection to how neutrinos are classified'], 0),
    ('Why was the discovery of neutrino oscillation considered surprising to physicists who had assumed neutrinos were massless?', ['Oscillation between flavors requires that neutrinos have some mass, contradicting earlier assumptions', 'The discovery confirmed exactly what physicists had already expected about neutrino mass', 'This concept has no connection to physics', 'Neutrino oscillation has no connection to whether neutrinos have any mass'], 0),
    ('Why do physicists build large, specialized detectors deep underground to study neutrino oscillations?', ['Neutrinos interact very weakly with matter, so sensitive, shielded detectors are needed to observe rare interactions', 'Neutrinos interact so strongly with matter that no special detection equipment is needed', 'This concept has no relevance to physics', 'Neutrino detectors are never built underground for any particular reason'], 0)]),
]),

day(82, [
E('Writing: The Prose Poem — Blurring Genre Boundaries',
  'Grade 12 English strand: a prose poem is written in paragraph form without line breaks, yet retains the compressed imagery, rhythm, and intensity typically associated with poetry.',
  [('What form is a prose poem written in?', ['Paragraph form without line breaks', 'Only traditional poetic stanzas with strict rhyme', 'A concept unrelated to writing', 'A formal legal contract format'], 0),
   ('Does a prose poem typically retain compressed imagery and rhythm associated with poetry?', ['Yes', 'No, a prose poem never uses any poetic qualities', 'A concept unrelated to prose poems', 'Imagery has no connection to how a prose poem is written'], 0),
   ('Why might a writer choose the prose poem form to blur the boundary between poetry and prose?', ['It allows them to explore poetic techniques while working within a continuous, paragraph-based structure', 'The prose poem form never blurs any distinction between poetry and prose', 'This concept has no connection to writing', 'Prose poems are always identical in structure to a traditional short story'], 0),
   ('Which of these best describes a prose poem?', ['A short, paragraph-form piece rich with vivid imagery and rhythmic language, but without line breaks.', 'A formal essay with numbered sections and citations.', 'A grocery list organized by food category.', 'A weather report broadcast on the evening news.'], 0),
   ('Why might studying the prose poem help students think more flexibly about genre and literary form?', ['It challenges the assumption that poetry must always follow a fixed set of structural rules', 'The prose poem has no connection to how genre or literary form is understood', 'This concept has no relevance to writing', 'Genre boundaries in literature are always fixed and can never be challenged'], 0)]),
AF('Functions: Polynomial Interpolation — Lagrange’s Method',
   'Grade 12 Advanced Functions strand: Lagrange’s method constructs a polynomial that passes exactly through a given set of data points, providing a way to estimate values between known data.',
   [('What does Lagrange’s method construct?', ['A polynomial that passes exactly through a given set of data points', 'A random polynomial unrelated to any specific data', 'A concept unrelated to functions', 'A single straight line with no curvature'], 0),
    ('Can polynomial interpolation help estimate values between known data points?', ['Yes', 'No, interpolation never estimates any value between known points', 'A concept unrelated to polynomial interpolation', 'Estimating values is never possible using a polynomial'], 0),
    ('Does Lagrange’s method require the constructed polynomial to pass exactly through the given points?', ['Yes', 'No, the polynomial only needs to pass near the given points', 'A concept unrelated to Lagrange’s method', 'Passing through the given points is never a requirement of this method'], 0),
    ('Why might an engineer use polynomial interpolation to estimate a value between two measured data points?', ['It provides a mathematical way to approximate unknown values based on a smooth curve fitting known data', 'Polynomial interpolation never provides any useful estimate of unknown values', 'This concept has no connection to functions', 'Engineers never need to estimate values between known measurements'], 0),
    ('Why might using too many data points in Lagrange interpolation sometimes lead to an unexpectedly oscillating polynomial?', ['A higher-degree polynomial fitted to many points can swing widely between the given points, a known interpolation issue', 'Adding more data points always produces a smoother, more accurate polynomial with no downsides', 'This concept has no relevance to functions', 'Polynomial interpolation is never affected by the number of data points used'], 0)]),
CA('Calculus: Numerical Differentiation Methods',
   'Grade 12 Calculus strand: numerical differentiation estimates a function’s derivative using values of the function at nearby points, useful when an exact algebraic derivative is difficult or impossible to find.',
   [('What does numerical differentiation estimate?', ['A function’s derivative using values at nearby points', 'The exact area under a curve only', 'A concept unrelated to calculus', 'A function’s value at a single fixed point with no estimation'], 0),
    ('Is numerical differentiation useful when an exact algebraic derivative is difficult to find?', ['Yes', 'No, numerical differentiation is never useful in this situation', 'A concept unrelated to numerical differentiation', 'An exact derivative can always be found for every function with ease'], 0),
    ('Does numerical differentiation rely on values of a function at points near the point of interest?', ['Yes', 'No, it never uses any nearby function values', 'A concept unrelated to numerical differentiation', 'Nearby values are never relevant to estimating a derivative'], 0),
    ('Why might a scientist use numerical differentiation when working with experimental data instead of a known algebraic function?', ['Experimental data often comes as discrete points rather than a formula, making numerical methods necessary to estimate rates of change', 'Experimental data can always be converted instantly into an exact algebraic function', 'This concept has no connection to calculus', 'Numerical differentiation is never applied to real experimental data'], 0),
    ('Why might using a smaller interval between data points generally improve the accuracy of a numerical derivative estimate?', ['A smaller interval more closely approximates the true instantaneous rate of change at a given point', 'Smaller intervals always make a numerical derivative estimate less accurate', 'This concept has no relevance to calculus', 'The size of the interval used never affects the accuracy of a numerical estimate'], 0)]),
PH('Physics: Quantum Tunneling and Its Applications',
   'Grade 12 Physics strand: quantum tunneling describes how a particle can pass through an energy barrier that classical physics predicts it should not have enough energy to overcome.',
   [('What does quantum tunneling describe?', ['How a particle can pass through an energy barrier it classically should not overcome', 'How particles always bounce off every barrier with no exception', 'A concept unrelated to physics', 'How particles disappear permanently upon striking a barrier'], 0),
    ('According to classical physics, should a particle without enough energy be able to pass through a barrier?', ['No', 'Yes, classical physics predicts it can always pass through easily', 'A concept unrelated to quantum tunneling', 'Classical physics makes no prediction about this situation'], 0),
    ('Is quantum tunneling a phenomenon explained by quantum mechanics rather than classical physics?', ['Yes', 'No, quantum tunneling is fully explained by classical physics alone', 'A concept unrelated to quantum tunneling', 'Quantum mechanics has no connection to tunneling behaviour'], 0),
    ('Why is quantum tunneling important for understanding how the sun generates energy through nuclear fusion?', ['It allows particles to overcome repulsive forces and fuse together even without classically sufficient energy', 'Quantum tunneling has no connection to the process of nuclear fusion', 'This concept has no connection to physics', 'Nuclear fusion in the sun occurs with no reliance on any quantum phenomenon'], 0),
    ('Why is quantum tunneling relevant to the design of modern electronic devices like tunnel diodes?', ['Engineers can exploit tunneling behaviour to create devices that operate based on this quantum effect', 'Quantum tunneling has no practical application in modern electronic devices', 'This concept has no relevance to physics', 'Electronic devices never rely on any quantum mechanical effect'], 0)]),
]),

day(83, [
E('Media Analysis: Analyzing Data Journalism and Infographics',
  'Grade 12 English strand: data journalism combines reporting with statistical analysis and visual infographics, presenting complex information in a form intended to be both accurate and accessible.',
  [('What does data journalism combine with reporting?', ['Statistical analysis and visual infographics', 'Only handwritten personal opinions with no data', 'A concept unrelated to media analysis', 'Fictional storytelling with no factual basis'], 0),
   ('Is data journalism intended to present complex information in an accessible form?', ['Yes', 'No, data journalism intentionally makes information as confusing as possible', 'A concept unrelated to data journalism', 'Accessibility has no connection to how data journalism is presented'], 0),
   ('Why might a poorly designed infographic mislead readers even if the underlying data is accurate?', ['Visual choices like scale, colour, or omitted context can distort how accurate data is perceived', 'Infographic design never has any effect on how data is perceived', 'This concept has no connection to media analysis', 'Accurate data can never be presented in a misleading way visually'], 0),
   ('Why is it important for readers to critically evaluate the source of data used in a piece of data journalism?', ['Understanding where data comes from helps readers assess its reliability and any potential bias', 'The source of data used in journalism is never relevant to evaluating an article', 'This concept has no connection to media analysis', 'All data sources used in journalism are always equally reliable'], 0),
   ('Why might data journalism be considered a valuable tool for making complex issues, like climate trends, understandable to a general audience?', ['Well-designed visualizations can make large or complex data sets easier to interpret at a glance', 'Data journalism never makes complex issues any easier to understand', 'This concept has no relevance to media analysis', 'Complex issues can only ever be communicated through lengthy written text'], 0)]),
AF('Number Theory: The Chinese Remainder Theorem',
   'Grade 12 Advanced Functions strand: the Chinese remainder theorem provides a method for solving a system of simultaneous congruences, finding a unique solution modulo the product of the given moduli.',
   [('What does the Chinese remainder theorem help solve?', ['A system of simultaneous congruences', 'A single simple linear equation only', 'A concept unrelated to number theory', 'A basic addition problem with whole numbers'], 0),
    ('Does the Chinese remainder theorem require the moduli involved to typically be coprime?', ['Yes', 'No, the moduli involved are never required to share any particular relationship', 'A concept unrelated to the Chinese remainder theorem', 'Coprimality has no connection to how this theorem is applied'], 0),
    ('Does the Chinese remainder theorem produce a unique solution modulo the product of the given moduli?', ['Yes', 'No, it never produces a solution of any kind', 'A concept unrelated to the Chinese remainder theorem', 'This theorem only ever applies to a single modulus at a time'], 0),
    ('Why might the Chinese remainder theorem be useful in modern computer science, such as in cryptography?', ['It provides an efficient method for performing certain calculations involving large numbers by breaking them into smaller, manageable pieces', 'The Chinese remainder theorem has no connection to computer science or cryptography', 'This concept has no connection to functions', 'Cryptography never makes use of any number theory concept'], 0),
    ('Why is solving a system of congruences using the Chinese remainder theorem often more efficient than checking every possible number individually?', ['The theorem provides a direct method to construct the solution rather than requiring an exhaustive, one-by-one search', 'Checking every possible number individually is always the fastest method available', 'This concept has no relevance to functions', 'The Chinese remainder theorem never actually reduces the amount of work required'], 0)]),
CA('Calculus: Series Solutions to Differential Equations',
   'Grade 12 Calculus strand: series solutions express the solution to a differential equation as an infinite power series, useful when the equation cannot be solved using elementary functions alone.',
   [('How do series solutions express the solution to a differential equation?', ['As an infinite power series', 'Only as a single constant number', 'A concept unrelated to calculus', 'As a finite list of whole numbers'], 0),
    ('Are series solutions useful when a differential equation cannot be solved using elementary functions?', ['Yes', 'No, series solutions are never useful in this situation', 'A concept unrelated to series solutions', 'Every differential equation can always be solved using elementary functions alone'], 0),
    ('Does finding a series solution typically involve assuming a general power series form and solving for its coefficients?', ['Yes', 'No, coefficients are never involved in finding a series solution', 'A concept unrelated to series solutions', 'A power series form is never assumed when solving a differential equation this way'], 0),
    ('Why might a series solution be considered an approximation rather than an exact closed-form answer?', ['A power series may need to be truncated after a certain number of terms to be practically useful for calculation', 'A series solution always provides an exact, finite closed-form answer with no approximation involved', 'This concept has no connection to calculus', 'Series solutions have no connection to approximating a differential equation’s behaviour'], 0),
    ('Why are series solutions to differential equations especially valuable in physics and engineering applications?', ['Many real-world differential equations lack simple closed-form solutions, making series methods a practical alternative', 'Series solutions have no practical application in physics or engineering', 'This concept has no relevance to calculus', 'Every differential equation encountered in physics has a simple closed-form solution'], 0)]),
PH('Physics: The Meissner Effect in Superconductors',
   'Grade 12 Physics strand: the Meissner effect describes how a superconductor expels magnetic field lines from its interior when it transitions into the superconducting state.',
   [('What does the Meissner effect describe a superconductor doing?', ['Expelling magnetic field lines from its interior', 'Attracting magnetic field lines more strongly than any other material', 'A concept unrelated to physics', 'Absorbing all magnetic energy permanently with no expulsion'], 0),
    ('Does the Meissner effect occur when a material transitions into the superconducting state?', ['Yes', 'No, the Meissner effect has no connection to superconductivity', 'A concept unrelated to the Meissner effect', 'Superconductors never expel any magnetic field lines'], 0),
    ('Can the Meissner effect be demonstrated by a magnet appearing to float above a superconductor?', ['Yes', 'No, magnets are never affected in any way by a superconductor', 'A concept unrelated to the Meissner effect', 'Floating magnets have no connection to superconducting behaviour'], 0),
    ('Why does a magnet appear to levitate above a superconductor cooled below its critical temperature?', ['The expelled magnetic field lines create a repulsive force that can support the magnet’s weight', 'The magnet levitates due to an unrelated mechanical mechanism with no connection to magnetism', 'This concept has no connection to physics', 'Superconductors have no effect whatsoever on nearby magnets'], 0),
    ('Why is the Meissner effect considered an important piece of evidence that a material has truly become superconducting?', ['It demonstrates a distinctive magnetic behaviour that occurs specifically in the superconducting state, beyond just zero electrical resistance', 'The Meissner effect provides no useful evidence about whether a material is superconducting', 'This concept has no relevance to physics', 'Superconductivity can only ever be confirmed by measuring electrical resistance alone'], 0)]),
]),

day(84, [
E('Literature: Ekphrasis — Writing About Visual Art',
  'Grade 12 English strand: ekphrasis is a literary description of a visual artwork, using vivid language to capture and interpret what is depicted in a painting, sculpture, or photograph.',
  [('What does ekphrasis describe?', ['A visual artwork', 'A weather pattern occurring in a specific season', 'A concept unrelated to literature', 'A mathematical proof with no artistic content'], 0),
   ('Does ekphrasis use vivid language to interpret a visual artwork?', ['Yes', 'No, ekphrasis never uses any vivid or descriptive language', 'A concept unrelated to ekphrasis', 'Interpretation has no connection to how ekphrasis is written'], 0),
   ('Why might a poet write an ekphrastic poem about a specific painting rather than simply describing it literally?', ['An ekphrastic poem can interpret the emotional or symbolic meaning of the artwork, not just its literal appearance', 'Ekphrastic poems never interpret any deeper meaning within an artwork', 'This concept has no connection to literature', 'Ekphrasis only ever provides a literal, objective description with no interpretation'], 0),
   ('Which of these would most likely be an example of ekphrasis?', ['A poem imagining the inner thoughts of a woman captured in a famous portrait.', 'A recipe for baking a loaf of bread.', 'A user manual explaining how to install software.', 'A weather report predicting rain for the weekend.'], 0),
   ('Why might studying ekphrasis help students think about the relationship between different art forms?', ['It highlights how written language can respond to and reinterpret meaning found in a visual medium', 'Ekphrasis has no connection to the relationship between visual art and literature', 'This concept has no relevance to literature', 'Visual art and written literature are never connected in any meaningful way'], 0)]),
AF('Discrete Math: Generating Functions — An Introduction',
   'Grade 12 Advanced Functions strand: a generating function encodes a sequence of numbers as the coefficients of a power series, providing a powerful algebraic tool for solving counting problems.',
   [('What does a generating function encode a sequence of numbers as?', ['The coefficients of a power series', 'A single unrelated constant value', 'A concept unrelated to discrete math', 'A random list with no defined structure'], 0),
    ('Are generating functions a useful tool for solving counting problems?', ['Yes', 'No, generating functions have no application to counting problems', 'A concept unrelated to generating functions', 'Counting problems can never be represented using any function'], 0),
    ('Does a generating function typically take the form of a power series?', ['Yes', 'No, a generating function is never expressed as a power series', 'A concept unrelated to generating functions', 'Power series have no connection to generating functions'], 0),
    ('Why might a generating function be useful for finding a formula for a recursively defined sequence, like the Fibonacci sequence?', ['Manipulating the generating function algebraically can reveal a closed-form expression for the sequence’s terms', 'Generating functions have no connection to recursively defined sequences', 'This concept has no connection to functions', 'A closed-form expression for a recursive sequence can never be found using this method'], 0),
    ('Why are generating functions considered a valuable tool in combinatorics, the study of counting and arrangement?', ['They allow complex counting problems to be translated into algebraic operations on power series, simplifying the analysis', 'Generating functions have no relevance to the field of combinatorics', 'This concept has no relevance to functions', 'Combinatorics never makes use of any algebraic tool of this kind'], 0)]),
CA('Calculus: The Integral Test for Series Convergence',
   'Grade 12 Calculus strand: the integral test compares an infinite series to a related improper integral, determining whether the series converges or diverges based on the integral’s behaviour.',
   [('What does the integral test compare an infinite series to?', ['A related improper integral', 'A single unrelated finite sum', 'A concept unrelated to calculus', 'A geometric shape with no numerical value'], 0),
    ('Can the integral test help determine whether a series converges or diverges?', ['Yes', 'No, the integral test has no connection to convergence or divergence', 'A concept unrelated to the integral test', 'Convergence can never be determined using any comparison method'], 0),
    ('Does the integral test require the function being compared to be positive and decreasing?', ['Yes', 'No, the function used in this test can behave in any way at all', 'A concept unrelated to the integral test', 'Decreasing behaviour is never a requirement of this test'], 0),
    ('Why might the integral test be a useful method for analyzing a series whose terms resemble a continuous function?', ['If the series closely relates to a function that can be integrated, the integral’s convergence behaviour can indicate the series’ behaviour', 'The integral test is never useful for analyzing any type of series', 'This concept has no connection to calculus', 'Series and integrals have no mathematical relationship to one another'], 0),
    ('Why is it important to verify that a function meets the conditions required for the integral test before applying it?', ['Applying the test to a function that does not meet the conditions could lead to an incorrect conclusion about convergence', 'The conditions of the integral test never actually matter for reaching a correct conclusion', 'This concept has no relevance to calculus', 'The integral test can be applied to any function with no restrictions whatsoever'], 0)]),
PH('Physics: Gravitational Lensing',
   'Grade 12 Physics strand: gravitational lensing occurs when the gravity of a massive object bends the path of light from a more distant source, sometimes creating multiple or distorted images.',
   [('What does gravitational lensing occur due to?', ['The gravity of a massive object bending light from a distant source', 'Only ordinary reflections off a mirror-like surface', 'A concept unrelated to physics', 'Sound waves travelling through empty space'], 0),
    ('Can gravitational lensing sometimes create multiple or distorted images of a distant object?', ['Yes', 'No, gravitational lensing never affects the appearance of an image', 'A concept unrelated to gravitational lensing', 'Multiple images are never produced by this phenomenon'], 0),
    ('Does gravitational lensing rely on the bending of light by a massive object’s gravity?', ['Yes', 'No, light bending has no connection to gravitational lensing', 'A concept unrelated to gravitational lensing', 'Gravity has no effect on the path light travels'], 0),
    ('Why can gravitational lensing be used by astronomers to detect the presence of dark matter?', ['Dark matter’s gravitational effects can bend light in ways that reveal its presence, even though it cannot be seen directly', 'Gravitational lensing has no connection to detecting dark matter', 'This concept has no connection to physics', 'Dark matter can always be observed directly without needing any indirect method'], 0),
    ('Why is gravitational lensing considered strong evidence supporting Einstein’s general theory of relativity?', ['The bending of light by massive objects was a key prediction of general relativity that has since been confirmed through observation', 'Gravitational lensing has no connection to any prediction made by general relativity', 'This concept has no relevance to physics', 'General relativity makes no prediction whatsoever about the behaviour of light'], 0)]),
]),

day(85, [
E('Oral Communication: The Impromptu Response in Academic Discourse',
  'Grade 12 English strand: responding effectively to an unplanned question in academic discourse requires organizing thoughts quickly, staying on topic, and structuring a clear, coherent response under time pressure.',
  [('What does responding effectively to an impromptu academic question require?', ['Organizing thoughts quickly and structuring a clear response', 'Memorizing an entire prepared script in advance', 'A concept unrelated to oral communication', 'Speaking for as long as possible with no clear structure'], 0),
   ('Is staying on topic important when responding to an unplanned question?', ['Yes', 'No, staying on topic is never important in this situation', 'A concept unrelated to impromptu responses', 'Topic relevance has no connection to academic discourse'], 0),
   ('Why might briefly pausing before responding to an unexpected question actually improve the quality of an answer?', ['A short pause allows time to organize a coherent response rather than speaking without a clear structure', 'Pausing before responding always makes an answer less clear and organized', 'This concept has no connection to oral communication', 'Immediate, unplanned responses are always more effective than a brief pause'], 0),
   ('Which of these best demonstrates an effective impromptu response?', ['Briefly organizing key points before clearly answering an unexpected question during a discussion.', 'Refusing to answer any question that was not planned in advance.', 'Repeating the exact same rehearsed statement regardless of the question asked.', 'Speaking without pausing about an unrelated topic instead of answering the question.'], 0),
   ('Why is developing strong impromptu response skills valuable for academic settings like seminars or oral examinations?', ['These settings often require thinking clearly and communicating effectively without extensive advance preparation', 'Impromptu response skills have no connection to academic seminars or oral examinations', 'This concept has no relevance to oral communication', 'Academic discourse never requires responding to any unplanned question'], 0)]),
AF('Functions: The Fundamental Theorem of Algebra',
   'Grade 12 Advanced Functions strand: the fundamental theorem of algebra states that every non-constant polynomial with complex coefficients has at least one complex root.',
   [('What does the fundamental theorem of algebra state about a non-constant polynomial?', ['It has at least one complex root', 'It always has exactly zero roots', 'A concept unrelated to functions', 'It can never be solved using any method'], 0),
    ('Does the fundamental theorem of algebra apply to polynomials with complex coefficients?', ['Yes', 'No, it only applies to polynomials with whole number coefficients', 'A concept unrelated to the fundamental theorem of algebra', 'Complex coefficients have no connection to this theorem'], 0),
    ('Does the fundamental theorem of algebra guarantee that a polynomial has at least one root, even if that root is complex?', ['Yes', 'No, it guarantees a polynomial has absolutely no roots of any kind', 'A concept unrelated to this theorem', 'Real roots are the only type of root ever guaranteed by any theorem'], 0),
    ('Why is the fundamental theorem of algebra considered significant for understanding polynomial equations?', ['It guarantees that every polynomial equation can be fully factored over the complex numbers', 'This theorem provides no useful information about factoring polynomial equations', 'This concept has no connection to functions', 'Polynomial equations can never be guaranteed to have any solution at all'], 0),
    ('Why might a polynomial with only real coefficients still have complex roots, according to the fundamental theorem of algebra?', ['The theorem guarantees roots exist among the complex numbers, which include real numbers as a special case, but complex roots are still possible', 'A polynomial with real coefficients can never have any complex roots under any circumstances', 'This concept has no relevance to functions', 'The type of coefficients used never affects whether a root is real or complex'], 0)]),
CA('Calculus: Volume by the Washer Method',
   'Grade 12 Calculus strand: the washer method finds the volume of a solid of revolution with a hole through its center, integrating the difference between the areas of an outer and inner radius.',
   [('What kind of solid does the washer method calculate the volume of?', ['A solid of revolution with a hole through its center', 'A solid with absolutely no hole of any kind', 'A concept unrelated to calculus', 'A flat, two-dimensional shape with no volume'], 0),
    ('Does the washer method involve integrating the difference between an outer and inner radius?', ['Yes', 'No, only a single radius is ever considered in this method', 'A concept unrelated to the washer method', 'Radius has no connection to how this method calculates volume'], 0),
    ('Is the washer method a variation of the disk method used when a solid has an internal cavity?', ['Yes', 'No, the washer method has no connection to the disk method', 'A concept unrelated to calculus', 'Internal cavities are never relevant to any volume calculation method'], 0),
    ('Why might the washer method be necessary instead of the simpler disk method when a region is revolved around an axis outside the region itself?', ['Revolving a region that does not touch the axis creates a hollow solid, requiring the subtraction of an inner area', 'The washer method is never actually needed under any circumstances', 'This concept has no connection to calculus', 'A hollow solid can always be calculated using the exact same method as a solid disk'], 0),
    ('Why is setting up the correct outer and inner radius functions considered the most important step when applying the washer method?', ['An incorrect radius function would lead to an inaccurate calculation of the cross-sectional area at each point', 'The radius functions used in this method never actually affect the accuracy of the final volume calculation', 'This concept has no relevance to calculus', 'The washer method produces the same result regardless of which radius functions are used'], 0)]),
PH('Physics: The Chandrasekhar Limit and White Dwarf Stars',
   'Grade 12 Physics strand: the Chandrasekhar limit defines the maximum mass a white dwarf star can have before its own gravity overcomes electron degeneracy pressure, leading to further stellar collapse.',
   [('What does the Chandrasekhar limit define?', ['The maximum mass a white dwarf star can have before further collapse', 'The minimum temperature required for a star to form', 'A concept unrelated to physics', 'The exact colour every white dwarf star must appear'], 0),
    ('Does a white dwarf’s stability depend on electron degeneracy pressure resisting gravitational collapse?', ['Yes', 'No, electron degeneracy pressure has no connection to a white dwarf’s stability', 'A concept unrelated to the Chandrasekhar limit', 'Gravity has no effect on a white dwarf star of any mass'], 0),
    ('Could a white dwarf that exceeds the Chandrasekhar limit undergo further gravitational collapse?', ['Yes', 'No, exceeding this limit has no effect on a white dwarf’s stability', 'A concept unrelated to the Chandrasekhar limit', 'White dwarfs can never exceed any mass limit under any circumstances'], 0),
    ('Why is the Chandrasekhar limit important for understanding the different possible end stages of a dying star?', ['A star’s mass relative to this limit helps determine whether it becomes a stable white dwarf or continues collapsing further', 'The Chandrasekhar limit has no connection to the different possible fates of a dying star', 'This concept has no connection to physics', 'Every dying star follows exactly the same evolutionary path regardless of its mass'], 0),
    ('Why might exceeding the Chandrasekhar limit in certain binary star systems potentially lead to a type of supernova explosion?', ['If a white dwarf accumulates enough mass from a companion star to exceed the limit, it can become unstable and detonate', 'Exceeding this limit in a binary system never leads to any dramatic astronomical event', 'This concept has no relevance to physics', 'White dwarfs in binary systems are never affected by mass gained from a companion star'], 0)]),
]),

day(86, [
E('Writing: The Annotated Bibliography and Source Synthesis',
  'Grade 12 English strand: an annotated bibliography lists sources along with a brief summary and evaluation of each, helping a writer organize and synthesize research before drafting a longer academic paper.',
  [('What does an annotated bibliography include for each source, beyond a simple citation?', ['A brief summary and evaluation', 'Only the exact page count of the source', 'A concept unrelated to writing', 'A random unrelated quotation with no connection to the source'], 0),
   ('Can an annotated bibliography help a writer organize research before drafting a longer paper?', ['Yes', 'No, an annotated bibliography never helps organize any research', 'A concept unrelated to annotated bibliographies', 'Research organization has no connection to this type of writing'], 0),
   ('Why might a writer evaluate the credibility of a source within an annotated bibliography entry?', ['Assessing credibility helps determine which sources are strong enough to support a future argument', 'Evaluating credibility never matters when compiling an annotated bibliography', 'This concept has no connection to writing', 'Every possible source is always considered equally credible with no evaluation needed'], 0),
   ('Which of these would most likely appear in an annotated bibliography entry?', ['This source presents strong statistical evidence but focuses narrowly on one region, limiting its broader applicability.', 'A weather forecast for tomorrow’s temperature.', 'A grocery list for a weekly shopping trip.', 'A recipe for making pasta from scratch.'], 0),
   ('Why is creating an annotated bibliography a valuable step before writing a longer research paper?', ['It helps a writer synthesize and evaluate multiple sources, clarifying how each one supports the overall argument', 'An annotated bibliography never contributes anything useful to the research writing process', 'This concept has no relevance to writing', 'Longer research papers are always written with no reference to any collected sources'], 0)]),
AF('Number Theory: Fermat’s Little Theorem',
   'Grade 12 Advanced Functions strand: Fermat’s little theorem states that if p is a prime number, then for any integer a not divisible by p, a raised to the power of p minus 1 is congruent to 1 modulo p.',
   [('What must p be, according to Fermat’s little theorem?', ['A prime number', 'Any even number', 'A concept unrelated to number theory', 'A number divisible by 4'], 0),
    ('Does Fermat’s little theorem apply to any integer a that is not divisible by the prime p?', ['Yes', 'No, it only applies to integers that are divisible by p', 'A concept unrelated to Fermat’s little theorem', 'The integer a has no connection to this theorem'], 0),
    ('Does Fermat’s little theorem involve congruence modulo the prime number p?', ['Yes', 'No, modular arithmetic has no connection to this theorem', 'A concept unrelated to Fermat’s little theorem', 'This theorem only ever applies to non-modular arithmetic'], 0),
    ('Why is Fermat’s little theorem useful in modern cryptographic systems?', ['It provides a mathematical foundation for certain encryption methods that rely on properties of prime numbers', 'This theorem has no application in any area of cryptography', 'This concept has no connection to functions', 'Cryptographic systems never rely on any property of prime numbers'], 0),
    ('Why might Fermat’s little theorem be used as a quick test to check whether a large number is likely to be prime?', ['If a number fails the conditions described by the theorem, it cannot be prime, offering an efficient preliminary check', 'This theorem provides no useful information for testing whether a number might be prime', 'This concept has no relevance to functions', 'Testing whether a number is prime never involves any theorem from number theory'], 0)]),
CA('Calculus: The Divergence Theorem',
   'Grade 12 Calculus strand: the divergence theorem relates the flow of a vector field out through a closed surface to the divergence of that field integrated over the enclosed volume.',
   [('What does the divergence theorem relate the flow of a vector field through a closed surface to?', ['The divergence of the field integrated over the enclosed volume', 'A single unrelated scalar number with no integral involved', 'A concept unrelated to calculus', 'The area of a completely separate, unrelated shape'], 0),
    ('Does the divergence theorem require the surface being considered to be closed?', ['Yes', 'No, the surface can be entirely open with no boundary at all', 'A concept unrelated to the divergence theorem', 'Closed surfaces have no connection to this theorem'], 0),
    ('Does the divergence theorem connect a surface integral to a volume integral?', ['Yes', 'No, it only ever involves a single type of integral with no connection between them', 'A concept unrelated to the divergence theorem', 'Volume integrals are never involved in this theorem'], 0),
    ('Why might the divergence theorem be useful for simplifying a difficult surface integral calculation?', ['Converting the surface integral into a volume integral can sometimes make the calculation more straightforward', 'The divergence theorem never simplifies any type of integral calculation', 'This concept has no connection to calculus', 'Surface and volume integrals are never mathematically related to one another'], 0),
    ('Why is the divergence theorem considered useful in physics for describing fluid flow through a closed surface, like a balloon?', ['It relates the net outward flow through the surface to sources or sinks of the fluid contained within the enclosed volume', 'The divergence theorem has no application in describing physical fluid flow', 'This concept has no relevance to calculus', 'Fluid flow through a closed surface can never be described using any calculus concept'], 0)]),
PH('Physics: Quark-Gluon Plasma',
   'Grade 12 Physics strand: quark-gluon plasma is an extremely hot, dense state of matter in which quarks and gluons are no longer confined within individual protons and neutrons.',
   [('What are quarks and gluons no longer confined within, in a quark-gluon plasma?', ['Individual protons and neutrons', 'Only individual electrons', 'A concept unrelated to physics', 'A completely empty vacuum with no particles present'], 0),
    ('Is quark-gluon plasma considered an extremely hot, dense state of matter?', ['Yes', 'No, it is considered an extremely cold, low-density state', 'A concept unrelated to quark-gluon plasma', 'Temperature and density have no connection to this state of matter'], 0),
    ('Do scientists believe quark-gluon plasma existed shortly after the beginning of the universe?', ['Yes', 'No, this state of matter has no connection to the early universe', 'A concept unrelated to quark-gluon plasma', 'The early universe never contained any unusual states of matter'], 0),
    ('Why do physicists use powerful particle accelerators to try to recreate quark-gluon plasma in a laboratory?', ['Extremely high-energy collisions can briefly reproduce the intense heat and density needed to free quarks and gluons from confinement', 'Particle accelerators have no connection to studying quark-gluon plasma', 'This concept has no connection to physics', 'Quark-gluon plasma can be easily created using ordinary laboratory equipment with no special conditions'], 0),
    ('Why is studying quark-gluon plasma valuable for understanding the conditions of the early universe?', ['Recreating this extreme state can help scientists understand what matter behaved like moments after the universe began', 'Quark-gluon plasma provides no useful information about the early universe', 'This concept has no relevance to physics', 'The early universe has already been fully understood with no remaining scientific questions'], 0)]),
]),

day(87, [
E('Literature: The Unreliable Chronicle — History Told Through Fiction',
  'Grade 12 English strand: an unreliable chronicle presents historical events through a narrator whose biases, gaps in memory, or hidden motives call into question the accuracy of the account being told.',
  [('What might call into question the accuracy of an unreliable chronicle?', ['A narrator’s biases, gaps in memory, or hidden motives', 'Only the exact publication date of the text', 'A concept unrelated to literature', 'The font used in the printed edition'], 0),
   ('Does an unreliable chronicle present historical events through the perspective of a specific narrator?', ['Yes', 'No, this narrative form never uses any particular narrator’s perspective', 'A concept unrelated to unreliable chronicles', 'Historical events are never presented through any narrator’s viewpoint'], 0),
   ('Why might an author choose to tell a historical story through a narrator whose account may not be entirely trustworthy?', ['It can highlight how historical understanding is often shaped by subjective perspective rather than pure objective fact', 'Unreliable narration never reveals anything meaningful about how history is understood', 'This concept has no connection to literature', 'Historical fiction always presents events with complete, unquestionable accuracy'], 0),
   ('Which of these best illustrates an unreliable chronicle?', ['A narrator who admits to forgetting key details while recounting a war they witnessed decades earlier.', 'A textbook timeline listing dates with no narrative voice at all.', 'A dictionary definition of the word history.', 'A weather report describing today’s forecast.'], 0),
   ('Why is analyzing an unreliable chronicle a useful exercise for developing critical historical thinking?', ['It encourages readers to consider multiple perspectives and question a single narrative’s claim to objective truth', 'This type of narrative never encourages any critical thinking about history', 'This concept has no relevance to literature', 'Historical accounts are always completely objective with no room for critical questioning'], 0)]),
AF('Functions: Convex and Concave Functions — A Formal Look',
   'Grade 12 Advanced Functions strand: a convex function curves upward like a bowl, while a concave function curves downward like a dome, a distinction formally connected to the sign of the function’s second derivative.',
   [('What shape does a convex function typically curve like?', ['A bowl, curving upward', 'A flat, straight line with no curvature at all', 'A concept unrelated to functions', 'A dome, curving downward'], 0),
    ('What shape does a concave function typically curve like?', ['A dome, curving downward', 'A bowl, curving upward', 'A concept unrelated to functions', 'A perfectly straight, unchanging line'], 0),
    ('Is the distinction between convex and concave functions formally connected to the sign of the second derivative?', ['Yes', 'No, the second derivative has no connection to this distinction', 'A concept unrelated to convex and concave functions', 'The second derivative is never used to classify a function this way'], 0),
    ('Why might a positive second derivative across an interval indicate that a function is convex on that interval?', ['A positive second derivative shows the function’s slope is increasing, producing the upward, bowl-like curve characteristic of convexity', 'A positive second derivative always indicates a function is concave, not convex', 'This concept has no connection to functions', 'The second derivative has no relationship to whether a function is convex or concave'], 0),
    ('Why is understanding convexity useful in fields like economics when analyzing cost or utility functions?', ['Convex functions often model situations with increasing marginal costs, an important concept for economic decision-making', 'Convexity has no relevance to analyzing cost or utility in economics', 'This concept has no relevance to functions', 'Economic cost functions are never analyzed using concepts like convexity or concavity'], 0)]),
CA('Calculus: Stokes’ Theorem — An Introduction',
   'Grade 12 Calculus strand: Stokes’ theorem relates a surface integral of the curl of a vector field over a surface to a line integral of the field around the surface’s boundary curve.',
   [('What does Stokes’ theorem relate a surface integral of curl to?', ['A line integral around the surface’s boundary curve', 'A single unrelated scalar with no integral of any kind', 'A concept unrelated to calculus', 'The area of an entirely separate, unrelated shape'], 0),
    ('Does Stokes’ theorem involve the curl of a vector field?', ['Yes', 'No, curl has no connection to Stokes’ theorem', 'A concept unrelated to Stokes’ theorem', 'This theorem only ever involves a field with zero curl'], 0),
    ('Does Stokes’ theorem connect a surface integral to a line integral around the surface’s boundary?', ['Yes', 'No, boundaries are never relevant to this theorem', 'A concept unrelated to Stokes’ theorem', 'Line integrals are never involved in Stokes’ theorem'], 0),
    ('Why might Stokes’ theorem be useful for simplifying a difficult line integral calculation around a complicated boundary curve?', ['Converting the line integral into a surface integral of the curl can sometimes make the calculation more manageable', 'Stokes’ theorem never simplifies any type of integral calculation', 'This concept has no connection to calculus', 'Line and surface integrals are never mathematically related to each other'], 0),
    ('Why is Stokes’ theorem considered a generalization of concepts first introduced in a basic study of circulation and curl?', ['It extends the relationship between circulation around a curve and the rotational behaviour of a field across a broader class of surfaces', 'Stokes’ theorem has no connection to any earlier concept involving circulation or curl', 'This concept has no relevance to calculus', 'Circulation and curl are entirely unrelated mathematical ideas with no connection to this theorem'], 0)]),
PH('Physics: The Aharonov-Bohm Effect',
   'Grade 12 Physics strand: the Aharonov-Bohm effect shows that a charged particle can be affected by an electromagnetic field even in a region where the field strength itself is zero, revealing the deeper role of the field’s potential.',
   [('Can a charged particle be affected by an electromagnetic field even where the field strength is zero, according to the Aharonov-Bohm effect?', ['Yes', 'No, a particle is never affected by a field of zero strength', 'A concept unrelated to physics', 'Field strength always determines every possible effect with no exceptions'], 0),
    ('Does the Aharonov-Bohm effect reveal something significant about the role of the electromagnetic potential?', ['Yes', 'No, the electromagnetic potential has no connection to this effect', 'A concept unrelated to the Aharonov-Bohm effect', 'Potential and field strength are always exactly equivalent concepts with no distinction'], 0),
    ('Is the Aharonov-Bohm effect considered a quantum mechanical phenomenon?', ['Yes', 'No, it is fully explained using only classical physics', 'A concept unrelated to the Aharonov-Bohm effect', 'Quantum mechanics has no connection to this effect'], 0),
    ('Why was the Aharonov-Bohm effect considered surprising when it was first proposed?', ['It suggested that particles could be influenced by potentials even in regions where no classical force from the field was present', 'The effect confirmed exactly what classical physics had already predicted with no surprises', 'This concept has no connection to physics', 'Electromagnetic potentials were already known to have no possible physical effect on particles'], 0),
    ('Why is the Aharonov-Bohm effect considered important for deepening our understanding of quantum mechanics?', ['It challenged assumptions about which physical quantities directly cause observable effects on particles', 'This effect has no relevance to how physicists understand quantum mechanical systems', 'This concept has no relevance to physics', 'Quantum mechanics was already fully understood before this effect was discovered'], 0)]),
]),

day(88, [
E('Grammar and Style: Periodic and Cumulative Sentences',
  'Grade 12 English strand: a periodic sentence withholds its main point until the very end, building suspense, while a cumulative sentence states its main point early and adds supporting details afterward.',
  [('When does a periodic sentence reveal its main point?', ['At the very end of the sentence', 'At the very beginning of the sentence', 'A concept unrelated to grammar', 'A periodic sentence never actually contains any main point'], 0),
   ('When does a cumulative sentence typically state its main point?', ['Early in the sentence', 'Only at the very end of the sentence', 'A concept unrelated to cumulative sentences', 'A cumulative sentence never contains a clear main point'], 0),
   ('Which sentence is an example of a periodic sentence?', ['After years of hardship, endless doubt, and quiet perseverance, she finally succeeded.', 'She succeeded, after years of hardship, doubt, and perseverance.', 'She succeeded quickly.', 'Success came to her.'], 0),
   ('Why might a writer use a periodic sentence to build suspense before revealing a key idea?', ['Delaying the main point can create anticipation and emphasize its importance once it is finally revealed', 'Periodic sentences never create any sense of suspense or anticipation', 'This concept has no connection to grammar', 'The main point is always more effective when placed at the very beginning'], 0),
   ('Why might a writer choose a cumulative sentence structure when providing additional supporting detail after a main point?', ['It allows the core idea to be established first, then expanded upon with layered, additional description', 'Cumulative sentences never add any supporting detail after the main point', 'This concept has no connection to grammar', 'The main point in a cumulative sentence is always saved until the very end'], 0)]),
AF('Functions: The Method of Undetermined Coefficients',
   'Grade 12 Advanced Functions strand: the method of undetermined coefficients solves certain equations by guessing a solution form with unknown constants, then solving for those constants by matching terms.',
   [('What does the method of undetermined coefficients involve guessing?', ['A solution form with unknown constants', 'A completely random final answer with no structure', 'A concept unrelated to functions', 'A solution containing no unknown values whatsoever'], 0),
    ('Does this method involve solving for unknown constants by matching terms?', ['Yes', 'No, matching terms is never involved in this method', 'A concept unrelated to the method of undetermined coefficients', 'Unknown constants are never actually solved for in this method'], 0),
    ('Is the method of undetermined coefficients typically used for equations with a specific, recognizable form?', ['Yes', 'No, this method works equally well for equations of absolutely any form', 'A concept unrelated to this method', 'Recognizable equation forms have no connection to this method'], 0),
    ('Why might the method of undetermined coefficients be considered more straightforward than some other solving techniques for certain types of equations?', ['It provides a systematic guess-and-check structure that works well when the equation has a predictable, recognizable form', 'This method is always more difficult than any other available solving technique', 'This concept has no connection to functions', 'Equations with a recognizable form can never be solved using this method'], 0),
    ('Why is it important to choose an appropriately general guess when applying the method of undetermined coefficients?', ['An overly simple or incorrect guess may fail to include all the terms needed to satisfy the original equation', 'The specific form of the guess used never actually matters for reaching a correct final solution', 'This concept has no relevance to functions', 'Any arbitrary guess will always work correctly regardless of its form'], 0)]),
CA('Calculus: The Fourier Transform — From Series to Transform',
   'Grade 12 Calculus strand: the Fourier transform extends the idea of a Fourier series to non-periodic functions, decomposing a function into a continuous spectrum of frequencies rather than a discrete sum.',
   [('What does the Fourier transform extend the idea of a Fourier series to?', ['Non-periodic functions', 'Only functions with a single repeating value', 'A concept unrelated to calculus', 'Functions defined solely on whole numbers'], 0),
    ('Does the Fourier transform decompose a function into a continuous spectrum of frequencies?', ['Yes', 'No, it never breaks a function down into any frequency information', 'A concept unrelated to the Fourier transform', 'Frequencies have no connection to how a Fourier transform works'], 0),
    ('Is a Fourier series generally associated with periodic functions, while the Fourier transform applies more broadly?', ['Yes', 'No, both concepts only ever apply to the exact same type of function', 'A concept unrelated to the Fourier transform', 'Periodicity has no connection to the distinction between these two concepts'], 0),
    ('Why might the Fourier transform be useful for analyzing an audio signal that does not repeat in a perfectly periodic pattern?', ['It can decompose the signal into its underlying frequency components regardless of whether the original signal repeats exactly', 'The Fourier transform can only ever be applied to signals that repeat in a perfectly periodic way', 'This concept has no connection to calculus', 'Audio signals can never be analyzed using any frequency-based mathematical tool'], 0),
    ('Why is the Fourier transform considered a foundational tool in fields like signal processing and image compression?', ['It allows complex signals or images to be represented and manipulated in terms of their underlying frequency content', 'The Fourier transform has no practical application in signal processing or image compression', 'This concept has no relevance to calculus', 'Signal processing never involves analyzing any kind of frequency information'], 0)]),
PH('Physics: Sonoluminescence — Light from Sound',
   'Grade 12 Physics strand: sonoluminescence occurs when sound waves cause tiny gas bubbles in a liquid to collapse so rapidly and intensely that they emit brief flashes of light.',
   [('What causes sonoluminescence to occur?', ['Sound waves causing tiny gas bubbles to collapse rapidly', 'A completely silent, unrelated chemical reaction', 'A concept unrelated to physics', 'Light shining directly onto a solid metal surface'], 0),
    ('Does sonoluminescence involve gas bubbles emitting brief flashes of light?', ['Yes', 'No, sonoluminescence never produces any visible light', 'A concept unrelated to sonoluminescence', 'Gas bubbles have no connection to this phenomenon'], 0),
    ('Does sonoluminescence require the rapid, intense collapse of tiny bubbles in a liquid?', ['Yes', 'No, bubble collapse has no connection to sonoluminescence', 'A concept unrelated to sonoluminescence', 'This phenomenon occurs only in a completely dry, gas-free environment'], 0),
    ('Why do scientists find the extremely high temperatures generated during bubble collapse in sonoluminescence surprising?', ['The brief but intense compression of the collapsing bubble can generate temperatures far higher than the surrounding liquid', 'Bubble collapse never generates any significant increase in temperature', 'This concept has no connection to physics', 'Sonoluminescence occurs at exactly the same temperature as the surrounding liquid at all times'], 0),
    ('Why is sonoluminescence considered a valuable phenomenon for physicists studying extreme, localized conditions?', ['It offers a rare, accessible way to observe extremely high temperatures and pressures within a small, controlled laboratory setting', 'Sonoluminescence provides no useful information about extreme physical conditions', 'This concept has no relevance to physics', 'Extreme temperatures and pressures can never be studied using this type of phenomenon'], 0)]),
]),

day(89, [
E('Literature: Speculative Fiction and the Ethics of World-Building',
  'Grade 12 English strand: speculative fiction imagines alternative worlds or futures, raising ethical questions about the societies, technologies, and consequences an author chooses to construct.',
  [('What does speculative fiction imagine?', ['Alternative worlds or futures', 'Only strictly factual historical events', 'A concept unrelated to literature', 'A single unchanging present-day setting'], 0),
   ('Can speculative fiction raise ethical questions about the societies an author constructs?', ['Yes', 'No, speculative fiction never raises any ethical questions', 'A concept unrelated to speculative fiction', 'Ethics has no connection to how fictional worlds are built'], 0),
   ('Why might an author use a speculative fiction setting to explore a real-world ethical issue indirectly?', ['A fictional, distanced setting can allow readers to consider difficult issues without the immediate defensiveness a direct discussion might provoke', 'Speculative fiction never provides any useful way to explore real-world ethical concerns', 'This concept has no connection to literature', 'Fictional settings always completely disconnect a story from any real-world relevance'], 0),
   ('Which of these best describes an ethical question raised by world-building in speculative fiction?', ['What are the consequences of a society that assigns each citizen’s occupation before birth?', 'What font should be used for the book’s cover design?', 'How many chapters should the novel contain?', 'What is the author’s preferred writing schedule?'], 0),
   ('Why is examining the ethics of world-building considered valuable when studying speculative fiction critically?', ['It encourages readers to consider the implications and assumptions embedded within an author’s imagined world', 'The ethics of world-building has no connection to critically studying speculative fiction', 'This concept has no relevance to literature', 'Speculative fiction worlds are always constructed with no underlying assumptions or implications'], 0)]),
AF('Discrete Math: Ramsey Theory — An Introduction',
   'Grade 12 Advanced Functions strand: Ramsey theory studies the conditions under which a certain kind of order or pattern must eventually appear within a sufficiently large structure, even one that seems random.',
   [('What does Ramsey theory study?', ['The conditions under which order must eventually appear within a large structure', 'Only structures that are guaranteed to remain completely disordered forever', 'A concept unrelated to discrete math', 'A single isolated numerical calculation with no broader pattern'], 0),
    ('Does Ramsey theory suggest that complete disorder becomes impossible once a structure is sufficiently large?', ['Yes', 'No, Ramsey theory has no connection to order appearing within large structures', 'A concept unrelated to Ramsey theory', 'Structure size has no connection to whether patterns must appear'], 0),
    ('Is Ramsey theory associated with a well-known saying that suggests complete disorder is impossible in sufficiently large systems?', ['Yes', 'No, Ramsey theory is never associated with any such idea', 'A concept unrelated to Ramsey theory', 'Order and structure have no connection to Ramsey theory whatsoever'], 0),
    ('Why might Ramsey theory be relevant to a simple example like guaranteeing that within a large enough group of people, some subset shares mutual acquaintances or mutual strangers?', ['Ramsey theory guarantees this kind of pattern must emerge once the group reaches a large enough size, regardless of how relationships are arranged', 'This kind of guarantee has no connection to any principle within Ramsey theory', 'This concept has no connection to functions', 'Patterns among relationships in a group can never be guaranteed by any mathematical principle'], 0),
    ('Why is Ramsey theory considered a fascinating area of discrete mathematics for advanced students?', ['It reveals that seemingly unpredictable systems must still contain guaranteed patterns once they reach a sufficient size', 'Ramsey theory has no connection to any patterns found within mathematical structures', 'This concept has no relevance to functions', 'Discrete mathematics never studies the emergence of patterns within larger structures'], 0)]),
CA('Calculus: Green’s Theorem in the Plane',
   'Grade 12 Calculus strand: Green’s theorem relates a line integral around a closed curve in the plane to a double integral of the curve’s enclosed region, connecting circulation to a region’s interior behaviour.',
   [('What does Green’s theorem relate a line integral around a closed curve to?', ['A double integral over the curve’s enclosed region', 'A single unrelated point value with no integral involved', 'A concept unrelated to calculus', 'The volume of an entirely separate three-dimensional solid'], 0),
    ('Does Green’s theorem apply to curves and regions located in a two-dimensional plane?', ['Yes', 'No, Green’s theorem only ever applies to three-dimensional space', 'A concept unrelated to Green’s theorem', 'Two-dimensional regions have no connection to this theorem'], 0),
    ('Does Green’s theorem connect the idea of circulation around a boundary to behaviour within the enclosed interior?', ['Yes', 'No, circulation has no connection to this theorem', 'A concept unrelated to Green’s theorem', 'The interior of a region is never relevant to Green’s theorem'], 0),
    ('Why might Green’s theorem be useful for simplifying a difficult line integral calculation around a complicated closed curve?', ['Converting the line integral into a double integral over the enclosed region can sometimes make the calculation more manageable', 'Green’s theorem never simplifies any type of integral calculation', 'This concept has no connection to calculus', 'Line integrals and double integrals are never mathematically related to one another'], 0),
    ('Why is Green’s theorem often introduced as a foundational stepping stone toward understanding Stokes’ theorem in three dimensions?', ['Green’s theorem represents a two-dimensional special case of the more general relationship expressed by Stokes’ theorem', 'Green’s theorem has no mathematical connection to Stokes’ theorem in any way', 'This concept has no relevance to calculus', 'Two-dimensional and three-dimensional integral theorems are always entirely unrelated to one another'], 0)]),
PH('Physics: The Fermi Paradox and Astrophysical Constraints',
   'Grade 12 Physics strand: the Fermi paradox highlights the apparent contradiction between the high probability of extraterrestrial civilizations existing and the lack of any confirmed evidence of their presence.',
   [('What does the Fermi paradox highlight an apparent contradiction between?', ['The probability of extraterrestrial civilizations and the lack of confirmed evidence of them', 'The exact number of planets in our solar system', 'A concept unrelated to physics', 'The distance between Earth and the moon'], 0),
    ('Has any confirmed evidence of extraterrestrial civilizations been found, according to the Fermi paradox?', ['No', 'Yes, extraterrestrial civilizations have already been definitively confirmed', 'A concept unrelated to the Fermi paradox', 'Evidence of extraterrestrial life has no connection to this paradox'], 0),
    ('Does the Fermi paradox consider the vast number of stars and potentially habitable planets in the universe?', ['Yes', 'No, the number of stars and planets has no connection to this paradox', 'A concept unrelated to the Fermi paradox', 'The scale of the universe is never considered relevant to this question'], 0),
    ('Why might astrophysical constraints, like the vast distances between stars, help explain the Fermi paradox?', ['Enormous distances could make travel or communication between civilizations extremely difficult, even if such civilizations exist', 'Distance between stars has no connection to any possible explanation for the Fermi paradox', 'This concept has no connection to physics', 'Travel between stars is already known to be simple and instantaneous for any civilization'], 0),
    ('Why is the Fermi paradox considered a valuable topic for connecting physics with broader questions about life in the universe?', ['It combines astrophysical reasoning about the scale of the universe with deep philosophical questions about the likelihood of other civilizations', 'The Fermi paradox has no connection to any broader philosophical or scientific question', 'This concept has no relevance to physics', 'Questions about extraterrestrial life have no connection to any principle of physics or astronomy'], 0)]),
]),

day(90, [
E('Review: Literary Form, Media, and Style (Days 81-89)',
  'Grade 12 English strand review: students revisit the roman a clef, the prose poem, data journalism, ekphrasis, impromptu academic response, annotated bibliographies, the unreliable chronicle, periodic and cumulative sentences, and speculative fiction ethics.',
  [('What does a roman a clef portray under a thin fictional disguise?', ['Real people and events', 'Only entirely invented, fantastical worlds', 'A concept unrelated to literature', 'A textbook’s worth of unrelated facts'], 0),
   ('What form is a prose poem written in?', ['Paragraph form without line breaks', 'Only traditional poetic stanzas with strict rhyme', 'A concept unrelated to writing', 'A formal legal contract format'], 0),
   ('What does ekphrasis describe?', ['A visual artwork', 'A weather pattern occurring in a specific season', 'A concept unrelated to literature', 'A mathematical proof with no artistic content'], 0),
   ('When does a periodic sentence reveal its main point?', ['At the very end of the sentence', 'At the very beginning of the sentence', 'A concept unrelated to grammar', 'A periodic sentence never actually contains any main point'], 0),
   ('What does speculative fiction imagine?', ['Alternative worlds or futures', 'Only strictly factual historical events', 'A concept unrelated to literature', 'A single unchanging present-day setting'], 0)]),
AF('Review: Number Theory, Interpolation, and Advanced Structures (Days 81-89)',
   'Grade 12 Advanced Functions strand review: students revisit the Riemann zeta function, polynomial interpolation, the Chinese remainder theorem, generating functions, the fundamental theorem of algebra, Fermat’s little theorem, convex and concave functions, undetermined coefficients, and Ramsey theory.',
   [('What does the Riemann zeta function connect number theory to?', ['Complex analysis', 'Only basic arithmetic with whole numbers', 'A concept unrelated to functions', 'Elementary geometry only'], 0),
    ('What does Lagrange’s method construct?', ['A polynomial that passes exactly through a given set of data points', 'A random polynomial unrelated to any specific data', 'A concept unrelated to functions', 'A single straight line with no curvature'], 0),
    ('What does the fundamental theorem of algebra state about a non-constant polynomial?', ['It has at least one complex root', 'It always has exactly zero roots', 'A concept unrelated to functions', 'It can never be solved using any method'], 0),
    ('What shape does a convex function typically curve like?', ['A bowl, curving upward', 'A flat, straight line with no curvature at all', 'A concept unrelated to functions', 'A dome, curving downward'], 0),
    ('What does Ramsey theory study?', ['The conditions under which order must eventually appear within a large structure', 'Only structures that are guaranteed to remain completely disordered forever', 'A concept unrelated to discrete math', 'A single isolated numerical calculation with no broader pattern'], 0)]),
CA('Review: Advanced Integration and Vector Calculus (Days 81-89)',
   'Grade 12 Calculus strand review: students revisit the epsilon-delta definition, numerical differentiation, series solutions, the integral test, the washer method, the divergence theorem, Stokes’ theorem, the Fourier transform, and Green’s theorem.',
   [('What does the epsilon-delta definition provide for the concept of a limit?', ['A rigorous, formal definition using precise inequalities', 'Only an informal, intuitive description with no precision', 'A concept unrelated to calculus', 'A definition that applies only to whole numbers'], 0),
    ('What kind of solid does the washer method calculate the volume of?', ['A solid of revolution with a hole through its center', 'A solid with absolutely no hole of any kind', 'A concept unrelated to calculus', 'A flat, two-dimensional shape with no volume'], 0),
    ('What does the divergence theorem relate the flow of a vector field through a closed surface to?', ['The divergence of the field integrated over the enclosed volume', 'A single unrelated scalar number with no integral involved', 'A concept unrelated to calculus', 'The area of a completely separate, unrelated shape'], 0),
    ('What does the Fourier transform extend the idea of a Fourier series to?', ['Non-periodic functions', 'Only functions with a single repeating value', 'A concept unrelated to calculus', 'Functions defined solely on whole numbers'], 0),
    ('What does Green’s theorem relate a line integral around a closed curve to?', ['A double integral over the curve’s enclosed region', 'A single unrelated point value with no integral involved', 'A concept unrelated to calculus', 'The volume of an entirely separate three-dimensional solid'], 0)]),
PH('Review: Particle, Quantum, and Astrophysical Phenomena (Days 81-89)',
   'Grade 12 Physics strand review: students revisit neutrino oscillations, quantum tunneling, the Meissner effect, gravitational lensing, the Chandrasekhar limit, quark-gluon plasma, the Aharonov-Bohm effect, sonoluminescence, and the Fermi paradox.',
   [('What can neutrinos do as they travel, according to neutrino oscillation?', ['Change between different types called flavors', 'Instantly disappear with no trace', 'A concept unrelated to physics', 'Always remain in exactly the same unchanging state'], 0),
    ('What does quantum tunneling describe?', ['How a particle can pass through an energy barrier it classically should not overcome', 'How particles always bounce off every barrier with no exception', 'A concept unrelated to physics', 'How particles disappear permanently upon striking a barrier'], 0),
    ('What does gravitational lensing occur due to?', ['The gravity of a massive object bending light from a distant source', 'Only ordinary reflections off a mirror-like surface', 'A concept unrelated to physics', 'Sound waves travelling through empty space'], 0),
    ('What does the Chandrasekhar limit define?', ['The maximum mass a white dwarf star can have before further collapse', 'The minimum temperature required for a star to form', 'A concept unrelated to physics', 'The exact colour every white dwarf star must appear'], 0),
    ('What does the Fermi paradox highlight an apparent contradiction between?', ['The probability of extraterrestrial civilizations and the lack of confirmed evidence of them', 'The exact number of planets in our solar system', 'A concept unrelated to physics', 'The distance between Earth and the moon'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g12_81_90)
    append_to(12, g12_81_90)
