#!/usr/bin/env python3
"""Grade 10 — days 1-15. Subjects: English, Math, Science, History."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,write_new

U='https://tvolearn.com/pages/grade-10'
R='TVO Learn: Grade 10'

def E(t,s,q): return sub('English',t,s,R,U,q)
def M(t,s,q): return sub('Math',t,s,R,U,q)
def Sc(t,s,q): return sub('Science',t,s,R,U,q)
def H(t,s,q): return sub('History',t,s,R,U,q)

g10=[
day(1,[
E('Literary Analysis: Elements of Fiction','Students analyse the key elements of fiction — plot, character, setting, conflict, theme, point of view, and style — in preparation for novel and short story study.',[
  ('Which element of fiction asks "how is the story told and in whose voice?"',['Plot','Setting','Theme','Point of view and narrative style'],3),
  ('The climax of a narrative is ___.',['the opening situation','the falling action','the point of highest tension where the central conflict reaches its peak','the resolution where conflict is resolved'],2),
  ('A flat character is ___.',['always the protagonist','a character who changes dramatically','a character with only one or two traits who does not develop over the course of the story','more realistic than a round character'],2),
  ('Setting contributes to a story by ___.',['only providing physical location','being unimportant to theme','establishing mood, creating symbolic meaning, reflecting character psychology, and shaping the conflicts characters face','only indicating time period'],2),
  ('Style in fiction refers to ___.',['only the plot structure','the author\'s characteristic way of using language — sentence structure, diction, imagery, rhythm, and tone','only genre','the length of the work'],1)]),
M('Linear Systems: Two Variables','Students review and extend solving systems of linear equations (two variables) graphically, by substitution, and by elimination. They interpret solutions in context.',[
  ('A system of two linear equations with one unique solution means ___.',['the lines are parallel','the equations are identical','the lines intersect at exactly one point','there are infinite solutions'],2),
  ('Solve by elimination: 3x + y = 11 and x − y = 1',['x = 3, y = 2','x = 2, y = 5','x = 4, y = −1','x = 3, y = −2'],0),
  ('Solve by substitution: y = 2x − 3 and 4x − y = 9',['x = 3, y = 3','x = 2, y = 1','x = 4, y = 5','x = 3, y = 1'],0),
  ('A system with no solution has lines that are ___.',['perpendicular','identical','intersecting','parallel — same slope, different y-intercepts'],3),
  ('In context, the solution (3, 150) to a cost system where x = hours and y = dollars means ___.',['the minimum cost is 3','the maximum hours are 150','at 3 hours, the cost is $150 — the two pricing options cost the same','3 hours costs $0'],2)]),
Sc('Chemistry: Atomic Theory and the Periodic Table','Students examine the development of atomic theory (Dalton, Thomson, Rutherford, Bohr) and how the periodic table organises elements by atomic structure.',[
  ('Rutherford\'s gold foil experiment showed ___.',['atoms are solid spheres','electrons orbit in shells','atoms have a small, dense, positively charged nucleus with mostly empty space around it','atoms contain no neutrons'],2),
  ('The Bohr model of the atom shows electrons ___.',['randomly distributed throughout','in the nucleus','orbiting the nucleus in specific energy levels (shells)','only on one side of the nucleus'],2),
  ('In the periodic table, elements in the same group (column) ___.',['have the same atomic mass','are in the same period','share similar chemical properties because they have the same number of valence electrons','have the same number of neutrons'],2),
  ('Atomic number equals ___.',['the number of neutrons','the number of protons (which equals the number of electrons in a neutral atom)','the mass number','protons plus neutrons'],1),
  ('Mass number equals ___.',['atomic number only','number of electrons','number of protons','protons + neutrons'],3)]),
H('Canada and World War II: Causes and Outbreak','Students examine the causes of WWII — rise of fascism, appeasement, Nazi aggression — and Canada\'s declaration of war and early contributions.',[
  ('The policy of appeasement pursued by Britain and France in the 1930s meant ___.',['confronting Hitler\'s aggression immediately','imposing economic sanctions only','making concessions to Hitler (notably at Munich, 1938) to avoid war — ultimately failing when Germany invaded Poland','supporting Germany\'s expansion'],2),
  ('Canada declared war on Germany in September 1939 ___.',['the same day as Britain, demonstrating full dependence','before Britain, showing independence','a week after Britain, demonstrating growing autonomy as a sovereign nation','only after Japan attacked Pearl Harbor'],2),
  ('The Holocaust refers to ___.',['a German military strategy','civilian war casualties in general','the systematic Nazi genocide of six million Jews and millions of others (Roma, LGBTQ+, disabled people, Soviet POWs)','the firebombing of German cities'],2),
  ('The Battle of the Atlantic was crucial for Canada because ___.',['it was fought in the Pacific','it only involved the British Navy','the Royal Canadian Navy played a central role protecting supply convoys that kept Britain alive and enabled the Allied war effort','it ended the war quickly'],2),
  ('Canada\'s decision to declare war separately from Britain in 1939 was significant because ___.',['it made no difference','Canada was forced to declare war','it was a major assertion of Canadian sovereignty — contrasting with WWI when Canada was automatically at war when Britain declared it','Canada opposed the war initially'],2)])]),
day(2,[
E('Writing: The Literary Essay','Students write analytical literary essays with a clear thesis, developed body paragraphs using textual evidence, and effective conclusions. They apply the writing process.',[
  ('A literary essay thesis should ___.',['summarise the plot','ask a question about the text','state an arguable, specific interpretation of the text that the essay will prove through close analysis','describe the author\'s biography'],2),
  ('Body paragraphs in a literary essay should follow ___.',['no particular structure','the PEEL or similar structure: Point, Evidence (quotation), Explanation/Analysis, Link','only description of events','the plot chronologically'],1),
  ('Embedding a quotation means ___.',['dropping in a quote with no context','using only long block quotations','integrating the quoted words smoothly into your own sentence so the result is grammatically coherent','avoiding quotations entirely'],2),
  ('Literary present tense means ___.',['discussing the author\'s life in present tense','using future tense for predictions','writing about the events of a literary text in present tense (e.g., "Hamlet hesitates because...")','only for poetry'],2),
  ('A counterargument paragraph in a literary essay ___.',['proves your thesis is wrong','is always required','acknowledges a competing interpretation and then refutes it, making your argument more sophisticated','only appears in persuasive essays'],2)]),
M('Quadratic Equations: Factoring and the Quadratic Formula','Students solve quadratic equations by factoring and applying the quadratic formula. They connect solutions to graphs of parabolas.',[
  ('The quadratic formula is ___.',['x = −b/2a','x = (−b ± √(b²−4ac)) / 2a','x = b² − 4ac','x = a(x−h)² + k'],1),
  ('The discriminant b² − 4ac tells you ___.',['the vertex of the parabola','the y-intercept','the nature of solutions: positive = 2 real roots, zero = 1 repeated root, negative = no real roots','the axis of symmetry'],2),
  ('Factor and solve: x² − 7x + 12 = 0',['x = 3 and x = 4','x = −3 and x = −4','x = 3 and x = −4','x = −3 and x = 4'],0),
  ('Solve using the quadratic formula: 2x² + 3x − 2 = 0',['x = 1/2 and x = −2','x = 2 and x = −1/2','x = 1 and x = −2','x = 1/2 and x = 2'],0),
  ('The solutions of a quadratic equation correspond to ___.',['the y-intercepts of the parabola','the vertex of the parabola','the x-intercepts (zeros/roots) of the corresponding parabola','the axis of symmetry'],2)]),
Sc('Chemistry: Chemical Bonding','Students explore ionic bonding (transfer of electrons between metals and non-metals) and covalent bonding (sharing of electrons between non-metals).',[
  ('Ionic bonds form when ___.',['two non-metals share electrons','a metal transfers electrons to a non-metal, forming positive and negative ions that attract each other','two metals combine','atoms share electrons equally'],1),
  ('Covalent bonds form when ___.',['metals and non-metals combine','two non-metals share one or more pairs of electrons to achieve stable electron configurations','electrons are transferred','ionic compounds dissolve'],1),
  ('NaCl (table salt) is an example of ___.',['a covalent compound','a metallic bond','an ionic compound (Na⁺ and Cl⁻ attracted by electrostatic force)','a noble gas compound'],2),
  ('H₂O is an example of ___.',['an ionic compound','a metallic compound','a covalent compound (oxygen and hydrogen share electrons)','a noble gas compound'],2),
  ('Valence electrons are important in bonding because ___.',['they are in the nucleus','only metals have them','they are the outermost electrons that atoms share or transfer during chemical bonding','they are irrelevant to chemical reactions'],2)]),
H('Canada\'s War Effort: Military Contributions','Students examine Canada\'s major military contributions in WWII — Battle of Britain, Dieppe, Sicily, Italy, and D-Day.',[
  ('The British Commonwealth Air Training Plan (BCATP) located in Canada was significant because ___.',['it trained only British pilots','Canada refused to participate','it trained nearly 140,000 air crew from Allied nations in Canada, making Canada crucial to Allied air power','it was a failure'],2),
  ('The Dieppe Raid (August 1942) was significant because ___.',['it was a major Allied victory','Canada was not involved','despite being a costly failure with enormous Canadian casualties, it provided crucial lessons that improved the planning of D-Day','it ended the war in Europe'],2),
  ('Canadian forces participated in the Italian Campaign (1943-45), which was important because ___.',['it had no strategic value','the Pacific front was more important','liberating Italy helped weaken Axis power in southern Europe and tied up significant German forces, contributing to the overall Allied strategy','Canada was only involved in Northwest Europe'],2),
  ('On D-Day (June 6, 1944), Canadians landed at ___.',['Omaha Beach','Utah Beach','Gold Beach','Juno Beach, one of five Allied landing zones, where they achieved the greatest advance of any Allied force on that day'],3),
  ('The Liberation of the Netherlands (1944-45) is remembered because ___.',['it had little strategic importance','only British forces were involved','Canadian forces played the primary role, and the Dutch people have maintained a deep gratitude and friendship with Canada ever since','it was the last battle of WWI'],2)])]),
day(3,[
E('Shakespeare: Studying a Play','Students read and analyse a Shakespearean play in depth, examining dramatic conventions, language, themes, and historical context. (e.g., Romeo and Juliet, Macbeth, A Midsummer Night\'s Dream)',[
  ('Tragic heroes in Shakespeare typically possess ___.',['no admirable qualities','only virtues with no flaws','a fundamental flaw (hamartia) that, combined with fate and circumstance, leads to their destruction despite their admirable qualities','complete knowledge of their fate'],2),
  ('Shakespeare\'s language uses iambic pentameter, which ___.',['is a type of rhyme scheme','has 12 syllables per line','has 10 syllables per line alternating unstressed and stressed (da-DUM), creating a natural speech rhythm','is always rhymed'],2),
  ('Dramatic irony in a Shakespeare play occurs when ___.',['two characters argue','the audience knows something a character does not, creating tension or dark humour (e.g., the audience knows Romeo and Juliet will die)','the plot has a twist ending','a character delivers a soliloquy'],1),
  ('The theatrical conventions of the Globe Theatre included ___.',['women playing female roles','elaborate special effects','all male cast (boys playing women), minimal scenery, and audiences standing in the yard or seated in galleries — the language did the work of setting and atmosphere','private performances only for royalty'],2),
  ('Analysing Shakespeare\'s language involves ___.',['only translating into modern English','ignoring the poetry','examining metaphor, imagery, verse vs. prose, wordplay, and how specific language choices reveal character and develop theme','memorising speeches'],2)]),
M('Quadratics: Graphing Parabolas','Students graph parabolas using vertex form y = a(x−h)² + k, identify key features (vertex, axis of symmetry, direction of opening, x- and y-intercepts), and use transformations.',[
  ('In y = a(x − h)² + k, the vertex is ___.',['(h, k)','(k, h)','(−h, k)','(a, k)'],0),
  ('If a > 0, the parabola opens ___.',['downward','horizontally','upward','sideways'],2),
  ('The axis of symmetry of a parabola in vertex form y = a(x − h)² + k is ___.',['y = k','x = 0','x = h','y = h'],2),
  ('The graph of y = −2(x − 3)² + 5 has vertex ___ and opens ___.',['(3, 5) and upward','(−3, 5) and downward','(3, 5) and downward','(−3, −5) and upward'],2),
  ('Converting from standard form (ax² + bx + c) to vertex form requires ___.',['factoring only','the quadratic formula','completing the square','graphing first'],2)]),
Sc('Chemistry: Chemical Reactions','Students classify chemical reactions (synthesis, decomposition, single displacement, double displacement, combustion) and balance equations.',[
  ('A balanced chemical equation has ___.',['more products than reactants','the same number of atoms of each element on both sides of the equation','different total masses on each side','fewer products than reactants'],1),
  ('In a synthesis reaction ___.',['one compound breaks into two products','two or more reactants combine to form one product','one element replaces another in a compound','two ionic compounds exchange ions'],1),
  ('Combustion reactions always involve ___.',['water and carbon dioxide only','a compound decomposing','a substance reacting with oxygen to produce heat and light, usually producing CO₂ and H₂O','two ionic compounds reacting'],2),
  ('The Law of Conservation of Mass states ___.',['mass is created in exothermic reactions','mass is lost in combustion','the total mass of reactants equals the total mass of products in a chemical reaction','only applies to physical changes'],2),
  ('Balance: H₂ + O₂ → H₂O. The balanced equation is ___.',['H₂ + O₂ → H₂O','2H₂ + O₂ → 2H₂O','H₂ + 2O₂ → H₂O','H₂ + O₂ → 2H₂O'],1)]),
H('Canada\'s Home Front in WWII','Students examine how WWII transformed Canadian society — women\'s roles, war economy, rationing, and injustices such as Japanese-Canadian internment.',[
  ('The internment of Japanese Canadians during WWII involved ___.',['voluntary relocation for safety','about 100 people','the forced removal of approximately 22,000 Japanese Canadians from BC, confiscation of their property, and internment in camps — a serious violation of civil rights','immediate restoration of rights after the war'],2),
  ('Women\'s roles changed during WWII because ___.',['women were prohibited from wartime work','nothing changed significantly','with men overseas, women entered the industrial workforce in large numbers, taking on roles previously closed to them','only nursing was available'],2),
  ('War industries in Canada during WWII ___.',['had no impact on the economy','led to economic depression','transformed Canada\'s economy, producing ships, aircraft, and munitions that made Canada a significant industrial power','employed only men'],2),
  ('Rationing during WWII in Canada ___.',['was not necessary in Canada','only applied to luxury goods','restricted civilian consumption of resources (food, fuel, rubber, metals) to ensure sufficient supplies for the military','was entirely voluntary'],2),
  ('The Quebec government\'s resistance to conscription during WWII ___.',['showed Quebec supported full participation','had no significant effect','reflected deep French-Canadian opposition to fighting in what many Québécois saw as a British war, reviving the tensions of the 1917 conscription crisis','was supported by the federal Liberal government fully'],2)])]),
day(4,[
E('Media Studies: Advertising and Persuasion','Students critically analyse advertising texts across media, examining techniques of persuasion, target audiences, construction of identity, and representation.',[
  ('Semiotics in media analysis is the study of ___.',['statistics about media use','only visual art','signs and symbols and how they create meaning — how images, words, sounds, and colours communicate culturally specific messages','only written language'],2),
  ('A target audience is ___.',['all people everywhere','only children','the specific group of people an advertiser intends to reach, defined by demographics, interests, and values','only people who buy the product'],2),
  ('How advertising constructs identity means ___.',['advertising reflects only real identities','products have no connection to identity','advertisers create associations between products and desirable identities, lifestyles, or values — buying the product is implicitly coded as "becoming" that identity','only clothing ads do this'],2),
  ('Representation in media refers to ___.',['technical production quality','only who is shown in ads','how media texts portray different groups of people — which groups are shown, how, in what roles, and which groups are absent or stereotyped','only gender representation'],2),
  ('Decoding media means ___.',['fixing broken signals','only describing what you see','actively analysing the constructed meanings, assumptions, and ideological messages embedded in media texts — asking who made it, for what purpose, and whose interests it serves','only for professional critics'],2)]),
M('Quadratics: Standard Form and Applications','Students work with quadratic functions in standard form (y = ax² + bx + c), find the vertex using x = −b/2a, and model real-world situations.',[
  ('In the standard form y = ax² + bx + c, the axis of symmetry is ___.',['x = c','x = a/b','x = −b/2a','x = b/2a'],2),
  ('A ball is thrown and its height (in metres) is h = −5t² + 20t + 2. The t-value at max height = ?',['2 s (from t = −20/(2×−5) = 2)','4 s','10 s','1 s'],0),
  ('The y-intercept of y = 3x² − 5x + 7 is ___.',['3','−5','7','0'],2),
  ('Revenue R = x(100 − 2x) where x = price increase. Maximum revenue is at x = ___.',['100','50','25','0'],2),
  ('The parabola y = −x² + 4x − 3 opens ___ and its vertex is at ___.',['upward, (2, 1)','downward, (2, 1)','downward, (−2, 1)','upward, (−2, −1)'],1)]),
Sc('Biology: Cell Biology Review and DNA','Students review cell structure and extend understanding to DNA structure, the genetic code, and the processes of transcription and translation.',[
  ('DNA is a double helix composed of ___.',['amino acids and lipids','nucleotides — each with a sugar (deoxyribose), phosphate group, and one of four nitrogenous bases (A, T, G, C)','proteins only','lipids and carbohydrates'],1),
  ('Complementary base pairing in DNA means ___.',['any base can pair with any other','Adenine pairs with Thymine (A-T) and Guanine pairs with Cytosine (G-C)','bases pair randomly','only A-T pairs exist'],1),
  ('Transcription is the process of ___.',['copying DNA to make a DNA copy','using mRNA to make a protein','synthesising mRNA from a DNA template in the nucleus','cell division'],2),
  ('Translation is the process of ___.',['copying DNA','making mRNA','synthesising a protein by reading the mRNA sequence using ribosomes and tRNA','DNA replication'],2),
  ('A mutation is ___.',['always harmful','a change in the DNA sequence, which may be neutral, beneficial, or harmful, and can be caused by errors in replication or environmental factors (mutagens)','always beneficial','only in cancer cells'],1)]),
H('The Cold War: Origins and Canada\'s Role','Students examine the ideological conflict between the USA and USSR, Canada\'s participation in NATO and NORAD, and the Korean War.',[
  ('The Cold War was primarily ___.',['a hot shooting war between the US and USSR','an economic partnership','a military conflict in Asia only','a political, economic, and ideological struggle between the capitalist West (led by the US) and the communist East (led by the USSR), 1945–1991'],3),
  ('The NATO alliance, which Canada joined in 1949, committed members to ___.',['economic cooperation only','trade agreements','collective defence: an attack on one member is considered an attack on all','a shared currency'],2),
  ('NORAD (1958) involved Canada and the United States in ___.',['joint economic management','a trade agreement','joint air defence of North America against the threat of Soviet nuclear bomber attack','a shared space program'],2),
  ('Canada\'s participation in the Korean War (1950-53) saw ___.',['Canada officially neutral','no Canadian casualties','over 26,000 Canadians serving as part of the UN force, with Canada fulfilling its collective security commitments','Canada leading the UN forces'],2),
  ('The Avro Arrow (CF-105) controversy in 1959 involved ___.',['Canada building nuclear weapons','a successful fighter jet program','the Canadian government cancelling what was arguably the world\'s most advanced jet interceptor, raising questions about Canadian industrial sovereignty and dependence on the US','a dispute with the Soviet Union'],2)])]),
day(5,[
E('Independent Reading: Novel Selection and Response','Students select a Canadian novel or a world novel in English translation and write analytical reading journal entries tracking theme, character, and author\'s craft.',[
  ('When selecting a novel for independent study, you should consider ___.',['only page count','only genre','whether the novel offers complexity — rich characters, thematic depth, and stylistic choices worth analysing','only how popular it is'],2),
  ('A reading response that analyses theme goes beyond plot by ___.',['listing chapter summaries','counting characters','examining how specific events, characters, and images work together to develop the author\'s central insight about human experience','only describing the ending'],2),
  ('Tracking character arc means ___.',['listing every action a character takes','noting physical descriptions only','examining how a character\'s beliefs, values, and behaviour change in response to the conflicts and events of the narrative','only tracking the protagonist'],2),
  ('Reading a Canadian novel specifically can develop ___.',['only grammar skills','awareness of Canadian geography','understanding of Canadian history, social issues, and diverse voices — including Indigenous, immigrant, and regional perspectives often absent from US and British canons','only French-language knowledge'],2),
  ('An analytical journal entry differs from a summary by ___.',['being longer','having no plot references','asking "why" and "how" rather than only "what" — examining the author\'s choices and their effects rather than retelling events','using more quotations'],2)]),
M('Quadratics: Revenue, Profit, and Projectile Problems','Students apply quadratic models to real-world situations: projectile motion, revenue and profit maximisation, area optimisation.',[
  ('A projectile is launched with height h = −4.9t² + 30t + 1.5. Maximum height occurs at t = ?',['approximately 3.06 s (using t = −b/2a = −30/(2×−4.9))','5 s','0 s','1.5 s'],0),
  ('Revenue = price × quantity sold. If quantity decreases as price increases according to q = 200 − 2p, then Revenue = ?',['200p','p(200 − 2p) = 200p − 2p² — a downward parabola','2p − 200','200 − 2p'],1),
  ('For R = −2p² + 200p, maximum revenue is at p = ___.',['200','100','50','25'],2),
  ('A rectangular garden has perimeter 40 m. The area as a function of width w is ___.',['A = w²','A = w(40 − w)','A = w(20 − w)','A = 20w'],2),
  ('The maximum area of the garden from the previous question is ___.',['400 m²','200 m²','100 m²','25 m²'],2)]),
Sc('Biology: Genetics and Heredity','Students apply Mendelian genetics — dominant/recessive, codominance, incomplete dominance, multiple alleles — to dihybrid crosses and inheritance patterns.',[
  ('In a dihybrid cross between two AaBb parents, the expected phenotype ratio of offspring is ___.',['1:2:1','1:1','3:1','9:3:3:1'],3),
  ('Codominance means ___.',['one allele is dominant over another','the heterozygote shows a blend of both traits','both alleles are fully expressed simultaneously in the phenotype (e.g., AB blood type showing both A and B antigens)','one allele disappears'],2),
  ('Incomplete dominance means ___.',['one allele masks the other','the heterozygote shows a phenotype intermediate between the two homozygous phenotypes (e.g., red + white = pink)','both alleles show separately','neither allele expresses'],1),
  ('Sex-linked traits are carried on ___.',['autosomes only','both X and Y chromosomes equally','the sex chromosomes (usually X), making them more commonly expressed in males (XY) who have only one X','mitochondrial DNA only'],2),
  ('Genetic disorders such as cystic fibrosis are ___.',['always dominant','caused by environmental factors only','autosomal recessive — two copies of the recessive allele are needed for the disorder to manifest','always sex-linked'],2)]),
H('The Quiet Revolution and Canadian Identity','Students examine Quebec\'s Quiet Revolution, bilingualism, the October Crisis, and the evolution of Canadian identity in the 1960s-70s.',[
  ('The Quiet Revolution in Quebec (1960-66 and beyond) involved ___.',['a violent uprising','no significant change to Quebec society','rapid secularisation, nationalisation of industries, modernisation of education and social services, and a strong assertion of Québécois identity under Premier Jean Lesage','Quebec separating from Canada'],2),
  ('The Official Languages Act (1969) ___.',['made only French official at the federal level','made only English official','declared English and French both official languages of Canada at the federal level, requiring government services in both languages','ended all language disputes'],2),
  ('The October Crisis (1970) involved ___.',['an economic crisis','a Quebec election','FLQ (Front de libération du Québec) terrorists kidnapping British diplomat James Cross and Quebec Cabinet minister Pierre Laporte — Trudeau invoked the War Measures Act','a peaceful protest'],2),
  ('Pierre Trudeau\'s vision of Canada emphasised ___.',['two nations (French and English) with equal power','Quebec as a special society','a bilingual, multicultural Canada where individual rights are paramount and Quebec does not have special status above other provinces','Canadian independence from all alliances'],2),
  ('The repatriation of the Constitution in 1982 was controversial in Quebec because ___.',['Quebec wanted it repatriated','Quebec approved the final document','Quebec Premier Lévesque felt that Quebec was left out of the final negotiations and never signed the Constitution Act, creating an ongoing constitutional wound','it granted Quebec special status'],2)])]),
day(6,[
E('Grammar and Style: Sophisticated Sentence Construction','Students apply advanced grammar — parallel structure, varied syntax, subordination and coordination, active vs. passive voice — to improve the quality of their analytical writing.',[
  ('Active voice means ___.',['the verb is in present tense','the subject performs the action (e.g., "The author develops tension")','the subject receives the action','only simple sentences'],1),
  ('Passive voice is appropriate when ___.',['always','never','the actor is unknown or less important than the action, or in formal scientific writing (e.g., "The sample was heated")','only in news writing'],2),
  ('Subordination in sentences means ___.',['using only short sentences','making all clauses equal','connecting a less important idea (dependent clause) to a main clause using a subordinating conjunction, showing the logical relationship between ideas','avoiding all conjunctions'],2),
  ('Varied sentence length in academic writing ___.',['is only for creative writing','is irrelevant to quality','creates rhythm, emphasises key points, and prevents monotony — a long analytical sentence followed by a short, punchy one can be highly effective','should be avoided in formal essays'],2),
  ('Wordiness in academic writing should be ___.',['encouraged for formal tone','eliminated — each word should earn its place; unnecessary padding weakens analytical writing','only avoided in creative writing','only a concern in short essays'],2)]),
M('Analytic Geometry: Distance, Midpoint, and Slopes','Students apply the distance formula, midpoint formula, and slope relationships to classify and verify geometric shapes.',[
  ('The midpoint formula for points (x₁,y₁) and (x₂,y₂) is ___.',['((x₁+x₂)/2, (y₁+y₂)/2)','(x₂−x₁, y₂−y₁)','((x₁×x₂)/2, (y₁×y₂)/2)','(x₁−x₂, y₁−y₂)'],0),
  ('Two lines are perpendicular if their slopes satisfy ___.',['m₁ = m₂','m₁ + m₂ = 0','m₁ × m₂ = −1','m₁ − m₂ = 1'],2),
  ('The distance between (1,2) and (4,6) is ___.',['5','7','3','4'],0),
  ('To verify a quadrilateral is a parallelogram, you would show ___.',['all angles are 90°','all sides are equal','both pairs of opposite sides have equal lengths and equal slopes (i.e., are parallel)','the diagonals are equal in length'],2),
  ('The median of a triangle from vertex A to the midpoint M of the opposite side is ___.',['the altitude from A','the line from A to M (midpoint of BC)','the perpendicular bisector','the angle bisector from A'],1)]),
Sc('Biology: Evolution and Natural Selection','Students examine Darwin\'s theory of evolution by natural selection, evidence for evolution, and mechanisms of evolutionary change.',[
  ('Natural selection operates on ___.',['individual organisms\'s acquired traits','genetic mutations only','heritable variation — individuals with traits better suited to their environment survive and reproduce more, passing those traits to offspring','all members of a species equally'],2),
  ('Evidence for evolution includes ___.',['only fossil records','only DNA comparisons','the fossil record, comparative anatomy (homologous structures), biogeography, comparative embryology, and DNA/protein similarities','only direct observation of new species forming'],2),
  ('Homologous structures are ___.',['structures that look identical and have the same function','structures with no genetic relationship','structures in different species that are anatomically similar due to common ancestry, even if they now serve different functions (e.g., human arm and whale flipper)','only found in invertebrates'],2),
  ('Genetic drift refers to ___.',['evolution driven by natural selection','gene flow between populations','random changes in allele frequencies in a population, especially significant in small populations where chance events can dramatically alter gene frequencies','directional selection'],2),
  ('Speciation occurs when ___.',['two populations exchange genes freely','populations become more similar','a population splits, the two parts become reproductively isolated, and they diverge genetically until they can no longer interbreed — forming two distinct species','only in isolated island ecosystems'],2)]),
H('Canada and the United States: A Complex Relationship','Students examine the economic, military, cultural, and political dimensions of the Canada-US relationship.',[
  ('Canada and the US share the world\'s largest ___.',['economic agreement','military alliance','land border — approximately 8,891 km — and maintain one of the world\'s most integrated economic relationships','cultural exchange program'],2),
  ('NAFTA (1994), replaced by CUSMA (2020), is significant because ___.',['it had no economic impact','it only affects agriculture','about 70-75% of Canadian exports go to the United States — free trade has deeply integrated the two economies','it was rejected by Canada initially'],2),
  ('American cultural dominance concerns some Canadians because ___.',['American and Canadian culture are identical','Canadians prefer American culture','the overwhelming presence of American media, entertainment, and consumer products can crowd out Canadian voices, leading to policies like Canadian content (CanCon) requirements','American culture only affects youth'],2),
  ('The National Policy (1879) and CanCon regulations (CRTC) are both examples of ___.',['Canadian indifference to American influence','Canada copying American policy','government measures to protect Canadian economic and cultural interests from American dominance','provincial policies only'],2),
  ('Canada-US tensions have arisen over ___.',['no significant issues','only trade disputes','issues including acid rain (1980s), softwood lumber, border management, Arctic sovereignty, and policy differences on issues like gun control, health care, and multilateralism','only environmental issues'],2)])]),
day(7,[
E('Oral Communication: Seminar and Discussion','Students participate in and lead Socratic seminars on literary and media texts. They apply skills in active listening, analytical speaking, text-based evidence, and respectful dialogue.',[
  ('A Socratic seminar is ___.',['a teacher-led lecture','a competitive debate','a student-led discussion in which participants explore ideas from a shared text through open-ended questions, building on each other\'s interpretations','a formal presentation with slides'],2),
  ('An open-ended question in a seminar ___.',['has one correct answer','can be answered yes or no','requires reading only one passage','opens rich discussion by asking "why," "how," or "what does this mean" — inviting multiple interpretations rather than a single correct answer'],3),
  ('Effective seminar participation includes ___.',['speaking as often as possible','only agreeing with others','interrupting to correct errors','building on others\' ideas, asking follow-up questions, referring to the text, and changing your view when presented with compelling evidence'],3),
  ('Evaluating the quality of an argument in a seminar means ___.',['judging how confident the speaker sounds','only agreeing with friends','checking whether the claim is supported by specific, relevant textual evidence and whether the reasoning is logical','only evaluating grammar'],2),
  ('The purpose of a Socratic seminar is ___.',['to determine who is right','to assign grades for speaking','to reach a single agreed conclusion','to deepen everyone\'s understanding through collaborative inquiry — the process of thinking together is the goal'],3)]),
M('Trigonometry: Primary Trig Ratios (SOH-CAH-TOA)','Students apply sine, cosine, and tangent ratios in right triangles to find unknown sides and angles. They solve problems in context.',[
  ('SOH-CAH-TOA means ___.',['a method for factoring quadratics','a type of geometric proof','the definitions of the three primary trig ratios: Sin = Opposite/Hypotenuse, Cos = Adjacent/Hypotenuse, Tan = Opposite/Adjacent','only used in advanced calculus'],2),
  ('In a right triangle with angle θ, opposite side 5, and hypotenuse 13, sin θ = ___.',['13/5','5/13','12/13','5/12'],1),
  ('To find an unknown angle using trig, you use ___.',['the Pythagorean theorem','a ratio and then the inverse trig function (sin⁻¹, cos⁻¹, or tan⁻¹)','only sin ratios','only the cosine rule'],1),
  ('A ladder 8 m long leans against a wall at 60° to the ground. Height on wall = ?',['4 m','6.93 m (8 × sin 60°)','4.62 m','8 × tan 60°'],1),
  ('The angle of elevation of the top of a building is 35° from 50 m away. Height = ?',['50 × tan 35° ≈ 35.0 m','50 × sin 35° ≈ 28.7 m','50 / tan 35°','50 × cos 35°'],0)]),
Sc('Physics: Kinematics — Motion in One Dimension','Students analyse motion using displacement, velocity, acceleration, and time. They apply kinematics equations and interpret distance-time and velocity-time graphs.',[
  ('Displacement differs from distance because ___.',['they are identical','displacement is always larger','displacement is a vector quantity describing change in position (with direction), while distance is the total path length travelled (scalar)','distance is a vector quantity'],2),
  ('Average velocity = ___.',['total distance / total time','displacement / time','speed only','final velocity only'],1),
  ('On a velocity-time graph, acceleration is represented by ___.',['the area under the graph','the slope of the graph','the y-intercept','the x-intercept'],1),
  ('On a distance-time graph, a horizontal line means ___.',['constant velocity','increasing speed','the object is stationary (no change in distance with time)','decreasing speed'],2),
  ('A car accelerates from 0 to 30 m/s in 10 s. Acceleration = ?',['3 m/s²','30 m/s²','300 m/s²','0.3 m/s²'],0)]),
H('The Charter of Rights and Freedoms','Students examine the Canadian Charter of Rights and Freedoms (1982), key rights it protects, important court cases, and its limitations.',[
  ('The Charter of Rights and Freedoms is part of ___.',['the Criminal Code','the Constitution Act, 1982 — making it the supreme law of Canada that overrides any inconsistent legislation','the Civil Code of Quebec only','the BNA Act of 1867'],1),
  ('Section 33 of the Charter, the "notwithstanding clause," allows ___.',['courts to override government decisions','individuals to exempt themselves from laws','Parliament or a provincial legislature to pass laws that override certain Charter rights for up to five years','the courts to strike down the Constitution'],2),
  ('Section 15 (Equality Rights) protects against discrimination based on ___.',['only race and gender','only citizenship','race, national or ethnic origin, colour, religion, sex, age, and mental or physical disability (and more as interpreted by courts)','only grounds explicitly listed, no more'],2),
  ('The Supreme Court of Canada has the power to ___.',['only advise on laws','strike down laws that violate the Charter, forcing legislatures to amend or repeal them','only interpret laws literally','override the Constitution'],1),
  ('A key limitation of Charter rights is ___.',['they apply only to federal government','they have no limitations','that Section 1 allows rights to be limited by law where the limit is reasonable and can be justified in a free and democratic society','they only protect citizens, not permanent residents'],2)])]),
day(8,[
E('Writing: The Comparative Essay','Students write a comparative literary essay analysing similarities and differences between two texts (novels, plays, poems, films) in terms of theme, technique, or character.',[
  ('A comparative essay thesis must ___.',['only list the texts being compared','only identify similarities','describe only differences','establish a meaningful analytical point about both texts — arguing what the comparison reveals about theme, technique, or human experience'],3),
  ('Two common structures for comparative essays are ___.',['block only','point-by-point only','block (all of text A, then all of text B) and point-by-point (compare both texts on each criterion in sequence), each with advantages','random alternation'],2),
  ('The "so what?" of a comparative essay means ___.',['explaining what the texts are about','listing plot differences','telling the reader why the comparison matters — what larger insight about literature, society, or human nature does comparing these two texts reveal','describing the authors'],2),
  ('Effective transitions in a comparative essay include ___.',['only "also" and "and"','words like "however," "in contrast," "similarly," "while," and "both authors..." to signal whether you are comparing or contrasting','only "but" and "or"','no transitions needed'],1),
  ('When writing a paragraph in a comparative essay, you should ___.',['write a full paragraph about text A, then a full paragraph about text B each time','only analyse one text thoroughly','avoid linking the two texts in the same paragraph','aim to discuss both texts within most analytical paragraphs, building a layered comparison'],3)]),
M('Trigonometry: Angles in Standard Position','Students extend trig to angles in standard position (0°–360°), the CAST rule, and the unit circle. They find exact trig values for special angles.',[
  ('An angle in standard position has its vertex at the origin and its initial arm ___.',['along the negative x-axis','along the positive y-axis','along the positive x-axis','along the negative y-axis'],2),
  ('The CAST rule tells you which trig functions are positive in each quadrant: ___.',['All positive in Q1 only','Sin positive in Q1 and Q2; Cos positive in Q1 and Q4; Tan positive in Q1 and Q3','All functions negative in Q2','Only Cos is ever positive'],1),
  ('The reference angle is ___.',['the angle in standard position','always 45°','the acute angle between the terminal arm and the nearest x-axis','the complement of the angle'],2),
  ('sin 150° = ___.',['−1/2','√3/2','1/2','−√3/2'],2),
  ('cos 270° = ___.',['0','1','−1','undefined'],0)]),
Sc('Physics: Forces and Newton\'s Laws','Students apply Newton\'s three laws of motion to analyse forces and predict the behaviour of objects. They work with free body diagrams.',[
  ('Newton\'s First Law (Inertia) states ___.',['force equals mass times acceleration','for every action there is an equal and opposite reaction','an object at rest stays at rest and an object in motion stays in motion with constant velocity unless acted upon by a net external force','heavier objects fall faster'],2),
  ('Newton\'s Second Law states ___.',['objects always move in circles','F = ma: net force equals mass times acceleration','for every action there is a reaction','inertia keeps objects at rest'],1),
  ('Newton\'s Third Law states ___.',['only applies to collisions','objects slow down due to gravity','F = ma','for every force (action), there is an equal and opposite force (reaction) exerted on the first object by the second'],3),
  ('A free body diagram shows ___.',['the path an object takes','the internal structure of an object','all external forces acting on an object as arrows, used to analyse net force','only gravitational force'],2),
  ('If a 10 kg object experiences a net force of 30 N, its acceleration is ___.',['300 m/s²','0.33 m/s²','3 m/s²','30 m/s²'],2)]),
H('Multiculturalism and Immigration in Canada','Students examine the evolution of Canadian immigration policy from exclusion to multiculturalism, and the ongoing debates about Canadian identity.',[
  ('Canada\'s pre-WWII immigration policy was ___.',['open and welcoming to all','consistently multicultural','explicitly racially discriminatory, favouring white British and Northern European immigrants and using mechanisms like the Chinese Head Tax, Continuous Journey Regulation, and order-in-council to exclude others','neutral and based only on economics'],2),
  ('The Immigration Act of 1967 introduced a ___.',['racial preference system','points-based system that evaluated applicants on education, skills, and language ability, effectively removing explicit racial discrimination','quota system by country of origin','policy of accepting only refugees'],1),
  ('The Canadian Multiculturalism Act (1988) ___.',['was only a symbolic gesture','declared Canada officially bilingual','enshrined multiculturalism in law, committing the government to preserve and enhance the multicultural heritage of Canadians while ensuring all Canadians enjoy equal opportunity','reversed immigration policy'],2),
  ('Current debates about Canadian immigration include ___.',['no debates — it is completely settled','only economic concerns','questions about integration vs. cultural retention, housing pressures from population growth, refugee processing times, and recognition of foreign credentials','only refugee policy'],2),
  ('Canada accepts immigrants through several streams including ___.',['only refugees','only economic immigrants','economic immigration (skilled workers, investors), family reunification, and humanitarian/refugee streams — each reflecting different priorities','only family reunification'],2)])]),
day(9,[
E('Novel Study: Examining a Contemporary Canadian Novel','Students deeply read a contemporary Canadian novel, examining how the text engages with specifically Canadian themes — landscape, identity, colonial history, immigration, or social justice.',[
  ('Canadian literature often reflects ___.',['only rural themes','identical concerns to American and British literature','specifically Canadian preoccupations: the vastness of the landscape, settler-colonial history, multicultural identity, and the ongoing question of what it means to be Canadian','only Quebec themes'],2),
  ('Postcolonial literary criticism examines ___.',['only novels set in the past','how literature reinforces colonial power','how literary texts engage with the history and legacy of colonialism — examining power dynamics, representation of Indigenous peoples, and resistance and reclamation','only British literature'],1),
  ('Narrative voice in a novel set in Canada might use dialect, Indigenous languages, or multicultural expressions to ___.',['alienate readers','make the novel less marketable','confuse the language','authentically represent Canadian voices and resist the dominance of standard white, anglophone literary conventions'],3),
  ('Setting in a Canadian novel often functions as more than location — it can ___.',['always be ignored','only indicate time period','represent the social and political tensions of Canada itself — from frozen tundra representing isolation to urban diversity representing the complexity of modern Canadian identity','only establish mood'],2),
  ('Reading a Canadian novel critically includes asking ___.',['only what happens','only who the main character is','whose perspective dominates, whose voices are absent, what assumptions about Canada are embedded in the narrative, and how the text challenges or reinforces those assumptions','only what the theme is'],2)]),
M('Trigonometry: The Sine Law','Students apply the Sine Law (a/sinA = b/sinB = c/sinC) to find unknown sides and angles in non-right triangles.',[
  ('The Sine Law applies to ___.',['only right triangles','only equilateral triangles','any triangle where you know two angles and a side (AAS or ASA) or two sides and an angle opposite one of them (SSA)','only when all three sides are known'],2),
  ('The Sine Law states ___.',['a² = b² + c² − 2bc cosA','a/sinA = b/sinB = c/sinC','sinA + sinB + sinC = 1','a × sinA = b × sinB'],1),
  ('In a triangle, angle A = 35°, angle B = 80°, a = 10 cm. Find b.',['b = 10 × sin80° / sin35° ≈ 17.2 cm','b = 10 × sin35° / sin80°','b = sin80° / sin35°','b = 10 / sin80°'],0),
  ('The ambiguous case (SSA) in the Sine Law can result in ___.',['always one triangle','always no triangle','zero, one, or two possible triangles depending on the relative lengths of the given sides','always two triangles'],2),
  ('To use the Sine Law, the angle must be ___.',['90° always','opposite to a known side (so that angle-side pair appears in the same ratio)','adjacent to both known sides','the largest angle'],1)]),
Sc('Physics: Work, Energy, and Power','Students apply the concepts of work (W = Fd cosθ), kinetic and potential energy, conservation of energy, and power (P = W/t).',[
  ('Work is done on an object when ___.',['a force is applied','an object is at rest but a force is applied','a force causes displacement in the direction of the force (W = Fd cosθ)','any force is present'],2),
  ('Kinetic energy is ___.',['energy stored in position','energy due to motion: KE = ½mv²','energy from chemical bonds','energy from heat'],1),
  ('Gravitational potential energy is ___.',['energy due to motion','energy from temperature','energy from chemical bonds','energy stored in an object due to its height: PE = mgh'],3),
  ('The Law of Conservation of Energy states ___.',['energy is created in nuclear reactions','energy is destroyed in friction','energy can be created from nothing','energy cannot be created or destroyed — only transformed from one form to another'],3),
  ('Power is ___.',['force times distance','the total energy used','the rate at which work is done: P = W/t (measured in watts, W)','energy per unit mass'],2)]),
H('Indigenous Rights and Land Claims in Canada','Students examine the historical and legal context of Indigenous land claims, treaty rights, and the Supreme Court\'s evolving jurisprudence.',[
  ('The Royal Proclamation of 1763 is significant to Indigenous rights because ___.',['it removed all Indigenous land rights','it had no lasting legal significance','it explicitly recognised Indigenous peoples\' right to their lands and required the Crown to negotiate treaties before settlement — its principles remain relevant in Canadian law','it only applied to Quebec'],2),
  ('Section 35 of the Constitution Act (1982) ___.',['removed treaty rights','was a minor symbolic clause','recognises and affirms existing Aboriginal and treaty rights, providing constitutional protection that has enabled significant court victories for First Nations','only protects Métis rights'],2),
  ('The Calder case (1973) was significant because ___.',['Canada won completely','no court considered Indigenous land rights','the Supreme Court of Canada was split but acknowledged for the first time that Aboriginal title may exist in Canadian law — a turning point in legal recognition','only BC was affected'],2),
  ('Comprehensive land claims are ___.',['already fully settled','criminal cases','claims by First Nations that were never covered by treaties, seeking negotiated agreements on land ownership, resource rights, and governance','minor boundary disputes'],2),
  ('Free, prior, and informed consent (FPIC), enshrined in UNDRIP, means ___.',['governments can consult without obtaining agreement','companies do not need to consult Indigenous peoples','only applies outside Canada','Indigenous peoples must be consulted and must give meaningful consent — not just be notified — before projects affecting their lands and rights proceed'],3)])]),
day(10,[
E('Film Study: Cinematic Techniques','Students study film as a literary medium. They analyse how directors use camera work, editing, sound, mise-en-scène, and narrative structure to create meaning.',[
  ('Mise-en-scène refers to ___.',['only camera movement','only dialogue','the editing choices in a film','everything visible in the frame: set design, lighting, costumes, actor placement and movement — the visual environment of a scene'],3),
  ('A close-up shot in film is used to ___.',['show the entire scene','establish location','emphasise a character\'s facial expression, revealing emotion or psychological state','only show objects'],2),
  ('Non-diegetic sound in film is ___.',['sound that characters in the film can hear','only dialogue','background noise from the setting','sound outside the film\'s world that only the audience hears — such as a musical score'],3),
  ('Parallel editing (cross-cutting) is a film technique that ___.',['slows narrative pace','only shows one storyline','cuts between two or more scenes happening simultaneously, building tension and showing thematic connections between actions','removes sound from scenes'],2),
  ('Analysing film as a text means ___.',['only describing the plot','listing all the actors','watching it for entertainment only','examining the choices the director makes and the effects they create — film is a constructed text like a novel, with meaning made through deliberate artistic decisions'],3)]),
M('Trigonometry: The Cosine Law','Students apply the Cosine Law (a² = b² + c² − 2bc cosA) to find unknown sides and angles in triangles where the Sine Law cannot be applied directly.',[
  ('The Cosine Law is used when ___.',['two angles and a side are known','only right triangles','you have two sides and the included angle (SAS) or all three sides and need an angle (SSS)','any triangle problem'],2),
  ('The Cosine Law states: a² = ___.',['b × c × cosA','b² + c² − 2bc cosA','b + c − 2bc cosA','sinA × sinB × sinC'],1),
  ('In a triangle with b = 7, c = 9, and A = 50°, find a.',['a² = 49 + 81 − 2(7)(9)cos50° ≈ a ≈ 7.0','a = 7 + 9 = 16','a = 50','a = sin50°'],0),
  ('The Cosine Law rearranged to find angle A gives ___.',['cosA = (b² + c² + a²) / 2bc','cosA = (b² + c² − a²) / 2bc','cosA = a/sinA','cosA = 2bc − b² − c²'],1),
  ('When would you choose the Cosine Law over the Sine Law?',['Always','When you have AAS or ASA','When you know SAS or SSS — cases where the Sine Law cannot be applied directly','Never'],2)]),
Sc('Physics: Waves and Sound','Students examine the properties of waves (transverse, longitudinal, amplitude, wavelength, frequency, speed) and sound as a longitudinal wave.',[
  ('A transverse wave has ___.',['particles moving parallel to wave direction','no amplitude','no frequency','particles oscillating perpendicular to the direction of wave travel (e.g., water waves, light)'],3),
  ('A longitudinal wave has particles moving ___.',['perpendicular to wave direction','in circles','parallel to the direction of wave travel (e.g., sound waves)','only vertically'],2),
  ('The speed of a wave equals ___.',['amplitude × frequency','wavelength / frequency','wavelength × frequency (v = fλ)','frequency only'],2),
  ('Sound travels fastest in ___.',['a vacuum','air','water','solids, where particles are closely packed and can transmit vibrations rapidly'],3),
  ('The Doppler effect is ___.',['a change in wave amplitude','a standing wave pattern','the apparent change in frequency of a wave due to relative motion between the source and observer — sound from an approaching ambulance has higher pitch than one moving away','only applies to light'],2)]),
H('Canada\'s Environmental History','Students examine key moments in Canadian environmental history, from the creation of national parks to current climate policy debates.',[
  ('Banff National Park (established 1885) and subsequent parks were initially created primarily to ___.',['protect Indigenous territory','serve purely ecological goals','attract tourists and protect scenic landscapes, though the conservation mission grew over time — a complex history that included displacing Indigenous peoples from park lands','protect endangered species'],2),
  ('The Kyoto Protocol (1997) committed Canada to ___.',['no specific emissions targets','only monitoring emissions','reducing greenhouse gas emissions below 1990 levels — though Canada later withdrew in 2011 without meeting its targets','only renewable energy',],2),
  ('The "social licence to operate" concept in resource development means ___.',['government approval is sufficient','legal permits override all concerns','companies need more than legal permits — they need the genuine acceptance of communities (including Indigenous communities) affected by their projects','only applies in BC'],2),
  ('The debate over the Trans Mountain Pipeline expansion reflects tensions between ___.',['only economic concerns','only environmental concerns','only Indigenous rights','multiple competing interests: Indigenous rights and title, environmental protection, economic development, and national energy strategy'],3),
  ('Canada\'s Net Zero by 2050 target means ___.',['Canada will stop all industrial activity','zero emissions from all sources by 2050','reducing emissions to zero immediately','achieving a balance between greenhouse gas emissions produced and removed, through a combination of emission reductions and carbon sequestration'],3)])]),
day(11,[
E('Writing: The Reflective Essay','Students write a personal reflective essay on a significant literary or cultural experience. They combine analytical rigour with genuine personal voice and insight.',[
  ('A reflective essay differs from a personal narrative because ___.',['reflective essays are shorter','narratives are more accurate','a reflective essay doesn\'t just describe an experience but critically examines what it meant and what the writer learned from it — the reflection is the point','only narratives use personal voice'],2),
  ('Effective reflective writing moves between ___.',['only description','only analysis','only emotion','the specific (concrete events, quotations, images) and the general (broader insights, connections to larger ideas or universal experiences)'],3),
  ('Voice in reflective writing ___.',['should be completely impersonal','is unimportant','should sound like an academic essay only','is central — the essay should sound like a thinking, feeling human being, not a generic template'],3),
  ('A strong reflective essay ending ___.',['simply stops describing','restates the opening paragraph','summarises only what happened','leaves the reader with a new understanding that emerged from the reflection — a genuine insight, not just a summary'],3),
  ('The best reflective essays are ___.',['always positive','free of any analysis','written about trivial events only','honest, specific, and intellectually curious — they take a risk by exploring genuine complexity rather than offering safe, expected conclusions'],3)]),
M('Financial Literacy: Earning, Saving, and Investing','Students examine income types, taxes, budgeting, compound interest, and basic investing principles relevant to their near future.',[
  ('Canada\'s progressive income tax system means ___.',['everyone pays the same rate','lower incomes pay more','higher income earners pay a higher marginal tax rate on income above each bracket threshold','taxes are optional'],2),
  ('A TFSA (Tax-Free Savings Account) ___.',['has no contribution limit','removes all income tax on your salary','allows Canadians to contribute up to an annual limit and earn investment income tax-free inside the account','is only for retirement'],2),
  ('An RRSP (Registered Retirement Savings Plan) ___.',['is taxed on contribution','earns no interest','allows contributions to be deducted from taxable income now, with growth tax-sheltered until withdrawal in retirement when you may be in a lower tax bracket','is only for people over 65'],2),
  ('Diversification in investing means ___.',['only investing in one stock','always investing in gold','putting all money in savings accounts','spreading investments across different asset types and sectors to reduce risk — losses in one area are offset by gains in another'],3),
  ('The Rule of 72 estimates ___.',['how long to pay off debt at any rate','how many years to accumulate $1000','your retirement age','how many years it takes to double an investment: 72 ÷ annual interest rate ≈ years to double'],3)]),
Sc('Physics: Light — Reflection, Refraction, Optics','Students study the behaviour of light: law of reflection, refraction (Snell\'s Law), total internal reflection, and optical instruments.',[
  ('Snell\'s Law (n₁sinθ₁ = n₂sinθ₂) describes ___.',['the reflection of light','the absorption of light','how light bends when passing from one medium to another — the angle of refraction depends on the ratio of the refractive indices','only applies to lenses'],2),
  ('Total internal reflection occurs when ___.',['light enters a denser medium','light hits a mirror','light travels from a denser to a less dense medium at an angle greater than the critical angle — it reflects completely rather than refracting','light hits a coloured surface'],2),
  ('Fibre optic cables transmit data using ___.',['electrical signals','radio waves','magnetic pulses','total internal reflection — light pulses bounce along the glass fibre without escaping, enabling high-speed data transmission'],3),
  ('A converging (convex) lens ___.',['diverges all light','has no focal point','only works in telescopes','bends parallel rays of light toward a focal point, forming real images of distant objects'],3),
  ('The index of refraction (n) of a medium is ___.',['the speed of light in that medium','the wavelength of light in that medium','c/v — the ratio of the speed of light in a vacuum to the speed of light in the medium (always ≥ 1)','the colour of light in that medium'],2)]),
H('Charter Rights: Case Studies','Students examine landmark Supreme Court of Canada cases under the Charter, analysing the legal reasoning and social implications.',[
  ('R v Oakes (1986) established ___.',['that the Charter has no limits','the Oakes Test — a two-part framework for determining whether a law that limits a Charter right can be justified under Section 1','that all laws are constitutional','that Section 33 is never valid'],1),
  ('Singh v Minister of Employment and Immigration (1985) established ___.',['only citizens have Charter rights','refugee claimants have no rights in Canada','that Convention refugees have Charter rights, including the right to an oral hearing before being denied protection — a landmark case for refugee rights in Canada','only landed immigrants have Charter rights'],2),
  ('M v H (1999) was significant for ___.',['corporate rights','freedom of speech','extending spousal support rights to same-sex partners, a major step toward equal rights for LGBTQ+ Canadians','religious rights'],2),
  ('Eldridge v British Columbia (1997) established ___.',['corporations have equality rights','that language rights only apply to official languages','that the government must provide sign language interpreters to Deaf patients in hospitals, as failing to do so violates Section 15 equality rights','that only federal laws must respect the Charter'],2),
  ('A common pattern in Charter litigation is ___.',['Charter cases always go against the government','the government always wins','courts balance individual rights against collective interests, with Section 1 allowing rights to be limited when demonstrably justified — no right is absolute in a constitutional democracy','only wealthy individuals use the Charter'],2)])]),
day(12,[
E('Literature: Poetry — Voice, Identity, and Social Justice','Students read and analyse contemporary poetry by Canadian poets, particularly from Indigenous, Black Canadian, and immigrant voices, examining how poetry enacts identity and challenges injustice.',[
  ('Contemporary Canadian poetry by marginalised voices ___.',['is identical to traditional British poetry','has no political dimension','often challenges dominant narratives, reclaims cultural identity, uses code-switching between languages, and speaks truth about lived experiences of colonialism, racism, and displacement','is only about nature'],2),
  ('Code-switching in poetry refers to ___.',['only a technical error','a poetic device unrelated to identity','switching between computer codes in a poem','alternating between two or more languages or registers within a single poem, often reflecting the speaker\'s multiple cultural identities'],3),
  ('Slam poetry and spoken word ___.',['are not literary forms','are only for entertainment','have no connection to written poetry','are forms of oral poetry that emphasise performance, rhythm, voice, and political engagement — often more accessible and diverse in voices than published print poetry'],3),
  ('When reading poetry by marginalised poets, it is important to ___.',['apply only standard literary analysis tools','ignore context','assume all such poetry is political','bring understanding of the historical and social context of the poet\'s experience, recognising that form, language, and voice are often themselves acts of resistance'],3),
  ('The intersection of identity and poetry means ___.',['poets should not write about their identity','only confessional poetry has value','all poetry is political','a poet\'s race, gender, sexuality, class, and cultural background shape what they write about, how they write, and what literary conventions they accept, reject, or subvert'],3)]),
M('Review: Quadratics, Trigonometry, and Analytic Geometry','Students consolidate Grade 10 math topics.',[
  ('Solve by the quadratic formula: x² − 4x − 5 = 0',['x = 5 and x = −1','x = −5 and x = 1','x = 4 and x = −5','x = 4 and x = 1'],0),
  ('In a triangle with A = 40°, B = 75°, a = 12, find b using the Sine Law.',['b = 12 sin75° / sin40° ≈ 18.0','b = 12 sin40° / sin75°','b = sin75° / sin40°','b = 12 / sin75°'],0),
  ('Two lines are perpendicular. One has slope 2/3. The other\'s slope is ___.',['2/3','−3/2','3/2','−2/3'],1),
  ('A parabola y = a(x − 3)² − 4 opens upward. Which value of a is correct?',['a = −1','a = −0.5','a = 2','a = 0'],2),
  ('The distance between (−1, 2) and (3, −1) is ___.',['5','7','√7','3'],0)]),
Sc('Physics: Electromagnetism Basics','Students explore electric fields, electric potential, magnetic fields, and how they interact — culminating in understanding electromagnetic induction.',[
  ('Electric field lines show ___.',['the path a positive test charge would take if released in the field','the direction of electron flow only','the location of neutral particles','magnetic force only'],0),
  ('A magnetic field is created by ___.',['stationary electric charges','temperature differences','light waves','moving electric charges (current-carrying conductors) and permanent magnets'],3),
  ('Electromagnetic induction (Faraday\'s law) means ___.',['magnetic fields attract iron','magnets produce light','a changing magnetic field through a conductor induces an electric current — the principle behind generators and transformers','current only flows in one direction'],2),
  ('An electric motor converts ___.',['mechanical energy to electrical energy','chemical energy to heat','electrical energy to mechanical energy, using the force on a current-carrying conductor in a magnetic field','light to electrical energy'],2),
  ('An electric generator converts ___.',['electrical energy to heat','electrical energy to mechanical energy','light to electricity','mechanical energy (e.g., from a turbine) to electrical energy through electromagnetic induction'],3)]),
H('Contemporary Canadian Issues: Technology and Society','Students examine how digital technology and social media have transformed Canadian society, politics, and economy.',[
  ('The digital economy has changed Canadian employment by ___.',['having no significant effect','only reducing jobs','creating entirely new sectors (tech companies, the gig economy, platform work) while automating or displacing some traditional jobs — raising questions about the future of work and worker protections','only benefiting urban workers'],2),
  ('Social media platforms in Canada raise concerns about ___.',['only privacy issues','only political advertising','no significant concerns','privacy, disinformation, mental health impacts (especially on youth), algorithmic content curation, and foreign interference in democratic processes'],3),
  ('Canada\'s Bill C-18 (Online News Act, 2023) was an attempt to ___.',['censor online news','ban social media','require digital platforms (Google, Meta) to pay Canadian news publishers for using their content — a major policy attempt to support journalism in the digital age','regulate only CBC content'],2),
  ('Artificial intelligence is affecting Canadian society by ___.',['having no economic effect','only helping in medicine','eliminating all creative jobs','transforming healthcare (diagnosis), financial services (fraud detection), transportation (autonomous vehicles), and raising fundamental questions about labour, privacy, and democratic oversight'],3),
  ('A key Canadian concern about digital technology is ___.',['Canada is a world leader with no concerns','only copyright issues','technological dependence — Canada consumes vast amounts of US-developed technology and platforms, raising questions about sovereignty, data privacy, and the economic costs of foreign tech dominance','only gaming addiction'],2)])]),
day(13,[
E('Writing: The Research Essay — Advanced Skills','Students research and write a multi-source academic essay on a literary, historical, or social topic, applying MLA or APA citation, synthesis, and academic argument.',[
  ('An annotated bibliography includes ___.',['only titles and authors','only the URL','a full citation plus a brief critical summary of each source — evaluating its relevance, credibility, and contribution to your research','only books, not websites'],2),
  ('Synthesising multiple sources means ___.',['only summarising each source separately','summarising sources in alphabetical order','weaving ideas from multiple sources together to build a complex argument — connecting, comparing, and contrasting perspectives rather than simply reporting them one by one','only using the most recent sources'],2),
  ('In MLA format, in-text citations for a quotation include ___.',['only the author\'s first name','the full title of the source','the author\'s last name and page number in parentheses: (Smith 42)','a footnote number only'],2),
  ('A research essay conclusion at the senior level should ___.',['only repeat the introduction','introduce entirely new evidence','show the significance of your findings, acknowledge complexity or limitations, and suggest questions for further inquiry','just restate your thesis'],2),
  ('Academic writing avoids ___.',['first-person entirely always','logical argument','evidence','vague generalisations, unsupported claims, colloquialisms, and hedging that avoids taking a clear position'],3)]),
M('Geometry: Circle and Line Relationships','Students explore the geometry of circles — tangent lines, chords, secants — and prove circle theorems using congruence and angle relationships.',[
  ('A tangent to a circle ___.',['passes through the centre','intersects the circle at two points','is perpendicular to the radius at the point of tangency','is parallel to any chord'],2),
  ('An inscribed angle in a circle is ___.',['a central angle','an angle between two tangents','an angle formed by two chords that meet at a point on the circle, and equals half the central angle that subtends the same arc','an angle outside the circle'],2),
  ('A central angle ___.',['is less than its inscribed angle','is half the inscribed angle subtending the same arc','is unrelated to the arc','equals the inscribed angle subtending the same arc'],1),
  ('Two tangents drawn from an external point to a circle ___.',['have different lengths','may or may not be equal','are equal in length','are perpendicular to each other'],2),
  ('The angle in a semicircle (inscribed angle subtending a diameter) is always ___.',['45°','60°','180°','90°'],3)]),
Sc('Physics and Chemistry: Nuclear Science','Students explore nuclear structure, radioactive decay (alpha, beta, gamma), half-life, nuclear fission and fusion, and their applications and risks.',[
  ('Radioactive decay occurs when ___.',['any atom is heated','only man-made isotopes break down','an unstable nucleus releases energy/particles to reach a more stable configuration, changing its atomic number or mass number','electrons are removed from atoms'],2),
  ('Alpha radiation is ___.',['a high-energy photon','a fast electron','a helium nucleus (2 protons + 2 neutrons) — most massive and least penetrating (stopped by paper or skin)','a neutron'],2),
  ('Beta radiation is ___.',['a helium nucleus','a high-energy photon','a fast-moving electron emitted from the nucleus when a neutron converts to a proton — more penetrating than alpha, stopped by thin metal','a cluster of protons'],2),
  ('Half-life is ___.',['the time for a radioactive sample to decay to 50% of its initial amount of radioactive material','the time for complete decay','the lifespan of a nuclear reactor','the time for gamma radiation to stop'],0),
  ('Nuclear fission differs from fusion in that ___.',['fission joins nuclei; fusion splits them','only fusion produces energy','fission splits heavy nuclei (releasing energy), while fusion joins light nuclei (also releasing energy but requiring enormous temperatures and pressure — the process powering the sun)','both are identical processes'],2)]),
H('Global Citizenship and Human Rights','Students examine international human rights frameworks (UDHR, ICC), Canada\'s role, and the responsibilities of individuals and states in a globalised world.',[
  ('The Universal Declaration of Human Rights (1948) ___.',['only applies to UN member states','was drafted without Canadian involvement','is legally binding on all nations','was proclaimed by the UN General Assembly as a foundational statement of universal human rights — though it is not legally binding on its own, it has inspired binding human rights treaties'],2),
  ('The International Criminal Court (ICC) ___.',['is the same as the International Court of Justice','has no jurisdiction over heads of state','was established in 2002 to try individuals for genocide, war crimes, and crimes against humanity where national courts are unable or unwilling to do so','only tries non-state actors'],2),
  ('Canada\'s commitment to international human rights has been complicated by ___.',['Canada having a perfect human rights record','no domestic rights violations','the gap between Canada\'s stated commitments internationally and the ongoing human rights issues at home — particularly the rights of Indigenous peoples, systemic racism, and poverty','only foreign policy issues'],2),
  ('R2P (Responsibility to Protect) is a principle that ___.',['gives any country the right to invade another','has no support from Canada','denies sovereignty in all cases','states that when a government fails to protect its people from atrocities or commits atrocities itself, the international community has a responsibility to intervene — Canada was a key architect of this doctrine'],3),
  ('Being a global citizen means ___.',['ignoring local issues','only caring about problems in other countries','taking no responsibility for global issues','recognising that you are connected to and affected by what happens elsewhere in the world, and that you have responsibilities to promote justice, equality, and sustainability globally'],3)]),
]),
day(14,[
E('Oral and Media: Podcasting and Digital Storytelling','Students plan and create a short digital story or podcast episode, applying media production principles, research, and narrative skills.',[
  ('A podcast script differs from a written essay because ___.',['it requires no research','it uses casual language only','it never uses evidence','it is designed to be heard — it uses conversational language, shorter sentences, audio cues, and engaging pacing, while still requiring solid research and clear structure'],3),
  ('Digital storytelling combines ___.',['only text','only images','only audio','narrative, images, video, music, and/or sound effects to tell a story or explain a topic in a multi-modal format accessible to modern audiences'],3),
  ('Copyright considerations in podcasting and digital media mean ___.',['all music and images are freely usable','only images need attribution','copyright doesn\'t apply to educational projects','you must use licensed or original music and images, give proper attribution, and understand Creative Commons licensing'],3),
  ('The most important quality in a podcast is ___.',['the most expensive microphone','the longest run time','the most sound effects','clear, well-organised content delivered with an engaging voice that creates a genuine connection with the listener'],3),
  ('Audience awareness in digital storytelling means ___.',['ignoring who will see your work','only making content for your teacher','making content as long as possible','constantly making decisions about content, tone, language, and format based on who you are trying to reach and what you want them to take away'],3)]),
M('Linear and Quadratic Systems','Students find the intersection of a linear equation and a quadratic (parabola), solving graphically and algebraically.',[
  ('To find where y = x + 3 meets y = x², you set them equal and solve ___.',['y = y','x + 3 = x², then x² − x − 3 = 0','x = x²','y = 0'],1),
  ('The number of intersections of a line and a parabola can be ___.',['only 1','only 2','always 0','0, 1, or 2, depending on the discriminant of the resulting quadratic equation'],3),
  ('Solve: y = 3 and y = x² − 1',['x = ±1','x = ±2','x = 0 only','x = 3'],1),
  ('If the discriminant of the system\'s resulting equation is negative, the line and parabola ___.',['intersect at two points','are parallel','intersect at one point','do not intersect'],3),
  ('Graphically, the solution(s) to a linear-quadratic system are ___.',['the x-intercepts of the parabola','the y-intercepts of both graphs','the point(s) where the line and parabola cross','the vertex of the parabola'],2)]),
Sc('Science Review: Connecting Chemistry, Biology, Physics','Students connect the three Grade 10 science strands and their real-world applications.',[
  ('Biochemistry connects chemistry and biology through ___.',['only DNA','only enzymes','the study of chemical reactions in living things — photosynthesis (chemistry of carbon fixation), cellular respiration (oxidation of glucose), and protein synthesis (chemistry of the genetic code)','only cell division'],2),
  ('Biophysics connects biology and physics through ___.',['only anatomy','only genetics','the application of physical principles to biological systems — fluid dynamics in blood flow, optics in vision, electricity in nerve impulses, and mechanics in muscle and bone','only ecology'],2),
  ('Medical imaging (MRI, X-ray, ultrasound) applies ___.',['only biology','only chemistry','physics (electromagnetic radiation, magnetic fields, sound waves) to visualise internal biological structures — a synthesis of physics and biology','only genetics'],2),
  ('Climate change is a phenomenon that requires ___.',['only chemistry to understand','only biology to understand','only physics to understand','understanding from all three strands: chemistry (greenhouse gas reactions), biology (ecosystem impacts), and physics (heat transfer, atmospheric science)'],3),
  ('The synthesis of penicillin from a biological source (Penicillium mold) into a pharmaceutical involves ___.',['only biology','only physics','a combination of biology (identifying the natural compound), chemistry (purifying and synthesising it), and physics (understanding its mechanism of action)','only chemistry'],2)]),
H('Year-End Review: Canadian History and Civics','Students synthesise learning across Grade 10 history, connecting historical developments to contemporary Canadian issues.',[
  ('Which concept best connects Canada\'s experience in WWI and WWII to Canada\'s contemporary foreign policy?',['Isolationism','Military dominance','Colonial dependence','Canada as a "middle power" — committed to multilateralism, collective security, and peacekeeping rather than unilateral military action'],3),
  ('The connection between the Quiet Revolution, the Official Languages Act, and the Quebec referendums is ___.',['no meaningful connection','the growth of English dominance','the ongoing tension between Quebec\'s desire for self-determination and the federal vision of a bilingual, multicultural Canada','only economic issues'],2),
  ('Indigenous land claims, the Charter\'s Section 35, and the TRC Calls to Action are all part of ___.',['completed historical events','only legal debates','only provincial issues','Canada\'s ongoing — and still incomplete — process of addressing the colonial legacy and working toward reconciliation with Indigenous peoples'],3),
  ('Canada\'s immigration and multiculturalism policies, while imperfect, reflect ___.',['a desire for cultural homogeneity','complete equality for all groups','no particular values','a stated commitment to diversity and inclusion that must be evaluated against lived realities of discrimination and inequality that many communities still face'],3),
  ('The most important lesson from Grade 10 Canadian history and civics is ___.',['Canada is perfect','history has no relevance to today','all problems are already solved','democracy, rights, and justice are ongoing projects — the Canada of today was made by choices, and the Canada of the future will be made by the choices of people like you'],3)]),
]),
day(15,[
E('Writing: Exam Preparation — Timed Literary Response','Students practise timed literary analysis, applying strategies for close reading under time pressure, efficient evidence selection, and focused analytical argumentation.',[
  ('For a timed literary essay (45-60 min), the best planning approach is ___.',['writing without planning','planning for 20+ minutes before writing','spending 5-7 minutes forming a clear thesis, selecting 2-3 pieces of evidence, and making a quick outline, then writing efficiently','only writing a conclusion first'],1),
  ('Under time pressure, you should prioritise ___.',['perfect spelling throughout','covering every detail in the text','a clear argument with well-selected evidence over quantity of points — depth beats breadth in a time-limited analytical response','the longest quotations possible'],2),
  ('If you get stuck mid-essay during an exam, you should ___.',['start over','leave the essay blank','stare at the page indefinitely','quickly reread the question, decide on your most important analytical point for the next paragraph, and continue writing even if it\'s less polished than ideal'],3),
  ('The most common weakness in timed literary essays is ___.',['too much analysis','using quotations','excessive personal opinion','plot summary replacing analysis — strong exam essays spend most of their words analysing and interpreting, not describing what happens'],3),
  ('After writing a timed essay, use any remaining time to ___.',['rewrite the entire introduction','add random quotations','add as many new points as possible','check that your thesis is clear, your evidence is relevant, and your analysis actually explains the connection between evidence and argument'],3)]),
M('Review: Grade 10 Math Comprehensive','Students review all major Grade 10 mathematics topics.',[
  ('Solve the system: 2x + 3y = 12 and x − y = 1',['x = 3, y = 2','x = 2, y = 3','x = 4, y = 3','x = 5, y = 1'],0),
  ('Factor: x² − 9',['(x − 3)²','(x + 9)(x − 1)','(x − 3)(x + 3)','(x + 9)(x − 9)'],2),
  ('A triangle has sides a = 8, b = 6, and included angle C = 45°. Find c.',['c² = 64 + 36 − 2(8)(6)cos45° ≈ c ≈ 5.68','c = 14','c = 10','c = 45'],0),
  ('The vertex of y = 2x² + 8x + 5 is at x = ___.',['x = −2 (from x = −8/(2×2))','x = 2','x = 5','x = 4'],0),
  ('Two tangents from external point P to a circle each have length 10 cm. The angle between them is 60°. This is a ___ problem.',['trigonometry and circle geometry','pure algebra','systems of equations','only requiring the Pythagorean theorem'],0)]),
Sc('Science: Sustainability and Future Technologies','Students examine sustainable technologies — renewable energy, green chemistry, biotechnology — and their role in addressing 21st century challenges.',[
  ('Green chemistry principles aim to ___.',['increase chemical production','maximise energy consumption','design chemical products and processes that reduce or eliminate hazardous substances — making chemistry more environmentally sustainable from the start','only apply to pharmaceuticals'],2),
  ('Solar cells (photovoltaics) convert ___.',['heat to electricity','chemical energy to electricity','nuclear energy to electricity','light (photons) directly to electrical energy using semiconductor materials'],3),
  ('Bioremediation is ___.',['removing beneficial organisms','only relevant in Canada','a technology using living organisms (bacteria, fungi, plants) to break down or neutralise pollutants in contaminated environments','a type of genetic engineering'],2),
  ('Carbon capture and storage (CCS) ___.',['removes CO₂ from the atmosphere permanently always','is only theoretical','has no application to industry','captures CO₂ emissions at point sources (e.g., power plants) and stores them underground — controversial because it may allow fossil fuel use to continue while reducing emissions'],2),
  ('The sustainable development concept of "meeting the needs of the present without compromising the ability of future generations to meet their own needs" was defined in ___.',['the Paris Agreement','the Kyoto Protocol','only recently','the 1987 Brundtland Report — and remains the foundational definition of sustainability'],3)]),
H('Citizenship: Civic Participation and Democratic Engagement','Students examine forms of civic engagement, the responsibilities of citizenship, and how they can participate meaningfully in Canadian democracy now.',[
  ('Voting is ___.',['the only form of civic engagement','the most effective form of advocacy','not important for young people','a fundamental right and responsibility in democracy — but just one of many forms of civic participation'],3),
  ('Active citizenship includes ___.',['only voting','only serving in government','boycotting elections','staying informed, engaging with community issues, contacting elected representatives, participating in public consultations, joining community organisations, and advocating for change'],3),
  ('Civil disobedience is ___.',['always illegal and never justified','always effective','never used in Canada','the deliberate, nonviolent breaking of a law as a form of protest against injustice — with a long history in Canadian and global activism'],3),
  ('Media literacy is a civic skill because ___.',['it is not relevant to democracy','it is only for media professionals','only governments need it','citizens who can critically evaluate media — identifying bias, misinformation, and propaganda — make better informed democratic decisions'],3),
  ('Young people\'s civic engagement matters because ___.',['youth have no political power','only adults can make change','voting is the only mechanism for change','young Canadians\' voices, especially on climate, Indigenous reconciliation, and inequality, are essential to the democracy\'s future — and the decision to engage or disengage has real consequences'],3)]),
]),
]

write_new(10, g10)
print('Grade 10 days 1-15 written.')
