#!/usr/bin/env python3
"""Phase 3 extension: Grade 12, Days 51-60 (final batch of this whole
curriculum extension project, completing Days 1-60 across Grades 3-12).
Topics chosen to avoid any overlap with the existing Day 1-50 set (see
data/grade12.json), which already spans extremely advanced ground --
Taylor/Maclaurin series, De Moivre's theorem, general relativity,
quantum mechanics, matrices, parametric/polar equations, and more.
New topics for this batch: existentialist literature, eigenvalues,
the Squeeze Theorem, the Bohr model, diasporic identity, the normal
distribution, hyperbolic functions, neutron stars, modular arithmetic,
volumes by cross-sections, and more (see full list in g12_51_60 below).

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as gen_grade12_days41_50.py).

Note: Day 30 in the existing data has only 3 subjects (missing a
Calculus entry) -- a pre-existing data quirk from an earlier session,
unrelated to this batch and not something this script touches.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys
sys.path.insert(0, '/sessions/modest-compassionate-lamport/mnt/gradesbooster')
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
C12 = 'https://tvolearn.com/pages/grade-12-calculus'
P12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RC, RP = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def C(t, s, q):
    return sub('Calculus', t, s, RC, C12, q)


def P(t, s, q):
    return sub('Physics', t, s, RP, P12, q)


g12_51_60 = [
day(51, [
E('Literature: Existentialist Philosophy in the Modern Novel',
  'Grade 12 English strand: existentialist literature explores themes of individual freedom, absurdity, and the necessity of creating meaning in a universe without inherent purpose, often through protagonists confronting difficult choices.',
  [('Existentialist literature explores themes of individual freedom and the necessity of creating ___ in a universe without inherent purpose.', ['Meaning', 'A fixed, predetermined destiny with no room for individual choice', 'A concept unrelated to existentialist philosophy', 'Wealth and material success exclusively'], 0),
   ('A central existentialist concern is that human beings must define themselves through ___.', ['Their own choices and actions', 'A destiny fully determined by fate or divine will', 'A concept unrelated to existentialist thought', 'Rules imposed entirely by external authorities, with no personal input'], 0),
   ('Which is an example of an existentialist theme appearing in a novel?', ['A protagonist confronting the absence of inherent meaning and choosing how to respond', 'A protagonist whose life is entirely controlled by fate with no capacity for choice', 'A theme entirely unrelated to questions of freedom or meaning', 'A story that avoids any exploration of a character’s inner life'], 0),
   ('Why might an existentialist novel emphasize a character’s anxiety when facing a significant decision?', ['The weight of radical freedom and responsibility for one’s choices can provoke genuine existential anxiety', 'Anxiety has no connection to existentialist philosophy or literature', 'Existentialist characters never face any significant decisions', 'This concept has no relevance to how existentialist themes are portrayed'], 0),
   ('Why is existentialist philosophy considered particularly relevant to modern and contemporary literature?', ['It reflects modern uncertainties about meaning, identity, and moral responsibility in a rapidly changing world', 'Existentialist philosophy has no connection to literature written after the nineteenth century', 'This philosophical movement has no relevance to how contemporary authors explore identity', 'Modern literature never engages with questions of meaning or personal responsibility'], 0)]),
AF('Eigenvalues and Eigenvectors: An Introduction',
   'Grade 12 Advanced Functions strand: an eigenvector of a matrix is a nonzero vector whose direction remains unchanged when the matrix is applied to it, and the eigenvalue is the scalar factor by which it is stretched or shrunk.',
   [('An eigenvector of a matrix is a nonzero vector whose ___ remains unchanged when the matrix is applied to it.', ['Direction', 'Exact numerical length, in every single case', 'A concept unrelated to matrices', 'Colour, with no connection to matrix operations'], 0),
    ('The eigenvalue associated with an eigenvector is the scalar factor by which the vector is ___.', ['Stretched or shrunk', 'Rotated by exactly ninety degrees in every case', 'A concept unrelated to how a matrix transforms a vector', 'Converted into a completely different, unrelated vector'], 0),
    ('If Av = λv for a matrix A, nonzero vector v, and scalar λ, then v is called ___.', ['An eigenvector of A, with eigenvalue λ', 'A vector entirely unrelated to matrix A', 'A value that can never satisfy any matrix equation', 'The determinant of matrix A'], 0),
    ('Why might finding a matrix’s eigenvalues be useful before analyzing repeated applications of that matrix?', ['Eigenvalues reveal how a transformation stretches or shrinks space along specific directions, which helps predict long-term behaviour', 'Eigenvalues provide no useful information about how a matrix behaves when applied repeatedly', 'A matrix’s eigenvalues have no connection to its overall transformation properties', 'This concept has no relevance to understanding matrix transformations'], 0),
    ('Why are eigenvalues and eigenvectors useful in fields like engineering and computer graphics?', ['They help identify natural directions of stretching or vibration in a system, simplifying complex transformations', 'Eigenvalues and eigenvectors have no practical application outside of pure mathematics', 'Engineering and computer graphics never require analyzing matrix transformations', 'This concept only applies to purely abstract mathematics with no real-world use'], 0)]),
C('Calculus: Optimization in Economics -- Elasticity of Demand',
  'Grade 12 Calculus strand: elasticity of demand measures how sensitive the quantity demanded of a good is to a change in its price, and calculus can express this sensitivity as a derivative-based ratio.',
  [('Elasticity of demand measures how sensitive the quantity demanded of a good is to a change in its ___.', ['Price', 'Colour or packaging design, with no connection to price', 'A concept unrelated to consumer demand', 'The manufacturer’s total production costs exclusively'], 0),
   ('Elasticity of demand can be expressed using calculus as a ratio involving the ___ of the demand function.', ['Derivative', 'Constant term only, with no derivative involved', 'A concept unrelated to calculus', 'Second antiderivative exclusively, with no first derivative involved'], 0),
   ('If demand is described as elastic, a small change in price leads to ___.', ['A relatively large change in quantity demanded', 'No change whatsoever in quantity demanded', 'A concept unrelated to elasticity', 'An identical, proportionally smaller change in every case'], 0),
   ('Why might a business use elasticity of demand, calculated using calculus, to help set prices?', ['Understanding how sensitive demand is to price changes can help predict the effect of a price change on total revenue', 'Elasticity of demand has no connection to setting prices or predicting revenue', 'Businesses never need to consider how demand responds to price changes', 'This concept only applies to purely abstract mathematics with no economic use'], 0),
   ('Why is calculus particularly well suited to modelling elasticity of demand, compared to using only static calculations?', ['Calculus captures the instantaneous rate of change in demand at a specific price point, offering more precise insight than an average rate', 'Calculus provides no additional precision compared to simple average calculations', 'Elasticity of demand can never be modelled using any calculus-based method', 'This concept has no connection to how economists analyze market behaviour'], 0)]),
P('Physics: The Bohr Model and Atomic Emission Spectra',
  'Grade 12 Physics strand: the Bohr model describes electrons orbiting the nucleus in fixed energy levels, and atomic emission spectra result from electrons releasing specific amounts of energy as light when they drop to a lower energy level.',
  [('The Bohr model describes electrons orbiting the nucleus in ___.', ['Fixed energy levels', 'A single continuous, unrestricted path with no defined levels', 'A concept unrelated to atomic structure', 'Random, unpredictable positions with no defined structure at all'], 0),
   ('An atomic emission spectrum results from electrons releasing specific amounts of energy as light when they ___.', ['Drop to a lower energy level', 'Remain permanently fixed at the same energy level with no movement', 'A concept unrelated to atomic structure', 'Merge directly with the nucleus of the atom'], 0),
   ('Each element produces a ___ emission spectrum.', ['Unique, identifiable', 'Identical, with no connection to which element is involved', 'A concept unrelated to atomic emission', 'Completely random pattern that changes unpredictably each time'], 0),
   ('Why does an electron release a photon of a very specific energy, and therefore a specific colour of light, when moving to a lower energy level?', ['The energy released exactly matches the difference between the two specific, fixed energy levels involved', 'The energy released by an electron is always identical, regardless of which energy levels are involved', 'Photon energy has no connection to the difference between an atom’s energy levels', 'This concept has no relevance to how atomic emission spectra are produced'], 0),
   ('Why are atomic emission spectra useful tools for astronomers studying distant stars?', ['The unique spectral pattern of light from a star can reveal which elements are present in its composition', 'Emission spectra provide no useful information about the composition of distant objects', 'Astronomers never use light analysis to study the composition of stars', 'This concept has no connection to studying objects outside our solar system'], 0)])]),

day(52, [
E('Writing: The Manifesto as Literary Form',
  'Grade 12 English strand: a manifesto is a public declaration of beliefs, intentions, or a call to action, often using bold, direct language and repetition to persuade readers toward a specific artistic, political, or social position.',
  [('A manifesto is a public declaration of beliefs, intentions, or a call to ___.', ['Action', 'Silence, with no attempt to influence any reader', 'A concept unrelated to persuasive writing', 'Complete inaction, discouraging any response from readers'], 0),
   ('Manifestos often use bold, direct language and ___ to persuade readers.', ['Repetition', 'Deliberately vague, ambiguous phrasing throughout', 'A concept unrelated to persuasive technique', 'Only passive, hesitant statements with no clear position'], 0),
   ('A manifesto is typically written to advocate for a specific ___ position.', ['Artistic, political, or social', 'Purely mathematical, with no connection to ideas or beliefs', 'A concept unrelated to persuasive writing', 'Entirely neutral, taking no position on any issue'], 0),
   ('Why might a writer use short, forceful sentences when composing a manifesto?', ['Short, forceful sentences can convey urgency and conviction, strengthening the persuasive impact of the declaration', 'Short sentences always weaken the persuasive impact of a manifesto', 'Manifestos are never intended to persuade or convince a reader', 'This concept has no connection to the stylistic choices of persuasive writing'], 0),
   ('Why has the manifesto remained a significant literary and political form across different historical movements?', ['It offers a direct, memorable way for a group or individual to publicly articulate and advocate for change', 'Manifestos have never played any significant role in historical or artistic movements', 'This literary form has no lasting relevance across different time periods', 'This concept has no connection to how ideas are publicly communicated'], 0)]),
AF('Functions: Solving Systems of Non-Linear Equations',
   'Grade 12 Advanced Functions strand: solving a system of non-linear equations means finding the values that satisfy two or more equations simultaneously, often using substitution or graphical methods since these systems can have multiple or no solutions.',
   [('Solving a system of non-linear equations means finding values that satisfy ___ simultaneously.', ['Two or more equations', 'Only a single equation, with no other equations involved', 'A concept unrelated to systems of equations', 'No equations whatsoever'], 0),
    ('A system involving a parabola and a line may have ___ possible number(s) of solutions.', ['Zero, one, or two, depending on the specific equations', 'Always exactly one solution, with no other possibility', 'A concept unrelated to solving these systems', 'An infinite number of solutions in every single case'], 0),
    ('Which is a common method for solving a system of non-linear equations?', ['Substitution, replacing one variable using an expression from the other equation', 'Ignoring one of the equations entirely', 'A method entirely unrelated to solving equation systems', 'Assuming a solution exists with no calculation required'], 0),
    ('Why might a system involving a circle and a line have zero, one, or two points of intersection?', ['Depending on the line’s position, it may miss the circle entirely, be tangent to it, or cross through it at two points', 'A line and a circle can never intersect at more than one point under any circumstances', 'The number of intersection points has no connection to the geometric relationship between the curves', 'This concept has no relevance to solving non-linear systems'], 0),
    ('Why is graphing a helpful strategy when solving a system of non-linear equations, even before solving algebraically?', ['A graph can reveal the approximate number and location of solutions, helping check the reasonableness of an algebraic answer', 'Graphing provides no useful information when solving a system of equations', 'Non-linear systems can never be represented or understood graphically', 'This concept has no connection to solving systems of equations effectively'], 0)]),
C('Calculus: The Squeeze Theorem',
  'Grade 12 Calculus strand: the Squeeze Theorem determines the limit of a function by trapping it between two other functions with the same known limit at a given point, useful for functions that are difficult to evaluate directly.',
  [('The Squeeze Theorem determines the limit of a function by trapping it between ___.', ['Two other functions with the same known limit at a given point', 'A single unrelated function with no connection to the original limit', 'A concept unrelated to evaluating limits', 'An infinite number of unrelated functions with no shared limit'], 0),
   ('The Squeeze Theorem is especially useful for functions that are ___.', ['Difficult to evaluate directly', 'Already fully simplified, requiring no further evaluation', 'A concept unrelated to the Squeeze Theorem', 'Undefined at every single point in their domain'], 0),
   ('For the Squeeze Theorem to apply, the two bounding functions must approach ___ at the point in question.', ['The same limiting value', 'Two completely different, unrelated values', 'A concept unrelated to how the Squeeze Theorem works', 'Infinity in every single case, with no other possibility'], 0),
   ('Why is the Squeeze Theorem often used to evaluate a limit like sin(x)/x as x approaches zero?', ['This expression cannot be evaluated by direct substitution, but it can be trapped between two simpler functions with a known common limit', 'This type of limit can always be evaluated using direct substitution, so no special theorem is needed', 'The Squeeze Theorem has no application to trigonometric limits', 'This concept has no connection to evaluating limits involving trigonometric functions'], 0),
   ('Why is the Squeeze Theorem a valuable tool in a calculus student’s broader toolkit for evaluating limits?', ['It provides a rigorous method for finding limits of functions that resist other standard techniques', 'The Squeeze Theorem provides no advantage over other limit-evaluation techniques', 'This theorem has no practical use in evaluating limits of any kind', 'This concept only applies to purely abstract mathematics with no broader use'], 0)]),
P('Physics: The Compton Effect and Photon Momentum',
  'Grade 12 Physics strand: the Compton effect describes the change in wavelength of a photon after it scatters off a charged particle, providing strong evidence that photons carry momentum in addition to energy.',
  [('The Compton effect describes a change in ___ of a photon after it scatters off a charged particle.', ['Wavelength', 'Colour of the particle it scatters from, with no connection to the photon itself', 'A concept unrelated to photon behaviour', 'Mass, which photons do not possess'], 0),
   ('The Compton effect provides strong evidence that photons carry ___ in addition to energy.', ['Momentum', 'Electric charge, which photons do not carry', 'A property entirely unrelated to photon behaviour', 'Mass, in every measurable interaction'], 0),
   ('In the Compton effect, a photon typically scatters off a ___.', ['Charged particle, such as an electron', 'A particle with no measurable properties whatsoever', 'A concept unrelated to photon scattering', 'An empty region of space with no particles present'], 0),
   ('Why does a scattered photon in the Compton effect have a longer wavelength than the incoming photon?', ['The photon transfers some of its energy and momentum to the particle it collides with, reducing its own energy and increasing its wavelength', 'A scattered photon always has exactly the same wavelength as the incoming photon', 'Wavelength has no connection to a photon’s energy or momentum', 'This concept has no relevance to how photons interact with charged particles'], 0),
   ('Why was the Compton effect historically significant in the development of quantum physics?', ['It provided compelling experimental evidence that light behaves as a particle carrying momentum, supporting the quantum theory of light', 'The Compton effect had no significant impact on the development of quantum physics', 'This effect provided no evidence relevant to understanding the nature of light', 'Light was already fully understood as only a particle before this discovery'], 0)])]),

day(53, [
E('Literary Analysis: Free Indirect Discourse and Narrative Distance',
  'Grade 12 English strand: free indirect discourse blends a character’s inner thoughts and voice with the narrator’s own voice, without direct quotation, allowing a writer to shift narrative distance and intimacy within a single passage.',
  [('Free indirect discourse blends a character’s inner thoughts and voice with ___.', ['The narrator’s own voice', 'A completely separate character’s dialogue, quoted directly', 'A concept unrelated to narrative technique', 'A footnote entirely disconnected from the main narrative'], 0),
   ('Free indirect discourse conveys a character’s thoughts without using ___.', ['Direct quotation', 'Any narration whatsoever', 'A concept unrelated to this narrative technique', 'Any grammar or sentence structure at all'], 0),
   ('This technique allows a writer to shift ___ within a single passage.', ['Narrative distance and intimacy', 'The entire setting of the story, with no connection to a character’s perspective', 'A concept unrelated to free indirect discourse', 'The book’s physical formatting exclusively'], 0),
   ('Why might free indirect discourse feel more intimate to a reader than a traditional third-person narration?', ['It merges the narrator’s voice with a character’s private thoughts, drawing the reader closer to that character’s perspective', 'Free indirect discourse always creates more distance between the reader and a character than traditional narration', 'This technique has no effect on how close a reader feels to a character', 'This concept has no connection to how narrative intimacy is achieved'], 0),
   ('Why is free indirect discourse considered a sophisticated technique for Grade 12-level literary analysis?', ['Identifying it requires careful attention to subtle shifts in tone and perspective that are not explicitly marked in the text', 'This technique requires no careful analysis to identify or understand', 'Free indirect discourse is never considered a significant literary technique', 'This concept has no relevance to advanced literary study'], 0)]),
AF('Vectors: The Scalar (Dot) Product and Projections',
   'Grade 12 Advanced Functions strand: the dot product of two vectors produces a single scalar value related to their magnitudes and the angle between them, and it can be used to find the projection of one vector onto another.',
   [('The dot product of two vectors produces ___.', ['A single scalar value', 'A completely new vector unrelated to the original two', 'A concept unrelated to vector operations', 'Two separate scalar values, with no single result'], 0),
    ('The dot product of two vectors is related to their magnitudes and the ___ between them.', ['Angle', 'Colour, with no connection to either vector', 'A factor entirely unrelated to their geometric relationship', 'Total combined length, with no connection to angle'], 0),
    ('The dot product can be used to find the ___ of one vector onto another.', ['Projection', 'Cross product exclusively, with no connection to projection', 'A concept unrelated to vector operations', 'Determinant, which applies only to matrices'], 0),
    ('Why does a dot product of zero indicate that two vectors are perpendicular?', ['A dot product of zero means the angle between the vectors is ninety degrees, since cosine of that angle is zero', 'A dot product of zero always indicates the vectors point in exactly the same direction', 'The value of a dot product has no connection to the angle between two vectors', 'This concept has no relevance to understanding perpendicular vectors'], 0),
    ('Why is the concept of vector projection, calculated using the dot product, useful in fields like physics and engineering?', ['It allows a vector, such as a force, to be broken down into a component acting in a specific, relevant direction', 'Vector projection has no practical application in physics or engineering', 'A vector can never be broken down into components using the dot product', 'This concept only applies to purely abstract mathematics with no real-world use'], 0)]),
C('Calculus: Linear Approximation and Differentials',
  'Grade 12 Calculus strand: linear approximation uses a function’s tangent line at a known point to estimate nearby values, and the differential expresses the small resulting change in output for a small change in input.',
  [('Linear approximation uses a function’s tangent line at a known point to estimate ___.', ['Nearby values of the function', 'Only the exact value at that single known point, with no estimation involved', 'A concept unrelated to tangent lines', 'Values infinitely far from the known point'], 0),
   ('The differential of a function expresses the small resulting change in output for a small change in ___.', ['Input', 'Colour, with no connection to the function’s input or output', 'A concept unrelated to differentials', 'The function’s name, with no connection to its numerical behaviour'], 0),
   ('Linear approximation is generally most accurate when the estimated point is ___ the known point.', ['Close to', 'Extremely far from', 'A concept unrelated to how accurate this approximation is', 'Located at a completely different, unrelated function'], 0),
   ('Why does a function’s tangent line provide a reasonable estimate of its value near the point of tangency?', ['Near that point, the tangent line closely follows the curve’s actual behaviour before the curve diverges more noticeably', 'A tangent line always provides an equally accurate estimate no matter how far from the point of tangency', 'Tangent lines have no relationship to a function’s actual behaviour at nearby points', 'This concept has no connection to how linear approximation works'], 0),
   ('Why is linear approximation a practically useful tool in fields like engineering, where an exact function value may be difficult to compute directly?', ['It provides a fast, reasonably accurate estimate using only a function’s value and slope at a nearby known point', 'Linear approximation has no practical use when an exact calculation is difficult', 'Engineers never rely on estimation techniques when exact values are unavailable', 'This concept only applies to purely theoretical mathematics with no practical application'], 0)]),
P('Physics: Electromagnetic Waves and the Electromagnetic Spectrum',
  'Grade 12 Physics strand: electromagnetic waves consist of oscillating electric and magnetic fields that travel through space, and the electromagnetic spectrum organizes these waves by wavelength and frequency, from radio waves to gamma rays.',
  [('Electromagnetic waves consist of oscillating electric and ___ fields.', ['Magnetic', 'Gravitational, with no connection to electric fields', 'A concept unrelated to electromagnetic waves', 'Nuclear, with no connection to oscillating fields'], 0),
   ('The electromagnetic spectrum organizes waves by wavelength and ___.', ['Frequency', 'Colour exclusively, with no connection to any other property', 'A concept unrelated to the electromagnetic spectrum', 'Mass, which electromagnetic waves do not possess'], 0),
   ('Which of these is an example of electromagnetic radiation with a very short wavelength?', ['Gamma rays', 'Radio waves, which have very long wavelengths', 'A type of radiation unrelated to the electromagnetic spectrum', 'Sound waves, which are not electromagnetic at all'], 0),
   ('Why do all types of electromagnetic waves travel at the same speed in a vacuum, despite having different wavelengths and frequencies?', ['The speed of light in a vacuum is a fundamental constant that applies to all electromagnetic radiation, regardless of wavelength', 'Different types of electromagnetic waves always travel at significantly different speeds in a vacuum', 'The speed of electromagnetic waves has no defined relationship to physical constants', 'This concept has no connection to how electromagnetic waves behave'], 0),
   ('Why is understanding the electromagnetic spectrum important for technologies like medical imaging and wireless communication?', ['Different parts of the spectrum have distinct properties that make them suited to specific practical applications', 'The electromagnetic spectrum has no connection to modern technology', 'All parts of the electromagnetic spectrum behave identically for every possible application', 'This concept has no relevance to medical imaging or communication technology'], 0)])]),

day(54, [
E('Media Literacy: Analyzing Deepfakes and Synthetic Media',
  'Grade 12 English strand: deepfakes and other forms of synthetic media use artificial intelligence to create convincingly fabricated images, audio, or video, raising urgent questions about trust, authenticity, and critical media evaluation.',
  [('Deepfakes and synthetic media use artificial intelligence to create convincingly fabricated ___.', ['Images, audio, or video', 'Only printed text, with no visual or audio component', 'A concept unrelated to media technology', 'Content that is always clearly and obviously fake to any viewer'], 0),
   ('The rise of synthetic media raises urgent questions about trust and ___.', ['Authenticity', 'A concept entirely unrelated to how media is evaluated', 'Printing costs exclusively, with no connection to content itself', 'File size, with no connection to the truthfulness of content'], 0),
   ('Which is an example of a strategy for evaluating whether media might be a deepfake?', ['Checking for a credible original source or cross-referencing with other reporting', 'Assuming every video encountered online is automatically authentic', 'A strategy entirely unrelated to evaluating synthetic media', 'Ignoring the context in which the media was shared'], 0),
   ('Why might deepfakes pose a significant challenge to how people evaluate the credibility of visual evidence?', ['They can convincingly mimic real people and events, undermining the assumption that seeing is the same as verifying', 'Deepfakes never appear convincing enough to be mistaken for real footage', 'Visual evidence has no connection to how people evaluate credibility', 'This concept has no relevance to media literacy or critical evaluation'], 0),
   ('Why is developing skills to critically evaluate synthetic media especially important for students today?', ['As this technology becomes more accessible and realistic, distinguishing authentic from fabricated media is increasingly essential for informed citizenship', 'Synthetic media has no real-world consequences worth understanding', 'These evaluation skills have no connection to being an informed member of society', 'This concept has no relevance to contemporary media literacy education'], 0)]),
AF('Rational Root Theorem and Polynomial Root-Finding',
   'Grade 12 Advanced Functions strand: the Rational Root Theorem lists the possible rational roots of a polynomial with integer coefficients, narrowing the search when factoring or solving higher-degree polynomial equations.',
   [('The Rational Root Theorem lists the possible ___ of a polynomial with integer coefficients.', ['Rational roots', 'Irrational roots exclusively, with no connection to rational values', 'A concept unrelated to polynomial equations', 'Complex, non-real roots exclusively'], 0),
    ('The Rational Root Theorem is especially useful for narrowing the search when factoring or solving ___ polynomial equations.', ['Higher-degree', 'Only first-degree, linear equations', 'A concept unrelated to solving polynomial equations', 'Equations with no variable terms whatsoever'], 0),
    ('According to the Rational Root Theorem, a possible rational root is formed by dividing a factor of the constant term by a factor of the ___.', ['Leading coefficient', 'Exponent of the variable, with no connection to any coefficient', 'A concept unrelated to the Rational Root Theorem', 'Number of terms in the polynomial exclusively'], 0),
    ('Why is testing possible rational roots a practical first step when trying to factor a higher-degree polynomial by hand?', ['It narrows an otherwise unlimited search down to a specific, finite list of candidates worth testing', 'Testing possible rational roots never helps narrow the search for actual roots', 'Every polynomial always has the same set of rational roots, regardless of its coefficients', 'This concept has no connection to factoring higher-degree polynomials'], 0),
    ('Why might the Rational Root Theorem sometimes fail to identify any actual roots of a given polynomial?', ['A polynomial with integer coefficients can have roots that are irrational or complex rather than rational', 'Every polynomial with integer coefficients is guaranteed to have at least one rational root', 'This theorem always identifies every root of any given polynomial without exception', 'This concept has no connection to the nature of a polynomial’s actual roots'], 0)]),
C('Calculus: Newton’s Method for Root Approximation',
  'Grade 12 Calculus strand: Newton’s Method uses a function’s tangent lines to iteratively generate closer and closer approximations to a root, starting from an initial guess and refining it using the function’s derivative.',
  [('Newton’s Method uses a function’s tangent lines to iteratively generate closer approximations to a ___.', ['Root', 'Local maximum exclusively, with no connection to roots', 'A concept unrelated to approximating a function’s behaviour', 'Constant term, with no connection to solving the equation'], 0),
   ('Newton’s Method begins with an initial guess and refines it using the function’s ___.', ['Derivative', 'Constant term only, with no derivative involved', 'A concept unrelated to Newton’s Method', 'Second antiderivative exclusively'], 0),
   ('Each iteration of Newton’s Method typically produces an approximation that is ___ to the actual root than the previous one.', ['Closer', 'Farther from', 'A concept unrelated to how Newton’s Method works', 'Exactly identical, with no meaningful change from the previous approximation'], 0),
   ('Why might Newton’s Method be preferred over algebraic factoring when solving certain equations?', ['Many equations, such as those involving transcendental functions, cannot be solved exactly using algebraic factoring alone', 'Newton’s Method is always slower and less accurate than algebraic factoring for every possible equation', 'Algebraic factoring can always solve any equation exactly, making other methods unnecessary', 'This concept has no connection to solving equations that resist algebraic methods'], 0),
   ('Why is a poor initial guess sometimes a problem when applying Newton’s Method?', ['A poor starting guess can cause the sequence of approximations to converge slowly, to the wrong root, or fail to converge at all', 'The initial guess has no effect on whether Newton’s Method successfully converges to a root', 'Newton’s Method always converges correctly and quickly, regardless of the initial guess chosen', 'This concept has no relevance to the practical application of Newton’s Method'], 0)]),
P('Physics: Neutron Stars and Stellar Remnants',
  'Grade 12 Physics strand: a neutron star is an extremely dense stellar remnant formed when a massive star’s core collapses after a supernova, packing roughly the mass of the Sun into a sphere only a few kilometres across.',
  [('A neutron star is an extremely dense stellar remnant formed when a massive star’s core collapses after a ___.', ['Supernova', 'A completely stable, unchanging period with no collapse involved', 'A concept unrelated to the life cycle of a star', 'A minor, gradual cooling process with no dramatic collapse'], 0),
   ('A neutron star packs roughly the mass of the Sun into a sphere only a few ___ across.', ['Kilometres', 'Light-years, an enormously larger distance', 'A unit entirely unrelated to describing a neutron star’s size', 'Millimetres, an enormously smaller distance'], 0),
   ('Neutron stars are primarily composed of tightly packed ___.', ['Neutrons', 'Free electrons exclusively, with no other particles present', 'A type of particle unrelated to neutron star composition', 'Empty space, with no particles present at all'], 0),
   ('Why does a neutron star’s extreme density result in such an intense gravitational field at its surface?', ['Gravitational field strength depends on how much mass is concentrated within a given volume, and a neutron star packs enormous mass into a very small space', 'A neutron star’s density has no connection to the strength of its gravitational field', 'Gravitational field strength is always identical for every type of stellar remnant', 'This concept has no relevance to understanding the physics of neutron stars'], 0),
   ('Why do astrophysicists study neutron stars to test predictions of general relativity?', ['Their extreme density and gravity create conditions where relativistic effects become especially pronounced and measurable', 'Neutron stars have no connection to testing theories of gravity', 'General relativity makes no distinctive predictions about extremely dense objects', 'This concept has no relevance to modern astrophysics research'], 0)])]),

day(55, [
E('Literature: Diasporic Identity and Migration Narratives',
  'Grade 12 English strand: diasporic literature explores the experiences of individuals and communities living away from an ancestral homeland, often examining themes of displacement, hybrid identity, and the tension between memory and belonging.',
  [('Diasporic literature explores the experiences of individuals and communities living away from an ___.', ['Ancestral homeland', 'Entirely fictional setting with no connection to any real place', 'A concept unrelated to migration or identity', 'Empty, unpopulated location with no cultural history'], 0),
   ('Diasporic literature often examines themes of displacement and ___ identity.', ['Hybrid', 'Entirely singular, with no blending of cultural influences', 'A concept unrelated to diasporic experience', 'Completely erased, with no cultural connection remaining'], 0),
   ('A recurring tension in diasporic narratives is often between memory and ___.', ['Belonging', 'A concept entirely unrelated to identity or place', 'Only geography, with no connection to a character’s inner life', 'Financial success exclusively, with no connection to identity'], 0),
   ('Why might a diasporic narrative depict a character navigating two or more distinct cultural worlds?', ['This reflects the lived reality of many diasporic individuals, who often draw on and reconcile multiple cultural influences', 'Diasporic narratives never depict characters engaging with more than one culture', 'This concept has no connection to how diasporic identity is portrayed in literature', 'Cultural influence has no relevance to a character’s sense of identity'], 0),
   ('Why is diasporic literature an important area of study within a broader survey of contemporary world literature?', ['It offers vital perspectives on migration, identity, and belonging that reflect significant global realities', 'Diasporic literature has no connection to broader patterns in contemporary world literature', 'Migration and displacement are not meaningful subjects for literary exploration', 'This concept has no relevance to studying literature from a global perspective'], 0)]),
AF('Statistics: The Normal Distribution and Z-Scores',
   'Grade 12 Advanced Functions strand: the normal distribution is a symmetric, bell-shaped probability distribution describing many real-world data sets, and a z-score expresses how many standard deviations a value lies from the mean.',
   [('The normal distribution is a symmetric, ___ probability distribution.', ['Bell-shaped', 'Rectangular, with equal probability across the entire range', 'A concept unrelated to probability distributions', 'Sharply spiked at only a single possible value'], 0),
    ('A z-score expresses how many standard deviations a value lies from the ___.', ['Mean', 'Minimum possible value in the entire data set', 'A concept unrelated to standard deviation', 'Total number of data points collected'], 0),
    ('In a normal distribution, most data values cluster ___ the mean.', ['Close to', 'Extremely far from, with almost no values near it', 'A concept unrelated to how a normal distribution is shaped', 'Exclusively at, with no values anywhere else'], 0),
    ('Why is a z-score useful for comparing values that come from data sets with different means and standard deviations?', ['A z-score standardizes a value, expressing its relative position within its own distribution so different data sets can be meaningfully compared', 'Z-scores can never be used to compare values from different data sets', 'A z-score has no connection to how far a value lies from its data set’s mean', 'This concept has no relevance to comparing data across different distributions'], 0),
    ('Why is the normal distribution considered a foundational model in statistics, appearing in fields from psychology to quality control?', ['Many natural and measured phenomena approximately follow this bell-shaped pattern, making it broadly applicable for analysis and prediction', 'The normal distribution has no practical application outside of pure mathematics', 'Real-world data sets never resemble a bell-shaped distribution', 'This concept has no relevance to fields outside of mathematics'], 0)]),
C('Calculus: Hyperbolic Functions and Their Derivatives',
  'Grade 12 Calculus strand: hyperbolic functions, such as sinh(x) and cosh(x), are defined using combinations of exponential functions and share structural similarities with trigonometric functions, including distinct derivative rules.',
  [('Hyperbolic functions, such as sinh(x) and cosh(x), are defined using combinations of ___ functions.', ['Exponential', 'Logarithmic functions exclusively, with no connection to exponentials', 'A concept unrelated to how hyperbolic functions are defined', 'Purely constant functions, with no variable component'], 0),
   ('Hyperbolic functions share structural similarities with ___ functions, including distinct derivative rules.', ['Trigonometric', 'A category of functions entirely unrelated to hyperbolic functions', 'Only linear functions, with no other connection', 'Rational functions exclusively, with no other similarity'], 0),
   ('The derivative of cosh(x) is ___.', ['Sinh(x)', 'Negative sinh(x), the opposite sign', 'A result entirely unrelated to hyperbolic function derivatives', 'Cosh(x), identical to the original function'], 0),
   ('Why might hyperbolic functions be useful for describing the shape of a hanging cable or chain?', ['The curve formed by a hanging cable, called a catenary, can be precisely modelled using the cosh function', 'Hyperbolic functions have no application in modelling physical shapes like a hanging cable', 'A hanging cable’s shape can never be described using any mathematical function', 'This concept has no connection to real-world applications of calculus'], 0),
   ('Why is understanding hyperbolic functions valuable preparation for further study in calculus and physics?', ['They appear in contexts ranging from special relativity to engineering, and their derivative rules parallel those of trigonometric functions', 'Hyperbolic functions have no further application beyond an introductory Grade 12 calculus course', 'These functions never appear in any physics or engineering context', 'This concept has no relevance to further mathematical or scientific study'], 0)]),
P('Physics: Nuclear Binding Energy and Mass Defect',
  'Grade 12 Physics strand: the mass defect of a nucleus is the difference between the total mass of its separate protons and neutrons and the actual mass of the bound nucleus, and this missing mass corresponds to the nucleus’s binding energy.',
  [('The mass defect of a nucleus is the difference between the total mass of its separate protons and neutrons and the actual mass of the ___.', ['Bound nucleus', 'Surrounding electron cloud exclusively, with no connection to the nucleus', 'A concept unrelated to nuclear structure', 'Entire atom’s outermost electron shell only'], 0),
   ('The missing mass in a nucleus corresponds to its ___.', ['Binding energy', 'Electric charge exclusively, with no connection to energy', 'A concept unrelated to nuclear stability', 'Total number of protons, with no connection to energy'], 0),
   ('Binding energy can be understood using Einstein’s famous relationship between ___.', ['Mass and energy', 'Force and acceleration exclusively, with no connection to mass or energy', 'A concept unrelated to nuclear physics', 'Voltage and current, with no connection to nuclear structure'], 0),
   ('Why does a nucleus with a larger binding energy per nucleon tend to be more stable?', ['A greater binding energy per nucleon means more energy would be required to break the nucleus apart into its individual particles', 'Binding energy per nucleon has no connection to how stable a nucleus is', 'A larger binding energy per nucleon always makes a nucleus less stable', 'This concept has no relevance to understanding nuclear stability'], 0),
   ('Why is the concept of mass defect and binding energy essential to understanding both nuclear fission and fusion?', ['Both processes release energy because the resulting nuclei have a different total binding energy than the starting nuclei', 'Mass defect and binding energy have no connection to how fission or fusion release energy', 'Fission and fusion release energy through a process entirely unrelated to nuclear mass or binding', 'This concept has no relevance to understanding nuclear reactions'], 0)])]),

day(56, [
E('Writing: The Academic Book Review',
  'Grade 12 English strand: an academic book review summarizes a text’s central argument, evaluates its evidence and methodology, and situates the work within a broader field of scholarship, going beyond a simple opinion or summary.',
  [('An academic book review summarizes a text’s central ___.', ['Argument', 'Cover design and page count exclusively', 'A concept unrelated to reviewing a text', 'Author’s personal biography only, with no connection to the text’s content'], 0),
   ('An academic book review evaluates a text’s evidence and ___.', ['Methodology', 'Font choice, with no connection to the quality of the work', 'A concept unrelated to academic evaluation', 'Number of chapters exclusively, with no connection to content'], 0),
   ('An academic book review situates a work within a broader field of ___.', ['Scholarship', 'A concept entirely unrelated to how a text connects to other work', 'Unrelated entertainment media exclusively', 'The author’s personal finances'], 0),
   ('Why does an academic book review go beyond a simple summary or personal opinion of a text?', ['It critically assesses the strength of the argument and evidence, offering an informed evaluation grounded in the wider field', 'An academic book review is identical in every way to a simple personal opinion', 'Critical evaluation has no role in this type of writing', 'This concept has no connection to how academic texts are assessed'], 0),
   ('Why is writing an academic book review considered valuable preparation for university-level coursework?', ['It builds skills in critical reading, evaluating evidence, and engaging with existing scholarship, all central to academic writing', 'This type of writing has no connection to skills needed in university coursework', 'Academic book reviews require no critical thinking or evaluation skills', 'This concept has no relevance to preparing for post-secondary academic work'], 0)]),
AF('Matrices: Applications to Transformations in the Plane',
   'Grade 12 Advanced Functions strand: a transformation matrix can rotate, reflect, or scale points in the plane, and multiplying a point’s coordinate vector by the matrix produces the coordinates of the transformed point.',
   [('A transformation matrix can rotate, reflect, or ___ points in the plane.', ['Scale', 'Permanently erase, with no way to recover the original points', 'A concept unrelated to matrix transformations', 'Convert into a completely different, unrelated shape with no geometric relationship'], 0),
    ('Multiplying a point’s coordinate vector by a transformation matrix produces the coordinates of the ___.', ['Transformed point', 'Original, completely unchanged point', 'A concept unrelated to matrix transformations', 'Matrix’s determinant exclusively, with no connection to the point’s new location'], 0),
    ('A rotation matrix uses trigonometric functions to determine how points are rotated around a fixed ___.', ['Point, often the origin', 'Colour, with no connection to geometric rotation', 'A concept unrelated to rotation matrices', 'Random location that changes with each individual point'], 0),
    ('Why can a sequence of multiple transformations, such as a rotation followed by a reflection, be represented by a single combined matrix?', ['Multiplying the individual transformation matrices together produces one matrix that captures the overall combined effect', 'Multiple transformations can never be combined into a single matrix', 'Combining transformation matrices has no connection to representing sequential transformations', 'This concept has no relevance to how matrices are used to model transformations'], 0),
    ('Why are transformation matrices widely used in computer graphics and animation?', ['They provide an efficient, standardized way to rotate, scale, and reposition objects on screen using consistent mathematical operations', 'Transformation matrices have no practical application in computer graphics', 'Computer graphics never require any mathematical representation of movement or rotation', 'This concept only applies to purely abstract mathematics with no real-world use'], 0)]),
C('Calculus: Volumes by Cross-Sections (Non-Revolution Solids)',
  'Grade 12 Calculus strand: the cross-sections method finds the volume of a solid by integrating the area of its cross-sections along an axis, applicable even when the solid is not formed by revolving a curve around an axis.',
  [('The cross-sections method finds the volume of a solid by integrating the ___ of its cross-sections along an axis.', ['Area', 'Perimeter exclusively, with no connection to area', 'A concept unrelated to finding volume', 'Colour, with no connection to any geometric property'], 0),
   ('The cross-sections method is applicable even when a solid is not formed by ___ a curve around an axis.', ['Revolving', 'Drawing, in any form whatsoever', 'A concept unrelated to how a solid is constructed', 'Measuring, with no connection to how the solid is generated'], 0),
   ('Which is an example of a solid whose volume could be found using the cross-sections method, with cross-sections that are squares?', ['A solid built with a square cross-section at every point along its length', 'A solid with no defined cross-sectional shape at any point', 'A concept unrelated to the cross-sections method', 'A solid that has no measurable volume whatsoever'], 0),
   ('Why must the area of each cross-section be expressed as a function of the axis variable before integrating?', ['The cross-sectional area typically changes along the solid’s length, so it must be described as a function to be integrated accurately', 'The cross-sectional area is always exactly the same at every point along a solid', 'Expressing area as a function has no connection to calculating volume through integration', 'This concept has no relevance to using the cross-sections method'], 0),
   ('Why is the cross-sections method more broadly applicable than the disk or shell methods used for solids of revolution?', ['It can find the volume of solids with cross-sections of any consistent shape, not only those generated by revolving a curve', 'The cross-sections method can only ever be applied to solids formed by revolution', 'This method has no advantage over the disk or shell methods in any situation', 'This concept has no connection to calculating the volume of irregular solids'], 0)]),
P('Physics: Lenses and Optical Instruments (Telescopes and Microscopes)',
  'Grade 12 Physics strand: lenses refract light to form images, and combining multiple lenses in optical instruments like telescopes and microscopes can magnify distant or tiny objects beyond what a single lens could achieve.',
  [('Lenses form images by ___ light.', ['Refracting', 'Completely absorbing, with no light passing through', 'A concept unrelated to how lenses function', 'Reflecting exclusively, with no refraction involved'], 0),
   ('Combining multiple lenses in optical instruments can ___ distant or tiny objects beyond what a single lens could achieve.', ['Magnify', 'Completely hide from view, with no image produced', 'A concept unrelated to optical instruments', 'Shrink to an unusable, indistinguishable size'], 0),
   ('Which of these is an example of an optical instrument that uses combined lenses to view distant objects?', ['A telescope', 'A mirror with no lens involved at all', 'A device entirely unrelated to viewing distant objects', 'A flashlight, which produces light rather than forming an image'], 0),
   ('Why does a microscope typically use two separate lenses, an objective lens and an eyepiece, rather than a single lens?', ['Combining two lenses allows the image formed by the first lens to be magnified further by the second, achieving much greater overall magnification', 'Using two lenses always produces exactly the same magnification as using only one', 'A microscope’s design has no connection to how its lenses work together', 'This concept has no relevance to how optical instruments achieve magnification'], 0),
   ('Why is understanding lens behaviour important for designing optical instruments used in scientific research, such as advanced telescopes?', ['Precisely controlling how lenses refract and focus light is essential for achieving clear, accurately magnified images', 'Lens behaviour has no connection to the design of scientific optical instruments', 'Optical instruments used in research never rely on any understanding of lenses', 'This concept has no relevance to producing clear, magnified images'], 0)])]),

day(57, [
E('Oral Communication: Facilitating a Panel Discussion',
  'Grade 12 English strand: facilitating a panel discussion involves guiding multiple speakers through a structured conversation, balancing airtime, asking clarifying questions, and keeping the discussion focused on its central topic.',
  [('Facilitating a panel discussion involves guiding multiple speakers through a ___ conversation.', ['Structured', 'Completely unplanned, with no guidance from a facilitator', 'A concept unrelated to oral communication', 'Silent, with no spoken conversation at all'], 0),
   ('A skilled facilitator balances ___ among panelists.', ['Airtime', 'Only the opinions of a single panelist, ignoring all others', 'A concept unrelated to facilitating group discussion', 'Background noise, with no connection to speaker participation'], 0),
   ('A facilitator often asks ___ questions to help the audience better understand a panelist’s point.', ['Clarifying', 'Deliberately confusing, with no intent to aid understanding', 'A concept unrelated to facilitating discussion', 'Entirely unrelated, with no connection to the discussion topic'], 0),
   ('Why might a facilitator need to gently redirect a panel discussion back to its central topic?', ['Conversations can naturally drift, and redirection helps ensure the discussion remains valuable and focused for the audience', 'A facilitator should never attempt to guide the direction of a panel discussion', 'Panel discussions never drift away from their intended topic', 'This concept has no connection to effectively facilitating a group conversation'], 0),
   ('Why is facilitating a panel discussion considered a valuable oral communication skill to develop at the Grade 12 level?', ['It requires active listening, quick thinking, and the ability to manage group dynamics, all skills valuable in academic and professional settings', 'Facilitating a panel discussion requires no particular skill or preparation', 'This skill has no connection to future academic or professional communication', 'This concept has no relevance to developing strong oral communication abilities'], 0)]),
AF('Number Theory: Modular Arithmetic and Applications',
   'Grade 12 Advanced Functions strand: modular arithmetic describes a system where numbers wrap around after reaching a fixed value called the modulus, with wide applications in areas such as cryptography and scheduling.',
   [('Modular arithmetic describes a system where numbers wrap around after reaching a fixed value called the ___.', ['Modulus', 'Determinant, a concept unrelated to modular arithmetic', 'A concept unrelated to this number system', 'Coefficient, with no connection to how numbers wrap around'], 0),
    ('Modular arithmetic has wide applications in areas such as cryptography and ___.', ['Scheduling', 'A field entirely unrelated to any practical application', 'Only purely decorative art, with no mathematical or practical use', 'A concept unrelated to modular arithmetic’s uses'], 0),
    ('In modulo 5 arithmetic, what is 12 mod 5?', ['2', '5', 'A value unrelated to the calculation', '12'], 0),
    ('Why is a standard analog clock often used as an everyday example of modular arithmetic?', ['The hours wrap back around to 1 after reaching 12, mirroring how modular arithmetic wraps around after reaching the modulus', 'A clock has no connection to how modular arithmetic functions', 'Clocks always count upward with no repeating or wrapping pattern', 'This concept has no relevance to understanding modular systems'], 0),
    ('Why is modular arithmetic considered essential to modern cryptographic systems that protect digital information?', ['Many encryption methods rely on the mathematical properties of numbers within a modular system to securely encode and decode information', 'Modular arithmetic has no connection to how digital information is secured', 'Cryptography never relies on any mathematical structure or system', 'This concept has no relevance to digital security or encryption'], 0)]),
C('Calculus: Center of Mass and Centroids',
  'Grade 12 Calculus strand: the center of mass of an object is the point at which its mass can be considered concentrated, and for a region with uniform density, this point (the centroid) can be found using integration.',
  [('The center of mass of an object is the point at which its ___ can be considered concentrated.', ['Mass', 'Colour, with no connection to a physical property', 'A concept unrelated to an object’s physical properties', 'Surface temperature exclusively, with no connection to mass'], 0),
   ('For a region with uniform density, the center of mass is also known as the ___.', ['Centroid', 'Determinant, a concept unrelated to center of mass', 'A concept unrelated to describing a region’s geometry', 'Vertex, with no connection to a region’s balance point'], 0),
   ('Finding the centroid of a two-dimensional region typically requires using ___.', ['Integration', 'Only basic addition, with no calculus involved', 'A concept unrelated to finding a centroid', 'A single, isolated measurement with no calculation required'], 0),
   ('Why might an irregularly shaped object’s center of mass not be located at its visual, geometric center?', ['If mass is not distributed uniformly throughout the object, the balance point shifts toward the regions with greater mass concentration', 'An object’s center of mass is always located at its exact visual center, regardless of shape', 'Mass distribution has no connection to where an object’s center of mass is located', 'This concept has no relevance to understanding how objects balance'], 0),
   ('Why is understanding an object’s center of mass important in fields like engineering and structural design?', ['Knowing where mass is effectively concentrated helps engineers predict how a structure will balance, rotate, or respond to applied forces', 'Center of mass has no practical relevance to engineering or structural design', 'Structures never need to be analyzed for balance or stability', 'This concept only applies to purely theoretical mathematics with no engineering application'], 0)]),
P('Physics: Simple Machines and Mechanical Advantage',
  'Grade 12 Physics strand: a simple machine, such as a lever or pulley, changes the size or direction of an applied force, and its mechanical advantage describes the ratio between the output force and the input force.',
  [('A simple machine, such as a lever or pulley, changes the size or ___ of an applied force.', ['Direction', 'Colour, with no connection to how force is applied', 'A concept unrelated to simple machines', 'Chemical composition, with no connection to mechanical force'], 0),
   ('Mechanical advantage describes the ratio between the output force and the ___ force.', ['Input', 'A completely unrelated, external force with no connection to the machine', 'A concept unrelated to mechanical advantage', 'Gravitational force exclusively, regardless of the machine involved'], 0),
   ('Which of these is an example of a simple machine?', ['A lever', 'A battery, which stores electrical energy rather than transmitting mechanical force', 'A device entirely unrelated to mechanical force', 'A thermometer, which measures temperature rather than force'], 0),
   ('Why can a lever allow a person to lift a heavy object using less applied force than lifting it directly?', ['A lever can trade a smaller input force over a greater distance for a larger output force over a shorter distance', 'A lever always requires exactly the same force as lifting an object directly, with no advantage at all', 'Mechanical advantage has no connection to how a lever functions', 'This concept has no relevance to understanding simple machines'], 0),
   ('Why do engineers consider mechanical advantage when designing tools and machines for practical tasks?', ['Understanding mechanical advantage helps engineers design tools that make physical tasks easier or more efficient to perform', 'Mechanical advantage has no practical relevance to designing tools or machines', 'Engineers never need to consider the relationship between input and output force', 'This concept only applies to purely theoretical physics with no practical use'], 0)])]),

day(58, [
E('Literature: Dystopian and Utopian Fiction in Dialogue',
  'Grade 12 English strand: dystopian and utopian fiction imagine radically different societies, and reading these genres together reveals how authors use imagined worlds to critique or idealize aspects of their own historical moment.',
  [('Dystopian and utopian fiction imagine ___ societies.', ['Radically different', 'Entirely identical to the author’s own contemporary society, with no imaginative change', 'A concept unrelated to speculative or imaginative fiction', 'Societies with no connection to any real-world concerns'], 0),
   ('Reading dystopian and utopian fiction together reveals how authors use imagined worlds to critique or ___ aspects of their own historical moment.', ['Idealize', 'Completely ignore, with no connection to their own historical moment', 'A concept unrelated to how these genres function', 'Erase entirely, with no reflection of any real-world concerns'], 0),
   ('Which is a common feature of dystopian fiction?', ['A society governed by oppressive control, often disguised as order or perfection', 'A society with no flaws, conflicts, or forms of control whatsoever', 'A concept unrelated to dystopian fiction', 'A story set entirely in the past, with no imagined future elements'], 0),
   ('Why might a dystopian novel and a utopian novel be understood as two sides of a similar imaginative project?', ['Both genres extrapolate present-day values and anxieties to imagine how a society might evolve, whether toward collapse or improvement', 'Dystopian and utopian fiction have no meaningful relationship to one another', 'These two genres never engage with any of the same underlying societal concerns', 'This concept has no connection to how speculative fiction functions'], 0),
   ('Why might comparing dystopian and utopian visions from different historical periods reveal something about changing societal concerns?', ['The specific anxieties or hopes reflected in these imagined worlds often mirror the pressing issues of the era in which they were written', 'These genres never reflect the specific societal concerns of the time period in which they were written', 'This concept has no relevance to understanding literature within its historical context', 'Dystopian and utopian fiction are unrelated to the broader historical moment of their creation'], 0)]),
AF('Functions: Rational Exponents, Radicals, and Simplification Techniques',
   'Grade 12 Advanced Functions strand: rational exponents express roots and powers together in a single notation, allowing radical expressions to be simplified and manipulated using the same rules that apply to integer exponents.',
   [('Rational exponents express roots and powers together in a single ___.', ['Notation', 'A concept entirely unrelated to exponents or radicals', 'Physical measurement, with no connection to algebraic notation', 'Geometric shape, with no connection to numerical expressions'], 0),
    ('Rational exponents allow radical expressions to be simplified using the same rules that apply to ___ exponents.', ['Integer', 'Only negative exponents, with no connection to positive integer exponents', 'A concept unrelated to simplifying expressions', 'Undefined exponents, with no consistent rules at all'], 0),
    ('The expression x^(1/2) is equivalent to ___.', ['The square root of x', 'X squared, an entirely different operation', 'A value unrelated to square roots', 'Negative x, with no connection to roots at all'], 0),
    ('Why is expressing a radical using a rational exponent often useful when simplifying a complicated algebraic expression?', ['Rational exponent notation allows familiar exponent rules, such as multiplying powers, to be applied directly to expressions involving roots', 'Rational exponent notation makes simplifying expressions involving roots significantly more difficult', 'Radical expressions can never be rewritten using exponent notation', 'This concept has no connection to simplifying algebraic expressions'], 0),
    ('Why is fluency with rational exponents and radical simplification considered important preparation for university-level mathematics and science courses?', ['These techniques appear frequently in advanced algebra, calculus, and scientific formulas, so fluency supports success in more advanced coursework', 'Rational exponents and radicals have no further relevance beyond an introductory Grade 12 course', 'University-level mathematics and science never involve expressions with roots or rational exponents', 'This concept has no connection to preparing for advanced academic study'], 0)]),
C('Calculus: Work Done by a Variable Force',
  'Grade 12 Calculus strand: when a force applied to an object changes over distance, the total work done can be found by integrating the force function with respect to displacement, rather than using a single multiplication.',
  [('When a force applied to an object changes over distance, the total work done can be found by ___ the force function with respect to displacement.', ['Integrating', 'Multiplying by a single, constant value with no variation considered', 'A concept unrelated to calculating work', 'Differentiating, the opposite calculus operation'], 0),
   ('Work done by a variable force cannot generally be found using a single ___.', ['Multiplication', 'Integration, which is the appropriate method for this calculation', 'A concept unrelated to calculating variable work', 'Function, since a function is required to describe the varying force'], 0),
   ('Which is an example of a situation involving work done by a variable force?', ['Stretching a spring, where the force required increases as the spring stretches farther', 'Lifting an object with a perfectly constant force over the entire distance', 'A situation entirely unrelated to changing force', 'A scenario where no force is applied at any point'], 0),
   ('Why is integration necessary to calculate the work done in stretching a spring, rather than simple multiplication of force and distance?', ['Since the force required to stretch a spring increases continuously with displacement, the work must be accumulated over infinitesimally small distances', 'The force required to stretch a spring always remains exactly constant, so integration is unnecessary', 'Integration has no connection to calculating work done by a changing force', 'This concept has no relevance to how work is calculated in physical situations'], 0),
   ('Why is the calculus-based approach to calculating work broadly useful across physics and engineering problems?', ['Many real-world forces are not constant, so integration provides an accurate method for calculating the total work done in these more realistic situations', 'Calculus has no advantage over simple multiplication when calculating work in real-world situations', 'Forces encountered in physics and engineering are always constant, making integration unnecessary', 'This concept only applies to purely theoretical mathematics with no practical use'], 0)]),
P('Physics: The Uncertainty Principle and Quantum Measurement',
  'Grade 12 Physics strand: the uncertainty principle states that certain pairs of properties, such as a particle’s position and momentum, cannot both be known with arbitrary precision at the same time, a fundamental limit rather than a measurement flaw.',
  [('The uncertainty principle states that certain pairs of properties cannot both be known with ___ at the same time.', ['Arbitrary precision', 'Any degree of precision whatsoever, under any circumstances', 'A concept unrelated to measurement in quantum physics', 'Complete inaccuracy, with no meaningful information available at all'], 0),
   ('A classic pair of properties limited by the uncertainty principle is a particle’s position and ___.', ['Momentum', 'Colour, a property that particles at this scale do not possess', 'A concept unrelated to the uncertainty principle', 'Name, which has no physical or measurable meaning'], 0),
   ('The limit described by the uncertainty principle is considered ___ rather than a flaw in measurement technique.', ['Fundamental', 'Completely avoidable with sufficiently advanced instruments', 'A concept unrelated to the nature of this physical limit', 'Irrelevant to how particles actually behave'], 0),
   ('Why does increasing the precision of a position measurement for a quantum particle necessarily increase the uncertainty in its momentum?', ['According to the uncertainty principle, the product of the uncertainties in these two properties cannot fall below a fundamental limit', 'Measuring position more precisely always has no effect whatsoever on how precisely momentum can be known', 'Position and momentum have no established mathematical relationship at the quantum scale', 'This concept has no relevance to how quantum measurement works'], 0),
   ('Why was the uncertainty principle a significant departure from the assumptions of classical physics?', ['It revealed a fundamental limit to what can be simultaneously known about a system, challenging the classical assumption of unlimited measurement precision', 'The uncertainty principle made no meaningful change to how physicists understood measurement', 'Classical physics already assumed inherent limits on measurement precision at every scale', 'This concept has no relevance to the historical development of quantum theory'], 0)])]),

day(59, [
E('Grammar and Style: The Semicolon, the Colon, and Rhythm in Prose',
  'Grade 12 English strand: skilled use of the semicolon and colon shapes the rhythm and emphasis of a sentence, allowing a writer to connect closely related ideas or build toward a climactic point with precision.',
  [('Skilled use of the semicolon and colon shapes the rhythm and ___ of a sentence.', ['Emphasis', 'Total word count exclusively, with no connection to meaning', 'A concept unrelated to sentence-level style', 'Font size, with no connection to punctuation'], 0),
   ('A semicolon can be used to connect ___ ideas within a single sentence.', ['Closely related independent', 'Completely unrelated, disconnected', 'A concept unrelated to how a semicolon functions', 'Only single words, with no connection to full clauses'], 0),
   ('A colon can be used to build toward a ___ point in a sentence.', ['Climactic', 'Entirely irrelevant, with no connection to the sentence’s meaning', 'A concept unrelated to how a colon functions stylistically', 'Grammatically incorrect, with no stylistic purpose'], 0),
   ('Why might a writer choose a semicolon over a period when connecting two related independent clauses?', ['A semicolon can signal a closer, more immediate relationship between the two ideas than a full stop would suggest', 'A semicolon always creates a greater sense of separation between two ideas than a period', 'Semicolons have no effect on how closely two ideas feel connected', 'This concept has no connection to shaping a sentence’s rhythm or meaning'], 0),
   ('Why is deliberate, purposeful punctuation considered a mark of sophisticated prose style at the Grade 12 level?', ['It shows a writer’s control over pacing and emphasis, shaping how a reader experiences the rhythm and meaning of a sentence', 'Punctuation choices have no meaningful effect on how a reader experiences a piece of writing', 'Sophisticated writing never requires any deliberate attention to punctuation', 'This concept has no relevance to developing an advanced prose style'], 0)]),
AF('Discrete Math: Graph Theory Basics (Vertices and Edges)',
   'Grade 12 Advanced Functions strand: a graph in discrete mathematics is a structure made up of vertices connected by edges, used to model relationships or connections between objects in networks, maps, and scheduling problems.',
   [('A graph in discrete mathematics is a structure made up of vertices connected by ___.', ['Edges', 'Determinants, a concept unrelated to graph theory', 'A concept unrelated to graph structures', 'Colours, with no connection to how vertices are linked'], 0),
    ('Graphs are used to model relationships or connections between objects in networks, maps, and ___ problems.', ['Scheduling', 'A category entirely unrelated to practical applications of graph theory', 'Purely decorative art, with no connection to relationships or networks', 'Only physical distance, with no connection to abstract relationships'], 0),
    ('In graph theory, a vertex represents ___.', ['An individual object or point in the structure', 'The total number of connections in the entire graph', 'A concept unrelated to graph theory', 'A specific numerical value with no connection to a point or object'], 0),
    ('Why might a graph be a useful way to represent a network of cities connected by direct flight routes?', ['The cities can be represented as vertices and the flight routes as edges, capturing the connections between them clearly', 'A graph provides no useful way to represent connections between different locations', 'Cities and flight routes have no relationship that can be modelled using vertices and edges', 'This concept has no relevance to representing real-world networks'], 0),
    ('Why is graph theory considered a foundational tool in computer science, such as in designing efficient networks or algorithms?', ['It provides a precise mathematical framework for modelling and analyzing complex systems of connected objects', 'Graph theory has no application in computer science or algorithm design', 'Complex systems of connections can never be represented using graph theory', 'This concept only applies to purely abstract mathematics with no practical use'], 0)]),
C('Calculus: Area Enclosed by Polar Curves',
  'Grade 12 Calculus strand: finding the area enclosed by a polar curve involves integrating a formula based on the square of the radius function over a given angular interval, rather than using standard Cartesian area methods.',
  [('Finding the area enclosed by a polar curve involves integrating a formula based on the square of the ___ function.', ['Radius', 'Angle exclusively, with no connection to the radius', 'A concept unrelated to polar curves', 'Slope, a concept unrelated to polar area formulas'], 0),
   ('The polar area formula integrates over a given ___ interval.', ['Angular', 'Purely linear, horizontal interval, as in standard Cartesian area problems', 'A concept unrelated to polar coordinates', 'Vertical interval exclusively, with no connection to angle'], 0),
   ('Standard Cartesian area methods are generally ___ for finding the area enclosed by many polar curves.', ['Not directly suitable', 'Always the simplest and most direct method available', 'A concept unrelated to comparing area calculation methods', 'Identical in every way to the polar area method'], 0),
   ('Why is a specialized formula needed to find the area enclosed by a polar curve, rather than using the standard Cartesian integral for area under a curve?', ['Polar curves are described in terms of radius and angle rather than x and y, so accumulating area requires a formula suited to that coordinate system', 'Polar curves can always be converted into Cartesian form with no change to the resulting area calculation', 'The standard Cartesian area formula works equally well for every polar curve without modification', 'This concept has no connection to how area is calculated in different coordinate systems'], 0),
   ('Why is being able to calculate area enclosed by polar curves a valuable extension of a Grade 12 calculus student’s integration skills?', ['It demonstrates how integration techniques can be adapted to different coordinate systems, deepening understanding of area accumulation more broadly', 'This skill has no further relevance beyond a single specific type of calculus problem', 'Polar coordinates are never used in any further mathematical or scientific study', 'This concept has no connection to broader integration techniques in calculus'], 0)]),
P('Physics: Cosmic Rays and Particle Detection in the Atmosphere',
  'Grade 12 Physics strand: cosmic rays are high-energy particles originating from outer space that collide with molecules in Earth’s atmosphere, producing cascades of secondary particles that can be detected and studied from the ground.',
  [('Cosmic rays are high-energy particles originating from ___.', ['Outer space', 'Only man-made sources located on Earth’s surface', 'A concept unrelated to high-energy particles', 'The centre of the Earth exclusively, with no connection to space'], 0),
   ('When cosmic rays collide with molecules in Earth’s atmosphere, they produce cascades of ___ particles.', ['Secondary', 'Entirely identical, unchanged original particles with no new particles produced', 'A concept unrelated to particle collisions', 'Particles that immediately disappear with no detectable trace at all'], 0),
   ('Cascades of particles produced by cosmic ray collisions can be detected and studied from ___.', ['The ground', 'Nowhere; these cascades can never be detected in any way', 'A concept unrelated to studying cosmic rays', 'Only from within the source star itself, with no detection possible on Earth'], 0),
   ('Why do cosmic rays colliding with the atmosphere produce a cascade of many secondary particles rather than a single resulting particle?', ['The initial high-energy collision can trigger a chain of further collisions and particle interactions as energy is distributed through the atmosphere', 'A cosmic ray collision always produces exactly one resulting particle, with no further interactions', 'Cosmic ray collisions have no connection to producing additional particles', 'This concept has no relevance to understanding particle behaviour in the atmosphere'], 0),
   ('Why do physicists study cosmic ray cascades using ground-based particle detectors?', ['These cascades provide valuable information about high-energy particles and astrophysical processes that would be difficult to study directly', 'Cosmic ray cascades provide no useful scientific information about particles or astrophysical processes', 'Ground-based detectors have no ability to detect or study particle cascades', 'This concept has no relevance to modern astrophysics or particle physics research'], 0)])]),

day(60, [
E('Review: Grade 12 English -- Days 51-59 Synthesis',
  'Grade 12 English strand review: this lesson revisits existentialist philosophy in the novel, media literacy around synthetic media, diasporic identity, and the stylistic use of semicolons and colons from Days 51-59.',
  [('Existentialist literature explores themes of individual freedom and the necessity of creating ___ in a universe without inherent purpose.', ['Meaning', 'A fixed, predetermined destiny with no room for individual choice', 'A concept unrelated to existentialist philosophy', 'Wealth and material success exclusively'], 0),
   ('Deepfakes and synthetic media use artificial intelligence to create convincingly fabricated ___.', ['Images, audio, or video', 'Only printed text, with no visual or audio component', 'A concept unrelated to media technology', 'Content that is always clearly and obviously fake to any viewer'], 0),
   ('Diasporic literature explores the experiences of individuals and communities living away from an ___.', ['Ancestral homeland', 'Entirely fictional setting with no connection to any real place', 'A concept unrelated to migration or identity', 'Empty, unpopulated location with no cultural history'], 0),
   ('Skilled use of the semicolon and colon shapes the rhythm and ___ of a sentence.', ['Emphasis', 'Total word count exclusively, with no connection to meaning', 'A concept unrelated to sentence-level style', 'Font size, with no connection to punctuation'], 0),
   ('Why is it useful to review existentialist themes, media literacy, diasporic identity, and stylistic punctuation together?', ['These related English concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in English', 'Each topic must be learned in complete isolation'], 0)]),
AF('Review: Grade 12 Advanced Functions -- Days 51-59 Synthesis',
   'Grade 12 Advanced Functions strand review: this lesson revisits eigenvalues and eigenvectors, the normal distribution, rational exponents, and graph theory basics from Days 51-59.',
   [('An eigenvector of a matrix is a nonzero vector whose ___ remains unchanged when the matrix is applied to it.', ['Direction', 'Exact numerical length, in every single case', 'A concept unrelated to matrices', 'Colour, with no connection to matrix operations'], 0),
    ('The normal distribution is a symmetric, ___ probability distribution.', ['Bell-shaped', 'Rectangular, with equal probability across the entire range', 'A concept unrelated to probability distributions', 'Sharply spiked at only a single possible value'], 0),
    ('The expression x^(1/2) is equivalent to ___.', ['The square root of x', 'X squared, an entirely different operation', 'A value unrelated to square roots', 'Negative x, with no connection to roots at all'], 0),
    ('A graph in discrete mathematics is a structure made up of vertices connected by ___.', ['Edges', 'Determinants, a concept unrelated to graph theory', 'A concept unrelated to graph structures', 'Colours, with no connection to how vertices are linked'], 0),
    ('Why is it useful to review eigenvalues, the normal distribution, rational exponents, and graph theory together?', ['These related math concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in math', 'Each topic must be learned in complete isolation'], 0)]),
C('Review: Grade 12 Calculus -- Days 51-59 Synthesis',
  'Grade 12 Calculus strand review: this lesson revisits the Squeeze Theorem, hyperbolic functions, center of mass, and area enclosed by polar curves from Days 51-59.',
  [('The Squeeze Theorem determines the limit of a function by trapping it between ___.', ['Two other functions with the same known limit at a given point', 'A single unrelated function with no connection to the original limit', 'A concept unrelated to evaluating limits', 'An infinite number of unrelated functions with no shared limit'], 0),
   ('Hyperbolic functions, such as sinh(x) and cosh(x), are defined using combinations of ___ functions.', ['Exponential', 'Logarithmic functions exclusively, with no connection to exponentials', 'A concept unrelated to how hyperbolic functions are defined', 'Purely constant functions, with no variable component'], 0),
   ('The center of mass of an object is the point at which its ___ can be considered concentrated.', ['Mass', 'Colour, with no connection to a physical property', 'A concept unrelated to an object’s physical properties', 'Surface temperature exclusively, with no connection to mass'], 0),
   ('Finding the area enclosed by a polar curve involves integrating a formula based on the square of the ___ function.', ['Radius', 'Angle exclusively, with no connection to the radius', 'A concept unrelated to polar curves', 'Slope, a concept unrelated to polar area formulas'], 0),
   ('Why is it useful to review the Squeeze Theorem, hyperbolic functions, center of mass, and polar area together?', ['These related calculus techniques reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in calculus', 'Each topic must be studied with no connection to the others'], 0)]),
P('Review: Grade 12 Physics -- Days 51-59 Synthesis',
  'Grade 12 Physics strand review: this lesson revisits the Bohr model and atomic spectra, neutron stars, simple machines, and the uncertainty principle from Days 51-59.',
  [('The Bohr model describes electrons orbiting the nucleus in ___.', ['Fixed energy levels', 'A single continuous, unrestricted path with no defined levels', 'A concept unrelated to atomic structure', 'Random, unpredictable positions with no defined structure at all'], 0),
   ('A neutron star is an extremely dense stellar remnant formed when a massive star’s core collapses after a ___.', ['Supernova', 'A completely stable, unchanging period with no collapse involved', 'A concept unrelated to the life cycle of a star', 'A minor, gradual cooling process with no dramatic collapse'], 0),
   ('A simple machine, such as a lever or pulley, changes the size or ___ of an applied force.', ['Direction', 'Colour, with no connection to how force is applied', 'A concept unrelated to simple machines', 'Chemical composition, with no connection to mechanical force'], 0),
   ('The uncertainty principle states that certain pairs of properties cannot both be known with ___ at the same time.', ['Arbitrary precision', 'Any degree of precision whatsoever, under any circumstances', 'A concept unrelated to measurement in quantum physics', 'Complete inaccuracy, with no meaningful information available at all'], 0),
   ('Why is it useful to review the Bohr model, neutron stars, simple machines, and the uncertainty principle together?', ['These related physics concepts reinforce each other for stronger overall understanding', 'These topics have no connection to each other', 'Review is never useful in physics', 'Each topic must be studied with no connection to the others'], 0)])]),
]


def _rebalance_answer_positions(days, seed=20260807):
    """Same technique used for the earlier Phase 3 batches -- reassigns
    each question's correct-answer slot via a shuffled round-robin (even
    across 0-3) and shuffles the wrong options into the remaining slots.
    Question and option TEXT is never changed. Mutates `days` in place."""
    import random
    rng = random.Random(seed)
    all_quizzes = [quiz for _, subs in days for *_, quiz in subs]
    n = sum(len(quiz) for quiz in all_quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in all_quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)


if __name__ == '__main__':
    _rebalance_answer_positions(g12_51_60)
    append_to(12, g12_51_60)
