#!/usr/bin/env python3
"""Grade 9, Days 171-180 -- extends Grade 9 from 170 to 180 days. Topics
chosen after dumping and reading the full Day 1-170 title list (data/grade9.json)
to avoid any overlap, which by this point is exhaustive across all four
subjects: analyzing misinformation and verification techniques, tense
consistency and avoiding verb tense shifts, acronyms and initialisms,
analyzing red herrings and misdirection in plot, writing a memoir excerpt,
double negatives and negation in Standard English, homophones and
homographs, analyzing exposition and rising action in plot structure, and
writing a press release; graphing the cosecant, secant, and cotangent
functions, Wilsons Theorem, an introduction to the central limit theorem,
payday loans and the cost of predatory lending, the scalar triple product
and volume of a parallelepiped, the inclusion-exclusion principle,
optimization using derivatives, the angle between two planes using normal
vectors, and recursive versus explicit formulas for sequences;
electrolysis and electroplating, diffraction and polarization of light,
neurons and synaptic transmission, aurora and the interaction of solar
wind with the atmosphere, Keplers Laws of planetary motion, water
purification and treatment chemistry, entropy and the second law of
thermodynamics, animal migration and navigation, and light pollution and
its effects on ecosystems; the geography of colonial boundaries and their
legacy in Africa, transboundary rivers and water-sharing conflicts, fair
trade and ethical sourcing, illegal wildlife trade and poaching hotspots,
salt production and historic salt trade routes, global courier and
logistics networks, transboundary air pollution and regional haze, urban
waterfront redevelopment, and micronations and unrecognized states. Day
180 is a cross-subject review day drawing quiz content from Days 171-179
of this same batch; its four review titles ("Language Review:
Misinformation, Acronyms, Red Herrings, and Press Releases", "Math
Review: Reciprocal Trig Functions, Wilsons Theorem, Payday Loans, and
Optimization", "Science Review: Electrolysis, Neurons, Keplers Laws, and
Entropy", "Social Studies Review: Colonial Boundaries, Fair Trade,
Wildlife Trade, and Micronations") are textually distinct from every
earlier review days title in Days 1-170.

Subject keys for Grade 9 are "Language", "Math", "Science",
"SocialStudies" (same as all earlier Grade 9 batches); SocialStudies
content is Geography-focused, matching the existing convention.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes are avoided entirely (e.g.
"Wilsons Theorem" not "Wilson's Theorem", "Keplers Laws" not "Kepler's
Laws", "Earths" not "Earth's", "citys" not "city's").
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

L9 = 'https://tvolearn.com/pages/grade-9-english'
M9 = 'https://tvolearn.com/pages/grade-9-mathematics'
S9 = 'https://tvolearn.com/pages/grade-9-science'
SS9 = 'https://tvolearn.com/pages/grade-9-geography'
RL, RM, RS, RSS = (
    'TVO Learn: Grade 9 English',
    'TVO Learn: Grade 9 Mathematics',
    'TVO Learn: Grade 9 Science',
    'TVO Learn: Grade 9 Geography',
)


def L(t, s, q):
    return sub('Language', t, s, RL, L9, q)


def M(t, s, q):
    return sub('Math', t, s, RM, M9, q)


def Sc(t, s, q):
    return sub('Science', t, s, RS, S9, q)


def SS(t, s, q):
    return sub('SocialStudies', t, s, RSS, SS9, q)


def _rebalance_answer_positions(days, seed=20260818):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g9_171_180 = [
day(171, [
L('Media Literacy: Analyzing Misinformation and Verification Techniques',
  'Grade 9 Language strand: misinformation is false or inaccurate information spread regardless of intent to deceive, and media-literate readers verify claims by checking original sources, cross-referencing multiple outlets, and looking for evidence before sharing content further.',
  [('What is misinformation?', ['False or inaccurate information that is spread, regardless of whether the person sharing it intends to deceive', 'Information that is always spread deliberately to deceive an audience', 'A type of information that is always factually accurate and verified', 'A term used only to describe information found in printed newspapers'], 0),
   ('What is a reliable first step when verifying a claim seen online?', ['Checking the original source and looking for supporting evidence from other credible outlets', 'Sharing the claim immediately without reading past the headline', 'Assuming the claim is true because many people have shared it', 'Ignoring the source of the claim entirely'], 0),
   ('Why is cross-referencing multiple sources useful when evaluating a claim?', ['It helps confirm whether independent, credible sources agree on the same facts', 'It guarantees a claim is false if only one source reports it', 'Cross-referencing sources has no value in verifying information', 'A single source is always more reliable than several independent sources'], 0),
   ('How does misinformation differ from disinformation?', ['Misinformation may be spread without intent to deceive, while disinformation is deliberately created or shared to mislead', 'Misinformation and disinformation are exactly the same thing', 'Disinformation is always accidental, while misinformation is always deliberate', 'Neither term has any connection to the accuracy of information'], 0),
   ('Why should a media-literate reader pause before resharing a surprising claim?', ['Sharing false information quickly can spread inaccurate claims before they can be verified', 'Pausing before sharing information always makes a claim less accurate', 'Surprising claims are always guaranteed to be true', 'A reader has no responsibility for what they choose to share online'], 0)]),
M('Trigonometry: Graphing the Cosecant, Secant, and Cotangent Functions',
  'Grade 9 Math strand: cosecant, secant, and cotangent are the reciprocal trigonometric functions of sine, cosine, and tangent respectively, and their graphs contain vertical asymptotes wherever the corresponding reciprocal function equals zero.',
  [('What is the cosecant function defined as the reciprocal of?', ['The sine function', 'The cosine function', 'The tangent function', 'Cosecant has no relationship to any other trigonometric function'], 0),
   ('What is the secant function defined as the reciprocal of?', ['The cosine function', 'The sine function', 'The tangent function', 'Secant has no relationship to any other trigonometric function'], 0),
   ('Where do vertical asymptotes occur on the graph of y = csc(x)?', ['Wherever sine of x equals zero', 'Wherever cosine of x equals zero', 'At every integer value of x with no exceptions', 'The cosecant graph never contains any asymptotes'], 0),
   ('What is the cotangent function defined as the reciprocal of?', ['The tangent function', 'The sine function', 'The cosine function', 'Cotangent has no relationship to any other trigonometric function'], 0),
   ('How does the graph of secant relate to the graph of cosine?', ['Secant has vertical asymptotes wherever cosine equals zero, and its curves open away from the x-axis near those points', 'Secant and cosine have exactly identical graphs with no differences', 'Secant is always a straight horizontal line regardless of cosine', 'Secant has vertical asymptotes wherever cosine reaches its maximum value'], 0)]),
Sc('Chemistry: Electrolysis and Electroplating',
   'Grade 9 Science strand: electrolysis uses an electric current to drive a non-spontaneous chemical reaction, and electroplating applies this process to coat a conductive object with a thin layer of metal, commonly used to prevent corrosion or improve appearance.',
   [('What does electrolysis use to drive a non-spontaneous chemical reaction?', ['An electric current supplied from an external source', 'Heat energy released from a spontaneous reaction', 'Light energy absorbed directly from the sun', 'Mechanical energy produced by a spinning turbine'], 0),
    ('What is electroplating?', ['A process that uses electrolysis to coat a conductive object with a thin layer of metal', 'A process that removes all metal coatings from an object', 'A process that has no connection to electric current of any kind', 'A process used only to melt metal objects completely'], 0),
    ('Why might a manufacturer choose to electroplate a metal object?', ['To prevent corrosion or improve the objects appearance with a thin protective or decorative layer', 'Electroplating always makes an object more likely to corrode', 'Electroplating has no practical application in manufacturing', 'Electroplating is used only to make an object heavier'], 0),
    ('How does electrolysis differ from the spontaneous redox reaction in a galvanic cell studied earlier in this course?', ['Electrolysis requires an external electrical current to force a non-spontaneous reaction, while a galvanic cell generates current from a spontaneous reaction', 'Electrolysis and a galvanic cell are exactly the same process', 'A galvanic cell always requires an external electrical current to function', 'Electrolysis never involves any redox reaction of any kind'], 0),
    ('What happens at the electrodes during electrolysis?', ['Oxidation occurs at one electrode and reduction occurs at the other, driven by the applied current', 'No chemical reaction of any kind occurs at either electrode', 'Both electrodes undergo identical reactions with no distinction between them', 'Electrolysis occurs without the use of any electrodes'], 0)]),
SS('Social Studies: The Geography of Colonial Boundaries and Their Legacy in Africa',
   'Grade 9 Social Studies (Geography) strand: many national borders in Africa were drawn by European colonial powers with limited regard for existing ethnic, linguistic, or cultural boundaries, and the resulting mismatch between political borders and cultural groups continues to influence regional conflict and cooperation today.',
   [('How were many national borders in Africa originally established?', ['They were drawn largely by European colonial powers, often with limited regard for existing ethnic or cultural boundaries', 'They were drawn entirely by African nations working together with no outside influence', 'They have remained completely unchanged since long before any colonial contact', 'They were determined only by natural physical features such as rivers and mountains'], 0),
    ('What is a common consequence of colonial-era borders cutting across existing ethnic or cultural groups?', ['Some communities were divided across multiple countries, while others were combined with groups they had little historical connection to', 'Colonial borders always perfectly matched every existing ethnic and cultural group', 'This kind of border-drawing had no lasting effect on any African nation', 'Every African country today has a population that is entirely ethnically uniform'], 0),
    ('Why do some geographers link colonial-era boundaries to modern regional conflict?', ['Borders that ignored existing cultural or ethnic divisions can contribute to tension between groups now sharing a single country', 'Colonial-era boundaries are considered entirely unrelated to any modern conflict', 'All conflicts in Africa today have origins with no connection to historical borders', 'Colonial borders always guaranteed lasting peace and cooperation between all groups'], 0),
    ('What does the term arbitrary border mean in the context of colonial map-making?', ['A border drawn without careful consideration of the people or geography actually present on the land', 'A border that was drawn only after extensive consultation with local populations', 'A border that changes automatically every year', 'A border that has never been drawn by any human decision'], 0),
    ('Why do many African governments today emphasize maintaining existing colonial-era borders despite their flaws?', ['Changing established borders could risk widespread instability, so many leaders have prioritized preserving the current boundaries', 'African governments have always preferred to redraw their borders every decade', 'Colonial-era borders are considered to have no relevance to modern governments', 'Every African border has already been completely redrawn since independence'], 0)]),
]),
day(172, [
L('Grammar: Tense Consistency and Avoiding Verb Tense Shifts',
  'Grade 9 Language strand: tense consistency means maintaining the same verb tense throughout a sentence or passage unless a genuine change in time requires a shift, since unnecessary tense shifts can confuse a reader about when events are occurring.',
  [('What does tense consistency require of a writer?', ['Maintaining the same verb tense throughout a sentence or passage unless a real change in time occurs', 'Switching verb tenses randomly throughout every paragraph', 'Using only the past tense in every sentence ever written', 'Avoiding the use of verbs entirely throughout a passage'], 0),
   ('Why can an unnecessary tense shift confuse a reader?', ['It can make it unclear when the events being described are actually taking place', 'Tense shifts always make a passage easier to understand', 'Readers never notice a change in verb tense within a passage', 'An unnecessary tense shift always clarifies the timeline of events'], 0),
   ('Which sentence contains an unnecessary tense shift?', ['She walked to the store and then buys some milk.', 'She walked to the store and then bought some milk.', 'She walks to the store and then buys some milk.', 'She will walk to the store and then will buy some milk.'], 0),
   ('When is a shift in verb tense considered appropriate within a passage?', ['When the passage genuinely moves between different points in time, such as from past events to present commentary', 'A shift in verb tense is never appropriate under any circumstances', 'Verb tense should shift only for decorative effect, with no relation to time', 'Appropriate tense shifts only occur when describing a single, unchanging moment'], 0),
   ('How might a writer revise a passage to fix inconsistent verb tenses?', ['By identifying the intended overall time frame and adjusting each verb to match it consistently', 'By removing every verb from the passage entirely', 'By changing only the nouns in the passage, leaving all verbs unchanged', 'Inconsistent verb tenses cannot be corrected through revision'], 0)]),
M('Number Theory: Wilsons Theorem',
  'Grade 9 Math strand: Wilsons Theorem states that a number p greater than 1 is prime if and only if the factorial of p minus 1, plus 1, is divisible by p, providing another tool for testing primality using modular arithmetic.',
  [('What does Wilsons Theorem state about a number p greater than 1?', ['p is prime if and only if (p minus 1) factorial plus 1 is divisible by p', 'p is always prime regardless of any factorial calculation', 'p is prime only if p is an even number', 'p is prime if and only if p is divisible by 2'], 0),
   ('What mathematical operation is central to Wilsons Theorem?', ['The factorial of p minus 1', 'The square root of p', 'The cube of p', 'The sum of the digits of p'], 0),
   ('How can Wilsons Theorem be used in practice?', ['As a test to help determine whether a given number is prime', 'As a method for calculating the area of a triangle', 'As a way to convert fractions into decimals', 'Wilsons Theorem has no practical mathematical application'], 0),
   ('How does Wilsons Theorem relate to the modular arithmetic studied earlier in this course?', ['It expresses a specific congruence condition, using factorials and modulo p, that holds precisely when p is prime', 'It has no connection whatsoever to modular arithmetic', 'It replaces the need for modular arithmetic entirely', 'It only applies when no modulus is used at all'], 0),
   ('Why might Wilsons Theorem be considered less practical than other primality tests for very large numbers?', ['Calculating a large factorial becomes computationally expensive as numbers grow larger', 'Wilsons Theorem becomes easier to compute as numbers grow larger', 'Factorials cannot be calculated for any number greater than ten', 'Wilsons Theorem only applies to numbers smaller than five'], 0)]),
Sc('Physics: Diffraction and Polarization of Light',
   'Grade 9 Science strand: diffraction occurs when light waves bend around obstacles or spread out after passing through a narrow opening, while polarization restricts the oscillation of light waves to a single plane, a property used in applications such as polarized sunglasses.',
   [('What is diffraction?', ['The bending and spreading of light waves as they pass around obstacles or through narrow openings', 'The complete absorption of light by an opaque object', 'The reflection of light directly back toward its source', 'A process that only affects sound waves, never light waves'], 0),
    ('What is polarization of light?', ['The restriction of light wave oscillations to a single plane', 'The complete blocking of all light passing through a material', 'The process by which light changes colour permanently', 'A property that applies only to sound waves, never to light'], 0),
    ('What everyday application relies on the polarization of light?', ['Polarized sunglasses, which reduce glare by blocking light oscillating in certain directions', 'Polarization has no practical everyday application', 'Standard household light bulbs, which rely entirely on polarization to produce light', 'Polarization is used exclusively in microwave ovens'], 0),
    ('Under what condition does diffraction become more noticeable?', ['When light passes through an opening comparable in size to its wavelength', 'Diffraction only occurs when light passes through extremely large openings', 'Diffraction never occurs regardless of the size of an opening', 'Diffraction is only noticeable when light is completely blocked'], 0),
    ('How does diffraction provide evidence for the wave nature of light?', ['Bending and spreading around obstacles is a behaviour characteristic of waves, not of particles travelling in straight lines', 'Diffraction proves that light behaves only as a stream of particles', 'Diffraction has no connection to whether light behaves as a wave or a particle', 'Diffraction only occurs with sound, providing no evidence about light at all'], 0)]),
SS('Social Studies: The Geography of Transboundary Rivers and Water-Sharing Conflicts',
   'Grade 9 Social Studies (Geography) strand: a transboundary river flows through or along the border of more than one country, and disputes can arise when upstream nations build dams or divert water in ways that reduce the flow available to downstream countries.',
   [('What is a transboundary river?', ['A river that flows through or along the border of more than one country', 'A river that flows entirely within the borders of a single country', 'A river that exists only underground with no surface flow', 'A term used only to describe rivers that have completely dried up'], 0),
    ('Why can upstream dam construction on a transboundary river create tension with downstream countries?', ['It can reduce the amount of water flow available to countries located further downstream', 'Upstream dams always increase water flow to downstream countries', 'Dam construction has no effect on the water available to any other country', 'Downstream countries are never affected by activity occurring upstream'], 0),
    ('What is one reason countries sharing a transboundary river might negotiate a water-sharing agreement?', ['To establish agreed rules for water use and reduce the risk of conflict over a shared resource', 'Water-sharing agreements always increase tension between countries', 'Countries sharing a river never have any reason to cooperate', 'Transboundary rivers are never subject to any international agreement'], 0),
    ('Why might a growing population increase pressure on a shared transboundary river?', ['Rising demand for drinking water, irrigation, and industry can strain the same limited water supply shared by multiple countries', 'Population growth has no effect on the demand for river water', 'A larger population always reduces the demand for water resources', 'Transboundary rivers are unaffected by the size of a countrys population'], 0),
    ('Why do geographers study transboundary rivers as part of political and physical geography?', ['They show how a shared physical resource can shape international relationships, cooperation, and conflict', 'Transboundary rivers have no connection to political geography of any kind', 'Every transboundary river in the world is governed by identical rules', 'This topic is considered purely a matter of hydrology, not geography'], 0)]),
]),
day(173, [
L('Vocabulary: Acronyms and Initialisms',
  'Grade 9 Language strand: an acronym is a word formed from the initial letters of a phrase and pronounced as a single word, such as NASA, while an initialism is formed the same way but is pronounced letter by letter, such as FBI.',
  [('What is an acronym?', ['A word formed from the initial letters of a phrase and pronounced as a single word', 'A word formed by shortening a single longer word', 'A punctuation mark used to separate two independent clauses', 'A term that applies only to words borrowed from another language'], 0),
   ('What is an initialism?', ['A term formed from the initial letters of a phrase but pronounced letter by letter rather than as a single word', 'A term that is always pronounced as a single word, never letter by letter', 'A word formed by combining two entire unrelated words', 'A word that has no connection to any longer phrase'], 0),
   ('Which of the following is an example of an acronym rather than an initialism?', ['NASA, pronounced as a single word', 'FBI, pronounced letter by letter', 'CEO, pronounced letter by letter', 'USA, pronounced letter by letter'], 0),
   ('How does an acronym differ from a clipped word, studied earlier in this course?', ['An acronym is built from the initial letters of several words, while a clipped word shortens a single existing word', 'An acronym and a clipped word are formed in exactly the same way', 'A clipped word is always built from the initial letters of several words', 'Acronyms and clipped words have no connection to shortening language at all'], 0),
   ('Why might acronyms and initialisms become common in specialized fields such as technology or government?', ['They allow long, frequently used phrases to be communicated more quickly and efficiently', 'They are always more difficult to understand than the full original phrase', 'Acronyms and initialisms are forbidden in specialized professional fields', 'They add unnecessary length to a frequently used phrase'], 0)]),
M('Statistics: An Introduction to the Central Limit Theorem',
  'Grade 9 Math strand: the central limit theorem states that as the size of random samples drawn from a population increases, the distribution of the sample means tends to approach a normal distribution, regardless of the shape of the original population distribution.',
  [('What does the central limit theorem describe?', ['As sample size increases, the distribution of sample means tends to approach a normal distribution', 'As sample size increases, the distribution of sample means always becomes less predictable', 'A single sample always perfectly represents the entire population', 'The central limit theorem applies only to populations that are already normally distributed'], 0),
   ('What is notable about the central limit theorem regarding the shape of the original population?', ['It holds true regardless of the shape of the original population distribution, given a sufficiently large sample size', 'It only applies when the original population is already perfectly normal', 'The shape of the original population has no relevance to statistics of any kind', 'It applies only to populations with exactly two possible outcomes'], 0),
   ('Why is the central limit theorem considered important in statistics?', ['It allows researchers to make reliable inferences about a population using sample means, even without knowing the populations exact distribution', 'It guarantees that every individual sample will match the population exactly', 'It has no practical application in statistical analysis', 'It only applies to extremely small sample sizes'], 0),
   ('How does increasing the sample size generally affect the distribution of sample means?', ['It causes the distribution of sample means to more closely approximate a normal, bell-shaped curve', 'It causes the distribution of sample means to become increasingly random and unpredictable', 'Sample size has no effect whatsoever on the distribution of sample means', 'Increasing sample size always produces a distribution with two separate peaks'], 0),
   ('How does the central limit theorem build on the law of large numbers studied earlier in this course?', ['Both describe how outcomes stabilize with larger samples, but the central limit theorem specifically describes the resulting shape of the sample mean distribution', 'The central limit theorem and the law of large numbers are entirely unrelated concepts', 'The law of large numbers describes only the shape of a distribution, never an average', 'The central limit theorem replaces the need for the law of large numbers entirely'], 0)]),
Sc('Biology: Neurons and Synaptic Transmission',
   'Grade 9 Science strand: a neuron is a specialized cell that transmits electrical and chemical signals throughout the nervous system, and synaptic transmission occurs when a neuron releases chemical messengers called neurotransmitters across a small gap to communicate with the next neuron or a target cell.',
   [('What is a neuron?', ['A specialized cell that transmits electrical and chemical signals throughout the nervous system', 'A cell found only in muscle tissue with no connection to the nervous system', 'A type of blood cell responsible for carrying oxygen', 'A structure found only in plants, never in animals'], 0),
    ('What is synaptic transmission?', ['The process by which a neuron releases neurotransmitters across a small gap to communicate with another cell', 'The process by which a neuron absorbs nutrients from the bloodstream', 'A process that occurs only within the digestive system', 'The complete destruction of a neuron following an electrical signal'], 0),
    ('What are neurotransmitters?', ['Chemical messengers released by a neuron to communicate with the next neuron or a target cell', 'Structural proteins that make up the outer covering of a bone', 'Molecules used exclusively to digest food in the stomach', 'A type of neuron found only in the eye'], 0),
    ('What is the small gap between two neurons called, across which neurotransmitters travel?', ['A synapse', 'A ventricle', 'An alveolus', 'A follicle'], 0),
    ('Why is synaptic transmission essential for the functioning of the nervous system?', ['It allows signals to pass from one neuron to the next, enabling coordinated communication throughout the body', 'Synaptic transmission prevents any communication from occurring between neurons', 'It has no role in how the nervous system communicates', 'Synaptic transmission only occurs after the nervous system has stopped functioning'], 0)]),
SS('Social Studies: The Geography of Fair Trade and Ethical Sourcing',
   'Grade 9 Social Studies (Geography) strand: fair trade is a certification and trading model that aims to ensure producers, particularly in developing regions, receive a fair price and safe working conditions for goods such as coffee, cocoa, and textiles sold in global markets.',
   [('What is the main goal of the fair trade model?', ['To ensure producers receive a fair price and safe working conditions for the goods they sell in global markets', 'To guarantee that producers receive the lowest possible price for their goods', 'To eliminate all forms of international trade completely', 'Fair trade has no connection to the price paid to producers'], 0),
    ('Which types of products are commonly associated with fair trade certification?', ['Coffee, cocoa, and textiles', 'Products that are never traded internationally', 'Only products manufactured entirely within a single wealthy country', 'Products that have no connection to agriculture or manufacturing'], 0),
    ('Why might fair trade certification be particularly relevant to producers in developing regions?', ['It can help protect them from unfairly low prices and poor working conditions often linked to global supply chains', 'Fair trade certification only benefits producers in wealthy, developed countries', 'Producers in developing regions are never affected by global market prices', 'Fair trade certification guarantees a producer will receive no payment at all'], 0),
    ('What is meant by ethical sourcing in the context of global trade?', ['Choosing to obtain goods from suppliers that meet certain labour, environmental, or social standards', 'Sourcing goods only from suppliers with the lowest possible production costs', 'A term with no connection to labour or environmental standards', 'A practice that applies only to goods produced within a single country'], 0),
    ('Why might a consumer choose to pay a premium for a fair trade certified product?', ['To support fairer wages and working conditions for the producers who grew or made the product', 'Fair trade products are always identical in price to non-certified products', 'Consumers who choose fair trade products receive no benefit of any kind', 'Fair trade certification guarantees a lower price than any other product'], 0)]),
]),
day(174, [
L('Reading: Analyzing Red Herrings and Misdirection in Plot',
  'Grade 9 Language strand: a red herring is a clue or detail deliberately placed in a narrative to mislead readers away from the true solution or outcome, a technique especially common in mystery and suspense writing.',
  [('What is a red herring in a narrative?', ['A clue or detail deliberately placed to mislead readers away from the true solution or outcome', 'A character who always tells the reader the complete truth', 'A detail that has no purpose within the structure of a story', 'A setting description with no connection to the plot'], 0),
   ('In which genre is the use of red herrings especially common?', ['Mystery and suspense writing', 'Instructional and technical writing', 'Recipe writing', 'Weather reporting'], 0),
   ('Why might an author include a red herring in a story?', ['To create suspense by leading readers toward an incorrect conclusion before the true outcome is revealed', 'To make the plot immediately obvious to every reader', 'Red herrings are included only by accident, never intentionally', 'To remove all tension and surprise from a narrative'], 0),
   ('How does a red herring typically function in relation to the true solution of a mystery?', ['It distracts attention away from the true solution, at least temporarily', 'It always reveals the true solution immediately to the reader', 'A red herring and the true solution are always identical', 'Red herrings have no relationship to a storys eventual solution'], 0),
   ('Why might readers feel satisfied when they look back and notice a red herring after finishing a mystery?', ['They can appreciate how the author carefully planted misleading details that still fit logically within the story', 'Red herrings always make a mystery feel poorly constructed', 'Readers never notice a red herring, even after finishing a story', 'A satisfying mystery never includes a single misleading detail'], 0)]),
M('Financial Literacy: Payday Loans and the Cost of Predatory Lending',
  'Grade 9 Math strand: a payday loan is a short-term, high-interest loan intended to be repaid by a borrowers next paycheque, and the very high fees and interest rates associated with these loans can trap borrowers in a cycle of repeated borrowing, a practice often described as predatory lending.',
  [('What is a payday loan?', ['A short-term, high-interest loan intended to be repaid by a borrowers next paycheque', 'A long-term, low-interest loan intended to fund the purchase of a home', 'A type of loan that always charges no interest of any kind', 'A government benefit paid automatically to every worker'], 0),
   ('What is a common criticism of payday loans?', ['Their very high fees and interest rates can trap borrowers in a cycle of repeated borrowing', 'Payday loans always charge lower interest rates than a standard bank loan', 'Payday loans are never associated with any financial risk', 'Payday loans are only available to borrowers with substantial savings'], 0),
   ('What does the term predatory lending generally describe?', ['Lending practices that impose unfair or excessive costs on borrowers, often those with limited alternatives', 'A lending practice that always benefits the borrower more than the lender', 'A term with no connection to interest rates or lending practices', 'A type of loan available only to large corporations'], 0),
   ('Why might someone with limited access to traditional credit turn to a payday loan despite its high cost?', ['They may need cash quickly and have few other borrowing options available to them', 'Payday loans are always the cheapest borrowing option available to any consumer', 'People with strong credit histories are the only ones who use payday loans', 'Payday loans are never used to cover an urgent, short-term expense'], 0),
   ('What financial habit can help someone avoid relying on high-cost short-term loans like payday loans?', ['Building an emergency savings fund to cover unexpected expenses', 'Avoiding all forms of saving in order to spend every paycheque immediately', 'Emergency savings have no effect on a persons need for a payday loan', 'Relying exclusively on payday loans for every unexpected expense'], 0)]),
Sc('Earth Science: Aurora and the Interaction of Solar Wind with the Atmosphere',
   'Grade 9 Science strand: an aurora is a natural light display that occurs when charged particles from the solar wind interact with gases in Earths upper atmosphere near the polar regions, and Earths magnetic field channels these particles toward the poles, producing the shifting colours seen in the night sky.',
   [('What is an aurora?', ['A natural light display caused by charged particles from the solar wind interacting with gases in Earths upper atmosphere', 'A type of cloud formation seen only during a thunderstorm', 'A phenomenon that occurs only on the surface of the Moon', 'A light display produced entirely by artificial sources'], 0),
    ('What role does Earths magnetic field play in the formation of an aurora?', ['It channels charged particles from the solar wind toward the polar regions', 'It completely blocks all charged particles from reaching Earths atmosphere', 'Earths magnetic field has no connection to the formation of an aurora', 'It pushes charged particles away from the poles toward the equator'], 0),
    ('Why are auroras most commonly observed near the polar regions?', ['Earths magnetic field lines converge near the poles, funnelling charged particles into the atmosphere there', 'Auroras occur with equal frequency at every latitude on Earth', 'Charged particles from the solar wind are only present near the equator', 'Polar regions receive no charged particles from the solar wind'], 0),
    ('What produces the different colours seen during an aurora display?', ['Charged particles colliding with different gases in the atmosphere at different altitudes', 'The colours of an aurora are produced entirely by reflected moonlight', 'Aurora colours have no connection to the gases present in the atmosphere', 'Every aurora display produces exactly the same single colour'], 0),
    ('How does the study of auroras connect to the earlier study of Earths magnetic field in this course?', ['Both topics involve understanding how Earths magnetic field interacts with charged particles from space', 'Auroras and Earths magnetic field are entirely unrelated topics', 'Earths magnetic field has no measurable effect on the atmosphere', 'Auroras occur independently of any magnetic field, on Earth or elsewhere'], 0)]),
SS('Social Studies: The Geography of Illegal Wildlife Trade and Poaching Hotspots',
   'Grade 9 Social Studies (Geography) strand: the illegal wildlife trade involves the poaching and trafficking of protected animal species and their parts, often driven by demand in distant markets, and certain regions with high biodiversity face particular pressure as poaching hotspots.',
   [('What does the illegal wildlife trade involve?', ['The poaching and trafficking of protected animal species and their parts', 'The legal, regulated sale of farmed livestock within a single country', 'A trade that has no connection to protected or endangered species', 'A form of trade that occurs only with the full approval of international law'], 0),
    ('What often drives demand for products from the illegal wildlife trade?', ['Demand in distant markets for items such as ivory, exotic pets, or traditional medicine ingredients', 'The illegal wildlife trade has no connection to any market demand', 'Demand for illegally traded wildlife products has never existed anywhere', 'Illegal wildlife products are demanded only within the country where the animal lives'], 0),
    ('What is a poaching hotspot?', ['A region with high biodiversity that faces particular pressure from illegal hunting of protected species', 'A region where wildlife populations are completely unaffected by human activity', 'An area where all wildlife poaching has been permanently eliminated', 'A term used only to describe regions with no wildlife of any kind'], 0),
    ('Why can the illegal wildlife trade threaten biodiversity in affected regions?', ['Overhunting protected species can push already vulnerable populations closer to extinction', 'The illegal wildlife trade always increases the population of every affected species', 'Illegal wildlife trade has no measurable effect on any species population', 'Biodiversity is never affected by the hunting of a single species'], 0),
    ('What approach do many governments and conservation groups use to try to reduce illegal wildlife trade?', ['Combining law enforcement, international cooperation, and community-based conservation programs', 'Illegal wildlife trade is addressed only by increasing demand for wildlife products', 'No government or organization has ever attempted to address illegal wildlife trade', 'Community-based conservation programs have no role in protecting wildlife'], 0)]),
]),
day(175, [
L('Writing: Writing a Memoir Excerpt',
  'Grade 9 Language strand: a memoir excerpt is a short piece of personal narrative writing that focuses on a specific memory or period in the writers life, using vivid sensory detail and reflection to convey the personal significance of the experience.',
  [('What does a memoir excerpt typically focus on?', ['A specific memory or period in the writers own life', 'A completely fictional event with no connection to the writer', 'A biography written entirely about another persons life', 'A set of instructions for completing a specific task'], 0),
   ('What kind of detail is especially valued in memoir writing?', ['Vivid sensory detail that helps a reader experience the memory alongside the writer', 'Vague, general statements with no specific sensory description', 'Only statistical data with no personal reflection', 'Details about a completely unrelated event'], 0),
   ('Why does a memoir typically include the writers reflection on an experience, not just a description of events?', ['Reflection helps convey why the experience mattered and what the writer learned or felt about it', 'Reflection is always considered unnecessary in memoir writing', 'A memoir must never include the writers own thoughts or feelings', 'Reflection has no connection to the personal significance of an experience'], 0),
   ('How does a memoir excerpt differ from a full autobiography?', ['A memoir excerpt focuses on a specific memory or period, while an autobiography typically covers the writers entire life', 'A memoir excerpt and an autobiography are exactly the same length and scope', 'An autobiography focuses on a single memory, while a memoir excerpt covers an entire life', 'There is no meaningful difference between these two forms of writing'], 0),
   ('Why might a writer choose first-person point of view when writing a memoir excerpt?', ['First-person point of view allows the writer to share their own direct perspective and personal voice', 'First-person point of view is forbidden in memoir writing', 'A memoir must always be written from the point of view of an unrelated narrator', 'First-person point of view removes all personal perspective from a narrative'], 0)]),
M('Geometry: The Scalar Triple Product and Volume of a Parallelepiped',
  'Grade 9 Math strand: the scalar triple product combines three vectors using a cross product followed by a dot product to produce a single scalar value, and the absolute value of this result equals the volume of the parallelepiped formed by the three vectors.',
  [('What does the scalar triple product of three vectors combine?', ['A cross product followed by a dot product, producing a single scalar value', 'Three separate dot products added together', 'A single vector multiplied by a scalar constant only', 'The scalar triple product involves no vector operations at all'], 0),
   ('What geometric shape is formed by three vectors used in a scalar triple product?', ['A parallelepiped', 'A perfect sphere', 'A flat, two-dimensional triangle', 'A single straight line segment'], 0),
   ('What does the absolute value of the scalar triple product represent?', ['The volume of the parallelepiped formed by the three vectors', 'The surface area of the parallelepiped formed by the three vectors', 'The length of a single edge of the parallelepiped', 'The scalar triple product has no geometric meaning of any kind'], 0),
   ('What does it mean if the scalar triple product of three vectors equals zero?', ['The three vectors are coplanar, meaning they all lie within the same plane', 'The three vectors are always perpendicular to each other', 'The three vectors form a parallelepiped with maximum possible volume', 'A scalar triple product can never equal zero under any circumstances'], 0),
   ('How does the scalar triple product build on the cross product and dot product studied earlier in this course?', ['It combines both operations in sequence to produce a single scalar describing a three-dimensional volume', 'The scalar triple product has no connection to either the cross product or the dot product', 'It replaces the need for both the cross product and dot product entirely', 'The scalar triple product only applies to two-dimensional vectors'], 0)]),
Sc('Astronomy: Keplers Laws of Planetary Motion',
   'Grade 9 Science strand: Keplers Laws describe the motion of planets around the sun, establishing that planetary orbits are elliptical, that a planet sweeps out equal areas in equal times, and that there is a mathematical relationship between a planets orbital period and its distance from the sun.',
   [('According to Keplers first law, what shape do planetary orbits follow?', ['An ellipse, with the sun located at one focus', 'A perfect circle, with the sun located at its exact centre', 'A straight line directly toward the sun', 'Planetary orbits follow no consistent geometric shape'], 0),
    ('What does Keplers second law state about a planets motion around the sun?', ['A planet sweeps out equal areas in equal amounts of time', 'A planet always moves at exactly the same speed throughout its entire orbit', 'A planet sweeps out increasingly larger areas as time passes at a constant rate', 'Keplers second law describes only the colour of a planets surface'], 0),
    ('What does Keplers third law relate to each other?', ['A planets orbital period and its average distance from the sun', 'A planets mass and its surface temperature', 'A planets colour and its distance from Earth', 'Keplers third law describes no mathematical relationship at all'], 0),
    ('According to Keplers second law, when does a planet move fastest in its orbit?', ['When it is closest to the sun', 'When it is farthest from the sun', 'A planets speed never changes at any point in its orbit', 'When it is exactly halfway between its closest and farthest points'], 0),
    ('How did Keplers Laws contribute to later developments in physics, such as Newtons work on gravity?', ['They provided a precise mathematical description of planetary motion that later theories of gravity needed to explain', 'Keplers Laws had no influence on any later scientific development', 'Keplers Laws were developed after Newtons laws and simply restated them', 'Keplers Laws describe only the motion of stars, not planets'], 0)]),
SS('Social Studies: The Geography of Salt Production and Historic Salt Trade Routes',
   'Grade 9 Social Studies (Geography) strand: salt has historically been a valuable commodity essential for food preservation, and regions with access to salt deposits, salt flats, or coastal salt evaporation sites often developed important trade routes and settlements built around its production and distribution.',
   [('Why was salt historically such a valuable commodity?', ['It was essential for preserving food before the widespread use of refrigeration', 'Salt had no practical use in any historical society', 'Salt was valued only for its use in construction materials', 'Salt has always been the least valuable resource traded historically'], 0),
    ('What are some common natural sources of salt used in historic salt production?', ['Salt deposits, salt flats, and coastal salt evaporation sites', 'Salt can only be produced through modern industrial chemical processes', 'Salt has no natural sources and must always be manufactured artificially', 'Salt is found only deep within tropical rainforests'], 0),
    ('How did access to salt resources influence the location of some historic trade routes and settlements?', ['Regions with valuable salt deposits often became centres of production and trade, attracting settlement and route development', 'Salt resources had no influence on the location of any historic settlement', 'Trade routes were never built to transport salt of any kind', 'Settlements only formed in regions with no access to salt resources'], 0),
    ('Why might salt have been used historically as a form of currency or valuable trade good?', ['Its necessity for food preservation and scarcity in some regions gave it significant and stable value', 'Salt has always been so abundant everywhere that it held no trade value', 'Salt could never be transported over long distances in the past', 'Salt was valued only for decorative, not practical, purposes'], 0),
    ('Why do geographers study historic resources like salt as part of economic geography?', ['They show how the physical distribution of a valuable resource can shape trade networks, settlement patterns, and regional economies', 'Historic salt production has no connection to the study of geography', 'Trade routes have never been influenced by the location of natural resources', 'This topic is considered purely a matter of chemistry, not geography'], 0)]),
]),
day(176, [
L('Grammar: Double Negatives and Negation in Standard English',
  'Grade 9 Language strand: a double negative occurs when two negative words are used in the same clause, which in Standard English typically creates a confusing or grammatically incorrect statement, even though double negatives are accepted in some dialects and used deliberately in certain styles for emphasis.',
  [('What is a double negative?', ['The use of two negative words within the same clause', 'A sentence that contains no negative words of any kind', 'A punctuation mark used to indicate a strong negative statement', 'A grammatical structure that always makes a sentence perfectly clear'], 0),
   ('In Standard English, how is a double negative generally regarded?', ['As a construction that is typically considered confusing or grammatically incorrect', 'As the only grammatically correct way to express a negative idea', 'As a construction that is always required in formal writing', 'Double negatives are never used or discussed in Standard English'], 0),
   ('Which of the following sentences contains a double negative?', ['I do not have no time for this today.', 'I do not have time for this today.', 'I have no time for this today.', 'I have plenty of time for this today.'], 0),
   ('Why are double negatives sometimes accepted or used deliberately in certain dialects or styles?', ['They can serve as a recognized feature of a dialect or be used intentionally for stylistic emphasis', 'Double negatives are always considered incorrect in every dialect and style', 'Double negatives have no recognized use in any form of English', 'Every dialect of English strictly forbids the use of any negative word'], 0),
   ('How might a writer revise the sentence I dont have no time to follow Standard English conventions?', ['I do not have time, removing the second negative word', 'I dont have some time, keeping both negative words in place', 'I have no not time, adding a third negative word', 'The original sentence already follows every Standard English convention'], 0)]),
M('Data Management: The Inclusion-Exclusion Principle',
  'Grade 9 Math strand: the inclusion-exclusion principle is a counting method used to find the size of the union of two or more overlapping sets by adding the sizes of the individual sets and then subtracting the size of their overlap, avoiding the mistake of counting shared elements more than once.',
  [('What does the inclusion-exclusion principle help calculate?', ['The size of the union of two or more overlapping sets', 'The average value of a single data set', 'The probability of a single independent event', 'The inclusion-exclusion principle has no connection to counting sets'], 0),
   ('For two overlapping sets, what must be subtracted after adding their individual sizes?', ['The size of their overlap, so shared elements are not counted twice', 'The size of a completely unrelated third set', 'Nothing needs to be subtracted under any circumstances', 'The total size of the union itself'], 0),
   ('Why is it necessary to subtract the overlap when finding the size of a union of two sets?', ['Elements that belong to both sets would otherwise be counted twice, leading to an inflated total', 'Subtracting the overlap always produces an artificially small result with no meaning', 'Overlapping elements should always be counted as many times as possible', 'Two sets can never have any elements in common'], 0),
   ('How does the inclusion-exclusion principle change when three overlapping sets are involved instead of two?', ['Additional terms must be added and subtracted to correctly account for pairs of overlaps and the overlap shared by all three sets', 'The calculation remains exactly the same regardless of the number of sets involved', 'Only one of the three sets needs to be considered at all', 'The inclusion-exclusion principle cannot be applied to more than two sets'], 0),
   ('How does the inclusion-exclusion principle connect to the study of sets and Venn diagrams earlier in this course?', ['It provides a precise formula for counting elements in regions of a Venn diagram where sets overlap', 'It has no connection whatsoever to sets or Venn diagrams', 'It replaces the need to understand sets or Venn diagrams entirely', 'The inclusion-exclusion principle only applies to diagrams with no overlapping regions'], 0)]),
Sc('Chemistry: Water Purification and Treatment Chemistry',
   'Grade 9 Science strand: water treatment uses a combination of physical and chemical processes, including filtration, coagulation, and disinfection with substances such as chlorine, to remove contaminants and pathogens from water before it is considered safe for drinking.',
   [('What is the general goal of water treatment?', ['To remove contaminants and pathogens from water before it is considered safe for drinking', 'To add as many contaminants to water as possible', 'Water treatment has no connection to making water safer to drink', 'To permanently remove all minerals from every water source'], 0),
    ('What is coagulation in the context of water treatment?', ['A process that causes small suspended particles to clump together so they can be more easily removed', 'A process that dissolves all solid particles completely, making them undetectable', 'A process used only to add colour to treated water', 'Coagulation has no role in any water treatment process'], 0),
    ('Why is chlorine commonly added during water treatment?', ['To disinfect water by killing or inactivating harmful pathogens', 'To make water taste sweeter without affecting safety', 'Chlorine is added only to change the colour of treated water', 'Chlorine has no effect on pathogens present in water'], 0),
    ('What role does filtration play in the water treatment process?', ['It physically removes suspended particles and some microorganisms as water passes through a filtering material', 'Filtration adds additional contaminants back into the water supply', 'Filtration has no effect on the particles present in water', 'Filtration is used only to make water colder'], 0),
    ('Why is it important to treat water even when it appears visibly clear?', ['Water can contain invisible pathogens or dissolved contaminants that pose health risks despite appearing clean', 'Visibly clear water is always guaranteed to be completely safe to drink', 'Appearance is the only factor that determines whether water is safe', 'Invisible contaminants have never been found in any water source'], 0)]),
SS('Social Studies: The Geography of Global Courier and Logistics Networks',
   'Grade 9 Social Studies (Geography) strand: global courier and logistics networks move goods efficiently between producers and consumers using a combination of air, sea, rail, and road transportation, with hub cities and major distribution centres playing a central role in coordinating the flow of shipments worldwide.',
   [('What is the main purpose of global courier and logistics networks?', ['To move goods efficiently between producers and consumers using multiple forms of transportation', 'To prevent goods from ever being transported between different countries', 'Logistics networks exist only to transport passengers, never goods', 'To ensure that every shipment travels using exactly one mode of transportation only'], 0),
    ('What role do hub cities typically play in global logistics networks?', ['They serve as central locations for coordinating and redirecting the flow of shipments', 'Hub cities have no role in coordinating the movement of goods', 'Hub cities exist only to store goods permanently with no further shipment', 'Every shipment must avoid passing through any hub city'], 0),
    ('Which combination of transportation modes is commonly used within global logistics networks?', ['Air, sea, rail, and road transportation', 'Only a single mode of transportation is ever used for any shipment', 'Logistics networks rely exclusively on foot courier delivery', 'Air and rail transportation are never used together in the same network'], 0),
    ('Why might a company use air freight for some shipments despite its higher cost compared to sea freight?', ['Air freight is much faster, making it valuable for urgent or time-sensitive shipments', 'Air freight is always slower than sea freight for every type of shipment', 'Air freight always costs less than every other form of transportation', 'Companies never consider shipment speed when choosing a transportation method'], 0),
    ('Why do geographers study global courier and logistics networks as part of economic geography?', ['They reveal how transportation infrastructure and hub locations shape the efficient movement of goods across the world', 'Logistics networks have no connection to the study of economic geography', 'Every logistics network in the world operates in an identical way', 'This topic is considered purely a matter of business management, not geography'], 0)]),
]),
day(177, [
L('Vocabulary: Homophones and Homographs',
  'Grade 9 Language strand: homophones are words that sound identical but differ in spelling and meaning, such as their and there, while homographs are words that share the same spelling but differ in meaning and sometimes pronunciation, such as the noun and verb forms of the word tear.',
  [('What is a homophone?', ['A word that sounds identical to another word but differs in spelling and meaning', 'A word that is spelled identically to another word but has a completely different sound', 'A word that has only one possible meaning in every context', 'A punctuation mark used to separate two related clauses'], 0),
   ('What is a homograph?', ['A word that shares the same spelling as another word but differs in meaning, and sometimes pronunciation', 'A word that sounds identical to another word but is always spelled differently', 'A word that has no relationship to any other word in the language', 'A term used only to describe words borrowed from another language'], 0),
   ('Which of the following pairs is an example of homophones?', ['Their and there', 'Tear (to rip) and tear (a drop from crying)', 'Bank (a financial institution) and bank (the side of a river)', 'Lead (a metal) and lead (to guide)'], 0),
   ('Why can homophones create challenges for writers, particularly with spelling?', ['Since the words sound the same, a writer might choose the wrong spelling for the intended meaning', 'Homophones never cause any confusion in written English', 'Homophones are always spelled identically, removing any risk of error', 'Homophones only exist in spoken language, never in writing'], 0),
   ('How does a homograph like the word tear demonstrate the importance of context in reading?', ['The surrounding words and sentence help the reader determine which meaning and pronunciation is intended', 'Context has no effect on how a homograph should be interpreted', 'A homograph always has exactly one meaning regardless of context', 'Homographs are pronounced identically in absolutely every context'], 0)]),
M('Calculus Preview: Optimization Using Derivatives',
  'Grade 9 Math strand: optimization problems use derivatives to find the maximum or minimum value of a function by locating points where the derivative equals zero or is undefined, then testing those critical points to determine whether they represent the best possible outcome within given constraints.',
  [('What is the goal of an optimization problem in calculus?', ['To find the maximum or minimum value of a function, often within given constraints', 'To find every possible value a function could ever produce', 'To determine the exact colour of a functions graph', 'Optimization problems have no defined goal of any kind'], 0),
   ('What condition is typically true of the derivative at a critical point where a maximum or minimum may occur?', ['The derivative equals zero or is undefined at that point', 'The derivative is always a very large positive number at that point', 'The derivative can never equal zero at any point on a function', 'Critical points have no relationship to the value of the derivative'], 0),
   ('After finding a critical point, what must be done to confirm whether it represents a maximum or a minimum?', ['Test the critical point, often using the sign of the derivative or second derivative nearby', 'No further testing is ever required after finding a critical point', 'Critical points are always automatically maximum values with no further testing', 'The value of the function at a critical point is always irrelevant'], 0),
   ('Why are optimization problems useful in real-world applications, such as business or engineering?', ['They help identify the most efficient or profitable choice within a set of practical constraints', 'Optimization problems have no real-world applications of any kind', 'They are used only to calculate the area of abstract geometric shapes', 'Optimization problems always ignore any practical constraints'], 0),
   ('How does optimization build on the concept of concavity studied earlier in this course?', ['The concavity of a function, determined by the second derivative, helps confirm whether a critical point is a maximum or a minimum', 'Optimization has no connection whatsoever to the concept of concavity', 'Concavity is used only to calculate a functions domain, not its extreme values', 'Optimization problems can only be solved without any reference to concavity'], 0)]),
Sc('Physics: Entropy and the Second Law of Thermodynamics',
   'Grade 9 Science strand: entropy is a measure of the disorder or randomness within a system, and the second law of thermodynamics states that the total entropy of an isolated system tends to increase over time, explaining why natural processes tend to move toward greater disorder unless energy is added.',
   [('What does entropy measure within a system?', ['The degree of disorder or randomness within the system', 'The exact temperature of a system at a single moment', 'The total mass contained within a system', 'Entropy has no measurable meaning in physics'], 0),
    ('What does the second law of thermodynamics state about the entropy of an isolated system?', ['The total entropy of an isolated system tends to increase over time', 'The total entropy of an isolated system always decreases over time', 'Entropy always remains exactly constant in every isolated system', 'The second law of thermodynamics makes no statement about entropy'], 0),
    ('According to the second law of thermodynamics, in what general direction do natural processes tend to move?', ['Toward greater disorder, unless energy is added to the system', 'Toward perfect order, with no additional energy required', 'Natural processes never move in any consistent direction', 'Toward a state of zero entropy in every case'], 0),
    ('Which everyday example illustrates an increase in entropy?', ['An ice cube melting into a puddle of water at room temperature', 'Water freezing spontaneously into a perfectly ordered ice cube with no outside cooling', 'A messy room spontaneously becoming perfectly organized with no outside effort', 'Entropy cannot be illustrated using any everyday example'], 0),
    ('How does the second law of thermodynamics help explain why some processes are considered irreversible?', ['Reversing certain processes would require a spontaneous decrease in the entropy of an isolated system, which the law states does not occur', 'All natural processes are equally easy to reverse without any additional energy', 'The second law of thermodynamics has no connection to whether a process can be reversed', 'Irreversible processes always involve a decrease in total entropy'], 0)]),
SS('Social Studies: The Geography of Transboundary Air Pollution and Regional Haze',
   'Grade 9 Social Studies (Geography) strand: transboundary air pollution occurs when pollutants such as smoke or industrial emissions produced in one country travel across borders and affect air quality in neighbouring regions, often creating a persistent regional haze that can strain diplomatic relations between affected countries.',
   [('What is transboundary air pollution?', ['Air pollution produced in one country that travels across borders and affects air quality in neighbouring regions', 'Air pollution that remains permanently confined within the borders of a single country', 'A term used only to describe pollution that occurs over open ocean', 'Air pollution that has no connection to international borders of any kind'], 0),
    ('What is one common source of pollutants that can contribute to transboundary regional haze?', ['Large-scale agricultural or forest burning and industrial emissions', 'Transboundary haze is caused entirely by natural volcanic activity alone', 'Regional haze has no connection to any human activity', 'Haze is produced only by activities occurring at sea'], 0),
    ('Why can transboundary air pollution create diplomatic tension between neighbouring countries?', ['A country affected by haze originating elsewhere may have limited direct control over reducing the pollution at its source', 'Transboundary air pollution never affects relations between neighbouring countries', 'Every country responsible for producing haze willingly stops the activity immediately', 'Diplomatic tension only arises from issues unrelated to air quality'], 0),
    ('What health effects can prolonged exposure to regional haze have on affected populations?', ['Respiratory and other health problems linked to poor air quality', 'Regional haze has no effect on human health of any kind', 'Haze always improves air quality in the regions it reaches', 'Health effects from haze are limited only to the country where it originated'], 0),
    ('Why might regional cooperation agreements be developed to address transboundary haze?', ['Coordinated action across borders can be more effective at reducing the sources and impact of shared air pollution than efforts by a single country alone', 'Regional cooperation has no effect on reducing transboundary air pollution', 'Countries affected by haze are legally forbidden from cooperating with one another', 'A single country acting alone is always more effective than regional cooperation'], 0)]),
]),
day(178, [
L('Reading: Analyzing Exposition and Rising Action in Plot Structure',
  'Grade 9 Language strand: exposition is the opening stage of a plot that introduces the characters, setting, and initial situation, while rising action consists of the connected events that build tension and develop the central conflict on the way toward the storys climax.',
  [('What does the exposition of a plot typically introduce?', ['The characters, setting, and initial situation of the story', 'The final resolution of every conflict in the story', 'A summary of unrelated events happening in another narrative', 'Only the ending of the story, with no earlier context'], 0),
   ('What is the purpose of the rising action in a plot?', ['To build tension and develop the central conflict on the way toward the climax', 'To resolve the central conflict immediately after it is introduced', 'Rising action has no connection to a storys central conflict', 'To gradually reduce tension until the story reaches its exposition'], 0),
   ('In what order do exposition and rising action typically occur within a traditional plot structure?', ['Exposition occurs first, followed by the rising action', 'Rising action always occurs before the exposition', 'Exposition and rising action always occur at exactly the same time', 'A traditional plot structure never includes both exposition and rising action'], 0),
   ('How does the rising action typically relate to the storys eventual climax?', ['The events of the rising action build toward and lead directly into the climax', 'The rising action has no connection to the climax of a story', 'The climax always occurs before any rising action takes place', 'Rising action and climax are always identical stages of a plot'], 0),
   ('Why is a clear exposition important for a reader following a story?', ['It establishes the necessary context a reader needs to understand later events and rising tension', 'A clear exposition always makes a story less understandable', 'Exposition provides no useful information to a reader', 'Readers never need any context about characters or setting'], 0)]),
M('Geometry: The Angle Between Two Planes Using Normal Vectors',
  'Grade 9 Math strand: the angle between two planes in three-dimensional space can be found by calculating the angle between their normal vectors using the dot product formula, since the orientation of a plane is fully determined by the direction of the vector perpendicular to it.',
  [('What vectors are used to calculate the angle between two planes?', ['The normal vectors of the two planes', 'Two direction vectors that lie flat within a single plane', 'A single vector with no defined direction', 'The angle between two planes cannot be calculated using vectors'], 0),
   ('What mathematical operation is used to find the angle between two normal vectors?', ['The dot product formula', 'Simple addition of the two vectors', 'Division of one vector by the other', 'No mathematical operation can relate two normal vectors'], 0),
   ('Why does the orientation of a plane depend directly on its normal vector?', ['The normal vector is perpendicular to every line within the plane, fully determining the planes tilt in space', 'The normal vector lies flat within the plane and has no connection to its orientation', 'A plane has no defined orientation in three-dimensional space', 'Every plane shares an identical, fixed orientation regardless of its normal vector'], 0),
   ('If the normal vectors of two planes are parallel, what can be concluded about the planes themselves?', ['The planes are parallel to each other', 'The planes must always intersect at a single point', 'The planes are necessarily perpendicular to each other', 'Nothing can be concluded about the relationship between the planes'], 0),
   ('How does finding the angle between two planes build on the study of normal vectors and vector equations of planes earlier in this course?', ['It applies the same normal vector concept, using the dot product to measure the angular relationship between two planes', 'This method has no connection to normal vectors or vector equations of planes', 'The angle between two planes can only be found without using any normal vector', 'This method replaces the need to understand normal vectors entirely'], 0)]),
Sc('Biology: Animal Migration and Navigation',
   'Grade 9 Science strand: animal migration is the seasonal movement of a species between different regions, often to find food, breeding grounds, or more favourable climate conditions, and many migratory species navigate using cues such as the position of the sun, Earths magnetic field, or landmarks.',
   [('What is animal migration?', ['The seasonal movement of a species between different regions', 'A permanent relocation that an animal never repeats', 'A behaviour that occurs only within a single, fixed location', 'Animal migration describes a change in an animals diet only'], 0),
    ('What is a common reason species migrate seasonally?', ['To find food, breeding grounds, or more favourable climate conditions', 'Migration never provides any survival advantage to a species', 'Species migrate only to avoid other members of their own species', 'Migration occurs randomly with no connection to survival needs'], 0),
    ('Which of the following is a cue some migratory species use for navigation?', ['Earths magnetic field', 'The migrating animals own body temperature', 'The migrating animals sense of taste', 'Migratory species never rely on any external cue for navigation'], 0),
    ('How might the position of the sun help a migrating animal navigate?', ['Some species use the suns position in the sky as a reference point to maintain a consistent direction of travel', 'The suns position has no connection to how any animal navigates', 'The sun is used only to help animals regulate their body temperature', 'Migrating animals avoid all sunlight throughout their entire journey'], 0),
    ('Why might climate change pose a challenge to species that rely on long-distance seasonal migration?', ['Shifting temperatures and changing conditions along migration routes can disrupt the timing and availability of food or breeding grounds', 'Climate change has no effect on any migratory species', 'Migration routes are entirely unaffected by changes in climate', 'Migratory species are guaranteed to adapt instantly to any environmental change'], 0)]),
SS('Social Studies: The Geography of Urban Waterfront Redevelopment',
   'Grade 9 Social Studies (Geography) strand: urban waterfront redevelopment transforms formerly industrial harbour, dock, or riverfront land into new residential, commercial, or public spaces, often revitalizing a citys economy while raising questions about affordability and access for long-time residents.',
   [('What does urban waterfront redevelopment typically involve?', ['Transforming formerly industrial harbour, dock, or riverfront land into new residential, commercial, or public spaces', 'Converting residential neighbourhoods into new industrial harbour facilities', 'Waterfront redevelopment never involves any change to how land is used', 'Removing all public access to a citys waterfront permanently'], 0),
    ('What economic benefit can waterfront redevelopment bring to a city?', ['New investment, businesses, and jobs that can help revitalize a citys economy', 'Waterfront redevelopment always eliminates every economic benefit to a city', 'Cities never experience any economic change from redevelopment projects', 'Redevelopment guarantees the permanent closure of all nearby businesses'], 0),
    ('What concern is commonly raised by long-time residents when a waterfront area is redeveloped?', ['Rising property values and living costs that may make the area less affordable for existing residents', 'Long-time residents are never affected by redevelopment of any kind', 'Redevelopment always lowers the cost of living for every resident', 'Waterfront redevelopment has no connection to housing affordability'], 0),
    ('Why might former industrial waterfront land be particularly attractive for redevelopment?', ['Its central location and scenic access to water can make it valuable for new residential or commercial use once industrial activity declines', 'Former industrial land is always considered worthless for any future use', 'Waterfront land has no appeal for residential or commercial development', 'Industrial areas can never be redeveloped for a different purpose'], 0),
    ('Why do many redevelopment projects include new public parks or walkways along a citys waterfront?', ['To create shared public space that gives a wider range of residents access to the waterfront, not just new property owners', 'Public parks and walkways are never included in waterfront redevelopment projects', 'Public space along a waterfront always reduces a citys overall property values', 'Redevelopment projects are legally forbidden from including any public spaces'], 0)]),
]),
day(179, [
L('Writing: Writing a Press Release',
  'Grade 9 Language strand: a press release is a concise, factual document written to announce newsworthy information to media outlets, typically following an inverted pyramid structure that presents the most important information first, followed by supporting details.',
  [('What is the main purpose of a press release?', ['To announce newsworthy information concisely and factually to media outlets', 'To provide a lengthy, highly personal account of a private event', 'To advertise a product directly to a single individual consumer', 'A press release has no defined purpose in professional writing'], 0),
   ('What structure do press releases typically follow?', ['An inverted pyramid structure that presents the most important information first', 'A structure that saves the most important information for the very last line', 'Press releases follow no consistent structure of any kind', 'A structure that always begins with an unrelated personal story'], 0),
   ('What kind of tone is generally appropriate for a press release?', ['A clear, factual, and professional tone', 'A tone that is deliberately vague and difficult to understand', 'A tone appropriate only for private correspondence between friends', 'An emotional tone with no factual content included'], 0),
   ('Why is it useful for a press release to include a clear headline?', ['It quickly conveys the main newsworthy point and can capture the attention of a busy journalist', 'A headline is never included in a properly written press release', 'Headlines are always intentionally misleading in a press release', 'A headline has no connection to the content that follows in a press release'], 0),
   ('How does a press release differ from a feature article, studied earlier in this course?', ['A press release is typically a brief factual announcement meant to prompt media coverage, while a feature article offers an in-depth, developed exploration of a topic', 'A press release and a feature article are always identical in length and purpose', 'A feature article is always shorter than a typical press release', 'There is no meaningful difference between these two forms of writing'], 0)]),
M('Sequences and Series: Recursive versus Explicit Formulas',
  'Grade 9 Math strand: a recursive formula defines each term of a sequence in relation to one or more previous terms, while an explicit formula calculates any term directly using its position in the sequence, offering two different but related ways to describe the same pattern.',
  [('What does a recursive formula use to define a term in a sequence?', ['One or more previous terms in the sequence', 'Only the position number of the term, with no reference to any other term', 'A recursive formula never refers to any other term in the sequence', 'The final term of the sequence only'], 0),
   ('What does an explicit formula allow you to calculate directly?', ['Any term in a sequence, using its position number', 'Only the very first term of a sequence', 'An explicit formula cannot be used to calculate any term directly', 'The sum of every term in an infinite sequence only'], 0),
   ('What is a disadvantage of using a recursive formula to find a term far along in a sequence?', ['It typically requires calculating every preceding term first, which can be time-consuming', 'A recursive formula always calculates a distant term instantly with no prior terms needed', 'Recursive formulas can only be used to find the first term of a sequence', 'There is no disadvantage to using a recursive formula for any term'], 0),
   ('Which type of formula would be more efficient for finding the 100th term of a sequence directly?', ['An explicit formula', 'A recursive formula', 'Neither type of formula can be used to find a specific term', 'Both formulas require exactly the same amount of calculation in every case'], 0),
   ('How do recursive and explicit formulas relate to each other when describing the same sequence?', ['They can describe the same underlying pattern using two different approaches, one based on previous terms and one based on position', 'Recursive and explicit formulas always describe two completely unrelated sequences', 'A sequence can only ever be described using a recursive formula', 'Explicit and recursive formulas never produce the same set of terms'], 0)]),
Sc('Environmental Science: Light Pollution and Its Effects on Ecosystems',
   'Grade 9 Science strand: light pollution is excessive or misdirected artificial light, especially from urban areas at night, that can disrupt the natural behaviours of nocturnal animals, interfere with bird migration, and reduce the visibility of stars in the night sky.',
   [('What is light pollution?', ['Excessive or misdirected artificial light, especially from urban areas at night', 'A form of pollution caused exclusively by natural sunlight during the day', 'A term that applies only to pollution found in ocean water', 'Light pollution has no connection to any form of artificial lighting'], 0),
    ('How can light pollution disrupt nocturnal animals?', ['It can interfere with natural behaviours that depend on darkness, such as hunting or resting patterns', 'Light pollution has no effect on any nocturnal species', 'Light pollution always improves the natural behaviour of nocturnal animals', 'Nocturnal animals are entirely unaffected by any change in light levels'], 0),
    ('How can artificial light at night interfere with bird migration?', ['It can disorient migrating birds that rely on natural light cues, sometimes leading them off course', 'Artificial light has no effect on migrating birds of any kind', 'Migrating birds are guaranteed to ignore all artificial light sources', 'Bird migration never occurs at night, so light pollution has no relevance'], 0),
    ('What effect does light pollution have on the visibility of stars in the night sky?', ['It can significantly reduce the visibility of stars, especially in and around urban areas', 'Light pollution always makes stars easier to see from any location', 'Light pollution has no measurable effect on the visibility of stars', 'Stars are only visible in locations with significant light pollution'], 0),
    ('What is one strategy that can help reduce light pollution in a city?', ['Using shielded or directional outdoor lighting that reduces light scattering into the sky', 'Increasing the brightness of every outdoor light as much as possible', 'Light pollution cannot be reduced through any change in lighting design', 'Removing all forms of outdoor lighting is the only possible solution'], 0)]),
SS('Social Studies: The Geography of Micronations and Unrecognized States',
   'Grade 9 Social Studies (Geography) strand: a micronation is a small entity that claims independence but lacks widespread international recognition, while an unrecognized state controls territory and functions similarly to a country but is not officially recognized as sovereign by most of the international community.',
   [('What is a micronation?', ['A small entity that claims independence but lacks widespread international recognition', 'A large, fully recognized member state of the United Nations', 'A term used only to describe a small province within a recognized country', 'A micronation always receives full recognition from every country in the world'], 0),
    ('What distinguishes an unrecognized state from a fully recognized country?', ['An unrecognized state controls territory and functions similarly to a country but is not officially recognized as sovereign by most of the international community', 'An unrecognized state has no defined territory of any kind', 'There is no meaningful difference between an unrecognized state and a fully recognized country', 'An unrecognized state is always recognized by every other country in the world'], 0),
    ('Why might a territory become an unrecognized state?', ['It may have declared independence or gained de facto control following a conflict or political dispute, without gaining widespread diplomatic recognition', 'Unrecognized states are always created through a fully approved international process', 'A territory can only become an unrecognized state with unanimous global recognition', 'Unrecognized states have no connection to political conflict or dispute'], 0),
    ('What practical challenges might an unrecognized state face in international affairs?', ['Difficulty accessing international trade, aid, or organizations that generally require formal diplomatic recognition', 'Unrecognized states face no challenges different from those of any fully recognized country', 'Unrecognized states automatically receive full membership in every international organization', 'International trade and aid have no connection to diplomatic recognition'], 0),
    ('Why do geographers study micronations and unrecognized states as part of political geography?', ['They illustrate the complex relationship between territorial control, sovereignty, and international recognition', 'Micronations and unrecognized states have no connection to political geography', 'Every territory in the world has always had exactly the same recognized status', 'This topic is considered purely a matter of law, not geography'], 0)]),
]),
day(180, [
L('Language Review: Misinformation, Acronyms, Red Herrings, and Press Releases',
  'Grade 9 Language strand review: students revisit analyzing misinformation and verification techniques, acronyms and initialisms, analyzing red herrings and misdirection in plot, double negatives, and writing a press release from Days 171-179.',
  [('What is misinformation?', ['False or inaccurate information that is spread, regardless of whether the person sharing it intends to deceive', 'Information that is always spread deliberately to deceive an audience', 'A type of information that is always factually accurate and verified', 'A term used only to describe information found in printed newspapers'], 0),
   ('What is an acronym?', ['A word formed from the initial letters of a phrase and pronounced as a single word', 'A word formed by shortening a single longer word', 'A punctuation mark used to separate two independent clauses', 'A term that applies only to words borrowed from another language'], 0),
   ('What is a red herring in a narrative?', ['A clue or detail deliberately placed to mislead readers away from the true solution or outcome', 'A character who always tells the reader the complete truth', 'A detail that has no purpose within the structure of a story', 'A setting description with no connection to the plot'], 0),
   ('What is a double negative?', ['The use of two negative words within the same clause', 'A sentence that contains no negative words of any kind', 'A punctuation mark used to indicate a strong negative statement', 'A grammatical structure that always makes a sentence perfectly clear'], 0),
   ('What is the main purpose of a press release?', ['To announce newsworthy information concisely and factually to media outlets', 'To provide a lengthy, highly personal account of a private event', 'To advertise a product directly to a single individual consumer', 'A press release has no defined purpose in professional writing'], 0)]),
M('Math Review: Reciprocal Trig Functions, Wilsons Theorem, Payday Loans, and Optimization',
  'Grade 9 Math strand review: students revisit graphing the cosecant, secant, and cotangent functions, Wilsons Theorem, payday loans and predatory lending, optimization using derivatives, and recursive versus explicit formulas from Days 171-179.',
  [('What is the cosecant function defined as the reciprocal of?', ['The sine function', 'The cosine function', 'The tangent function', 'Cosecant has no relationship to any other trigonometric function'], 0),
   ('What does Wilsons Theorem state about a number p greater than 1?', ['p is prime if and only if (p minus 1) factorial plus 1 is divisible by p', 'p is always prime regardless of any factorial calculation', 'p is prime only if p is an even number', 'p is prime if and only if p is divisible by 2'], 0),
   ('What is a payday loan?', ['A short-term, high-interest loan intended to be repaid by a borrowers next paycheque', 'A long-term, low-interest loan intended to fund the purchase of a home', 'A type of loan that always charges no interest of any kind', 'A government benefit paid automatically to every worker'], 0),
   ('What is the goal of an optimization problem in calculus?', ['To find the maximum or minimum value of a function, often within given constraints', 'To find every possible value a function could ever produce', 'To determine the exact colour of a functions graph', 'Optimization problems have no defined goal of any kind'], 0),
   ('What does a recursive formula use to define a term in a sequence?', ['One or more previous terms in the sequence', 'Only the position number of the term, with no reference to any other term', 'A recursive formula never refers to any other term in the sequence', 'The final term of the sequence only'], 0)]),
Sc('Science Review: Electrolysis, Neurons, Keplers Laws, and Entropy',
   'Grade 9 Science strand review: students revisit electrolysis and electroplating, neurons and synaptic transmission, Keplers Laws of planetary motion, entropy and the second law of thermodynamics, and light pollution from Days 171-179.',
   [('What does electrolysis use to drive a non-spontaneous chemical reaction?', ['An electric current supplied from an external source', 'Heat energy released from a spontaneous reaction', 'Light energy absorbed directly from the sun', 'Mechanical energy produced by a spinning turbine'], 0),
    ('What is a neuron?', ['A specialized cell that transmits electrical and chemical signals throughout the nervous system', 'A cell found only in muscle tissue with no connection to the nervous system', 'A type of blood cell responsible for carrying oxygen', 'A structure found only in plants, never in animals'], 0),
    ('According to Keplers first law, what shape do planetary orbits follow?', ['An ellipse, with the sun located at one focus', 'A perfect circle, with the sun located at its exact centre', 'A straight line directly toward the sun', 'Planetary orbits follow no consistent geometric shape'], 0),
    ('What does entropy measure within a system?', ['The degree of disorder or randomness within the system', 'The exact temperature of a system at a single moment', 'The total mass contained within a system', 'Entropy has no measurable meaning in physics'], 0),
    ('What is light pollution?', ['Excessive or misdirected artificial light, especially from urban areas at night', 'A form of pollution caused exclusively by natural sunlight during the day', 'A term that applies only to pollution found in ocean water', 'Light pollution has no connection to any form of artificial lighting'], 0)]),
SS('Social Studies Review: Colonial Boundaries, Fair Trade, Wildlife Trade, and Micronations',
   'Grade 9 Social Studies (Geography) strand review: students revisit colonial boundaries in Africa, fair trade and ethical sourcing, illegal wildlife trade, global courier and logistics networks, and micronations from Days 171-179.',
   [('How were many national borders in Africa originally established?', ['They were drawn largely by European colonial powers, often with limited regard for existing ethnic or cultural boundaries', 'They were drawn entirely by African nations working together with no outside influence', 'They have remained completely unchanged since long before any colonial contact', 'They were determined only by natural physical features such as rivers and mountains'], 0),
    ('What is the main goal of the fair trade model?', ['To ensure producers receive a fair price and safe working conditions for the goods they sell in global markets', 'To guarantee that producers receive the lowest possible price for their goods', 'To eliminate all forms of international trade completely', 'Fair trade has no connection to the price paid to producers'], 0),
    ('What does the illegal wildlife trade involve?', ['The poaching and trafficking of protected animal species and their parts', 'The legal, regulated sale of farmed livestock within a single country', 'A trade that has no connection to protected or endangered species', 'A form of trade that occurs only with the full approval of international law'], 0),
    ('What is the main purpose of global courier and logistics networks?', ['To move goods efficiently between producers and consumers using multiple forms of transportation', 'To prevent goods from ever being transported between different countries', 'Logistics networks exist only to transport passengers, never goods', 'To ensure that every shipment travels using exactly one mode of transportation only'], 0),
    ('What is a micronation?', ['A small entity that claims independence but lacks widespread international recognition', 'A large, fully recognized member state of the United Nations', 'A term used only to describe a small province within a recognized country', 'A micronation always receives full recognition from every country in the world'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g9_171_180)
    append_to(9, g9_171_180)
