#!/usr/bin/env python3
"""Grade 8 — days 16-30."""
import sys
sys.path.insert(0,'/sessions/wonderful-keen-tesla/mnt/gradesbooster')
from gen_curriculum import sub,day,append_to

U='https://tvolearn.com/pages/grade-8'
R='TVO Learn: Grade 8'

def L(t,s,q): return sub('Language',t,s,R,U,q)
def M(t,s,q): return sub('Math',t,s,R,U,q)
def Sc(t,s,q): return sub('Science',t,s,R,U,q)
def H(t,s,q): return sub('History',t,s,R,U,q)

g8b=[
day(16,[
L('Writing: Narrative with Shifting Point of View','Students experiment with narrative point of view — first person, second person, third limited, and third omniscient — and analyse how POV shapes reader experience.',[
  ('First-person POV uses ___.',['he/she/they pronouns','you pronouns','I/we pronouns and gives readers direct access to the narrator\'s thoughts','a neutral outside perspective'],2),
  ('Third-person omniscient POV means ___.',['the narrator knows only one character\'s thoughts','the narrator is a character in the story','the narrator has access to all characters\' thoughts, feelings, and knowledge','only descriptions of external events'],2),
  ('Third-person limited POV ___.',['knows all characters\' inner thoughts','is told from a character\'s perspective','follows one character\'s perspective closely, accessing only that character\'s inner world','uses first-person pronouns'],1),
  ('How does POV affect a story?',['It has no effect','It only changes pronouns','It fundamentally shapes what readers know, whom they trust, what information is withheld, and how they emotionally connect to the narrative','Only the style changes'],2),
  ('Shifting the POV mid-story can ___.',['never work','always improve any story','add depth by revealing different characters\' perspectives on the same events — when done deliberately, it enriches theme and creates dramatic irony','only confuse readers'],2)]),
M('Algebra: Multiplying Polynomials','Students multiply polynomials: monomial × polynomial and binomial × binomial using the distributive property and FOIL.',[
  ('To multiply 3x(2x + 5), you apply ___.',['the commutative property only','the distributive property: 3x × 2x + 3x × 5 = 6x² + 15x','FOIL','the Pythagorean theorem'],1),
  ('FOIL stands for ___.',['First, Outer, Inner, Last — a method for multiplying two binomials','Factor, Operate, Integrate, List','First, Open, Include, Last','None of these'],0),
  ('(x + 3)(x + 4) using FOIL = ___.',['x² + 12','x² + 7x + 12','x² + 7x + 7','2x + 7'],1),
  ('(2x − 1)(3x + 2) = ___.',['6x² + 4x − 3x − 2 = 6x² + x − 2','5x + 1','6x² − 2','6x² + 1'],0),
  ('(x + 5)² = ___.',['x² + 25','x² + 5x + 25','x² + 10x + 25','x² + 10x'],2)]),
Sc('Mechanical Systems: Efficiency and Energy','Students examine efficiency in machines, energy input vs. output, friction losses, and renewable energy technologies.',[
  ('Mechanical efficiency is ___.',['always 100% in ideal machines','always less than 100% in real machines because friction converts some input energy to heat','greater than 100% in compound machines','unrelated to energy'],1),
  ('Efficiency = ___.',['input energy / output energy × 100%','output energy / input energy × 100%','output + input','energy × time'],1),
  ('Why is no real machine 100% efficient?',['Engineers are not skilled enough','Friction always converts some energy to heat, sound, or vibration — wasted energy','Perfect machines do exist','Small machines are always 100%'],1),
  ('Renewable energy sources include ___.',['coal and natural gas','oil and propane','nuclear only','solar, wind, hydroelectric, geothermal, and tidal energy'],3),
  ('Reducing friction in a machine improves efficiency by ___.',['increasing heat loss','decreasing the work output','reducing the amount of input energy wasted as heat and increasing the proportion converted to useful work','slowing the machine'],2)]),
H('Post-WWII Canada: Growth and Change','Students examine the baby boom, suburbanisation, the Quiet Revolution, Expo 67, and Canada\'s evolving sense of identity in the 1950s–1960s.',[
  ('The baby boom refers to ___.',['a decline in birth rates after WWII','a government program for children','the significant increase in birth rates from approximately 1946 to 1964 as soldiers returned and families expanded','a type of school program'],2),
  ('Suburbanisation after WWII was driven by ___.',['a preference for city centres','declining car ownership','the growth of car culture, affordable housing programs, and a desire for space and safety outside crowded cities','government mandates'],2),
  ('Expo 67 in Montreal was significant because ___.',['it had no impact','it was held in another country','it was Canada\'s centennial celebration and World\'s Fair, showcasing Canadian and global achievements and generating enormous national pride','it was a trade fair only'],2),
  ('Canada\'s centennial year was ___.',['1982','1967','1997','1927'],1),
  ('The Quiet Revolution in Quebec (1960s) resulted in ___.',['French Canadians losing cultural influence','Quebec separating from Canada','rapid secularisation, modernisation of education and social services, and a strong assertion of Québécois identity and eventually a separatist movement','no major changes'],2)]),
]),
day(17,[
L('Reading: Dystopian Fiction','Students examine dystopian fiction as a genre, exploring how authors use dystopias to critique contemporary society and raise questions about power, freedom, and identity.',[
  ('A dystopian society is ___.',['a perfect utopia','a realistic present-day society','an imagined society characterised by oppression, environmental destruction, or authoritarian control — the opposite of a utopia','only a futuristic setting'],2),
  ('Dystopian fiction typically critiques ___.',['nothing in the real world','only science and technology','aspects of real contemporary society — surveillance, conformity, authoritarianism, inequality — by projecting them to an extreme conclusion','only historical governments'],2),
  ('In dystopian fiction, the protagonist usually ___.',['perfectly fits into their society','is the government leader','becomes aware of and resists the oppressive systems controlling their society','is entirely happy'],2),
  ('Surveillance, censorship, and propaganda are common dystopian elements because ___.',['they make for exciting action','they are uniquely fictional','they reflect real mechanisms used by authoritarian regimes to control populations and suppress dissent','only dystopian governments use them'],2),
  ('Reading dystopian fiction develops critical thinking because ___.',['it is purely escapist entertainment','it has no connection to real life','it encourages readers to question power structures, consider what freedoms are worth protecting, and imagine alternatives to existing social arrangements','it only improves vocabulary'],2)]),
M('Geometry: 3D Solids — Nets and Surface Area','Students draw and interpret nets of 3D solids and calculate surface area of composite solids.',[
  ('A net of a 3D solid is ___.',['a 3D model','a graph of its volume','a flat (2D) pattern that folds up to form the 3D shape','a shadow'],2),
  ('The surface area of a cylinder = ___.',['πr²h','2πr² + 2πrh (two circular ends + curved rectangular surface)','πr² + πrh','4πr²'],1),
  ('To find the surface area of a composite solid ___.',['add the volumes','find the surface area of each part and add them, subtracting any shared faces','measure only the base','use only the perimeter'],1),
  ('A net for a square pyramid has ___.',['four triangles only','one square base and four triangular faces','two squares and four triangles','only triangles'],1),
  ('Surface area is measured in ___.',['cm³','cm','cm² (square units)','kg'],2)]),
Sc('Cells: Organ Systems in Detail','Students examine two body systems in depth — cardiovascular and nervous — exploring their structures, functions, and interactions.',[
  ('The heart pumps blood through ___.',['one loop','three loops','two loops: pulmonary circulation (heart to lungs and back) and systemic circulation (heart to body and back)','the lymphatic system only'],2),
  ('Arteries carry blood ___.',['to the heart at low pressure','away from the heart, typically at high pressure','only deoxygenated blood','only to the lungs'],1),
  ('Neurons transmit signals using ___.',['mechanical pressure','sound waves','electrical signals along the axon and chemical signals (neurotransmitters) across the synapse','magnetic fields'],2),
  ('The central nervous system (CNS) consists of ___.',['all nerves in the body','only the brain','the brain and spinal cord, which process and coordinate all neural information','only the spinal cord'],2),
  ('How do the nervous and cardiovascular systems interact?',['They do not interact','Only the heart has nerves','The nervous system regulates heart rate, blood pressure, and blood vessel diameter through neural and hormonal signals','Only the brain has a blood supply'],2)]),
H('Quebec Referendums and Canadian Unity','Students examine the two Quebec referendums (1980, 1995) and the complex questions of identity, language, and national unity they raised.',[
  ('The 1980 Quebec Referendum was on ___.',['whether Quebec should join the United States','Quebec independence outright','whether Quebec should negotiate "sovereignty-association" with Canada — a form of political independence while maintaining economic ties','Quebec leaving Confederation temporarily'],2),
  ('The result of the 1980 referendum was ___.',['60% Yes for sovereignty-association','a tied vote','59.6% No — Quebecers voted against sovereignty-association','a Yes vote for full independence'],2),
  ('The 1995 Quebec Referendum result was ___.',['70% No','70% Yes','50.58% No — the narrowest possible result, with the No side winning by less than 1 percentage point','exactly 50-50'],0),
  ('The Clarity Act (2000) was passed to ___.',['encourage Quebec to separate','ban all future referendums','establish federal conditions for any future separation — requiring a clear question and a clear majority before negotiation could begin','grant Quebec special status'],2),
  ('The Quebec referendums highlight tensions between ___.',['English Quebec and French Ontario','only economic issues','the French-Canadian identity and desire for self-determination in Quebec vs. the English-Canadian vision of a bilingual, multicultural Canada','only language policy'],2)]),
]),
day(18,[
L('Writing: The Short Story','Students plan and write an original short story with an engaging hook, developed plot structure, consistent point of view, vivid characterisation, and a resonant ending.',[
  ('A story\'s inciting incident is ___.',['the resolution','the falling action','the event that disrupts the protagonist\'s normal world and sets the main conflict in motion','the climax'],2),
  ('Rising action consists of ___.',['events after the climax','the resolution of all conflicts','the series of complications and events that build tension and lead toward the climax','only dialogue'],2),
  ('An effective ending ___.',['always wraps everything up perfectly','is always surprising','follows logically from the story\'s events and themes — it can be resolved, ambiguous, or open, but must feel earned','is always happy'],2),
  ('Showing vs. telling in fiction means ___.',['having a narrator explain everything','only using dialogue','using specific details, actions, and sensory descriptions to show emotions and events rather than simply stating them directly','writing longer descriptions'],2),
  ('Consistent point of view means ___.',['changing POV whenever convenient','using only dialogue','maintaining the same narrative perspective throughout, except for deliberate artistic shifts with clear purpose','using multiple narrators in every story'],2)]),
M('Data Management: Scatter Plots and Correlations','Students create scatter plots, identify correlations (positive, negative, none), draw lines of best fit, and use them to make predictions.',[
  ('A scatter plot is used to ___.',['show proportions of a whole','track changes over time','show the relationship between two variables by plotting data as points on a coordinate plane','only show categorical data'],2),
  ('A positive correlation means ___.',['as x increases, y decreases','there is no relationship','as x increases, y also increases','the data is perfectly linear'],2),
  ('A line of best fit ___.',['must pass through all data points','passes through the origin','is a straight line that best represents the overall trend in scatter plot data, passing through the middle of the data','is always horizontal'],2),
  ('Correlation does NOT prove ___.',['a relationship exists','a trend','causation — two variables can be correlated without one causing the other','a line of best fit'],3),
  ('To predict a value not in a data set using a scatter plot, you ___.',['guess randomly','use the y-axis only','extrapolate or interpolate using the line of best fit to estimate the y-value for a given x-value','average all x-values'],2)]),
Sc('Optics: Telescopes and Modern Technology','Students explore how modern telescopes work, the electromagnetic spectrum beyond visible light, and how optical technology has transformed astronomy.',[
  ('The Hubble Space Telescope operates in space to avoid ___.',['gravity','the moon','atmospheric distortion and light pollution that reduce image clarity for ground-based telescopes','solar radiation'],2),
  ('Radio telescopes detect ___.',['visible light','X-rays only','radio waves emitted by celestial objects — allowing study of objects invisible to optical telescopes','infrared only'],2),
  ('The James Webb Space Telescope primarily observes in ___.',['visible light like Hubble','ultraviolet light','X-rays','infrared, allowing it to see the earliest galaxies and peer through dust clouds'],3),
  ('Adaptive optics in modern ground-based telescopes ___.',['magnifies the image more','replaces lenses with mirrors','uses real-time adjustments to mirror shape to compensate for atmospheric turbulence, dramatically sharpening images','only works in space'],2),
  ('CCD (charge-coupled device) detectors replaced photographic film in telescopes because ___.',['film is more accurate','CCDs are heavier','CCDs are far more sensitive, accurate, and produce digital data that can be processed instantly on computers','CCDs use more energy'],2)]),
H('Indigenous Issues: Land Rights and Reconciliation','Students examine specific Indigenous land claims, treaty rights, and current reconciliation efforts in Canada, connecting to historical policies.',[
  ('A land claim in Canada refers to ___.',['a private real estate dispute','a complaint about municipal zoning','a legal claim by an Indigenous group seeking recognition of rights to lands not covered by treaty or from which they were dispossessed','a tax dispute'],2),
  ('The Haida Gwaii (2004) and Tsilhqot\'in Nation (2014) Supreme Court decisions were significant because ___.',['they reduced Indigenous land rights','they had no lasting impact','they affirmed the duty of the Crown to consult and accommodate Indigenous peoples and recognised Aboriginal title to specific territories','they only applied to British Columbia'],2),
  ('Section 35 of the Constitution Act, 1982 ___.',['removed all Indigenous rights','is irrelevant today','recognises and affirms existing Aboriginal and treaty rights of the Indigenous peoples of Canada — a landmark constitutional protection','only protects Métis rights'],2),
  ('The 94 Calls to Action from the Truth and Reconciliation Commission address ___.',['only educational reform','only language revitalisation','a broad range of areas including child welfare, education, language, health, justice, and commemoration — requiring action from governments, churches, and all Canadians','only the federal government'],2),
  ('Reconciliation in Canada means ___.',['returning all land to Indigenous peoples immediately','pretending the residential school era never happened','the ongoing process of establishing respectful, equitable relationships between Indigenous and non-Indigenous peoples, addressing historical wrongs and building a shared future','Indigenous peoples assimilating fully'],2)]),
]),
day(19,[
L('Grammar Review: Clauses, Phrases, and Usage','Students distinguish between phrases and clauses, identify misplaced and dangling modifiers, and apply grammar knowledge to revise writing for clarity and precision.',[
  ('A phrase is ___.',['a complete thought','a group of words with a subject and verb','a group of words that functions as a unit but does NOT contain both a subject and a verb','always one word'],2),
  ('A misplaced modifier is ___.',['a modifier that is missing','a modifier placed correctly','a modifier positioned so far from the word it modifies that the sentence is ambiguous or illogical','a type of adverb'],2),
  ('Which sentence contains a dangling modifier?',['Having studied hard, she passed the exam.','Running quickly, John reached the bus stop.','Walking through the park, the flowers were beautiful.','After eating dinner, he went for a walk.'],2),
  ('Parallel structure means ___.',['using only simple sentences','using only adjectives','items in a list or series should have the same grammatical form (all nouns, all phrases, all clauses)','sentences that rhyme'],2),
  ('Which sentence demonstrates parallel structure?',['She likes swimming, to run, and hiking.','She likes swimming, running, and to hike.','She likes to swim, running, and a hike.','She likes swimming, running, and hiking.'],3)]),
M('Algebra: Factoring','Students factor polynomials by finding the greatest common factor (GCF) and factoring simple trinomials.',[
  ('Factoring a polynomial means ___.',['multiplying it out','adding like terms','expanding it','expressing it as a product of simpler expressions'],3),
  ('The GCF of 12x² and 8x is ___.',['4x²','2x','4x','8x'],2),
  ('Factor: 6x² + 9x',['3(2x² + 3x)','3x(2x + 3)','6x(x + 9)','3x²(2 + 3)'],1),
  ('Factor: x² + 5x + 6',['(x + 6)(x − 1)','(x + 2)(x + 3)','(x + 1)(x + 6)','(x − 2)(x − 3)'],1),
  ('Factoring is the reverse of ___.',['differentiation','adding','subtraction','expanding (multiplying out)'],3)]),
Sc('Fluids: Technology and Society','Students evaluate how fluid technology has shaped society — from ancient aqueducts to modern medicine (syringes, IV drips, blood pressure monitors).',[
  ('Ancient Roman aqueducts used ___.',['pumps and electricity','gravity to move water through channels from highland sources to cities — an early example of fluid engineering','steam power','windmills'],1),
  ('A syringe uses ___.',['electrical pressure','compressed gases','pneumatic/hydraulic principles: pulling the plunger creates low pressure that draws fluid in; pushing increases pressure to expel it','gravity only'],2),
  ('Blood pressure monitors (sphygmomanometers) measure ___.',['blood sugar','blood oxygen level','the pressure exerted by blood against artery walls, expressed as systolic/diastolic pressure in mmHg','heart rate only'],2),
  ('Dialysis machines clean blood by ___.',['using electrical current','using fluid dynamics: blood is passed through a semi-permeable membrane in dialysate solution, removing waste through diffusion while retaining needed components','using lasers','compressing the blood'],1),
  ('Innovations in fluid technology for sustainability include ___.',['only desalination','only sewage treatment','drip irrigation (reducing agricultural water use), desalination, water recycling, and smart pipe sensors to detect leaks in water systems','only dam construction'],2)]),
H('Canada and Globalisation','Students examine how globalisation affects Canada — trade, immigration, cultural exchange, and environmental interdependence.',[
  ('Globalisation refers to ___.',['only the spread of the internet','only economic trade','the increasing interconnection and interdependence of countries through trade, technology, communication, migration, and cultural exchange','only political alliances'],2),
  ('CUSMA (Canada-United States-Mexico Agreement, 2020) is ___.',['a defence treaty','a cultural agreement','an immigration policy','a trade agreement replacing NAFTA that governs trade among North America\'s three countries'],3),
  ('Canada\'s immigration policy is described as a "points-based system" that ___.',['selects immigrants randomly','only accepts refugees','only accepts immigrants from wealthy countries','evaluates applicants on education, work experience, language skills, and adaptability to select economic immigrants'],3),
  ('Cultural globalisation can threaten local cultures because ___.',['global culture always improves local culture','diversity naturally increases with globalisation','the dominance of a few global cultures (especially American media and English-language content) can displace or erode local languages, traditions, and cultural practices','there is no evidence of cultural displacement'],2),
  ('Environmental globalisation means ___.',['environmental problems only occur locally','only climate change is global','pollution, species extinction, and climate change cross national borders, requiring international cooperation to address problems no single country can solve alone','only trade causes environmental problems'],2)]),
]),
day(20,[
L('Independent Novel Study: Theme and Author\'s Craft','Students write an analytical essay on their novel, examining how the author uses specific craft choices to develop a central theme.',[
  ('A thematic essay about a novel should ___.',['summarise the plot','list all the characters','analyse how the author\'s specific craft choices (diction, structure, imagery, character development) work together to develop a central theme','only quote the most famous lines'],2),
  ('Diction refers to ___.',['sentence length only','only dialogue','the author\'s choice of specific words and phrases, which creates tone, reveals character, and contributes to meaning','only formal language'],2),
  ('Imagery in a novel ___.',['only describes nature','is decorative only','uses sensory language to create vivid pictures that evoke emotion, deepen character, and develop themes','is only in poetry'],2),
  ('When discussing an author\'s craft, you should ___.',['only praise the author','only identify techniques','identify the technique, provide a textual example, and explain the specific effect the technique creates in service of the theme','ignore technique'],2),
  ('A strong essay conclusion on theme ___.',['summarises only the plot','introduces entirely new evidence','synthesises how the evidence shows the theme\'s development, extends the theme to a broader human truth, and leaves the reader with a new insight','just restates the thesis'],2)]),
M('Financial Literacy: Budgeting and Tax','Students create a personal budget, understand gross vs. net income, and learn the basics of taxes (income tax, HST/GST) and why they exist.',[
  ('Net income is ___.',['income before deductions','total money earned before taxes','income after all deductions (taxes, CPP, EI contributions) — what you actually take home','only investment income'],2),
  ('A personal budget ___.',['is only for people in debt','is unnecessary if you earn enough','tracks income and planned expenses to ensure you can meet financial obligations and save toward goals','replaces the need for a bank account'],2),
  ('HST (Harmonised Sales Tax) in Ontario is ___.',['a federal income tax','an investment return','a combined federal and provincial sales tax of 13% applied to most goods and services at the point of sale','a luxury tax only'],2),
  ('Why do governments collect income tax?',['To punish workers','Taxes are unnecessary','To fund public services (health care, education, roads, defence, social programs) that benefit all citizens','Only to pay politicians'],2),
  ('The "50/30/20 rule" for budgeting suggests ___.',['spending 50% on wants and 30% on savings','saving 50% of income','allocating roughly 50% to needs, 30% to wants, and 20% to savings and debt repayment','spending all income on needs'],0)]),
Sc('Biology: Biodiversity and Ecosystems Review','Students consolidate understanding of cells, genetics, reproduction, and connect to ecosystem-level impacts of biodiversity loss.',[
  ('Genetic diversity within a species is important because ___.',['all individuals being identical is more efficient','genetic variation gives a population the raw material to adapt to environmental changes through natural selection','genetic diversity has no survival value','only biodiversity between species matters'],1),
  ('Species extinction reduces ecosystem resilience because ___.',['ecosystems function better with fewer species','extinct species are replaced instantly','each species plays a role in ecosystem function; losing species can cascade through food webs and destabilise entire systems','only keystone species matter'],2),
  ('The primary driver of current biodiversity loss globally is ___.',['natural climate cycles','disease only','habitat destruction (primarily for agriculture, logging, and urban expansion)','pollution alone'],2),
  ('Conservation biology strategies include ___.',['only captive breeding programs','only creating national parks','a range of approaches: protected areas, wildlife corridors, captive breeding, rewilding, invasive species control, and addressing root causes like habitat loss','only legislation'],2),
  ('CRISPR technology may help conservation by ___.',['eliminating all genetic modification','only working in humans','potentially reviving extinct species, boosting disease resistance in endangered species, or controlling invasive species populations — though ethical questions remain','replacing all natural ecosystems'],2)]),
H('Canada\'s Environmental History and Policy','Students examine key environmental milestones — creation of national parks, environmental legislation, climate commitments, and Indigenous land stewardship.',[
  ('Banff National Park (1885) was Canada\'s first national park, established primarily to ___.',['protect Indigenous territory','provide housing for workers','attract tourists and protect the landscape around the hot springs — later expanding to broader conservation goals','mine the Rocky Mountains'],2),
  ('The Canadian Environmental Protection Act (CEPA) ___.',['bans all industrial activity','has no enforcement powers','is federal legislation regulating toxic substances, pollution, and environmental emergencies','only applies to provinces'],2),
  ('Canada\'s commitment to the Paris Agreement (2015) involves ___.',['withdrawing from all climate targets','ignoring carbon emissions','reducing greenhouse gas emissions to limit global temperature rise to 1.5–2°C above pre-industrial levels','only reforestation'],2),
  ('Indigenous land stewardship is increasingly recognised as important to conservation because ___.',['Indigenous peoples have no connection to land stewardship','it is only a political claim','Indigenous communities have managed territories sustainably for millennia, and Indigenous-led conservation areas have proven highly effective at protecting biodiversity','only Western science understands ecology'],2),
  ('The concept of "seventh generation" in some Indigenous traditions relates to ___.',['voting every seven years','a type of government','making decisions with consideration of their impact seven generations into the future — a model of long-term environmental thinking','a religious practice'],2)]),
]),
day(21,[
L('Writing: Reflection and Self-Assessment','Students write a formal self-assessment of their learning and growth throughout the year, applying metacognitive skills to evaluate strengths and areas for continued development.',[
  ('Metacognition means ___.',['thinking about other people\'s ideas','only remembering what you learned','thinking about your own thinking and learning — reflecting on how you learn, what strategies work, and where you need to improve','only writing reflections'],2),
  ('A strong self-assessment is ___.',['only positive','only critical','honest, specific, and evidence-based — identifying genuine strengths and areas for growth with examples','vague and general'],2),
  ('Why is self-assessment a valuable skill?',['It replaces teacher feedback','Only teachers should assess','It develops independence, self-awareness, and the ability to set meaningful goals — essential for lifelong learning beyond school','It is only required in school'],2),
  ('When identifying an area for improvement, you should ___.',['simply say "I need to improve"','only blame external factors','be specific about what the challenge is and what concrete steps you will take to address it','avoid it in a self-assessment'],2),
  ('Goal-setting in a self-assessment should be ___.',['vague and aspirational only','impossible to achieve','SMART: Specific, Measurable, Achievable, Relevant, and Time-bound','only academic'],2)]),
M('Review: Algebra and Analytic Geometry','Students consolidate Grade 8 algebra and geometry — equations, polynomials, graphing, systems, and geometric formulas.',[
  ('Solve: 2(3x − 4) = 16',['x = 2','x = 3','x = 4','x = 6'],2),
  ('What is the slope of the line through (0,3) and (4,11)?',['2','3','8','4'],0),
  ('Expand: (x − 3)(x + 7)',['x² + 4x − 21','x² − 4x + 21','x² + 4x + 21','x² − 4x − 21'],0),
  ('Factor: x² − x − 12',['(x − 4)(x + 3)','(x + 4)(x − 3)','(x − 6)(x + 2)','(x + 6)(x − 2)'],0),
  ('Two lines: y = x + 2 and y = −2x + 8. Their intersection = ?',['(2,4)','(3,5)','(6,0)','(0,8)'],0)]),
Sc('Review: Science Synthesis Grade 8','Students connect all four Grade 8 science strands and reflect on how scientific knowledge evolves and intersects with ethical and social questions.',[
  ('Which strand explains how a vaccine trains your immune system?',['Fluids','Mechanical systems','Optics','Cells, genetics, and the immune system'],3),
  ('A hydraulic excavator applies which strand\'s principles?',['Optics','Cells','Fluids and mechanical systems','Genetics'],2),
  ('The Hubble Space Telescope\'s discoveries relate primarily to which strand?',['Cells','Mechanical advantage','Fluids','Optics'],3),
  ('How does genetic engineering (cells strand) connect to the environment (fluids/ecosystems)?',['It does not connect','Only through water','Through GMO crops that may affect soil and water ecosystems, and conservation genetics that could protect endangered species','Only through climate'],2),
  ('Why do scientific advances often raise ethical questions?',['They do not','Ethics and science are separate','Science gives us power to change the world — from editing genes to altering ecosystems — but whether we should, and for whose benefit, requires ethical reflection beyond what science alone can answer','Only medical science raises ethics'],2)]),
H('Review: Canadian History Grade 8','Students synthesise their understanding of Canadian history from New France to the present, identifying themes of identity, power, rights, and responsibility.',[
  ('Which theme connects New France, Confederation, and modern Canada most directly?',['Military conflict only','Economic growth only','The ongoing negotiation of identity — who belongs, who has power, and what it means to be Canadian across French, English, and Indigenous communities','Cultural exchange only'],2),
  ('The numbered treaties, residential schools, and UNDRIP are all connected by ___.',['immigration policy','economic policy','the relationship between the Canadian state and Indigenous peoples — from dispossession to legal recognition and ongoing reconciliation','environmental history'],2),
  ('WWI, WWII, and the Korean War all contributed to Canada\'s identity as ___.',['a purely peaceful nation','a military superpower','a middle power with a distinct identity, growing international independence, and a commitment to collective security and peacekeeping','an isolationist state'],2),
  ('The Charter of Rights and Freedoms (1982) and multiculturalism policy (1971) both reflect ___.',['the dominance of French culture','a preference for assimilation','the gradual development of a Canadian identity based on rights, diversity, and inclusion — though imperfectly realised','the end of Indigenous rights'],2),
  ('The most important lesson from studying Canadian history is arguably ___.',['Canada has always been perfect','history is irrelevant today','history is not just the past — it actively shapes the present, and understanding it helps us recognise injustice, celebrate progress, and take responsibility for building a better future','only some Canadians need to know history'],2)]),
]),
day(22,[
L('Media: Analysing Propaganda','Students examine propaganda techniques and historical and contemporary examples. They develop critical tools for identifying manipulation in media.',[
  ('Propaganda is ___.',['always obviously false','only used in wartime','media designed to promote a particular political cause or point of view, often using emotional manipulation, selective facts, and misleading framing','only government communication'],2),
  ('The "big lie" propaganda technique involves ___.',['a minor exaggeration','stating a minor untruth','repeating a massive falsehood so frequently and confidently that people come to believe it — associated with totalitarian regimes','satire'],2),
  ('Scapegoating as a propaganda technique ___.',['is rare in modern media','fairly identifies causes of problems','blames a specific group (ethnic, religious, political) for complex societal problems to redirect public anger and justify discrimination','only occurs in history'],2),
  ('How can you identify propaganda?',['Only experts can','You cannot','Examining sources, checking whether claims are supported by verifiable evidence, identifying emotional manipulation, and seeking diverse perspectives','Only by feeling what sounds wrong'],2),
  ('Understanding propaganda is important because ___.',['it is only a historical concern','modern media has no propaganda','the techniques of manipulation are pervasive in modern media, advertising, and politics — critical media literacy is essential for democratic citizenship','only media professionals need this skill'],2)]),
M('Review: Measurement and Data','Students consolidate measurement (surface area, volume of 3D solids) and data management (scatter plots, probability) from Grade 8.',[
  ('A cone has radius 4 cm and height 9 cm. Volume = ? (π ≈ 3.14)',['452.2 cm³','150.7 cm³','603.0 cm³','37.7 cm³'],1),
  ('A sphere has radius 6 cm. Surface area = ? (π ≈ 3.14)',['150.7 cm²','75.4 cm²','452.2 cm²','904.3 cm²'],2),
  ('A scatter plot shows a strong negative correlation. As x increases, y ___.',['also increases','stays the same','cannot be determined','decreases'],3),
  ('P(rolling a 3 on a die AND flipping heads) = ?',['1/3','1/4','1/12','1/6'],2),
  ('The line of best fit on a scatter plot is used to ___.',['describe only existing data','always give exact answers','replace the original data','make predictions for values not in the original data set'],3)]),
Sc('Science: Careers and Future Directions','Students explore STEM careers and how Grade 8 science connects to real-world professions and future study.',[
  ('A biomedical engineer uses knowledge from ___.',['only math','only history','cells and fluids and mechanical systems — designing medical devices like prosthetics, dialysis machines, and drug delivery systems','only one science strand'],2),
  ('An optometrist applies knowledge of ___.',['genetics and cells','fluid dynamics','optics and the physics of light, lenses, and the human eye to assess and correct vision','mechanical advantage'],2),
  ('Environmental engineers need knowledge of ___.',['only chemistry','only biology','fluid dynamics, ecology, chemistry, and engineering to design systems that protect and clean water, air, and soil','only mechanical systems'],2),
  ('Genetic counsellors use knowledge of ___.',['optics','fluid mechanics','genetics, inheritance, and cell biology to advise families about hereditary conditions and reproductive options','mechanical engineering'],2),
  ('Studying Grade 8 science helps future decision-making because ___.',['it has no practical value','only scientists need science','scientific literacy enables everyone to evaluate health claims, understand environmental issues, engage with technology, and participate in decisions about science policy','only if you become a scientist'],2)]),
H('Critical Thinking: Historical Perspective Taking','Students practise empathetic historical thinking — examining events from multiple perspectives to develop nuanced understanding and avoid presentism.',[
  ('Presentism in history means ___.',['studying the present day','accurately applying modern values to all periods','judging historical people and events by the standards of our own time, without considering the context and knowledge available to them','caring about the present'],2),
  ('Historical perspective taking means ___.',['agreeing with all historical actors','ignoring historical wrongdoing','attempting to understand historical actors\' viewpoints, values, and knowledge within their own context — without necessarily endorsing those views','only focusing on victims'],2),
  ('Multiple accounts of the same historical event ___.',['always contradict each other meaninglessly','should be avoided','reveal different perspectives, priorities, and experiences — each is partial, and historians must critically evaluate them all to construct fuller understanding','are always equally reliable'],2),
  ('Primary sources help historians because ___.',['they are always objective','they contain no bias','they are first-hand accounts created at the time of an event, giving direct (though always partial and perspective-specific) evidence of what happened','they are more recent than secondary sources'],2),
  ('Why is understanding history from multiple perspectives essential for democratic citizenship?',['It is not','Only one perspective is valid','History with multiple perspectives reveals complexity, challenges simple narratives, and helps citizens avoid manipulation by those who oversimplify the past for political purposes','Only historians need multiple perspectives'],2)]),
]),
day(23,[
L('Writing: Publishing and Sharing','Students select, polish, and present a piece of writing to a real or simulated audience. They understand the writing-to-publish process.',[
  ('Publishing writing means ___.',['printing a book only','submitting to a professional editor only','sharing completed work with a real or simulated audience — which could include a class anthology, school blog, letter, or formal submission','only digital publication'],2),
  ('Choosing which piece to publish involves ___.',['always picking the longest piece','picking the first piece you wrote','selecting the piece that best represents your voice, growth, and skills — and that is most appropriate for the target audience','picking randomly'],2),
  ('Formatting and presentation of published writing should ___.',['be ignored — content is all that matters','follow no conventions','follow conventions appropriate to the form (paragraph breaks, headings, consistent font) so that presentation enhances rather than distracts from the content','always use decorative fonts'],2),
  ('Author\'s note or introduction to a published piece ___.',['is always required','is never appropriate','can contextualise the piece, explain the writer\'s process or inspiration, and help readers connect with the work','must explain every choice'],2),
  ('Sharing writing with an audience ___.',['is only for professional writers','only exposes your weaknesses','develops communication skills, builds confidence, and makes writing purposeful — real audiences give writing meaning beyond classroom assessment','is always stressful and unproductive'],2)]),
M('Algebra: Solving Quadratic Equations (Introduction)','Students are introduced to quadratic equations in standard form (ax² + bx + c = 0). They solve simple cases by factoring.',[
  ('A quadratic equation has a degree of ___.',['1','2','3','4'],1),
  ('The standard form of a quadratic equation is ___.',['y = mx + b','ax + b = 0','ax² + bx + c = 0','x² = c only'],2),
  ('Solve x² − 5x + 6 = 0 by factoring.',['x = 2 and x = 3 (from (x−2)(x−3) = 0)','x = −2 and x = −3','x = 5 and x = 6','x = 1 and x = 6'],0),
  ('The zero product property states: if ab = 0, then ___.',['a = b','a + b = 0','a = 0 OR b = 0 (at least one factor must be zero)','a = 0 AND b = 0'],2),
  ('Solve x² = 9.',['x = 3 only','x = 9 only','x = 3 or x = −3','x = 81'],2)]),
Sc('Environmental Science: Climate Change Science','Students examine the evidence for climate change, the greenhouse effect, tipping points, and current mitigation and adaptation strategies.',[
  ('The enhanced greenhouse effect refers to ___.',['the natural greenhouse effect that makes Earth habitable','farmers growing more in greenhouses','the amplification of Earth\'s natural greenhouse effect due to human emissions of CO₂, methane, and other gases, causing additional warming','glass buildings trapping heat'],2),
  ('Climate tipping points are ___.',['minor fluctuations','easily reversible changes','thresholds beyond which a climate system component changes dramatically and potentially irreversibly — for example, the collapse of the Greenland ice sheet','political decisions about emissions'],2),
  ('Evidence for current climate change includes ___.',['only computer models','only rising temperatures in one region','rising global average temperatures, melting ice sheets and glaciers, rising sea levels, more frequent extreme weather events, and shifting seasons — all corroborated by multiple independent data sources','only CO₂ measurements'],2),
  ('Mitigation refers to ___.',['adapting to inevitable changes','ignoring climate change','reducing greenhouse gas emissions and enhancing carbon sinks to slow or prevent future warming','measuring temperature'],2),
  ('Adaptation to climate change includes ___.',['only reducing emissions','pretending impacts won\'t occur','measures to adjust to current and expected impacts — seawalls, drought-resistant crops, urban heat island management, and early warning systems','only technological solutions'],2)]),
H('Canada\'s Future: Challenges and Opportunities','Students examine key challenges Canada faces in the 21st century: reconciliation, climate change, economic inequality, and democratic participation.',[
  ('The most significant unresolved challenge in Canadian history for Indigenous peoples is ___.',['language differences only','economic development only','the ongoing legacy of colonialism — including land rights, self-governance, socioeconomic gaps, and the multigenerational effects of residential schools, which requires sustained reconciliation','already completely resolved'],2),
  ('Canada\'s climate commitments face challenges because ___.',['climate change is not real','Canada is too small to matter','as a major fossil fuel exporter and high per-capita emitter, balancing economic interests (oil sands, pipelines) with emissions reduction targets creates significant political and economic tensions','Canada already met all targets'],2),
  ('Democratic participation in Canada includes ___.',['only voting in federal elections','only joining a political party','voting, engaging with elected officials, participating in public consultations, joining civil society organisations, and staying informed — democracy requires active citizens, not just voters every four years','only running for office'],2),
  ('Immigration is central to Canada\'s future because ___.',['Canada has too many immigrants','immigration creates no economic benefit','Canada\'s aging population and low birth rate mean immigration is necessary for economic growth, filling labour shortages, and sustaining social programs like CPP and health care','immigration is purely humanitarian'],2),
  ('A "global citizen" perspective means ___.',['ignoring local issues','only caring about global issues','rejecting Canadian identity','understanding that local and global issues are interconnected, and that citizens have responsibilities not just to their own nation but to humanity and the planet'],3)]),
]),
day(24,[
L('Reading: Poetry Analysis','Students closely analyse poems from different traditions and periods. They examine structure, diction, imagery, figurative language, and theme.',[
  ('Close reading of a poem means ___.',['reading it as fast as possible','memorising it','examining every word, image, and structural choice carefully to understand how they work together to create meaning','only identifying rhyme scheme'],2),
  ('Enjambment in poetry is ___.',['a pause at the end of a line','rhyming every two lines','the continuation of a sentence or phrase beyond the end of a line without a pause, creating momentum and ambiguity','a type of metaphor'],2),
  ('A volta in a sonnet is ___.',['the final couplet\'s rhyme','the first quatrain','a sudden shift or turn in argument, emotion, or perspective — typically at line 9 in a Petrarchan sonnet or at the couplet in a Shakespearean sonnet','the opening question'],2),
  ('Personification in poetry ___.',['only describes landscapes','only occurs in prose','attributes human qualities, emotions, or actions to non-human things, creating vivid emotional connections','is a type of rhyme scheme'],2),
  ('Tone in a poem is conveyed through ___.',['only the poem\'s topic','only the rhyme scheme','diction (word choice), imagery, sound devices, and structural choices — the accumulation of these elements creates the poet\'s attitude toward the subject','only the poem\'s title'],2)]),
M('Number Systems: Square Roots and Irrational Numbers','Students distinguish rational from irrational numbers, estimate square roots, and place them on a number line.',[
  ('A rational number is ___.',['any square root','a number that CANNOT be written as a fraction','any number that can be expressed as a fraction p/q where p and q are integers and q ≠ 0','only whole numbers'],2),
  ('An irrational number is ___.',['any decimal','a fraction with an irrational denominator','a number whose decimal expansion is non-terminating and non-repeating — it cannot be written as a simple fraction','any large number'],2),
  ('√2 is ___.',['exactly 1.41','exactly 1.414','rational','irrational — its decimal expansion goes on forever without repeating'],3),
  ('Estimate √50 to the nearest whole number.',['6','7','8','9'],1),
  ('Which is NOT an irrational number?',['√2','π','√9 = 3','√3'],2)]),
Sc('Systems: Connecting Science Strands','Students explore how the four Grade 8 science strands connect — cells and systems, fluids and pressure, mechanical advantage, optics — within real engineering contexts.',[
  ('A kidney dialysis machine demonstrates ___.',['only electrical principles','only optics','only mechanical advantage','fluid dynamics (semi-permeable membranes, pressure) and cell biology (removing waste from blood)'],3),
  ('A car\'s braking system demonstrates ___.',['optics','cell biology','genetic engineering','fluid dynamics (hydraulic brakes) and mechanical systems (brake pads, rotors)'],3),
  ('Medical imaging (X-rays, MRI, ultrasound) relates primarily to ___.',['cell division','fluid pressure','mechanical advantage','optics and the physics of waves — electromagnetic or sound waves interact with body tissues to create images'],3),
  ('CRISPR gene editing relates to which two strands most directly?',['Fluids and optics','Mechanical systems and optics','Cells and genetics (understanding DNA structure and function) plus ethics (social implications)','Fluids and mechanical systems'],2),
  ('An engineer designing a submarine needs knowledge of ___.',['genetics','optics and light only','cell biology','fluid pressure, buoyancy, and mechanical systems'],3)]),
H('Digital History: Canada\'s Information Age','Students examine how digital technology has transformed Canadian society, economy, and governance since the 1980s.',[
  ('The World Wide Web, invented by Tim Berners-Lee in 1989, transformed Canada by ___.',['having no major impact','reducing communication speed','eliminating all printed media','enabling instant global communication, e-commerce, digital education, and the information economy — reshaping how Canadians work, shop, and connect'],3),
  ('Social media has affected Canadian democracy by ___.',['having no effect','only improving political participation','completely replacing traditional media','enabling citizen voice and political mobilisation, but also spreading misinformation, enabling foreign interference, and creating filter bubbles that deepen polarisation'],3),
  ('The digital divide refers to ___.',['the difference between digital and analogue cameras','only slow internet speeds','a mathematical concept','the gap between those who have access to digital technology and internet connectivity and those who do not — affecting equality of opportunity'],3),
  ('Canada\'s Digital Charter (2019) addresses ___.',['internet speeds only','postal service','immigration through the internet','principles for protecting Canadians\' privacy, security, and rights in the digital age'],3),
  ('Cybersecurity is important for Canada because ___.',['Canada has no cyber threats','only private companies are targeted','digital infrastructure is increasingly critical, and cyberattacks on government, health care, and finance systems can threaten national security and Canadians\' personal data','only the US faces cyber threats'],2)]),
]),
day(25,[
L('Research: Ethics in Writing and Citation','Students deepen their understanding of academic integrity. They distinguish paraphrase, summary, and quotation, and practise ethical source integration.',[
  ('Academic integrity means ___.',['always getting high grades','using AI to write for you','submitting others\' work without attribution','honesty in all academic work — producing your own ideas, properly crediting sources, and not misrepresenting your work'],3),
  ('A summary differs from a paraphrase because ___.',['they are identical','a summary is longer','a summary condenses the main ideas of a larger passage into a much shorter form, while a paraphrase restates a specific passage in your own words at roughly the same length','a paraphrase is shorter'],2),
  ('When should you use a direct quote?',['For all information from sources','Never — always paraphrase','When the original wording is especially precise, memorable, or authoritative — and it always requires quotation marks and a citation','Only for very long passages'],2),
  ('Why is citing sources important beyond avoiding plagiarism?',['It is only about avoiding plagiarism','It makes essays longer','Citations allow readers to verify your sources, trace the conversation of ideas, and give proper credit to the scholars whose work you built upon — it is a mark of scholarly honesty','Only for academic papers'],2),
  ('If you are unsure whether something needs a citation, you should ___.',['leave it out','cite it — it is always better to over-cite than to under-cite and risk plagiarism','ask someone to write it for you','use it without citing'],1)]),
M('Measurement: Optimisation Problems','Students solve problems that require optimising area, perimeter, surface area, or volume — finding maximum or minimum values given constraints.',[
  ('Optimisation in math means ___.',['making something more complicated','only making things bigger','finding the maximum or minimum value of something (area, cost, volume) subject to given constraints','only for calculus'],2),
  ('For a fixed perimeter, which rectangle has the maximum area?',['The longest possible rectangle','A very narrow rectangle','A square (all sides equal)','Shape doesn\'t matter'],2),
  ('A farmer has 200 m of fencing for a rectangular pen. Maximum area = ?',['100 m × 100 m = ... wait, perimeter 400 m for a 100×100','50 m × 50 m = 2500 m² (a square uses all 200 m as perimeter)','40 m × 60 m = 2400 m²','25 m × 75 m = 1875 m²'],1),
  ('For a fixed volume, a cylinder with minimum surface area has ___.',['height much greater than diameter','height much less than diameter','height equal to diameter (h = 2r)','no specific relationship'],2),
  ('Why do companies care about optimisation?',['They don\'t','Only engineers need it','It is only for math class','Minimising material while maximising volume reduces costs — e.g., designing a can that holds the most with least metal'],3)]),
Sc('Science and Society: Ethics of Technology','Students examine the ethical dimensions of emerging technologies — AI, genetic engineering, space exploration — and practise ethical reasoning.',[
  ('Ethical reasoning about technology involves ___.',['only celebrating new inventions','only opposing all new technology','asking who benefits, who bears the risks, whether consent was given, and what the long-term social and environmental consequences might be','only asking if it works'],2),
  ('Artificial intelligence raises ethical concerns including ___.',['none — AI only helps','AI is not real yet','algorithmic bias (AI reflecting human prejudices in training data), job displacement, privacy, and questions about accountability when AI makes harmful decisions','only questions of speed'],2),
  ('The precautionary principle in science and ethics states ___.',['always pursue all technologies','wait until all uncertainty is resolved','when an action raises potential serious harm, precautionary measures should be taken even if full scientific certainty is lacking — err on the side of safety','ignore risks that are not yet proven'],2),
  ('Gene therapy (correcting genetic diseases) raises ethical questions about ___.',['whether genetics exists','whether it will work','the difference between treating disease and enhancing human traits (designer babies), consent (especially for germline changes affecting future generations), and equitable access','only cost'],2),
  ('Space exploration raises ethical questions because ___.',['space is infinite so no ethics apply','it has no Earth applications','it involves vast public expenditure; potential environmental impact on other planetary bodies; and questions of who owns and benefits from space resources','only scientists need to consider this'],2)]),
H('Year-End History Synthesis','Students synthesise Canadian history from New France to the present, examining recurring themes and their relevance to contemporary Canada.',[
  ('Which recurring theme links Indigenous history from colonial times to today?',['Complete resolution of all issues','No significant connection between periods','Sovereignty and self-determination — from treaty rights, through the Indian Act and residential schools, to the TRC Calls to Action and UNDRIP','Only economic issues'],2),
  ('How has Canada\'s relationship with Britain evolved from 1867 to today?',['It has not changed','Canada became less independent over time','From a self-governing Dominion under British authority to full constitutional independence (1982), while maintaining Commonwealth ties','Canada broke all ties with Britain'],2),
  ('What do WWI, WWII, and peacekeeping have in common for Canadian identity?',['Only military spending','Only casualties','They all contributed to Canada establishing itself as a distinct middle power with a unique international identity — not simply following Britain or the United States','Only alliances'],2),
  ('Why is reconciliation with Indigenous peoples described as "unfinished business"?',['It is already complete','It was never started','It is impossible','Legal recognition (Section 35, UNDRIP) has occurred but structural inequalities, land claims, and the healing of multigenerational trauma require sustained action across generations'],3),
  ('The most important civic responsibility for Grade 8 students as future Canadian citizens is ___.',['only voting when old enough','only paying taxes','ignoring politics','staying informed, thinking critically, participating actively in democracy, and working toward a more just and equitable Canada for all people'],3)]),
]),
day(26,[
L('Language Arts: Consolidation and Celebration','Students reflect on their growth as readers, writers, and communicators in Grade 8. They celebrate achievements and set goals for high school.',[
  ('Growth as a writer means ___.',['only getting perfect grades','never making mistakes','developing more sophisticated vocabulary, stronger analytical thinking, greater awareness of craft, and ability to adapt writing for diverse purposes and audiences','only writing longer pieces'],2),
  ('The most important skill developed in Grade 8 Language Arts is arguably ___.',['perfect spelling','fast reading speed','critical thinking — the ability to analyse, evaluate, and synthesise ideas from texts and express complex thinking clearly in writing and speech','memorising literary terms'],2),
  ('Setting a literacy goal for high school means ___.',['giving up on improving','being satisfied with current skills','identifying a specific area (analytical writing, reading challenging texts, oral communication) where you want to grow and making a concrete plan','only planning which books to read'],2),
  ('Reading widely is important because ___.',['it is only about pleasure','it wastes time','it builds vocabulary, background knowledge, empathy, and critical thinking — across genres, cultures, and perspectives','only fiction counts'],2),
  ('High school English will build on Grade 8 skills by ___.',['starting from scratch','ignoring everything learned in Grade 8','requiring more sophisticated analysis, longer essays, more complex texts, and greater independence as a thinker and writer — the foundations built in Grade 8 are essential','only testing grammar'],2)]),
M('Grade 8 Math: Comprehensive Review','Students review all major Grade 8 math strands.',[
  ('Solve: 5(x − 2) = 3x + 6',['x = 4','x = 8','x = 2','x = 16'],1),
  ('A cylinder has r = 5 cm, h = 12 cm. Volume = ? (π ≈ 3.14)',['940.0 cm³','942.0 cm³','188.4 cm³','314.0 cm³'],1),
  ('The slope of the line −3x + y = 6 is ___.',['−3','6','3','1/3'],2),
  ('Expand and simplify: (2x + 3)(x − 4)',['2x² − 5x − 12','2x² + 5x − 12','2x² − 8x + 3x − 12','2x² − 5x + 12'],0),
  ('A bag has 4 red and 6 blue marbles. P(red, then blue without replacement) = ?',['4/10 × 6/10 = 24/100','4/10 × 6/9 = 24/90 = 4/15','6/10 × 4/9','4/10 × 6/10'],1)]),
Sc('Science: Looking Ahead to Grade 9','Students preview the Grade 9 science curriculum (biology, chemistry, physics, earth science) and connect Grade 8 learning to what comes next.',[
  ('Grade 9 Science includes which four broad areas?',['Cells, Fluids, Optics, Mechanics','Math, History, Language, PE','Biology (biodiversity), Chemistry (atomic theory), Physics (electricity), Earth science (climate and space)','Only biology and chemistry'],2),
  ('Which Grade 8 topic connects most directly to Grade 9 chemistry?',['Optics','Fluid power','Genetics','Cells — understanding cell structure and molecules (DNA, proteins) leads to atomic theory and chemical reactions in Grade 9'],3),
  ('The concept of energy (work, mechanical efficiency) from Grade 8 connects to ___.',['Grade 9 biology','Grade 9 geography','Grade 9 history','Grade 9 physics, which examines electricity, circuits, and energy transfer in more depth'],3),
  ('Studying science in high school will require ___.',['no mathematical reasoning','only memorisation','forgetting Grade 8 concepts','stronger mathematical reasoning, lab skills, and ability to connect evidence to theory — all skills practised in Grade 8'],3),
  ('The scientific method — observation, hypothesis, experiment, analysis, conclusion — is ___.',['only relevant in Grade 8','replaced in high school','a foundation that grows more sophisticated in high school as experiments become more complex and analysis more quantitative','optional in high school'],2)]),
H('History: Becoming an Informed Citizen','Students reflect on how studying history prepares them for democratic participation and lifelong civic engagement.',[
  ('Studying history prepares you for citizenship by ___.',['teaching you only memorised dates','having no connection to the present','developing your ability to evaluate sources, understand context, recognise cause and effect, and think critically about competing narratives — skills essential for navigating a complex modern world','only teaching you about Canadian government'],2),
  ('Historical empathy means ___.',['agreeing with historical actors','judging the past harshly always','trying to understand the perspectives, values, and contexts of people in the past without necessarily endorsing those views','only feeling sad about past tragedies'],2),
  ('Why is it important to know Canadian history as a voter?',['It is not important for voting','Only political science courses teach voting','Historical knowledge helps you understand why current political issues exist, evaluate political claims, and make informed choices that consider the long-term consequences for all Canadians','Only federal election history matters'],2),
  ('The concept of "historical responsibility" means ___.',['personally feeling guilty for past wrongs','ignoring the past','blaming only one group for history','acknowledging that societies can have responsibilities to address historical injustices — even those they did not personally commit — and work toward just outcomes'],3),
  ('The best way to honour those who built and shaped Canada is to ___.',['only celebrate the heroes','pretend history was perfect','criticise everything about the past','understand the full complexity of their stories — achievements and failures — and use that knowledge to build a more just and inclusive Canada for all'],3)]),
]),
day(27,[
L('Exam Preparation: Close Reading Practice','Students practise close reading and analytical response to unseen texts — a key skill for high school and standardised assessments.',[
  ('When approaching an unseen text on a test, you should ___.',['read it once very fast','only skim for key words','read it twice: first for overall understanding, then closely for specific textual details that will support your responses','only look at the questions'],2),
  ('RACES (or a similar response framework) helps structure exam answers by ___.',['making answers longer','only for multiple choice','Restate the question, Answer it, Cite evidence, Explain the evidence, connect to your argument — ensuring all responses are complete and evidence-based','avoiding personal pronouns'],2),
  ('Timed writing differs from essay writing because ___.',['it requires no planning','grammar doesn\'t matter','you don\'t need evidence','you must plan quickly, write efficiently, and prioritise the most important points — strong outlining in the first 2 minutes pays off heavily'],3),
  ('If you don\'t understand a word in an exam passage, you should ___.',['stop writing','ask for a dictionary','use context clues from surrounding sentences to infer the meaning and continue reading','skip the whole question'],2),
  ('The most common error in timed literary response is ___.',['using quotations','analysing evidence','having too much analysis','retelling the plot instead of analysing it — always prioritise insight over summary'],3)]),
M('Pre-High-School Math: Review and Extensions','Students consolidate all Grade 8 math and preview Grade 9 topics: linear equations, quadratics, and analytic geometry extensions.',[
  ('In Grade 9 Math, students will extend linear equations to ___.',['only graphing','only simple equations','systems of inequalities, which find all solutions satisfying a condition rather than one exact answer','only factoring'],2),
  ('The quadratic y = x² produces a ___.',['straight line','circle','parabola','hyperbola'],2),
  ('The distance formula between two points (x₁,y₁) and (x₂,y₂) is ___.',['(x₂ − x₁) + (y₂ − y₁)','|(x₂ − x₁)|','√((x₂−x₁)² + (y₂−y₁)²)','(x₂ + y₂) − (x₁ + y₁)'],2),
  ('Scientific notation is used in Grade 9 science because ___.',['scientists prefer it for aesthetic reasons','it is optional','it doesn\'t apply in high school','very large and very small numbers (atoms, distances in space) are impossible to work with in standard form'],3),
  ('Good mathematical habits include ___.',['showing no work if the answer is obvious','guessing on hard problems','always showing work, checking reasonableness of answers, and being willing to revisit a problem from a different angle','only using calculators'],2)]),
Sc('Science: Lab Skills and Safety Review','Students review scientific inquiry, lab safety, equipment use, and how to write effective lab reports.',[
  ('A hypothesis is ___.',['a proven fact','a random guess','an educated, testable prediction about the outcome of an experiment, based on prior knowledge','the conclusion of an experiment'],2),
  ('The independent variable in an experiment is ___.',['what you measure as output','kept constant','the variable the experimenter deliberately changes','always temperature'],0),
  ('The dependent variable is ___.',['the variable you change','the variable that is kept constant','the variable that responds to the independent variable — what you measure as the outcome','only for science fairs'],2),
  ('A control group in an experiment ___.',['is always the experimental group','is not used in good experiments','receives no treatment, providing a baseline for comparison with the experimental group','must be very large'],2),
  ('A good lab report conclusion ___.',['lists equipment only','copies the procedure','states whether the hypothesis was supported, summarises the data, identifies sources of error, and suggests improvements','only says whether it worked'],2)]),
H('History: The Power of Narrative','Students examine how the stories we tell about history shape national identity, and whose voices have historically been left out of official narratives.',[
  ('Historical narrative refers to ___.',['only textbook history','only dates and facts','the stories we tell about the past — what we include, exclude, emphasise, and interpret — which shape our understanding of who we are','only fiction'],2),
  ('Dominant historical narratives in Canada have historically ___.',['included all voices equally','marginalised or erased Indigenous, Black, and other minority perspectives, presenting European settler experiences as the default Canadian story','been fully inclusive since Confederation','been only negative'],2),
  ('Counter-narratives are important because ___.',['they are always more accurate than dominant narratives','they replace all existing history','they present experiences and perspectives excluded from dominant narratives, creating a fuller, more truthful, and more inclusive account of the past','only one narrative can be true'],2),
  ('The inclusion of diverse voices in Canadian history education ___.',['complicates history unnecessarily','only benefits minority students','creates a more accurate and complete history that helps all Canadians understand the full range of experiences that built this country','should be limited to specific months'],2),
  ('Whose stories most need to be better told in Canadian history?',['Only political leaders','Only military heroes','History is complete','Indigenous peoples, Black Canadians, immigrants, women, and other groups whose experiences have been underrepresented or erased from the mainstream Canadian historical narrative'],3)]),
]),
day(28,[
L('Writing: Letter to Future Self','Students write a formal reflective letter to their future high-school self, synthesising their growth, expressing hopes, and setting intentions.',[
  ('A letter to your future self is a form of ___.',['formal business writing','news writing','argumentative essay','reflective writing that captures your current thoughts, values, and aspirations as a document your future self will return to'],3),
  ('Effective reflective writing ___.',['lists facts without interpretation','avoids personal voice','is analytical and honest — examining not just what happened but what it means, what you learned, and how it changed you','only summarises events'],2),
  ('Including specific details from Grade 8 experiences in the letter ___.',['is irrelevant','makes it too long','makes it impersonal','grounds the reflection in concrete reality and will be more meaningful when your future self reads it'],3),
  ('The tone of a letter to your future self should be ___.',['critical and discouraging','completely formal','entirely casual with no reflection','honest, warm, and thoughtful — like a conversation with someone you trust deeply'],3),
  ('What makes this type of writing meaningful?',['Only the grammar','Only the length','It is a form of self-documentation — capturing who you are at a specific moment in time, which gains value as you grow and change','Only if a teacher grades it'],2)]),
M('Algebra: Inequalities','Students solve one- and two-step inequalities in one variable, graph solutions on a number line, and understand how multiplying/dividing by a negative reverses the inequality sign.',[
  ('An inequality shows ___.',['an exact value','that two expressions are equal','that two expressions are not equal — one is greater than or less than the other','only negative numbers'],2),
  ('Solve: x + 4 > 10',['x > 6','x > 14','x > 4','x = 6'],0),
  ('Solve: −2x < 8',['x < −4','x < 4','x > −4','x > 4'],2),
  ('Why does the inequality sign reverse when multiplying or dividing by a negative?',['It is a random rule','It only happens sometimes','Because the relative order of numbers flips when negated: if 2 < 5, then −2 > −5','To make problems easier'],2),
  ('On a number line, x ≥ 3 is shown with ___.',['an open dot at 3 with arrow to the left','an open dot at 3 with arrow to the right','a closed dot at 3 with arrow to the right','a closed dot at 3 with arrow to the left'],2)]),
Sc('Review: Environmental Science and Stewardship','Students synthesise environmental learning — climate, biodiversity, fluid systems — and develop a personal stewardship plan.',[
  ('The most direct action individuals can take to reduce their carbon footprint is ___.',['only recycling plastic','doing nothing — only governments can help','buying a second car','reducing energy use at home, eating less meat, using public transit, and buying less — especially fast fashion and single-use plastics'],3),
  ('Environmental stewardship means ___.',['leaving all problems to government','ignoring environmental issues','only protesting','responsible management of natural resources — taking only what is needed, reducing waste, and actively working to protect ecosystems for future generations'],3),
  ('Connecting personal choices to environmental outcomes requires ___.',['understanding only global policy','ignoring individual actions','systems thinking — understanding how individual choices aggregate into large-scale effects, and how economic, political, and social systems shape what choices are available','only scientific knowledge'],2),
  ('Indigenous-led conservation models are valuable because ___.',['only Western science is valid','they only apply to forests','Indigenous communities have developed deep ecological knowledge and sustainable management practices over millennia that can complement and enhance modern conservation science','they are purely political'],2),
  ('Why study environmental science in Grade 8?',['It is required but irrelevant','It only helps future scientists','Students who understand environmental systems are better equipped to make responsible personal choices and participate in democratic decisions about environmental policy','Only for students planning outdoor careers'],2)]),
H('History Exam Preparation and Reflection','Students review key concepts, practise historical thinking skills, and reflect on the significance of Grade 8 history for their lives as citizens.',[
  ('The historical thinking concepts taught in Grade 8 History include ___.',['only memorisation of dates','only reading textbooks','chronological thinking, historical perspective taking, cause and consequence, continuity and change, ethical judgement, and historical significance','only map skills'],2),
  ('Historical significance means ___.',['everything that happened is equally important','only recent events matter','some events, people, and ideas have greater impact on the course of history and the lives of people — identifying significance requires analysis and argumentation','only sad events are significant'],2),
  ('Cause and consequence in history means ___.',['events have only one cause','consequences are always immediate','historical events have multiple, interconnected causes, and their consequences can be short-term and long-term, intended and unintended','causes are always economic'],2),
  ('Continuity and change as a historical thinking concept means ___.',['everything always changes','nothing ever changes','examining what has changed over time AND what has remained the same — both are equally important to understand','only wars cause change'],2),
  ('The most valuable skill from Grade 8 History for future citizenship is ___.',['memorising all dates','knowing every Prime Minister\'s name','only drawing historical maps','critical analysis of evidence — the ability to evaluate competing claims, consider multiple perspectives, and form reasoned judgements about complex issues'],3)]),
]),
day(29,[
L('Culminating Activity: Oral Presentation','Students deliver a culminating oral presentation on a significant Canadian historical or contemporary issue, demonstrating research, analysis, and communication skills.',[
  ('A culminating presentation differs from a regular presentation because ___.',['it is always longer','it has no requirements','it requires no research','it synthesises learning across the year, requiring you to connect ideas, demonstrate depth of understanding, and communicate at a high level for a formal audience'],3),
  ('To prepare an effective culminating presentation, you should ___.',['write and read every word','practice once only','avoid visual aids','research your topic deeply, organise your argument clearly, prepare notes (not a full script), and rehearse multiple times to build fluency and confidence'],3),
  ('Using visual aids (slides, maps, images) in a presentation should ___.',['replace your words','contain all your text','not be used in high school','supplement and support your points — visuals should enhance, not replace, your spoken argument'],3),
  ('Answering audience questions well demonstrates ___.',['that you memorised everything','that you read many books','only confidence','genuine deep understanding of your topic — you can engage with what you don\'t know honestly and think on your feet'],3),
  ('The most important quality of a culminating presentation is ___.',['a flashy design','speaking the fastest','the longest presentation','a clearly argued, well-evidenced position that shows you have thought deeply and critically about your topic and its significance'],3)]),
M('Culminating Math: Problem Solving Challenge','Students apply all Grade 8 math concepts to multi-step real-world problems.',[
  ('A cylindrical water tank has r = 2 m and h = 5 m. Volume = ? (π ≈ 3.14)',['62.8 m³','94.2 m³','125.6 m³','31.4 m³'],0),
  ('You invest $2000 at 4% compound interest for 3 years. Approximate value = ?',['$2240','$2253','$2249.73','$2400'],2),
  ('A scatter plot shows height vs. shoe size with a positive correlation. What does this mean?',['Height causes larger feet','Taller people always have the exact same shoe size','Height and shoe size tend to increase together, though correlation does not prove causation','Shoe size determines height'],2),
  ('Solve the system: y = 3x + 1 and 2x + y = 16',['x = 3, y = 10','x = 5, y = 6','x = 3, y = 7','x = 2, y = 7'],0),
  ('A rectangle has perimeter 60 cm. Dimensions for maximum area = ?',['10 cm × 20 cm','12 cm × 18 cm','15 cm × 15 cm = 225 cm²','5 cm × 25 cm'],2)]),
Sc('Science: Year Review and Looking Forward','Students review all four Grade 8 science strands and connect learning to Grade 9 and beyond.',[
  ('Which Grade 8 science topic is most directly extended in Grade 9 biology?',['Fluids','Mechanical systems','Cells, reproduction, genetics, and ecosystems — all deepened in Grade 9 Biology and extended further in senior sciences','Optics'],2),
  ('Fluid dynamics connects to Grade 9 physics through ___.',['optics','genetics','chemistry','the study of forces, pressure, and energy — Grade 9 extends from Pascal\'s principle to broader physics concepts'],3),
  ('The study of light and optics connects to ___.',['only telescope use','Grade 9 physics waves unit, which explores sound and light as waves in much greater depth','Grade 9 chemistry only','no Grade 9 topic'],1),
  ('Genetics from Grade 8 cells connects to ___.',['Grade 9 earth science','Grade 9 physics','Grade 9 Language','Grade 9 biology, which introduces evolution and natural selection — both depend on understanding genetic variation and inheritance'],3),
  ('The scientific thinking skills from Grade 8 — hypothesis, evidence, analysis — are ___.',['replaced in high school','only for Grade 8','not used in real science','the foundation of all high school science and will be applied with increasing sophistication in every future science course'],3)]),
H('Grade 8 History: Final Reflection','Students write a final historical reflection, identifying the most significant idea they will carry forward from Grade 8 History.',[
  ('The most important question in historical thinking is ___.',['What year did it happen?','How many people were involved?','Where exactly did it occur?','So what? — Why does this event, person, or idea matter, and what does it mean for us today?'],3),
  ('If you had to identify the single most significant event in Canadian history studied this year, it would require ___.',['looking it up','no justification','simply picking the biggest battle','arguing for your choice with evidence, explaining its short- and long-term consequences, and considering its impact on different groups'],3),
  ('The history of Canada is best described as ___.',['a story of continuous perfect progress','a simple story of heroes and villains','irrelevant to modern Canada','a complex, ongoing story of competing visions, hard-won rights, profound injustices, remarkable achievements, and unfinished work toward a more just and inclusive nation'],3),
  ('As a future Canadian citizen, the most important thing you can do with your knowledge of history is ___.',['keep it only for yourself','forget it after the test','only share it in class','use it — to vote thoughtfully, engage with public debates, support reconciliation, and work toward the Canada that history has shown us we can and must become'],3),
  ('Grade 8 History ends, but Canadian history ___.',['ended in 2000','is complete','only matters to historians','is still being written — and your generation will be the authors of its next chapter'],3)]),
]),
day(30,[
L('Year-End Celebration: Voices and Stories','A celebration of Grade 8 Language Arts learning. Students share their best writing and reflect on their development as literate, critical thinkers.',[
  ('The journey from Grade 8 to high school in Language Arts involves ___.',['starting over completely','no significant change','a significant step up in analytical complexity, text difficulty, and independence as a writer and thinker — but built on skills you developed this year','only more vocabulary tests'],2),
  ('Your voice as a writer is ___.',['identical to everyone else\'s','only for creative writing','something you\'ve been developing all year — through choices of diction, style, argument, and perspective that make your writing distinctively yours','something only famous writers have'],2),
  ('The texts you\'ve read and analysed this year have ___.',['had no lasting impact','only been for assessment','built your capacity for empathy, critical thinking, and understanding of human experience — literature is one of humanity\'s most powerful tools for making sense of the world','only improved your grammar'],2),
  ('Being a literate person in the 21st century means ___.',['only being able to read words','only being able to write essays','being able to critically read, analyse, and evaluate ALL types of texts — written, visual, digital, and multimodal — and respond with your own thoughtful voice','only reading books'],2),
  ('The most important thing you\'ve learned in Grade 8 Language Arts is ___.',['how to spell better','more vocabulary words','that stories and language are how humans make meaning — and your ability to engage with and create them gives you power to understand and shape the world','to write faster'],2)]),
M('Grade 8 Math: Celebration and Forward Look','A final review celebrating mathematical growth and looking ahead to Grade 9.',[
  ('The most important mathematical habit developed in Grade 8 is ___.',['memorising all formulas','only following rules','working quickly always','mathematical reasoning — the ability to think logically, connect ideas, and explain your thinking rather than just produce answers'],3),
  ('Grade 9 Principles of Mathematics (MPM1D) will extend ___.',['nothing from Grade 8','only geometry','linear relations, algebra, and analytic geometry — the exact topics you developed this year — into a formal credit course','only data management'],2),
  ('Mathematics is connected to other subjects because ___.',['it is not','only science uses math','math only applies to math class','logical reasoning, data analysis, proportional thinking, and spatial reasoning are used across all disciplines from science to social studies to music'],3),
  ('Being good at math means ___.',['never making mistakes','only getting right answers','being fast always','being willing to struggle with challenging problems, learning from errors, making connections between ideas, and persisting until you reach understanding'],3),
  ('The mathematical confidence you\'ve built this year ___.',['will be completely reset in Grade 9','is only useful in Grade 8','has no value beyond school','is a genuine achievement that will support you through high school, post-secondary education, and any career that requires systematic thinking — which is nearly all of them'],2)]),
Sc('Science: Final Synthesis and Celebration','Students celebrate their learning across all Grade 8 science strands and look forward to the broader world of scientific inquiry.',[
  ('Science is a process, not just a body of facts. This means ___.',['only facts matter in science','textbooks have all the answers','science is finished','scientific knowledge is always provisional — built on evidence, open to revision, and advancing through questioning, experimentation, and debate'],3),
  ('The most important scientific skill you\'ve developed in Grade 8 is ___.',['memorising periodic table elements','only conducting experiments','only writing lab reports','asking good questions and thinking carefully about evidence — the foundation of all scientific thinking'],3),
  ('Grade 8 science has explored cells, fluids, mechanical systems, and optics. The common theme is ___.',['they are all unrelated topics','only measurement','all four require only memorisation','all involve understanding how systems work — how components interact, transfer energy, and produce outcomes — a way of thinking applicable far beyond these specific topics'],3),
  ('Science and society are interconnected because ___.',['science is separate from society','only scientists need to understand science','scientists work in a social and political vacuum','scientific discoveries shape society (medicines, technology, energy) and society shapes science (funding priorities, ethical constraints, public demand)'],3),
  ('The most exciting thing about science is ___.',['that all questions are answered','that it never changes','that it is only for experts','that there are still vast unknowns — new diseases, undiscovered particles, unexplored ecosystems, potential life elsewhere — and the scientists who will explore them may be in classrooms like yours right now'],3)]),
H('Farewell: You Are Canadian History','A final message connecting students to their role as participants in the ongoing story of Canada.',[
  ('Every Canadian is part of Canadian history because ___.',['only famous people matter','history is only in the past','only politicians shape Canada','history is made by all people — through the choices they make, the communities they build, and the values they uphold'],3),
  ('Learning from historical mistakes means ___.',['feeling permanently guilty','pretending they didn\'t happen','blaming all people alive today','acknowledging injustice, understanding its roots, and working actively to ensure it is not repeated — especially for Indigenous reconciliation, racism, and inequality'],3),
  ('Canada\'s greatest strength is ___.',['being a military power','having no challenges to overcome','economic wealth only','its ongoing commitment to becoming a more just, inclusive, and diverse nation — a project that is never finished, but always worth pursuing'],3),
  ('Your role as a future Canadian citizen is ___.',['only to vote every four years','to be a passive observer of events','only to follow the news','to engage, to think critically, to care about justice, and to contribute your unique voice and skills to the communities and country you are part of'],3),
  ('Grade 8 is complete. High school begins. Which best describes the journey ahead?',['A completely fresh start with nothing from Grade 8 carrying forward','Only harder versions of the same tests','An expansion of everything you\'ve built — more complex texts, deeper history, more abstract math, and greater opportunity to develop your own voice, values, and vision for the future','Only more difficult and stressful'],2)]),
]),
]

append_to(8, g8b)
print('Grade 8 days 16-30 appended.')
