#!/usr/bin/env python3
"""Grade 9, Days 161-170 -- extends Grade 9 from 160 to 170 days. Topics
chosen after dumping and reading the full Day 1-160 title list (data/grade9.json)
to avoid any overlap, which by this point is exhaustive across all four
subjects: elliptical constructions and implied words, clipped words and
shortenings, analyzing antagonists and their narrative function, writing an
obituary, analyzing product placement in film and television, subject
complements and predicate adjectives, loanwords and borrowed vocabulary in
English, analyzing deus ex machina and plot resolution, and writing a formal
complaint letter; graphing the tangent function and its asymptotes, Fermats
Little Theorem, the law of large numbers, renting versus buying a home,
vector equations of planes, the birthday problem and probability, continued
fractions, concavity and the second derivative, and the distance from a
point to a line using vectors; electrochemistry and galvanic cells, the
photoelectric effect and the dual nature of light, comparative anatomy and
vestigial structures, Earths magnetic field and magnetic reversals, the
cosmic microwave background radiation, blackbody radiation and Wiens Law,
thermochemistry and enthalpy of reaction, plant reproduction (pollination
and seed dispersal), and noise pollution and its effects on wildlife; the
geography of urban congestion pricing and traffic management, wine regions
and terroir, cruise tourism and port cities, international student
migration and study abroad, high-speed rail networks, whaling and marine
mammal conservation, desert agriculture and irrigation innovation, company
towns and resource-based settlements, and cultural festivals and
event-based tourism. Day 170 is a cross-subject review day drawing quiz
content from Days 161-169 of this same batch; its four review titles
("Elliptical Constructions, Antagonists, Obituaries, and Complaint
Letters", "Tangent Graphs, Fermats Little Theorem, Vector Planes, and
Concavity", "Electrochemistry, the Photoelectric Effect, Magnetic
Reversals, and Plant Reproduction", "Congestion Pricing, Cruise Tourism,
High-Speed Rail, and Company Towns") are textually distinct from every
earlier review days title in Days 1-160.

Subject keys for Grade 9 are "Language", "Math", "Science",
"SocialStudies" (same as all earlier Grade 9 batches); SocialStudies
content is Geography-focused, matching the existing convention.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes are avoided entirely (e.g.
"Fermats Little Theorem" not "Fermat's Little Theorem", "Wiens Law" not
"Wien's Law", "Earths" not "Earth's").
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

L9 = 'https://tvolearn.com/pages/grade-9-english'
M9 = 'https://tvolearn.com/pages/grade-9-mathematics'
S9 = 'https://tvolearn.com/pages/grade-9-science'
SS9 = 'https://tvolearn.com/pages/grade-9-geography'
RL, RM, RS, RSS = (
    'TVO Learn: Grade 9 English',
    'TVO Learn: Grade 9 Mathematics',
    'TVO Learn: Grade 9 Science',
    'TVO Learn: Grade 9 Geography',
)


def L(t, s, q):
    return sub('Language', t, s, RL, L9, q)


def M(t, s, q):
    return sub('Math', t, s, RM, M9, q)


def Sc(t, s, q):
    return sub('Science', t, s, RS, S9, q)


def SS(t, s, q):
    return sub('SocialStudies', t, s, RSS, SS9, q)


def _rebalance_answer_positions(days, seed=20260813):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g9_161_170 = [
day(161, [
L('Grammar: Elliptical Constructions and Implied Words',
  'Grade 9 Language strand: an elliptical construction omits a word or phrase that can be clearly understood from context, allowing a sentence to avoid needless repetition while still remaining fully comprehensible to the reader.',
  [('What is an elliptical construction?', ['A sentence structure in which a word or phrase is omitted because it can be understood from context', 'A sentence that repeats the same word or phrase multiple times for emphasis', 'A punctuation mark used only to separate two independent clauses', 'A grammatical rule that forbids the omission of any word under any circumstances'], 0),
   ('Why do writers use elliptical constructions?', ['To avoid needless repetition while keeping the sentence clear', 'To make a sentence as repetitive and confusing as possible', 'Because every sentence in formal writing must contain an omission', 'To remove all verbs from a sentence entirely'], 0),
   ('Which sentence contains an elliptical construction?', ['Maria studied French, and Carlos, Spanish.', 'Maria studied French, and Carlos studied Spanish, and both enjoyed it.', 'Maria studied French. Carlos studied Spanish. Both enjoyed it.', 'Maria and Carlos both studied French together every day.'], 0),
   ('What must be true for an omitted word in an elliptical construction to be acceptable?', ['The omitted word must be clearly recoverable from the surrounding context', 'The omitted word must never appear anywhere else in the sentence', 'The omitted word must always be a noun and nothing else', 'The omitted word must be replaced with a comma in every case'], 0),
   ('How does an elliptical construction differ from an incomplete sentence fragment?', ['An elliptical construction omits words that are still understood by the reader, while a fragment leaves a sentence incomplete and unclear', 'An elliptical construction and a sentence fragment are exactly the same thing', 'A fragment always contains more information than an elliptical construction', 'Elliptical constructions are never grammatically acceptable in any context'], 0)]),
M('Trigonometry: Graphing the Tangent Function and Its Asymptotes',
  'Grade 9 Math strand: the graph of the tangent function repeats every pi radians and has vertical asymptotes wherever cosine equals zero, since tangent is defined as sine divided by cosine and becomes undefined at those points.',
  [('What is the period of the basic tangent function y = tan(x)?', ['Pi', '2 pi', 'Pi divided by two', '4 pi'], 0),
   ('Where do vertical asymptotes occur on the graph of y = tan(x)?', ['Wherever cosine of x equals zero', 'Wherever sine of x equals zero', 'At every integer value of x with no exceptions', 'Tangent graphs never contain any asymptotes'], 0),
   ('Why is the tangent function undefined at its asymptotes?', ['Because tangent equals sine divided by cosine, and division by zero is undefined', 'Because tangent is defined only for negative angles', 'Because sine and cosine are always equal to each other at those points', 'Tangent is undefined everywhere, not just at specific points'], 0),
   ('How does the graph of tangent differ visually from the graphs of sine and cosine?', ['Tangent has vertical asymptotes and an unbounded range, while sine and cosine are continuous and bounded between -1 and 1', 'Tangent, sine, and cosine all look exactly identical when graphed', 'Sine and cosine both have vertical asymptotes, unlike tangent', 'Tangent has a smaller period than both sine and cosine combined'], 0),
   ('What is the general shape of one branch of the tangent graph between two consecutive asymptotes?', ['An increasing curve that passes through zero and approaches positive and negative infinity at its edges', 'A perfectly flat horizontal line with no curvature at all', 'A closed loop that returns exactly to its starting point', 'A decreasing curve that never crosses the x-axis'], 0)]),
Sc('Chemistry: Electrochemistry and Galvanic Cells',
   'Grade 9 Science strand: a galvanic cell generates electrical energy from a spontaneous redox reaction by separating oxidation and reduction into two half-cells connected by a wire and a salt bridge, allowing electrons to flow through an external circuit.',
   [('What does a galvanic cell convert into electrical energy?', ['The chemical energy released by a spontaneous redox reaction', 'The mechanical energy produced by a spinning turbine', 'The thermal energy released by burning fossil fuels', 'The light energy absorbed directly from the sun'], 0),
    ('What is the purpose of a salt bridge in a galvanic cell?', ['To maintain electrical neutrality by allowing ions to flow between the two half-cells', 'To completely stop any flow of ions between the two half-cells', 'To generate heat that powers the entire cell', 'To prevent electrons from ever leaving the cell'], 0),
    ('At which electrode does oxidation occur in a galvanic cell?', ['The anode', 'The cathode', 'Neither electrode, since oxidation never occurs in a galvanic cell', 'Both electrodes simultaneously at all times'], 0),
    ('At which electrode does reduction occur in a galvanic cell?', ['The cathode', 'The anode', 'Neither electrode, since reduction never occurs in a galvanic cell', 'Both electrodes simultaneously at all times'], 0),
    ('Why must the oxidation and reduction half-reactions be physically separated in a galvanic cell?', ['So the electrons released during oxidation are forced to travel through an external wire, generating a usable electric current', 'Separation has no effect on how a galvanic cell functions', 'To prevent the cell from ever producing any electrical energy', 'Because oxidation and reduction cannot occur in the same experiment under any circumstances'], 0)]),
SS('Social Studies: The Geography of Urban Congestion Pricing and Traffic Management',
   'Grade 9 Social Studies (Geography) strand: congestion pricing charges drivers a fee for entering a busy urban area during peak hours, aiming to reduce traffic congestion and pollution while encouraging the use of public transit and generating revenue for infrastructure.',
   [('What is congestion pricing?', ['A fee charged to drivers for entering a busy urban area, typically during peak travel hours', 'A tax applied only to pedestrians walking through a city centre', 'A subsidy that pays drivers to enter a citys downtown core', 'A rule that bans all vehicles from a city permanently'], 0),
    ('What is a primary goal of congestion pricing?', ['To reduce traffic congestion and encourage the use of public transit', 'To increase the total number of private vehicles on city streets', 'To eliminate all forms of public transit within a city', 'To make driving completely free within a citys core'], 0),
    ('What environmental benefit can congestion pricing provide?', ['Reduced vehicle emissions from fewer cars idling in traffic', 'A guaranteed increase in overall vehicle emissions citywide', 'Congestion pricing has no measurable environmental effect at all', 'A complete elimination of all forms of air pollution everywhere'], 0),
    ('How can revenue collected from congestion pricing be used?', ['To fund public transit improvements and other transportation infrastructure', 'It cannot legally be used for any transportation-related purpose', 'It is always distributed directly and exclusively to individual drivers', 'Congestion pricing revenue must be destroyed rather than spent'], 0),
    ('Why might congestion pricing generate public debate in a city?', ['Some residents and businesses may see it as an added cost that unfairly affects those who need to drive', 'Congestion pricing is universally supported with no opposition of any kind', 'The policy has no impact on residents or businesses in any way', 'Public debate about congestion pricing never occurs in any city'], 0)]),
]),
day(162, [
L('Vocabulary: Clipped Words and Shortenings',
  'Grade 9 Language strand: a clipped word forms when a longer word is shortened, dropping one or more syllables while keeping the same essential meaning, such as gym from gymnasium or phone from telephone.',
  [('What is a clipped word?', ['A word formed by shortening a longer word while keeping essentially the same meaning', 'A word created entirely from the initial letters of several other words', 'A word that has no relationship to any longer original word', 'A punctuation mark used to signal an omitted phrase'], 0),
   ('Which of the following is an example of a clipped word?', ['Gym, shortened from gymnasium', 'Radar, formed from radio detection and ranging', 'NASA, formed from the initial letters of an agencys name', 'Brunch, formed by combining breakfast and lunch'], 0),
   ('How does a clipped word differ from an acronym?', ['A clipped word shortens a single existing word, while an acronym forms a new word from the initial letters of several words', 'A clipped word and an acronym are formed in exactly the same way', 'An acronym always shortens a single word by removing its ending', 'Clipped words are always longer than the original word they come from'], 0),
   ('Why might clipped words become common in casual, everyday speech?', ['They are quicker and easier to say than the full original word', 'They are always more difficult to pronounce than the full word', 'Clipped words are forbidden in casual, everyday speech', 'They add unnecessary syllables to a word'], 0),
   ('Which of these pairs correctly shows a full word and its clipped form?', ['Advertisement and ad', 'Breakfast and brunch', 'Smoke and smog', 'Motor and hotel'], 0)]),
M('Number Theory: Fermats Little Theorem',
  'Grade 9 Math strand: Fermats Little Theorem states that if p is a prime number and a is an integer not divisible by p, then a raised to the power p minus 1 is congruent to 1 modulo p, a result with applications in modular arithmetic and cryptography.',
  [('What does Fermats Little Theorem state about a prime p and an integer a not divisible by p?', ['a raised to the power (p minus 1) is congruent to 1 modulo p', 'a raised to the power p is always exactly equal to zero', 'p raised to the power a is congruent to 1 modulo a', 'a divided by p always produces a whole number with no remainder'], 0),
   ('What condition must the number p satisfy for Fermats Little Theorem to apply?', ['p must be a prime number', 'p must always be an even number', 'p must always be equal to one', 'p must be a negative integer'], 0),
   ('What condition must the integer a satisfy for Fermats Little Theorem to apply?', ['a must not be divisible by p', 'a must always be divisible by p', 'a must always be a prime number itself', 'a must always be equal to zero'], 0),
   ('In which modern field is Fermats Little Theorem particularly useful?', ['Cryptography, where it supports methods for testing primality and encrypting data', 'Geometry, where it is used to calculate the area of a triangle', 'Statistics, where it is used to calculate a standard deviation', 'Coordinate geometry, where it locates the midpoint of a line segment'], 0),
   ('How does Fermats Little Theorem build on the modular arithmetic studied earlier in this course?', ['It describes a specific, predictable congruence relationship that holds whenever the modulus is prime', 'It has no connection whatsoever to modular arithmetic', 'It replaces the need for modular arithmetic entirely', 'It only applies when no modulus is used at all'], 0)]),
Sc('Physics: The Photoelectric Effect and the Dual Nature of Light',
   'Grade 9 Science strand: the photoelectric effect occurs when light striking a metal surface ejects electrons, and the observation that this only happens above a minimum light frequency, regardless of intensity, provided key evidence that light behaves as discrete packets of energy called photons.',
   [('What is the photoelectric effect?', ['The emission of electrons from a metal surface when light of sufficient frequency strikes it', 'The bending of light as it passes from one medium into another', 'The complete absorption of all light striking any surface', 'The process by which a metal surface emits sound waves'], 0),
    ('What determines whether electrons are ejected during the photoelectric effect?', ['The frequency of the incoming light, not its intensity', 'The intensity of the incoming light, not its frequency', 'The colour of the metal surface being struck by light', 'The temperature of the room where the experiment occurs'], 0),
    ('What name is given to the discrete packets of light energy involved in the photoelectric effect?', ['Photons', 'Electrons', 'Neutrons', 'Isotopes'], 0),
    ('Why was the photoelectric effect significant in the history of physics?', ['It provided strong evidence that light can behave as particles rather than only as a wave', 'It proved conclusively that light has no wave-like properties whatsoever', 'It showed that metals never interact with light in any way', 'It disproved the existence of electrons entirely'], 0),
    ('What happens to the number of ejected electrons if the intensity of light above the threshold frequency is increased?', ['More electrons are ejected, since more photons strike the surface', 'Fewer electrons are ejected as intensity increases', 'The number of ejected electrons always remains exactly the same', 'No electrons are ever ejected regardless of intensity'], 0)]),
SS('Social Studies: The Geography of Wine Regions and Terroir',
   'Grade 9 Social Studies (Geography) strand: terroir refers to the unique combination of climate, soil, and terrain that gives wine grown in a particular region its distinctive characteristics, making the geography of a wine region central to both its identity and its economic value.',
   [('What does the term terroir refer to?', ['The unique combination of climate, soil, and terrain that shapes the characteristics of wine from a particular region', 'A legal document required to export wine internationally', 'A specific brand name used only by a single winery', 'A type of grape that can only be grown indoors'], 0),
    ('Why might two vineyards located close together produce noticeably different wines?', ['Small differences in soil composition, slope, or microclimate can significantly affect grape development', 'All vineyards located near each other always produce identical wine', 'Grapevines are entirely unaffected by soil or climate conditions', 'Wine production has no connection to the physical geography of a vineyard'], 0),
    ('What climate factor is generally important for grape-growing regions?', ['A climate with distinct seasons and a suitable balance of sunlight and temperature for ripening', 'A climate with absolutely no seasonal variation of any kind', 'Grapevines require constant freezing temperatures year-round', 'Climate has no influence whatsoever on grape cultivation'], 0),
    ('How can the concept of terroir influence the economic value of a wine region?', ['Wines from a distinctive terroir can command higher prices due to their unique and recognizable qualities', 'Terroir always reduces the market value of a regions wine', 'Terroir has no connection to the pricing of wine at all', 'Every wine region in the world produces wine of identical value'], 0),
    ('Why do geographers study wine-producing regions?', ['They illustrate how physical geography can directly shape agricultural production and regional economic identity', 'Wine production has no relevance to the study of geography', 'Wine regions are distributed randomly with no connection to physical geography', 'This topic is considered purely a matter of chemistry, not geography'], 0)]),
]),
day(163, [
L('Reading: Analyzing Antagonists and Their Narrative Function',
  'Grade 9 Language strand: an antagonist is the character or force that opposes the protagonist, creating the central conflict that drives a narrative forward, and an effective antagonist often has understandable motivations rather than acting as pure, unexplained evil.',
  [('What is an antagonist?', ['The character or force that opposes the protagonist and drives the central conflict', 'The narrator of a story who has no influence on the plot', 'A minor character who never appears more than once', 'A setting description with no connection to any character'], 0),
   ('Why do many well-developed antagonists have understandable motivations?', ['It makes the conflict feel more realistic and the antagonist more compelling to readers', 'Motivations make an antagonist completely irrelevant to the plot', 'Readers are never interested in why an antagonist behaves a certain way', 'Understandable motivations always weaken a story rather than strengthen it'], 0),
   ('Can an antagonist be a force rather than a person?', ['Yes, an antagonist can be a natural disaster, a societal system, or another non-human force', 'No, an antagonist must always be a single human character', 'An antagonist can only ever be an animal, never a force of nature', 'Antagonists are always identical to the protagonist in every story'], 0),
   ('How does an antagonist typically relate to the protagonists goals?', ['The antagonist actively works against or blocks the protagonists central goal', 'The antagonist always shares the exact same goal as the protagonist', 'The antagonist has no connection whatsoever to the protagonists goals', 'The antagonist helps the protagonist achieve every goal without conflict'], 0),
   ('Why might an author avoid making an antagonist purely evil with no explained motivation?', ['A one-dimensional antagonist can feel less believable and reduce the tension of the conflict', 'Purely evil antagonists always make a story more believable', 'Explained motivations are strictly forbidden in fiction writing', 'An antagonist with no motivation always creates the strongest possible conflict'], 0)]),
M('Statistics: The Law of Large Numbers',
  'Grade 9 Math strand: the law of large numbers states that as the number of trials in a random experiment increases, the average of the results tends to get closer to the expected theoretical probability, explaining why a fair coin flipped many times approaches a fifty percent heads ratio.',
  [('What does the law of large numbers describe?', ['As the number of trials increases, the average of the results tends to approach the expected theoretical probability', 'As the number of trials increases, results become increasingly unpredictable', 'A single trial always perfectly matches the theoretical probability', 'The law of large numbers applies only to trials involving exactly two outcomes'], 0),
   ('If a fair coin is flipped only 10 times, why might the proportion of heads differ noticeably from 50 percent?', ['With a small number of trials, random variation can cause the observed results to differ from the theoretical probability', 'A fair coin can never produce a result other than exactly 50 percent heads', 'Ten flips always produces exactly five heads with certainty', 'Random variation only occurs when a coin is flipped an extremely large number of times'], 0),
   ('According to the law of large numbers, what happens as the number of coin flips grows into the thousands?', ['The proportion of heads tends to get closer and closer to 50 percent', 'The proportion of heads becomes increasingly unpredictable', 'The proportion of heads always moves further away from 50 percent', 'The coin stops producing random outcomes entirely'], 0),
   ('Why is the law of large numbers important for insurance companies estimating risk?', ['It allows them to predict average outcomes reliably when they observe a very large number of cases', 'It guarantees the exact outcome of any single individual insurance claim', 'Insurance companies never rely on probability or large samples of data', 'The law of large numbers has no application to risk or insurance of any kind'], 0),
   ('What is a common misconception related to the law of large numbers, sometimes called the gamblers fallacy?', ['Believing that a short-term run of one outcome makes the opposite outcome more likely on the very next trial', 'Believing that probabilities never change under any circumstances', 'Believing that large numbers of trials always produce completely random results', 'Believing that a fair coin can never produce heads more than once in a row'], 0)]),
Sc('Biology: Comparative Anatomy and Vestigial Structures',
   'Grade 9 Science strand: comparative anatomy studies the similarities and differences in body structures across different species, and a vestigial structure is a reduced or nonfunctional body part that once served a purpose in an ancestral species, offering evidence for evolutionary relationships.',
   [('What does comparative anatomy study?', ['The similarities and differences in body structures across different species', 'The chemical composition of non-living rock formations', 'The behaviour of a single organism in complete isolation', 'The weather patterns of a specific geographic region'], 0),
    ('What is a vestigial structure?', ['A reduced or largely nonfunctional body part that once served a purpose in an ancestral species', 'A body part that has always been fully functional with no evolutionary history', 'A structure that appears only in plants, never in animals', 'A newly evolved structure with no connection to any ancestral species'], 0),
    ('Which of the following is commonly cited as an example of a vestigial structure in humans?', ['The appendix', 'The heart', 'The lungs', 'The brain'], 0),
    ('How do vestigial structures provide evidence for evolution?', ['They suggest a shared ancestry with species in which the structure was fully functional', 'Vestigial structures have no connection to the study of evolution', 'They prove that no species has ever changed over time', 'They only appear in species with no evolutionary history at all'], 0),
    ('What is a homologous structure, a concept closely related to comparative anatomy?', ['A structure that is similar in different species because they share a common ancestor, even if the structure now serves different functions', 'A structure found only in a single species with no relation to any other', 'A structure that always serves the exact same function in every species', 'A structure that appears randomly with no evolutionary explanation'], 0)]),
SS('Social Studies: The Geography of Cruise Tourism and Port Cities',
   'Grade 9 Social Studies (Geography) strand: cruise tourism brings large numbers of visitors to port cities for short stays, generating significant economic activity for local businesses while also raising concerns about overcrowding, environmental impact, and strain on local infrastructure.',
   [('What is cruise tourism?', ['A form of tourism in which large ships carry passengers to visit multiple port cities, usually for short stays at each location', 'A form of tourism limited exclusively to a single inland city with no coastline', 'A type of tourism that never involves any form of travel by ship', 'A government policy that bans all visitors from arriving by sea'], 0),
    ('What economic benefit can cruise tourism bring to a port city?', ['Increased spending at local shops, restaurants, and tour operators during a ships visit', 'Cruise tourism always eliminates all local economic activity', 'Port cities receive no economic benefit whatsoever from cruise visitors', 'Cruise tourism only benefits cities with no coastal access'], 0),
    ('What is a common concern raised by residents of heavily visited cruise ports?', ['Overcrowding and strain on local infrastructure during peak cruise arrivals', 'Cruise tourism never causes any strain on local infrastructure', 'Residents of cruise ports never express any concerns about tourism', 'Overcrowding only affects cities with no cruise tourism at all'], 0),
    ('What environmental concern is often associated with large cruise ships?', ['Emissions and waste generated by the ships, as well as potential impacts on coastal ecosystems', 'Cruise ships produce no emissions or waste of any kind', 'Cruise ships have no possible impact on coastal ecosystems', 'Environmental concerns only apply to ships that never dock at any port'], 0),
    ('Why might a port citys economy be considered vulnerable if it relies heavily on cruise tourism?', ['A decline in cruise arrivals, such as during a global disruption, can sharply reduce local income tied to visitor spending', 'Port cities that rely on cruise tourism are never affected by changes in visitor numbers', 'Cruise tourism guarantees a citys economy will never experience any decline', 'A citys economy is entirely unrelated to the number of visitors it receives'], 0)]),
]),
day(164, [
L('Writing: Writing an Obituary',
  'Grade 9 Language strand: an obituary is a written notice of a persons death that summarizes their life, achievements, and surviving family members, typically published in a newspaper or online and written in a respectful, factual tone distinct from the more personal, spoken tone of a eulogy.',
  [('What is the primary purpose of an obituary?', ['To provide a written notice of a persons death that summarizes their life and achievements', 'To criticize a persons life choices in a public forum', 'To advertise an unrelated product or upcoming event', 'To provide a detailed weather forecast for the week'], 0),
   ('What tone is typically appropriate for an obituary?', ['A respectful and factual tone', 'A tone that is deliberately sarcastic and mocking throughout', 'A tone appropriate only for a comedic performance', 'A tone with no connection to respect or factual accuracy'], 0),
   ('What information is commonly included in an obituary?', ['The persons life achievements, dates of birth and death, and surviving family members', 'A list of unrelated local news stories from the same week', 'Only the persons favourite colour and hobbies, with no other details', 'A complete transcript of a private conversation'], 0),
   ('How does an obituary differ from a eulogy, studied earlier in this course?', ['An obituary is a written notice typically published for a wide audience, while a eulogy is a spoken tribute delivered at a memorial service', 'An obituary and a eulogy are always delivered aloud at the exact same event', 'A eulogy is always published in a newspaper, while an obituary is never written down', 'There is no meaningful difference between an obituary and a eulogy'], 0),
   ('Why might a family choose to highlight specific achievements or memories in an obituary?', ['To give readers who may not have known the person a meaningful sense of who they were', 'Specific achievements and memories are always forbidden in an obituary', 'To confuse readers about the identity of the person being remembered', 'Obituaries are required by law to contain no personal details at all'], 0)]),
M('Financial Literacy: Renting versus Buying a Home',
  'Grade 9 Math strand: renting a home typically requires lower upfront costs and offers more flexibility, while buying a home requires a larger initial investment such as a down payment but allows a person to build equity over time, making the better choice dependent on individual financial circumstances and goals.',
  [('What is a key financial advantage of renting a home compared to buying?', ['Lower upfront costs and greater flexibility to relocate', 'Renting always costs significantly more than buying in every situation', 'Renters automatically build equity in the property they rent', 'Renting requires a much larger upfront payment than buying'], 0),
   ('What is a key financial advantage of buying a home compared to renting?', ['The ability to build equity in the property over time', 'Buying a home always requires no upfront costs whatsoever', 'Homeowners can never sell their property under any circumstances', 'Buying a home guarantees there will be no ongoing costs of any kind'], 0),
   ('What upfront cost is typically required when buying a home but not when renting?', ['A down payment', 'A monthly grocery bill', 'A public transit fare', 'A streaming service subscription fee'], 0),
   ('Why might renting be a more suitable choice for someone who expects to relocate frequently?', ['Renting avoids the significant costs and effort involved in selling a home on short notice', 'Renters are legally required to remain in the same location for life', 'Relocating is always easier for homeowners than for renters', 'Renting has no connection to a persons flexibility to relocate'], 0),
   ('Why is deciding between renting and buying often described as dependent on individual circumstances?', ['Because factors such as income stability, planned length of stay, and local housing costs vary significantly from person to person', 'Every person faces the exact same financial circumstances regardless of their situation', 'Renting and buying always produce identical financial outcomes for everyone', 'The decision between renting and buying has no connection to income or housing costs'], 0)]),
Sc('Earth Science: Earths Magnetic Field and Magnetic Reversals',
   'Grade 9 Science strand: Earths magnetic field is generated by the movement of molten iron in its outer core, and the geological record shows that this field has reversed polarity many times throughout Earths history, evidence that is preserved in the magnetic alignment of minerals in rock formed at spreading ocean ridges.',
   [('What generates Earths magnetic field?', ['The movement of molten iron in Earths outer core', 'Sunlight reflecting off Earths surface', 'The rotation of the Moon around Earth', 'Wind currents in Earths upper atmosphere'], 0),
    ('What is a magnetic reversal?', ['An event in which Earths magnetic north and south poles switch places', 'A permanent and total loss of Earths magnetic field', 'An event that occurs only on the surface of the Moon', 'A process that happens identically every single day'], 0),
    ('Where is evidence of past magnetic reversals commonly preserved?', ['In the magnetic alignment of minerals within rock formed at spreading ocean ridges', 'In the growth rings found within ancient tree trunks', 'In the layered ice found within polar ice caps only', 'Magnetic reversals leave behind no physical evidence of any kind'], 0),
    ('Why is Earths magnetic field important for life on the planets surface?', ['It helps deflect harmful charged particles from the Sun, protecting the atmosphere and surface', 'It has no connection whatsoever to protecting life on Earth', 'It prevents the Moon from orbiting Earth', 'It is responsible for producing all of Earths rainfall'], 0),
    ('How do scientists use patterns of magnetic reversals recorded in ocean floor rock?', ['To help confirm the process of seafloor spreading and support the theory of plate tectonics', 'To predict the exact weather forecast for the following week', 'Magnetic reversal patterns provide no useful scientific information', 'To measure the exact temperature of Earths outer core directly'], 0)]),
SS('Social Studies: The Geography of International Student Migration and Study Abroad',
   'Grade 9 Social Studies (Geography) strand: international student migration involves students travelling to another country to pursue their education, often drawn by strong universities or specific programs, and host countries can benefit economically from tuition and spending while sometimes facing debate over housing pressure in university cities.',
   [('What is international student migration?', ['The movement of students to another country to pursue their education', 'A policy that forbids students from ever studying outside their home country', 'A term used only to describe students who study entirely online', 'A form of migration that has no connection to education of any kind'], 0),
    ('What commonly attracts international students to a particular host country?', ['Strong universities, specific academic programs, or opportunities not as readily available at home', 'International students are never attracted by any academic factors', 'Students only choose a host country at random with no consideration of programs', 'Host countries actively discourage all international students from applying'], 0),
    ('What economic benefit can international students bring to a host country?', ['Tuition payments and local spending that support universities and surrounding communities', 'International students never contribute any tuition or spending to a host country', 'Host countries always lose money by admitting international students', 'International student migration has no measurable economic effect at all'], 0),
    ('What housing concern is sometimes raised in cities with large numbers of international students?', ['Increased demand for rental housing can add pressure to local housing markets', 'International students never require any form of housing', 'Housing markets are always unaffected by changes in student population', 'Cities with international students always have unlimited housing available'], 0),
    ('Why might some students who study abroad choose to remain in the host country after graduation?', ['They may pursue work opportunities or permanent residency based on experiences and connections built during their studies', 'International students are legally required to leave the host country immediately after graduation', 'Students who study abroad are never permitted to remain in the host country', 'Remaining in a host country after graduation is always against the law'], 0)]),
]),
day(165, [
L('Media Literacy: Analyzing Product Placement in Film and Television',
  'Grade 9 Language strand: product placement occurs when a brand or product is deliberately featured within a film or television show in exchange for payment or promotional consideration, blending advertising with entertainment in a way that a media-literate viewer should learn to recognize.',
  [('What is product placement?', ['The deliberate inclusion of a brand or product within a film or television show, usually in exchange for payment or promotion', 'A completely random, unintentional appearance of an object with no connection to any brand', 'A separate advertisement that appears only between scenes of a film', 'A legal requirement that forbids any brand from appearing on screen'], 0),
   ('Why do companies pay for product placement instead of relying only on traditional commercials?', ['It can reach viewers in a less obvious way, embedding the brand naturally within the story', 'Traditional commercials are always more effective than product placement', 'Companies are legally forbidden from using traditional commercials', 'Product placement guarantees a company will never be recognized by viewers'], 0),
   ('Why is it useful for a media-literate viewer to recognize product placement?', ['It helps the viewer understand that certain products appearing on screen may be a form of paid advertising rather than a neutral creative choice', 'Recognizing product placement has no value to a viewer of any kind', 'Product placement is always clearly labelled with a warning on screen', 'Viewers are never influenced by brands appearing within a story'], 0),
   ('Which of the following would be an example of product placement?', ['A character in a movie prominently using and praising a specific named smartphone brand', 'A character using a plain, unbranded object with no company name visible', 'A commercial that airs during a break between two television programs', 'A billboard advertisement seen only outside a movie theatre'], 0),
   ('How does product placement differ from a traditional television commercial?', ['It is embedded directly within the content of a show rather than appearing as a separate advertisement', 'Product placement and traditional commercials are always identical in every respect', 'A traditional commercial is always embedded directly within a shows plot', 'Product placement never involves payment or promotional consideration of any kind'], 0)]),
M('Geometry: Vector Equations of Planes',
  'Grade 9 Math strand: a plane in three-dimensional space can be described using a vector equation that combines a known point on the plane with two non-parallel direction vectors lying in the plane, or more compactly using a normal vector that is perpendicular to every line within the plane.',
  [('What two types of vectors are commonly used to write the vector equation of a plane?', ['Two non-parallel direction vectors that lie within the plane', 'A single scalar value with no vector information at all', 'Three vectors that are all parallel to each other', 'Only a normal vector, with no reference point required'], 0),
   ('What is a normal vector to a plane?', ['A vector that is perpendicular to every line lying within that plane', 'A vector that lies flat within the plane itself', 'A vector with no defined direction of any kind', 'A vector that is always parallel to the plane'], 0),
   ('Why can a plane be described more compactly using a normal vector and a known point?', ['The normal vector alone captures the planes orientation, avoiding the need for two separate direction vectors', 'A normal vector provides no useful information about a planes orientation', 'Using a normal vector always requires more information than using two direction vectors', 'Planes cannot be described using a normal vector under any circumstances'], 0),
   ('How does the vector equation of a plane build on the vector equation of a line studied earlier in this course?', ['Both use a known point and direction information, but a plane requires two directions instead of just one to define its full extent', 'A plane and a line are described using completely unrelated mathematical concepts', 'A line requires two direction vectors, while a plane requires none at all', 'The vector equation of a plane has no connection to the vector equation of a line'], 0),
   ('If two planes have the same normal vector, what can be concluded about their orientation?', ['The planes are parallel to each other', 'The planes must always intersect at a single point', 'The planes are necessarily perpendicular to each other', 'Nothing can be concluded about the relationship between the planes'], 0)]),
Sc('Astronomy: The Cosmic Microwave Background Radiation',
   'Grade 9 Science strand: the cosmic microwave background radiation is the faint, nearly uniform glow of radiation that fills the observable universe, considered strong evidence for the Big Bang Theory since it represents the cooled remnant of the intense heat that existed shortly after the universes formation.',
   [('What is the cosmic microwave background radiation?', ['The faint, nearly uniform glow of radiation that fills the observable universe', 'A type of radiation found only within Earths own atmosphere', 'A signal broadcast intentionally by an extraterrestrial civilization', 'A form of visible light produced exclusively by nearby stars'], 0),
    ('Why is the cosmic microwave background radiation considered strong evidence for the Big Bang Theory?', ['It represents the cooled remnant of the intense heat present shortly after the universes formation', 'It proves that the universe has always existed in its exact current state', 'It has no connection whatsoever to any theory about the universes origin', 'It was discovered only within the last few years and has no historical significance'], 0),
    ('In what part of the electromagnetic spectrum is this background radiation primarily detected?', ['The microwave region', 'The visible light region only', 'The gamma ray region only', 'The radio wave region used for television broadcasts'], 0),
    ('What does the near uniformity of the cosmic microwave background suggest about the early universe?', ['The early universe was extremely hot and dense and expanded in a broadly consistent way in all directions', 'The early universe was cold and expanded unevenly in only one direction', 'The uniformity of the background radiation suggests nothing about the early universe', 'The early universe never underwent any period of expansion at all'], 0),
    ('How does studying the cosmic microwave background help astronomers understand the age of the universe?', ['Its properties allow scientists to estimate how long ago the universe began expanding from its hot, dense initial state', 'It provides no information relevant to estimating the universes age', 'It can only be used to measure the age of individual stars, not the universe', 'Astronomers have never used this radiation for any scientific purpose'], 0)]),
SS('Social Studies: The Geography of High-Speed Rail Networks',
   'Grade 9 Social Studies (Geography) strand: high-speed rail networks connect major cities with trains capable of significantly higher speeds than conventional rail, reshaping regional geography by shortening travel times, encouraging economic integration between connected cities, and offering an alternative to short-haul air travel.',
   [('What defines a high-speed rail network?', ['A rail system using trains capable of significantly higher speeds than conventional rail, connecting major cities', 'A rail system that only operates within a single small town', 'A network of roads designed exclusively for high-speed automobile travel', 'A rail system that has never connected more than one city'], 0),
    ('How can high-speed rail reshape the economic geography of connected regions?', ['By shortening travel times, it can encourage closer economic integration and commuting between connected cities', 'High-speed rail always reduces economic activity between connected cities', 'High-speed rail has no measurable effect on regional economic integration', 'Shorter travel times always discourage commuting between cities'], 0),
    ('What is one environmental argument in favour of expanding high-speed rail?', ['It can offer a lower-emission alternative to short-haul air travel between nearby cities', 'High-speed rail always produces more emissions than short-haul air travel', 'High-speed rail has no possible connection to reducing emissions', 'Expanding rail networks always increases pollution significantly'], 0),
    ('What geographic factor can make building a new high-speed rail line particularly costly?', ['The need for dedicated, carefully engineered track able to support very high train speeds, especially through mountainous or densely populated terrain', 'High-speed rail lines can always be built using existing conventional track with no modification', 'Terrain and geography have no effect on the cost of building rail infrastructure', 'Building a high-speed rail line never requires any specialized engineering'], 0),
    ('Why might a government invest heavily in high-speed rail despite its high construction cost?', ['To reduce regional travel times, ease congestion on roads and at airports, and support long-term economic integration between cities', 'Governments never consider the long-term benefits of transportation infrastructure', 'High-speed rail provides no benefit to congestion on roads or at airports', 'Investing in high-speed rail always worsens regional economic integration'], 0)]),
]),
day(166, [
L('Grammar: Subject Complements and Predicate Adjectives',
  'Grade 9 Language strand: a subject complement follows a linking verb and renames or describes the subject of a sentence, and a predicate adjective is a specific type of subject complement that describes a quality of the subject rather than renaming it with a noun.',
  [('What is a subject complement?', ['A word or phrase that follows a linking verb and renames or describes the subject of a sentence', 'A word that always follows an action verb and receives its action', 'A punctuation mark placed after every linking verb', 'A phrase that has no grammatical connection to the subject of a sentence'], 0),
   ('What is a predicate adjective?', ['A subject complement that describes a quality of the subject rather than renaming it', 'A verb that always requires a direct object to complete its meaning', 'A noun that renames the subject of a sentence exactly', 'A phrase that can only appear at the very beginning of a sentence'], 0),
   ('In the sentence The soup tastes delicious, what role does the word delicious play?', ['It is a predicate adjective describing the subject soup', 'It is a direct object receiving the action of the verb tastes', 'It is an adverb describing how the soup was prepared', 'It has no grammatical function within the sentence'], 0),
   ('What type of verb is required for a sentence to contain a subject complement?', ['A linking verb, such as a form of the verb to be, or a sensory verb like taste or seem', 'An action verb that always requires a direct object', 'A verb that can never appear with any subject at all', 'Only a verb in the past tense can introduce a subject complement'], 0),
   ('How does a predicate adjective differ from a predicate noun, another type of subject complement?', ['A predicate adjective describes a quality of the subject, while a predicate noun renames the subject with another noun', 'A predicate adjective and a predicate noun are exactly the same grammatical structure', 'A predicate noun always describes a quality rather than renaming the subject', 'Predicate adjectives can only appear in questions, never in statements'], 0)]),
M('Data Management: The Birthday Problem and Probability',
  'Grade 9 Math strand: the birthday problem is a classic probability puzzle that calculates the surprisingly high likelihood that at least two people in a moderately sized group share the same birthday, illustrating how quickly probabilities can grow as the number of possible pairs in a group increases.',
  [('What does the birthday problem calculate?', ['The probability that at least two people in a group share the same birthday', 'The exact date on which the most people in the world were born', 'The average number of days between two peoples birthdays', 'The probability that no person in the world has ever shared a birthday'], 0),
   ('Why is the result of the birthday problem often described as surprising?', ['The probability of a shared birthday becomes quite high with a relatively small group, far fewer than 365 people', 'The probability of a shared birthday is always exactly zero in any group', 'A shared birthday is impossible unless a group contains at least 365 people', 'The birthday problem always produces a probability of exactly 100 percent'], 0),
   ('With approximately 23 people in a room, what is roughly true about the probability that at least two share a birthday?', ['The probability is just over 50 percent', 'The probability is exactly 0 percent', 'The probability is less than 1 percent', 'The probability is always exactly 23 percent'], 0),
   ('Why does the number of possible pairs in a group grow quickly as more people are added?', ['Each new person can be paired with every other person already in the group, so the number of pairs increases much faster than the number of people', 'The number of pairs in a group always increases at exactly the same rate as the number of people', 'Adding more people to a group never changes the number of possible pairs', 'Pairs can only be formed between exactly two people in the entire group'], 0),
   ('How is the probability that at least two people share a birthday typically calculated?', ['By first finding the probability that no two people share a birthday, then subtracting that value from one', 'By directly counting every possible birthday combination for every person on Earth', 'By assuming every person in the group was born on the exact same day', 'The probability of a shared birthday cannot be calculated using any mathematical method'], 0)]),
Sc('Physics: Blackbody Radiation and Wiens Law',
   'Grade 9 Science strand: a blackbody is an idealized object that absorbs and re-emits all radiation that strikes it, and Wiens Law describes how the wavelength at which a blackbody emits the most radiation shifts to shorter wavelengths as its temperature increases, explaining why hotter stars appear bluer and cooler stars appear redder.',
   [('What is an idealized blackbody in physics?', ['An object that absorbs and re-emits all radiation that strikes it', 'An object that reflects all radiation and absorbs none of it', 'An object that emits no radiation under any circumstances', 'An object that exists only at absolute zero temperature'], 0),
    ('What does Wiens Law describe?', ['How the wavelength of peak emission from a blackbody shifts as its temperature changes', 'The exact chemical composition of a distant star', 'The precise distance between Earth and any given star', 'The speed at which light travels through a vacuum'], 0),
    ('According to Wiens Law, what happens to the peak emission wavelength as an objects temperature increases?', ['The peak wavelength shifts to shorter wavelengths', 'The peak wavelength shifts to longer wavelengths', 'The peak wavelength always remains exactly the same', 'The object stops emitting any radiation whatsoever'], 0),
    ('Why do hotter stars generally appear bluer while cooler stars appear redder?', ['Hotter stars emit their peak radiation at shorter, bluer wavelengths, while cooler stars peak at longer, redder wavelengths', 'Star colour has no connection to temperature of any kind', 'Hotter stars always appear redder, while cooler stars always appear bluer', 'All stars emit radiation at exactly the same wavelength regardless of temperature'], 0),
    ('How does blackbody radiation connect to the earlier study of spectroscopy in this course?', ['Both involve analyzing the wavelengths of light emitted by an object to learn about its physical properties', 'Blackbody radiation and spectroscopy are entirely unrelated concepts', 'Spectroscopy only applies to solid objects, never to radiation from stars', 'Blackbody radiation has no connection to the wavelengths of emitted light'], 0)]),
SS('Social Studies: The Geography of Whaling and Marine Mammal Conservation',
   'Grade 9 Social Studies (Geography) strand: commercial whaling once operated on a large global scale before steep population declines led most countries to adopt an international moratorium, and ongoing debates over marine mammal conservation reflect differing cultural, economic, and environmental perspectives across whaling and non-whaling nations.',
   [('What led most countries to adopt an international moratorium on commercial whaling?', ['Steep declines in whale populations caused by large-scale commercial whaling', 'A sudden and unexplained increase in whale populations worldwide', 'Commercial whaling had no measurable effect on whale populations', 'International agreements on whaling have never existed in any form'], 0),
    ('What is a moratorium, in the context of whaling regulation?', ['A temporary or ongoing ban on a particular activity, such as commercial whaling', 'A permanent government subsidy that funds commercial whaling', 'A legal requirement that increases the number of whales hunted each year', 'A type of ship used exclusively for whale conservation research'], 0),
    ('Why do debates over whaling and marine mammal conservation often involve differing cultural perspectives?', ['Some communities have long-standing cultural or subsistence traditions connected to whaling, while others prioritize conservation', 'Every country in the world holds the exact same cultural perspective on whaling', 'Cultural traditions have no connection to debates over whaling policy', 'Whaling has never been connected to any communitys cultural practices'], 0),
    ('What is one argument commonly made in favour of continued strict protections for whale populations?', ['Whale populations recover slowly, and overhunting could threaten their long-term survival', 'Whale populations recover instantly regardless of how many are hunted', 'Strict protections have no effect on the long-term survival of whale populations', 'Overhunting has never had any impact on any whale population'], 0),
    ('Why do geographers study the regulation of activities like whaling?', ['It illustrates how international agreements attempt to balance economic, cultural, and environmental interests across different regions', 'Whaling regulation has no geographic or international dimension worth studying', 'International agreements never address activities related to marine wildlife', 'This topic is considered purely a matter of marine biology, not geography'], 0)]),
]),
day(167, [
L('Vocabulary: Loanwords and Borrowed Vocabulary in English',
  'Grade 9 Language strand: a loanword is a word borrowed from another language and incorporated into English, often without significant translation, reflecting centuries of cultural contact, trade, and conquest that have shaped the English vocabulary.',
  [('What is a loanword?', ['A word borrowed from another language and incorporated into English', 'A word invented entirely within the last decade with no historical origin', 'A punctuation mark borrowed from another writing system', 'A grammatical rule that applies only to verbs'], 0),
   ('Why does English contain such a large number of loanwords?', ['Centuries of cultural contact, trade, and conquest have introduced vocabulary from many other languages', 'English has never had any contact with speakers of other languages', 'Loanwords are strictly forbidden in standard English vocabulary', 'English vocabulary has remained completely unchanged since its earliest form'], 0),
   ('Which of the following is an example of an English loanword borrowed from French?', ['Ballet', 'Sunlight', 'Handshake', 'Bookshelf'], 0),
   ('How does a loanword typically enter everyday use in a new language?', ['It is adopted by speakers, often with little or no change to its original spelling or pronunciation', 'It is banned from use by a formal government committee', 'A loanword must always be translated completely before it can be used', 'Loanwords can only ever appear in academic writing, never in speech'], 0),
   ('Why might studying loanwords help a reader better understand the history of the English language?', ['It reveals which other cultures and languages have historically influenced English vocabulary', 'Loanwords provide no information about the history of a language', 'English vocabulary has developed with no outside cultural influence whatsoever', 'Studying loanwords only reveals information about punctuation, not vocabulary'], 0)]),
M('Number Theory: Continued Fractions',
  'Grade 9 Math strand: a continued fraction expresses a number as a whole number plus a fraction whose denominator is itself a whole number plus another fraction, and this nested process can represent both rational and irrational numbers, offering another way to understand and approximate real numbers.',
  [('What is a continued fraction?', ['A way of expressing a number as a whole number plus a fraction whose denominator is itself a whole number plus another fraction', 'A fraction that can never be simplified under any circumstances', 'A decimal number with an infinite number of repeating digits', 'A fraction with a numerator and denominator that are always equal'], 0),
   ('What happens when a continued fraction is used to represent a rational number?', ['The continued fraction terminates after a finite number of steps', 'The continued fraction always continues forever without ending', 'Rational numbers can never be expressed using a continued fraction', 'The continued fraction becomes undefined immediately'], 0),
   ('What happens when a continued fraction is used to represent an irrational number?', ['The continued fraction continues indefinitely without terminating', 'The continued fraction always terminates after exactly one step', 'Irrational numbers can never be approximated using a continued fraction', 'The continued fraction becomes a whole number with no fractional part'], 0),
   ('Why are continued fractions sometimes used to approximate irrational numbers?', ['Stopping the continued fraction after a few steps produces a simple fraction that closely approximates the original irrational value', 'Continued fractions can never be used to approximate any number', 'Continued fractions always produce a less accurate result than a decimal approximation', 'Irrational numbers cannot be approximated using any mathematical method'], 0),
   ('How does a continued fraction differ from a standard decimal expansion of a number?', ['It expresses the number through a nested sequence of whole-number terms and reciprocals rather than through place value digits', 'A continued fraction and a decimal expansion are always exactly identical', 'A continued fraction can only represent whole numbers, never fractions', 'Decimal expansions can never represent irrational numbers of any kind'], 0)]),
Sc('Chemistry: Thermochemistry and Enthalpy of Reaction',
   'Grade 9 Science strand: thermochemistry studies the heat energy absorbed or released during a chemical reaction, and the enthalpy of reaction measures this heat change at constant pressure, with an exothermic reaction releasing heat to the surroundings and an endothermic reaction absorbing heat from them.',
   [('What does thermochemistry study?', ['The heat energy absorbed or released during chemical reactions', 'The colour changes that occur during a physical change of state', 'The exact mass of every reactant used in a chemical reaction', 'The speed at which a solid dissolves in a liquid'], 0),
    ('What does the enthalpy of reaction measure?', ['The heat change of a chemical reaction at constant pressure', 'The exact volume of gas produced by any chemical reaction', 'The colour of the products formed by a chemical reaction', 'The number of atoms present in a single reactant molecule'], 0),
    ('What happens to the surrounding temperature during an exothermic reaction?', ['The surroundings generally become warmer as heat is released', 'The surroundings generally become cooler as heat is released', 'The surrounding temperature never changes during an exothermic reaction', 'Exothermic reactions always absorb heat rather than release it'], 0),
    ('What happens to the surrounding temperature during an endothermic reaction?', ['The surroundings generally become cooler as heat is absorbed', 'The surroundings generally become warmer as heat is absorbed', 'The surrounding temperature never changes during an endothermic reaction', 'Endothermic reactions always release heat rather than absorb it'], 0),
    ('Why is the sign of the enthalpy change used to classify a reaction as exothermic or endothermic?', ['A negative enthalpy change indicates heat is released, while a positive enthalpy change indicates heat is absorbed', 'The sign of the enthalpy change has no connection to whether heat is released or absorbed', 'A positive enthalpy change always indicates heat is released to the surroundings', 'Enthalpy change can only ever be a positive value in any reaction'], 0)]),
SS('Social Studies: The Geography of Desert Agriculture and Irrigation Innovation',
   'Grade 9 Social Studies (Geography) strand: desert agriculture relies on innovative irrigation methods, such as drip irrigation and groundwater management, to grow crops in regions with very low natural rainfall, allowing some arid regions to become significant agricultural producers despite challenging environmental conditions.',
   [('Why does agriculture in desert regions typically depend heavily on irrigation?', ['Natural rainfall in desert regions is too low to reliably support crop growth without additional water', 'Desert regions always receive more than enough natural rainfall for agriculture', 'Irrigation has no connection to agricultural production in any climate', 'Crops grown in desert regions never require any additional water source'], 0),
    ('What is drip irrigation?', ['A method that delivers water slowly and directly to plant roots, reducing water waste', 'A method that floods an entire field with water all at once', 'A system that removes all water from a field before planting', 'A type of irrigation used only in regions with heavy rainfall'], 0),
    ('Why is drip irrigation particularly valuable in arid, water-scarce regions?', ['It conserves water more effectively than traditional flood irrigation methods', 'Drip irrigation always uses significantly more water than flood irrigation', 'Drip irrigation is only effective in regions with abundant rainfall', 'Water conservation has no relevance to farming in arid regions'], 0),
    ('What environmental concern can arise from heavy reliance on groundwater for desert irrigation?', ['Overuse can deplete groundwater aquifers faster than they can naturally recharge', 'Groundwater aquifers can never be depleted under any circumstances', 'Groundwater use has no connection to long-term water availability', 'Desert irrigation always increases the amount of groundwater available'], 0),
    ('Why might a country invest heavily in desert agriculture despite the challenges of an arid climate?', ['To increase domestic food production and reduce reliance on imported food', 'Desert agriculture always increases a countrys dependence on imported food', 'Arid climates make agricultural investment completely unnecessary', 'Investing in desert agriculture provides no benefit to a countrys food supply'], 0)]),
]),
day(168, [
L('Reading: Analyzing Deus Ex Machina and Plot Resolution',
  'Grade 9 Language strand: deus ex machina describes an unexpected, often implausible event or character that suddenly resolves a storys central conflict, a device that can feel unsatisfying to readers when it appears without earlier foreshadowing or logical connection to the plot.',
  [('What does the term deus ex machina describe?', ['An unexpected, often implausible event or character that suddenly resolves a storys central conflict', 'A character who has been carefully developed throughout an entire story', 'A type of setting description used only in poetry', 'A conflict that is never resolved by the end of a story'], 0),
   ('Why can a deus ex machina resolution feel unsatisfying to readers?', ['It can feel unearned when it appears without earlier foreshadowing or a logical connection to the rest of the plot', 'Readers always find this type of resolution highly satisfying', 'A deus ex machina always strengthens the logical structure of a plot', 'This type of resolution is required in every well-written story'], 0),
   ('Which of the following would be an example of deus ex machina?', ['A previously unmentioned character suddenly appearing to rescue the protagonist with no earlier setup', 'A character escaping danger using a skill the reader saw them practice earlier in the story', 'A conflict that is resolved gradually through a characters careful planning', 'An ending that directly follows from clues established earlier in the narrative'], 0),
   ('How does a well-foreshadowed plot resolution differ from a deus ex machina?', ['A well-foreshadowed resolution is supported by earlier clues or events, while a deus ex machina appears with no logical connection to what came before', 'A well-foreshadowed resolution and a deus ex machina are exactly the same technique', 'A deus ex machina is always foreshadowed carefully throughout a story', 'Foreshadowing has no connection to how a plot is eventually resolved'], 0),
   ('Why might a beginning writer be advised to avoid relying on deus ex machina?', ['It can undermine the tension and internal logic that the writer has built throughout the story', 'Deus ex machina always improves the tension and logic of a story', 'This device is required in order to write a satisfying ending', 'Avoiding this device has no effect on a storys overall quality'], 0)]),
M('Calculus Preview: Concavity and the Second Derivative',
  'Grade 9 Math strand: the second derivative of a function measures how its rate of change is itself changing, and its sign indicates the concavity of the functions graph, with a positive second derivative corresponding to a graph curving upward and a negative second derivative corresponding to a graph curving downward.',
  [('What does the second derivative of a function measure?', ['How the rate of change of the function is itself changing', 'The exact value of the function at a single point only', 'The total area under the functions graph', 'The slope of a straight line connecting two unrelated points'], 0),
   ('What does a positive second derivative indicate about the shape of a functions graph?', ['The graph is concave up, curving upward like a cup', 'The graph is concave down, curving downward like an upside-down cup', 'The graph is a perfectly straight horizontal line', 'The function has no defined value at that point'], 0),
   ('What does a negative second derivative indicate about the shape of a functions graph?', ['The graph is concave down, curving downward like an upside-down cup', 'The graph is concave up, curving upward like a cup', 'The graph is always increasing without any curvature', 'The second derivative has no effect on the shape of a graph'], 0),
   ('What is a point called where the concavity of a graph changes from concave up to concave down, or vice versa?', ['An inflection point', 'A vertical asymptote', 'A y-intercept', 'A removable discontinuity'], 0),
   ('How does the second derivative build on the concept of the first derivative studied earlier in this course?', ['The first derivative measures the rate of change of the original function, while the second derivative measures the rate of change of that first derivative', 'The first and second derivatives always represent exactly the same information', 'The second derivative has no mathematical connection to the first derivative', 'Only the second derivative can be used to describe a functions rate of change'], 0)]),
Sc('Biology: Plant Reproduction: Pollination and Seed Dispersal',
   'Grade 9 Science strand: plant reproduction typically begins with pollination, the transfer of pollen from a flowers male structures to its female structures, often assisted by wind, water, or animal pollinators, followed by seed dispersal, which spreads seeds away from the parent plant to reduce competition and expand its range.',
   [('What is pollination?', ['The transfer of pollen from a flowers male structures to its female structures', 'The process by which a plant absorbs water through its roots', 'The division of a single plant cell into two new cells', 'The process by which a plant releases oxygen at night'], 0),
    ('What role do animal pollinators, such as bees, commonly play in plant reproduction?', ['They help transfer pollen between flowers as they move from plant to plant', 'Animal pollinators have no role in plant reproduction of any kind', 'Bees prevent pollen from ever reaching a flowers female structures', 'Animal pollinators only interact with a plants roots, never its flowers'], 0),
    ('What is seed dispersal?', ['The process by which seeds are spread away from the parent plant', 'The process by which a seed absorbs sunlight for photosynthesis', 'The transfer of pollen between two separate flowers', 'The process by which a plant loses all of its leaves in autumn'], 0),
    ('Why is seed dispersal beneficial to a plant species?', ['It reduces competition for resources with the parent plant and allows the species to colonize new areas', 'Seed dispersal always increases competition between a seed and its parent plant', 'Seed dispersal has no effect on where a plant species can grow', 'Dispersed seeds are always less likely to survive than seeds left near the parent plant'], 0),
    ('Which of the following is a common method of seed dispersal?', ['Wind carrying lightweight, winged seeds away from the parent plant', 'Seeds that are physically unable to move away from a parent plant under any circumstances', 'A process that only occurs in plants that produce no seeds at all', 'Seeds absorbing pollen directly from a nearby flower'], 0)]),
SS('Social Studies: The Geography of Company Towns and Resource-Based Settlements',
   'Grade 9 Social Studies (Geography) strand: a company town is a settlement built and largely controlled by a single company, often to house workers near a mine, mill, or other resource-based operation, and many such towns face economic uncertainty or decline once the resource that supported them is depleted or a company relocates.',
   [('What is a company town?', ['A settlement built and largely controlled by a single company, often to house its workers', 'A large city with no connection to any single company or industry', 'A settlement that is governed exclusively by an elected national government', 'A town built entirely without any economic purpose'], 0),
    ('Why were many company towns historically built near mines or mills?', ['To provide convenient housing and services for workers employed in a nearby resource-based industry', 'Company towns were never built near any resource-based industry', 'Mines and mills have no historical connection to the location of settlements', 'Workers in resource-based industries never required any nearby housing'], 0),
    ('What economic risk do many company towns face over the long term?', ['Decline or abandonment if the resource that supported the towns economy is depleted or the company relocates', 'Company towns always experience continuous economic growth with no risk of decline', 'Depleting a local resource always benefits a company towns economy', 'Company towns are never affected by changes to the resource or company that supports them'], 0),
    ('What services might a company historically have provided directly within a company town?', ['Housing, stores, schools, and other essential community services', 'Company towns never provided any services to their residents', 'Only a national government is permitted to provide services within any town', 'Companies were legally forbidden from operating stores or schools'], 0),
    ('Why do geographers study company towns as part of settlement geography?', ['They illustrate how a single economic activity can shape the location, growth, and eventual decline of an entire community', 'Company towns have no connection to the geographic study of settlements', 'Every settlement in the world developed for identical economic reasons', 'This topic is considered purely a matter of business studies, not geography'], 0)]),
]),
day(169, [
L('Writing: Writing a Formal Complaint Letter',
  'Grade 9 Language strand: a formal complaint letter clearly and respectfully explains a problem with a product or service, states the specific outcome the writer is requesting, and typically includes relevant details such as dates, order numbers, or prior communication to support the request.',
  [('What is the main purpose of a formal complaint letter?', ['To clearly and respectfully explain a problem and request a specific resolution', 'To praise a company for excellent service with no request of any kind', 'To provide an unrelated summary of current news events', 'To advertise a product on behalf of the company being contacted'], 0),
   ('What tone is generally most effective in a formal complaint letter?', ['A respectful and professional tone, even when expressing frustration', 'A tone that is deliberately hostile and insulting throughout', 'A tone with no clear point or request of any kind', 'A tone appropriate only for casual conversation with a close friend'], 0),
   ('What kind of specific details should a formal complaint letter typically include?', ['Relevant details such as dates, order numbers, or a record of prior communication', 'No specific details of any kind, since details are considered unnecessary', 'Only vague, general statements with no supporting evidence', 'Details about an entirely unrelated purchase made by someone else'], 0),
   ('Why should a formal complaint letter clearly state the outcome the writer is requesting?', ['It gives the recipient a clear understanding of what action would resolve the complaint', 'Stating a desired outcome always makes a complaint less likely to be resolved', 'A formal complaint letter should never state what the writer wants', 'Recipients are legally forbidden from responding to a stated request'], 0),
   ('How does a formal complaint letter differ from a letter to the editor, studied earlier in this course?', ['A formal complaint letter is addressed directly to a company or organization to resolve a personal issue, while a letter to the editor addresses a public audience about a broader issue', 'A formal complaint letter and a letter to the editor are always addressed to the exact same audience', 'A letter to the editor is always sent privately to a single company', 'There is no meaningful difference between these two types of letters'], 0)]),
M('Geometry: The Distance from a Point to a Line Using Vectors',
  'Grade 9 Math strand: the shortest distance from a point to a line in space can be found using vectors by constructing a vector from a known point on the line to the external point, then applying the cross product with the lines direction vector to calculate the perpendicular distance.',
  [('What does the shortest distance from a point to a line represent geometrically?', ['The length of the perpendicular segment connecting the point to the line', 'The total length of the entire line itself', 'The distance between two completely unrelated points in space', 'The angle formed between the point and the line'], 0),
   ('What vector operation is commonly used to calculate the distance from a point to a line in three dimensions?', ['The cross product of a connecting vector with the lines direction vector', 'The simple addition of two unrelated vectors', 'Multiplying the coordinates of the point by zero', 'Dividing the direction vector by its own magnitude only'], 0),
   ('Why is the perpendicular distance considered the shortest distance from a point to a line?', ['Any other path from the point to the line would be longer than the perpendicular segment', 'The perpendicular distance is always longer than any other possible path', 'Distance from a point to a line has no single shortest value', 'A perpendicular segment can never be drawn to any line'], 0),
   ('How does this method build on the vector equation of a line studied earlier in this course?', ['It uses the same known point and direction vector that define the line to calculate distance from an external point', 'This method has no connection to the vector equation of a line', 'The vector equation of a line cannot be used to calculate any distance', 'This method requires an entirely different, unrelated equation for the line'], 0),
   ('What type of quantity results from calculating the distance from a point to a line?', ['A single non-negative scalar value representing length', 'A new vector pointing in a random direction', 'A pair of coordinates with no numerical value', 'An angle measured in degrees only'], 0)]),
Sc('Environmental Science: Noise Pollution and Its Effects on Wildlife',
   'Grade 9 Science strand: noise pollution from sources such as traffic, shipping, and industrial activity can interfere with the ability of many animal species to communicate, navigate, and detect predators, disrupting behaviours that depend on sound in both terrestrial and marine ecosystems.',
   [('What is noise pollution?', ['Excessive or disruptive human-generated sound that can negatively affect the environment', 'A form of pollution caused exclusively by chemical waste in water', 'A term that applies only to sound produced by natural sources like wind', 'A type of pollution with no possible effect on any living organism'], 0),
    ('How can noise pollution interfere with wildlife behaviour?', ['It can disrupt an animals ability to communicate, navigate, or detect predators using sound', 'Noise pollution has no effect on any animal behaviour of any kind', 'Noise pollution always improves an animals ability to detect predators', 'Only plants, never animals, are affected by noise pollution'], 0),
    ('Which marine animals are commonly cited as being affected by underwater noise pollution, such as from shipping?', ['Whales, which rely heavily on sound for communication and navigation', 'Animals that live entirely on land, with no connection to the ocean', 'Marine animals are never affected by sound produced by ships', 'Only fish that cannot hear any sound are affected by shipping noise'], 0),
    ('What human activities commonly contribute to noise pollution in ecosystems?', ['Traffic, shipping, and industrial activity', 'Only activities that occur deep underground contribute to noise pollution', 'Human activities never produce any form of noise pollution', 'Noise pollution is caused exclusively by natural weather events'], 0),
    ('Why might chronic noise pollution be especially harmful to species that rely on sound to find mates?', ['It can mask or interfere with mating calls, making it harder for individuals to successfully communicate and reproduce', 'Noise pollution always makes mating calls easier for animals to hear', 'Species that use sound to find mates are never affected by noise pollution', 'Mating behaviour has no connection to an animals ability to hear sound'], 0)]),
SS('Social Studies: The Geography of Cultural Festivals and Event-Based Tourism',
   'Grade 9 Social Studies (Geography) strand: event-based tourism draws visitors to a destination for a specific cultural festival or celebration, temporarily boosting local economic activity while also requiring careful planning to manage crowds, infrastructure, and the preservation of the traditions being celebrated.',
   [('What is event-based tourism?', ['Tourism driven by visitors travelling to a destination for a specific festival or cultural celebration', 'Tourism that occurs only in destinations with no cultural traditions of any kind', 'A form of tourism that never involves any form of travel', 'Tourism that is entirely unrelated to any local celebration or event'], 0),
    ('What economic effect can a major cultural festival have on its host city?', ['A temporary but often significant boost in local spending on accommodation, food, and services', 'Cultural festivals always reduce local spending in a host city', 'Major cultural festivals have no measurable economic effect at all', 'Host cities never experience any change in visitor spending during a festival'], 0),
    ('What infrastructure challenge might a city face when hosting a large cultural festival?', ['Managing large crowds and increased demand on transportation and public services', 'Large festivals never place any additional demand on a citys infrastructure', 'Cities hosting festivals always have unlimited transportation capacity', 'Infrastructure challenges only occur in cities with no festivals at all'], 0),
    ('Why might organizers of a cultural festival be concerned about the effects of rapid tourism growth on the event itself?', ['Rapid growth in visitor numbers can put pressure on traditions and local communities if not carefully managed', 'Rapid tourism growth always strengthens local traditions with no negative effects', 'Organizers of cultural festivals are never concerned about the effects of tourism', 'Traditions and local communities are never affected by an increase in visitors'], 0),
    ('Why do geographers study event-based tourism as part of economic and cultural geography?', ['It shows how a temporary cultural event can create significant, though often short-lived, economic and infrastructural effects on a place', 'Event-based tourism has no connection to economic or cultural geography', 'Cultural festivals never have any effect on the economy of a host city', 'This topic is considered purely a matter of entertainment, not geography'], 0)]),
]),
day(170, [
L('Language Review: Elliptical Constructions, Antagonists, Obituaries, and Complaint Letters',
  'Grade 9 Language strand review: students revisit elliptical constructions, antagonists and their narrative function, writing an obituary, subject complements and predicate adjectives, and writing a formal complaint letter from Days 161-169.',
  [('What is an elliptical construction?', ['A sentence structure in which a word or phrase is omitted because it can be understood from context', 'A sentence that repeats the same word or phrase multiple times for emphasis', 'A punctuation mark used only to separate two independent clauses', 'A grammatical rule that forbids the omission of any word under any circumstances'], 0),
   ('What is an antagonist?', ['The character or force that opposes the protagonist and drives the central conflict', 'The narrator of a story who has no influence on the plot', 'A minor character who never appears more than once', 'A setting description with no connection to any character'], 0),
   ('What is the primary purpose of an obituary?', ['To provide a written notice of a persons death that summarizes their life and achievements', 'To criticize a persons life choices in a public forum', 'To advertise an unrelated product or upcoming event', 'To provide a detailed weather forecast for the week'], 0),
   ('What is a predicate adjective?', ['A subject complement that describes a quality of the subject rather than renaming it', 'A verb that always requires a direct object to complete its meaning', 'A noun that renames the subject of a sentence exactly', 'A phrase that can only appear at the very beginning of a sentence'], 0),
   ('What is the main purpose of a formal complaint letter?', ['To clearly and respectfully explain a problem and request a specific resolution', 'To praise a company for excellent service with no request of any kind', 'To provide an unrelated summary of current news events', 'To advertise a product on behalf of the company being contacted'], 0)]),
M('Math Review: Tangent Graphs, Fermats Little Theorem, Vector Planes, and Concavity',
  'Grade 9 Math strand review: students revisit graphing the tangent function, Fermats Little Theorem, vector equations of planes, continued fractions, and concavity and the second derivative from Days 161-169.',
  [('What is the period of the basic tangent function y = tan(x)?', ['Pi', '2 pi', 'Pi divided by two', '4 pi'], 0),
   ('What condition must the number p satisfy for Fermats Little Theorem to apply?', ['p must be a prime number', 'p must always be an even number', 'p must always be equal to one', 'p must be a negative integer'], 0),
   ('What is a normal vector to a plane?', ['A vector that is perpendicular to every line lying within that plane', 'A vector that lies flat within the plane itself', 'A vector with no defined direction of any kind', 'A vector that is always parallel to the plane'], 0),
   ('What happens when a continued fraction is used to represent an irrational number?', ['The continued fraction continues indefinitely without terminating', 'The continued fraction always terminates after exactly one step', 'Irrational numbers can never be approximated using a continued fraction', 'The continued fraction becomes a whole number with no fractional part'], 0),
   ('What is a point called where the concavity of a graph changes from concave up to concave down, or vice versa?', ['An inflection point', 'A vertical asymptote', 'A y-intercept', 'A removable discontinuity'], 0)]),
Sc('Science Review: Electrochemistry, the Photoelectric Effect, Magnetic Reversals, and Plant Reproduction',
   'Grade 9 Science strand review: students revisit electrochemistry and galvanic cells, the photoelectric effect, Earths magnetic field and magnetic reversals, thermochemistry, and plant reproduction from Days 161-169.',
   [('What does a galvanic cell convert into electrical energy?', ['The chemical energy released by a spontaneous redox reaction', 'The mechanical energy produced by a spinning turbine', 'The thermal energy released by burning fossil fuels', 'The light energy absorbed directly from the sun'], 0),
    ('What determines whether electrons are ejected during the photoelectric effect?', ['The frequency of the incoming light, not its intensity', 'The intensity of the incoming light, not its frequency', 'The colour of the metal surface being struck by light', 'The temperature of the room where the experiment occurs'], 0),
    ('What is a magnetic reversal?', ['An event in which Earths magnetic north and south poles switch places', 'A permanent and total loss of Earths magnetic field', 'An event that occurs only on the surface of the Moon', 'A process that happens identically every single day'], 0),
    ('What does the enthalpy of reaction measure?', ['The heat change of a chemical reaction at constant pressure', 'The exact volume of gas produced by any chemical reaction', 'The colour of the products formed by a chemical reaction', 'The number of atoms present in a single reactant molecule'], 0),
    ('What is pollination?', ['The transfer of pollen from a flowers male structures to its female structures', 'The process by which a plant absorbs water through its roots', 'The division of a single plant cell into two new cells', 'The process by which a plant releases oxygen at night'], 0)]),
SS('Social Studies Review: Congestion Pricing, Cruise Tourism, High-Speed Rail, and Company Towns',
   'Grade 9 Social Studies (Geography) strand review: students revisit urban congestion pricing, cruise tourism and port cities, high-speed rail networks, desert agriculture and irrigation, and company towns from Days 161-169.',
   [('What is congestion pricing?', ['A fee charged to drivers for entering a busy urban area, typically during peak travel hours', 'A tax applied only to pedestrians walking through a city centre', 'A subsidy that pays drivers to enter a citys downtown core', 'A rule that bans all vehicles from a city permanently'], 0),
    ('What is cruise tourism?', ['A form of tourism in which large ships carry passengers to visit multiple port cities, usually for short stays at each location', 'A form of tourism limited exclusively to a single inland city with no coastline', 'A type of tourism that never involves any form of travel by ship', 'A government policy that bans all visitors from arriving by sea'], 0),
    ('What defines a high-speed rail network?', ['A rail system using trains capable of significantly higher speeds than conventional rail, connecting major cities', 'A rail system that only operates within a single small town', 'A network of roads designed exclusively for high-speed automobile travel', 'A rail system that has never connected more than one city'], 0),
    ('What is drip irrigation?', ['A method that delivers water slowly and directly to plant roots, reducing water waste', 'A method that floods an entire field with water all at once', 'A system that removes all water from a field before planting', 'A type of irrigation used only in regions with heavy rainfall'], 0),
    ('What is a company town?', ['A settlement built and largely controlled by a single company, often to house its workers', 'A large city with no connection to any single company or industry', 'A settlement that is governed exclusively by an elected national government', 'A town built entirely without any economic purpose'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g9_161_170)
    append_to(9, g9_161_170)
