#!/usr/bin/env python3
"""Grade 12, Days 131-140 -- extends Grade 12 from 130 to 140 days. Topics
chosen after reading the full existing Day 1-130 title list (see
data/grade12.json) to avoid any overlap. Grade 12 has been heavily mined in
prior batches (especially AdvancedFunctions number theory/discrete math and
Physics named experiments/effects), so this batch specifically hunts for
angles not yet touched: the epic tradition, free verse and Modernist
poetics, the fable and allegory, the anti-novel (Nouveau Roman), metatheatre,
climate fiction, travel writing, translation theory, and the aphorism/
epigram; Eulers totient function, derangements, Bayes theorem, Eulers
formula for planar graphs, generating Pythagorean triples, the Weierstrass
function, Lucas sequences, the birthday problem, and Chebyshev polynomials;
parametric arc length, scalar line integrals, the Laplacian operator,
two-variable Taylor series, Gaussian quadrature, Bernoulli differential
equations, elliptic integrals, the existence and uniqueness theorem, and
polar double integrals; stimulated emission and the laser, Rayleigh
scattering, Wiens displacement law, the Seebeck effect, the Joule-Thomson
effect, the Sagnac effect, Chladni patterns, the physics of lightning, and
GPS relativistic corrections. Day 140 is a review day, following the exact
per-subject review pattern used on Day 120/130: one review lesson per
subject, each quizzing the first five of that subject's nine new topics.

Subject keys for Grade 12 are "English", "AdvancedFunctions",
"Calculus", "Physics" (same as all earlier Grade 12 batches).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote or straight-apostrophe characters are used
anywhere in title/question/summary/option text; apostrophes are avoided
entirely, matching the convention used in the Days 121-130 batch.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

E12 = 'https://tvolearn.com/pages/grade-12-english'
AF12 = 'https://tvolearn.com/pages/grade-12-advanced-functions'
CA12 = 'https://tvolearn.com/pages/grade-12-calculus-and-vectors'
PH12 = 'https://tvolearn.com/pages/grade-12-physics'
RE, RAF, RCA, RPH = (
    'TVO Learn: Grade 12 English',
    'TVO Learn: Grade 12 Advanced Functions',
    'TVO Learn: Grade 12 Calculus and Vectors',
    'TVO Learn: Grade 12 Physics',
)


def E(t, s, q):
    return sub('English', t, s, RE, E12, q)


def AF(t, s, q):
    return sub('AdvancedFunctions', t, s, RAF, AF12, q)


def CA(t, s, q):
    return sub('Calculus', t, s, RCA, CA12, q)


def PH(t, s, q):
    return sub('Physics', t, s, RPH, PH12, q)


def _rebalance_answer_positions(days, seed=20260801):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g12_131_140 = [
day(131, [
E('The Epic Tradition: Oral Composition and the Heroic Journey',
  'Grade 12 English strand: the epic is a long narrative poem, originally composed and transmitted orally, that recounts the heroic deeds of a legendary or historical figure, typically opening in medias res and invoking a muse to authorize the tale.',
  [('What is an epic, in its traditional literary sense?', ['A long narrative poem recounting the heroic deeds of a legendary or historical figure', 'A short lyric poem about a single private feeling', 'A brief prose essay on a historical event', 'A modern screenplay with no poetic structure'], 0),
   ('What does the phrase in medias res describe?', ['Beginning a narrative in the middle of the action rather than at the start', 'Beginning a narrative with a full biography of the hero', 'Ending a narrative without any resolution', 'A rule that forbids flashbacks entirely'], 0),
   ('Why might an epic poet invoke a muse at the opening of the poem?', ['To call on divine inspiration and lend authority to the story that follows', 'To warn readers the story is entirely fictional', 'To introduce a minor comic character', 'To signal that the poem has ended'], 0),
   ('How were epics such as the Iliad and the Odyssey originally composed and transmitted?', ['Orally, through recitation and memory before being written down', 'Entirely in silence with no performance tradition', 'Only as private letters between individuals', 'Exclusively through modern printed editions'], 0),
   ('What kind of protagonist typically anchors an epic narrative?', ['A hero of legendary or historical stature undertaking a significant, often perilous journey', 'An entirely ordinary character with no notable qualities', 'A narrator who never appears in the story', 'A character defined only by comic flaws'], 0)]),
AF('Number Theory: Eulers Totient Function and Counting Coprimes',
   'Grade 12 Advanced Functions strand: Eulers totient function, written phi of n, counts the positive integers up to n that are coprime to n, providing a key tool in number theory and in cryptographic systems such as RSA encryption.',
   [('What does Eulers totient function, phi of n, count?', ['The positive integers up to n that are coprime to n', 'The total number of divisors of n', 'The sum of all prime factors of n', 'The number of even integers less than n'], 0),
    ('What does it mean for two integers to be coprime?', ['Their greatest common divisor is one', 'They are both prime numbers', 'They are exactly equal to one another', 'Their sum is always an even number'], 0),
    ('For a prime number p, what is the value of phi of p?', ['p minus one', 'p itself', 'Zero, always', 'p multiplied by two'], 0),
    ('In which cryptographic system studied in this course does Eulers totient function play a central role?', ['RSA encryption and public-key cryptography', 'A system with no connection to number theory', 'Simple substitution ciphers only', 'A system that avoids all use of prime numbers'], 0),
    ('Why is the totient function considered a useful tool in number theory?', ['It provides a systematic way to measure how many integers share no common factor with a given number', 'It has no practical or theoretical use whatsoever', 'It only applies to the number zero', 'It replaces the need for prime numbers entirely'], 0)]),
CA('Calculus: Arc Length of a Parametric Curve',
   'Grade 12 Calculus strand: the arc length of a curve defined parametrically by x of t and y of t is found by integrating the square root of the sum of the squares of the derivatives of x and y with respect to t, extending arc length calculations to curves that are not simple functions of x.',
   [('How is a parametric curve typically defined?', ['By separate functions x of t and y of t, both depending on a parameter t', 'By a single equation with no parameter involved', 'Only by a table of coordinates with no formula', 'By a function that must always be linear'], 0),
    ('What quantities are combined under the square root in the parametric arc length formula?', ['The squares of the derivatives of x and y with respect to t', 'The squares of x and y themselves, with no derivatives', 'The sum of x and y with no squaring', 'The product of t with itself only'], 0),
    ('Why is the parametric arc length formula useful for curves that fail the vertical line test?', ['Parametric equations can describe such curves even though they are not simple functions of x', 'The vertical line test has no relevance to arc length', 'Parametric curves can never fail the vertical line test', 'Arc length cannot be computed for such curves under any method'], 0),
    ('How does the parametric arc length formula relate to the earlier Cartesian arc length formula studied in this course?', ['Both integrate an expression built from the curves rate of change, adapted to the relevant description of the curve', 'The two formulas share no mathematical relationship', 'Cartesian arc length can never be extended to a parametric description', 'Parametric arc length requires no integration whatsoever'], 0),
    ('In what kind of physical situation might parametric arc length naturally arise?', ['Describing the total distance travelled by an object whose position is given as a function of time', 'A situation with no motion or curve involved', 'A purely static, unchanging measurement', 'A situation where time plays no role whatsoever'], 0)]),
PH('Physics: Stimulated Emission and the Physics of the Laser',
   'Grade 12 Physics strand: a laser produces intense, coherent light through stimulated emission, in which a photon triggers an excited atom to emit a second photon of identical frequency, phase, and direction, amplified within a population inversion sustained by an external energy source.',
   [('What process underlies the operation of a laser?', ['Stimulated emission, in which a photon triggers an excited atom to emit an identical second photon', 'Spontaneous emission with no external trigger of any kind', 'The complete absorption of all light with no emission', 'Radioactive decay of atomic nuclei'], 0),
    ('In stimulated emission, how does the emitted photon compare to the photon that triggered it?', ['It matches it in frequency, phase, and direction', 'It always has a completely different frequency', 'It travels in a random, unrelated direction', 'It has no relationship to the triggering photon whatsoever'], 0),
    ('What condition, in which more atoms occupy an excited state than a lower energy state, is required for laser operation?', ['Population inversion', 'Thermal equilibrium', 'Complete atomic ionization', 'Perfect vacuum with no atoms present'], 0),
    ('What is required to sustain a population inversion in a laser?', ['An external energy source that continually excites atoms to a higher energy state', 'Removing all energy from the system entirely', 'A source that only cools the system to absolute zero', 'No energy input of any kind'], 0),
    ('What key property of laser light distinguishes it from ordinary light sources such as an incandescent bulb?', ['Its coherence, with photons in phase and travelling in a well-defined direction', 'Laser light always has a lower energy than ordinary light', 'Laser light is never visible to the human eye', 'Laser light has no defined frequency at all'], 0)]),
]),
day(132, [
E('Free Verse and Modernist Poetics: Whitman, Pound, and the Break from Metre',
  'Grade 12 English strand: free verse abandons regular metre and rhyme in favour of rhythms closer to natural speech, a shift pioneered by poets such as Walt Whitman and later championed by Modernist writers such as Ezra Pound as a deliberate break from fixed poetic form.',
  [('What does free verse deliberately abandon?', ['Regular metre and a fixed rhyme scheme', 'All use of imagery and figurative language', 'Any division into lines at all', 'The use of the English language itself'], 0),
   ('Whose nineteenth-century poetry is often cited as an early, influential example of free verse?', ['Walt Whitman', 'William Shakespeare', 'Geoffrey Chaucer', 'Alexander Pope'], 0),
   ('What rhythmic quality does free verse often aim to capture?', ['Rhythms closer to natural speech patterns', 'A strict, unvarying drumbeat pattern', 'Complete silence with no rhythm', 'A rhythm borrowed only from Latin poetry'], 0),
   ('How did Modernist poets such as Ezra Pound regard free verse?', ['As a deliberate, purposeful break from fixed traditional poetic form', 'As a mistake to be avoided at all costs', 'As identical in every way to the sonnet', 'As a form with no relationship to Modernism'], 0),
   ('Why might a poet choose free verse over a fixed form such as the sonnet?', ['To gain flexibility in line length and rhythm that better matches the poems content and voice', 'Free verse always requires more rhymes than a sonnet', 'Free verse is required by law for modern poetry', 'A fixed form always communicates more freedom than free verse'], 0)]),
AF('Discrete Math: Derangements and the Hat-Check Problem',
   'Grade 12 Advanced Functions strand: a derangement is a permutation of a set in which no element appears in its original position, classically illustrated by the hat-check problem, which asks for the probability that no person receives their own hat back from a checkroom.',
   [('What defines a derangement of a set?', ['A permutation in which no element appears in its original position', 'A permutation in which every element appears in its original position', 'A set with no elements at all', 'A permutation with exactly one fixed element'], 0),
    ('What classic scenario illustrates the concept of a derangement?', ['The hat-check problem, in which no person receives their own hat back', 'A problem involving only sorted, ordered lists', 'A problem with no random assignment involved', 'A scenario where every person always receives their own item'], 0),
    ('As the number of items grows large, what does the probability of a random permutation being a derangement approach?', ['A value close to one divided by e, roughly 0.368', 'A value that approaches exactly zero', 'A value that approaches exactly one', 'A value that grows without bound'], 0),
    ('What broader mathematical field does the study of derangements belong to?', ['Combinatorics', 'Trigonometry', 'Financial mathematics', 'Basic arithmetic'], 0),
    ('Why might the hat-check problem be a useful teaching example in combinatorics?', ['It gives a concrete, intuitive scenario for exploring permutations with no fixed points', 'It has no connection to permutations at all', 'It only applies to problems involving exactly two items', 'It cannot be generalized beyond hats and people'], 0)]),
CA('Calculus: Line Integrals of Scalar Fields — Mass and Average Value Along a Curve',
   'Grade 12 Calculus strand: the line integral of a scalar field integrates a function of position along a curve with respect to arc length, allowing calculations such as the total mass of a wire with variable density or the average value of a function along a path.',
   [('What does the line integral of a scalar field integrate?', ['A function of position along a curve with respect to arc length', 'A vector field along a closed surface only', 'A constant with no relationship to a curve', 'The area enclosed by a curve'], 0),
    ('What physical quantity can a scalar line integral compute for a wire with variable density?', ['Its total mass', 'Its electric charge only, with no other application', 'Its exact colour', 'Its temperature at a single fixed point'], 0),
    ('How does a line integral of a scalar field differ from a line integral of a vector field, such as one used to compute work?', ['A scalar line integral integrates a scalar-valued function rather than a vector field along the curve', 'The two types of line integral are mathematically identical in every way', 'A scalar line integral never involves a curve', 'A vector line integral cannot be used to compute work under any circumstances'], 0),
    ('What does dividing a scalar line integral by the total arc length of the curve produce?', ['The average value of the function along that curve', 'The exact maximum value of the function on the curve', 'A value unrelated to the function being integrated', 'The total mass of the curve regardless of density'], 0),
    ('How does the scalar line integral build on the earlier study of arc length in this course?', ['It weights each small piece of arc length by the value of a function at that point before summing', 'It ignores arc length entirely in its calculation', 'It replaces arc length with volume', 'Arc length and scalar line integrals are entirely unrelated concepts'], 0)]),
PH('Physics: Rayleigh Scattering and the Colour of the Sky',
   'Grade 12 Physics strand: Rayleigh scattering describes how electromagnetic radiation is scattered by particles much smaller than its wavelength, with shorter, blue wavelengths of sunlight scattered far more strongly than longer, red wavelengths, explaining why the daytime sky appears blue.',
   [('What does Rayleigh scattering describe?', ['The scattering of electromagnetic radiation by particles much smaller than its wavelength', 'The complete absorption of all wavelengths of light equally', 'The scattering of sound waves in a solid material', 'The refraction of light through a lens'], 0),
    ('Which wavelengths of sunlight are scattered most strongly according to Rayleigh scattering?', ['Shorter, blue wavelengths', 'Longer, red wavelengths', 'All wavelengths are scattered by exactly the same amount', 'Only wavelengths outside the visible spectrum'], 0),
    ('Why does the daytime sky typically appear blue rather than red?', ['Blue light is scattered across the sky far more strongly than red light by tiny atmospheric particles', 'Red light is always more abundant in sunlight than blue light', 'The atmosphere absorbs all colours except blue completely', 'The sky has no relationship to scattered sunlight'], 0),
    ('How does the strength of Rayleigh scattering typically depend on wavelength?', ['It increases sharply as wavelength decreases', 'It is completely independent of wavelength', 'It increases as wavelength increases', 'It only occurs for wavelengths longer than red light'], 0),
    ('How does Rayleigh scattering help explain the reddish colour of a sunset?', ['Sunlight passing through more atmosphere at low angles has much of its blue light scattered away, leaving more red and orange light', 'Sunsets have no connection to the scattering of sunlight', 'Blue light is scattered away only at midday, never at sunset', 'Red light is scattered more strongly than blue light at sunset'], 0)]),
]),
day(133, [
E('The Fable and the Allegorical Mode',
  'Grade 12 English strand: a fable is a brief narrative, often featuring animal characters, constructed to teach a moral lesson, and belongs to the broader allegorical mode in which characters and events consistently represent abstract ideas or values beyond the literal story.',
  [('What is a fable typically constructed to do?', ['Teach a moral lesson through a brief narrative', 'Provide a detailed historical record of real events', 'Describe a scientific process in technical language', 'Offer a purely factual news report'], 0),
   ('What kind of characters commonly appear in fables?', ['Animals that speak and act with human characteristics', 'Only real historical figures', 'Only characters with no defined traits', 'Exclusively machines and robots'], 0),
   ('What does it mean for a story to work in the allegorical mode?', ['Its characters and events consistently represent abstract ideas or values beyond the literal story', 'The story refuses to have any symbolic meaning whatsoever', 'The story is written entirely in code with no plot', 'The story can only be understood literally'], 0),
   ('How does a fables moral typically relate to its narrative events?', ['The events are shaped and simplified specifically to illustrate the lesson clearly', 'The moral has no connection to the events of the story', 'The events always contradict the stated moral', 'A fable never states or implies a moral'], 0),
   ('Why might a fable use animal characters rather than human ones?', ['Animal characters can represent human traits and follies with useful distance and simplicity', 'Animal characters make a story impossible to interpret', 'Fables are required to avoid any human relevance', 'Animals cannot be used to represent ideas'], 0)]),
AF('Statistics: Bayes Theorem and Updating Probabilities',
   'Grade 12 Advanced Functions strand: Bayes theorem describes how to update the probability of an event in light of new evidence, relating the probability of a hypothesis given evidence to the probability of the evidence given the hypothesis and the hypothesis prior probability.',
   [('What does Bayes theorem allow a statistician to do?', ['Update the probability of an event in light of new evidence', 'Calculate the exact mean of any data set', 'Determine whether a number is prime', 'Graph a function without any data'], 0),
    ('What is a prior probability, in the context of Bayes theorem?', ['An initial estimate of a hypothesis probability before new evidence is considered', 'The final answer produced after all evidence is considered', 'A probability that must always equal one', 'A value that has no role in Bayes theorem'], 0),
    ('How does Bayes theorem relate the probability of a hypothesis given evidence to other probabilities?', ['It relates it to the probability of the evidence given the hypothesis and the hypothesis prior probability', 'It relates it only to the size of the data set, with no other factors', 'It ignores the hypothesis prior probability entirely', 'It treats all hypotheses as equally likely by definition'], 0),
    ('In what kind of real-world application might Bayes theorem be especially useful?', ['Medical diagnosis, where a test result updates the estimated probability of a disease', 'Situations where no new information is ever available', 'Contexts where probability has no meaning', 'Simple arithmetic with no uncertainty involved'], 0),
    ('How does Bayes theorem connect to the earlier study of conditional probability in this course?', ['It builds directly on conditional probability, providing a formal way to reverse the direction of a conditional relationship', 'It has no relationship to conditional probability', 'It replaces the need for probability entirely', 'Conditional probability and Bayes theorem address entirely unrelated questions'], 0)]),
CA('Calculus: The Laplacian Operator and Harmonic Functions',
   'Grade 12 Calculus strand: the Laplacian operator combines the second partial derivatives of a multivariable function, and a function whose Laplacian equals zero everywhere is called harmonic, a property central to describing steady-state temperature distributions and other equilibrium phenomena.',
   [('What does the Laplacian operator combine?', ['The second partial derivatives of a multivariable function', 'Only the first partial derivatives of a function', 'A single first derivative with no other terms', 'The original function values with no derivatives at all'], 0),
    ('What is a harmonic function?', ['A function whose Laplacian equals zero everywhere in its domain', 'A function that is never differentiable', 'A function whose Laplacian is always equal to one', 'A function defined only at a single point'], 0),
    ('What kind of physical situation is commonly modelled using harmonic functions?', ['A steady-state temperature distribution or other equilibrium phenomenon', 'A situation with constant, rapid change and no equilibrium', 'A purely discrete, non-continuous process', 'A situation with no physical interpretation whatsoever'], 0),
    ('How does the Laplacian operator relate to the earlier study of the divergence of a vector field in this course?', ['The Laplacian of a function can be understood as the divergence of that functions gradient', 'The Laplacian and divergence share no mathematical relationship', 'Divergence only applies to scalar functions, never vector fields', 'The Laplacian eliminates the need for the concept of a gradient'], 0),
    ('In which broader area of applied mathematics does the Laplacian operator commonly appear?', ['The study of diffusion, heat flow, and other equilibrium processes', 'Basic single-variable arithmetic with no derivatives', 'Elementary counting problems in combinatorics', 'Simple linear equations with one variable'], 0)]),
PH('Physics: Wiens Displacement Law and the Colour of Stars',
   'Grade 12 Physics strand: Wiens displacement law states that the wavelength at which a blackbody radiates most intensely is inversely proportional to its temperature, meaning hotter objects, including stars, peak at shorter wavelengths and therefore appear bluer, while cooler objects appear redder.',
   [('What does Wiens displacement law relate?', ['The wavelength of peak blackbody radiation to the objects temperature', 'The mass of an object to its electric charge', 'The volume of a gas to its pressure alone', 'The colour of an object to its chemical composition only'], 0),
    ('According to Wiens law, how does the peak wavelength of radiation change as an objects temperature increases?', ['It shifts to shorter wavelengths', 'It shifts to longer wavelengths', 'It remains completely unchanged regardless of temperature', 'It becomes undefined at high temperature'], 0),
    ('Why do hotter stars typically appear bluer than cooler stars?', ['Their blackbody radiation peaks at shorter, bluer wavelengths', 'Hotter stars emit no visible light at all', 'Blue stars are always cooler than red stars', 'Colour has no relationship to a stars temperature'], 0),
    ('How does Wiens displacement law build on the earlier study of blackbody radiation and Plancks law in this course?', ['It identifies where the peak of the blackbody spectrum described by Plancks law occurs at a given temperature', 'It has no relationship to blackbody radiation or Plancks law', 'It contradicts the predictions of Plancks law', 'It applies only to objects with no temperature at all'], 0),
    ('Why is Wiens displacement law useful to astronomers studying distant stars?', ['It allows a stars surface temperature to be estimated from the colour, or peak wavelength, of its light', 'It has no practical use in astronomy', 'It can only be applied to objects within the solar system', 'It determines a stars mass directly with no other data needed'], 0)]),
]),
day(134, [
E('The Anti-Novel: Nouveau Roman and the Rejection of Convention',
  'Grade 12 English strand: the anti-novel, most closely associated with the French Nouveau Roman movement, rejects traditional elements of fiction such as a clear plot, consistent characters, and an authoritative narrator, instead foregrounding perception, fragmentation, and the instability of meaning.',
  [('What does the anti-novel typically reject?', ['Traditional elements such as a clear plot, consistent characters, and an authoritative narrator', 'All use of written language', 'The existence of any reader whatsoever', 'Every form of punctuation'], 0),
   ('Which French literary movement is most closely associated with the anti-novel?', ['The Nouveau Roman', 'The Romantic movement', 'Naturalism', 'Symbolist theatre alone'], 0),
   ('What does the anti-novel often foreground instead of conventional plot?', ['Perception, fragmentation, and the instability of meaning', 'A strictly chronological, linear timeline', 'A single unambiguous moral lesson', 'An entirely predictable, formulaic structure'], 0),
   ('Why might a Nouveau Roman writer avoid giving characters a stable, consistent identity?', ['To challenge readers expectations about coherent selfhood and traditional characterization', 'Because writing consistent characters is not technically possible', 'Because publishers forbid consistent characters', 'Because readers always prefer inconsistent characters'], 0),
   ('How might reading an anti-novel differ from reading a conventional realist novel?', ['A reader must tolerate ambiguity and piece together meaning without a reliable guiding narrator', 'Reading an anti-novel requires no interpretation at all', 'An anti-novel always provides more narrative certainty than a realist novel', 'The two reading experiences are identical in every way'], 0)]),
AF('Discrete Math: Eulers Formula for Planar Graphs and Polyhedra',
   'Grade 12 Advanced Functions strand: Eulers formula states that for any connected planar graph, or for the network of vertices, edges, and faces of a convex polyhedron, the number of vertices minus the number of edges plus the number of faces always equals two.',
   [('What does Eulers formula for planar graphs and polyhedra state?', ['Vertices minus edges plus faces always equals two', 'Vertices plus edges plus faces always equals zero', 'Vertices minus edges minus faces always equals one', 'Edges alone always equal the number of faces'], 0),
    ('What is a planar graph?', ['A graph that can be drawn on a flat plane with no edges crossing', 'A graph that must always be three-dimensional', 'A graph with no vertices at all', 'A graph that can only represent numbers, not relationships'], 0),
    ('To which three-dimensional geometric objects does Eulers formula also apply?', ['Convex polyhedra, such as a cube or a tetrahedron', 'Objects with no defined vertices or edges', 'Only perfectly flat, two-dimensional shapes', 'Curved surfaces with no edges or vertices whatsoever'], 0),
    ('For a simple cube, how many vertices, edges, and faces does it have, consistent with Eulers formula?', ['Eight vertices, twelve edges, and six faces', 'Four vertices, four edges, and four faces', 'Six vertices, eight edges, and twelve faces', 'Twelve vertices, six edges, and eight faces'], 0),
    ('Why is Eulers formula considered a foundational result in the study of graphs and polyhedra?', ['It reveals a simple, invariant relationship that holds across an enormous range of connected planar structures', 'It only applies to a single specific polyhedron', 'It has no connection to graph theory', 'It contradicts other results in discrete mathematics'], 0)]),
CA('Calculus: Taylor Series for Functions of Two Variables',
   'Grade 12 Calculus strand: the Taylor series of a function of two variables extends the single-variable Taylor expansion by using partial derivatives evaluated at a point, producing a polynomial approximation that incorporates the functions curvature in every direction near that point.',
   [('What does the two-variable Taylor series use in place of ordinary derivatives from the single-variable case?', ['Partial derivatives evaluated at a given point', 'Only the original function values, with no derivatives', 'A single derivative taken with respect to one variable only', 'Random coefficients with no relation to the function'], 0),
    ('What does a two-variable Taylor approximation aim to capture near a given point?', ['The functions curvature in every direction near that point', 'The functions value at every point in its entire domain equally well', 'Only the functions behaviour infinitely far from the point', 'A single straight-line approximation with no curvature at all'], 0),
    ('Which earlier multivariable concept from this course is directly used in constructing the second-order terms of a two-variable Taylor series?', ['The Hessian matrix of second-order partial derivatives', 'The concept of an indefinite integral alone', 'The trapezoid rule for numerical integration', 'The ratio test for series convergence'], 0),
    ('How does the two-variable Taylor series generalize the single-variable Taylor and Maclaurin series studied earlier in this course?', ['It extends the same idea of local polynomial approximation to functions depending on more than one variable', 'It has no relationship to the single-variable Taylor series', 'It only applies to functions of exactly one variable', 'It removes the need for any derivatives whatsoever'], 0),
    ('Why might a two-variable Taylor approximation be useful near a critical point identified using the Hessian matrix?', ['It provides a more detailed local model of the functions shape than the Hessian classification alone', 'It has no use near a critical point', 'It always produces a less accurate result than a single point evaluation', 'Critical points cannot be approximated using Taylor series'], 0)]),
PH('Physics: The Seebeck Effect and Thermoelectric Power Generation',
   'Grade 12 Physics strand: the Seebeck effect occurs when a temperature difference across a junction of two dissimilar conductors generates a small electric voltage, a principle used in thermocouples for temperature measurement and in thermoelectric generators that convert heat directly into electricity.',
   [('What does the Seebeck effect describe?', ['A temperature difference across a junction of two dissimilar conductors generating an electric voltage', 'An electric current generating a magnetic field', 'A mechanical stress generating an electric voltage', 'A voltage generating mechanical deformation in a crystal'], 0),
    ('What everyday device relies on the Seebeck effect to measure temperature?', ['A thermocouple', 'A simple mercury thermometer', 'A barometer', 'A piezoelectric microphone'], 0),
    ('What technology uses the Seebeck effect to convert heat directly into electricity?', ['A thermoelectric generator', 'A nuclear fission reactor core', 'A photovoltaic solar panel', 'A hydroelectric turbine'], 0),
    ('How does the Seebeck effect differ from the Peltier effect studied earlier in this course?', ['The Seebeck effect converts a temperature difference into voltage, while the Peltier effect uses current to produce a temperature difference', 'The two effects are identical in every respect', 'The Seebeck effect has no relationship to temperature at all', 'The Peltier effect only occurs in insulators, never conductors'], 0),
    ('Why must the two conductors forming a Seebeck junction be dissimilar materials?', ['The voltage arises from a difference in how strongly each material responds to a temperature gradient', 'Identical materials always produce a larger Seebeck voltage', 'The materials used have no effect on the resulting voltage', 'Dissimilar materials prevent any voltage from forming'], 0)]),
]),
day(135, [
E('Metatheatre: The Play Within the Play',
  'Grade 12 English strand: metatheatre draws attention to a plays own status as a performance, often through a play within the play, direct address to the audience, or characters who comment self-consciously on the act of staging a drama.',
  [('What does metatheatre draw attention to?', ['A plays own status as a performance', 'Only the historical accuracy of a plays setting', 'The private life of the playwright alone', 'The cost of producing a play'], 0),
   ('What is a play within the play?', ['A performance staged by characters within the larger surrounding drama', 'A play with no characters at all', 'A play performed only once and never repeated', 'A play that exists solely as a written text with no staging'], 0),
   ('How might direct address to the audience function as a metatheatrical device?', ['It breaks the illusion of a sealed fictional world by acknowledging the audiences presence', 'It strengthens the illusion that the audience does not exist', 'It is only ever used in silent films', 'It removes the need for any actors'], 0),
   ('Why might a playwright use metatheatrical techniques?', ['To prompt reflection on the nature of performance, illusion, and reality', 'To make a play entirely indistinguishable from real life', 'To avoid any communication with the audience', 'To eliminate the need for a script'], 0),
   ('Which earlier dramatic tradition studied in this course also self-consciously foregrounds the artificiality of performance?', ['The Theatre of Cruelty and other avant-garde staging traditions', 'Strict, invisible fourth-wall realism with no self-awareness', 'Silent, unstaged private reading only', 'A tradition with no connection to performance at all'], 0)]),
AF('Number Theory: Generating Pythagorean Triples',
   'Grade 12 Advanced Functions strand: a Pythagorean triple is a set of three positive integers satisfying the Pythagorean relationship, and Euclids formula generates every primitive triple from a pair of positive integers, offering a systematic algebraic method for producing whole-number right triangles.',
   [('What is a Pythagorean triple?', ['A set of three positive integers satisfying the Pythagorean relationship', 'Any three integers with no relationship to a right triangle', 'A set of three prime numbers only', 'Three integers that always sum to zero'], 0),
    ('What classic example is the smallest Pythagorean triple?', ['Three, four, and five', 'One, two, and three', 'Two, three, and four', 'Five, six, and seven'], 0),
    ('What does Euclids formula for generating Pythagorean triples use as its starting input?', ['A pair of positive integers with specific conditions', 'A single prime number with no other input', 'A random decimal value', 'An equation with no integer inputs at all'], 0),
    ('What is a primitive Pythagorean triple?', ['A triple in which the three integers share no common factor', 'A triple that includes only even numbers', 'A triple where all three numbers are equal', 'A triple that cannot be verified algebraically'], 0),
    ('Why is generating Pythagorean triples algebraically useful, rather than searching for them by trial and error?', ['It produces every primitive triple systematically, guaranteeing valid whole-number right triangles', 'Trial and error is always faster and more reliable', 'Algebraic generation cannot produce valid triples', 'Pythagorean triples have no algebraic structure at all'], 0)]),
CA('Calculus: Gaussian Quadrature — Optimal Nodes for Numerical Integration',
   'Grade 12 Calculus strand: Gaussian quadrature approximates a definite integral by evaluating the integrand at a small number of strategically chosen, unevenly spaced nodes, achieving greater accuracy for a given number of evaluations than evenly spaced methods such as the midpoint or trapezoid rule.',
   [('What distinguishes Gaussian quadrature from evenly spaced numerical integration methods?', ['It evaluates the integrand at strategically chosen, unevenly spaced nodes', 'It requires evenly spaced nodes exactly like the trapezoid rule', 'It avoids evaluating the integrand at any point', 'It only works for functions with no curvature'], 0),
    ('What advantage does Gaussian quadrature typically offer over methods such as the midpoint or trapezoid rule?', ['Greater accuracy for a given number of function evaluations', 'It always requires far more evaluations for the same accuracy', 'It cannot be applied to any polynomial function', 'It eliminates the need for a definite integral altogether'], 0),
    ('How are the node locations in Gaussian quadrature typically determined?', ['Through the roots of a specific family of orthogonal polynomials', 'By selecting points completely at random', 'By always using only the endpoints of the interval', 'By evenly dividing the interval into equal pieces'], 0),
    ('Why might an engineer prefer Gaussian quadrature when computational evaluations of a function are expensive?', ['It can achieve high accuracy while minimizing the total number of function evaluations required', 'Gaussian quadrature always requires the most evaluations of any numerical method', 'Computational cost is irrelevant to choosing a numerical method', 'Gaussian quadrature cannot be used in engineering applications'], 0),
    ('How does Gaussian quadrature relate to the earlier numerical integration methods studied in this course, such as Simpsons rule?', ['Both approximate a definite integral without requiring an explicit antiderivative, but choose evaluation points differently', 'The two methods share no mathematical relationship', 'Simpsons rule requires no evaluation points at all', 'Gaussian quadrature can only be used when an antiderivative is already known'], 0)]),
PH('Physics: The Joule-Thomson Effect and Real Gas Cooling',
   'Grade 12 Physics strand: the Joule-Thomson effect describes the change in temperature of a real gas as it expands through a valve or porous plug without exchanging heat with its surroundings, a cooling effect exploited in refrigeration and in the liquefaction of gases such as nitrogen and oxygen.',
   [('What does the Joule-Thomson effect describe?', ['The temperature change of a real gas as it expands through a valve without exchanging heat with its surroundings', 'The temperature change of an ideal gas under constant volume', 'The pressure change of a liquid at constant temperature', 'The colour change of a gas as it is compressed'], 0),
    ('For most gases near room temperature, what typically happens to temperature during a Joule-Thomson expansion?', ['The gas cools', 'The gas always heats up substantially', 'The gas temperature never changes under any condition', 'The gas instantly becomes a solid'], 0),
    ('In what practical technology is the cooling from the Joule-Thomson effect directly exploited?', ['Refrigeration and the liquefaction of gases such as nitrogen and oxygen', 'The generation of electric current in a battery', 'The transmission of radio waves', 'The magnetization of a ferromagnetic material'], 0),
    ('Why does the Joule-Thomson effect not occur for an ideal gas?', ['An ideal gas has no intermolecular forces, which are responsible for the temperature change in a real gas', 'Ideal gases always experience a much larger Joule-Thomson effect than real gases', 'Ideal gases cannot expand under any circumstances', 'The Joule-Thomson effect has nothing to do with intermolecular forces'], 0),
    ('How does the Joule-Thomson effect relate to the earlier study of thermodynamics and gas laws in this course?', ['It extends ideal gas reasoning to real gases, where intermolecular interactions produce measurable deviations', 'It has no relationship to thermodynamics or gas laws', 'It only applies to solids, never gases', 'It contradicts the first law of thermodynamics'], 0)]),
]),
day(136, [
E('Climate Fiction (Cli-Fi): Imagining Environmental Futures',
  'Grade 12 English strand: climate fiction, or cli-fi, is a contemporary genre that imagines the human and social consequences of environmental change, using speculative settings to explore themes of loss, adaptation, and responsibility.',
  [('What does climate fiction, or cli-fi, primarily imagine?', ['The human and social consequences of environmental change', 'Purely historical events with no relation to the environment', 'A world with no connection to climate at all', 'Only the technical science of weather forecasting'], 0),
   ('What narrative approach does cli-fi commonly use to explore its themes?', ['Speculative settings, often set in a near or distant future', 'Strictly factual news reporting with no narrative', 'Only autobiographical memoir with no invention', 'A format that excludes any setting whatsoever'], 0),
   ('Which themes are commonly explored in climate fiction?', ['Loss, adaptation, and responsibility in the face of environmental change', 'Themes entirely unrelated to the environment', 'Only comedic misunderstandings between characters', 'Exclusively themes of ancient mythology'], 0),
   ('How does cli-fi relate to the broader tradition of speculative fiction studied elsewhere in this course?', ['It applies speculative and world-building techniques specifically to environmental and climate concerns', 'Cli-fi has no relationship to speculative fiction', 'Speculative fiction never addresses real-world issues', 'Cli-fi rejects every convention of speculative fiction'], 0),
   ('Why might a contemporary author choose cli-fi as a genre for social commentary?', ['It allows imagined futures to dramatize the stakes of present-day environmental choices', 'Cli-fi cannot comment on real-world issues', 'The genre is required to avoid any social commentary', 'Cli-fi focuses solely on unrelated fantasy creatures'], 0)]),
AF('Functions: The Weierstrass Function — Continuous but Nowhere Differentiable',
   'Grade 12 Advanced Functions strand: the Weierstrass function is defined as an infinite sum of scaled cosine terms and provides a classic example of a function that is continuous everywhere yet differentiable nowhere, challenging the nineteenth-century assumption that continuity implied smoothness.',
   [('What makes the Weierstrass function mathematically remarkable?', ['It is continuous everywhere yet differentiable nowhere', 'It is differentiable everywhere with no exceptions', 'It is discontinuous at every single point', 'It has no defined value at any point'], 0),
    ('How is the Weierstrass function typically constructed?', ['As an infinite sum of scaled cosine terms', 'As a single simple linear expression', 'As a finite polynomial of degree two', 'As a function with no formula at all'], 0),
    ('What nineteenth-century mathematical assumption did the Weierstrass function famously challenge?', ['The assumption that a continuous function must also be smooth, or differentiable', 'The assumption that all functions must be linear', 'The assumption that numbers can be negative', 'The assumption that a function must have a domain'], 0),
    ('Why might the Weierstrass function appear jagged or fractal-like when graphed?', ['The infinite sum introduces fine detail and roughness at every scale', 'The graph is always a perfectly smooth straight line', 'The function has no graphical representation', 'Rounding errors are the only source of any roughness'], 0),
    ('What broader mathematical field does the discovery of the Weierstrass function influence?', ['Real analysis and the rigorous study of continuity and differentiability', 'Basic arithmetic with whole numbers', 'Elementary geometry with no functions involved', 'Financial mathematics exclusively'], 0)]),
CA('Calculus: Bernoulli Differential Equations',
   'Grade 12 Calculus strand: a Bernoulli differential equation is a first-order equation containing a term raised to a power of the dependent variable, which can be transformed into a linear differential equation through a substitution, allowing it to be solved using the integrating factor method.',
   [('What distinguishes a Bernoulli differential equation from an ordinary first-order linear equation?', ['It contains a term with the dependent variable raised to a power other than one', 'It contains no derivatives at all', 'It can never involve the dependent variable', 'It is defined only for second-order equations'], 0),
    ('What technique transforms a Bernoulli equation into a linear differential equation?', ['A specific substitution involving the dependent variable', 'Simply ignoring the nonlinear term entirely', 'Converting the equation into a matrix with no substitution', 'Replacing every derivative with a constant'], 0),
    ('Once transformed, what earlier solution method from this course can be applied to a Bernoulli equation?', ['The integrating factor method for first-order linear equations', 'The method of undetermined coefficients only, with no other option', 'A purely graphical method with no algebra', 'The bisection method for root-finding'], 0),
    ('Why are Bernoulli equations considered an important technique to learn in the study of differential equations?', ['They extend solvable methods to a class of nonlinear equations that would otherwise resist a direct linear approach', 'They apply only to equations with no practical use', 'They cannot be solved by any known method', 'They are identical to every other type of differential equation'], 0),
    ('In what kind of applied problem might a Bernoulli differential equation arise?', ['Population growth models that include a nonlinear limiting term', 'A situation with absolutely no rate of change', 'A purely static geometric shape with no variables', 'A problem involving only whole-number counting'], 0)]),
PH('Physics: The Sagnac Effect and Ring Laser Gyroscopes',
   'Grade 12 Physics strand: the Sagnac effect produces a measurable phase shift between two light beams travelling in opposite directions around a rotating closed loop, a principle exploited in ring laser gyroscopes to precisely detect rotation without any external reference point.',
   [('What does the Sagnac effect produce?', ['A measurable phase shift between two light beams travelling in opposite directions around a rotating loop', 'A permanent change in the colour of light passing through a loop', 'A magnetic field generated by rotating light', 'A sudden increase in the speed of light itself'], 0),
    ('What technology exploits the Sagnac effect to detect rotation?', ['A ring laser gyroscope', 'A simple mechanical compass', 'A barometer', 'A piezoelectric sensor'], 0),
    ('What is required to produce a Sagnac phase shift?', ['Rotation of the closed loop through which the two counter-propagating light beams travel', 'A loop that remains perfectly stationary at all times', 'The complete absence of any light source', 'A loop made only of a non-conducting material'], 0),
    ('Why is a ring laser gyroscope valuable for navigation systems, such as those in aircraft?', ['It can precisely detect rotation without relying on any external reference point', 'It requires a constant external satellite signal to function at all', 'It can only detect motion in a straight line, never rotation', 'It has no practical navigational application'], 0),
    ('How does the Sagnac effect connect to the broader study of light and relativity in this course?', ['It demonstrates a measurable optical consequence of rotation, connecting classical optics to relativistic reasoning about light propagation', 'It has no connection to the study of light or relativity', 'It shows that light behaves identically regardless of any rotation', 'It disproves the constancy of the speed of light'], 0)]),
]),
day(137, [
E('Travel Writing: Place, Encounter, and the Outsider Perspective',
  'Grade 12 English strand: travel writing blends observation, narrative, and reflection to record a writers encounter with unfamiliar places and cultures, raising questions about the authority and possible bias of an outsiders perspective.',
  [('What does travel writing typically blend together?', ['Observation, narrative, and reflection on encounters with unfamiliar places and cultures', 'Only technical statistics about a region', 'Purely invented settings with no real place', 'A single unsupported opinion with no description'], 0),
   ('What perspective does a travel writer typically bring to the places they describe?', ['An outsiders perspective, encountering a place as unfamiliar', 'A perspective that is always fully native to the place described', 'A perspective with no viewpoint at all', 'A perspective limited strictly to maps and statistics'], 0),
   ('What question does travel writing often raise about its own point of view?', ['Whether the outsiders perspective introduces bias or limited authority in representing a place', 'Travel writing never raises questions about perspective', 'Only insiders are capable of writing about a place', 'The question of bias never applies to nonfiction writing'], 0),
   ('How does travel writing typically differ from a straightforward guidebook?', ['It incorporates personal narrative and reflection rather than only practical information', 'A guidebook always includes more personal reflection than travel writing', 'The two forms are identical in every respect', 'Travel writing excludes any factual description'], 0),
   ('Why might travel writing be studied alongside other nonfiction forms in this course?', ['It shares techniques of narrative and reflection with forms such as the personal essay and documentary', 'Travel writing has no connection to any other nonfiction form', 'Nonfiction forms cannot be meaningfully compared', 'Travel writing is considered purely fictional'], 0)]),
AF('Number Theory: Lucas Sequences and Generalized Fibonacci Numbers',
   'Grade 12 Advanced Functions strand: a Lucas sequence generalizes the Fibonacci sequence by starting from different initial values while following the same rule that each term equals the sum of the two preceding terms, producing related sequences with their own distinctive number-theoretic properties.',
   [('What rule do Lucas sequences share with the Fibonacci sequence?', ['Each term equals the sum of the two preceding terms', 'Each term is always double the preceding term', 'Each term is the product of all previous terms', 'Each term is chosen at random'], 0),
    ('How does a Lucas sequence generally differ from the standard Fibonacci sequence?', ['It begins from different initial values while following the same recursive rule', 'It uses an entirely different, unrelated recursive rule', 'It contains only even numbers', 'It has no starting values at all'], 0),
    ('What are the first two terms of the classic Lucas numbers sequence?', ['Two and one', 'Zero and one', 'One and one', 'Three and five'], 0),
    ('Why are Lucas sequences of interest in number theory?', ['They display distinctive divisibility and growth properties related to, but distinct from, the Fibonacci numbers', 'They have no mathematical properties worth studying', 'They are identical in every property to the Fibonacci sequence', 'They only ever produce the number zero'], 0),
    ('How does studying Lucas sequences connect to the earlier study of Fibonacci representations in this course?', ['Both rely on the same additive recursive structure, generalized from different starting points', 'The two topics share no mathematical connection', 'Lucas sequences replace the need for the Fibonacci sequence entirely', 'Fibonacci numbers are a special case that excludes any related sequences'], 0)]),
CA('Calculus: Elliptic Integrals and the Pendulum Problem',
   'Grade 12 Calculus strand: elliptic integrals arise when calculating quantities such as arc length along an ellipse or the exact period of a pendulum swinging through a large angle, and generally cannot be expressed using elementary functions, requiring specialized methods or numerical evaluation.',
   [('In what classic physical problem do elliptic integrals commonly arise?', ['Finding the exact period of a pendulum swinging through a large angle', 'Finding the area of a perfect circle', 'Calculating a simple linear velocity', 'Finding the volume of a rectangular box'], 0),
    ('What geometric quantity is also classically associated with elliptic integrals?', ['The arc length along an ellipse', 'The area of a square', 'The volume of a sphere alone', 'The circumference of a perfect circle only'], 0),
    ('Why are elliptic integrals considered mathematically special?', ['They generally cannot be expressed using elementary functions', 'They can always be evaluated using basic algebra alone', 'They never require any numerical methods', 'They are identical to ordinary polynomial integrals'], 0),
    ('How are elliptic integrals typically evaluated in practice when no elementary closed form exists?', ['Using specialized methods or numerical approximation', 'They are simply left unsolved with no approach at all', 'They are always solved using only mental arithmetic', 'They require no calculation of any kind'], 0),
    ('How does the small-angle approximation for a pendulum relate to the need for elliptic integrals?', ['The small-angle approximation avoids elliptic integrals, but a large-angle pendulum requires them for an exact period', 'The small-angle approximation also requires elliptic integrals', 'Elliptic integrals are needed regardless of the pendulums angle', 'A pendulums period never depends on its swing angle at all'], 0)]),
PH('Physics: Chladni Patterns and Standing Waves in Two Dimensions',
   'Grade 12 Physics strand: Chladni patterns form when a flat plate is vibrated at a resonant frequency and fine particles, such as sand, collect along the nodal lines where the plate does not move, visually revealing the two-dimensional standing wave patterns of the plates vibration.',
   [('What causes Chladni patterns to form on a vibrating plate?', ['Fine particles collecting along the nodal lines where the plate does not move', 'Particles collecting randomly with no relationship to vibration', 'The plate melting under intense heat', 'A magnetic field pulling particles into place'], 0),
    ('What is a nodal line, in the context of a vibrating plate?', ['A line along which the plate remains stationary during vibration', 'A line that vibrates with maximum amplitude', 'A line that exists only in three-dimensional objects', 'A line unrelated to the plates motion'], 0),
    ('At what type of frequency must a plate be vibrated to produce a clear Chladni pattern?', ['A resonant frequency of the plate', 'Any frequency at all, with no relationship to resonance', 'A frequency of exactly zero', 'A frequency outside the range of audible sound only'], 0),
    ('How do Chladni patterns relate to the concept of standing waves studied earlier in this course?', ['They provide a visual, two-dimensional demonstration of standing wave nodes and antinodes', 'They have no connection to standing waves', 'Chladni patterns only occur in the absence of any wave motion', 'Standing waves can only exist in one dimension, never two'], 0),
    ('Why might Chladni patterns be used as a teaching demonstration in acoustics and wave physics?', ['They make an otherwise invisible vibrational pattern directly visible using simple materials', 'They have no educational value in physics', 'They can only be observed using expensive specialized equipment', 'They demonstrate a phenomenon unrelated to sound or vibration'], 0)]),
]),
day(138, [
E('Translation Theory: Fidelity, Domestication, and Foreignization',
  'Grade 12 English strand: translation theory examines the choices a translator makes between fidelity to a source texts literal meaning and readability in the target language, including the contrasting strategies of domestication, which adapts a text to feel familiar, and foreignization, which preserves its foreignness.',
  [('What central tension does translation theory examine?', ['The balance between fidelity to a source texts meaning and readability in the target language', 'Whether a text should be translated at all, with no other consideration', 'The cost of printing a translated book', 'The length of the original text alone'], 0),
   ('What does a domesticating translation strategy aim to do?', ['Adapt a text to feel familiar to readers in the target language and culture', 'Preserve every unfamiliar feature of the original culture with no adaptation', 'Remove all meaning from the original text', 'Translate a text word for word with no regard for readability'], 0),
   ('What does a foreignizing translation strategy aim to preserve?', ['The foreignness and distinct cultural texture of the original text', 'A translations complete familiarity to the target audience', 'The physical binding of the original book', 'The publication date of the original text'], 0),
   ('Why might translators disagree about whether fidelity or readability should be prioritized?', ['Strict literal fidelity can sometimes produce awkward, unclear prose in the target language, creating a genuine trade-off', 'There is never any disagreement among translators', 'Fidelity and readability always align perfectly with no tension', 'Readability is considered irrelevant to translation entirely'], 0),
   ('How does studying translation theory connect to the study of literature in translation elsewhere in this course?', ['It reveals how translation choices shape the version of a text that reaches a new audience', 'Translation theory has no relevance to reading translated literature', 'Every translation of a text is always identical', 'Translation choices never affect a readers experience of a text'], 0)]),
AF('Probability: The Birthday Problem and Coincidence in Large Groups',
   'Grade 12 Advanced Functions strand: the birthday problem asks how many people must be in a group before there is a better than even chance that two of them share a birthday, with the surprising answer, just twenty-three, illustrating how quickly coincidence probabilities grow in combinatorial settings.',
   [('What does the birthday problem ask?', ['How many people must be in a group before there is a better than even chance two share a birthday', 'How many days are in a year', 'How many people have the same favourite colour', 'How many months contain thirty-one days'], 0),
    ('What is the surprisingly small number of people needed for a better than even chance of a shared birthday?', ['Twenty-three', 'One hundred eighty-three', 'Three hundred sixty-five', 'Fifty'], 0),
    ('Why is the answer to the birthday problem often described as counterintuitive?', ['The number of people required is far smaller than most peoples initial intuition suggests', 'The number of people required is far larger than anyone expects', 'The problem has no numerical answer at all', 'Most people correctly guess the answer immediately'], 0),
    ('What combinatorial idea explains why shared-birthday probability grows so quickly with group size?', ['The number of possible pairs of people grows much faster than the number of people itself', 'The number of possible pairs grows more slowly than the number of people', 'Group size has no effect on the number of possible pairs', 'Only exact matches of triplets are ever counted'], 0),
    ('How does the birthday problem relate to the broader study of probability and counting in this course?', ['It applies combinatorial counting of pairs to a surprising, easily testable probability question', 'It has no connection to combinatorics or counting', 'It is purely a geography question with no mathematics', 'It contradicts the basic principles of probability'], 0)]),
CA('Calculus: The Existence and Uniqueness Theorem for Differential Equations',
   'Grade 12 Calculus strand: the existence and uniqueness theorem gives conditions, typically involving continuity of the differential equation and its derivative with respect to the dependent variable, under which an initial value problem is guaranteed to have exactly one solution near the initial point.',
   [('What does the existence and uniqueness theorem guarantee, when its conditions are met?', ['That an initial value problem has exactly one solution near the initial point', 'That a differential equation has infinitely many unrelated solutions', 'That no differential equation can ever be solved', 'That every equation has exactly zero solutions'], 0),
    ('What kind of problem does the existence and uniqueness theorem typically address?', ['An initial value problem for a differential equation', 'A definite integral with no initial condition', 'A basic algebraic equation with no derivatives', 'A geometry problem involving only static shapes'], 0),
    ('What property of the differential equation is typically required for the theorem to apply?', ['Continuity of the equation and its derivative with respect to the dependent variable', 'The equation must be discontinuous everywhere', 'The equation must have no dependent variable at all', 'The equation must always be exactly linear with no exceptions'], 0),
    ('Why is a guarantee of uniqueness valuable when solving a real-world differential equation model?', ['It confirms that the predicted solution is the only one consistent with the given initial condition, supporting confident interpretation', 'Uniqueness has no practical value in modelling', 'A model is more useful when it has many contradictory solutions', 'Uniqueness guarantees that no solution actually exists'], 0),
    ('How does the existence and uniqueness theorem relate to earlier numerical methods for differential equations studied in this course, such as Eulers method?', ['It provides theoretical assurance that the solution numerical methods approximate is well defined and unique', 'It has no connection to numerical solution methods', 'It proves that numerical methods can never approximate a real solution', 'It shows that Eulers method always produces an incorrect result'], 0)]),
PH('Physics: The Physics of Lightning — Charge Separation and Electrical Breakdown',
   'Grade 12 Physics strand: lightning results from charge separation within a thundercloud, driven by collisions between ice particles and graupel, which builds an electric field strong enough to cause electrical breakdown of the air, producing a sudden, visible discharge between cloud and ground or within the cloud itself.',
   [('What process within a thundercloud leads to the buildup of electric charge?', ['Collisions between ice particles and graupel that separate charge within the cloud', 'The complete absence of any particle motion within the cloud', 'A steady, unchanging temperature throughout the cloud', 'The cloud absorbing all surrounding electric charge instantly'], 0),
    ('What must happen to the air for a lightning discharge to occur?', ['Electrical breakdown, in which the air briefly becomes a conductor', 'The air must become a perfect permanent insulator', 'The air must be entirely removed from the atmosphere', 'The air must freeze completely solid'], 0),
    ('What condition in the electric field between cloud and ground precedes a lightning strike?', ['The electric field becomes strong enough to ionize the surrounding air', 'The electric field drops to exactly zero', 'The electric field remains constant and weak throughout', 'There is no electric field involved in lightning at all'], 0),
    ('How does lightning relate to the earlier study of electric fields and circuits in this course?', ['It illustrates a natural, large-scale example of charge buildup and sudden discharge through a conducting path', 'Lightning has no relationship to electric fields or circuits', 'Lightning only involves magnetic fields, never electric fields', 'Electric circuits can never involve a discharge of any kind'], 0),
    ('Why does thunder typically follow the flash of lightning after a short delay?', ['Light travels far faster than sound, so the sound of the rapidly heated air reaches an observer later', 'Thunder is produced before the lightning flash occurs', 'Sound travels faster than light in air', 'Thunder and lightning always occur at exactly the same instant with no delay'], 0)]),
]),
day(139, [
E('The Aphorism and the Epigram: Compression and Wisdom in Short Form',
  'Grade 12 English strand: the aphorism is a brief, memorable statement expressing a general truth or observation with concentrated wit, closely related to the epigram, a short, pointed piece of writing often turning on a clever or surprising final line.',
  [('What does an aphorism typically express?', ['A general truth or observation, stated briefly and memorably', 'A lengthy, detailed argument spanning many pages', 'A purely factual statistic with no interpretation', 'A random string of unrelated words'], 0),
   ('What quality is most valued in a well-crafted aphorism?', ['Concentrated wit and memorable compression of meaning', 'Maximum length and exhaustive detail', 'Complete avoidance of any meaning', 'Repetition of the same idea many times over'], 0),
   ('What is an epigram, as related to the aphorism?', ['A short, pointed piece of writing often turning on a clever or surprising final line', 'A full-length novel with no concise elements', 'A type of formal legal document', 'A lengthy academic footnote'], 0),
   ('Why might a writer favour the compressed form of the aphorism over an extended essay?', ['Compression can sharpen an idea and make it more memorable and quotable', 'Compression always weakens an ideas impact', 'Aphorisms are incapable of expressing any meaning', 'Short forms are never memorable to readers'], 0),
   ('How does the aphorisms use of compression relate to other short literary forms studied in this course, such as flash fiction?', ['Both forms rely on concentrated language to achieve a strong effect within a small space', 'The aphorism and flash fiction share no stylistic qualities whatsoever', 'Short forms are considered inferior to long forms in every case', 'Compression is unique to the aphorism alone among literary forms'], 0)]),
AF('Functions: Chebyshev Polynomials and Optimal Approximation',
   'Grade 12 Advanced Functions strand: Chebyshev polynomials form a special sequence of polynomials defined through trigonometric identities, and are prized in approximation theory because choosing evaluation points based on their roots minimizes the maximum error when approximating a function by a polynomial.',
   [('Through what kind of identities are Chebyshev polynomials commonly defined?', ['Trigonometric identities involving cosine', 'Identities involving only whole-number addition', 'Identities with no connection to trigonometry', 'Identities defined solely through logarithms'], 0),
    ('What property makes Chebyshev polynomials especially valuable in approximation theory?', ['Choosing evaluation points based on their roots minimizes the maximum approximation error', 'They guarantee an approximation error of exactly zero in every case', 'They eliminate the need for polynomials in approximation', 'They apply only to functions with no curvature'], 0),
    ('How do Chebyshev polynomials relate to earlier approximation methods studied in this course, such as Pade approximants?', ['Both aim to approximate a function more effectively than a naive, evenly spaced approach', 'They share no relationship to any other approximation method', 'Chebyshev polynomials replace the need for functions entirely', 'Pade approximants and Chebyshev polynomials address entirely unrelated problems'], 0),
    ('What term describes minimizing the largest possible error across an approximation interval?', ['Minimax approximation', 'Maximin subtraction', 'Zero-error guarantee', 'Constant-error approximation'], 0),
    ('In which practical fields might Chebyshev polynomials be applied to improve numerical approximation?', ['Numerical analysis and computer algorithms for evaluating functions efficiently', 'Fields with no use for numerical approximation whatsoever', 'Only in fields unrelated to mathematics', 'Exclusively in ancient historical record-keeping'], 0)]),
CA('Calculus: Double Integrals in Polar Coordinates',
   'Grade 12 Calculus strand: evaluating a double integral over a circular or annular region is often simplified by converting to polar coordinates, replacing the area element dx dy with r dr dtheta to account for how area scales with distance from the origin.',
   [('Why might a double integral be converted to polar coordinates?', ['To simplify integration over a circular or annular region', 'To make every integral impossible to evaluate', 'Polar coordinates can only be used for one-dimensional problems', 'To avoid ever using an integral sign'], 0),
    ('What replaces the area element dx dy when converting a double integral to polar coordinates?', ['r dr dtheta', 'A constant with no relationship to r or theta', 'dx dy remains unchanged in polar coordinates', 'theta dr dx'], 0),
    ('Why does the extra factor of r appear in the polar area element?', ['It accounts for how a small change in angle sweeps out more area farther from the origin', 'It is an arbitrary constant with no geometric meaning', 'It corrects for a units conversion between radians and degrees only', 'It has no mathematical justification'], 0),
    ('How does converting to polar coordinates relate to the earlier study of double integrals in Cartesian coordinates?', ['The same idea of summing values over small area elements is retained, adapted to a coordinate system suited to circular symmetry', 'Polar and Cartesian double integrals compute entirely different quantities', 'Cartesian double integrals can never be converted to polar form', 'Polar coordinates eliminate the need for double integrals'], 0),
    ('For what type of region is a polar double integral especially well suited?', ['A region with circular or radial symmetry, such as a disk or an annulus', 'A perfectly rectangular region with no curved boundary', 'A region with no defined boundary at all', 'A one-dimensional line segment'], 0)]),
PH('Physics: GPS and Relativistic Time Corrections',
   'Grade 12 Physics strand: the Global Positioning System requires corrections from both special and general relativity, since satellite clocks run slower due to their high orbital speed yet faster due to the weaker gravitational field at orbital altitude, and neglecting either effect would cause rapidly accumulating position errors.',
   [('Why do satellite clocks in the Global Positioning System require relativistic corrections?', ['Their high orbital speed and the weaker gravitational field at altitude both affect the rate at which their clocks run', 'Satellite clocks are entirely unaffected by relativity', 'GPS satellites do not use clocks of any kind', 'Relativity applies only to objects travelling at the speed of light'], 0),
    ('According to special relativity, how does a satellites high orbital speed affect its clock compared to a clock on Earths surface?', ['The satellites clock runs slower due to time dilation from its speed', 'The satellites clock runs faster due to its speed alone', 'Speed has no effect on a clocks rate according to special relativity', 'The satellites clock stops completely due to its speed'], 0),
    ('According to general relativity, how does the weaker gravitational field at orbital altitude affect a satellites clock?', ['The satellites clock runs faster than a clock deeper in Earths gravitational field', 'The weaker gravitational field has no effect on clock rate', 'The satellites clock runs slower due to the weaker gravitational field', 'Gravity only affects the colour of light, never the rate of a clock'], 0),
    ('What would happen to GPS position accuracy if relativistic corrections were ignored?', ['Position errors would accumulate rapidly, making the system unreliable within a short time', 'GPS accuracy would be completely unaffected by ignoring relativity', 'Position accuracy would improve if relativity were ignored', 'The GPS system would immediately stop functioning entirely'], 0),
    ('How does the GPS correction illustrate the combined roles of special and general relativity studied elsewhere in this course?', ['It shows both theories producing opposing but individually essential corrections to a single real-world system', 'It shows that only special relativity, and never general relativity, has any real-world application', 'It shows that relativity has no measurable effect on modern technology', 'It demonstrates that general relativity contradicts special relativity in this context'], 0)]),
]),
day(140, [
E('English Review: Genre, Form, and Global Perspectives',
  'Grade 12 English strand review: students revisit the epic tradition, free verse and Modernist poetics, the fable and allegorical mode, the anti-novel, metatheatre, climate fiction, travel writing, translation theory, and the aphorism and epigram.',
  [('What is an epic, in its traditional literary sense?', ['A long narrative poem recounting the heroic deeds of a legendary or historical figure', 'A short lyric poem about a single private feeling', 'A brief prose essay on a historical event', 'A modern screenplay with no poetic structure'], 0),
   ('What does free verse deliberately abandon?', ['Regular metre and a fixed rhyme scheme', 'All use of imagery and figurative language', 'Any division into lines at all', 'The use of the English language itself'], 0),
   ('What is a fable typically constructed to do?', ['Teach a moral lesson through a brief narrative', 'Provide a detailed historical record of real events', 'Describe a scientific process in technical language', 'Offer a purely factual news report'], 0),
   ('What does the anti-novel typically reject?', ['Traditional elements such as a clear plot, consistent characters, and an authoritative narrator', 'All use of written language', 'The existence of any reader whatsoever', 'Every form of punctuation'], 0),
   ('What does metatheatre draw attention to?', ['A plays own status as a performance', 'Only the historical accuracy of a plays setting', 'The private life of the playwright alone', 'The cost of producing a play'], 0)]),
AF('AdvancedFunctions Review: Number Theory, Probability, and Approximation',
   'Grade 12 Advanced Functions strand review: students revisit Eulers totient function, derangements and the hat-check problem, Bayes theorem, Eulers formula for planar graphs, generating Pythagorean triples, the Weierstrass function, Lucas sequences, the birthday problem, and Chebyshev polynomials.',
   [('What does Eulers totient function, phi of n, count?', ['The positive integers up to n that are coprime to n', 'The total number of divisors of n', 'The sum of all prime factors of n', 'The number of even integers less than n'], 0),
    ('What defines a derangement of a set?', ['A permutation in which no element appears in its original position', 'A permutation in which every element appears in its original position', 'A set with no elements at all', 'A permutation with exactly one fixed element'], 0),
    ('What does Bayes theorem allow a statistician to do?', ['Update the probability of an event in light of new evidence', 'Calculate the exact mean of any data set', 'Determine whether a number is prime', 'Graph a function without any data'], 0),
    ('What does Eulers formula for planar graphs and polyhedra state?', ['Vertices minus edges plus faces always equals two', 'Vertices plus edges plus faces always equals zero', 'Vertices minus edges minus faces always equals one', 'Edges alone always equal the number of faces'], 0),
    ('What is a Pythagorean triple?', ['A set of three positive integers satisfying the Pythagorean relationship', 'Any three integers with no relationship to a right triangle', 'A set of three prime numbers only', 'Three integers that always sum to zero'], 0)]),
CA('Calculus Review: Vector Calculus, Series, and Differential Equations',
   'Grade 12 Calculus strand review: students revisit arc length of a parametric curve, line integrals of scalar fields, the Laplacian operator and harmonic functions, Taylor series for functions of two variables, and Gaussian quadrature.',
   [('How is a parametric curve typically defined?', ['By separate functions x of t and y of t, both depending on a parameter t', 'By a single equation with no parameter involved', 'Only by a table of coordinates with no formula', 'By a function that must always be linear'], 0),
    ('What does the line integral of a scalar field integrate?', ['A function of position along a curve with respect to arc length', 'A vector field along a closed surface only', 'A constant with no relationship to a curve', 'The area enclosed by a curve'], 0),
    ('What does the Laplacian operator combine?', ['The second partial derivatives of a multivariable function', 'Only the first partial derivatives of a function', 'A single first derivative with no other terms', 'The original function values with no derivatives at all'], 0),
    ('What does the two-variable Taylor series use in place of ordinary derivatives from the single-variable case?', ['Partial derivatives evaluated at a given point', 'Only the original function values, with no derivatives', 'A single derivative taken with respect to one variable only', 'Random coefficients with no relation to the function'], 0),
    ('What distinguishes Gaussian quadrature from evenly spaced numerical integration methods?', ['It evaluates the integrand at strategically chosen, unevenly spaced nodes', 'It requires evenly spaced nodes exactly like the trapezoid rule', 'It avoids evaluating the integrand at any point', 'It only works for functions with no curvature'], 0)]),
PH('Physics Review: Optics, Thermal Effects, and Relativistic Applications',
   'Grade 12 Physics strand review: students revisit stimulated emission and the laser, Rayleigh scattering, Wiens displacement law, the Seebeck effect, the Joule-Thomson effect, the Sagnac effect, Chladni patterns, the physics of lightning, and GPS relativistic corrections.',
   [('What process underlies the operation of a laser?', ['Stimulated emission, in which a photon triggers an excited atom to emit an identical second photon', 'Spontaneous emission with no external trigger of any kind', 'The complete absorption of all light with no emission', 'Radioactive decay of atomic nuclei'], 0),
    ('What does Rayleigh scattering describe?', ['The scattering of electromagnetic radiation by particles much smaller than its wavelength', 'The complete absorption of all wavelengths of light equally', 'The scattering of sound waves in a solid material', 'The refraction of light through a lens'], 0),
    ('What does Wiens displacement law relate?', ['The wavelength of peak blackbody radiation to the objects temperature', 'The mass of an object to its electric charge', 'The volume of a gas to its pressure alone', 'The colour of an object to its chemical composition only'], 0),
    ('What does the Seebeck effect describe?', ['A temperature difference across a junction of two dissimilar conductors generating an electric voltage', 'An electric current generating a magnetic field', 'A mechanical stress generating an electric voltage', 'A voltage generating mechanical deformation in a crystal'], 0),
    ('What does the Joule-Thomson effect describe?', ['The temperature change of a real gas as it expands through a valve without exchanging heat with its surroundings', 'The temperature change of an ideal gas under constant volume', 'The pressure change of a liquid at constant temperature', 'The colour change of a gas as it is compressed'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g12_131_140)
    append_to(12, g12_131_140)
