#!/usr/bin/env python3
"""Grade 9, Days 151-160 -- extends Grade 9 from 150 to 160 days. Topics
chosen after dumping and reading the full Day 1-150 title list (data/grade9.json)
to avoid any overlap, which by this point is exhaustive across all four
subjects: restrictive and nonrestrictive clauses, eggcorns and commonly
misheard expressions, verbal and situational irony, writing a speech of
introduction, analyzing podcast and audio journalism, emphatic and cleft
sentences, archaisms and obsolete word forms, analyzing pastoral and nature
imagery, and writing a letter to the editor; graphing sine and cosine
functions, the Chinese Remainder Theorem, the chi-square test for
independence, mortgages and down payments, vector equations of lines, the
pigeonhole principle, perfect/deficient/abundant numbers, related rates, and
spherical coordinates; gas laws (Boyles Law and Charless Law), wave
interference and standing waves, population genetics and the
Hardy-Weinberg Principle, mineral identification and crystal structure, the
search for extraterrestrial intelligence and the Drake Equation, special
relativity (time dilation and length contraction), spectroscopy and flame
tests, plant physiology (transpiration and nutrient transport), and ocean
acidification; the geography of cross-border metropolitan regions and twin
cities, the global semiconductor supply chain, global remote work and
digital nomadism, the global fast fashion and textile trade, extreme
poverty and the global poverty line, global grain trade and food export
restrictions, Antarctic and polar tourism, language policy and official
bilingualism, and fisheries management and overfishing. Day 160 is a
cross-subject review day drawing quiz content from Days 151-159 of this
same batch.

Subject keys for Grade 9 are "Language", "Math", "Science",
"SocialStudies" (same as all earlier Grade 9 batches); SocialStudies
content is Geography-focused, matching the existing convention.

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes are avoided entirely (e.g.
"Boyles Law" not "Boyle's Law", "Earths" not "Earth's").
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

L9 = 'https://tvolearn.com/pages/grade-9-english'
M9 = 'https://tvolearn.com/pages/grade-9-mathematics'
S9 = 'https://tvolearn.com/pages/grade-9-science'
SS9 = 'https://tvolearn.com/pages/grade-9-geography'
RL, RM, RS, RSS = (
    'TVO Learn: Grade 9 English',
    'TVO Learn: Grade 9 Mathematics',
    'TVO Learn: Grade 9 Science',
    'TVO Learn: Grade 9 Geography',
)


def L(t, s, q):
    return sub('Language', t, s, RL, L9, q)


def M(t, s, q):
    return sub('Math', t, s, RM, M9, q)


def Sc(t, s, q):
    return sub('Science', t, s, RS, S9, q)


def SS(t, s, q):
    return sub('SocialStudies', t, s, RSS, SS9, q)


def _rebalance_answer_positions(days, seed=20260809):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g9_151_160 = [
day(151, [
L('Grammar: Restrictive and Nonrestrictive Clauses',
  'Grade 9 Language strand: a restrictive clause provides essential information that narrows the meaning of the noun it modifies and is not set off by commas, while a nonrestrictive clause adds extra, non-essential information and is always set off by commas.',
  [('What is a restrictive clause?', ['A clause that provides essential information narrowing the meaning of the noun it modifies', 'A clause that can be removed without changing a sentences essential meaning', 'A punctuation mark that separates two independent clauses', 'A clause that always begins with a coordinating conjunction'], 0),
   ('What is a nonrestrictive clause?', ['A clause that adds extra, non-essential information and is set off by commas', 'A clause that narrows the meaning of the noun it describes', 'A clause that cannot be removed without changing the sentences meaning', 'A verb phrase with no subject at all'], 0),
   ('Which sentence contains a restrictive clause?', ['The book that is on the table belongs to my sister.', 'The book, which is on the table, belongs to my sister.', 'My sister, who loves reading, owns many books.', 'The table, which is old, belongs to my sister.'], 0),
   ('Why is a nonrestrictive clause typically set off with commas?', ['To signal that the clause offers additional information that could be removed without changing the sentences core meaning', 'Commas are required before every clause regardless of its function', 'To show that the clause is the most important part of the sentence', 'Nonrestrictive clauses are never set off by any punctuation'], 0),
   ('Which relative pronoun is most commonly used to introduce a restrictive clause about a thing?', ['That', 'Which, in every formal style guide with no exceptions', 'Who', 'Whom'], 0)]),
M('Geometry: Graphing Sine and Cosine Functions (Amplitude and Period)',
  'Grade 9 Math strand: the graphs of sine and cosine functions are smooth, repeating waves whose amplitude describes their maximum height above the midline and whose period describes the horizontal length of one complete cycle.',
  [('What does the amplitude of a sine or cosine graph describe?', ['The maximum height of the wave above (or below) its midline', 'The total horizontal length of the graph', 'The number of times the graph crosses the x-axis', 'The steepness of the graph at the origin only'], 0),
   ('What does the period of a sine or cosine function describe?', ['The horizontal length required to complete one full cycle of the wave', 'The maximum height reached by the graph', 'The y-intercept of the function', 'The number of amplitudes in a single wave'], 0),
   ('What is the period of the basic function y = sin(x), measured in radians?', ['2 pi', 'Pi', 'Pi divided by two', '4 pi'], 0),
   ('How does increasing the coefficient in front of sin(x) in y = a sin(x) affect the graph?', ['It increases the amplitude, making the wave taller', 'It increases the period, making the wave wider', 'It has no effect on the graph whatsoever', 'It shifts the entire graph horizontally'], 0),
   ('Why are sine and cosine graphs often described as periodic?', ['Their pattern of values repeats identically at regular horizontal intervals', 'Their values never repeat under any circumstances', 'They only produce a single output value for all inputs', 'They only exist for negative input values'], 0)]),
Sc('Chemistry: Gas Laws: Boyles Law and Charless Law',
   'Grade 9 Science strand: Boyles Law describes how the pressure and volume of a gas are inversely related at constant temperature, while Charless Law describes how the volume and temperature of a gas are directly related at constant pressure.',
   [('What does Boyles Law describe?', ['The inverse relationship between the pressure and volume of a gas at constant temperature', 'The direct relationship between the volume and temperature of a gas at constant pressure', 'The relationship between the mass and colour of a gas', 'A rule that applies only to solids, never to gases'], 0),
    ('According to Boyles Law, what happens to the volume of a gas if its pressure increases at constant temperature?', ['The volume decreases', 'The volume increases proportionally', 'The volume remains exactly the same', 'The volume becomes impossible to measure'], 0),
    ('What does Charless Law describe?', ['The direct relationship between the volume and temperature of a gas at constant pressure', 'The inverse relationship between pressure and volume at constant temperature', 'The relationship between a gases colour and its density', 'A rule describing only solid substances'], 0),
    ('According to Charless Law, what happens to the volume of a gas as its temperature increases at constant pressure?', ['The volume increases', 'The volume decreases', 'The volume stays exactly constant', 'The volume becomes negative'], 0),
    ('Why must temperature be held constant when applying Boyles Law?', ['Because Boyles Law specifically describes the relationship between pressure and volume only when temperature does not change', 'Temperature has no relevance to any gas law', 'Boyles Law requires temperature to constantly increase', 'Pressure and volume are unrelated to temperature in every gas law'], 0)]),
SS('Social Studies: The Geography of Cross-Border Metropolitan Regions and Twin Cities',
   'Grade 9 Social Studies (Geography) strand: a cross-border metropolitan region forms when two cities in different countries grow closely linked through trade, commuting, and shared infrastructure, creating a functionally connected urban area that spans an international boundary.',
   [('What is a cross-border metropolitan region?', ['A functionally connected urban area formed by two cities in different countries linked by trade, commuting, and infrastructure', 'A city located entirely within a single countrys interior with no border nearby', 'A rural region with no urban development of any kind', 'A metropolitan area that has never had any international connections'], 0),
    ('What commonly links twin cities across an international border?', ['Shared infrastructure such as bridges, and strong daily flows of trade and commuters', 'A complete absence of any transportation connecting the two cities', 'A shared currency used nowhere else in either country', 'Total isolation from each others economies'], 0),
    ('Why might businesses in a cross-border metropolitan region benefit from their location?', ['They can access labour, customers, and suppliers on both sides of the border', 'Businesses located near a border are always cut off from any trade', 'Cross-border regions eliminate the need for any economic activity', 'Businesses in these regions cannot legally trade internationally'], 0),
    ('What kind of infrastructure challenge is common in cross-border metropolitan regions?', ['Coordinating border crossings, customs, and transportation systems between two different national governments', 'These regions require no coordination since they share one single government', 'Cross-border regions never experience any transportation challenges', 'International borders are always closed permanently in these regions'], 0),
    ('Why do geographers study cross-border metropolitan regions?', ['To understand how economic and social ties can create a functionally unified region despite a political border dividing it', 'Twin cities have no relevance to the study of political or economic geography', 'These regions are considered identical to any single-country city', 'Borders always completely separate the economies of neighbouring cities'], 0)]),
]),
day(152, [
L('Vocabulary: Eggcorns and Commonly Misheard Expressions',
  'Grade 9 Language strand: an eggcorn occurs when a speaker mishears a word or phrase and replaces it with a similar-sounding substitute that still seems to make logical sense, such as saying old-timers disease instead of Alzheimers disease.',
  [('What is an eggcorn?', ['A misheard word or phrase replaced with a similar-sounding substitute that still seems to make sense', 'A word that has absolutely no meaning in any language', 'A formal grammatical rule taught in every textbook', 'A punctuation mark used only in poetry'], 0),
   ('Why do eggcorns often go unnoticed by the person using them?', ['The substituted phrase sounds similar to the original and can still seem logically meaningful in context', 'Eggcorns are always immediately obvious to every listener', 'Eggcorns never resemble the original expression in any way', 'Speakers who use eggcorns always know they are making an error'], 0),
   ('Which of these is a classic example of an eggcorn?', ['Saying for all intensive purposes instead of for all intents and purposes', 'Saying for all intents and purposes correctly with no substitution', 'Using a completely unrelated word with no similarity to the original', 'Deliberately inventing a brand new word with no prior expression'], 0),
   ('How does an eggcorn differ from a simple spelling mistake?', ['An eggcorn results from mishearing a spoken phrase, while a spelling mistake occurs in writing an already-known word', 'An eggcorn and a spelling mistake are exactly the same phenomenon', 'Eggcorns only ever occur in formal written documents', 'Spelling mistakes always involve a change in the words entire meaning'], 0),
   ('Why might studying eggcorns be useful for understanding how language changes?', ['Eggcorns show how a small alteration in an expression can begin to spread and reshape common usage over time', 'Eggcorns never influence how a language develops', 'Language never changes because of anything speakers say', 'Eggcorns only occur in written academic texts, never in speech'], 0)]),
M('Number Theory: An Introduction to the Chinese Remainder Theorem',
  'Grade 9 Math strand: the Chinese Remainder Theorem states that a system of simultaneous congruences with pairwise coprime moduli has a unique solution modulo the product of those moduli, making it possible to reconstruct a number from its remainders.',
  [('What does the Chinese Remainder Theorem allow you to do?', ['Find a unique solution to a system of simultaneous congruences with pairwise coprime moduli', 'Calculate the area of any triangle using only its perimeter', 'Determine the exact prime factorization of a fraction', 'Solve any equation with no variables at all'], 0),
   ('What condition must the moduli in the system satisfy for the Chinese Remainder Theorem to guarantee a unique solution?', ['The moduli must be pairwise coprime, meaning each pair shares no common factor greater than one', 'The moduli must all be equal to zero', 'The moduli must always be even numbers', 'The moduli must share every factor in common'], 0),
   ('If a solution exists under the Chinese Remainder Theorem, over what range is it unique?', ['Modulo the product of all the given moduli', 'Modulo exactly one, meaning only zero is a solution', 'Over the entire set of real numbers with no restriction', 'The solution is never unique under any conditions'], 0),
   ('Why might the Chinese Remainder Theorem be useful when a number is described only by its remainders after division by several smaller numbers?', ['It provides a systematic way to reconstruct the original number from those remainders', 'It proves the number described cannot possibly exist', 'It only applies to numbers that are already known in full', 'It eliminates the need for any remainders in mathematics'], 0),
   ('The Chinese Remainder Theorem builds most directly on which earlier number theory concept studied in this course?', ['Modular arithmetic and the idea of congruence', 'The dot product of two vectors', 'The Pythagorean theorem', 'Sigma notation for finite sums'], 0)]),
Sc('Physics: Wave Interference and Standing Waves',
   'Grade 9 Science strand: wave interference occurs when two or more waves overlap, combining constructively to produce a larger amplitude or destructively to cancel each other out, and a standing wave forms when two identical waves travel in opposite directions and interfere to create fixed points that do not move.',
   [('What is wave interference?', ['The overlapping of two or more waves that combine to produce a new wave pattern', 'A phenomenon that only occurs when a single wave travels alone with nothing else present', 'The complete disappearance of all wave motion', 'A process that only applies to particles, never to waves'], 0),
    ('What is constructive interference?', ['Interference in which overlapping waves combine to produce a wave of larger amplitude', 'Interference that always cancels out every wave completely', 'A process that only occurs in complete darkness', 'Interference that decreases the speed of a wave to zero'], 0),
    ('What is destructive interference?', ['Interference in which overlapping waves combine to reduce or cancel out the resulting amplitude', 'Interference that always increases the amplitude of every wave', 'A process that has no effect on wave amplitude at all', 'Interference that only happens to sound waves, never other waves'], 0),
    ('How does a standing wave form?', ['Two identical waves travelling in opposite directions interfere, creating fixed points called nodes that do not move', 'A standing wave forms only when a single wave travels with nothing to interfere with it', 'Standing waves form exclusively in the absence of any wave motion', 'A standing wave requires two completely different, unrelated frequencies'], 0),
    ('What term describes the fixed points of zero displacement in a standing wave?', ['Nodes', 'Crests', 'Troughs', 'Wavelengths'], 0)]),
SS('Social Studies: The Geography of the Global Semiconductor Supply Chain',
   'Grade 9 Social Studies (Geography) strand: semiconductor chips are manufactured through a highly specialized global supply chain concentrated in a small number of regions, making the geography of chip design, fabrication, and assembly a major factor in global trade and international relations.',
   [('What is a semiconductor supply chain?', ['The global network of specialized regions and facilities involved in designing, fabricating, and assembling computer chips', 'A single factory that produces every step of a chip with no international involvement', 'A supply chain that has no connection to any global trade', 'A network used exclusively for growing agricultural crops'], 0),
    ('Why is semiconductor manufacturing described as highly concentrated geographically?', ['Advanced chip fabrication requires specialized facilities and expertise found in only a small number of regions worldwide', 'Every country in the world manufactures advanced semiconductor chips equally', 'Semiconductor manufacturing requires no specialized technology or facilities', 'Chip fabrication facilities are spread evenly across every continent'], 0),
    ('Why can disruptions to the semiconductor supply chain have wide-reaching global effects?', ['Chips are essential components in a vast range of industries, from electronics to automobiles', 'Semiconductors are used in only one narrow product with no broader impact', 'Disruptions to chip supply have no effect on any other industry', 'Semiconductor chips are not used in any modern technology'], 0),
    ('Why have some governments invested in building new domestic chip fabrication facilities?', ['To reduce reliance on a small number of foreign suppliers and strengthen supply chain security', 'Because domestic chip production has no strategic or economic value', 'Governments are legally forbidden from investing in chip manufacturing', 'Every country already produces all the chips it needs domestically'], 0),
    ('Why do geographers study the semiconductor supply chain?', ['It illustrates how a highly specialized global industry can concentrate economic and political power in specific regions', 'The semiconductor industry has no geographic dimension worth studying', 'Chip manufacturing occurs randomly with no identifiable geographic pattern', 'This topic is considered purely a matter of chemistry, not geography'], 0)]),
]),
day(153, [
L('Reading: Analyzing Verbal and Situational Irony',
  'Grade 9 Language strand: verbal irony occurs when a speaker says the opposite of what they truly mean, while situational irony occurs when the actual outcome of a situation is strikingly different from what was expected, and both differ from dramatic irony, where the audience knows something a character does not.',
  [('What is verbal irony?', ['When a speaker says the opposite of what they actually mean', 'When an audience knows something that a character does not know', 'When the outcome of events matches exactly what was expected', 'A type of punctuation used to end a sarcastic sentence'], 0),
   ('What is situational irony?', ['When the actual outcome of a situation is strikingly different from what was expected', 'When a character speaks directly to the audience', 'When a speaker always states their literal, intended meaning', 'A device used only in formal persuasive essays'], 0),
   ('How does verbal irony differ from dramatic irony?', ['Verbal irony involves a speaker meaning the opposite of their words, while dramatic irony involves the audience knowing something a character does not', 'Verbal irony and dramatic irony are exactly the same literary device', 'Dramatic irony only occurs in spoken dialogue, never in narration', 'Verbal irony requires an audience to know more than any character'], 0),
   ('A fire station burning down would be an example of what kind of irony?', ['Situational irony, since the outcome sharply contradicts what would normally be expected', 'Verbal irony, since it involves a spoken statement', 'Dramatic irony, since it requires an audience with hidden knowledge', 'No irony at all, since fires are common at any building'], 0),
   ('Why might an author use verbal irony in dialogue?', ['To create a sarcastic or humorous effect by having a character say the opposite of their true meaning', 'To ensure every character always states their literal meaning with no exceptions', 'To completely remove any tension or humour from a scene', 'Verbal irony can only appear in narration, never in dialogue'], 0)]),
M('Statistics: An Introduction to the Chi-Square Test for Independence',
  'Grade 9 Math strand: a chi-square test for independence compares observed frequencies in categorical data to the frequencies expected if two variables were unrelated, producing a statistic used to judge whether an apparent association between the variables is likely to be real.',
  [('What does a chi-square test for independence help determine?', ['Whether an apparent association between two categorical variables is likely to be real rather than due to chance', 'The exact mean of a continuous data set', 'The slope of a line of best fit', 'The volume of a three-dimensional solid'], 0),
   ('What two sets of frequencies does a chi-square test compare?', ['The observed frequencies in the data and the frequencies expected if the variables were unrelated', 'The largest and smallest values in a data set', 'The mean and the median of a single variable', 'The area and the perimeter of a rectangle'], 0),
   ('What type of data is a chi-square test for independence typically used to analyze?', ['Categorical data organized into a table of counts', 'Continuous data measured on a precise numerical scale only', 'Data with no categories or groupings of any kind', 'Only data collected from a single individual'], 0),
   ('A large chi-square statistic generally suggests what about the observed and expected frequencies?', ['A substantial difference between the observed and expected frequencies, suggesting the variables may be associated', 'That the observed and expected frequencies are identical in every case', 'That no data was collected for the test at all', 'That the two variables are definitely unrelated with certainty'], 0),
   ('Why is a chi-square test for independence considered useful in fields like social science research?', ['It allows researchers to test whether relationships observed between categorical variables, such as preference and age group, are likely genuine', 'It can only be applied to physical measurements like length and mass', 'It eliminates the need to collect any data before analysis', 'It guarantees a cause-and-effect relationship between any two variables'], 0)]),
Sc('Biology: Population Genetics and the Hardy-Weinberg Principle',
   'Grade 9 Science strand: population genetics studies how allele frequencies change within a population over time, and the Hardy-Weinberg Principle describes the conditions under which those allele frequencies remain stable from one generation to the next in the absence of evolutionary forces.',
   [('What does population genetics study?', ['How allele frequencies change, or remain stable, within a population over time', 'The individual medical history of a single organism', 'The structure of a single cell under a microscope', 'The chemical composition of non-living rock formations'], 0),
    ('What does the Hardy-Weinberg Principle describe?', ['The conditions under which allele frequencies in a population remain stable across generations', 'The exact process by which a virus spreads between individuals', 'A rule that applies only to a single organism, never a population', 'The chemical structure of a strand of DNA'], 0),
    ('Which of the following would violate the assumptions of Hardy-Weinberg equilibrium?', ['Natural selection favouring one allele over another in the population', 'A population mating completely at random with no external influence', 'A population with an extremely large, stable number of individuals', 'A population experiencing no mutation, migration, or selection at all'], 0),
    ('Why is Hardy-Weinberg equilibrium often described as a useful theoretical baseline?', ['It shows what allele frequencies would look like without evolutionary change, making deviations easier to detect and study', 'It always accurately predicts every real population with no exceptions', 'It describes only how a single organism inherits traits', 'It has no connection to the study of evolution at all'], 0),
    ('Which evolutionary force could cause a real populations allele frequencies to shift away from Hardy-Weinberg equilibrium?', ['Genetic drift, migration, mutation, or natural selection', 'A population remaining completely isolated with random mating and no mutation', 'The complete absence of any environmental change', 'A population of only theoretical, non-living organisms'], 0)]),
SS('Social Studies: The Geography of Global Remote Work and Digital Nomadism',
   'Grade 9 Social Studies (Geography) strand: the growth of remote work has allowed some workers to become digital nomads, living and working from different countries while maintaining employment elsewhere, reshaping migration patterns and prompting some governments to create specific visas to attract these mobile workers.',
   [('What is a digital nomad?', ['A remote worker who lives and works from different locations, often across international borders, while maintaining employment elsewhere', 'A worker who is permanently required to work from a single fixed office location', 'A person with no access to the internet or digital technology', 'A farmer who moves seasonally to follow crop harvests'], 0),
    ('What technological development has enabled the growth of digital nomadism?', ['Widespread access to reliable internet connectivity that allows work to be done from many locations', 'The invention of the telephone in the nineteenth century', 'A global ban on all forms of remote communication', 'The complete elimination of computers from modern workplaces'], 0),
    ('Why have some governments created special visas aimed at digital nomads?', ['To attract remote workers whose spending can benefit the local economy without displacing local jobs', 'To prevent any foreign remote workers from ever entering the country', 'Because digital nomads are legally required to become permanent citizens', 'To eliminate tourism entirely in favour of remote work visas'], 0),
    ('How can digital nomadism affect housing markets in popular destination cities?', ['Increased demand from relatively higher-earning remote workers can raise local housing costs', 'Digital nomads never rent or purchase any housing in a destination city', 'Digital nomadism always lowers housing costs in every destination', 'Remote workers have no measurable effect on local housing markets'], 0),
    ('Why do geographers study patterns of digital nomadism?', ['It reveals how technology is reshaping traditional patterns of migration and where people choose to live and work', 'Digital nomadism has no connection to migration or economic geography', 'Remote work eliminates the need to study any human movement patterns', 'This topic is considered purely a matter of computer science, not geography'], 0)]),
]),
day(154, [
L('Writing: Writing a Speech of Introduction',
  'Grade 9 Language strand: a speech of introduction presents a speaker or guest to an audience by highlighting relevant credentials and accomplishments, building interest and credibility, and is typically brief so it does not overshadow the main speaker who follows.',
  [('What is the main purpose of a speech of introduction?', ['To present a speaker or guest to an audience by highlighting relevant credentials and building interest', 'To deliver the entire main presentation instead of the featured speaker', 'To criticize the credentials of the speaker being introduced', 'To provide an unrelated summary of a completely different event'], 0),
   ('Why should a speech of introduction typically remain brief?', ['So it builds anticipation without overshadowing the main speaker who follows', 'Because audiences are legally prohibited from listening to long speeches', 'A speech of introduction must always be longer than the speech that follows', 'Brevity has no relevance to a speech of introduction'], 0),
   ('What kind of information is most appropriate to include in a speech of introduction?', ['Relevant credentials, accomplishments, and background that build the speakers credibility', 'Personal criticism of the audience members', 'A detailed account of an entirely unrelated historical event', 'A summary of the introducers own life story with no mention of the speaker'], 0),
   ('Why might a speech of introduction end with a direct welcome, such as inviting the speaker to the stage?', ['It creates a clear, smooth transition from the introduction to the main speakers presentation', 'Ending a speech of introduction is considered inappropriate in every context', 'A direct welcome always confuses the audience about who is speaking next', 'It is meant to indicate that the event has concluded entirely'], 0),
   ('How does a speech of introduction differ from a eulogy studied earlier in this course?', ['A speech of introduction builds anticipation for an upcoming speaker, while a eulogy honours someone who has died', 'A speech of introduction and a eulogy serve exactly the same purpose', 'A eulogy is always delivered before the person it honours arrives on stage', 'A speech of introduction can only be delivered at a memorial service'], 0)]),
M('Financial Literacy: Mortgages and Down Payments',
  'Grade 9 Math strand: a mortgage is a long-term loan used to purchase property, typically requiring an upfront down payment representing a percentage of the purchase price, with the remaining balance repaid over time along with interest.',
  [('What is a mortgage?', ['A long-term loan specifically used to purchase property', 'A short-term loan used only to buy groceries', 'A type of insurance that covers vehicle repairs', 'A savings account with no connection to borrowing money'], 0),
   ('What is a down payment?', ['An upfront payment representing a percentage of a propertys purchase price, paid before financing the remainder', 'The final payment made at the very end of a mortgage term', 'A fee charged only if a mortgage payment is missed', 'A payment that has no connection to purchasing property'], 0),
   ('Why does a larger down payment generally reduce the total interest paid over the life of a mortgage?', ['A smaller loan amount is borrowed, so less interest accrues on the remaining balance over time', 'A larger down payment always increases the interest rate charged', 'Down payments have no effect on the total interest paid on a mortgage', 'The size of a down payment is entirely unrelated to a loans structure'], 0),
   ('What generally happens to a homeowners equity as mortgage payments are made over time?', ['Equity typically increases as more of the loan principal is paid down', 'Equity always decreases to zero regardless of payments made', 'Equity has no relationship to mortgage payments at all', 'Equity remains exactly the same throughout the entire mortgage term'], 0),
   ('How does a mortgage relate to the concept of amortization studied earlier in this course?', ['A mortgage is commonly repaid using an amortization schedule that spreads principal and interest payments over time', 'A mortgage has no connection to amortization of any kind', 'Amortization only applies to short-term loans, never to long-term mortgages', 'Mortgages are always repaid in a single lump sum with no schedule'], 0)]),
Sc('Earth Science: Mineral Identification and Crystal Structure',
   'Grade 9 Science strand: minerals are identified using physical properties such as hardness, streak, lustre, and cleavage, and each mineral forms a characteristic crystal structure based on the orderly, repeating arrangement of its atoms.',
   [('What is a mineral?', ['A naturally occurring, inorganic solid with a definite chemical composition and an orderly internal crystal structure', 'Any liquid substance found underground', 'A living organism found only in caves', 'A type of soil with no defined chemical structure'], 0),
    ('What property describes the colour of a minerals powder when scraped across an unglazed surface?', ['Streak', 'Lustre', 'Hardness', 'Cleavage'], 0),
    ('What scale is commonly used to measure and compare the hardness of minerals?', ['The Mohs hardness scale', 'The Richter scale', 'The pH scale', 'The Beaufort scale'], 0),
    ('What is cleavage in the context of mineral identification?', ['The tendency of a mineral to break along flat, smooth planes related to its internal crystal structure', 'A term describing only the colour of a mineral', 'The process by which a mineral melts under heat', 'A property that applies only to living organisms'], 0),
    ('Why does each mineral form a characteristic crystal structure?', ['Its atoms are arranged in a specific, orderly, repeating pattern determined by its chemical composition', 'Crystal structures form entirely at random with no relationship to chemical composition', 'Minerals never have any internal structure of any kind', 'Every mineral shares an identical crystal structure regardless of composition'], 0)]),
SS('Social Studies: The Geography of the Global Fast Fashion and Textile Trade',
   'Grade 9 Social Studies (Geography) strand: the fast fashion industry relies on a global textile supply chain that moves raw materials, manufacturing, and finished clothing across many countries to produce inexpensive garments quickly, raising ongoing questions about labour conditions and environmental impact.',
   [('What is fast fashion?', ['A business model that produces inexpensive clothing quickly in response to rapidly changing trends', 'A method of producing clothing exclusively by hand over many years', 'A term describing only clothing manufactured within a single country', 'A style of clothing with no connection to global trade'], 0),
    ('Why is the fast fashion industrys supply chain often described as global?', ['Raw materials, manufacturing, and distribution frequently span many different countries before a garment reaches a consumer', 'Every step of fast fashion production always occurs within a single factory', 'Fast fashion garments are never transported across international borders', 'Textile production has no connection to international trade of any kind'], 0),
    ('What labour concern is commonly associated with fast fashion manufacturing?', ['Low wages and poor working conditions in some garment factories', 'Fast fashion factories are required by law to offer the highest wages in the world', 'There are no labour concerns associated with garment manufacturing anywhere', 'Fast fashion production never involves any human workers'], 0),
    ('What environmental impact is commonly linked to the fast fashion industry?', ['Significant water use, chemical pollution, and textile waste from rapidly discarded clothing', 'Fast fashion production has no environmental impact of any kind', 'The fast fashion industry always improves local water quality', 'Textile waste from fast fashion is entirely eliminated through recycling'], 0),
    ('Why do geographers study the global textile and fast fashion trade?', ['It illustrates how consumer demand in one region can shape labour practices and environmental conditions in distant manufacturing regions', 'The fast fashion trade has no geographic pattern worth studying', 'Clothing is manufactured only in the same country where it is sold', 'This topic is considered purely a matter of fashion design, not geography'], 0)]),
]),
day(155, [
L('Media Literacy: Analyzing Podcast and Audio Journalism',
  'Grade 9 Language strand: podcast and audio journalism deliver news and storytelling through sound alone, relying on voice, pacing, and sound design to engage listeners, which requires a media-literate listener to evaluate the credibility of sources even without visual cues.',
  [('What distinguishes podcast and audio journalism from traditional print journalism?', ['It delivers news and storytelling through sound alone, relying on voice, pacing, and sound design', 'It relies entirely on printed photographs with no audio component', 'It can only be produced by large, well-funded television networks', 'It never includes any interviews or spoken commentary'], 0),
   ('Why might a listener need to work harder to evaluate credibility in an audio-only format compared to a written article?', ['There are no visual cues, such as citations or bylines, immediately visible to help verify claims', 'Audio journalism always automatically verifies every claim it makes', 'Written articles never require any evaluation of credibility', 'Listeners cannot access any information about a podcasts sources'], 0),
   ('What production element can influence how a listener emotionally responds to a podcast episode?', ['Sound design, such as background music or pacing of the narration', 'The typeface used on the podcasts website', 'The number of pages included in a printed transcript', 'The colour of the podcasts logo image'], 0),
   ('Why is it useful for a listener to research a podcasts host or production team?', ['It can reveal potential biases, expertise, or funding sources that shape the content', 'Researching a podcasts producers never reveals any useful information', 'Podcast hosts are legally required to have no opinions of any kind', 'This information is always irrelevant to understanding the podcasts content'], 0),
   ('How can transcripts or show notes support media literacy when engaging with a podcast?', ['They can help a listener verify quotations, sources, and claims made during the episode', 'Transcripts and show notes are never provided for any podcast', 'They eliminate the need to think critically about the content', 'They only ever contain unrelated advertising content'], 0)]),
M('Geometry: Vector Equations of Lines',
  'Grade 9 Math strand: a line in space can be described using a vector equation that combines a known point on the line with a direction vector scaled by a parameter, allowing every point on the line to be generated as that parameter varies.',
  [('What two pieces of information are needed to write the vector equation of a line?', ['A known point on the line and a direction vector parallel to the line', 'Only the length of the line, with no other information', 'Only the colour used to draw the line', 'The area enclosed by the line and the x-axis'], 0),
   ('In the vector equation r = r0 + t*d, what does the parameter t represent?', ['A scalar that varies to generate every different point along the line', 'The exact length of the direction vector only', 'A fixed constant that never changes for any point on the line', 'The angle between the line and the x-axis'], 0),
   ('What does the direction vector in a vector equation of a line indicate?', ['The orientation, or direction, in which the line extends through space', 'The exact starting point of the line only', 'The colour used to represent the line on a graph', 'The total distance from the origin to every point on the line'], 0),
   ('Why can a vector equation describe a line in three-dimensional space more naturally than a single slope-intercept equation?', ['A vector equation can represent direction and position in multiple dimensions, while slope-intercept form is limited to two dimensions', 'Slope-intercept form works equally well in any number of dimensions', 'Vector equations cannot be used to describe any line at all', 'A vector equation only applies to curves, never to straight lines'], 0),
   ('If two lines have direction vectors that are scalar multiples of each other, what can be concluded about the lines?', ['The lines are parallel, since their direction vectors point along the same or opposite direction', 'The lines must always intersect at a single point', 'The lines are necessarily perpendicular to each other', 'Nothing can be concluded about the relationship between the lines'], 0)]),
Sc('Astronomy: The Search for Extraterrestrial Intelligence and the Drake Equation',
   'Grade 9 Science strand: the search for extraterrestrial intelligence uses radio telescopes to listen for potential signals from other civilizations, and the Drake Equation estimates the number of communicating civilizations in our galaxy by multiplying several factors, including the rate of star formation and the fraction of planets that could support life.',
   [('What is the main goal of the search for extraterrestrial intelligence?', ['To detect potential signals or evidence of intelligent life beyond Earth', 'To permanently prevent any future space exploration', 'To confirm that no other planets exist in the universe', 'To study only the geology of planets within our own solar system'], 0),
    ('What tool is commonly used in the search for extraterrestrial intelligence to listen for potential signals?', ['Radio telescopes', 'Standard household telephones', 'Underwater sonar equipment', 'Ordinary magnifying glasses'], 0),
    ('What does the Drake Equation attempt to estimate?', ['The number of potentially communicating civilizations that might exist in our galaxy', 'The exact distance between Earth and every star in the galaxy', 'The precise age of the entire universe', 'The total mass of every planet in our solar system'], 0),
    ('Which of the following is one of the factors multiplied together in the Drake Equation?', ['The fraction of planets that could potentially support life', 'The average temperature of the Suns surface only', 'The number of moons orbiting Earth', 'The exact colour of distant stars'], 0),
    ('Why is the Drake Equation considered more of a framework for discussion than a precise prediction?', ['Many of its factors, such as the likelihood of life developing intelligence, remain highly uncertain and difficult to measure', 'Every factor in the equation has already been measured with complete certainty', 'The equation has no connection to the search for extraterrestrial life', 'The Drake Equation only applies to planets within our own solar system'], 0)]),
SS('Social Studies: The Geography of Extreme Poverty and the Global Poverty Line',
   'Grade 9 Social Studies (Geography) strand: the global poverty line is a standardized income threshold used to measure extreme poverty across countries, and its uneven geographic distribution reflects differences in economic development, conflict, and access to resources around the world.',
   [('What is the global poverty line?', ['A standardized income threshold used to measure and compare extreme poverty across different countries', 'A physical border separating wealthy countries from all other nations', 'A line drawn on a map showing the location of every city in the world', 'A measurement used only to describe rainfall patterns'], 0),
    ('Why is a standardized measure like the global poverty line useful for international comparisons?', ['It allows researchers and organizations to compare poverty levels consistently across countries with different currencies and economies', 'It makes comparing poverty between countries completely impossible', 'Every country already uses an identical measure of income with no need for standardization', 'The global poverty line only applies to a single country at a time'], 0),
    ('What factor can contribute to a country having a higher concentration of extreme poverty?', ['Ongoing conflict, limited infrastructure, or restricted access to education and resources', 'A complete absence of any economic activity is required for poverty to exist', 'Extreme poverty is distributed identically in every country regardless of circumstances', 'Countries with abundant infrastructure always have the highest poverty rates'], 0),
    ('How can improved access to infrastructure, such as roads and electricity, affect extreme poverty in a region?', ['It can support economic development and improve access to markets, jobs, and services, potentially reducing poverty', 'Infrastructure improvements always increase the rate of extreme poverty', 'Infrastructure has no measurable effect on economic development', 'Access to roads and electricity is unrelated to a regions economy'], 0),
    ('Why do geographers study the spatial distribution of extreme poverty?', ['To identify where poverty is concentrated and understand the geographic factors contributing to it', 'Poverty has no geographic pattern and is distributed randomly worldwide', 'This topic is considered purely a matter of individual choice, not geography', 'Geographers are only interested in wealthy regions of the world'], 0)]),
]),
day(156, [
L('Grammar: Emphatic and Cleft Sentences',
  'Grade 9 Language strand: an emphatic sentence uses structures such as the auxiliary verb do to stress a point, while a cleft sentence divides a single idea into two clauses, often beginning with it or what, to highlight one particular piece of information.',
  [('What is the purpose of an emphatic sentence?', ['To stress or emphasize a particular point, often using an auxiliary verb such as do', 'To remove all emphasis from every part of a sentence', 'To combine two unrelated ideas with no connection at all', 'To eliminate the need for a main verb in a sentence'], 0),
   ('Which sentence is an example of emphatic structure using the auxiliary verb do?', ['I did finish my homework before dinner.', 'I finished my homework before dinner.', 'Finishing my homework, I ate dinner.', 'Homework, I finished, before dinner.'], 0),
   ('What is a cleft sentence?', ['A sentence divided into two clauses, often beginning with it or what, to highlight a specific piece of information', 'A sentence that contains no verbs of any kind', 'A sentence that must always begin with a question word', 'A type of sentence found only in poetry, never in prose'], 0),
   ('Which sentence is an example of a cleft sentence?', ['It was Maria who solved the difficult problem.', 'Maria solved the difficult problem.', 'The difficult problem was solved.', 'Solving the difficult problem, Maria smiled.'], 0),
   ('Why might a writer choose a cleft sentence structure instead of a simple, direct sentence?', ['To draw special attention to one particular piece of information within the sentence', 'Cleft sentences always make a sentence less clear to the reader', 'A cleft sentence removes the subject from a sentence entirely', 'Cleft sentences are grammatically incorrect in every context'], 0)]),
M('Data Management: An Introduction to the Pigeonhole Principle',
  'Grade 9 Math strand: the pigeonhole principle states that if more items are placed into containers than there are containers available, at least one container must hold more than one item, providing a simple but powerful tool for proving certain results in combinatorics.',
  [('What does the pigeonhole principle state?', ['If more items are placed into containers than there are containers, at least one container must hold more than one item', 'Every container must always hold exactly one item and no more', 'Items placed into containers are always distributed perfectly evenly', 'The number of containers must always exceed the number of items'], 0),
   ('If 13 people are in a room, what can the pigeonhole principle guarantee about their birthday months?', ['At least two people must share the same birthday month, since there are only 12 months', 'Every person in the room must have a different birthday month', 'No two people can ever share the same birthday month', 'The pigeonhole principle cannot be applied to this situation at all'], 0),
   ('Why is the pigeonhole principle considered a useful proof technique in combinatorics?', ['It can prove that a certain outcome must occur without needing to identify exactly which item causes it', 'It can only be used to disprove mathematical statements, never to prove them', 'It requires calculating every possible outcome individually with no shortcuts', 'It has no application to counting or combinatorics problems'], 0),
   ('What is required for the pigeonhole principle to guarantee at least one container with more than one item?', ['The number of items must be strictly greater than the number of containers', 'The number of items must always be exactly equal to the number of containers', 'The number of containers must always be greater than the number of items', 'No specific relationship between items and containers is required'], 0),
   ('Which of the following scenarios illustrates the pigeonhole principle?', ['Proving that among 32 students, at least two must have the same last initial, since there are only 26 letters', 'Measuring the exact height of a single student', 'Calculating the average grade on a single test', 'Determining the colour of a randomly selected object'], 0)]),
Sc('Physics: Special Relativity: Time Dilation and Length Contraction',
   'Grade 9 Science strand: special relativity describes how time and space are experienced differently depending on relative motion, predicting time dilation, in which a moving clock runs slower relative to a stationary observer, and length contraction, in which a moving objects length appears shorter along its direction of motion.',
   [('What does special relativity describe?', ['How time and space are experienced differently depending on the relative motion between observers', 'A theory that applies only to objects that are completely motionless', 'A rule stating that time always passes identically for every observer', 'A theory with no connection to the speed of light'], 0),
    ('What is time dilation?', ['The effect in which a clock moving relative to an observer appears to run slower than a stationary clock', 'The effect in which time always passes at exactly the same rate for every observer', 'A phenomenon that only applies to objects at rest', 'An effect that causes clocks to run faster the slower an object moves'], 0),
    ('What is length contraction?', ['The effect in which a moving objects length appears shorter along its direction of motion, as measured by a stationary observer', 'The effect in which a moving object always appears longer than its rest length', 'A phenomenon that has no connection to relative motion', 'An effect that only applies to objects that are not moving at all'], 0),
    ('Under what condition do the effects of time dilation and length contraction become significant?', ['When an objects speed approaches a substantial fraction of the speed of light', 'These effects are always significant, even at extremely slow, everyday speeds', 'These effects only occur for objects that are completely stationary', 'Time dilation and length contraction have no relationship to speed at all'], 0),
    ('Why do time dilation and length contraction rarely affect everyday human experience?', ['Everyday speeds are far too slow relative to the speed of light for these relativistic effects to be noticeable', 'Time dilation and length contraction occur at every speed, no matter how slow', 'Special relativity applies only to objects located on Earths surface', 'These effects were disproven and no longer apply to modern physics'], 0)]),
SS('Social Studies: The Geography of Global Grain Trade and Food Export Restrictions',
   'Grade 9 Social Studies (Geography) strand: a small number of countries produce and export the majority of the worlds staple grains, and when a major exporter restricts or bans grain exports during a crisis, the resulting supply shock can sharply raise food prices and threaten food security in countries that depend on imports.',
   [('Why is the global grain trade often described as geographically concentrated?', ['A relatively small number of countries produce and export the majority of the worlds staple grains, such as wheat and corn', 'Every country in the world produces and exports an identical amount of grain', 'Grain production occurs evenly across every climate zone on Earth', 'The global grain trade has no geographic concentration of any kind'], 0),
    ('What is a food export restriction?', ['A policy in which a government limits or bans the export of a food commodity, often during a shortage or crisis', 'A policy that requires a country to export as much food as possible at all times', 'A rule that has no connection to international food trade', 'An agreement that always increases food exports during a crisis'], 0),
    ('Why might a major grain-exporting country impose an export restriction during a crisis?', ['To prioritize the availability and affordability of food for its own domestic population', 'To intentionally raise global food prices for other countries with no domestic benefit', 'Export restrictions have no effect on the food supply of any country', 'To permanently end all agricultural production within its own borders'], 0),
    ('How can a grain export restriction imposed by one major exporting country affect countries that depend on imports?', ['It can reduce global supply and sharply raise prices, threatening food security in import-dependent countries', 'It has no effect whatsoever on countries that rely on imported grain', 'It always lowers food prices in every importing country', 'Import-dependent countries are entirely unaffected by changes in global grain supply'], 0),
    ('Why do geographers study the concentration and trade patterns of staple grain production?', ['To understand how food security in many countries depends on the stability of a relatively small number of exporting regions', 'Grain production and trade have no relevance to the study of geography', 'Every country grows enough grain domestically to be entirely self-sufficient', 'This topic is considered purely a matter of nutrition, not geography'], 0)]),
]),
day(157, [
L('Vocabulary: Archaisms and Obsolete Word Forms',
  'Grade 9 Language strand: an archaism is a word or expression that was once common but has fallen out of everyday use, often surviving today only in historical texts, formal ceremonies, or deliberately old-fashioned writing.',
  [('What is an archaism?', ['A word or expression that was once common but has fallen out of everyday use', 'A brand new word that was invented within the last year', 'A punctuation mark used only in modern text messaging', 'A grammatical rule that applies only to future tense verbs'], 0),
   ('Where might a reader still commonly encounter archaisms today?', ['In historical texts, formal ceremonies, or writing deliberately styled to sound old-fashioned', 'Exclusively in casual text messages between friends', 'Only in modern scientific research papers', 'Archaisms never appear in any form of writing today'], 0),
   ('Which of these words would be considered an archaism in modern everyday English?', ['Thee, an old form of you', 'Computer', 'Internet', 'Smartphone'], 0),
   ('Why might an author deliberately use archaisms in a historical novel?', ['To create a sense of authenticity or atmosphere appropriate to the time period being depicted', 'To make the novel completely unreadable to any audience', 'Archaisms are always accidental and never used deliberately by authors', 'To ensure that the novel is set in the present day'], 0),
   ('How does an archaism differ from a neologism, a concept studied earlier in this course?', ['An archaism is an old word that has fallen out of use, while a neologism is a newly coined word', 'An archaism and a neologism refer to exactly the same kind of word', 'A neologism is always older than any archaism', 'Neither archaisms nor neologisms have any connection to how language changes'], 0)]),
M('Number Theory: Perfect, Deficient, and Abundant Numbers',
  'Grade 9 Math strand: a perfect number is equal to the sum of its proper divisors, a deficient number has a divisor sum less than the number itself, and an abundant number has a divisor sum greater than the number itself, offering a way to classify positive integers based on their divisors.',
  [('What is a perfect number?', ['A positive integer that is equal to the sum of its proper divisors', 'A positive integer with no divisors of any kind', 'Any number that is divisible by exactly two', 'A number whose only divisor is itself'], 0),
   ('What is the smallest perfect number, and what are its proper divisors?', ['6, whose proper divisors 1, 2, and 3 sum to 6', '10, whose proper divisors sum to 15', '28, whose proper divisors sum to 20', '4, whose proper divisors sum to 3'], 0),
   ('What defines a deficient number?', ['A positive integer whose proper divisors sum to less than the number itself', 'A positive integer whose proper divisors sum to exactly the number itself', 'A positive integer whose proper divisors sum to more than the number itself', 'A number that has no proper divisors whatsoever'], 0),
   ('What defines an abundant number?', ['A positive integer whose proper divisors sum to more than the number itself', 'A positive integer whose proper divisors sum to less than the number itself', 'A positive integer equal exactly to the sum of its proper divisors', 'A number that cannot be divided by any other number'], 0),
   ('Why are perfect, deficient, and abundant numbers considered part of number theory rather than simple arithmetic?', ['They involve classifying integers based on properties of their divisors, a central theme of number theory', 'They have no mathematical classification or pattern of any kind', 'These classifications only apply to negative numbers', 'They are used exclusively to measure geometric shapes'], 0)]),
Sc('Chemistry: Spectroscopy and Flame Tests: Identifying Elements',
   'Grade 9 Science strand: spectroscopy analyzes the specific wavelengths of light absorbed or emitted by a substance to identify its composition, and a flame test applies this idea practically by observing the characteristic colour a metal ion produces when heated in a flame.',
   [('What does spectroscopy analyze to help identify a substance?', ['The specific wavelengths of light that a substance absorbs or emits', 'Only the physical texture of a solid material', 'The exact temperature of a substance at room conditions', 'The sound produced when a substance is struck'], 0),
    ('What is a flame test used to identify?', ['The presence of specific metal ions, based on the characteristic colour they produce when heated in a flame', 'The exact boiling point of a liquid', 'The pH level of an acidic solution', 'The density of a solid object'], 0),
    ('What colour flame is commonly associated with the presence of copper ions in a flame test?', ['A blue-green colour', 'A bright yellow colour', 'A deep violet colour', 'No colour change at all'], 0),
    ('Why does each element tend to produce a distinctive pattern of emitted light?', ['Electrons in that elements atoms release specific amounts of energy as light when they fall back to lower energy levels', 'Every element produces exactly the same pattern of light with no distinguishing features', 'Light emission has no connection to the electrons within an atom', 'Only metals are capable of absorbing or emitting any light at all'], 0),
    ('Why is spectroscopy useful to astronomers studying distant stars, in addition to chemists in a laboratory?', ['It allows scientists to determine the chemical composition of a star based on the light it emits, even from great distances', 'Spectroscopy can only be used on objects that are physically accessible in a laboratory', 'Astronomers have no way of analyzing the light emitted by distant stars', 'Spectroscopy provides no information about chemical composition at all'], 0)]),
SS('Social Studies: The Geography of Antarctic and Polar Tourism',
   'Grade 9 Social Studies (Geography) strand: Antarctic and polar tourism has grown steadily in recent decades, drawing visitors to remote, fragile environments and raising questions about how to balance economic opportunity with environmental protection under agreements such as the Antarctic Treaty System.',
   [('What has generally happened to the level of tourism to Antarctica and other polar regions in recent decades?', ['It has grown steadily as more visitors seek out these remote destinations', 'It has completely disappeared with no visitors permitted at all', 'It has remained at exactly the same level since the region was first discovered', 'Polar tourism has never existed in any form'], 0),
    ('Why are polar regions considered particularly fragile environments for tourism?', ['Their ecosystems can be highly sensitive to disturbance, and recovery from damage can take a long time in extreme climates', 'Polar environments are considered the most resilient ecosystems on Earth', 'Tourism has no potential impact on polar ecosystems of any kind', 'Polar regions contain no living organisms that could be affected by visitors'], 0),
    ('How does the Antarctic Treaty System, studied earlier in this course, relate to Antarctic tourism?', ['It provides a framework of international agreements that help regulate human activity, including tourism, to protect the continent', 'The Antarctic Treaty System has no connection to tourism of any kind', 'The treaty system actively encourages unrestricted tourism with no oversight', 'Antarctic tourism operates entirely outside any international agreement'], 0),
    ('What economic opportunity can polar tourism provide to companies and nearby gateway communities?', ['Revenue from tour operators, transportation, and related services supporting visitors to the region', 'Polar tourism generates no economic activity of any kind', 'Gateway communities near polar regions receive no benefit from tourism', 'Tourism to polar regions is entirely free of charge for every visitor'], 0),
    ('Why might environmental groups express concern about the continued growth of polar tourism?', ['Increased visitor numbers could accelerate environmental disturbance in ecosystems that are slow to recover', 'Environmental groups have no interest in the effects of tourism on polar regions', 'More visitors to polar regions always improve the health of local ecosystems', 'Polar tourism has no possible connection to environmental impact'], 0)]),
]),
day(158, [
L('Reading: Analyzing Pastoral and Nature Imagery',
  'Grade 9 Language strand: pastoral imagery idealizes rural or natural settings, often to contrast the simplicity of nature with the complexity of urban or modern life, and writers use nature imagery more broadly to reflect a characters emotional state or reinforce a texts central themes.',
  [('What does pastoral imagery typically idealize?', ['Rural or natural settings, often contrasted with the complexity of urban or modern life', 'The chaos and noise of a busy modern city', 'The interior of a large industrial factory', 'A setting with no natural elements of any kind'], 0),
   ('Why might a writer use pastoral imagery to contrast with urban settings?', ['To emphasize a sense of simplicity, peace, or purity associated with nature compared to modern complexity', 'Pastoral imagery is only ever used to describe complicated machinery', 'To completely eliminate any reference to nature within a text', 'Contrast between settings never serves any purpose in literature'], 0),
   ('How can nature imagery reflect a characters emotional state in a piece of writing?', ['A storm might mirror inner turmoil, while a calm landscape might mirror peace or clarity', 'Nature imagery can never be connected to a characters emotions', 'Descriptions of weather always have no symbolic meaning whatsoever', 'Only dialogue, never imagery, can reveal a characters emotional state'], 0),
   ('Which of the following is an example of pastoral imagery?', ['A peaceful description of rolling green fields and grazing sheep', 'A description of a crowded, noisy subway station', 'A description of a busy corporate office building', 'A description of heavy highway traffic at rush hour'], 0),
   ('Why might recognizing nature imagery help a reader identify a texts central themes?', ['Recurring natural images are often deliberately chosen by an author to reinforce key ideas or emotional patterns throughout the text', 'Nature imagery has no connection to a texts central themes in any case', 'Recognizing imagery only helps identify punctuation choices, not themes', 'Themes can only be identified through direct statements, never imagery'], 0)]),
M('Calculus Preview: An Introduction to Related Rates',
  'Grade 9 Math strand: related rates problems use the derivative to connect how the rates of change of two or more related quantities are linked to each other, often by differentiating an equation that relates the quantities with respect to time.',
  [('What is the general goal of a related rates problem?', ['To determine how the rate of change of one quantity relates to the rate of change of another connected quantity', 'To find the exact area under a curve between two boundaries', 'To calculate the greatest common divisor of two related integers', 'To determine whether a function is continuous at a specific point'], 0),
   ('What mathematical tool is used to relate the rates of change of two connected quantities over time?', ['Differentiating an equation that relates the quantities, with respect to time', 'Simplifying a radical expression with no reference to time', 'Factoring a polynomial with no variables representing time', 'Graphing a single point with no connection to any rate'], 0),
   ('In a classic related rates problem involving a ladder sliding down a wall, what two rates are typically related?', ['The rate at which the base of the ladder slides away from the wall and the rate at which the top slides down the wall', 'The colour of the ladder and the length of the wall', 'The weight of the ladder and the temperature of the wall', 'The angle of the sun and the height of the wall alone'], 0),
   ('Why is the chain rule often essential when solving a related rates problem?', ['It allows a quantity that depends on time to be differentiated correctly within a larger equation', 'The chain rule has no application to problems involving multiple related quantities', 'Related rates problems never require differentiating with respect to time', 'The chain rule can only be applied to problems involving whole numbers'], 0),
   ('Which earlier calculus preview concept from this course is most directly built upon when studying related rates?', ['The derivative as a rate of change', 'The Euclidean algorithm', 'Sigma notation for finite sums', 'The Pythagorean theorem'], 0)]),
Sc('Biology: Plant Physiology: Transpiration and Nutrient Transport',
   'Grade 9 Science strand: transpiration is the evaporation of water from a plants leaves, which helps draw water and dissolved nutrients upward through the xylem, while sugars produced during photosynthesis are transported to other parts of the plant through the phloem.',
   [('What is transpiration?', ['The evaporation of water from the surface of a plants leaves', 'The process by which a plant absorbs sunlight for photosynthesis', 'The division of a single plant cell into two new cells', 'The process by which a plant releases oxygen exclusively at night'], 0),
    ('How does transpiration help transport water within a plant?', ['It creates a pulling force that helps draw water and dissolved nutrients upward through the xylem', 'Transpiration has no connection to the movement of water within a plant', 'It pushes water downward from the leaves into the surrounding soil', 'It causes water to move only within a single leaf, with no further transport'], 0),
    ('What is the primary function of the xylem in a plant?', ['Transporting water and dissolved minerals upward from the roots to the rest of the plant', 'Transporting sugars produced during photosynthesis to other parts of the plant', 'Producing new pollen for reproduction', 'Absorbing sunlight directly for use in photosynthesis'], 0),
    ('What is the primary function of the phloem in a plant?', ['Transporting sugars produced during photosynthesis to other parts of the plant', 'Transporting water upward from the roots to the leaves', 'Anchoring the plant firmly into the surrounding soil', 'Producing the pigment responsible for a leafs green colour'], 0),
    ('Why might a plant close the tiny pores on its leaves, called stomata, during a hot, dry day?', ['To reduce water loss through transpiration and help prevent dehydration', 'Closing stomata always increases the rate of water loss from a plant', 'Stomata have no connection to water loss or transpiration at all', 'Plants are physically unable to close their stomata under any conditions'], 0)]),
SS('Social Studies: The Geography of Language Policy and Official Bilingualism',
   'Grade 9 Social Studies (Geography) strand: language policy refers to the official decisions a government makes about which languages are used in education, government, and public life, and official bilingualism, as practiced in Canada, recognizes two languages with equal legal status at the federal level.',
   [('What is language policy?', ['The official decisions a government makes about which languages are used in education, government, and public life', 'A rule that forbids any government from using more than one language', 'A policy that applies only to private businesses, never to governments', 'A term with no connection to how governments function'], 0),
    ('What does official bilingualism, as practiced federally in Canada, recognize?', ['Two languages, English and French, with equal legal status at the federal level', 'A single official language recognized across the entire country', 'Three or more official languages recognized equally at the federal level', 'A policy that forbids the use of French in any federal institution'], 0),
    ('Why might a government adopt an official language policy recognizing more than one language?', ['To reflect the linguistic diversity or historical composition of its population and support access to services in multiple languages', 'Language policy is never influenced by the composition of a countrys population', 'Governments are legally required to recognize only a single language worldwide', 'Recognizing more than one language always eliminates the need for translation'], 0),
    ('What is one practical effect of official bilingualism on government services in Canada?', ['Federal government documents and services are generally required to be available in both English and French', 'Federal services are only available in a single language chosen at random', 'Official bilingualism has no effect on how government services are delivered', 'Bilingual policy applies only to private companies, never to the government'], 0),
    ('Why do geographers study language policy as part of political and cultural geography?', ['Language use is tied to identity, regional history, and the distribution of population groups across a territory', 'Language policy has no connection to geography of any kind', 'Every country in the world uses an identical language policy', 'This topic is considered purely a matter of linguistics, not geography'], 0)]),
]),
day(159, [
L('Writing: Writing a Letter to the Editor',
  'Grade 9 Language strand: a letter to the editor is a brief, persuasive piece submitted by a reader in response to a published article or current issue, typically stating a clear opinion and supporting it with concise, focused reasoning within a strict word limit.',
  [('What is a letter to the editor?', ['A brief, persuasive piece submitted by a reader in response to a published article or current issue', 'A private letter sent only to a single friend with no public audience', 'A formal legal document filed with a government office', 'An anonymous post with no stated opinion of any kind'], 0),
   ('What should a letter to the editor typically state clearly near its beginning?', ['A clear, focused opinion on the issue being addressed', 'A summary of an entirely unrelated news story', 'A list of the writers personal hobbies', 'A detailed biography of the writer with no reference to any issue'], 0),
   ('Why must a letter to the editor typically remain concise?', ['Publications generally enforce a strict word limit for reader-submitted letters', 'Letters to the editor have no length restrictions of any kind', 'Concise writing is discouraged in favour of very long letters', 'A letter to the editor must always exceed the length of the original article'], 0),
   ('How does a letter to the editor differ from the editorial (op-ed) studied earlier in this course?', ['A letter to the editor is submitted by a reader, while an editorial is typically written by a staff writer or invited columnist', 'A letter to the editor and an editorial are always written by exactly the same person', 'An editorial is always shorter than a letter to the editor', 'Letters to the editor are never published in newspapers or online publications'], 0),
   ('Why might a reader choose to write a letter to the editor?', ['To publicly respond to a published article and share a differing or supporting perspective with other readers', 'Letters to the editor are never intended to respond to anything', 'To avoid ever expressing a personal opinion on an issue', 'Because publications never accept any submissions from their readers'], 0)]),
M('Geometry: An Introduction to Spherical Coordinates',
  'Grade 9 Math strand: spherical coordinates locate a point in three-dimensional space using a radial distance from the origin and two angles, extending the idea of polar coordinates into three dimensions and offering a natural way to describe points on or near a sphere.',
  [('What three values are used to describe a point in spherical coordinates?', ['A radial distance from the origin and two angles', 'Only a single distance value with no angles at all', 'Three separate distances with no angles involved', 'A single angle and no distance value at all'], 0),
   ('How do spherical coordinates extend the idea of polar coordinates studied earlier in this course?', ['They add a second angle to describe position in three dimensions rather than just two', 'They remove the need for any angle measurement entirely', 'Spherical coordinates are entirely unrelated to polar coordinates', 'They reduce a three-dimensional description to a single number'], 0),
   ('Why are spherical coordinates a natural choice for describing points on or near a sphere?', ['The radial distance can remain constant while the two angles vary to describe every point on the spheres surface', 'Spherical coordinates cannot be used to describe any point on a sphere', 'A sphere has no meaningful relationship to any coordinate system', 'Spherical coordinates require the radial distance to change constantly'], 0),
   ('In spherical coordinates, what does the radial distance typically represent?', ['The straight-line distance from the origin to the point being described', 'The angle measured from a fixed reference axis', 'The height of the point above the ground only', 'The colour associated with the point being plotted'], 0),
   ('Spherical coordinates are commonly used in which real-world application?', ['Describing positions on Earths surface using latitude, longitude, and radius from Earths centre', 'Measuring the exact temperature of a liquid', 'Calculating the greatest common divisor of two integers', 'Determining the probability of a coin flip'], 0)]),
Sc('Environmental Science: Ocean Acidification and Its Effects on Marine Life',
   'Grade 9 Science strand: ocean acidification occurs as seawater absorbs excess carbon dioxide from the atmosphere, lowering the oceans pH and making it more difficult for many marine organisms to build and maintain their calcium carbonate shells and skeletons.',
   [('What causes ocean acidification?', ['Seawater absorbing excess carbon dioxide from the atmosphere, which lowers the oceans pH', 'A sudden and permanent increase in ocean water temperature alone', 'An increase in the amount of salt dissolved in seawater', 'A decrease in the total volume of water contained in the oceans'], 0),
    ('What happens to the pH of seawater as it absorbs more carbon dioxide?', ['The pH decreases, making the water more acidic', 'The pH increases, making the water more basic', 'The pH remains completely unchanged regardless of carbon dioxide levels', 'The pH becomes impossible to measure once carbon dioxide is absorbed'], 0),
    ('Which marine organisms are particularly vulnerable to the effects of ocean acidification?', ['Organisms that build calcium carbonate shells or skeletons, such as corals and some shellfish', 'Organisms with no shell or skeletal structure of any kind', 'Only organisms that live exclusively on land, not in the ocean', 'Organisms that never interact with seawater in any way'], 0),
    ('How does a lower ocean pH make it more difficult for organisms to build calcium carbonate structures?', ['More acidic water contains fewer of the carbonate ions needed to form and maintain these structures', 'A lower pH always increases the availability of carbonate ions in seawater', 'Ocean pH has no connection to an organisms ability to build shells', 'Acidic water makes calcium carbonate structures form more easily than before'], 0),
    ('Why is ocean acidification connected to the broader issue of rising atmospheric carbon dioxide levels?', ['The ocean absorbs a significant portion of the carbon dioxide released into the atmosphere, driving the acidification process', 'The ocean and the atmosphere have no chemical connection to each other', 'Atmospheric carbon dioxide levels have no effect on ocean chemistry', 'Ocean acidification occurs entirely independently of atmospheric conditions'], 0)]),
SS('Social Studies: The Geography of Fisheries Management and Overfishing',
   'Grade 9 Social Studies (Geography) strand: overfishing occurs when fish are harvested faster than populations can naturally replenish, and fisheries management uses tools such as catch limits, protected areas, and international agreements to try to sustain fish stocks and the coastal communities that depend on them.',
   [('What is overfishing?', ['Harvesting fish from a body of water faster than the population can naturally replenish itself', 'A practice in which no fish are ever harvested from a body of water', 'A method of fishing that always increases fish populations over time', 'A term with no connection to the sustainability of fish stocks'], 0),
    ('What is a common consequence of overfishing for a fish population?', ['A significant decline in population size, which can threaten the long-term viability of the fishery', 'Overfishing always causes fish populations to grow larger indefinitely', 'Fish populations are entirely unaffected by the rate at which they are harvested', 'Overfishing eliminates the need for any fisheries management'], 0),
    ('What is a catch limit in fisheries management?', ['A regulation restricting the total amount of fish that can be legally harvested within a given period', 'A rule requiring fishers to catch as many fish as physically possible', 'A limit that applies only to recreational swimming, not fishing', 'A term with no connection to regulating fish harvests'], 0),
    ('Why might countries negotiate international agreements regarding shared fish stocks?', ['Many fish populations migrate across maritime boundaries, requiring cooperation between countries to manage them sustainably', 'Fish populations never cross any international maritime boundaries', 'International cooperation has no relevance to managing shared natural resources', 'Countries are legally forbidden from cooperating on fisheries management'], 0),
    ('How can overfishing affect coastal communities that depend on fishing for their livelihood?', ['Declining fish stocks can reduce income and food security for communities that rely heavily on fishing', 'Overfishing always increases economic prosperity for coastal fishing communities', 'Coastal communities have no economic connection to local fish populations', 'Fisheries management has no effect on the livelihoods of coastal communities'], 0)]),
]),
day(160, [
L('Language Review: Restrictive Clauses, Irony, Speeches, and Letters to the Editor',
  'Grade 9 Language strand review: students revisit restrictive and nonrestrictive clauses, verbal and situational irony, the speech of introduction, emphatic and cleft sentences, and the letter to the editor from Days 151-159.',
  [('What is a restrictive clause?', ['A clause that provides essential information narrowing the meaning of the noun it modifies', 'A clause that can be removed without changing a sentences essential meaning', 'A punctuation mark that separates two independent clauses', 'A clause that always begins with a coordinating conjunction'], 0),
   ('What is situational irony?', ['When the actual outcome of a situation is strikingly different from what was expected', 'When a character speaks directly to the audience', 'When a speaker always states their literal, intended meaning', 'A device used only in formal persuasive essays'], 0),
   ('What is the main purpose of a speech of introduction?', ['To present a speaker or guest to an audience by highlighting relevant credentials and building interest', 'To deliver the entire main presentation instead of the featured speaker', 'To criticize the credentials of the speaker being introduced', 'To provide an unrelated summary of a completely different event'], 0),
   ('What is a cleft sentence?', ['A sentence divided into two clauses, often beginning with it or what, to highlight a specific piece of information', 'A sentence that contains no verbs of any kind', 'A sentence that must always begin with a question word', 'A type of sentence found only in poetry, never in prose'], 0),
   ('What is a letter to the editor?', ['A brief, persuasive piece submitted by a reader in response to a published article or current issue', 'A private letter sent only to a single friend with no public audience', 'A formal legal document filed with a government office', 'An anonymous post with no stated opinion of any kind'], 0)]),
M('Math Review: Trigonometric Graphs, Number Theory, and Spherical Coordinates',
  'Grade 9 Math strand review: students revisit graphing sine and cosine functions, the Chinese Remainder Theorem, mortgages and down payments, related rates, and spherical coordinates from Days 151-159.',
  [('What does the amplitude of a sine or cosine graph describe?', ['The maximum height of the wave above (or below) its midline', 'The total horizontal length of the graph', 'The number of times the graph crosses the x-axis', 'The steepness of the graph at the origin only'], 0),
   ('What condition must the moduli in a system satisfy for the Chinese Remainder Theorem to guarantee a unique solution?', ['The moduli must be pairwise coprime, meaning each pair shares no common factor greater than one', 'The moduli must all be equal to zero', 'The moduli must always be even numbers', 'The moduli must share every factor in common'], 0),
   ('What is a down payment?', ['An upfront payment representing a percentage of a propertys purchase price, paid before financing the remainder', 'The final payment made at the very end of a mortgage term', 'A fee charged only if a mortgage payment is missed', 'A payment that has no connection to purchasing property'], 0),
   ('What is the general goal of a related rates problem?', ['To determine how the rate of change of one quantity relates to the rate of change of another connected quantity', 'To find the exact area under a curve between two boundaries', 'To calculate the greatest common divisor of two related integers', 'To determine whether a function is continuous at a specific point'], 0),
   ('What three values are used to describe a point in spherical coordinates?', ['A radial distance from the origin and two angles', 'Only a single distance value with no angles at all', 'Three separate distances with no angles involved', 'A single angle and no distance value at all'], 0)]),
Sc('Science Review: Gas Laws, Relativity, Genetics, and Ocean Acidification',
   'Grade 9 Science strand review: students revisit Boyles Law and Charless Law, population genetics and the Hardy-Weinberg Principle, special relativity, plant physiology, and ocean acidification from Days 151-159.',
   [('What does Boyles Law describe?', ['The inverse relationship between the pressure and volume of a gas at constant temperature', 'The direct relationship between the volume and temperature of a gas at constant pressure', 'The relationship between the mass and colour of a gas', 'A rule that applies only to solids, never to gases'], 0),
    ('What does the Hardy-Weinberg Principle describe?', ['The conditions under which allele frequencies in a population remain stable across generations', 'The exact process by which a virus spreads between individuals', 'A rule that applies only to a single organism, never a population', 'The chemical structure of a strand of DNA'], 0),
    ('What is time dilation?', ['The effect in which a clock moving relative to an observer appears to run slower than a stationary clock', 'The effect in which time always passes at exactly the same rate for every observer', 'A phenomenon that only applies to objects at rest', 'An effect that causes clocks to run faster the slower an object moves'], 0),
    ('What is transpiration?', ['The evaporation of water from the surface of a plants leaves', 'The process by which a plant absorbs sunlight for photosynthesis', 'The division of a single plant cell into two new cells', 'The process by which a plant releases oxygen exclusively at night'], 0),
    ('What causes ocean acidification?', ['Seawater absorbing excess carbon dioxide from the atmosphere, which lowers the oceans pH', 'A sudden and permanent increase in ocean water temperature alone', 'An increase in the amount of salt dissolved in seawater', 'A decrease in the total volume of water contained in the oceans'], 0)]),
SS('Social Studies Review: Twin Cities, Remote Work, Grain Trade, and Fisheries',
   'Grade 9 Social Studies (Geography) strand review: students revisit cross-border metropolitan regions, global remote work and digital nomadism, the global fast fashion trade, global grain trade and food export restrictions, and fisheries management from Days 151-159.',
   [('What is a cross-border metropolitan region?', ['A functionally connected urban area formed by two cities in different countries linked by trade, commuting, and infrastructure', 'A city located entirely within a single countrys interior with no border nearby', 'A rural region with no urban development of any kind', 'A metropolitan area that has never had any international connections'], 0),
    ('What is a digital nomad?', ['A remote worker who lives and works from different locations, often across international borders, while maintaining employment elsewhere', 'A worker who is permanently required to work from a single fixed office location', 'A person with no access to the internet or digital technology', 'A farmer who moves seasonally to follow crop harvests'], 0),
    ('What is fast fashion?', ['A business model that produces inexpensive clothing quickly in response to rapidly changing trends', 'A method of producing clothing exclusively by hand over many years', 'A term describing only clothing manufactured within a single country', 'A style of clothing with no connection to global trade'], 0),
    ('What is a food export restriction?', ['A policy in which a government limits or bans the export of a food commodity, often during a shortage or crisis', 'A policy that requires a country to export as much food as possible at all times', 'A rule that has no connection to international food trade', 'An agreement that always increases food exports during a crisis'], 0),
    ('What is overfishing?', ['Harvesting fish from a body of water faster than the population can naturally replenish itself', 'A practice in which no fish are ever harvested from a body of water', 'A method of fishing that always increases fish populations over time', 'A term with no connection to the sustainability of fish stocks'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g9_151_160)
    append_to(9, g9_151_160)
