#!/usr/bin/env python3
"""Grade 11, Days 101-110 -- extends Grade 11 from 100 to 110 days. Topics
chosen to avoid any overlap with the existing Day 1-100 set (see
data/grade11.json): Gothic fiction and the uncanny, the villanelle and
other fixed poetic forms, the character sketch, the trickster figure in
folklore, meme analysis and digital rhetoric, code-switching and dialect
as literary voice, detective fiction and the whodunit, preparing for a
formal interview, and the book review as critical genre; the Euclidean
algorithm and greatest common divisor, propositional logic and the
contrapositive, confidence intervals and margin of error, vector
equations of lines, Eulerian and Hamiltonian paths, the intermediate
value theorem, the rational root theorem, an introduction to hypothesis
testing, and effective annual rate for comparing loans; comparative
digestion in ruminants and monogastrics, osmoconformers and
osmoregulators in marine life, comparative vision (camera eye vs
compound eye), insect metamorphosis, open vs closed circulatory systems,
nitrogenous waste excretion strategies, plant tissue systems, animal
locomotion adaptations, and cell cycle checkpoints; Avogadro's law and
molar volume, the common ion effect, the Arrhenius equation and
activation energy, addition vs condensation polymerization, Faraday's
laws of electrolysis, titration types beyond acid-base, the kinetic
molecular theory of gases, the chemistry of baking, and isotopic
abundance / average atomic mass calculations.

Topics were checked closely against near-neighbours already on the books
to avoid overlap: "The Character Sketch" is a short descriptive-writing
technique distinct from Day 65's analytical "Character Study Essay";
"Code-Switching and Dialect as Literary Voice" is distinct from Day 53's
grammar-focused "Nominalization and Academic Register"; "The Rational
Root Theorem" narrows in on identifying candidate roots, distinct from
Day 92's remainder theorem and synthetic division, which test/divide
once a candidate is known; "Comparative Vision" (camera eye vs compound
eye) is distinct from Day 54's human-focused "Sensory Systems -- Vision
and the Eye"; "Nitrogenous Waste" is distinct from Day 34's excretory
system/homeostasis and Day 52's osmosis/cell transport, focusing
specifically on ammonia/urea/uric acid excretion strategies; "The Cell
Cycle: Checkpoints and Regulation of Mitosis" narrows in on a specific
regulatory mechanism distinct from Day 2's general "Mitosis and Meiosis
Compared"; "The Kinetic Molecular Theory of Gases" is the particle-level
model distinct from the empirical gas laws of Day 31 and the Ideal Gas
Law/molar volume of Day 72; "The Common Ion Effect" extends Day 77's
solubility product constant the way Day 81's buffer capacity extended
Day 75's weak acid/base equilibria.

Subject keys for Grade 11 are "English", "Functions", "Biology",
"Chemistry" (same as all earlier Grade 11 batches).

videoUrl is intentionally left unset for every subject --
fetch_video_ids.py fills these in automatically on its next daily run.
No embedded ASCII double-quote characters are used anywhere in
question/summary/option text; apostrophes use the curly Unicode form
(’).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_curriculum import sub, day, append_to

E11 = 'https://tvolearn.com/pages/grade-11-english'
F11 = 'https://tvolearn.com/pages/grade-11-functions'
B11 = 'https://tvolearn.com/pages/grade-11-biology'
C11 = 'https://tvolearn.com/pages/grade-11-chemistry'
RE, RF, RB, RC = (
    'TVO Learn: Grade 11 English',
    'TVO Learn: Grade 11 Functions',
    'TVO Learn: Grade 11 Biology',
    'TVO Learn: Grade 11 Chemistry',
)


def E(t, s, q):
    return sub('English', t, s, RE, E11, q)


def F(t, s, q):
    return sub('Functions', t, s, RF, F11, q)


def B(t, s, q):
    return sub('Biology', t, s, RB, B11, q)


def C(t, s, q):
    return sub('Chemistry', t, s, RC, C11, q)


def _rebalance_answer_positions(days, seed=20260930):
    import random
    rng = random.Random(seed)
    quizzes = [sub_entry[5] for _, subs in days for sub_entry in subs]
    n = sum(len(q) for q in quizzes)
    targets = [i % 4 for i in range(n)]
    rng.shuffle(targets)
    idx = 0
    for quiz in quizzes:
        for i, (q, opts, ans) in enumerate(quiz):
            correct_text = opts[ans]
            wrong_texts = [o for j, o in enumerate(opts) if j != ans]
            rng.shuffle(wrong_texts)
            target = targets[idx]
            idx += 1
            new_opts = [None, None, None, None]
            new_opts[target] = correct_text
            wi = 0
            for slot in range(4):
                if new_opts[slot] is None:
                    new_opts[slot] = wrong_texts[wi]
                    wi += 1
            quiz[i] = (q, new_opts, target)
    return days


g11_101_110 = [
day(101, [
E('Literature: Gothic Fiction and the Uncanny',
  'Grade 11 English strand: Gothic fiction blends horror, romance, and the supernatural, often set in decaying architecture, to explore the uncanny — the unsettling sense of something being simultaneously familiar and strange.',
  [('What does Gothic fiction typically blend?', ['Horror, romance, and the supernatural', 'Only realistic depictions of everyday life', 'A concept unrelated to literature', 'A strictly comedic tone with no serious themes'], 0),
   ('Is Gothic fiction often set in decaying or isolated architecture, such as castles or old mansions?', ['Yes', 'No, Gothic fiction never uses architecture as a setting', 'A concept unrelated to Gothic fiction', 'Architecture has no connection to this genre'], 0),
   ('Does the uncanny describe something that feels both familiar and unsettlingly strange at once?', ['Yes', 'No, the uncanny has no connection to feelings of familiarity or strangeness', 'A concept unrelated to Gothic fiction', 'Familiarity and strangeness can never occur together in fiction'], 0),
   ('Why might a Gothic novelist set a story in a crumbling, ancestral mansion rather than a modern city apartment?', ['A decaying, isolated setting can heighten a sense of dread, mystery, and the characters’ entrapment by the past', 'A crumbling mansion never has any effect on a story’s atmosphere', 'This concept has no connection to literature', 'Modern settings always create more suspense than historical ones in Gothic fiction'], 0),
   ('Why has Gothic fiction remained influential in shaping later horror and suspense genres?', ['Its techniques for building dread, atmosphere, and psychological unease established conventions that later writers continued to adapt', 'Gothic fiction has had no influence on any later literary genre', 'This concept has no relevance to literature', 'Horror and suspense genres never draw on any earlier literary conventions'], 0)]),
F('Number Theory: The Euclidean Algorithm and Greatest Common Divisor',
  'Grade 11 Functions strand: the Euclidean algorithm finds the greatest common divisor of two integers by repeatedly applying the division algorithm, replacing the larger number with the remainder until a remainder of zero is reached.',
  [('What does the Euclidean algorithm find?', ['The greatest common divisor of two integers', 'The least common multiple of two integers only', 'A concept unrelated to number theory', 'The exact prime factorization of a number'], 0),
   ('Does the Euclidean algorithm involve repeatedly applying division and keeping track of remainders?', ['Yes', 'No, the Euclidean algorithm never involves division or remainders', 'A concept unrelated to the Euclidean algorithm', 'Remainders have no connection to finding a greatest common divisor'], 0),
   ('Applying the Euclidean algorithm to 48 and 18, is the greatest common divisor 6?', ['Yes', 'No, the greatest common divisor of 48 and 18 is not 6', 'A concept unrelated to the Euclidean algorithm', 'Greatest common divisors are never single, specific numbers'], 0),
   ('Why does the Euclidean algorithm stop once a remainder of zero is reached?', ['A remainder of zero indicates that the previous divisor evenly divides both original numbers, making it their greatest common divisor', 'A remainder of zero never signals anything meaningful about two integers', 'This concept has no connection to functions', 'The algorithm continues indefinitely even after reaching a remainder of zero'], 0),
   ('Why is the Euclidean algorithm considered more efficient than listing all factors of two large numbers to find their greatest common divisor?', ['It requires only a small number of division steps, even for very large integers, rather than an exhaustive search through all possible factors', 'The Euclidean algorithm is never more efficient than listing all factors of a number', 'This concept has no relevance to functions', 'Listing all factors of a large number is always faster than applying the Euclidean algorithm'], 0)]),
B('Comparative Digestion: Ruminant and Monogastric Digestive Strategies',
  'Grade 11 Biology strand: ruminant animals, such as cows, use a multi-chambered stomach and microbial fermentation to break down cellulose in plant material, while monogastric animals rely on a single-chambered stomach and enzymatic digestion.',
  [('What do ruminant animals use to break down cellulose in plant material?', ['A multi-chambered stomach and microbial fermentation', 'Only a single-chambered stomach with no microbes involved', 'A concept unrelated to biology', 'A completely liquid diet with no solid plant material'], 0),
   ('Do monogastric animals rely on a single-chambered stomach for digestion?', ['Yes', 'No, monogastric animals always have a multi-chambered stomach', 'A concept unrelated to comparative digestion', 'Stomach structure has no connection to how an animal digests food'], 0),
   ('Do microbes in a ruminant’s stomach help ferment and break down cellulose that the animal’s own enzymes cannot digest?', ['Yes', 'No, microbes play no role in a ruminant’s digestion', 'A concept unrelated to ruminant digestion', 'Cellulose can always be digested directly by an animal’s own enzymes alone'], 0),
   ('Why might a cow re-chew previously swallowed plant material, a process called rumination?', ['Re-chewing further breaks down tough plant fibres, increasing the surface area available for microbial fermentation', 'Re-chewing swallowed food never aids in digestion', 'This concept has no connection to biology', 'Rumination has no relationship to how efficiently cellulose is broken down'], 0),
   ('Why is understanding the difference between ruminant and monogastric digestion useful for agricultural feed planning?', ['Different digestive strategies process nutrients differently, so feed composition can be tailored to what each type of animal can efficiently digest', 'Digestive strategy has no connection to how animals should be fed', 'This concept has no relevance to biology', 'All animals digest exactly the same types of feed with equal efficiency'], 0)]),
C('Chemistry: Avogadro’s Law and Molar Volume at STP',
  'Grade 11 Chemistry strand: Avogadro’s law states that equal volumes of gases at the same temperature and pressure contain equal numbers of particles, meaning one mole of any ideal gas occupies the same molar volume at standard temperature and pressure.',
  [('What does Avogadro’s law state about equal volumes of gases at the same temperature and pressure?', ['They contain equal numbers of particles', 'They always contain completely different numbers of particles', 'A concept unrelated to chemistry', 'They must be composed of the exact same element'], 0),
   ('At standard temperature and pressure, does one mole of any ideal gas occupy approximately the same molar volume?', ['Yes', 'No, molar volume at STP is never the same for different gases', 'A concept unrelated to Avogadro’s law', 'Molar volume has no connection to the number of moles of gas present'], 0),
   ('Is the molar volume of an ideal gas at STP approximately 22.4 litres per mole?', ['Yes', 'No, the molar volume of a gas at STP is never close to 22.4 litres per mole', 'A concept unrelated to molar volume', 'Litres per mole is never a unit used to describe molar volume'], 0),
   ('Why can Avogadro’s law be used to compare the number of moles of two different gases without knowing their molar masses?', ['Since equal volumes at the same temperature and pressure contain equal numbers of particles, comparing gas volumes directly reveals the ratio of moles present', 'Avogadro’s law never allows the number of moles of a gas to be estimated from its volume', 'This concept has no connection to chemistry', 'Molar mass must always be known before comparing the number of moles in two gas samples'], 0),
   ('Why is the concept of molar volume at STP useful for stoichiometric calculations involving gases?', ['It allows the volume of a gas to be converted directly into moles, without needing to measure its mass', 'Molar volume has no connection to stoichiometric calculations involving gases', 'This concept has no relevance to chemistry', 'Gas volumes can never be used in stoichiometric calculations'], 0)]),
]),

day(102, [
E('Poetry: The Villanelle and Other Fixed Poetic Forms',
  'Grade 11 English strand: the villanelle is a nineteen-line poem built on two repeating refrains and an alternating rhyme scheme, illustrating how fixed poetic forms impose structural constraints that shape a poem’s meaning and emotional effect.',
  [('How many lines does a traditional villanelle contain?', ['Nineteen', 'Fourteen', 'A concept unrelated to poetry', 'Twelve'], 0),
   ('Does a villanelle rely on two repeating refrain lines throughout the poem?', ['Yes', 'No, a villanelle never repeats any lines', 'A concept unrelated to fixed poetic forms', 'Repetition has no connection to the villanelle form'], 0),
   ('Is a villanelle considered a fixed poetic form with a set structure, unlike free verse?', ['Yes', 'No, a villanelle has no fixed structure at all', 'A concept unrelated to fixed poetic forms', 'Fixed structure is never a feature of any poem'], 0),
   ('Why might a poet choose the villanelle’s repeating refrains to convey a feeling of obsession or inescapable memory?', ['The return of the same lines throughout the poem can mirror a thought or feeling that keeps resurfacing, reinforcing the theme through form', 'Repeating refrains never have any effect on a poem’s emotional impact', 'This concept has no connection to poetry', 'A villanelle’s structure always works against conveying any specific emotion'], 0),
   ('Why do poets sometimes choose to work within a demanding fixed form like the villanelle rather than writing in free verse?', ['Working within strict formal constraints can push a poet toward unexpected, inventive language and can reinforce a poem’s meaning through its structure', 'Fixed poetic forms never influence a poem’s language or meaning', 'This concept has no relevance to poetry', 'Free verse is always considered a more disciplined form than any fixed form'], 0)]),
F('Discrete Math: Propositional Logic — Conditional Statements and Contrapositives',
  'Grade 11 Functions strand: propositional logic analyzes conditional statements of the form if p then q, and every conditional statement has a logically equivalent contrapositive formed by negating and reversing its two parts.',
  [('What does a conditional statement in propositional logic take the form of?', ['If p then q', 'p is always equal to q', 'A concept unrelated to functions', 'p multiplied by q'], 0),
   ('Is the contrapositive of a conditional statement formed by negating and reversing its two parts?', ['Yes', 'No, a contrapositive has no connection to negating or reversing a statement’s parts', 'A concept unrelated to propositional logic', 'Contrapositives are never logically related to their original conditional statement'], 0),
   ('Is a conditional statement always logically equivalent to its contrapositive?', ['Yes', 'No, a conditional statement is never logically equivalent to its contrapositive', 'A concept unrelated to conditional statements', 'Logical equivalence has no connection to contrapositives'], 0),
   ('What is the contrapositive of the statement, if it rains, then the ground is wet?', ['If the ground is not wet, then it did not rain', 'If it does not rain, then the ground is not wet', 'If the ground is wet, then it rains', 'The ground is always wet regardless of rain'], 0),
   ('Why is understanding the contrapositive useful when trying to prove a conditional statement is true?', ['Since a statement and its contrapositive are always logically equivalent, proving the contrapositive is sometimes an easier way to establish the same result', 'The contrapositive of a statement is never useful for proving anything', 'This concept has no relevance to functions', 'A conditional statement and its contrapositive can never both be proven using the same reasoning'], 0)]),
B('Biology: Osmoconformers and Osmoregulators in Marine Life',
  'Grade 11 Biology strand: osmoconformers allow their internal osmotic concentration to match that of their surrounding seawater, while osmoregulators actively maintain a stable internal osmotic concentration that differs from their environment.',
  [('What do osmoconformers allow their internal osmotic concentration to do?', ['Match that of their surrounding seawater', 'Remain fixed regardless of the surrounding environment', 'A concept unrelated to biology', 'Increase indefinitely without any limit'], 0),
   ('Do osmoregulators actively maintain an internal osmotic concentration that differs from their environment?', ['Yes', 'No, osmoregulators never maintain any difference from their surrounding environment', 'A concept unrelated to osmoregulation', 'Internal osmotic concentration is never actively controlled by osmoregulators'], 0),
   ('Are most marine invertebrates, such as jellyfish, generally considered osmoconformers?', ['Yes', 'No, marine invertebrates are never considered osmoconformers', 'A concept unrelated to osmoconformers', 'Osmoconformity has no connection to marine invertebrates'], 0),
   ('Why might an osmoregulator, such as a marine bony fish, expend significant metabolic energy to maintain its internal salt balance?', ['Actively pumping ions against a concentration gradient requires continuous energy, but it allows the fish to maintain stable internal conditions despite living in salty seawater', 'Maintaining internal salt balance never requires any metabolic energy', 'This concept has no connection to biology', 'Osmoregulators never need to expend any energy to control their internal environment'], 0),
   ('Why might osmoconformity be a less energetically costly strategy than osmoregulation for an organism living in a stable marine environment?', ['Allowing internal concentration to match a stable external environment avoids the continuous energy expenditure required to actively pump ions against a gradient', 'Osmoconformity always requires more energy than osmoregulation', 'This concept has no relevance to biology', 'Energy expenditure has no connection to how an organism manages its internal osmotic balance'], 0)]),
C('Chemistry: The Common Ion Effect and Solubility Equilibria',
  'Grade 11 Chemistry strand: the common ion effect describes how the solubility of a slightly soluble ionic compound decreases when a solution already contains an ion identical to one produced by that compound’s dissolution.',
  [('What does the common ion effect describe?', ['How the solubility of a slightly soluble compound decreases when a solution already contains a matching ion', 'How solubility always increases regardless of the ions present in solution', 'A concept unrelated to chemistry', 'How a compound’s colour changes when dissolved in water'], 0),
   ('Does adding a common ion to a saturated solution shift the solubility equilibrium to favour the solid, undissolved form?', ['Yes', 'No, adding a common ion never affects a solubility equilibrium', 'A concept unrelated to the common ion effect', 'Solubility equilibria are never influenced by the ions already present in a solution'], 0),
   ('Would adding sodium chloride to a saturated silver chloride solution decrease the solubility of the silver chloride due to the shared chloride ion?', ['Yes', 'No, adding sodium chloride would never affect the solubility of silver chloride', 'A concept unrelated to the common ion effect', 'Shared ions between two compounds never influence solubility equilibria'], 0),
   ('Why does the common ion effect follow directly from Le Chatelier’s principle?', ['Adding a product ion to the solubility equilibrium shifts the reaction toward the reactant side, favouring the undissolved solid and reducing further dissolution', 'Le Chatelier’s principle has no connection to solubility equilibria', 'This concept has no connection to chemistry', 'Adding a product ion always shifts an equilibrium further toward the product side'], 0),
   ('Why is the common ion effect an important consideration when calculating the solubility of a compound in a solution that already contains dissolved ions?', ['Ignoring the presence of a common ion would lead to an inaccurate, overestimated solubility calculation for that compound', 'The common ion effect has no relevance to accurately calculating a compound’s solubility', 'This concept has no relevance to chemistry', 'Solubility calculations are never affected by other ions already present in a solution'], 0)]),
]),

day(103, [
E('Writing: The Character Sketch — Capturing Personality Through Detail',
  'Grade 11 English strand: a character sketch is a brief piece of descriptive writing that conveys a character’s personality, appearance, and mannerisms through carefully selected, concrete details rather than direct explanation.',
  [('What does a character sketch primarily aim to convey?', ['A character’s personality, appearance, and mannerisms through concrete detail', 'A complete plot summary of an entire novel', 'A concept unrelated to writing', 'A formal citation of a source used in an essay'], 0),
   ('Does an effective character sketch typically rely on specific, concrete details rather than simply stating a character’s traits directly?', ['Yes', 'No, a character sketch always states a character’s traits directly with no supporting detail', 'A concept unrelated to character sketches', 'Concrete details have no connection to how a character sketch is written'], 0),
   ('Might a character sketch describe a small, specific habit, like tapping a pen, to suggest nervousness rather than stating the character is nervous?', ['Yes', 'No, a character sketch never uses small habits to suggest a personality trait', 'A concept unrelated to character sketches', 'Small habits are never useful details in descriptive writing'], 0),
   ('Why might a writer choose to show a character nervously twisting a ring rather than simply writing that the character felt anxious?', ['A specific, physical detail allows readers to infer the character’s emotional state themselves, making the description feel more vivid and convincing', 'Showing a specific physical detail never conveys any emotional state to a reader', 'This concept has no connection to writing', 'Stating a character’s emotion directly is always more effective than showing it through detail'], 0),
   ('Why is the character sketch a useful exercise for writers developing longer works of fiction?', ['Focusing closely on a single character’s traits and mannerisms can help a writer develop a consistent, believable voice before drafting a full narrative', 'Character sketches have no connection to developing longer works of fiction', 'This concept has no relevance to writing', 'Writers never need to understand a character’s personality before writing a longer narrative'], 0)]),
F('Statistics: Confidence Intervals and Margin of Error',
  'Grade 11 Functions strand: a confidence interval provides a range of values, built around a sample statistic, that is likely to contain the true population parameter, with the margin of error determining the width of that range.',
  [('What does a confidence interval provide?', ['A range of values likely to contain the true population parameter', 'A single, exact value that always equals the population parameter', 'A concept unrelated to statistics', 'A list of every value ever recorded in the sample'], 0),
   ('Does the margin of error determine the width of a confidence interval?', ['Yes', 'No, the margin of error has no connection to the width of a confidence interval', 'A concept unrelated to confidence intervals', 'Confidence intervals are never affected by margin of error'], 0),
   ('Does increasing the sample size generally decrease the margin of error, producing a narrower confidence interval?', ['Yes', 'No, increasing sample size always increases the margin of error', 'A concept unrelated to margin of error', 'Sample size has no connection to a confidence interval’s width'], 0),
   ('Why might a survey with only 20 respondents produce a much wider confidence interval than one with 2,000 respondents?', ['A smaller sample provides less information about the population, increasing the uncertainty and widening the margin of error around the estimate', 'A smaller sample size never affects the width of a confidence interval', 'This concept has no connection to functions', 'Sample size never has any relationship to the precision of a statistical estimate'], 0),
   ('Why is reporting a confidence interval, rather than a single sample statistic alone, considered good statistical practice?', ['It communicates the level of uncertainty in an estimate, giving a more honest picture of how precisely the true population value is known', 'Reporting a confidence interval never provides any additional useful information beyond a single statistic', 'This concept has no relevance to functions', 'A single sample statistic is always exactly equal to the true population parameter'], 0)]),
B('Biology: Comparative Vision — The Camera Eye and the Compound Eye',
  'Grade 11 Biology strand: the vertebrate camera eye forms a single focused image using a lens and retina, while the arthropod compound eye uses many individual light-sensing units called ommatidia to build a mosaic-like image especially suited to detecting motion.',
  [('What does the vertebrate camera eye use to form a single focused image?', ['A lens and a retina', 'Thousands of independent light-sensing units', 'A concept unrelated to biology', 'No light-sensitive structures whatsoever'], 0),
   ('Does the arthropod compound eye consist of many individual units called ommatidia?', ['Yes', 'No, the compound eye has no connection to individual light-sensing units', 'A concept unrelated to comparative vision', 'Ommatidia are never found in an arthropod’s eye'], 0),
   ('Is the compound eye generally considered especially effective at detecting motion?', ['Yes', 'No, the compound eye is never effective at detecting motion', 'A concept unrelated to compound eyes', 'Motion detection has no connection to how a compound eye functions'], 0),
   ('Why might an insect’s compound eye be well suited to detecting a rapidly approaching predator even without forming a sharp, detailed image?', ['Each ommatidium can detect changes in light independently, so a moving object triggers a rapid, staggered pattern of activation across many units, making motion easy to detect', 'A compound eye never provides any advantage in detecting movement', 'This concept has no connection to biology', 'Detailed image sharpness is always more important than motion detection for insect survival'], 0),
   ('Why is comparing the camera eye and the compound eye a useful example of adaptation to the shared challenge of detecting light?', ['Both structures independently evolved solutions for sensing light and forming a usable image, despite arising in very different evolutionary lineages', 'Comparing these two eye types provides no insight into how vision evolved', 'This concept has no relevance to biology', 'The camera eye and compound eye are always considered identical in structure and function'], 0)]),
C('Chemistry: The Arrhenius Equation and Activation Energy',
  'Grade 11 Chemistry strand: the Arrhenius equation quantitatively relates a reaction’s rate constant to its activation energy and temperature, showing that reaction rate increases sharply as either temperature rises or activation energy falls.',
  [('What does the Arrhenius equation relate a reaction’s rate constant to?', ['Its activation energy and temperature', 'Only the colour of the reactants involved', 'A concept unrelated to chemistry', 'The exact volume of the reaction container'], 0),
   ('According to the Arrhenius equation, does increasing temperature generally increase a reaction’s rate constant?', ['Yes', 'No, increasing temperature always decreases a reaction’s rate constant', 'A concept unrelated to the Arrhenius equation', 'Temperature has no connection to a reaction’s rate constant'], 0),
   ('Does a lower activation energy generally correspond to a faster reaction rate, according to the Arrhenius equation?', ['Yes', 'No, activation energy has no connection to reaction rate', 'A concept unrelated to activation energy', 'A lower activation energy always corresponds to a slower reaction rate'], 0),
   ('Why might a catalyst increase a reaction’s rate without being consumed in the reaction?', ['A catalyst provides an alternative reaction pathway with a lower activation energy, allowing more particles to react successfully without altering the catalyst itself', 'A catalyst never has any effect on a reaction’s activation energy', 'This concept has no connection to chemistry', 'Catalysts are always consumed entirely during the reactions they speed up'], 0),
   ('Why is the Arrhenius equation useful for predicting how sensitive a reaction’s rate is to changes in temperature?', ['It shows mathematically that even small increases in temperature can produce large increases in reaction rate, particularly for reactions with high activation energy', 'The Arrhenius equation has no connection to predicting how temperature affects reaction rate', 'This concept has no relevance to chemistry', 'Reaction rate is never sensitive to changes in temperature'], 0)]),
]),

day(104, [
E('Literature: The Trickster Figure in Folklore and Fiction',
  'Grade 11 English strand: the trickster is a recurring archetype who uses wit, deception, and rule-breaking to disrupt social order, often appearing across diverse folklore traditions and continuing to shape characters in contemporary fiction.',
  [('What does the trickster archetype typically use to disrupt social order?', ['Wit, deception, and rule-breaking', 'Only brute physical strength', 'A concept unrelated to literature', 'Strict, unwavering obedience to every rule'], 0),
   ('Does the trickster figure appear across many diverse folklore traditions around the world?', ['Yes', 'No, the trickster figure appears in only one single culture’s folklore', 'A concept unrelated to the trickster archetype', 'Folklore traditions never share any common character archetypes'], 0),
   ('Can a trickster character be both mischievous and, at times, a source of important wisdom or change?', ['Yes', 'No, a trickster character is never anything more than purely mischievous', 'A concept unrelated to trickster figures', 'Wisdom is never associated with the trickster archetype'], 0),
   ('Why might an author use a trickster character to challenge a story’s existing power structures or social norms?', ['The trickster’s willingness to break rules and outwit authority figures can expose the flaws or rigidity of those existing structures', 'A trickster character never challenges any existing power structure or social norm', 'This concept has no connection to literature', 'Power structures in fiction are never challenged by any type of character'], 0),
   ('Why does the trickster archetype remain a compelling figure in contemporary fiction and film?', ['Its blend of cleverness, unpredictability, and moral ambiguity continues to offer writers a flexible way to critique authority and entertain audiences', 'The trickster archetype has no relevance to any contemporary fiction or film', 'This concept has no relevance to literature', 'Contemporary fiction never draws on archetypes found in traditional folklore'], 0)]),
F('Geometry: Vector Equations of Lines in Two Dimensions',
  'Grade 11 Functions strand: a line in two dimensions can be described using a vector equation, combining a known point on the line with a direction vector scaled by a parameter, offering an alternative to the standard slope-intercept form.',
  [('What does a vector equation of a line combine?', ['A known point on the line with a direction vector scaled by a parameter', 'Only two unrelated points with no direction specified', 'A concept unrelated to functions', 'The exact length of the line segment being described'], 0),
   ('Does a vector equation of a line rely on a direction vector to describe the line’s orientation?', ['Yes', 'No, a vector equation never uses a direction vector', 'A concept unrelated to vector equations of lines', 'Direction has no connection to how a vector equation describes a line'], 0),
   ('Can two different points on the same line, combined with the same direction vector, both produce valid vector equations for that line?', ['Yes', 'No, only one single point can ever be used to write a line’s vector equation', 'A concept unrelated to vector equations', 'A line can never be described using more than one vector equation'], 0),
   ('Why might a vector equation be more useful than slope-intercept form when describing a line in a physics or engineering context involving motion?', ['A vector equation naturally incorporates both a starting position and a direction of travel, which closely models an object’s position changing over time', 'A vector equation never provides any advantage over slope-intercept form in any context', 'This concept has no connection to functions', 'Slope-intercept form always models motion more effectively than a vector equation'], 0),
   ('Why is understanding vector equations of lines a useful foundation for later work with lines and planes in three dimensions?', ['The same parameter-based approach extends naturally from two dimensions into three, where slope-intercept form no longer directly applies', 'Vector equations of lines have no connection to describing lines or planes in three dimensions', 'This concept has no relevance to functions', 'Three-dimensional geometry never requires any concept related to vectors'], 0)]),
B('Biology: Insect Metamorphosis — Complete and Incomplete Development',
  'Grade 11 Biology strand: complete metamorphosis proceeds through four distinct stages, egg, larva, pupa, and adult, while incomplete metamorphosis proceeds through egg, nymph, and adult stages without a pupal stage.',
  [('How many distinct stages does complete metamorphosis proceed through?', ['Four: egg, larva, pupa, and adult', 'Only two stages total', 'A concept unrelated to biology', 'Six entirely different stages'], 0),
   ('Does incomplete metamorphosis skip the pupal stage found in complete metamorphosis?', ['Yes', 'No, incomplete metamorphosis always includes a pupal stage', 'A concept unrelated to insect metamorphosis', 'A pupal stage has no connection to distinguishing these two types of development'], 0),
   ('Do butterflies undergo complete metamorphosis, including a pupal, or chrysalis, stage?', ['Yes', 'No, butterflies never undergo any pupal stage', 'A concept unrelated to complete metamorphosis', 'A chrysalis stage is never associated with butterfly development'], 0),
   ('Why might a larva, such as a caterpillar, look and behave completely differently from its adult form, such as a butterfly?', ['During the pupal stage, the organism’s body undergoes a dramatic reorganization of tissues, producing an adult body plan suited to a very different role, such as reproduction and dispersal', 'A larva and its adult form are always identical in appearance and behaviour', 'This concept has no connection to biology', 'Metamorphosis never changes an insect’s body plan between life stages'], 0),
   ('Why might complete metamorphosis reduce competition for resources between the young and adult stages of the same insect species?', ['Because larvae and adults often occupy different habitats and eat different foods, they are less likely to compete directly with one another for the same limited resources', 'Complete metamorphosis never affects how young and adult insects compete for resources', 'This concept has no relevance to biology', 'Larvae and adults of the same species always compete directly for identical resources'], 0)]),
C('Chemistry: Addition versus Condensation Polymerization',
  'Grade 11 Chemistry strand: addition polymerization joins monomers together without losing any atoms, while condensation polymerization joins monomers together while releasing a small molecule, such as water, as a byproduct.',
  [('What happens to the atoms of monomers during addition polymerization?', ['No atoms are lost as the monomers join together', 'All atoms are converted into an entirely different element', 'A concept unrelated to chemistry', 'The monomers are destroyed rather than joined'], 0),
   ('Does condensation polymerization release a small molecule, such as water, as a byproduct?', ['Yes', 'No, condensation polymerization never releases any byproduct', 'A concept unrelated to condensation polymerization', 'Byproducts are never released during any type of polymerization'], 0),
   ('Are addition polymers, such as polyethylene, typically formed from monomers containing carbon-carbon double bonds?', ['Yes', 'No, addition polymers never form from monomers containing double bonds', 'A concept unrelated to addition polymerization', 'Carbon-carbon double bonds have no connection to addition polymerization'], 0),
   ('Why does condensation polymerization typically require monomers with two reactive functional groups, one on each end?', ['Having two reactive ends allows each monomer to bond with two neighbouring monomers, enabling a continuous chain to form as small molecules like water are released', 'Condensation polymerization never requires monomers with more than one reactive functional group', 'This concept has no connection to chemistry', 'Reactive functional groups have no relationship to how a polymer chain forms'], 0),
   ('Why is understanding the distinction between addition and condensation polymerization important for predicting a polymer’s properties and byproducts?', ['Knowing the mechanism reveals what byproducts, if any, are released and helps explain differences in the resulting polymer’s structure and characteristics', 'This distinction has no connection to a polymer’s resulting properties or byproducts', 'This concept has no relevance to chemistry', 'All polymerization reactions always produce identical byproducts regardless of mechanism'], 0)]),
]),

day(105, [
E('Media Literacy: Analyzing Memes and Digital Rhetoric',
  'Grade 11 English strand: memes combine image and concise text to spread ideas rapidly online, and analyzing their digital rhetoric involves examining how humour, irony, and repetition are used to persuade or shape public opinion.',
  [('What do memes typically combine to spread ideas rapidly online?', ['Image and concise text', 'Only lengthy, unrelated paragraphs of text', 'A concept unrelated to media literacy', 'Audio recordings with no accompanying visuals'], 0),
   ('Does analyzing a meme’s digital rhetoric involve examining how humour and irony are used to persuade an audience?', ['Yes', 'No, digital rhetoric never involves examining humour or irony', 'A concept unrelated to memes', 'Persuasion has no connection to how memes function online'], 0),
   ('Can the rapid, widespread repetition of a meme format across social media strengthen its persuasive impact?', ['Yes', 'No, repetition never strengthens a meme’s persuasive impact', 'A concept unrelated to digital rhetoric', 'Social media has no connection to how a meme spreads or persuades'], 0),
   ('Why might a meme’s brevity make it a particularly effective tool for shaping public opinion quickly?', ['A short, easily shareable format can be consumed and passed along rapidly, spreading an idea to a wide audience before it can be carefully scrutinized', 'A meme’s brevity never has any effect on how quickly it spreads or persuades', 'This concept has no connection to media literacy', 'Longer, more detailed messages are always more effective at shaping public opinion quickly'], 0),
   ('Why is media literacy training in analyzing memes considered important for navigating contemporary digital culture?', ['It helps readers recognize when humour or irony is being used to advance a persuasive argument or misleading claim, rather than accepting a message uncritically', 'Analyzing memes has no relevance to understanding contemporary digital culture', 'This concept has no relevance to media literacy', 'Memes are never used to advance any persuasive argument or claim'], 0)]),
F('Discrete Math: Graph Theory — Eulerian and Hamiltonian Paths',
  'Grade 11 Functions strand: an Eulerian path traverses every edge of a graph exactly once, while a Hamiltonian path visits every vertex of a graph exactly once, and determining whether either type of path exists depends on distinct structural properties of the graph.',
  [('What does an Eulerian path traverse exactly once?', ['Every edge of a graph', 'Every vertex of a graph', 'A concept unrelated to functions', 'No part of the graph whatsoever'], 0),
   ('Does a Hamiltonian path visit every vertex of a graph exactly once?', ['Yes', 'No, a Hamiltonian path never visits every vertex of a graph', 'A concept unrelated to graph theory', 'Vertices have no connection to a Hamiltonian path'], 0),
   ('Does a graph need every vertex to have an even degree, with at most two exceptions, to contain an Eulerian path?', ['Yes', 'No, the degree of a graph’s vertices has no connection to whether an Eulerian path exists', 'A concept unrelated to Eulerian paths', 'Vertex degree is never relevant to determining whether an Eulerian path exists'], 0),
   ('Why is determining whether a Hamiltonian path exists in a graph generally considered more computationally difficult than determining whether an Eulerian path exists?', ['There is no simple, general rule for identifying a Hamiltonian path, unlike the well-defined vertex-degree condition that determines an Eulerian path’s existence', 'Determining a Hamiltonian path’s existence is never more difficult than determining an Eulerian path’s existence', 'This concept has no connection to functions', 'Hamiltonian paths and Eulerian paths are always determined using an identical, straightforward rule'], 0),
   ('Why is the distinction between Eulerian and Hamiltonian paths useful for solving real-world routing problems, such as delivery routes?', ['Recognizing whether a problem is really about covering every edge or visiting every location clarifies which type of path-finding approach is appropriate to apply', 'This distinction has no relevance to solving real-world routing or delivery problems', 'This concept has no relevance to functions', 'Every routing problem can always be solved using the exact same approach regardless of its structure'], 0)]),
B('Biology: Circulatory Systems — Open versus Closed Systems Across Animal Phyla',
  'Grade 11 Biology strand: an open circulatory system releases blood-like fluid directly into body cavities to bathe tissues, as in insects, while a closed circulatory system keeps blood confined within vessels throughout its circuit, as in vertebrates.',
  [('What does an open circulatory system release fluid directly into?', ['Body cavities, to bathe tissues directly', 'A completely sealed network of vessels', 'A concept unrelated to biology', 'No fluid is released in an open circulatory system'], 0),
   ('Does a closed circulatory system keep blood confined within vessels throughout its circuit?', ['Yes', 'No, a closed circulatory system never confines blood within vessels', 'A concept unrelated to circulatory systems', 'Vessels have no connection to closed circulatory systems'], 0),
   ('Do insects typically have an open circulatory system?', ['Yes', 'No, insects always have a closed circulatory system', 'A concept unrelated to open circulatory systems', 'Circulatory system type has no connection to insect physiology'], 0),
   ('Why might a closed circulatory system allow for more efficient oxygen and nutrient delivery than an open system in large, active animals?', ['Confining blood within vessels allows pressure and flow to be more precisely controlled, delivering oxygen and nutrients more quickly to tissues with high metabolic demands', 'A closed circulatory system never provides any advantage over an open circulatory system', 'This concept has no connection to biology', 'Open and closed circulatory systems always deliver oxygen and nutrients with identical efficiency'], 0),
   ('Why is comparing open and closed circulatory systems useful for understanding the physiological limits on body size and activity level across animal groups?', ['The efficiency of a circulatory system can constrain how large or active an animal can become, helping explain differences between phyla like arthropods and vertebrates', 'Circulatory system type has no connection to constraints on body size or activity level', 'This concept has no relevance to biology', 'Body size and activity level are never influenced by an animal’s circulatory system'], 0)]),
C('Chemistry: Faraday’s Laws of Electrolysis',
  'Grade 11 Chemistry strand: Faraday’s laws of electrolysis quantitatively relate the amount of substance produced or consumed at an electrode to the quantity of electric charge passed through an electrolytic cell.',
  [('What do Faraday’s laws of electrolysis relate the amount of substance produced at an electrode to?', ['The quantity of electric charge passed through the electrolytic cell', 'Only the colour of the electrolyte solution used', 'A concept unrelated to chemistry', 'The exact temperature of the room where the cell is located'], 0),
   ('Does increasing the electric charge passed through an electrolytic cell generally increase the mass of substance deposited at an electrode?', ['Yes', 'No, electric charge has no connection to the mass of substance deposited', 'A concept unrelated to Faraday’s laws', 'The mass deposited at an electrode is never related to the amount of charge passed through a cell'], 0),
   ('Can Faraday’s laws be used to calculate how much metal will be deposited during an electroplating process?', ['Yes', 'No, Faraday’s laws have no application in electroplating calculations', 'A concept unrelated to electrolysis', 'Electroplating calculations never rely on any quantitative relationship involving charge'], 0),
   ('Why does the amount of substance deposited during electrolysis depend on the number of electrons required to produce one unit of that substance?', ['A given quantity of charge corresponds to a fixed number of electrons, and the number of electrons needed per ion determines how many ions can be reduced or oxidized', 'The number of electrons involved in a reaction never affects how much substance is produced during electrolysis', 'This concept has no connection to chemistry', 'Electrolysis always produces the same amount of substance regardless of the number of electrons involved in the reaction'], 0),
   ('Why are Faraday’s laws of electrolysis important for industries that rely on electroplating or metal refining?', ['They allow precise calculation of the electric charge needed to produce a desired quantity of metal, supporting efficient and predictable industrial processes', 'Faraday’s laws have no practical application for industries involving electroplating or metal refining', 'This concept has no relevance to chemistry', 'Industrial electroplating processes never rely on any quantitative calculation involving charge'], 0)]),
]),

day(106, [
E('Literature: Code-Switching and Dialect as Literary Voice',
  'Grade 11 English strand: authors use code-switching, shifting between languages or dialects, and other markers of dialect to construct a character’s identity, signal cultural belonging, and add authenticity to a narrative voice.',
  [('What does code-switching involve, as used by an author to construct a character’s voice?', ['Shifting between languages or dialects', 'Speaking in a single, unchanging formal register throughout an entire text', 'A concept unrelated to literature', 'Removing all traces of a character’s cultural background from the text'], 0),
   ('Can dialect in a text help signal a character’s cultural background or sense of belonging?', ['Yes', 'No, dialect never signals anything about a character’s cultural background', 'A concept unrelated to code-switching', 'Cultural belonging has no connection to how a character speaks'], 0),
   ('Might an author use code-switching to show a character moving between two different social or cultural contexts?', ['Yes', 'No, code-switching never reflects a character moving between different contexts', 'A concept unrelated to code-switching', 'Social and cultural contexts have no connection to how a character speaks in a narrative'], 0),
   ('Why might a bilingual character in a novel switch briefly into their first language during an emotional moment?', ['A shift in language can convey deeper authenticity or intimacy, suggesting the character is expressing something that feels most natural in that language', 'A character switching languages during an emotional moment never conveys anything meaningful to a reader', 'This concept has no connection to literature', 'Emotional authenticity is never connected to which language a character uses'], 0),
   ('Why is representing dialect and code-switching accurately considered important for authentic literary representation?', ['It can honour the lived linguistic realities of a community and avoid flattening a character’s cultural identity into a single, generic voice', 'Representing dialect accurately has no connection to how authentically a character’s identity is portrayed', 'This concept has no relevance to literature', 'Dialect and code-switching are never connected to a character’s cultural identity'], 0)]),
F('Functions: The Intermediate Value Theorem and Locating Roots',
  'Grade 11 Functions strand: the intermediate value theorem states that if a continuous function takes on two values of opposite sign at the endpoints of an interval, it must have at least one root somewhere within that interval.',
  [('What does the intermediate value theorem guarantee about a continuous function that takes on opposite signs at the endpoints of an interval?', ['That it has at least one root somewhere within that interval', 'That it has no roots anywhere within that interval', 'A concept unrelated to functions', 'That the function must be constant throughout the entire interval'], 0),
   ('Does the intermediate value theorem require the function being examined to be continuous over the interval in question?', ['Yes', 'No, the intermediate value theorem never requires a function to be continuous', 'A concept unrelated to the intermediate value theorem', 'Continuity has no connection to whether the intermediate value theorem applies'], 0),
   ('If a polynomial function is negative at x equals 1 and positive at x equals 2, does the intermediate value theorem guarantee a root exists between those two values?', ['Yes', 'No, opposite signs at two points never guarantee a root exists between them', 'A concept unrelated to locating roots', 'Sign changes have no connection to the existence of a root between two values'], 0),
   ('Why is the intermediate value theorem useful for approximating a root of a polynomial that cannot be easily factored?', ['It confirms that a root exists within a narrowing interval, allowing repeated testing of smaller subintervals to estimate the root’s location with increasing precision', 'The intermediate value theorem never helps in approximating the location of a root', 'This concept has no connection to functions', 'Roots of a polynomial can only ever be found through exact factoring, never through approximation'], 0),
   ('Why must a student confirm that a function is continuous before applying the intermediate value theorem to locate a root?', ['If the function is not continuous, it could jump between the two signs without actually passing through zero at any point in the interval', 'Continuity has no bearing on whether the intermediate value theorem’s guarantee actually holds', 'This concept has no relevance to functions', 'The intermediate value theorem always applies regardless of whether a function is continuous'], 0)]),
B('Biology: Nitrogenous Waste — Ammonotelic, Ureotelic, and Uricotelic Excretion',
  'Grade 11 Biology strand: animals excrete nitrogenous waste from protein breakdown in different chemical forms depending on their environment, with aquatic animals typically excreting ammonia, mammals excreting urea, and birds and reptiles excreting uric acid.',
  [('What do aquatic animals typically excrete as their primary nitrogenous waste product?', ['Ammonia', 'Uric acid exclusively', 'A concept unrelated to biology', 'No nitrogenous waste at all'], 0),
   ('Do mammals typically excrete urea as their primary nitrogenous waste product?', ['Yes', 'No, mammals never excrete urea as a nitrogenous waste product', 'A concept unrelated to nitrogenous waste', 'Urea has no connection to how mammals excrete nitrogenous waste'], 0),
   ('Do birds and reptiles typically excrete uric acid rather than ammonia or urea?', ['Yes', 'No, birds and reptiles always excrete ammonia directly', 'A concept unrelated to uricotelic excretion', 'Uric acid has no connection to how birds and reptiles excrete waste'], 0),
   ('Why might birds and reptiles excrete uric acid, a low-solubility, paste-like waste, rather than the highly toxic and water-demanding ammonia?', ['Uric acid requires very little water to excrete safely, which is especially valuable for animals that lay shelled eggs or live in environments where conserving water is important', 'Excreting uric acid never provides any advantage related to water conservation', 'This concept has no connection to biology', 'Birds and reptiles always excrete exactly the same nitrogenous waste product as aquatic animals'], 0),
   ('Why can ammonia be safely excreted directly by aquatic animals despite being highly toxic?', ['Ammonia can be rapidly diluted and washed away into the surrounding water before it accumulates to toxic levels within the animal’s body', 'Ammonia is never toxic to any animal that excretes it', 'This concept has no relevance to biology', 'Aquatic animals never need to consider the toxicity of the nitrogenous waste they produce'], 0)]),
C('Chemistry: Titration Types — Acid-Base, Redox, and Complexometric Titrations',
  'Grade 11 Chemistry strand: titration is a general quantitative technique for determining the concentration of a solution, applied not only to acid-base reactions but also to redox reactions and complexometric reactions involving metal ions.',
  [('What is titration generally used to determine?', ['The concentration of a solution', 'The exact colour of a solid precipitate', 'A concept unrelated to chemistry', 'The temperature at which a substance melts'], 0),
   ('Can titration be applied to redox reactions in addition to acid-base reactions?', ['Yes', 'No, titration can only ever be applied to acid-base reactions', 'A concept unrelated to titration types', 'Redox reactions have no connection to titration as a technique'], 0),
   ('Does a complexometric titration typically involve a reaction between a metal ion and a complexing agent?', ['Yes', 'No, complexometric titrations never involve metal ions', 'A concept unrelated to complexometric titration', 'Complexing agents have no connection to complexometric titration'], 0),
   ('Why might a chemist choose a redox titration, rather than an acid-base titration, to determine the concentration of an oxidizing agent in a solution?', ['A redox titration relies on an oxidation-reduction reaction with a known reagent, allowing the concentration of the oxidizing agent to be calculated from the volume needed to reach the endpoint', 'A redox titration is never useful for determining the concentration of an oxidizing agent', 'This concept has no connection to chemistry', 'Acid-base titrations are always equally effective for measuring the concentration of an oxidizing agent'], 0),
   ('Why is understanding multiple types of titration useful for analytical chemists working with a wide range of substances?', ['Different substances react through different types of chemical reactions, so having multiple titration methods allows concentration to be measured accurately across many contexts', 'Every titration type produces identical results regardless of the substance being analyzed', 'This concept has no relevance to chemistry', 'Analytical chemists never need more than one method for determining a solution’s concentration'], 0)]),
]),

day(107, [
E('Literature: Detective Fiction and the Structure of the Whodunit',
  'Grade 11 English strand: detective fiction, or the whodunit, follows a structured narrative pattern in which clues are deliberately planted for readers to interpret alongside the detective, building toward a climactic revelation of the culprit.',
  [('What does detective fiction deliberately plant throughout its narrative?', ['Clues for readers to interpret alongside the detective', 'Only irrelevant details with no connection to the plot', 'A concept unrelated to literature', 'A complete solution revealed at the very beginning of the story'], 0),
   ('Does a whodunit typically build toward a climactic revelation of the culprit?', ['Yes', 'No, a whodunit never reveals the identity of the culprit', 'A concept unrelated to detective fiction', 'A climactic revelation has no connection to the structure of detective fiction'], 0),
   ('Can readers of detective fiction often try to solve the mystery themselves by interpreting the clues alongside the detective?', ['Yes', 'No, readers of detective fiction are never invited to interpret clues themselves', 'A concept unrelated to the whodunit structure', 'Interpreting clues has no connection to how readers typically engage with detective fiction'], 0),
   ('Why might an author of detective fiction deliberately include a red herring, a misleading clue, within the narrative?', ['A red herring can create suspense and challenge readers’ deductions, making the eventual, correct solution feel more satisfying and less predictable', 'A red herring never has any effect on how a mystery unfolds for the reader', 'This concept has no connection to literature', 'Detective fiction never includes any misleading or false clues'], 0),
   ('Why does the structured, clue-based format of detective fiction appeal to readers across many different eras and cultures?', ['It engages readers actively in a puzzle-solving process, offering the satisfaction of logical reasoning combined with narrative suspense', 'The structured format of detective fiction has no appeal to readers in any era or culture', 'This concept has no relevance to literature', 'Puzzle-solving and logical reasoning are never connected to why readers enjoy a narrative'], 0)]),
F('Functions: The Rational Root Theorem',
  'Grade 11 Functions strand: the rational root theorem identifies a finite list of possible rational roots of a polynomial equation with integer coefficients, based on the factors of its constant term and leading coefficient.',
  [('What does the rational root theorem identify?', ['A finite list of possible rational roots of a polynomial equation', 'The exact value of every root of any polynomial equation', 'A concept unrelated to functions', 'Whether a polynomial has any roots at all, without specifying values'], 0),
   ('Does the rational root theorem rely on the factors of a polynomial’s constant term and leading coefficient?', ['Yes', 'No, the rational root theorem has no connection to a polynomial’s constant term or leading coefficient', 'A concept unrelated to the rational root theorem', 'Factors of a polynomial’s coefficients are never relevant to identifying possible roots'], 0),
   ('For the polynomial 2x cubed minus 3x squared minus 8x plus 12, is 2 one of the possible rational roots to test, according to the theorem?', ['Yes', 'No, 2 could never be a possible rational root of this polynomial', 'A concept unrelated to the rational root theorem', 'Possible rational roots are never determined by any factor of a polynomial’s coefficients'], 0),
   ('Why does the rational root theorem only produce a list of possible roots rather than guaranteeing which ones are actual roots?', ['The theorem narrows down candidates based on the structure of the coefficients, but each candidate must still be tested, often using the remainder theorem, to confirm whether it is truly a root', 'Every value produced by the rational root theorem is always guaranteed to be an actual root of the polynomial', 'This concept has no connection to functions', 'The rational root theorem has no relationship to testing whether a value is a root'], 0),
   ('Why is the rational root theorem a useful complement to the remainder theorem when solving higher-degree polynomial equations?', ['It narrows down which values are worth testing with the remainder theorem, making the process of finding an actual root far more efficient than guessing randomly', 'The rational root theorem has no useful relationship with the remainder theorem', 'This concept has no relevance to functions', 'Testing random values is always more efficient than using the rational root theorem to narrow down candidates'], 0)]),
B('Biology: Plant Tissue Systems — Dermal, Ground, and Vascular Tissue',
  'Grade 11 Biology strand: plants are organized into three main tissue systems, dermal tissue that forms a protective outer covering, ground tissue that carries out photosynthesis and storage, and vascular tissue that transports water and nutrients.',
  [('What does dermal tissue in a plant primarily form?', ['A protective outer covering', 'The plant’s main photosynthetic tissue', 'A concept unrelated to biology', 'A network exclusively for transporting nutrients'], 0),
   ('Does vascular tissue transport water and nutrients throughout a plant?', ['Yes', 'No, vascular tissue has no connection to transporting water or nutrients', 'A concept unrelated to plant tissue systems', 'Transport is never a function of any plant tissue system'], 0),
   ('Does ground tissue carry out functions such as photosynthesis and storage in a plant?', ['Yes', 'No, ground tissue never carries out photosynthesis or storage', 'A concept unrelated to ground tissue', 'Photosynthesis and storage have no connection to any plant tissue system'], 0),
   ('Why might a plant’s vascular tissue be organized into two distinct types, xylem and phloem, rather than a single uniform tissue?', ['Xylem and phloem transport different substances in different directions, so distinct specialized tissues allow water and nutrients to be moved efficiently to where they are needed', 'A plant’s vascular tissue is always a single, undifferentiated type with no distinct components', 'This concept has no connection to biology', 'Xylem and phloem always transport identical substances in the exact same direction'], 0),
   ('Why is understanding the three plant tissue systems useful for explaining how a plant’s different organs, such as leaves, stems, and roots, function together?', ['Each organ is built from the same three tissue systems arranged differently, so recognizing this shared organization helps explain how structure supports each organ’s specific function', 'The three plant tissue systems have no connection to how a plant’s different organs function', 'This concept has no relevance to biology', 'Leaves, stems, and roots are never built from any shared type of plant tissue'], 0)]),
C('Chemistry: The Kinetic Molecular Theory of Gases',
  'Grade 11 Chemistry strand: the kinetic molecular theory explains gas behaviour by modelling gas particles as constantly moving in random, straight-line motion, with average kinetic energy directly proportional to the gas’s absolute temperature.',
  [('How does the kinetic molecular theory model the motion of gas particles?', ['As constantly moving in random, straight-line motion', 'As remaining completely stationary at all times', 'A concept unrelated to chemistry', 'As moving only in a single, fixed circular pattern'], 0),
   ('According to the kinetic molecular theory, is a gas’s average kinetic energy directly proportional to its absolute temperature?', ['Yes', 'No, average kinetic energy has no connection to a gas’s absolute temperature', 'A concept unrelated to the kinetic molecular theory', 'A gas’s temperature is never related to the motion of its particles'], 0),
   ('Does the kinetic molecular theory assume that collisions between gas particles are perfectly elastic, meaning no overall kinetic energy is lost?', ['Yes', 'No, the kinetic molecular theory assumes gas particles lose all their kinetic energy upon collision', 'A concept unrelated to the kinetic molecular theory', 'Collisions between gas particles are never addressed by this theory'], 0),
   ('Why does raising a gas’s temperature cause its particles to move faster, on average, according to the kinetic molecular theory?', ['Temperature is a direct measure of the average kinetic energy of the particles, so increasing temperature increases their average speed', 'Raising a gas’s temperature never has any effect on how fast its particles move', 'This concept has no connection to chemistry', 'Particle speed is never related to a gas’s temperature according to this theory'], 0),
   ('Why is the kinetic molecular theory considered the underlying explanation for the empirical gas laws, such as Boyle’s and Charles’s laws?', ['It provides a particle-level model of motion, collision, and energy that explains why gases behave in the predictable, measurable ways described by those laws', 'The kinetic molecular theory has no connection to explaining why the empirical gas laws hold true', 'This concept has no relevance to chemistry', 'The empirical gas laws were developed with no reference to any theory about particle motion'], 0)]),
]),

day(108, [
E('Oral Communication: Preparing for and Conducting a Formal Interview',
  'Grade 11 English strand: preparing for a formal interview involves researching the interviewer or organization, anticipating likely questions, and practising clear, concise responses that highlight relevant experience and skills.',
  [('What does preparing for a formal interview typically involve researching?', ['The interviewer or organization', 'Only unrelated topics with no connection to the interview', 'A concept unrelated to oral communication', 'The exact number of chairs in the interview room'], 0),
   ('Does effective interview preparation involve anticipating likely questions in advance?', ['Yes', 'No, interview preparation never involves anticipating likely questions', 'A concept unrelated to formal interviews', 'Anticipating questions has no connection to how well an interview goes'], 0),
   ('Can practising clear, concise responses help a candidate communicate their relevant skills more effectively during an interview?', ['Yes', 'No, practising responses never improves how effectively a candidate communicates', 'A concept unrelated to interview preparation', 'Clarity and concision have no connection to communicating relevant skills'], 0),
   ('Why might a candidate prepare specific examples from past experience before a formal interview, rather than planning to answer questions purely in the moment?', ['Having concrete examples ready allows a candidate to respond confidently and specifically, rather than relying on vague or unprepared answers under pressure', 'Preparing specific examples in advance never improves the quality of an interview response', 'This concept has no connection to oral communication', 'Answering questions purely in the moment is always more effective than any advance preparation'], 0),
   ('Why is active listening considered an important skill during a formal interview, not just when answering questions?', ['Listening carefully to the interviewer’s questions and follow-ups allows a candidate to respond precisely to what is actually being asked, rather than a rehearsed but unrelated answer', 'Active listening has no relevance to how a candidate performs during a formal interview', 'This concept has no relevance to oral communication', 'A candidate’s listening skills are never evaluated as part of a formal interview'], 0)]),
F('Statistics: Hypothesis Testing — An Introduction',
  'Grade 11 Functions strand: hypothesis testing evaluates a claim about a population by comparing a null hypothesis of no effect or no difference against observed sample data, determining whether the results are unlikely enough to reject that null hypothesis.',
  [('What does hypothesis testing compare a null hypothesis against?', ['Observed sample data', 'Only a second, unrelated null hypothesis', 'A concept unrelated to statistics', 'A prediction made without any reference to data at all'], 0),
   ('Does a null hypothesis typically represent an assumption of no effect or no difference?', ['Yes', 'No, a null hypothesis always assumes a large, significant effect exists', 'A concept unrelated to hypothesis testing', 'Effect size has no connection to how a null hypothesis is defined'], 0),
   ('If observed sample data is very unlikely to have occurred under the null hypothesis, would a researcher typically consider rejecting that null hypothesis?', ['Yes', 'No, unlikely sample data never leads a researcher to reject a null hypothesis', 'A concept unrelated to hypothesis testing', 'A null hypothesis can never be rejected regardless of how the sample data appears'], 0),
   ('Why might a researcher testing a new medication compare patient outcomes against a null hypothesis of no difference from a placebo?', ['Starting from an assumption of no effect provides a clear baseline, so evidence of a significant difference in the data can be used to challenge that assumption', 'Comparing outcomes to a null hypothesis of no difference never provides any useful information to a researcher', 'This concept has no connection to functions', 'A null hypothesis is never relevant when testing whether a new medication is effective'], 0),
   ('Why is hypothesis testing considered a foundational tool in fields like medicine, psychology, and social science research?', ['It provides a structured, evidence-based method for determining whether an observed pattern in data is likely meaningful or simply due to chance', 'Hypothesis testing has no relevance to research conducted in medicine, psychology, or social science', 'This concept has no relevance to functions', 'Observed patterns in research data are never evaluated for whether they could be due to chance'], 0)]),
B('Biology: Animal Locomotion — Adaptations for Movement on Land, Water, and Air',
  'Grade 11 Biology strand: animals have evolved structural adaptations suited to their mode of locomotion, including limbs for movement on land, streamlined bodies and fins for swimming, and wings for powered or gliding flight.',
  [('What structural adaptations have animals evolved for movement on land?', ['Limbs suited to walking, running, or crawling', 'Only wings for powered flight', 'A concept unrelated to biology', 'No structural adaptations related to movement whatsoever'], 0),
   ('Do animals adapted for swimming often have streamlined bodies and fins?', ['Yes', 'No, swimming animals never have streamlined bodies or fins', 'A concept unrelated to animal locomotion', 'Streamlined bodies have no connection to efficient movement through water'], 0),
   ('Do wings allow some animals to achieve either powered or gliding flight?', ['Yes', 'No, wings never allow any animal to fly or glide', 'A concept unrelated to animal locomotion', 'Flight has no connection to the structure of an animal’s wings'], 0),
   ('Why might a streamlined body shape reduce the energy an aquatic animal needs to expend while swimming?', ['A streamlined shape reduces drag from the surrounding water, allowing the animal to move more efficiently with less resistance to overcome', 'A streamlined body shape never has any effect on how much energy is needed for swimming', 'This concept has no connection to biology', 'Drag from water never affects how much energy an aquatic animal expends while moving'], 0),
   ('Why is comparing locomotor adaptations across land, water, and air useful for understanding how physical environment shapes an animal’s body plan?', ['It reveals how the specific physical demands of moving through a particular medium, such as air resistance or water drag, have driven the evolution of very different structural solutions', 'Comparing locomotor adaptations across environments provides no insight into how an animal’s body plan evolved', 'This concept has no relevance to biology', 'An animal’s physical environment never influences the evolution of its body plan'], 0)]),
C('Chemistry: The Chemistry of Baking — Acid-Base Reactions in Leavening Agents',
  'Grade 11 Chemistry strand: chemical leavening agents, such as baking soda and baking powder, rely on acid-base reactions that release carbon dioxide gas, causing dough or batter to rise during baking.',
  [('What gas do chemical leavening agents like baking soda typically release to make dough or batter rise?', ['Carbon dioxide gas', 'Pure oxygen gas', 'A concept unrelated to chemistry', 'Hydrogen gas exclusively'], 0),
   ('Does baking soda require an acidic ingredient, such as buttermilk or vinegar, to react and release carbon dioxide?', ['Yes', 'No, baking soda never requires any acidic ingredient to react', 'A concept unrelated to chemical leavening', 'Acidic ingredients have no connection to how baking soda functions in a recipe'], 0),
   ('Does baking powder typically already contain both an acid and a base, unlike baking soda alone?', ['Yes', 'No, baking powder never contains both an acid and a base', 'A concept unrelated to baking powder', 'The presence of an acid and base has no connection to how baking powder works'], 0),
   ('Why might a recipe using baking soda without enough acidic ingredients fail to rise properly?', ['Without sufficient acid to react with the baking soda, the acid-base reaction needed to release carbon dioxide gas does not occur completely, limiting the leavening effect', 'A recipe using baking soda always rises properly regardless of the presence of any acidic ingredients', 'This concept has no connection to chemistry', 'Acid-base reactions are never involved in how baking soda causes dough to rise'], 0),
   ('Why is understanding the acid-base chemistry behind leavening agents useful for adapting a recipe that changes its acidic ingredients?', ['Recognizing the underlying acid-base reaction helps a baker adjust the amount of leavening agent needed to maintain a properly balanced reaction and consistent rise', 'This chemistry has no connection to adapting a recipe’s ingredients', 'This concept has no relevance to chemistry', 'A recipe’s ability to rise is never affected by changes to its acidic ingredients'], 0)]),
]),

day(109, [
E('Writing: The Book Review as Critical Genre',
  'Grade 11 English strand: a book review combines summary, analysis, and evaluative judgment, offering a concise assessment of a text’s strengths, weaknesses, and significance for a prospective reader.',
  [('What three elements does a book review typically combine?', ['Summary, analysis, and evaluative judgment', 'Only a full, unabridged copy of the original text', 'A concept unrelated to writing', 'A complete biography of the author with no reference to the text itself'], 0),
   ('Does a book review typically offer some evaluative judgment about a text’s strengths and weaknesses?', ['Yes', 'No, a book review never includes any evaluative judgment', 'A concept unrelated to the book review genre', 'Strengths and weaknesses are never addressed in a book review'], 0),
   ('Is a book review generally intended to help a prospective reader decide whether to read a text?', ['Yes', 'No, a book review is never intended to help a prospective reader make a decision', 'A concept unrelated to book reviews', 'Prospective readers are never a consideration when writing a book review'], 0),
   ('Why might a book reviewer support a claim, such as that a novel’s pacing feels uneven, with a specific example from the text?', ['A specific example gives the evaluative claim credibility, showing readers precisely what led the reviewer to that judgment rather than leaving it as an unsupported opinion', 'Supporting a claim with a specific example never strengthens a book review’s credibility', 'This concept has no connection to writing', 'A book reviewer’s claims are always more convincing without any supporting evidence from the text'], 0),
   ('Why is the book review considered a valuable form of public literary discourse?', ['It offers accessible, critical engagement with a text that can shape a wider readership’s understanding of and interest in that work', 'Book reviews have no influence on how a text is understood or received by a wider readership', 'This concept has no relevance to writing', 'Public literary discourse is never shaped by any critical engagement with a text'], 0)]),
F('Financial Mathematics: Effective Annual Rate and Comparing Loan Options',
  'Grade 11 Functions strand: the effective annual rate converts a loan’s nominal interest rate and compounding frequency into a single standardized rate, allowing fair comparison between loan or investment options that compound interest differently.',
  [('What does the effective annual rate convert a nominal interest rate and compounding frequency into?', ['A single, standardized rate for fair comparison', 'A rate that always equals zero regardless of compounding', 'A concept unrelated to functions', 'An amount measured only in a foreign currency'], 0),
   ('Does the effective annual rate allow fair comparison between loans that compound interest at different frequencies?', ['Yes', 'No, the effective annual rate has no connection to comparing loans with different compounding frequencies', 'A concept unrelated to effective annual rate', 'Compounding frequency is never relevant to comparing loan or investment options'], 0),
   ('Is the effective annual rate of a loan generally higher than its stated nominal rate when interest compounds more than once per year?', ['Yes', 'No, the effective annual rate is always lower than the nominal rate regardless of compounding frequency', 'A concept unrelated to effective annual rate', 'Compounding frequency never affects the relationship between nominal and effective rates'], 0),
   ('Why might two loans with the same nominal interest rate actually cost a borrower different amounts over a year?', ['If one loan compounds interest more frequently than the other, its effective annual rate will be higher, resulting in more interest accumulating over the same period', 'Two loans with the same nominal interest rate always cost a borrower exactly the same amount, regardless of compounding frequency', 'This concept has no connection to functions', 'Compounding frequency never has any effect on the total interest a borrower pays over a year'], 0),
   ('Why is calculating the effective annual rate important for a consumer comparing loan offers from different lenders?', ['It reveals the true annual cost of borrowing for each option, allowing an accurate comparison beyond simply looking at each loan’s stated nominal rate', 'The effective annual rate has no relevance to comparing loan offers from different lenders', 'This concept has no relevance to functions', 'A loan’s stated nominal rate always provides a complete and accurate picture of its true cost'], 0)]),
B('Biology: The Cell Cycle — Checkpoints and Regulation of Mitosis',
  'Grade 11 Biology strand: the cell cycle is regulated by checkpoints at key transition points that monitor conditions such as DNA integrity and cell size, halting the cycle when problems are detected to prevent the division of damaged cells.',
  [('What do cell cycle checkpoints monitor before allowing the cycle to proceed?', ['Conditions such as DNA integrity and cell size', 'Only the colour of the surrounding tissue', 'A concept unrelated to biology', 'The exact geographic location of the organism'], 0),
   ('Can a cell cycle checkpoint halt the cycle if DNA damage is detected?', ['Yes', 'No, checkpoints never halt the cell cycle for any reason', 'A concept unrelated to cell cycle regulation', 'DNA damage detection has no connection to cell cycle checkpoints'], 0),
   ('Does failure of cell cycle checkpoint regulation increase the risk that damaged cells will continue to divide uncontrollably?', ['Yes', 'No, checkpoint failure never has any effect on whether damaged cells continue dividing', 'A concept unrelated to checkpoint regulation', 'Uncontrolled cell division has no connection to checkpoint failure'], 0),
   ('Why might a cell with significantly damaged DNA be halted at a checkpoint rather than allowed to continue dividing?', ['Allowing a cell with damaged DNA to divide could pass on harmful mutations to daughter cells, so halting the cycle allows time for repair or triggers the damaged cell’s controlled destruction', 'A cell with damaged DNA is always allowed to continue dividing regardless of the damage present', 'This concept has no connection to biology', 'DNA damage never has any influence on whether a cell proceeds through the cell cycle'], 0),
   ('Why is understanding cell cycle checkpoint regulation important for explaining how cancer can develop?', ['Many cancers arise when mutations disable checkpoint regulation, allowing damaged cells to divide uncontrollably rather than being halted or destroyed', 'Cell cycle checkpoint regulation has no connection to how cancer develops', 'This concept has no relevance to biology', 'Cancer development is never related to any failure of cell cycle regulation'], 0)]),
C('Chemistry: Isotopic Abundance and Average Atomic Mass Calculations',
  'Grade 11 Chemistry strand: an element’s average atomic mass, listed on the periodic table, is calculated as the weighted average of the masses of its naturally occurring isotopes, based on each isotope’s relative abundance.',
  [('What is an element’s average atomic mass calculated as?', ['A weighted average of the masses of its naturally occurring isotopes', 'The mass of only its single most common isotope', 'A concept unrelated to chemistry', 'The sum of the masses of every element on the periodic table'], 0),
   ('Does an isotope’s relative abundance affect how much it contributes to an element’s average atomic mass?', ['Yes', 'No, relative abundance has no connection to an element’s average atomic mass', 'A concept unrelated to isotopic abundance', 'Average atomic mass is never influenced by the presence of different isotopes'], 0),
   ('If an element has two isotopes and one is far more abundant than the other, will the average atomic mass be closer to the mass of the more abundant isotope?', ['Yes', 'No, the average atomic mass is never closer to the mass of the more abundant isotope', 'A concept unrelated to average atomic mass calculations', 'Abundance never affects how close the average atomic mass is to any particular isotope’s mass'], 0),
   ('Why is chlorine’s average atomic mass, approximately 35.45, not a whole number even though individual isotopes have whole-number mass numbers?', ['The average atomic mass reflects a weighted blend of chlorine’s naturally occurring isotopes, so it falls between their individual whole-number mass values rather than matching either one exactly', 'Average atomic mass is always a whole number for every element on the periodic table', 'This concept has no connection to chemistry', 'Isotopes never have any effect on why an element’s average atomic mass might not be a whole number'], 0),
   ('Why is understanding the weighted-average nature of atomic mass important when performing mole calculations in stoichiometry?', ['Using the periodic table’s average atomic mass accounts for the natural mixture of isotopes in a real sample, giving accurate results for calculations involving moles and molar mass', 'The weighted-average nature of atomic mass has no relevance to mole calculations in stoichiometry', 'This concept has no relevance to chemistry', 'Stoichiometric calculations never rely on any value related to atomic mass'], 0)]),
]),

day(110, [
E('Review: Gothic Fiction, Genre, and Media Literacy (Days 101-109)',
  'Grade 11 English strand review: students revisit Gothic fiction, the villanelle, the character sketch, the trickster figure, meme analysis and digital rhetoric, code-switching as literary voice, detective fiction, formal interviews, and the book review.',
  [('What does Gothic fiction typically blend?', ['Horror, romance, and the supernatural', 'Only realistic depictions of everyday life', 'A concept unrelated to literature', 'A strictly comedic tone with no serious themes'], 0),
   ('What does a character sketch primarily aim to convey?', ['A character’s personality, appearance, and mannerisms through concrete detail', 'A complete plot summary of an entire novel', 'A concept unrelated to writing', 'A formal citation of a source used in an essay'], 0),
   ('What do memes typically combine to spread ideas rapidly online?', ['Image and concise text', 'Only lengthy, unrelated paragraphs of text', 'A concept unrelated to media literacy', 'Audio recordings with no accompanying visuals'], 0),
   ('What does detective fiction deliberately plant throughout its narrative?', ['Clues for readers to interpret alongside the detective', 'Only irrelevant details with no connection to the plot', 'A concept unrelated to literature', 'A complete solution revealed at the very beginning of the story'], 0),
   ('What three elements does a book review typically combine?', ['Summary, analysis, and evaluative judgment', 'Only a full, unabridged copy of the original text', 'A concept unrelated to writing', 'A complete biography of the author with no reference to the text itself'], 0)]),
F('Review: Number Theory, Logic, and Statistics (Days 101-109)',
  'Grade 11 Functions strand review: students revisit the Euclidean algorithm, propositional logic, confidence intervals, vector equations of lines, Eulerian and Hamiltonian paths, the intermediate value theorem, the rational root theorem, hypothesis testing, and effective annual rate.',
  [('What does the Euclidean algorithm find?', ['The greatest common divisor of two integers', 'The least common multiple of two integers only', 'A concept unrelated to number theory', 'The exact prime factorization of a number'], 0),
   ('What does a confidence interval provide?', ['A range of values likely to contain the true population parameter', 'A single, exact value that always equals the population parameter', 'A concept unrelated to statistics', 'A list of every value ever recorded in the sample'], 0),
   ('What does an Eulerian path traverse exactly once?', ['Every edge of a graph', 'Every vertex of a graph', 'A concept unrelated to functions', 'No part of the graph whatsoever'], 0),
   ('What does the rational root theorem identify?', ['A finite list of possible rational roots of a polynomial equation', 'The exact value of every root of any polynomial equation', 'A concept unrelated to functions', 'Whether a polynomial has any roots at all, without specifying values'], 0),
   ('What does the effective annual rate convert a nominal interest rate and compounding frequency into?', ['A single, standardized rate for fair comparison', 'A rate that always equals zero regardless of compounding', 'A concept unrelated to functions', 'An amount measured only in a foreign currency'], 0)]),
B('Review: Comparative Physiology and Cell Biology (Days 101-109)',
  'Grade 11 Biology strand review: students revisit comparative digestion, osmoconformers and osmoregulators, comparative vision, insect metamorphosis, circulatory systems, nitrogenous waste, plant tissue systems, animal locomotion, and cell cycle checkpoints.',
  [('What do ruminant animals use to break down cellulose in plant material?', ['A multi-chambered stomach and microbial fermentation', 'Only a single-chambered stomach with no microbes involved', 'A concept unrelated to biology', 'A completely liquid diet with no solid plant material'], 0),
   ('What does the vertebrate camera eye use to form a single focused image?', ['A lens and a retina', 'Thousands of independent light-sensing units', 'A concept unrelated to biology', 'No light-sensitive structures whatsoever'], 0),
   ('What does an open circulatory system release fluid directly into?', ['Body cavities, to bathe tissues directly', 'A completely sealed network of vessels', 'A concept unrelated to biology', 'No fluid is released in an open circulatory system'], 0),
   ('What does dermal tissue in a plant primarily form?', ['A protective outer covering', 'The plant’s main photosynthetic tissue', 'A concept unrelated to biology', 'A network exclusively for transporting nutrients'], 0),
   ('What do cell cycle checkpoints monitor before allowing the cycle to proceed?', ['Conditions such as DNA integrity and cell size', 'Only the colour of the surrounding tissue', 'A concept unrelated to biology', 'The exact geographic location of the organism'], 0)]),
C('Review: Gas Laws, Kinetics, and Quantitative Chemistry (Days 101-109)',
  'Grade 11 Chemistry strand review: students revisit Avogadro’s law, the common ion effect, the Arrhenius equation, polymerization, Faraday’s laws of electrolysis, titration types, the kinetic molecular theory, the chemistry of baking, and isotopic abundance.',
  [('What does Avogadro’s law state about equal volumes of gases at the same temperature and pressure?', ['They contain equal numbers of particles', 'They always contain completely different numbers of particles', 'A concept unrelated to chemistry', 'They must be composed of the exact same element'], 0),
   ('What does the Arrhenius equation relate a reaction’s rate constant to?', ['Its activation energy and temperature', 'Only the colour of the reactants involved', 'A concept unrelated to chemistry', 'The exact volume of the reaction container'], 0),
   ('What do Faraday’s laws of electrolysis relate the amount of substance produced at an electrode to?', ['The quantity of electric charge passed through the electrolytic cell', 'Only the colour of the electrolyte solution used', 'A concept unrelated to chemistry', 'The exact temperature of the room where the cell is located'], 0),
   ('How does the kinetic molecular theory model the motion of gas particles?', ['As constantly moving in random, straight-line motion', 'As remaining completely stationary at all times', 'A concept unrelated to chemistry', 'As moving only in a single, fixed circular pattern'], 0),
   ('What is an element’s average atomic mass calculated as?', ['A weighted average of the masses of its naturally occurring isotopes', 'The mass of only its single most common isotope', 'A concept unrelated to chemistry', 'The sum of the masses of every element on the periodic table'], 0)]),
]),
]

if __name__ == '__main__':
    _rebalance_answer_positions(g11_101_110)
    append_to(11, g11_101_110)
